### ISSUE TITLE
Baritone reach is too high.

### ISSUE THREAD

**Issue by Lio4ik** [cabaletta/baritone#1001]
## Some information
Operating system: Windows 10.
Java version: 8 update 221
Minecraft version: 1.12.2
Baritone version: Impact: 4.7.3
Forge mods (if used): Nope.

## Exception, error or logs
https://www55.zippyshare.com/v/R3JmOqSh/file.html
https://streamable.com/zqm0a
## How to reproduce
Just set baritone to dig a huge hole. (I guess the reach is too high)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Baritone does not extend reach.
