### ISSUE TITLE
Cave-Mining

### ISSUE THREAD

**Issue by H4zZzi** [cabaletta/baritone#1004]
It would be nice to add a Cavemining mode for the bot.
This mode makes that the bot explores caves and kills mobs with a sword (or the most efficent weapon in his invetory). Plus that he breaks blocks but stays in his cave like he runs arround kills mobs and farms iron.
Thanks for your attention.

**Comment by usereewrjrjeejr** [comment]
Garbage

**Comment by H4zZzi** [comment]
It would be really useful on a server like hypixel skyblock or stuff like that

**Comment by strongboy54** [comment]
I'd love a feature like this. It would really add to the legitmining aspect. 
Honestly find the "legitmining" feature to be quite bad.

It should have 2 options. 1 for cave/ravine mining, and 1 for branch mining.

Cave/ravine mining
It would mine to a mineshaft, cave, ravine and search for ores, if nothing found, move on to the next closest cave, mineshaft, ravine.

Branch Mining
Dig down to X specified height, and mine in a straight line, stop at every 2 blocks to mine 5 blocks in each direction. If ores found, mine them, then continue.
