### ISSUE TITLE
#mine to be able to select multiple blocks to mine

### ISSUE THREAD

**Issue by eggshellsv** [cabaletta/baritone#1012]
## Describe your suggestion
The ability to select multiple blocks to mine with #mine (for example, iron ore + coal ore at once)
## Settings
Selection of blocks

## Context
Ease of use / QoL / speedy haha
## Final checklist
- [x] I have not used any OwO's or UwU's in this issue QwQ

**Comment by RealIndrit** [comment]
Insert Memetag here please... Im prettyyyyy fkn sure you can just list alot of blocks when doing #mine ...

**Comment by RealIndrit** [comment]
do "#mine diamond_ore iron_ore coal_ore gold_ore" it will mine all listed blocks...

**Comment by Harumasai** [comment]
you can already do that (#mine mob_spawner mossy_cobblestone)
