### ISSUE TITLE
Bot can't find path even when it should be able to

### ISSUE THREAD

**Issue by j13li78** [cabaletta/baritone#1014]
## Some information
Operating system: Windows 10 Version 1903
Java version: 1.8.0_191
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): None

## Exception, error or logs
https://gyazo.com/1d2117e66f93c4e6dd84e54b08e0123b
[latest.log](https://github.com/cabaletta/baritone/files/3665712/latest.log)

## How to reproduce
I stand infront of two cheats and tell the bot to mine chests but it responses with it can't find path towards the cheats and blacklists them.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Orinion** [comment]
whats your "blocksToAvoidBreaking" list set to?

**Comment by j13li78** [comment]
![Runtime Screenshot 2019 10 06 - 21 44 34 76](https://user-images.githubusercontent.com/40141174/66274820-9550be00-e882-11e9-935b-666376e85a6f.png)
none of the blocks that where there

**Comment by Orinion** [comment]
"chest" is in there

**Comment by j13li78** [comment]
> 
> 
> "chest" is in there

I disabled it now but i doubt thats the reason because it is mining chest fine even with this enabled. It just happens randomly that it says no path found.

**Comment by S-B99** [comment]
It is the reason. Avoid breaking is when pathing, not telling it to explicitly break them.
