### ISSUE TITLE
Bot doesn't search for blocks when there are none in his view (with exploreForBlocks enabled on .b mine)

### ISSUE THREAD

**Issue by j13li78** [cabaletta/baritone#1017]
## Some information
Operating system: Windows 10 Version 1903
Java version: 1.8.0_191
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): None

## Exception, error or logs
https://imgur.com/ETcgmPk
[latest.log](https://github.com/cabaletta/baritone/files/3694813/latest.log)

## How to reproduce
It happens when there are no chests in the range of the bot with .b mine, it just stops searching even when exploreForBlocks is set to true.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Xephorix** [comment]
is legitMine on? If so turn it off. That should fix it.

**Comment by j13li78** [comment]
> 
> 
> is legitMine on? If so turn it off. That should fix it.

no it's not

**Comment by Xephorix** [comment]
I just re-read the problem and realized that wouldn't work. Sorry I'm being dumb today.

**Comment by j13li78** [comment]
> 
> 
> I just re-read the problem and realized that wouldn't work. Sorry I'm being dumb today.

It looks like there isn't even a mode to explore for blocks implemented for mining.
![jzt](https://user-images.githubusercontent.com/40141174/66326291-ff23a300-e928-11e9-853b-6e47ef417461.PNG)

**Comment by Xephorix** [comment]
> It looks like there isn't even a mode to explore for blocks implemented for mining.
Oh yeah, that's a bit odd. I always thought that would have been implemented.

**Comment by j13li78** [comment]
Still not fixed

**Comment by S-B99** [comment]
exploreForBlocks is a thing, you probably are using something really old. what branch?

**Comment by j13li78** [comment]
but it does nothing

**Comment by S-B99** [comment]
again, what branch? it doesn't do 'nothing'
