### ISSUE TITLE
Can't open doors and trapdoors

### ISSUE THREAD

**Issue by xhBIROhx** [cabaletta/baritone#1028]
The title says it. So plz fix it.
I tested it like:
I did #save itt
And then baricaded the block with doors. I went out and then i did #goto itt. The bot youst walked to the door and sprint towards it, until i did #stop.

**Comment by itsLucaPereira** [comment]
If your structure looks like [this](https://gyazo.com/434885f2cf2ba599d9a437c206e77c67) it won't work. It needs to have a block under the door. 
As for trapdoors it seems it will break with the tests I've done

**Comment by CDAGaming** [comment]
A recent PR I was testing did need to open a door which Baritone was able to do multiple times without issue. This should be determined if this still occurs though as far as I can see, and from the comment above it seems fine (Though trapdoors wasnt used in my tests)

**Comment by S-B99** [comment]
This was closed in #3 

If this issue is still happening please provide logs and preferable a video of it happening. 

Trapdoors are #36
