### ISSUE TITLE
compileJava Fail using Baritone API in a custom mod – specifically BuilderProcess().build

### ISSUE THREAD

**Issue by VonHirsch** [cabaletta/baritone#1029]
I created a vanilla mod using Forge and MDK 1.12.2, and using the example API call works perfectly:

> BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().setGoalAndPath(new GoalXZ(10000, 20000));

However when I attempt to use the schematic builder in the same project like so:
> boolean success = BaritoneAPI.getProvider().getPrimaryBaritone().getBuilderProcess().build(file, origin);

The compiler is not happy:
![cannotAccessEt](https://user-images.githubusercontent.com/3280180/66531717-ba3f6e00-eada-11e9-85fb-2880bb8e11bf.JPG)

**Does anyone know why the argument "origin" of type BlockPos is obfuscated as type "et" in the IBuilderProcess build API call?  (see snippet of decompiled file in IDE below)**

![IBuilder](https://user-images.githubusercontent.com/3280180/66531845-4487d200-eadb-11e9-845f-d56447d104b3.JPG)

**Comment by VonHirsch** [comment]
was it something I said?  :)

**Comment by 0-x-2-2** [comment]
user error. use mcp mapped jar
