### ISSUE TITLE
Repack chunks on change

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#103]
Right now, if you mine diamond ore, the packed chunk will still think the diamond ore is there until it's unloaded and packed. We should repack chunks on any change to them, possibly. This might have high CPU usage though...

**Comment by leijurv** [comment]
We could hook this into onPlace in MixinMinecraft, but that wouldn't get placements by other players in the world.

**Comment by ZacSharp** [comment]
Wasn't this implemented in f3561cab47693799c01b6a59ee9fbaf2b7c0842c?

**Comment by leijurv** [comment]
yeah
