### ISSUE TITLE
Cannot access the builder process using the API

### ISSUE THREAD

**Issue by VonHirsch** [cabaletta/baritone#1030]
## Some information
Operating system: Windows
Java version: 1.8
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): Custom Vanilla MDK mod with sample command

## Exception, error or logs
![log](https://user-images.githubusercontent.com/3280180/66568674-ed641a80-eb37-11e9-8a1c-c0dd4d73903e.JPG)

## How to reproduce
Create a custom mod using MDK, attempt to access the builder process using the baritone API

## Offending Code
> String file = "test";
> BlockPos origin = new BlockPos(player.posX, player.posY, player.posZ);
> boolean success = BaritoneAPI.getProvider().getPrimaryBaritone().getBuilderProcess().build(file, origin); 
> _^ line 46_

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by VonHirsch** [comment]
I created a pull request which resolved this issue.  See if you like it:

https://github.com/cabaletta/baritone/pull/1035

**Comment by ZeroMemes** [comment]
How are you adding the dependency to your Forge environment?

**Comment by VonHirsch** [comment]
I added baritone-1.2.9.jar and baritone-1.2.9-sources.jar to /libs in my forge mod folder structure as I couldn't get the baritone gradle dependency to work as documented here: https://jitpack.io/#cabaletta/baritone

**Comment by VonHirsch** [comment]
I'm probably adding the dependency incorrectly then.

**Comment by VonHirsch** [comment]
is the method described on https://jitpack.io/#cabaletta/baritone the preferred way?
