### ISSUE TITLE
when I type command it says command not found don’t know what do do

### ISSUE THREAD

**Issue by Stingrayyz** [cabaletta/baritone#1037]
## Some information
Operating system: MAC
Java version: 1.14
Minecraft version: 1.14
Baritone version: 1.14
Forge mods (if used): 

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Orinion** [comment]
https://github.com/cabaletta/baritone/blob/master/USAGE.md
