### ISSUE TITLE
USAGE.md command link broken

### ISSUE THREAD

**Issue by jonnyawsom3** [cabaletta/baritone#1040]
Not really a bug and not very urgent, so i went with the suggestion tag. 

The link at the end of  

> For the rest of the commands, you can take a look at the code here.

In the USAGE.md (bottom of https://github.com/cabaletta/baritone/blob/master/USAGE.md#commands) no longer works, as the ExampleBaritoneControl.java no longer exists

**Comment by LeafHacker** [comment]
Can confirm. `ExampleBaritoneControl.java` no longer exists in `baritone.api.utils`

**Comment by Xephorix** [comment]
can confirm that confirmers confirment.

**Comment by jonnyawsom3** [comment]
Jeez, this still not fixed? Rip
