### ISSUE TITLE
API and Thrown Self on the Mercy of the Court

### ISSUE THREAD

**Issue by VonHirsch** [cabaletta/baritone#1041]
## Some information
Operating system: Windows
Java version: 1.8
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): Custom Vanilla MDK mod with sample command

## Appeal to the Developers
Hi guys, a few things:
1. I love you <3 you’re active, you’re passionate! it’s easy to order pizza with baritone
2. I’m trying to write a small forge bot to help IIS build highways on 2b (yes I know its dumb, but I’m really into 2b atm)
3. I promise, although I’m stupid I’m not a troll

My issue is, can you let me know the correct way to setup my environment so that the BuilderProcess API is not obfuscated.  I saw @LoganDark comments [here ](github.com/cabaletta/baritone/pull/952) about the API while I was trying to figure out why [ExampleBaritoneControl.java was deleted](https://github.com/cabaletta/baritone/pull/952/files#diff-6c14664f9f5156056826fb139767ccb1) and thought I’d make one last-ditch effort to see if I am stuck in “standalone, user error”

Thanks, Von

p.s. please let me know where I can donate $USD to this project
p.p.s apologize as this issue is probably a duplicate of https://github.com/cabaletta/baritone/issues/1030

## How to reproduce
See https://github.com/cabaletta/baritone/issues/1030

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Thrown self at your mercy

**Comment by leijurv** [comment]
ok i'll be real i really dont understand how any of the forge gradle stuff works

but

you can get a mcp mapped jar by doing `./gradlew jar`, you can get the notch mapped jar from releases, and you can get a searge mapped jar by doing some dark magic to build.gradle

i thINK `./gradlew jar` is what you want. bUT you can't launch that in forge after it's built, this jar is only to use as a library to build against.

you might have an easier time forking baritone and adding the stuff internally maybe

**Comment by VonHirsch** [comment]
thanks for the tips!  I'll look into those pixie dusts
