### ISSUE TITLE
why/how to get it to .b mine wood

### ISSUE THREAD

**Issue by Soulfultick** [cabaletta/baritone#1044]
It says Expected block option when i put .b mine Oak Wood

**Comment by theluigiduck** [comment]
it's .b mine oak_wood
spaces arent used
neither are capital letters

**Comment by theluigiduck** [comment]
i mean oak_log

**Comment by jpie726** [comment]
I personally am using just baritone, not impact yet, but it should be .b mine oak_log
since # is replaced by .b in impact as a "pointer" to baritone

**Comment by cancerousname69** [comment]
#mine log

**Comment by S-B99** [comment]
Why was this even opened. it's `#mine block damageId`
