### ISSUE TITLE
RAM usage instead of CPU usage?

### ISSUE THREAD

**Issue by jpie726** [cabaletta/baritone#1051]
I would like to see either optimization improvements cpu-side or swap some of the pathfinding processing to the RAM since i have a Ryzen 5 and I am maxing out at 1 fps whenever I
#mine a_block but i have 32gb of ram that i could easily dedicate 16 of for baritone.

**Comment by jpie726** [comment]
I am running 1.14.4 on a world that has already chunk-genned 1000+ chunks in any direction

**Comment by jpie726** [comment]
Did some even deeper digging and it looks like it is caused by biome blend, but i would still like to see baritone use RAM also.

**Comment by ZeroMemes** [comment]
RAM is not a processing unit

**Comment by 0-x-2-2** [comment]
🤡
