### ISSUE TITLE
when I type “# mine diamond_ore” it says command not found

### ISSUE THREAD

**Issue by Stingrayyz** [cabaletta/baritone#1054]
## Some information
Operating system: MAC
Java version: 1.14
Minecraft version: 1.14
Baritone version: 1.14
Forge mods (if used): 

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by aUniqueUser** [comment]
remove the space 
```#mine diamond_ore```

**Comment by TheK0tYaRa** [comment]
It ignores you because you haven't specified the mod for it.
`#mine minecraft:diamond_ore`

**Comment by TexRexTex** [comment]
> It ignores you because you haven't specified the mod for it.
> `#mine minecraft:diamond_ore`
it is not necessary to specify which mod it is from if it is from minecraft else you should specify the mod. Removing the space before `mine diamond_ore` should fix your problem

**Comment by TheK0tYaRa** [comment]
@TexRexTex it doesn't work so to me so I thought it won't work for anyone, but ok.

**Comment by Xephorix** [comment]
if you're running baritone through Impact then try the .b prefix.`.b mine minecraft:diamond_ore`

**Comment by SWEDCODER** [comment]
@Xephorix No wtf it's `.b mine diamond_ore` specifying the mod is useless for most cases

**Comment by TheK0tYaRa** [comment]
I never used .b in Impact, I just used # commands

**Comment by Coldram3n** [comment]
imagine using a mac

**Comment by TheK0tYaRa** [comment]
Imagine using non-quantum calculations

**Comment by dominikaaaa** [comment]
closed: inactive and offtopic
