### ISSUE TITLE
blocksToAvoidBreaking magma_block does not recognize the block name

### ISSUE THREAD

**Issue by BenVlodgi** [cabaletta/baritone#1056]
## Some information
Minecraft version: `1.12.2`
Baritone version: `1.2.10`
Impact version: `4.8.1`

## How to reproduce
Type
```#blocksToAvoidBreaking magma_block```

`#blocksToAvoidBreaking magma_block` fails because it does not recognize the block type.
However  `#blocksToAvoidBreaking magma` succeeds, though it shouldn't because I'm using the java version.
Even with `magma` set as a block to avoid, it still breaks it.

[Magma ID reference](https://minecraft.gamepedia.com/Magma_Block#Data_values)

**Comment by TheE1337** [comment]
blocksToAvoidBreaking is broken in general. I set it to minecraft:cobblestone_slab and it has no qualms about ruining my melon farm.

**Comment by ZeroMemes** [comment]
> However `#blocksToAvoidBreaking magma` succeeds, though it shouldn't because I'm using the java version.

Actually, this is incorrect. `magma` is the correct block name to use in 1.12.2.

Regardless, what is the situation in which magma is being broken? `blocksToAvoidBreaking` simply makes breaking the blocks less desirable, but if you're encased it will still break them.

**Comment by S-B99** [comment]
Closed due to inactivity and the issue being user error.
