### ISSUE TITLE
Mining/building underwater

### ISSUE THREAD

**Issue by wincheat02** [cabaletta/baritone#1060]
I would be nice to have an option to toggle mining/building underwater on and off.

**Comment by ZeroMemes** [comment]
Baritone is not designed to function in underwater movement, and it is designed to avoid liquids.

**Comment by wincheat02** [comment]
Okay, you have a point. I know this may be the wrong place to ask, but why does Build on Impact refuse to place blocks underwater. I have been told it uses baritone so..why?
