### ISSUE TITLE
Autocompletion don't update on user input

### ISSUE THREAD

**Issue by Ekibunnel** [cabaletta/baritone#1066]
## Some information
Minecraft version: 1.14.4
Baritone version: 1.4.3

## How to reproduce

1. Type your Baritone prefix
2. Press tab to use Autocompletion once
3. Continue to type your command
4. See that the Autocompletion is still at the start of your command

# Screenshots
### bug
![bug](https://i.imgur.com/XHdfQXO.gif)

### Expected behavior
![Expected behavior](https://i.imgur.com/VWKT7sD.gif)

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.

**Comment by ZacSharp** [comment]
Fixed in #4012
