### ISSUE TITLE
#goto death does not work. Expected ForBlockOptionalMeta

### ISSUE THREAD

**Issue by BenVlodgi** [cabaletta/baritone#1074]
## Some information
Minecraft version: `1.12.2`
Baritone version: `1.2.10`
Impact version: `4.8.1`

## How to reproduce
Die
Type `#goto death`
```Error at argument #1: Expected ForBlockOptionalMeta```

**Comment by leijurv** [comment]
The command has moved to be under `#wp`. Do `#help wp`. Once the goal is set you can do `#path`
