### ISSUE TITLE
(Aristois) @mine, and @goto both give an error "Error at argument #1: Expected ForBlockOptionalMeta"

### ISSUE THREAD

**Issue by EpicPro360** [cabaletta/baritone#1075]
@mine, and @goto both give an error "Error at argument #1: Expected ForBlockOptionalMeta" on Aristois client.

**Comment by MinecraftDude800** [comment]
Yeah I get this same issue using Aristois. It's weird because I used @mine 2 days ago and it worked perfectly.

**Comment by MinecraftDude800** [comment]
@EpicPro360 you should mark this as a bug

**Comment by FierceThundr** [comment]
Yup, I got the same thing, at least I don't need to make a new thread :P

**Comment by RealIndrit** [comment]
Chill, Im working on it lel

**Comment by hazenaerial** [comment]
Fabritone is not supported

**Comment by leijurv** [comment]
This is not a fabritone issue tracker
