### ISSUE TITLE
How do i install pullrequests?

### ISSUE THREAD

**Issue by PinkmanHD** [cabaletta/baritone#1076]
I think everything is saied

**Comment by zPeanut** [comment]
you cant "install" pull requests, what are you trying to do?

**Comment by StijnSimons** [comment]
you dont.

**Comment by PinkmanHD** [comment]
i want to install this feature
https://github.com/cabaletta/baritone/pull/877

but i dont know how to do it?
there isnt any info about it

**Comment by usereewrjrjeejr** [comment]
🤡

**Comment by Lokraan** [comment]
Go to the forked repository, clone it, and then follow the installation instructions.
