### ISSUE TITLE
Jumping??

### ISSUE THREAD

**Issue by Commander07** [cabaletta/baritone#1077]
baritone wont jump and just walks forward in 1.14.4 im using version 1.4.3

**Comment by LordVertice** [comment]
Does it refuse to jump at all, or only while walking forward?

**Comment by Commander07** [comment]
refuses to jump at all no jumping

**Comment by LordVertice** [comment]
Try toggling "#assumeStep"

**Comment by StijnSimons** [comment]
Comment your output of the `#modified` command.

**Comment by Marcus90000** [comment]
Mine doesn't jump up one single block forward I then type the #assumeStep and it jumps but only that once so I have to keep typing it in to make it keep jumping please help(P.S auto jump isn't on on anything)

**Comment by TheK0tYaRa** [comment]
`#set assumeStep true` if you have step functionality like a modified client or auto-jump enabled.
`#set assumeStep false` if you want Baritone to do that job.

**Comment by S-B99** [comment]
Closed as resolved.
