### ISSUE TITLE
Command to change the range of Baritone

### ISSUE THREAD

**Issue by j13li78** [cabaletta/baritone#1081]
## Describe your suggestion
Right now Baratione uses a increased range wich doesn't work on all servers.
Example: https://gyazo.com/14b883afd6ad5d75fd318d8bcc3657d0

## Settings
A float to change the range like ".b range 3.0".

## Context
It would make it work on some server that doesn't allow increased range

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
baritone uses the vanilla block reach.

**Comment by j13li78** [comment]
> 
> 
> baritone uses the vanilla block reach.

even tho you can see it's too high on some servers so a setting to change it would be nice

**Comment by ThebesAndSound** [comment]
2b2t is no longer the vanilla block reach, its slightly less meaning baritone keeps getting stuck especially when using cleararea. I am asking hause to fix it so this setting shouldn't be necessary at least for 2b.

**Comment by 0-x-2-2** [comment]
I don't think this is even in the scope of baritone anyways.

**Comment by leijurv** [comment]
Baritone overrides vanilla's block reach distance so it should at least be a setting, otherwise there would be literally no workaround possible

**Comment by 0-x-2-2** [comment]
> Baritone overrides vanilla's block reach distance so it should at least be a setting, otherwise there would be literally no workaround possible

Wtf?

**Comment by 0-x-2-2** [comment]
https://github.com/cabaletta/baritone/blob/518fa1c74daa7e8b9f764038410cc7b4fb982e94/src/main/java/baritone/utils/player/PrimaryPlayerContext.java#L61

Looks almost fine?

**Comment by 0-x-2-2** [comment]
Nice trolle. This is fake news.

https://github.com/cabaletta/baritone/blob/5c83ee264820cacd9ae133918faf3afd8541095b/src/api/java/baritone/api/utils/RayTraceUtils.java#L42

This is almost IDENTICAL to what the game does except it uses interpolated eye position and direction and I doubt that is the issue.

**Comment by leijurv** [comment]
look harder lmao
https://github.com/cabaletta/baritone/blob/518fa1c74daa7e8b9f764038410cc7b4fb982e94/src/api/java/baritone/api/utils/IPlayerController.java#L48

**Comment by 0-x-2-2** [comment]
> look harder lmao
> https://github.com/cabaletta/baritone/blob/518fa1c74daa7e8b9f764038410cc7b4fb982e94/src/api/java/baritone/api/utils/IPlayerController.java#L49

these are vanilla constants and this code is the same as vanilla.... nice "look harder"...

**Comment by leijurv** [comment]
I stand by what I said 
> Baritone overrides vanilla's block reach distance so it should at least be a setting, otherwise there would be literally no workaround possible

This is true. Since 2b2t has a lower block reach distance than vanilla, we should have some way to change this because it's hardcoded in our code, while some other mod could conceivably change vanilla's max to match.

**Comment by 0-x-2-2** [comment]
> I stand by what I said
> 
> > Baritone overrides vanilla's block reach distance so it should at least be a setting, otherwise there would be literally no workaround possible
> 
> This is true. Since 2b2t has a lower block reach distance than vanilla, we should have some way to change this because it's hardcoded in our code, while some other mod could conceivably change vanilla's max to match.

Is there a reason why Baritone even needs to have its own implementation of this? The game's implementation is the same and Forge added a reach entity attribute that is used here so making a mod would be super easy.

**Comment by mrphax0r** [comment]
I'd love that.

**Comment by 0-x-2-2** [comment]
2ae16d8bb1cd6bed87fe2a4858ac2e5458911079
