### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by PurplyDank** [cabaletta/baritone#1082]
## Some information
Operating system:Windows 10
Java version:Idk
Minecraft version:1.14.4 impact
Baritone version:1.4.3
Forge mods (if used): i didint

When i was trying to build a schamatic it said this:
 An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

**Comment by 0-x-2-2** [comment]
you cant use build on 1.13+
