### ISSUE TITLE
Baritone Won't Build Bug

### ISSUE THREAD

**Issue by SurviveThePersonPerson** [cabaletta/baritone#1084]
## Some information
Operating system: Windows 10
Java version: Version 8 Update 92
Minecraft version: Minecraft 1.14
Baritone version: 1.4.3
Forge mods (if used): None.

## Exception, error or logs
See logs here: https://hastebin.com/awumawawaq.md

## How to reproduce
Load any schematic in your schematics folder and attempt to allow baritone to build the schematic. You'll find an error telling you to report the bug here.

## Final checklist
- [ ✓] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ✓] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by TheK0tYaRa** [comment]
It looks like the block IDs are numbers, not letters. Not a dev, so I may be wrong.

**Comment by TheK0tYaRa** [comment]
Suggestion: try schematics NOT made for 1.13

**Comment by StijnSimons** [comment]
Invalid issue; log link is down.

**Comment by StijnSimons** [comment]
No build for 1.13+ yet. Blame schematic id’s.
... or leijurv for not using the updated sponge format.
