### ISSUE TITLE
Can't get Forge version to work

### ISSUE THREAD

**Issue by turret001** [cabaletta/baritone#1086]
## What do you need help with?
Hello, I've downloaded baritone-standalone-1.4.3.jar from [here](https://github.com/cabaletta/baritone/releases/tag/v1.4.3) and placed it into my Mods folder however, it does not show up in mods list in game.

Minecraft version: 1.14.4
Forge version 28.1.39
Java V8 Update 231 (build 1.8.0_231-b11)

## Final checklist
- [✓] I have not used any OwO's or UwU's in this issue.

**Comment by RealIndrit** [comment]
Well, maybe because of that 1.12. is the only Forge supported version?

**Comment by turret001** [comment]
> Well, maybe because of that 1.12. is the only Forge supported version?

ooh, I didn't know it was for 1.14.4. sorry!
