### ISSUE TITLE
Baritone with forge please 1.14.4

### ISSUE THREAD

**Issue by godjacky2** [cabaletta/baritone#1090]
Baritone with forge please 1.14.4

**Comment by TheK0tYaRa** [comment]
Not after 1.13.2 forge version, i suppose

**Comment by godjacky2** [comment]
How long it will be available

**Comment by TheK0tYaRa** [comment]
Dunno, not a dev

**Comment by StijnSimons** [comment]
Forge support has been abandoned

**Comment by unoccupiedname** [comment]
i agreee

**Comment by unoccupiedname** [comment]
> Baritone with forge please 1.14.4

pls

**Comment by S-B99** [comment]
Read like, 1 message up

**Comment by S-B99** [comment]
Isn't there a minimum age you have to have to be to have a github account, like 13?
![2020-02-09-111103_775x217_scrot](https://user-images.githubusercontent.com/17222512/74105556-fcca9300-4b2c-11ea-9435-e9101522b924.png)

**Comment by StijnSimons** [comment]
This is retarded

**Comment by unoccupiedname** [comment]
> This is retarded

no u

**Comment by StijnSimons** [comment]
petition to lock this thread

**Comment by S-B99** [comment]
> Unironically 9 years old

**Comment by Mhowser** [comment]
guys, use Fabric instead https://gitlab.com/CDAGaming/fabritone

**Comment by S-B99** [comment]
Uh, no? That's fabritone, that isn't baritone. That's an unsupported repo, and you linked exactly what this issue is not asking for.

**Comment by StijnSimons** [comment]
> guys, use Fabric instead https://gitlab.com/CDAGaming/fabritone

No reason to post that here, has nothing to do with baritone.

**Comment by Mhowser** [comment]
What do you mean it's not baritone? It is. It uses Fabric instead of Forge. If people want to play on 1.14+ this is another easy way.

**Comment by S-B99** [comment]
That's fabritone, not baritone. this repository is baritone, not fabritone.
