### ISSUE TITLE
trying to mine logs, error at arg. #1

### ISSUE THREAD

**Issue by riririru** [cabaletta/baritone#1091]
## Some information
Operating system:win10
Java version:newest
Minecraft version:1.14.4
Baritone version:newest, downloaded today
impact version 1.8.2
Forge mods (if used): 

## Exception, error or logs
Error at argument #1: Expected ForBlockOptionalMeta

## How to reproduce
type in minecraft chat: mine log  or type mine log:0

## Final checklist
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [dont know what these are] I have not used any OwO's or UwU's in this issue.

**Comment by TheK0tYaRa** [comment]
Try oak_log

**Comment by TheK0tYaRa** [comment]
Also, 1.14.4 has convinient thing called autocompletion. Baritone has it too, it just requires you to press ESC if it's stuck.

**Comment by riririru** [comment]
oak_log doesnt work aswell, i tried that on 1.12.2 and 1.14.4

**Comment by TheK0tYaRa** [comment]
try #mine 64 minecraft:oak_log

**Comment by riririru** [comment]
#mine log does work in 1.12.2

**Comment by TheK0tYaRa** [comment]
Yes, it doesn't work like that. You need to specify block id at least without the mod that is including it

**Comment by ZeroMemes** [comment]
The expected syntax for 1.12.2 is `block:meta`, so `log:0` would be valid.

The expected syntax for 1.13.2+ is `block`, because damage/meta values have been removed, so `oak_log` would be valid.
