### ISSUE TITLE
left click and drag to clear area

### ISSUE THREAD

**Issue by riririru** [cabaletta/baritone#1092]
## What do you need help with?
when i type .b click,
i can click and drag to select an area, but it doesnt clears it, how do i start the clearing process?

## Final checklist
- [i still dont know what these are ] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
As it helpfully says in chat, `#help sel` is where you want to look

**Comment by riririru** [comment]
but it doesnt say how i can mine them, it just tells me the arrangement
