### ISSUE TITLE
Multiple questions. [Solved]

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#1094]
## What do you need help with?
Is it possible to do a command to mine all types of logs?[Minecraft 1.14.4 Impact 4.8.2]
What is baritone made with{AI(Artificial Intelligence), ML(Machine Learning) OR DL(Deep Learning)}
[I always thought that dose three things are the same thing(I know they are similar but apparently they are not the same) I read [this article](https://towardsdatascience.com/deep-learning-weekly-piece-the-differences-between-ai-ml-and-dl-b6a203b70698)] which made me curious. Oh, and does it make any difference?

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheK0tYaRa** [comment]
Replacing in the selection is stackable so i suppose multimining is a thing if the number is specified.
As long as i know it's short-memory ML mixed with AI.
And the difference is that AI works only with expected states, while ML and DL can figure things out while running.

**Comment by StijnSimons** [comment]
https://en.m.wikipedia.org/wiki/A*_search_algorithm

**Comment by aUniqueUser** [comment]
You can specify multiple blocks using the #mine command, you can use this to mine all types of logs by listing them out.

Baritone is not an AI, it uses [A* search algorithm](https://en.wikipedia.org/wiki/A*_search_algorithm) to find the most efficient route to its destination.

**Comment by Hackerokuz** [comment]
Thank you for clearing this.
