### ISSUE TITLE
How use #wp save tag? 

### ISSUE THREAD

**Issue by NachoHuizar** [cabaletta/baritone#1096]
i use #wp save none , but they say "none" its not a tag, so what tag i have to use? or what is a tag?

**Comment by ZeroMemes** [comment]
"Saving" a waypoint simply means you are creating a waypoint based on some parameters, the valid syntax is below.
![image](https://user-images.githubusercontent.com/24485393/67595765-f3a7e880-f72c-11e9-8191-1a459ee96eda.png)

There are 4 tags that can be used: "home", "death", "bed" and "user". The death and bed tags will be automatically populated by baritone when you die or sleep, in most cases you will only ever use home or user.

An example of valid usage, assuming I am at my primary base and I want to create a new waypoint at it would be: `wp save home main`
