### ISSUE TITLE
Trace the path without walking

### ISSUE THREAD

**Issue by phaalonso** [cabaletta/baritone#1101]
All of us know how clear and open is a baritone user, so i have a suggestion for the goals. My suggestion is a command or a parameter that the baritone will show you the path but dont walk, the user has to done the walking by himself. This will help us mislead the staffs and anti-cheats

**Comment by mrphax0r** [comment]
Great idea!

**Comment by TheK0tYaRa** [comment]
It defeats half of the idea, but it still has usage. Unless you want to be accused of using Xray while going manually by the path to diamonds xD

**Comment by Footsiefat** [comment]
I see what you mean but its still a great idea for normal traversing to a location

**Comment by o0ZzM4g1c** [comment]
like #b gps start

**Comment by S-B99** [comment]
Duplicate of #431
