### ISSUE TITLE
Make ID conversion for schematics

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1103]
## Describe your suggestion
How about we add a possibility to convert schematics for the newer minecraft version using a script in #master or some fork.

## Settings
`$VersionFrom` and `$VersionTo` will be nice

## Context
Error reports with  `1.13 be like: numeric IDs btfo` will be solvable

## Final checklist
- [v] I have not used any OwO's or UwU's in this issue.

**Comment by SWEDCODER** [comment]
Great idea!

**Comment by TheK0tYaRa** [comment]
I will try to make it in AHK cause I don't know java or JS, hope it will be usable as is `before/if not` the proper implementation will be done.

**Comment by StijnSimons** [comment]
To be honest it should just be using the [updated Sponge format](https://github.com/SpongePowered/Schematic-Specification).

**Comment by ZacSharp** [comment]
Baritone now supports sponge schematics and at least one of the *.schematic formats in 1.13+ so I think this can be closed.
