### ISSUE TITLE
Baritone wont mine emerald ore

### ISSUE THREAD

**Issue by donatboy86** [cabaletta/baritone#1104]
When i try to mine emerald ores with #mine emerald_ore  it doesnt mine it but instead says:
[Baritone] Mining
[BlockOptionalMetaLookup{block={minecraft:emerald_ore}}]
[Baritone] No locations for
BlockOptionalMetaLookup[BlockOptionalMetaLookup{block={minecraft:emerald_ore}}] knowm, cancelling

am i doing something wrong or is something wrong
i use minecraft on windows 10 pro
i play minecraft java 1.14.4
[Edit] the command works with other blocks but emerald ores dont even work in singleplayer

**Comment by TheK0tYaRa** [comment]
Seems that you tried using Baritone on a server that has some complications with loading chunks or an anticheat. Try using `#set legitMine true`

**Comment by TexRexTex** [comment]
Hi I am pretty sure this error is occurring because there are no nearby emerald ores hence 
[Baritone] Mining
[BlockOptionalMetaLookup{block={minecraft:emerald_ore}}]
[Baritone] **No locations for**
BlockOptionalMetaLookup[BlockOptionalMetaLookup{block={minecraft:emerald_ore}}] knowm, cancelling

**Comment by TheK0tYaRa** [comment]
@TexRexTex You know that it can occur only if the server renders only 2 chunks away, right?

**Comment by TexRexTex** [comment]
Sorry I don’t understand

**Comment by TheK0tYaRa** [comment]
The game can't give Baritone the coordinates for the emerald_ore in two possibilities:
1) Server doesn't give client the coordinates for unseen blocks / parts of a chunk / seed.
2) Game is set to render distance of 2 chunks so they literally don't load in.

**Comment by donatboy86** [comment]
I edited something

**Comment by donatboy86** [comment]
@TheK0tYaRA I edited with extra info at the bottom

**Comment by RajehTXD** [comment]
@donatboy86 try placing some in creative and mining them

**Comment by donatboy86** [comment]
@RajehTXD then it works so i guess the problem is that there arent any close to me... but even if i put my render distance to max baritone still cant seem to find any

**Comment by MajsterTynek** [comment]
Are you sure you are mining in right biome?

**Comment by donatboy86** [comment]
Wait they spawn in specific biomes?

**Comment by MajsterTynek** [comment]
@donatboy86 [Emerald Ore](https://minecraft.gamepedia.com/Emerald_Ore#Natural_generation)
Baritone won't pathfind towards somthing it dosn't know about. 
It needs to know targets' positions first. 
You need to go mountain biome where it can find some.

**Comment by S-B99** [comment]
You can use https://baritone.leijurv.com/baritone/api/Settings.html#exploreForBlocks for that.

**Comment by pollyjuice** [comment]
See if you have allowonlyexposedores on true. If it's not it will only mine blocks that are well, exposed. This was my problem
