### ISSUE TITLE
Automine feature won't mine ores above head.

### ISSUE THREAD

**Issue by Rootzi** [cabaletta/baritone#1105]
## Some information
Operating system: 64-Bit Operating System, x64 based-processor
Java version: Version 8 Update 231 (build 1.8.0_231-b11)
Minecraft version: 1.14.4
Baritone version: Latest?
Forge mods (if used): Optifine

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
#mine (any_block)
be underneath a block and you will stand still and do nothing.

**Comment by TheK0tYaRa** [comment]
You sure it's forge, dude?

**Comment by kbartek05** [comment]
Happening to me too. Won't mine anything above the player, I'm on Aristois' EMC version tho.

**Comment by TexRexTex** [comment]
Hi I am pretty sure that baritone will not mine overhead blocks in case of gravel water lava etc.

**Comment by Footsiefat** [comment]
Same problem, cant automine quatrz in nether well

**Comment by SWEDCODER** [comment]
Weird thing, it doesn't happen to me.

**Comment by Footsiefat** [comment]
The problem occurred for most people with aristois 1.14.4

**Comment by Allison-Z** [comment]
same on aristois 1.14.4

**Comment by leijurv** [comment]
Aristois uses fabritone which is a fork of baritone that I'm not involved with. This is for issues with baritone, not ports of baritone to other environments (fabric in this case). Closing until someone can demonstrate that this issue exists with baritone (since every commenter so far has said it's with aristois 1.14.4).

**Comment by Footsiefat** [comment]
@leijurv I hope you can tell us how to use normal baritone with 1.14.4 then

**Comment by leijurv** [comment]
There is a very obvious link in the readme

normal baritone is not for fabric though, only vanilla 1.14.4

i'm not saying that this issue isn't fixable, and i'm not saying that you can't ask for it to be fixed, i'm just saying that this isn't the place to report it, since I can't fix it lol
