### ISSUE TITLE
replace funtion

### ISSUE THREAD

**Issue by TexRexTex** [cabaletta/baritone#1110]
## Describe your suggestion
replace <originalblock,originalblock2,etc.> <newblock,newblock2,etc.> [amount]
baritone would mine the original block then replace it with the new block

## Settings
amount of blocks to mine

## Context
This feature would greatly improve baritone saving lots of time being able to replace blocks.

## Final checklist
- [tick] I have not used any OwO's or UwU's in this issue.

**Comment by TheK0tYaRa** [comment]
Have you used `#sel replace` ever? It doesn't include the amount, but it can be stopped anytime

**Comment by TexRexTex** [comment]
Ok thanks. Ill try it
