### ISSUE TITLE
.b build not working.

### ISSUE THREAD

**Issue by costin88boss** [cabaletta/baritone#1113]
## Some information
Operating system: windows 10 64 bit 
Java version: 1.8 (8)
Minecraft version: 1.14.4
Baritone version: 1.4.3
Forge mods (if used): none. not even optifine, but i use impact 4.8.2

## Exception, error or logs
[https://drive.google.com/file/d/1Y4lpOn42g0jp1QLKd4x9iAOPM-cWmr_W/view?usp=sharing](url)
this is the download to latest log.
so, i have 2 schematics, one from a .b build tutorial, and one downloaded by me.
the one downloaded by me has couldn't load schematic error, the one from the tutorial is an unhandled exception occured. the error is in your game's log, please report this at (this site)
i don't think it is needed to put schematics links. 

## How to reproduce
use 1.14.4, baritone 1.4.3, enter any world, say .b build (schematic name) or #build schematicname.
the schematic from tutorial should work.

**Comment by TheK0tYaRa** [comment]
#1102

**Comment by zapidos** [comment]
baritone schematics not works in 1.14.4

**Comment by costin88boss** [comment]
zapidos answered so I closed it. looks like 1.14.4 doesn't  support. I think it's because 1.14 version changes schematics code when mojang built pillage post, abandoned villages, and stuff. they may also rebuilt the codes from other old schematics to make sure it works. If not, they may have rebuilt the schematics code and now pre-built generations from far away from player may be supported. else, they made minecraft stop lagging much, so they made schematics generate in another way and baritone can't success it.
