### ISSUE TITLE
Suggestions related to: general tasks and farming

### ISSUE THREAD

**Issue by CodeF53** [cabaletta/baritone#1115]
### What are these ideas for
Expanding the capability of autonomous work using baritone.
## Conditional actions.
- `#on` _condition_ `action`
  - conditions:
    - `#on complete` 
      - _after a task is completed, bots just sit there, so in the case of mobs, you are just left to die_
    - `#on damage`
      - _alot of tasks cant be done in protected areas, in the case of a skeleton, you can still be shot with `avoidance` on._
  - actions:
    - `ding` - plays a sound to alert the user of a finished task
    - `log` - logs the player off
    - `home` - bot goes home
    - `say ~~~~~` - says something in chat
      - _could be used with server commands like /home to avoid the bot getting stuck on it's way_
    - `store` - explained soon

## Parenthesis: `(action1, action2)` or `(condition1, condition2)`
if either condition1 or condition 2 are hit, do the following action
following the completion of action1, the bot will start action2.

#### components:
- while looking at a chest, type this to save a chest
  - `#savechest name`
- item types
  - `ores`
    - equivalent to `(iron_ore, coal_ore, gold_ore, emerald_ore, diamond_ore, redstone_ore)`
  - `mats`
    - equivalent to `(coal, redstone, diamond, emerald)`
  - `crops`
    - you get it.
#### `store` _item(s)/itemtype_ _chestname_
- will put all item(s) / items of itemtype into saved chest
- _items/itemtype_
  - `redstone` 
  - `(coal, diamond)`
  - `crops`
  - `(mats, cobblestone)`

## Farming
_lets be honest, `#farm` lacks a lot of capability_
What does it need?
- instead of farm failed when out of seeds/space/bonemeal, options for:
  - waiting for growth
  - completion
- target amounts to farm, just like target mine amounts
   - `#farm wheat 64`
- bone meal preference
  - what crop to use bone meal on when waiting

## Application of suggestions
`#on (damage, complete) (ding, home, store ores oreChest, store mats matChest)`
`#mine (iron 64, diamond 16)`
This will set off the bot to mine, then go home and store collected resources, without having it die idling in a cave after mining.

`#farmpref wait`
`#on (damage, complete) (ding, home, store (seeds, pumpkin_seeds) seedchest, store crops foodchest)`
`#farm (wheat 30, pumpkin 6, carrot 128)`

**Comment by MajsterTynek** [comment]
[done.wav](https://cdn.discordapp.com/attachments/443433439681839116/640409609231663104/done.wav), I suggest this as ding sound.
I made that for my log follower which searches for "Building done" phrase.
I wanted it to be as vibrant as possible, so we can hear it whatever we do in background.

Storing items should suport arrays of chest. 
There should be event (action?) for running out of storage space.
Looks like this "enhancement" goes towards some kind of scripting language.

**Comment by CodeF53** [comment]
If this could be integrated into some sort of scripting language that would Hella cool

**Comment by JoelEllis** [comment]
I’m gonna take the opportunity to point out that if you want to do this now, and a whole lot more, you should try the advanced macros mod. The mod uses Lua as a scripting language, and an event based trigger system. It is extremely powerful and one member of our community has even created an A* pathfinding script with it.

**Comment by dominikaaaa** [comment]
Most of these have already been suggested in other issues, make a new issue with just the farming stuff if you want that added.
