### ISSUE TITLE
Baritone building schematics not function

### ISSUE THREAD

**Issue by MinecraftIsFunWithBaritone** [cabaletta/baritone#1117]
## Some information
Operating system: MacOS
Java version: 1.14.4
Minecraft version: 1.14.4
Baritone version: 1.14.4
Forge mods (if used):  World Edit (Not with Baritone on)

I attempt to run baritone to build me an iron farm, but it keeps saying that is can't load the schematic. 

1. Use world edit to make a schematic (On Mac)
2. launch Baritone
3. Go to a new world
4. Get your items you need
5.  do "build (schematic name)"
At 5, Baritone says it can't load the file. I made a new file with the schematic inside of it

**Comment by StijnSimons** [comment]
Again, this is intentional. Building is currently not available for 1.13 or higher due to schematics being outdated.
