### ISSUE TITLE
Schematic building

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#112]
Just going to make an issue so I can write down my thoughts on the feasibility of this.

MineBot had a rudimentary structure builder, but it had several limitations. It worked by pathing to the position directly above every block it wanted to place. It assumed that the pathfinder would end up placing the block below in order to get there. It also pathed into blocks that should be air in the structure. This worked well for flat structures, but it got incredibly sketchy for larger structures. It could get stuck in loops weirdly. Most of the time it worked, but it placed way too many throwaway blocks then broke them on the layer down. As in, while removing the extraneous blocks in one layer, it placed exactly as many throwaways in the layer one below while pathing into them. 

I think Baritone structure building should go a slightly different route. MineBot structure building only relied on the pathfinding system, and that was its only interface with the world. I think we can do much better. For example, to break blocks we don't need to path into them, we just need to path within reach of them then break them from afar. Possibly same for placing, maybe later on.

I think a good first step is to have a different mode in the CalculationContext for structure building, in which instead of placing any throwaway block, it places the specific blocks that's supposed to go in that location. Pathing to above each location is possibly feasible, maybe from the bottom up. 

For building structures like map art, we could also include in the CalculationContext the positions that have high cost (maybe COST_INF) for placing above, and low cost for placing below. For example, placing a block above the map art ruins it, but placing a block below doesn't matter. 

Additionally, the CalculationContext could precompute what locations can be placed in, given what materials are currently on the hotbar. This could coordinate with the BuilderBehavior in terms of goal setting. For example, the BuilderBehavior could look at what block necessary to the schematic are present on the hotbar, then set a GoalComposite of GoalBlocks above those locations. It should only path to locations above blocks that should be present that aren't, *not* blocks that are present but incorrect. If the block is just incorrect, pathing to above it doesn't *do* anything. If the block is currently air, pathing to above it necessitates placing it.

An interesting question is how to deal with removing extraneous blocks. For example, should it place all the blocks it needs to, then remove all the extra ones. Or should it first remove the blocks that are incorrect, then place the blocks that should have been there, then finally remove all the blocks that should be air in the schematic? Or a hybrid alternating approach? I could see it doing parts of it along the whole path. For example, the cost of breaking a block that's incorrect is heavily decreased, and the cost of breaking a block that's correct is greatly increased.

Changes to pathing:

- Increase the cost of breaking a block that's correct in the schematic
- Decrease the cost of breaking a block that's incorrect in the schematic
- Decrease the cost of placing a block that's currently air but isn't in the schematic
- In map art mode, heavily increase the cost of placing a block that's above the schematic, and possibly decrease the cost of placing a block below the schematic. In normal mode, increase the cost of placing a throwaway block in a location that the schematic says should be air, relative to the cost of placing a throwaway block outside the schematic. (so it's better to pillar up outside the schematic then walk in higher up than pillaring up inside)
- When placing a throwaway block, instead of hotbar selecting dirt, cobble, or netherrack, select the block that the schematic calls for at that location.

Possible behavior of BuilderBehavior

- Build a list of all positions to be broken. 
- *stretch goal* maybe possibly raytrace and see on what blocks you could stand to break incorrect blocks?
- In any event, it should pause the path at any location where a block to be broken is within reach, but not directly supporting the player or a part of the planned path. Same for placing blocks that are currently air but shouldn't be, if any face of an adjacent block can be placed against and we hav ethe requisite block on the hotbar, place it. This is a crutch to the real solution (previous bullet point) but should allow for more efficient breaking and placing.
- Set the goal. This should definitely be a GoalComposite. This makes it go around the structure and doing all the things it needs to do, more or less. For any position that's air but should be a block, add a GoalBlock to the position directly above. For any position that's an incorrect block, or is a block but should be air, set a GoalTwoBlocks for it. 
- Update this goal every tick. Possibly even cancel the current path every time the state changes, to avoid placing throwaways as much as possible, and to end it early when its destination has already been satisfied by a place from BuilderBehavior while it was paused.

With that goal setting behavior, path pausing, and those changes to cost calculation and throwaway placing behavior, I think a robust structure builder can be created.

**Comment by SylveonBottle** [comment]
https://www.youtube.com/watch?v=mahhJ6zK2BU
https://github.com/ImpactDevelopment/ImpactClient/issues/858

**Comment by WaffleTraits** [comment]
You should add a way to display what items will be needed to build any given schematic.

**Comment by leijurv** [comment]
just do that in mcedit lol

**Comment by SylveonBottle** [comment]
Wait, doesn't schematica already do this?

**Comment by leijurv** [comment]
wait do people run both schematica and baritone

if so thats hilarious

**Comment by SylveonBottle** [comment]
🤔 ...would that even be compatible? Just get baritone to run around in a circle.. check for updated blocks.. maybe actually path through schematica's ghost blocks 'n shit... Maybe baritone can load schematica files?

**Comment by leijurv** [comment]
baritone can load schematics. but it doesn't do the cool ghostly rendering of what it'll eventually look like. i guess you could run baritone builder branch as a forge mod plus schematica, but only use schematica for the rendering 😂

**Comment by josephkentcraig** [comment]
Which version of baritone can load schematics?
Is there a standalone forge .jar for the builder? 

Because the rendering from schematica is rather nice. Especially with know the material list and an idea of what the finished project would look like.
