### ISSUE TITLE
loop bug

### ISSUE THREAD

**Issue by jesinhell** [cabaletta/baritone#1122]
## Some information
Operating system: windows
Java version: 

![ezgif-4-47483aeb4810](https://user-images.githubusercontent.com/57310550/68081494-49b11600-fe28-11e9-8300-6d95008bec8c.gif)

1.8.0 64 bit
Minecraft version: 12.2
Baritone version: 1.2.10
Forge mods (if used): nope

im trying to use autobuild for schematic file. when the automatic build puts half block (ex:stair,glass pane) which is in schematic plan,then it breaks that block and puts it back(looping). how can i fix it?

**Comment by PublicByte** [comment]
You seem to use an invalid issue format, please look at the issue template for further information.

**Comment by PublicByte** [comment]
Please edit your issue title according to reflect the essence of the issue itself.

**Comment by PublicByte** [comment]
You didn't fulfill all issue requirements, please look at issue requirements for further information.

**Comment by S-B99** [comment]
You can fix this by pausing baritone and resuming after walking somewhere else manually.
