### ISSUE TITLE
What is a 'tag'?

### ISSUE THREAD

**Issue by Wollfyy** [cabaletta/baritone#1126]
When I try to set a waypoint, I have to do the specific setup:
#wp s tag name
but I don't know what a 'tag' is, and how to use it... help?

**Comment by SWEDCODER** [comment]
A tag is like an user-defined ID, just like a name with less letters, I think it's that, I still haven't experimented with waypoints but try around.

**Comment by derBobo** [comment]
Tags are used to categorize your waypoints all tags can be found in this [file](https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/cache/IWaypoint.java)

**Comment by Wollfyy** [comment]
ty!!

**Comment by LoganDark** [comment]
In 1.12, there's tab completion too if you don't remember the tags.
