### ISSUE TITLE
Let "sel ca" mine from top to bottom.

### ISSUE THREAD

**Issue by Daenges** [cabaletta/baritone#1128]
## Describe your suggestion:
It would be a bool you could set to true or false. So Baritone would start to mine from the top of the selected area instead of going to the bottom first and start there.

## Settings:
You can activate it like any other option. For example "Legit Mine".

## Context:
The problem is that digging from the bottom to the top is very inefficient. Baritone always needs to build pillars to reach the top layer and starts to mine out of the marked box, which makes the walls looks awful. If the bot starts from the top, it just needs to dig 2 blocks down, clear the layer and start the next without abusing the walls or building pillars.

## Final checklist:
- [ ] I have not used any OwO's or UwU's in this issue.
- Sorry for English bad, me Michael from "Customer Support"!

**Comment by ThebesAndSound** [comment]
Do both #buildinlayers true and #layerorder true, this is what #layerorder does

**Comment by JulianGHill** [comment]
> Do both #buildinlayers true and #layerorder true, this is what #layerorder does

When I do this, the bot want to be able to stand on the level it has to dig.
This doesn't allow me to dig straight down so it keeps on looking for a path to go down.
Any fix for this?

**Comment by ThebesAndSound** [comment]
#breakfromabove true and #goalbreakfromabove true

**Comment by fulcanelly** [comment]
@ThebesAndSound 

> goalbreakfromabove

goalbreakfromabove for some reason causes infinite loop in some cases 

for example when breaking threes
