### ISSUE TITLE
Old waypoint system setting

### ISSUE THREAD

**Issue by mrphax0r** [cabaletta/baritone#1130]
## Describe your suggestion
It would be nice to add a setting that brings back the old waypoint system, for 2 reasons: 
1. Getting used to the new system is fucking annoying
2. The new #wp system is not as easy to understand for newbies as the old one. (#1126 )

## Context
Me still trying to #save waypoints. GRRRRRRRRRRRRRRRRRRRRRRRR

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SWEDCODER** [comment]
Heheh, donner worry with time it vers even casier than the old one

**Comment by S-B99** [comment]
New one was added for a reason.
