### ISSUE TITLE
The follow command doesn't seem to work right.

### ISSUE THREAD

**Issue by MajickTek** [cabaletta/baritone#1133]
## Some information
Operating system: Windows 10 Home
Java version: 1.8.0_222 [OpenJDK]
Minecraft version: 1.14.4
Baritone version: 1.4.3
Forge mods (if used): 

## Exception, error or logs
`Error at argument #1: Expected aw.`

## How to reproduce
Type `#follow playername`, as shown in the Usage readme.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
`playername` is a placeholder in syntax for the name of an actual player

**Comment by MajickTek** [comment]
That was not my issue. My issue is that if I use the command properly with a real username, it gives the error i posted.

it worked in previous versions

**Comment by 0xicl33n** [comment]
can confirm this bug, it used to work just fine
![image](https://user-images.githubusercontent.com/2192160/68901000-e8bbf480-06e9-11ea-8f7d-33425c094d54.png)

**Comment by Nikita11790** [comment]
help

**Comment by MajickTek** [comment]
Someone needs to reopen this issue, as it isn't solved and the person who closed it misread my issue.

@ZeroMemes Please reopen this

**Comment by MajickTek** [comment]
Still an issue.

**Comment by Wudg3r** [comment]
I found a solution! Type #follow then the type of entity. So #follow player (Playername)
Or #follow Sheep (Sheepname)
Worked for me!

**Comment by MajickTek** [comment]
Ah that does seem to be the solution! @ZeroMemes thanks for nothing, you could have told me the proper syntax. This needs to be changed in the help menu to be more clear.

**Comment by S-B99** [comment]
Uh, the help code literally says you need player before it. 

https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/command/defaults/FollowCommand.java#L129

**Comment by S-B99** [comment]
Then the usage doc is outdated.

**Comment by S-B99** [comment]
> which you said I should use

I didn't say that, but the linked documentation works. If you used the help command in game you would've gotten the proper usage.

**Comment by MajickTek** [comment]
read again. I said the _documentation_ said i should use a certain command.

> which said that you should use

**Comment by 0xicl33n** [comment]
In all fairness, `USAGE.md` should be updated

**Comment by S-B99** [comment]
It has an issue opened to be updated, and Seven is working on it as I speak. 

I linked the proper documentation and you confused me with Brady,

**Comment by Wudg3r** [comment]
In #help it says type #follow [playername]. That is the main thing people use when stumped ingame, and it should be updated as it is incorrect

**Comment by S-B99** [comment]
Then create an issue for that to be updated. I linked the actual code because that can't be outdated.

**Comment by Commandcracker** [comment]
#follow player [playername]
