### ISSUE TITLE
noXRay mode

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1137]
Like the bot don't search ores with xray, instead he play normally like exploring caves or use a normal mining optimisation technique, and if he find an ore he mine it, if not he continues to walk/mine randomly (but efficiently) to find new ones

THAT'S the ultimate legitMining

**Comment by bphd** [comment]
I suggest that because the XRay legitMine mode is way to obvious. Like yeah he use caves, but he goes DIRECTLY to the ores, especially when they're underground and thats not natural at all
I say that you should naturally continues to improve the XRay more but you should propose a non XRay mode to play a maximum legitimely because XRay is way too much obvious

**Comment by bphd** [comment]
Or yeah, you'll tell me that it isn't an AI but a bot, that he cannot "see" but only make path to an objective
So okay, use XRay bot not to find ores, but to help him to go mine it, but considerate that he can mine those only if he has see it (like direct vision for example), and maybe other conditions to define to act more naturally

**Comment by leijurv** [comment]
legitMine does not use xray, and it is truly legit. It will never go towards an ore that it cannot actually see visually.

**Comment by SylveonBottle** [comment]
> legitMine does not use xray, and it is truly legit. It will never go towards an ore that it cannot actually see visually.

But it does appear to mine towards open spots with xray, no? A legit "legitmine" would just keep digging forward until it finds a cave, explores the cave (digging up visible ores), then continues on it's way. 

![image](https://user-images.githubusercontent.com/17802843/69902558-da5e1180-1354-11ea-9679-bee1ce5e8085.png)

In this example, baritone shouldn't have known that there was a cave upwards and start digging towards it. 

![image](https://user-images.githubusercontent.com/17802843/69902626-9ae3f500-1355-11ea-9b7f-7e4db5a9dfc1.png)

Bot took a left up towards a cave it shouldn't have known that was there. If someone were to follow the path of the bot, one could assume the player was going the other way and went towards the sound of lava. 

![image](https://user-images.githubusercontent.com/17802843/69902662-eb5b5280-1355-11ea-8fd1-4681f1e98fbd.png)

But this here is clearly suspicious. Bot was on the tunnel in the right, took a sudden angle to the left immediately to the tip of a cave. Once again, if someone were to follow the tunnel _backwards_, it'd look a little fine - like the player dug in a little and just decided to head west or whatever. But if someone was spectating..

![image](https://user-images.githubusercontent.com/17802843/69902715-5f95f600-1356-11ea-9947-9bbfcf9eaa03.png)

Don't even get me started on this one. My ass would be immediately banned if anyone caught me digging straight down into a mineshaft. So much for "legitmine" never using xray.



That being said, I'd imagine a fix for this would to have the bot not path into areas beyond blocks. The bot, just as a player would, shouldn't know what's behind a wall. So if the bot wants to mine through a wall, it should mine to the wall first, then initiate tunneler feature until it either hits a cave / air again.

**Comment by m-sarabi** [comment]
I think for this to work the AI should ignore any path that involves breaking any block that is followed by an open area (except if it is at the mining Y level and mining straight, that should be allowed).
