### ISSUE TITLE
Need more examples of simple baritone itegration. (pause, resume, stop)

### ISSUE THREAD

**Issue by MajsterTynek** [cabaletta/baritone#1138]
## What do you need help with?
I want to get Baritone's state to check what it's doing, if it's paused
and I need some controlsover it like pausing, resuming and stopping.
I looked trough documentation, but I don't know what I should search for.

BTW [ExampleBaritoneControl.java](https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/utils/ExampleBaritoneControl.java) is missing from the source code

**Comment by 0-x-2-2** [comment]
ExampleBaritoneControl was replaced with a 10k command system. You can use a custom process with a higher priority level to pause and resume.

**Comment by MajsterTynek** [comment]
I do not want to create new process or start new one.
I need help with getting controls over active process. :/

**Comment by 0-x-2-2** [comment]
> I do not want to create new process or start new one.
> I need help with getting controls over active process. :/

My response is still valid... What I told you is how you do it...
