### ISSUE TITLE
More of a question: How can I change the speed at which baritone places blocks?

### ISSUE THREAD

**Issue by RileyGuy** [cabaletta/baritone#1142]
Essentially as the title says, I looked through the settings and can't find a way to change the block placing delay.

**Comment by RileyGuy** [comment]
P.S. Is there also a setting to make baritone search inventories for prerequisite blocks?

**Comment by koraseeq** [comment]
#rightClickSpeed

**Comment by ZacSharp** [comment]
No, there is no way to have it search in chests and even baritone would have to open them to see what is inside
But a feature to automatically walk to chest that baritone remembers a specific item in would be usefull

**Comment by dominikaaaa** [comment]
why is this still opened and why did you comment something completely unrelated on it??

**Comment by ZacSharp** [comment]
It was asked in the 2nd comment by the author

https://github.com/cabaletta/baritone/issues/1142#issuecomment-553248769 :
> Is there also a setting to make baritone search inventories for prerequisite blocks?

**Comment by dominikaaaa** [comment]
I missed that, sorry. Baritone has it suggested, and it's possible if you build the pull request for it
