### ISSUE TITLE
set a number of repeats for #buildrepeat

### ISSUE THREAD

**Issue by ThebesAndSound** [cabaletta/baritone#1145]
#repeatvalue `<number-of-times-to-repeat>`
0 = infinite (default)

I'm digging a long wide tunnel and want to afk it to the end but dont want it to continue after. Also has applications building, like if you only want to make 7 pillars.

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/ddc681fe772a4a8a3550d4f34a963bc1cc163b61
