### ISSUE TITLE
Gets stuck temporarily while jumping over 1 block barriers

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#115]
https://youtu.be/tqiSSsoZYLw?t=3m21s

Currently not sure what causes this. I've never seen it (that I can remember) in Baritone standalone, so it might be an interaction with one of Impact's hacks.

**Comment by leijurv** [comment]
It might be No Push

**Comment by leijurv** [comment]
https://youtu.be/O07asVhaCiI I can't reproduce this at all, I think it's an Impact issue? With No Push off in Impact I also can't make it happen there. @ZeroMemes ?

**Comment by ZeroMemes** [comment]
Did you rerun the exact test in that video with Impact?

**Comment by leijurv** [comment]
Yes it happens only with impact. The video I'm currently uploading has it several times.
