### ISSUE TITLE
Charcoal

### ISSUE THREAD

**Issue by Millanoski** [cabaletta/baritone#1151]
when i put #mine charcoal_ore it says it's wrong so i'd like to know the name of the things, i've been searching about those names but i just haven't found nothing so maybe the names for the ores in the "read me" text would be amazing

**Comment by Deauthorized** [comment]
theres no such thing as charcoal ore

it's minecraft:coal_ore

**Comment by leijurv** [comment]
Massive brain

**Comment by Millanoski** [comment]
sorry, i am a taco speaker and i didn't know coal was a sinonimyc of charcoal
