### ISSUE TITLE
Mine in a specific area 

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1152]
## Describe your suggestion
It would make it better to use in prison and probably also other stuff

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion. 
If you make a area with #sel pos1 and pos2 (or .click) and type #mine iron_ore it would only mine that ore in that area.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
It would make it easier to play prison. Because I play prison and it would help a lot

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.
Yes

**Comment by ThebesAndSound** [comment]
#sel replace iron_ore air

**Comment by S-B99** [comment]
Closed as resolved.

**Comment by Kezii** [comment]
this is not resolved, `sel replace` just breaks stuff, it doesn't pick it up, it doesn't work like the "mine" command

**Comment by Timmarus** [comment]
This should be reopened as it's not resolved. The two features discussed are fundamentally different

**Comment by MrFums** [comment]
This should be looked into, needs to be reopened again

**Comment by milezero31** [comment]
> This should be reopened as it's not resolved. The two features discussed are fundamentally different. Sel replace only allows one block to be chosen as opposed to multiple, and as mentioned before, does not pick up blocks mined

For anyone curious it is actually possible to do
Sel replace iron_ore coal_ore stone dirt air
And all of the blocks before the last block will be replaced by the last block

**Comment by Timmarus** [comment]
But that solution doesn't pick up dropped objects.

**Comment by ethbra** [comment]
This still needs to be fixed; there is a distinct difference between the "replace" and "mine" commands. You are unable to pick up the dropped item using a replace command, which would be helpful in many situations, for example mining trees that are near a wood base.

**Comment by Xerox0987** [comment]
Had anyone find a solution?
