### ISSUE TITLE
When mining, allow Baritone to destroy small packets of 1x1 lava.

### ISSUE THREAD

**Issue by Mentalgen** [cabaletta/baritone#1154]
> ## Describe your suggestion
> Allow Baritone to be "brave" and destroy lava blocks that is in it's path. (Smartly of course and not getting itself killed).
> 
> ## Settings
> 
>"#set doBreakLava"
>or
>"#set pathBraveBoy"
>  
>When set to true, the bot will brute-force it's way to the destination instead of going around.
>When set to false, the bot will take on the default path set before.
>
> ## Context
> Tunneling in the Nether to make highways is a painful process that requires almost constant attention. So much so that you might as well just be doing it yourself since. Having it detect the small pockets of lava and *then* getting rid of them with using a bucket or placing blocks within the lava and not just simply avoiding it would be really helpful.
> 
> ## Final checklist
> * I have not used any OwO's or UwU's in this issue.

**Comment by ThebesAndSound** [comment]
This is hard to code but I think it would be great if #tunnel can deal with lava pockets

**Comment by RajehTXD** [comment]
@ThebesAndSound is see you everywhere on repos

**Comment by ThebesAndSound** [comment]
@RajehTXD what can i say? im baritone’s number 1 fan 😅

**Comment by SylveonBottle** [comment]
> This is hard to code but I think it would be great if #tunnel can deal with lava pockets

Should be easy, no? Allow baritone to break blocks next to liquids if it's only a single liquid, then attempt to place a block on the liquid. If that block happens to be infront of tunneler, tunneler should continue on it's way, breaking the block that was just placed. Otherwise, this should also pretty much block off any 1x1x1 lava pockets in the nether if they would've flowed into the path.

**Comment by JDButter** [comment]
Ah, So this _was_ not a setting! Welp, hope I'm able to see it soon. Manual Digging's getting Tiring!

**Comment by graemeg** [comment]
Exactly the same request... I requested this for Impact client, but got told the Baritone project is probably the more appropriate place. My original report and use case:

**Is your feature request related to a problem? Please describe.**
I'm using Impact 4.9.1 + Baritone 1.2.14 to build a diagonal Nether highway. It simply stops when it found a lava pocket (1x1x1) and then stands there while lava flows onto your feet. Without AutoLog (during a AFK session) you will be dead.

**Describe the solution you'd like**
Could it be improved to auto-fill such single lava pockets, or step back to avoid the lava flow touching you.

**Describe alternatives you've considered**
Some other mod-clients like KAMI Blue can already do this (though glitchy at times).

**Comment by Eclipse-Sol** [comment]
Its been like 5 years since this issue was made, has this been added since, or does a similar feature exist? Id like to close this out.

**Comment by SeasonalFerret** [comment]
> Its been like 5 years since this issue was made, has this been added since, or does a similar feature exist? Id like to close this out.

Considering the lack of interest from anyone capable of creating such a feature, I would agree with closing this.
