### ISSUE TITLE
A way to run Baritone commands from other mods (Ex: Macro Keybind Mod)

### ISSUE THREAD

**Issue by U5B** [cabaletta/baritone#1155]
## Describe your suggestion
Intercept simulated chat packets sent by other mods.

## Settings
#chatIntercept 
Toggles between if Baritone is intercepting chat packets or not.

## Context
Allow you to use baritone commands in other mods such as Macro Keybind Mod by intercepting simulated chat packets from those mods.

This would allow players to make scripts that support Baritone.

An issue could be that servers could then run Baritone commands.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Simeonlps** [comment]
set the key to type something into the chat then let it type whatever you want into chat

example: set a key to #goto 0 0
