### ISSUE TITLE
#build not working!

### ISSUE THREAD

**Issue by NeonShy** [cabaletta/baritone#1157]
Was trying to get baritone to build a endercastle I plucked from schematics just to see if it would work and I got the following error on 1.14.4 

[aah.txt](https://github.com/cabaletta/baritone/files/3866718/aah.txt)

**Comment by stanley50z** [comment]
same

**Comment by aUniqueUser** [comment]
Schematica doesn't work in anything above 1.12.2.

**Comment by NeonShy** [comment]
> Schematica doesn't work in anything above 1.12.2.

Don't have schematica installed, was trying to #build don't know if it uses schematica to try and #build but I didn't have it installed. :P
