### ISSUE TITLE
Finding slime chunks and increase range for following mobs

### ISSUE THREAD

**Issue by ShadowDarkLight** [cabaletta/baritone#1161]
I don't know if there's already a slime chunk finder or a function for increase the range to following near mobs, like the mine function with entities or at least the mobs.

**Comment by cancerousname69** [comment]
Increasing the range of following mobs is pretty easy, read the Settings.json

**Comment by S-B99** [comment]
Finding slime chunks is not in the scope of baritone, use a website like chunkbase for that.
