### ISSUE TITLE
Error using Baritone API in a forge 1.14.4 mod

### ISSUE THREAD

**Issue by DiamondMiner88** [cabaletta/baritone#1172]
## What do you need help with?
When executing `BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().setGoalAndPath(new GoalXZ(100, 100));`
In a 1.14.4 forge mod, i imported the API as a library in IntelliJ and as a dependency in Gradle i get this error:

> Description: keyPressed event handler
> 
> java.lang.NoClassDefFoundError: bce
> 	at baritone.api.Settings.<init>(Unknown Source) ~[baritone-api-1.4.3.jar:1.4.3] {}
> 	at baritone.api.BaritoneAPI.<clinit>(Unknown Source) ~[baritone-api-1.4.3.jar:1.4.3] {}
> 	at ml.diamondbuildz.netherslabber.Main.startBaritone(Main.java:19) ~[classes/:?] {}
> 	at ml.diamondbuildz.netherslabber.EventHandler.clientChatEvent(EventHandler.java:16) ~[classes/:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler_0_EventHandler_clientChatEvent_ClientChatEvent.invoke(.dynamic) ~[?:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
> 	at net.minecraftforge.event.ForgeEventFactory.onClientSendMessage(ForgeEventFactory.java:341) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {}
> 	at net.minecraft.client.gui.screen.Screen.sendMessage(Screen.java:311) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screen.Screen.sendMessage(Screen.java:307) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screen.ChatScreen.keyPressed(ChatScreen.java:131) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.KeyboardListener.lambda$onKeyEvent$4(KeyboardListener.java:303) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.KeyboardListener.onKeyEvent(KeyboardListener.java:294) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
> 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
> 	at net.minecraft.client.MainWindow.poll(MainWindow.java:403) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.MainWindow.update(MainWindow.java:273) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.updateDisplay(Minecraft.java:979) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:943) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:384) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:128) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {pl:runtimedistcleaner:A}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
> 	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}
> 	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:101) [forge-1.14.4-28.1.0_mapped_snapshot_20191128-1.14.3-recomp.jar:?] {}
> Caused by: java.lang.ClassNotFoundException: bce
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202] {}
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_202] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202] {}
> 	... 34 more
## Final checklist
- [X ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
baritone does not work with 1.13/1.14 forge

**Comment by 0-x-2-2** [comment]
baritone does not work with 1.13/1.14 forge

**Comment by DiamondMiner88** [comment]
Then how am i supposed to use the api?

**Comment by 0-x-2-2** [comment]
You just use it when it is in the classpath
