### ISSUE TITLE
Baritone will not try to do any parkour with allow parkour on.

### ISSUE THREAD

**Issue by Xand0n** [cabaletta/baritone#1177]
Instead it stops under or runs into a wall and gives up. I cannot get it to do this totally possible jump with block placing/breaking set to false. When I turn on slowpath it doesn't ever check to jump.
![2019-12-01_15 06 04](https://user-images.githubusercontent.com/51677135/69922411-e3340d80-1450-11ea-8666-3157977a9a2a.png)

**Comment by 0Xandon0** [comment]
Somehow I found the email to my old lost account.

**Comment by ZacSharp** [comment]
It does not try parkour in your case because it only does 1-3 block gaps in the 4 cardinal directions, flat or ascending
You have a descending diagonal followed by a diagonal
