### ISSUE TITLE
Notify user with a sound when building a schematic has failed/completed?

### ISSUE THREAD

**Issue by Orange65** [cabaletta/baritone#1179]
## What do you need help with?
Is it possible to get a sound to play to notify the user when bartione has either complete a schematic or failed to complete a schematic (when the bot pauses/stops).
## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ThebesAndSound** [comment]
i too would like a bingy bell

**Comment by dominikaaaa** [comment]
See #https://github.com/cabaletta/baritone/pull/1324
