### ISSUE TITLE
Soul Sand frontplace issue

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#118]
Front placing while standing on soul sand works normally, but not if we're standing too close. This only happens (from what I've seen) when we've just mined and jumped through that space.

**Comment by leijurv** [comment]
Demo video: https://youtu.be/ANWhB-HOzPg

**Comment by leijurv** [comment]
Another example: https://youtu.be/vpWCAz3uGfA?t=0m43s

**Comment by Superfly-Johnson** [comment]
Still happens in 1.2.12, it's a real pain in the ass to get baritone unstuck whenever it interacts with soulsand.

**Comment by dominikaaaa** [comment]
you're not able to walk on Soul Sand by default in Baritone

**Comment by Superfly-Johnson** [comment]
> 
> 
> you're not able to walk on Soul Sand by default in Baritone

Guess it's a Kami problem then huh?

**Comment by dominikaaaa** [comment]
No????

**Comment by dominikaaaa** [comment]
If you experience this make an issue then. This is over 2 years old.
