### ISSUE TITLE
Autofarm Bug/Issue

### ISSUE THREAD

**Issue by glakoi** [cabaletta/baritone#1180]
## Some information
Operating system: Windows 10
Java version: Not sure, Im just running impact 1.14.4
Minecraft version: 1.14.4
Baritone version: Not sure, the latest one on impact hacked client
Forge mods (if used):  None

Hello, So i've been using impact client recently and also tested this on baritone (the latest version). Everytime I toggle autofarm, it brings me up to the farm layer and mines the netherwart and the soulsand and does not even place the netherwart back. I'm just trying to farm at the moment with the client but it seems to not work with me. Any help?

**Comment by Orinion** [comment]
there is a replantCrops setting

**Comment by glakoi** [comment]
> there is a replantCrops setting

How can i toggle that on? and is there a way to not mine the soul sand when the command farm is toggled on

**Comment by leonardosnt** [comment]
> > there is a replantCrops setting
> 
> How can i toggle that on? and is there a way to not mine the soul sand when the command farm is toggled on

To replant netherwart you need to set the `replantNetherWart` setting to true.
Use `#set replantNetherWart true` in the chat to do that
