### ISSUE TITLE
Add some command to highlight specific blocks.

### ISSUE THREAD

**Issue by SilentGamer475** [cabaletta/baritone#1181]
## Describe your suggestion
When using the mine command, you can see highlights of the block that you are trying to mine, and the target blocks. I think there should be some sort of command like “Highlight [block]” so that it highlights all of those target blocks like when using the mine command. I would use this for things like finding spawners without mining, see how ore rich an area is, etc. It would have the same context as the mine command, meaning you could target multiple types of blocks in one command. That’s all I really have for now. Thanks for reading.

**Comment by nbyrd** [comment]
Huh. I thought that the `#find` command did that, but it doesn't. I agree; would be handy for `#find` and `#findEntity`

**Comment by Luggibumm** [comment]
If you want to find a block just use #goto (block) or if you want it to highlight the block use impact(baritone is integrated) and use the search module(impact has other important features like autoeat, killaura, ...)

**Comment by 0-x-2-2** [comment]
> Huh. I thought that the `#find` command did that, but it doesn't. I agree; would be handy for `#find` and `#findEntity`

#follow entity minecraft:entity
#follow player name
#follow players

**Comment by 4021885** [comment]
There is kind of a solution.
First #mine "mincraft:Specific_Block"
Then: #pause

And you can use #unpause And #pause to check new area's.
It's not the best. but it works. for now.

It wil highlight the blocks, and a path to one in a, i would guess, 60 block radius. didnt measure. it's not how its suppose to work, but it does.
