### ISSUE TITLE
Where to find code and commands on website

### ISSUE THREAD

**Issue by rjgolinski** [cabaletta/baritone#1186]
## What do you need help with?
I wanted to know what all the baritone commands were, but when I click the link to the code after the "common commands" list in the usage tab (https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/utils/ExampleBaritoneControl.java), it gives me a 404 error. Is there anywhere I can currently find the list of ALL Baritone commands, not just the 20 common example ones?

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
https://github.com/cabaletta/baritone/tree/master/src/main/java/baritone/command/defaults

leaving this issue open since that link needs to be fixed

**Comment by S-B99** [comment]
mfw @leijurv hasn't fixed it yet

**Comment by S-B99** [comment]
Duplicate of #1040
