### ISSUE TITLE
Question about dists

### ISSUE THREAD

**Issue by Pannoniae** [cabaletta/baritone#1187]
## What do you need help with?
Just a quick question: why does the installation say "Unoptimized: Nothing is obfuscated. This shouldn't be used ever in production."
Is something bad happening if you do?

## Final checklist
- [yes] I have not used any OwO's or UwU's in this issue.

**Comment by aUniqueUser** [comment]
No, baritone is just much slower when its not obfuscated with progaurd.

**Comment by Pannoniae** [comment]
Thanks! Is that for every java program, or is baritone unique in that? If yes, how?

**Comment by aUniqueUser** [comment]
No, its only useful for baritone because it is a large program, on smaller programs their might be a small improvement but nothing noticeable.

**Comment by StijnSimons** [comment]
...because you shouldn’t put something in production which isn’t obfuscated?

**Comment by ramidzkh** [comment]
No, obfuscation doesn't help in performance. Proguard, however, also applies optimizations which do help in performance.

**Comment by RileyGuy** [comment]
You should probably use the builds meant for general use rather than the unobfuscated/unoptimized one unless you're working on it for development.
