### ISSUE TITLE
When will be 1.15 version release?

### ISSUE THREAD

**Issue by Deputy001** [cabaletta/baritone#1188]

**Comment by 0-x-2-2** [comment]
No ETA currently afaik.

**Comment by RealIndrit** [comment]
Lmao, Fabric version will be out pretty soon probably, because @CDAGaming  XDDD

**Comment by CDAGaming** [comment]
As of today as well, a 1.15 port of Baritone, using Fabric (Fabritone) will be available at my fork in Gitlab: https://gitlab.com/CDAGaming/fabritone

CI Builds are autobuilt, and note Fabritone is not an official product of Baritone, only a fork of it maintained for Fabric by me and @RealIndrit
