### ISSUE TITLE
Issue with #build

### ISSUE THREAD

**Issue by SlickRickBoi** [cabaletta/baritone#1190]
I might be doing it wrong, but I cannot get the #build command to work. I have the file in the correct folder I believe, but it gives me _this_ error in the Launcher log.

 **"[Info: 2019-12-15 02:59:42.0783597: GameCallbacks.cpp(142)] Game/rd (main) Info [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo"** 

I am fairly certain the files are in the right place, and I have used correct spellings. What have I done wrong here?

**Comment by S-B99** [comment]
Make sure your schematic is 1.12
