### ISSUE TITLE
Breking blocks specified in blocksToAvoidBreaking

### ISSUE THREAD

**Issue by wincheat02** [cabaletta/baritone#1196]
## What do you need help with?
Why does baritone break blocks that are specified in blocksToAvoidBreaking when doing #sel replace [block] air or #mine?
I have included a video to maybe help explain what I mean.
shorturl.at/chrzV
shorturl.at/bnsHS
## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by wincheat02** [comment]
thanks....

**Comment by wincheat02** [comment]
Thanks for the help :)

**Comment by ThebesAndSound** [comment]
a new setting that works called #buildignoreblocks is coming soon

**Comment by wincheat02** [comment]
Oh great, so it will basically be the same but actually working?

**Comment by ThebesAndSound** [comment]
i think blocktoavoidbreaking something to do with pathing and doesnt work for building

**Comment by wincheat02** [comment]
It doesnt, it works properly in some cases like here : shorturl.at/jqwT5
Why does it do this? I need to clear out a cylinder and I cant cause it will just go throught and keep mining the world.

**Comment by wincheat02** [comment]
Also its great that a legitimate question has been closed without any answers :)))))))

**Comment by ThebesAndSound** [comment]
the answer is that it is solved by #buildignoreblocks and if you compile baritone for yourself you have access to it right now

**Comment by wincheat02** [comment]
wdym
