### ISSUE TITLE
Disabling Freelook causes screen juddering

### ISSUE THREAD

**Issue by Virologicbody** [cabaletta/baritone#1198]
## Some information
Operating system: Windows 10
Java version: Standard/included Java Version
Minecraft version: 1.14.4-Impact 4.8.2/vanilla
Baritone version: 1.4.3
Forge mods (if used): NONE

## Exception, error or logs
No errors found

## How to reproduce
Using ImpactInstaller-0.7.5 install MC vanilla version 1.14.4, Impact version 4.8.2 (latest at the time of writing this).
In a world set a goal and start Baritone path with the setting 'freelook' disabled. Screen will quickly judder left/right as the player is moving.

https://youtu.be/sirNJvrJ3zc

It was suggested on Discord that I should disable/change the 'randomLooking' value but this did not solve the issue.

Also effects:
1.13.2-Impact 4.8.2/vanilla
Baritone version 1.3.5

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
¯\_(ツ)_/¯

**Comment by Virologicbody** [comment]
So.. I assume this issue will stay 'as is' then?

I have just done a fresh 1.14.4 Impact install on a Macbook Air as I thought something to do with my PC was causing this issue but the Macbook has the same problem.....

**Comment by Virologicbody** [comment]
EDIT:

https://pastebin.com/QZAYAfxn

Used Pastebin as this log is pretty big...

**Comment by 0-x-2-2** [comment]
Don't disable freeLook this is also purely visual.
