### ISSUE TITLE
Schematic files

### ISSUE THREAD

**Issue by noahthesehlat** [cabaletta/baritone#1202]
Please help. I can't find a schematic file anywhere in the %appdata%. What do I do, and how do I fix it?

**Comment by ThebesAndSound** [comment]
%appdata%/.minecraft/schematics

**Comment by oiirn29** [comment]
> %appdata%/.minecraft/schematics

ok fine but how can you save schematic files for 1.14?

**Comment by S-B99** [comment]
You use a program that supports saving them. Iirc baritone doesn't save schematics, only loads them.
