### ISSUE TITLE
Stop as soon as .goto found athe desired block

### ISSUE THREAD

**Issue by Johnny112233** [cabaletta/baritone#1203]
Hi,
I am searching with **.goto** and **exploreforblocks** for specific blocks in the nether. Since it is a lot faster and I only need the corrdinates, I am running on top of the bedrock. 

The **.goto** command of course cannot go through the bedrock and just goes on as soon as it finds the desired block since it cannot reach it. This is why I would just like it to stop as soon it finds the specific block, so I can note the coordinates and come back when I am below the bedrock.

Do you have any idea how to do that?

**Comment by S-B99** [comment]
Pretty sure if it can't find a path it stops
