### ISSUE TITLE
AutoMine addon

### ISSUE THREAD

**Issue by SuperFurias** [cabaletta/baritone#1206]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

Would it be possible to insert an option to mine the same block in different places? for example I am playing in a prison where there is a mine with infinite blocks (that is, they regenerate instantly as soon as you break them), but if you always dig the same block you take damage until you die, it would be possible to add an option that allows you to "move to another block" after you've mined it a few times or a whole while?

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

.b set checkPersistentBlock true/false (for example)
if the block you are digging is persistent, skip to the next available block, and ignore the one previously excavated for a certain amount of time 
(that the player can decide, for example 100 ticks which are 5 seconds)
.b set skipToNextBlock 100

(I'm not good at choosing names for these things, I ask for forgiveness)

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

It could be useful as in my case or like many other cases in which the block to be excavated cannot be mined in the same point several times

## Final checklist
- [yes] I have not used any OwO's or UwU's in this issue.

**Comment by PublicByte** [comment]
You seem to have forgotten how to tick checkboxes. GitHub/Markdown checkboxes can be used to keep track of tasks or to create a checklist of requirements that need to be fulfilled whilst writing, for example, an issue. This can be achieved through writing a text similar to this:

```markdown
- [x] Hello, fulfilled requirement!
- [ ] Hello, unfulfilled requirement!
```

The above example will turn into this:

- [x] Hello, fulfilled requirement!
- [ ] Hello, unfulfilled requirement!

What you might have observed is that the `x` between `[` and `]` indicates that the task has been fulfilled, compared to an unfulfilled task without `x`. There's no room for further spaces (meaning `- [ x]` and `- [x ]` is invalid).

**Comment by S-B99** [comment]
See #361 and the `#sel` command
