### ISSUE TITLE
Jittery camera on 1.13 or higher

### ISSUE THREAD

**Issue by Simeonlps** [cabaletta/baritone#1209]
when i switched to impact 1.13.2 and hopped on a server (anarchy) and imidiately did #goto 0 0
freelook was, and still is turned off.

because of that in 1.13 or above (tested all versions possible) the camera gets really jiterry and jumps around a the "pathing line" a lot.

is there a way to fix this? has anyone else experienced this?

*This isnt an optifine issue!!!*

**Comment by 0-x-2-2** [comment]
random looking to fix meme sprint bug
