### ISSUE TITLE
Baritone keeps falling off layers and stucking

### ISSUE THREAD

**Issue by Kentaurio** [cabaletta/baritone#1212]
## What do you need help with?
I'm trying to build a Jesus Christ statue from Rio and buildinlayers is set to true. But when baritone is building like 20th layer it falls down and can't continue. I found max fall height in settings but min value is 3 and even with this value it keeps falling down. 

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

One more question: what is OwO and UwU?

**Comment by ThebesAndSound** [comment]
does it go down to do something, or just fall off?

**Comment by Kentaurio** [comment]
nope, i just fall off

**Comment by ThebesAndSound** [comment]
if you are using impact try the antidesync module

**Comment by 0-x-2-2** [comment]
If you have any more info just post a comment with it and we will reopen the issue.
