### ISSUE TITLE
Minecraft Fabritone Problem 1.15.1

### ISSUE THREAD

**Issue by Deputy001** [cabaletta/baritone#1213]
Fabritone has no problems with the Parkour, but does not build on the edge of a block unless you look at it. (it can't make stairs, you have to look at that area to build that.)

Here's the video: https://youtu.be/5gXT3x-gXwM

**Comment by ThebesAndSound** [comment]
this is the baritone github not fabritone

**Comment by Deputy001** [comment]
it's still same program though.. So back to business is there a way to fix it?

**Comment by SpicyBigDaddy-alt** [comment]
Different dev team
