### ISSUE TITLE
Does the baritone have a function to automatically pick up falling objects?

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#1215]
I want to know if the baritone has the function of automatically picking up falling objects. If I don't want to add it, I think it will be very useful. If so, please tell me, thank you very much.

**Comment by panwojtek8** [comment]
yes if you use #mine [block name here] than it will mine and pick up the block

**Comment by lingyunQAQ** [comment]
> 是的，如果您使用#mine [这里的块名称]，那么它将开采并捡起该块

Oh no i'm talking about falling instead of mining

**Comment by 0-x-2-2** [comment]
> > 是的，如果您使用#mine [这里的块名称]，那么它将开采并捡起该块
> 
> Oh no i'm talking about harvesting rather than mining

#follow entity minecraft:item ?
