### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by nbyrd** [cabaletta/baritone#1217]
## Describe your suggestion
It would be handy if Baritone supported geofencing, allowing the bot to restrict its operations to explicitly include or exclude regions of the world map.

## Settings
Proposed example commands.
3-Dimensional: user specifies geofence using two sets of xyz coordinates (similar to vanilla's `/fill` command).
`#geofence 0 0 0 16 20 24` - This would create a 3D geofence with one corner at `x=0,y=0,z=0` and the opposing corner at `x=16,y=20,z=24`. 

2-Dimensional: user specifies geofence using two sets of xz coordinates.
`#geofence 0 0 100 200` - This would create a getofence with one corner at `x=0,z=0` and the opposing corner at `x=100,z=200`. The y axis would be agnostic, similar to how the 2-parameter `#goto` command works.

Clearing Geofence:
`#geofence clear` - Tells Baritone to stop restricting itself to any active geofence

Geofencing should support relative coordinates.
`#geofence ~ ~ ~-100 ~100`  - Creates a geofence whose XZ coordinate starts at the user's location and ends at `x=-100,z=100`.

Geofencing should be INCLUSIVE by default, meaning that the bot will not roam or affect blocks outside of the specified region. An exclusive option should be available to invert this behavior.
`#geofence 0 0 -420 69 exclusive` 

## Context
This could be used to restrict mining and farming to a fixed region, or to prevent accidentally mining through areas where block mining is undesirable. 

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
#sel?

**Comment by darkstar01** [comment]
This sounds like a great idea, or have it slowly expand its territory but always remember the home base. It would favor familiarity over expansion unless expansion was necessary for resource gathering.

The bot would choose to randomly explore while mining or hunting, etc.. then it could return and explore those new areas.

**Comment by S-B99** [comment]
You can do #sel

**Comment by MajsterTynek** [comment]
how would you do #sel for #farm or #path?
another good idea thrown to trash
