### ISSUE TITLE
An option for Baritone that it Logs Out when it reaches the specific #goto location

### ISSUE THREAD

**Issue by RicardoThanos** [cabaletta/baritone#1220]
## Describe your suggestion
There should be a setting (you can toggle on/off) that when you reach the Custom GoalBlock using #goto it would log out of the server/world (disconnect/save and quit to title)

## Settings
Toggling logout when reaching Custom GoalBlock using #goto

## Context
When you are going to set the goal to a really far place (like the worldborder) you might go to sleep or away from your device, if you reach the Custom GoalBlock without you being there and you die, you have to do it all over again. It would be helpful for me and possibly other players.

## Final checklist
     - [ ] I have not used any OwO's or UwU's in this issue.
No I have not used any OwO's or UwU's in this issue.

**Comment by panwojtek8** [comment]
disconnectOnArrival do you mean this toggle?

**Comment by leijurv** [comment]
Yep, already exists.
