### ISSUE TITLE
bot doesn't walk on hoppers

### ISSUE THREAD

**Issue by muleamike** [cabaletta/baritone#1225]
just like title says, bot doesn't walk on hoppers

**Comment by 0-x-2-2** [comment]
hoppers suck

**Comment by U5B** [comment]
add cauldrons too that

**Comment by S-B99** [comment]
why would you walk on hoppers

does that not hurt your feet

**Comment by StijnSimons** [comment]
https://github.com/cabaletta/baritone/blob/2b71b31cfac8c5e633c8e49aa8286eaa5ae3d78d/src/main/java/baritone/pathing/movement/MovementHelper.java#L296
Should be changed to add (semi) walkable blocks

**Comment by 0-x-2-2** [comment]
> Should be changed to add (semi) walkable blocks

It won't walk on them because it is very easy to get stuck.

**Comment by PublicByte** [comment]
You seem to use an invalid issue format, please look at the issue template for further information.

**Comment by S-B99** [comment]
> It won't walk on them because it is very easy to get stuck.

Closing as resolved, this is intentional behavior.
