### ISSUE TITLE
.Goto just like cancels after a while it has been on for no reason

### ISSUE THREAD

**Issue by imjohne** [cabaletta/baritone#1229]
## Some information
Operating system: Windows 7
Java version: 1.8.0_231-b11
Minecraft version: 1.12.2
Baritone version: 1.4.3 (Impact version: 4.8.2)
Forge mods (if used):  Optifine

I play on an anarchy server 2b2t and I've used .Goto (Coords) and #Goto (Coords) and both seem to just randomly stop after being on for a long time. It's like the baritone cancels itself and stops completly even tho it hasn't finished to it's goal. (Not sure if this is a bug or just a strange setting bug.)

(How to recreate)
just type #goto 100000 70 0 (Far distance) and if you leave it on it will just stop for no reason even tho it's not close to it's goal.

**Comment by S-B99** [comment]
Hi, please provide more information such as a video if this is still happening.
