### ISSUE TITLE
1.15.1

### ISSUE THREAD

**Issue by Deputy001** [cabaletta/baritone#1230]
Still waiting for 1.15.1 when will it be released?

**Comment by FTC55** [comment]
There's a fork called Fabritone that supports 1.15.1

**Comment by Deputy001** [comment]
i know and i used it and it has so many issues. I just want to know that when it could be released? is there and ETA?

**Comment by aUniqueUser** [comment]
@Deputy001 Currently no ETA, but their is a 1.15.1 branch of baritone in development.
https://github.com/cabaletta/baritone/tree/1.15.1

**Comment by 0-x-2-2** [comment]
no eta. it will be released when it is in a good state.

**Comment by S-B99** [comment]
Now in beta.
