### ISSUE TITLE
I have a request, not exactly sure where to add this at, but here it is.

### ISSUE THREAD

**Issue by karlwollerman** [cabaletta/baritone#1231]
(new to github btw)
I want to ask of a multi-bot command system, that I have seen someone going by "connor" use where bots can be either:
A: Controlled by command on another account than the bot account.
B: call "backup" to it's position.
I ask of this so I can command bots from my main account for more efficiency.
I have seen certain mentions of such a system, if it is existent already, please guide me.
this is useful to many people who want to make multi-bot operations, but not have to type out the wanted commands on those other bot accounts.

**Comment by karlwollerman** [comment]
I mean as in remotely commanding, if this is possible, I would love to know how to do it.

**Comment by mrphax0r** [comment]
There's a [Minecraft command-line client](https://github.com/ORelio/Minecraft-Console-Client), There might be a possibility to add baritone to it. I'll make a issue.

**Comment by 0-x-2-2** [comment]
> There's a [Minecraft command-line client](https://github.com/ORelio/Minecraft-Console-Client), There might be a possibility to add baritone to it. I'll make a issue.

🤡
