### ISSUE TITLE
I updated the JSON for use with Optifine (MC 1.14.4)

### ISSUE THREAD

**Issue by Ansh934** [cabaletta/baritone#1235]
## Information 
I have just updated the json file
earlier it was baritone 1.4.1 with optifine 1.14.4-OptiFine_HD_U_F3 
Now it will be baritone 1.4.4 with optifine 1.14.4-OptiFine_HD_U_F5
I think it is perfect because I have provided download link for libraries too 😀

## Steps
Firstly download https://github.com/cabaletta/baritone/releases/download/v1.4.4/baritone-api-1.4.4.jar this and place it like this `.minecraft\libraries\cabaletta\baritone-api\1.4.4\baritone-api-1.4.4.jar`

Then Replace the contents of `.minecraft/versions/1.14.4-OptiFine_HD_U_F5/1.14.4-OptiFine_HD_U_F5.json` with this text. (I hope you have installed 1.14.4-OptiFine_HD_U_F5)

```
{
  "id": "1.14.4-OptiFine_HD_U_F5",
  "inheritsFrom": "1.14.4",
  "time": "2020-01-13T10:23:29+05:30",
  "releaseTime": "2020-01-13T10:23:29+05:30",
  "type": "release",
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "0",
  "arguments": {
    "game": [
      "--tweakClass",
      "baritone.launch.BaritoneTweaker",
	  "optifine.OptiFineTweaker"
    ]
  },
  "libraries": [
    {
      "name": "cabaletta:baritone-api:1.4.4",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "http://repo1.maven.org/maven2/"
    },
	{
      "name": "optifine:OptiFine:1.14.4_HD_U_F5"
    },
    {
      "name": "optifine:launchwrapper-of:2.1"
    }
  ]
}
```

Done!

**Comment by crispylemons** [comment]
I've followed all the steps with the exact same versions of Optifine and Baritone Installed. When I run my version Optifine in the Minecraft launcher it does not launch. My Optifine version only launching after the modification of the .json file.

**Comment by Ansh934** [comment]
> I've followed all the steps with the exact same versions of Optifine and Baritone Installed. When I run my version Optifine in the Minecraft launcher it does not launch. My Optifine version only launching after the modification of the .json file.

I have made some changes in the json file. Now try to launch

**Comment by S-B99** [comment]
This is useful, but doesn't fit the purpose of an issue, though I will refer to this in the future when people ask for this, thank you!
