### ISSUE TITLE
Question about ladders and height

### ISSUE THREAD

**Issue by CTEIIAWKA** [cabaletta/baritone#1238]
is it possible to forbid a baritone to be at a certain height? and how to prohibit the use of stairs?

**Comment by Ansh934** [comment]
i dont think there is such a feature right now.

**Comment by cancerousname69** [comment]
it would be easily doable though.

**Comment by l1ving** [comment]
#2052

**Comment by InferusAnima** [comment]
why closed?

**Comment by l1ving** [comment]
It was a question.
