### ISSUE TITLE
Automatize processes with Baritone

### ISSUE THREAD

**Issue by justliunet** [cabaletta/baritone#1239]
I was wondering If there could be any way to automatize some of the features with MacroMod because as far as I know you can't macro any of the commands like `#save` or `#path`, it just shows the message in chat.

Thanks for your help!

- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
use a better macro mod

**Comment by lUCA299** [comment]
You cant read baritones chat output with macromod but you can execute commands with it. Although thats just basic. If u want something good you would need to make your own baritone module

**Comment by dominikaaaa** [comment]
why are you commenting on an already closed issue? Also, #176
