### ISSUE TITLE
Game crashes when opening in game links.

### ISSUE THREAD

**Issue by crispylemons** [cabaletta/baritone#1243]
## Some information
Operating system:
Java version: 1.8.0_51
Minecraft version: 1.14.4
Baritone version: Baritone 1.4.4 for 1.14.4 it also happens with Baritone 1.4 and Impact using Baritone 1.4.3
Forge mods (if used): N/A

## Exception, error or logs
https://pastebin.com/JVaNynm5 - Baritone log
https://pastebin.com/qZ6vDZ6X - Impact log

## How to reproduce
Login to any server and click a website link
I you need a link usually there is the command /website or /vote
The game will crash

## Final checklist
- [ Yes] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [Yes ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ Huh] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
This looks like a vanilla bug?

**Comment by leijurv** [comment]
Fixed in Impact 4.8.3, update
