### ISSUE TITLE
Auto durability checker

### ISSUE THREAD

**Issue by BlueChicken745** [cabaletta/baritone#1245]
Add a feature where the baritone bot checks your tool durability and if it is too low (say 1 durability) it will stop before the tool breaks.

The setting could be to change the durability that it will stop at (idk if that’s possible)

This would make it so you could use enchanted tools without worrying about them breaking while afk mining. I had this experience where I had just come back to my pc after leaving baritone on for a while and seeing my enchanted pickaxe was gone.

**Comment by TheCrazyInsanity** [comment]
its default n impact and impact includes baritone.

**Comment by S-B99** [comment]
This is out of the scope for baritone. The purpose of it is for path finding and automating actions, this is too specific imo.
