### ISSUE TITLE
Macro + repeet mine dection

### ISSUE THREAD

**Issue by crispylemons** [cabaletta/baritone#1246]
## Describe your suggestion
It would be nice if there were a way to detect when the bot has mined the same block more than a number of times and trigger a simple chat macro e.g. /home, /hub, /wild, /server factions or /spawn. And if you are up to it a macro which allows for hot bar selection, left and right click also on a chosen inventory slots (number the slots from 1 to 'however large the menu is'). As a server might only allows the compass to navigate.

## Settings
Number of times the same block needs to be mined.
Toggle for if the same blocks has been placed/mined or both.

## Context
This is applicable for factions when the bot runs into claimed land. Also is useful for when a server is reloaded and the bot is at spawn or the hub trying to mine. The bot could candle all actions but would lose hours of productivity. The option to trigger a simple chat macro in this situation would allow the bot to get back of track. E.g when the bot runs into claimed land #stop, /wild, #mine diamond_ore (some servers use a menu for /wild hens need for a more featured macro). E.g a survival server restart. #stop, /server survival, /wild #mine_diamond_ore. Combine this with lolzhunter suggestion of player detection and the bot could trigger /home or /wild. You can stack features on top of the macro easily. Like when baritone inventory is full trigger a macro to /shop and sell the item you were mining.

## Final checklist
- [What] I have not used any OwO's or UwU's in this issue.

**Comment by jpie726** [comment]
I second this, at the very least detection of amount of blocks mined will trigger #stop and a command

**Comment by S-B99** [comment]
This is out of scope. You can use the baritone API with literally any macro mod to achieve this as well.
