### ISSUE TITLE
buildIgnoreExisting option makes weired schematic

### ISSUE THREAD

**Issue by o0ZzM4g1c** [cabaletta/baritone#1250]
## Some information
Operating system: Win10 x64
Java version: 8u241 x64
Minecraft version: 1.12.2
Baritone version: 1.2.11
Impact 4.8.3

## Exception, error or logs
When build option _buildIgnoreExisting_ is _true_ : 
then it doesn't consider the schematic material but it takes the first or active one in the hot-bar.

## How to reproduce
- make a simple cobble schematic
- set option _buildIgnoreExisting_ to _true_
- put another material in the hot bar then cobble and dirt
- build the schematic

## Video of what it does
[https://streamable.com/s/8osn3](https://streamable.com/s/8osn3)

## Original cube.schematic
is 100% cobble !
![cube](https://user-images.githubusercontent.com/43145135/72574666-154ae300-38ca-11ea-8cf1-db83e8c65dc6.png)

**Comment by ZeroMemes** [comment]
The setting is behaving as expected 
![image](https://user-images.githubusercontent.com/24485393/76153844-e6feae00-6097-11ea-8222-a88812116362.png)

**Comment by S-B99** [comment]
Why was this reopened? Bruh

**Comment by daeds1dog** [comment]
How? It's just placing random garbage instead of the correct schematic blocks.

> The setting is behaving as expected
> ![image](https://user-images.githubusercontent.com/24485393/76153844-e6feae00-6097-11ea-8222-a88812116362.png)

How? It's just placing garbage instead of the actual blocks.

**Comment by ZeroMemes** [comment]
nvm

**Comment by S-B99** [comment]
mfw

**Comment by ZeroMemes** [comment]
Fixed
