### ISSUE TITLE
Follow feature doesn't work correctly

### ISSUE THREAD

**Issue by NopeScel** [cabaletta/baritone#1252]
## Some information
Operating system: windows
Java version: 1.12.2
Minecraft version: 1.12.2
Baritone version: from impact v 4.8
Forge mods (if used):

## Exception, error or logs
Exception ax

## How to reproduce
Follow (name of player you are trying to follow)

## Final checklist
- [ yes] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [yes ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ yes] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Works for me

**Comment by Nikita11790** [comment]
doesn't work for me

**Comment by S-B99** [comment]
Make sure you include the persons username after the follow command, it helps

**Comment by Nikita11790** [comment]
Already do that

**Comment by S-B99** [comment]
Try turning it off and on again

**Comment by Nikita11790** [comment]
Even tried reinstall didn’t work

**Comment by S-B99** [comment]
I have no words for you except maybe you're doing it wrong. It works on impact 4.8.3, and probably earlier.
![ezgif com-optimize](https://user-images.githubusercontent.com/17222512/72776597-c4e0c780-3be0-11ea-9fd9-71adbcb170df.gif)
