### ISSUE TITLE
Metadata not being taken into account for #mine

### ISSUE THREAD

**Issue by turret001** [cabaletta/baritone#1253]
## Some information
Operating system: Windows 10
Java version:  V8 Update 211 (build 1.8.0_211-b12)
Minecraft version: 1.12.2
Baritone version: v1.2.10
Forge mods (if used): https://rawgit.com/AllTheMods/ATM3-Remix/master/modlist.html

## Exception, error or logs
Baritone doesn't take metadata into account for modded ores. thermalfoundation:ore:2 should only mine copper ores from the mod Thermal Foundation but it also mines other ores from Thermal Foundation mod. It would be nice to have oreDict support for #mine 

## How to reproduce
Download ATM 3 Remix mod pack and try #mine thermalfoundation:ore:2.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by turret001** [comment]
can someone please confirm?

**Comment by NeariX67** [comment]
In FTB Ultimate reloaded with Baritone 1.2.14 ```#mine thermalfoundation:ore:0``` (copper ore) works perfectly
