### ISSUE TITLE
Only mine a block once/Only mine blocks in a certain area 

### ISSUE THREAD

**Issue by Kromittt** [cabaletta/baritone#1255]
So I was wondering if there is a way to get Baritone to only try to mine a block once? Because for example on the server im in an area, some certain oak logs can not be mined(the server doesnt let you), but i want baritone to mine the others near it but it always pathfinds there eventually and gets stuck.

This problem could also be fixed if there is a way to keep the bots pathfinding in a certain radius, or exclude blocks outside a certain radius or at certain coordinates.

Thanks in advance!

**Comment by ThebesAndSound** [comment]
#help sel
you can make a selection
#sel replace log air

**Comment by Kromittt** [comment]
> #help sel
> you can make a selection
> #sel replace log air

Could you please explain what this does?

**Comment by turret001** [comment]
> > #help sel
> > you can make a selection
> > #sel replace log air
> 
> Could you please explain what this does?

#help sel > shows help about selecting an area

#sel replace log air > replaces every 'log' block in area with 'air' (simply breaking every log block in area)

**Comment by Kromittt** [comment]
> > > #help sel
> > > you can make a selection
> > > #sel replace log air
> > 
> > 
> > Could you please explain what this does?
> 
> #help sel > shows help about selecting an area
> 
> #sel replace log air > replaces every 'log' block in area with 'air' (simply breaking every log block in area)

Thanks, ill try it and tell you how it goes!

**Comment by Kromittt** [comment]
> 
> 
> > > #help sel
> > > you can make a selection
> > > #sel replace log air
> > 
> > 
> > Could you please explain what this does?
> 
> #help sel > shows help about selecting an area
> 
> #sel replace log air > replaces every 'log' block in area with 'air' (simply breaking every log block in area)

Hey, So i'm running into a problem. When i try the command, it says No selections. Also I do not understand how this would fix my problem because whats happening is the bot paths to some logs that the server set as unbreakable so when its broken it just instantly comes back without giving anything so the bot is stuck mining that. Could you please help me some more.

**Comment by Kromittt** [comment]
> 
> 
> > > #help sel
> > > you can make a selection
> > > #sel replace log air
> > 
> > 
> > Could you please explain what this does?
> 
> #help sel > shows help about selecting an area
> 
> #sel replace log air > replaces every 'log' block in area with 'air' (simply breaking every log block in area)

Hey, unfortunately this doesnt work, because the blocks that the bot get stuck on the server doesnt allow you to break. This means that when using that command the bot still cant break those logs, they just instantly respawn. Is there a way to ignore that area?

**Comment by alexdieu** [comment]
No you need to modify the code or to list ALL the areas that you want the bot to ignore 
So you can code the addon ! On what server are you trying that ?

**Comment by S-B99** [comment]
> Hey, unfortunately this doesnt work, because the blocks that the bot get stuck on the server doesnt allow you to break.

`#sel` the area you want to mine in. Why is this still opened. 

> Is there a way to ignore that area?

Literally `#sel` the area you want to mine in.
