### ISSUE TITLE
Runtime Remapping

### ISSUE THREAD

**Issue by frogocomics** [cabaletta/baritone#1256]
I'm using baritone-api-forge-1.2.11.jar, and I can't run it due to remapping stuff. I'm trying to make a forge mod that uses Baritone. I believe that I'm using the correct file here.

I know this might be a common issue, but I didn't see much pertaining to it. Thank you in advance.

**Comment by S-B99** [comment]
I talked to leijruv, we got stuck at notch mappings being loaded before searge mappings causing a crash. Commenting to follow any insight on this.

**Comment by 0-x-2-2** [comment]
> I talked to leijruv, we got stuck at notch mappings being loaded before searge mappings causing a crash. Commenting to follow any insight on this.

Unrelated

**Comment by 0-x-2-2** [comment]
> I'm using baritone-api-forge-1.2.11.jar, and I can't run it due to remapping stuff. I'm trying to make a forge mod that uses Baritone. I believe that I'm using the correct file here.

Read ForgeGradle documentation for this and use jitpack to get per commit builds.

**Comment by frogocomics** [comment]
I'm using jitpack now, com.github.cabaletta:baritone:1.2.11. Running it is still not working, I'm still getting problems with mappings.

**Comment by S-B99** [comment]
I'm not sure how it's unrelated as that's exactly @frogocomics issue

**Comment by 0-x-2-2** [comment]
> I'm not sure how it's unrelated as that's exactly @frogocomics issue

Runtime issue != dev env issue.

**Comment by frogocomics** [comment]
I hope I'm describing my issue clearly enough. I'm using "com.github.cabaletta:baritone:1.2.11" in my build.gradle and the forge-api version in my mods folder. I'm getting a NoSuchFieldError, which indicates that there is a mapping issue. I don't know where I went wrong.

**Comment by S-B99** [comment]
Literally my issue word for word.

**Comment by 0-x-2-2** [comment]
> I hope I'm describing my issue clearly enough. I'm using "com.github.cabaletta:baritone:1.2.11" in my build.gradle and the forge-api version in my mods folder. I'm getting a NoSuchFieldError, which indicates that there is a mapping issue. I don't know where I went wrong.

Read my reply in the forge discord to where you included it in the wrong maven section in the build .gradle.

> Literally my issue word for word.

Yeah except it is not.

**Comment by frogocomics** [comment]
I fixed it. I have no problem building, but I have problems running.

**Comment by S-B99** [comment]
Send your log?

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/73327222-18779480-4223-11ea-8d21-b63eab3c23fb.png)

**Comment by S-B99** [comment]
Nevermind, yea. I got stuck at this after adding all of it to my gradle. Probably unrelated then.
```
[22:04:40] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:04:40] [main/FATAL] [mixin]: Mixin apply failed mixins.baritone.json:MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field player was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
```
```
[22:10:52] [main/FATAL] [mixin]: Mixin apply failed mixins.baritone.json:MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field player was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field player was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
```
