### ISSUE TITLE
I am trying to run Baritone on a private server, however @mine diamond_ore doesn't start mining... it finds the ore but never starts moving what gives?

### ISSUE THREAD

**Issue by darkstar01** [cabaletta/baritone#1257]
I am trying to run Baritone on a private server, however @mine diamond_ore doesn't start mining... it finds the ore but never starts moving what gives?

I have tools in the toolbar but not sure why this isn't starting up or moving at all.

There aren't any issues with the help, etc... just when you set a goal, and then move and try to @path there it fails, also @mine seems to not want to start.

Using the latest version of Baritone/1.15.1 minecraft.

Suggestions welcomed. 'Yes I did in fact look at the forums before posting this"

Please let me know if you want any additional information.

**Comment by StijnSimons** [comment]
Baritone modified settings, please?

**Comment by darkstar01** [comment]
It doesn't matter if I reset everything or only set a few to true the
mining function just sits there and never takes off. it finds paths, etc...
like in previous versions then just sits there.

**Comment by darkstar01** [comment]
allowInventory true
allowDiagonalAscend true
allowVines true
allowParkour true
allowParkourPlace true
antiCheatCompatibility false
maxCachedWorldScanCount 100
replantNetherWart true
extendCacheOnThreshold true
breakFromAbove true
goalBreakFromAbove true
okIfWater true
legitMineIncludeDiagonals true

**Comment by S-B99** [comment]
It's `#` not `@` by default iirc

**Comment by darkstar01** [comment]
I'm running the fabric Baritone, the default for fabritone is @

**Comment by S-B99** [comment]
Fabritone is that way [HexaPL/Fabritone-fork](https://github.com/HexaPL/Fabritone-fork)

**Comment by darkstar01** [comment]
Bella, your saying that Fabritone isn't stable yet and mileage may vary? :)
I've had better success with the older versions 1.22.2 and 1.44.4. It seems
Fabritone isn't fully developed yet,

**Comment by S-B99** [comment]
I'm saying, go make an issue there, not here. This isn't fabritone.

Also, it isn't stable, look at the diffs. It's fucking hacked together until it worked

**Comment by darkstar01** [comment]
Good point, thank you for the suggestion, and your time.

**Comment by jackytuutykcaj** [comment]
https://gitlab.com/CDAGaming/fabritone
works fine for me 1.15.2

**Comment by S-B99** [comment]
That's cool and all but nobody asked. This is super off topic. This repository is for Baritone.
