### ISSUE TITLE
Is there a way to make baritone respond to someone elses commands in chat?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [cabaletta/baritone#1258]
Hello i am using baritone on a alt to do mundane tasks while i do other things. it is very annoying having to switch to a seperate minecraft client EVERY time i want to do something on the alt. And its laggy to have multiple clients open
## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
No, there is not.
