### ISSUE TITLE
Baritone struggles to place blocks

### ISSUE THREAD

**Issue by Zachattack525** [cabaletta/baritone#1261]
Often when I'm mining, when baritone attempts to place blocks, it gets stuck and requires some human assistance. This is most common when placing a block above an area the bot previously occupied.

**Comment by S-B99** [comment]
Video? This sounds like desyncing

**Comment by GiantNuker** [comment]
same issue, tried to do #sel shell and it kept getting stuck in its own holes

**Comment by VanillaDark1** [comment]
I have the same trouble. Either I have to manually have to place a block using Freecam or it places the block after struggling.

**Comment by S-B99** [comment]
That sounds exactly like desyncing

**Comment by S-B99** [comment]
Closed due to not enough information.
