### ISSUE TITLE
Help pls :c

### ISSUE THREAD

**Issue by royal141414** [cabaletta/baritone#1262]
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Intentando descargar C:\Users\Admin\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar en tarea 'Version & Libraries'... (intento 1)
Finalizó la descarga C:\Users\Admin\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar en tarea 'Version & Libraries': La suma de comprobación remota coincide con el archivo local
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Intentando descargar C:\Users\Admin\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar en tarea 'Version & Libraries'... (intento 2)
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Intentando descargar C:\Users\Admin\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar en tarea 'Version & Libraries'... (intento 3)
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Intentando descargar C:\Users\Admin\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar en tarea 'Version & Libraries'... (intento 4)
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Intentando descargar C:\Users\Admin\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar en tarea 'Version & Libraries'... (intento 5)
No se pudo descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Nos dimos por vencidos intentando descargar http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar en tarea 'Version & Libraries'
Tarea 'Version & Libraries' terminada con 1 fallo(s)!

need help on that, here is with google traductor  

Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Trying to download C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ org \ ow2 \ asm \ asm-all \ 5.0.3 \ asm-all-5.0.3.jar in 'Version & Libraries' task .. (try 1)
Download completed C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ net \ minecraft \ launchwrapper \ 1.12 \ launchwrapper-1.12.jar in task 'Version & Libraries': The remote checksum matches the local file
Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Trying to download C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ org \ ow2 \ asm \ asm-all \ 5.0.3 \ asm-all-5.0.3.jar in 'Version & Libraries' task .. (try 2)
Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Trying to download C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ org \ ow2 \ asm \ asm-all \ 5.0.3 \ asm-all-5.0.3.jar in 'Version & Libraries' task .. (try 3)
Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Trying to download C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ org \ ow2 \ asm \ asm-all \ 5.0.3 \ asm-all-5.0.3.jar in 'Version & Libraries' task .. (try 4)
Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Trying to download C: \ Users \ Admin \ AppData \ Roaming \ .minecraft \ libraries \ org \ ow2 \ asm \ asm-all \ 5.0.3 \ asm-all-5.0.3.jar in 'Version & Libraries' task .. . (try 5)
Could not download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
We gave up trying to download http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar in task 'Version & Libraries'
Task 'Version & Libraries' finished with 1 bug (s)!

**Comment by S-B99** [comment]
Your ISP or something is blocking required libraries. Try using a VPN

**Comment by Xifong** [comment]
Hi, having the same issue as well - does anyone know why version 5.0.3 isn't available with https? Will using a VPN actually allow me to reach http://repo1.maven.org/maven2/ ? Is there anywhere else (trusted to distribute these libraries) I could get the jar file?

**Comment by 0-x-2-2** [comment]
https://libraries.minecraft.net/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar

**Comment by Xifong** [comment]
Thanks
