### ISSUE TITLE
I cant use the this command

### ISSUE THREAD

**Issue by ALEXCOOLREALYT** [cabaletta/baritone#1263]
## Some information
Operating system:windows 10
Java version: Idk
Minecraft version: 1.12.2
Baritone version:4.8.3
Forge mods (if used):  jei,journey map,wall jump, baila, grappling hook 

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
When i do the command #follow entity and any entity theres an error but the command #follow entities works just fine

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce this issue
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Nice logs and title, very useful.

**Comment by ALEXCOOLREALYT** [comment]
> Nice logs and title, very useful.

Shut up

**Comment by S-B99** [comment]
Wow you really reacted to your own message to make yourself look better. Ohh yea it's big brain time
![2020-01-26-223903_397x262_scrot](https://user-images.githubusercontent.com/17222512/73148936-d1f03180-408c-11ea-9380-432efbc5a183.png)

**Comment by ALEXCOOLREALYT** [comment]
> Wow you really reacted to your own message to make yourself look better. Ohh yea it's big brain time
> ![2020-01-26-223903_397x262_scrot](https://user-images.githubusercontent.com/17222512/73148936-d1f03180-408c-11ea-9380-432efbc5a183.png)

Shut up

**Comment by S-B99** [comment]
Please read [this)](https://www.thespruce.com/social-etiquette-tips-1216646)

**Comment by ALEXCOOLREALYT** [comment]
> Please read [this](https://www.thespruce.com/social-etiquette-tips-1216646)

No u

**Comment by S-B99** [comment]
You're using it wrong

https://github.com/cabaletta/baritone/blob/master/USAGE.md#commands

**Comment by ALEXCOOLREALYT** [comment]
> You're using it wrong
> 
> https://github.com/cabaletta/baritone/blob/master/USAGE.md#commands

When I do the command it says "an unbundled exception occurred.the error is in your game's log,please report this and the link to this pahe

> You're using it wrong
> 
> https://github.com/cabaletta/baritone/blob/master/USAGE.md#commands

When I do the command it says "an unbundled exception occurred.the error is in your game's log,please report this and the link to this pahe

**Comment by S-B99** [comment]
You didn't provide the log or the command you ran.

**Comment by ALEXCOOLREALYT** [comment]
> You didn't provide the log or the command you ran.

I am phone and I dont think that I can provide the log and the command is #follow entity cow and I did write it in the post

**Comment by S-B99** [comment]
Don't create an issue if you can't even fill the issue properly. And if you read the link I sent you'd know that's not the proper syntax.

**Comment by ALEXCOOLREALYT** [comment]
> Don't create an issue if you can't even fill out the issue properly. And if you read the link I sent you'd know that's not the proper syntax.

I read it but if I write #followentity it says unknown command but in #follow entity it takes it as a command

**Comment by S-B99** [comment]
Provide the log then.

**Comment by ALEXCOOLREALYT** [comment]
> Provide the log then.
Ok just give me a second I have to transfer it from my PC to mi phone

**Comment by ZeroMemes** [comment]
A brief read of the command syntax would address the cause to your problem. This can be accessed by using `#help follow`.

![image](https://user-images.githubusercontent.com/24485393/73149965-796b6500-4089-11ea-94b8-4ec14c6a10fc.png)

**Comment by ALEXCOOLREALYT** [comment]
> A brief read of the command syntax would address the cause to your problem. This can be accessed by using `#help follow`.
> 
> ![image](https://user-images.githubusercontent.com/24485393/73149965-796b6500-4089-11ea-94b8-4ec14c6a10fc.png)

It doesn't work

**Comment by S-B99** [comment]
What doesn't work?

**Comment by ALEXCOOLREALYT** [comment]
> What doesn't work?

The command

**Comment by S-B99** [comment]
What command?

**Comment by ALEXCOOLREALYT** [comment]
> > What doesn't work?
> 
> The command



> What command?

#follow entity

**Comment by S-B99** [comment]
That's not proper syntax

**Comment by ALEXCOOLREALYT** [comment]
> That's not proper syntax

Then which is the proper syntax

**Comment by S-B99** [comment]
![image](https://user-images.githubusercontent.com/17222512/73150195-1da5d980-4093-11ea-85a4-464ca597b502.png)

**Comment by ALEXCOOLREALYT** [comment]
S-B99 it says to type #follow entity pig (example) and nothing happens

**Comment by S-B99** [comment]
Send a video of it not working.

**Comment by ALEXCOOLREALYT** [comment]
Here it is

**Comment by S-B99** [comment]
Literally, WHERE
![2020-01-26-232820_813x265_scrot](https://user-images.githubusercontent.com/17222512/73150290-a0c72f80-4093-11ea-8e44-ffbe54adfcc7.png)

**Comment by ALEXCOOLREALYT** [comment]
[Uploading 20200127_012811.mp4…]()
Here it is

**Comment by S-B99** [comment]
![2020-01-26-232952_854x242_scrot](https://user-images.githubusercontent.com/17222512/73150320-d79d4580-4093-11ea-814c-f037c8447913.png)
you commented before it was done uploading

**Comment by ALEXCOOLREALYT** [comment]
It won't upload it just disappears

**Comment by S-B99** [comment]
https://youtube.com

**Comment by ALEXCOOLREALYT** [comment]
> https://youtube.com

Can we go to discord or something to make this easier

**Comment by S-B99** [comment]
[I'm going to regret this](https://discord.gg/XDrmTf)

**Comment by ALEXCOOLREALYT** [comment]
> [I'm going to regret this](https://discord.gg/AuruW6Z)

I am done I cant talk I saw you and other people where insulting me so I left the server and  you did absolutley nothing but say to type what i was typing

**Comment by ZeroMemes** [comment]
user error
