### ISSUE TITLE
Auto avoid/attack mobs

### ISSUE THREAD

**Issue by loler08vn** [cabaletta/baritone#1265]
The problem is: when I'm trying to escape 9b9t spawn (i escaped the 2b one), the monsters spawn and attack. But the bot doesn't do anything. It's just keep walking and doesn't even care about the damage (Y' khow that newfag in 9b9t don't have anything) and then I died by 3 zombies after 7000 block away from spawn. I have waited 30 minutes to goto it, but... the zombies killed me. Please add this feature.

**Comment by S-B99** [comment]
Enable Aura in Impact.

**Comment by 0-x-2-2** [comment]
avoid
ance
