### ISSUE TITLE
Baritone + ExtraUtils crash

### ISSUE THREAD

**Issue by turret001** [cabaletta/baritone#1268]
## Some information
Operating system: Windows 10
Java version:  V8 Update 211 (build 1.8.0_211-b12)
Minecraft version: 1.12.2
Baritone version: v1.2.10
Forge mods (if used): https://rawgit.com/AllTheMods/ATM3-Remix/master/modlist.html

## Exception, error or logs
Error log paste: https://paste.ee/p/Ju7ii

## How to reproduce
This happens when I try to join a server. It doesn't always happen but most of the time it does.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by pilchard2002** [comment]
https://pastebin.com/mtF54rfd
I'll add this to the thread as I'm getting the same problem.
From what I can tell the issues is with the transfer nodes.

**Comment by CDAGaming** [comment]
Can be closed from https://github.com/cabaletta/baritone/commit/17c691b1cfa4f05e97906ff7abf64c7d1e06b692

Reopen a new issue if still present.
