### ISSUE TITLE
Auto Coarse Dirt Tiler

### ISSUE THREAD

**Issue by lostallmymoney** [cabaletta/baritone#1270]
I FUCKING HATE COARSE DIRT, please make a coarse dirt auto tiler command lol

**Comment by S-B99** [comment]
What would it do?

**Comment by lostallmymoney** [comment]
> What would it do?

Convert coarse dirt to dirt with a hoe with allowbreak as false.

**Comment by lostallmymoney** [comment]
Also the option to ignore coarse dirt with full blocks on top and destroy grass when needed as blocks on top of coarse dirt stops you from tiling it, (thanks mojang)

**Comment by S-B99** [comment]
Hold right click

**Comment by S-B99** [comment]
Or make a schematic or use the existing functions to do it...

**Comment by lostallmymoney** [comment]
Teach me pls

**Comment by S-B99** [comment]
https://github.com/cabaletta/baritone/blob/master/FEATURES.md

**Comment by lostallmymoney** [comment]
Thanks but that doesn't seem enough, I like your idea of using the existing functions tho so I'll look forward to get all the tools needed to fork baritone into a massive coarse dirt destroyer
