### ISSUE TITLE
Baritone Building doesn't work

### ISSUE THREAD

**Issue by soomX** [cabaletta/baritone#1273]
Operating system: Windows OS
Minecraft version: 1.12.2
Baritone version: 4.0

Baritone refuses to build a schematic, I have the materials and everything (survival)
![wxYAMv2](https://user-images.githubusercontent.com/59781791/73882267-5da15500-4827-11ea-9456-076c9f5c48f6.png)

**Comment by BongEatBong** [comment]
Baritone version 4.0? That doesn't seem right. Latest version of Baritone is 1.4.3 I believe. 

Schematics made on game worlds 1.12.2 and later aren't guaranteed to work iirc, so you must be 100% sure the schematic was not made from a newer Minecraft game world (1.13, 1.14, 1.15, etc.)
