### ISSUE TITLE
i dont understand how to download it fro 1.12.2

### ISSUE THREAD

**Issue by unoccupiedname** [cabaletta/baritone#1274]

**Comment by BongEatBong** [comment]
1) Download and install Forge for MC 1.12.2

2) Download this version of Baritone: https://github.com/cabaletta/baritone/releases/download/v1.2.11/baritone-standalone-forge-1.2.11.jar

3) Put baritone-standalone-forge-1.2.11.jar in the mods folder of your .Minecraft folder.

That's it. When you launch the 1.12.2 Forge install of Minecraft you created in step 1, Baritone will be installed.

**Comment by S-B99** [comment]
How can you make a GitHub issue yet be unable to go to the releases page

**Comment by VanillaDark1** [comment]
> No description provided.

You can also download it for Vanilla Minecraft. That's what I did.
