### ISSUE TITLE
Baritone crash when I launch the game

### ISSUE THREAD

**Issue by meganano202** [cabaletta/baritone#1275]
### Some information
Operating system: Windows 10 build 1903
Java version: Default Minecraft Java
Minecraft version: 1.12.2
Baritone version: 1.2.11
Forge mods (if used): Dungeons, Dragons and Space Shuttles modpack

### Exception, error or logs
[https://pastebin.com/eUiih5DH](url)

### How to reproduce
I launch the minecraft and it give me this error in the console

### Final checklist

- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
![image](https://user-images.githubusercontent.com/17461028/74196876-7dd57780-4c5e-11ea-91f1-6e8d010f002d.png)
pozzed

**Comment by l1ving** [comment]
Closed as stale. Reopen if you can still reproduce this.
