### ISSUE TITLE
Can i make multiple clients running baritone execute a command at the same time?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [cabaletta/baritone#1280]
## What do you need help with?
Can i make multiple clients running baritone execute a command at the same time?

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
What?

**Comment by S-B99** [comment]
Like literally, what? What are you trying to do?

**Comment by jpie726** [comment]
I believe they mean can you have multiple accounts running baritone and have them execute a command (mine diamond_ore) and they would all do it from one command. Is that correct @TheCrazyInsanity ?

**Comment by jpie726** [comment]
I think the best way to do that would be to setup a script to go through each window and do [button:t ; text /mine diamond_ore ; button:return]

**Comment by S-B99** [comment]
Just do [this](https://www.tecmint.com/run-commands-on-multiple-linux-servers/) and run a command to send keyboard inputs

**Comment by S-B99** [comment]
```bash
#! /bin/sh

xdotool key Return
xdotool type \#mine\ diamond_ore
xdotool key Return
```
Save this in a `.sh` file and run it over ssh to multiple machines

**Comment by TheCrazyInsanity** [comment]
> I believe they mean can you have multiple accounts running baritone and have them execute a command (#mine diamond_ore) and they would all do it from one command. Is that correct @TheCrazyInsanity ?

yes

**Comment by S-B99** [comment]
I just showed you how you could do that

**Comment by S-B99** [comment]
```bash
#!/bin/sh

wmctrl -a \"Minecraft 1.12.2\"
xdotool key Escape
xdotool key t
xdotool type \#mine\ diamond_ore
xdotool key Return
```
I added a line, this selects a window called Minecraft 1.12.2, then presses escape (for the pause menu) and then runs it.

**Comment by jpie726** [comment]
Would you have to run the script every time or could you set it up to detect a keypress? Or a command?

**Comment by S-B99** [comment]
Each time you have to run 1 command and it sends those commands to all your computers. You could have it loop and run each time you just press something instead of running the entire command

**Comment by S-B99** [comment]
Closed as resolved. If you would like a baritone feature in order to do this you can reopen it but it probably won't happen.
