### ISSUE TITLE
@mine and some other commands not working at all

### ISSUE THREAD

**Issue by Rimfire41st** [cabaletta/baritone#1284]
## Some information
Operating system: Windows 7
Java version: fabric-loader-0.7.8+build.184-1.15.2
Minecraft version: 1.15.2
Baritone version: 1.4.5
Forge mods (if used): None

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/4177294/latest.log)

## How to reproduce
Installing everything from 0, starting the game and using the @mine command

## Final checklist
- [v] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [v] I have included logs, exceptions and / or steps to reproduce the issue.
- [v] I have not used any OwO's or UwU's in this issue.

**Comment by BongEatBong** [comment]
Bruh wtf

@ is the prefix for Fabritone

Why would you expect it to work with Baritone

**Comment by S-B99** [comment]
https://gitlab.com/CDAGaming/fabritone
Fabritone is that way

**Comment by Ollincay119** [comment]
So, based on your suggestions, it should work. One problem maybe double checking the ID that you're using for it. The command should be structured 
@mine <Ore> (optionally you can add more ore variables)
Ex: @mine diamond_ore
If you got the ID wrong then here's some block ID's to get you started:
| diamond_ore | coal_ore | iron_ore | lapis_lazuli_ore | nether_quartz_ore | emerald_ore | gold_ore | redstone_ore |
I hope this helps you In some way.

**Comment by S-B99** [comment]
Please open fabritone issues in the fabritone repo, not here.

**Comment by CDAGaming** [comment]
This Issue can be closed, as the rewritten ports for fabritone are on par with the codebase for Baritone, and the commands referenced here have been verified to work.

**Comment by S-B99** [comment]
I didn't have access to close this in the first place.

@CDAGaming can you please make it clear to kids to open fabritone issues in fabritone and not baritone. It's honestly annoying.
