### ISSUE TITLE
How do I make it dig 3x3 and not fall on the lava?

### ISSUE THREAD

**Issue by Jsrom123** [cabaletta/baritone#1288]
How do I make it dig 3x3 and not fall on the lava?

**Comment by S-B99** [comment]
This is how you can tell it's gonna be a really good issue
![Screenshot_20200210-090105](https://user-images.githubusercontent.com/17222512/74156281-02cf7b00-4be4-11ea-8cda-fbd5e3380df5.png)

Uh, baritone doesn't commit suicide? Just tell it to dig a 3x3

**Comment by S-B99** [comment]
It doesn't fall into the lava.
