### ISSUE TITLE
Baritone with future for 2b2t without forge

### ISSUE THREAD

**Issue by KazzaKING** [cabaletta/baritone#1293]
I think there used to be a json designed for 1.12, but ive been trying for an hour to get stuff working but it isnt. Must be a dumbass, could someone with more braincells than me explain how i could get baritone on 1.12 without forge please?

Thanks

**Comment by KazzaKING** [comment]
oh, im a heathen and im on mac, thats probably important.

**Comment by S-B99** [comment]
I'm pretty sure this repo doesn't have one for without forge. Either way, why do you need it to not be forge?

**Comment by StijnSimons** [comment]
@KazzaKING Yeah you can just add BaritoneTweaker as a class tweaker

**Comment by Mhowser** [comment]
There is Baritone for Fabric https://gitlab.com/CDAGaming/fabritone

**Comment by S-B99** [comment]
Closed due to inactivity.
