### ISSUE TITLE
[Baritone 1.15.2 from DC] Baritone not mining honey blocks

### ISSUE THREAD

**Issue by 7-Oaks** [cabaletta/baritone#1295]
## Some information
Operating system: Linux (manjaro)
Java version: 
Minecraft version: 1.15.2
Baritone version: 1.15.2 from #announcements

## How to reproduce
Place honey block, do #mine honey_block
Google maps will try do path into the honey blocks, as it apparently does with all "mining" operations. it just stands still right while touching the block. I have no idea why its happening, the issue can not be reproduced with slime blocks, as i thought it would be caused by the properties of the block. 

I have included a streamable link of me replicating the issue. (nevermind the scuffed ratio in the first 5 seconds, i break the blocks myself eventually)
https://streamable.com/j7ulp

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Thanks! Fixed by https://github.com/cabaletta/baritone/commit/0a1fe857dceae2ef275bd8c9374a5ba65ab8c6ac

**Comment by leijurv** [comment]
and released
