### ISSUE TITLE
Why does Baritone takes a bit longer to put out fires?

### ISSUE THREAD

**Issue by VanillaDark1** [cabaletta/baritone#1296]
## What do you need help with?
Is it normal that Baritone waits a bit then puts out the fire? `.b mine fire`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
because it's calculating where the fire is in order to put it out...

**Comment by VanillaDark1** [comment]
Thanks for answering!
