### ISSUE TITLE
Stairs

### ISSUE THREAD

**Issue by creepinson** [cabaletta/baritone#1297]
## Some information
Operating system: Mac OSX High Serria
Java version: 8
Minecraft version: 1.12.2
Baritone version: v1.2.11
Forge mods (if used): 
![explorer_l6XRGEZ6AD](https://user-images.githubusercontent.com/11761863/74500362-81a20d80-4e9b-11ea-987a-3cd8ff3de02f.png)
![explorer_dedCLTgm6d](https://user-images.githubusercontent.com/11761863/74500365-823aa400-4e9b-11ea-8514-8a5ec9854fa2.png)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

- Pathfinding up stairs or using #click and clicking up stairs to go up them. 
- The bot then tries to go up one stair and then gets pushed back down and then repeats this infinitely and I have to cancel it and go up them manually. 
I use stairs in my underground base to get out easier but baritone does not go up them.

**Comment by creepinson** [comment]
Here is the link to an example video:

https://streamable.com/ufamx

There are no errors which is weird.

**Comment by creepinson** [comment]
Also, at the very bottom, it started working and then a little way up the stairs it did it again.

**Comment by S-B99** [comment]
does this happen in vanilla? and what happens if you restart it?

**Comment by creepinson** [comment]
I haven't tested vanilla, will do right now. By restart it, you mean #cancel and then doing it again? I've done that, and it starts fine and then does it again.

**Comment by S-B99** [comment]
yes, and thanks.

**Comment by S-B99** [comment]
if it starts fine then it's a path finding thing

**Comment by creepinson** [comment]
I wonder if it has anything to do with the other issue about the mod Thermal Expansion... I am using the same mods here.

**Comment by S-B99** [comment]
that's why you see if it happens on vanilla

**Comment by S-B99** [comment]
and no mods means vanilla

**Comment by creepinson** [comment]
Definitely works without other mods. Let me add the mods list to the issue.

**Comment by cookiedragon234** [comment]
Please delete the contents of your mods folder. This is inhumane.

**Comment by creepinson** [comment]
Why? I need this modpack to play on our modded server.

**Comment by S-B99** [comment]
Then figure out what mod is causing the issue. You last replied 2 weeks ago

**Comment by cookiedragon234** [comment]
If you are reporting a bug in baritone, then only use baritone to recreate the bug. As far as we know at the moment, it could be one of the two hundred mods in your mods folder causing this issue.
