### ISSUE TITLE
Doesn't work on 1.15.2? 

### ISSUE THREAD

**Issue by Lonick32** [cabaletta/baritone#1299]
So I have downloaded baritone 1.5.1 placed it in mods (I use Fabric) and it doesn't work at all

**Comment by StijnSimons** [comment]
is this the fabritone repo?

**Comment by S-B99** [comment]
mfw people don't know how to make issues in the fabritone repo

**Comment by StijnSimons** [comment]
Gitlab XDDDDDDDDDDDDDDDD
