### ISSUE TITLE
Auto farm without stepping on hoe'd dirt

### ISSUE THREAD

**Issue by bazzb** [cabaletta/baritone#1302]
Is there currently a way to auto farm without stepping on dirt?

**Comment by fw4hre0xxq** [comment]
As far as I know it doesn't matter since you can only turn farmland into dirt by jumping or landing on it.

**Comment by S-B99** [comment]
I'm pretty sure baritone doesn't purposely jump onto the farmland, like, ever.

**Comment by bazzb** [comment]
> 
> 
> I'm pretty sure baritone doesn't purposely jump onto the farmland, like, ever.

It dosent do it purposely but if its walking onto like another platform sometimes it will by accident

**Comment by S-B99** [comment]
Then this should probably a bug report, or a suggestion to improve the pathing, instead of a question.

**Comment by CDAGaming** [comment]
Couldn't this simply be avoided by just setting farmland as a blocktoavoid xD
