### ISSUE TITLE
error: package javax.xml.bind does not exist

### ISSUE THREAD

**Issue by beckadamtheinventor** [cabaletta/baritone#1303]
## Some information
Operating system: Linux Mint 19.3
Java version: 11
Minecraft version: 1.13.2
Baritone version: Any
Forge mods (if used): N/A

## Exception, error or logs
I can't build from the github source, READMEs unhelpful.
error: package javax.xml.bind does not exist

## How to reproduce
Try to build by running ``./gradlew``

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
What is the exact output of `java -version`? 
And make sure you have a java compiler installed

**Comment by S-B99** [comment]
> README unhelpful

the readme tells you to read INSTALL for building it yourself

**Comment by S-B99** [comment]
also in order to build you have to run `./gradlew build`
I missed that in my first comment.

**Comment by beckadamtheinventor** [comment]
I did `./gradlew build`
I have OpenJDK 11.

**Comment by S-B99** [comment]
Please list the full output of `java -version`.

**Comment by aUniqueUser** [comment]
[Java 11 removed the Java EE modules](https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist)

**Comment by S-B99** [comment]
I was gonna suggest to use jdk8, but I wanted to be sure they had a javac installed first.

**Comment by beckadamtheinventor** [comment]
nevermind, had to install openjdk-8-jdk, and set the java/jdk path in the gradlew file to the location of my *java 8* installation rather than the default *java 11*
But now the task `:proguard` failed.

**Comment by S-B99** [comment]
With what error?

**Comment by beckadamtheinventor** [comment]
1

**Comment by S-B99** [comment]
Post the full error log.

**Comment by beckadamtheinventor** [comment]
I think I forgot to run `./gradlew setupDecompWorkspace`, so I'm doing that now

**Comment by beckadamtheinventor** [comment]
That succeeded

**Comment by beckadamtheinventor** [comment]
``> Task :proguard FAILED
Task ':proguard' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Running Determinizer
 Input path: /home/adam/Desktop/baritone/build/libs/baritone-1.2.11.jar
 Output path: /home/adam/Desktop/baritone/build/libs/baritone-unoptimized-1.2.11.jar
:proguard (Thread[Task worker for ':',5,main]) completed. Took 0.224 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proguard'.
> 1
``

**Comment by aUniqueUser** [comment]
I have this same error when building on Linux, but it builds fine on Windows.

**Comment by S-B99** [comment]
Works on Linux for me. Make sure you're using Oracle JDK 8 which is what I'm testing on.

**Comment by aUniqueUser** [comment]
@S-B99 Thanks, this fixed it.

**Comment by S-B99** [comment]
Resolved.
