### ISSUE TITLE
1.15 won'2 build schematic

### ISSUE THREAD

**Issue by martfoss04** [cabaletta/baritone#1309]
## Some information
Operating system:
windows 10
Java version:
build 1.8.0_241-b07)
Minecraft version:
1.15.2
Baritone version:
1.15.2-Baritone
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/4227700/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

schematics i'we tried:

[schematics.zip](https://github.com/cabaletta/baritone/files/4227727/schematics.zip)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Have problems building and loading schematics. Starts breaking blocks, but then it stops..
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
`[23:04:29] [main/INFO]: [STDERR]: java.io.FileNotFoundException: C:\Users\martf\AppData\Roaming\.minecraft\schematics\redemeer.schematic (The system cannot find the file specified)`

What command did you run, and make sure the name is correct and the schematic is in that folder
