### ISSUE TITLE
How to feed commands to baritone from an external Neural network?

### ISSUE THREAD

**Issue by darkstar01** [cabaletta/baritone#1310]
How would I go about feeding commands from an external neural network?  I know of a few people like the guy over at chaoscraft who is using a distributed network, and SQL to store data from each of the neural networks. Any suggestions are welcome.

**Comment by S-B99** [comment]
See the conversation in #1280

**Comment by S-B99** [comment]
Or you could write a mod that can take input from SSH that interacts with baritone's API, which would be more reliable

**Comment by ZeroMemes** [comment]
A layer would have to be established which is able to interpret neural network outputs into appropriate Baritone commands. That’s not something that contributors or maintainers here are going to help with.

**Comment by darkstar01** [comment]
Brady,

Not like i'm asking someone to make it for me, i was asking if there was a
way to issue commands externally rather than internally from the minecraft
client.  I have some experience with neural networks and wanted to
contribute to Baritone, the idea was to use Baritone as a set of neurons
(base data) and then use genetic learning algorithms to give the bot
learning, and possibly teach the neural network crafting. Using something
like JCUDA it may be possible to accelerate the AI using an extra video
card. (But these are only ideas atm, no clue if the JCUDA is possible.)

**Comment by S-B99** [comment]
there is, the baritone API exists. read the docs.
