### ISSUE TITLE
Player like AI no input needed and survival aspect

### ISSUE THREAD

**Issue by PlushBanshee** [cabaletta/baritone#1313]
× Have a option for Baritone to act more like a player and be able to build, craft, attack, ect, without having the programmer typing to much input from a little of only having to type the on command

× So Baritone is a path finding bot i know, but what if we allow a survival plugin that allows the AI to craft a work bench and stuff theres two ways for this

1. The player says get me iron but also allows to AI to make a furnace and work bench to make new pickaxes to mine iron and smelt them in a furnace heck even allow it to get coal to use a fual
2. Allow the bot to run without any human input, have a command call (.b survive) and let the bot randomly build schematics from a schematic folder. mine the resources and fight mobs (not players i have no idea if thats an idea yet) i found some AI that can do some of these things like crafting and what not
(https://github.com/PrismarineJS/mineflayer/blob/master/docs/README.md)

× have a custom command (.b survive) still have the classic code but also have a sister code that allows <autonomy> think of like the sims

× how can this help well heres some pointers
1. Your lonely and have no friends so having this makes you feel like you have people playing on your wannabe server
2. Helps improves player reaction time and reflexes, having an AI that can do what a player can makes it fun i have messed with full automatic bots in games before yer fighting PvP you cant think what the player is doing makes it hard but fighting a AI you have to think faster then it be wise with what your doing think of intense training it could help you improve your PvP skills
3. The bot dosnt need to attack players what if the bot did mob farming for you and then placed the stuff in storage for you no more making mob farms having the bot to do it for you will be a breeze theres a farming command what about farm a mob like (.b mobfarm creeper) them only walks around to kill creepers
4. Making a minecraft movie on your trashy youtube but have no friends to act as busy on your fake server or wgat about playing survival games but with the AI lead up survival games map 2 plop some bots in there play in survival mode so you can brake blocks and scream for help this idea was from when i played survival games with epic siege and another mod i cant remember but the zombies where building, burning, creepers exploding, skeletons with swords

× This is all an idea and would love to see it added one day i will be happy to wait but this is only an idea if theres an easier way to explain this or have commands for these actions im happy to hear some polishing comments and thank you for reading

**Comment by S-B99** [comment]
This is way out of scope for what baritone is meant for honestly. Please see the other issues discussing a 'full' AI in this repo.

**Comment by S-B99** [comment]
If you would like smaller specific features added that aren't as out of scope please update the issue with that or make a new one.
