### ISSUE TITLE
Unhandled exception when trying to follow entity

### ISSUE THREAD

**Issue by opticnexus** [cabaletta/baritone#1316]
## Some information
Operating system: Windows 10
Java version:
Minecraft version: 1.12.2
Baritone version: 1.2.10
Forge mods (if used): WWE Client, ClientCommands, Baritone, Osiris Client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[2020-02-21-2.log.gz](https://github.com/cabaletta/baritone/files/4237019/2020-02-21-2.log.gz)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Try to follow entity, happens again

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
What command did you run?

**Comment by opticnexus** [comment]
followentity

**Comment by S-B99** [comment]
That's not the proper syntax for the follow entity command. Please run `#help follow` or go to the follow documentation here: https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/command/defaults/FollowCommand.java#L129
