### ISSUE TITLE
How do I change the distance baritone thinks it can "Reach"

### ISSUE THREAD

**Issue by Jacob345k** [cabaletta/baritone#1317]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
So the server i play on is a bit gay and turned down default reach, not a problem unless i do sel replace or cleararea type stuff. how would i set my reach distance to 3?
## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
The [blockReachDistance](https://baritone.leijurv.com/baritone/api/Settings.html#blockReachDistance) setting.

**Comment by Jacob345k** [comment]
https://i.imgur.com/RomlX8O.png

**Comment by Jacob345k** [comment]
it says command not found

**Comment by TheK0tYaRa** [comment]
Try #set blockReachDistance <number>

**Comment by Jacob345k** [comment]
says error at argument#1: Expected a valid setting

**Comment by S-B99** [comment]
You didn't enter a valid number.

**Comment by Jacob345k** [comment]
is 3 not a valid number

**Comment by Jacob345k** [comment]
https://i.imgur.com/7dubbb5.png

**Comment by Jacob345k** [comment]
https://i.imgur.com/cxMUKvk.png

**Comment by S-B99** [comment]
:man_shrugging:

**Comment by HyCore** [comment]
still not working. it's would be nice to get something like that: #set blockReachDistance 3

**Comment by dominikaaaa** [comment]
do `#blockReachDistance 3`

**Comment by dominikaaaa** [comment]
it's documented in the javadocs https://baritone.leijurv.com/baritone/api/Settings.html#blockReachDistance

# ♿♿♿♿
