### ISSUE TITLE
Y level

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1318]
What is Y level in legit mining ? What does it changes ?
And i suggest that the "non legit mode" switch to "legit mode" just to move a bit and search for to pass in "non legit mode" as soon as possible, instead of just poweroff if there's no ores

With non legit the bot can't run for more than 3 minutes without stopping, with legit mode the player just walk around non efficiently

So you can insert a little of legit mode in non legit mode, to discover new places where pathfind, and let the legit mode as is (obviously if we run in legit, it should NEVER switches to non legit)

**Comment by S-B99** [comment]
> And i suggest that the "non legit mode" switch to "legit mode" just to move a bit and search for to pass in "non legit mode" as soon as possible, instead of just poweroff if there's no ores

That's just using non legit mode

> With non legit the bot can't run for more than 3 minutes without stopping, with legit mode the player just walk around non efficiently

Then there aren't any ores

> What is Y level in legit mining ? What does it changes ?

It changes the Y level it looks at

**Comment by S-B99** [comment]
https://baritone.leijurv.com/baritone/api/Settings.html#legitMineYLevel

It's like, right there. In the docs.
