### ISSUE TITLE
Don't closing issue before the author tells that the question is resolved

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1319]
It's a good suggestion

Isn't it ???

Anyway, i've asked a question like 5 minutes ago and the helper hasn't replied to any question and just ignore my suggestion and replies totally widely

So ! What actually is Y level ? What do he do if we modifies it ?

And I suggest a second time that the non legit mode should turn to legit mode in order to MOVE, to CHANGE PLACE, to search for ores that he doesn't find in the first place. Because it's what i do manually, because like i said, the bot automatically turns off and don't just like move a bit to make minecraft loading new ores

And don't close this one please..

**Comment by S-B99** [comment]
Please refer to #1318 

I answered all of your questions and linked the docs. 

And, in addition to this issue being a question, and the other one, not a suggestion, that's just using legit mode. It turns off because there are no ores it can find.
