### ISSUE TITLE
Hybrid legit mode

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1320]
I ask for a whole new mine mode because the other one will close the issue otherwise

So ! Not modifying the 2 acutals existing mode, no, you can't close this issue because it's not "just non legit mining mode", no it isn't, i ask for a whole new mode

Hope that you will listen : Okay, the bot turn off because he doesn't find ores, FINE. I'm okay with that, lets let that like that

Now ! A hybrid mode should help using both mode : He begin with turning "non legit mode" on. If he doesn't find anything, he goes into "legit mine mode" in order to MOVE and so minecraft can load new chunks, now biomes, new blocks, new places, NEW ORES.

So, the legit mining do hes stuff, but in background, baritone checks periodically for the targeted ore. If he find it, he turn into "non legit mining mode", so he can go reach him. If he doesn't find it, he just let the control to "legit mode" and will retry in a couple of seconds/minutes/whatever

No this mode doesn't exist, no it's not just "normal", it's a real suggestion that doesnt exists on Baritone and who should be cool to implement (so to CONSIDER the suggestion and not just closing it)

Thanks you for your intention :boom:

**Comment by S-B99** [comment]
https://baritone.leijurv.com/baritone/api/Settings.html#exploreForBlocks
https://baritone.leijurv.com/baritone/api/Settings.html#exploreMaintainY
