### ISSUE TITLE
5th reply of the eternal auto-closing issue "exploreForBlocks"

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1321]
You definitively making fun of me

You just completly throw off my suggestion to turn on by default an option

AND, the alternative that you suggest me doesn't work. https://baritone.leijurv.com/baritone/api/Settings.html#exploreForBlocks is already turned on by default and the bot STILLS turn off if he doesn't find ores, instead of like EXPLOREFORBLOCKS

Whats your suggestion ? (instead of just closing the issue without verifying if the issue is actually resolved in the first place and results with 5+ issue of the same problem i mean)

**Comment by S-B99** [comment]
> suggestion to turn on by default an option

> is already turned on by default 

Which is it?

Please enable exploreForBlocks. Also you can continue replying to an issue after it has been created, I asked you to stop making new ones.

**Comment by bphd** [comment]
You
making
fun
of
me

Definitively

Why you don't listen

What the actual fuck

> AND, the alternative that you suggest me doesn't work.

Can you even READ ?

**Comment by S-B99** [comment]
You didn't even follow it. 

Please read this.
![Screenshot_20200222_141051](https://user-images.githubusercontent.com/17222512/75097843-42e81380-557d-11ea-8d62-b2896b557633.png)

 Also where did I say I was making fun of you. If you have to defend something like that then you're most likely very young or immature.

**Comment by bphd** [comment]
> exploreForBlocks is already turned on by default and the bot STILLS turn off if he doesn't find ores, instead of like EXPLOREFORBLOCKS

What the fuck ????

**Comment by S-B99** [comment]
It is not enabled then.

**Comment by bphd** [comment]
Yes it is

**Comment by S-B99** [comment]
Please provide proof that it is.

**Comment by bphd** [comment]
You really want a screenshot of "[Baritone] Old value: true" ? You kidding me right ?

**Comment by S-B99** [comment]
Yes.

**Comment by S-B99** [comment]
And proof that exploring isn't working.

**Comment by bphd** [comment]
That will be difficult because it just outputs me the message that he doesn't find ores and don't move, how i make a proof otherwise ?

**Comment by S-B99** [comment]
Send a video of you turning on the option and it trying to explore.

**Comment by bphd** [comment]
And what element of troubleshooting this will add ? Gimme an exemple

**Comment by S-B99** [comment]
What?

**Comment by bphd** [comment]
In order to correct the problem you need element of troubleshooting. And in this context, what this video will get you ? I already tells what it outputs. What a picture of the same message will get ? Isn't it just bad faith ?

**Comment by S-B99** [comment]
It will show the issue that is happening.

**Comment by bphd** [comment]
Yeah okay, and about the troubleshooting ? you willnt get new logs, new error, just a footing of a steve failing to reach ores, what a novel

**Comment by S-B99** [comment]
I need a video of it not working.

**Comment by bphd** [comment]
You actually NEED it, wow, okay, hold on

**Comment by S-B99** [comment]
I wouldn't have asked otherwise.

**Comment by bphd** [comment]
Here you are big boy https://streamable.com/4n5e4

**Comment by S-B99** [comment]
There's no diamonds for it to mine then.

**Comment by bphd** [comment]
Whats the WHOLE point of this topic ? Try to remember

**Comment by S-B99** [comment]
Doesn't seem like ti
![Screenshot_20200222_164221](https://user-images.githubusercontent.com/17222512/75099668-4df96e80-5592-11ea-8562-089eb631a009.png)

**Comment by S-B99** [comment]
Is the title even english?

**Comment by bphd** [comment]
I repeat the scenario

I ask to enhance "non legit mining"
You reply that I can manually enhance it
I ask for a new mode who integrate this enhancement
You still reply the same
I try to enhance manually following your instruction
It doesn't work, it don't explore to generate new chunks, new ores
I tell you that it doesn't explore, considering that the good option is activated
You reply "it doesn't see new ores"

You're a bot or a comic ?

**Comment by S-B99** [comment]
You know https://translate.google.com would probably give me a more comprehensible reply.

There isn't anywhere to explore because there's no ores to find. It's probably cached the chunks and already knows there's no diamond ore.

**Comment by bphd** [comment]
Look, the minecraft client doesn't know all the chunks. I know it because MYSELF i move manually and reactivate the "non legit mining" bot and he find ores

SO, i search for a way for the bot to do that automatically

It seems that the "legit mode" is perfect for walking, but he wasting a lot of time and ressources

SO, i want the bot to go to "legit mode" the time to find new ore with his scan

You get it or you need a Google Translate Human > Monkey ?

**Comment by S-B99** [comment]
Oh. So you had legit mode on. So disable legit mode.

**Comment by bphd** [comment]
Please go view a new time the video and go repeat a new time that "you had legit mode on"

**Comment by disp3874** [comment]
Jesus christ, get your shit together @bphd!

You do realize that we obviously have a communication problem here, right? Use Google Translate because WE - DO - NOT - UNDERSTAND - YOU and your English skills are absolute garbage.

> I really want to punch you now, you're the king of avoidance

Honestly, everyone in this conversation wants to punch you in the face for opening several issues nobody understands and on top of that has the incorrect format! You didn't even read the fucking requirements to open an issue, don't complain when your issues get rejected.

> You closing it like to say "it's not software related, the problem is the user", and at each replies you redirect the problem to me, you never listen to me, you never understand that the software lacks a function, a funtion to avoid the auto deactivation of the bot, for him to continues the search without human interaction, you indefinitely avoid the real concern.

Well guess what? Did you ever evaluate yourself against other people speaking/writing English? No? Then don't complain when nobody deciphers what the fuck you wrote.

> What type of people you are in the real life?

We could be suicidal and thinking about committing suicide because of your stupidity.

> It's more 6 opened issues about your social problems than the Baritone problem

Sorry mate, you got that wrong. Those 6 issues are _your_ social problems.

Sorry @S-B99 but I can't take this shit. My principles include that you've to earn your respect and this dude earned himself a negative score. I don't care about a person when that person is a moron.
