### ISSUE TITLE
Can't mine andesite

### ISSUE THREAD

**Issue by dragonworm** [cabaletta/baritone#1323]
## Some information
Operating system: Windows 10 
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.11
Forge mods (if used): impact and future

## Exception, error or logs
Baritone will not recognize andesite, diorite, or granite as a black and won't mine it.
#Error at argument #1: Expected ForOptionalBlockMeta

## How to reproduce
try #mine andesite, or #b mine andesite, or any of the counterparts on impact

## Final checklist
- [x] I know how to properly use check boxes 
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ X] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
In 1.12.2 granite and the such are still called stone in the code, they have block data values. Please use `#mine stone:5` and so on, as per https://minecraft.gamepedia.com/Andesite#Data_values

**Comment by S-B99** [comment]
![Screenshot_20200222_162454](https://user-images.githubusercontent.com/17222512/75099455-dd515280-558f-11ea-89cb-662e9be923c6.png)
Also how did you manage to fuck that up
