### ISSUE TITLE
I am new to this and dont know how to install baritone 1.5.1 vanilla

### ISSUE THREAD

**Issue by PortalFan202** [cabaletta/baritone#1329]
## What do you need help with?
I dont know any programing and I am really confused. After I download the standalone .jar what should I do to make it into a version?, kind of like the 1.14.4 build wich was only drag and use. Thank you very much in advance, i really want to real uwu.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
1.15.2 is json. Move it to versions or use donator impact client.

**Comment by PortalFan202** [comment]
i did not understand at all, sorry

**Comment by S-B99** [comment]
If you don't know how to use a custom version then just wait for official impact 1.15 release or donate

**Comment by leijurv** [comment]
click the link in the main readme for 1.15.2 json just like 1.14.4

**Comment by S-B99** [comment]
i thought i linked it frick :flushed:
