### ISSUE TITLE
Errors upon running gradle project

### ISSUE THREAD

**Issue by marketingmark** [cabaletta/baritone#1330]
## What do you need help with?
This issue might be dumb as fuck, but it's been a while since I've used IntelliJ/gradle (maybe even Java in general) so I am in need of advice. 

I was trying to play around with the code a little to see if I can modify some functions within the build section in order to incorporate directional block placement. (relating to my previous Issues, of course)

I have followed the IntelliJ setup guide, and everything seemed to work as intended, including the setupDecompWorkspace and genIntellijRuns tasks. However, when trying to run the Minecraft Client configuration (With "Use classpath of module: baritone_launch"), I get the following errors:

![image](https://user-images.githubusercontent.com/50582661/75209556-d3da0d00-577e-11ea-84c8-6ba6763c8071.png)

The error seems to relate to the schematica packages rather than the baritone files themselves. Have I overlooked something with the dependencies or have I made some other mistake/problem with IntelliJ?

Otherwise I'll probably realise what stupid thing I have done wrong myself tomorrow-ish. 

Thanks in advance for any help provided (:

**Comment by marketingmark** [comment]
As of yet still no progress, still open to new input

**Comment by S-B99** [comment]
I'm going to be setting up a workspace later so I'll tell you if I have any issues

**Comment by marketingmark** [comment]
Any updates? I tried quite a couple of things now without success.

**Comment by S-B99** [comment]
Oh sorry, I got caught up with something. I'm completely free today so I'll do it in about half an hour.

**Comment by marketingmark** [comment]
Don't worry about it, I'm not in a hurry, take your time. I was just hoping to have a look somewhere later this weekend.

**Comment by marketingmark** [comment]
Did you have any problems setting up a workspace? At this point I've tried everything I could find without success.

**Comment by S-B99** [comment]
No, I've been busy. I'll try today.

**Comment by marketingmark** [comment]
Well nevermind. I moved the project to my main drive rather than my D drive, that seemed to fix the problem :)
