### ISSUE TITLE
Can't sprint by using the bind after pausing a task, but double tapping forward to sprint works

### ISSUE THREAD

**Issue by thegamerx1** [cabaletta/baritone#1331]
https://github.com/ImpactDevelopment/ImpactIssues/issues/2017

## Final checklist
- [No] I know how to properly use check boxes 
- [idk] I have included the version of Minecraft I'm running, baritone's version and forge _ᵁʷᵁ_ (if used).
- [I DONT KNOW] I have included logs, exceptions and / or steps to reproduce the issue.
- [yeeeeeeeeeeeeeeeee] I have used any ~~OwO~~'s or ~~UwU~~'s in this issue.

**Comment by S-B99** [comment]
Please fill out the issue template properly.

**Comment by thegamerx1** [comment]
again no pls

**Comment by thegamerx1** [comment]
every info that is asked
is in the issue that i mentioned

**Comment by S-B99** [comment]
This is the example baritone bug report template

```
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
```

**Comment by thegamerx1** [comment]
logs are not needed java isnt the problem baritone version should be the one that is on impact 4.8.3 steps are on the issue mentioned

**Comment by thegamerx1** [comment]
you arent even testing it, you are annoying me closing every single issue asking for the template when it isnt needed because the issue is fucking clear

**Comment by S-B99** [comment]
No, I asked you to properly fill out the template because I can't reproduce this issue, it works for me.

Forge 1.12.2, Arch Linux 5.5.2.

**Comment by thegamerx1** [comment]
maybe use 1.14.4?

**Comment by S-B99** [comment]
Thank you for filling out the issue template properly.

**Comment by thegamerx1** [comment]
as i said its on the issue that i mentioned..

**Comment by S-B99** [comment]
Not here. Testing 1.14.4 now.

**Comment by S-B99** [comment]
I can't reproduce this on 1.14.4 either.

**Comment by thegamerx1** [comment]
https://youtu.be/2D1nsmd5cEU

**Comment by aUniqueUser** [comment]
@thegamerx1 Do you have `#allowSprint` off?

**Comment by S-B99** [comment]
mfw

**Comment by thegamerx1** [comment]
> 
> 
> @thegamerx1 Do you have `#allowSprint` off?

![image](https://user-images.githubusercontent.com/34986564/75289560-d55b1200-581e-11ea-896b-2dca7adec431.png)

**Comment by S-B99** [comment]
Huh. I can reproduce this, though I can still double tap w to start sprinting.

**Comment by S-B99** [comment]
Could you please change the title to `Can't sprint by using the bind after pausing a task, but double tapping forward to sprint works` please

**Comment by S-B99** [comment]
https://.youtube.com/vFzNdhwau-k/
