### ISSUE TITLE
Able to set multiple identical waypoints but can't delete any

### ISSUE THREAD

**Issue by HexCodeFFF** [cabaletta/baritone#1333]
## Some information
Operating system: Windows 10 64bit
Java version: (build 1.8.0_241-b07)
Minecraft version: Impact 1.15.2
Baritone version: 1.5.1
Forge mods (if used): no

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1. set multiple waypoints with the same name (I used `#wp save user testd` twice)
2. try to delete them (`#wp delete user testd`)
3. Baritone says `Multiple waypoints were found:` and lists the 2 identical waypoints

maybe add an option to delete waypoint #n on a page or give each waypoint a unique ID that is displayed and be able to delete by that idk

this also means doing `#sethome` twice breaks that command entirely without names

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Delete it from the config file and don't set waypoints with the same name lol.

It's like saying "join my server" lol. Like, which server

**Comment by HexCodeFFF** [comment]
Right I get it can't figure out which one i want it to go to but i shouldnt have the option to save multiple duplicate waypoints if it doesnt work

**Comment by S-B99** [comment]
It has coordinates, right lol?

Why the fuck would you name all your waypoints the same thing in the first place, how did you want to use them? Like, you realize you're just asking for a feature to name them different 2 things right?

**Comment by S-B99** [comment]
Accidentally closed.

**Comment by S-B99** [comment]
This is a valid bug report but like, don't be retarded and name your waypoints all the same thing.

**Comment by HexCodeFFF** [comment]
I thought that if i did `#sethome` a second time it would override the first home or not let me set the home

**Comment by S-B99** [comment]
That's a valid bug report. Guess it doesn't do so.

**Comment by dankmolot** [comment]
Just click on the waypoint that you want to delete in the list

**Comment by S-B99** [comment]
That works
