### ISSUE TITLE
How do you intercept chat? Need to stop all chat but let baritone still work

### ISSUE THREAD

**Issue by TheUnderTaker11** [cabaletta/baritone#1335]
## What do you need help with?
I am trying to make a forge mod to disable all chat from being sent to the server. (But still allow baritone to work) I tried making a ClientChatEvent, setting it to lowest priority, then just canceling it. However it seems you don't use this method because baritone doesn't work when I do that.

I just really want to stop any possibility of accidentally sending my coords to the server again...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Uh, you can't really send your coords unless you forget the baritone prefix. 

Though I would be interested in this as well, as I asked leijurv the other day

**Comment by TheUnderTaker11** [comment]
I use macros to do my stuff, so it is very easy to accidently try and move at the wrong time, causing it to send w#goto blah

**Comment by TheUnderTaker11** [comment]
I could probably do it myself in a separate mod, I just need to know where/how baritone intercepts it to see if I can work around that and stop it after that.

**Comment by alexdieu** [comment]
You can with artoisis and Fabritone !
https://aristois.net/
then when you install it go in a solo world click pause (escape by default) then click addons and install Fabritone ! It the same just the commands are @mine diamond_ore 
In the cheats you can hide chat ! And IRC chat which is added by Artoisis !

**Comment by S-B99** [comment]
Hi, this is not the fabritone repo. Please stop posting fabritone here, as fabritone is not baritone. They asked for help with baritone. 

That's just avoiding the requested solution, and it doesn't really help anybody by switching to a different mod.

**Comment by cancerousname69** [comment]
Just cancel all C01PacketChatMessage packets, and you should be fine.
