### ISSUE TITLE
Trapped Chests make baritone freak out

### ISSUE THREAD

**Issue by fw4hre0xxq** [cabaletta/baritone#1339]
## Some information
Operating system: Win 10 x64
Java version: Bundled with vanilla launcher
Minecraft version: 1.12.2
Baritone version:  1.2.11
Forge mods (if used):  I tested without Forge mods

## How to reproduce
When setting a goto command to the block above a trapped chest, baritone freaks out, sometimes giving up, and sometimes even trying to break the trapped chest.

To reproduce, place down a trapped double chest, and note its coordinates. Then issue a #goto command to the coordinates directly above the chest. e.g. if the chest is at 100, 64, 100, issue the #goto command for 100, 65,100. Observe the freak out. This behavior does not happen with normal chests. With normal chests, Baritone will simply jump onto the chest.

I think this could be related to #1099 

I plan to make a PR to fix this. This is just to document in case I don't do that/if someone is using and old version and encounters this, for general completeness, etc.

I think this 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
^ OwO what's this? this sentence means that the box can never be checked without modifying the checklist.（=｀ェ´=）

**Comment by S-B99** [comment]
Does this happen with normal chests as well?

**Comment by fw4hre0xxq** [comment]
> This behavior does not happen with normal chests. With normal chests, Baritone will simply jump onto the chest.

@S-B99

**Comment by S-B99** [comment]
That's a feature, not a bug.

**Comment by fw4hre0xxq** [comment]
Why is this a feature? As far as I know trap chests aren't activated by standing on them, and they have the same shape as regular chests.

**Comment by S-B99** [comment]
It's a joke xd

**Comment by fw4hre0xxq** [comment]
Well thank you very much Poe's law. Should I put the PR in?

-------- Original Message --------

**Comment by S-B99** [comment]
Yes. <3 thanks
