### ISSUE TITLE
Legit mine, infinite loop

### ISSUE THREAD

**Issue by niggish** [cabaletta/baritone#1341]
## Some information
Operating system: Windows 10, 64-bit
Java version: Java version 8, update 211
Minecraft version: 1.12.2
Baritone version: v1.2.11

**Describe the bug**
Legit mine has an infinite loop in this scenario on hypixel for some reason.

**Watch for yourself**
https://streamable.com/oyrbc
/////////////
https://streamable.com/30r40
/////////////
https://streamable.com/pfjaz
```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.12.2 nightly-20200226
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: Auto mine(coal; legit), auto eat, auto tool, inventory, auto cheat, antibot, no push, sprint
- Operating System: Windows 10, 64 bit

**Comment by S-B99** [comment]
The bedrock there disappears and reappears. Baritone doesn't want to mine the ore from the side, it likely wants to stand there. You can't really report super specific pathing bugs here, it's too general.
