### ISSUE TITLE
how to download baritone as a mod for 1.12.2 ?

### ISSUE THREAD

**Issue by tuctor1234** [cabaletta/baritone#1343]
I would like to play Minecraft 1.12.2 baritone with other mods so I can't use Impact.
It would be great if someone could tell me if there is a way to play baritone as a 1.12.2 mod with Forge.
I have been searching the Internet but haven't found anything.

**Comment by Darkmindmc** [comment]
Im having the same issue with Future client. I have future installed on forge 1.12.2 and I've placed the baritone-forge-standalone jar into the mods folder but still nothing.

**Comment by Darkmindmc** [comment]
I've resolved my issue.
Have you tried typing these in chat?

#goal 0 0 2000
#path

**Comment by S-B99** [comment]
>  I have been searching the Internet but haven't found anything.

how the fuck did you find this

holy shit

# this is where you download it 

## you go here: 
 
(click the word **baritone**)

![2020-02-28-150626_234x63_scrot](https://user-images.githubusercontent.com/17222512/75583581-e6349f00-5a3b-11ea-8996-367a0a1d183f.png)

## then you go here 

((make sure you're using the **left** mouse button on your mouse, not the right one!!)

![2020-02-28-150654_189x106_scrot](https://user-images.githubusercontent.com/17222512/75583615-f8164200-5a3b-11ea-9fb8-2902f957aeaf.png)

### scroll down to the last supported forge 1.12.2 version

![2020-02-28-150730_563x265_scrot](https://user-images.githubusercontent.com/17222512/75583686-17ad6a80-5a3c-11ea-958e-4c8d5a69dda9.png)

**make sure to remember to press "Assets" first**


### then press this file

![2020-02-28-150821_364x61_scrot](https://user-images.githubusercontent.com/17222512/75583720-2dbb2b00-5a3c-11ea-818a-a1c2ddc8986a.png)

then you want to drag and drop the jar file from your downloads folder **to** your forge mods folder.

**Comment by elan69** [comment]
lmao

**Comment by ImMale** [comment]
Bruh it still doesnt work. I installed the jar file but the prefix # and .b just doesnt work. Baritone doesnt even show in forge mod list.w

**Comment by ImMale** [comment]
Found a solution. Some of these mods (ChunkAnimator-MC1.12-1.2, creepy-salhack-2.08, foamfix-0.10.11-1.12.2, InGameAccountSwitcher-1.12.2-7.0.5, OptiFine_1.12.2_HD_U_E3, Surge-1.12.2-2.0.77, VanillaFix-1.0.10-99, WurstPlusTwo) were conflicting with baritone. I think it is Salhack or wurst but i am not sure.

**Comment by OscarFan26** [comment]
lmao holy shxt why would u ask questions like that?
