### ISSUE TITLE
Make notification system more useful and configurable

### ISSUE THREAD

**Issue by dominikaaaa** [cabaletta/baritone#1345]
## Describe your suggestion
As it's crossplatform it would be nice to have notifications for simple events such as completing a destination, instead of just failed pathing, or if it has issues finding ores to mine and just stops.

## Settings
sendNotification <events on/off>

## Context
It makes the added notification system more useful and lets people just tab out of baritone. 

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
leij daddy pwease don't hurt me I wrote this on mobile I'll fill out a real issue template tomorrow but I have to sleep

**Comment by S-B99** [comment]
done c:

**Comment by aUniqueUser** [comment]
Working on this rn

**Comment by foxxd** [comment]
it would be nice if baritone make sounds when a task gets done

**Comment by S-B99** [comment]
See #1179 for that
