### ISSUE TITLE
Used click command and accidentally selected some blocks. How do i remove this selection.

### ISSUE THREAD

**Issue by salvo7-arch** [cabaletta/baritone#1350]
## Some information
Operating system: Windows
Java version:
Minecraft version: 15.2
Baritone version: 15.2
Forge mods (if used):  None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Please fill out the issue template correctly.

**Comment by S-B99** [comment]
`#sel clear`
