### ISSUE TITLE
Is there anyway I can make a large underground clearing?

### ISSUE THREAD

**Issue by salvo7-arch** [cabaletta/baritone#1351]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
`#sel`

**Comment by S-B99** [comment]
Please read this before asking another question. https://github.com/cabaletta/baritone/blob/master/USAGE.md
