### ISSUE TITLE
Will building function be back on 1.13 - 1.15?

### ISSUE THREAD

**Issue by smalhoi** [cabaletta/baritone#1352]
It is a good function in baritone, will it be support on 1.13+ minecraft later?
Is there any donation to the developer for updating the api?

**Comment by S-B99** [comment]
Their bitcoin address is `1Leijurv3DWTrGAfmmiTphjhXLvQiHg7K2` for donations. 

1.13 will not be supported as hardly any servers run on it, and 1.14.4 / 1.15.2 versions are released. 

Building does work. Do `#help build` or `#help schematic`
