### ISSUE TITLE
Inverted BuildInLayers for #sel ca

### ISSUE THREAD

**Issue by Nfuf15** [cabaletta/baritone#1353]
## Describe your suggestion
When clearing out a space it would be nice if baritone mines out layer by layer from top to bottom instead of bottom to top.

## Settings
The Setting could be #InvertBuildInLayers (Boolean)

## Context
This would be very useful for mining out huge and deep holes with #sel ca in an organized layered fashion, improving excavating and making baritone look more legal on servers.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
This setting already exists.

https://baritone.leijurv.com/baritone/api/Settings.html#layerOrder
