### ISSUE TITLE
When pathing/tunneling/mining Don't break tools

### ISSUE THREAD

**Issue by Nfuf15** [cabaletta/baritone#1354]
## Describe your suggestion
If there are multiple pickaxes or other tools in the players inventory Baritone won't use the tool until it breaks and will switch tools at around 50 durability left.

## Settings
#DontBreakTools (Boolean) 
and or
#SwapTools (Boolean)

## Context
This is very useful for when the user may want to have baritone mine for extended periods of time and or excavate huge areas without breaking their precious tools.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by aUniqueUser** [comment]
Sounds like a good idea, will work on tomorow if I have time.

**Comment by RealIndrit** [comment]
My tip would be to just add it to the current “getbesttoolslot” In ToolSet.java where you add  “prioritize durability“ as a setting such as “prefer silk touch“ is, can add this to fabritone  too, caus after all it will be needed in the future...

**Comment by cbrady350** [comment]
Would still very much like to see this addition! @aUniqueUser any update?!

**Comment by Titaniumtown** [comment]
bump, any progress on this? This would be amazing to have.

**Comment by scorbett123** [comment]
This is done, a pull has been made, however it is now waiting for leijurv to merge it, and it could be many decades until it is eventually merged at the current rate.

**Comment by cbrady350** [comment]
Great - please keep me posted on any further updates.

Thanks.

**Comment by scorbett123** [comment]
> > You are receiving this because you commented

Where you meaning to post this on this issue? This doesn't seem to make sense following through this thread.

**Comment by l1ving** [comment]
I was pointing out that

> please keep me posted on any further update

is redundant, because they're already subscribed to the issue.

**Comment by Gorex-alt** [comment]
Is there a way to add the toolsaver to a fabric mod? I tried the .zip file that was sent in this discussion but that didn't work.

**Comment by scorbett123** [comment]
You would have to build it for fabric, you would probably have to merge it into 1.16 yourself, make sure that you do it onto the 1.16 branch and run it as baritone.fabric_build.
