### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Assfugil** [cabaletta/baritone#1357]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by aUniqueUser** [comment]
lol

**Comment by S-B99** [comment]
LMAOOO

**Comment by Assfugil** [comment]
That is an accident

**Comment by cookiedragon234** [comment]
Thanks for the bug report, it’s being looked into

**Comment by Assfugil** [comment]
burh

**Comment by Assfugil** [comment]
lol
