### ISSUE TITLE
Baritone w OptiFine for 1.15.2

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#1359]
## JSON script to enable both OptiFine and Baritone

{
  "id": "1.15.2-BariFine",
  "inheritsFrom": "1.15.2",
  "time": "2020-03-02T12:44:12+11:00",
  "releaseTime": "2020-03-02T12:44:12+11:00",
  "type": "release",
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
      "name": "cabaletta:baritone-api:1.5",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "https://repo1.maven.org/maven2/"
    },
    {
      "name": "optifine:OptiFine:1.15.2_HD_U_G1_pre9"
    },
    {
      "name": "optifine:launchwrapper-of:2.1"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker",
      "--tweakClass",
      "baritone.launch.BaritoneTweaker"
    ]
  }
}

**Comment by S-B99** [comment]
Thanks for creating this, but it's not what issues on GitHub are for. If you'd like to contribute you can make a pull request adding this as a markdown file with instructions in USAGE or something.

**Comment by alexzhou4129** [comment]
hey, can you elaborate on how to use this, I've tried to replace both optifine json and baritone json with that, the minecraft launcher says it's unable to start the game.
