### ISSUE TITLE
I cant figure out the follow command

### ISSUE THREAD

**Issue by jagaimo348** [cabaletta/baritone#1360]
I can not figure out how to use the follow command
I am trying to make it follow 4 specific entity types
I have impact
here is the log

[21:43:13] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > follow entity pig cow sheep chicken
[21:43:13] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

it works fine when I use "#follow entities" but not when I specify which entities

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I know how to properly spell checkboxes
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Please post the entire log, but from what information you've given you can assume the next line is going to say NullPointerException, which means that the loaded chunks don't have all of those entities, so you can't follow them.

**Comment by jagaimo348** [comment]
Why did you close this

**Comment by S-B99** [comment]
I closed it because it was resolved.

**Comment by jagaimo348** [comment]
I disagree

**Comment by S-B99** [comment]
Please read the comment I posted when I closed this, that is why you're getting an exception. If you think otherwise, post the entire log and I will reopen this.

**Comment by jagaimo348** [comment]
I did read it and I was planning to post the whole log, I just assumed you would wait until I do that

I'm sorry
