### ISSUE TITLE
avoidance isnt working

### ISSUE THREAD

**Issue by Yolotroll101** [cabaletta/baritone#1361]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.10

## How to reproduce
1- literally just enable avoidance
it doesn't work and waltzes straight into mobs

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Unable to reproduce.
