### ISSUE TITLE
How to build Baritone for Snapshots?

### ISSUE THREAD

**Issue by CosmicSnow** [cabaletta/baritone#1365]
## What do you need help with?
Is it possible to build for snapshots, if yes, how to do it? Is there any example so I can do it myself? I understand how to program, just need some starting steps so I can do it myself for any snapshot with no much difference, like 20w10a.

**Comment by CDAGaming** [comment]
Snapshots are only possible in the Fabric Modloader, which currently is being supported under Fabritone at https://gitlab.com/CDAGaming/fabritone

Note that this is a modified and unofficial version of baritone; support for fabric officially atm is n/a

**Comment by S-B99** [comment]
Closed as question answered, not possible for baritone.

**Comment by CosmicSnow** [comment]
> 
> 
> Snapshots are only possible in the Fabric Modloader, which currently is being supported under Fabritone at https://gitlab.com/CDAGaming/fabritone
> 
> Note that this is a modified and unofficial version of baritone; support for fabric officially atm is n/a

Nice! Is there any tutorial how to use it? I never user fabric, Also is there the version 20w10a available?

**Comment by CDAGaming** [comment]
@CosmicSnow Mostly is the same as Baritone; just using the @ symbol as prefix, not #

And yea a version exists for 20w10a, builds for that, 1.15.2, 1.14.4, and any in-between are available in the CI menu in the repo

**Comment by CosmicSnow** [comment]
> 
> 
> @CosmicSnow Mostly is the same as Baritone; just using the @ symbol as prefix, not #
> 
> And yea a version exists for 20w10a, builds for that, 1.15.2, 1.14.4, and any in-between are available in the CI menu in the repo

Sorry, my question wasn't clear, I meant, 
For using the fabritone build, I need the fabric installed, or I just need to select the fabritone.jar file on the launcher? sorry if it's simple, I think I missed some step and didn't figure out how to initialize the fabritone-1.5.1.jar build :P

**Comment by CDAGaming** [comment]
@CosmicSnow All youll need for fabritone is just a valid launcher profile with the Fabric Loader (You can get its installer from fabric's website)

After that, fabritone is loaded just like any normal mod within your mods folder.

**Comment by CosmicSnow** [comment]
> 
> 
> @CosmicSnow All youll need for fabritone is just a valid launcher profile with the Fabric Loader (You can get its installer from fabric's website)
> 
> After that, fabritone is loaded just like any normal mod within your mods folder.

Worked, thank you very much! 👍
