### ISSUE TITLE
#goto negative coords off by one error

### ISSUE THREAD

**Issue by fw4hre0xxq** [cabaletta/baritone#1366]
## Some information
Operating system: Win 10 Pro x64
Java version:
 ```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment Corretto-8.242.08.1 (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM Corretto-8.242.08.1 (build 25.242-b08, mixed mode)
```

Minecraft version: 1.12.2
Baritone version: baritone-standalone-forge-1.2.11
Forge mods (if used): Just Forge, no mods

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce

1. Create a brand new 1.12.2 install (I used MultiMC).
2. Teleport around until you find negative coordinates on land.
3. Issue a #goto command with two arguments (the X and Z coordinates) with at least one of them being negative.
4. Observe. Expected behavior is that when Baritone stops moving, if the coordinates specified in step 3 are e.g. -100 -100, the F3 screen will show -100 -100. Actual behavior is that F3 reads -99 -99. When one coordinate is negative and one is postitive, only the negative coordinate will be effected. When the coordinates are -0 -0 the F3 screen shows 0 0.

This 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by fw4hre0xxq** [comment]
[baritone-issue1366-log.txt](https://github.com/cabaletta/baritone/files/4301507/baritone-issue1366-log.txt)

**Comment by fw4hre0xxq** [comment]
Thoughts: Is it possible that Baritone isn't accounting for Minecraft having a negative zero?

**Comment by CDAGaming** [comment]
Possibly related to #1364

**Comment by ZeroMemes** [comment]
Integer coordinates refer to the corner of the block farthest from `(0, 0)`. This isn't a legitimate issue, try doing `/tp <player> -X, ~ -Y` and you will end up on the same block Baritone will take you to.
