### ISSUE TITLE
How to follow entity again?

### ISSUE THREAD

**Issue by AnimeniacSimey** [cabaletta/baritone#1367]
I noticed how in Baritone 1.15.2 the command "followentity" doesn't exist anymore. Is there an equivalent to this right now? (I want to use it to find wither skeletons so if there's a better option please tell!)

**Comment by S-B99** [comment]
`#help follow`

**Comment by AnimeniacSimey** [comment]
Thanks!!

**Comment by S-B99** [comment]
If the help command is outdated go [here](https://github.com/cabaletta/baritone/blob/1.15.2/src/main/java/baritone/command/defaults/FollowCommand.java#L129), it has exact what you're looking for
