### ISSUE TITLE
Look for a certain command

### ISSUE THREAD

**Issue by AnimeniacSimey** [cabaletta/baritone#1368]
Is there a command in baritone that allows you to just see the waypoint? For example if you use
`follow entity wither_skeleton` it shows you where to go rather than automatically going there on it's own. Thanks!

**Comment by S-B99** [comment]
Duplicate of #928

**Comment by AnimeniacSimey** [comment]
It doesn't answer my question though...

**Comment by S-B99** [comment]
It's not added yet, as that issue is still opened
