### ISSUE TITLE
I want to only mine a specific type of wood and with auto mine I cant seem to make it do that 

### ISSUE THREAD

**Issue by Boi1234242424242** [cabaletta/baritone#1370]
## What do you need help with?
plz tell me how to make it only mine 1 type of wood
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CDAGaming** [comment]
#mine oak_log
#mine birch_log

All you really need is the namespaced id, which can be googled or seen ingame via the F3 menu

**Comment by fw4hre0xxq** [comment]
The thing is the namespace IDs changed in version 1.13. For version 1.13 and above, @CDAGaming's method should work.

 For 1.12 and below, all the log types are two blocks, `log` and `log2`. And the variant is stored as a data value. If you only want blocks with a specific data value, you can specify like so:

`log:0` is for Oak Logs
`log:1` for Spruce
`log:2` for Birch
`log:3` for Jungle
`log2:0` for Acacia
`log2:1` for Dark Oak.

**Comment by Boi1234242424242** [comment]
> The thing is the namespace IDs changed in version 1.13. For version 1.13 and above, @CDAGaming's method should work.
> 
> For 1.12 and below, all the log types are two blocks, `log` and `log2`. And the variant is stored as a data value. If you only want blocks with a specific data value, you can specify like so:
> 
> `log:0` is for Oak Logs
> `log:1` for Spruce
> `log:2` for Birch
> `log:3` for Jungle
> `log2:0` for Acacia
> `log2:1` for Dark Oak.

thank you so much

**Comment by Kruemmelspalter** [comment]
So please close the issue
