### ISSUE TITLE
How to avoid caves (when mining)?

### ISSUE THREAD

**Issue by Kruemmelspalter** [cabaletta/baritone#1372]
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
You can't, but you can avoid mobs. The 4 settings are described here https://baritone.leijurv.com/baritone/api/Settings.html#avoidance

**Comment by CDAGaming** [comment]
Actually technically you can @S-B99 at least in 1.13+

Thanks to mojang separating air to also have CAVE_AIR, you can set this as a block to avoid
@Kruemmelspalter

**Comment by S-B99** [comment]
Then this should be a feature request

**Comment by S-B99** [comment]
Ohhh no I misread your thing. That's right.

**Comment by EnderRobber101** [comment]
so how do you avoid caves

**Comment by StroepWafel** [comment]
#blocksToAvoid cave_air
