### ISSUE TITLE
#mine IC2 blocks

### ISSUE THREAD

**Issue by lRoberth** [cabaletta/baritone#1373]
I'm trying to mine IC2 mod blocks, but I receive an error saying "Error at argument #1: Expected aa"
I thought you could mine mod blocks too just by specifying mod:block. In this case, I want to mine copper, so the block ID would be IC2:blockOreCopper, but I just get that message. Is there something else I could do to get this running?

**Comment by CDAGaming** [comment]
Are you sure IC2 is the modid, as it should be actually ic2
Do bare in mind, especially in the case of modded blocks, that the id is case-sensitive.

**Comment by lRoberth** [comment]
> 
> 
> Are you sure IC2 is the modid, as it should be actually ic2
> Do bare in mind, especially in the case of modded blocks, that the id is case-sensitive.

How can I get the real blockID?, in F3 says the ID is "ic2:resource type:copper_ore", but in the wiki, it says It's IC2:blockOreCopper

**Comment by S-B99** [comment]
Yes, you do.

**Comment by S-B99** [comment]
This isn't a baritone issue really, it's with however your mod stores block names.
