### ISSUE TITLE
How to integrate baritone into my own 1.15.1 mod?

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [cabaletta/baritone#1375]
Hello there!

I am developing my own minecraft forge mod (automatic potion brewer) and I require baritone's movement functionality for that to move around the potion machine, collect more potion supplies, etc. I am interested how I could integrate baritone into my mod.

Thank you for the time taken!

**Comment by S-B99** [comment]
Read the getting started in the readme https://github.com/cabaletta/baritone#getting-started

The tldr is, add the API to whatever build system you're using and then you can call the API
