### ISSUE TITLE
So I'm using baritone to mine  wood   and my   thing keeps jumping up  on the wood and then staying still so is there anyway to  disable  jumping?

### ISSUE THREAD

**Issue by Boi1234242424242** [cabaletta/baritone#1380]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Basically I need  help  finding out where  I c an add and change settings all  the while figuring out how to disable jumping with auto  mining wood

**Comment by S-B99** [comment]
`#assumeStep true`
