### ISSUE TITLE
Add mining by Ore Dictionary Name

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1381]
## Describe your suggestion
Ability to do `#mine oreCopper` and etc.

## Settings
Mods to ignore would be nice

## Context
It would be very usefull.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
This is literally too much effort for what it accomplishes. Also if multiple mods have the same block names the user would have to setup special rules and everything.
