### ISSUE TITLE
Need the bot to keep mining after inventory is full

### ISSUE THREAD

**Issue by Kasaplaza** [cabaletta/baritone#1382]
I currently want Baritone to work on prison like servers, where it mines for experience and the actual drops dont matter. How would i go about setting it up to ignore the items dropped on the floor and only target blocks?

**Comment by S-B99** [comment]
`#mineDropLoiterDurationMSThanksLouca 0`

**Comment by CDAGaming** [comment]
In relation to this, https://github.com/cabaletta/baritone/pull/1064 is gonna have to be adjusted as this will collide with it if its ever merged

(Made as note to myself to do this)

**Comment by derBobo** [comment]
@CDAGaming 
I don't see where this collides with #1064  the only difference woul be that you also had to write `#checkInventory false`

**Comment by CDAGaming** [comment]
It took you SEVEN MONTHS TO RESPOND TO THIS.

Well either way, the other prs updated and my comment is now outdated by this stage lol
