### ISSUE TITLE
How to mine by id from tooltips?

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1383]
## What do you need help with?
How to mine by numeric or literal id from advanced tooltips if the mod uses one ID for all the resources, like `forestry:resources` ?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
You need the numerical id, for example the pre 1.13 system with `minecraft:stone 1`, 1 being the type of stone.
