### ISSUE TITLE
Baritone can't jump

### ISSUE THREAD

**Issue by pNoName1337** [cabaletta/baritone#1384]
## Some information
Operating system: Windows 10
Java version: 241x64
Minecraft version: 1.15.2
Baritone version: 1.5.1
Forge mods (if used): fabric - xray, voxelmap, REI, but also it happened to me when I was using normal baritone with no mods

## Exception, error or logs
https://pastebin.com/xVTn6a4n

## How to reproduce
Just watch this: https://www.youtube.com/watch?v=sXknPJxB6bA&feature=youtu.be

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Send your modified settings list.

**Comment by pNoName1337** [comment]
> Send your modified settings list.

maxFallHeightBucket 42
chatControl false
legitMineIncludeDiagonals true
followRadius 2

**Comment by pNoName1337** [comment]
I just had to remove the baritone folder to make it work
closed

**Comment by S-B99** [comment]
you had another setting modified then

**Comment by CDAGaming** [comment]
Perhaps in the future any modified settings should be a requirement in the issue template...

**Comment by S-B99** [comment]
Lemme fix

**Comment by S-B99** [comment]
opened #1401
