### ISSUE TITLE
How to set Boundaries for Baritone?

### ISSUE THREAD

**Issue by Jamishs** [cabaletta/baritone#1385]
## What do you need help with?
How to set boundaries so that i cant mine unbreakable blocks in spawn and mine in just one area like i #sel 1 and #sel 2 a position and then i #mine oak_wood it and then it doesnt go to mine a house or table it only mines the oak logs in the select

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
` #sel replace log air`
