### ISSUE TITLE
minecraft 1.12.2 autocompletion not working

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1386]
## Some information
Operating system: win10x64
Java version: comes with minecraft installer
Minecraft version: 1.12.2
Baritone version: 1.2.10
Forge mods (if used): Baritone

## Exception, error or logs
not usefull

## How to reproduce
type a part of Baritone command
press tab

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
There is no auto completion.
