### ISSUE TITLE
Error in downloading the version from json

### ISSUE THREAD

**Issue by simoaspe** [cabaletta/baritone#1387]
I get this error when I try to download Baritone 1.15.2 using the json file

Failed to download file.
Name: 1.15.2.jar
URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
Error details: The requested URL returned error: 403 Forbidden
Filename on disk: 1.15.2.jar
Path: /Users/simoneasperti/Library/Application Support/minecraft/versions/1.15.2/1.15.2.jar
Exists: Nonexistent

**Comment by S-B99** [comment]
then your isp or firewall is blocking it
