### ISSUE TITLE
How to build a forge version with gradlew

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#1391]
I entered gradlew build and it will not generate a forge version of the jar mod file

Console display :

> Task :proguard
Running Determinizer
 Input path: E:\下载\baritone-1.2.11\build\libs\baritone-1.2.11.jar
 Output path: E:\下载\baritone-1.2.11\build\libs\baritone-unoptimized-1.2.11.jar
<============-> 95% EXECUTING [1m 11s]
> :proguard
![image](https://user-images.githubusercontent.com/59153990/76566727-533e3f00-64e8-11ea-8709-bd57e646a1cf.png)

**Comment by S-B99** [comment]
you need to wait.

**Comment by KingsMentor** [comment]
Please, how was this resolve ?

**Comment by KingsMentor** [comment]
from running `./gradlew :proguard`
> Task :proguard FAILED
Running Determinizer
 Input path: /Users/macbook/Downloads/baritone-1.2.14/build/libs/baritone-1.2.14.jar
 Output path: /Users/macbook/Downloads/baritone-1.2.14/build/libs/baritone-unoptimized-1.2.14.jar
