### ISSUE TITLE
how to have auto miner go but with less  stopping

### ISSUE THREAD

**Issue by Boi1234242424242** [cabaletta/baritone#1392]
basically i'm auto mining wood  and  sometimes  it stops for a while any way to prevent this or  make it less common?

<3

**Comment by S-B99** [comment]
It's calculating where the next place to go is. If you mean waiting for items to pickup / drop, there are the `mineDropLoiterDurationMSThanksLouca`, `mineScanDroppedItems` and `mineGoalUpdateInterval` settings.

**Comment by Boi1234242424242** [comment]
tysm  ur a big help

**Comment by darkstar01** [comment]
This is very useful info, thank you.
