### ISSUE TITLE
Build error \

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#1394]
![image](https://user-images.githubusercontent.com/59153990/76590547-64a73b80-6528-11ea-895e-0616a6cc0b30.png)

**Comment by djkcyl** [comment]
debug mode

![image](https://user-images.githubusercontent.com/59153990/76591683-0ed49280-652c-11ea-99de-1274944d4b11.png)

**Comment by aUniqueUser** [comment]
Make sure your using Oracle JDK 8

**Comment by S-B99** [comment]
That's the issue here.
