### ISSUE TITLE
A question about #mine chopping trees

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#1395]
The following text comes from Google Translate :D

In #mine, only the lower half of the tree is cut during log2's tree felling process, and then I ran to the tree to cut, but always stayed the same when the last one was cut (possibly because of fear of falling damage). Now, find a solution.

**Comment by S-B99** [comment]
Because it's faster to go to another tree then to build up to chop the rest.

**Comment by lingyunQAQ** [comment]
> 因为去另一棵树然后砍去剩下的树要快得多。

No i mean he doesn't move

**Comment by S-B99** [comment]
If baritone isn't doing anything then there isn't anything for it to do.

**Comment by lingyunQAQ** [comment]
> 如果男中音什么也没做，那就没有什么可做的了。

Sorry, I'm using machine translation, I have a bit of difficulty understanding what you mean.
But what I mean is that he seems to cancel the action to avoid the damage caused by the drop, and the bottom left corner shows：
 [Baritone] Unable to find any path to BlockOptionalMetaLookup {[BlockOptionalMeta {block = Block {minecraft: log2}, meta = null}]}, blacklisting presumably unreachable closest instance ...

**Comment by lingyunQAQ** [comment]
![TG98N_{8AMHW4%H 7RT3ONX](https://user-images.githubusercontent.com/58384404/76626754-b2499580-6574-11ea-859f-a6078e306717.png)

**Comment by S-B99** [comment]
That means it can't find any of log2. What type of log are you standing on?

**Comment by lingyunQAQ** [comment]
> 这意味着它找不到任何log2。您站在哪种类型的日志上？

Please take a look at the picture I just uploaded, but there are log2 everywhere under his feet and nearby.
He is standing above log2

**Comment by S-B99** [comment]
Is there a drop under? If so, there is a `maxFallHeightBucket` setting

**Comment by lingyunQAQ** [comment]
> 下方有下落吗？如果是这样，有一个`maxFallHeightBucket`设置

let me try

**Comment by lingyunQAQ** [comment]
> 下方有下落吗？如果是这样，有一个`maxFallHeightBucket`设置

Still so

**Comment by S-B99** [comment]
What does it look like under the logs? And what did you change it to?

**Comment by lingyunQAQ** [comment]
> 在日志下看起来像什么？您将其更改为什么？


Lots of
![_%)Y WRZ{ JOY7_RUHSNSEU](https://user-images.githubusercontent.com/58384404/76627693-70215380-6576-11ea-8d59-6a328c4c751c.png)

**Comment by S-B99** [comment]
The oak log.

**Comment by S-B99** [comment]
And what did you change the setting to?

**Comment by lingyunQAQ** [comment]
> 您将设置更改为什么？

I did n’t change how to set it, I just entered #mine log2, and maxFallHeightBucket you just said

**Comment by S-B99** [comment]
https://github.com/cabaletta/baritone/blob/master/USAGE.md

**Comment by S-B99** [comment]
I gave you the wrong setting, if you don't have water it's `maxFallHeightNoWater`

**Comment by lingyunQAQ** [comment]
> 我给你的环境设置错误，如果你没有水，那是 `maxFallHeightNoWater`

Thank you very much, he started again, because I don't speak English, I just misunderstood what you meant, I'm very sorry.

**Comment by S-B99** [comment]
run the command `#maxFallHeightNoWater <insert whatever the height of your fall is + some more>`

**Comment by S-B99** [comment]
Oh, if it works now that's good.

**Comment by lingyunQAQ** [comment]
> 哦，如果现在可以，那就好了。

谢谢老板，老板大气，老板身体欠肛!~
I use chinese language thank you
hahahahahaha qwq！~
