### ISSUE TITLE
a stupid question

### ISSUE THREAD

**Issue by iagamer** [cabaletta/baritone#1399]
where is the uploading instruction(for 1.5.2)....

**Comment by S-B99** [comment]
https://github.com/cabaletta/baritone/blob/master/README.md

**Comment by iagamer** [comment]
i meant that i downloaded the zip but how can I upload it to my launcher. I checked "README" but there is no instruction for how do I do it.(or maybe I'm just blind)
could u help me with that? thx

**Comment by S-B99** [comment]
it's literally the second link in getting started

**Comment by iagamer** [comment]
ok im just blind lol
