### ISSUE TITLE
The "unobfuscated" api classes are obfuscated in the 1.12.x pre-built releases

### ISSUE THREAD

**Issue by Brian-Graham** [cabaletta/baritone#1400]
## What do you need help with?
When adding the baritone-api.1.2.11.jar (as instructed), then rebuilding cache. I can see the api classes but when I access methods they're still obfuscated.

When I try to access `BaritoneAPI.getSettings().allowBreak.value`, it says "cannot resolve symbol value". If I hover over `allowBreak` it's looking for `baritone.api.Settings.Setting<java.lang.Boolean>`, but the class decompiled by IntelliJ is `baritone.api.Settings$Setting`.

As well when I try to set a goal, it's looking for a class called `et` (I know it's BlockPos).

Am I dumb or something? I've tried the other files (even though it says not to) and they all do the same thing, am I missing something in my build.gradle?

P.S. I'm not sure whether to add this under repositories using flatDir or compile in dependencies (I'm not a gradle master).

**Comment by ashdawngary** [comment]
this is the same exact problem I had, I just built all of api/ into my code and magically things worked.  You do have to patch random bugs/inconsistencies though(get the api dir from source-code in releases)

**Comment by 0-x-2-2** [comment]
Use Jitpack or simular.

**Comment by ashdawngary** [comment]
jitpack does not have a release pre 1.3

**Comment by Brian-Graham** [comment]
What is Jitpack.

Why is this closed when it's genuinely an issue, and the only response is some half-assed mention to something without a link or explanation?

**Comment by 0-x-2-2** [comment]
you use commit hash

**Comment by S-B99** [comment]
It's not genuine an issue, it's user error.
