### ISSUE TITLE
1.15.2 Unable to build

### ISSUE THREAD

**Issue by NecroWafer** [cabaletta/baritone#1405]
I love baritone and im incredibly sad that im not able to use it for 1.15.2. Heres my problem, when i start to do the .b build (Buildname, in my case 3x3.schematic) it send me this error message.
![asrtewrwer](https://user-images.githubusercontent.com/52283017/76691985-82ef6300-661e-11ea-8122-ad5632522ab5.JPG)

**Comment by S-B99** [comment]
You need all the blocks in your hotbar by default.

**Comment by NecroWafer** [comment]
I had all the blocks which were 9 blocks of oak wooden planks

**Comment by eduardartz** [comment]
I have the same problem

**Comment by dominikaaaa** [comment]
Metadata is not preserved with the legacy mcedit format on 1.13+:

Use sponge format schematic created by modern WorldEdit or have default block type in inventory.
