### ISSUE TITLE
What is Jitpack and how will it fix Issue #1400?

### ISSUE THREAD

**Issue by Brian-Graham** [cabaletta/baritone#1406]
## What do you need help with?
What is Jitpack (as mentioned in issue https://github.com/cabaletta/baritone/issues/1400) and how can it fix the issue outlined in the question.

Your collaborators need some help if the best they can do is answer with 4 words, to something with almost no google presence, or how and why it can fix my issue. (When this isn't even outlined or mentioned in the Setup documentation)

## Final checklist
- [x] I know some of your collaborators need some serious help with how to properly answer a question.

**Comment by CDAGaming** [comment]
@Brian-Graham 

From Jitpack.io:

> Easy to use package repository for Git
IE A type of Maven Repository you can use to link the api to your project.

From Googling "jitpack baritone" yields https://jitpack.io/p/cabaletta/baritone which allows you to link on any branch or commit, provided it is able to build successfully within Jitpack.

**Comment by Brian-Graham** [comment]
`Could not find method implementation() for arguments [com.github.cabaletta:baritone:1.2.11] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

This is my repositories:
`repositories {
    mavenCentral()
    maven {
        name = 'spongepowered-repo'
        url = 'https://repo.spongepowered.org/maven'
    }
    maven {
        name = 'impactdevelopment-repo'
        url = 'https://impactdevelopment.github.io/maven/'
    }
    maven {
        name = 'jitpack-repo'
        url = 'https://jitpack.io'
    }
    /*flatDir {
        dirs 'libs'
    }*/
}`

This is my dependencies:
`dependencies {
    provided("org.spongepowered:mixin:0.7.11-SNAPSHOT") {
        //transitive = false
        // Mixin includes a lot of dependencies that are too up-to-date
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
        exclude module: 'log4j-core'
    }

    implementation 'com.github.cabaletta:baritone:1.2.11'
}`

**Comment by Brian-Graham** [comment]
If I change `implementation` to `compile`, it works... I'm not even sure what the difference is... time to google it.

**Comment by S-B99** [comment]
That's proper.

**Comment by 0-x-2-2** [comment]
You should use the latest and the latest stable mappings for 1.12.2
