### ISSUE TITLE
Building doesnt work

### ISSUE THREAD

**Issue by PatrickDiePizza** [cabaletta/baritone#1414]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Hi I have a question for the forums cause I have a problem that When I want to build something with (.b build) it tells me that (An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues) so I'm gonna link the log below and hope somebody can help me with this
[latest.log](https://github.com/cabaletta/baritone/files/4338823/latest.log)

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Include the file extension in the command.

**Comment by PatrickDiePizza** [comment]
OwO
