### ISSUE TITLE
How to use fortune items

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#1416]
When I was in autofarm, I had a manuscript of Fortune III. I wanted him to destroy wheat, so that I could get more seeds, but he did n’t use his hands.

**Comment by scorbett123** [comment]
Disable autotool using the settings and then hold it in your hands.

Either use #autoTool or #disableAutotool, which one of those two to use is version specific.

Also, 623 days time until first response, so you probably aren't still looking for this.
