### ISSUE TITLE
add option to mine only selected blocks when mining

### ISSUE THREAD

**Issue by foxxd** [cabaletta/baritone#1417]
## Describe your suggestion
avoid breaking every block except the blocks that you want to mine

## Settings
#MineSelectedOnly [boolean]

## Context
easier than blocksToAvoidBreaking when there is a lot of blocks to avoid
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
`#blocksToAvoidBreaking` setting
