### ISSUE TITLE
Error with path

### ISSUE THREAD

**Issue by WilsontheWolf** [cabaletta/baritone#1420]
## Some information
Operating system: Windows 10
Java version: 
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
Minecraft version: forge 1.12.2
Baritone version: Not sure. It says null version. Impact 4.8.3
Forge mods (if used): ![Mods](https://jwiggs.is-ne.at/nlQlQt.png)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/4346224/latest.log)

## How to reproduce
Run `#thisway 100`
Run `#path`

## Modified settings
To get the modified settings run `#modified` in-game
```
[Baritone] > modified
[Baritone] All modified settings:
[Baritone] allowParkour (Boolean)
[Baritone] allowParkourPlace (Boolean)
[Baritone] assumeWalkOnWater (Boolean)
[Baritone] chatControl (Boolean)
[Baritone] colorGoalBox (Color)
[Baritone] freeLook (Boolean)
```
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and/or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
1. B doesnt show up in mod menu
2. #version or sth

**Comment by dominikaaaa** [comment]
The log suggests that baritone can't find a path
