### ISSUE TITLE
Build replication bot

### ISSUE THREAD

**Issue by beskhu3epnm** [cabaletta/baritone#1421]
## What do you need help with?
Hi. I'm wondering if you would happen to know if a bot exists for replicating someone's build by observing video footage of it being built, and copying it block for block? Presume the footage is not sped up, 1080p 60fps, and the world seed and version number is known. Does such a bot exist?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
No. Just create a schematic and tell baritone to build it.

**Comment by beskhu3epnm** [comment]
I wasn't reporting an issue. This seemed like the best place to ask this general question.
