### ISSUE TITLE
Will build functionality get updated?

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [cabaletta/baritone#1426]
## What do you need help with?
As far as I am aware, the .build functionality does not work in baritone for versions 1.13.2 and up. As minecraft has advanced greatly since 1.12.2, I am interested if build functionality will ever be renewed/updated to higher versions.

**Comment by Hyper1025** [comment]
up

**Comment by S-B99** [comment]
It does work.

**Comment by Fish-In-A-Suit** [comment]
1.13.2 throws an exception and 1.14.4 doesn't work either?

**Comment by CDAGaming** [comment]
@Fish-In-A-Suit Could you post the crash log in that case?

**Comment by S-B99** [comment]
Make an issue ^ 

It does work.
