### ISSUE TITLE
Blockstoavoidbreaking isn't working

### ISSUE THREAD

**Issue by Jacob345k** [cabaletta/baritone#1427]
So i used the settings "Blockstoavoidbreaking" to not break glowstone, yet when using sel replace command on a selected area, it will still break glowstone to achieve it's goal.

**Comment by Jacob345k** [comment]
to be clear im not using sel replace to replace glowstone, im using it for melon blocks

**Comment by Jacob345k** [comment]
https://gyazo.com/0e185da9be4fa1aa4d9d441a37898a94

**Comment by cancerousname69** [comment]
BlocksToAvoidBreaking is, as the name says, a list of blocks to **avoid** breaking. If it seems that the goal cannot be achieved by another path, it will break those blocks. Please close this issue, this is **not** a bug, this is intentional.
