### ISSUE TITLE
My building isnt working

### ISSUE THREAD

**Issue by PatrickDiePizza** [cabaletta/baritone#1429]
## What do you need help with?
For a few days now I have the same problem with Impact. The problem is that I cant use the build command I even tried deleting Minecraft and impact but it still didn't work so I'm hoping somebody here can help me
![2020-03-20_12 12 42](https://user-images.githubusercontent.com/62252874/77158891-819dba80-6aa4-11ea-882c-743709fa78ba.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by PatrickDiePizza** [comment]
Here is the log
[latest.log](https://github.com/cabaletta/baritone/files/4359188/latest.log)

**Comment by 1Gewiner** [comment]
I have the same problem.

**Comment by PatrickDiePizza** [comment]
well then follow this issue so if someone can help me you will get notified too

**Comment by S-B99** [comment]
what version was your schematic made in? and what does it have in it?

**Comment by PatrickDiePizza** [comment]
I made the Schematic in 1.12.2 and i called it Void because the Schematic is just empty only air
Then I tried to use it in 1.13

**Comment by S-B99** [comment]
Then make it in 1.13

**Comment by PatrickDiePizza** [comment]
how i dont have the Schematica mod in 1.13 ?

**Comment by PatrickDiePizza** [comment]
or how can i create Schematics

**Comment by S-B99** [comment]
no clue how you make schematics, that sounds like a you problem

**Comment by PatrickDiePizza** [comment]
yea
