### ISSUE TITLE
Can't have baritone and Liquidbounce in mod folder at same time

### ISSUE THREAD

**Issue by CarsterQ** [cabaletta/baritone#1431]
Can't have baritone and Liquidbounce in mod folder at same time

Hey!, so i got the idea to install baritone and liquidbounce for the best hacking experience but everytime i launching minecraft it crashes.
Do anyone have a fix?

**Comment by S-B99** [comment]
Try removing liquid bounce from your mods folder, that should fix the issue.

**Comment by CarsterQ** [comment]
> Try removing liquid bounce from your mods folder, that should fix the issue.

Why cant i use both of them at same time?'

**Comment by S-B99** [comment]
Because apparently it crashes
