### ISSUE TITLE
Schematica Doesnt Work in 1.14.4

### ISSUE THREAD

**Issue by VortexCZE09** [cabaletta/baritone#1433]
I was trying to use schematica in 1.14.4 but i have this issue. Screenshot - > https://imgur.com/a/BPx214v
Btw there is the latest log with this error - > 
[latest.log](https://github.com/cabaletta/baritone/files/4361809/latest.log)

Maybe is something wrong on my side, i actually dont know, what to do with this error.

Btw. 1.13.2 also doesnt work.

**Comment by S-B99** [comment]
You need to include the **full** file name in the command
