### ISSUE TITLE
It's clearly not done.

### ISSUE THREAD

**Issue by Snowflake101** [cabaletta/baritone#1438]
Operating system: Win 7
Java version: Version 8 Build 241
Minecraft version: 1.15.2
Baritone version: Latest release.
Forge mods (if used): N/A

## Exception, error or [logs]
http://prntscr.com/rlh9xn

## How to reproduce
Step 1 #sel ca a large ( in this case 128x128 ) area
Step 2 #sel f the area with a block( in this case "black concrete powder" )
Step 3 realize it has left numerous holes. That even after the fact are "unfill-able" according to the bot. 

## Modified settings
allowDownward (true)
allowInventory (true)
breakFromAbove (true)
freeLook (false)
rightClickSpeed (2)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Send the log.
