### ISSUE TITLE
Just doesn't mine the ore

### ISSUE THREAD

**Issue by 265866** [cabaletta/baritone#1443]
Operating system: Windows 10
Java version: 8 update 241
Minecraft version: 1.12.2
Baritone version: im not sure, downloaded it about a month ago.
Forge mods (if used): none

## Latest Log
[latest.log](https://github.com/cabaletta/baritone/files/4378272/latest.log)

## How to reproduce

Join cosmicprisons.com
wait in queue
complete tutorial
do #mine coal_ore or once you clear that section (takes about 10 minutes) do #mine quartz_ore

## Modified settings

Just ChatControl

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Can you send a video of it not mining the ore?

**Comment by 265866** [comment]
Sure, here it is.

[Link to Video](https://youtu.be/5Nz57yol9Vo)

**Comment by 265866** [comment]
And also, theirs another error that's happening where I think that theirs just too much ore, so it just overwhelms baritone (just an idea) do I have to make a another bug report for that?

**Comment by S-B99** [comment]
No, there is no such thing as too much. For some reason it can't find a destination to the path. The server probably has some sort of anti baritone anticheat.

**Comment by 265866** [comment]
oh, okay, so im assuming that theres no solution to the problem?

**Comment by S-B99** [comment]
Probably so.
