### ISSUE TITLE
How to use the Baritone API?

### ISSUE THREAD

**Issue by Stenlan** [cabaletta/baritone#1444]
## What do you need help with?
I can't seem to understand how to get started on creating a mod that utilizes the Baritone API. I know modloaders like Fabric and Forge (except 1.12) aren't supported, so how _do_ I create a mod that utilizes the API then? Am I missing something in that Minecraft has some kind of native modding support now? Do I need to write my own launch wrapper? Sorry if this is a dumb question, but I couldn't related information anywhere either. Thanks in advance.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Call BaritoneAPI.method();

**Comment by S-B99** [comment]
also read the docs

**Comment by Stenlan** [comment]
> 
> 
> Call BaritoneAPI.method();

In what?? I can't use any mod loader, so how do I even extend minecraft's code, unless I'm missing something ENTIRELY obvious?? I'm so confused right now...

> also read the docs

I have read the docs, I can read documentation and would know how to use the actual API, once I know how to get started even accessing it... I feel like I'm really missing something obvious here or I'm just plain retarded

**Comment by S-B99** [comment]
That's completely up to you as to what you use. It's not baritones responsibility as to what you use to launch mc. You could use ClientAPI or Forge, and some people have gotten it working on Fabric.
