### ISSUE TITLE
Bamboo? How to Farm

### ISSUE THREAD

**Issue by JmartDeacon** [cabaletta/baritone#1448]
Hi sorry to bother you guys but im super new to baritone... 
Is there a way to make baritone automatically farm bamboo (does not come under the #farm command) and either cut it just above the stem or cut it and replant it? 
Also how do I then command the player when its inventory is full to put the bamboo in chests.

Thanks so much.

**Comment by S-B99** [comment]
This is a bug, as I guess it doesn't consider bamboo for farming.

**Comment by JmartDeacon** [comment]
yeah is there a way to add bamboo to the farm command?

**Comment by S-B99** [comment]
That's why I labelled this as bug.

**Comment by kcoderhtml** [comment]
This would be usefull.

**Comment by Bluscream** [comment]
Indeed

**Comment by SavageTheUnicorn** [comment]
Obligatory necro, I'd love to see this fixed as well.
