### ISSUE TITLE
My modpack not launching in multimc with Baritone

### ISSUE THREAD

**Issue by josh-65** [cabaletta/baritone#1456]
When launching my modpack in multimc it gets to mixin stuff the exits it with process code 1.

## Some information
Operating system     : Windows 10 pro - 64 bit 
Java version               : 8 - 242
Minecraft version      : 1.12.2
Baritone version        : Impact 4.8.2
Forge mods (if used) : In log

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/4394231/latest.log)

## How to reproduce
1. Use multimc
2. Add [baritone.txt](https://github.com/cabaletta/baritone/files/4394251/baritone.txt)
3. Launch game

**Comment by S-B99** [comment]
One if your mods is causing this.

**Comment by josh-65** [comment]
Do you know what ones as the log doesn't say anything about other mods for me.

**Comment by S-B99** [comment]
Remove them one by one and find out.
