### ISSUE TITLE
Placing farming materials

### ISSUE THREAD

**Issue by vplayer132** [cabaletta/baritone#1459]
Hey I was wondering if there was a way to make Baritone place farm materials such as wheat, sugarcane, etc., for the build a schematic command because in-game it keeps being unable to place them.

If there's already a way to do this, how so?

Thank you

**Comment by YEETICUS12332** [comment]
Did u ever figure it out?

**Comment by dominikaaaa** [comment]
`;b farm`

You have to place them manually beforehand
