### ISSUE TITLE
Baritone 1.14.4 when i try to join a world my game crashes

### ISSUE THREAD

**Issue by kortay123kivancasd** [cabaletta/baritone#1460]
## Some information
Operating system:windows
Java version:java 8 update 241
Minecraft version:1.14.4
Baritone version:in https://www.youtube.com/watch?v=3ggBfaCE_tk
Forge mods (if used): nothing

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Fill out the issue template properly.
