### ISSUE TITLE
baritone trying to hunt mobs

### ISSUE THREAD

**Issue by LordFetznschaedl** [cabaletta/baritone#1463]
Is it possible to let your character using baritone to hunt for specific mobs kill them and then pick up specific items you are able to configure. 

For example just heads.

**Comment by marsuh228** [comment]
.b follow entity <your entity>
I am not sure about killing.

**Comment by LordFetznschaedl** [comment]
Yeah but another problem is picking up just specific items

**Comment by S-B99** [comment]
It has a setting for drops.
