### ISSUE TITLE
Quartz can use mine command

### ISSUE THREAD

**Issue by ToonamiSenpai** [cabaletta/baritone#1464]
## Some information
Operating system: Windows 10 Ver 1909
Java version: 8
Minecraft version: 1.15.2
Baritone version: 1.5.2
Forge mods (if used): N/Q

## Exception, error or logs
[22:43:31] [main/INFO]: [CHAT] [Baritone] > mine quartz_ore
[22:43:31] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected ForBlockOptionalMeta

## How to reproduce
Just do #mine quartz_ore

## Modified settings
To get the modified settings run `#modified` in game
N/A
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by HexCodeFFF** [comment]
I think it's called nether_quartz_ore

**Comment by S-B99** [comment]
correct.
