### ISSUE TITLE
Baritone standalone forge not working 

### ISSUE THREAD

**Issue by Wheatlyguy756** [cabaletta/baritone#1465]
## Some information
Operating system: Windows 10
Java version: V8
Minecraft version:1.12.2
Baritone version: 1.2.10 -1.2.13
Forge mods (if used): https://tekxit.fandom.com/wiki/Tekxit_Wiki <- mod list 

No Crash report is created

i have also tried running baritone with forge in the Minecraft launcher with the same mods with no avail
##Logs
[latest.log](https://github.com/cabaletta/baritone/files/4398230/latest.log)

## How to reproduce
Install modpack, add baritone, run mod pack.

## Modified settings
none because it doesnt work lol

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Try removing the modpack, that should fix the issue.

**Comment by Wheatlyguy756** [comment]
@S-B99 yes I understand that but I have reattached that it is possible to use baritone with mods hence why I have posted the issue

**Comment by S-B99** [comment]
You can, but some modpacks won't work.
