### ISSUE TITLE
Open and use chests

### ISSUE THREAD

**Issue by marsuh228** [cabaletta/baritone#1466]
## Descriptiomn
Baritone can't open chests. But why? I think it would be very useful for automatisating processes (like mining).
## How

- Allow opening chests
- Select the chest(s) to use

## How would it help???/
It will automatisate much.

## Checc
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
Bottom text

**Comment by S-B99** [comment]
Duplicate of #495
