### ISSUE TITLE
Freecam locked yaw and pitch 

### ISSUE THREAD

**Issue by THeeRealKomila** [cabaletta/baritone#1468]
When I turn on freecam my pitch and yaw gets locked when I try to move the camera with my mouse it doesn't work. 
Minecraft version:1.12.2

Forge mods (if used):Ares,Elementars,impact

## How to reproduce
Turn on freecam

## Final checklist
- [x] I know how to properly use check boxes 
- [ yes ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [no] I have included logs, exceptions and / or steps to reproduce the issue.
- [ xD I have not ] I have not used any OwO's or UwU's in this issue.

**Comment by ScanmanTM** [comment]
??? What does this have to do with baritone???

**Comment by S-B99** [comment]
Not a baritone issue.
