### ISSUE TITLE
Ender pearls in baritone? (what)

### ISSUE THREAD

**Issue by marsuh228** [cabaletta/baritone#1469]
## well
Sometimes it is necessary to go somewhere instantly, doesn't it? And you have no blocks in inventory (or have) but enderpearls. You go somewhere and WHAM there is a griefer behind you. Baritone throws a pearl, like in trajectories, but automatically and that's all.
## Settings
#set allowPearl

## Context
It is cool.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] ergrehergseevxxhgd.
- [x] revhsstydkufkk.
- [x] feshf4shshffebczbehef.

**Comment by S-B99** [comment]
Baritone is for pathing, not using ender pearls.

**Comment by TheK0tYaRa** [comment]
But pathing with pearls really sounds cool ._.

**Comment by S-B99** [comment]
That's way out of the scope of what baritone does. It's pathing system is written specifically for walking / running.
