### ISSUE TITLE
Fight Back

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#1471]
## Describe your suggestion
Fairly simple, in concept at least. If you get hurt by a mob and you have a sword on your hotbar, use that sword to kill the mob

## Settings
#fightBack (to togge between true/false)

## Context
Would increase the survivability of an automated player.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Y E S

**Comment by S-B99** [comment]
Impact has hunt. Also duplicates of #927 and #932
