### ISSUE TITLE
Automatic Torch Placing

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#1473]
## Describe your suggestion
Add a setting to place torches either in the offhand or in the hotbar when the light level of the block that the player is standing on is below 7, or a configurable number.

## Settings
autoTorch (to toggle the setting true/false)
torchLightLevel [number] (to choose at what light level to place a torch)

## Context
Increased survivability for automated players.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Y E S

**Comment by marsuh228** [comment]
I've seen auto torch in Wurst and leijurv should add this to baritone.

**Comment by S-B99** [comment]
Duplicate of #971
