### ISSUE TITLE
Placing blocks is unreliable

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#1474]
## Some information
Operating system: Windows 10
Java version: 8.0.2210.11
Minecraft version: 1.15.2
Baritone version: How to find this out? 2481 commits?

## How to reproduce
I got the bug while using #mine diamond_ore when the player is trying to place a block at seemingly random times.

##logs
[latest.log.txt](https://github.com/cabaletta/baritone/files/4399042/latest.log.txt)

## Modified settings
allowParkour
allowParkourPlace
avoidance
blocksToAvoid
blocksToAvoidBreaking
chatControl
freeLook

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and/or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
You can find out the baritone version in game with the help command. You didn't actually tell us what the bug is in any sort of detail, other then "unreliable"
