### ISSUE TITLE
How do I get Baritone to work with Thermal Foundation

### ISSUE THREAD

**Issue by TheSSSSNAKEKing** [cabaletta/baritone#1478]
## What do you need help with?
I am attempting to use auto mine in Baritone with my mod Thermal Foundation and when I list an ore from the mod, Baritone says it does not recognize the block.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
You need to put the modid before the block name, and use the block IDs from thermal, not the block names.

**Comment by TheSSSSNAKEKing** [comment]
Can you give an example so that I know how to format it?

**Comment by S-B99** [comment]
See #1253

**Comment by TheSSSSNAKEKing** [comment]
I still don’t understand how to do it, can I get an example of the code I could type in

**Comment by S-B99** [comment]
It doesn't work with thermal foundation apparently, as shown in the linked issue.

**Comment by TheSSSSNAKEKing** [comment]
Oh okay
