### ISSUE TITLE
1.14.4 Wont launch

### ISSUE THREAD

**Issue by EdiLOL2005** [cabaletta/baritone#1479]
Every time I want to play baritone it just says:

"Failed to download file.
Name: asm-all-5.0.3.jar
URL: http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
Error details: The requested URL returned error: 501 HTTPS Required
Filename on disk: asm-all-5.0.3.jar
Path: C:\Users\REDACTED\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
Exists: Nonexistent"

I tried everything Including: Redownloading 1.14.4, switch the asm-all file to 3.3.1, deleting the ow2 and reputing it back, redownloading baritone. I'm going insane. Please help!

**Comment by S-B99** [comment]
Your ISP or firewall is blocking that resource, try a VPN.
