### ISSUE TITLE
Fatal crash when using #build, Unexpected Error. 1.15 version

### ISSUE THREAD

**Issue by Goodgun123456789** [cabaletta/baritone#1484]
>What I was doing
I was starting the build on a massive project, crashes when trying to find route to something. 
>Crash Log
[crash-2020-03-31_05.35.31-client.txt](https://github.com/cabaletta/baritone/files/4408487/crash-2020-03-31_05.35.31-client.txt)

**Comment by S-B99** [comment]
Fill out the issue template properly.
