### ISSUE TITLE
There is no "Minecraft Client" launch config in 1.5.2 baritone

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1485]
## What do you need help with?
Can't follow the Intellij guide in readme.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
You need to reimport gradle.

**Comment by TheK0tYaRa** [comment]
I have closed Intellij as in the guide. Didn't help either.

**Comment by S-B99** [comment]
*reimport* gradle after generating intellij runs.

**Comment by TheK0tYaRa** [comment]
After generating it for which time exactly? It will be a seventh by now. I haven't skipped any other step but the configuration editing. I have even tried --recursive option with git clone -b 1.15.2 [baritone.git]

**Comment by S-B99** [comment]
You need to *reimport* gradle after generating.

**Comment by TheK0tYaRa** [comment]
I suppose it will be more sense for me to record step by step actions just to be sure on video. Lemme do that for some time.

**Comment by TheK0tYaRa** [comment]
https://drive.google.com/open?id=1_58CfSkouesQHuxKeXuVH26rjKDMCEt5
Here it is

**Comment by S-B99** [comment]
You *need* to setup the workspace first

**Comment by TheK0tYaRa** [comment]
With no info of how to do it?

**Comment by S-B99** [comment]
It's in the same file you were reading.

**Comment by TheK0tYaRa** [comment]
But it fails

**Comment by S-B99** [comment]
If setupDecompWorkspace doesn't exist as an option then that's a different issue.

**Comment by TheK0tYaRa** [comment]
Found info [here](https://www.minecraftforge.net/forum/topic/74277-setupdecompworkspace-not-found/) that  

> That function is antiquated since forge 1.13 (or so). You don't have to do it anymore, just run : `./gradlew eclipse`

Almost sure that this step isn't a proper way to compile Baritone 1.5.2 which doesn't support Forge.

**Comment by S-B99** [comment]
1.15.2 actually does support forge now.

**Comment by S-B99** [comment]
Not the official releases, but there's a pull to support t.

**Comment by TheK0tYaRa** [comment]
So it's in the master branch?

**Comment by S-B99** [comment]
It should be merged by now, yes

**Comment by S-B99** [comment]
Same branch you're already using https://github.com/cabaletta/baritone/pull/1446

**Comment by TheK0tYaRa** [comment]
Thanks

**Comment by TheK0tYaRa** [comment]
The last commit is adding and removing the changes for README.md while the info about MixinBootstrap-1.0.2.jar is required to run forge 1.15.2 build

**Comment by S-B99** [comment]
Can you make an issue to fix that?

**Comment by TheK0tYaRa** [comment]
#1486
