### ISSUE TITLE
Baritone won't place blocks

### ISSUE THREAD

**Issue by BlueBurgersTDD** [cabaletta/baritone#1489]
# Information

Operating system: Windows 10
Java version: Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Minecraft version: Minecraft 1.14.4
Baritone version: 1.4.3
Forge mods (if used): None.

# Errors
The log doesnt log any errors at all
# How to reproduce
Give baritone a mission that requires it to place blocks

Baritone tries to place blocks, it just doesn't, it just spam-shifts and goes down from the block. [Video](https://medal.tv/clips/21538558)

In the beginning i placed some blocks manually.

**Comment by S-B99** [comment]
Try pausing it and unpausing it. It's a velocity calculation error.
