### ISSUE TITLE
Killer mode

### ISSUE THREAD

**Issue by marsuh228** [cabaletta/baritone#1490]
## Description
Kill aura + .b follow does not always work properly and when you attack the following just pauses, the player stops and begins to attack (kill aura). What if my player follows a creeper? It will blow up, I think killer mode should do better (go back or use a shield automatically if it is about to blow up).

## Settings
#set killerMode (boolean)
It would work with #follow
#set killEntites (string)
## Context
As devs said, toggle Kill aura + follow for fun time. For bad time I suggest to toggle killer mode.

## c
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I know what am I saying.
- [ ] Welcome to die.

**Comment by StijnSimons** [comment]
This is a feature for Impact, not baritone.
