### ISSUE TITLE
Building schematics is broke

### ISSUE THREAD

**Issue by ZygZagGaming** [cabaletta/baritone#1496]
When I try to build a schematic, Baritone keeps trying to pillar up or complete impossible jumps with carpets and slabs. Please fix!!

**Comment by S-B99** [comment]
Fill out the issue template properly.

**Comment by S-B99** [comment]
Also it will pillar up with whatever valid blocks it has.

**Comment by ZygZagGaming** [comment]
I just meant that it would jump up on the carpet as if it were a full
block, and try to jump on it and place a full block on top of it.

**Comment by S-B99** [comment]
Then open a bug report with the issue template filled out for it.
