### ISSUE TITLE
Clear Area killed by mobs

### ISSUE THREAD

**Issue by VoidedKN0X** [cabaletta/baritone#1497]
## What do you need help with?
everytime i want to clear an area mobs spawn and kills me... is there a feature to auto torch in minecraft 1.15.2? or just kill the mobs that stand in a specefic radius? i've messed around with some settings but nothing helps

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Duplicate of #971
