### ISSUE TITLE
Autotorch not working

### ISSUE THREAD

**Issue by VoidedKN0X** [cabaletta/baritone#1498]
## What do you need help with?
the autotorch isn't a function in baritone with 1.15.2 and impact and that duplicate question doesn't answer mine... so what can i do about it

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
There is no autotorch, so of course it won't work. Issue #971 is a suggestion to add automatic placing for torches.
