### ISSUE TITLE
Schematic autobuild

### ISSUE THREAD

**Issue by VoidedKN0X** [cabaletta/baritone#1499]
## What do you need help with?
everytime i want to build a schematic it goes to a place and just stands there, i can see the blue lines flickering left to right so the ai is thinking but it doesn't build somehow... 
EDIT: just found out it builds from top to bottom, wich command changes that?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
layerOrder
