### ISSUE TITLE
blockReachDistance 

### ISSUE THREAD

**Issue by beginner69-69** [cabaletta/baritone#1502]
## Some information
Operating system:windows 10
Java version:1.8.0_221
Minecraft version:1.12.2
Baritone version:can't dind it it says "nul version (this is normal in a dev enviroment)"
Forge mods (if used): scematica impact

[latest.log](https://github.com/cabaletta/baritone/files/4431306/latest.log)

the problem is if i do the command .b blockReachDistance 3 or #blockReachDistance 3  then it says" [baritone] command not found: blockReachDistance  " or it says "[impact] invalid syntax provided you can view  the usage on github"

## Modified settings
To get the modified settings run `## Final checklist
- [x] I know how to properly use check boxes  
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).no not baritone but the rest yes
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by MajsterTynek** [comment]
You have got outdated version 
where there was no such command. 
It was created after #1121, 
when people started complaing 
about anti-cheat interference.
