### ISSUE TITLE
1.15.2 branch has a major issue with #mine

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1504]
## Some information
Operating system:
Java version: 1.8.0_242
Minecraft version: 1.15.2
Baritone version: 1.5.2
Forge mods (if used): Baritone, MixinBootstrap-1.0.2

## Exception, error or logs
Error at argument #2: Expected aa

## How to reproduce
Type without using TAB #mine 1 minecraft:dirt
Get an exception specified above

## Modified settings
legitMine true
legitMineIncludeDiagonals true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used)
- [ ] I tried to use TAB and with it it works
- [x] I run baritone with forge because I don't know how to run it without forge

**Comment by scorbett123** [comment]
I believe that this has been fixed.
