### ISSUE TITLE
.b Build Log output.

### ISSUE THREAD

**Issue by Liviflame** [cabaletta/baritone#1505]
## Some information
Operating system:Windows 
Java version:1.8.0_231
Minecraft version:1.14.4-Impact_4.8.3
Baritone version:  Not sure which one is in this version of impact.
Forge mods (if used):  N/A

## Exception, error or logs
It is NOT a crash, 
https://pastebin.com/c2BABQ7t
Here is my issue, condensed into its own section in the log. I will post the full thing if requested.

## How to reproduce
Just use the .b build command in baritone from impact, ill be happy to supply the schematic
## Modified settings
impact doesnt recognize this.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue. <-- except for those, i didnt write those.

**Comment by S-B99** [comment]
You're missing the .schematic in the file name
