### ISSUE TITLE
How do you use the standalone version of Baritone?

### ISSUE THREAD

**Issue by ZeLalo** [cabaletta/baritone#1506]
## What do you need help with?
I'm new to using Baritone, but fairly experienced with Windows and Minecraft. But how do I use the prebuilt standalone versions? Do I need to use a modloader or do I do I need to replace files / import files somewhere?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
It depends on the version. For the forge versions just install it as a forge mod, otherwise use a json launch profile.

**Comment by ZeLalo** [comment]
But where do I get the json?

**Comment by dominikaaaa** [comment]
Search this repo.

**Comment by ZeLalo** [comment]
All I see is json for 1.14.4. Where do I get the 1.15.2 one?

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md#more-info
