### ISSUE TITLE
"Unable to do it" when attempting to build a schematic on a multiplayer Creative server

### ISSUE THREAD

**Issue by coreynj** [cabaletta/baritone#1509]
I'm attempting to build using the schematic functionality on a creative server. I have more than enough space, and I have all the required items in my inventory. I have buildinlayers set to true. It started normally and everything seemed fine, however it has hit a point where all it says in chat is "Unable to do it" and will not continue building any further, no matter what I do. I'm running 1.12.2. What's going on? 

Here are the blocks that the schematic contains:
Sand
Dirt
Grass Block
Wooden Trapdoor
Red Stained Glass
Red Glazed Terracotta 
Nether Wart Block
White Concrete
White Concrete Power
Block of Quartz

When viewing the blueprints for the schematic, it appears to have gotten stuck on trying to place a trap door. Is this a common issue?

**Comment by S-B99** [comment]
Fill out the issue template properly please.
