### ISSUE TITLE
How to get The Bot To Only Dig A Chunk

### ISSUE THREAD

**Issue by G12gaming475** [cabaletta/baritone#1510]
## What do you need help with?
I have tried many different things, I am using 1.15.2 no forge. Does anyone know how on earth to get the bot to only mine a chunk? I need this for a slime farm.

## Final checklist
- [x] I know how to properly use checkboxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
`#sel` and `#sel replace air`
