### ISSUE TITLE
Auto put in shulkers etc?

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1515]
## What do you need help with?
Like when mining then make it put the blocks in shulker box and maybe put in ender chest and take new empty shulker? I also saw the a group on 2b2t used a motified version of baritone to make it automatically take ender chests from shulker and break the ender chests to get obsidian to place obisidian? Is it possible a guy like me every could get that program

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Duplicate  #605
