### ISSUE TITLE
Baritone automatic take from chest/shulker/enderchest

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1517]
## What do you need help with?
I saw a group on 2b2t using a version of baritone to make it automatically take ender chests from shulker and break the ender chests to get obsidian to place obisidian? Is it possible a guy like me every could get that program , or anything similar

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Duplicate of #1515 

I marked your other issue as a duplicate because it hasn't been added to baritone.

**Comment by NumseBacon** [comment]
> 
> 
> Duplicate of #1515
> 
> I marked your other issue as a duplicate because it hasn't been added to baritone.

Thats 2 different things I talked about in the first post and that doesnt make any sense that its a duplicate because it hasent been added and u say its duplicate of my other post

**Comment by S-B99** [comment]
It's the same thing.

**Comment by S-B99** [comment]
And it is a duplicate, it's the exact same thing.

**Comment by NumseBacon** [comment]
How is something a group has the same as putting in chests

**Comment by S-B99** [comment]
You'd have literally the exact same code to have baritone store shit in chests vs shulkers. It's the same concept and idea. Even your issue description is copy and pasted.

**Comment by NumseBacon** [comment]
Yep ofc I copied some of the description. So he is working on it?

**Comment by S-B99** [comment]
[????](https://lmgtfy.com/?q=how+does+github+issues+work+)

**Comment by NumseBacon** [comment]
????

**Comment by S-B99** [comment]
click the link ♿♿♿♿

**Comment by NumseBacon** [comment]
U calling me handicapped?

**Comment by NumseBacon** [comment]
damn so he isnt gonna add it

**Comment by S-B99** [comment]
no?? the issue is still open. that doesn't mean it won't be added, it just means it hasn't

**Comment by NumseBacon** [comment]
But I asked if it was possible that a guy like me could get the software that group is using

**Comment by S-B99** [comment]
no?? this is baritone, and it's not implemented in baritone. we don't know what random ass youtube video you were watching.

**Comment by NumseBacon** [comment]
FitMC

**Comment by S-B99** [comment]
i couldn't care less. if it's not in baritone (as shown by the issue being still open) we can't help you with it

**Comment by Aaron2550** [comment]
_that moment when someone asks which video you were watching and you reply with a whole channel_
