### ISSUE TITLE
Take advantage of creative flying?

### ISSUE THREAD

**Issue by matthewfcarlson** [cabaletta/baritone#1518]
## Describe your suggestion
As mentioned in my previous issue #1516 sometimes it has trouble pathing to where it wants to be. 
The bot is on creative, could it query whether the player is in creative and activate flying to get where it wants to be if it can't path there quickly. 

## Settings
Perhaps a switch
allowFlyingIfCreative: boolean

## Context
This would make builds easier

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by matthewfcarlson** [comment]
This is somewhat no longer an issue since I give it some dirt and it was amazing how good it was

**Comment by S-B99** [comment]
0x22's response to using creative mode can be found here, https://github.com/cabaletta/baritone/issues/545, which I guess does slightly defeat the purpose of baritone? It was originally intended to be for survival path finding

**Comment by matthewfcarlson** [comment]
Ah that makes sense. My scenario is a friends server, which I have creative permissions but no mods to place large structures. This seems like a good scenario.

**Comment by matthewfcarlson** [comment]
But I agree- if it's not core to the feature set, leave it out

**Comment by soshimee** [comment]
I'm using a client-side flight mod alongside baritone, but it can't use the flight feature.

**Comment by qtqgyt** [comment]
> I'm using a client-side flight mod alongside baritone, but it can't use the flight feature.

... as he said, baritone cant fly
