### ISSUE TITLE
Done Building

### ISSUE THREAD

**Issue by matthewfcarlson** [cabaletta/baritone#1519]
## Some information
Operating system: Windows 18362
Java version: 8
Minecraft version: 1.15.2
Baritone version: 1.5
Forge mods (if used):  None

## Exception, error or logs
When doing a build command, it pauses as it scans through the world and then says "Done Building" and doesn't move. I'm looking through the NBT explorer and they look the same.

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by matthewfcarlson** [comment]
https://1drv.ms/u/s!Av_7XCX7B5S9icRDmH3zabs_kEs0qg?e=O9jBjL schematic file in question

**Comment by matthewfcarlson** [comment]
[13:57:19] [main/INFO]: [CHAT] [Baritone] > modified
[13:57:19] [main/INFO]: [CHAT] [Baritone] All modified settings:
[13:57:19] [main/INFO]: [CHAT] [Baritone] allowDiagonalDescend (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] allowInventory (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] allowParkour (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] allowParkourPlace (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] allowWaterBucketFall (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] buildIgnoreExisting (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] chatDebug (Boolean)
[13:57:19] [main/INFO]: [CHAT] [Baritone] --
[13:57:19] [main/INFO]: [CHAT] [Baritone] << | >> 1/1

**Comment by matthewfcarlson** [comment]
And yes- I tried messing with buildIgnoreExisting

**Comment by S-B99** [comment]
That would likely be the cause of it, change it back to default.

**Comment by matthewfcarlson** [comment]
Sorry, yes I did toggle that. I've set it to false and it still fails. It is a large structure. When I ask it to build in a complete empty area it, it says done after thinking for a moment

**Comment by matthewfcarlson** [comment]
Let me try building from source and perhaps adding in some debugging. I think I see that 1.5.1 is out and I'm on 1.5

**Comment by thetechlover0010** [comment]
Same issue here https://github.com/cabaletta/baritone/issues/1532

**Comment by 0-x-2-2** [comment]
#1528

**Comment by BackupInventory** [comment]
When I do #litematica command it says >done building and won't start

**Comment by rycbar0** [comment]
> When I do #litematica command it says >done building and won't start

you're building a .nbt schematic. that file format is not supported.
