### ISSUE TITLE
Can't run commands with block parameter. Baritone incompatibility with Advanced Macros.

### ISSUE THREAD

**Issue by MajsterTynek** [cabaletta/baritone#1521]
## Some information
Operating system: Windows10 Version1909 Build 18363.752
Java version: 1.8.0_51 64bit
Minecraft version: 1.12.2-forge1.12.2-14.23.5.2768
Baritone version: 1.2.13
Forge mods (if used): 
- [OptiFine HD Ultra F5](http://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_F5.jar), 
- [Advanced Macros 7.7.7](https://www.curseforge.com/minecraft/mc-mods/advanced-macros) ([Source](https://github.com/TheIncgi/AdvancedMacros-Source))

## Exception, error or logs
`java.lang.IllegalStateException`, [latest_barifail.log](https://github.com/cabaletta/baritone/files/4439575/latest_barifail.log)

## How to reproduce
Create new world with seed `13`.
Do `#mine sand` and `#goto sand`.
Baritone will throw execption `java.lang.IllegalStateException`
`baritone.api.command.exception.CommandUnhandledException:`
Mining will be aborted. Goto will work, but throws anyway.
Selection command family is unaffected by this bug.

**Comment by dominikaaaa** [comment]
Try uninstalling advanced macros, that should fix the issue.

**Comment by MajsterTynek** [comment]
Gotta rebuild Baritone myself then. Thank you. :/

**Comment by MajsterTynek** [comment]
Found the bug...
Baritone forces to run itself onto main Minecraft thread.
Fixed this by putting Baritone iteraction in "sheduled task".
Also suggested AM devs to move chat back onto MC thread.

**Comment by dominikaaaa** [comment]
Minecraft is **not** thread safe. This is a AM issue

**Comment by MajsterTynek** [comment]
For any others who find this issue: Use `runOnMC( say, "#command" )` in macros instead. 
It got implemented in newst versions of AM. Also fix for regular chat will happen too.
