### ISSUE TITLE
Replace with Air is not working correctly

### ISSUE THREAD

**Issue by Whitedoteu** [cabaletta/baritone#1523]
## Some information
Operating system: Win 10
Java version: 1.8.0_241
Minecraft version: 1.15.2
Baritone version: 1.5.1
Forge mods (if used): No

## Exception, error or logs
[latest - Kopie.txt](https://github.com/cabaletta/baritone/files/4446605/latest.-.Kopie.txt)
Windows: `%appdata%/.minecraft/logs/`

## How to reproduce
`#sel replace air cobblestone`
I selected an Area 1x1x1000 and tried to replace all empty blocks with cobblestone

Two unwanted behaviors I found. 

- Removing filled blocks and replace with cobblestone
- Not filling Air blocks.
- There is no error Log in the ChatDebug. Completed Successfully.
![image](https://user-images.githubusercontent.com/16068109/78710734-2417c380-7916-11ea-8c9e-a40ea7157383.png)

[Video](https://transfer.sh/eWQ7S/gP14tMCT7j.mp4)

## Modified settings

- allow DiagonalAscend
- allowDiagonalDescend
- allowInventory
- allowParkour
- allowParkourPlace
- chatControl
- chatDebug
- rendererCachedChunks

also tried without:

- avoidance
- layerOrder
- assumeWalkonWater

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Please add a brief but descriptive title

**Comment by Whitedoteu** [comment]
Edited the Description.
