### ISSUE TITLE
Error when using "#tunnel" for custom tunnel sizes

### ISSUE THREAD

**Issue by Bocal2** [cabaletta/baritone#1524]
## Some information
Operating system: Windows 10
Java version: Java 8 Update 321
Minecraft version: 1.15.2
Baritone version: 1.15.2
Forge mods (if used):  None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[16:29:34] [main/INFO]: [CHAT] [Baritone] > tunnel 3 3 10
[16:29:34] [main/INFO]: [CHAT] [Baritone] Too many arguments (expected at most 0)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
"#tunnel -" (any three digits following the word tunnel, i.e. "tunnel 5 5 100")
This could be a simple oversight on my part, if so a quick explanation as to my error would be greatly appreciated.  
## Modified settings
To get the modified settings run `#modified` in game
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You're using an outdated version.

**Comment by Bocal2** [comment]
> You're using an outdated version.

I received the version I'm using from the dropbox link provided in [this](https://www.youtube.com/watch?v=j1qKtCZFURM) YouTube video.  If this is not the current version, would you please direct me to the correct location?

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/releases

**Comment by dominikaaaa** [comment]
As you can see, https://github.com/cabaletta/baritone/pull/1332 was merged on Feb 27th and the video was uploaded on Feb 14th

**Comment by Bocal2** [comment]
> https://github.com/cabaletta/baritone/releases

Thank you, my level of incompetence surprises even me at times.  I would strongly suggest that the link to either the Dropbox or the YouTube video be removed from the main page though, as I'm sure many dolts such as myself will get confused.

**Comment by dominikaaaa** [comment]
Eh that's the official dropbox. The pre releases always have a dropbox link.

**Comment by dominikaaaa** [comment]
You will have to build it yourself, as the last official release was on the 25th, 2 days before it was merged, meaning that there isn't a prebuilt release for custom tunnelling.

**Comment by Bocal2** [comment]
> You will have to build it yourself, as the last official release was on the 25th, 2 days before it was merged, meaning that there isn't a prebuilt release for custom tunnelling.

If it's not too much trouble, may I ask where I might learn to "build it myself?" Does such a system function as a schematic?  Or sort of a reverse-schematic?

**Comment by dominikaaaa** [comment]
It's not like an in game thing, you have to create the file yourself. You can find instructions here: https://github.com/cabaletta/baritone/blob/master/SETUP.md (see the Built it Yourself section)

**Comment by Bocal2** [comment]
> It's not like an in game thing, you have to create the file yourself. You can find instructions here: https://github.com/cabaletta/baritone/blob/master/SETUP.md (see the Built it Yourself section)

My apologies for bothering you again.  I reviewed the link you provided and decided that, without several hours I don't have to tinker, it's beyond my abilities at this time; but I wanted to inquire as to if there was a version lurking somewhere on the web for 1.15.2 that did include the tunneling?  It is, at this time, the only feature with which I have a heavy interest in?  Again, my apologies for taking up more of your time.

**Comment by dominikaaaa** [comment]
Um, remind me tomorrow and I can build a copy for you

**Comment by StijnSimons** [comment]
Ez rat

**Comment by dominikaaaa** [comment]
ezz

**Comment by StijnSimons** [comment]
Botnet prepared nerddt!! Ez hack

**Comment by StijnSimons** [comment]
Oops
