### ISSUE TITLE
Doesn't use axe for leaf blocks

### ISSUE THREAD

**Issue by matthewfcarlson** [cabaletta/baritone#1525]
## Some information
Operating system:
Java version: 8.241
Minecraft version: 1.15.2
Baritone version: master (as of yesterday)
Forge mods (if used): a few

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Normally, baritone is quite good about selecting to tool that will get the job done. 
However, it was using a dirt block to mine the leaf blocks, which seems a little strange.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Does it use shears if you have them?

**Comment by HexCodeFFF** [comment]
axes dont mine leaf blocks faster

**Comment by matthewfcarlson** [comment]
It doesn't. Interesting. Ah- the axe is enchanted. My bad.

**Comment by dominikaaaa** [comment]
Because iirc it just uses Minecraft math to determine what's fastest. Also the title is confusing.

**Comment by dominikaaaa** [comment]
Ah lol

**Comment by matthewfcarlson** [comment]
@dominikaaaa also yes- it does use shears if I have them
