### ISSUE TITLE
"java.lang.NoClassDefFoundError: ain" when calling "BaritoneAPI.getProvider()"

### ISSUE THREAD

**Issue by SamHDev** [cabaletta/baritone#1526]
Hello, I'm an in-experienced java developer who doesn't know what the f*ck I'm doing. I'm making this issue under the request of a discord member within the Impact Server.

I'm trying to use the BaritoneAPI within a forge mod (1.12.2) however I get this error when executing the following code:
```java
IBaritoneProvider provider = BaritoneAPI.getProvider();
IBaritone baritone = provider.getPrimaryBaritone(); ICustomGoalProcess process = baritone.getCustomGoalProcess();
process.setGoal(new GoalBlock(x, y, z));
process.path();
```
```
 java.lang.NoClassDefFoundError: ain
 	at baritone.api.Settings.<init>(Unknown Source)
 	at baritone.api.BaritoneAPI.<clinit>(Unknown Source)
 	at shd.bachitone.net.BachitoneServer.clientHandler(BachitoneServer.java:250)
 	at shd.bachitone.net.BachitoneServer.serverAcceptLoop(BachitoneServer.java:263)
 	at shd.bachitone.net.BachitoneServer$2.run(BachitoneServer.java:280)
 	at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.ClassNotFoundException: ain
 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
 	... 6 more
 Caused by: java.lang.NullPointerException
```
I presume that is cause by importing `BaritoneAPI` or using `BaritoneAPI.getProvider())` without baritone within my classpath? (I have no idea what I'm doing) 
I'm using the `baritione-api-forge.1.2.13.jar ` within my project libraries, but If i place the standalone or standalone-forge within my libraries it does not work, and If I place any baritone jar, forge or not within the mods directory I get more errors.

Any help would be greatly appreciated.
Thanks 
-Sam

## Final checklist
- [ x ] I know how to properly use checkboxes 
- [ x ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Because you're using a jar with obfuscated mappings against a testing development, clearly not obfuscated.

**Comment by SamHDev** [comment]
So how would I fix this? From my limited knowledge, obfuscation takes functions/classes and renames them to smaller terms. Would I de-obfuscate the jar, How would that happen?

**Comment by dominikaaaa** [comment]
Um, don't run the obfuscated jar, or disable obfuscation in your build.gradle entirely

**Comment by StijnSimons** [comment]
`gradlew jar`.....

**Comment by HexCodeFFF** [comment]
I'm having the same issue using forge-api or unoptimized
baritone is included via `compile fileTree(dir: 'libs', include: ['*.jar'])` in build.gradle (jar is in `libs/`)
im also new with forge

**Comment by StijnSimons** [comment]
Just generate a jar without obfuscated mapping using `gradlew jar` and use that one as dependency???

**Comment by StijnSimons** [comment]
Duplicate of #853 iirc.

**Comment by HexCodeFFF** [comment]
still crashing but its a different bug lol so fixed i guess?
I'll open a new question
