### ISSUE TITLE
Blocks with block data don't work in schematics above 1.12.2

### ISSUE THREAD

**Issue by royaljjj** [cabaletta/baritone#1528]
## Some information
Operating system: Windows 10
Java version: Version 8 (build 1.8.0_241-b07)
Minecraft version: 1.15.2
Baritone version: 1.2? (the one that's from https://www.youtube.com/watch?v=j1qKtCZFURM)
Forge mods (if used):  none

Basically the game lags out for a seconds and I get the following message but nothing actually builds:
![image](https://user-images.githubusercontent.com/63326124/78734135-6bea1b00-7915-11ea-945c-1a6916f56308.png)

Surprisingly, the exact same schematic (except it's made out of obsidian) works perfectly.
https://drive.google.com/file/d/1fWJJq8yzLa0fqMdSiYaUiz10MSv2ieMJ/view?usp=sharing

This is probably because obsidian does not have block data, where as planks do. It also doesn't work for normal planks as well. (which have block data of 0)

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/4447669/latest.log)

## How to reproduce
Load baritone 1.15.2
Download wood4.schematics
Download here: https://drive.google.com/file/d/1HxgL3FEPHZVjdgERSIB-D_wB3Rkz68Wn/view?usp=sharing

Enter build command

## Modified settings

allowinventory:true
allowParkourPlace:true
buildInLayers:True
chatControl:false
LegitMine:true
mobAvoidanceRadius:20

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by royaljjj** [comment]
Basically the game lags out for a seconds and I get this happening but nothing actually builds:
![image](https://user-images.githubusercontent.com/63326124/78733970-fc742b80-7914-11ea-81fb-c21e6ab529e9.png)

**Comment by matthewfcarlson** [comment]
I've seen this as well (See issue #1519) I've tracked it down to schematics that use blocks that have data elements (for example wood and in my case concrete)

**Comment by matthewfcarlson** [comment]
cubical.xyz is great for modifying schematic files and you easily replace the obsidian with planks

**Comment by royaljjj** [comment]
> cubical.xyz is great for modifying schematic files and you easily replace the obsidian with planks

While it does work for replacing it, the baritone still refuses to build the schematic. I decided to build it out of cobblestone instead since there is no block data associated with that.

**Comment by matthewfcarlson** [comment]
Yeah that's what I did. Just build it out of something without block data and just use a /fill command on the server to replace it to the end result.

**Comment by dominikaaaa** [comment]
@royaljjj could you change the title to something like "Blocks with block data don't work in schematics above 1.12.2" (as iirc 1.12.2 works fine with these)

**Comment by royaljjj** [comment]
> @royaljjj could you change the title to something like "Blocks with block data don't work in schematics above 1.12.2" (as iirc 1.12.2 works fine with these)

Yep changed

**Comment by royaljjj** [comment]
> Yeah that's what I did. Just build it out of something without block data and just use a /fill command on the server to replace it to the end result.

Unfortunately, I'm unable to do that because it's a survival server. Otherwise I would've pasted it with world edit which has no issues from what I can gather.

**Comment by 0-x-2-2** [comment]
Metadata is not preserved with the legacy mcedit format on 1.13+: https://github.com/cabaletta/baritone/blob/b9a7efc25bdcaabc9d9e5add025ac9b5bb507574/src/main/java/baritone/utils/schematic/format/defaults/MCEditSchematic.java#L68. 

Use sponge format schematic created by modern WorldEdit or have default block type in inventory.
