### ISSUE TITLE
Baritone Causing Game To Crash

### ISSUE THREAD

**Issue by Manaball123** [cabaletta/baritone#1530]
Every time I use an baritone related command(autowalk, .b mine etc.) my game crashes.
[crash-2020-04-09_08.34.57-client.txt](https://github.com/cabaletta/baritone/files/4453408/crash-2020-04-09_08.34.57-client.txt)

**Comment by StijnSimons** [comment]
| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | ruhama    | 0.7          | Ruhama_0.7.jar                | None                                     |
Ruhama???

**Comment by dominikaaaa** [comment]
That's the issue lol.
