### ISSUE TITLE
IRC bot control

### ISSUE THREAD

**Issue by yellowishBlue** [cabaletta/baritone#1534]
## Describe your suggestion
Basically the idea is that you have other accounts running Baritone, and using your main one you can send commands to the rest. (i.e. You are on your main account, and you want all the bots to go to you or make the bots go to specific coordinates, without manually pasting in the commands.)

## Settings
ircPassword
ircIP
ircPort

## Context
Imagine having 10 combat bots, and you want all of them to go to a specific direction, change a setting for all of them. You could do that with just running a command like "irc-exec-all {command}" instead of manually typing the command in for all the accounts..

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This is already a thing tho

**Comment by yellowishBlue** [comment]
then where is it? i can't seem to find it anywhere

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/tree/bot-system

**Comment by flae7** [comment]
how do you even use this, just build it and then what
