### ISSUE TITLE
Bot-system usage

### ISSUE THREAD

**Issue by flae7** [cabaletta/baritone#1537]
## What do you need help with?
I want to setup my bot-system. What I've done so far is I built Baritone from here https://github.com/cabaletta/baritone/tree/bot-system and figured out it runs only on 1.12.2 Forge. So I moved the built file (baritone-standalone-forge-1.2.13), ran the game and i have no clue how to use the bots. I tried searching for commands, none of them were associated to the bots. If anyone could help me, or tell me how to use them properly, i would be really thankful.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by flae7** [comment]
NVM, stupid me cloned the MASTER branch, instead of the bot-system branch. epic

**Comment by flae7** [comment]
so it turns out the mod doesn't actually work on both 1.12.2, 1.14.4... basically i put the correct jar file into the mods folder, launched the game on both versions and none of them worked. (any command didn't work, just posts the command into chat)

**Comment by dominikaaaa** [comment]
Make sure you're running the standalone forge release jar.

**Comment by flae7** [comment]
i am 100% sure i'm running the standalone forge release jar.

**Comment by flae7** [comment]
![obraz](https://user-images.githubusercontent.com/51024668/79002544-fb2f4280-7b50-11ea-8ff9-a9786524f82b.png)

my mods folder, and in game (1.12.2 forge) none of the commands work, but they're posted in chat instead

**Comment by flae7** [comment]
btw, is it normal that
![obraz](https://user-images.githubusercontent.com/51024668/79005079-662f4800-7b56-11ea-86c0-21d37c3bee3c.png)
there's no forge jar file in the versions folder?

**Comment by flae7** [comment]
i tried 1.12 instead of 1.12.2, the only difference is that the game crashes **INSTANTLY**. i tried reinstalling forge, rebuilding baritone and none of them worked...

**Comment by 0-x-2-2** [comment]
dev branch

**Comment by GunnerBasil** [comment]
wdym?

**Comment by dominikaaaa** [comment]
it is a development branch and is unsupported

**Comment by GunnerBasil** [comment]
ik.

**Comment by GunnerBasil** [comment]
I'd like to contact the dev and ask him how to use it though.

**Comment by dominikaaaa** [comment]
You don't. I already told you how in your own issue anyways.

**Comment by GunnerBasil** [comment]
I know.
