### ISSUE TITLE
How to properly implement baritone into a MCP client

### ISSUE THREAD

**Issue by BradTheGoose** [cabaletta/baritone#1538]
Tile says it, I've tryed to port baritone into my 1.12.2 mcp client by copy-pasting all the circled classes & directories https://prnt.sc/rwovqd then I've fixed all the errors and "translated" mixin classes into minecraft code.
Is this enough to have it to work? am I missing anly classes? is this the best way to get beritone into my client? 
Right now it doesn't work tho, I'm getting a NoSuchElementException when starting up:  https://prnt.sc/rwoyg6 the code only reaches the provider then crashes. 
Could it be an error from what I've done or am I missing some clesses? 
(I've left out BaritoneTweaker.java as it seems to be only used to start baritone from intellij, maybe im wrong idk)

**Comment by scorbett123** [comment]
You won't be able to get help with this here.
