### ISSUE TITLE
How to use baritone's api GoalGetToBlock ?

### ISSUE THREAD

**Issue by DiamondLink** [cabaletta/baritone#1539]
## What do you need help with?
I'm making a mod using baritone api, but I can't find out how to use GoalGetToBlock : 

https://baritone.leijurv.com/baritone/api/pathing/goals/GoalGetToBlock.html

Anyone knows how to use that ?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
![2020-04-11-090549_519x175_scrot](https://user-images.githubusercontent.com/17222512/79044539-a5e84500-7bd3-11ea-8a08-32b64d28670b.png)

**Comment by DiamondLink** [comment]
Yeah but I get this erorr
![error](https://user-images.githubusercontent.com/59293428/79145980-df7ea300-7dc1-11ea-9d04-f05e39e06d53.png)
Am I missing something ?

**Comment by DiamondLink** [comment]
I gonna open a new issue
