### ISSUE TITLE
Baritone wierd Handling of Stairs/Slabs/Doors

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1540]
## Some information
Operating system: linux
Java version: 8
Minecraft version: 1.15.2
Baritone version: 1.4.5 (fabritone)

## How to reproduce
make baritone take a route with stairs in the way and Baritone will jump at every stair
Baritone tryin to jump on block, that cannot be reached cause of standin on slab
Baritone gettin stuck at door when path goes through

## Modified settings
DiagonalAscend
inventory
Jumpat256
parcour
parcorplace
vined
chatdebug
clientmode
goalbreakfromabove
legitmineincludediagonals
renderpathasline

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
This is not the Fabritone issue tracker please reproduce with upstream instead.

**Comment by JamesTheAwesomeDude** [comment]
This bug still applies in version 1.6.3, can it be re-opened?
