### ISSUE TITLE
Ability to list blocks in #sel replace

### ISSUE THREAD

**Issue by fw4hre0xxq** [cabaletta/baritone#1542]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

I'd like the ability to list multiple types of blocks for #sel replace. Right now if I want to replace all the dirt and grass in a selection with air, I'd have to run two different #sel commands or possibly more since if I do dirt first I'm left with floating grass that then has to be pillared up to to be removed, or run multiple passes to handle grass spread.

Desired syntax would be something like `#sel replace dirt.grass air` or `#sel replace (dirt grass) air` for the above example. 

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by sportshead** [comment]
To go with the World Edit theme, syntax should probably be `#sel replace dirt,grass air`

**Comment by dominikaaaa** [comment]
I feel this should be closed in favor of #708 and have it implemented with that, as it's pretty much the same request.
