### ISSUE TITLE
#sel replace on large areas can sometimes freeze client

### ISSUE THREAD

**Issue by fw4hre0xxq** [cabaletta/baritone#1543]
## Some information
Operating system: Win 10 x64
Java version: OpenJDK 8 Corretto 1.8.0_242
Minecraft version: 1.12.2
Baritone version: 1.2.12
Forge mods (if used): 

I'm not sure if this even qualifies as a bug, but when doing `#sel replace` on large areas, aprox. 500x500x100 larger, can cause minecraft to completely freeze for several seconds. The effect seems to be intensified when the block to be replaced is rare or non-existent in the selected area, and when render distance is low.

**Comment by UltraBlackLinux** [comment]
Hm I rather think this is a gpu issue...
Mc has to render 250000 green squares...

**Comment by dominikaaaa** [comment]
Closing as won't fix, this isn't really a bug.
