### ISSUE TITLE
Baritone continue after leaving server

### ISSUE THREAD

**Issue by domitp20** [cabaletta/baritone#1544]
Hello, i wanted to build a big house in survival in a server,  is there any command that if i leave the server, that baritone continues there where i lefted the server?
Because, i write .b pause. Then i leave the world, and then i write .b resume, but  nothing happends. Is there any command for that?

**Comment by dominikaaaa** [comment]
Duplicate of #1007

**Comment by domitp20** [comment]
But there is no answer wtf??
