### ISSUE TITLE
Favorite commands

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1551]
## Describe your suggestion
you can set and execute favorite commands
## Settings
save: #fav add <name> <baritone command>
e.g. #fav add iron mine iron_ore

delete: #fav delete <name>

execute: #fav <name> 
e.g. #fav iron

list: #fav list
(shows list of commands, clickable to execute)

show: #fav show <name>
(shows command of fav)

## Context
makes quick execution of baritone commands easier, e.g. instead of typing #mine coal_ore iron_ore gold_ore emerald_ore redstone_ore  diamond_ore, you type: #fav mineores

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Use impact macros or see this issue #881
