### ISSUE TITLE
Is there a way to make baritone persistant when a server is lagging.

### ISSUE THREAD

**Issue by sabian149-uk** [cabaletta/baritone#1553]
Is there a way to make baritone continue to walk in a direction continuously until it stops manualy or if it is not possible at all? I have found on some laggy server, or at time when my ping high, baritone will walk up to the edge of a chunk where no other chunks are loaded and then just stop and give up and wont restart after when the chunks are loaded again. Is there any work around or a solution to fix this?

I dont want to write a script just to have the function of spamming the command in game when something can be implemented easily to fix this problem.

**Comment by dominikaaaa** [comment]
Nope

**Comment by sabian149-uk** [comment]
thanks for that very useful
