### ISSUE TITLE
Schematica 'not present' in 1.15.2 download

### ISSUE THREAD

**Issue by smalls24** [cabaletta/baritone#1555]
## What do you need help with?
I have downloaded Baritone 1.15.2 from the [YouTube link](https://www.youtube.com/watch?v=j1qKtCZFURM) on the main GitHub page. After some research I was still not able to find a way to upload schematics into the game files. I tried making a folder labelled 'schematica' and putting it in there. When I tried to run the command "#build modern-house-2" it says "couldn't load the schematic", and when I use "#schematica" it says "Schematica is not present". Would I have to download schematica separately and somehow put it into baritone, if so how?
Thank you

**Comment by dominikaaaa** [comment]
You need to include the full file name for building. Also schematica doesn't exist for 1.15
