### ISSUE TITLE
Baritone wants to mine Block outta the Worldborder

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1557]
## Some information
Operating system: linux
Java version: 8
Minecraft version: 1.15.2
Baritone version: 1.5.2
Forge mods (if used): none

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
place block, shrink wb further that block, make block only available outta wb - go mine it. Baritone will highight and go for the block

## Modified settings
diagonal ascend/ descend
parcour
jump at 256
parkourplace

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I don't think there is a bug here
It just does not check  the worldborder when searching the blocks and simply marks them as unreachable later

**Comment by dominikaaaa** [comment]
Yea, this isn't really a bug
