### ISSUE TITLE
Block Highlight

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1558]
## Describe your suggestion
searched blocks would be highlighted
## Command
#search entity/block (entity/block...)

## Context
would show blocks, but not mine em - for situations where u dont want the blocks to be mined by baritone, you can do it by yourself

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Select already does this.

**Comment by UltraBlackLinux** [comment]
oh
well
