### ISSUE TITLE
Baritone schematic build not working

### ISSUE THREAD

**Issue by Gizzy226** [cabaletta/baritone#1564]
## Some information
Operating system: 18363.720
Java version: 8
Minecraft version: 1.13.2
Baritone version: I think the latest version, Im not sure which version impact uses
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/

[2020-04-14-4.log](https://github.com/cabaletta/baritone/files/4477281/2020-04-14-4.log)

`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Your log doesn't even open Minecraft, the log you attached is Minecraft crashing before you can even try building the schematic.

**Comment by Gizzy226** [comment]
> Your log doesn't even open Minecraft, the log you attached is Minecraft crashing before you can even try building the schematic.

I attached the latest log of minecraft. Do you know a reason of why its crashing or how I can fix it?

**Comment by dominikaaaa** [comment]
No, latest.log is the name of the log. Your issue wasn't reporting a game crash, it was reporting building not working, so clearly you attached the wrong log.
