### ISSUE TITLE
Baritone work in conjunction with AdvancedMacros for script writing

### ISSUE THREAD

**Issue by acesblue** [cabaletta/baritone#1565]
## Describe your suggestion
I would love it if baritone wouldnt cause issues while AdvancedMacros is suggesting what to do. For example I send ".mine dirt" ,from an AdvancedMacros script, and baritone returns an error.
If someone could implement these to work together better that would be awsome.  

## Settings
Possibly a ui interface custom built for communication of the mods.

## Context
The combination of these two mods together could completely change what is possible on an individual scale, person to person, and could open up many doors for what the people want to create.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
See #448 and #881
