### ISSUE TITLE
Baritone not working in the conjunction with AdvancedMacros

### ISSUE THREAD

**Issue by acesblue** [cabaletta/baritone#1566]
## Some information
Operating system: Windows 10
Java version: 1.12.2
Minecraft version: forge 1.12.2-14.23.5.2847
Baritone version: Impact-4.8.3-1.12.2
Forge mods (if used): AdvancedMacros

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: [`~/.minecraft/logs/`]

Windows: `
[debug.log](https://github.com/cabaletta/baritone/files/4477418/debug.log)
`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
type #mine log 

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by acesblue** [comment]
advancedmacros-7.7.7b.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
OptiFine_1.14.4_HD_U_F5.jar
Schematica-1.12.2-1.8.0.git-universal.jar

**Comment by dominikaaaa** [comment]
Fill out the issue template properly please.

**Comment by acesblue** [comment]
> 
> 
> Fill out the issue template properly please.

I thought I filled it out properly.

**Comment by dominikaaaa** [comment]
I can't figure out what the issue is from the information provided. Also, that's not a baritone issue, if it's fixed by removing AdvancedMacros.
