### ISSUE TITLE
Baritone Auto build schematics not working.

### ISSUE THREAD

**Issue by Gizzy226** [cabaletta/baritone#1567]
## Some information
Operating system: 18363.720
Java version: 8
Minecraft version: 1.13.2
Baritone version: I think the latest version, Im not sure which version impact uses
Forge mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
(I think this is the right one now)
[2020-04-14-5.log](https://github.com/cabaletta/baritone/files/4477421/2020-04-14-5.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Include the full file name in the command.
