### ISSUE TITLE
Baritone not working with AdvancedMacros

### ISSUE THREAD

**Issue by acesblue** [cabaletta/baritone#1568]
## Some information
Operating system: Windows
Java version: 1.12.2
Minecraft version: 1.12.2
Baritone version: 4.8.3
Forge mods (if used): 
advancedmacros-7.7.7b.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
OptiFine_1.14.4_HD_U_F5.jar
Schematica-1.12.2-1.8.0.git-universal.jar

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows: `
[latest.log](https://github.com/cabaletta/baritone/files/4477463/latest.log)
`

## How to reproduce
Use AdvancedMacros and type #mine log and it produces the error
It is fixed by removing AdvancedMacros but I would like to know what baritone is doing

## Modified settings
None

## Final checklist
- [ ] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Try uninstalling AdvancedMacros, that should fix the issue.
