### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CPTProgrammer** [cabaletta/baritone#1571]
### Proguard error when building Baritone 1.2.13 & 1.2.11
I have built the Baritone project for several times, but it failed all the time.

Build with Stack trace:
![image](https://user-images.githubusercontent.com/46586216/79287749-5ff2f000-7ef7-11ea-8365-1ec3830e6130.png)
![image](https://user-images.githubusercontent.com/46586216/79287760-684b2b00-7ef7-11ea-8bcc-a8a879763ae3.png)
![image](https://user-images.githubusercontent.com/46586216/79287770-700acf80-7ef7-11ea-8386-c014e0a7bdf6.png)

### Java
![image](https://user-images.githubusercontent.com/46586216/79287352-17870280-7ef6-11ea-9c61-081384ffa44d.png)

_My English is not good XD_

**Comment by CorruptedSeal** [comment]
See https://github.com/cabaletta/baritone/pull/1873
