### ISSUE TITLE
How do i use the baritone-standalone.jar?

### ISSUE THREAD

**Issue by Harry989** [cabaletta/baritone#1574]
## What do you need help with?
I wanna make my own standalone builds, it would be very helpful if anyone would like to help. and yes, i'm terrible at asking questions. ;-;
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Read this https://github.com/cabaletta/baritone/blob/master/SETUP.md
