### ISSUE TITLE
Hunt command not working.

### ISSUE THREAD

**Issue by MajeMack25** [cabaletta/baritone#1577]
I have been trying 

to use baritone for the hunt feature automatically but it won't even attack anyone, even mobs!
![Mods](https://user-images.githubusercontent.com/49461218/79409676-869f3e00-7f6c-11ea-8b89-af92fd892203.png)

**Comment by dominikaaaa** [comment]
fill out the issue template properly.

**Comment by MajeMack25** [comment]
I meant is there a way to enable hunting for baritone? I tried with the impact Client mod but it was not working.

**Comment by dominikaaaa** [comment]
fill out the issue template properly.

**Comment by MajeMack25** [comment]
But you said it for the second time. I am not trying to be rude but I just need help to solve my problem and all I am saying is, the hunting feature is not working properly. Every time I turn hunting on, my character still doing nothing. Even though I enabled passive it doesn't work. I was just wondering if there is a fix.

**Comment by dominikaaaa** [comment]
nobody can help you solve the problem if they don't have more information.

**Comment by MajeMack25** [comment]
How about I send you a video?

**Comment by dominikaaaa** [comment]
you can fill out the template with the requested information.
