### ISSUE TITLE
Follow players at long distance

### ISSUE THREAD

**Issue by alpal283** [cabaletta/baritone#1578]
I need help with the baritone bot following players that are quite far away. In a 200x200 world border, there were 3 players. The bot had a hard time pathfinding players close to the worldborder unless I manually walked the bot closer to them. I'm using Impact btw, and I can't find an option in baritone or impact that increases the range that players are rendered or tracked. I also have a feeling this might be Impact's problem as player tracers and ESPs don't work beyond a certain distance.

**Comment by dominikaaaa** [comment]
This is because they're not in the render distance
