### ISSUE TITLE
What do region file names represent? (r.10.2.bcr)

### ISSUE THREAD

**Issue by nombrekeff** [cabaletta/baritone#1581]
## What do you need help with?
Hey, I was just wondering what the numbers in the cached region file represent, are they the chunk coordinates? or do you group more than 1 chunk into one region? If so how big are these regions?

PD: I've searched this but with no success, so I asked here If there is an online resource I will check it there!

Cheers!

**Comment by nombrekeff** [comment]
I found a reference to this on the code, it is here if anybody else needs it:

https://github.com/cabaletta/baritone/blob/580ba607626c752c73164765711743f63fe2e83d/src/api/java/baritone/api/cache/ICachedRegion.java#L30

region sizes are 512x512 blocks

**Comment by nombrekeff** [comment]
I needed this to be able to get back to a death point xD 

I forgot to activate logging death coordinates on Impact. So this region files have saved me :P

**Comment by 76max** [comment]
> I needed this to be able to get back to a death point xD
> 
> I forgot to activate logging death coordinates on Impact. So this region files have saved me :P

Can you explain how you did this? I'm in a bit of trouble here lol
