### ISSUE TITLE
Disable certain block breaking

### ISSUE THREAD

**Issue by UpsidePlayz** [cabaletta/baritone#1582]
Would be nice if i can make auto mine avoid breaking a certain block, i tried using .b blocksToAvoidBreaking stone,cobblestone but when i turn on automine it continues breaking through them. Would be also good if we can set a list of blocks baritone CAN mine.

**Comment by dominikaaaa** [comment]
It's *avoid* for a reason. Also you can set blacklists / whitelists.

**Comment by henrydatei** [comment]
How do I set a blacklist?
