### ISSUE TITLE
Too many arguments (expected at most 0)

### ISSUE THREAD

**Issue by UpsidePlayz** [cabaletta/baritone#1583]
Question:
I tried blacklisting stone while auto mining but it did nothing and instead said "Too many arguments (expected at most 0)". Am i doing something wrong or is it a bug?

**Comment by dominikaaaa** [comment]
Send the actual command that you ran.

**Comment by UpsidePlayz** [comment]
.b blacklist stone,cobblestone

**Comment by ScanmanTM** [comment]
Cause it doesn't take arguments retard. 
![image](https://user-images.githubusercontent.com/46611235/79600885-caff1b00-80df-11ea-9135-50ec929b2c72.png)

**Comment by dominikaaaa** [comment]
A `blacklist` command doesn't exist.

**Comment by dominikaaaa** [comment]
Oops, didn't mean to reopen this, and my page was cached so I didn't see Scan's response :/
