### ISSUE TITLE
Chat Logging & Chat Tweaks Mod

### ISSUE THREAD

**Issue by Infinidoge** [cabaletta/baritone#1584]
## What do you need help with?
I am attempting to use the [Chat Tweaks](https://www.curseforge.com/minecraft/mc-mods/chat-tweaks) mod to filter client messages into a separate tab (namely, using the RegEx `\[.*\].*`), for the purposes of separating out Impact and Baritone messages. However, I have noticed that while the mod is installed, Baritone does not print any messages to chat at all, while still functioning.

Are there any possible fixes, or should this be reported as a bug under Chat Tweaks or Baritone?
Based on the settings, using a different `logger` may be an applicable fix, however, I am not sure.

The RegEx and mod works for the Impact messages, at least. I have also noticed that Impact messages don't show up in the minecraft log at all.

[Log](https://paste.ee/p/bVChD)
<details><summary>Screenshot of Chat</summary>
<img  src="https://user-images.githubusercontent.com/22727114/79600901-ee14d500-80b5-11ea-8dd7-4eb2581262a6.png"  alt=""  /> 
(Corresponds to the "Hello" in the log file)
</details>

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This isn't baritone's fault, the mod you're using doesn't listen to the same chat baritone logs to.

**Comment by Infinidoge** [comment]
Thanks, will report in Chat Tweaks then
