### ISSUE TITLE
Adding preferFortune or preferTool

### ISSUE THREAD

**Issue by CoolGuy64** [cabaletta/baritone#1585]
Hi,
This is just a suggestion as I really like the capabilities of Baritone. This is basically just a suggestion to add a setting that allows a user to choose whether or not they want a tool to be used in most activities (like in #farm) or just to prefer fortune when doing any of the possible actions in #mine. 

Thanks for checking this out and creating this mod, it's awesome! 

-CoolGuy

**Comment by dominikaaaa** [comment]
This is already a thing.
