### ISSUE TITLE
Where is schematic's origin point?

### ISSUE THREAD

**Issue by Whatwaq** [cabaletta/baritone#1587]
So basically I was building [this](https://www.minecraft-schematics.com/schematic/3816/download/) schematic using Baritone on my friend's minecraft server, when halfway through building he had to go and close the server. Before I disconnected I put Baritone on #pause. When I reconnected the next day however, #resume didn't seem to work, even when though I was in generally inside the unfinished build (It gave the error Not Paused). When I tried to use the #build the-venus-project.schematic command, it started to destroy parts of the unfinished build and started building within the unfinished build. While this issue could be an enhancement request for a #resumebuild command, I just wanted to ask how do I find the origin point of a schematic? How does baritone choose it? If I could find the origin point of the schematic and the go there physically, use the #build command, Baritone should probably be able to finish the unfinished build. Thanks.

**Comment by dominikaaaa** [comment]
You can't resume between reconnects. The origin is where you're standing from the beginning point in the schematic. Also build has this setting already `buildIgnoreExisting` so you can resume between disconnects without breaking everything.

**Comment by Whatwaq** [comment]
Thank you for your reply. I understand that the origin block in the world is where I am standing on. However, it seems as if I had phrased my question incorrectly, I wanted to ask where the origin point of a schematic was relative to the schematic, not the world. For example, if the schematic I wanted to build was a 5x1x5 platform, would the origin point of the schematic be the centre of the platform, the bottom left, bottom right, or what? Thanks.

**Comment by dominikaaaa** [comment]
The origin point of the schematic is probably the positive x / y corner
