### ISSUE TITLE
Can't build from IntelliJ or Command Line because of Java error

### ISSUE THREAD

**Issue by LowlyDev** [cabaletta/baritone#1590]
When trying to build from either IntelliJ or Command Line I get these errors:
`> Task :buildSrc:compileJava FAILED
C:\Users\xxxx\Downloads\Baritone\buildSrc\src\main\java\baritone\gradle\task\CreateDistTask.java:22: error: package javax.xml.bind does not exist
import javax.xml.bind.DatatypeConverter;
                     ^
C:\Users\xxxx\Downloads\Baritone\buildSrc\src\main\java\baritone\gradle\task\CreateDistTask.java:80: error: cannot find symbol
            return DatatypeConverter.printHexBinary(SHA1_DIGEST.digest(Files.readAllBytes(path))).toLowerCase();
                   ^
  symbol:   variable DatatypeConverter
  location: class CreateDistTask
Note: C:\Users\xxxx\Downloads\Baritone\buildSrc\src\main\java\baritone\gradle\task\ProguardTask.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You need to setup your workspace first.
