### ISSUE TITLE
avoidance not working with slimes

### ISSUE THREAD

**Issue by SylveonBottle** [cabaletta/baritone#1592]
Large slimes on the path reck baritone

![image](https://user-images.githubusercontent.com/17802843/79678940-50f59180-81c6-11ea-83f9-59072c8caa2b.png)

**Comment by scorbett123** [comment]
I can't reproduce this on the latest version, it may be that the slimes have jumped into the path since it last calculated the path, in that case the best thing to do would be to increase the mob avoidance radius.

**Comment by SylveonBottle** [comment]
If avoidance is meant to avoid mobs, would it not be beneficial for avoidance to also check the stale path for any mobs while pathing? 
If a skeleton walks into your range, just path around it. We shouldn't have to have an avoidance of 100 blocks just to prevent this

**Comment by scorbett123** [comment]
Really it should, however I don't think that is the main issue here. Normally mobs don't enter the path like they do when you are on a super flat world, however that is a separate issue to this, I think. I have managed to path through slime chunks no problem, so it isn't that it doesn't work with slimes in any case.

**Comment by SylveonBottle** [comment]
In that case, shall one of us make a feature request about Avoidance checking mobs on the path every 5 seconds or so?

If the user wants to avoid mobs, and they have "avoidance" enabled, I'm sure they would appreciate baritone not letting a skeleton walk into the path and shooting their bot. Or a nether mob

**Comment by scorbett123** [comment]
you could if you like dunno if there is already an issue about it though so check for that first.
