### ISSUE TITLE
Setting the Logger

### ISSUE THREAD

**Issue by Infinidoge** [cabaletta/baritone#1593]
## What do you need help with?
I'm not sure if I'm being stupid here, but I'm trying to change the chat logger from:
```java
Minecraft.getMinecraft().ingameGUI.getChatGUI()::printChatMessage
```
to
```java
Minecraft.getMinecraft().player::sendMessage
```
(based off of my research this should be valid, but I'm not quite sure)

in my `settings.txt` file, I added:
```
logger Minecraft.getMinecraft().player::sendMessage
```
However, whenever the game gets started up, this line gets removed (not sure if this is due to Impact or baritone, though)

And whenever I set it in-game, it spits out an error: [log](https://paste.ee/p/Vshld) (at the bottom)

Am I setting the logger correctly, and is what I'm trying to set it to valid?
Additionally, if it's impact trying to remove the line, how would I stop it from doing so?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Infinidoge** [comment]
Upon further inspection, the error I received happens regardless of what I put into the command to set it in game.

**Comment by ZacSharp** [comment]
I'm surprised no one answered this.
The can only be changed using Baritones Java API and is never saved or loaded from saved settings.
