### ISSUE TITLE
how do I mine ice with baritone?

### ISSUE THREAD

**Issue by dracocrash** [cabaletta/baritone#1594]
title

**Comment by dominikaaaa** [comment]
#mine

**Comment by dracocrash** [comment]
> #mine

hi! I did try that, but when i type #mine (block) it detects there are no blocks nearby. This only happens for ice, as I'm able to mine coal and iron.
I have the exact same problem as stated in this thread https://github.com/cabaletta/baritone/issues/735.

**Comment by dominikaaaa** [comment]
If it's the same problem as that issue then follow that issue.
