### ISSUE TITLE
notAllowedToBreak 

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1595]
## Describe your suggestion
A command to choose which blocks it isnt allowed to break no matter what

## Settings
Maybe like #notAllowedToBreak beacon

## Context
Mining an area and I dont want it to mine the beacon in the area :c

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
blocksToAvoidBreaking

**Comment by NumseBacon** [comment]
That doesnt work for me and  a supporter told me to create a ticket here

**Comment by dominikaaaa** [comment]
the description is this
> blocksToAvoidBreaking
> Blocks that Baritone is not allowed to break
if it still tries breaking them then open a bug report.
