### ISSUE TITLE
#blocksToAvoidBreaking not working?

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1597]
## Some information
Operating system: Windows
Java version: build 1.8.0_221-b11
Minecraft version: 1.12.2
Baritone version: 1.12.2? (The one from 4.8.3 impact)
Forge mods (if used):  Auto-pickup-mod, durabilityviewer, inventorytweaks, itemsDontBreak, OPtifine, worldedit

## Exception, error or logs
Im aware of that it still wants to break if its the only path or something? But like this is a open area so it should be able to do it? (ive also tried to increase maxCostIncrease didnt help)
[latest.log](https://github.com/cabaletta/baritone/files/4499871/latest.log)

## How to reproduce
First do #blocksToAvoidBreaking Beacon then make selection around a beacon (iron blocks and beacon) and #sel set air or #sel ca etc. 

## Modified settings
https://gyazo.com/89fa4bc7012b73ad1ba6d200e2dae8e6 https://gyazo.com/d42443d6c0079a1a3a4cfa745c200c83 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by GloomyGerbil** [comment]
Try `#set buildIgnoreBlocks beacon`
replace beacon with whatever you want baritone to ignore
be aware that it will treat as if the block doesn't exists.. applies to `#build` as well

Lemme know how it works out for you

**Comment by NumseBacon** [comment]
"Error at argument #1: Expected a valid setting" so no

**Comment by GloomyGerbil** [comment]
works for me... I'm on 1.5.1 baritone, not sure about u
https://i.imgur.com/krQihtm.png

buildIgnoreBlocks
public final Settings.Setting<java.util.List<net.minecraft.block.Block>> buildIgnoreBlocks
A list of blocks to be treated as if they're air.
If a schematic asks for air at a certain position, and that position currently contains a block on this list, it will be treated as correct.

buildIgnoreExisting
public final Settings.Setting<java.lang.Boolean> buildIgnoreExisting
If this is true, the builder will treat all non-air blocks as correct. It will only place new blocks.

**Comment by NumseBacon** [comment]
Hmmm weirddd. Even with just #buildIgnoreBlocks it says command not found. But like yea im playing 1.12.2

**Comment by NumseBacon** [comment]
So when I type #settings and go to Bui it doesnt even show buildIgnoreBlocks

**Comment by GloomyGerbil** [comment]
Yup I think you're outta luck :/
Most be an older version of baritone.. 
Unless someone else has found a workaround I haven't thought of

In case you're wondering where the api is.. 
https://baritone.leijurv.com/baritone/api/Settings.html#field.detail

**Comment by NumseBacon** [comment]
ripp D:
