### ISSUE TITLE
Mining a certain amount of <block>

### ISSUE THREAD

**Issue by iCrashPhones** [cabaletta/baritone#1598]
## Describe your suggestion
improvement/enhancement to the #mine <amount> <block> command.
when using the #mine command, you can input a number, and it will online mine that much of the block (in total, it also counts ur inventory items). I think it would be a good idea to make it allow for multiple blocktypes. like how you can #mine stone grass dirt 
and it mines all of those blocks, we should be able to also do 
#mine 64 dirt 200 stone 3 grass
This would overall help the bot be more automated, instead of the player having to wait for one of the commands to finish to type the new one.

## Context
#mine command can mine 
"#mine 64 oak_log" which would make it only mine 64 (or tell you that you have enough already in ur inv).

**Comment by sportshead** [comment]
did you even read the [usage](../blob/master/USAGE.md)?
> - `mine diamond_ore iron_ore` to mine diamond ore or iron ore (turn on the setting `legitMine` to only mine ores that it can actually see. It will explore randomly around y=11 until it finds them.) An amount of blocks can also be specified, for example, `mine diamond_ore 64`.

**Comment by iCrashPhones** [comment]
1: that doesnt even work
2: yes I read it and I had to find another post which gives the actual usage

**Comment by dominikaaaa** [comment]
@sportshead they're asking to set the max amount to mine for multiple items

As for your suggestion @iCrashPhones, see #176
