### ISSUE TITLE
Baritone Patrol Route

### ISSUE THREAD

**Issue by ToxicDevv** [cabaletta/baritone#1599]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
It would be useful for protecting a base or grinding certain mobs. 

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
Passive or Aggressive patrol. How often baritone goes to another waypoint on the route.  

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

To help people that don't want to guard bases 24/7 or hate mob grinding. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
See #176
