### ISSUE TITLE
Prevention Of Picking Up Items With Full Inventory

### ISSUE THREAD

**Issue by gsharburg** [cabaletta/baritone#1600]
## Issue:
So while farming the bot stays on top of the items dropped on the ground (example pumpkin farm).
Is there a command where the bot ignores dropped items and still farms pumpkins with a full inventory?

Thank you

**Comment by gsharburg** [comment]
a quick and detailed answer would help :)

**Comment by dominikaaaa** [comment]
No.

**Comment by owufail7** [comment]
So does "No." mean its not getting implemented ever? Seems sorta handy to have, farming mcmmo levels, can pickup drops with a non baritone main, as unless its possible to have baritone deposit items into a chest it seems sorta silly it stops on a full inv.

**Comment by LysiBee** [comment]
It can help `#mineScanDroppedItems false`
