### ISSUE TITLE
Baritone Rainbow Colors Stop.

### ISSUE THREAD

**Issue by ToxicDevv** [cabaletta/baritone#1604]
## Some information
Operating system: Win 10
Java version:  8
Minecraft version: Any
Baritone version: Any
Forge mods (if used): 

## Exception, error or logs
No logs for this issue, as it isn't a client breaking error.

## How to reproduce
Turn on rainbow colors for baritone's path or any of baritone's colors. 
Quit game
Join back
Boom that's the error. Rainbow mode is disabled. 

## Modified settings
Turning on rainbow mode. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
As far as I know that's a bug in Impact (I just guess you use it) because Baritone has no rainbow mode
