### ISSUE TITLE
How can we code baritone bots ?

### ISSUE THREAD

**Issue by AloysMp4** [cabaletta/baritone#1606]
So i have recently discover the existence of these bots, and it blew my mind.
I'm learning to code and i am very curious how we can code them.
Is there any tutorial or just help on how to make them do precise things ?
Also I am french  so sorry for the bad english ;)

**Comment by dominikaaaa** [comment]
What do you mean be "code baritone bots"?

**Comment by dominikaaaa** [comment]
Baritone is already written, you opened this issue in the repository that already has all the code

**Comment by sportshead** [comment]
he's probably a @c0nn3r wannabe
