### ISSUE TITLE
Using baritone builder on hypixel skyblock any settings I need to be aware  of to not get banned

### ISSUE THREAD

**Issue by Boi1234242424242** [cabaletta/baritone#1609]
<3  thanks

**Comment by sportshead** [comment]
how to not get banned: don't use a utility mod on hypixel skyblock

**Comment by Boi1234242424242** [comment]
didn't  answer my  question

**Comment by dominikaaaa** [comment]
Yes it did. Don't use baritone on Hypixel if you don't want to get banned.
