### ISSUE TITLE
Building bug

### ISSUE THREAD

**Issue by xTMMDx** [cabaletta/baritone#1612]
## Some information
Operating system: Windows 10 x64
Java version: Version 8 Update 221
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): KAMI-blue, Schematica, WorldEdit.

## Exception, error or logs
- [latest.log](https://github.com/cabaletta/baritone/files/4525159/latest.log)
- [Video](https://youtu.be/vd-V_cPdphY)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game
allowDiagonalAscend (true)
allowDiagonalDescend (true)
allowInventory (true)
allowParkour (true)
allowParkourPlace (true)
assumeStep (true)
avoidance (true)
blockPlacementPenalty (20)
buildInLayers (true)
chatControl (false)
maxFallHeightBucket (255)
primaryTimeoutMS (3741)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Pause and unpause building from a different location.
