### ISSUE TITLE
Baritone mine function doesn't use pickaxe to mine beacons

### ISSUE THREAD

**Issue by crypthusiast0** [cabaletta/baritone#1616]
## Some information
Operating system: Windows 10 Pro
Java version: 1.8.0_51
Minecraft version: 1.12.2 Impact
Baritone version: 1.2.10
Forge mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Just run .b mine beacon or #b mine beacon

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This is because pickaxes don't mine beacons faster then a hand. 
https://minecraft.gamepedia.com/Beacon

**Comment by crypthusiast0** [comment]
Is there a way I can force it to use a pickaxe?

**Comment by dominikaaaa** [comment]
Using a pickaxe won't make it mine any faster.

**Comment by dominikaaaa** [comment]
Read the Minecraft wiki link I sent you. The fastest way to break it is using your fist.

**Comment by crypthusiast0** [comment]
Right, I know it doesn't mine it faster. Is there a way to force it to use a pick? It's cuz on certain servers I play on, it requires a pick to mine it.

**Comment by dominikaaaa** [comment]
No, there is not.

**Comment by crypthusiast0** [comment]
Ok, thanks for your help

**Comment by dominikaaaa** [comment]
you could just hold the pickaxe and I'm pretty sure it'll use it

**Comment by crypthusiast0** [comment]
I have the same issue as the original person who posted the other suggestion, where it mines it with a backpack.

**Comment by dominikaaaa** [comment]
Ah. Well #1334 should fix that, once it's added.
