### ISSUE TITLE
So i'm using schematica to build  a huge platform  and I need   help   ;/

### ISSUE THREAD

**Issue by YEETICUS12332** [cabaletta/baritone#1619]
When I'm too far  away from the unplaced parts  it  stops and says unable to do it pausing  and  then it just stops(is there any way to have it so it   knows  where it needs  to build on the whole  schematic

**Comment by dominikaaaa** [comment]
You need to have some items that you have set in `acceptableThrowawayItems` so it can use blocks to get to the place it can't get to.
