### ISSUE TITLE
Can I add new blocks from mods in baritone

### ISSUE THREAD

**Issue by SleepyOwl07** [cabaletta/baritone#1620]
i have some mods and there new blocks and ore. I tried to write a comand to dig it, but I get error like "ForBlockOptionalMeta".

**Comment by dominikaaaa** [comment]
You need to use the `modid:block_id`

**Comment by Cazcez** [comment]
> You need to use the `modid:block_id`

Its not working

**Comment by scorbett123** [comment]
> > You need to use the `modid:block_id`
> 
> Its not working

What mod and what block are you using?

**Comment by olliethefuck** [comment]
attempting to do this with Fantasycraft to get Mithril faster, continuing to get 
>[BlockOptionalMeta{block=Block{fantasycraft:mithril_ore}}]

**Comment by Cazcez** [comment]
> > > You need to use the `modid:block_id`
> > 
> > 
> > Its not working
> 
> What mod and what block are you using?

I noticed i used wrong arguments, so its working!
