### ISSUE TITLE
Add AI?

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1622]
## Describe your suggestion
Id really appreciate a function, that lets baritone learn from the users Baritone Inputs and improve its own movement/actions. Btw, this may also fix problems with movement, baritone does. If its completely useless, e.g. jumping on stairs, Baritone would learn, and avoid it. Also it would fix things, like Baritone has a list of blocks to mine, and if 2 blocks are near each other, baritone would learn to mine both, instead of walking 20 blocks a way, to mine a listed block there, and then come back to the spot from before.

## Settings
#learning boolean

## Context
This would be a hard job at first, but baritone wouldnt have to get any small movement and action patches, it would do it by itself. Additionally, users may upload theitr trained baritone data somehow. Maybe even cabaletta can use the data to create updates for stupid bugs.
:D

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] AI Factor
- [x] Loves Baritone

**Comment by dominikaaaa** [comment]
Closing this as won't fix as I doubt leij has the resources or time to maintain such an idea, let alone even implement a way to gather input and use it in a useful way.

**Comment by UltraBlackLinux** [comment]
thats sad.

**Comment by dominikaaaa** [comment]
It's reality. Machine learning isn't just as easy as "oh hey just add a few lines of code", you would need servers to host all that information and process it, and then a way for baritone to receive instructions based on the path finding. It's a neat idea but would provide little benefit compared to the existing solution and relative to the amount of work required to do so.
