### ISSUE TITLE
Wierd Log

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1623]
## Some information
Operating system: linux
Java version: 8 
Minecraft version: any
Baritone version: any
Forge mods (if used): none

## Exception, error or logs
[log.log](https://github.com/cabaletta/baritone/files/4534031/log.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Run minecraft with baritone

## Wish
please remove this wierd log when minecraft starts. it floods my log and I always think there is an error. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This is perfectly fine, it just means it's Mixins are conflicting with another client.
