### ISSUE TITLE
Any way to disable command feedback in chat?

### ISSUE THREAD

**Issue by TheUnderTaker11** [cabaletta/baritone#1625]
## What do you need help with?
I want to know if I can disable the command feeback in chat, like this stuff
![image](https://user-images.githubusercontent.com/63371073/80307415-939f0700-878e-11ea-9e06-6a83f0796543.png)

It would be super helpful if there was some way to stop it completely, or at least have a blacklist/whitelist of commands that will or won't give feedback like that in chat.

I see this https://github.com/cabaletta/baritone/blob/c2624bbaafd88b7c02b07f8fc4d65c35637b9f1a/src/api/java/baritone/api/Settings.java#L957      
But I have no idea how it could be used to stop logging certain things, or altogether stopping logging, either is acceptable. I can do this in code myself with a Forge mod if I only knew HOW to do it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
its a setting i think..
maybe censorRanCommands
maybe you could delete it with a regex mod..

**Comment by TheUnderTaker11** [comment]
censorRanCommands doesn't do that, it's got another purpose. echoCommands also isn't really helpful. 

If someone could tell me how to change the behavior of the logger, it would perfectly fit my situation.

**Comment by dominikaaaa** [comment]
Censor censors the coordinates in commands. 
If you wanna do this with a forge mod, just make a ClientChatReceivedEvent event and then do 
```kotlin
if (event.getMessage().match(REGEX GOES HERE)) event.setCancelled(true)
```

There isn't a way to disable it in baritone itself without changing the logger to some custom chat source that doesn't show.

**Comment by TheUnderTaker11** [comment]
@dominikaaaa It took me awhile to test since Baritone legit just won't run in my workspace (Yes I changed the mappings of my mod to the ones baritone uses, compiled it myself using ``gradlew java`` from the source code, put it on the build path, it just simply doesn't load baritone, then trying to put baritone in the run directory as a normal mod just crashes)

But that aside, the ClientChatRecivedEvent is not fired by Baritone's chat messages, so that doesn't work.

**Comment by dominikaaaa** [comment]
Look at the last 2 commits in my build.gradle [here](https://github.com/kami-blue/client/commits/feature/baritone%23584/build.gradle) for how we got Baritone working in our gradle. As for the second one, I can't help you there.

**Comment by TheUnderTaker11** [comment]
I thought overwriting the logger using something like 
``BaritoneAPI.getSettings().logger.value = SOMETHING`` would work, however I was never able to get anything at all in that SOMETHING to work. It either crashed the game, or didn't overwrite the fact it logs to chatGUI

**Comment by TheUnderTaker11** [comment]
Here is how to change it.
```
BaritoneAPI.getSettings().logger.value = (component) -> {
            System.out.println("BARITONE SAID :: " + component.getUnformattedText());
        };
```

**Comment by Merczy** [comment]
can you give me compiled version?
