### ISSUE TITLE
Slightly changed idea of Pull request "Loot command #1613"

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1626]
## Describe your suggestion
baritone will also loot chests when mining e.g. diamonds, then it will also take em outta chests

## Settings
#allowloot

## Context
Thought "Loot command #1613" was a nice idea but a bit to complex and not quite..... kinda matching..

## Final checklist
- [x] I know how to properly use check boxes 
- [x] OOF

**Comment by dominikaaaa** [comment]
Comment on the pull request then.
