### ISSUE TITLE
1.5.3 Forge Jars Not Broken

### ISSUE THREAD

**Issue by davidsch22** [cabaletta/baritone#1630]
## Describe your suggestion
In the downloads page, the description for the 1.5.3 artifacts says that the Forge jars are mostly broken, so I wanted to see if I could take a look at the mixins and fix it myself. I started out by just building the forge jars as they are, but to my surprise they worked 100% just fine. So I downloaded the jars from the downloads page directly to see if they were any different and I got the same result. I don't know if the description on the page is just out of date or something is wrong on your end, but I just wanted to let you know they work fine.

## Context
It won't give fake news lol

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
1.5.3 doesn't support Forge?

**Comment by davidsch22** [comment]
Not Minecraft 1.5.3 you blockhead. Baritone v1.5.3, the most recent version for MC 1.15.2.

**Comment by dominikaaaa** [comment]
Yes. We don't officially support Forge above 1.12.2

**Comment by davidsch22** [comment]
Except there are clearly Forge jars for 1.15.2 on the downloads page and they claim to be broken even though they're not.

**Comment by dominikaaaa** [comment]
Oh you're talking about the latest. I didn't realize it had forge jars.

**Comment by dominikaaaa** [comment]
You can ask @leijurv to explain that one

**Comment by davidsch22** [comment]
Lmao what other version would I be talking about?

**Comment by dominikaaaa** [comment]
Well I had no idea that the latest release has Forge jars, as usually releases don't get them.

**Comment by leijurv** [comment]
See what I wrote in the release:

```
For example, mining for ores is broken, following entities is broken, placing blocks doesn't work. They are essentially only good for walking to coordinates. 
```

Emphasis on the second sentence. These jars are horribly broken, and error out on those three listed tasks. But they will function for walking to coordinates, and basically nothing more.

**Comment by davidsch22** [comment]
Except I was perfectly able to do all three of those things.

**Comment by dominikaaaa** [comment]
Leij were you testing with any other mods installed?

**Comment by leijurv** [comment]
what the fr*ck?!??!

**Comment by davidsch22** [comment]
I used the Forge API file just so you know.

**Comment by leijurv** [comment]
`#mine coal_ore`, `#mine stone` etc all don't work, just tried right now

**Comment by davidsch22** [comment]
I also just tried the Forge standalone file and it worked just fine too. For extra info, I'm using a fresh installation of Forge 31.1.0, the Mixins jar from the exact link you gave us, and no other mods.

**Comment by davidsch22** [comment]
Both worked for me.

**Comment by leijurv** [comment]
living in the twilight zone?

**Comment by davidsch22** [comment]
Maybe you are lol

**Comment by leijurv** [comment]
Twilight zone confirmed. Thanks forge.

Forge `31.1.0` works, but forge `31.1.50` doesn't.

**Comment by leijurv** [comment]
Updated the releases page

**Comment by davidsch22** [comment]
LOL
