### ISSUE TITLE
MLG water bucket not working

### ISSUE THREAD

**Issue by AFKglass** [cabaletta/baritone#1631]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

Specs
iMac 21.5-inch late 2009
processor 3.06 GHz intel core 2 duo
memory 12 GB 1067 MHz DDR3
startup disk macintosh HD
Graphics NIVDIA GeForce 9400 256 MB
I don't know if that could help
[Also it some how is a pretty beefy computer for a mac I get 80fps with optifine which I think is pretty good in a hypixel lobby and a 11 year old computer]

I have tried to get the mlg water bucket thing working I have looked through the setting [#settings] I saw a command [forgot it] I set it to true then I towered up with cobblestone with a water bucket in my hand then I did #goto [cordniates] [cordniates] [cordniates] then the bot fell and did nothing to stop from taking fall damage and I did the excact same thing but with the setting on false it didn't do anything I don't if I'm doing some very idiotic stuff here because I used this mod for only a couple days when posting this.

please help me....

**Comment by dominikaaaa** [comment]
`#allowWaterBucketFall`, `#maxFallHeightBucket`
