### ISSUE TITLE
#ExploreForBlocks not properly working, especially in connection with #LegitMine

### ISSUE THREAD

**Issue by N2Blue** [cabaletta/baritone#1637]
I am a duplicate of #1017, #766 and #1320 but I try to explain the problem more in detail and maybe someone can merge these issues into my one.

Setting #ExploreForBlocks is not working as expected, especially if setting #LegitMine is used as well. My testing was done using #reset all every time and I set values by hand:
| LegitMine | ExploreForBlocks |   | Behavior    | as expected? |
|-----------|------------------|---|-------------|:------------:|
| False     | True             |   | not explore |      No      |
| False     | False            |   | not explore |      Yes     |
| True      | True             |   | explores    |      Yes     |
| True      | False            |   | explores    |      No      |

#### Conclusion
As you see we have two setting-choices which do not work as expected.
If we disable #LegitMine and enable #ExploreForBlocks it will not start exploring.
If we enable #LegitMine and disable #ExploreForBlocks it will still start exploring.

I think this inconsistent behavior is a bug and could be fixed, but this report will also help people having problems with #ExploreForBlocks and give them a nice overview (see table).

## Some information
Operating system: W10 x64
Java version: 1.8.0_251
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): -

#### Should not explore but does:
```
[20:18:21] [Client thread/INFO]: [CHAT] [Baritone] > mine 1 diamond_ore
[20:18:21] [Client thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]
[20:18:21] [Client thread/INFO]: [baritone.ke:a:-1]: Currently have 0 valid items
[20:18:21] [Client thread/INFO]: [baritone.ke:a:-1]: Currently have 0 valid items
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: 1955712 movements considered
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: Open set size: 36582
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: PathNode map size: 125478
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: 177792 nodes per second
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hh:a:-1]: Path goes for 105.68348972285122 blocks
```

#### Should explore but does not:
```
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] > mine 1 diamond_ore
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] No locations for BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]} known, cancelling
```

#### Case 1 (exploring when it shouldn't):
- #reset all
- #LegitMine true
- #ExploreForBlocks false
- #mine 1 diamond_ore

#### Case 2 (not exploring when it should):
- #reset all
- #LegitMine false
- #ExploreForBlocks true
- #mine 1 diamond_ore

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]} known, cancelling
This means Baritone doesnt recongize any type of this block, so have u tried stone or grass or stuff, when standing on it?

**Comment by MrAlexEsisteGia** [comment]
> 
> 
> BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]} known, cancelling
> This means Baritone doesnt recongize any type of this block, so have u tried stone or grass or stuff, when standing on it?

I've recently had some problems with baritone being practically blind, I did #mine diamond_ore with one at 10 blocks from me and it didn't see it and started searching elsewhere.
I think it's related

**Comment by dominikaaaa** [comment]
That's not related.

**Comment by ZacSharp** [comment]
The intended and now implemented table is
LegitMine | ExploreForBlocks | Behavior
-|-|-
False | True | explore
False | False | don't explore
True | True | explore
True | False | explore

so it always explores when `legitMine` is true

**Comment by muchi99** [comment]
i think i have a similar problem here but i cant make it work
![image](https://github.com/cabaletta/baritone/assets/107821146/6caa4f98-2022-4230-bb6f-0d03612085e2)
thats the message i get everytime i try to make it work

**Comment by ZacSharp** [comment]
That means Baritone knows where an `oak_log` is but can't find a path to get there, so you problem is entirely unrelated to this long fixed issue.

If you are sure there is a reasonable path to some oak log (not something like mining though stone by hand for hours) please open a new issue with more detailed information.
