### ISSUE TITLE
while mining a block of a certain type I want it to onlly mine from the front and not the sides

### ISSUE THREAD

**Issue by YEETICUS12332** [cabaletta/baritone#1638]
is there any way to do this because it keeps going to the side of the block to break it instead of just running forward(and yes I have walkwhilebreaking set to true)

**Comment by dominikaaaa** [comment]
No, why would you even want that?

**Comment by dominikaaaa** [comment]
Baritone goes to the most efficient way to mine it, including future ores.

**Comment by YEETICUS12332** [comment]
its so slow tho

**Comment by YEETICUS12332** [comment]
I'm farming a pumpkin farm and it goes out of its way to mine sideways and make the process slower

**Comment by dominikaaaa** [comment]
If it was slower then it wouldn't do it.

**Comment by dominikaaaa** [comment]
Overall, it uses the fastest way *including future mining destinations*

**Comment by YEETICUS12332** [comment]
no trust me it's going so much slower

**Comment by YEETICUS12332** [comment]
Can I send a vid in like 10 seconds each one with baritone and 1 without

**Comment by dominikaaaa** [comment]
Then disable walkwhilebreaking

**Comment by YEETICUS12332** [comment]
imma just make a macro idk

**Comment by YEETICUS12332** [comment]
one last thing it keeps breaking blocks that I have it set to avoid breaking wtf do I do ur big brain right?

**Comment by dominikaaaa** [comment]
#919
