### ISSUE TITLE
How to make baritone mine pumpkins faster?

### ISSUE THREAD

**Issue by beanisready** [cabaletta/baritone#1639]
https:/gyazo.com/88ebce38d47f09abbdaa4f9a26934b9c

I am going through the issue of baritone hitting against blocks slowing mining pumpkins by a lot. Would possibly increasing the range help this? What else could I do to mine these pumpkins faster.

Without baritone I can mine 3x more pumpkins in the same amount of time. Any suggestions on commands? I would greatly appreciate any input.

**Comment by YEETICUS12332** [comment]
too much skyblock

**Comment by dominikaaaa** [comment]
Use a macro or something.
