### ISSUE TITLE
Javadoc link is dead (404)

### ISSUE THREAD

**Issue by norisak** [cabaletta/baritone#1640]
The javadoc link https://baritone.leijurv.com/ is dead.

**Comment by UltraBlackLinux** [comment]
Github had some downtime the last days, its back on :)

**Comment by dominikaaaa** [comment]
They're not hosted on github
![2020-05-04-132901_429x238_scrot](https://user-images.githubusercontent.com/17222512/80994793-3ac51380-8e0b-11ea-887b-6a6fc8d8e8e9.png)

**Comment by UltraBlackLinux** [comment]
Oops xD always read properly, i ment javadocs

**Comment by MajsterTynek** [comment]
OOF, it did again...

**Comment by dominikaaaa** [comment]
Yes, it happens randomly. Just wait for it to come back online

**Comment by MajsterTynek** [comment]
It happened two days in a row. I don't like that.
