### ISSUE TITLE
Error at Argument #1: Expected aa

### ISSUE THREAD

**Issue by pokemongen4champ** [cabaletta/baritone#1641]
Cant use the #mine diamon_ore
I only get the above error

**Comment by dominikaaaa** [comment]
That's not how you spell it.

**Comment by dominikaaaa** [comment]
In the future, fill out the issue template properly.

**Comment by pokemongen4champ** [comment]
Sorry, whats the issue template. And as for the mispell obviously i didnt spell it "diamon".

**Comment by dominikaaaa** [comment]
It's spelled "diamond". Also when you go to create a new issue it presents you with 3 templates. 
![2020-04-30-161906_1030x265_scrot](https://user-images.githubusercontent.com/17222512/80755156-545e1680-8afe-11ea-9c88-7b9e28e4050c.png)
