### ISSUE TITLE
Baritone Automine Pathing exception: java.lang.NullPointerExpection

### ISSUE THREAD

**Issue by NightHybrid** [cabaletta/baritone#1643]
Can't seem to get AutoMine to work, it's set to mine diamonds.
As you can see, I'm in a regular Plains biome, so won't be any issues with snow (as I've found other people have this issue).

Minecraft 1.12.2
Baritone 4.8.3

chat message
![Minecraft 1 12 2 5_1_2020 10_37_14 AM](https://user-images.githubusercontent.com/63908553/80773155-24fbe800-8b98-11ea-9888-fca2919a0e9e.png)

forge mods
![Screenshot 5_1_2020 10_39_26 AM](https://user-images.githubusercontent.com/63908553/80773165-288f6f00-8b98-11ea-9c18-77e6b84e395d.png)

**Comment by dominikaaaa** [comment]
If you can reproduce this with only baritone installed please reopen this issue. Also please provide your lgos.

**Comment by NightHybrid** [comment]
> If you can reproduce this with only baritone installed please reopen this issue. Also please provide your logs.

So I redid it without my mods and it works.
Do you know of Baritone having conflicts with specific mods?

**Comment by dominikaaaa** [comment]
Find which mod caused it I guess.
