### ISSUE TITLE
Keep farming with full inventory

### ISSUE THREAD

**Issue by khandielas10** [cabaletta/baritone#1644]
I understand that you can use
mineScanDroppedItems
to prevent the bot from stopping to pick up drops while mining, but is there an equivalent for farming?

I want to use this on a modpack where you gain xp for farming, but I don't care about the crops. When I end up with a full inventory I stop farming.

When I add the crops in as trash to discard, the client kicks me for some reason.

**Comment by dominikaaaa** [comment]
No, there isn't a way to do this.
