### ISSUE TITLE
Baritone #Mine and #goto dont work.

### ISSUE THREAD

**Issue by JamiePlaysTwitch** [cabaletta/baritone#1645]
Hi there,

I have downloaded baritone to forge for 1.15.2. I play on a server with friends and want to troll them by having alot of recources, because of the AutoMine feature. I play on Java Edition on Windows. I have 2 more mods installed beside baritone: Shulkerboxtooltip and MixinBootstrap. I get an error when I type this: #mine iron_ore and when I do #goto iron_ore. This is an example, it doesnt work with any type of block. I get this error in chat: Error at Argument #1: Expected aa
I hope someone can help me!

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.

**Comment by Olliisreal** [comment]
that happens to me to

**Comment by Olliisreal** [comment]
plz help

**Comment by scorbett123** [comment]
Fill in a proper issue then someone might be able to help.
