### ISSUE TITLE
Error at argument #1: Expected ForBlockOptionalMeta

### ISSUE THREAD

**Issue by finalnoob5** [cabaletta/baritone#1648]
## Some information
Operating system: **Windows 10 Home v.1909**
Java version: **1.8.0_251**
Minecraft version: **1.15.2**
Baritone version: **1.5.3**
Forge mods (if used): **Baritone, MixinBootstrap-1.0.3** (allows Baritone to function with forge)

## Exception, error or logs
Error at argument #1: Expected ForBlockOptionalMeta
[debug.log](https://github.com/cabaletta/baritone/files/4565409/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/4565417/latest.log)

## How to reproduce

1. Install and run Minecraft version 1.15.2
2. Download **forge-1.15.2-31.1.63** forge installer from [https://files.minecraftforge.net/](url) and install Forge into your Minecraft. Run Minecraft with Forge.
3. Download **MixinBootstrap-1.0.3.jar** from [https://github.com/LXGaming/MixinBootstrap/releases](url) and place the .jar in your .minecraft\mods folder.
4. Download **baritone-api-forge-1.5.3.jar** from [https://github.com/cabaletta/baritone/releases/tag/v1.5.3](url) and place the .jar in your .minecraft\mods folder.
5. Run Minecraft with Forge and type any command with baritone that requires targeting a block ID.

## Modified settings
allowDiagonalAscend **true**
allowDiagonalDescend **true**
allowInventory **true**
allowParkour **true**
allowParkourPlace **true**
allowVines **true**

## Screenshot
![2020-04-30_19 38 32](https://user-images.githubusercontent.com/64618336/80826252-ebcf7200-8baf-11ea-85e7-55f0f8440dea.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

Edit: *This also occurs with **baritone-unoptimized-forge-1.5.3.jar**

**Comment by Zaureau15** [comment]
I'm having the exact same problem. Can't find a solution anywhere online.

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/releases/tag/v1.5.3

# 🤡

**Comment by sophronesis** [comment]
Same problem here if trying to execute `#sel fill dirt`. It even can't replicate `#mine diamond_ore` from `#help mine`. Hope this will be fixed

**Comment by MasterOrg012** [comment]
u need change the method try this #mine minecraft:diamond_ore for mi works fine

**Comment by UltraBlackLinux** [comment]
@MasterOrg012 this is only relevant when mods r installed. This works for you since (i assume) you dont have this problem. Read through the issue.

**Comment by sophronesis** [comment]
> u need change the method try this #mine minecraft:diamond_ore for mi works fine

It was because of newer version of Forge installed. Now it all works just fine

**Comment by JakoDel** [comment]
having this issue with impact forge 4.9.1 for 1.12.2

**Comment by ummm288** [comment]
I can't find solution online

**Comment by ummm288** [comment]
It works on minecraft forge* 1.20.1?
