### ISSUE TITLE
Error at argument #1: Expected aa

### ISSUE THREAD

**Issue by finalnoob5** [cabaletta/baritone#1649]
## Some information
Operating system: **Windows 10 Home v.1909**
Java version: **1.8.0_251**
Minecraft version: **1.15.2**
Baritone version: **1.5.3**
Forge mods (if used): **Baritone, MixinBootstrap-1.0.3** (allows Baritone to function with forge)

## Exception, error or logs
Error at argument #1: Expected aa
[debug.log](https://github.com/cabaletta/baritone/files/4565782/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/4565784/latest.log)

## How to reproduce

1. Install and run Minecraft version 1.15.2
2. Download **forge-1.15.2-31.1.63** forge installer from [https://files.minecraftforge.net/](url) and install Forge into your Minecraft. Run Minecraft with Forge.
3. Download **MixinBootstrap-1.0.3.jar** from [https://github.com/LXGaming/MixinBootstrap/releases](url) and place the .jar in your .minecraft\mods folder.
4. Download **baritone-standalone-forge-1.5.3.jar** from [https://github.com/cabaletta/baritone/releases/tag/v1.5.3](url) and place the .jar in your .minecraft\mods folder.
5. Run Minecraft with Forge and type any command with baritone that requires targeting a block ID.

## Modified settings
allowDiagonalAscend true
allowDiagonalDescend true
allowInventory true
allowParkour true
allowParkourPlace true
allowVines true

## Screenshot
![2020-05-01_13 46 50](https://user-images.githubusercontent.com/64618336/80831024-09a0d500-8bb8-11ea-80ab-aa3849775cd7.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheButterbrotMan** [comment]
You can fix it by using, Mixin 1.0.2.

Best regards

**Comment by TheButterbrotMan** [comment]
Ît is a problem with the experimental forge version, use recommend and it will work.

Best regards

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/releases/tag/v1.5.3
