### ISSUE TITLE
stronghold/end portal finder

### ISSUE THREAD

**Issue by CopyPaste3** [cabaletta/baritone#1651]
I made this suggestion on the impact github but was told it was better suited for baritone than impact so here it is. 
link to original: [https://github.com/ImpactDevelopment/ImpactIssues/issues/2227](url)

**Is your feature request related to a problem? Please describe.**
no, its just a feature that I would like.

**Describe the solution you'd like**
Throw 2 eyes of ender, each throw separated by a few hundred blocks(to improve accuracy). Save the throw coordinates and direction of the eyes of ender, calculate a line based on this data, then do the same with the second throw. Calculate the intersection point of the 2 lines and the stronghold should be at the intersection.

this part is the same as above except using a slightly different method. Instead of using the throw coords and direction, use throw coords and a distant block they are traveling towards(makes math easier). Do the line equation given 2 points math, then find the intersection of the lines.

**Describe alternatives you've considered**
doing it the regular way

**Additional context**
I added a diagram to help show what I mean
![calculate](https://user-images.githubusercontent.com/62960686/80875558-cebaa200-8c88-11ea-81a3-ab296835142f.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Please add a brief but descriptive title

**Comment by zPeanut** [comment]
Please add a brief but descriptive title

**Comment by circl-lastname** [comment]
Please add a brief but descriptive title

**Comment by Ilidumb** [comment]
Please add a brief but descriptive title

**Comment by sportshead** [comment]
I made this a while ago, might help (don't judge): https://www.desmos.com/calculator/hbuzsmpsjd
