### ISSUE TITLE
I keep trying to break quartz using mine command and it walks up to it and doesn't break

### ISSUE THREAD

**Issue by YEETICUS12332** [cabaletta/baritone#1653]
I have allow break on and a pick

**Comment by YEETICUS12332** [comment]
![bugg](https://user-images.githubusercontent.com/64301995/80907107-c6db1c00-8ce1-11ea-8e39-dafe41decb30.png)

**Comment by DavidCarl** [comment]
Could it be because the name is nether_quartz_ore and not quartz_ore ?

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.

**Comment by YEETICUS12332** [comment]
wdym?

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.
