### ISSUE TITLE
Bots won't follow player

### ISSUE THREAD

**Issue by flae7** [cabaletta/baritone#1654]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: newest, bot-system branch
Forge mods (if used): none

## Exception, error or logs
there is no error, the problem is that i try to make the bots follow a specific player, everything seems to be ok but the bots stay in place 
![obraz](https://user-images.githubusercontent.com/51024668/80916992-7bb21f00-8d5c-11ea-9925-7d6c5cbdd0de.png)

## How to reproduce
1. Run the bot-system branch
2. "follow player name"

## Modified settings
acceptableThrowawayItems
allowDiagonalAscend/Descend
allowParkourAscend/Descend
allowInventory
allowParkour(place)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You need to include the entity name in the command.

**Comment by flae7** [comment]
if you look closely, it clearly says "follow player Player29(i ran the game in debug)" and i clearly included the entity name, which is player

**Comment by flae7** [comment]
![obraz](https://user-images.githubusercontent.com/51024668/80923087-9054de00-8d81-11ea-82c5-c8648ade18aa.png)
it's clearly in the command, i tried chat control too. #1322

**Comment by dominikaaaa** [comment]
`#follow entityplayer Name` or `#follow player name`

**Comment by flae7** [comment]
You clearly didn't read my issue. I already said that i tried "follow player name". It didn't work because the bots didn't move, like showed in the 1st picture. I tried follow entityplayer name and it didn't work either. And please, before you respond, read the entire issue once again correctly...

**Comment by dominikaaaa** [comment]
Your first screenshot shows it working perfectly.

**Comment by flae7** [comment]
You didn't read the issue, it does not work, i said that literally ABOVE THE IMAGE
![obraz](https://user-images.githubusercontent.com/51024668/80982180-3f012900-8e2b-11ea-9a6d-20a965c905dd.png)

**Comment by dominikaaaa** [comment]
> Your first screenshot shows it working perfectly.

**Comment by flae7** [comment]
> there is no error, the problem is that i try to make the bots follow a specific player, everything seems to be ok but the **bots stay in place**

the bots STAY IN PLACE after executing the command, which should NOT happen. that is the ORIGINAL ISSUE

**Comment by dominikaaaa** [comment]
What you're describing is completely normal behavior as you're in range of the player you want to follow.

**Comment by flae7** [comment]
no, the issue persists even after i am 100% not in the follow radius.

**Comment by dominikaaaa** [comment]
Send a video of the issue then.

**Comment by flae7** [comment]
https://youtu.be/7U8Pkv2gRgQ

**Comment by dominikaaaa** [comment]
Try in survival, and send a screenshot of `#proc`

**Comment by flae7** [comment]
Survival didn't work either
![obraz](https://user-images.githubusercontent.com/51024668/80985204-2f83df00-8e2f-11ea-8e11-639615ffea12.png)

**Comment by SuperGamingBros4** [comment]
I figured out that you need to disable chat control for it to work but first use "#prefix (whatever you want)" because # is the default prefix then use "(your set prefix)set chatcontrol false". Then just use the prefix you set to use have the bots do it

**Comment by cookiedragon234** [comment]
Who would have thought

**Comment by SuperGamingBros4** [comment]
Yeah his problem was he was using it to control himself.

**Comment by dominikaaaa** [comment]
Tbh I forgot why I kept this opened, the bot branch isn't receiving support in the first place.
