### ISSUE TITLE
Allow toggling the option for stopping while eating.

### ISSUE THREAD

**Issue by circl-lastname** [cabaletta/baritone#1660]
## Describe your suggestion
Allow toggling the option for stopping while eating. That way Baritone doesn't stop to eat.

## Settings
Allow us to toggle the option using a command like \#eatingPause.

## Context
I have the No Slow cheat on in Impact which let's you walk at full speed while eating, but baritone stops to eat.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This is not a Baritone issue.
Impact (and other clients) create there own pause process and baritone doesn't know anything about it's purpose, so it can't ignore it.

Please close this issue and ask on the suggestions page of the client of your choice (Impact I guess).
Have you looked at impacts settings btw? There is a toggle for combat pause and there might be one for pause while eating. Don't bother anyone by suggesting implemented and working features.
