### ISSUE TITLE
Are the pvp bots still in development?

### ISSUE THREAD

**Issue by smasher-101** [cabaletta/baritone#1661]
I saw some videos on youtube of @c0nn3r 's pvp bots and I'm wondering if they ever got good enough to do crystal pvp.  They looked really cool and I just want to see someone get swarmed by a bunch of robots exploding someone in 2 seconds.

**Comment by dominikaaaa** [comment]
they're finished, didn't you know? they're talking over 2b2t as we speak

**Comment by smasher-101** [comment]
are there any videos of them?

**Comment by dominikaaaa** [comment]
yes

**Comment by dominikaaaa** [comment]
but they're top secret, you're not allowed to see

**Comment by smasher-101** [comment]
so has anyone been killed by them?

**Comment by dominikaaaa** [comment]
yes, all the oldfags are dying to them. they're programmed to avoid new players to new players don't know about them until it's too late

**Comment by smasher-101** [comment]
Ok so I just need to get good gear so I'm not "new" and then just wait until they kill me just so I can see what they do.

**Comment by dominikaaaa** [comment]
no, they know how long you've been playing by using rusherbot's commands. so you have to be an oldfag

**Comment by smasher-101** [comment]
I'm starting to think that there are no bots or else someone would have posted film of dieing to them on reddit or something.

**Comment by 0-x-2-2** [comment]
oy vey
