### ISSUE TITLE
Baritone Forge version not working in development environment

### ISSUE THREAD

**Issue by funnyrick01** [cabaletta/baritone#1664]
## What do you need help with?
Alright so, what i trying get working is simply Baritone as a forge mod in a development environment (in Intellij).
for convenience sake i've put the "baritone-api-forge-1.5.3.jar" in the libs folder in my project and within the build.gradle i compile it along with `compile fileTree(dir: 'libs', include: ['*.jar'])`
Baritone does get loaded in according to Forge:
![image](https://user-images.githubusercontent.com/33003030/81074487-5999d780-8ee9-11ea-9060-94d9f443fccf.png)
But it does not work when typing a command or trying to acces it's api.
![image](https://user-images.githubusercontent.com/33003030/81074587-80f0a480-8ee9-11ea-89e9-be2fe7e680ec.png)

> Stacktrace:
> 	at baritone.api.Settings.<init>(Settings.java:160)
> Caused by: java.lang.NoSuchFieldError: field_150346_d
> 	at baritone.api.BaritoneAPI.<clinit>(BaritoneAPI.java:34)
> 	at com.example.examplemod.ChatListener.onSendChatMessage(ChatListener.java:21)

I asume this is because baritone expects the environment to be obfuscated while a dev environment is not? (It works fine in a production env.)
How do i fix this? I've been stuck on this small problem for way to long now...

## Version
minecraft: 1.15
Baritone: api forge 1.5.3

## How to reproduce
Install the forge MDK version 1.15.2 - 31.1.0.
Add baritone-api-forge-1.5.3.jar as a dependency.
Run the client and watch it load in but not work.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/releases

**Comment by dominikaaaa** [comment]
Please read it.

**Comment by funnyrick01** [comment]
my apologies, i forgot to state that i also included the "MinxinBootstrap-1.0.2.jar" as a dependency.
![image](https://user-images.githubusercontent.com/33003030/81078470-90beb780-8eee-11ea-8b98-7c153e3521b3.png)

**Comment by dominikaaaa** [comment]
You're using 31.1.10 right now

**Comment by funnyrick01** [comment]
I am using 31.1.0? as clearly shown in the screenshot above 
![image](https://user-images.githubusercontent.com/33003030/81078899-193d5800-8eef-11ea-83a8-130d4f633338.png)

**Comment by dominikaaaa** [comment]
Oh it appears I misread your issue. My bad

**Comment by Stijnkluiters** [comment]
I got the exact same issue. Baritone forge is working fine when put in "\Roaming\.minecraft\mods" but in my IDE it doesn't wanne work. Any solution found for this?

**Comment by Maarsupial** [comment]
Same issue here. Found a solution yet?

**Comment by funnyrick01** [comment]
> Same issue here. Found a solution yet?

No, kinda gave up on using Baritone for now. I've spend way more time on trying to get it to work then i should have. Still hope someone else can come with an awnser tho

**Comment by ZacSharp** [comment]
I just set up a production enviroment and used a symbolic link to the build result.
To use it I just build my code and relaunch the game.

**Comment by dominikaaaa** [comment]
Idk why this is still opened, this works just fine in a dev env. These instructions from [here](https://kamiblue.org/contributing) work just fine for me

![dominikaaaa org-2020-07-11-16-24-50](https://user-images.githubusercontent.com/17222512/87233153-0e8dbc00-c393-11ea-8143-4a7bbaa67236.png)
