### ISSUE TITLE
Schematic not working

### ISSUE THREAD

**Issue by boomyimagine** [cabaletta/baritone#1667]
## Some information
Operating system: Windows 10 
Java version: 8 update 251
Minecraft version: 1.12.2
Baritone version:  4.8.3
Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/4587258/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
I got the schematic I wanted in the schematics file. I loaded on, got the materials, and typed #build imagine. (that is the name of the schematic.) The following message appeared: An unhandled exception occurred.The error is in your game's log. Please report this at https://github.com/cabaletta/baritone/issues

## Modified settings
To get the modified settings run `#modified` in game
chatControl is the only modified setting (I don't know what that is)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Include the full file name.

**Comment by boomyimagine** [comment]
thank you its working now

**Comment by calloutplayed** [comment]
Not working
