### ISSUE TITLE
My game crashes at launch

### ISSUE THREAD

**Issue by area51alienufo** [cabaletta/baritone#1668]
I need help with the baritone 1.2.7 my game always crashes if I try to launch it here is the crash log:
[latest.log](https://github.com/cabaletta/baritone/files/4589435/latest.log)
![image](https://user-images.githubusercontent.com/38160916/81227945-82a39080-8fed-11ea-88e8-ae5c30c5b4ae.png)
And here are my other mods that I am using.

**Comment by dominikaaaa** [comment]
Remove the mods 1 by 1 until you find which one causes it.
