### ISSUE TITLE
Schematic builds not working

### ISSUE THREAD

**Issue by Catzardo330** [cabaletta/baritone#1672]
## Some information
Operating system: Windows 10
Java version: i have no idea
Minecraft version: 1.14.4
Baritone version: idk, its on impact
Forge mods (if used): no

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/4602331/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Use proper file naming.
