### ISSUE TITLE
Can I mine a specific block with a specific tool.

### ISSUE THREAD

**Issue by ceilingfans** [cabaletta/baritone#1673]
## Can you help me find out how to use a specific pickaxe to mine beacons
I went to use #mine beacon it started mining the beacons but switched to the 1st hotbar slot. So the server wont let me mine it as it is using the wrong tool.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
See #1334
