### ISSUE TITLE
Inventory blocks 

### ISSUE THREAD

**Issue by ixLava** [cabaletta/baritone#1674]
I want to build a schematic in creative mode which includes more than 9 blocks ( hotbar ) , and i want the full schematic builded. SO  how can I let baritone to get blocks from my inventory and hotbar instead of my hotbar only? 

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
`#allowInventory`
