### ISSUE TITLE
How can I mine a certain type of block?

### ISSUE THREAD

**Issue by area51alienufo** [cabaletta/baritone#1676]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

How can I mine a certain type of block?

If there re diffrent type of ores under the same name I can't choose a certain one Baritone always mines all ores at once. I tried: 
mekanism:oreblock type:osmium
mekanism:osmium
mekanism:oreblock:osmium
mekanism:oreblock_osmium

they all didn't work! 

Could someone help me?
Or is that just now possible? 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
If ur on 1.12, there are numeric ids. If u wanna display em press f3+h.
To make use of this look at the block and paste the whole id to baritones mi e. What also works is: mine stone:1 or mine stone/1 i figured this out at some point, im not sure wich one of those 2 works.
At least the ids thing should work surely.
But if ure on 1.13+, look what f3+h displays u (minecraft:example) and paste this into baritone

**Comment by area51alienufo** [comment]
What is the mi e?

**Comment by area51alienufo** [comment]
could you send a screen shot how you type it in?

**Comment by dominikaaaa** [comment]
If u wanna display em press f3+h.

**Comment by UltraBlackLinux** [comment]
#mine 1:1
