### ISSUE TITLE
Stop baritone from breaking the block above

### ISSUE THREAD

**Issue by EnderInvader** [cabaletta/baritone#1677]
## What do you need help with?
If the block above the ore is constantly being replaced then baritone will never break the ore, is there a way to have baritone ignore the block above the ore and directly break the ore?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by EnderInvader** [comment]
I found that this is actually possible by rewriting the farming process code in the api to include ores. I'm not sure how or why this works, but it does.

However, I am still wondering if there is a way to do this without rewriting the api?

**Comment by UltraBlackLinux** [comment]
Do u have goalbreakfromabove activated?

**Comment by dominikaaaa** [comment]
No, baritone breaks the above block in order to be able to walk into the 2x1 space to pick up the item. There isn't a way to do this @EnderInvader, you're on your own.
