### ISSUE TITLE
autoTool not working

### ISSUE THREAD

**Issue by ceilingfans** [cabaletta/baritone#1678]
## Some information
Operating system: MacOS Catalina
Java version: (I do not know)
Minecraft version: 1.15.2
Baritone version: 1.5.3
Forge mods (if used): MixinBootstrap

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. Run the baritone client
2. type #autotool false in chat
3. This is the response <img width="340" alt="Screenshot 2020-05-10 at 1 09 37 PM" src="https://user-images.githubusercontent.com/65061212/81491336-1318f400-92c0-11ea-9795-75d52b07f711.png">

## Modified settings
1. legitMine (Boolean)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/4605188/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/4605189/debug.log)

**Comment by dominikaaaa** [comment]
That's not a valid setting.

**Comment by dominikaaaa** [comment]
Autotool is always on with no way to change it. See issue #1334
