### ISSUE TITLE
Baritone falls in lava while mining obsidian 

### ISSUE THREAD

**Issue by CONBlaze** [cabaletta/baritone#1679]
## Some information
Operating system: ZorinOS 15
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.10
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/` 

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
do mine obsidian 

I first thought it was because of low TPS but it sometimes falls into lava at 20 TPS. Jesus hacks are not on or anything. It just continues mining the block while swimming in lava
## Modified settings
To get the modified settings run `#modified` in game
allowParkour - true
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Can you provide a video?

**Comment by CONBlaze** [comment]
> Can you provide a video?

https://streamable.com/ehlweb

**Comment by dominikaaaa** [comment]
That's the servers fault. You can see in the video baritone placed a block but the server removed it.
