### ISSUE TITLE
How can I mine exacly that block?

### ISSUE THREAD

**Issue by area51alienufo** [cabaletta/baritone#1680]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I have here two screenshots of the block that I would like to mine.
The problem is that in this mod all blocks are named ore but have diffrent id's but I cant just paste the id's in baritone. 
How an I supposed to do that?

![Unbenannt (2)](https://user-images.githubusercontent.com/38160916/81505565-715dcb00-92f0-11ea-87c2-ee73fb031fc5.png)
![Unbenannt (1)](https://user-images.githubusercontent.com/38160916/81505566-71f66180-92f0-11ea-80e3-e6ac886f2f0b.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Enter the block ID in the mine command.

**Comment by area51alienufo** [comment]
how? I get the message isn't a valid block name!

**Comment by dominikaaaa** [comment]
Thermal foundation isn't supported. Search this repo for the million other people asking the same question.

**Comment by UltraBlackLinux** [comment]
does this work? mine

**Comment by UltraBlackLinux** [comment]
mine 5293/5 OR mine thermalfoundation:ore/5 if it doesnt work replace / with :
