### ISSUE TITLE
Default hotbar slot

### ISSUE THREAD

**Issue by olsze1** [cabaletta/baritone#1681]
When I want to use .b mine (impact) on server (for quest) baritone use hotbar slot 1 and open menu with choosing mode to play. Is it possible to change slot 1 for any other slots?

**Comment by UltraBlackLinux** [comment]
Try using a corresponding tool, baritone will use it

**Comment by olsze1** [comment]
I mean when there is no tool for this type of block

**Comment by dominikaaaa** [comment]
See #1334
