### ISSUE TITLE
#mine does not work

### ISSUE THREAD

**Issue by akinblack** [cabaletta/baritone#1682]
## Some information
Operating system: Windows 10
Java version: Build 1.8.0
Minecraft version: 1.13.2-1.15.2
Baritone version: I don't know but it's the latest Impact version for 1.13.2 and higher

## Exception, error or logs
There are no errors I checked. If I do the #mine command it goes mining and everytime it's near the ore it changes his mind and goes to another ore and a loop begins. Please is this an anti-Bot mod?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/65178997/81581518-20f97280-93af-11ea-9630-fb6559df8ee4.gif)

## How to reproduce
Go in a Server and do #mine any ore.

## Modified settings
There are none just normal #mine command. Legit mine is also off.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x]  I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Restart it from another location ig

**Comment by akinblack** [comment]
Still does not work.

**Comment by akinblack** [comment]
> Restart it from another location ig



> Restart it from another location ig

THIS IS NOT CLOSED!

**Comment by akinblack** [comment]
> Restart it from another location ig

OPEN THIS ISSUE

**Comment by lflare** [comment]
Looks to be an anti-xray plugin, which Baritone somewhat relies on. Can't be fixed.
