### ISSUE TITLE
Can't Build Schematics

### ISSUE THREAD

**Issue by dreddsdynasty** [cabaletta/baritone#1683]
Some information
Operating system: Win 10
Java version: build 1.8.0_251-b08
Minecraft version: 1.14.4
Baritone version: Impact 4.8.3
Forge mods (if used): N/A

[latest.log](https://github.com/cabaletta/baritone/files/4612030/latest.log)

I placed the schematic in the folder in .minecraft. Then when I loaded  up a super flat and ran the build command I just got this error: 
![2020-05-12_08 50 21](https://user-images.githubusercontent.com/65195061/81611338-fcdd7600-942e-11ea-8516-3bb571830493.png)

Modified settings
![image](https://user-images.githubusercontent.com/65195061/81611569-62316700-942f-11ea-9756-16a00e63804e.png)

**Comment by dominikaaaa** [comment]
Include the full file name.

**Comment by dreddsdynasty** [comment]
> Include the full file name.

I don't follow...

**Comment by dominikaaaa** [comment]
The full file name as the file is named. 
For example:
![2020-05-11-183018_627x136_scrot](https://user-images.githubusercontent.com/17222512/81618502-7afd3680-93b5-11ea-8559-a1d02a6bdb29.png)
If you file is named that, the command would be `#build penish.schematic`, not `build penis`

**Comment by dreddsdynasty** [comment]
Still getting the same error message.
Even with the full file name.

**Comment by dominikaaaa** [comment]
Send the log.

**Comment by dreddsdynasty** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/4612543/latest.log)

**Comment by dominikaaaa** [comment]
You have to create your schematic in sponge format or in the same version as you're building it in

**Comment by dreddsdynasty** [comment]
ohhh ok thanks for your help
