### ISSUE TITLE
Trying to auto mine logs, when i try to do .b sel replace log air it works but then after a while a light blue line starts spazzing and i cant move

### ISSUE THREAD

**Issue by TheFishyKing27** [cabaletta/baritone#1684]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.

**Comment by TheFishyKing27** [comment]
whats the issue template

**Comment by dominikaaaa** [comment]
The template that comes up when you create a new issue.
