### ISSUE TITLE
What is the correct file name?

### ISSUE THREAD

**Issue by Catzardo330** [cabaletta/baritone#1686]
I submitted a bug issue, and this is what i got back
https://github.com/cabaletta/baritone/issues/1672#issue-615051960

I have no idea what file name to use or what I even did wrong, can someone explain?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
The full file name as the file is named. 
For example:
![2020-05-11-183018_627x136_scrot](https://user-images.githubusercontent.com/17222512/81618502-7afd3680-93b5-11ea-8559-a1d02a6bdb29.png)
If your file is named that, the command would be `#build penish.schematic`, not `build penis`

**Comment by Catzardo330** [comment]
Would that work in Impact? The command in Impact for baritone is .b build
