### ISSUE TITLE
Baritone cant build schematics. (Unhandled Exception)

### ISSUE THREAD

**Issue by Apitaph** [cabaletta/baritone#1688]
## Some information
Operating system:Windows 10
Java version:1.8.0_231-b11
Minecraft version:1.12.2
Baritone version:1.2.10
Forge mods (if used): none

## Exception, error or logs
19:53:08.621
bjb
main
[CHAT] [Baritone] > build funnydog
19:53:08.630
bjb
main
[CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
19:53:08.631
no
main
[STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.IllegalStateException: bad schematic 
19:53:08.631
no
main
[STDERR]: 	at baritone.cc.execute(Unknown Source)
19:53:08.631
no
main
[STDERR]: 	at baritone.x.a(Unknown Source)
19:53:08.631
no
main
[STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
19:53:08.631
no
main
[STDERR]: 	at baritone.ce.a(Unknown Source)
19:53:08.631
no
main
[STDERR]: 	at baritone.ce$$Lambda$693/53696275.accept(Unknown Source)

19:53:14.114
bjb
main
[CHAT] [Baritone] > build funnydog.schematic
19:53:14.123
bjb
main
[CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
19:53:14.123
no
main
[STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.IllegalStateException: bad schematic 
19:53:14.123
no
main
[STDERR]: 	at baritone.cc.execute(Unknown Source)
19:53:14.123
no
main
[STDERR]: 	at baritone.x.a(Unknown Source)
19:53:14.123
no
main
[STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
19:53:14.124
no
main
[STDERR]: 	at baritone.ce.a(Unknown Source)
19:53:14.124
no
main
[STDERR]: 	at baritone.ce$$Lambda$693/53696275.accept(Unknown Source)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
 .b build (any schematic) 

## Modified settings
To get the modified settings run `#modified` in game
AllowParkour (Boolean)
AllowParkourPlace (Boolean)
assumeStep (Boolean)
MaxFallHeightBucket (Boolean)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
include the full file name

**Comment by Apitaph** [comment]
> 
> 
> include the full file name

As in include the .schematic at the end? I did that secondly in the post and there was the same error

**Comment by UltraBlackLinux** [comment]
Your schematic seems broken, try anotherone

**Comment by Apitaph** [comment]
> 
> 
> Your schematic seems broken, try anotherone

Yeah that was it, i downloaded another one and it works fine. Can you recommend a website with a lot of schematic files on it? Im having trouble finding a good one.

**Comment by UltraBlackLinux** [comment]
Maybe planet mc - its a page w/ the crappiest content, but you can find loads of stuff there

**Comment by DaraHeaphy** [comment]
any updates? having similar issue
