### ISSUE TITLE
How to use go home after mining?

### ISSUE THREAD

**Issue by katzerax** [cabaletta/baritone#1690]
## What do you need help with?
Im not sure how to utilize the code implemented in pull request #910 to go home after mining, or put items in a chest after mining.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
https://www.google.com/search?q=what+is+a+pull+request

**Comment by UltraBlackLinux** [comment]
You can do this man, by setting a waypoint at your home
