### ISSUE TITLE
Add a find structure command

### ISSUE THREAD

**Issue by Dipek** [cabaletta/baritone#1693]
## Describe your suggestion
So, you would enter a command to set a goal in the nearest structure. So Minecraft has a /locate command that gets the coordinates, so it would be similar in Baritone, but instead of giving you the coords... It will set the goal. After that, you can do #path and your good to go!
## Settings
I don't see how this can be modified.
## Context
It would allow to easier find Villages, Temples, Igloos etc.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by The2nddarkness** [comment]
Sounds like an Interesting challenge, i have thought about this modification a few times when playing on a new server as i always like to build my bases close to a village. However, on spawn I often don't have the patience to search for these things. I will try my hand at this one asap.

**Comment by dominikaaaa** [comment]
`#goto <insert coordinates>`

**Comment by Dipek** [comment]
I meant without using /locate, like your on a multiplayer server. You can't really use /locate can you?

**Comment by UltraBlackLinux** [comment]
But this locatw would only work in renderdistance, quite useless

**Comment by dominikaaaa** [comment]
The only way this is possible is with a seed cracker or op permission, and a seed cracker is an external tool, and not what baritone is for.
