### ISSUE TITLE
Make Baritone Movements smoother

### ISSUE THREAD

**Issue by ToxicDevv** [cabaletta/baritone#1694]
## Describe your suggestion
It would allow baritone to make smoother movements instead of just snapping to a block or ore

## Settings
how fast or slow it would snap

## Context
It would improve baritone by making it look nicer and smoother and make it look less suspicious to owners/admins 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Ctrl f

**Comment by ToxicDevv** [comment]
CTRL + f???

**Comment by dominikaaaa** [comment]
this is a duplicate, use the search
