### ISSUE TITLE
Bot don't wanna get dropped ore

### ISSUE THREAD

**Issue by Spirious111** [cabaletta/baritone#1695]
First, i'm french so sorry if my english is bad.

Hellow, i've puted all the setting we need to put to make the bot go and get the dropped item that he broke, but some times, he just ignore the item and go on the next one ore without getting the first already broke, how can i fix that ? thanks

**Comment by UltraBlackLinux** [comment]
@Spirious111 Thats baritone wierdo. Sometimes it mines a block goes to the next one and later it picks it up, the problwm is, that the item despawns before the bot picks it up. U cant fix that sadly, thats how baritone calculates the path...

**Comment by dominikaaaa** [comment]
mineScanDroppedItems, mineDropLoiterDurationMSThanksLouca
