### ISSUE TITLE
Baritone Crashing on Launch (1.14.4)

### ISSUE THREAD

**Issue by RicochetYT** [cabaletta/baritone#1699]
## Some information
Operating system: Windows 10
Java version: Version 8 Update 251 (build 1.8.0_251-b08)
Minecraft version: 1.14.4
Baritone version: 1.4.6
Forge mods (if used): None

## Exception, error or logs
https://pastebin.com/ExV6GM0m
(There was nothing in my /Logs folder so I had to go into the launcher logs.)

## How to reproduce
- Fresh install of Minecraft Launcher (Wiped .minecraft and Minecraft Launcher folder)
- Boot 1.14.4 Once successfully
- Use the custom Baritone JSON for 1.14.4 (Made by the creators)
- Boot
- Crash for no reason
- Look through several other crash reports only to find one similar one with no answer.
- Cry.

## Modified settings
To get the modified settings run `#modified` in game
(Doesn't apply since I reset the Baritone settings after wiping my whole MC folder.)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
Paste the json here too pls

**Comment by UltraBlackLinux** [comment]
Try multimc, the installation is way easier. I created a tool for the json on this launcher

**Comment by dominikaaaa** [comment]
Use the official launcher.
