### ISSUE TITLE
Auto chest filling bot?

### ISSUE THREAD

**Issue by Mtusic** [cabaletta/baritone#1701]
Hi, I'm a complete noob when it comes to coding ect.

I was wondering if there was a fork/extension for baritone that allowed the bot to place items in a chest when the bot's inventory is full while carrying out a mining function such as: .mine or .sel cleararea . 

Alternatively is there a way I can code my own fork/extension for baritone to do this and how would you suggest I go about doing this?

Thank you,

~Mtusic

**Comment by dominikaaaa** [comment]
#605

**Comment by dominikaaaa** [comment]
> Alternatively is there a way I can code my own fork/extension for baritone to do this and how would you suggest I go about doing this?

idk learn how to code
