### ISSUE TITLE
How to make a JSON for a built Baritone Jar

### ISSUE THREAD

**Issue by Styxies** [cabaletta/baritone#1702]
## What do you need help with?
I need help with making the Minecraft Launcher run the compiled version of baritone on my pc. I followed all steps for building baritone and I now need help on how to make the JSON file to run the given files.

## Final checklist
- [X] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Ctrl f

**Comment by UltraBlackLinux** [comment]
If ur using multimc, I can help you. If not: look through the closed issues. U will find several posts with .jsons for the normal mc launcher
