### ISSUE TITLE
Buildinlayers modified stops building after the 0 layer.

### ISSUE THREAD

**Issue by DeadLord1337** [cabaletta/baritone#1703]
## Some information
Operating system: Windows 10
Java version: Java 8 Update 221 (build 1.8.0_221-b11)
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): None

## Exception, error or logs
[Download link Debug and Lasted logs](https://drive.google.com/open?id=1CXI6bQhSXE-ZpyRE1i5TbWz6qJpSFChj) 

## How to reproduce
1 - Launching minecraft with baritone 1.2.14 and Forge 14.23.5.2847 (TLauncher-Forge 1.12.2)
2 - I go to any world or server (this problem is everywhere).
3 - I want to build the statue of liberty.
4 - enter a command in the chat to build - build libertyst2.schematic. [Schematic file download link](https://drive.google.com/open?id=1ECzD4W07kfRfoFh2ogQZlzP7atYHbWxy)
5 - I wait, and after building 0 layer, it stops building.
6 - I enter the chat - #resume, thinking that the building is put on pause, but nothing happens
7 - I leave minecraft in a misunderstanding...
P.S: I noticed this problem even in minecraft 1.14.4 and 1.12.2 (Impact client) everything is exactly the same. I tried reinstalling minecraft completely, but the problem still remains..

## Modified settings
allowDiagonalDescend true
allowDiagonalAscend true
allowParkour true
maxFallHeightNoWater 4
chatControl false
freeLook false
antiCheatCompatibility false
buildInLayers true
okIfWater true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by DeadLord1337** [comment]
I solved this problem

**Comment by dominikaaaa** [comment]
how?? at least leave an answer for people in the future lmao

**Comment by DeadLord1337** [comment]
@dominikaaaa I just enabled the following settings :D

buildIgnoreBlocks air
buildIgnoreExisting true
buildInLayers true

**Comment by iSeekerTW** [comment]
thank you so much!!!!!
