### ISSUE TITLE
Help with BaritoneAPI mapping

### ISSUE THREAD

**Issue by NateKomodo** [cabaletta/baritone#1704]
## What do you need help with?
When calling the Baritone API, i get a field not found error that i assume is caused by mapping issues. I referenced baritone by adding the latest api-forge and mixin 1.0.2 to my libs folder, then added
```
compile fileTree(dir: 'libs', include: ['*.jar']) 
```
to my build.gradle

I'm assuming one of the following is true:
- I havent referenced baritone and mixin correctly or in the intentional way
- I need to run some method for mapping

Any help?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
does it work in a dev env?

**Comment by NateKomodo** [comment]
> 
> 
> does it work in a dev env?

Im running this via the runClient gradle task

**Comment by dominikaaaa** [comment]
does it work if you run it through the provided intellij app?

**Comment by NateKomodo** [comment]
> 
> 
> does it work if you run it through the provided intellij app?

I'm not sure what you mean by that, is there a sample project I've missed?

**Comment by dominikaaaa** [comment]
You're able to create an "application" for intellij if you're using forgegradle, which allows you to run a debugger with your forge mod. You should just be able to run genIntellijRuns and then get this 
![maim-2020-05-17-21-26-34](https://user-images.githubusercontent.com/17222512/82166008-1e9e8900-9885-11ea-99cd-ef8eb0fd80ac.png)

**Comment by NateKomodo** [comment]
Works fine when built, so I'll assume something wrong with the runClient gradle task

**Comment by dominikaaaa** [comment]
Yea, that's why I asked about the application, I don't recommend using runClient.
