### ISSUE TITLE
Issues placing blocks in 1.15.2

### ISSUE THREAD

**Issue by KlusterMonkey** [cabaletta/baritone#1705]
## Some information
Operating system: Windows 10 64 bit
Java version: Version 8 Update 241
Minecraft version: 1.15.2 (Aristois build 295)
Baritone version: Got a 'null version', I'm running the latest Fabritone fork.
Forge mods (if used): Optifine (experienced the issue before Optifine was installed)

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/4641913/latest.log)

Logfile cut a bit to protect privacy of a private server/members, but I only cut between logging on and logging off of this server, the singleplayer logs are in tact. This error occurs on singleplayer (shown in the log) as well as multiple multiplayer servers.

Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Easiest way to reproduce this issue is to dig a pit, disable block breaking and try to path out. This issue occurs very frequently however in normal mining and building circumstances with default settings, as well as the settings I have here. [Here's a video of the issue.](https://streamable.com/8exkbu)

## Modified settings
To get the modified settings run `#modified` in game

allowBreak false
allowDiagonalDescend true
allowDiagonalAscend true
blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,spawner
allowVines true
allowParkour true
allowParkourPlace true
blockReachDistance 4.3
avoidance true
buildInLayers true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by KlusterMonkey** [comment]
After using the impact client, it's clear this is an issue with Aristois not Baritone

**Comment by dominikaaaa** [comment]
you're using fabritone, not baritone in the first place
