### ISSUE TITLE
Preventing mining same block multiple times on low TPS

### ISSUE THREAD

**Issue by nombrekeff** [cabaletta/baritone#1707]
## Describe your suggestion
I've been using Baritone on low TPS servers and realized that when mining a block with low TPS it sometimes does not mine the first time so baritone mines it, again and again, wasting durability. 

I don't know if this has been talked about, but I think it would be a nice addition, that it knows to not break the same block multiple times and conserve some durability (would be good for big highways or large mining operations).

I haven't looked at the code (yet) so this is just speculation, but some possible solutions would be:

1. Wait until the mined block is dropped, either when picking it up or hearing it fall (similar to auto fish).
2. Make some kind of average of the time it takes to mine a block with certain TPS and use it for the next mined block (this is relative, as it differs from pick to pick and from block to block).
3. Watching pickaxe durability (not reliable as if unbreaking or mending is present it does not reflect exactly the amount of blocks mined)

> I imagine there are more ways of accomplishing this but have not thought that much, will add more suggestions if I come across any.

## Settings
Maybe a `delay between blocks` setting would fit in, so we can configure the time between mining a block and mining another one.

## Context
This would mainly help with preventing wasting tools.

**Comment by KMatias123** [comment]
the durability is server sided so it shouldnt waste it

**Comment by nombrekeff** [comment]
Ohh, yeah? Didn't know this, I was convinced it was wasting durability though... If it's server-side it's wonderful and no need to improve then :)



I will test it later and let you know though. Just in case some servers handle it differently.

**Comment by nombrekeff** [comment]
One thing I've noticed is, that when auto mining it sometimes takes 3-5 tries, although if doing it by hand it takes 1-2 tries, I don't know what is causing this if it's just those milliseconds between me mining a block and the next block. I will try and gather some more info about this if I can.

**Comment by nombrekeff** [comment]
Yeah, after much pain I finally have been able to test it out. It does not waste durability it seems.

Thanks for the quick reply! I will be back with more ideas, hopefully a bit better researched :P
