### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ColdHulkmask** [cabaletta/baritone#1712]
## Some information
Operating system:Windows
Java version:32 bit
Minecraft version:1.12.2
Baritone version:impact
[latest.log](https://github.com/cabaletta/baritone/files/4651278/latest.log)
[latest.log](https://github.com/cabaletta/baritone/files/4651335/latest.log)

Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i dont know how but i tried to use a schematic file and used #build but it said to report it here
## Modified settings
To get the modified settings run `#modified` in game
chatControl(boolean)
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue. UwU

**Comment by dominikaaaa** [comment]
you didn't put the schematic in the folder

**Comment by dominikaaaa** [comment]
actually, I misread it

> IllegalStateException: bad schematic 

Your schematic is broken

**Comment by UltraBlackLinux** [comment]
@dominikaaaa add this to faq?? this is the 2nd person with that problem...

**Comment by dominikaaaa** [comment]
Why does an error message have to be in the FAQ?

I can add "Please learn how to fucking read" to the faq

**Comment by dominikaaaa** [comment]
If the chat literally says "bad schematic" I don't understand how people don't understand "oh the schematic is broken"

**Comment by UltraBlackLinux** [comment]
@dominikaaaa ik, but we see to many ppl have this problem, there will follow more. Each of those will create an issue. Isnt that annoying?

**Comment by dominikaaaa** [comment]
> ik, but we see to many ppl have this problem, there will follow more. Each of those will create an issue. Isnt that annoying?

This is the first time I've seen an issue for bad schematic, and I read every issue here. If people can't learn how to read the chat and comprehend that "bad schematic" means the schematic is broken, then they won't read an faq.
