### ISSUE TITLE
1.12.2 impact avoidance doesn't work

### ISSUE THREAD

**Issue by AirKetchPLAYZ** [cabaletta/baritone#1714]
## Some information
Operating system: Linux Debian
Java version: openjdk version "1.8.0_252"
Minecraft version: 1.12.2
Baritone version: 1.2.10 (packaged with impact)
Forge mods (if used): none

# Steps to reproduce
Add your steps to reproduce the issue/bug experienced here.
.b avoidance true
.b goto <block name>

## Modified settings
To get the modified settings run `#modified` in game
allowParkour true
allowParkourPlace true
allowSprint false
avoidance true
colorCurrentPath 255,0,0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by DeadLord1337** [comment]
No debug or lastest.log, For the goto command, you need to specify where the baritone bot should go, coordinates, or the block name. Close issues

**Comment by AirKetchPLAYZ** [comment]
I did specify where to go. For example when I did .goto web it goes there. The problem is it doesn't avoid mobs. There weren't errors so I didn't see why to include a log.

**Comment by dominikaaaa** [comment]
provide a log

**Comment by DeadLord1337** [comment]
@AirKetchPLAYZ I just checked, I have everything working, I understand baritone avoids only the first nearest mob on the way. watching video https://www.youtube.com/watch?v=p6rp2_9fOQI. works for me impact 1.12.2

**Comment by AirKetchPLAYZ** [comment]
Doesn't work for me, walks right into a cave full of skeletons next to each other. Where do I get a log?

**Comment by dominikaaaa** [comment]
inside the log folder
