### ISSUE TITLE
#mine is not working

### ISSUE THREAD

**Issue by PartyManCZ** [cabaletta/baritone#1718]
![error](https://user-images.githubusercontent.com/51057771/82666564-7a2a9700-9c36-11ea-8d52-f5e520adc470.png)

EVEN WHEN THERE IS OBSIDIAN NEXT TO IT.

## Some information
Operating system: Win 10
Java version: Ver 8 Update 231
Minecraft version: 1.12.2
Baritone version: The Future client one
Forge mods (if used): Future client, WWE client, Toast+ control, smarthud, schematica, shulker box viewer, placebo, optifine, lunatrius core, luaj, iChunUtil, ding, custom backgrounds, controlling, client tweaks, client commands, bettertitlescreen, Baritone, autoreglib, advanced macros

## Exception, error or logs
Command executed on line 7226
[debug.log](https://github.com/cabaletta/baritone/files/4667863/debug.log)

## Modified settings
allowDiagonalAscend
allowDiagonalDescend
allowDownward
allowInventory
allowParkour
allowParkourPlace
allowVines
allowWalkOnBottomSlab
avoidance
chatControl

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#1717
