### ISSUE TITLE
Error at argument #1: Expcected aa

### ISSUE THREAD

**Issue by GarethCarew** [cabaletta/baritone#1720]
## Some information
Operating system: Windows 10
Java version: 1.8.0_251
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): (Modpack) Omnifactory

## How to reproduce
Attempting to mine silver ore from Greg tech: CE. I can mine vanilla ores fine. if I try "#mine gregtechcommunityedition:silver_ore" it gives me the error in the title. I'm probably just getting the mod tag wrong but I'm not sure what it is supposed to be.

I've tried:
gregtechcommunityedition:silver_ore
gregtechce:silver_ore
gregtech:silver_ore
![ErrorExpectedAA](https://user-images.githubusercontent.com/50182665/82703455-82d09c80-9c39-11ea-8716-4c9767492c13.png)
![Ore](https://user-images.githubusercontent.com/50182665/82703456-83693300-9c39-11ea-8273-2e36f75ec6d9.png)

## Modified settings
N/A

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You have to use modid:blockid

**Comment by GarethCarew** [comment]
@dominikaaaa That’s what I was doing, was I not? If I am not, then could you tell me how to do it correctly. I am pretty certain that I am doing modid:blockid as the mod is gregtech and the block I’d would be silver_ore.

**Comment by UltraBlackLinux** [comment]
Baritone seems to have some sierious mining problems - #1642

**Comment by dominikaaaa** [comment]
That's not a baritone issue, that's a mod issue.

**Comment by Deauthorized** [comment]
use version 31.1.0 of forge

**Comment by dominikaaaa** [comment]
That isn't related unless you're using v1.5.3

**Comment by CDAGaming** [comment]
Can you enable advanced tooltips to see the actual id that the game is interpreting it as?

**Comment by scorbett123** [comment]
I believe that this has been fixed, anyway it is a duplicate.
