### ISSUE TITLE
Add entitie ride or somthing (for boat,horse,etc)

### ISSUE THREAD

**Issue by anshbhalala** [cabaletta/baritone#1721]
## Describe your suggestion
Add a support for boat and horses (entiteride) for ease of travel

## Settings
I DONT KNOW XD (sorry but i am a rookie)

## Context
Improves mobilitie

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by anshbhalala** [comment]
Also if possible provide a download of baritone.json that works with optifine (if possible update it with every optifine release) (1.15.2 user) (its a request dont target me) (if u dont wanna do it fine just dont cringe me already :_____( )

**Comment by dominikaaaa** [comment]
#223

as for the json, search the repo, someone posted one
