### ISSUE TITLE
Item ID question

### ISSUE THREAD

**Issue by Yucareux** [cabaletta/baritone#1724]
## What do you need help with?
I'm trying to get Baritone to mine this:
![Sin título](https://user-images.githubusercontent.com/65836586/82743241-3c109e80-9d2e-11ea-9583-0cb5e8cb0faf.png)

The problem is that the item ID is generic, and I don't know how to specify that it exactly mine that block.
I tried to put the number 1 after the ID, but I get this error.
I'm on version 1.12.2
![asdf](https://user-images.githubusercontent.com/65836586/82743263-83972a80-9d2e-11ea-977e-d85336412d39.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by circl-lastname** [comment]
You need to put the 1 before the ore name

**Comment by dominikaaaa** [comment]
They're asking for setting the ID of it, not the amount.

**Comment by UltraBlackLinux** [comment]
Setting the id is possible via ":", e.g.: stone:2

**Comment by dominikaaaa** [comment]
That's not possible if you have a modid before it

**Comment by UltraBlackLinux** [comment]
It should be...

**Comment by dominikaaaa** [comment]
It should, but it isn't. Which is why this issue is still opened.

**Comment by UltraBlackLinux** [comment]
Maybe a slash instead if 2nd :

**Comment by TheK0tYaRa** [comment]
But.... `modid:block:subid` does work...

**Comment by ZacSharp** [comment]
For me it looks like the author wrote modid:block subid instead of modid:block:subid
Is that the problem here or have I missed something?

**Comment by dominikaaaa** [comment]
Oh yea
