### ISSUE TITLE
The 1.5.3 file could not be launched in macos

### ISSUE THREAD

**Issue by Nemodong** [cabaletta/baritone#1725]
"bariton 1.5.3" could not be launched. Thanks
<img width="369" alt="Screen Shot 2020-05-24 at 9 58 03 AM" src="https://user-images.githubusercontent.com/65073533/82743958-107ccb00-9da5-11ea-83ee-d00c2b498447.png">

**Comment by KMatias123** [comment]
use the minecraft launcher
