### ISSUE TITLE
Baritone GUI

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1726]
## Describe your suggestion
A GUI that has many functionalities; Changing Settings (maybe with search bar?), Manage Waypoints, Select schematics to build, Create Mining/Command Presets (that can be activated via a Keybind or GUI Button),...

## No setting, but command to open GUI - maybe a Keybind, that can be pressed to open it
#gui

## Context
Would make Baritone a more Comfortable to use. - At all.
Id really love this feature

**Comment by dominikaaaa** [comment]
No
