### ISSUE TITLE
Hey, can I ask you a question? 

### ISSUE THREAD

**Issue by qnmdzzsb** [cabaletta/baritone#1727]
I try to type #mine dirt To automatically dig soil     It turned out to be a pile of red letters
 What shall I do?  edition：1.12.2

![@(X`RM@5PD)R_ NV 1JZ`RW](https://user-images.githubusercontent.com/65850442/82751219-560eb780-9de8-11ea-9ba8-01fd2d24a241.png)

**Comment by UltraBlackLinux** [comment]
1. Most undescriptive Title
2. Did you read the message? It says "The Error is in your games's log". upload it, e.g. to [gist.github.com](gist.github.com)

**Comment by dominikaaaa** [comment]
fill out the template
