### ISSUE TITLE
Is there any guide how to add Baritone/BaritoneApi to a MCP Client?

### ISSUE THREAD

**Issue by MrAn0nym** [cabaletta/baritone#1728]
Is there any guide how to add Baritone/BaritoneApi to a MCP Client?

- [ ] Added Baritone to my Client

**Comment by UltraBlackLinux** [comment]
Quite easy actually. just use a json file - there r a few issues about this. Multimc is even easier to install baritone on:
#1535
#1289
...

**Comment by dominikaaaa** [comment]
No, because it's against mojangs ELUA

**Comment by MrAn0nym** [comment]
> No, because it's against mojangs ELUA

Do you mean that a Guide wouldn't be legal or a MCP Client?

**Comment by dominikaaaa** [comment]
Yes, both would be breaking Mojangs EULA.

**Comment by UltraBlackLinux** [comment]
In what way?

**Comment by dominikaaaa** [comment]
https://account.mojang.com/documents/minecraft_eula

It's literally in bold "One major rule"

**Comment by aapje303-site** [comment]
mojang didnt make mcp so distributing mcp clients **isnt** against eula

**Comment by FloGo3308** [comment]
> mojang didnt make mcp so distributing mcp clients **isnt** against eula

doesn't the output jar of a MCP client include minecrafts code itself?(obfuscated, but its still there)

**Comment by scorbett123** [comment]
> mojang didnt make mcp so distributing mcp clients **isnt** against eula

MCP itself is against mojangs eula, it contains minecraft's code. Therefore distributing mcp clients is against the eula.
