### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by NateKomodo** [cabaletta/baritone#1729]
## What do you need help with?
Anime OwO

## Final checklist
- [ ] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Banned for shitposting

**Comment by NateKomodo** [comment]
fuck

**Comment by dominikaaaa** [comment]
me when i get a notification for this very important baritone issue

**Comment by NateKomodo** [comment]
@dominikaaaa cant lie this issue is more descriptive then some of the other baritone issues

**Comment by dominikaaaa** [comment]
unfortunately, yes.
