### ISSUE TITLE
How change cleararea radius?

### ISSUE THREAD

**Issue by DeadLord1337** [cabaletta/baritone#1730]
## What do you need help with?
How can I change the block breaking radius when using the sel cleararea process? according to the standard, I understand that blocks are broken within a radius of 6 blocks, how to change this to 3 blocks, for example?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
There doesn't appear to be a setting for that. 

You *can* do `#sel` and `#sel replace air`

**Comment by DeadLord1337** [comment]
@dominikaaaa I actually found a setting for this :D

blockReachDistance 4.0 - where the number is the distance to the block

**Comment by Toiisha** [comment]
hi #baritone-log

**Comment by dominikaaaa** [comment]
@Toiisha please stop making spam comments
