### ISSUE TITLE
#build not working

### ISSUE THREAD

**Issue by Zvrf555** [cabaletta/baritone#1731]
Operating system: win 7
Java version:  1.8.0_251
Minecraft version: 1.14.4
Baritone version: 1.2.14
Forge mods (if used): 

## How to reproduce
just type #build and it won't work for me

## Modified settings
acceptablethrowawayitems minecraft:dirt               (i changed it once and now i dont know how to add more then 1 block into it)
allowparkour true
allowparkourplace true
assumewalkonwater true
buildinlayers true
chatcontrol false
maxfallheightbucket 165
primarytimeoutMS 1124

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
provide logs
