### ISSUE TITLE
Multiplayer compatible Baritone Tag

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1732]
A tag comparable to the next to name symbol in BAC

**Comment by dominikaaaa** [comment]
Fill out the issue template

**Comment by UltraBlackLinux** [comment]
This was not supposed to get sent

**Comment by UltraBlackLinux** [comment]
Also The template is not showing up at all - wtf github

**Comment by dominikaaaa** [comment]
Make a new issue with the template

https://github.com/cabaletta/baritone/issues/new/choose

**Comment by UltraBlackLinux** [comment]
For some reason does my github app not work as usual...
