### ISSUE TITLE
Baritone NameTag/Chat

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1733]
## Describe your suggestion
Baritone user could identify themselves with a lil symbol next to the name.
Maybe even some kinda baritone chat too - either irc or just packets that get sent or sth that only baritone users can read.

## Settings
#showtag

## Context
its quite useless, but you would see ppl with baritone, and, idk, team with em. Also they could chat w/ eachother w/o visible for anybody else

## Final checklist
- [x] E

**Comment by Deauthorized** [comment]
whats the point

**Comment by UltraBlackLinux** [comment]
thats litterally what im thinking about lol. idk what the point of this is. it makes exactly as less sense as BAC users can identify themselevs with such a thing. WHY DOES IT EXIST?! well never know

**Comment by dominikaaaa** [comment]
I don't see why this would improve baritone in the slightest.
