### ISSUE TITLE
Can't use mine and sel replace commands in lastest update.

### ISSUE THREAD

**Issue by sophronesis** [cabaletta/baritone#1734]
## Some information
Operating system: Ubuntu 18.04
Java version: openjdk version "1.8.0_252"
Minecraft version: 1.15.2
Baritone version: 1.15.3
Forge mods (if used): OptiFine-1.15.2_HD_U_G1_pre16.jar, MixinBootstrap-1.0.2.jar

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/4682522/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/4682523/latest.log)

## How to reproduce
Running any command that use block info will result in errors like this:
`Error at argument #1: Expected ForBlockOptionalMeta`
![image](https://user-images.githubusercontent.com/13190573/82906713-4faa4800-9f6e-11ea-9f1b-aaaa4a0426c7.png)
![image](https://user-images.githubusercontent.com/13190573/82906816-75cfe800-9f6e-11ea-887c-b3a92a2e8664.png)
Any other commands are unaffected

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

Found similar issue (#1648) but it was closed without any explanations so i think another one will do it's job

**Comment by UltraBlackLinux** [comment]
Didnt you read y it got closed? Here again: https://github.com/cabaletta/baritone/releases/tag/v1.5.3

**Comment by sophronesis** [comment]
> Didnt you read y it got closed? Here again: https://github.com/cabaletta/baritone/releases/tag/v1.5.3

In Forge 31.1.0 works like a charm. Can close now

**Comment by MasterOrg012** [comment]
u need change the method try this #mine minecraft:diamond_ore for mi works fine

**Comment by sophronesis** [comment]
> u need change the method try this #mine minecraft:diamond_ore for mi works fine

Look closely to first screenshot. I tried all variants possible and none worked
