### ISSUE TITLE
Baritone 1.15.2 does not show up in the installation

### ISSUE THREAD

**Issue by Nemodong** [cabaletta/baritone#1735]
hello sorry to bother. My computer is a mac. I have put the whole baritone folder in the version folder of Minecraft. However, it does not show up in the installation? Do you know whats wrong with it? Thanks a lot.

**Comment by dominikaaaa** [comment]
Um, that's not how you install it.

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md
