### ISSUE TITLE
Wym thats not how to install?

### ISSUE THREAD

**Issue by Nemodong** [cabaletta/baritone#1736]
<img width="628" alt="Screen Shot 2020-05-27 at 10 38 10 AM" src="https://user-images.githubusercontent.com/65073533/82971812-2a691880-a006-11ea-926b-fd0967785ddf.png">
hello? it literally says drag and drop into versions? if thats not how you put it, can u at least teach me instead of jus showing me a link? Thank you.

**Comment by dominikaaaa** [comment]
You drag and drop the baritone/baritone.json into the versions folder, not the repo.
