### ISSUE TITLE
Addon system

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1738]
## Describe your suggestion
A way to create .jar or whatever extentions, that can be loaded to Baritone. To implement unofficial features.
## Settings
#addon enable/disable bla.jar
#addon folder

## Context
This would users give the ability to create custom baritone addons, that may end up in a pull request. This is basically a way to modify Baritone with features, that havent got implemented yet/ever, e.g. #1733 
Also, an additional Plugin Repo would be cool.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#881
