### ISSUE TITLE
Allow Baritone commands to be controlled by external mods (E.g. MC-Macro Mod)

### ISSUE THREAD

**Issue by CrusadeChaos** [cabaletta/baritone#1739]
## Describe your suggestion

Intercept simulated chat packets sent by other mods.
## Settings

#chatIntercept
Toggles between if Baritone is intercepting chat packets or not.
## Context

Allow you to use baritone commands in other mods such as Macro Keybind Mod by intercepting simulated chat packets from those mods.

This would allow players to make scripts that support Baritone.

Currently, trying to send #goto for example in chat using a script in mc-macro mod would result in the message ("#goto") being fully printed in chat instead of running the Baritone command. It would be very helpful if this can be rectified. Thanks in advance.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue as this is gay.

**Comment by KleinBagel** [comment]
good idea =)

**Comment by UltraBlackLinux** [comment]
isnt that possible already?

**Comment by KleinBagel** [comment]
yes but it does not detect the personal chat I give the commands with type in macro keybind

**Comment by UltraBlackLinux** [comment]
so Baritone would have to use a bit different system: Baritone Reads chat all time, and every thing wrote into chat would be checked by baritone, if its a command, else it will be let though to the server

**Comment by KMatias123** [comment]
it has an api

**Comment by UltraBlackLinux** [comment]
whatever xD

**Comment by dominikaaaa** [comment]
this entire repository is the API. 

Baritone chat control is already possible with mods, if it doesn't work for your mod then that's your fault.
