### ISSUE TITLE
Baritone spams me with "Paused due to lag!" and "Unpaused!" messages without a reason.

### ISSUE THREAD

**Issue by iSeros** [cabaletta/baritone#1743]
![image](https://user-images.githubusercontent.com/59029191/83163019-2c6ccd80-a113-11ea-8e40-8cfdf576aa2d.png)

Here are the messages, and in action. ^^

So, brief explanation:

Baritone keeps spamming me with those "Paused due to lag!" and "Unpaused!" messages mostly when the server has 1 to 8 TPS, still happens when it's above 15 TPS. This has never happened before, till I got Impact. When I used other clients with Baritone integrated in them, and even Baritone standalone, it never happened, even when the TPS was 1 to 8. This is a weird issue, and it seems like the help channel in Impact didn't help me with this issue, so I reported it here.

Oh also, I socialize in chat as this is not 2b2t where the chat is just random stuff, so this is a pretty large issue for me as I cannot see other people's messages.

**Comment by dominikaaaa** [comment]
This is a kami blue feature, in lag notifier. You can disable the chat option in the module settings, or completely disable baritone pausing when the server is lagging.

**Comment by dominikaaaa** [comment]
Note this only happens when the server is lagging (unless you're using an older release which was bugged), and you can change how long it waits to do that (default is 2 seconds)
