### ISSUE TITLE
Build Not working

### ISSUE THREAD

**Issue by ItCameFr0mMars** [cabaletta/baritone#1744]
## Some information
Operating system: Windows
Java version: 8 update 211 
Minecraft version: 1.12.2
Baritone version: Latest
Forge mods (if used): SalHack and Impact 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

When I tried to use #build, it successfully loads the schematic, but then says, unable to do it. I moved a few blocked and tried again, and it worked. I am making a big mapart and do not want to have to move it. Is there any fix?

**Comment by dominikaaaa** [comment]
you're either missing some blocks in your hotbar, or there's a liquid or something in the way

**Comment by ItCameFr0mMars** [comment]
I had all of the materials.

**Comment by dominikaaaa** [comment]
In your hotbar?

**Comment by ItCameFr0mMars** [comment]
Yes, in my hotbar

**Comment by UltraBlackLinux** [comment]
Is there som tallgrass or sth in the way?

**Comment by ItCameFr0mMars** [comment]
That’s probably it
