### ISSUE TITLE
Surface command

### ISSUE THREAD

**Issue by cazeip** [cabaletta/baritone#1745]
## Describe your suggestion
Add a command `surface` that would find a path to the surface of the overworld.

## Settings
There is no need for settings, it just finds the most optimized path to the surface of the world, which is not necessarily at the same coordinates as the player when he runs the command.

## Context
It would we useful to find a path to the surface because using the `goto` command is not the best idea, because it's hard for players to find the Y coordinates of the surface, because it is not always 64, thanks to the mountains.
I usually use `goto ~ 80 ~` but it either :

- Stops while you're still underground

- Gets to the surface and starts pillaring up

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by hYdos** [comment]
this has been done. Should it be closed?
