### ISSUE TITLE
Builder places wrong blocks somewhere

### ISSUE THREAD

**Issue by itdimk** [cabaletta/baritone#1746]
## What do you need help with?
Hi!. I got a problem.
When i'm using ".b build schematic-file" bot places wrong blocks somewhere.
For example, places clay instead of polished diorite or just places andesite instead of another blocks.
And more, bot doesn't break any wrong blocks to place correct block instead at all.
Schematic file is flat horizontal rectangle 256x256 (kinda pixel-art) was created with SpriteCraft.
Minecraft Version 1.12.2 FORGE

## Final checklist
I was trying to toggle some settings, but problem still be.

**Comment by UltraBlackLinux** [comment]
For me it sounds like 1492
