### ISSUE TITLE
Baritone just not working?

### ISSUE THREAD

**Issue by DefinitelyNoIdeasForNames** [cabaletta/baritone#1747]
So... Idk if I am just stupid, but I downloaded baritone for minecraft 1.12.2, and I just can't get it to work. I don't know if I maybe didn't install it properly, but I know it is... installed because I got a message from baritone. However when I want to use the help command nothing happens, I've used every prefix I that could work, like # .b . and... idk #b or anything like that. I am not using impact, still tried .b and stuff like that, still nothing.

**Comment by dominikaaaa** [comment]
The prefix is #

**Comment by DefinitelyNoIdeasForNames** [comment]
> The prefix is #

doesn't work

**Comment by dominikaaaa** [comment]
send a screenshot of the error

**Comment by DefinitelyNoIdeasForNames** [comment]
> send a screenshot of the error

that's my problem, there is no error, f.ex. #help is just being send into the normal chat in minecraft, did I maybe do something wrong when installing baritone?

![image](https://user-images.githubusercontent.com/66178284/83336001-c1f19400-a2b0-11ea-90f1-8f6c27e272a7.png)
this is the only file I downloaded lol

**Comment by dominikaaaa** [comment]
Send a screenshot of how you installed it then

**Comment by DefinitelyNoIdeasForNames** [comment]
> Send a screenshot of how you installed it then

wdym? I just downloaded this file and then I put it into my mods folder, maybe I did it wrong?

**Comment by dominikaaaa** [comment]
Send your log file then

**Comment by DefinitelyNoIdeasForNames** [comment]
> Send your log file then

well haha... where do I find them and how could they help me? xd

**Comment by dominikaaaa** [comment]
inside the minecraft/logs/latest.log folder

**Comment by DefinitelyNoIdeasForNames** [comment]
> inside the minecraft/logs/latest.log folder

well... how would that help me, and what would I have to look for?

**Comment by dominikaaaa** [comment]
just look for the file called latest.log

**Comment by DefinitelyNoIdeasForNames** [comment]
at one point it said "Inspecting jar metadata in 'baritone-standalone-forge-1.2.14"
In the next line it says
Ignoring (path of the file)"baritone-standalone-forge-1.2.14" does that mean anything, maybe? lol

**Comment by dominikaaaa** [comment]
if it loaded baritone then idk what you did wrong

**Comment by DefinitelyNoIdeasForNames** [comment]
> if it loaded baritone then idk what you did wrong

I think I found out why it is not working, well... not really. I've tried baritone out alone, that works. The other mods I used before were: Optifine, the 5zig mod and the macro mod, I thought non of them would block anything chat-wise? Now I will find out which mods "blocks" baritone, or do you know it? lol

**Comment by dominikaaaa** [comment]
macro mod messes up a lot of stuff

**Comment by Pr0gr1m** [comment]
so what's an soultion?

**Comment by Pr0gr1m** [comment]
xd 2 years ago probably nobody will rspnd

**Comment by stfecelamiater** [comment]
install fabric 1.19.3, fabric api 1.19.3, (or forge, but i don't know how to do it with forge), put fabric api in mods, install baritone standalone fabric 1.9.1 (1.19.3), load minecraft with the fabric 1.19.3 version, prefix is #

**Comment by grandtitan** [comment]
Literally same issue. Done everything like im supposed to and it just wont work.

Edit: I disabled optifabric minihud, optifine and malilib and now it works.
