### ISSUE TITLE
Add blocks max count for #mine command

### ISSUE THREAD

**Issue by Fokz210** [cabaletta/baritone#1748]
## Describe your suggestion
It would be cool if i could set count of blocks i want to be mined

## Settings
Just add subcommand to #mine
#mine diamond_ore 128 - mine just 128 diamonds and then stop

## Context
I was just making my morning coffee while my baritone was mining. When i came back i saw, that my inventory was full, baritone was just wasting diamonds and i could be killed by mobs in the cave, and i thougt that it would be cool if it will stop mining when reaches some couple of stacks

Have a good day bro :)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
that's actually how it works

**Comment by dominikaaaa** [comment]
this is already a feature lol

**Comment by dominikaaaa** [comment]
![maim-2020-05-30-15-00-28](https://user-images.githubusercontent.com/17222512/83337064-5eeb0780-a286-11ea-93e6-3541e7b1d3fc.png)

**Comment by Fokz210** [comment]
Ahahaha lol i tried but it was saying just invalid block meta :C 
Sorry for your time, my bad
