### ISSUE TITLE
can you select some blocks that baritone should not destroy with #mine?

### ISSUE THREAD

**Issue by DefinitelyNoIdeasForNames** [cabaletta/baritone#1749]
If you play a game where there is an area where blocks are respawning, can you select some blocks that should not destroy? Also is there a place to ask questions about baritone other than here? Because I have many more questions about Baritone, if yes, I guess I will ask them there, because idk if this is the right place to ask the questions, but if not, I guess I'll ask here

**Comment by UltraBlackLinux** [comment]
@DefinitelyNoIdeasForNames 
I think there is an option
BlocksAvoidBreaking (string)
And I think there is no other place to ask...
