### ISSUE TITLE
Do not break tools Setting would be nice

### ISSUE THREAD

**Issue by DE-Max-42** [cabaletta/baritone#1753]
## Describe your suggestion
A setting to not break tools would be very nice to have to repair enchantet tools.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You can enable ToolSaver or whatever it's called in Impact, with KAMI Blue having a similar feature planned. Idk if WWE or other clients have it though

**Comment by DE-Max-42** [comment]
Thanks for the Suggestio,n i will try them.
