### ISSUE TITLE
Gettings Stuck On a carpet

### ISSUE THREAD

**Issue by ItCameFr0mMars** [cabaletta/baritone#1754]
![the thing](https://user-images.githubusercontent.com/48456413/83666834-8e0dbb80-a59b-11ea-97b0-81cf9b7db781.gif)

## Some information
Operating system: Win10
Java version: Latest
Minecraft version: 1.12.2
Baritone version: Latest
Forge mods (if used): Impact, SalHack

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here. 
Have a build with a lot of carpets. (like mapart) then wait.

## Modified settings
To get the modified settings run `#modified` in game
allowinventory true
chatcontrol true.

I was building a mappart when this happened. (srry for bad quality)

## Final checklist
- [x] I know how to properly use check boxes 
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by ItCameFr0mMars** [comment]
Is anyone helping?

**Comment by dominikaaaa** [comment]
can't reproduce this issue.

**Comment by ItCameFr0mMars** [comment]
Might be because I have some hacks enabled

**Comment by UltraBlackLinux** [comment]
some ppl use carpet ontop of carpet to stop villagers from pathfinding in their trading halls. Could be the same here too.

**Comment by dominikaaaa** [comment]
Baritone can pathfind on carpet just fine in my testing, it's not the primitive mob "AI" that minecraft uses

**Comment by arceuss** [comment]
same here
