### ISSUE TITLE
Error Log Build Schematic

### ISSUE THREAD

**Issue by Spekbillenn** [cabaletta/baritone#1758]
## Some information
Operating system: Windows 10 Pro
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.14.4 (Inside Impact)
Forge mods (if used):  None

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/4737010/latest.log)

## How to reproduce
i did "#build atlas-statue"

## Modified settings
[Baritone] All modified settings:
[Baritone] allowParkour (Boolean)
[Baritone] allowParkourPlace (Boolean)
[Baritone] allowPlace (Boolean)
[Baritone] chatControl (Boolean)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You gotta allowPlace
