### ISSUE TITLE
Mining/Following with NBT

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1760]
labels: enhancement

## Describe your suggestion

So basically allows baritone to mine a block with a specific nbt tag, e.g. 

#mine furnace[lit=true]

## Settings

#togglenbtmode
Toggles between the vanilla nbt tag syntax and an easier one based on entity nbt ("block" = placeholder for mc block):
mine block[nbt]
What also would work with the entity based syntax:

mine block[r=5]

mine block[r=..5]

And custom syntax:

mine block[facing=north]..

(This ".." at the end allows the use of an expandable selector: not only blocks with this nbt will be mined, also blocks with this and some other.)

Examples:

mine log:3[r=20,x=~3,y=3..5,z=7]

mine iron_door[facing=north]..

## Context

This would add more funcionality to the mine feature and make it better for specific uses, e.g. u placed a ton of doors in the wrong direction  near u, then u do: 

#mine door[r=..20,facing=north]

This could also enhance the follow command (and maybe more)

## Final checklist

- [x] I know how to properly use check boxes

**Comment by YunaraD0ki** [comment]
I must say that this is a very good idea. Using NBT tags and block states would be really useful.

**Comment by rahulcvwebsitehosting** [comment]
Fixed this in my fork — https://github.com/rahulcvwebsitehosting/baritone. Not PR'd upstream yet but it works if you need it now. Lmk if anything's off.

**Comment by UltraBlackLinux** [comment]
Uh what? This was merged over three years ago. What is there to fix?

**Comment by rahulcvwebsitehosting** [comment]
After personal testing the bot wasnt able to mine north facing blocks specifically there were some issues with that in Public servers, i have fixed that.

**Comment by UltraBlackLinux** [comment]
What exactly does that have to do with this feature request?

**Comment by rahulcvwebsitehosting** [comment]
Just to inform you that i have made a personal fork of Baritone to make those fixes, and would love to take any feature requests if you like my changes.

**Comment by UltraBlackLinux** [comment]
bröther ... -- no.

Seems mostly AI generated anyway.
