### ISSUE TITLE
im trying to load a schematica of map art but when i do #build (name of schematic) it says "Error at arguent #2 ExpectedRelativeBlocPos" does anyone know what this means?

### ISSUE THREAD

**Issue by owen-pp** [cabaletta/baritone#1761]
## Some information
Operating system:windows
Java version:java 8 update 251
Minecraft version:1.15.2
Baritone version:1.8.3
Forge mods (if used): NA

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
ExpectedRelativeBlocPos
