### ISSUE TITLE
im trying to load a schematica of map art but when i do #build (name of schematic) it says "Error at arguent #2 ExpectedRelativeBlocPos" does anyone know what this means?

### ISSUE THREAD

**Issue by owen-pp** [cabaletta/baritone#1762]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
ExpectedRelativeBlocPos
