### ISSUE TITLE
4 Block Parkour jumps

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1763]
## Describe your suggestion
Just 4 Block parkour jumps - why arent they added yet?

## Context
I just thought it would be better if Baritone could do that...

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by mariusdkm** [comment]
The problem is, you have to calculate precicly how far you can jump with the current momentum, and what to do if you don't have enough momentum, how you to gain that momentum. 
Whereas it's much simpler, to just build a bridge.

But it would definetly add some cool parkour skills.

**Comment by dominikaaaa** [comment]
It's too unreliable. Iirc there's also more risky parkour options already available that should do this
