### ISSUE TITLE
.locate System

### ISSUE THREAD

**Issue by Baduser902** [cabaletta/baritone#1765]
## Some information
Operating system: Windows 10 2004
Java version: Version 8 Update 251
Minecraft version: 1.1.52
Baritone version: Impact Nightly Version 0527
Forge mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
To reproduce just enter .locate pillager_outpost.
I've found that the .locate feature only works for strongholds and sometimes is 1k blocks off when compared to /locate.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
this isn't related to baritone???
