### ISSUE TITLE
Baritone's buildinlayers feature.

### ISSUE THREAD

**Issue by Warpeer** [cabaletta/baritone#1768]
Is it possible to select a specific layer for Baritone to build? I've been having issues with the bot only trying to build layer 0, even though it's complete. So, is there a command to make it start building at layer 1, or 2... ?

**Comment by FireSeth** [comment]
Use `#buildignoreexisting`

**Comment by dominikaaaa** [comment]
What lmao. That's not related

**Comment by FireSeth** [comment]
worked for me idk

**Comment by ZacSharp** [comment]
`#set startAtLayer` can now be used to do this.
