### ISSUE TITLE
.litematica not being recognized as a schematic file

### ISSUE THREAD

**Issue by Paandizz** [cabaletta/baritone#1769]
## Some information
Operating system: Windows 10 64-bit
Java version: 1.8.0_221
Minecraft version: 1.15.2
Baritone version:  1.5.3
Forge mods (if used):  N/a

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[2020-06-08-2.log.gz](https://github.com/cabaletta/baritone/files/4743184/2020-06-08-2.log.gz)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Attempt to build a schematic using a .litematic file
The issue is that the mod does not recognize .litematic as a schematic file
## Modified settings
N/A

- [x] I know how to properly use check boxes 
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [X ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
yes, because it doesn't end in .schematic

**Comment by Paandizz** [comment]
its still a schematic file, and making your own schematics is v hard without litematic

**Comment by dominikaaaa** [comment]
Then convert it to a `.schematic¢`.

Baritone only recognizes `.schematic`s

**Comment by Paandizz** [comment]
How do i convert it to .schematic?
