### ISSUE TITLE
Glass panes walking

### ISSUE THREAD

**Issue by Paandizz** [cabaletta/baritone#1770]
## Describe your suggestion
Allow Baritone to walk on glass/iron bars/fences to allow apple farms to work more efficiently.

## Final checklist
- [x] I know how to properly use check boxes 
- [X ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
I don't see how it would make baritone more efficient, and walking on non-full blocks is unreliable.

**Comment by Paandizz** [comment]
Allow for the setting atleast

**Comment by dominikaaaa** [comment]
It's too unreliable
