### ISSUE TITLE
AutoMine modded blocks.

### ISSUE THREAD

**Issue by gutoguto08** [cabaletta/baritone#1771]
## Is there a way to mine modded blocks?
I have tried to do 
#mine mod_name:block_ore 
but it doesn't work.

## Final checklist
- [x] I know how to properly use mine.
- [x] I have not and will not use any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Duplicate of something. Searching on mobile is hard

**Comment by gutoguto08** [comment]
That's not very helpful, just so you know i did try to search for it.

**Comment by dominikaaaa** [comment]
#1253 #1720 #1294
