### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1772]
## Describe your suggestion
just a small calculator that calculates exacly as in worldedit //calc 
so e.g. #calc 1*1

## Context
quick maths

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
could you describe what this does?

**Comment by UltraBlackLinux** [comment]
it calculates.

**Comment by dominikaaaa** [comment]
I don't see why this would be useful or related to Baritone imo.
