### ISSUE TITLE
Baritone not respecting the #sel limit

### ISSUE THREAD

**Issue by Ricael1** [cabaletta/baritone#1774]
I'm trying to farm wood in a server and i put a #sel 1 and #sel 2, so it makes a big square, but when i get to the edge of it, the bot just pass throuh it
## Final checklist
Minecraft 1.14.4
Baritone v1.4.6
Windows 10

**Comment by dominikaaaa** [comment]
Baritone is allowed to walk outside of selections, #sel is not a barrier.

**Comment by Ricael1** [comment]
I thought that it selected an area to work inside of... but ok, is there a feature that could help me?

**Comment by dominikaaaa** [comment]
I don't think so. Selections are used to replace / fill / build or whatever inside, it's not meant to be a barrier where baritone can and can't walk

**Comment by Ricael1** [comment]
Ok, thanks
