### ISSUE TITLE
How to make automatic bot more automatic?

### ISSUE THREAD

**Issue by Elnuir** [cabaletta/baritone#1775]
Hello, i've got a question about bariton. Shortly, I'm building pixel art, not too big, just 640x512 blocks. But, first is  I always getting kicked, a lot more often if you set rightclickspeed 1. Second, after each relog u have to .b build name x y z. A third he is often lose route so i have to walk a little to find a block bot wants to place. Server also have /shop where u can buy the most of blocks, exept of couple of craftable(colorful wool and clue blocks), but u can buy materials to craft them(white wool, dues, clue). So, is there anyway to make like full-full automatically? For he'd buy required blocks, make auto reconnect (ye this function exists already), type /sur to go to the survival server from lobby, automatically type coordinates? It'd be soo much helpful if i'd not have to babysit it during the building process. I know i'm asking for a lot, but probably i have to just set couple of settings and things'll go a lot more faster.
p.s. it'd be also helpful if someone would tell me is there any way to avoid kicks during max speed building? It say scaffold related hack, what, i guess, means i'm stacking up or build bridge. Here, on picture, i showed directions of build platform made of grass. Red dot - player, green lines - grass, green arrows - direction of building and black arrow - main direction, where player goes while building. Thus, If i use 1 way - he probably don't get kicked. If i use 2 way - his kick is question of time. Even on max speed

![Unt1313itled](https://user-images.githubusercontent.com/66650896/84095524-32628880-aa08-11ea-929b-a0cb109f34a8.png)

**Comment by dominikaaaa** [comment]
This isn't what baritone is designed for, write your own scripts to buy stuff from mini game shops. 

As for the other stuff, looking through the possible settings is helpful https://baritone.leijurv.com/baritone/api/Settings.html

**Comment by Elnuir** [comment]
> 
> 
> This isn't what baritone is designed for, write your own scripts to buy stuff from mini game shops.
> 
> As for the other stuff, looking through the possible settings is helpful https://baritone.leijurv.com/baritone/api/Settings.html


 thank you so much
