### ISSUE TITLE
Baritone Keeps going back and forth

### ISSUE THREAD

**Issue by TastefullBricodes** [cabaletta/baritone#1779]
## Some information
Operating system: Windows 10
Java version: 11.0.7
Minecraft version: 1.12.2
Baritone version: 1.5.3
Forge mods (if used):  none

## Exception, error or logs
I was trying to build an obsidian redeemer with baritone with build in layers on but when it reach to layer 8 it just stops and goes to a random location away from the build site and just stays there with no reason and just keeps path find somewhere that is not even related

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheK0tYaRa** [comment]
You can't install 1.5.* versions of baritone on minecraft 1.12.2.

**Comment by dominikaaaa** [comment]
Yea ngl I'm wondering how that happened. Reopen this issue with the proper information please.
