### ISSUE TITLE
Legit Mine gives up, and can't mine.

### ISSUE THREAD

**Issue by wasdwasdwasdwas** [cabaletta/baritone#1782]
## What do you need help with?

Whenever I try to use Legit Mine, it gives up after a few seconds, and gives me this:

Unable to find any path to BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]}, cancelling mine.

There's videos out there that all show this working perfectly fine, but whenever I try to use legit mine, it just stops and gives up after wandering around.

I haven't changed any settings
![image](https://user-images.githubusercontent.com/66849006/84545482-361a3780-acb4-11ea-96d0-3f65557f0320.png)

Video:
https://drive.google.com/file/d/1dmgBhq98J5kaeHQB0EjCOCZElm77Kl4b/view?usp=sharing

I've tried this many times but the same thing happens every time.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Try not using creative

**Comment by DeadLord1337** [comment]
creative off = success ))

**Comment by dominikaaaa** [comment]
Oh I thought you were the original issue creator. Either way, I can't reproduce this issue, legit mine works just fine for me. @wasdwasdwasdwas if you can still reproduce this in survival please reopen the issue.
