### ISSUE TITLE
Can you add #sel copy and #sel paste?

### ISSUE THREAD

**Issue by jonfinnelizaga** [cabaletta/baritone#1785]
## Describe your suggestion would it be nice to copy someone's or you own build my auto building it
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings#selmcopy and #sel paste
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Contextit will be an interesting feature in baritone
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist[]
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by jonfinnelizaga** [comment]
Sry its #sel copy and #sel paste

**Comment by Dazzle20XX** [comment]
I'd like this. Maybe also save it as schematic.
