### ISSUE TITLE
Path makes you fall with backfill when hugging a wall

### ISSUE THREAD

**Issue by Dafeader** [cabaletta/baritone#1788]
## Some information
Operating system:Windows but same issue on linux
Java version:1.8.0_51 64bit
Minecraft version:1.12.2
Baritone version: (Null version ??, i'm on latest kami blue client)
Forge mods (if used): kami blue

## How to reproduce
after enabling backfill, make baritone have to hug a block after he broke a block, baritone will try to put the block back before being safe and will fall off, 
it's easier to understand in video so here it is: https://streamable.com/ghtius
## Modified settings
backfill set to true

**Comment by ZacSharp** [comment]
Why did you close this?

**Comment by dominikaaaa** [comment]
Nobody closed this?

**Comment by ZacSharp** [comment]
Wut? I swear I saw it cosed
Or maybe I saw the added bug label message and had something with my eyes???
Confused, Sorry for that

**Comment by dominikaaaa** [comment]
Bruh moment

**Comment by ZacSharp** [comment]
Anyways
I found the cause and a fix
I'll do the pull request soon
