### ISSUE TITLE
Help downloading

### ISSUE THREAD

**Issue by willyreh** [cabaletta/baritone#1789]
I get this error when I try to download Baritone 1.15.2 using the json file

Failed to download file.
Name: 1.15.2.jar
URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
Error details: The requested URL returned error: 403 Forbidden
Filename on disk: 1.15.2.jar
Path: /Users/willy/Library/Application Support/minecraft/versions/1.15.2/1.15.2.jar
Exists: Nonexistent

**Comment by dominikaaaa** [comment]
That means your ISP / firewall is blocking it or you forgot to run normal 1.15.2 Minecraft beforehand, or your json file isn't configured properly.
