### ISSUE TITLE
Baritone Instincts 

### ISSUE THREAD

**Issue by AverWasTaken** [cabaletta/baritone#1790]
## Describe your suggestion
Basically if baritone failed a jump, make it MLG water or MLG block. Therefore not dying or taking fall damage. Also if it was hit by a mob make it calculate if it has enough health to fight said mob. If it does, turn around and kill it, if not run.

## Settings
doReflexes true/false
addMlgBlockBlacklist minecraft:stone

## Context
This would improve baritone by giving it another way to actively avoid damage and get things done more effectively. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Baritone can already mlg water bucket, and using blocks to mlg is already suggested. 

Also, Baritone isn't meant to fight mobs, but there are other issues created to allow Baritone to fight, but for now just use a client which already has that built in (eg Impact or KAMI Blue)
