### ISSUE TITLE
Smooth Cursor Movement

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1795]
## Describe your suggestion

So this just makes baritones cursor movements smoother, to prevent a jumping cursor and make it less obvious to others.
## Settings

#smoothcursor boolean or #sc boolean
#smoothcursorspeed float or #scs föoat

## Context
I thought about this cause baritones cursor movement is quite ugly and in a few cases not anticheat compatible...

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#1048, #414
