### ISSUE TITLE
Zeroday interesting baritone bot integration

### ISSUE THREAD

**Issue by SuperGamingBros4** [cabaletta/baritone#1797]
## What do you need help with?
The hacked client Zeroday, found on intent.store has a baritone integration and it's own bot system I was wondering if anyone can break down the code and make a client with the bots from the Zeroday client that can be controlled in the same way with killaura etc...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Zeroday unironically took baritone and just added KillAura from https://github.com/MintyCodesYT/TutorialClient1.8.8/ :clown_face:

**Comment by dominikaaaa** [comment]
Both Impact and KAMI Blue have killaura integration for Baritone

**Comment by SuperGamingBros4** [comment]
I mean it has it's own bot-system with the bots having killaura with them and more thing like jesus.
in this video, youtube.com/watch?v=rB2Wdb8_k1c the creator of Zeroday shows him using bots to get everything he needs in minutes.

**Comment by dominikaaaa** [comment]
It's literally just a client with baritone integration. Just like impact and kami blue have those exact same features.

**Comment by SuperGamingBros4** [comment]
what i'm talking about is zeroday has this thing called zerobot which allows you to use alts as bots with baritone to perform tasks for you

**Comment by dominikaaaa** [comment]
And?

**Comment by dominikaaaa** [comment]
It's not like they rebranded baritone and tried to claim that they created it or anything

https://github.com/cabaletta/baritone/tree/bot-system

**Comment by SuperGamingBros4** [comment]
is there someway to give the bots in bot-system killaura?

**Comment by dominikaaaa** [comment]
No, but killaura is literally 50 lines of code.

**Comment by SuperGamingBros4** [comment]
oh I'll look into integrating killaura and other modules.
