### ISSUE TITLE
Update setup.md / How can I replace impact nightly's baritone for MultiMC?

### ISSUE THREAD

**Issue by aria1th** [cabaletta/baritone#1802]
Setup.md is currently focused on previous version. It's outdated. 
I build baritone in one branch by gradlew, but I cannot replace it because its json format is different. When I erases 'url', entire json load will fail, even if I corrected sha1 hash and file size. If I leave url, then it will fail because impact still attempts to download baritone-api 1.5.3.jar from github release. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
Why not trying to change the url lol

**Comment by UltraBlackLinux** [comment]
I also made a tool for that look at my repos

**Comment by scorbett123** [comment]
Setup.md has been updated and this isn't the repo for asking how to update the impact nightly version.
