### ISSUE TITLE
Unmodded Client/Baritone Hide

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1812]
## Describe your suggestion
This sends Servers that the Baritone client is an Unmodded/Forged Client

## Settings
#hide

## Context
This makes the Baritone client less suspicious since its not Modded

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
I don't see how this would improve Baritone. You don't have to use the forge mod if you don't want the client to report the fact that you're running forge. Baritone already doesn't report itself to the server as a forge mod.

**Comment by UltraBlackLinux** [comment]
I know It doesnt, but servers can detect Forge I think. Also, my minecraft client itself tells me that my client is modded if I do stuff wit th the jsons, It wouldnt surprise me, if even this gets sent to the server.

**Comment by dominikaaaa** [comment]
Only the stuff you can see in the top of the f3 menu is sent to the server. If both the client and server are forge, the server can see the loaded forge mods in the client, but Baritone doesn't report that it's a forge mod

**Comment by UltraBlackLinux** [comment]
Yeah ok, true :)
