### ISSUE TITLE
minecraft crashes when i open it with baritone

### ISSUE THREAD

**Issue by GoogledMusic** [cabaletta/baritone#1814]
## Some information
Operating system: Windows 10
Java version: 8 update 251 build 1.8.0_251-b08
Minecraft version: 1.15.2
Baritone version:
Forge mods (if used): 

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/4810127/latest.log)

## How to reproduce
Add your
 steps to reproduce the issue/bug experienced here.
open minecraft
open the configuration for 1.15.2-baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Please provide the log of when it crashes. You posted an empty log.

**Comment by GoogledMusic** [comment]
[2020-06-21-1.log.gz](https://github.com/cabaletta/baritone/files/4810199/2020-06-21-1.log.gz)

**Comment by dominikaaaa** [comment]
That's also empty. Are you *sure* you're using *Oracle* JDK and the official Minecraft launcher?

**Comment by GoogledMusic** [comment]
i am using the minecraft launcher for sure, the reason why its empty is because when i open minecraft it just closes right away to this screen https://owo.oooooooooooooo.ooo/i/ihgv.png i'm not sure what oracle jdk is so if you send me a download link i will try that

**Comment by dominikaaaa** [comment]
https://docs.oracle.com/javase/8/docs/api/java/

**Comment by GoogledMusic** [comment]
i am using oracle jdk i just checked

**Comment by dominikaaaa** [comment]
Try restarting your computer? I'm not sure why that would be happening

**Comment by GoogledMusic** [comment]
this happened along time ago and it is still occurring i have never been on a working baritone 1.15.2 but it works on other versions i just decided to report it today

**Comment by dominikaaaa** [comment]
Make sure you've launched normal Minecraft 1.15 beforehand

**Comment by GoogledMusic** [comment]
Just tried launching 1.15 before launching baritone doesn't work also did the same with 1.15.2

**Comment by GoogledMusic** [comment]
if you need me to screen share on discord i do not mind

**Comment by dominikaaaa** [comment]
I have no idea what's the issue here, that wouldn't help

**Comment by dominikaaaa** [comment]
I have no idea what's the issue here, that wouldn't help

**Comment by GoogledMusic** [comment]
hmm the issue is that when i launch minecraft baritone it crashes right away

here is a video: https://streamable.com/fv75kb

**Comment by dominikaaaa** [comment]
To clarify, I have no idea what is causing it.

**Comment by GoogledMusic** [comment]
same here, the crash log provides nothing useful

**Comment by GoogledMusic** [comment]
i had an idea on running forge with baritone but im not sure how to install it

**Comment by dominikaaaa** [comment]
Drag this [file](https://github.com/cabaletta/baritone/releases/download/v1.5.3/baritone-standalone-forge-1.5.3.jar) into your forge 1.15.2 *31.1.0* mods folder

**Comment by UltraBlackLinux** [comment]
If you want a launcher it surely works with: multimc. The discord helps you very quickly too

**Comment by GoogledMusic** [comment]
i found an alternative fix and can be a possible fix for anyone else in the future; it was to use the forge version instead of the normal.

**Comment by UltraBlackLinux** [comment]
Dont mind me @dominikaaaa pls
hey, @GoogledMusic could you gimme access to this cool webpage: https://elixi.re/ Id love to have a place to host my files without google being involved. But I need sb to referr me xD
Id love that.
