### ISSUE TITLE
Auto mining does not avoid mining floating gravels

### ISSUE THREAD

**Issue by KevinMei-Github** [cabaletta/baritone#1819]
Operating system: Windows 10
Java version: 8u251
Minecraft version: 1.15.2
Baritone version: 1.5.3
Issue: The auto-mining AI does not avoid mining floating gravels or sands, and I fell into lava last time...
[latest.log](https://github.com/cabaletta/baritone/files/4817610/latest.log)

**Comment by dominikaaaa** [comment]
#avoidUpdatingFallingBlocks
