### ISSUE TITLE
Baritone should automatically get blocks.

### ISSUE THREAD

**Issue by Wyatt-Stanke** [cabaletta/baritone#1822]
Baritone should be able to get blocks when creating something in creative mode. I'm sick of having to take everything out myself, and sometimes all the blocks can't fit in my inv. It also could alternate between blocks by getting them out, and then destroying them. This suggestion has been said before, but nothing has happened.

**Comment by dominikaaaa** [comment]
\> be me
\> check notifications
\> @Wyatt-Stanke created a new issue
\> mfw they didn't search 

![maim-2020-06-24-17-54-20](https://user-images.githubusercontent.com/17222512/85631544-bf7e2200-b643-11ea-9c69-2fe83c8d594d.png)
