### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by KiwiFruit555** [cabaletta/baritone#1826]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

Make a 1.8.9 Version of baritone

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

More versions available

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

Improve Compatibility, and ultimately increase users

## Final checklist
- [✔️] I know how to properly use check boxes 
- [✔️] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
> and ultimately increase users

yea right, for the whole 5 non PVP 1.8.9 players that exist

**Comment by dominikaaaa** [comment]
https://github.com/michaelzangl/minebot
