### ISSUE TITLE
Building Baritone with 8u25 on Windows

### ISSUE THREAD

**Issue by chrishaxalot** [cabaletta/baritone#1827]
I have been using Bartione for some months now and wanted to understand more how it works. I study computer science and we are doing Java most of the times, so i thought i know how this should works but im unable to build.

I try to work on the 1.15.2 branch but the setup.md workflow for building relies on folders and files that doesnt seem to be there. Even if i search the whole project, i dont find "setupDecompWorkspace", "genIntellijRuns".

Also Intelij shows some errors in the build.gradle file.

![grafik](https://user-images.githubusercontent.com/45143330/85944621-74f8f000-b938-11ea-989a-cf92e1d783a9.png)

Im using jdk 8u25, should i use another jdk? Or can someone suggest a solution?

I have been programming in java for some years but never tried to build such a complex project. If i manage to build (and understand some stuff) i would like to try to commit something.

Chris

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
you need to setupdecompworkspace

**Comment by chrishaxalot** [comment]
I'm sorry to reopen. Getting closer: Im able to build baritone-api-1.5.3.jar, baritone-standalone-1.5.3.jar and baritone-unoptimized-1.5.3.jar. Also gradle runClient works. Now, how can i build the missing forge files?

Just for my understanding:  setupdecompworkspace actually works, but it stills ends with "Task 'setupdecompworkspace' not found in root project 'baritone'". Is this my fault?

**Comment by dominikaaaa** [comment]
Uhhh that means it didn't work. Try reimporting and restarting intellij

**Comment by chrishaxalot** [comment]
Sadly the error is still there. After i import the gradle project for the first time, im supposed to execute setupdecompworkspace, but it isnt there.
![grafik](https://user-images.githubusercontent.com/45143330/86047827-cf38a480-ba4f-11ea-9b5b-2cea5c1ba37a.png)

Even a search for "setupdecompworkspace" in the baritone folder doesnt show anything

Again, i work on https://github.com/cabaletta/baritone/releases/tag/v1.5.3. Everything accept forge works.

I really appreciate your help and hope i get to build my forge .jars =)

**Comment by chrishaxalot** [comment]
I forgot: building accept forge works, but the "Minecraft Client" application configuration is missing also.

**Comment by dominikaaaa** [comment]
The application configuration is created automatically after genIntellijRuns and a reimport

**Comment by dominikaaaa** [comment]
> For both Intellij IDEA and Eclipse their Gradle integration will handle the rest of the initial workspace setup, this includes downloading packages from Mojang, MinecraftForge, and a few other software sharing sites. * For most, if not all, changes to the build.gradle file to take effect Gradle will need to be invoked to re-evaluate the project, this can be done through Refresh buttons in the Gradle panels of both the previously mentioned IDEs.

from forge wiki

Try importing the build.gradle, not the folder, when making a new project

**Comment by chrishaxalot** [comment]
I tried the whole process again. Import build.gradle as project:
![grafik](https://user-images.githubusercontent.com/45143330/86049946-5b000000-ba53-11ea-8041-7ef81dddf71b.png)

![grafik](https://user-images.githubusercontent.com/45143330/86049976-66532b80-ba53-11ea-8984-7b06bfe4f23d.png)

![grafik](https://user-images.githubusercontent.com/45143330/86050014-766b0b00-ba53-11ea-9bd7-02b391e4cce2.png)

no setupdecompworkspace:
![grafik](https://user-images.githubusercontent.com/45143330/86050161-aa463080-ba53-11ea-9467-bb48605e6421.png)

If i try setupdecompworkspace:
![grafik](https://user-images.githubusercontent.com/45143330/86050285-ee393580-ba53-11ea-918c-7fb2756c310b.png)

nevertheless, runClient works. Naive question: is forge in https://github.com/cabaletta/baritone/releases/tag/v1.5.3 really integreated?

**Comment by dominikaaaa** [comment]
I have no idea then

**Comment by CDAGaming** [comment]
Ok so CCing @dominikaaaa and @chrishaxalot to close this

In ForgeGradle 3 (Used in Forge 1.13+ and using a modified version of this for Baritone 1.13+), setupDecompWorkspace is not in any case used anymore, as it's performed automatically during a refresh/resync.

The original errors were likely due to it not being fully imported, so that mostly needed a refresh.
If the docs are still referencing setupDecompWorkspace, then those need updating for 1.13+

**Comment by dominikaaaa** [comment]
Oh I see. Thank you for explaining :3
