### ISSUE TITLE
Auto mine for ancient debris on 1.16

### ISSUE THREAD

**Issue by yodaluca** [cabaletta/baritone#1829]
[I mentioned this here too.](https://github.com/ImpactDevelopment/ImpactIssues/issues/2474)

When it updates to 1.16 can you add auto mine for ancient debris I mean it’s pretty self-explanatory it would be a bot mode option under auto mine section and you just choose ancient debris.

**Comment by RinAndShizuka** [comment]
Given that Baritone has the ability to mine for any block, you would assume that the ancient debris will also be added, wouldn't you?

**Comment by yodaluca** [comment]
Ok yay 😁

**Comment by dominikaaaa** [comment]
I think they meant an option in the AutoMine menu, like beside diamonds.

**Comment by dominikaaaa** [comment]
This shouldn't be in the baritone repo, baritone automatically supports any block, it's not manually hardcoded what works and what doesn't.
