### ISSUE TITLE
Technically it shouldn't need to sneak while backplacing / bridging

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#183]
Right now it does that just to guarantee it won't fall off but it isn't strictly necessary actually.

**Comment by Thunder33345** [comment]
could be on for sake on legit servers who otherwise dont like it

**Comment by ThatGrzegorzB** [comment]
you could make it sneak when players centre is above air and then rotate backwards attempt to place next tick, and unshift if the place is successful and rotate again it would reduce the amt of sneak time by a lot, look legit and be more reliable than god-bridging

**Comment by leijurv** [comment]
yeah we do epic gamer stuff now, added in https://github.com/cabaletta/baritone/commit/863ae447b9d36fb272d303c7e5babd2c361b8f49 it sprints then sneaks for the last 0.1 blocks
