### ISSUE TITLE
Goto and wp command on neither to travel to the overworld 

### ISSUE THREAD

**Issue by jonfinnelizaga** [cabaletta/baritone#1831]
## Describe your suggestion add feature on the #goto command that you can use to on the neither to travel on the overworld and same with the #wp you can use the overworld waypoint in the nether
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.#goto x y z overworld and #wp

## Context it will improve the nether travel
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Duplicate
