### ISSUE TITLE
Feature request: auto-mine giant tree

### ISSUE THREAD

**Issue by Artoria2e5** [cabaletta/baritone#1836]
## Describe your suggestion
Baritone's mine bot is currently able to hunt down logs, but the logic used is very unsuited to giant trees. In particular, baritone likes to cut down the reachable "base" of the tree first, and then handle the rest. The problem with that is baritone now needs to place blocks to get up there, and that is too much of a cost for tree farming.

It would be nice if baritone could somehow replicate the way human players deal with these trees, either by a top-down method or a spiral-up-then-down method. This will require changes to the how mine bot prioritizes targets, in that doing either requires the cutting to be done in a certain order while recognizing that breaking the block we want to break is essentially cost-free.

## Settings
A boolean switch may be needed while the new logic is being tested.

## Context
Giant trees are cool to farm. They are the only sustainable option for jungle trees in terms of sapling return. And giant spruce gives podzol and makes natural sky needles.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

(Hey, what's the anime exception in the license?)

**Comment by Artoria2e5** [comment]
Duplicate of #1659. Sometimes people prefer 2x2 to "giant" I guess.

**Comment by rahulcvwebsitehosting** [comment]
Fixed this in my fork — https://github.com/rahulcvwebsitehosting/baritone. Not PR'd upstream yet but it works if you need it now. Lmk if anything's off.
