### ISSUE TITLE
Mining "short memory"

### ISSUE THREAD

**Issue by wiktuur** [cabaletta/baritone#1841]
Often when mining on 1.16.1 version, the bot just forgets about what he was doing and goes to the next vein, absolutely forgetting about it. Also, often it goes into a hole to pick up an item and doesn't pick it up... But that may be "server lag"... I was mining coal and lapis (@mine coal_ore lapis_ore) and got to a vein of both, but the bot broke 1-3 ores and went on it's way onward

**Comment by StijnSimons** [comment]
This isn't fabritone.

**Comment by wiktuur** [comment]
Ok, if yo say so... I downloaded it from here so I thought that it was good place, but ok, going to fabritone git.

**Comment by StijnSimons** [comment]
> Ok, if yo say so... I downloaded it from here so I thought that it was good place, but ok, going to fabritone git.

No way you did download it from here; there's no 1.16.1 version yet.

**Comment by dominikaaaa** [comment]
how tf did you download it from here ♿
