### ISSUE TITLE
How to disable breaking blocks that do not obstruct path

### ISSUE THREAD

**Issue by Bluscream** [cabaletta/baritone#1842]
## What do you need help with?
I have tried setting `blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,torch` to include torches for example, and yet everytime i set `allowBreak true` baritone annihalates every torch in it's 2 block path

## Modified settings
```
allowBreak true
allowDownward false
blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,torch
avoidance true
containerMemory true
autoTool false
chatControlAnyway true
renderPathAsLine true
renderGoalXZBeacon true
antiCheatCompatibility false
renderCachedChunks true
prefix #
shortBaritonePrefix true
walkWhileBreaking false
```

## Final checklist
- [x] I know how to properly use check boxes 
- [UwU] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
blocksToAvoidBreaking

**Comment by Bluscream** [comment]
@dominikaaaa 🤔 

![image](https://user-images.githubusercontent.com/3318223/86438515-02588d80-bd07-11ea-98b5-f1a0aa0704c2.png)

**Comment by dominikaaaa** [comment]
this is baritone, not fabritone.

**Comment by Choder7** [comment]
set blocksToDisallowBreaking torch,wall_torch,soul_torch,soul_wall_torch
