### ISSUE TITLE
So my baritone follow command doesn't work and i've tried all the tip/tricks to make it work

### ISSUE THREAD

**Issue by Donkeyinthellamas** [cabaletta/baritone#1844]
## Some information
Operating system: mac
Java version: idk
Minecraft version: 1.15.2
fabritone version: 1.5.2
Forge mods (if used): none

## Exception, error or logs
not the issue

## How to reproduce
I just used @ follow entity pig
## Modified settings
To get the modified settings run `#modified` in game
<img width="2048" alt="Screen Shot 2020-07-02 at 9 14 19 PM" src="https://user-images.githubusercontent.com/67778088/86441226-baaf1300-bcc0-11ea-93d7-c7457a0cbad6.png">
<img width="2048" alt="Screen Shot 2020-07-02 at 9 14 19 PM" src="https://user-images.githubusercontent.com/67778088/86441256-c7cc0200-bcc0-11ea-9ef5-5c455737f665.png">

so my fabritone follow command wont work, it highlights the things I'm supposed to follow but it just wont follow them.

**Comment by dominikaaaa** [comment]
this is baritone

**Comment by Donkeyinthellamas** [comment]
yes this is baritone and im confused why that matters

**Comment by Donkeyinthellamas** [comment]
I just need to know why it wont follow them

**Comment by dominikaaaa** [comment]
it matters because you're asking for help with not baritone

**Comment by Donkeyinthellamas** [comment]
wait what
I don't follow

**Comment by Donkeyinthellamas** [comment]
I just really need to know why it wont follow them

**Comment by Donkeyinthellamas** [comment]
and i do i fix the invalid thing

**Comment by dominikaaaa** [comment]
Try asking for help in Fabritones repo
