### ISSUE TITLE
How do i use the jar files after building?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [cabaletta/baritone#1848]
## What do you need help with?
After building baritone you get an assortment of jar files. I have no idea how to use them as i am stupid. Can someone pls tell me how

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheCrazyInsanity** [comment]
For a bit more info im using the bot system version of baritone. The one that uses multiple accounts in one client

**Comment by dominikaaaa** [comment]
You take the jar file and install it for whichever platform you're using

**Comment by dominikaaaa** [comment]
ie if it's a forge standalone file, you just move that to the mods folder

**Comment by TheCrazyInsanity** [comment]
> ie if it's a forge standalone file, you just move that to the mods folder

I tried that and it is not loading into forge when i do that.

**Comment by dominikaaaa** [comment]
Make sure you use the release jar

**Comment by TheCrazyInsanity** [comment]
> Make sure you use the release jar

I am specifically asking about the jar files i build myself. Not the release ones. Please read.

**Comment by dominikaaaa** [comment]
The build creates release jars and non release jars.

**Comment by TheCrazyInsanity** [comment]
> The build creates release jars and non release jars.

Where do i find the release ones then?

**Comment by dominikaaaa** [comment]
Inside the same folder

**Comment by TheCrazyInsanity** [comment]
> Inside the same folder

Well i tried every single one of them as a custom version and as forge and none of them worked

**Comment by dominikaaaa** [comment]
It works just fine for everyone else, otherwise the GitHub releases wouldn't exist

**Comment by TheCrazyInsanity** [comment]
> It works just fine for everyone else, otherwise the GitHub releases wouldn't exist

Yeah but there is obviously a problem here. Saying it works for everyone else isnt helping to solve the problem

**Comment by UltraBlackLinux** [comment]
Screenshot of the files?

**Comment by TheCrazyInsanity** [comment]
> Screenshot of the files?
> Have you tried using the files that are named like the releases? why even build yourself if you want to use the releases bruh

I dont want to use the releases. I am building the bot branch of baritone. That version has no compiled binaries. And none of them will actually run in minecraft. Well here is the screenshot
![Untitled](https://user-images.githubusercontent.com/39921530/87162549-1450a800-c294-11ea-80d5-2f47f1ebd3c4.png)

**Comment by dominikaaaa** [comment]
it works just fine for everyone else ngl

**Comment by TheCrazyInsanity** [comment]
> it works just fine for everyone else ngl

You already said that. And im using bot system branch not normal branch
https://github.com/cabaletta/baritone/tree/bot-system
I am asking help specifically for this branch

**Comment by dominikaaaa** [comment]
And you are not getting help for bot-system, as stated numerous times.

**Comment by TheCrazyInsanity** [comment]
I figured it out. Had to build through command prompt and not intellij for some unknown reason. And you dont use chat prefix

**Comment by TheCrazyInsanity** [comment]
Aaaaand it wont run a second time.
