### ISSUE TITLE
Add CARVED_PUMPKIN on #farm command

### ISSUE THREAD

**Issue by ralphchristianeclipse** [cabaletta/baritone#1849]
CARVED_PUMPKIN is not farmed by #farm command

**Comment by dominikaaaa** [comment]
Yes, because carved pumpkins can't be farmed in Minecraft, only normal pumpkins can.

**Comment by ralphchristianeclipse** [comment]
@dominikaaaa but can we add that as an option?

**Comment by dominikaaaa** [comment]
`#mine carved_pumpkin` 

Carved pumpkins don't grow naturally, they only have a chance to be generated once. Only normal pumpkins can be farmed
