### ISSUE TITLE
Crash at startup, 1.12.2.

### ISSUE THREAD

**Issue by TheButterbrotMan** [cabaletta/baritone#1850]
## Some information
Operating system: Windows 10 Pro 1909
Java version: Version 8 Update 251
Minecraft version: 1.12.2 (Forge 14.23.5.2847)
Baritone version: v1.2.14
Forge mods (if used): [MC.Eternal Lite Modpack 1 .3.5](https://www.curseforge.com/minecraft/modpacks/mc-eternal-lite)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log.txt](https://github.com/cabaletta/baritone/files/4873022/latest.log.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Download the MC.Eternal Lite Modpack, install it (MultiMC). 
Add Baritone-Standalone-Forge.
Game will crash at startup.

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Uninstall mc eternal lite

**Comment by TheButterbrotMan** [comment]
No way to use them together?

**Comment by dominikaaaa** [comment]
no
