### ISSUE TITLE
Fully connected Minecraft accounts that run off of the same AI

### ISSUE THREAD

**Issue by yodaluca** [cabaletta/baritone#1851]
Ok Ik your going to say this is a duplicate of [This one](https://github.com/cabaletta/baritone/issues/1832) but I’m saying something different more like all the Minecraft accounts are connected and the AI can like call for back up for one account or what not and have a pvp mode where they can all go for one player in synchronize patterns or build mode where are you put in a schematic and they automatically all work together to build it automatically.

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/tree/bot-system

**Comment by yodaluca** [comment]
Huh?

**Comment by yodaluca** [comment]
Mega Confusion please reply??!!!

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/tree/bot-system

**Comment by dominikaaaa** [comment]
reply

**Comment by GunnerBasil** [comment]
@dominikaaaa I understand that it's different from baritone, but i think they're just confused as to how to use it differently.

**Comment by dominikaaaa** [comment]
it's not different from baritone?? it's literally baritone lmao

**Comment by GunnerBasil** [comment]
then whats the difference?

**Comment by dominikaaaa** [comment]
that's the bot system branch

**Comment by GunnerBasil** [comment]
yeah, but it doesn't have any documentation different from the master branch.

**Comment by dominikaaaa** [comment]
no, it does not have documentation.

**Comment by GunnerBasil** [comment]
yeah, i think they want to know how to use it.

**Comment by dominikaaaa** [comment]
¯\\\_(ツ)_/¯

read the code idk

**Comment by GunnerBasil** [comment]
yeah, but im not sure what's different.

**Comment by dominikaaaa** [comment]
I mean, it's in the name

https://youtu.be/pKhNzYiXyQ8

**Comment by GunnerBasil** [comment]
how would I use multiple accounts? i just built it through the command line like you would build normal baritone, and I'm going to try launching it with forge.

**Comment by dominikaaaa** [comment]
Check the commands, idk

**Comment by dominikaaaa** [comment]
The bot system brain is officially unsupported

**Comment by GunnerBasil** [comment]
yeah, i just want to know how to use it through 1 forge client :P

**Comment by dominikaaaa** [comment]
I'd assume the normal way you use baritone

**Comment by GunnerBasil** [comment]
i laucnhed forge 1.12.2 with the forge standalone, but the # commands dont work

**Comment by GunnerBasil** [comment]
but this is for multiple accounts controlled by one person, right?

**Comment by dominikaaaa** [comment]
Yes. If those commands don't work, then you used the wrong jar. As I said, it's unsupported

**Comment by GunnerBasil** [comment]
oh ok. could I contact the dev?

**Comment by dominikaaaa** [comment]
You can ask for help in the impact discord, but it is unsupported. Nobody will help you with this

**Comment by GunnerBasil** [comment]
ok ¯\\\_(ツ)_/¯

**Comment by ZacSharp** [comment]
prefix commands are only sent to the bots, so they don't work without bots
chat commands (no prefix) ore only for yourself, so use them to spawn bots

also be careful with "#bot" (with prefix), because it will execute once for each existing bot, effectively doubling your bots

**Comment by GunnerBasil** [comment]
What do you mean to spawn bots? I tried saying both "mine dirt" and "#mine dirt" in the chat, and i had the world open to LAN, but nothing happened. The branch isn't finished though, so might not be a thing :P

**Comment by ZacSharp** [comment]
there is a "bot" command that creates a fake player with its own baritone instance

**Comment by ZacSharp** [comment]
I don't know how to use real players as bots (or if it is possible at all)

**Comment by ZacSharp** [comment]
Wait, nothing happened with "mine dirt"?
That means baritone does not work.

**Comment by GunnerBasil** [comment]
so what command is it? I just want to get this on a LAN world, so real players aren't necessary. Do you know what the command is?

**Comment by ZacSharp** [comment]
"#bot"
for the first bot you **have** to omit the prefix and later you will need to omit the prefix to spawn only a single bot

**Comment by GunnerBasil** [comment]
doesn't work. can you send me like a video or something if it working for you?

**Comment by GunnerBasil** [comment]
hm. I typed in #bot and bot, but nothing happened.

**Comment by yodaluca** [comment]
[Yes this is exactly what I meant how do I do this￼](https://github.com/cabaletta/baritone/issues/1851#issuecomment-654930535)

**Comment by yodaluca** [comment]
> I mean, it's in the name
> 
> 
> 
> https://youtu.be/pKhNzYiXyQ8

Yes this is exactly what I meant please tell me how I do this￼

**Comment by GunnerBasil** [comment]
I'd love to get this working too.

**Comment by yodaluca** [comment]
Can someone at least reopen this??????

**Comment by GunnerBasil** [comment]
no. its an unsupported branch and i dont think its finished.

**Comment by yodaluca** [comment]
Umm ok not exactly sure what that means but do you know of any mod that can come do this￼￼

**Comment by GunnerBasil** [comment]
no. you could use like OQ.Minebot or something, or make your own fork.

**Comment by dominikaaaa** [comment]
> Can someone at least reopen this??????
Do none of you understand the word unsupported?

![Screenshot_20200717_192341](https://user-images.githubusercontent.com/17222512/87837867-12be4b80-c863-11ea-8b21-0a16aba862f7.png)
![Screenshot_20200717_192424](https://user-images.githubusercontent.com/17222512/87837880-22d62b00-c863-11ea-9c63-98af504fe82e.png)

**Comment by yodaluca** [comment]
Ok I try

**Comment by GunnerBasil** [comment]
OQ.Minebot is paid tho.

**Comment by ZacSharp** [comment]
> doesn't work. can you send me like a video or something if it's working for you?

No, github doesn't let me drag-and-drop files into my comments ("Something went really wrong, and we can't process that file.")
I'll maybe (very likely) try to work around this soon.
I only tried to run it in the dev end with `gradlew runClient` not with a built mod / standalone. I'll try that soon.

**Comment by ZacSharp** [comment]
Just in case you are still interested in it: ![gif](https://raw.githubusercontent.com/ZacSharp/uploads/master/cabaletta/baritone/issues/1851/working_bot-system.gif)

**Comment by GunnerBasil** [comment]
is that the one in the branch? sorry for necropost :/

**Comment by ZacSharp** [comment]
What do you mean with "the one in the branch"?

**Comment by GunnerBasil** [comment]
like the branch of baritone that was made for multiaccount bot support.

**Comment by ZacSharp** [comment]
this was done by downloading the bot-system branch and running it as-is with `./gradlew runClient`. the rest is in the video.
I don' think you can use multiple accounts with bot-system and I never tried it on a server.
The bots in the video all belong to one Minecraft instace and there is no account related to them (or the player cuz dev-env).
Still don't know what you mean but trying to answer.

**Comment by GunnerBasil** [comment]
yeah, i was asking whether this was the bot system branch or not. thanks!

**Comment by yodaluca23** [comment]
Bot system branch had commits 11 months ago…

Does anyone know how to set this up and get this working? tutorial?

**Comment by pizzav-xyz** [comment]
is this like run multiple accounts in one instance?

**Comment by yodaluca23** [comment]
> is this like run multiple accounts in one instance?
> 
> 

Kind of??


Looks like meteorclient has a similar feature using baritone https://meteorclient.com/faq/swarm/

**Comment by pizzav-xyz** [comment]
> > is this like run multiple accounts in one instance?
> 
> Kind of??
> 
> Looks like meteorclient has a similar feature using baritone https://meteorclient.com/faq/swarm/

no thats just that you can command them with 1 instance you still need 1 instance per account

**Comment by ZacSharp** [comment]
> Does anyone know how to set this up and get this working? tutorial?

No there is no tutorial. The bot-system branch is an experimental branch and as far as I know it doesn't even work with real accounts.
