### ISSUE TITLE
blockBreakAdditionalPenalty to grass = 0

### ISSUE THREAD

**Issue by Mankita-chan** [cabaletta/baritone#1853]
## What do you need help with?
How do i change the block break penalty of a single kind of block?

## Final checklist
- [x] I so f*cking done of dodging grass when pathing
- [nope] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
I'm pretty sure you can't do that, best make a suggestion

**Comment by Mankita-chan** [comment]
> I'm pretty sure you can't do that, best make a suggestion

But, fire has the 0 penalty; i gues there is a file that contains the "ignore firewall" rule and i can modify that to include the grass?

**Comment by dominikaaaa** [comment]
I have no idea where that is in baritone's code, you'd probably need to modify that yourself.

**Comment by ZacSharp** [comment]
No, fire has a breaking cost of 0, but the blockBreakAdditionalPenalty is the same for **all** blocks.
This means that it will slightly prefer paths that do not require any block to be broken.

This is from api/java/baritone/api/Settings.java
```
    /**
     * This is just a tiebreaker to make it less likely to break blocks if it can avoid it.
     * For example, fire has a break cost of 0, this makes it nonzero, so all else being equal
     * it will take an otherwise equivalent route that doesn't require it to put out fire.
     */
    public final Setting<Double> blockBreakAdditionalPenalty = new Setting<>(2D);

```

**Comment by thecakeisalie25** [comment]
Also, what situation would it need to break grass? Grass doesn't have a hitbox, so it shouldn't affect pathing at all, right?
