### ISSUE TITLE
Entity targeting

### ISSUE THREAD

**Issue by AstroOrbis** [cabaletta/baritone#1855]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
It would allow for players to target certain entities, pathfind their way towards the entity, and kill the entity. 
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
Pathfinding, Killaura, Autotool
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
Its a feature that would greatly improve Baritone.

**Comment by dominikaaaa** [comment]
this has already been suggested, and baritone already has #follow

**Comment by AstroOrbis** [comment]
but it doesn't automatically kill the targeted entity

**Comment by scorbett123** [comment]
Just enable kill aura on a client at the same time. As l1ving said in their original message, this is also a duplicate.

**Comment by AstroOrbis** [comment]
duplicate of what issue?

**Comment by AstroOrbis** [comment]
and i only want baritone installed, killaura is kinda op because it can go through walls

**Comment by l1ving** [comment]
Out of scope.

**Comment by AstroOrbis** [comment]
?

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/109336591-a1e80480-7831-11eb-9295-8058770873e3.png)

**Comment by AstroOrbis** [comment]
ah ok...
