### ISSUE TITLE
Baritone only works for one or two game launches

### ISSUE THREAD

**Issue by SkywalkerSW5** [cabaletta/baritone#1859]
## Some information
Operating system: Linux
Java version: 1.8
Minecraft version: 1.12.2
Baritone version: Impact 4.9.1

Hello

I have an issue where baritone will only work on the first game launch. After the first launch when I try to use ex mine iron, it says it will do it but it doesn’t. There us absolutely no error messages, it just doesn’t do it.

## How to reproduce
Launch Minecraft 1.12.2 with Impact 4.9.1 .
Play a server world, then quit.
Launch the game again.

## Modified settings
I have no modified settings.

**Comment by dominikaaaa** [comment]
I can't reproduce this. Try using Oracle JDK 8
