### ISSUE TITLE
When 1.16.1 tho?

### ISSUE THREAD

**Issue by c0d3rb0y** [cabaletta/baritone#1860]
## The problem
I was in an email chain about Baritone 1.16 and they said theres no MCP 1.16.1
And now there is. So is that gonna happen or nah?

# ALSO I KNOW YOU HATE IT WHEN PEOPLE ASK BUT MCP 1.16 IS OUT SO CAN YOU PLEASSSSSSSSSSSSSE

**Comment by dominikaaaa** [comment]
when it's released
