### ISSUE TITLE
Ability to register functions to be run when the current process finishes

### ISSUE THREAD

**Issue by FeldrinH** [cabaletta/baritone#1861]
## Describe your suggestion
Some system accessible from the Baritone Java API to register arbitrary functions or event handlers to run when the current process (building, mining, pathing, etc) finishes with info about whether the process ended with failure or success.

## Context
This would make it much easier to write complex bots which use the API to execute multiple actions in sequence that depend on the previous action being successful to continue.

I'm a little hazy on the Baritone internals, so please let me know if there already is a system to do this in place.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#176

**Comment by dominikaaaa** [comment]
You'd have to do this yourself, (#proc returns the current process), as there isn't a way to queue processes yet
