### ISSUE TITLE
Baritone can't find path when there's a clear path.

### ISSUE THREAD

**Issue by sheemee1836** [cabaletta/baritone#1862]
## Some information
Operating system: Windows 10
Java version: Java 8 Version 251
Minecraft version: 1.15
Baritone version: 1.5.3
Forge mods (if used): 

## How to reproduce
Sometimes the bot is able to run for a few hours with no issue, but other times it just can't find pathts

## Modified settings
allowPlace false
blockBreakAdditionalPenalty 20
blockReachDistance 4.5
blocksToAvoidBreaking grass
breakCorrectBlockPenaltyMultiplier 3

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

![b1](https://user-images.githubusercontent.com/38139583/87105477-1fbab980-c229-11ea-804c-0555996ed246.PNG)
As you can see, the blocks are clearly there and in range, but Baritone can't find a path to them.

**Comment by dominikaaaa** [comment]
> allowPlace false

# :monkey:

**Comment by sheemee1836** [comment]
Hi I have allowPlace false because I'm botting on hypixel and can't place blocks in the tree area

**Comment by sheemee1836** [comment]
Hi,

I have allowPlace set to false because the server I play on does not allow block placement at that area.

**Comment by dominikaaaa** [comment]
okay but baritone clearly can't reach the block without placing blocks, and you have disallowed palcing

**Comment by sheemee1836** [comment]
When I get stuck, I always walk forward a bit and then Baritone automatically breaks the block because it's only 4 blocks off the ground (only this tree and one other tree causes issues for some reason) and continues pathing. For some reason, the path occasionally stops early and is unable to break the target block. I can try to record the issue; it's just hard to get on recording because I normally leave my laptop on and come back to see it stuck. I've never actually seen it get stuck while I was looking at it.

**Comment by dominikaaaa** [comment]
```
#failureTimeoutMS 10000
#movementTimeoutTicks 10000
#planAheadFailureTimeoutMS 10000
```

**Comment by sheemee1836** [comment]
Thanks!
I changed these values and I'll see if the problem has been fixed.
