### ISSUE TITLE
Baritone console client

### ISSUE THREAD

**Issue by TheCrazyInsanity** [cabaletta/baritone#1864]
## Describe your suggestion
Allow baritone to be ran with no graphics just text in a command prompt like environment where all you can do is send chat messages (or commands)

##Settings
Scripting, allowing simple programming using baritone allowing capability such as mining untill inventory is full then pathfinding to house and placing items in chest then start mining again.

## Context
It would allow running multiple baritone sessions at once to be alot easier and less resource intensive.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#844

**Comment by dominikaaaa** [comment]
Comment from the original 

> It's a neat idea but it would be hard to implement because of how much it relies on running mc features.
