### ISSUE TITLE
add bots back

### ISSUE THREAD

**Issue by axcsds** [cabaletta/baritone#1866]
## Describe your suggestion
add bots back and fix bugs in bots

## Settings
DoesBotPlace defualt = true
DoesBotBreak defualt = true
DoesBotIummueToFire defualt = true
DoesBotIummueToCactus defualt = true
DoesBotCanWalkInWater defualt = true
DoesBotCanWalkInLava defualt = true

## Context
Because this feature needs to be here

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
lol

**Comment by dominikaaaa** [comment]
what???

**Comment by UltraBlackLinux** [comment]
Heck what are you trying to explain here
