### ISSUE TITLE
I can't @mine for diamond_ore.

### ISSUE THREAD

**Issue by filiperose** [cabaletta/baritone#1868]
![image](https://user-images.githubusercontent.com/29162342/87240911-e744f680-c447-11ea-9a3d-9e1f7ffdabea.png)

How can I fix it?

**Comment by ZacSharp** [comment]
This is the Baritone repository and you are asking for help with Fabritone.
This is still open just because I can't close it.

**Comment by Bluscream** [comment]
the error means that fabritone doesn't find the ore. you either need to enable cheat mode or search for the ore yourself and only use fabritone to mine it
