### ISSUE TITLE
Water bucket fall not working

### ISSUE THREAD

**Issue by tay7770** [cabaletta/baritone#1869]
I am currently using 1.15.2 Impact 4.9.1, and I turn on baritone, then set a goal, and then path. In the settings I put max water bucket fall 255. I leave baritone to do its thing, but when I look back I had died from fall damage. I had a water bucket in my inventory with auto tool on. Please explain why water bucket fall isn't working. Thanks!

**Comment by dominikaaaa** [comment]
> In the settings I put max water bucket fall 255. I leave baritone to do its thing, but when I look back I had died from fall damage. 

It's working just fine, you changed the fall height to too much. 
![dominikaaaa org-2020-07-12-16-32-46](https://user-images.githubusercontent.com/17222512/87255993-5547e880-c45d-11ea-9837-ab150174fc9f.png)
