### ISSUE TITLE
Will you update Baritone to the newer versions of forge? (31.2.X)

### ISSUE THREAD

**Issue by TheButterbrotMan** [cabaletta/baritone#1870]
## What do you need help with?
Will you update Baritone to the newer versions of forge? (31.2.X)
Or can i allready use it with newer version then 31.1.0?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
No.
