### ISSUE TITLE
''#farm'' function lag

### ISSUE THREAD

**Issue by idkthunder** [cabaletta/baritone#1872]
I'm using ''#farm'' to auto plant and harvest carrots, and when I use it on a small plantation it doesn't lag. But when I'm using it with a lot of farmland blocks around me it lags a lot due to the green line around the farmland blocks Baritone identifies.

I know the green lines are part of Baritone and it's not a bug. I just wanna know if is possible to turn off this green markers around the farmland blocks, so it will stop lagging

I'm attaching a in-game print showing what I'm talking about
![Baritone](https://user-images.githubusercontent.com/62973832/87504109-3e132180-c63c-11ea-9ccd-f334d78d243f.png)

**Comment by dominikaaaa** [comment]
![Screenshot_20200715-092720](https://user-images.githubusercontent.com/17222512/87550779-6f601180-c67d-11ea-98c8-0255c8171760.png)

**Comment by UltraBlackLinux** [comment]
Heck? @dominikaaaa isbthis jenkins or an app?

**Comment by dominikaaaa** [comment]
this is the documentation which is linked in the read me

**Comment by idkthunder** [comment]
Thank you :)
