### ISSUE TITLE
[Feature] Hability to Prune all waypoints by tag

### ISSUE THREAD

**Issue by leafax** [cabaletta/baritone#1874]
## Describe your suggestion
Have the ability to delete multiple waypoints containing the same tag.
#wp d Bed all would delete all waypoints made under the tag bed and so and so.

## Settings
Possibly by tag but also add a feature to delete the whole page as well maybe 

## Context
I retardedly click on beds/die so having the option to purge my wp list would make it possible to have less than 120 pages of waypoints

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
#wp clear <Tag>     will clear all the waypoints under a specific tag.
