### ISSUE TITLE
#farm function not working properly while farming nether warts

### ISSUE THREAD

**Issue by idkthunder** [cabaletta/baritone#1877]
-Operating system: Windows 10 Professional
-Java version: Version 8 Update 51 (build 1.8.0_51-b16)
-Minecraft version: 1.15.2
-Baritone version: 1.15.2
-Forge mods (if used): none

*I know in order to plant nether warts it's necessary to toggle ''replantNetherWart'' to true.

But even after doing it, the ''#farm'' function still doesn't work properly. I gonna mention a few cases that happened to me:

-Baritone only plants nether warts on the soul sands that are at my reach distance without moving my character! And ignores the soul sands far from my range (and I meant it only by a few blocks), then after a couple seconds it shows a ''Farm failure'' error message.
-Baritone doesn't even plant the warts on all soul sands near me.

I noticed a couple other glitches involving this matter, but I only mentioned the ones I considered important.

This is a link to a video I did showing my problem: https://www.youtube.com/watch?v=KIBA428bOms&feature=youtu.be
(I know the quality is shit, but you guys can see whats going on).

*/
I tried to explain my issue in the best way I could, but I'm from Brazil and english is not my main language, so I'm sorry for any mistakes.
*/

**Comment by dominikaaaa** [comment]
Can you send a screenshot of #modified

**Comment by idkthunder** [comment]
> Can you send a screenshot of #modified

![BugBaritone](https://user-images.githubusercontent.com/62973832/87678679-9c7df400-c751-11ea-86c0-6145141abd7a.png)

Do you think this is a problem with my Baritone?

**Comment by dominikaaaa** [comment]
No. I was just making sure a setting wasn't intefering. It looks like Baritone can't path on soul sand properly.

**Comment by idkthunder** [comment]
> No. I was just making sure a setting wasn't intefering. It looks like Baritone can't path on soul sand properly.

When you have time, can you please try it and see if the same thing happens to you please?
It`s very simple to reproduce it.

Thank you for the attention!

**Comment by idkthunder** [comment]
I just found this ticket: https://github.com/cabaletta/baritone/issues/19

It explains why this happens, and unfortunately I think there's no way around it

Thank your for the attention!

**Comment by idkthunder** [comment]
It would be nice if someone could add Soul Sand to the list of ''canWalkOn'' blocks. Or do something where it can be toggled on or off.
