### ISSUE TITLE
Can i start on 1.16.1 workings?

### ISSUE THREAD

**Issue by c0d3rb0y** [cabaletta/baritone#1878]
## What do you need help with?
Absolutely nothing. Just need to know if i have permission.
Edit: wait should i just fork it and do that
Edit 2: Yeah i'm gonna fork it but can someone close this?

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Just follow the license. Also you always have permission to close issues you created.
