### ISSUE TITLE
Decrease render settings on travis, no one's looking at the gui anyway

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#188]
Right now there's a "can't keep up, skipping ticks" every minute or so

**Comment by ZeroMemes** [comment]
Even after d7a0d26 Travis is still getting like 7 of those per successful build. At least it's consistent.

**Comment by ZeroMemes** [comment]
o o p s l o l

**Comment by leijurv** [comment]
gonna call https://github.com/cabaletta/baritone/commit/d7a0d26fd24fd5f881f56db6596e57df3b4353b1 good enough
