### ISSUE TITLE
Parameter to limit Y level for automine (Non legit)

### ISSUE THREAD

**Issue by muniategui** [cabaletta/baritone#1883]
## Describe your suggestion
I would like a parameter to limit Y level for example MaximumMineYLevel 50 will allow baritone only to mine on level 51 and above. 

## Settings
MaximumMineYLevel

## Context
The request is done in order to bypass some Xray which places fake blocks in deeper Y levels and with that setting Baritone would be able to avoid them while Xray mining is performed.

**Comment by l1ving** [comment]
Bruh, this issue was for max, not min

**Comment by Tanju42** [comment]
so then what happened with this request?

**Comment by l1ving** [comment]
the wrong thing was added

**Comment by Tanju42** [comment]
yeah and when are you guys planing to implement it I dont know the code but I think its fairly simple?

**Comment by l1ving** [comment]
it will be implemented once it is added to Baritone

**Comment by Tanju42** [comment]
On https://github.com/cabaletta/baritone/blob/16cfcb36a3cf7ce4063740498cf45efcd6f1c463/src/main/java/baritone/process/MineProcess.java#L420

is this:
`.filter(pos -> pos.getY() >= Baritone.settings().minYLevelWhileMining.value)`
and when you add this:
`.filter(pos -> pos.getY() <= Baritone.settings().maxYLevelWhileMining.value)`

and the commands to adjust it + the settings() section it would work right?

**Comment by Tanju42** [comment]
I will try to fork it and implement it

**Comment by zengkuankuan** [comment]
Now 1.17.1 has Y0, how to import minerals below - 60, only dig minerals below 0
