### ISSUE TITLE
How to reduce the speed of the system?

### ISSUE THREAD

**Issue by Luminuus** [cabaletta/baritone#1885]
Hello, 

I'd like to know if it's possible to reduce the speed of the #mine #farm automatic system. 

I'm on a server where there are jobs that make money. 
But here's the thing, in my case it's picking up too fast and I'm getting messages like "please wait 0 sec / 1sec to get paid again". 

Is there any way to reduce that speed ?

thx

**Comment by dominikaaaa** [comment]
You can't do that.

**Comment by Luminuus** [comment]
sad but ok
