### ISSUE TITLE
When running #goto, after an hour or two it just randomly stops and i have to run the command again.

### ISSUE THREAD

**Issue by 2northdeq** [cabaletta/baritone#1886]
## Some information
Operating system: MacOSX Catalina 10.15.5
Java version: Java 8 Update 261
Minecraft version: 1.12.2
Baritone version: Impact 4.9.1
Forge mods (if used): Impact, Mystic.cc, Osiris

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Use the #goto command and let it run for an hour or two.

## Modified settings
To get the modified settings run `#modified` in game
ChatControl, Type: Boolean, Value: False
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
That means it can't find a path
