### ISSUE TITLE
Baritone with forge

### ISSUE THREAD

**Issue by McKoolAid** [cabaletta/baritone#1887]
Hello, I have been trying for several days to figure out how to use baritone with forge, i am trying to utilize it with either a premade modpack like FTB or a modpack that i put together. Any help would be greatly appreciated. I have downloaded just about every file in the releases for 1.12.2 and still cant get it to read as a mod in the game. Thanks!

**Comment by dominikaaaa** [comment]
Baritone doesn't show up as a forge mod when installed in forge
