### ISSUE TITLE
How do I add schematics

### ISSUE THREAD

**Issue by yodaluca** [cabaletta/baritone#1890]
using impact version 4.9.1 I was not sure if I should submit this in the impact github but yea I can't find a folder for the schematics someone please tell me how￼￼????

**Comment by dominikaaaa** [comment]
![Screenshot_20200719_101835](https://user-images.githubusercontent.com/17222512/87876935-37bcd680-c9a9-11ea-8dc5-68856d108bae.png)

**Comment by yodaluca** [comment]
Ik how to do the build commands but I can't find the folder to put it in

**Comment by dominikaaaa** [comment]
It's called `schematics`

**Comment by yodaluca** [comment]
Is that the folder I will look again I guess

**Comment by yodaluca** [comment]
I still can't find it and I looked in every single folder in my .minecraft folder￼

**Comment by dominikaaaa** [comment]
If you don't have a `schematics` folder inside .minecraft then you can make one
