### ISSUE TITLE
#Mine when entered freezes immediattely and outputs this in console

### ISSUE THREAD

**Issue by GaboGamer1435MC** [cabaletta/baritone#1891]
13:58:11.030
[STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.OutOfMemoryError: Java heap space
13:58:11.030
[STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
13:58:11.030
[STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
13:58:11.030
[STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
13:58:11.030
[STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:144)
13:58:11.030
[STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:67)
13:58:11.030
[STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:70)
13:58:11.030
[STDERR]: 	at baritone.event.GameEventHandler$$Lambda$4301/1933264335.accept(Unknown Source)

**Comment by dominikaaaa** [comment]
https://downloadmoreram.com/
