### ISSUE TITLE
Does it work to mine modded blocks?

### ISSUE THREAD

**Issue by Llamaverse7** [cabaletta/baritone#1896]
I tried using it to mine pixelmon blocks but it doesn't work so i was just wondering if I'm doing something wrong

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
`#mine modid:blockid`

**Comment by dominikaaaa** [comment]
If it doesn't work, then you can search to see the existing opened issues about this

**Comment by Llamaverse7** [comment]
thank you

**Comment by CDAGaming** [comment]
Linking to #1720 if it doesn't work. I mention there to ensure it's the actual id from advanced tooltips if you dont know the id directly.

**Comment by Dannyboibruh** [comment]
So to clarify to anyone searching this up, go to https://pixelmonmod.com/wiki/Item_IDs for the item ID, and in baritone, do #mine pixelmon:[item ID]  that is what they meant modid:blockid, but I just wanted to clarify.

**Comment by vnsugadev** [comment]
I am trying to mine Copper Ore from the mod Tinker's Construct, I tried what the Wiki told it's ID is #mine TConstruct:materials:9
But it doesn't seem to work.
