### ISSUE TITLE
How to add Baritone to MCP-Reborn

### ISSUE THREAD

**Issue by SemmieboyYT** [cabaletta/baritone#1898]
## What do you need help with?
So I am making my own hacked client using [MCP-Reborn](https://github.com/Hexeption/MCP-Reborn) and [IntelliJ IDEA](https://www.jetbrains.com/idea/). Then I got the idea to add Baritone to my client. I am not that good with Java, but I was able to add Baritone to my client. All errors fixed, and my client is able to start up. But when I try to use Baritone by doing any of his commands, my message just gets send to the server and nothing else happens. I did find one line in the log that makes me think I am just launching the client wrong: `Completely ignored arguments: [--tweakClass, baritone.launch.BaritoneTweaker]`. Please help me fix this, and please don't use to difficult words unless you can't otherwise. If any more information is needed just ask it in the comments.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this question.

**Comment by dominikaaaa** [comment]
How did you add it?

**Comment by SemmieboyYT** [comment]
I just copied all the files in the correct place, then ran the client with the tweak class set. Then I got the errors, fixed them, ran the client, fixed the errors, until all the errors were fixed. But then I got the problems I said in my main question. Its most likely the worst way I could have added it but as I said, I don't know THAT much of Java yet. Oh, also here is my run configuration: 
![SharedScreenshot](https://user-images.githubusercontent.com/58337334/88081906-5a094c80-cb81-11ea-9ac0-1245d808d202.jpg)

**Comment by dominikaaaa** [comment]
uh yea you don't do that

**Comment by dominikaaaa** [comment]
add it to your gradle with the instructions in setup.md

**Comment by SemmieboyYT** [comment]
Do I have to copy over any files?

**Comment by dominikaaaa** [comment]
No, you do *not* do that. You do it properly, with Gradle.

**Comment by CDAGaming** [comment]
Also might I add, why do you even feel the need to use MCP-Reborn, when you could just use ForgeGradle 3.+, as other clients can be made in it just fine. Using an unofficial product would just be over-complicating things imo.

**Comment by dominikaaaa** [comment]
And distributing MCP clients is completely against mojang's EULA

**Comment by dominikaaaa** [comment]
I'm closing this because we don't even really support MCP clients, do it properly or don't do it at all
