### ISSUE TITLE
Commands and Settings for mining a 2x1 Nether Tunnel?

### ISSUE THREAD

**Issue by JDButter** [cabaletta/baritone#1900]
## What do you need help with?
So, I have been trying to mine out a nether tunnel in a server, But doing it manually has been quite annoying. #tunnel Doesn't exactly fulfill the things I want, And instead of filling in lava pockets, It mines around them. Is there a setting to turn off that would change that? Or is this too complex? Cheers!

TLDR, I want Nether Tunneling bot that doesn't avoid obstacles, and rather fills them in/fixes them. but brain too small to understand how to get it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue. (Surprisingly)

**Comment by dominikaaaa** [comment]
No, currently it can only go around lava. There's a suggestion already opened to have it fill the lava in
