### ISSUE TITLE
Baritone UI.

### ISSUE THREAD

**Issue by AverWasTaken** [cabaletta/baritone#1901]
## Describe your suggestion
A UI for baritone. Like for going to a certain place or mining certain blocks.

## Settings
A fully customization rich UI. IE, Colors, Layouts etc...  

## Context
This would improve baritone by adding a easy way to get baritone to do things. Instead of having to remember commands. For example you could have a box that says Path To, and a user input box, Then you just click path, and baritone goes. You could have a little list of blocks, you pick the ones you wan't baritone to mine, click go, and boom. It goes. Overall just a cleaner way to do things, and an easier way for beginners to learn how to use it. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Duplicate

**Comment by AverWasTaken** [comment]
Can you link the issue where this is a duplicate.

**Comment by dominikaaaa** [comment]
#887

**Comment by dominikaaaa** [comment]
## #794

**Comment by dominikaaaa** [comment]
# #1726
