### ISSUE TITLE
Why can't I connect to a server with baritone?

### ISSUE THREAD

**Issue by TheMadShotgun** [cabaletta/baritone#1902]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheMadShotgun** [comment]
every time I try to log in, it just gets stuck and says "logging in" for every server I try

**Comment by TheMadShotgun** [comment]
Wait, I may have fixed it, brb with more info if anyone is on this thread

**Comment by mesolol919** [comment]
how
