### ISSUE TITLE
Baritone breaking not grown crops

### ISSUE THREAD

**Issue by Xscallcos** [cabaletta/baritone#1903]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
On fabritone, when I try to use the command #farm to farm the crops it frequently gets stuck breaking and placing the same crop even though it is not grown yet. I have tried to disable breaking of carrots and potatoes but that didnt help the issue.
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Please stop making duplicate and spam issues
