### ISSUE TITLE
Link to Javadocs in readme is broken.

### ISSUE THREAD

**Issue by MikhailKhromov** [cabaletta/baritone#1906]
When trying to go to https://baritone.leijurv.com/, I get 404 not found error.

**Comment by dominikaaaa** [comment]
#1640

**Comment by MajsterTynek** [comment]
Ah yes... They unavailable 3rd day in a row...

I suggest downloading source code
and running `gradlew javadoc` yourself...
Then find `.\build\docs\javadoc\index.htm`
