### ISSUE TITLE
cannot find schematic file

### ISSUE THREAD

**Issue by Spraizwastaken** [cabaletta/baritone#1908]
## Some information
Operating system: Windows
Java version:
Minecraft version: 1.15.2
Baritone version:
Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/latest.log

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
bruh
