### ISSUE TITLE
Make that Baritone can use all items in inventory while using build

### ISSUE THREAD

**Issue by tr432** [cabaletta/baritone#1910]
## Describe your suggestion
So, building schematics is very easy with Baritone. You can build a mansion, can build everything that's available as a schematic, but as an exception: If the build has more than 9 different blocks, you must change the slots constantly/or 5-6 times at least, as more than 9 blocks doesn't fit our hotbar.

## Settings
There's no settings available for this.

## Context
It could improve the Baritone from the building side, there's people who don't want to build 30 minutes long pixel arts/build, instead building them with no effort, without WorldEdit. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
allowInventory
