### ISSUE TITLE
Baritone 1.8

### ISSUE THREAD

**Issue by c0d3rb0y** [cabaletta/baritone#1911]
## Describe your suggestion
It would allow more utility mod makers to have more things to put in their utility mods

## Settings
Not really anything but basic pathfinding

## Context
go to the first part

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
No

**Comment by dominikaaaa** [comment]
https://github.com/michaelzangl/minebot
