### ISSUE TITLE
What is the name for concrete in Baritone

### ISSUE THREAD

**Issue by SuperMiniDaws** [cabaletta/baritone#1913]
i just need to know because i want to "#sel fill" blue concrete into my selected
![image](https://user-images.githubusercontent.com/68859124/88551200-7fcba100-d01a-11ea-8964-13e2c5982b94.png)

Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Same name that minecraft calls it. Baritone uses Minecraft namespaced names, not some special whatever.

**Comment by dominikaaaa** [comment]
![Screenshot_20200727-102844](https://user-images.githubusercontent.com/17222512/88554039-fe611800-cff3-11ea-961a-60562422bac0.png)
https://minecraft.gamepedia.com/Java_Edition_data_value/Pre-flattening#Block_IDs
