### ISSUE TITLE
Choose what slot to use

### ISSUE THREAD

**Issue by Wahubah** [cabaletta/baritone#1915]
## Describe your suggestion
We should be able to choose what slot we want to use when mining blocks instead of it defaulting to the "best item" in whatever slot

## Settings
n/a

## Context
theres a lot of Minecraft servers in the prison genre where beacons are a main currency and baritone will default to slot 1 when mining beacons which can cause problems when servers don't allow you to put your pickaxe in slot 1. The reason I need to use my pickaxe is because it has haste which makes mining them faster so being able to do something like #slot 2 or be able to like choose which type of tool u want to use to do something would be a good addition to the bot

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by Wahubah** [comment]
And before you close this because baritone accounts for enchantments, apparently it might not on certain servers because of plugins because the pickaxe I use does have haste but will still refuse to use it

**Comment by dominikaaaa** [comment]
I'd close this in favor of #1334, because with #1334 it wouldn't change the slot, so it would use whichever slot you selected
