### ISSUE TITLE
Baritone And cobblestone gens

### ISSUE THREAD

**Issue by FliqaX** [cabaletta/baritone#1916]
I really want to use barritone on a skyblock server so it will automaticly mine the cobblestone generated from a cobble gen but it gives me the error message : no lacations for blockoptionalmetalookup{[BlockOptionalmeta{block=Block{minecraft:cobblestone}}]} know, cancelling. Is this a feature i need to enable?

**Comment by UltraBlackLinux** [comment]
Please fill out the template

**Comment by dominikaaaa** [comment]
That means there's not cobblestone in render distance
