### ISSUE TITLE
bot not moving

### ISSUE THREAD

**Issue by turbokillerfin** [cabaletta/baritone#1918]
## Some information
Operating system: Windows 10 home
Java version: don't really know.
Minecraft version: 1.16.1
Baritone version: says that it's a null version.
Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by turbokillerfin** [comment]
So i play Minecraft 1.16.1 with Aristois and baritone as an addon.
It has worked always before and this is the first time ever im having any problems with baritone.
So the bot does the pathfinding thing and after that when there is a path it just doesn't move anywhere.

**Comment by BroSotos** [comment]
if you have sodium installed, baritone won't move

**Comment by CDAGaming** [comment]
@turbokillerfin Since im assuming your using fabritone, this should be closed as fabritone hasnt been updated to fully work for 1.16.1, and not planned to be until Baritone is considered releasable.

**Comment by dominikaaaa** [comment]
> So i play Minecraft 1.16.1 with Aristois and baritone as an addon.

That's called Fabritone, not Baritone. This issue is better suited in the Fabritone repo

**Comment by turbokillerfin** [comment]
thanks!
