### ISSUE TITLE
 #Farm prefers thinking rather than farming

### ISSUE THREAD

**Issue by beerjongen** [cabaletta/baritone#1920]
The 'to be farmed' crops are completely ignored, as well as the locations to plant new ones. Creative with bonemeal doesn't change anything. 
I've not been able to pin down exactly where it works and where it doesn't. Sometimes it gets a few random crops and calls it a day, sometimes it just ignores all.
All below screenshots are baritone v1.6.1 on 1.16.1, taken on both sp & mp servers. 
With some version testing I have found this bug to be 1.6.1 specific (in oppose to the 'portal issue'). 

![image](https://user-images.githubusercontent.com/43498703/88827500-52bdf080-d1ca-11ea-8c1c-4553530e76d6.png)
![image](https://user-images.githubusercontent.com/43498703/88827546-5f424900-d1ca-11ea-979a-a7117ca4ba05.png)
![image](https://user-images.githubusercontent.com/43498703/88827607-708b5580-d1ca-11ea-823b-75b06ed13345.png)
![image](https://user-images.githubusercontent.com/43498703/88827641-7e40db00-d1ca-11ea-957d-944407c0c89f.png)

**Comment by dominikaaaa** [comment]
This is an issue in older versions, I've 100% seen people report this before

**Comment by beerjongen** [comment]
I've been checking though v1.2.9 to v1.2.14, 1.5.3 and multiple instances of 1.6.1
All 1.6.1 tests were unsuccesful. All other versions were succesful.

**Comment by beerjongen** [comment]
Duplicate of #1877

**Comment by CDAGaming** [comment]
Can be closed now, fixed in 1.16.2 Branch!
