### ISSUE TITLE
#mine ignores new placed blocks

### ISSUE THREAD

**Issue by beerjongen** [cabaletta/baritone#1921]
Another 1.6.1 specific issue tested over a wide range of versions with default settings. 
Newly placed blocks are completely ignored. Biome foreign blocks result in 'no locations' prompt. 
No workaround has been found like #1920 , which also shares the similarity to be 1.6.1 specific. Unlike #1919 which seems to be around for a while and eventually finds the portal. Might be related. 
![image](https://user-images.githubusercontent.com/43498703/88839789-cf0cff80-d1db-11ea-8bbf-dfbeb0953d62.png)

**Comment by UltraBlackLinux** [comment]
What are you talking about?! There is no 1.6.1.

**Comment by beerjongen** [comment]
> What are you talking about?! There is no 1.6.1.

There is. Please do a bit of reasearch before posting.

**Comment by dominikaaaa** [comment]
Yes there is.

**Comment by UltraBlackLinux** [comment]
There is no release.

**Comment by dominikaaaa** [comment]
No, there is no release. No, it is officially supported. No, it is not Fabritone. Stop spreading misinformation

**Comment by UltraBlackLinux** [comment]
It isnt officially supported: #1934
Also where can I get baritone 1.16 sigh.

**Comment by dominikaaaa** [comment]
Who said it's not officially supported in the issue you linked??? The only comment was mine.

**Comment by UltraBlackLinux** [comment]
That basically means it isnt supported. As you said in many Issues.

**Comment by beerjongen** [comment]
Can you stop being a smart ass, this is not reddit. You are responding to a support ticket, not a reddit post. Please only resort to posting here if you have something to say related to this issue.

**Comment by CDAGaming** [comment]
Ok @UltraBlackLinux Ill try to be as nice as i can

Baritone 1.16.1 is being developed.
These issues were posted as a result of LIVE TESTING within the discord, and also effect other version of Baritone.

You may also notice I never mentioned fabritone in here, as this is a baritone issue at heart.

What your doing is inflating a ticket meant for investigating a possible severe issue, but If you dont mind baritone breaking later down the line from this, please continue.

**Comment by CDAGaming** [comment]
Also in regards to where you can get it, Live Testing has been postponed until the issues get investigated to prevent mass issue sending.

In regards to Fabritone "not being official", do note the branches on my repo, as if you had done a simple search, would see that other branches are baritone 1:1 with fabric.

All Fabritone is now is extra features, so if you dont want that you can use official baritone on fabric in the repo and have the same experience

**Comment by UltraBlackLinux** [comment]
Thanks for the info. Even though Fabritone is almost the same as Baritone, it isnt supported - dont ask me why.

**Comment by dominikaaaa** [comment]
It is not supported here. That does not mean you can spread misinformation. **Baritone** 1.16 exists and is supported.

**Comment by UltraBlackLinux** [comment]
Then Please tell me where. It seems like thee is an official download link, but no release. I dont understand.

**Comment by beerjongen** [comment]
> Also in regards to where you can get it, **Live Testing has been postponed until the issues get investigated to prevent mass issue sending**.
> 
> In regards to Fabritone "not being official", do note the branches on my repo, as if you had done a simple search, would see that other branches are baritone 1:1 with fabric.
> 
> All Fabritone is now is extra features, so if you dont want that you can use official baritone on fabric in the repo and have the same experience

**Comment by UltraBlackLinux** [comment]
oh yes lol

**Comment by CDAGaming** [comment]
@UltraBlackLinux https://gist.github.com/CDAGaming/ffef6af7236fbb70a09eb7a30812dd5b

This is my full statement

**Comment by UltraBlackLinux** [comment]
Thanks!

**Comment by dominikaaaa** [comment]
> Then Please tell me where. It seems like thee is an official download link, but no release. I dont understand.

https://github.com/cabaletta/baritone/tree/1.16.1

There's no prebuilt releases

**Comment by UltraBlackLinux** [comment]
thanks alot!

**Comment by CDAGaming** [comment]
Can be closed as Resolved, will be fixed in next release!
