### ISSUE TITLE
Baritone-API throwing NoClassDefFoundError: bei

### ISSUE THREAD

**Issue by Stelath** [cabaletta/baritone#1923]
## What do you need help with?
I am currently coding a Minecraft bot using the [mcprotocollib](https://github.com/Steveice10/MCProtocolLib), and I added the baritone API to my java library and imported it using:
```
import baritone.api.BaritoneAPI;
import baritone.api.pathing.goals.GoalXZ;
```
The issue arises after I connect to the server, once I get the "ServerJoinGamePacket" which confirms my client has joined the game I run the Baritone-API setGoalAndPath. This then throws the error, I also cant change the BaritoneAPI settings as adding ".value" to the end seems to be invalid.
```
                if(event.getPacket() instanceof ServerJoinGamePacket)
                {

                    event.getSession().send(new ClientChatPacket("Testing"));

                    // Run Baritone Run Command
                    BaritoneAPI.getSettings().allowSprint.value = true;
                    BaritoneAPI.getSettings().primaryTimeoutMS.value = 2000L;
                    BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().setGoalAndPath(new GoalXZ(10000, 20000));
                }
```

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [] I have resolved this issue.

**Comment by dominikaaaa** [comment]
it should be .getValue() on Java

**Comment by Stelath** [comment]
@dominikaaaa Unfortunately, .getValue() doesn't work for the settings and the main problem was the NoClassDefFoundError: bei

**Comment by dominikaaaa** [comment]
then you're mismatching an obf / unobf jar in a obf / unobf environment

**Comment by Stelath** [comment]
@dominikaaaa Sorry, I don't want to bother you much more but, can you clarify that a bit more?

**Comment by dominikaaaa** [comment]
You're using the wrong jar in the wrong environment probably. Meaning you're using an obfuscated jar in a developer environment or an unobfuscated jar in a normal environment

**Comment by Stelath** [comment]
Sorry to bother you again but how would I get an unobfuscated jar? Would I build it using the source code download with Gradle? Or is it the Baritone-API jar on the releases page?

**Comment by Stelath** [comment]
@dominikaaaa please read the above comment

**Comment by dominikaaaa** [comment]
You're not supposed to use the unobfuscated jar anywhere
