### ISSUE TITLE
Package schematica.client.world does not exist when running Baritone

### ISSUE THREAD

**Issue by Olament** [cabaletta/baritone#1924]
I followed the [setup](https://github.com/cabaletta/baritone/blob/master/SETUP.md) instruction and generated a ```Minecraft Client``` configuration to run baritone with ```genIntellijRuns```. However, I got the following error message

```
/Users/***/IDEAProjects/baritone/src/main/java/baritone/utils/schematic/schematica/SchematicAdapter.java:21:52
java: package com.github.lunatrius.schematica.client.world does not exist
```

JDK version: jdk1.8.0_261

Let me know if you need any further information, Thank you!

**Comment by dominikaaaa** [comment]
I'm pretty sure it's not supposed to exist, schematica is a different mod

**Comment by Olament** [comment]
Yeah it looks like a wrapper to support schematica integration in baritone. Here is the [line](https://github.com/cabaletta/baritone/blob/a25afd5c139d1a54d428d764239fc5fe355e0289/src/main/java/baritone/utils/schematic/schematica/SchematicAdapter.java#L21). Any thoughts?

**Comment by Olament** [comment]
Thank you! It looks like ```runClient``` works but not ```Minecraft Client```. Not sure why.

**Comment by dominikaaaa** [comment]
That's strange. It's always been the other way around for me

**Comment by Olament** [comment]
Indeed, I tested it on both Windows and macOS with Intellij IDE and got the same result.
