### ISSUE TITLE
Baritone gets stuck in build then break loop when on top of cactus while building schematic.

### ISSUE THREAD

**Issue by JackertheHacker** [cabaletta/baritone#1927]
## Some information
Operating system: Windows
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.14
When attempting to build any sort of compact cactus farm with B. it makes it partially through the first layer then gets stuck in an infinite loop of placing, then jumping on top of, then breaking the same cactus. I think it wants to avoid getting hurt on the cactus so it breaks it but then it replaces it to continue the build. Any settings that bypass this?

**Comment by dominikaaaa** [comment]
Baritone can't talk on cactus, it's blacklisted.
