### ISSUE TITLE
How do I have completely afk and safe mining?

### ISSUE THREAD

**Issue by bluedeix** [cabaletta/baritone#1929]
I discovered baritone through afk mining, I think that at first it was what attracted me the most, but now that I have installed it, I started to see the other functions etc.

But speaking of mining, on several occasions that I left mining, I would die for lava or for mobs, I wanted to know if there is any configuration or change so that it doesn't happen anymore, and have safe mining and afk, thank you.

**Comment by dominikaaaa** [comment]
Use a client that has a baritone compatible killaura, such as kami blue or impact

**Comment by ZacSharp** [comment]
and for the lava the only option is fire resistance
