### ISSUE TITLE
Where in setup.md does it say how to add it to an existing project's gradle?

### ISSUE THREAD

**Issue by c0d3rb0y** [cabaletta/baritone#1930]
## What do you need help with?
I read this [issue](https://github.com/cabaletta/baritone/issues/1898) and domnika said that you can use instructions from setup.md to add it to your MCP-Reborn client. Where does it say this?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
I didn't say that. I said don't use MCP to make a client

**Comment by dominikaaaa** [comment]
Did you even try reading the issue??
![Screenshot_20200802-141118](https://user-images.githubusercontent.com/17222512/89129277-1b04c080-d4ca-11ea-9aa4-4bc8bebdc07a.png)
![Screenshot_20200802-141136](https://user-images.githubusercontent.com/17222512/89129280-1cce8400-d4ca-11ea-905f-2c085959c437.png)

**Comment by MeetPing** [comment]
Yes but it should still be the same behavior. So if it were be possible then how?

**Comment by dominikaaaa** [comment]
Don't use MCP

**Comment by SirObby** [comment]
Okay so im going to use forgegraddle as i havent done anything in mcp-reborn yet
How would i add it?

**Comment by dominikaaaa** [comment]
by reading the instructions

**Comment by SirObby** [comment]
What instructions? If i cant see them its because im blind.

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone#getting-started

**Comment by SirObby** [comment]
So then im blind

**Comment by SirObby** [comment]
i dont even know how to use forgegradle

**Comment by dominikaaaa** [comment]
Just shadowjar baritone with jitpack lmfao
