### ISSUE TITLE
Add amount of given block to #mine

### ISSUE THREAD

**Issue by THEqqBULDIpp** [cabaletta/baritone#1931]
It would be very usefull if we were able to specify how much of each block in #mine command baritone has to dig out.

#mine (block id) [amount]; (next block id) [amount]; ... etc
~something like this (if possible of course)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
#mine iron_ore 20

**Comment by ZacSharp** [comment]
Nope that does not work @dominikaaaa 
It's `#mine 20 iron_ore`

**Comment by dominikaaaa** [comment]
¯\\\_(ツ)_/¯
