### ISSUE TITLE
Amount od items in #mine.

### ISSUE THREAD

**Issue by THEqqBULDIpp** [cabaletta/baritone#1934]
It would be nice to be able to customize how much of given Item baritone has to dig out with #mine

## Context
I already asked for that once and received response like #mine (block) (amount)
When i try to do that, baritone treats amount as next block id.
(Prefix is #)

#mine stone 10
[Fabritone] >mine stone 10
[Fabritone] Error at argument #2: Expected
ForBlockOptionalMeta

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
It's `#mine amount block`, also **don't** ask for help with Fabritone here, it is *not* Baritone
