### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by OwenFriend** [cabaletta/baritone#1937]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I think its a bug but I'm not sure. whenever I build something baritone eventually just places a block continues moving goes back to the block it has placed and breaks then immediately places it back and continues walking then goes back to the block breaks and places and it repeats this forever. I can sometimes fix the problem by walking off of the structure or placing a block but that is a rare occurrence and it usually happens again a little bit later. I use tinkercad for the schematics and blender for modeling but I don't think that is the problem because they work completely fine otherwise.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
template
