### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by donatboy86** [cabaletta/baritone#1938]
Could i get a rough estimate when Baritone for minecraft 1.16 will be coming out?
Also, is there a way i could help speeding up the process?

**Comment by UltraBlackLinux** [comment]
Seems like fabritone is the new mc 1.16 baritone - even though its still not officially supported

**Comment by dominikaaaa** [comment]
Fabritone is not the "new" Baritone, 1.16 Fabritone is supported even less then Baritone 1.16 is
