### ISSUE TITLE
Bariton 1.16 @build not working

### ISSUE THREAD

**Issue by 1Eis1** [cabaletta/baritone#1940]
ok so i am trying to get it to build s chem i tell it to build it and it says successfully loaded schematic for building origin better block pos unable to do it pausing resume to resume to cancel to cancel i need some help please

**Comment by beerjongen** [comment]
Try buildinlayers true and ignoreexisting true. As well, make sure you have all the blocks in your inv (allowinventory) or hotbar. As well have a stack of dirt, a shovel and a pickaxe. These are not official requirements but what I managed to be consistently successful with

**Comment by dominikaaaa** [comment]
**Don't** ask for help with Fabritone here, it is *not* Baritone

**Comment by Molly6969** [comment]
have the same issue with  Baritone every time start to build even with the coords its says origin: betterBlock Pos then goes away from where i want the house to be is there a fix for this?

**Comment by jockeking12** [comment]
> have the same issue with Baritone every time start to build even with the coords its says origin: betterBlock Pos then goes away from where i want the house to be is there a fix for this?

How can i fix this?
