### ISSUE TITLE
FullAuto Highway Builder

### ISSUE THREAD

**Issue by system69-e** [cabaletta/baritone#1945]
What I am trying to say is something that places e-chests, mines them, and places the obsidian according to your configured settings. note that I have tried to find something like this on this github and on Baritone itself, but i could not find what i was looking for

I have tried to find something like this on this github and on Baritone itself, but i could not find what i was looking for

**Comment by Tragafantas** [comment]
If what you want to do is building the Spawn Mason logo, note that they used a modified version of Baritone

**Comment by dominikaaaa** [comment]
> What I am trying to say is something that places e-chests, mines them, and places the obsidian according to your configured settings.

This is out of scope for baritone. KAMI Blue already has this feature and is compatible with kami blue

You can already do what you're trying to accomplish by creating a "template" for the highway out of dirt, `#s 1` and `#s 2` to create a selection and `#buildrepeat 1,0,0` and `#s r dirt obsidian`.

I'm currently working on a module that does exactly this, but it's automatic and you just right click the block to start.
