### ISSUE TITLE
Unable to mine chain redstone ore

### ISSUE THREAD

**Issue by hsh778205** [cabaletta/baritone#1948]
Operating system:windows 10
Java version:1.8.0_261-b12
Minecraft version:1.12.2
Baritone version:Forge 1.2.14
Forge mods (if used): no

## Exception, error or logs
Directive: #mine redstone_ore
When digging a chain of redstone_ore, the surrounding redstone will become lit_redstone_ore because it is activated, so it cannot be digged.

mc:1.12.2
baritone:Forge 1.12.14

**Comment by dominikaaaa** [comment]
do `#mine redstone_ore lit_redstone_ore` lmao
