### ISSUE TITLE
How to prevent Baritone from mining blocks that can't be broken?

### ISSUE THREAD

**Issue by henrydatei** [cabaletta/baritone#1949]
## What do you need help with?
I'm playing on a server that offers you to mine at a specific location. Only there you are able to break blocks, but only ores. Since the mining location is a cave, there is a lot of decorative (but not breakable) blocks. The ores are in the walls and refill every few minutes. I want baritone to mine to ores so I run `.b mine iron_ore`. This works perfectly fine until baritone tries to mine blocks that are harder to reach. Then it tries to break the blocks in the way which is prevented by the server, so baritone is stuck in breaking blocks.

Here you can see that baritone tries to mine a cobblestone slab that is unbreakable.
![2020-08-15_16 43 34](https://user-images.githubusercontent.com/31316025/90314758-8745e200-df16-11ea-8533-8b737ee19049.png)

I would now like to know what I can do to prevent baritone from breaking stone, cobblestone, cobblestone slabs, ... I know there's a setting `blocksToAvoidBreaking` but the blocks in this list get simply ignored.

BTW: I'm using Impact 4.9.1

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CDAGaming** [comment]
If by logical conclusion, the servers simply modofying its hardnessLevel, it should be pretty trivial to add this, though safe to say it would be in a new setting most likely

Ill take a look later on this.

**Comment by henrydatei** [comment]
I'm not really sure if that's the thing. I can break the cobblestone slab in normal time but when I've broken it, it gets put there instantly. It's a bit like when the server has some form of plot system (like the plugin plot^2). When you there try to break blocks on other players property the blocks get instantly replaced.

**Comment by dominikaaaa** [comment]
> I would now like to know what I can do to prevent baritone from breaking stone, cobblestone, cobblestone slabs, ... I know there's a setting `blocksToAvoidBreaking` but the blocks in this list get simply ignored.

That's a known bug

**Comment by henrydatei** [comment]
Are there already ideas to fix this? Or is there a fix in progress?

**Comment by dominikaaaa** [comment]
There's an opened issue somewhere

**Comment by UltraBlackLinux** [comment]
Turn on legit mine

**Comment by ScorpGaming4432** [comment]
How do i turn `legit mine` on?

**Comment by scorbett123** [comment]
#legitmine, it is a setting.

**Comment by 4lve** [comment]
im having the same problem

**Comment by Davut-A** [comment]
Same problem

**Comment by ZacSharp** [comment]
As far as I know `blocksToAvoidBreaking` does work, but if all alternatives are much longer or impossible Baritone will still mine the blocks in it (avoid != disallow). There is a newish `blocksToDisallowBreaking` setting which essentially makes path finding treat the specified blocks as unbreakable and there is `allowBreakAnyway` which is a list of blocks to be considered  breakable even if `allowBreak` is disabled.
