### ISSUE TITLE
Baritone Pathfinding

### ISSUE THREAD

**Issue by Mortaper** [cabaletta/baritone#1950]
I had an experiment using two accounts both with baritone installed. I dug a few tunnels in the nether leading up to a final goal. With two players starting at the exact same spot, I typed .goto (goal coords). However, the path taken by the two AI's are different, so I was just wondering if the final goal coords is the same across the two bots, shouldn't they be able to reach the goal using the same path?

**Comment by Tragafantas** [comment]
I think Baritone avoids players

**Comment by dominikaaaa** [comment]
It doesn't avoid players by default. It depends on if you have blocks in your inventory / tools / if you can sprint and have hunger

**Comment by dominikaaaa** [comment]
Baritone depends on a lot of factors to be as efficient as possible. It's rare to start it in the same spot and take the same path
