### ISSUE TITLE
Adding Baritone API Forge to a Forge mod

### ISSUE THREAD

**Issue by DrunkShulker** [cabaletta/baritone#1952]
## Adding Baritone API Forge to a Forge mod
I'm creating a Forge mod that uses Baritone API Forge. I got the API  working.. partially. The problem is that whenever I try to use any Baritone method that takes a parameter with it's type defined in `net.minecraft….`, the following happens:

![Untitled](https://user-images.githubusercontent.com/67510976/90338391-f5aba280-dff1-11ea-989b-e7edfb1fe4d9.png)
In this example, BlockPos is not recognized when used with Baritone method.

I have tried different versions of Forge and Baritone API Forge and this same problem seems to appear every time. I think the problem has something to do with my dependencies but I have no idea what it is. Any thoughts?

### Dependency in build.gradle:
![Untitljed](https://user-images.githubusercontent.com/67510976/90338392-f6dccf80-dff1-11ea-9dc9-c40345a36eba.png)

-Drunk

**Comment by dominikaaaa** [comment]
Baritone uses BetterBlockPos, it's own BlockPos implementation.

**Comment by DrunkShulker** [comment]
@dominikaaaa I know BetterBlockPos, but it's not the case here. See the [documentation](https://baritone.leijurv.com/baritone/api/process/IBuilderProcess.html) for IBuilderProcess. The BlockPos used in there is `net.minecraft.util.math.BlockPos`

I would like to point out that BlockPos is not the only class producing this problem. Anything that comes from `net.minecraft...`
package does the same thing.

I appreciate your answer but this issue is certainly not closed.

**Comment by dominikaaaa** [comment]
That's an issue on your end then. Idk, invalidate your cache and try again

**Comment by DrunkShulker** [comment]
I still don't know what the problem was. I ended up copying parts of KAMI Blue's buildscripts & workspace structure and got it working.

If someone knows how to do this properly, please make a tutorial as it will probably help a lot people!:)

-Drunk

**Comment by dominikaaaa** [comment]
you could've like read the tutorial but okay

**Comment by Tragafantas** [comment]
> I still don't know what the problem was. I ended up copying parts of KAMI Blue's buildscripts & workspace structure and got it working.
> 
> If someone knows how to do this properly, please make a tutorial as it will probably help a lot people!:)
> 
> -Drunk

Yeah dont expect much cuz this community is toxic

**Comment by Tragafantas** [comment]
> I still don't know what the problem was. I ended up copying parts of KAMI Blue's buildscripts & workspace structure and got it working.
> 
> If someone knows how to do this properly, please make a tutorial as it will probably help a lot people!:)
> 
> -Drunk

Yeah dont expect much cuz this community is toxic

**Comment by dominikaaaa** [comment]
??? what

**Comment by ThermalDig62530** [comment]
Hold up, BARTENDER
