### ISSUE TITLE
is there a way to have it build where you want and not the best location

### ISSUE THREAD

**Issue by fsdfsjdlfksjdflksdj** [cabaletta/baritone#1953]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by fsdfsjdlfksjdflksdj** [comment]
?

**Comment by dominikaaaa** [comment]
With as much detail as possible, describe your question and what you may need help with.

**Comment by Tragafantas** [comment]
> With as much detail as possible, describe your question and what you may need help with.

Bro its literally in the title cant you read
