### ISSUE TITLE
how to make baritone build where you want it to and not where it choses to.

### ISSUE THREAD

**Issue by fsdfsjdlfksjdflksdj** [cabaletta/baritone#1954]
is there a way to make baritone build where you want and not where it wants.

**Comment by dominikaaaa** [comment]
Baritone builds wherever you tell it to.

**Comment by Tragafantas** [comment]
> Baritone builds wherever you tell it to.

Please explain more

**Comment by dominikaaaa** [comment]
Baritone will build your schematic wherever you tell it to build your schematic.

**Comment by dominikaaaa** [comment]
Baritone will build particularly your schematic wherever you tell it to mostly build actually your schematic in a for all intents and purposes major way.

**Comment by dominikaaaa** [comment]
Baritone will mostly build particularly fairly your schematic wherever you for all intents and purposes tell it to mostly build actually basically your schematic in a for all intents and purposes sort of major way.

**Comment by Tragafantas** [comment]
> Baritone will build your schematic wherever you tell it to build your schematic. 

Bruh but where do I set the location then if I have to tell him the location

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/90434010-c1d88780-e09a-11ea-9198-46c192b75859.png)
from the [**FAQ**](https://github.com/cabaletta/baritone/blob/master/USAGE.md)

**Comment by dominikaaaa** [comment]
you don't have to provide a location... if you don't it will use wherever you're standing
