### ISSUE TITLE
Question: How do you set up minecraft 1.16?

### ISSUE THREAD

**Issue by TFTWPhoenix** [cabaletta/baritone#1955]
## What do you need help with?
I'm building baritone on Ubuntu Linux using ./gradlew build. I want to know how to make it use a newer version of mc than 1.12.2.
If I change:
minecraft {
    version = '1.12.2'
    mappings = 'stable_39'
    tweakClass = 'baritone.launch.BaritoneTweaker'
    runDir = 'run'

    // The sources jar should use SRG names not MCP to ensure compatibility with all mappings
    makeObfSourceJar = true
}
in build.gradle to:
minecraft {
    version = '1.16.2'
    mappings = 'stable_39'
    tweakClass = 'baritone.launch.BaritoneTweaker'
    runDir = 'run'

    // The sources jar should use SRG names not MCP to ensure compatibility with all mappings
    makeObfSourceJar = true
}
It errors out and says it can't find MCP for that version. How do I use Minecraft 1.16 with baritone?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
> It errors out and says it can't find MCP for that version.

Well MCP `stable_39`doesn't exist for 1.16.2.... and that's not an issue with Baritone

You shouldn't be using MCP clients, they're against Mojangs EULA and unsupported here. 

Here is a list of MCP mappings http://export.mcpbot.bspk.rs/

**Comment by CDAGaming** [comment]
Further more, you do realize there are other branches in this repo for the newer mc versions right?

*And also that you would be changing 100s of files for a 1.12.x to 1.16.x jump, not just build.gradle*

**Comment by TFTWPhoenix** [comment]
> 
> 
> Further more, you do realize there are other branches in this repo for the newer mc versions right?

I had not realized.
Thanks for your help!
