### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class baritone.api.BaritoneAPI

### ISSUE THREAD

**Issue by P3rZ3r0** [cabaletta/baritone#1957]
## What do you need help with?
I tried the baritone api and the unobfuscated version for my client, both put them in my dependencies in my project structure and everytime I try to do anything with baritone it gives me this error Caused by: java.lang.NoClassDefFoundError: Could not initialize class baritone.api.BaritoneAPI
My client is running on 1.12.2

**Comment by P3rZ3r0** [comment]
and so I am guessing there isn't a way to get baritone without gradle

**Comment by CDAGaming** [comment]
-_-

**Comment by dominikaaaa** [comment]
No. Stop breaking Mojang's EULA

**Comment by dominikaaaa** [comment]
It's possible but we're not helping you with it.
