### ISSUE TITLE
@mine missing ores

### ISSUE THREAD

**Issue by svember** [cabaletta/baritone#1965]
I just started using fabritone with aristois and I type @mine gold_ore and it begins pathing. But then I noticed it is frequently leaving ores behind. I stop the program and go mine them and they are always perfectly fine to mine. Is this a known bug or setting I can adjust or something?

**Comment by CDAGaming** [comment]
Which mc version?

**Comment by svember** [comment]
1.16.1

**Comment by TonyDangermouse** [comment]
I’ve experienced something similar in 1.15.2, usually happens in caves

**Comment by CDAGaming** [comment]
@dominikaaaa You can close this as op is using a now unsupported version of fabritone that I wont provide support for due to its prior instability. Please use the 1.16.2 version.
