### ISSUE TITLE
An extra @Sel command to prioritize a certant block while using @sel cleararea. It goes to that block first. Then starts clearing the rest.

### ISSUE THREAD

**Issue by DamOnlyDC** [cabaletta/baritone#1966]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

This would make us be able to use the addon mod for clearing areas while afk but also first getting the important blocks out of the way.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
@sel targetblock ancient_debris, nether_gold_ore(An example). You can add multiple blocks so it first gets ancient_debris then nether_gold_ore. Then the rest of the area.
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
My personal reasoning is for a server i am playing which has certant rare blocks which i wanna mine first. And then the rest. I've tried using AutoCommand to mine both but it does not work propperly. A reasoning for the public is so they can use the @sel cleararea for survival mining. Instead of using @mine which leaves a very unnatural tunnel you can use this to mine the diamonds then clear the area to make it look normal.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You should suggest an extra `#sel` not `@sel`. If you want to insist on the `@` then go to the fabritone repo please.
Also you can do this by running `#sel replace <someBlock> air` before running `#sel cleararea`

**Comment by RealIndrit** [comment]
Or just use legit mining with correct y level settings added

**Comment by dominikaaaa** [comment]
Yea lmao.
