### ISSUE TITLE
implement #win

### ISSUE THREAD

**Issue by xCjay** [cabaletta/baritone#1968]
## Describe your suggestion
It would simply beat the game.

## Settings
Speedrun/Normal

## Context
Have it do the steps to beat the game. Get diamonds, Kill endermen, make a portal, kill blazes, make ender eyes, goto dungeon, open portal, kill dragon.

Also you could showcase that your bot can beat the game. if it can beat the game, then it can almost do anything. 'almost'

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Justgamer101** [comment]
> ## Describe your suggestion
> It would simply beat the game.

https://github.com/gaucho-matrero/altoclef
