### ISSUE TITLE
Include special-drop blocks on #mine (amount of blocks) (block).

### ISSUE THREAD

**Issue by anumy** [cabaletta/baritone#1976]
- Description
For those who don't know you can mine a certain amount of blocks with #mine (block amount) (block), for example, if you put #mine 2 dirt, it will mine two dirt blocks. But if you do it with blocks like diamond ores, it wouldn't work because when you break it gives diamond, not the ore. That's why I offer this option, that Baritone is able to detect this kind of blocks when executing this command.

- Setting
I think the best command we can apply in the configuration would be something similar to, #includeSpecialBlocks or something shorter. In case someone comes up with a shorter variation, put it in this post.

- Context
It would help a lot to people who want to automate the tasks when using the bot, and so they would have much more free time to do other things while Baritone does its job for them.

- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This already happens by default.

**Comment by anumy** [comment]
> 
> 
> This already happens by default.

Not true, I've already tried on different versions and just mines infinitely.

**Comment by scorbett123** [comment]
What versions, I have tested 1.16.2 and 1.12.2, and what precise command are you doing?

**Comment by anumy** [comment]
> 
> 
> What versions, I have tested 1.16.2 and 1.12.2, and what precise command are you doing?

I've tested 1.16.2, 1.16.1, 1.15.2, 1.14.4 & 1.12.2. The command #mine (amount of blocks) (block).

**Comment by scorbett123** [comment]
What block are you testing with?

**Comment by scorbett123** [comment]
And what is the result of #modified

**Comment by anumy** [comment]
> 
> 
> What block are you testing with?

Diamond ore & stone.

**Comment by anumy** [comment]
> 
> 
> And what is the result of #modified

What's that command?

**Comment by scorbett123** [comment]
It just shows modified settings.

**Comment by anumy** [comment]
Let me check.

**Comment by anumy** [comment]
allowInventory true
allowDiagonalDescend true
allowDiagonalAscend true
allowParkour true
allowParkourPlace true
prefix @
buildInLayers true
legitMine true

**Comment by dominikaaaa** [comment]
CNR, works fine for me.
