### ISSUE TITLE
ERROR [BARITONE] IMPACT 4.9.1!!!

### ISSUE THREAD

**Issue by 0uth** [cabaletta/baritone#1979]
![image](https://user-images.githubusercontent.com/69104021/91413792-5047c880-e854-11ea-9511-892bc89446d2.png)
Hello,I entered #build in my name.schemes and it throws an error:Couldn't load the schematic make sure to use the full name,including the extension (You can also view a screenshot)!!!
HELP ME!!!
The first time I was able to build a scheme,but the second time nothing works!

**Comment by Tragafantas** [comment]
Just change the name of the schematic to a more writable name

**Comment by dominikaaaa** [comment]
Řekl jste to špatně
