### ISSUE TITLE
how to mine with chosen item at the chosen item slot

### ISSUE THREAD

**Issue by KendalPehlivan** [cabaletta/baritone#1980]
so what I need is to mine with a chosen pickaxe that I cannot put in the first slot but whenever it starts to mine things if there is no useful items baritone directly jumps to the first item slot how can I change that

**Comment by dominikaaaa** [comment]
`#disableAutoTool true`

**Comment by RealIndrit** [comment]
Actually, it depends on the usage, if you only use disableAutoTool it will repath depending on tool used, meanwhile if you enable assumeExternalAutoTool it will actually assume best tool being used and path normally while using the chosen tool (if disableAutoTool is enabled)

**Comment by KendalPehlivan** [comment]
This just gives me errors, if I write it without baritone in front of it,
it says command not found. If i right it with baritone in front of it it
says unexpected integer

27 Ağu 2020 Per, saat 20:09 tarihinde Dominika <notifications@github.com>
şunu yazdı:

**Comment by RealIndrit** [comment]
update baritone

**Comment by dominikaaaa** [comment]
I don't believe there's a prebuilt release with this option yet. I'll probably switch KAMI Blue to build master.

**Comment by dominikaaaa** [comment]
Or you can just build a forge jar yourself
