### ISSUE TITLE
baritone incompatible with SevTech Ages modpack, error 255

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1982]
## Some information
Operating system: manjaro btw
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
Minecraft version: 1.12.2
Baritone version: any
Forge mods (if used): [SevTech Ages modpack](https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/3038158)

## Exception, error or logs
error 255
[latest.log](https://github.com/cabaletta/baritone/files/5139006/latest.log)

## How to reproduce
add baritone
run minecraft
crash on step 1
cwy a little
wipe tears in anger of lack of stupid pearls in the game generation
duplicate this issue

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
> java.lang.RuntimeException:  java.lang.NoSuchFieldException: processor

try uninstalling the modpack, that should fix the issue

**Comment by TheK0tYaRa** [comment]
so no suggestions of how to fix it without breaking down the modpack?

**Comment by TheK0tYaRa** [comment]
i've tried installing mixins-0.8-processor and it didn't work. mixins-0.8 too.

**Comment by TheK0tYaRa** [comment]
Modpack works by itself.

**Comment by dominikaaaa** [comment]
Baritone uses mixins 7.11

Unless you find out exactly which mod is causing it then it's pretty hard to help with that

**Comment by SevensRequiem** [comment]
Any fix yet?

**Comment by Pingger** [comment]
Downgrade the JustEnoughIds Mod to Build `…-48`
