### ISSUE TITLE
Ability to set a bounding bot for the farm feature

### ISSUE THREAD

**Issue by ColdHulkmask** [cabaletta/baritone#1983]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
i want the .b farm feature to be able to set a bounding box similar to the sel commands like .b farm x y x to x y z
or the box can be set before hand like the .b sel pos1 command

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
allowoutofboundingbox
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
This will make it easier when other farms are nearby and it in render distance so baritone wont target those farms so my friends wont kill me 0w0
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by TexRexTex** [comment]
you could combine it with .b sel maybe

**Comment by ColdHulkmask** [comment]
thats what i said

**Comment by dominikaaaa** [comment]
Duplicate
