### ISSUE TITLE
how to use schematics in impact forge

### ISSUE THREAD

**Issue by superdestroyer7** [cabaletta/baritone#1984]
i want to use schematics but i use tlauncher so i use the forge version of impact so i want to use  
schematics help pls

**Comment by berrely** [comment]
We don't offer support for TLauncher

**Comment by berrely** [comment]
Also this was not a suitable question for the GitHub repository.

**Comment by superdestroyer7** [comment]
so what do i do

**Comment by berrely** [comment]
I suggest you join the Discord: https://discord.com/invite/yA7sQD

**Comment by superdestroyer7** [comment]
ok

**Comment by dominikaaaa** [comment]
tlauncher is not supported.
