### ISSUE TITLE
Added disable auto-tool in auto-mine

### ISSUE THREAD

**Issue by Slhsmile** [cabaletta/baritone#1985]
On prison servers, when farming beacons, you can switch to 1 slot where the backpack is located (example: mcprison.com), which cannot be broken by beacons. I would like to see an option to disable automatic selection of tools when enabled auto-mine

**Comment by berrely** [comment]
Turn of autotool?

**Comment by RealIndrit** [comment]
Toggle setting “disableAutoTool” and I would probably also toggle “assumeExternalAutoTool”

**Comment by Slhsmile** [comment]
> Toggle setting “disableAutoTool” and I would probably also toggle “assumeExternalAutoTool”

how "toogle setting disableAutoTool"?

**Comment by RealIndrit** [comment]
depending on what version you are using, just do "#disableAutoTool" in chat

**Comment by Slhsmile** [comment]
> depending on what version you are using, just do "#disableAutoTool" in chat

not working :/

**Comment by dominikaaaa** [comment]
did you completely ignore what I told you here? https://github.com/kami-blue/client/issues/1268
