### ISSUE TITLE
How to use baritone in a third-party launcher

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#1986]
I am using the HMCL launcher, but I cannot add baritone to my 1.16.1 client
[HMCL](https://github.com/huanghongxun/HMCL/releases)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
https://minecraft.net/download

**Comment by djkcyl** [comment]
I have an official account, but I need to use a third-party client instead of the official client

**Comment by dominikaaaa** [comment]
The same way you would use it with the official one.

**Comment by djkcyl** [comment]
ok
