### ISSUE TITLE
schematic file maker

### ISSUE THREAD

**Issue by somedude21** [cabaletta/baritone#1989]
## Describe your suggestion
It would be cool if the sel tool could MAKE schematic files instead of building

## Context
say you make a house in creative and you go onto a server and build on there all in baritone but that's just a suggestion 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
gee I wonder what schematica is for

**Comment by somedude21** [comment]
gee i wonder why i specified if it would be cool if it was all in baritone

**Comment by dominikaaaa** [comment]
see my above comment
