### ISSUE TITLE
How can i slow baritone auto build bot.cause it gets detected by the anticheat.

### ISSUE THREAD

**Issue by RavingLoon** [cabaletta/baritone#1990]
Please add a function where we can slow the auto build bot..

**Comment by dominikaaaa** [comment]
https://baritone.leijurv.com/baritone/api/Settings.html

**Comment by skerit** [comment]
Is it the `slowPath` setting you're referring to? That seems to pause the player for a very long time when a new path needs to be found. It also doesn't solve the player looking around too fast, right?

Also, I see antiCheatCompatibility is on by default in Impact, and the `randomLooking` setting is also `0.01` by default, yet I'm still getting kicked by AAC. Head movement still seems very, very fast.

**Comment by dominikaaaa** [comment]
Head movement is fast, yes
