### ISSUE TITLE
How to load schematics

### ISSUE THREAD

**Issue by SableRojo** [cabaletta/baritone#1993]

**Comment by SableRojo** [comment]
> #build blah.schematic

but where do i load it?
i created a schematic folder in .minecraft and doesn't  work

**Comment by scorbett123** [comment]
have you placed your schematic in that folder?
If you have just use that command, with blah being replaced by the name of your schematic then baritone will start building it.

**Comment by SableRojo** [comment]
> have you placed your schematic in that folder?
> If you have just use that command, with blah being replaced by the name of your schematic then baritone will start building it.

nope, it says schematic not found
![image](https://user-images.githubusercontent.com/62173050/92105832-bba91180-ede3-11ea-948f-bcf231b9fd84.png)
![image](https://user-images.githubusercontent.com/62173050/92105853-c8c60080-ede3-11ea-864c-c897849e0167.png)

**Comment by scorbett123** [comment]
have you named the folder schematics, or just schematic. It should be named schematics.

**Comment by SableRojo** [comment]
> have you named the folder schematics, or just schematic. It should be named schematics.

schematic

**Comment by scorbett123** [comment]
rename it to schematics then it should work

**Comment by SableRojo** [comment]
it worked thanks!
