### ISSUE TITLE
Error when i do mine command.

### ISSUE THREAD

**Issue by RogbonolYT** [cabaletta/baritone#1997]
Hey, im using Meteor Client with fabritone, i was doing some tests and when i tried to do the command it says this in the log:

https://pastebin.com/3X63AUjp <--- The error

I hope someone can help me with this cause i need those diamonds! ;)

**Comment by scorbett123** [comment]
Fabritone is unsupported.

**Comment by RogbonolYT** [comment]
Oh ok thanks for the support!
