### ISSUE TITLE
Why doesn't baritone break blocks to go somewhere? And put them back

### ISSUE THREAD

**Issue by ThereIsNoChance** [cabaletta/baritone#1998]
A lot of times baritone cant get to a certain place because it cant break blocks to get there, has anyone coded baritone to make it break the blocks (and place it back later) to get to where it needs to be?

**Comment by dominikaaaa** [comment]
#allowBreak

**Comment by scorbett123** [comment]
>  break the blocks (and place it back later) 

if you also set backfill to true then it will replace the blocks back behind you.
