### ISSUE TITLE
no works mod

### ISSUE THREAD

**Issue by BurnSkull** [cabaletta/baritone#1999]
My mod stupidly does not work for me, I reinstalled minecraft, and reinstalled the mod different versions. Maybe a problem in the forge? NOT! I've played with it before, worked, great mod! But recently under the same circumstances, I launch the game, but nothing works, not even #help. It does not give any error to the chat, just emptiness.
![Безымянный](https://user-images.githubusercontent.com/70850367/92328265-1a7ebd00-f068-11ea-9b20-6e13284551e2.png)

**Comment by dominikaaaa** [comment]
You have to install Baritone in order for Baritone commands to work.

**Comment by BurnSkull** [comment]
> Для работы команд Baritone необходимо установить Baritone.


Well, I installed, even decided 5 baritone (different versions) at once, it did not work.

**Comment by dominikaaaa** [comment]
Install Impact client or KAMI Blue, which have Baritone included, if you don't understand how to install it standalone

**Comment by ZacSharp** [comment]
If you are using forge 1.15.2, did you also install [MixinBootstrap](https://github.com/LXGaming/MixinBootstrap/releases/download/v1.0.2/MixinBootstrap-1.0.2.jar)?

**Comment by c0d3rb0y** [comment]
lmao his grammar is the crap here look at the title
