### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by RealIndrit** [cabaletta/baritone#2000]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
poggers

**Comment by RealIndrit** [comment]
Unironically the most complete suggestion

**Comment by SpicyBigGithub** [comment]
woah
