### ISSUE TITLE
Crap mod

### ISSUE THREAD

**Issue by BurnSkull** [cabaletta/baritone#2001]
I asked for help with the mod, it didn't work for me. Showed proofs. They answered me: "For the mod to work, you had to install the mod." YES? Wow, I didn't know! I thought I needed to spell some kind of spell! Wow! This is logical! And now the reason why I'm writing this: I just want to crap for "help".

**Comment by uwuplant** [comment]
which MC and baritone version are you using?

**Comment by BurnSkull** [comment]
> какую версию MC и баритона вы используете?


I tried all the last, not one does not work for me.

**Comment by uwuplant** [comment]
Какую версию Minecraft вы используете? (1.12.2?)
(used translator for this)

**Comment by BurnSkull** [comment]
> Какую версию Minecraft вы используете? (1.12.2?)
> (Для этого использовал переводчик)

1.15.2

**Comment by BurnSkull** [comment]
> > Какую версию Minecraft вы используете? (1.12.2?) 
> > (Для этого использования переводчик)
> 
> 1.15.2

а бро я тоже русский.

**Comment by uwuplant** [comment]
Я знаю, это не так. Я использую переводчика, чтобы облегчить тебе задачу.
Попробуйте следовать руководству в описании этого видео.
https://youtu.be/j1qKtCZFURM

**Comment by BurnSkull** [comment]
> Я знаю, это не так. Я использую переводчика, чтобы облегчить тебе задачу.
> Попробуйте следовать руководству в описании этого видео.
> https://youtu.be/j1qKtCZFURM

![Безымянный](https://user-images.githubusercontent.com/70850367/92329012-58321480-f06d-11ea-8857-ef5b74c29cf7.png)
 не сработало, ну мод вообще не работает.

**Comment by scorbett123** [comment]
какую версию майнкрафта вы используете?

**Comment by dominikaaaa** [comment]
Решение уже комментировалось в #1999.
