### ISSUE TITLE
Auto refill inventory

### ISSUE THREAD

**Issue by BramPlayzz** [cabaletta/baritone#2002]
Is there a way to auto refill the inventory of the baritone bot? I want to build a 161x161 dirt layer for a big farm. Or what's the easiest way to do this?

**Comment by ZacSharp** [comment]
It does not refill it's inventory automatically.
If you are able to do it, you can use baritones API to add that feature yourself, otherwise you will simply need to manually refill your inventory (or let someone else do the work :smile:).
For the dirt layer:
1. select the area
2. use `sel fill dirt`

**Comment by BramPlayzz** [comment]
Ok thanks, I might have an idea. I have some experience with a other mod to make scripts (macro mod) and i could let that take the dirt and then let baritone build again?

**Comment by dominikaaaa** [comment]
As long as it runs #pause and #resume, sure

**Comment by ZacSharp** [comment]
With java it is probably easier because you can hook into baritone directly bot a macro mod should also work

**Comment by BramPlayzz** [comment]
I don't really have any experience with java.

**Comment by ZacSharp** [comment]
Then use your macro mod
As @dominikaaaa said you can `#pause` and `#resume` if you don't need baritone to get the blocks.
If you need it (e.g. to go to a chest) then use `#cancel` to stop, `#goto` to go to your chest and `#sel fill` to restart builing.

**Comment by ZacSharp** [comment]
Also check out #1706. I don't know if it is usable but if it is, it is everything you need (assuming you have shulkerboxes)

**Comment by BramPlayzz** [comment]
Thanks!

**Comment by BramPlayzz** [comment]
Don't have shulker boxes tho, im trying this on hypixel skyblock (1.8)
