### ISSUE TITLE
unhandled error whenever #mine is used

### ISSUE THREAD

**Issue by TeslaCoil69** [cabaletta/baritone#2007]
## Some information
Operating system:windows 10
Java version:1.8.0_261 64 bit
Minecraft version:1.12.2
Baritone version:baritone-api-forge-1.2.14 
Forge mods (if used): schematica and lunatrius core, pixelmon 8.0.2, advanced macros 7.9.0+

#

[latest.zip](https://github.com/cabaletta/baritone/files/5197914/latest.zip)

## How to reproduce
run #mine iron_ore

## Modified settings
none, literally fresh install after had the same issue with earlier

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Try without mods

**Comment by TeslaCoil69** [comment]
advanced macros was causing the issue, thank you guys!
