### ISSUE TITLE
json version for 1.16.x?

### ISSUE THREAD

**Issue by MakeLord95** [cabaletta/baritone#2008]
## What do you need help with?
I'm trying to install baritone with x-ray and optifine and I can't seem to find the json version for 1.16.x versions.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
https://www.youtube.com/watch?v=_4eVJ9Qz2J8

**Comment by MakeLord95** [comment]
Thanks
