### ISSUE TITLE
Baritone pathfinding visuals gone when using optifine with a shader

### ISSUE THREAD

**Issue by MakeLord95** [cabaletta/baritone#2011]
## Some information
Operating system: Windows 10
Java version: v8 u261
Minecraft version: 1.16.2
Baritone version: 1.6.1
Other mods: Optifine 1.16.2 HD U G3
Shaderpack used: [BeyondRelief VanillaReborn](https://www.curseforge.com/minecraft/customization/beyondbelief-vanilla-reborn/files/3046796)

## Exception, error or logs
[latest.log](https://pastebin.com/QXvJG0sL)

## How to reproduce
1. Install optifine
2. Install baritone json version with optifine in it [My json with optifine installed](https://pastebin.com/zxFnam40)
3. Download and select shaderpack (I used BeyondBelief VanillaReborn)
4. Load into singleplayer world
5. Use any baritone command that should display the pathfinding visuals (I used #mine smoker, since it was the easiest)

## Modified settings
To get the modified settings run `#modified` in game
- None

## Extra
[Pictures of the issue](https://imgur.com/a/qnqURq5)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by phyyyl** [comment]
Why was the issue closed?

**Comment by MakeLord95** [comment]
I had a network error while submitting the bug report, so it submitted the report twice. See #2010
