### ISSUE TITLE
Boundaries for auto-farming

### ISSUE THREAD

**Issue by Tofuine** [cabaletta/baritone#2012]
I want to auto farm in a server, but I cannot modify/create/destroy blocks in a plot that is close to mine. I have a farm, however, after a while it just automatically goes to my neighbor's farm and tries to destroy it but it is pointless because I cannot destroy things there. Is there any way I can set a boundary so that I auto farm in that area only.

**Comment by ZacSharp** [comment]
No, there is no way to set a boundary.
Depending on your farm you can select it and use `#sel replace <crop> air` and `#sel replace air <crop>` instead (won't pickup items though)
