### ISSUE TITLE
Update README.md WWE integration badge

### ISSUE THREAD

**Issue by omninope** [cabaletta/baritone#2013]
## Describe your suggestion
The WWE mod got renamed to Inertia. I suggest updating the integration badge name to Inertia and the website to https://inertiaclient.com/.
Reference: https://www.reddit.com/r/minecraftclients/comments/i9mxpd/wwe_download/g1g2w8p/?context=3

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Don't they violate Baritone's license by not releasing their custom remapped version? lmfao

**Comment by CDAGaming** [comment]
Hehe Inertia DMCA go brrr lol

**Comment by 0-x-2-2** [comment]
> Don't they violate Baritone's license by not releasing the source to their custom remapped version? lmfao

The source is in this repo, they have no obligations to release any custom tools they have created to change the officially released compiled binaries from leijurv from using mojang names to yarn.

**Comment by l1ving** [comment]
# :moyai:

**Comment by scorbett123** [comment]
The badge has been completely removed.
