### ISSUE TITLE
Problem building a cactusfarm schematic.

### ISSUE THREAD

**Issue by manu1002** [cabaletta/baritone#2022]
When trying to build a cactusfarm using a schematic, baritone keeps replacing the cactus below me. Known error? I couldn't find a solution. Video: https://streamable.com/kcy4kb

**Comment by dominikaaaa** [comment]
1. You're in creative
2. Baritone can't find a valid path 
3. Just restart and try again

**Comment by manu1002** [comment]
Tried it in Singeplayer. Doesn't work either. The cactus below me still gets broken.

**Comment by dominikaaaa** [comment]
read the other 2 points

**Comment by manu1002** [comment]
What can i do about point 2? I restarted multiple times with multiple schematics.

**Comment by dominikaaaa** [comment]
I highly doubt all your schematics have the exact same arrangement of cacti in them

**Comment by manu1002** [comment]
I have the same problem with different layouts. Is it possible that it breaks cactusses below me to prevent me from getting damage? Even when building a 1x1 cactus farm tower it doesnt work.

**Comment by dominikaaaa** [comment]
I guess make a bug report detailing that baritone doesn't handle cacti well
