### ISSUE TITLE
Forge standalone for 1.12 does not work

### ISSUE THREAD

**Issue by Claw76** [cabaletta/baritone#2023]
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12
Baritone version: 1.2.14
Forge mods: AstroBlock-modpack

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/5247801/debug.log)
Minecraft Launcher says Exit code:0

## How to reproduce
installed AstroBlock-modpack with Twitch
added baritone-forge-standalone-1.2.14 into the mods folder of the AstroBlock-modpack and started the game
(also tried it with MixinBootstrap as an addition, same result)

**Comment by dominikaaaa** [comment]
1.2.14 is only for the 1.12.2 version of minecraft

**Comment by Claw76** [comment]
I'm truly sorry for this stupid mistake on my side. It is, of course version 1.12.2

**Comment by dominikaaaa** [comment]
idk, try without other mods
