### ISSUE TITLE
Bartione won't change changes made in settings file (like blockstoavoid or blockstoavoidbreaking)

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#2026]
Everytime i start the game (fabric with baritone / fabritone 1.6.2) it seems to delete my changes and revert back to another state of that file. I save the file everytime i close it but nothing works. Anything i can do to make it keep the changes and apply them ingame? Also of course there's no error coming up otherwise i would have attached it.

**Comment by dominikaaaa** [comment]
Fill out the template

**Comment by Tendas240** [comment]
> Fill out the template

i did now

**Comment by dominikaaaa** [comment]
Doesn't look filled out to me 
![image](https://user-images.githubusercontent.com/17222512/93670625-b649f900-fa6a-11ea-8a73-24a246c26d81.png)
