### ISSUE TITLE
Fabritone blocksToAvoid won't work

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#2027]
## Some information
Operating system: Windows 64 Bit
Java version: java 8 update 251
Minecraft version: 1.16.2
Baritone version: Fabritone 1.6.2
Forge mods (if used): i use fabric (with inertia utility client, inventoryprofiles mod, optifabric)

## Exception, error or logs
There are no errors. If I add the line "blocksToAvoid (name),(name)" it obviously doesn't recognize this line and automatically deletes it after i started the game.

## How to reproduce
- going to the settings file in the baritone folder in ".minecraft"
- adding the line "blocksToAvoid" with some id names because somehow this line doesn't exist already
- starting the game
- ingame using the chat: *prefix*blockstoavoid
- it doesn't show any blocks i added but it does recognize the command ingame

## Modified settings
- acceptablethrowawayitems
- allowdiagonalascend
- allowdiagonaldescend
- allowdownward
- allowparkour
- allowparkourplace
- allowwalkonbottomslab
- avoidance
- blockbreakadditionalpenalty
- blockplacementpenalty
- blockstoavoidbreaking
- buildertickscanradius
- chatcontrol
- colorblockstoplace
- colorblockstowalkinto
- colorcurrentpath
- colorgoalbox
- colormostrecentconsidered
- costheuristic
- exploreforblocks
- exploremaintainy
- freelook
- maxcachedworldscancounts
- maxfallheightbucket
- prefix
- selectionlinewidth
- simplifyunloadedycoord
- worldexploringchunkoffset

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This is a known bug in Baritone

**Comment by Tendas240** [comment]
> This is a known bug in Baritone

didnt have this bug in previous versions of baritone and any other version of baritone/fabritone i was using

**Comment by dominikaaaa** [comment]
ok

**Comment by Tendas240** [comment]
> ok

so theres no known way to bypass it? no alternative you know maybe? but thanks though

**Comment by dominikaaaa** [comment]
this is the baritone repo
