### ISSUE TITLE
Single Layer of Schematic

### ISSUE THREAD

**Issue by Zenot1cc** [cabaletta/baritone#2031]
Is there a way for me to build a schematic one layer at a time? i only need the bottom layer of a schematic, and i cannot find away to do this?

**Comment by dominikaaaa** [comment]
`#buildInLayers` and then cancel once layer is done

**Comment by Zenot1cc** [comment]
> `#buildInLayers` and then cancel once layer is done

i do this and it returns "unable to do it. Pausing

**Comment by dominikaaaa** [comment]
Then it's unable to do it
