### ISSUE TITLE
How can I upgrade the default Impact Baritone Version to the newest one?

### ISSUE THREAD

**Issue by BMax-sudo** [cabaletta/baritone#2038]
## What do you need help with?
I want to upgrade to the newest baritone version, but I am using the impact client. I read in the SETUP.md that to replace out Impact 4.5's Baritone build with a customized one I have to build Baritone as shown above. How do I "build" Baritone? And where is the dist/ folder?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Building instructions are here https://www.github.com/cabaletta/baritone/tree/master/SETUP.md
