### ISSUE TITLE
Minecraft Loading issue

### ISSUE THREAD

**Issue by Whiskyleach** [cabaletta/baritone#2046]
Error: java.lang.NoClassDefFoundError: Could not initialize class baritone.api.BaritoneAPI 

Please Help

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)
