### ISSUE TITLE
Rotate build

### ISSUE THREAD

**Issue by CUPZYY** [cabaletta/baritone#2047]
Is there a way to rotate the build i am going to build with #build?

**Comment by l1ving** [comment]
Yes. Read the docs

**Comment by CUPZYY** [comment]
what about without schematica?

**Comment by l1ving** [comment]
Yes you can iirc

**Comment by CUPZYY** [comment]
Do you know how?

**Comment by l1ving** [comment]
https://github.com/Lunatrius/Schematica/wiki/Controlling-a-loaded-schematic

**Comment by CUPZYY** [comment]
but without schematica

**Comment by l1ving** [comment]
RTFM

**Comment by CUPZYY** [comment]
bruh, it does not say anything about that in usage.md

**Comment by CUPZYY** [comment]
bruh, it doesn't say anything about that

**Comment by l1ving** [comment]
Well that answers your question. This isn't a Baritone question in the first place.

**Comment by CUPZYY** [comment]
Wdym with "this isn't a Baritone question"? It is literally only about Baritone.

**Comment by l1ving** [comment]
Well it's not a Baritone feature to rotate schematics.

**Comment by CUPZYY** [comment]
ok

**Comment by CUPZYY** [comment]
ok
