### ISSUE TITLE
baritone stack some times which make afk rly anoying.

### ISSUE THREAD

**Issue by natan515** [cabaletta/baritone#2048]
*Operating system: not sure what it is

*Java version: 8
*Minecraft version: 1.12.2
*Baritone version: the lastest 
*Forge mods (if used): normal forge...

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
*make so baritone wont stop lol, we cant afk like this.

the start of baritone file:///C:/Users/speed/Desktop/ice_video_20201002-141407.webm
the end of it, and how to start it back.
file:///C:/Users/speed/Desktop/ice_video_20201002-142717.webm
it stop for a sec for no resone... and it come back when i moving which make afk so anoying!!!!! i would like you to fix it have a good day.

**Comment by l1ving** [comment]
I don't really understand, can you attach a video of the issue?

**Comment by natan515** [comment]
I did , copy the links ive send there

**Comment by l1ving** [comment]
No you didn't

**Comment by natan515** [comment]
[Uploading ice_video_20201002-142717 (2).zip…]()

**Comment by Scattered-Faith** [comment]
You posted a Windows recognized path to a local file on your computer instead of uploading to a file hosting service. We can't help.

**Comment by UltraBlackLinux** [comment]
If you cant use your stupid OS, dont ask for help. *salt*

**Comment by l1ving** [comment]
Sent video on discord, duplicate
