### ISSUE TITLE
Mouse/Movement Issue

### ISSUE THREAD

**Issue by kyllianlissens** [cabaletta/baritone#2050]
## Some information
Operating system: Windows 10
Java version: 1.8
Minecraft version: 1.16.3
Baritone version: 1.6.1 (Downloaded source.zip of latest release)
Forge mods (if used): /

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[debug.log](https://github.com/cabaletta/baritone/files/5320487/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/5320488/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Download source, build forge version in gradle, load in latest forge. 
Type #mine oak_log 
it'll start moving but no mouse rotation

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by kyllianlissens** [comment]
Here ya go @l1ving https://youtu.be/hJp2jkAEZsU

**Comment by kyllianlissens** [comment]
@l1ving Did you see it?

**Comment by l1ving** [comment]
Yes

**Comment by l1ving** [comment]
The issue is with a jar you built yourself?

**Comment by kyllianlissens** [comment]
Yes @l1ving

**Comment by l1ving** [comment]
See #2028

**Comment by kyllianlissens** [comment]
How do I run it in client and they refer to a file that is a nonshit refmap but I don't have that file
@l1ving

**Comment by l1ving** [comment]
You can find the not shitty refmap inside the precompiled binaries of Baritone. You have to replace your compiled jar's refmap with the fixed one. 

Put this inside `fix.bat` and run it lmfao
![image](https://user-images.githubusercontent.com/17222512/95021455-221d8b80-063f-11eb-934a-e2665d24ce01.png)

**Comment by l1ving** [comment]
Or use a better operating system
