### ISSUE TITLE
allowLadder

### ISSUE THREAD

**Issue by InferusAnima** [cabaletta/baritone#2052]
## Describe your suggestion
This function will enable or disable laddering.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
true/false

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
This will add another feature of control baritone's moving and this is useful in some cases.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CelestialStreamer** [comment]
This would be nice, especially for building schematics.

**Comment by scorbett123** [comment]
#allowVines, I believe that this setting should do this.
