### ISSUE TITLE
When creating a custom command, how would I make it use the mine command in it?

### ISSUE THREAD

**Issue by Jeremys556** [cabaletta/baritone#2055]
Title might not be worded well, as I'm somewhat new to Java so this is a bit confusing for me.

My goal is to create a modified version of the #mine (ore).

What I want it to do is mine just like the #mine command, and then when it's inventory is full it will return to coordinates specified in the arguments of the command, deposit items into nearby chests, and repeat. However, I'm not sure how I would make it mine just like the mine command, as im not too sure how it works.

Thank you in advance

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
call the mine command from it
