### ISSUE TITLE
How to get the arguments of the command in the ExampleBaritoneControl.java file

### ISSUE THREAD

**Issue by Jeremys556** [cabaletta/baritone#2056]
I am trying to get the arguments of the commands that the user runs, so I can feed them into other stuff, but can't figure out how to do it. Please provide an example if your able to answer this

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Look at the code
