### ISSUE TITLE
Smooth movements

### ISSUE THREAD

**Issue by AbyssStudios** [cabaletta/baritone#2057]
## Describe your suggestion
Adds a setting to Baritone. The setting makes movements more smooth. These movements could be head movements going to break a block.

## Settings
#set smoothMove [boolean]

## Context
This could add it to make recording with Baritone more suitable to the eye. It also makes the user of Baritone get what is happening more. If Baritone moves its head instantly when it has to mine something, it gets kind of hard to tell what is happening.
(And, I guess, another 'benefit' is making it look less like you are hacking. Now, I hate hacking so I think there are two sides to this argument.)

## Final checklist
- [x] I know how to properly use checkboxes 
- [ ] I have not used any OwO's or UwU's in this issue.
(I can't check this box because there are some right above.)

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
