### ISSUE TITLE
No line tracing

### ISSUE THREAD

**Issue by AbyssStudios** [cabaletta/baritone#2058]
## Describe your suggestion
Enables a setting that turns off the lines that show when you #path.

## Settings
#set linePath [boolean]

## Context
Adding this would make a better personalization option for Baritone.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any anime in this issue.

**Comment by l1ving** [comment]
Damn I wonder what these do
![image](https://user-images.githubusercontent.com/17222512/95230695-33e26880-07d0-11eb-8537-5ba0ce0cd7f0.png)
