### ISSUE TITLE
elytra with auto walk or any thing else that has movment in him.

### ISSUE THREAD

**Issue by natan515** [cabaletta/baritone#2059]
hello, so as I'm pretty sure you know that there is an auto elytra mod, which is open source and I was thinking that it could be awesome if it would be in baritone. I'm thinking about having a commend like #useelytra true or have #elytrawithrockets true #normalelytralfying true, I will explain each and one of the settings I propose. so the first one will tell baritone if he should use elytra in commends like #goto or auto walk, only if the elytra is on the players.  The second one is if he want the elytra to use rockets if he is stuck or want to start his flying easialy (only if he got rockets on him). The third commend is for servers like 2b2t where elytra is patch and you can use a hack for it, it will require that the second commend to be on, and it can look as more lagit flying sometimes. of course im not saying you need to add excatly this but this is just suggestion and ideas. i feel like bariotne is a great thing but it stoped getting upgrades and it doesn't use it full potiontiol. baritone hasn't gotten any update for 1.12.2 for a very long time and I think it can be very useful. ok so now, why you should add it: it can make people to use much more baritone by get him to easialy move with elytras whenever you want and get minecraft to next leavel of automation. thank you very much for reading and i hope you will accapt it and that you will have a beautiful day. Sorry for not having a great english (;

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by natan515** [comment]
oh sorry, I've wrote it for so long lol... I just didn't thought someone olredy suggest it.
