### ISSUE TITLE
1.16.1?

### ISSUE THREAD

**Issue by EXPerience255** [cabaletta/baritone#2062]
## What do you need help with?
I want to use the forge version of Baritone for 1.16.1, but the closest I could find is 1.16.2. Is there any releases or clients for 1.16.1 that allow forge to be used?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Fabritone with multiconnect

**Comment by EXPerience255** [comment]
Doesn't Fabritone use Fabric and not Forge?

**Comment by l1ving** [comment]
Yes it does, that's the entire point

**Comment by ZacSharp** [comment]
> that allow forge to be used?

It's the entire point of fabritone and the reason why it is not an answer to this question

**Comment by EXPerience255** [comment]
I asked if there was a 1.16.1 baritone that can use _forge_, all the mods I want to use with baritone are forge mods.

> Is there any releases or clients for 1.16.1 that allow forge to be used?

**Comment by EXPerience255** [comment]
Wait fabritone uses forge, too? Or am I reading that wrong?

**Comment by EXPerience255** [comment]
Baritone has 1.16.2 forge and not 1.16.1 forge. If I want to use 1.16.1, I have to use fabric. All mods that I want to use Baritone with are 1.16.1 forge mods, not fabric, not 1.16.2.

**Comment by l1ving** [comment]
Then you'll need to build Baritone for outdated versions then

**Comment by EXPerience255** [comment]
ok
