### ISSUE TITLE
Baritone miner for nether ceiling

### ISSUE THREAD

**Issue by Rextus** [cabaletta/baritone#2067]
Hello,

Is it possible for baritone to mine blocks that aren't directly above the player? Say I have a 1 block wide pathway, could baritone mine up to 4 blocks to the left and right of said pathway?

Similarly, is it possible for baritone to mine blocks that are situated at the same level than the block he is currently standing on (but not the one the player is standing on)?

Thanks

**Comment by l1ving** [comment]
Use a custom selection or schematic
