### ISSUE TITLE
Able to drop specific items or junk while it mines.

### ISSUE THREAD

**Issue by Mohammed8339** [cabaletta/baritone#2068]
idk if this is a issue or not, but I want to know if it is possible to make baritone drop specific item that it collects while its mining, like for example I want baritone to drop gravel that it mines while its mining diamonds. is that a already built in command?

**Comment by CesiumCs** [comment]
it's not built in but if you're using Baritone with a client you can use that clients autoeject

**Comment by Mohammed8339** [comment]
oh ok thanks

> it's not built in but if you're using Baritone with a client you can use that clients autoeject

**Comment by l1ving** [comment]
Both Impact and KAMI Blue have AutoEject. The latter has better support afaik, as it (optionally) pauses baritone while ejecting, so baritone doesn't pick it up again

**Comment by Lavaking-da-coder** [comment]
baritone has a auto throwaway thing without a clint needed but i don't know how to mess with it so its good

**Comment by Lavaking-da-coder** [comment]
> it's not built in but if you're using Baritone with a client you can use that clients autoeject

false
