### ISSUE TITLE
Fabric Support Since forge isnt stable very fast

### ISSUE THREAD

**Issue by ApposModding** [cabaletta/baritone#2069]
Can you make barittone for fabric. its more stable than forge and fabric has more mods for 1.16.1+ than forge:
fabric:[](fabricmc.net/use)
download fabric api. pls do this since i run a fabric serv

**Comment by scorbett123** [comment]
Use fabritone.

**Comment by ApposModding** [comment]
uh. but fabrittone doesnt work with wrust.

**Comment by scorbett123** [comment]
Then create an issue on the fabritone repo.

**Comment by l1ving** [comment]
You do realize, vanilla fabritone without any feature patches is just Baritone with Fabric mappings??

**Comment by ApposModding** [comment]
ok. my server was running sodium

**Comment by Mhowser** [comment]
??? sodium is clientside only

**Comment by l1ving** [comment]
That's not true, and it's entirely irrelevant. This issue is resolved
