### ISSUE TITLE
#build commands help 

### ISSUE THREAD

**Issue by Logerxy** [cabaletta/baritone#2070]
when i start #build example.schematic it run perfect but it start building in random position so i cant regulate position if building

any ideas how to regulate building position?

**Comment by scorbett123** [comment]
#build blah.schematic <x> <y> <z>.

**Comment by Logerxy** [comment]
> #build blah.schematic x y z.

when i start #build example.schematic x y z (i write my current coordinates) it start building from corner

**Comment by Logerxy** [comment]
thanks
