### ISSUE TITLE
Add lily pad parkour to Baritone's pathfinding

### ISSUE THREAD

**Issue by GGamer6458** [cabaletta/baritone#2071]
## Describe your suggestion
Lily pad parkour in the pathfinding of Baritone so it can cross oceans easier and faster.

## Context
I was watching Baritone pathfind to specific coords that I told it to go to and I saw that it kept going really slow in the water. That's when I thought: "Why can't it do lily pad parkour like how it does block parkour?"

## Settings
#allowLilyPad

## PS
I have no idea if lily pad parkour is even in Baritone's pathfinding, but I'll suggest it anyways.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by GGamer6458** [comment]
I couldn't find the original post. Can you link it to me?

**Comment by l1ving** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/issues/1968
