### ISSUE TITLE
Get look vector of current player

### ISSUE THREAD

**Issue by SebaSphere** [cabaletta/baritone#2072]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Hey how would I get the look vector of a player using the baritone api. 
Tried the method "primaryBaritone.getPlayerContext().player().getLookVec();" but that's the vector for the player

How would I set and get the look vector if that's and capabilities that exist within baritones api.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Use `primaryBaritone.getPlayerContext().player().getLookVec();`

**Comment by SebaSphere** [comment]
Sorry should clarify that the look vector is for the local player and not the serverside player.

**Comment by l1ving** [comment]
Then no

**Comment by l1ving** [comment]
disable freelook

**Comment by SebaSphere** [comment]
hm alright
