### ISSUE TITLE
#goto, #path, etc does not work

### ISSUE THREAD

**Issue by ulaanbaatarhoteltours** [cabaletta/baritone#2073]
In my current setup in 1.15, Baritone works -- in terms of chat commands and settings, the mod is clearly installed. Aside from Baritone and Optifine I am not using any mods.

However, whenever I try to use #goto or #path, my character will not move -- instead he will stand immobilized in the spot where I was supposed to start walking from. I don't even get the pathfinding visuals I used to get on 1.12.

And when I then type #stop, i will still be unable to control my character, until i relog.

I tried looking for similar issues here but unfortunately I have not found any.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)

**Comment by SzybkiEZ** [comment]
Any Baritone movement commands don't work when you have x-ray on.
