### ISSUE TITLE
Mining after using #pause

### ISSUE THREAD

**Issue by CrumblyLiquid** [cabaletta/baritone#2075]
## Some information
Operating system: Windows
Java version: 1.8.0_212
Minecraft version: 1.16.3
Baritone version: 1.6.1 (Baritone API - Forge)
Forge mods (if used):

- Bookshelf-1.16.3-8.4.15
- cloth-config-forge-4.1.0
- forgemod_VoxelMap-1.10.11_for_1.16.3
- Hwyla-forge-1.10.11-B78_1.16.2
- invtweaks-1.16.2-1.0.0
- light-overlay-5.5.3
- MouseTweaks-2.13-mc1.16.2
- OptiForge-MC1.16.3-0.3.4 (preview_OptiFine_1.16.3_HD_U_G4_pre2)
- RoughlyEnoughItems-Forge-5.6.0+20200930-1640
- ShulkerTooltip-1.9.3
- WAWLA-1.16.3-6.0.1
- worldedit-forge-mc1.16.3-7.2.0-rc-01

## Exception, error or logs
There's just:
[Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > pause
[Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] Paused
Nothing else related.

## How to reproduce
Use for example #mine oak_log
Then use #pause while the bot is mining a block
The mining process would continue even if you weren't pointing to the same block

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by mpfaff** [comment]
I found a similar issue where after running `#pause` successfully, running `#stop` without running `#resume` first causes it to resume mining forever.

**Comment by l1ving** [comment]
That would explain why I can't reproduce it. See that issue for more information.
