### ISSUE TITLE
Add a fastbreak command

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2082]
## Title says it all
I've noticed when using the mine command or tunnel command, or any command that breaks blocks, when I hold LMB it breaks blocks twice as fast. I've found this to be extremely useful as I can mine much faster. It's like mining with two picks at once.

## The suggestion
I was thinking you could add a #FastBreak command that whenever and whatever you mine, Baritone also mines. It works on many servers and is undetectable. Another suggestion is a "FastbreakSwitchTools" command which when you have an empty fist, it automatically selects the tool in the hotbar suitable for breaking the current block (eg. you have a shovel in your hotbar but you're holding a bucket, and as soon as you mine it switches to the shovel.) You could also make this an individual command.

## Other info
Sorry if you're confused as I am bad at wording things. If you need more context you can reply here.

**Comment by GameCenterJerry** [comment]
Version is 1.16.3 Forge btw I forgot to mention

**Comment by ZacSharp** [comment]
1. I don't think that behaviour is intended but if you want a switch for it just use a hacked client.
2. Baritone already has an autotool for itself and if you want one that works for you you also want a client here.
The only 1.16.3 Forge hacked client I know is [ForgeHax](https://github.com/fr1kin/ForgeHax)

**Comment by GameCenterJerry** [comment]
@ZacSharp 
That's the point though, a non hacked client fastbreak. I just thought it would be fun to add one. Btw I don't usually play on forge, I only mentioned forge because I figured out the glitch on the forge version of Baritone. Plus for me, it's a lot less buggy than a hacked client's fast break

**Comment by l1ving** [comment]
Closed as won't fix, use Impact. Baritone is a pathfinding bot for Minecraft, not a cheating tool.
