### ISSUE TITLE
Selecting mining/harvest tool?

### ISSUE THREAD

**Issue by crazyminer66** [cabaletta/baritone#2083]
In the pack im playing theres a enchanting to increase crop yield for hoes but when i do # farm it goes to my sword even when i only have a hoe it will mine with my fist

How do i make it so i can farm/break with a hoe

**Comment by ZacSharp** [comment]
Three options:
1. get an autotool respecting that enchantment and use `#disableAutotool true` (and `#assumeExternalAutotool true`)
2. use `#disableAutotool true` and manually select the hoe manually
3. put your hoe in the first hotbar slot (the fallback slot) and make sure it does not find another slot to select
