### ISSUE TITLE
Pathfinding can stop due to "a goal with higher priority."

### ISSUE THREAD

**Issue by zincodrone** [cabaletta/baritone#2087]
## Some information
Operating system: WindowsOS-64x
Java version: 1.8.0_261
Minecraft version: 1.12.2
Baritone version: v1.2.14 (or whatever version used by Kami BLUE and Impact version not listed so just guessing.)
Forge mods (if used): Kami BLUE and Impact mod versions.

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5404898/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1. Use Kami BLUE w/ Impact
2. Use any command sign for Baritone, Kami BLUE, or Impact to run the goto command.
3. Have Minecraft running in the background. (Don't have Minecraft on screen.)
## Modified settings
To get the modified settings run `#modified` in game
allowInventory: true
allowParkour: true
chatControl: false
failureTimeoutMS: 2000

(Type_Boolean for allowInventory, allowParkour, chatControl | Type_Long for failureTimeoutMS)
## Final checklist
- [✓] I know how to properly use check boxes 
- [✓] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [✓] I have included logs, exceptions and / or steps to reproduce the issue.
- [✓] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
That's not a bug, that's a feature. Something else with a higher priority overrides impacts .goto

**Comment by zincodrone** [comment]
> That's not a bug, that's a feature. Something else with a higher priority overrides impacts .goto

It's not a feature. What it does is that it stops all features of baritone it stops the pathfinding, mining, everything. It won't listen to commands so at that point it is only a text generator in the chat at this point. You have to spam #stop a bunch to get it to fix itself it is a bug because of this,

**Comment by l1ving** [comment]
Closed as stale. Reopen if you can still reproduce this.
