### ISSUE TITLE
Soulsand & building

### ISSUE THREAD

**Issue by kyllianlissens** [cabaletta/baritone#2094]
All latest edition etc everything works probs just a setting...

When having a schematic with soulsand and trying to do #build baritone starts glitching out
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by kyllianlissens** [comment]
@l1ving Send link of dupe?

**Comment by l1ving** [comment]
search button

**Comment by kyllianlissens** [comment]
![image](https://user-images.githubusercontent.com/16906265/96759833-d60d6d80-13d8-11eb-93ac-57081d233f29.png)

**Comment by l1ving** [comment]
![Screenshot_20201021-140616.png](https://user-images.githubusercontent.com/17222512/96759884-9af24680-13a6-11eb-8daf-23447e89b143.png)![Screenshot_20201021-140607.png](https://user-images.githubusercontent.com/17222512/96759896-9f1e6400-13a6-11eb-8e00-cc2249d30980.png)![Screenshot_20201021-140541.png](https://user-images.githubusercontent.com/17222512/96759902-a0e82780-13a6-11eb-9098-ede754a4bbda.png)

**Comment by kyllianlissens** [comment]
@l1ving I meant like the specific issue where it solves my problem

**Comment by l1ving** [comment]
It doesn't solve your problem, it's a known bug. All the ones I showed are duplicates, the bug is with how Baritone handles non-whole blocks

**Comment by kyllianlissens** [comment]
So there's no fix alright

**Comment by l1ving** [comment]
No, it's a bug.
