### ISSUE TITLE
Baritone crashing immediately after mods begin to be loaded when in use with another mod

### ISSUE THREAD

**Issue by Iridum-png** [cabaletta/baritone#2095]
I believe the mod that's causing the conflict is JustEnoughIDs. This changes 1.12.2 chunk storage to the newer, larger 1.13 format. This is causing this error 

[The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.NoSuchFieldException: processor
Exit Code: -1]

which is greatly frustrating. Is there any fix to this issue? Thanks in advance to all who reply!

[crash-2020-10-21_17.27.01-client.txt](https://github.com/cabaletta/baritone/files/5417353/crash-2020-10-21_17.27.01-client.txt)

**Comment by l1ving** [comment]
Holy shit you're mixing 4 different game versions in your mods. I can spot 1.12.2, 1.13.2, 1.14.4 and 1.8.9 

Reopen this issue with a log file that's running *only* the incompatible mod.
