### ISSUE TITLE
when i try to do .b build, then the schem name, all it tells me is error at arguement #2 expected relativeblockpos, please help me

### ISSUE THREAD

**Issue by nik4nao** [cabaletta/baritone#2097]
## Some information
Operating system: W10
Java version: 1.12.2
Minecraft version:1.12.2
Baritone version:Latest
Forge mods (if used): 1.12.2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by nik4nao** [comment]
![image](https://user-images.githubusercontent.com/73259691/96794277-c3803d80-13b2-11eb-86c9-83e986229666.png)

**Comment by l1ving** [comment]
I don't understand why you're putting `(1)` after the command. 

Closed, user error. Run `#help build`

**Comment by nik4nao** [comment]
thats part of the file

**Comment by nik4nao** [comment]
![image](https://user-images.githubusercontent.com/73259691/96799376-d9443180-13b7-11eb-9cc0-dd9657c9c83f.png)

**Comment by l1ving** [comment]
Don't name it that then

**Comment by nik4nao** [comment]
I changed it, it still says the same thing

**Comment by nik4nao** [comment]
any ideas on how to fix it?

**Comment by l1ving** [comment]
Send a new log file

**Comment by nik4nao** [comment]
?

**Comment by l1ving** [comment]
Send your new log file

**Comment by nik4nao** [comment]
What is a log file?

**Comment by l1ving** [comment]
oh you didn't even bother to fill out the issue template. go read it

**Comment by nik4nao** [comment]
where is the issue template

**Comment by l1ving** [comment]
inside your issue

**Comment by nik4nao** [comment]
now it just says that it can't find the schem, im gonna restart my pc
