### ISSUE TITLE
Avoid potential rare ConcurrentModificationException on pathing thread

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#210]
To avoid a ConcurrentModificationException between ChunkProviderClient.loadedChunks loading a chunk on the main thread and BlockStateInterface.get reading from that Long2ObjectOpenHashMap<Chunk> at the exact same time, perhaps BlockStateInterface could make a copy, its own Long2ObjectMap<Chunk>, once a tick, and just refer to that for lookups?

**Comment by ZeroMemes** [comment]
Exceptions? I prefer try/catch and retry!

**Comment by leijurv** [comment]
```} catch(ConcurrentModificationException ex){
return get(x, y, z); // retry
}```

**Comment by leijurv** [comment]
Welllll, this is both theoretical and incredibly rare, I've never seen it and I doubt I ever will, and it would only cause an exception on the pathing thread not a game crash...
Any call to BlockStateInterface.get from the main thread will obviously succeed...
