### ISSUE TITLE
Where are the colors of the api located*

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2101]
## Just a small question
I was wondering which file in the source code holds the colours for the path line, chat commands or are they split up around the source code. I'm mainly looking for the colours of the Baritone output in chat. (When you do #help or other commands)
## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I have done way too much today

**Comment by l1ving** [comment]
![Screenshot_20201021_231337](https://user-images.githubusercontent.com/17222512/96820043-0feb6d80-13f3-11eb-87c0-cc7862e68b7d.png)
Lots of places. Would be worth just looking at the default values. https://baritone.leijurv.com/baritone/api/Settings.html

**Comment by l1ving** [comment]
If you want only the colors Baritone uses for chat, here you go 
![image](https://user-images.githubusercontent.com/17222512/96820182-65277f00-13f3-11eb-9390-a9e0a80ef5ec.png)

**Comment by GameCenterJerry** [comment]
I meant the **[Baritone]** part, not the text it outputs. eg. **[Baritone]** >Mine diamond_ore

**Comment by l1ving** [comment]
That's just light purple and dark purple

**Comment by GameCenterJerry** [comment]
Lol still not quite my point. My ultimate goal is to change the color of the **[Baritone]** thing to fit what I like. I just want to know which file is responsible for displaying that color
