### ISSUE TITLE
disabling sneak 

### ISSUE THREAD

**Issue by northwind4ofrip** [cabaletta/baritone#2102]
I'm in a server and it keeps kicking me for sneak hacks is there a way to disable sneaking with baritone overall?
my friends baritone doesn't sneak but when I checked the settings list there was nothing except the ones about bridging and backspace and I already disabled them.

**Comment by ZacSharp** [comment]
Fill out the template. You have left out a lot of information it asks for.

**Comment by l1ving** [comment]
`#allowSprint` is a setting, `allowSneak` is not as sneaking isn't really cheating lol
