### ISSUE TITLE
cant build cactus nor string

### ISSUE THREAD

**Issue by northwind4ofrip** [cabaletta/baritone#2103]
Operating system:pc
Java version: last
Minecraft version:1.12.2
Baritone version: latest
Forge mods (if used): schematic and impact

for some reason when I try to build a cactus farm schematic it builds the sand but after that, it breaks I'm not sure what the problem is with it

**Comment by scorbett123** [comment]
This is a known bug.

**Comment by scorbett123** [comment]
There are half a million duplicates of this.

**Comment by scorbett123** [comment]
See #2094

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
