### ISSUE TITLE
Gradle fails to build with modified line (Sorry for another issue lol)

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2104]
## Some information
Operating system: 10.15.3
Java version: 1.8
Minecraft version: 1.16.3 & 1.12.2
Baritone version: master & 1.6.1
Forge mods (if used): 

## INFO
The correct java version was used, only every time I tried to `./gradle build` it failed with an output of `Execution failed for task ':compileApiJava'`

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
```
% git clone https://github.com/cabaletta/baritone.git

% export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

% java -version

% cd baritone

baritone % ./gradlew setupDecompWorkspace

baritone % ./gradlew --refresh-dependencies

baritone % ./gradlew build
```

ERROR output:
````
baritone % ./gradlew build

> Configure project :
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.

> Task :compileApiJava FAILED
/Users/me/baritone/build/sources/api/java/baritone/api/utils/Helper.java:1: error: class, interface, or enum expected
LIGHT_RED/*
^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileApiJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
4 actionable tasks: 4 executed
````

# IMPORTANT INFO
I found the place of error, it was in a line I modified. I changed `DARK_PURPLE` and `LIGHT_PURPLE` into `DARK_RED`and `LIGHT_RED`. That was probably the issue. If so, could I get a list of colors available or a link to the "Colors in javascript" or something?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue. œw0

**Comment by l1ving** [comment]
You're trying to reference an unknown enum value. Either statically import it or put TextFormatting before it

**Comment by GameCenterJerry** [comment]
Nevermind I found it, it wasn't javascript colors it was minecraft

**Comment by GameCenterJerry** [comment]
https://minecraft.gamepedia.com/Formatting_codes

**Comment by GameCenterJerry** [comment]
It turns out "DARK_RED" is just RED

**Comment by l1ving** [comment]
# :moyai:
