### ISSUE TITLE
Stopall command

### ISSUE THREAD

**Issue by AbyssStudios** [cabaletta/baritone#2106]
## Describe your suggestion
Adds a command that will stop all paths running

## Settings
N/A

## Context
This could help because if you need to spam #stop, you could just do this to stop all processes.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`#stop` already stops all processes

**Comment by l1ving** [comment]
Yea it sounds like something you're using is constantly making new processes, not a Baritone issue.
