### ISSUE TITLE
Player can't move after bot finishes mining

### ISSUE THREAD

**Issue by Objectful** [cabaletta/baritone#2108]
## Some information
Operating system: Windows 10
Java version: Java 8 (build 1.8.0_251-b08)
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): SalHack, Optifine, BetterSprinting

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5433542/latest.log)

## How to reproduce
The log doesn't seem to give any essential information about what was happening. All what I did was doing #mine grass, then waited for a bit. The task was done but when I tried to move, it didn't let me. ToggleSprint was changing the FOV but there was no movement. To make myself move again, I have to exit my world, then enter back in. No errors were in the log. I have footage of it happening: https://www.youtube.com/watch?v=TZxt8a1CDBI And yes, I did stop the process afterwards and it still wouldn't let me move.

## Modified settings
allowPlace
chatControl

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Salhack is incompatible with Baritone, it's an issue on their end.
