### ISSUE TITLE
Baritone mining fake blocks

### ISSUE THREAD

**Issue by heIIhound** [cabaletta/baritone#2109]
## Some information
Operating system: Windows 10
Java version: Java 8
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): Optifine

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5433632/latest.log)

## How to reproduce

Baritone worked perfectly fine until the server owner put up an anti-Xray plugin which puts fake block everywhere, baritone is mining those fake blocks.

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
#legitmine true

**Comment by scorbett123** [comment]
I don't know if this is in a release yet but; #allowOnlyExposedOres is a setting meant to counteract this.
