### ISSUE TITLE
Weirdest bug yet, 2 block parkour fails depending on the presence of a seemingly random other block

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#211]
https://youtu.be/njNpbKN0qKA

I cannot explain this.

I want to douse my computer in holy water.

Not joking this is the weirdest bug yet by far.

**Comment by leijurv** [comment]
@ZeroMemes this bug doesn't happen when freelook is off so i blame you haha rekt

**Comment by 0-x-2-2** [comment]
wow this is epicc
