### ISSUE TITLE
How to compile 1.16.2

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2110]
## What do you need help with?
This is stuck between a question and a bug. I can build master, but cannot build any of the other branches (1.16.2). The log says there is no such action of “setupDecompWorkspace” in the root folder of the project. I was wondering if there was a way around this or do I have to make my own.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I successfully used
```
git clone https://github.com/cabaletta/baritone.git
cd baritone
git checkout 1.16.2
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
./gradlew build
```

**Comment by l1ving** [comment]
You don't need a workspace for building in the first place.
