### ISSUE TITLE
How to make baritone work as a mod?

### ISSUE THREAD

**Issue by HoldMyVotka** [cabaletta/baritone#2111]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by HoldMyVotka** [comment]
I downloaded the right version od baritone that supports forge, I'm using that forge version, but when I run the game it just doesn't show it...

**Comment by HoldMyVotka** [comment]
![image](https://user-images.githubusercontent.com/73425285/97105441-fa0fce00-16ba-11eb-8941-9da2eb973b47.png)
That's a pic of my mods folder, and it has baritone in it.

**Comment by HoldMyVotka** [comment]
![image](https://user-images.githubusercontent.com/73425285/97106013-65f43580-16bf-11eb-9ac9-fa86069c0d1e.png)
Here is my 1.12.2 mods folder pic...

**Comment by l1ving** [comment]
Baritone isn't supposed to show up in the mod list.

**Comment by HoldMyVotka** [comment]
But does it work tho?

**Comment by l1ving** [comment]
Yes.
