### ISSUE TITLE
AssumeFlight setting.

### ISSUE THREAD

**Issue by Z3r0ut** [cabaletta/baritone#2112]
I want to use flight with pathfinding, no matter if it is creative fly or a flight "hack" that works like the creative one.

## Settings
Well.. Assumeflight to all pathfinding.

## Context
So Baritone doesnt have to place blocks, or water bucket fall etc.
or to travel to a certain coordinate that is thausands or more blocks away quicker

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Duplicate
