### ISSUE TITLE
AssumeNofall

### ISSUE THREAD

**Issue by Z3r0ut** [cabaletta/baritone#2113]
## Describe your suggestion
Nofall = an "Hack" that negates all falldamage.

## Settings
AssumeNofall

## Context
So it can jump from high places even in the nether.
(And yes, i know there is a setting where i can choose how far it is allowed to fall, but this setting makes it easier)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
`#maxFallHeightNoWater 100`
