### ISSUE TITLE
No Teleport/instand Rotation setting

### ISSUE THREAD

**Issue by Z3r0ut** [cabaletta/baritone#2114]
## Describe your suggestion
i want a setting that moves the "vision" like a player would do, and not that instand thing.

## Settings
Well, an setting to "imitate player look behavior"

## Context
On some servers i get kicked sometimes for "Illegal Rotations" And i think thats related to the bot like teleport/instand rotations.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
duplicate of #2034 and similar to #1218, #1470, #1795, #1048, #2066.
