### ISSUE TITLE
What happened to the .json files from 1.14.4?

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2119]
## What do you need help with?
What happened to just using .json files to install baritone? Will it ever be like this again or keep on using .jars

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Nothing happened to it? Baritone has always supported the same formats and will continue to support them.

**Comment by GameCenterJerry** [comment]
@l1ving what I meant was in 1.15.2 you downloaded a folder with a .json file and a README.md. Now you have to download the .jar file itself with no .json.

**Comment by l1ving** [comment]
Version modding is still available, you can get the json on Leijs channel

**Comment by GameCenterJerry** [comment]
As far as I know Baritone 1.6.1 works with 1.16.4. Would it work if i changed the "1.16.2" in the .json to "1.16.4"

**Comment by l1ving** [comment]
Maybe
