### ISSUE TITLE
#Craft command

### ISSUE THREAD

**Issue by Z3r0ut** [cabaletta/baritone#2121]
## Describe your suggestion
It could be done this way: It remembers the content of the chests
 we open, and then we can type for example #craft minecraft:gold_block minecraft:redstone_block
and then it goes to chests it know that has gold ingots/nuggets and redstone, fills up the inventory walks to a crafting table and crafts them
## Settings
#onlyinventory so we can toggle the use of chests. So it only uses the resources that are in the inventory
#allowEnderchest so we can toggle if it should use the contents of an enderchest or not.

## Context
It would save a lot of time, and it is, in a way a path finding tool.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CDAGaming** [comment]
not only a duplicate but likely out of scope for Baritone as an **Automine** not an _autocraft_ bot

**Comment by l1ving** [comment]
this has also been suggested at LEAST 20 times

**Comment by NatoBoram** [comment]
Duplicate of #295

**Comment by CesiumCs** [comment]
good god someone ban this dude from the repo
