### ISSUE TITLE
How to build baritone for versions 1.13.2 and under.

### ISSUE THREAD

**Issue by josephyooo** [cabaletta/baritone#2122]
I assume to build baritone for the different versions, you would use the different branches, but only versions 1.13.2+ are available, not even 1.12.2 which is available in releases. For these versions of Minecraft, how would I build baritone? Also, for all versions prior to v1.2.9, there are no more captions, which I feel shouldn't be too difficult to add compared to the effort people might spend testing random versions to see if it works for whatever version of Minecraft they may be using.

Anyways, all I'm trying to do is get baritone for Minecraft 1.7.10. If that's possible or if there are any older alternatives, please let me know.

**Comment by l1ving** [comment]
No, and Minebot. Read the README.md

Also the 1.12.2 branch is the master branch.
