### ISSUE TITLE
My player is not moving

### ISSUE THREAD

**Issue by fenixcresp0** [cabaletta/baritone#2123]
## I tried to use automatic mode but my player doesn't move
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): I use fabric, only baritone and sodium.

## ![image](https://user-images.githubusercontent.com/71677565/97305805-f8b5e100-1833-11eb-81bb-2f10b07e8f54.png)

What is going on: I try to use #mine (and the id), the client locate and show me but it only mine if it is on the side of the item

**Comment by l1ving** [comment]
Where did you get the jar?

**Comment by fenixcresp0** [comment]
On a yt tutorial :/

**Comment by fenixcresp0** [comment]
here's the link: https://gitlab.com/CDAGaming/fabriton...

**Comment by l1ving** [comment]
Where specifically?

**Comment by fenixcresp0** [comment]
at this yt tutorial https://www.youtube.com/watch?v=5Hw0xBE-hpY

**Comment by l1ving** [comment]
Well to me that looks like old Fabritone builds, not Baritone.
