### ISSUE TITLE
Follow entity doesn't work

### ISSUE THREAD

**Issue by Xiarno** [cabaletta/baritone#2131]
## Some information
Operating system: Windows 10
Java version: 1.8.0_51 64bit (Written on the top right of the F3 menu idk how to check anywhere else)
Minecraft version: 1.12.2
Baritone version: Baritone v1.2.14
Forge mods (if used): None (except Baritone itself)

## Exception, error or logs
Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/5461588/latest.log)

## How to reproduce
Just write the command `#follow entity [name of entity]`. I did it with a pig. I made sure there was a pig right beside me and still didn't work. `#follow entities` work just fine though

## Modified settings
allowInventory
allowParkour
allowParkourPlace

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by Xiarno** [comment]
> This is a duplicate. Please search before creating an issue next time.

I did search and found things similar but absolutely no fixes or just nothing useful. Please send a link to the duplicate since I probably missed it.

**Comment by l1ving** [comment]
It's already fixed, you need to use the latest version of Baritone. https://github.com/cabaletta/baritone/pull/1971

**Comment by Xiarno** [comment]
> It's already fixed, you need to use the latest version of Baritone. #1971

The latest ? But, I took the latest available for 1.12.2 that I could find which was this one: https://github.com/cabaletta/baritone/releases/tag/v1.2.14
And I've been searching and I can't find any more recent than that.

**Comment by l1ving** [comment]
v1.2.14 is 99 commits old. 
![image](https://user-images.githubusercontent.com/17222512/97641701-de3d5c80-1a19-11eb-9d99-e44d6f184e97.png)

You'll need to build your own release

**Comment by Xiarno** [comment]
> v1.2.14 is 99 commits old.
> ![image](https://user-images.githubusercontent.com/17222512/97641701-de3d5c80-1a19-11eb-9d99-e44d6f184e97.png)
> 
> You'll need to build your own release

And how do I do that ? I'm not that advanced ;-;

**Comment by l1ving** [comment]
Read the README

Preferably, wait for the next Baritone release

**Comment by Xiarno** [comment]
> Read the README
> 
> Preferably, wait for the next Baritone release

Yeah I did. When I got to the build, I got stuck on IntelliJ. Like, what is this ?

**Comment by ZacSharp** [comment]
It is an IDE, you don't need it for building baritone.
Just get the repository and run `./gradlew build` (Linux/Mac) / `gradlew build` (Windows, no guarantees). The result is in the dist directory.

**Comment by Xiarno** [comment]
> It is an IDE, you don't need it for building baritone.
> Just get the repository and run `./gradlew build` (Linux/Mac) / `gradlew build` (Windows, no guarantees). The result is in the dist directory.

Okay, so where do I run the command `gradlew build` and what is the dist directory ?  From context, I assume the dist directory is where I downloaded the repository, right ? Thanks !

**Comment by scorbett123** [comment]
Enter either windows powershell or the terminal . Then enter the command `cd \Path\To\Download`. Then run `./gradlew build`.

Then after running the command (the command might takes a while to run) it will create a folder called dist inside where you have downloaded the repository. Inside that folder there will be the .jar files.
