### ISSUE TITLE
cRAshes when i try to open Multiplyer

### ISSUE THREAD

**Issue by GamingReflexThePenguin** [cabaletta/baritone#2134]
## Some information
Operating system:Windows 10
Java version:Not Sure
Minecraft version:1.12.2
Baritone version:The Latest 1.12.2 One 1.2.1.4

Forge mods (if used): Crack Future Client, JEI, HUDS,ELECCORE.GHOSTWRITE,

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[debug.log](https://github.com/cabaletta/baritone/files/5468542/debug.log)

(IN 2B2T QUEEQ IT SHOWS MY CURRENT GAME THING BUT I DONT HAVE BARITONE ON ON THE GAME THAT IS THE ONE OF WHERE I HJAE IT OPEN) sorry for caps btw

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Just Loading Into Any multiplayer sever
singleplayer works 
but when i try multiplayer it crashes

## Modified settings
To get the modified settings run `#modified` in game
[2020-10-31_16 03 30](https://user-images.githubusercontent.com/73213402/97771624-aa397700-1b92-11eb-9090-8102acddc359.png)
Done In SinglePlayer

## Final checklist
- [x] I know how to properly use check boxes Yes
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue. Why Would I Have Those There People WHo say that arent ok in the head

**Comment by l1ving** [comment]
I don't know what you expected when installing pirated software.

**Comment by GamingReflexThePenguin** [comment]
k thanks
also yeah 
im probaly gonna spend money and get future client soon
