### ISSUE TITLE
Unable to mine ores that are not seen.

### ISSUE THREAD

**Issue by Hayliox** [cabaletta/baritone#2137]
## Some information
Operating system: Windows 10
Java version: 1.8.0_261
Minecraft version: 1.12.2
Baritone version: Baritone standalone forge 1.2.14
Forge mods (if used): Konas client and Optifine 1.12.2 F5

## Exception, error or logs
When trying to mine for diamond ore, it tells me "Unable to find any path to BlockOptionMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]}, blacklisting presumably unreachable closest instance

## How to reproduce
Do #mine diamond_ore

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Send a video of this issue, and include the #modified command in the same video

**Comment by Hayliox** [comment]
https://streamable.com/xtzu0f

It does this for a looooooong time until I'm near/the ore is visible. Thinking the problem might be a compatibility issue with Konas but I doubt it to be fair.

**Comment by scorbett123** [comment]
does this issue still occur with a pickaxe in your inventory?

**Comment by Hayliox** [comment]
> 
> 
> Does this issue still occur with a pickaxe in your inventory?

It doesn't anymore. It does work now, apparently needed a pick!

**Comment by l1ving** [comment]
idk why you'd mine diamonds without tools in the first place. this behavior is entirely intentional, as it's faster to find a cave then it is to mine through a shit ton of stone
