### ISSUE TITLE
(May be a bug) Baritone doesn’t kill mobs or players that try to kill them doing “b mine”

### ISSUE THREAD

**Issue by waterdragon78** [cabaletta/baritone#2140]
Baritone doesn’t kill mobs or players that try to kill them doing “b mine”

(Also Idk if it avoids hazards like lava, fall damage, etc...)

**Comment by CesiumCs** [comment]
it isnt supposed to. you probably want to use your favorite clients killaura mod or something similar

**Comment by l1ving** [comment]
This isn't a bug.
