### ISSUE TITLE
How can i locate a end city with Baritone?

### ISSUE THREAD

**Issue by Deshinangla** [cabaletta/baritone#2141]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
use a seed cracker mod to get the seed
paste the seed into chunkbase and find an end city
tell baritone to `#goto` the coords of that end city

**Comment by scorbett123** [comment]
you could also put a lot of blocks in your inventory (to get between the islands) and make sure that the setting exploreForBlocks is on. Then use goto purpur_block. This would mean that it would search randomly, not just going straight to different end cities previously found.
