### ISSUE TITLE
12.2.2 Forge Baritone wont turn Camera

### ISSUE THREAD

**Issue by Owenson123** [cabaletta/baritone#2143]
Baritone wont turn my camera by itself, using automine and #build i have to turn the camera with my mouse and then it will place the block. Additionally everytime i get baritone to do something like #path afterwards my wasd keys are inverted. How do I fix this? To fix the wasd issue I have to restart the game everytime.
thanks

**Comment by l1ving** [comment]
#freeLook false 

> How so I fix this

Fill in the proper issue template
