### ISSUE TITLE
Baritone 1.12.2 wont turn camera

### ISSUE THREAD

**Issue by Owenson123** [cabaletta/baritone#2144]
[latest.log](https://github.com/cabaletta/baritone/files/5481497/latest.log)
## Some information
Operating system:Windows 10
Java version:(build 1.8.0_251-b08)
Minecraft version:1.12.2 Forge
Baritone version:1.12.2
Forge mods (if used): MDSEGKA   modpack on technic its huge.
[latest.log](https://github.com/cabaletta/baritone/files/5481475/latest.log)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/` ([latest.log](https://github.com/cabaletta/baritone/files/5481475/latest.log))

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
I do #mine or #build and its just wont turn the camera. I can manually turn my camera and then it will place/mine the items but thats where it ends. Additionally if I get baritone to move anywhere for me the wasd keys are inverted dependant to which direction I was facing when I entered the command.

## Modified settings
Vanilla settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
I don't know what those logs are, however they certainly aren't of this issue. It seems like you are just entering the game, typing #help, and then very quickly leaving, before the help command can even print. You don't even run the #mine or the #build command. Please can you send new logs that demonstrate that your issue.

**Comment by l1ving** [comment]
And you need to include a screenshot of #modified

**Comment by ZacSharp** [comment]
Just did a search for "baritone" in that new log and for me it looks like mixin failed to transform NetHandlerPlayServer and EntityPlayerSP because some other mod already did changes to them (in one case it might be xaero's minimap).

**Comment by l1ving** [comment]
Xaero's minimap worked fine with Baritone for me last time I used it. Reopen this issue with the name of the specific mod that breaks it.
