### ISSUE TITLE
.b goto <block> is broken for me

### ISSUE THREAD

**Issue by thebruhmoment** [cabaletta/baritone#2145]
when i`m trying do .b goto <block> it`s not working with all blocks, it just tries to find something not in my loaded chunks
![2020-11-03 21-25-17 (1)](https://user-images.githubusercontent.com/65070996/98036238-5e9cfc80-1e22-11eb-8379-c541e983e1d0.gif)
i recreated it in singleplayer and this issue same for all the blocks i checked  (blocks i checked below)
![image](https://user-images.githubusercontent.com/65070996/98036573-ef73d800-1e22-11eb-85d6-82e8ae2d3667.png)

**Comment by l1ving** [comment]
Fill out the issue template properly please.
