### ISSUE TITLE
Null getCollisionShape returned when standing on irregular shaped blocks

### ISSUE THREAD

**Issue by ViRb3** [cabaletta/baritone#2148]
## Some information
Operating system: Windows 10
Java version: 1.8
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): https://www.curseforge.com/minecraft/modpacks/all-the-mods-6 + Baritone + ForgeHax

## Correlated between
- https://github.com/TeamPneumatic/pnc-repressurized/issues/649
- https://github.com/BluSunrize/ImmersiveEngineering/issues/4408

## Exception, error or logs
https://paste.ubuntu.com/p/KDgYj76K9B/ - crashes PneumaticCraft [here](https://github.com/TeamPneumatic/pnc-repressurized/blob/da1e1e6fb5b95117c4e382388d3b1c654a478b17/src/main/java/me/desht/pneumaticcraft/common/block/BlockPneumaticCraftCamo.java#L86)
https://pastebin.com/X5EpVU5f - crashes PneumaticCraft [here](https://github.com/TeamPneumatic/pnc-repressurized/blob/da1e1e6fb5b95117c4e382388d3b1c654a478b17/src/main/java/me/desht/pneumaticcraft/common/block/BlockPneumaticCraftCamo.java#L86)
https://pastebin.com/3Nmjbn5E - crashes Immersive Engineering [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/549dfa3182fa5ef0842c51f438a4a43ac1413f41/src/main/java/blusunrize/immersiveengineering/common/blocks/IETileProviderBlock.java#L378)

As you can notice, both mods crash on the same Forge method call. 

## How to reproduce
It seems like whenever the player is standing on top of a non-standard-shaped block, a Block#getCollisionShape() of null is returned and the next mod that tries to use it crashes. This happened to me on two separate mods - Immersive Engineering Conveyor Belt, and PneumaticCraft Air Pressurizer, both of which look non-standard.

**Comment by wagyourtail** [comment]
I've looked into this, one choice is to ignore by setting to air (or a full block) but that can cause issues.
 ![image](https://media.discordapp.net/attachments/822210907173421116/828049802297344070/unknown.png)
 if someone else wants to look into coding this... https://github.com/wagyourtail/baritone/tree/c%26bfix1.16 is the WIP

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
if Block#getCollisionShape() fails (java.lang.NullPointerException) this will treat as full block

**Comment by wagyourtail** [comment]
it can then try to walk ontop of blocks when that is not the case, I think it's better to add it to the blocksToAvoid list

**Comment by scorbett123** [comment]
> if Block#getCollisionShape() fails (java.lang.NullPointerException) this will treat as full block

really I think it should default the other way. If baritone can't get the information it should not walk over the block.

**Comment by wagyourtail** [comment]
yeah, but not through it either, so forcing baritone to either mine it or go around would be best and is the first half of how I solve it in #3067 but I still need to fix it so baritone actually aims at it when mining. (or just add it to the avoid breaking list as well)

**Comment by ZacSharp** [comment]
#3067 is now merged
