### ISSUE TITLE
Couple suggestions for features

### ISSUE THREAD

**Issue by jacke123** [cabaletta/baritone#2149]
There is a couple features I'd like to see

-Automated bedrock breaking with machines

-Automated duplicating (Some dupe methods are time based.)

-Automated chest stealing (Mine to chests and get the materials)

-Command Lines, Like say it would mine 30 diamonds then go to a goal then go to a diferant goal in one line

-Auto craft 

-Item priority (When mine you can leave things behind)

----------

Just thought of these, Though they would be hard to implement they  would be useful.

**Comment by CesiumCs** [comment]
usually its better to put each suggestion into its own issue with more detail, so each can be closed as the feature is added

**Comment by scorbett123** [comment]
Many of these are duplicates, for those that aren't please split them into separate issues.

**Comment by l1ving** [comment]
All of these are either duplicate or out of scope
