### ISSUE TITLE
1.16.3?

### ISSUE THREAD

**Issue by randomairborne** [cabaletta/baritone#2151]
I was wondering if there will be a 1.16.3/4 release.  If one becomes supported, the other most likely will as most mods I have used work across versions 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Don't ask for version support. Every single time there's a new Minecraft version 2983498298349823498 children are instantly rushing to the Baritone / Impact Github to ask "wHeN uPdaTe pLease soon I need co ChEaT on notvirus.b2t2b.net riGhT awaY plEase uPdate"

**Comment by randomairborne** [comment]
I mean, I was trying to be polite, not even asking for the latest version, or a massive jump.  You could have said "there are no plans for that as of yet" and I would have been fine.  Thank you for the response, though!

**Comment by randomairborne** [comment]
At least i did not do this https://github.com/cabaletta/baritone/issues/2009

**Comment by l1ving** [comment]
Valid point, sorry. It just gets tiring of people asking the same thing all over. All version related questions will almost always have the same answer, it'll be released once it's released.

**Comment by CesiumCs** [comment]
the release of baritone for 1.16.2 happens to work with forge 1.16.3 because of how small the change was between those versions. not sure if it works with 1.16.4 though

**Comment by randomairborne** [comment]
@CesiumCs hmm odd.  I could get all other mods working across 1.16.3/4, but could not get baritone working across 1.16.2/3.  odd.
also, @l1ving I feel ya, I help out on the minecraft discord and the number of people who asked about the cave update were SO annoying.

**Comment by randomairborne** [comment]
Just as a question, what would it take to update to 1.16.3 if I wanted to, as the only change was to fix a dupe, and a pathing bug.  Also, 1.16.4 added the social interaction screen, so it should work with that too.

**Comment by l1ving** [comment]
Well they refactored quite a bit of stuff behind the scenes, which caused issues for some mods such as KAMI
![image](https://user-images.githubusercontent.com/17222512/98299595-f6672b80-1f85-11eb-8db9-3970328d83f4.png)

**Comment by randomairborne** [comment]
hm, ok. I can wait.

**Comment by l1ving** [comment]
Fabritone no longer exists, it's known as Baritone and it's just a 1:1 of Baritone with different mappings now.

**Comment by CDAGaming** [comment]
For an official statement, 1.16.4 should be 1:1 from 1.16.3, which I plan to diffset when I have time. At the moment however, I hve coursework to take care of first.

**Comment by thisismikk** [comment]
> At least i did not do this https://github.com/cabaletta/baritone/issues/2009
> 
> 

hello

**Comment by PraamFloppa** [comment]
hello
