### ISSUE TITLE
Structure / biome finder

### ISSUE THREAD

**Issue by 13154LFCLM** [cabaletta/baritone#2152]
I think that would be very usefull to be able to specify a biome/structure in the goto command so that whenever you would need to find a specific structure (mansion, stronghold, villages, nether fortress) or biome (Swamp, Jungle, Badlands) you could just let the baritone bot search in a random direction (maybe customizable) and then found it for you.

## Settings
You could set the direction it will run in order to find the biome

## Context
That would be very usefull if you would need to find entities that spawn only in certain biomes/structure such as llama(mountain), cat (villages).

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
