### ISSUE TITLE
Baritone can't place string and breaks cactus by placing blocks while using #schematica

### ISSUE THREAD

**Issue by kensac** [cabaletta/baritone#2153]
## Some information
Operating system: Mac os
Java version: 
Minecraft version: 1.12.2
Baritone version: impact 4.9.1 
Forge mods (if used): schematica

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Using any cactus farm schematic that includes string 

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

Furthermore I am aware that this issue has been reported earlier but I could not find a solution so if anyone could guide me to a solution if there is any.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by kensac** [comment]
Hi I'm aware that this is a duplicate. Could you please guide me to a solution :)

**Comment by scorbett123** [comment]
Unfortunately at the moment there isn't one.

**Comment by kensac** [comment]
Oh okay thank you very much
