### ISSUE TITLE
Baritone should be able to get items from creative

### ISSUE THREAD

**Issue by waterdragon78** [cabaletta/baritone#2154]
Baritone won't get items from creative for build, leaving you t A: get the items yourself or B: find them if you don't know the blocks. I really beg, can you please add it? I just started with baritone and I LOVE IT, but this really bugs me. OwO UwU.
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.
- [ ] Baritone can now get items from creative
- [ ] It got rejected :(

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by waterdragon78** [comment]
hey where is the dupe other dupe

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/98303424-10a40800-1f8c-11eb-9300-2368f3dde42f.png)

**Comment by waterdragon78** [comment]
Thx!!

**Comment by waterdragon78** [comment]
Hey, I know this is a dupe, but it never got answered. Can u please reopen it?

**Comment by waterdragon78** [comment]
Please?

**Comment by l1ving** [comment]
It got answered, it's a duplicate.

**Comment by waterdragon78** [comment]
i would really appreciate if u linked it, thx :)

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/98304830-bb1d2a80-1f8e-11eb-921a-ad5077175478.png)

**Comment by waterdragon78** [comment]
no i know that, i looked at them and they never god answered, just closed

**Comment by l1ving** [comment]
you even commented on the opened one
![image](https://user-images.githubusercontent.com/17222512/98304901-ddaf4380-1f8e-11eb-89d4-2fb7c5e2496a.png)

**Comment by waterdragon78** [comment]
Closed

**Comment by l1ving** [comment]
#1675 is very clearly not closed and you even commented on it

**Comment by waterdragon78** [comment]
my bad, thx for help :D

**Comment by waterdragon78** [comment]
may be off topic, but do u think it will ever get solved?

**Comment by l1ving** [comment]
No, no issues are ever closed in this repository, we might as well disable the issues tab entirely while we're at it. */s*

**Comment by waterdragon78** [comment]
darn, well thx for ur help! :D
