### ISSUE TITLE
Baritone randomly stops when building

### ISSUE THREAD

**Issue by waterdragon78** [cabaletta/baritone#2155]
## Some information OwO UwU
Operating system:Mac
Java version:8
Minecraft version:1.16.2
Baritone version:Latest
Forge mods (if used): Optifine

## How to reproduce
get a schematic, and run #build thing.schematic and wait

## Modified settings
allowinventory, chatcontrol, freelook

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
>  I have included logs, exceptions and / or steps to reproduce the issue.

You forgot this step.

**Comment by waterdragon78** [comment]
sorry

**Comment by waterdragon78** [comment]
I fixed it

**Comment by l1ving** [comment]
How? It's the same as before

**Comment by waterdragon78** [comment]
i included the log

**Comment by waterdragon78** [comment]
Ahh didnt save my bad

**Comment by waterdragon78** [comment]
now i fixed it

**Comment by waterdragon78** [comment]
soooooo, any fixes?

**Comment by l1ving** [comment]
At least one of either things is true
- There is a liquid in the way
- You don't have all the blocks in your hotbar || allowInventory is false
- Baritone is unable to do it

**Comment by waterdragon78** [comment]
> At least one of either things is true
> 
> * There is a liquid in the way
> * **You don't have all the blocks in your hotbar || allowInventory is false**
> * Baritone is unable to do it

This leads to my other issue
(also thx for responding :)
