### ISSUE TITLE
How to make baritone search the entire schematic for blocks it can place?

### ISSUE THREAD

**Issue by circl-lastname** [cabaletta/baritone#2156]
## What do you need help with?
I'm making a mapart, of course I can't put all of the blocks in my inventory, so I tried to make baritone use current blocks up before trying to use others. When in an area full of the blocks it has no problem, but sooner or later it's gonna show me the vague "Unable to do it" message. I understand it is because it doesn't see more of the blocks it can place, and doesn't have any other blocks. So how do I extend the search area for blocks to the entire schematic? I don't see any setting for it, and schematica can't make my job easier by rendering only the blocks I have.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
You can't.

**Comment by circl-lastname** [comment]
Thanks
