### ISSUE TITLE
Standalone Baritone 1.12.2 not working in mods

### ISSUE THREAD

**Issue by lee98976** [cabaletta/baritone#2157]
I doesn't work when I put standalone Baritone in the mods folder. It doesn't register it as a mod.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by CesiumCs** [comment]
doesn't it just not show up regardless of whether it loaded properly? do #help in a world

**Comment by l1ving** [comment]
Yes, it's not supposed to show up as a Forge mod either.
