### ISSUE TITLE
Issue with ESP

### ISSUE THREAD

**Issue by terminator-alligator** [cabaletta/baritone#2159]
When using ESP on the mode shader with it in outline mode  and items turned on if you have an item dropped on the ground near you it will cause your hand and items held to turn darke

It's just a weird shader bug I imagine it has something to do with OptiFine

Operating system windows
Minecraft version 1.12.2
Impact version 4.9.1
Not using forge

**Comment by berrely** [comment]
Not Baritone related

**Comment by terminator-alligator** [comment]
Sorry
I thought I was reporte an issue somewhere else
Just ignore my dumbass
