### ISSUE TITLE
Build function being allowed to access inventory for needed blocks (grabInventoryBlocks)

### ISSUE THREAD

**Issue by DefyEnjoyCantCode** [cabaletta/baritone#2160]
So, I think Baritone is pretty poggers, but I feel like there's a pretty large issue with the build function.
Yes, Baritone can build the selected schematic with ease, but it can only use blocks currently in the hotbar.
That is ok, but that only leaves either 9 or 10 blocks for use, meaning if there's more than 10 unique blocks, there's an issue.

My basic idea for this suggestion is grabInventoryBlocks.
By toggling this to true, Baritone can grab needed blocks for the build function when it needs them.
Sadly, allowInventory doesn't do this, so this would be a big help for the build function.
If this is toggled to false, it won't grab needed blocks in the inventory and put them in the hotbar.

**Comment by l1ving** [comment]
> Sadly, allowInventory doesn't do this, so this would be a big help for the build function.

... yes it does? This is exactly what allowInventory is for.

> If this is toggled to false, it won't grab needed blocks in the inventory and put them in the hotbar.

And this is exactly how the existing allowInventory works

**Comment by DefyEnjoyCantCode** [comment]
> > Sadly, allowInventory doesn't do this, so this would be a big help for the build function.
> 
> ... yes it does? This is exactly what allowInventory is for.
> 
> > If this is toggled to false, it won't grab needed blocks in the inventory and put them in the hotbar.
> 
> And this is exactly how the existing allowInventory works

really? damn
I'm using Impact, and for me it doesn't grab blocks from the inventory for me, even when allowInventory is on
most recent version of Impact

**Comment by DefyEnjoyCantCode** [comment]
Ok, nevermind, it works
I'm stupid lol
