### ISSUE TITLE
Baritone does not move when mine command is issued

### ISSUE THREAD

**Issue by NO-1-1** [cabaletta/baritone#2161]
When i type the command "mine diamond_ore" for instance, baritone will find all paths to diamond_ore blocks, however, it does not actually move. It has worked before, but stopped working one time, and now it never seems to work. Modifiers are: allowParkour True
allowParkourPlace True
blocksToAvoid False   
blocksToAvoid used to be set to "cave_air' as i thought it would help baritone avoid caves, but this didn't work. Further, this didn't seem to cause the issue as it worked fine even with blocksToAvoid being set to that value. I use the fabric version of baritone for minecraft 1.16.1 on 1.16.3, I'm aware that it's technically being used on the wrong version but it worked perfectly fine before. The other mod I have installed is called "wurst," a hacked client, but no hacks on it are enabled and I usually have it disabled in game. Finally, I have looked at other issues that are exactly the same as mine, but they never get answered. So please try to answer it or dont respond.

**Comment by DefyEnjoyCantCode** [comment]
That's really odd. Are you using Impact's built-in baritone?
If you're using the separate baritone thing, try resetting your settings for Baritone.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)
