### ISSUE TITLE
Make a way for baritone to move its head slower.

### ISSUE THREAD

**Issue by RandomName18** [cabaletta/baritone#2163]
## Describe your suggestion
When either mining or using #sel Baritone would move its head at an instant which triggers some anticheats, if there is a way to make baritone move its head equal to the sensitivity or to a set amount.

## Settings
Like slowpath, you should change how fast it can move its head in seconds/ms

## Context
This could make baritone less noticeable, and the reason for it being added is that on my SMP Im trying to make a perimeter for my wither skeleton farm, however I don't want to place slabs so I thought maybe I could use a world eater of some kind to go from the ceiling to the bottom bedrock, but I found clearing the top section for the world eaters is tricky and time consuming.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
