### ISSUE TITLE
What is the correct way to do a forge build

### ISSUE THREAD

**Issue by lizelive** [cabaletta/baritone#2168]
## What do you need help with?
I am trying to fix baritone-forge 1.15.2 'aa' bug and think I have a workaround, but can't seem to be able to make a forge jar

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Read the instructions

**Comment by lizelive** [comment]
@l1ving  I tried to follow the instructions to the best of my abilities here but they seem to be wrong https://github.com/cabaletta/baritone/blob/1.15.2/SETUP.md as their is no longer a setupDecompWorkspace, and you have recommended in #2110 to just do `./gradlew` build which does not result in the creation of forge artifacts. Which instructions should i follow?

Also the output of following the instructions.

```
PS D:\source\baritone> ./gradlew setupDecompWorkspace

> Configure project :
New Dep: com.github.ImpactDevelopment:Vanilla:1.15.2_mapped_snapshot_20200515-1.15.1

FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupDecompWorkspace' not found in root project 'baritone'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings`
``

**Comment by l1ving** [comment]
> which does not result in the creation of forge artifacts

lol idk

works fine on Linux

**Comment by scorbett123** [comment]
For later versions don't you need to do something like ./gradlew build -Pbaritone.forge_build. But idk, just remembering from #2107.

**Comment by lizelive** [comment]
i tried it on linux even with devspace and stuff. looking at code `./gradlew -P'baritone.forge_build' build` seems like it might be the correct response and does cause it to generate the forge jars, but im not sure that it is the 'correct' way to do this, as it only seems to be used once (i assume one of the plugins must use it)

**Comment by lizelive** [comment]
#1486 is also relevent

**Comment by randomairborne** [comment]
on windows you don't use the ./ afaik

**Comment by l1ving** [comment]
> i tried it on linux even with devspace and stuff. looking at code `./gradlew -P'baritone.forge_build' build` seems like it might be the correct response and does cause it to generate the forge jars, but im not sure that it is the 'correct' way to do this, as it only seems to be used once (i assume one of the plugins must use it)

that's correct I guess. closed as resolved
