### ISSUE TITLE
reopen for issue #2167 as i followed insturtions and it still doen't work

### ISSUE THREAD

**Issue by kety-folf** [cabaletta/baritone#2169]
refer to issue  #2167  for other info not in this report

link to video of me fixing the issue that that person said was causing it when infact it was not
https://drive.google.com/file/d/1d4TzbWgbdPcD4IoPJjnFbxVt3Z3zpADF/view?usp=sharing

**Comment by NatoBoram** [comment]
That should be a comment under #2167, not a new issue
