### ISSUE TITLE
Baritone does not begin movment

### ISSUE THREAD

**Issue by randomairborne** [cabaletta/baritone#2170]
When I type `#mine diamond_ore` after a fresh baritone reinstall, nothing happens. The system renders the path, but never starts moving.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by randomairborne** [comment]
This is  a question because I think its a me issue

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
