### ISSUE TITLE
render goal without motion

### ISSUE THREAD

**Issue by thecakeisalie25** [cabaletta/baritone#2171]
## Describe your suggestion
When you render a goal block (default in green) it does this weird thing where it moves parts of the outline up and down. This would disable that.

## Settings
renderGoalAsStaticCube? renderGoalWithoutMotion? idk

## Context
If I'm mining stone it just kinda sucks a lot real bad.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue, as much as I wanted to.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by thecakeisalie25** [comment]
I can't find the old one, what did you search to find it? I tried "render goal", "goal static", and "goal movement" and didn't find anything relevant, closed or open. Sorry about that.

**Comment by l1ving** [comment]
Oh I misread the original issue. I thought you meant rendering goal without actually moving
