### ISSUE TITLE
My autominer isn't moving the baritone is on on but it doesn't move

### ISSUE THREAD

**Issue by Valix1** [cabaletta/baritone#2176]
## Some information
Operating system:Windows 10
Java version:Latest
Minecraft version:1.16.4
Baritone version:latest
Fabric mods (if used): Sodium, phosphor, lithium

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Unfortunately sodium is not compatible with baritone. If you want to use baritone uninstall it, if that doesn't make it work take out the other two one by one.
