### ISSUE TITLE
Can you use baritone to mine modded ores

### ISSUE THREAD

**Issue by Commmmandotoo** [cabaletta/baritone#2177]
I have been trying to mine modded ores with baritone I have tried to use the full mod name and then the ore but, it still does not work I am using baritone-standalone-forge-1.2.10.

**Comment by l1ving** [comment]
`modid:blockid:damage`

**Comment by Commmmandotoo** [comment]
When I run the command it says no locations for the block even though it is right in front of me

**Comment by SourcedCoded** [comment]
You might not be putting the correct id name

**Comment by Commmmandotoo** [comment]
![image](https://user-images.githubusercontent.com/74387481/99015764-82d79800-250a-11eb-864a-7e2e7714400d.png)
This is the id The command I run is #mine galacticraftcore:basic_block_core:6467
Do you know the correct command?

**Comment by CesiumCs** [comment]
galacticraftcore:basic_block_core:7

**Comment by Commmmandotoo** [comment]
@CesiumCs 
Thank you it works
