### ISSUE TITLE
Suggest why "unable to do it" is reported.

### ISSUE THREAD

**Issue by Fatih120** [cabaletta/baritone#2180]
## Describe your suggestion
When a build fails through the use of Baritone, it would be beneficial to report to the player why the build fails, whether it is an obstruction, missing material, et cetera. Having no verbose output makes troubleshooting difficult. Reporting what block is required or what external factors must be fixed would be helpful.

## Settings
N/A

## Context
"Unable to do it" is a very vague error, especially when old schematics that should be compatible fail even with the proper materials. If there is a failure, this should be able to be traced.

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
# :joy_cat: 

trolled. Yea I hate getting 2984982398498234 different issues with 0 information except the error message and it turns out someone is building a jesus statue inside a fucking lava cast where baritone fails due to liquid

**Comment by Fatih120** [comment]
https://anonfiles.com/R0J6R5p4p2/Fatih_schematic

Would you like to examine this for yourself? I would like more than 0 pieces of information so that I wouldn't have to open it. Thanks in advance.
