### ISSUE TITLE
Baritone veinmining

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#2182]
## Describe your suggestion
Add #set veinmine and #set veinmineKey

## Settings
```
#set veinmine `bool`
#set veinmine `string`
```

## Context
Well... It'll not require users to mash Shift every time the ore is in the viewframe

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I am a lazy arse that wants baritone to mine faster

**Comment by ZacSharp** [comment]
I can only guess the mod you are using, but if I guessed right it should be possible to activate it without pressing shift.

**Comment by TheK0tYaRa** [comment]
It's literally modID:'veinminer' xD

**Comment by ZacSharp** [comment]
Maybe use `/veinminer mode no_sneak`, `/veinminerc released` or `/veinminerc no_sneak`, depending on whether you have it client-side or not?

**Comment by l1ving** [comment]
This it out of scope for Baritone.

**Comment by TheK0tYaRa** [comment]
Well, that's why I used an "enhancement" preset.

**Comment by l1ving** [comment]
Out of scope
