### ISSUE TITLE
#Follow entity ghast returns with a error message in version 1.12.2 

### ISSUE THREAD

**Issue by DezzDox** [cabaletta/baritone#2183]
It says An unhandled exception occurred the error is in your game's log please report this at https://github.com/cabaletta/baritone/issues and my friends have also tried the same thing I have also tried on a different computer and so on its baritone itself.

I did make this bug report a month ago to but it seems like I was misunderstood or I didn't give enough context but this is in version 1.12.2, not the newer Minecraft versions. and it's still there in baritone-standalone-forge-1.2.14

**Comment by BlueBurgersTDD** [comment]
Please send your logs.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
