### ISSUE TITLE
How do I run this without Impact or forge

### ISSUE THREAD

**Issue by capjay45** [cabaletta/baritone#2184]
Impact 1.16.2 isn't out yet and I want to use baritone without forge. Is there a way to do this?

**Comment by l1ving** [comment]
https://www.youtube.com/watch?v=_4eVJ9Qz2J8

**Comment by capjay45** [comment]
I have done all the steps but I can't find baritone in the installations. Any way to fix this?

**Comment by capjay45** [comment]
oh nevermind
