### ISSUE TITLE
Add 1.16.4 .json only support

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2186]
## Describe your suggestion
As shown in Leiji's video (https://www.youtube.com/watch?v=_4eVJ9Qz2J8&ab_channel=LurfJurv), there IS a .json only file for Minecraft 1.16.2, but changing everything inside the .json file Leji provided that has "1.16.2" in it to "1.16.4" doesn't work and results in an error log.

### File after changing:
```
{
  "id": "1.16.4-Baritone",
  "type": "release",
  "inheritsFrom": "1.16.4",
  "jar": "1.16.4",
  "time": "2019-07-23T20:50:21Z",
  "releaseTime": "2019-07-23T20:50:21Z",
  "downloads": {},
  "minimumLauncherVersion": 0,
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
     "--tweakClass",
     "baritone.launch.BaritoneTweaker"
    ]
  },
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
      "name": "cabaletta:baritone-api:1.6",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "https://repo1.maven.org/maven2/"
    }
  ]
}
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 
[**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
