### ISSUE TITLE
Baritone doesnt mine anything.

### ISSUE THREAD

**Issue by boofiboi69** [cabaletta/baritone#2188]
Operating system: Windows 10 20H2
Java version: 1.8.0_271
Minecraft version : 1.16.4
Baritone version: Null version?
Fabric mods: sodium, and inertia client.

Error logs:

[latest.log](https://github.com/cabaletta/baritone/files/5550205/latest.log)

How to reproduce:
 
Be on a skyblock island, and just write #mine dirt..

Modified settings: none

**Comment by GameCenterJerry** [comment]
Are you using fabric loader?

**Comment by boofiboi69** [comment]
I am, and i have fabric API

Also im using baritone built into inertia.

**Comment by l1ving** [comment]
Baritone is incompatible with Sodium
