### ISSUE TITLE
#theme command

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2189]
## Describe your suggestion
Title says it all, allows the user to change the colour of the interface.

## Settings
`#theme` and `#help theme`, eg. `#theme GREEN`, and `#help theme` showing a list of the colours available.

## Context
Just a thought that occurred to me, thought it would be useful to add as users can change the interface to the colours they want. Unless it's left out for a reason, they can change the theme of the chat output [Baritone]

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Not really useful.
