### ISSUE TITLE
Desktop notifications for when path can not be found

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [cabaletta/baritone#219]
Self explanatory. I use a client that sends Windows 10 desktop notifications when a player comes into render distance so I know that it is infact very much possible to send a desktop notification when Baritone can not find a successful path to take. This would save the pain and agony of alt tabbing into your game only to find out you've just been sitting there not moving towards your goal for the past 5 hours or however long you AFKed for.

**Comment by ZeroMemes** [comment]
I know you can do this on windows by creating a ``TrayIcon`` and calling ``displayMessage``. Not sure if this also works on Mac/Linux.

**Comment by S-B99** [comment]
Fixed in #1324
