### ISSUE TITLE
blocksToAvoidBreaking with cleararea

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#2191]
## Describe your suggestion
Currently it seems like blocksToAvoidBreaking with #sel cleararea doesn't work. I'm actually not sure if this is a bug or if this is the intended use. I assumed that maybe this setting was intended to only be used with pathing to locations? If this is actually a bug, please let me know and I'll reupload with the correct settings.

Anyways, if this is not a bug, this is my suggestion:

Have some way to tell baritone you don't want it to remove certain block.

## Settings
which blocks to ignore.

## Context
I want to clear a mountain, but I don't want it to waste its time removing leaves, so I ignore leaves so it does it more efficiently by focusing on logs, dirt, stone, etc.
I have an area I'm trying to clear but mobs keep appearing, so I don't allow baritone to destroy torches.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Known bug
