### ISSUE TITLE
Auto fishing

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#2192]
## Describe your suggestion
Very simple way to have baritone auto fish for you.

## Settings
length of time to fish, items to keep/throwaway, 

## Context
The recent minecraft patch has made afk fishing very difficult. It would be nice if baritone had a auto fish feature where id did it indefinitely.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
i think baritone having an auto fish is out of scope; most clients already have this
