### ISSUE TITLE
Repeated custom tasks

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#2194]
## Describe your suggestion
The ability to 'record' paths/tasks and save them for repetition.

## Settings
Number of times to repeat, variance in path if something gets in the way, whether to stop whole task if you run out of an item for one part of the task, what to record (pathing, clicks, item use, etc)

## Context
Sometimes the pathing that the ai uses to get to goals is not the most efficient. For example, in The End before you have elytra, building bridges to different islands to get places. If I want to return to that place the ai has a hard time finding a route because of the long distance and lack of land. However I know all the bridges, so I could easily record my path once, save it, then use it again later.
Another example may be to set my person to patrol an area to keep certain chunks loaded.
Another example could be to mass craft an item. If I had an auto cobblestone farm. I might record myself going to the chest, taking out cobblestone, going to a crafting table, creating stacks of furnaces, then going to another part of the map to put them in a different chest.
A simpler form of this could be I'm mining very far away and want to walk back to put my items in a chest. I could automate my walk back to put in the chest. Since I cannot see my chest from where I am, I cannot simply use the #click command, instead I need a way for baritone to remember what I clicked before and do that again.
Another simple use could be to use this as an auto clicker. Instead of having a different app on my computer to auto click at a mob spawner, I could afk my character to click every few seconds by recording that action then setting it to repeat.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
