### ISSUE TITLE
Startatlayer not working

### ISSUE THREAD

**Issue by DirtyDave77** [cabaletta/baritone#2198]
## Some information
Operating system: Windows 10
Java version: 
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): impact client

## How to reproduce
cant change #set startatlayer

## Modified settings
buildinlayers true
allowinventory

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

Trying to get this to work so I can #build a large schematic. it completes the first layer but wont advance to the next without verifying all the unloaded chunks.

**Comment by l1ving** [comment]
You missed one
![image](https://user-images.githubusercontent.com/17222512/99571635-8e5f0f00-29a1-11eb-902f-c3570e859151.png)
