### ISSUE TITLE
is startatlayers coming to v1.2.14?

### ISSUE THREAD

**Issue by DirtyDave77** [cabaletta/baritone#2201]
## What do you need help with?

#set startatlayer doesn't seem to be included in version 1.2.14. this would be very helpful for a big build I am trying to complete. any way we can get it added? its in the documentation on here but not in the #set list

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
> any way we can get it added

It's already added. 

> #set startatlayer doesn't seem to be included in version 1.2.14.

It's not.

**Comment by DirtyDave77** [comment]
how is it added to v1.2 but not in the latest build of 1.2?

**Comment by l1ving** [comment]
I have no idea what you're trying to ask.

**Comment by DirtyDave77** [comment]
ok. 
In baritone 1.2.14, there is not a setting listed for startatlayer using #set list. In the documentation on github, it lists the startatlayer as a setting. 
why is it not working in 1.2.14? is it a feature only for 1.6?

**Comment by l1ving** [comment]
> why is it not working in 1.2.14

Because it's not in 1.2.14

> is it a feature only for 1.6?

No, it's on master, meaning it's for 1.2.15
