### ISSUE TITLE
Baritone won't use the right tools

### ISSUE THREAD

**Issue by ashor777** [cabaletta/baritone#2202]
Baritone won't use the tools that I give it in the hot bar.

**Comment by TheMadHau5** [comment]
Maybe you could provide more details?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
