### ISSUE TITLE
New mapArtMode for map art servers.

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#2204]
## Describe your suggestion
I would like baritone to be able to punch the ground when it wants to put a block down for schematica.
it would preferably be a second option under command mapArtMode

## Settings
The setting should be turned on by using command #mapArtMode FlatLands

## Context
I play on a server called Skenia FlatLands it is a serbian server for map art, technically it is an anarchy server but there are some rules for example you have to punch the ground to replace it with another block, you can't build up or down (basically you can only build in 2D) and you can only place limited amount of blocks per second.
a server is for map art(serbian server) where you have only one layer on which you build
I would like if baritone can build on that server
If someone wants to take a look the ip is fl.skenons.com (server is cracked)
Also server is 1.13-1.16.4
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is out of scope for Baritone.
