### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by blackzafiqz** [cabaletta/baritone#2205]
Hi, can you the documentation website? seems down now

**Comment by CesiumCs** [comment]
for more context, the webserver nginx itself is still up, but everything under the baritone.leijurv.com subdomain returns a 404 error

**Comment by l1ving** [comment]
> can you the documentation website? 

# :moyai:

**Comment by l1ving** [comment]
it happens

**Comment by blackzafiqz** [comment]
> it happens

it was 4 am at my place xD. Is there any mirror for the documentation?

**Comment by l1ving** [comment]
No, it goes down every once in a while for a day or so. Have to build it yourself or just wait

**Comment by blackzafiqz** [comment]
what do you means build myself? I can build the docs?

**Comment by blackzafiqz** [comment]
nvm found it #1906
