### ISSUE TITLE
Make path record option

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#2206]
## Describe your suggestion
Baritone should be able to record what ever you did and than just loop the path you took.
There should be an option to allow baritone to path some parts of the path by it self.
Also it should have a waypoint routine where it would path from a waypoint to waypoint in a loop.
It would be nice if it is possible to make baritone do something at a certain waypoint for some time and than go to the next waypoint.
It should record how a player sneaks sprints and rotates...
## Settings
#recordPath [name of path recording]
#loopWP [waypoint 1] [waypoint 2] [waypoint 3] etc
#playPath [name of the path recording] (would play the recorded path)
#doOnWP [command it should do] [for how long it should do the action]

## Context
Useful on anarchy servers for automated patrol, possibility to make automated routine on farming servers for efficient farming, maybe once  #244  is implemented it can be used to have bots do stuff for you as you do something else...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
