### ISSUE TITLE
ToolSaver

### ISSUE THREAD

**Issue by randomairborne** [cabaletta/baritone#2208]
How would one enable the ability to not use tools that are at 1 durability?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#toolSaver

**Comment by randomairborne** [comment]
[Baritone] Command Not Found: toolSaver

**Comment by l1ving** [comment]
Then your version is oudated

**Comment by scorbett123** [comment]
@l1ving, it hasn't yet been merged.

**Comment by l1ving** [comment]
I was thinking of autotool, you're right. My bad, #2107
