### ISSUE TITLE
Game not launching with Bewitchment (1.12.2)

### ISSUE THREAD

**Issue by MarshMello0** [cabaletta/baritone#2215]
When running Bewitchment with Baritone the game window won't even show before it exits with code 1.
I was running this in a mod pack then managed to narrow it down to this mod. It seems like it's something to do with bewitchment and spongepowered mixin stuff (Should I be posting an issue on spongepowered somewhere?).

Both mods work fine when the other one is disabled.

## Some information
Operating system: Windows 10
Java version: Java 8 Update 261
Minecraft version: 1.12.2
Baritone version: Standalone Forge 1.2.13
Forge mods (if used): 
- Baubles 1.12-1.5.2
- Bewitchment 1.12.2-0.0.22.44
- Patchouli 1.0-22
## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5579721/latest.log)
## How to reproduce
1. Install [Bewitchment](https://www.curseforge.com/minecraft/mc-mods/bewitchment/files/3111586)
2. Install Baritone Standalone Forge 1.2.13.jar
3. Try start game
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Won't fix, not much Baritone can do. Bewitchment requires a newer version of Mixins.
