### ISSUE TITLE
Baritone just stops moving after I mine a few blocks

### ISSUE THREAD

**Issue by Tyrannicalz** [cabaletta/baritone#2217]
## Some information
Operating system: Windows
Java version: Latest
Minecraft version: 1.16.3
Baritone version: 1.16.3 one
Forge mods (if used): No forge mod but a few fabric mods (sodium, lithium & a few more)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/5582151/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/5582152/debug.log)

`

## How to reproduce
Type #mine (any block) 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
baritone is not compatible with sodium.
