### ISSUE TITLE
Is opti fabric compatible with baritone?

### ISSUE THREAD

**Issue by Tyrannicalz** [cabaletta/baritone#2218]
## What do you need help with?
Is opti fabric compatible with baritone?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
https://tryitands.ee/

**Comment by l1ving** [comment]
Sodium isn't, and Optifine is way more invasive so it's safe to say it *probably* isn't
