### ISSUE TITLE
Baritone doesn't mine some blocks! 

### ISSUE THREAD

**Issue by Javaisveryhardtoprogram** [cabaletta/baritone#2220]
With Baritone I use it mostly to mine ores and i have a few mods on it but when i tell baritone to mine the block it doesnt know what block it is. The mod that has ores that i want baritone to mine is called: Just a few more ores. And the ore i want it to mine is "black diamond ore" but it cant! Oh and im using 1.12.2. I downloaded the mod from https://www.curseforge.com/minecraft/mc-mods/just-a-few-more-ores/files and like i said baritone wont mine it!!! Please help!

 Here is a photo of the command and the output:
[The Output](https://user-images.githubusercontent.com/75195475/100534687-b3873380-3265-11eb-87e3-eac48042f695.png)
[The command](https://user-images.githubusercontent.com/75195475/100534680-a702db00-3265-11eb-9425-ae98515ab10e.png)

**Comment by l1ving** [comment]
it's `#mine modid:blockid:damage`
