### ISSUE TITLE
Way to change where Baritone starts #build from?

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#2223]
## What do you need help with?
When using the #build command, it starts in a corner.

Two questions:
Where is the origin of the schematic? Which corner does baritone default start from (i.e. if I do "#build blah.schem 10 50 10" then what part of the schematic will be at 10 50 10)?

Is there a way to change the default origin? Like in WorldEdit, the origin starts in the spot that you use the copy command (where you're standing at the time). Would there be a way to use that origin in baritone?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
the corner

**Comment by Colmonkey** [comment]
Is there any rhyme or reason to what corner it starts in or do you have to just guess each time? I'm assuming the answer to my second question is there is no way to change schematic origin?

**Comment by l1ving** [comment]
it's the corner closest to you

**Comment by Colmonkey** [comment]
Sorry, my question was unclear, not where does it start building, but where is the schematic origin in relation to the world origin. Is it always just like the bottom northwest corner of the schematic that lines up with the #build origin? Is there a way to change that? Say I have a schematic that is 25 blocks tall and I wanted to #build at 0 50 0, instead of 50 being the bottom of the schematic, could I tell baritone that is the top of the schematic? Or would I need to dig down and do the #build command at 0 25 0?

I realize I could just use the command #build 0 25 0. However, I don't think thats always intuitive of where thats going to end. Instead of the user doing the math, to figure out where the top is going to end, could the user issue a command that essentially says this is the top (or middle, etc).

There doesn't seem to be much documentation about how the build command actually works, so its mostly just trial and error to get your schematic exactly where you want it, and on really large schematics when buildinlayers isn't working properly it's very cumbersome to have to guess, wait to see if certain blocks end up where you want them and if they don't then restart the whole thing.

**Comment by l1ving** [comment]
>  Is there a way to change that?

No

> Or would I need to dig down and do the #build command at 0 25 0?

Freecam or dig
