### ISSUE TITLE
Baritone crashing when building schematics while using "allowInventory"

### ISSUE THREAD

**Issue by X3RMINATION** [cabaletta/baritone#2226]
## Some information
Operating system:
Windows 10
Java version:
8
Minecraft version:
1.16.2 Fabric
Baritone version:
1.6.2
Forge mods (if used): (Fabric)
appleskin
baritone
bboutlinereloaded
better-enchanted-books
boosted-brightness
CraftPresence
dynamic-fps
fabric-api
horse-stats
light-overlay
litematica
malilib
minihud
modmenu
optifabric
optifine
shulkerboxtooltip
trajectoryfabric
worldedit
## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5619214/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

#build (schematic file)
#allowInventory
when baritone places block game will crash
## Modified settings
To get the modified settings run `#modified` in game
[settings.txt](https://github.com/cabaletta/baritone/files/5619229/settings.txt)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Try removing mods to find out if one of them causes the issue and if so, which mod
Using less modified settings might also help finding the cause

**Comment by X3RMINATION** [comment]
I removed every mod except for fabric api and baritone and it still seems to crash, I also tried redoing the schematic file

**Comment by ZacSharp** [comment]
Then please upload the new log, the new settings (preferably default settings / empty settings.txt) and maybe the schematic.
Baritone doesn't need Fabric API btw

**Comment by Nawor3565** [comment]
Having the same problem, here's my most recent crash log. I'm using 1.16.3, but the exact same thing happens in the most recent Baritone/MC versions.

https://paste.ee/p/qsNYw

**Comment by l1ving** [comment]
Open a proper bug report. 

Re: X3RMINATION closed, reopen with requested information.
