### ISSUE TITLE
Baritone stands still and does nothing when using #mine command

### ISSUE THREAD

**Issue by ThatBenderGuy** [cabaletta/baritone#2227]
## Some information
Operating system: Windows 10
Java version: 1.8.0
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): https://www.modpackindex.com/modpack/21762/technical-electrical-vi

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5624891/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/5624893/debug.log)

## How to reproduce
Type in #mine <any_ore> and the bot finds ore and a path to them but just stands there doing nothing

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by randomairborne** [comment]
are you using fabritone and sodium?

**Comment by ThatBenderGuy** [comment]
> are you using fabritone and sodium?

Idk what either of those are. I'm assuming fabritone is a fabric version of baritone but I have no clue what sodium is

**Comment by SouthernPixel** [comment]
I am having the same issue except im using #sel cleararea and it mines for a bit but then quits moving or just goes to a unnecessary location

**Comment by l1ving** [comment]
Fabritone is deprecated iirc, use Baritone

**Comment by qwertaii** [comment]
> I am having the same issue except im using #sel cleararea and it mines for a bit but then quits moving or just goes to a unnecessary location. Im using Fabritone 1.6.1

Also having this issue using Baritone 1.6.2, "#sel ca" mines everything within reach and then just stops.

**Comment by jhonnystene** [comment]
I am having the same issue on Baritone 1.6.2 on Minecraft 1.16.4. Exact same issue as @qwertaii.

**Comment by BlockOG** [comment]
> Fabritone is deprecated iirc, use Baritone

What if I want to have Some fabric mods?

**Comment by l1ving** [comment]
On Fabric.

**Comment by BlockOG** [comment]
Ok for me the reason that it didn't work was that I had Sodium I took it out and it works now :D

**Comment by SkilledAlpaca** [comment]
> > I am having the same issue except im using #sel cleararea and it mines for a bit but then quits moving or just goes to a unnecessary location. Im using Fabritone 1.6.1
> 
> Also having this issue using Baritone 1.6.2 (forge ver), "#sel ca" mines everything within reach and then stops.

If I bump into the bot or move the bot myself they start mining again. I've st the `blockReachDistance` between 2 and 5. Not sure why it's stopping. I only have Forge and Baritone installed. No other mods.

**Comment by ZekerDEATH** [comment]
I'm having this issue with ca and set air and nothing fixes it PLEASE HELP

**Comment by scorbett123** [comment]
This is a known issue to-do with cave air,   there is currently a pr that fixes it.

**Comment by ZekerDEATH** [comment]
> This is a known issue to-do with cave air, there is currently a pr that fixes it.

I'm sorry, a pr? And I'm running Impact generally, would there be a way to incorporate what you speak of into it?

**Comment by scorbett123** [comment]
You would have to build baritone yourself, I have misremembered there isn't a pr, but you would have to use #2323 and run buildValidSubstitutes air->cave_air.

There are instructions on how to do this and build for yourself in this issue or follow the build it yourself instructions here : https://github.com/cabaletta/baritone/blob/master/SETUP.md

**Comment by ZekerDEATH** [comment]
> You would have to build baritone yourself, I have misremembered there isn't a pr, but you would have to use #2323 and run buildValidSubstitutes air->cave_air.
> 
> There are instructions on how to do this and build for yourself in this issue or follow the build it yourself instructions here : https://github.com/cabaletta/baritone/blob/master/SETUP.md

I'm having some trouble figuring that out but thanks anyhow

**Comment by ZekerDEATH** [comment]
> You would have to build baritone yourself, I have misremembered there isn't a pr, but you would have to use #2323 and run buildValidSubstitutes air->cave_air.
> 
> There are instructions on how to do this and build for yourself in this issue or follow the build it yourself instructions here : https://github.com/cabaletta/baritone/blob/master/SETUP.md

okay so I'm not really understanding how to do this, and what does #2323 have to do with it?

**Comment by scorbett123** [comment]
#2323 is the issue that is discusing how to fix something that would also fix this issue.

**Comment by ZekerDEATH** [comment]
ah

**Comment by ZekerDEATH** [comment]
i take it i won't be able to do that then, bc im really unsure of how. when do you think itll get patched?

**Comment by ZekerDEATH** [comment]
> #2323 is the issue that is discusing how to fix something that would also fix this issue.

if you wouldnt mind, could i have a step by step on what im doing to make a build that fixes the issue?

**Comment by l1ving** [comment]
you can find a step by step [here](https://github.com/cabaletta/baritone/blob/master/SETUP.md)

**Comment by ZekerDEATH** [comment]
> you can find a step by step [here](https://github.com/cabaletta/baritone/blob/master/SETUP.md)

maybe im just too stupid because I'm having a lot of trouble following what to do. I'm on windows.
