### ISSUE TITLE
API fails to load

### ISSUE THREAD

**Issue by DontHUrTMe** [cabaletta/baritone#2229]
Operating system: Windows 10
Java version: 1.8.0 212
Minecraft version: 1.16.2
Baritone version: 1.6.1
Forge version: 33.0.61
Forge mods (if used): Only an empty mod, that i'm trying to write

## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
When loading Forge the runClient task gets the following error: Process 'command 'C:\Program Files\Java\jdk1.8.0_212\bin\java.exe'' finished with non-zero exit value 1
I have no idea, why this happens.

I only get this error: [03:16:22] [main/ERROR] [mixin/]: Mixin config mixins.baritone.json does not specify "minVersion" property

Pastebin to logs: https://pastebin.com/wJGFukaJ

If you have any idea why this happens, please help me.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
See comment in #2168

**Comment by DontHUrTMe** [comment]
@l1ving This helped me compile, however the shadowjar now fails to load. I think its a problem with my poor configuration, but its not essential for now. My only problem now is, that I cannot use runClient. Can you suggest a solution for that?
Thanks in advance.

**Comment by l1ving** [comment]
I've personally never had runClient reliably work, I instead use the Minecraft Client profile inside intellij, you need to genIntellijRuns and reimport the project for it to work

**Comment by DontHUrTMe** [comment]
This method compiles too without the -P'baritone.forge_build' argument, and I cant find where to add this.

**Comment by l1ving** [comment]
In the compile arguments
