### ISSUE TITLE
Can't Build Baritone 1.15.2: Missing Impact Vanilla repo for Baritone 1.15.2

### ISSUE THREAD

**Issue by ralphchristianeclipse** [cabaletta/baritone#2235]
Currently missing a repository while building on branch 1.15.2

![image](https://user-images.githubusercontent.com/25447231/101051220-2ffc7800-35c0-11eb-99a9-791cf93dbede.png)

**Comment by l1ving** [comment]
Post your build.gradle on a pastebin

**Comment by ralphchristianeclipse** [comment]
https://github.com/cabaletta/baritone/blob/1.15.2/build.gradle @l1ving  i'm just using the one that's on the repo

well anyways here is it on pastebin

https://pastebin.com/iLy3YE20

**Comment by ralphchristianeclipse** [comment]
@l1ving it works now thanks :)
