### ISSUE TITLE
'dewspawn' an area

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#2236]
## Describe your suggestion
Use slabs or carpet on all surfaces in an area so mobs cannot spawn there.

## Settings
items to use
use selection or distance from feet
height range to despawn

## Context
Many times when making farms its helpful to make so no mobs are able to spawn anywhere nearby. An example is when making a wither skeleton farm, people usually put slabs on all the ground all around the area. Instead this could be automated so Baritone did all the pathing and found all the 'spawnable' blocks in a radius and put slabs, carpets, or something else on them.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
#1347?

**Comment by l1ving** [comment]
and #971
