### ISSUE TITLE
Is it possible to fork baritone and install the fork on top of an already installed Impact instance?

### ISSUE THREAD

**Issue by mvrozanti** [cabaletta/baritone#2238]
## What do you need help with?
I want to make a Command that scans for chests in close proximity with each other and when it is true, stop all movement or disconnect or something like that. A personal, custom Command not necessarily suitable for the original repo. 

I'm trying to figure out what's the installation process when I already have Impact installed.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md#more-info

**Comment by mvrozanti** [comment]
thanks!
