### ISSUE TITLE
Baratone Vs Minecart Chest

### ISSUE THREAD

**Issue by Johnathan356654** [cabaletta/baritone#2239]
is their anyway i can make baritone hunt down and destroy minecart chests from mineshafts?

**Comment by randomairborne** [comment]
You can couple the follow command with a kill aura set to kill minecarts.

**Comment by Johnathan356654** [comment]
> You can couple the follow command with a kill aura set to kill minecarts.

How do i use the follow command?

**Comment by randomairborne** [comment]
#follow entity chest_minecart
