### ISSUE TITLE
Where in the code is the system that searches for and highlights entities during #follow?

### ISSUE THREAD

**Issue by randomairborne** [cabaletta/baritone#2240]
## What do you need help with?
I would like to know a small about about what files the entity highlighter is located in.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
![Screenshot_20201205-214320.png](https://user-images.githubusercontent.com/17222512/101270036-f43deb80-3742-11eb-84f1-5b1e7076b7eb.png)
