### ISSUE TITLE
Keeps getting stuck when jumping

### ISSUE THREAD

**Issue by Vukovii** [cabaletta/baritone#2242]
Whenever I do the #mine command if it has to go up a block it just stops and my screen starts to shake.  I'm using the latest version of baritone and Minecraft.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
