### ISSUE TITLE
Speed Hacks+ Barittone

### ISSUE THREAD

**Issue by ApposModding** [cabaletta/baritone#2245]
With Meteor Client (Fabrittone)
WHENEVER I use speedhacks, the bot gets stuck on the edge of a block and shakes like crazy
(Fabrittone devs WILL not patch this)
Can also affect other clients.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
