### ISSUE TITLE
Spawn proofing and lighting mines

### ISSUE THREAD

**Issue by ismailsultan** [cabaletta/baritone#2246]
umm this is actually a suggestion or enhancement.
one of the commands that baritone has is the **MINE** command and one of the issues that this command has is that sometimes mob spawn in the mine due to the low light level. So you can add a setting which places torch every 8 blocks or so through which the player can mine safely.My second suggestion is that you can add another feature in which we can specify the radius and baritone automatically spawn proof that area(by placing buttons or carpets) which can really help in making redstone mob farms/
i really would like these features and hope to see them in the mod.

**Comment by scorbett123** [comment]
Both of these have already been suggested.

**Comment by ismailsultan** [comment]
ok ill delete then

**Comment by l1ving** [comment]
#971
