### ISSUE TITLE
How to create a visualization of cached chunks?

### ISSUE THREAD

**Issue by mvrozanti** [cabaletta/baritone#2247]
## What do you need help with?
I want to use the cached chunks to create an image to visually represent what chunks have been visited. Is this currently possible, using the *.bcr files generated?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Yea, this was possible at some point. I don't think it was ever merged into master due to stability?

https://www.youtube.com/watch?v=FyBP_IUkY9o

**Comment by mvrozanti** [comment]
Sorry, that's not what I meant. 

I want to serialize the chunks to an image file, not render it in-game. The functionality should work as described in this [Impact issue](https://github.com/ImpactDevelopment/ImpactIssues/issues/2713)

**Comment by mvrozanti** [comment]
Like, I'd imagine that if we take the top-side texture of each block that is immediately under the highest air block in a given X,Z coordinate (or if it _is_ the highest block at that location), we can stitch an image that represents it correctly. 

We could worry about block rotation in the future, if that works.

**Comment by mvrozanti** [comment]
Only problem is, I have no idea how to read .bcr files

**Comment by l1ving** [comment]
Baritone doesn't have a way to do this

**Comment by mvrozanti** [comment]
I thought bcr stands for baritone cached region, does it not?

**Comment by l1ving** [comment]
idk lol, but Baritone doesn't have a way to *visualize* it as far as I know

**Comment by mvrozanti** [comment]
Can we extract every `BlockPos` from a bcr file? Because if so, we _can_ visualize it with a little effort

**Comment by l1ving** [comment]
maybe, the code would probably help more

**Comment by mvrozanti** [comment]
I'm gonna try and see how to read a bcr and reply back here

**Comment by mvrozanti** [comment]
```
        ICachedRegion cr = ctx.worldData().getCachedWorld().getRegion(0, 0);
```

This is pretty much it. We just need to:

1) List every cached region for current server
2) For each region, extract every block contained in it
3) For every block in the region map the image for that block in the correct relative position
4) Save that to a png

**Comment by l1ving** [comment]
I mean, would be nice to have

**Comment by mvrozanti** [comment]
Textures can be found at .minecraft/versions/1.15.2.jar/assets/minecraft/textures/block/

**Comment by ZacSharp** [comment]
for me #66 looks similar to this

**Comment by mvrozanti** [comment]
@ZacSharp It really does. But development on that issue seems discontinued? 

It also seems overcomplicated. Why bring a  "Web UI"  into it?

**Comment by ZacSharp** [comment]
Well, development is really discontinued there :smiley:
They didn't touch the Web UI there, just talk about it. I also think the goal seems to be slightly different (you want to create a image that contains all faces with full resolution, oldgalileo kinda tried to mimic the vanilla map behaviour) and the bitwise operations are there to assemble r, b and g values into one rgb value.
Yes there is no issue for it because it is perfectly possible to just start developing a feature without opening an issue first.

**Comment by mvrozanti** [comment]
Good point. I assume we could use a single pixel for each block and the color of that pixel could be the average color in that block's texture.

**Comment by l1ving** [comment]
Imo I'd love an option for full textures, even if it takes a while to export would be cool for making desktop wallpapers

**Comment by mvrozanti** [comment]
The part I'm most interested in right now is how to calculate the coordinates of the corners of a given region.

**Comment by mvrozanti** [comment]
How do we get block id from a `Block`?

**Comment by l1ving** [comment]
I'd rely on your IDEs autocomplete for that. I'm on mobile otherwise I'd check myself

**Comment by mvrozanti** [comment]
Assuming the above is correct, the following code gets every `Block` for a given region.

```
        Map<String, int[]> cornerBlockCoordinatesForZeroZero = getBlockCoordsOfChunkCorners(0, 0);
        int[] nw = cornerBlockCoordinatesForZeroZero.get("NW");
        logDirect("nw=" + nw[0] + "," + nw[1]);
        logDirect("ne=" + ne[0] + "," + ne[1]);
        logDirect("sw=" + sw[0] + "," + sw[1]);
        logDirect("se=" + se[0] + "," + se[1]);


        for (int x = nw[0]; x < nw[0] + 512; x++) {
            for (int z = nw[1]; z < nw[1] + 512; z++) {
                for (int y = 256; y > 0; y++) {
                    BlockState bs = cr.getBlock(x, y, z);
                    if (bs == null) {
                        logDirect("bs can be null");
                        return;
                    }
                    Block b = bs.getBlock();
                    if (b == null) {
                        logDirect("b can be null");
                        return;
                    }
                    if (b != null && !(b instanceof AirBlock)) { // we must show this block
                        // must get block ID to get its texture
                    }
                }
            }
        }
```

I just can't find the (obvious yet nonexistent) `Block#getID`.

**Comment by mvrozanti** [comment]
There's `Block.BLOCK_STATE_IDS#get`, but it returns an integer. I'd like the namespaced ID.

**Comment by mvrozanti** [comment]
This is a very crude way of getting all the namespaced IDs we need.

```
        String[][] topView = new Block[512][512];
        for (int x = nw[0]; x < nw[0] + 512; x++) {
            for (int z = nw[1]; z < nw[1] + 512; z++) {
                for (int y = 256; y > 0; y--) {
                    BlockState bs = cr.getBlock(x, y, z);
                    String blockID = bs.toString().substring(6, bs.toString().length() - 2); // regex is slower
                    Block b = bs.getBlock();
                    if (!(b instanceof AirBlock)) { // we must show this block
                        topView[x][z] = blockID;
                        break;
                    }
                }
            }
        }
```

**Comment by mvrozanti** [comment]
![mta](https://user-images.githubusercontent.com/11381662/101994651-ba209c80-3ca2-11eb-86c7-972edde9116f.png)

This is region 0,0 of my favorite server.

**Comment by ZacSharp** [comment]
Shouldn't the image be coloured?

**Comment by ZacSharp** [comment]
> bitmap is an interesting one because we don't have to have the image loaded to append to it

As far as I know that's only half true. We can in fact just append new lines to the bottom of it but when we want to append to the side we need to rewrite the whole file. It still has a benefit over the compressed formats because we don't need to have it loaded at once even when appending to the side. We can just read it line by line and write every line plus our addition straight to the output and forget them (which results a lot of IO operations though).

**Comment by mvrozanti** [comment]
> Shouldn't the image be coloured?

Yeah, I'm not really sure why it didn't turn out to be colored inside the square. The rest being black is expected though, since it's all bedrock (or, its average color).

**Comment by ZacSharp** [comment]
`Color(sumr / num, sumg / num, sumb / num)`
Because you are using `int` for `sumr`, `sumg`, `sumb` and `num` the result of the divisions is trucated to be an in as well. You need to make at least one of the variables in each division (I suggest num because it is used in all of them) to float or double so the result is a float/double.

**Comment by mvrozanti** [comment]
My mistake, well pointed out

**Comment by mvrozanti** [comment]
I'm closing this because there's absolutely no way I'm solving this problem on my own.
