### ISSUE TITLE
Joining servers from development enviroment

### ISSUE THREAD

**Issue by ZacSharp** [cabaletta/baritone#2251]
## What do you need help with?
I want to test a pull on a server and because I don't want to do the full build + copy into mods + restart minecraft process every time I tried to just join the server when running minecraft using `./gradlew runClient`.
On all servers I tried (even those that don't exist, e.g. localhost without a local server) it got stuck on `connecting` and printed
```
[01:56:18] [main/INFO]: Connecting to localhost, 25565
[01:56:18] [Server Connector #1/INFO]: [STDERR]: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiScreen.mc from class net.minecraft.client.multiplayer.GuiConnecting$1
[01:56:18] [Server Connector #1/INFO]: [STDERR]: 	at net.minecraft.client.multiplayer.GuiConnecting$1.run(SourceFile:58)
```
Since this did not happen with a different workspace and `net.minecraft.client.gui.GuiScreen` is a class Baritone uses Mixin on I wondered if this is Baritones fault.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used more than two OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
1. Don't use runClient
2. The current steps [here](https://kamiblue.org/contributing) will work. Note: this website is being rewritten very soon, and that page will have it's instructions drastically changed, for future reference. 
3. You want to add a --username and --password to the launch arguments in Minecraft Client

**Comment by ZacSharp** [comment]
1. The Baritone build instructions and even your guide tell me to use runClient when I look for instructions for anything other than IDEA, which I am definitely not using. If you want me to use something else then come up with a solution that works with bash.
2. I followed the instructions there and after a `./gradlew clean` it still did not work.
3. I have a username set and the server is cracked but it doesn't even get to the authentication part anyway (it doesn't even check if the server exists)

**Comment by ZacSharp** [comment]
Using the eclipse setup and then plain runClient worked

**Comment by l1ving** [comment]
> If you want me to use something else then come up with a solution that works with bash.

Lol good luck. ForgeGradle is a fucking pain in the ass, you'll need to update Baritone to FG3 if you want runClient to work consistently
