### ISSUE TITLE
Automatic Captcha/Maptcha code.

### ISSUE THREAD

**Issue by Mysteriusss** [cabaletta/baritone#2252]
## Describe your suggestion
I suggest that there can be option to turn on automatic captcha/maptcha code solver. A lot servers have protection againts "automated movements" it can recognize if players is playing or its some sorf of mod/software".

## Settings
It can be turn on/off by #captcha

## Context
This can rly help with automation overall.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
no
