### ISSUE TITLE
Check block is reachable without additional mining

### ISSUE THREAD

**Issue by maxsupermanhd** [cabaletta/baritone#2253]
Hello there, I want to enchant mining process to filter ores that are not reachable (not able to mine them without mining additional blocks). I looked at some classes but did not found such an algorithm. Also want to make it configurable and open pull request.

- [x] I did search by project
- [x] I tried to reverse whole thing how baritone starts *mining*, not super successful as you can imagine
- [x] Noob in java, know C well

**Comment by l1ving** [comment]
`#allowBreak false`

**Comment by maxsupermanhd** [comment]
Oh... I've missed that one, thanks.

**Comment by PoloAC** [comment]
When I turn allowbreak false, the mine function wont work.
