### ISSUE TITLE
Baritone won't move

### ISSUE THREAD

**Issue by alpitu21** [cabaletta/baritone#2255]
## Some information
Operating system: windows 10
Java version: latest
Minecraft version: latest
Baritone version: null version
Forge mods (if used): sodium, inertia

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
there's no crash ;-;

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I do #follow player Aladin321 (my friend) and a path creates (red line) but it won't move.
I do #mine iron_ore and it won't break anything or move, but if i'm right next to iron ore it breaks it.
i do #goto (my coords) and a path creates (red line) but it won't move...

## Modified settings
To get the modified settings run `#modified` in game
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
> Forge mods (if used): sodium, inertia

ive heard theres some weirdness with baritone and sodium, try removing that

**Comment by l1ving** [comment]
Sodium breaks Baritone movement.
