### ISSUE TITLE
#mine option for maxYlevel the bot will go

### ISSUE THREAD

**Issue by Tanju42** [cabaletta/baritone#2256]
I wanna mine Ancient_Debris at y level 14 but the bot always trys to go up where he finds some ancient debris
So I want an option like
maxYlevel = 20
Then the bot will not pathfind anything above 20

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
