### ISSUE TITLE
#mine improvment: maxYlevel

### ISSUE THREAD

**Issue by Tanju42** [cabaletta/baritone#2258]
## Describe your suggestion
maxYlevel function so the #mine function wouldnt go above that

## Settings
maxYlevel = 0 - 256

## Context
It would stop the glitched pathfinding for ancient deprise 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#2256??

**Comment by l1ving** [comment]
wait hold on I can't read

**Comment by l1ving** [comment]
#1883
