### ISSUE TITLE
Baritone crashes after using fill command

### ISSUE THREAD

**Issue by luthfiandam** [cabaletta/baritone#2259]
## Some information
Operating system: Windows 10 Pro 64 bit (build 17763)
Java version:  
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
Minecraft version: 1.16.4
Baritone version: 1.16.4
Forge mods (if used): I'm using aristois client and install the baritone addons.

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5684545/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
So i marked an area using sel p1 ~ ~ ~ and sel p2 ~ ~ ~
when i type "sel fill stone" .. the game crash

## Modified settings
none of the settings i modified

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 970037201** [comment]
I have the same error - Something about a NULL pointer.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
