### ISSUE TITLE
Ability to craft/smelt

### ISSUE THREAD

**Issue by TheArcaneBrony** [cabaletta/baritone#2260]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
When building a schematic/filling an area, I would like Baritone to be able to craft for example hoppers, or smelt iron ore to do so.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
[optional] ability to disable this

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by NatoBoram** [comment]
Duplicate of #295

**Comment by Jimin69** [comment]
b
