### ISSUE TITLE
Multi aia acc baritone thing

### ISSUE THREAD

**Issue by astriogamer** [cabaletta/baritone#2262]
## What do you need help with?
I saw a video from along time with multi baritone bots going to 0,0. I was wondering how to do this? or was that idea scrapped and deleted. (was prefer plain baritone/interia client cause impact not 1.16.4 :()
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
ow

**Comment by scorbett123** [comment]
This was the bot-system branch. It doesn't quite fully work so hasn't been merged into master, however it hasn't been deleted.

**Comment by l1ving** [comment]
bot-system branch
