### ISSUE TITLE
Responding to commands without prefix

### ISSUE THREAD

**Issue by CptDinosaur** [cabaletta/baritone#2263]
## Some information
Operating system: Windows 10 64-Bit
Java version: 8 update 271
Minecraft version: 1.16.4
Baritone version: 1.6.1
Forge mods (if used): None, other than baritone

## How to reproduce

1. Type in chat #stop, baritone responds
2. Type in chat stop, baritone still responds
3. Toggle prefixControl true and false, neither stops baritone responding to commands without a prefix

This might be intended behavior, not sure. But not being able to say "help" or "stop" is irritating. Or, I've missed a setting to change this. All I could find is prefixControl, that seems to match this issue.

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CptDinosaur** [comment]
Nevermind, setting chatControl to false fixes this. I'd assumed that turning chatControl off was in order to only interface with baritone via other mods.

**Comment by ZacSharp** [comment]
No
chatControl -> without prefix
prefixControl -> with prefix
chatControlAnyways -> override chatControl to true
