### ISSUE TITLE
how to use bot-system

### ISSUE THREAD

**Issue by astriogamer** [cabaletta/baritone#2264]
I saw the bot system thigny. now i need help on how to use it/ install it
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
[README.md](https://github.com/cabaletta/baritone/tree/bot-system#getting-started)

**Comment by astriogamer** [comment]
wait that doesnt help for the bot-sytem

**Comment by CesiumCs** [comment]
if you looked you'd find your way to how to build from source

**Comment by astriogamer** [comment]
oop
damn this crap is hard.
i was gunna troll on my friends mc sevre but it seems wayyy to complcated

**Comment by CesiumCs** [comment]
literally just running [three commands](https://github.com/cabaletta/baritone/blob/bot-system/SETUP.md#command-line)

**Comment by astriogamer** [comment]
windows 10 support or nah?
cause all i saw was linux 0_o

**Comment by CesiumCs** [comment]
yes 0_o

**Comment by astriogamer** [comment]
were do we run da command?

**Comment by l1ving** [comment]
a terminal

**Comment by astriogamer** [comment]
i wasnt done yet :(
