### ISSUE TITLE
(continuned) Can i start up the 3 lines of code thingy with VSC?

### ISSUE THREAD

**Issue by astriogamer** [cabaletta/baritone#2265]
MY dumbass is so smort idk anything about coding.
i saw to like start the code you can type 3 lines of code in a terminal.
if i am correct VSC has terminal. would it work there?
or pls give me simple intructions cause i cannot read
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If it is really just a console using your system path you can use it.
Otherwise I'm on linux myself but a quick search brought me to this: 
press Win+R and enter cmd

**Comment by astriogamer** [comment]
system path as in system 32 correct?

**Comment by ZacSharp** [comment]
That's to much detail for me to know it.
Just try running the commands in your repository.
And from what a search for "system 32 path" told me I guess that folder is on the search path, alongside some other folders for the non-system commands.

**Comment by l1ving** [comment]
This isn't really a Baritone question, if you're unsure how to use a terminal you have to google that yourself. Or you could use something like Intellij to do the work for you
