### ISSUE TITLE
Can't make a list of blocks to ignore mining with #blocksToAvoidBreaking

### ISSUE THREAD

**Issue by SouthernPixel** [cabaletta/baritone#2266]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

How do I make a list of blocks to ignore with #blocksToAvoidBreaking? I tried put for example "#blocksToAvoidBreaking iron_block beacon" but it says command not found. I tried with and without a comma and neither work

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by SouthernPixel** [comment]
You closed this question before i could reply.

Im just simply trying to add a list of blocks to make baritone not be able to mine
I type "#blocksToAvoidBreaking iron_block" so it sets that as a block it cant mine but if i type "#blocksToAvoidBreaking iron_block beacon" you know, trying to make a list instead of just one block then it just says command not found.

**Comment by l1ving** [comment]
#2267
