### ISSUE TITLE
Cant make a list of blocks for #BlocksToAvoidBreaking

### ISSUE THREAD

**Issue by SouthernPixel** [cabaletta/baritone#2267]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
You closed this question before i could reply.

Im just simply trying to add a list of blocks to make baritone not be able to mine
I type "#blocksToAvoidBreaking iron_block" so it sets that as a block it cant mine but if i type "#blocksToAvoidBreaking iron_block beacon" you know, trying to make a list instead of just one block then it just says command not found.
https://imgur.com/a/QqBUwGE

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I don't know why it says "Command not found" since "Too many arguments" would be more accurate.
The list is a single argument (no spaces) with comma separated values.

**Comment by SouthernPixel** [comment]
oh so you don't put a space after the comma? Ok, thank you.
Why does it still try to mine my beacons though?

**Comment by ZacSharp** [comment]
I don't know exactly why but I've seen a lot of issues on this get closed as "known bug"
But in your case it might be because schematic building (and `#sel` build dynamically created schematics) seems ignores that.
There should be a setting called `buildIgnoreBlocks` so the builder does not care about your beacons.

**Comment by SouthernPixel** [comment]
It also says #BuildingoreBlocks is not found.
Ok

**Comment by ZacSharp** [comment]
it also takes a single list argument
for me `buildIgnoreBlocks iron_block,beacon` worked

**Comment by l1ving** [comment]
> oh so you don't put a space after the comma? Ok, thank you.
> Why does it still try to mine my beacons though?

Known bug
