### ISSUE TITLE
Baritone commands not working or am i just stupid

### ISSUE THREAD

**Issue by Austruss** [cabaletta/baritone#2268]
if i type a baritone command like #goto ... ... it just types it in chat. It does show up in the mods section/settings of forge. please help

**Comment by l1ving** [comment]
It's not supposed to show up in the Forge mod list.

Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
