### ISSUE TITLE
My game keeps crashing. 

### ISSUE THREAD

**Issue by Relbu** [cabaletta/baritone#2269]
## Some information
Operating system: Windows 10
Java version: "1.8.0_271"
Minecraft version: 1.12.2
Baritone version: All versions ive used. 
Forge mods (if used): 

## Logs

[latest.log](https://github.com/cabaletta/baritone/files/5697736/latest.log)

## How to reproduce
This is an issue ive had for several months. I can run any version of baritone, it being inside of a client or used as an api. And It'll always crash. It crashes when i joined a server or world, sometimes i can walk around for 10 seconds but in the end it still crashes. I am doing nothing ingame in which could cause a crash. In the logs you will only see crashes from API most likely but other versions still crashed my game. 

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [OwO] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
1. Stop using pirated software
2. Stop using horrible KAMI skids which try catch 30 thousand fucking lines of stacktraces

**Comment by linustouchtips** [comment]
> 1. Stop using pirated software
> 2. Stop using horrible KAMI skids which try catch 30 thousand fucking lines of stacktraces

how about giving actual support instead of jumping to conclusions. he's using a custom base client which uses the baritone API, not pirated or a skid of your shitcode client.

**Comment by Jumpinqq** [comment]
> > 1. Stop using pirated software
> > 2. Stop using horrible KAMI skids which try catch 30 thousand fucking lines of stacktraces
> 
> how about giving actual support instead of jumping to conclusions. he's using a custom base client which uses the baritone API, not pirated or a skid of your shitcode client.

i second this, fuck kami blue

**Comment by l1ving** [comment]
> how about giving actual support

I gave you actual support. Stop using pirated software and software that prints 30 thousand lines of stacktraces on startup.

**Comment by linustouchtips** [comment]
> > how about giving actual support
> 
> I gave you actual support. Stop using pirated software and software that prints 30 thousand lines of stacktraces on startup.

ctrl f exists

**Comment by linustouchtips** [comment]
also he gets the same crash with impact

**Comment by l1ving** [comment]
That does not matter. Stop using pirated software *alongside* Baritone.

**Comment by linustouchtips** [comment]
I'm interested to hear why you think the client is kami

**Comment by scorbett123** [comment]
Looking at this log I don't think that this is a baritone issue. If this is a custom client then he shouldn't be happy with the people who made it, there is about  500 errors inside that log, all occurring from this "momentum" client. The crash could occur from anywhere inside these logs. Even though the end thing is baritone crashes if the writer even ran the client I would be surprised, that sort of thing is a stain on the Minecraft modding community. However I do have to agree with you that it isn't a Kami skid due to it being written in java not kotlin, however that doesn't excuse the mess that that client is.

**Comment by l1ving** [comment]
KAMI was originally in Java, including the Linus-MHACK-beta3.jar which I have :p

As for the actual issue, they're using shitty pirated software which requires -noverify, which is incompatible with Baritone

**Comment by linustouchtips** [comment]
oh you were referring to future, mb lol. i agree but they removed future and got the same crash. they also got a similar crash using impact.

**Comment by linustouchtips** [comment]
> Looking at this log I don't think that this is a baritone issue. If this is a custom client then he shouldn't be happy with the people who made it, there is about 500 errors inside that log, all occurring from this "momentum" client. The crash could occur from anywhere inside these logs. Even though the end thing is baritone crashes if the writer even ran the client I would be surprised, that sort of thing is a stain on the Minecraft modding community. However I do have to agree with you that it isn't a Kami skid due to it being written in java not kotlin, however that doesn't excuse the mess that that client is.

<img width="377" alt="Screen Shot 2020-12-16 at 11 53 46 AM" src="https://user-images.githubusercontent.com/68214996/102399348-5d203180-3f95-11eb-8295-589cefdf263c.png">

those stack traces are from this, which has since been removed. still doesn't explain why he had crashes with impact.

**Comment by l1ving** [comment]
> still doesn't explain why he had crashes with impact.

I already explained it, use your eyes.

**Comment by Jumpinqq** [comment]
> 

> 

> 

> [``](

- 

1. url

)
