### ISSUE TITLE
Build schematic at player position

### ISSUE THREAD

**Issue by Talhoid-Coder** [cabaletta/baritone#2270]
I'm going to build a schematic with baritone in the future and the in the videos i've seen baritone goes to the origin of the schematic and not the player position.
Can I make baritone build the schematics at the current player position?
-Talhoid

**Comment by l1ving** [comment]
`#build name.schematic`

**Comment by Talhoid-Coder** [comment]
That builds the schematic at the _schematic_'s origin, not the _player_'s positon

**Comment by l1ving** [comment]
`#build name.schematic x y z` 

Try reading the docs
