### ISSUE TITLE
low fps in servers

### ISSUE THREAD

**Issue by undertalez9** [cabaletta/baritone#2272]
## Some information
Operating system: Windows 10
Java version: jre_271
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): almost 30 mods. (cant write)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
(no log)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
#mine (block)
## Modified settings 
To get the modified settings run `#modified` in game

## Final checklist
- [] I know how to properly use check boxes 
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Incomplete template, closing.
