### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by SouthernPixel** [cabaletta/baritone#2273]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
You keep closing the conversation before I can even reply and before the issue is even resolved.
I could'nt make a list for #blockstoavoidbreaking but now I can but i am still having the issue of not being able to prevent baritone from mining those blocks entirely. I have iron_block and beacon on that list and it still pathfinds to my beacons when i use #sel cleararea
Please this issue is not resolved yet so please stop closing it when its not resolved yet. If its a well known bug then say it dont just close the conversation without any explanation or reasoning
Not trying to be be rude im just annoyed

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Send a screenshot of `#modified`

**Comment by ZacSharp** [comment]
And by the way you can continue a conversation on closed issues. If you think an issue has not been resolved then try convincing the maintainers that it is not resolved so they reopen it.

**Comment by SouthernPixel** [comment]
Thank you for replying. Well I did reply on a closed topic but nobody is replying back because its closed. Here is the screenshot https://imgur.com/a/rqYlMOZ

**Comment by l1ving** [comment]
Send your baritone settings

**Comment by SouthernPixel** [comment]
Do you mean the Baritone world folder or a screenshot of my settings?

**Comment by l1ving** [comment]
The settings file

**Comment by SouthernPixel** [comment]
oh ok here it is https://drive.google.com/file/d/1Yt25fGX_4J7hxyqDZJaa8STXLKe-AnKZ/view?usp=sharing

**Comment by l1ving** [comment]
:neutral_face: It's a text file, just paste the contents into a comment
![image](https://user-images.githubusercontent.com/17222512/102440896-195a1600-3fef-11eb-8413-386984b13e5f.png)

**Comment by SouthernPixel** [comment]
oh ok

blockPlacementPenalty 20.0
blocksToAvoid iron_block
blocksToAvoidBreaking iron_block,beacon,chest,trapped_chest,furnace,ender_chest
buildIgnoreBlocks iron_block,beacon
allowParkour true
allowParkourPlace true
blockReachDistance 5.0
maxFallHeightBucket 255
chatControl false
layerOrder true
followRadius 100

**Comment by l1ving** [comment]
> but i am still having the issue of not being able to prevent baritone from mining those blocks entirely

Oh I missed this part, the formatting is weird. This is a known bug.

**Comment by SouthernPixel** [comment]
So nothig can be done about this right now?

**Comment by l1ving** [comment]
No, you just have to wait for a fix

**Comment by SouthernPixel** [comment]
ok
