### ISSUE TITLE
AFK farming

### ISSUE THREAD

**Issue by wellsilver** [cabaletta/baritone#2274]
## Describe your suggestion
Make it so when the farm is still growing it will wait, not be impatient and stop farming.

## Settings
Make the setting standard or make it so when its farming it will be alot more patient and wait for the crops to grow.

## Context
Would allow automatic AFK farming

## Final checklist
- [ ] I know how to properly use check boxes 
- [ ] Make the farming more "patient"

**Comment by l1ving** [comment]
#893
