### ISSUE TITLE
Pathfinding keeps giving up or is wrong

### ISSUE THREAD

**Issue by SouthernPixel** [cabaletta/baritone#2276]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I keep getting an issue where pathfinding keeps giving up or is just messed up https://imgur.com/a/BZ00Xuq
I am using Fabric and using Baritone version 1.6.1 and playing on a Fabric server
I recently did a "#reset all" and only made it where it mines blocks on the top layer first while mining

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)

**Comment by SouthernPixel** [comment]
I already asked people on Discord and nobody knows how to fix it
