### ISSUE TITLE
Placing blocks when theyre not suppose to be

### ISSUE THREAD

**Issue by SouthernPixel** [cabaletta/baritone#2277]
## What do you need help with?
is there another blockplacement option other than #allowplace & #allowparkourplace?
I have both of those disabled and it still keeps wanting to place blocks

I've already asked this question in the Discord server so please don't tell me to ask them, I already have and nobody will answer me.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
No

**Comment by SouthernPixel** [comment]
Ok you just say no and not say any solutions to why its still placing blocks...

**Comment by l1ving** [comment]
You asked if there were any other settings and the answer to that is no
