### ISSUE TITLE
Baritone 1.12.2 won't build schematic.

### ISSUE THREAD

**Issue by Mineworld6214** [cabaletta/baritone#2279]
Comes up with 'Error at Argument #3: Expected ah' Tried different schematics, won't work.
Baritone 1.12.2 Standalone Forge with Schematica enabled. I've tried EVERYTHING, plz help.

**Comment by scorbett123** [comment]
Can you send the actual command that you are running.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
