### ISSUE TITLE
Build Command not working

### ISSUE THREAD

**Issue by Mineworld6214** [cabaletta/baritone#2280]
## Some information
Operating system: Windows 10
Java version: 1.8.0_271
Minecraft version: 1.12.2
Baritone version: 1.2.13
Forge mods (if used): Schematica

## How to reproduce
Go on world, type in chat '#build <Name of Schematic>.schematic'
Comes up with 'Error at Argument #3: Expected ah'

## Modified settings
[None]

## Final `checklist`
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

[debug.log](https://github.com/cabaletta/baritone/files/5720061/debug.log)

**Comment by scorbett123** [comment]
make sure that the schematic name doesn't have any spaces in it.

**Comment by Mineworld6214** [comment]
> make sure that the schematic name doesn't have any spaces in it.

oh, thx, ill try that now!

**Comment by Mineworld6214** [comment]
It worked, thx!
