### ISSUE TITLE
Baritone not building

### ISSUE THREAD

**Issue by aquazzz1** [cabaletta/baritone#2281]
I can load the schematic, and I have all of the material that i want for the schematic, no error or anything but my character just keeps walking diagonally and not building anything.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
