### ISSUE TITLE
Will not avoid/putout Soul Fire

### ISSUE THREAD

**Issue by a1cd** [cabaletta/baritone#2282]
## Some information
Operating system: MacOS
Java version: 1.8.0_111
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): Xaeros minimap, optifine

_**baritone will not avoid/putout Soul Fire and walks through it, talking damage**_

## How to reproduce
make platform of soul sand
make ring of fire around self
look foreward
type #thisway 10
put out the fire directly behind you
type #path

## Modified settings
allow inventory
blockBreakAdditionalPenalty

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any REDACTED or REDACTED in this issue.

**Comment by ZacSharp** [comment]
Does it put out the fire if you don't put out one yourself?
What is the value of blockBreakAdditionalPenalty? If it is too high baritone will take long detours to avoid block breaking.

**Comment by a1cd** [comment]
it walks through soul fire

**Comment by scorbett123** [comment]
fixed in 373ad3efdd6b1fe9f57e58978e7cb4adbb233737

**Comment by ZacSharp** [comment]
That is actually a different version.
I'm not sure how things are handled that can't be done on master, but I'd expect that the non-release branches (1.16.2) are still used when merging upwards, so 373ad3efdd6b1fe9f57e58978e7cb4adbb233737 should be cherry-picked onto the lowest 1.16 branch.

**Comment by ZacSharp** [comment]
Checked it, they aren't updated when there is a higher minor mc release.
So this is fixed and can be closed.

**Comment by l1ving** [comment]
That's on the 1.16.5 branch.

Also it shouldn't be cherry picked down because builds are being made off of 1.16.5?

**Comment by ZacSharp** [comment]
I though the old branches were still used as intermediate steps when merging upwards, but they aren't.

**Comment by l1ving** [comment]
Well they are, but I suppose new version-specific changes aren't bothered to be made on old minor versions?? Or leij is too lazy to bother either way lol
