### ISSUE TITLE
Cannot interact with 9th slot

### ISSUE THREAD

**Issue by omegadeltoro** [cabaletta/baritone#2288]
## Some information
Operating system:windows 
Java version:?
Minecraft version:1.16.4
Baritone version:last
Forge mods (if used): optifine 

So, at first everything was ok but after I was unable to remove, move item in 9th slot. It was stuck in there. Everything fixed when I deleted baritone but baritone is unique and it would be sad if I would be unable to use it. How to fix this issue?

**Comment by l1ving** [comment]
User error. Disable allowInventory

**Comment by omegadeltoro** [comment]
Woah, that was fast. Thanks, have a great day!
