### ISSUE TITLE
java.lang.NullPointerException with pathing

### ISSUE THREAD

**Issue by Argonius-Angelus** [cabaletta/baritone#2290]
## Some information
Operating system: Windows 10 Pro (64-bit)
Java version: Version 8 Update 271
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): Pixelmon Reforged
BiblioCraft
Dynamic Trees
Dynamic Trees Biomes O'Plenty
Dynamic Trees Pam's HarvestCraft
MrCrayfish's Furniture Mod
Pam's HarvestCraft
Cooking for Blockhead
Waystones
Nature's Compass
Comforts
Storage Drawers
Iron Chests
Chisel
Unlimited Chisel Works
JEI
Journeymaps
Hwyla
CraftingTweaks
InventoryTweaks
MouseTweaks
MoreOverlays

## Exception, error or logs
https://paste.ee/p/PGape

## How to reproduce
This happens somewhat sporadically, but is easy to reproduce when you find a 'problem area' so to speak. I have noticed it is easiest to reproduce inside or near dense forest areas filled with Dynamic Trees.

I believe that Dynamic Trees is the main cause for this, as it is a common part of the stack traces for the null pointers.

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a problem with dynamic trees, go to **them** and ask **them** to fix it.

**Comment by Argonius-Angelus** [comment]
> 
> 
> This is a problem with dynamic trees, go to **them** and ask **them** to fix it.

Will do, but what exactly is causing this issue to occur? I can be more accurate about making the mod more compatible with baritone if I can explain it to them.

**Comment by scorbett123** [comment]
The issue is centered in their getBlockHardness override, however the actual issue is this [line](https://github.com/ferreusveritas/DynamicTrees/blob/07a150b27517a8593459cb804ac78fb67be6efe9/src/main/java/com/ferreusveritas/dynamictrees/blocks/BlockTrunkShell.java#L150) no-one on this repo will help you further than this.

**Comment by Argonius-Angelus** [comment]
Thank you. I will pass this along.

**Comment by Argonius-Angelus** [comment]
So it turns out this was caused by the fact that [this line](https://github.com/cabaletta/baritone/blob/5eeb33a6f5a971f6052c1a6bf0abc23c3b4f2764/src/main/java/baritone/utils/ToolSet.java#L172) passes null twice when trying to get the hardness of a block. Dynamic Trees actually uses the getBlockHardness's parameters and the fact that baritone isn't passing any is resulting in null pointers down the line. The fact that Dynamic Trees actually uses those parameters is somewhat out of the norm, but you should always expect a parameter to be used so this is no excuse.
