### ISSUE TITLE
Hey, @mine doesnt works!

### ISSUE THREAD

**Issue by MarkusLevinson** [cabaletta/baritone#2291]
## need help!
- Hello there! I am using Fabritone 1.4.6. I have an problem: when i am typing "@mine diamond_ore", and bot starts mine, but bot cant normally jump around blocks and normally walk. Video embed! https://youtu.be/Ue0X5nfazTY

`Minecraft 1.16.3, fabritone 1.4.6
My mod list:`
![image](https://user-images.githubusercontent.com/48959279/103015975-5e7fca00-4552-11eb-8409-084af546b853.png)
Win10! Somebody help me!!!!!!!!!

**Comment by l1ving** [comment]
Fabritone is deprecated, use Baritone.
