### ISSUE TITLE
Get input at each frame

### ISSUE THREAD

**Issue by TheGreatRambler** [cabaletta/baritone#2294]
## What do you need help with?
I would like to be able to determine exactly what inputs the bot is using every tick or frame using the baritone api

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
It's not

**Comment by TheGreatRambler** [comment]
Could you explain why this isn't possible? I'm planning on using Baritone in a vanilla fashion, not a hacked client speed mod sort of fashion.

**Comment by l1ving** [comment]
Because that's not how Baritone works
