### ISSUE TITLE
How Do I let bariton repeat clear area

### ISSUE THREAD

**Issue by foxxd** [cabaletta/baritone#2297]
## What do you need help with?
I need to mine a 1x1 block area that changes to a random block after breaking it

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Afaik you can't do that in vanilla Baritone. KAMI Blue's spammer module is able to send Baritone commands, Impact might have it as well.

**Comment by foxxd** [comment]
bruh I did it in impact without using any spammer baritone was able to clear area countless amount of times but it broke after installing meteor i tried to reinstall impact but I get the same result baritone only cleararea once
