### ISSUE TITLE
It doesn't load up schematics.

### ISSUE THREAD

**Issue by Petar252525** [cabaletta/baritone#2300]
I made a folder named schematics in the .minecraft folder but whenever i try to do the #build castle.schematic it tells me there's no such file. 
![image](https://user-images.githubusercontent.com/76625433/103156218-26c18e00-47af-11eb-996d-3422b9c0ead4.png)
![image](https://user-images.githubusercontent.com/76625433/103156242-4b1d6a80-47af-11eb-8e5a-5b51f1fcde71.png)

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
