### ISSUE TITLE
Find not working

### ISSUE THREAD

**Issue by SHOPENS** [cabaletta/baritone#2301]
## Some information
Operating system: Windows
Java version: 
Minecraft version: 1.16.4
Baritone version: 1.16.3
Forge mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

So, whenever i do #find (generic block here) it just does nothing, all it does is show on the chat:
[Baritone] > find bee_nest (bee_nest changes depending the block you searched, or whatever you put in as optional block meta)

## Modified settings
No modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Bee nests aren't cached by Baritone.

**Comment by SHOPENS** [comment]
It does the same to every block, i have tested with diamond ore, grass, oak logs, and it just does the same

**Comment by l1ving** [comment]
Baritone doesn't cache those blocks either

**Comment by SHOPENS** [comment]
Uh, no, im pretty sure find highlights the specified block right?

So basically, it just does "find [input i put here]" and does nothing, ill get a photo as soon as i can

**Comment by SHOPENS** [comment]
![image](https://user-images.githubusercontent.com/76633593/103176661-34235a80-4839-11eb-82fc-7333b449ea87.png)
Red: Proof that other commands work
Blue: baritone deciding to not respond to command after i typed it on chat

**Comment by SHOPENS** [comment]
> Bee nests aren't cached by Baritone.

Also about this, when i do #mine bee_nest, it works just fine.

**Comment by l1ving** [comment]
Yes, because mining is not finding cached tile entities

**Comment by SHOPENS** [comment]
So like, this is a bug or nah? i'm really confused

**Comment by scorbett123** [comment]
Can you send a log file, this should help clear up any confusions on either end.

**Comment by l1ving** [comment]
No, it's not a bug. You're just trying to use on blocks which aren't cached

**Comment by scorbett123** [comment]
Try enabling exploreForBlocks, however if it is in render distance it should still go to the block @l1ving, which I imagine some of the blocks he has tried are.

**Comment by l1ving** [comment]
Oh, well maybe. I can't know from their perspective.

It works perfectly fine for tile entities for me

**Comment by scorbett123** [comment]
I refer to my previous comment.

> Can you send a log file, this should help clear up any confusions on either end.

**Comment by SHOPENS** [comment]
> Can you send a log file, this should help clear up any confusions on either end.

I'll do as soon as I can, also about the render distance, it is definetely, cause i was near the oak log and it didnt highlight it in anyway

**Comment by SHOPENS** [comment]
Heres what happens when I do # find

It just sends a popup in the chat and does nothing, even if the block is standing infront of me (as you can see in the picture) it wont do anything
![image](https://user-images.githubusercontent.com/76633593/103290695-c188bb00-49af-11eb-8b42-90b3e1527313.png)

**Comment by SHOPENS** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/5751016/latest.log)


> Can you send a log file, this should help clear up any confusions on either end.

Heres the log

**Comment by SHOPENS** [comment]
> Try enabling exploreForBlocks, however if it is in render distance it should still go to the block @l1ving, which I imagine some of the blocks he has tried are.

![image](https://user-images.githubusercontent.com/76633593/103291024-82a73500-49b0-11eb-837c-a44538b5306b.png)
Still no work, I have no idea what's wrong, i've also tried installing and uninstalling it again and it still doesn't work, maybe it is probably the fact that im using a 1.16.3 baritone on a 1.16.4 version? (The dev probably didnt add find for that version maybe)

**Comment by l1ving** [comment]
- Oak logs are also not cached

**Comment by l1ving** [comment]
> https://github.com/cabaletta/baritone/blob/72cf9392b16884005ffc2d83c68dacc39832723c/src/main/java/baritone/command/defaults/FindCommand.java#L48

the code only looks for cached blocks

**Comment by SHOPENS** [comment]
> > https://github.com/cabaletta/baritone/blob/72cf9392b16884005ffc2d83c68dacc39832723c/src/main/java/baritone/command/defaults/FindCommand.java#L48
> 
> the code only looks for cached blocks

im going to be 100 percent true with you i have no idea what cached means

**Comment by l1ving** [comment]
What the hell do you think it means then??

**Comment by SHOPENS** [comment]
> What the hell do you think it means then??

something about uh, maybe storing data?

**Comment by l1ving** [comment]
> https://github.com/cabaletta/baritone/blob/dbb0f599fc76a1c91c06eb6d406708188d224fc4/src/main/java/baritone/cache/CachedChunk.java#L42

Here is a list of blocks which Baritone caches on the 1.16.4 version.

Unlike the 1.12.2 version, it no longer caches ores.

**Comment by SHOPENS** [comment]
> > https://github.com/cabaletta/baritone/blob/dbb0f599fc76a1c91c06eb6d406708188d224fc4/src/main/java/baritone/cache/CachedChunk.java#L42
> 
> Here is a list of blocks which Baritone caches on the 1.16.4 version.
> 
> Unlike the 1.12.2 version, it no longer caches ores.

Yeah it seems to work now, thanks for clearing this up
![image](https://user-images.githubusercontent.com/76633593/103291962-73c18200-49b2-11eb-9586-aed228be1ac3.png)

**Comment by scorbett123** [comment]
Wait, why does it not use getToBlockProcess?

**Comment by l1ving** [comment]
lol idk

**Comment by l1ving** [comment]
goto does it just fine, idk what people use find for

**Comment by SHOPENS** [comment]
> goto does it just fine, idk what people use find for

Personally i was trying to find beehives but since i alredy had some in my base, if i did goto, it would go to the bee hives in my base and not new ones, so i had to walk far to actually find them, and since i dont know how to make baritone ignore some blocks so it doesn't go to my base, i thought "hey i could use find to just go to new ones"
