### ISSUE TITLE
Are the none forge builds decorative?

### ISSUE THREAD

**Issue by randomairborne** [cabaletta/baritone#2302]
## What do you need help with?
Are the non forge builds just for fun, or do they work like Optifine?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
The standalone builds can be loaded with the vanilla launcher.

**Comment by randomairborne** [comment]
I use MultiMC, should I add to minecraft.jar or replace it?

**Comment by l1ving** [comment]
No

**Comment by randomairborne** [comment]
I cannot use Baritone with MultiMC?

**Comment by l1ving** [comment]
Yes you can, but if you want to use it standalone you'll have to ask Multimc how to use a version json in multimc

**Comment by randomairborne** [comment]
:+1:
