### ISSUE TITLE
Baritone Starts mining from bottom and then needs to pillar up.

### ISSUE THREAD

**Issue by JoenneSpreuwers** [cabaletta/baritone#2303]
Im trying to mine alot (12k) obsidian and i tough the end would be the best place. But since its obsidian i though, lets just put baritone on in and go to sleep. But when i start at the top of the pillar baritone first mines in a cross down and then starts clearing the bottom until it cannot reach any further and just stops. Does anyone know how i could stop it?

**Comment by l1ving** [comment]
#stop 

In the future, fill out the issue template
