### ISSUE TITLE
Baritone Mines straight down (on end pillars) and then starts clearing. Not from the top to bottom.

### ISSUE THREAD

**Issue by JoenneSpreuwers** [cabaletta/baritone#2304]
## Some information
I have an issue where if i want to automine alot of obsidian, in the end, baritone starts on the top, then mines down to 1 and starts mining until he cannot reach any further. This is frustrating bcuz i need 12k obsidian and doing it by hand is a bit awfull.

## Question
Is there a way that baritone starts mining from the top to the bottom? and doesn't just crossmine down.

## Things Tried
i tried:
\#buildinlayers true
\#layerorder true

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
No

**Comment by CesiumCs** [comment]
use selection areas instead, #mine doesnt follow buildinlayers

**Comment by JoenneSpreuwers** [comment]
> use selection areas instead, #mine doesnt follow buildinlayers

Thanks Cesium
