### ISSUE TITLE
How to place top slabs?

### ISSUE THREAD

**Issue by JacoboGuijar** [cabaletta/baritone#2305]
## What do you need help with?
How can I fill a selection with top slabs? 
I tried #sel fill cobblestone_slab and #sel fill cobblestone_sla[type=top] but did not work. 
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I don't believe there's a way to select that

**Comment by SylveonBottle** [comment]
Should there be a way? Should this be turned into a feature request?
I'm wanting to use baritone to fill a large area with top slabs (slime farm), however it can only build bottom slabs.. so I'm going to have to do it all manually

**Comment by ehylo** [comment]
I don't think you can do it with the sel command like living said but you can always make a schematic and baritone should build it and place them as top slabs

**Comment by TImmigamer06** [comment]
You need to also do waterlogged=false in the statement, otherwise it defaults to true and fails
