### ISSUE TITLE
Unable to find any path even tho the whole place is made of that ore

### ISSUE THREAD

**Issue by Tytova** [cabaletta/baritone#2309]
## Some information
Operating system: 10 pro
Java version: (build 1.8.0_271-b09)
Minecraft version: impact 4.9.1 minecraft 1.12.2
Baritone version:impact 4.9.1 
Forge mods (if used): none

## How to reproduce
no clue really lol, but it happens 100% when im at that server that is full of iron ores, happens with other ores too

## Modified settings
didn't modify anything there 
![image](https://user-images.githubusercontent.com/76726837/103269694-0405c400-49bf-11eb-818f-a0245d908b7e.png)

**Comment by scorbett123** [comment]
Do you only have a wooden pickaxe in your inventory?

**Comment by Tytova** [comment]
> Do you only have a wooden pickaxe in your inventory?

Yes my inv is empty only wooden pickaxe is there

**Comment by l1ving** [comment]
Mining iron ore with a wooden pickaxe does not drop the ore in vanilla Minecraft.
