### ISSUE TITLE
Legit build

### ISSUE THREAD

**Issue by iamdiwang** [cabaletta/baritone#2310]
Please add legit build where the baritone will go to a specific position and move the camera direction like a legit player , and when it can see the block side (top/side/bottom) , it places the block . 
Currently the baritone just does not care about looking like a legit player and just trying to place the block as fast as possible .

**Comment by scorbett123** [comment]
This is a duplicate and will probably be closed by #2293.

**Comment by l1ving** [comment]
In the future, search for existing issues and fill in the issue template.
