### ISSUE TITLE
How do I actually add Baritone to my client as dependency?

### ISSUE THREAD

**Issue by DarkReaper231** [cabaletta/baritone#2312]
## What do you need help with?
I tried multiple ways of including Baritone into my client. I tried jitpack with both Baritone and the fabric port from CDA but that one ended up with very fun error 
`org.lwjgl.lwjgl:lwjgl-platform:2.9.1 has more than one client module definitions.`
so I excluded all the deps with multiple definition and that ended up with this error
`[main/ERROR] (mixin) Mixin config bleachhack.mixins.json does not specify "minVersion" property`
Somebody already stated here that it should launch anyway with this error but it does not.
I tried using Impactdevelopment maven and including from here https://github.com/ImpactDevelopment/maven That does build without errors but it doesn't seem to be initiated so no commands work. 

How the fuck do I include Baritone to Fabric client?

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
> Somebody already stated here that it should launch anyway with this error but it does not.

Because you included the least useful part of the log

**Comment by lafkpages** [comment]
So what is the recommended way to add Baritone as a dependency for a mod?
