### ISSUE TITLE
How to downlaod Baritone for fabric , not for forge

### ISSUE THREAD

**Issue by NazzyLPC** [cabaletta/baritone#2314]
## What do you need help with?
Please, i need help for this
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
###

**Comment by scorbett123** [comment]
https://gitlab.com/CDAGaming/fabritone/-/tree/master get fabric releases from here.

**Comment by NazzyLPC** [comment]
> https://gitlab.com/CDAGaming/fabritone/-/tree/master get fabric releases from here.

is that for 1.16.4 ? and how to get .jar file? I'm not quite sure yet)))

**Comment by scorbett123** [comment]
Use this link https://gitlab.com/CDAGaming/fabritone/-/jobs/851971418/artifacts/download , extract files from the zip file, then go through the folders (there is only ever one subfolder) and the jar is  baritone-1.16.1.

**Comment by NazzyLPC** [comment]
> Use this link https://gitlab.com/CDAGaming/fabritone/-/jobs/851971418/artifacts/download , extract files from the zip file, then go through the folders (there is only ever one subfolder) and the jar is baritone-1.16.1.

thank you so much)

**Comment by NazzyLPC** [comment]
> Use this link https://gitlab.com/CDAGaming/fabritone/-/jobs/851971418/artifacts/download , extract files from the zip file, then go through the folders (there is only ever one subfolder) and the jar is baritone-1.16.1.

I've 1 question , i find link [ https://gitlab.com/CDAGaming/fabritone/-/commit/d98632503069218d2a9dffb81ac227dcc4745748 ]
I'm download that, how can i get .jar file?

**Comment by scorbett123** [comment]
extract the zip file. Then it is in build then libs.

**Comment by NazzyLPC** [comment]
> extract the zip file. Then it is in build then libs.

Sorry , not that link
this link [https://gitlab.com/CDAGaming/fabritone/-/commit/d98632503069218d2a9dffb81ac227dcc4745748](url)

**Comment by scorbett123** [comment]
no - sorry just noticed, wrong link.

**Comment by NazzyLPC** [comment]
> extract the zip file. Then it is in build then libs.

[https://gitlab.com/CDAGaming/fabritone/-/commit/d98632503069218d2a9dffb81ac227dcc4745748](url) it is port to fabric 1.16.4 
can i get .jar file ? or compile to jar.. I just dont understand

**Comment by l1ving** [comment]
https://s.l1ving.org/baritone1-16-4 this redirects to the correct link. press the download button on the latest one and extract the zip to get a jar.
