### ISSUE TITLE
baritone stops tunneling if it encounter holes

### ISSUE THREAD

**Issue by edyxrp** [cabaletta/baritone#2316]
While tunneling baritone will freeze in place if it encounters a hole in the tunnel direction
How do i tell it to make a bridge in ordre to continue tunneling

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
