### ISSUE TITLE
Baritone crashes with no other mods.

### ISSUE THREAD

**Issue by ChristoferMinestar** [cabaletta/baritone#232]
## Steps to reproduce the problem

  01. Delete .minecraft
  02. Launch clean install of Forge
  03. It works
  09. Build `baritone-standalone-1.0.0-hotfix-2.jar`
  10. Copy it to the mods\1.12.2 folder
  11. Launch and see a crash

## Specifications

  - Version: Latest build as of October 21st
  - Platform: Win10 x64
  - Forge: Latest as of October 21st

## Logs:

Edit: sent wrong logs.
Here are new ones.

[debug.log](https://github.com/cabaletta/baritone/files/2499590/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/2499591/latest.log)

No crash logs were produced even though the launcher detected a crash

**Comment by 0-x-2-2** [comment]
Logs show "KAMI-feature-baritone-impl-b9-release.jar"

**Comment by leijurv** [comment]
owned 😎

**Comment by leijurv** [comment]
I'm not sure if the `leftClickCounter` is actually an issue specifically, or if it's just the first field in the first mixin. In my latest commit I actually removed that shadow since we don't use it.

**Comment by leijurv** [comment]
Steps to realize baritone standalone does work: 

1. Clone baritone
2. `./gradlew runClient`
3. Notice it working

**Comment by ChristoferMinestar** [comment]
> 
> 
> Logs show "KAMI-feature-baritone-impl-b9-release.jar" has the crash and the clean install looks like a clean minecraft install lol.

@0-x-2-2 
Sorry, I will send new logs. I mixed them up
[debug.log](https://github.com/cabaletta/baritone/files/2499586/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/2499587/latest.log)

**Comment by 0-x-2-2** [comment]
Make sure simpletweaker is installed to the classpath.

**Comment by Ilomantis** [comment]
Even with SimpleTweaker in the classpath it still crashes on launch.

Forge 14.23.5.2772
baritone-standalone-1.0.0-hotfix-2.jar (a6dc156)
[debug.log](https://github.com/cabaletta/baritone/files/2501061/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/2501062/latest.log)

**Comment by Ilomantis** [comment]
Even with SimpleTweaker in the classpath it still crashes on launch.

Forge 14.23.5.2772
baritone-standalone-1.0.0-hotfix-2.jar (a6dc156)
[debug.log](https://github.com/cabaletta/baritone/files/2501078/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/2501080/latest.log)

**Comment by 0-x-2-2** [comment]
`java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap`
wOw Ayy Wander what this could mean??? how 3 fik???

**Comment by 0-x-2-2** [comment]
Follow the guide please because you are missing other libs now.

**Comment by leijurv** [comment]
@ChristoferMinestar yes i'm aware you're trying to install with forge, the fact remains your issue was not having SimpleTweaker in your classpath

**Comment by ChristoferMinestar** [comment]
Thanks @leijurv
