### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by Fuzqi** [cabaletta/baritone#2324]
## Describe your suggestion
I feel like Baritone could introduce a self-fishing feature where it will find fish and catch it.

## Settings
You should be able to specify how many fish you need and what type you want (it gets rid of the ones you don't want).

## Context
I'm on a server where you can fish and make lots of money with it and this would be really useful! Also, this would be nice as a general feature in Baritone.
## Final checklist
- [✔] I know how to properly use check boxes 
- [✔] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Out of scope

**Comment by mewduifhi** [comment]
What server are you on? It sounds fun. Not sure if I am supposed to post this here but oh well

**Comment by Fuzqi** [comment]
> What server are you on? It sounds fun. Not sure if I am supposed to post this here but oh well

I'm on this server called SolaxMC the ip is play.solaxmc.com. It's a faction type server.
