### ISSUE TITLE
i cannot disable auto tool in what way i try

### ISSUE THREAD

**Issue by lemonpillow** [cabaletta/baritone#2327]
i cannot seem to disable autotool with baritone, i tried:
.b set autoTool false
#set disableAutoTool true
#set disableAutoTool false
#set disableAutoTool

and i cannot figure out how to do it!
i am using the newest version (1.6.2)

https://i.imgur.com/hl0GRko.png

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
The setting is disableAutoTool so to toggle it just type #disableAutoTool or #set disableAutoTool true, in the screen shot you just use "autoTool" not "disableAutoTool".
