### ISSUE TITLE
Self Disconnect

### ISSUE THREAD

**Issue by pls-eee** [cabaletta/baritone#2331]
Disconnect automatically when a player comes within a set radius or when a certain player logs in.

Would be helpful to avoid getting killed while automated building / mining.

**Comment by ZacSharp** [comment]
Out of Scope
Use a client with an AutoDisconnect in addition to Baritone for this

**Comment by CesiumCs** [comment]
#2330 mfw

**Comment by ZacSharp** [comment]
Think so. First asking and only suggesting if it's not possible yet is ok (but not really good cuzin most cases you could just search) IMHO

**Comment by pls-eee** [comment]
Sorry about that, thought it was better as it asks to spear, my bad.

Cant use existing auto disconnect due to combat log plugin, wanted to log out pre-emptively.

**Comment by l1ving** [comment]
This was already suggested
