### ISSUE TITLE
Head movement while running

### ISSUE THREAD

**Issue by quanto3** [cabaletta/baritone#2332]
Could you make the head lock the way you are moving? It looks very suspicious while sprinting backwards and mining.

**Comment by ZacSharp** [comment]
Ever heard of `#freeLook false`?
I suggest reading [USAGE.md](https://github.com/cabaletta/baritone/blob/master/USAGE.md) and finding the links to [settings javadoc](https://baritone.leijurv.com/baritone/api/Settings.html), [settings source](https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/Settings.java) or [javadoc again but this time directly to field details](https://baritone.leijurv.com/baritone/api/Settings.html#field.detail), which all contain a full list of all settings with documentation.

**Comment by ZacSharp** [comment]
Dumb me.
It always looks in the direction of movement serverside, freeLook is purely clientSide.
Baritone still looks suspicious I know. Don't create an issue on "smother Aim", "more legit head movement" or similar, there's a ton of those.

**Comment by ZacSharp** [comment]
Oh and using the supplied issue templates instead of deleting them would be nice.
