### ISSUE TITLE
Can #farm run even when no crops can be farmed yet?

### ISSUE THREAD

**Issue by CharlesDoesEverything** [cabaletta/baritone#2333]
## What do you need help with?
Once #farm has completed its task, the bot stops farming. But is there away for the bot to wait for the crops to grow, and then the bot will farm again? 

I need this feature to be added so that I don't need a carrot farm with villagers, I can just use bots.

**Comment by l1ving** [comment]
No

**Comment by ZacSharp** [comment]
There is not way using only Baritone. But it is possible with external macros by just running `#farm` every few seconds.

**Comment by Strikeeaglechase** [comment]
Any chance this could be added as a config option? `allowIdleFarm` or whatever
