### ISSUE TITLE
Ability to mine or goto blocks with specific blockstates

### ISSUE THREAD

**Issue by Ibex80** [cabaletta/baritone#2334]
We should be able to do the mine command and have baritone mine only blocks with the specified blockstate.
For example: **#mine note_block:blockstates(instrument: guitar, note: 12, powered: false)** or **#goto note_block:blockstates(instrument: guitar, note: 12, powered: false)**

I feel like this would improve baritone because sometimes when you're building a large redstone machine you set a repeater to too many or too few ticks without knowing, then later you have to go over the whole machine to find where that ONE repeater is. With this you would do the command **#goto redstone_repeater:blockstates(delay: 2)** to find the repeater with the wrong delay.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
