### ISSUE TITLE
How to get the position of blocks?

### ISSUE THREAD

**Issue by Neirno** [cabaletta/baritone#2335]
## What do you need help with?
How can I get the position of the blocks? For example, as soon as I write #mine *** _ ore I want to get the coordinates of this ore?

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
You cannot do the via Baritone

**Comment by Neirno** [comment]
Can it be possible to get it using fields?

**Comment by l1ving** [comment]
Depends

**Comment by Neirno** [comment]
Well, so I ask how)

**Comment by ZacSharp** [comment]
Do you want it in java code or as a chat output for you?

**Comment by l1ving** [comment]
This isn't a Baritone question because Baritone does not have built in functionality to tell it to the user.

**Comment by Neirno** [comment]
Yes I want use it in java code

**Comment by ZacSharp** [comment]
If you want it as an addition to `#mine` without a custom version of baritone I can't help you.
If you are fine with a separate command, have a look at WoorldScanner and Command.
