### ISSUE TITLE
Mine mod specific blocks

### ISSUE THREAD

**Issue by lRoberth** [cabaletta/baritone#2340]
## What do you need help with?
How would you specify to Baritone what block to mine?, for example in IndustrialCraft and Thermal Foundation, for the tin and copper ore.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#mine modid:blockid:damage

I suggest searching for existing issues with the names of those mods (individually)
