### ISSUE TITLE
#buildinlayers but reverse

### ISSUE THREAD

**Issue by Ardenzard** [cabaletta/baritone#2341]
## Describe your suggestion
There should be a setting that works just like #buildinlayers but instead of it starting at layer 0 it starts at the top and works its way to the bottom.

## Settings
Same as #buildinlayers

## Context
 this could help with clearing out large areas since if it starts at the beginning it would have to tower up to break each part and that takes more time and is less efficent. For example if you are digging a 16x16 (one chunk) hole down to bedrock but want baritone to do it for you it could start at the top which is much faster and just better in general then starting at the bottom or using standard baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#layerorder much
