### ISSUE TITLE
How can I #goto a specific type of spawner?

### ISSUE THREAD

**Issue by Claw76** [cabaletta/baritone#2343]
Is there a way to only go to a certain type of spawner? I looked at BlockOptionalMeta, which you can add to a #goto command, but I couldn't get it to work. So for example: What would I need to do for baritone to only go to a skeleton-spawner?
#goto spawner:???

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
No

**Comment by ZacSharp** [comment]
BlockOptionalMeta only supports selection by block and optionally metadata, just like the name says.
The mob spawned from a spawner is part of the spawner tile-entities NBT data.
There at least one issues about using NBT for block selection in Baritone, so don't open a new one.
