### ISSUE TITLE
Can I tell baritone to mine a certain block within a given area?

### ISSUE THREAD

**Issue by devonaw** [cabaletta/baritone#2345]
I want to mine all grass_blocks and all dirt_blocks within a given area, within 2 coordinates.

**Comment by l1ving** [comment]
``` 
#s 1
#s 2
#s set grass air
#s set dirt air
```

**Comment by scorbett123** [comment]
@l1ving you need to use #s replace blockToReplace blockToReplaceWith for this, #s set only takes 1 argument.

**Comment by devonaw** [comment]
this is in survival mode

**Comment by CesiumCs** [comment]
> this is in survival mode

then use a shovel

**Comment by scorbett123** [comment]
This method works in survival if you are using baritone, they are all baritone commands.
