### ISSUE TITLE
I need to mine grass_block and dirt_block within a given area in SURVIVAL mode.

### ISSUE THREAD

**Issue by devonaw** [cabaletta/baritone#2346]
I asked the same question and the people who answered assumed I was doing this in creative mode and closed it.

**Comment by CesiumCs** [comment]
> #s 1
> #s 2
> #s replace grass air
> #s replace dirt air

https://github.com/cabaletta/baritone/issues/2345#issuecomment-757996411

**Comment by l1ving** [comment]
> I asked the same question and the people who answered assumed I was doing this in creative mode and closed it.

No??
