### ISSUE TITLE
Is there a feature that ONLY highlights blocks

### ISSUE THREAD

**Issue by OOgla** [cabaletta/baritone#2348]
## What do you need help with?
Is there a feature that highlights blocks, but doesn't go to the blocks or mines them? If there isn't that feature, could you add that feature?

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
No

**Comment by CesiumCs** [comment]
`#mine diamond_ore` and then immediately `#pause` i guess... dunno why you'd want to do that when you can just use baritone along with a client that has a search mod

**Comment by l1ving** [comment]
my mans actually deleted his account after cesium's genius idea

**Comment by mwahaha9** [comment]
👏
