### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by lisismel** [cabaletta/baritone#2353]
## Settings
PriorityBreakeBlock
PriorityWalk
PriorityParcour

Ext.

## Context
sometimes the baritone does strange things, preferring to break blocks instead of just bypassing them

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
this is what penalties are for

**Comment by scorbett123** [comment]
You can mess around with the cost settings to have this effect.
