### ISSUE TITLE
Gray chat in multiplayer

### ISSUE THREAD

**Issue by MegaMen1245** [cabaletta/baritone#2355]
## Some information
Operating system: Windows 7
Java version: 1.8.0_51 64bit
Minecraft version: 1.12.2
Baritone version: baritone-api-forge-1.2.12
Forge mods: OptiFine_1.12.2_HD_U_F5, xray-1.12.2-1.6.0
Forge version: 1.12.2-forge-14.23.5.2854

## Exception, error or logs
debug.log: https://drive.google.com/file/d/19ZKDjsDF0x8W0fRIvJfow80SW6jFWzzT/view?usp=sharing
latest.log: https://drive.google.com/file/d/1mEiRyAUiU1Bavft4Ui-a1xvUyL6S2-gy/view?usp=sharing

## How to reproduce
I put the baritone in mods and went into multiplayer, on the 2b2t server. And I saw that the chat and the tab turned gray, as soon as I removed the baritone from the mods, the chat became normal. There is no such problem in singleplayer, only in multiplayer.

screenshot of the problem: https://drive.google.com/file/d/1Nl-V6Bw4XCvspSBCZMZj65zR20pmVS1s/view?usp=sharing

## Modified settings

https://drive.google.com/file/d/1e6FxUJZ5T5W786eErl3WUP4BKmz3bJLE/view?usp=sharing

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by MegaMen1245** [comment]
Addition. I found that if you remove OptiFine from the mods, the problem disappears. I tried to download another version of OptiFine and try to play with it, the problem still remained. I even tried using a different version of the forge with no success. Apparently OptiFine and Baritone interfere with each other's work.

**Comment by scorbett123** [comment]
Yes, baritone is not fully compatible with OptiFine, however this should only be rendering issues and baritone shouldn't have issues pathing. I recommend that you rename optifine to something like "AOptifine" so it is higher in the alphabet, therefore there might be less issues and optifine might work better.

**Comment by MegaMen1245** [comment]
Doesn`t help.

**Comment by MegaMen1245** [comment]
Can i do anything else?

**Comment by MegaMen1245** [comment]
I'm very happy here and I want to let you know that I have found a solution to the problem. In the OptiFine settings there is an option "Fast Render" and I had it enabled. Once I turned it off, the problem went away. If you are using baritone and optifine together, then never enable "Fast Render" as this option conflicts with baritone.
