### ISSUE TITLE
How to make baritone react to commands only with specific prefix

### ISSUE THREAD

**Issue by WolfGames** [cabaletta/baritone#2362]
I very often i say "help' in chat but when i do this baritone displaying help menu.
I tried to set command prefix in setting but still when i say command without prefix baritone was reacting.
help pls

**Comment by WolfGames** [comment]
Ok nvm i found how to do this

**Comment by javalsai** [comment]
Not saying how to is criminal. Necro-bumping as this is one of the first search results.

Setting `chatControl` to `false` will disable unprefixed commands, while if `prefixControl` is set, it will keep reacting to prefixed commands, baritone considers them 2 completely different interfaces to interact with.
