### ISSUE TITLE
Allow Baritone to sleep at night

### ISSUE THREAD

**Issue by kirjorjos** [cabaletta/baritone#2366]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
Allow players to set the location of a bed or have a bed in their inventory that Baritone will attempt to use to auto sleep when It's night.
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
On/Off, if it should pause other tasks or not
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
Often times, when traveling long distances, the best way to avoid monsters is to sleep the night away.
## Final checklist
- [x] I know how to properly use check boxes 
- [] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
> Allow players to set the location of a bed

baritone already does this as part of its waypoints:
`#wp list`

**Comment by l1ving** [comment]
out of scope
