### ISSUE TITLE
Baritone can't pathfind to death waypoint

### ISSUE THREAD

**Issue by BLucky-gh** [cabaletta/baritone#2367]
## Some information
Operating system: MacOS
Java version: 8
Minecraft version: 1.12
Baritone version: Null version (bundled with kami blue)
Forge mods (if used): schematica, kami blue

## How to reproduce
1. Die
2. Click latest death waypoint, set goal
3. Baritone jumps in place a couple of times
4. manually set a goal on the same block (for example left click in freecam in kami blue), it pathfinds perfectly fine

[Footage](https://imgur.com/a/DXfg3sD)

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.''

**Comment by ZacSharp** [comment]
It did what you asked it to do, both times.
You told it to set the goal by clicking the text, it did it. You told it to go to a block (which wasn't your waypoint btw) using your clients click feature, it went there.
If you want it to actually walk to your waypoint I suggest telling it to do so by using `#path`

**Comment by BLucky-gh** [comment]
Oh, so I have to separately tell it to pathfind to a goal. Welp, should have learned more about it before reporting. Thanks for the info!
