### ISSUE TITLE
Baritone dont move by self, only lights the path and ores

### ISSUE THREAD

**Issue by JohnMar1** [cabaletta/baritone#2371]
## Some information
Operating system: win 10
Java version: latest 64bit
Minecraft version: 1.16.4
Baritone version: latest
Forge mods (if used): im using fabric, mods - wurst, xaeros minimap, modmenu, kron HUD, REI, sodium, torohealth

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[2021-01-20-1.log.gz](https://github.com/cabaletta/baritone/files/5841633/2021-01-20-1.log.gz)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Sodium is not compatible with baritone, uninstall it and then it should work.

**Comment by JohnMar1** [comment]
Oh, thanks
