### ISSUE TITLE
[Suggestion] Autofish

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#2372]
## Describe your suggestion
Baritone is already pretty much a must have for many things, though I would like it, if we had autofish

## Settings
I guess, a setting, to wait in ms, until pulling back the rod - the deeper the rod goes, the higher of a chance of getting good loot, afaik

**Comment by scorbett123** [comment]
I would say that this is out of scope for baritone. Baritone mainly focuses on the path finding aspect of tasks, and this involves none of that.

**Comment by UltraBlackLinux** [comment]
> I would say that this is out of scope for baritone. Baritone mainly focuses on the path finding aspect of tasks, and this involves none of that.

Yeah, that seems right, ok then.
