### ISSUE TITLE
Baritone issues with chat commands

### ISSUE THREAD

**Issue by ThePartySlime** [cabaletta/baritone#2374]
Operating system: Windows 10
Java version: Java 8 Update 261
Minecraft version: 1.16.4 Fabric
Baritone version: Baritone Fabric 1.16.3 (compatible with 1.16.4)

I'm having trouble with sending commands to Baritone. Baritone responds to command without using a '#' before a command. And whenever I try to click a command in chat, it sends a chat message. I've read a thread (https://github.com/cabaletta/baritone/issues/1951) about this being fixed since Baritone 1.16.2. Somehow, the issue is still there. Any solutions?

**Comment by l1ving** [comment]
This isn't a bug and it was never "fixed"

**Comment by Bluscream** [comment]
I have the same issue again, can you please atleast explain why this happens?

**Comment by wagyourtail** [comment]
part one is just the chatcontrol setting
part 2 if it's just sending `<<uuid>>commandName` in chat, restart game fixes iirc
