### ISSUE TITLE
Does baritone not work with terracotta?

### ISSUE THREAD

**Issue by vaz3yy** [cabaletta/baritone#2375]
## What do you need help with?

I'm trying to get baritone to mine terracotta and I just get this error seen below.
![image](https://user-images.githubusercontent.com/77464771/105230663-b26ed600-5b33-11eb-87e0-0fbf65938bb5.png)
Am I doing something wrong? I'm on 1.12.2 impact client.

**Comment by l1ving** [comment]
You have to give it the right block name

**Comment by ZacSharp** [comment]
that is stained_hardened_clay
To get the id of blocks just enable the F3 debug overlay and look at them.
No need to open an issue here.

**Comment by vaz3yy** [comment]
> that is stained_hardened_clay
> To get the id of blocks just enable the F3 debug overlay and look at them.
> No need to open an issue here.

It wasn't an issue, it was a question, dipshit.

**Comment by l1ving** [comment]
then why is it called the `New Issue` button

**Comment by vaz3yy** [comment]
So I'm not allowed to have a question??? Are you a female?? You seem like one

**Comment by l1ving** [comment]
rude
