### ISSUE TITLE
Custom mine - options

### ISSUE THREAD

**Issue by PoloAC** [cabaletta/baritone#2376]
Hi,
I'm playing on a server with custom mines, thereforce the normal use of baritone is not for any use there. The server is in adventure mode, where you can only mine ores. And there is where the problem starts. Baritone will always break blocks in other to reach the visible ores. 

So my question is, if you can please make an option for these kind of mine plugins. Or I would propose to make an option that makes sure that baritone doens't mine any other block.
-An option that allows the mod to only break the 'green' boxes and not the 'red'.

Kind regards
Polo

**Comment by l1ving** [comment]
I wonder what #help does

**Comment by PoloAC** [comment]
> I wonder what #help does

There are no options for that kind of mine

**Comment by PoloAC** [comment]
I have read al the #help / .help options and concluded that there are no settings that can help with this.

**Comment by PoloAC** [comment]
Hi

I have searched al over the #help. 
https://youtu.be/u0HWoLRvm-I
7:0, you can see what I mean. If I turn alowbreak to false, then the mine option won’t work. Need help to help me set it that it only mines the ores without Mining other blocks. 

Kind regards

**Comment by l1ving** [comment]
I'm fairly certain it'll work fine

**Comment by PoloAC** [comment]
Just tried it. It says ‘unable to mine when allowBreaj is false!’

Verstuurd vanaf mijn iPhone
