### ISSUE TITLE
Pathfinding in water can get stuck

### ISSUE THREAD

**Issue by Pesoen** [cabaletta/baritone#2377]
## Some information
Operating system: Windows 10
Java version: 8 Update 281
Minecraft version: 1.16.4
Baritone version: 1.6.2

## How to reproduce
1. Set it to go to some coordinates, or set go to a waypoint, that requires it to traverse water.
2. when entering the water, or the path is recalculated while the player is at the endpoint of the current path, it can get stuck bopping up and down.
3. keep bouncing up and down until baritone is canceled, og a block is placed underneath.

## Modified settings
allowBreak: false
allowDiagonalAscend: true
allowDiagonalDescend: true
allowOnlyExposedOred: true
allowPlace: false
allowSprint: false
avoidance: true
blockReachDistance: 3.0
buildInLayers: true
legitMine: true

##Notes:
when using it mainly to travel, i disable block breaking, since i tend to move around structures and i don't want to break holes in them to get around. Some of the settings are just set for fun, and forgotten.

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Jacqueb-1337** [comment]
@5HT2 you can't just close an issue because "duplicate" but not provide the duplicate link. As far as I can tell, there IS no duplicate. Others have this issue and can't find a solution to it because of people like you.

**Comment by scorbett123** [comment]
> @5HT2 you can't just close an issue because "duplicate" but not provide the duplicate link. As far as I can tell, there IS no duplicate. Others have this issue and can't find a solution to it because of people like you.

#3200 is after this, but is the same issue, there currently isn't a solution unless you find one yourself.

**Comment by Jacqueb-1337** [comment]
@scorbett123 thank you for sharing the link to the original, that means a lot. By the way, I have found a workaround (if you don't necessarily need to traverse across water) just do command "#blocksToAvoid water" and it will attempt to avoid water and instead will walk around or build over it.
