### ISSUE TITLE
Mining without breaking blocks

### ISSUE THREAD

**Issue by PoloAC** [cabaletta/baritone#2379]
Hi
Is there an option to onlymine the targetted ore without breaking other blocks (#allowbreak false, undermines the #mine function) I need it for an special adventure mode mining server.

**Comment by ClausWiingreen** [comment]
I think the only way to do this currently, is to add all other blocks to blocksToAvoidBreaking.

**Comment by PoloAC** [comment]
Even if you do that, most of the time they wil try to mine the blocks they needed to avoid.

**Comment by rlelchev** [comment]
I think the only way is to use Impact and disable mining blocks from there

**Comment by l1ving** [comment]
That won't be any different than #allowBreak

**Comment by scorbett123** [comment]
> Even if you do that, most of the time they wil try to mine the blocks they needed to avoid.

It still will if it can't find any other path to get there, however will minimize the amount that it tries to break.

**Comment by scorbett123** [comment]
Also don't use baritone on servers that it isn't allowed.
