### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KyleWasTaken** [cabaletta/baritone#2381]
Pls Make A Command That Does ANYTHING In Its Power To Get Exp Thx

**Comment by ZacSharp** [comment]
Probably out of scope.
Also there's plenty of ways you can automatically farm xp with a vanilla client, way faster than what Baritone could do (except it becomes an autoclicker, which is definitely out of scope). If you really want Baritone to gather xp, just use killaura together with hunt or `#follow`.

**Comment by l1ving** [comment]
I hate children
