### ISSUE TITLE
Baritone doesn't build schematics with concrete or terracotta

### ISSUE THREAD

**Issue by TheTemporaryAnon** [cabaletta/baritone#2383]
## Some information
Operating system: Windows10 Home
Java version: 1.8.0_51
Minecraft version: 1.16.4
Baritone version: The one coming with the Inertia Client 3.1.3
Forge mods (if used): None
Other mods: Optifabric, Litematica with Lalalib, Inertia

Whenever I try to build a schematic file that has concrete in it, Baritone attempts to build it but ignores all concrete blocks. But it still behaves like normal (i.e. refusing to start if no concrete blocks are present).

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/5857384/latest.log)

## How to reproduce
1. Use a schematic that has concrete in it
2. Use command #build <schematicfilename>.schematic
3. Wait until it's done

## Modified settings
Happens with both modified and default settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
quoth the great bot:
![image](https://user-images.githubusercontent.com/24397680/105537558-17573700-5cc0-11eb-824b-65b273c17e93.png)
