### ISSUE TITLE
#build Schematic file 

### ISSUE THREAD

**Issue by calloutplayed** [cabaletta/baritone#2384]
Where do you place the schematic file for baritone to build.and the schematic file is downloaded from https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.minecraft-schematics.com/&ved=2ahUKEwiw956Wr7LuAhX8zjgGHQDZDeEQFjAAegQIAhAD&usg=AOvVaw34JqX6Nh9QqJ_fKWilm1ZJ
???

**Comment by calloutplayed** [comment]
???

**Comment by calloutplayed** [comment]
Label question

**Comment by calloutplayed** [comment]
label:question

**Comment by calloutplayed** [comment]
label:bug

**Comment by calloutplayed** [comment]
#1667

**Comment by calloutplayed** [comment]
@l1ving

**Comment by l1ving** [comment]
RTFM
