### ISSUE TITLE
using a boat with baritone goto is very buggy

### ISSUE THREAD

**Issue by liampbjray** [cabaletta/baritone#2387]
not much else to say but that

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
