### ISSUE TITLE
Baritone does not move after using commands that require movement

### ISSUE THREAD

**Issue by Xialionit** [cabaletta/baritone#2388]
## Some information
Operating system: Windows 10 
Java version: newest
Minecraft version: 1.16.4
Baritone version: newest
Forge mods (if used):  Voxel Map,Neat,Optifine,Eq Sorter

It's like that
Bariton worked properly until today on the server I play (the server does not have anti-cheat) and for about 2 hours after running commands that require movement, Bariton destroys blocks and stands still. Any advice on how to fix it ???

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
