### ISSUE TITLE
Chat Anti-Spam doesnt let me click on Baritone Commands

### ISSUE THREAD

**Issue by HaphazardJoker** [cabaletta/baritone#2390]
## Some information
Operating system: Windows 10
Java version: (build 1.8.0_281-b09)
Minecraft version: 1.16.5
Baritone version: 1.6.1
Forge mods (if used): 

## How to reproduce
Click on command in chat from baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.
