### ISSUE TITLE
Anarchy elytra hack fly bot

### ISSUE THREAD

**Issue by costin88boss** [cabaletta/baritone#2392]
## Description
Sinply a feature where Baritone can fly with the elytra hack in Anarchy servers and trying to avoid objects that would stop the player. 

I really hope it is going to be added as it is useful when you want go far without having to wait and hold some buttons.

## Settings
Is elytra hack enabled
Destination nether position
Highway width
Highway made of block (useless probably)

## Context
It would improve Baritone for anarchy players heavily so you can travel without waiting.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by costin88boss** [comment]
With what it is duplicate?

**Comment by l1ving** [comment]
# this has been suggested 934929834982983498 times

**Comment by costin88boss** [comment]
When is it added

**Comment by l1ving** [comment]
it's not
