### ISSUE TITLE
Can I use baritone to play parkour maps 

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#2393]
I want to try to use baritone to play parkour maps, but I cannot reach the corresponding place after using the goto command. Baritone always tries to destroy and place blocks in adventure mode. 

Map example: [PARKOUR SPIRAL](http://www.minecraftmaps.com/parkour-maps/parkour-spiral )

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
To prevent it from preaking/placing blocks I suggest turning `allowBreak` and `allowPlace` off.
After you have done that you will quickly notice that Baritone only does straight flat jumps and straight ascends both with a gap of at most 3 blocks.
You might be able to use #2142, which aims to add descends, 4 block jumps and diagonals, but it isn't finished.

**Comment by djkcyl** [comment]
> To prevent it from preaking/placing blocks I suggest turning and off.
> After you have done that you will quickly notice that Baritone only does straight flat jumps and straight ascends both with a gap of at most 3 blocks.
> You might be able to use #2142, which aims to add descends, 4 block jumps and diagonals, but it isn't finished.`allowBreak``allowPlace`
> 
> Simple answer: you can use it, but it isn't good at parkour

ok thx

**Comment by olivercool** [comment]
Same problem, I wonder If there was a version **specifically** made for parkour.
