### ISSUE TITLE
Maby A #beat?

### ISSUE THREAD

**Issue by galileoleosolis** [cabaletta/baritone#2395]
So I was thinking what if you could do #beat so that baratone can can mine oak_logs make a pick then bla bla bla then make diamond armer enter nether find a fortres by mining netherbricks. then kill blazes with fight bot or somthing. then e men and use trianglation. Then Beat e dragon. I know but it is hard, But with how Awsome baratone is I think it can be added. I think It would just be nice.

Then maby you can do #elytra to get one and #allowElytra to let baratone use a elytra it would be nice or just give it a goal to get full enchants and let it train. I know this is probley not going to get read but if you see this Please Add it in. Thank You!

**Comment by galileoleosolis** [comment]
oops sorry for not doing it in correct format. I am new to GitHub Sorry

**Comment by scorbett123** [comment]
> WHAT THE HELL THATS A GOOD THING I did not know baratone was so 1 sided and NO SUGJESTIONS ARE CONSEDERD better off making my own

1. If you make your own well done.
2. If this has been already suggested then it shouldn't be suggested again.
3. Don't change the main comment like that, no-one will be notified and it can just make us look stupid.
4. This should be split into at least 10 different issues, and baritone is out of active development. This sort of thing would take a year to code, and no-one will be willing to do that, and still it would be out of scope for baritone.
5. Suggestions are considered, but not when they are as ridiculous as yours. If you really need something that can do more use this: [minebot](https://github.com/michaelzangl/minebot
)

**Comment by l1ving** [comment]
I like that they added a :+1: to their own issue rofl

**Comment by galileoleosolis** [comment]
Fine here baratone dosent have good features has suport for a mod that dosent even exist in 1.16 (schmatica) and If ItS GOiNg tO tAkE A LonG tImE NoONe iS goInG to CoDe it. thats lazynes and sure ima just take baratons code and mix and mash a few things and boom #beat and I will have somthing WORTH downloading

**Comment by l1ving** [comment]
I don't understand how you manage to get so many things wrong, such as the spelling of common words or even the name of Baritone, or the fact that Baritone does indeed run on 1.16. 

> sure ima just take baratons code and mix and mash a few things and boom #beat and I will have somthing WORTH downloading.

I'd really like to see a 12 year old accomplish that much. It's really not that simple.

**Comment by galileoleosolis** [comment]
oh and Challenge accepted.

**Comment by l1ving** [comment]
😐

**Comment by galileoleosolis** [comment]
for the record I dont even know java and I figured out how to call functions so if you tell me I cant do somthing your going down and I will do it. SO NEVER SAY I CAN NOT DO SOMTHING

**Comment by scorbett123** [comment]
If you can learn java, and figure out how baritone works, I will give you a clue here, A* pathing, and sort out this #beat function, then I will be really impressed. It isn't laziness, as well. It is us knowing how much effort it will take compared to how much reward you get. In fact I am thinking of starting a project that takes baritone and uses it for things such as finding diamond ore, or even adding auto crafting, however this isn't the repo for it, and it would be a many year project, and I don't have any free time already. But I doubt that even that would get to the stage of beating the game completely automatically, there is so many small features that would have to be created, and it would barely ever be used.

**Comment by galileoleosolis** [comment]
ok I already got it to get diamonds

**Comment by l1ving** [comment]
> ok I already got it to get diamonds
> but u do all the crafting

so, regular baritone 
![](https://cdn.discordapp.com/emojis/786660680648491028.png)
