### ISSUE TITLE
Maybe add a mob tracking system to prevent withers from finding them

### ISSUE THREAD

**Issue by avneh** [cabaletta/baritone#2397]
Every time I play on 2b2t and using baritone withers come out of nowhere and blasts me Maybe if player has obsidian to surround them self and one the wither(s) go away then they an mine themselves out

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
