### ISSUE TITLE
Conflict with forged-carpet

### ISSUE THREAD

**Issue by DeadlyMC** [cabaletta/baritone#2398]
## Some information
Operating system: Windows 8.1
Java version: 8
Minecraft version: 1.12.2
Baritone version: v1.2.14
Forge mods (if used): forged-carpet

## Exception, error or logs
https://gist.github.com/DeadlyMC/da57c4c6280587b624273bbae9808be1

## How to reproduce
Add [forged-carpet](https://github.com/DeadlyMC/forged-carpet/releases/) and [baritone-standalone](https://github.com/cabaletta/baritone/releases/tag/v1.2.14) to the mods folder and run the game with forge 1.12.2. It will crash instantly

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

## Suggested fix
Updating to mixin 0.8.2 will most probably fix this issue, i tried downgrading the shaded mixin in my mod to 0.7.11, it didnt crash with that version. You prolly want to update to the latest version anyways

**Comment by l1ving** [comment]
> You prolly want to update to the latest version anyways

that's pending

**Comment by l1ving** [comment]
I'm closing this as it will be resolved by bumping mixin anyways
