### ISSUE TITLE
Farm configuration

### ISSUE THREAD

**Issue by elcracen** [cabaletta/baritone#2399]
## What do you need help with?
I need to know if it's possible to select which crops baritone will farm when i do @farm or #farm (whatever command y'all got)
Since i've got my farm near sugarcane and i want to let the sugarcane grow separately.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by elcracen** [comment]
And, it doesn't plant carrots so ye, would be cool if you could choose that

**Comment by l1ving** [comment]
no
