### ISSUE TITLE
Baritone switching to most efficient pickaxe as soon as it enters the inventory and I can't switch out and it gets really buggy.

### ISSUE THREAD

**Issue by Mikitom** [cabaletta/baritone#2402]
## Some information
Operating system: Windows
Java version: 8
Minecraft version: Latest 1.16.5
Baritone version: Null version (this is normal in a dev environment), idk what that means, I'm in a singleplayer creative world.
Forge mods (if used): Optifabric

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
No logs are there for this issue

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Just get 2 pickaxes, one being better than the other (stone and iron)
## Modified settings
To get the modified settings run `#modified` in game
allowDiagonalAscend
allowDiagonalDescend
allowInventory
allowJumpAt256
allowParkour
allowParkourPlace
allowVines
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord)
