### ISSUE TITLE
Game crashes when i try to join on a Server.

### ISSUE THREAD

**Issue by tobi8126** [cabaletta/baritone#2404]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.5
Baritone version: 1.6.2
Forge mods (if used): -

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. Launch Forge 1.16.5
2. Connect to a Server
3. Game crash in the Joining Phase

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

[latest.log](https://github.com/cabaletta/baritone/files/5899524/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/5899525/debug.log)

**Comment by l1ving** [comment]
Not a baritone issue

**Comment by tobi8126** [comment]
but what could it be. I tried with the Inertia client which has baritone included and same issue
