### ISSUE TITLE
baritone not mining walking forward to mine using .b click

### ISSUE THREAD

**Issue by moonies44** [cabaletta/baritone#2405]
Hello. when mining out simple 20x20 , the baritone will mine out all blocks in its reach , but then does not walk itself forward to get closed to the other blocks to mine , so it just stands there , when trying to manually walk it it just walks back to the spot it first completed it area break. and sometimes it will walk with manual input and then continue to mine blocks in reach again , until it needs manually moving again. the bot is failing to walk the character to the next mine area.

**Comment by scorbett123** [comment]
I believe that this is the cave air issue, however I don't fully know. This is a bug though, however is definitely a duplicate.
