### ISSUE TITLE
Can't move at all in online

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#2406]
## What do you need help with?
Whenever I run a command that leads to me moving I just freeze in place and can't move manually. Baritone just stands completely still too. Everything works in singleplayer so I think it's linked to some anti-cheat on the server, anyone being able to identify which it is would also be appreciated.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Fill in the bug template.
