### ISSUE TITLE
java.NullPointerException when joining servers - consistent and reproducible

### ISSUE THREAD

**Issue by ThisIsanAlt** [cabaletta/baritone#2408]
## Some information
Operating system: Windows 10 2004
Java version: 1.8.0_261
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge Version: 35.1.4
Forge mods (if used): None

## Exception, error or logs
https://mystb.in/GenreRubyKnew.yaml

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
- Launch Forge with Baritone
- Attempt to join vanilla server on 1.16.4
- Game crashes

## Modified settings
To get the modified settings run `#modified` in game
None 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

## Additional notes
Singleplayer worlds do not seem to be affected. This only affects multiplayer servers.

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by ThisIsanAlt** [comment]
Turned out there was a weird unicode character lurking in the server IP that affected baritone. Removing it fixed it.

Thanks!

**Comment by Superpapotas** [comment]
Server ip has ":" for special port, what to do in that case?

**Comment by Superpapotas** [comment]
> I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

Server ip has ":" for special port, what to do in that case?

**Comment by l1ving** [comment]
Nothing. Works perfectly fine on Linux

**Comment by l1ving** [comment]
> I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

Nothing. Works perfectly fine on Linux

**Comment by ehylo** [comment]
mfw

**Comment by Superpapotas** [comment]
> > I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.
> 
> Nothing. Works perfectly fine on Linux

So, that means i cant use baritone in windows because it works only on linux?

**Comment by scorbett123** [comment]
> > > I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.
> > 
> > 
> > Nothing. Works perfectly fine on Linux
> 
> So, that means i cant use baritone in windows because it works only on linux?

No, baritone works on windows, however problems such as this are sometimes caused by OS, just make sure that it just the alphabet, not weird Unicode characters.

**Comment by ThisIsanAlt** [comment]
> Server ip has ":" for special port, what to do in that case?

Like scorbett said, make sure there are no trailing weird unicode characters afterwards.

Also, I closed the issue ages ago, no need to try to reproduce lmao
