### ISSUE TITLE
Mine but wont run

### ISSUE THREAD

**Issue by gigante7** [cabaletta/baritone#2410]
Mines blocks that are close but doesnt run and i cant run myself for version 1.12.2
Note this is on a pixelmon server

**Comment by scorbett123** [comment]
Can you fill in the bug template. It is there for a reason.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
