### ISSUE TITLE
any way to quickly do a speedbridge

### ISSUE THREAD

**Issue by stylinnile** [cabaletta/baritone#2415]
I just want baritone to do a simple speedbridge like it does when tunnel but standalone. is this possible?

**Comment by l1ving** [comment]
yes

**Comment by stylinnile** [comment]
how

**Comment by scorbett123** [comment]
Just make baritone go somewhere that it needs to bridge, there is of course a quite high coefficient for it so it won't do it all the time, however will if it has no other options.

**Comment by ZacSharp** [comment]
Or use `#tunnel` where you want your bridge and it will almost always opt for placing, because tunneling has a really high penalty for leaving the straight path.
If you need a wider bridge use a schematic and buildRepeat.
