### ISSUE TITLE
Baritone doesnt mine purple Terracotta, ive tried #mine purple_Terracotta but it doesnt work

### ISSUE THREAD

**Issue by InstaGG** [cabaletta/baritone#2416]
Baritone doesnt mine purple Terracotta, ive tried #mine purple_Terracotta but it doesnt work 

im using it for prison server so i have to mine purple terracotta

**Comment by scorbett123** [comment]
Do you get any errors in chat.?

**Comment by InstaGG** [comment]
Error at argument #1: Expected ForBlockOptionalMeta

**Comment by ZacSharp** [comment]
just use the correct block id instead of trying to use the name with underscores instead of spaces
The search bar in the issues section of this repo is a useful tool by the way.
I already told someone else about the block id of terracotta, find it yourself.

**Comment by InstaGG** [comment]
thankyou
