### ISSUE TITLE
Add specific block every x amount of blocks

### ISSUE THREAD

**Issue by LucasGDpro** [cabaletta/baritone#2419]
I'd like a command in which if I enable a "tunnel" command to tunnel for 5000 blocks, I'd like the bot to place a torch every 10-20 blocks to light up the area. Maybe even make the block customizable as well as the location.

Its probably possible to change what block baritone places every x amount of blocks

It'd make it a lot easier to make overworld highways in anarchy servers.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Oh my god this has literally been suggested 50 times

**Comment by LucasGDpro** [comment]
I jus wanted to help expand baritone :( is it going to be added?

**Comment by l1ving** [comment]
Yes, the original issue is still open.

**Comment by ZacSharp** [comment]
And until that is done you can just make a schematic containing a 10 blocks long section of your tunnel and use buildRepeat to make Baritone repeat it along the tunnel.
