### ISSUE TITLE
Baritone doesn't work on forge.

### ISSUE THREAD

**Issue by mrcackalacky** [cabaletta/baritone#2421]
## Some information
Operating system: Windows 10
Java version: Java 8 Build 271
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): 
AmbientSounds_v3.1.4_mc1.16.4.jar
Apotheosis-1.16.3-4.4.1.jar
AutoRegLib-1.6-47.jar
baritone-standalone-forge-1.6.2.jar
caelus-forge-1.16.5-2.1.2.2.jar
charm-forge-1.16.4-2.1.9.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
citadel-1.5.3.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
CraftPresence-Forge-1.16.4-Release-1.7.6.jar
create-mc1.16.3_v0.3e.jar
CreativeCore_v2.0.10_mc1.16.4.jar
curios-forge-1.16.5-4.0.4.0.jar
curiouselytra-forge-1.16.5-4.0.2.0.jar
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar
dcintegration-2.0.9-1.16.jar
EnderStorage-1.16.4-2.7.1.166-universal.jar
ForgivingVoid_1.16.3-5.2.0.jar
furniture-7.0.0-pre19-1.16.3.jar
gravestone-1.16.4-1.0.8.jar
immersive-portals-0.14-mc1.16.4-forge.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar
inventorypets-2.0.11.jar
ironchest-1.16.4-11.2.10.jar
ironshulkerboxes-1.16.4-5.1.11.jar
jei-1.16.4-7.6.1.65.jar
JustEnoughCalculation-1.16.4-3.6.3.jar
JustEnoughResources-1.16.4-0.12.0.104.jar
Kiwi-1.16.3-3.4.1.jar
Ma-Essentials-1.16.3-3.4.0.jar
mcw-bridges-1.0.5-mc1.16.5-4.jar
mining-helmet-1.16.4-2.0.0.jar
MixinBootstrap-1.0.5.jar
Morpheus-1.16.4-4.2.68.jar
Neat 1.7-27.jar
OptiFine_1.16.4_HD_U_G5.jar
paintings-1.16.4-7.0.0.1.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodcore-1.16.3-1.0.1.jar
pamhc2foodextended-1.16.3-1.0.0.jar
pamhc2trees-1.16.3-1.0.0.jar
performant-1.16.2-4-3.30m.jar
Placebo-1.16.4-4.4.1.jar
polymorph-forge-1.16.4-0.23.jar
Quark-r2.4-300.jar
QuarkOddities-1.16.3.jar
ratlantis-1.0.0-1.16.3.jar
rats-7.1.0-1.16.5.jar
reliquary-1.16.3-1.3.4.1061.jar
scuba-gear-1.16.4-1.0.1.jar
SnowRealMagic-1.16.4-2.3.0.jar
SoundFilters-0.14_for_1.16.2.jar
SpartanShields-1.16.4-2.1.1.jar
SpartanWeaponry-1.16.4-2.1.0-beta-3.jar
StorageDrawers-1.16.3-8.2.2.jar
theoneprobe-1.16-3.0.7.jar
Waddles-1.16.4-0.8.11.jar
WaterStrainer-1.16.3-10.0.0.jar
worldedit-forge-mc1.16.3-7.2.2-dist.jar

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/5915064/latest.log)
The Baritone stuff is toward the bottom
Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I type "#goto 0 70 0"
Then I see the pathfinder line pop up but I dont move. It sees the path it needs to take but doesn't move my player.
The same thing happens with mining. It shows the path and renders the ore box but doesn't goto or mine the ores.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Uninstall the other mods

**Comment by rlelchev** [comment]
I think the game is overloading. I looked at your latest.log file and everything is working fine - the mods are loading, Baritone detects your command, but doesn't go to do the task. I think this is in Sponge server. Am i right?

**Comment by wagyourtail** [comment]
Its immersive portals replacing the chunk provider
