### ISSUE TITLE
How to plant trees when cutting down trees

### ISSUE THREAD

**Issue by MyICEY** [cabaletta/baritone#2422]
title

**Comment by l1ving** [comment]
use the scroll wheel on your mouse to select the sapling, and right click with your mouse to place it

**Comment by ChillerDragon** [comment]
@5HT2 this is the baritone repository. So the question was probably about how to let baritone replant trees automatically. So it can be left unattended for farming wood.

**Comment by jovylle** [comment]
didn't effort to demostrate more, but i also have this thing want baritone to do
