### ISSUE TITLE
baritone is messing up builds

### ISSUE THREAD

**Issue by ranger4052** [cabaletta/baritone#2423]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
i was building a redeemer schematic in an anarchy server. And after finishing about half of the build I ran out of obsidian so I had to close my game and switch to my duping client. When I came back I tried to build the schematic again using baritone but it started destroying the old progress. Like schematic mod which puts the schematic on top of the already existing structure, I want to know if there is a way to that in baritone.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
General troubleshooting should be done on the [Impact Discord](https://impactclient.net/discord)
