### ISSUE TITLE
1.17 baritone

### ISSUE THREAD

**Issue by SillyBillBo** [cabaletta/baritone#2425]
how long does it take for baritone to update to the next version? such as 1.17 when it releases

**Comment by scorbett123** [comment]
It depends, there might be a lot of remapping done, or there might be none. It also depends on how many changes is made to the backend of minecraft code. In some cases this could take a couple of days, in others it might take a few weeks, maybe even a month. We also depend on leijurv to do this sort of stuff, which means that it might never happen for about 6 years.

**Comment by scorbett123** [comment]
> I've been waiting for 1.17 baritone. When does the 1.17 Baritone going to Release

Baritone will eventually be updated, currently we are waiting on forge 1.17 before we start working towards doing the update.

**Comment by TemperedRelic24** [comment]
what about fabric its already at 1,17 mean while 1.17 forge opens

**Comment by scorbett123** [comment]
> what about fabric its already at 1,17 mean while 1.17 forge opens

Currently the fabric build requires forge on the backend. This is due to the way that the project has evolved meaning that updating is completely dependant on forge.

**Comment by wagyourtail** [comment]
actually, there's kinda a point since forge is now forcing mojmap... we could do the fabric build first, migrating to mojmap and expect it to "just work" on forge... as it currently "just works" on fabric...

**Comment by GGAYUSH123** [comment]
So you soon gonna update to 1.17 fabric before forge comes as it will take time ??

**Comment by scorbett123** [comment]
> So you soon gonna update to 1.17 fabric before forge comes as it will take time ??

Currently to update fabric we need forge first.

**Comment by Decme** [comment]
Can the Forge dependency be dropped somehow? Fabric updates so quickly and Forge takes forever.

**Comment by wagyourtail** [comment]
> Can the Forge dependency be dropped somehow? Fabric updates so quickly and Forge takes forever.

#2814 applied with my fork, wip 1.17 chunk cache and some other stuff is probably broken, and if #2814 is rejected i should be able to rebase 1.17 onto the current toolchain

**Comment by MrMagmaQuartzYT** [comment]
can we convert  a 1.16.5 fabric baritone mod to 1.17 using config?

**Comment by scorbett123** [comment]
> can we convert a 1.16.5 fabric baritone mod to 1.17 using config?

Nope, it is more complex than that to port a mod.

**Comment by Atlas7005** [comment]
Peeps, when Forge 1.17 is done and released, I trust that this will be updated VERY quickly. Be patient and keep an eye out for updates. If you want to help speed up the process, you can use any coding skills you may have and help update it, maybe even make it independent of Forge so something like this is less likely to happen again.

**Comment by wagyourtail** [comment]
> If you want to help speed up the process, you can use any coding skills you may have and help update it, maybe even make it independent of Forge so something like this is less likely to happen again.
#2814

**Comment by monkeyboyt** [comment]
> "It depends, there might be a lot of remapping done, or there might be none. It also depends on how many changes is made to the backend of minecraft code. In some cases this could take a couple of days, in others it might take a few weeks, maybe even a month. We also depend on leijurv to do this sort of stuff, which means that it might never happen for about 6 years."

So... I'm guessing leijurv is making it take 6 years, or never happen at all.

**Comment by wagyourtail** [comment]
see #2850

**Comment by DartsgameGokai** [comment]
Can wee test the beta to help you?

**Comment by wagyourtail** [comment]
You can access it in the assets zip at https://github.com/cabaletta/baritone/actions/runs/1044190429 post issues as comments in #2850 or find me on the baritone discord

**Comment by lticxel** [comment]
Heyy 1.17 forge is out so is baritone gonna update soon or is it gonna take some time? :)

**Comment by LysiBee** [comment]
> Heyy 1.17 forge is out so is baritone gonna update soon or is it gonna take some time? :)

Just wait, in discord you can see updates and other info about 1.17 baritone

**Comment by wagyourtail** [comment]
> forge doesn't have mixin for 1.17

**Comment by CjTheGod27** [comment]
> > what about fabric its already at 1,17 mean while 1.17 forge opens
> 
> Currently the fabric build requires forge on the backend. This is due to the way that the project has evolved meaning that updating is completely dependant on forge.

How come there are clients that use baritone for 1.17.1? How do they work?

**Comment by wagyourtail** [comment]
> see #2850

**Comment by Hacker12456** [comment]
> You can access it in the artifacts zip at https://github.com/cabaletta/baritone/actions/runs/1044190429 post issues as comments in #2850 or find me on the baritone discord

Um when I put it in my mods folder it doesnt do anything

**Comment by 10maurycy10** [comment]
> > can we convert a 1.16.5 fabric baritone mod to 1.17 using config?
> 
> Nope, it is more complex than that to port a mod.

yup, if you just change the minecraft version it will crash.

**Comment by Poliano** [comment]
There is a way to run sodium (baritone) in 1.17.: https://github.com/CaffeineMC/sodium-fabric/releases

**Comment by DavidTrack** [comment]
@wagyourtail i just noticed your question, no, i don't have immersive portals installed

**Comment by Poliano** [comment]
> @wagyourtail maybe it's the version of baritone that I'm using, how did you get the baritone version that you tested? Can you link it or suggest me how to get it? Have a nice day

Try this version of Sodium/Baritone:
https://drive.google.com/file/d/175Z1blxVBCVgqNdzEl1nhoP5l23nu8xD/view?usp=sharing

**Comment by wagyourtail** [comment]
yep that's the version I tested with...
try with this baritone version https://github.com/cabaletta/baritone/actions/runs/1394944956
if it doesn't list, post your modlist as a screenshot or something

**Comment by DavidTrack** [comment]
At the moment i'm trying to start the game with that sodium mod but the game keep crashing.
[crash-2021-11-01_11.49.39-client.txt](https://github.com/cabaletta/baritone/files/7452538/crash-2021-11-01_11.49.39-client.txt)

**Comment by wagyourtail** [comment]
yes, I can see that with the crash report now, I think one of the other mods is causing an issue, if you can figure out which one I might be able to see if I can do anything to fix it. 

this might help with making that faster:
1. Remove half of your mods and see if the issue still persists
2. If the issue is still happening then you know the issue is within this half, If the issue does not still happen it is within the half that you removed
3. Get the chunk of mods that the issue is still within and repeat until you find the trouble mod

**Comment by DavidTrack** [comment]
@wagyourtail  @Poliano  guys, you did it, i used the sodium+iris and the baritone release that you suggested and in singleplayer it works. Good job 👍
