### ISSUE TITLE
JSON file for usage of Baritone with OptiFine (MC 1.16.5)

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2426]
## Describe your suggestion
This is an updated version of [#797](https://github.com/cabaletta/baritone/issues/797). The one I made for 1.16.4 didn't work, so I looked closely and fixed the problem. I was going to make a PR out of this but couldn't find a place to add it.

## Settings
Replace the contents of the .JSON file from 

**Windows:**
`.minecraft/versions/1.16.5-OptiFine_HD_U_G6`

**MacOS:**
Open finder, navigate to the top bar `Go`, click it and hold down alt. `Library` should appear. Click on it, find `ApplicationSupport`, then find `minecraft`. Go to `versions` and find your OptiFine folder.

With the text below:
```
{
  "id": "1.16.5-BariFine",
  "inheritsFrom": "1.16.5",
  "time": "2021-02-02T10:00:42+11:00",
  "releaseTime": "2021-02-02T10:00:42+11:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.16.5_HD_U_G6"
    },
    {
      "name": "optifine:launchwrapper-of:2.2"
    },
    {
      "name": "cabaletta:baritone-api:1.6",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "https://repo1.maven.org/maven2/"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker",
      "--tweakClass",
      "baritone.launch.BaritoneTweaker"
    ]
  }
}
```

## Final checklist
- [ ] Copy
- [ ] Paste
- [ ] Click
- [ ] Run

**Comment by l1ving** [comment]
I'm closing this as it isn't really a suggestion
