### ISSUE TITLE
Baritone doesn't scan for dropped items during #sel ca

### ISSUE THREAD

**Issue by Badwolf369** [cabaletta/baritone#2427]
## Some information
Operating system: Windows 10
Java version: 1.8.0
Minecraft version: Fabric 1.16.4
Baritone version: 1.6.2
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5923628/latest.log)

## How to reproduce
create an area selection, make sure #minescandroppeditems is set to true, then run #sel ca and watch as baritone leaves blocks on the ground to despawn

## Modified settings
allowInventory: true
assumeWalkOnWater: true
blockReachDistance: 4.3
blocksToAvoidBreaking: iron_ore, coal_ore, redstone_ore, diamond_ore, emerald_ore, gold_ore
buildInLayers: true
chatControl: false
layerOrder: true
mineDropLoiterDurationMSThanksLouca: 1000

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It is called <code>**mine**ScanDroppedItems</code> because it only affects `#mine`.
`#sel` (and anything else that does not use the `MineProcess`) not scanning for items is intended behaviour, not a bug
