### ISSUE TITLE
How to find mobs?

### ISSUE THREAD

**Issue by rlelchev** [cabaletta/baritone#2428]
## What do you need help with?
I want to find horses. I noticed, that there is a command "#goto [block]" Is there a way i can find an entity? I'm using baritone with Impact 1.12.2

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#help follow

**Comment by rlelchev** [comment]
#follow is looking for entities near you. I want to find mobs even if they are away like with #goto [block]. Is it possible?

**Comment by l1ving** [comment]
no
