### ISSUE TITLE
Always mlg

### ISSUE THREAD

**Issue by WahidIslamLinad** [cabaletta/baritone#2431]
## Describe your suggestion
Adding a option of mld which will work even when im not pathfinding

## Context
dieing from fall damage is obviously a pain while playing Minecraft..but baritone has auto mlg feature while pathfinding but it's only limited to that feature..so if there's a way to make it work it would be great ig🤔

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
I think that this is out of scope for baritone, it doesn't really fit in the description, maybe add this request to a client or something, but not here.
