### ISSUE TITLE
How do I build a schematic which requires more materials than can fit in my inventory?

### ISSUE THREAD

**Issue by NotADinosaur** [cabaletta/baritone#2432]
How do I build a schematic which requires more materials than can fit in my inventory?
I have build small schematics which I can hold all the materials needed before, and I’m wanting to build a very large one but I’m not sure how to do it, it keeps failing with "unable to build, canceling"

## Final checklist
- [✅] I know how to properly use check boxes 
- [✅ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
You cannot.

**Comment by ZacSharp** [comment]
Split it into multiple smaller schematics it can build with one inventory.
