### ISSUE TITLE
Not Actually Building when Using #Build

### ISSUE THREAD

**Issue by dcjvliet** [cabaletta/baritone#2434]
## Some information
Operating system: PC
Java version: 8. something something
Minecraft version: 1.16.5, using 1.12.2 schematica
Baritone version: latest
Forge mods (if used): none

[2021-01-16-1.log.gz](https://github.com/cabaletta/baritone/files/5936100/2021-01-16-1.log.gz)

## How to reproduce
I had spent hours figuring out how to get a schematica file for 1.16.5, and finally had figured it out. I then went into 1.16.5 and did #Build Useless_Machine.schematic. Baritone then responded with ok building now at ~ ~ ~ (Don't know exact coordinates). it then path found, sat there and did nothing, in blocks that it should have been placing. It was trying to path find forward and up, but just wouldn't move. Here is screenshot

![2021-02-06_02 15 42](https://user-images.githubusercontent.com/78621484/107106009-64c2c080-67f7-11eb-98b6-fd50ffa9ab83.png)
![2021-02-06_02 15 50](https://user-images.githubusercontent.com/78621484/107106011-67bdb100-67f7-11eb-9c7b-cc134159da6d.png)

## Modified settings
allowInventory
avoidance
allowParkour
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
do you have sodium installed
