### ISSUE TITLE
Bot can no longer find a way

### ISSUE THREAD

**Issue by Altonos** [cabaletta/baritone#2436]
## Some information
Operating system: Win10
Java version: 1.8.0_51
Minecraft version: 1.16.4
Baritone version: 1.6.2

Hey ho I think I found a bug.
If there are caves or holes nearby, the bot will stop working.

## How to reproduce
https://youtu.be/KIxIZCy9QFY?t=39

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
[debug-1.log](https://github.com/cabaletta/baritone/files/5936666/debug-1.log)

**Comment by scorbett123** [comment]
This is a duplicate.

**Comment by Altonos** [comment]
Oh sorry
