### ISSUE TITLE
Pick up drops from mined blocks

### ISSUE THREAD

**Issue by EvModder** [cabaletta/baritone#2437]
`@mine spawner chest` is excellent way to find dungeons (especially with SilkSpawners), but it's a bit unfortunate how if there is, say, an `enchanted_golden_apple` in the chest there is no way to tell the client to pick it up.
When mining diamonds with `@mine diamond_ore`, baritone will wait to pick up the diamonds before moving on, but no such setting exists for non-Block items.

Something similar would be nice for `chest_minecart`s, but that probably deserves its own issue (currently they can be followed, but baritone doesn't know how to attack/break them).

**Comment by l1ving** [comment]
change the mine loiter setting
