### ISSUE TITLE
Baritone avoids targeted block

### ISSUE THREAD

**Issue by 4Orion4** [cabaletta/baritone#2438]
I have used baritone on version 1.12.2 and have had no problems. I recently have installed it for 1.16.4 and have encountered a major problem. I tell baritone to mine say redstone. It find a path and starts mining, but when it gets close to the block, it diverts its path an doesn't mine it. It constantly changes its path and doesn't mine any of what I tell it to. I used standalone baritone and baritone that comes incorporated with a hacked client and the problem is the same. Is this something other people have encountered before? How can I fix it?
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): Optifine and Aristois

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5937872/latest.log)

## How to reproduce
I simply told baritone to mine a specific block.

## Modified settings
I have no modified settings.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
