### ISSUE TITLE
Version Not Showing in Creating Installation

### ISSUE THREAD

**Issue by NicholasBastion** [cabaletta/baritone#2439]
The version will not show up regardless of what I do. I've tried multiple times to create the installation, but it won't show.

![image](https://user-images.githubusercontent.com/67483895/107132633-554e8080-68a6-11eb-9a64-b3791ef8af68.png)

**Comment by l1ving** [comment]
General troubleshooting should be done on the [Impact Discord](https://impactclient.net/discord)
