### ISSUE TITLE
Autominer not working when ore is right there(doing this again cause i filled it out wrong again)

### ISSUE THREAD

**Issue by Sanityfrog502** [cabaletta/baritone#2442]
## Some information
Operating system:pc
Java version:idk how to find it
Minecraft version:1.16.4
Baritone version:1.6.3
[debug.log](https://github.com/cabaletta/baritone/files/5938240/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/5938241/latest.log)

Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i dont know what this means
## Modified settings
To get the modified settings run `#modified` in game
allowinventory true
## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Do you have a pickaxe in your inventory?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
