### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Geir-tools** [cabaletta/baritone#2443]
## Some information
Operating system: Windows 10
Java version:
Minecraft version: 1.12.2 (Ares client)
Baritone version: Idk
Forge mods (if used):  14.23.5.2854

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/5939254/latest.log)

## How to reproduce
Trying to log to a world

## Modified settings
Nothing

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
What is actually happening?

**Comment by l1ving** [comment]
I don't understand why it's so hard to fill out the issue template properly. 

Go [**here**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md) and fill in ALL of the requested information
