### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by moonies44** [cabaletta/baritone#2444]
## Some information
Operating system: win 10
Java version:
Minecraft version: 1.16.4
Baritone version: latest
Forge mods (if used): meteor client

## Exception, error or logs
no errors

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
clicking location in chat when wanting to baritone walk somewhere. does not allow it can not use the command 
![Screenshot_4](https://user-images.githubusercontent.com/66435479/107162048-8dce8700-6998-11eb-9557-fab28eef3de0.png)

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
CNR on vanilla Baritone.

**Comment by moonies44** [comment]
not sure what CNR on vanilla Baritone means , sorry

**Comment by l1ving** [comment]
Cannot reproduce

**Comment by ZacSharp** [comment]
There's a "&a" before the command prefix. I guess you have some chat module for coloured chat enabled and should turn it off.
