### ISSUE TITLE
Ignore air?

### ISSUE THREAD

**Issue by samusmclame** [cabaletta/baritone#2445]
## What do you need help with?
I have an underground build that I want to do. The base it self is sounded by air blocks because I want pretty much anything to be allowed to occupy that space. Is there a way to do this with baritone? I've looked and there doesn't seem to be any thing I could find in the documents but I might just be wrong. Obviously I want it to be able to hollow, so ignore all air wouldn't work. Is there a work around for this? Is it best to just fill the exterior with dirt? This is for survival so resource management is a factor.
UwU

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Not yet possible.
