### ISSUE TITLE
How do I use baritone mine command for mod added ores?

### ISSUE THREAD

**Issue by silentscreams90** [cabaletta/baritone#2446]
I’m using the baritone forge api for Minecraft version 1.16.4 . I have read an closed issue after doing multiple searches online and cannot find a single post about this issue. I use the command .b mine <modname>:<theidoftheoreiktryingtohorde> but keep getting “expected whitespace to end one argument but found trailing data” this also occurred with the versions other commands even basic ones like farm . When I type .b and tab the commands the only commands that show up is go to, mine and , help . I have also noticed help 2-x doesn’t work at all and gives the same error. It seems like my command list is severely limited . I understand this is more than one question but in sake of flooding the issues tab I tried to keep it in one post. 

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
#mine modName:blockName to mine modded ores.

What blocks are you trying to do this with? File a bug report and send logs. Logs are glorious things that mean that we can understand what is going on.

**Comment by silentscreams90** [comment]
![unknown2](https://user-images.githubusercontent.com/78727728/107205193-8ffe0900-69cb-11eb-8642-85ae3e3d0ac1.png)
![unknown1](https://user-images.githubusercontent.com/78727728/107205198-90969f80-69cb-11eb-91b5-f49f55b14297.png)
![unknown](https://user-images.githubusercontent.com/78727728/107205200-912f3600-69cb-11eb-95b2-8999899c0dda.png)
there really isint a log output that im aware of when it comes to this.

i have done what another user suggested in a issue someone posted awhile back asking about how make baritone mine modded ores and in the pictures i have uploaded this is my return

**Comment by scorbett123** [comment]
Have you tried just running them, the auto complete isn't built into baritone (at least not in 1.12) so I believe that that is impact, so just try with the other commands. Just a query, what minimap are you using?

**Comment by l1ving** [comment]
#mine modid:blockid:damage

**Comment by silentscreams90** [comment]
> #mine modid:blockid:damage

![does not work 2](https://user-images.githubusercontent.com/78727728/107247370-33b4dc80-69ff-11eb-90a9-b6a15ff92e50.png)
![does not work](https://user-images.githubusercontent.com/78727728/107247373-344d7300-69ff-11eb-9123-9756f6cca111.png)
![does not work 3](https://user-images.githubusercontent.com/78727728/107247662-81c9e000-69ff-11eb-9fbf-ecae609eac8e.png)

I have already tried that and it gave me that same error  . these are the screen shots , my issue still is not solved

**Comment by silentscreams90** [comment]
> Have you tried just running them, the auto complete isn't built into baritone (at least not in 1.12) so I believe that that is impact, so just try with the other commands. Just a query, what minimap are you using?

i believe its ftb chunks

**Comment by silentscreams90** [comment]
Nothing ?

**Comment by scorbett123** [comment]
Try without having damage at the end. Except from that idk.

**Comment by xf64sdm** [comment]
Hey I found the solution, Juste press F3 + H and with this you will see item id, juste do .mine modname_other:orename 
Ex : .mine create_new_age:magnetite_block
