### ISSUE TITLE
2b2t mining issue 

### ISSUE THREAD

**Issue by denysterepa** [cabaletta/baritone#2447]
## What do you need help with?
The issue I'm experiencing is the fact that when I enable auto mine on 2b2t server the blocks do not seem to break while mined when the player position is right next to the mined block, is there any way to tweak the bots path so that it will at least keep some minimal distance to the block? Although the bot works when mining down. But not when mining sideways. Thank you in advance.
 
here is the link to the video I have recorded to make it more clear.
https://www.youtube.com/watch?v=9F1ULVBVbts&feature=youtu.be

**Comment by berrely** [comment]
It's called lag.

**Comment by denysterepa** [comment]
It's definitely not a lag, sorry for correcting you. I have made another video just to make it a bit more clear

https://youtu.be/keR0wVaDBrg

**Comment by l1ving** [comment]
server issue
