### ISSUE TITLE
Chat clicking bug

### ISSUE THREAD

**Issue by Markg546** [cabaletta/baritone#2448]
Bug: clicking on text generated by baritone spits out the command in chat instead of executing. 
How to reproduce (on 1.16.5 fabric): save a waypoint and access it through #wp list

![image](https://user-images.githubusercontent.com/11317615/107221944-fb23fb80-6a1c-11eb-85c9-e58fc3d99314.png)

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
