### ISSUE TITLE
Chat clicking bug

### ISSUE THREAD

**Issue by Markg546** [cabaletta/baritone#2449]
## Some information
Operating system: Windows10
Java version: 1.8
Minecraft version: 1.16.5
Baritone version: 1.6.3 (fabric)

The bug occurs when clicking text generated by baritone, instead of executing it spits out the command in chat.

## Exception, error or logs
No error logs

## How to reproduce
1. Have some waypoints saved 
2. Access it through #wp list
(alternatively)
2. #wp goto death ... to select which death (image attached) 
![image](https://user-images.githubusercontent.com/11317615/107233195-fb2af800-6a2a-11eb-8f72-eeb537cd9a3f.png)

Another way to reproduce is 
1. type #help
2. click any command to show details (image attached)
![image](https://user-images.githubusercontent.com/11317615/107237658-a2119300-6a2f-11eb-891d-11103c0da2f4.png)

## Modified settings
Nothing modified

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Cannot reproduce this bug on Baritone built from source.

**Comment by Markg546** [comment]
Just compiled myself and I have to say that the [docs](https://github.com/cabaletta/baritone/blob/1.16.5/SETUP.md) lack the explanation to make a fabric version.

The problem arrises on the fabric one and sadly I dont know how to compile that one.

**Comment by l1ving** [comment]
Merge the 1.15.2 branch into the 1.16.5 branch locally, and bump the mappings.

More context in #2370, `./gradlew -Pbaritone.fabric_build build` should work after that.
It's a little finicky and manual, I do think the docs are really suffering and lacking in Baritone.

It would probably be better to go bug @leijurv to merge the branches upstream, I wanted to do it but I'm usually extremely busy. I think this is a bug specific to the jar you're using, it's possible it was built off of Fabritone or some older commit.

I will reopen this until someone other than me can confirm it doesn't happen on official 1.16.5 jars on the latest commit.

**Comment by scorbett123** [comment]
Can't reproduce on latest official 1.16.5 jar. There hasn't been any commits since the one that leijurv built for releases.

**Comment by leijurv** [comment]
> Merge the 1.15.2 branch into the 1.16.5 branch locally, and bump the mappings.

I'm not sure what you're talking about? This bug report is for 1.16.5, I released 1.16.5 for fabric a few days ago, why would 1.15.2 be involved in any way?

> Can't reproduce on latest official 1.16.5 jar.

Thx

**Comment by l1ving** [comment]
>  I released 1.16.5 for fabric a few days ago

Well I'm stupid then, I guess my local branch was outdated, I didn't have the updated gradle task.

**Comment by leijurv** [comment]
no worries

**Comment by wagyourtail** [comment]
just tested, could not reproduce on 1.16.5 using `baritone-api-fabric-1.6.3.jar`

**Comment by jiaaluo** [comment]
This issue is caused by using Wurst
https://github.com/Wurst-Imperium/Wurst7

**Comment by Markg546** [comment]
Opened it there as well but never received any feedback: https://github.com/Wurst-Imperium/Wurst7/issues/306 
It just didn't occur to me, it would break the chat like that...

Instead of testing it standalone, I built from source and still kept the other mod lol
Sorry about hastely jumping to conclusions
