### ISSUE TITLE
Updating the build it yourself setup.md

### ISSUE THREAD

**Issue by Markg546** [cabaletta/baritone#2450]
## What do you need help with?
Curently the [setup doc](https://github.com/cabaletta/baritone/blob/bot-system/SETUP.md#IntelliJ) lacks proper explanation to making a fabric version of baritone. Is it in plans to be updated in the near future?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Make  sure that you are on 1.15, then ./gradlew build -baritone.fabric_build

**Comment by l1ving** [comment]
I made a more detailed comment on your other issue, #2449
