### ISSUE TITLE
Does auto mine work in the neither?

### ISSUE THREAD

**Issue by Sanityfrog502** [cabaletta/baritone#2451]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
i was trying to mine quartz ore so i typed in "mine quartz_ore" and i even checked minecraft ids and see what is said and i typed in what the name id was typed that in too
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening

**Comment by Sanityfrog502** [comment]
i went on there and copy quartz_ore and it still did not work it says "Error at argument #1648 "

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
