### ISSUE TITLE
Auto mine does not work in the nether

### ISSUE THREAD

**Issue by Sanityfrog502** [cabaletta/baritone#2452]
## Some information
Operating system: pc
Java version: 8
Minecraft version: 1.16.4
Baritone version:1.6.3
Forge mods (if used): lifematica but for fabric
[debug.log](https://github.com/cabaletta/baritone/files/5949660/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/5949661/latest.log)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i keep saying stop and cancel and keep trying the mine quartz_ore and it did not work 
## Modified settings
To get the modified settings run `#modified` in game
the only one i changed was viewinventory
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Can't reproduce this issue
