### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by bobzaaaa** [cabaletta/baritone#2454]
## Some information
Operating system: windows 10
Java version:8
Minecraft version:1.16.5
Baritone version:1.6.1
Forge mods (if used): no

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[10:16:30] [main/INFO]: [CHAT] [Baritone] > build cristo
[10:16:30] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[10:16:30] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=-121,y=4,z=-101}
[10:16:30] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
put on the layer for layer and it wont start
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Do you have all of the required blocks in your inventory?

**Comment by bobzaaaa** [comment]
> Do you have all of the required blocks in your inventory?

yes it was only stone

**Comment by l1ving** [comment]
Not enough information to reproduce the issue.
