### ISSUE TITLE
allowOnlyExposedOresDistance doesn't change anything when configured

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#2455]
## Some information
Operating system: Windows 10
Java version: 8 update 251
Minecraft version: 1.16.5
Baritone version: 1.6.1
Forge mods (if used): using fabric (with fabritone) with "appleskin", "cmdkeybind", "easierchests", "fabric api", "meteor client", "modmenu", "mousetweaks", "optifabric", "optifine", "torohealth"

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5953001/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
[prefix]allowonlyexposedoredistance (anything else than the default 1) and then enable legitmine and let it run. You'll see the range it's looking for doesn't change even though you changed the setting.

## Modified settings
acceptablethrowawayitems
allowdiagonalascend
allowdiagonaldescend
allowdownward
allowonlyexposedoredistance (for the test 100 but also tried lower values)
allowparkour
allowparkourplace
allowwalkonbottomslab
avoidance
blockbreakadditionalpenalty
blockplacementpenalty
blockreachdistance
blockstoavoid
blockstoavoidbreaking
buildertickscanradius
cachedchunksopacity
(almost everything of the color change stuff im not gonna list)
costheuristic
exploreforblocks
exploremaintainy
failuretimeoutms
followoffsetdirection
freelook
goalrenderlinewidthpixels
legitmine
maxcachedworldscancount
maxfallheightbucket
minedroploiterdurationmsthankslouca
minescandroppeditems
mobavoidanceradius
pathingmaploadfactor
pathrenderlinewidthpixels
planaheadfailuretimeoutms
planaheadprimarytimeoutms
prefix
primarytimeoutms
selectionlinewidth
selectionopacity
simplifyunloadedycoord
slowpathtimeoutms
toasttimer
worldexploringchunkoffset

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Yes it does, make sure that you have enabled allowOnlyExposedOres.

**Comment by scorbett123** [comment]
And it isn't meant to work with legit mine, it is meant to be a non-legit version of legit-mine that gets around ore obfuscators.

**Comment by Tendas240** [comment]
> And it isn't meant to work with legit mine, it is meant to be a non-legit version of legit-mine that gets around ore obfuscators.

if i run it without legitmine it will also mine underground ores..

**Comment by Tendas240** [comment]
> Yes it does, make sure that you have enabled allowOnlyExposedOres.

youre right. allowonlyexposedores wasn't enabled. but still allowonlyexposedores feature won't work.

**Comment by scorbett123** [comment]
It is meant to work without legit mine, disable legit mine, otherwise there is no point in using it.

**Comment by Tendas240** [comment]
> It is meant to work without legit mine, disable legit mine, otherwise there is no point in using it.

i did. still won't work. still mines underground ores

**Comment by scorbett123** [comment]
It was never meant to work with legit mine, and never will.

**Comment by scorbett123** [comment]
Is there a cave next to them? If not please can you provide a video for debugging purposes.

**Comment by scorbett123** [comment]
wtf is your allowOnlyExposedOresDistance, it should be set to 2 at most 3 not 100. There will always be a air block within 100 blocks on an ore

**Comment by Tendas240** [comment]
> wtf is your allowOnlyExposedOresDistance, it should be set to 2 at most 3 not 100. There will always be a air block within 100 blocks on an ore

haha :D it was just for the test to see if anything changed. i wouldnt have seen the contrast if the value wasnt that high. maybe if allowonlyexposedores isnt the feature im looking for is there the possibility change the radius legitmine will notice ores?

**Comment by scorbett123** [comment]
No legit mine only mines blocks that it has line of sight to, however to slightly increase it enable legitMineIncludeDiagonals

**Comment by scorbett123** [comment]
You are looking at the wrong setting.

**Comment by Tendas240** [comment]
> No legit mine only mines blocks that it has line of sight to, however to slightly increase it enable legitMineIncludeDiagonals

i noticed it runs past pretty obvious ores which are actually pretty near and clearly visbile.

**Comment by scorbett123** [comment]
> And also: isnt the value the amount of blocks? 1 seems pretty low.

Yes, it was primarily built for ore randomizing that isn't done close to air pockets, therefore you can assume ores there are real.

**Comment by scorbett123** [comment]
> > No legit mine only mines blocks that it has line of sight to, however to slightly increase it enable legitMineIncludeDiagonals
> 
> i noticed it runs past pretty obvious ores which are actually pretty near and clearly visbile.

Do you have the ability to send a video or screen shots of this?

**Comment by Tendas240** [comment]
> > > No legit mine only mines blocks that it has line of sight to, however to slightly increase it enable legitMineIncludeDiagonals
> > 
> > 
> > i noticed it runs past pretty obvious ores which are actually pretty near and clearly visbile.
> 
> Do you have the ability to send a video or screen shots of this?

ill try it with the diagonals setting. and if the issue persists ill try to reproduce and record it.

**Comment by Tendas240** [comment]
ill upload a video on youtube. gimme a few minutes

**Comment by Tendas240** [comment]
> > > No legit mine only mines blocks that it has line of sight to, however to slightly increase it enable legitMineIncludeDiagonals
> > 
> > 
> > i noticed it runs past pretty obvious ores which are actually pretty near and clearly visbile.
> 
> Do you have the ability to send a video or screen shots of this?

https://youtu.be/U8qbdm-LQTo
jump to 0:55

**Comment by scorbett123** [comment]
Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.

**Comment by Tendas240** [comment]
> Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.

i tried that and i ran in the other issue of it mining underground ores even though allowonlyexposedores is enabled. im already uploading another video for this on youtube. ill share the link when its done

**Comment by Tendas240** [comment]
> Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.

https://youtu.be/6GDS96UGaH0

**Comment by pozhiloy-enotik** [comment]
> 
> 
> > Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.
> 
> https://youtu.be/6GDS96UGaH0

You can try setting allowonlyexposedoresdistance to 1

**Comment by scorbett123** [comment]
> > > Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.
> > 
> > 
> > https://youtu.be/6GDS96UGaH0
> 
> You can try setting allowonlyexposedoresdistance to 1

Yep, in the video you have it at 20, if you set it lower then you should get the required behaviour.

**Comment by Tendas240** [comment]
> > > Unfortunately really it is meant for mining, and to fix that issue would require a lot of computational power, and would dramatically slow everything down. However for that use use allowOnlyExposedOres, however use it without legit mine. This way it will find all of those ores, legit mine just isn't really fit for that purpose.
> > 
> > 
> > https://youtu.be/6GDS96UGaH0
> 
> You can try setting allowonlyexposedoresdistance to 1

ok thats eems to work. so theres no option to increase the range legitmine notices ores yet?
also another question: baritone seems to have a limit of blocks you can put in "blockstoavoid". I can type in a few ingame but if i do that in the file in the explorer it doesnt save it and its gone the next time i join the game or open the file. And the chat ingame has a character limit. The problem didn't exist in earlier versions of baritone.

**Comment by scorbett123** [comment]
> ok thats seems to work. so theres no option to increase the range legitmine notices ores yet?

No, I believe that I have said this earlier.

> also another question: baritone seems to have a limit of blocks you can put in "blockstoavoid". I can type in a few ingame but if i do that in the file in the explorer it doesnt save it and its gone the next time i join the game or open the file.

Make sure to click ctrl+s before you leave the file and that baritone isn't currently running.

 >And the chat ingame has a character limit.

I believe that this is a minecraft thing. It is an in game limitation

> The problem didn't exist in earlier versions of baritone.

Maybe you just didn't type long enough messages, unless there is something that stopped the limit that I don't know about.

**Comment by Tendas240** [comment]
> > ok thats seems to work. so theres no option to increase the range legitmine notices ores yet?
> 
> No, I believe that I have said this earlier.
> 
> > also another question: baritone seems to have a limit of blocks you can put in "blockstoavoid". I can type in a few ingame but if i do that in the file in the explorer it doesnt save it and its gone the next time i join the game or open the file.
> 
> Make sure to click ctrl+s before you leave the file and that baritone isn't currently running.
> 
> > And the chat ingame has a character limit.
> 
> I believe that this is a minecraft thing. It is an in game limitation
> 
> > The problem didn't exist in earlier versions of baritone.
> 
> Maybe you just didn't type long enough messages, unless there is something that stopped the limit that I don't know about.

of course i saved the file :D 
and yes i did write long lists back then
sure thats a minecraft thing so thats why i wanted to type it in the file rather than ingame.

**Comment by scorbett123** [comment]
> of course i saved the file 

Sorry, you don't know the amount of people on here that make us spend a while debugging an unsaved file, just make sure that baritone isn't running and that the block-id's in the file are all valid, if it isn't working after that create a separate bug report, it is a long distance from what we have been talking about in this.

**Comment by Tendas240** [comment]
> > of course i saved the file
> 
> Sorry, you don't know the amount of people on here that make us spend a while debugging an unsaved file, just make sure that baritone isn't running and that the block-id's in the file are all valid, if it isn't working after that create a separate bug report, it is a long distance from what we have been talking about in this.

yes okay no problem. so i type it in the file (minecraft is not running) (block ids are valid - "vine", "rose_bush" for example) and when i start the game and type: "(prefix)blockstoavoid" it should list the things but it just shows an empty list.

**Comment by scorbett123** [comment]
Can you send me your config file

**Comment by Tendas240** [comment]
> Can you send me your config file

you mean the "settings.txt"?
[settings.txt](https://github.com/cabaletta/baritone/files/5953591/settings.txt)

**Comment by Tendas240** [comment]
> Can you send me your config file

you mean the "settings.txt"?
[settings.txt](https://github.com/cabaletta/baritone/files/5953596/settings.txt)

**Comment by Tendas240** [comment]
> Can you send me your config file

it automatically deletes the entire blockstoavoid line

**Comment by scorbett123** [comment]
[settings.txt](https://github.com/cabaletta/baritone/files/5953661/settings.txt)
Try using this, I can't reproduce your issue, so I can only assume that it is a mistake on your end. This should work for your setting files, I have tested it.

**Comment by Tendas240** [comment]
> [settings.txt](https://github.com/cabaletta/baritone/files/5953661/settings.txt)
> Try using this, I can't reproduce your issue, so I can only assume that it is a mistake on your end. This should work for your setting files, I have tested it.

i think i found

**Comment by Tendas240** [comment]
> [settings.txt](https://github.com/cabaletta/baritone/files/5953661/settings.txt)
> Try using this, I can't reproduce your issue, so I can only assume that it is a mistake on your end. This should work for your setting files, I have tested it.

it was the data value: "flowing_lava". It doesnt exist. I think it used to. I had an issue like that before when mojang changed crimson_vines to weeping_vines.
