### ISSUE TITLE
Auto mine not working in nether

### ISSUE THREAD

**Issue by Sanityfrog502** [cabaletta/baritone#2456]
## Some information
Operating system:pc
Java version:8
Minecraft version:1.16.4
Baritone version:1.6.3
Forge mods (if used): lifematica fabric
[debug.log](https://github.com/cabaletta/baritone/files/5953313/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/5953315/latest.log)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i went to the nether cause i need quartz so i typed in "mine quartz_ore" and it kept giving me a error so i asked a question on here and they said it worked in the nether and told me to make a bug report 
## Modified settings
To get the modified settings run `#modified` in game
veiwInventory
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
quartz_ore does not exist on 1.16.4

**Comment by Sanityfrog502** [comment]
then what would i type in the mine quartz?

**Comment by scorbett123** [comment]
Wow, somehow filling in the bug template properly meant that we could properly diagnose and propose a solution to your problem!!! Id is :nether_quartz_ore

**Comment by Sanityfrog502** [comment]
is there a website where i can find all of the names?

**Comment by scorbett123** [comment]
https://minecraft.gamepedia.com/Nether_Quartz_Ore#ID
