### ISSUE TITLE
Baritone's incompatibility with immersive portals (forge)

### ISSUE THREAD

**Issue by yplusz** [cabaletta/baritone#2457]
## Some information
Operating system: Windows 10
Java version: Version 8, Update 271 (build 1.8.0_271-b09)
Minecraft version: 1.16.4
Baritone version: baritone-standalone-forge-1.6.3.jar
Forge mods (if used): immersive portals for forge (immersive-portals-0.14-mc1.16.4-forge.jar)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/` 

Mac: `/Library/Application\ Support/minecraft/logs/`

My logs have a lot of other mods registred to them, but as soon as I removed immersive portals baritone began to work again. I can still share it if thats usefull

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Install baritone standalone and immersive portals to forge. Try to use #click, then select an area. Then use #sel ca, baritone won't move your character towards the blocks. If you manually position yourself next to the blocksand repeat the process, it will break the blocks, but it won't be able to recognise when all of the block have been broken, therefore, it doesn't send "done building" in the chat. Also, it completely freezes your character in place, making you unable to move, the only way to get back your controls is by using #cancel. Hope you could understand the issue, english isn't my first language. Hope this helps

## Modified settings
To get the modified settings run `#modified` in game

allowBreak, allowInventory and freeLook

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a duplicate, there is a pull to start fixing this as well.

**Comment by yplusz** [comment]
Ohhh I see, well... thank you!
