### ISSUE TITLE
Tell baritone to make staircases instead of poles

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#2458]
## What do you need help with?
Is it possible to tell baritone to make usable, walkable stairs instead of poles created by stacking up blocks into the sky (for example to get to glowstone). So is there something like "allowdownward" for placing? If im high up on a pole (which it unfortunetly created) for example i want it to build a staircase downward? Is this possible?
I know two different questions but theyre pretty related. (upward and downward)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This isn't possible at the moment.

**Comment by Tendas240** [comment]
> This isn't possible at the moment.

okay but it could be some kind of an improvement suggestion :)

**Comment by Tendas240** [comment]
> > This isn't possible at the moment.
> 
> okay but it could be some kind of an improvement suggestion :) like tunneling specific strip mine tunnels with different sub-tunnel-veins

**Comment by wellsilver** [comment]
You should change it to a suggestion then.
