### ISSUE TITLE
Old and (mostly) deprecated bot-system usage

### ISSUE THREAD

**Issue by wellsilver** [cabaletta/baritone#2459]
## What do you need help with?
Ive been looking everywhere for any kind of how to use the built in baritone bot system where I could have multiple bots with only 1 window open. I looked everywhere even youtube but all I got on youtube was just the trailer and a demo of the bots digging a hole.

TL;DR. Where do I find how to use the bot system? (allbeit i haved to use a older baritone version)

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I put a tl;dr

**Comment by scorbett123** [comment]
Use the bot system branch. You well have to build it yourself.

**Comment by wellsilver** [comment]
I have no idea how to download it, or build it.

**Comment by wellsilver** [comment]
I tried and it didnt work, I probably did a few million things wrong though.

**Comment by l1ving** [comment]
Well it's not officially supported in the docs.
