### ISSUE TITLE
Is there a way to link multiple bots together to follow same commands? If not will this ever be available?

### ISSUE THREAD

**Issue by Csquaredaap** [cabaletta/baritone#2460]
I have multiple bots and I want them both to be able to execute the same command at the same time..... is this possible?

**Comment by scorbett123** [comment]
The bot system would do this, however it has been deprecated,  so may no longer work. And you would have to build it yourself.

**Comment by Csquaredaap** [comment]
Is it already in baritone or is it a seperate download?

**Comment by scorbett123** [comment]
You would have to use git and then build it yourself, it is not in any released version.

**Comment by Csquaredaap** [comment]
Ok thx
