### ISSUE TITLE
FPS drop extremely when using (prefix)sel ca

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#2461]
## Some information
Operating system: Windows 10
Java version: 8 update 251
Minecraft version: 1.16.5
Baritone version: 1.6.1
Forge mods (if used): using fabric (with fabritone) with "appleskin", "cmdkeybind", "easierchests", "fabric api", "meteor client (with baritone support)", "modmenu", "mousetweaks", "optifabric", "optifine", "torohealth"

## Exception, error or logs
There are no errors displayed or crashed happening. Just the immense fps drop.

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Just select any area with baritone and run the cleararea command. I also reached out to the developers of the meteor client im using and they said it has nothing to do with their client so it must be baritone because i have a very strong pc.

## Modified settings
acceptablethrowawayitems
allowdiagonalascend
allowdiagonaldescend
allowdownward
allowonlyexposedoredistance
allowparkour
allowparkourplace
allowwalkonbottomslab
avoidance
blockbreakadditionalpenalty
blockplacementpenalty
blockreachdistance
blockstoavoid
blockstoavoidbreaking
buildertickscanradius
cachedchunksopacity
(almost everything of the color change stuff im not gonna list)
costheuristic
exploreforblocks
exploremaintainy
failuretimeoutms
followoffsetdirection
freelook
goalrenderlinewidthpixels
legitmine
maxcachedworldscancount
maxfallheightbucket
minedroploiterdurationmsthankslouca
minescandroppeditems
mobavoidanceradius
pathingmaploadfactor
pathrenderlinewidthpixels
planaheadfailuretimeoutms
planaheadprimarytimeoutms
prefix
primarytimeoutms
selectionlinewidth
selectionopacity
simplifyunloadedycoord
slowpathtimeoutms
toasttimer
worldexploringchunkoffset

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Hi, looking at your baritone version, there is a new version out, please go to downloads and download baritone 1.6.3 with fabric support from here: https://github.com/cabaletta/baritone/releases, please confirm if your issue still exists on this version.

**Comment by scorbett123** [comment]
Actually, can reproduce with your settings, however can't with default settings, one of your settings is causing this.

**Comment by Tendas240** [comment]
> Actually, can reproduce with your settings, however can't with default settings, one of your settings is causing this.

also with the new version? ya it would like to know which setting is causing this. im at work atm but i can test things when im home.

**Comment by Tendas240** [comment]
> Hi, looking at your baritone version, there is a new version out, please go to downloads and download baritone 1.6.3 with fabric support from here: https://github.com/cabaletta/baritone/releases, please confirm if your issue still exists on this version.

i should download the baritone standalone fabric jar and just put it in the mods folder right?

**Comment by Tendas240** [comment]
> Actually, can reproduce with your settings, however can't with default settings, one of your settings is causing this.

actually how do you know my setting values? :D

**Comment by scorbett123** [comment]
Yesterday you send me your settings.txt, I believe.

**Comment by scorbett123** [comment]
> > Hi, looking at your baritone version, there is a new version out, please go to downloads and download baritone 1.6.3 with fabric support from here: https://github.com/cabaletta/baritone/releases, please confirm if your issue still exists on this version.
> 
> i should download the baritone standalone fabric jar and just put it in the mods folder right?

yep

**Comment by Tendas240** [comment]
> Yesterday you send me your settings.txt, I believe.

ah ye i forgot xD good

**Comment by scorbett123** [comment]
> > Actually, can reproduce with your settings, however can't with default settings, one of your settings is causing this.
> 
> also with the new version? ya it would like to know which setting is causing this. im at work atm but i can test things when im home.

I can do more testing later, however it won't be one of the rendering settings, might be blocks to avoid breaking.

**Comment by Tendas240** [comment]
> > Yesterday you send me your settings.txt, I believe.
> 
> ah ye i forgot xD good

im still so glad that the blockstovoid setting finally works. it is so useful

**Comment by Tendas240** [comment]
> > > Actually, can reproduce with your settings, however can't with default settings, one of your settings is causing this.
> > 
> > 
> > also with the new version? ya it would like to know which setting is causing this. im at work atm but i can test things when im home.
> 
> I can do more testing later, however it won't be one of the rendering settings, might be blocks to avoid breaking.

oh okay ._. but what does blockstoavoidbreaking has to do with it?

**Comment by scorbett123** [comment]
If it needs to scan every block it might delay it, however I don't think it would be this much, I am going to test it further later, I imagine that it is a group of settings causing this issue.

**Comment by Tendas240** [comment]
> If it needs to scan every block it might delay it, however I don't think it would be this much, I am going to test it further later, I imagine that it is a group of settings causing this issue.

ok thank you. im waiting for your answer :)

**Comment by scorbett123** [comment]
It isn't blocksToAvoidBreaking, but I don't know what it is, will test further.

**Comment by Tendas240** [comment]
> It isn't blocksToAvoidBreaking, but I don't know what it is, will test further.

appreciate it

**Comment by Tendas240** [comment]
btw do you have a discord? this way i dont always have to create a post for every little question and i can ask more if there are any questions.

**Comment by scorbett123** [comment]
There isn't an official one, however you can dm me, scorbett123#5313.

**Comment by scorbett123** [comment]
The issue you are experiencing is with builderTickScanRadius, you had it set to 100, with it set to 5 (the default) the problem no longer exists.

**Comment by Tendas240** [comment]
> There isn't an official one, except impact which I am not in., however you can dm me, scorbett123#5313.

okay nice thx. will do if i have any question

**Comment by Tendas240** [comment]
> The issue you are experiencing is with builderTickScanRadius, you had it set to 100, with it set to 5 (the default) the problem no longer exists.

oh okay nice one thank you very much. i changed this setting because i wanted the mine command to update more frequent because i experienced it walking right next to a ore vein while favoring another one which is much further away.

**Comment by scorbett123** [comment]
That would be done by a different setting, mineGoalUpdateInterval. It is probably due to something wrong with the ore vein though, such as lava behind or above it.

**Comment by Tendas240** [comment]
> That would be done by a different setting, mineGoalUpdateInterval. It is probably due to something wrong with the ore vein though, such as lava behind or above it.

yes thats what i thought but its a normal vein which will be mined if i cancel and run the mine command again.

**Comment by scorbett123** [comment]
If you can reproduce that and send the settings in please create another issue. That sounds like a proper bug.

**Comment by l1ving** [comment]
Fabritone is unsupported. Please open a bug report with the steps to reproduce this issue, including which setting needs to be changed
