### ISSUE TITLE
Bot Wont Follow Players Through Portals

### ISSUE THREAD

**Issue by Csquaredaap** [cabaletta/baritone#2465]
So i have a bot and I want him to follow me into a portal but the second i go thru 1 he stops and loses me. Is there a way to get him to follow me through portals? I think I have seen people do it before but they dont say how

**Comment by l1ving** [comment]
No

**Comment by l1ving** [comment]
I mean, `no`, assuming you didn't disable the `enterPortal` option

**Comment by Csquaredaap** [comment]
The enterportal option is enabled

**Comment by l1ving** [comment]
Then no

**Comment by Csquaredaap** [comment]
oh ok
