### ISSUE TITLE
Follow player command, unknown error

### ISSUE THREAD

**Issue by Koldexx** [cabaletta/baritone#2466]
When I type the command it says an unhandled exception has occurred, anyone know a fix?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
