### ISSUE TITLE
Freezing when inside a sugar cane block

### ISSUE THREAD

**Issue by lilman514** [cabaletta/baritone#2468]
when i'm AFK farming sugar cane sometimes the bot will stand inside a 3 high stalk of sugar cane and then not break it or continue moving despite telling it to replace all sugar cane with air.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
