### ISSUE TITLE
Bot does not recognize Soul Sand speed differences

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#247]
If you traverse the nether with baritone, it will eventually fall into lava while parkouring on soul sand. Does not seem to recognize the speed differences.

**Comment by leijurv** [comment]
![2018-11-05_13 45 47](https://user-images.githubusercontent.com/3837873/48028740-2f533800-e101-11e8-8bb8-eb4fa8f2c59e.png)

Thanks for the report! I've made it so that a parkour starting from soul sand can be a 1-block gap at most, not 2 or 3.

**Comment by EvilSourcerer** [comment]
Thank you for fixing this. My friend who fell into lava while parkouring across soul sand in the nether on an anarchy server appreciates this.
