### ISSUE TITLE
mining out area with #tunnel and baritone just stops in one area

### ISSUE THREAD

**Issue by stylinnile** [cabaletta/baritone#2470]
I'm trying to mine out a 10 high, 20x20 wide area with the #tunnel command it just goes to a block and stands there. I can move around manually and it mines out whatever's in range but eventually if I go to far it walks back to the block. I cant figure out what the issue is can someone help?

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
