### ISSUE TITLE
Try to place a block on top of lava

### ISSUE THREAD

**Issue by yangshuo2008** [cabaletta/baritone#2472]
When there is lava near baritone, the task stops and attempts to place the block. 
Routes are not calculated from the new.
（1.16.5）

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
