### ISSUE TITLE
Crash while trying to view replay with replay mod

### ISSUE THREAD

**Issue by notahumanthatisimportant** [cabaletta/baritone#2474]
## Some information
Operating system: linux
Java version:jdk8
Minecraft version:1.16.5
Baritone version:1.6.3
Fabric mods (if used): 
Baritone
Replay mod
Carpet
Carpet extra
Easy piglins
Easy villagers
Fabric api 
Immersive portals
Literati
Mailing
Minimum
Optifabric
Optimize
ToolSwap

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

https://drive.google.com/file/d/1_ZIuFmXqK0Y3E7DV1q9jefskw3Pu7FHs/view?usp=drivesdk

## How to reproduce
Launch minecraft with all mods running
Record replay
Leave the minecraft world
Try to view replay

## Modified settings
#prefix

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by notahumanthatisimportant** [comment]
I did look this up before I've an issue and didn't find a solution

**Comment by scorbett123** [comment]
Please can you send the log in [paste bin](https://pastebin.pl/), two things, one you haven't enabled link sharing, two, it makes sure that everyone can remain anonymous, or not have a google account.
