### ISSUE TITLE
Replay mod replay view crash

### ISSUE THREAD

**Issue by notahumanthatisimportant** [cabaletta/baritone#2475]
## Some information
Operating system:linux
Java version:jdk8
Minecraft version:1.16.5
Baritone version:1.6.3
Forge mods (if used): 
Java version:jdk8
Minecraft version:1.16.5
Baritone version:1.6.3
Fabric mods (if used):
Baritone
Replay mod
Carpet
Carpet extra
Easy piglins
Easy villagers
Fabric api
Immersive portals
Litematica
Malilib
Minihud
Optifabric
Optimize
ToolSwap

Exception, error or logs

Please find your latest.log or debug.log in this folder and attach it
https://pastebin.com/sGud0k40
latest.log
https://pastebin.com/LHPDJdFf
How to reproduce

Launch minecraft with all mods running
Record replay
Leave the minecraft world
Try to view replay

Modified settings

#prefix

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Please include the `debug.log` file

**Comment by ehylo** [comment]
> Please include the `debug.log` file

when using fabric this log does not exist

**Comment by l1ving** [comment]
I assumed it does. That's also why the issue template asks for `latest.log` *or* `debug.log`
