### ISSUE TITLE
#goto can't find a block point-blank

### ISSUE THREAD

**Issue by p2r3** [cabaletta/baritone#2477]
the "how to reproduce" section basically covers the issue: #goto just wanders aimlessly
specifically, i tested this with chests and then command blocks just to be sure it's not trying to find some far off unloaded chest it somehow remembers. nope, it walks away from the only command block on the entire map. #find and #mine worked, though.

here's a vid to show what i mean: https://youtu.be/locKpF6FPYk

and here's another video on a fresh world, except this time even #find and #mine don't work for whatever reason: https://youtu.be/aviKTPR4c_I

i might just be misunderstanding something lol

## Some information
Operating system: Linux (Debian)
Java version: 8
Minecraft version: 1.12.2
Baritone version: uhhh... the one in Impact 4.9.1?
Forge mods (if used): nope.

## Exception, error or logs
I've attached it, don't really see how it would help here:
[latest.log](https://github.com/cabaletta/baritone/files/5987766/latest.log)

## How to reproduce

place enderchests all around you
type "#goto ender_chest" in chat
watch yourself walk right past the chest :)

in my first case, #mine and #find worked flawlessly, but upon trying it in a fresh world those broke too.

## Modified settings
allowBreak = false
allowInventory = true
allowParkour = true
allowPlace = false
avoidance = true
chatControl = false
freeLook = false
maxFallHeightNoWater = 8

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Fixed in 43d5458a2
