### ISSUE TITLE
v1.2.14 forge dependency fail : could not find sponge mixin 0.7.11

### ISSUE THREAD

**Issue by DarKiiii** [cabaletta/baritone#2478]
## Some information
Operating system: Windows
Java version: 1.8.0_261-b12
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): none, trying to create dev env to make one

## Exception, error or logs
I'm trying to add the forge api as dependency for a 1.12.2 mod

Here is the build error log from jitpack : https://jitpack.io/com/github/cabaletta/baritone/33d4dd47bb/build.log

And here are the log in my terminal :
>Could not resolve all files for configuration ':compileClasspath'.
 Could not find org.spongepowered:mixin:0.7.11-SNAPSHOT.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/org/spongepowered/mixin/0.7.11-SNAPSHOT/maven-metadata.xml

## How to reproduce
1. Add baritone as dependency to a forge mod (i'm using last forge 1.12.2 MDK with IntelliJ) in gradle
```
dependencies {
   ...
   implementation 'com.github.cabaletta:baritone:v1.2.14'
}
```
2. Run `.\gradlew build --refresh-dependencies`

Thank you!

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Looking at the jitpack log, it seems to not be attempting to get mixins, this is due to a change in their end, that has meant that some urls have been changed, this may mean that you aren't able to do this until either a new release happens, or you build off of master, not off of the latest 1.12 release, due to this now having been fixed on master.

**Comment by DarKiiii** [comment]
Ok, but how should I be able to make it able to use my builded version as dependency ?

**Comment by l1ving** [comment]
Use the impact maven repository. If you insist on using jitpack, compile the master branch and not the v1.2.14 tag
