### ISSUE TITLE
Baritone With Other Mods

### ISSUE THREAD

**Issue by AxeMan04** [cabaletta/baritone#2479]
Hello, I have a question regarding Baritone and other mods. I was wondering if it's possible for the mine feature of Baritone to work with other mods. For example, would it be possible to mine Ruby Ore from the Biomes O' Plenty mod. If there is a way, then what is the command for it to work?

**Comment by scorbett123** [comment]
You can do this:

```
#mine modid:blockid
```
so in your case:
```
#mine BiomesOPlenty:gems:1
```
 should work
