### ISSUE TITLE
Unable to load schematic from litematica

### ISSUE THREAD

**Issue by Demon-tk** [cabaletta/baritone#2487]
## Some information
Operating system: Windows 10
Java version: 1.8.0_271
Minecraft version: 1.16.4
Baritone version: Null version
Forge mods (if used): Meteor client

## Exception, error or logs
https://gist.github.com/Demon-tk/461e97088254a0fcab8ea35bca97d57f
``` Couldn't load the schematic. Make sure to use the FULL file name, including the extension (e.g. blah.schematic).```

## How to reproduce
Issue the command `@build [schematic].litematic`

## Modified settings
Default

Yes, I have ensured that the schematic file is in `~/.minecraft/schematics`

I have also tied changing the extension to `.schematic` from `.litematic`

**Comment by l1ving** [comment]
it's not supported yet, and fabritone is unsupported as well
