### ISSUE TITLE
How to run baritone along other mods

### ISSUE THREAD

**Issue by Quinniboi10** [cabaletta/baritone#2488]
I am trying to run forge 1.12.2 with baritone as one of my mods, but forge will not launch, the launcher closes and the reopens a second later saying **GAME CRASHED**

I have tried the unoptimized and standalone-forge jar files (v1.2.14)
Mods:
[1.12.2]+SecurityCraft+v1.8.21.jar
[1.12.2]DamageIndicatorsMod-3.5.1.jar
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
BlockArmor-1.12.2-2.4.12.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
iChunUtil-1.12.2-7.2.2.jar
InventoryHud_1.12.2.forge-3.2.1.jar
jei_1.12.2-4.16.1.302.jar
LiquidBounce1.12.2.jar
Morph-1.12.2-7.2.1.jar
OptiFine_1.12.2_HD_U_G5_MOD.jar
PortalGun-1.12.2-7.1.0.jar
secretroomsmod-1.12.2-5.6.4.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SpartanShields-1.12.2-1.5.4.jar
SpartanWeaponry-1.12.2-beta-1.3.8.jar
WR-CBE-1.12.2-2.3.2.33-universal.jar
Xaeros_Minimap_21.3.0.2_Forge_1.12.jar
XaerosWorldMap_1.12.0.2_Forge_1.12.jar

Thanks,
Quinniboi10

**Comment by l1ving** [comment]
General troubleshooting should be done on the [Impact Discord](https://impactclient.net/discord)
