### ISSUE TITLE
Is there a way to make baritone be able to walk on soul sand?

### ISSUE THREAD

**Issue by ipxter** [cabaletta/baritone#2489]
## What do you need help with?
Would it be possible to make Baritone be able to walk on soul sand? If not #farm fails with nether wart because it cannot walk on soul-sand. How could this be fixed?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I tested this: It can walk on soul sand and `#farm` with nether warts works fine.
