### ISSUE TITLE
When will Sodium compatibility be available? 

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2490]
## What do you need help with?
Alright, let's dive in.
Sodium is a mod that I'm sure you know of, given the massive impact it's had on the community. It is a very effective FPS boosting mod. I use Fabritone (the one over at GitLab by CDAGaming, forgot why) on 1.16.5. It's very effective to travel long distances on a server I play on. I use an experimental fix of Fabritone from a user on CDAGaming's gitlab. Unfortunately, I recently ran into issues with Fabritone and Sodium. Specifically, I am using a fork of Sodium that is designed to work with the Fabric Rendering API, which lets mods have specific textures and behaviors for new items, blocks, mobs, etc. The issue I run into is here: https://gitlab.com/CDAGaming/fabritone/-/issues/78
THIS IS NOT AN ISSUE REPORT.
I believe that the CDAGaming Fabritone is a decent fix for some, but I am wondering when there will be _official_ support for Sodium. 

## Final checklist
I know how to properly use check boxes 
I have not used any OwO's or UwU's in this issue.

**Comment by CDAGaming** [comment]
Closr as invalid. this fix was proprrly added to official.

**Comment by CDAGaming** [comment]
Adittionally your using a fork which isnt officially supported.
