### ISSUE TITLE
Baritone not moving

### ISSUE THREAD

**Issue by Mochi-09** [cabaletta/baritone#2492]
## Some information
Operating system: Windows 10
Java version: Inertia Fabric 1.16.5
Minecraft version: 1.16.5
Baritone version: I am not sure
Forge mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
Idk what to do here

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
When I do .b mine diamond_ore (or any other baritone command) it shows the route but doesn't take me to the destination. For some reason whenever I am within 1 block of the thing baritone wants to mine it will mine it then stop.

## Modified settings
To get the modified settings run `#modified` in game
![Screenshot (14)](https://user-images.githubusercontent.com/79372640/108603169-5c7c9080-7374-11eb-97f0-d5952e434b4c.png)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I cannot reproduce this issue on regular Baritone. Please provide alternate steps to reproduce it on regular Baritone without Inertia.
