### ISSUE TITLE
baritone gets stuck while walking up blocks

### ISSUE THREAD

**Issue by cavan123456789** [cabaletta/baritone#2496]
## Some information
Operating system:windows
Java version:15
Minecraft version:1.16.5
Baritone version:1.6.3
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
You didn't fill in like... any of the template
