### ISSUE TITLE
Sodium compatibility with fabric 1.16.5?

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2497]
## What do you need help with?
Hi all, I use the Sodium mod to increase my performance, but as of now, it does not work with the fabric 1.16.5 release of Baritone that is available when I click on the Fabric 1.16.5 link in the readme.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Ok

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/108632856-0294cd00-743f-11eb-957b-280b65fff70b.png)

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/108632866-0fb1bc00-743f-11eb-81e1-53b2121d389d.png)

**Comment by l1ving** [comment]
use your eyes betterer
