### ISSUE TITLE
Fabritone crashes with AOF3 modpack and sodium + indium.

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2501]
## Some information
Operating system: Win 10 Pro, latest version
Java version: 11, GraalVM
Minecraft version: 1.16.5
Baritone version: Standalone 1.6.3 fabric.
Forge mods (if used): N/A
 
Errors:
https://paste.ee/p/lBC0k
https://paste.ee/p/Yjkp7

## How to reproduce
Install AOF3 modpack 2.6.9, use the Sodium + Indium version found on the Discord server. Download Fabritone standalone 1.6.3 for fabric. Launch game, and enter world. Go to creative mode and place down anything from the modpack, keep placing different items until game crashes. 

## Modified settings
To get the modified settings run `#modified` in game
None.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Fabritone is unsupported, use Baritone.

**Comment by bloxanne123** [comment]
If you look in the releases for 1.6.3, it specifically says Fabric IS supported, sodium IS supported.

**Comment by scorbett123** [comment]
You just said fabritone in the description of how to reproduce. That means that we assume that you are using fabritone not baritone for fabric, there is a difference. Your issue is in appliedenergistics2, I believe it is an issue on their end though, so we can't fix it.

**Comment by bloxanne123** [comment]
I assumed they meant the same thing, but to clarify, I am using baritone-standalone-fabric-1.6.3.
And I do not think it's an issue on their end. The log states this: 

> at baritone.hn.h(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.hn.c(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.hn.b(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.hn.b(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.em.a(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.em.a(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at baritone.hf.a(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_242]
	at baritone.hf.a(Unknown Source) ~[baritone-standalone-fabric-1.6.3.jar:?]

This issue stops happening with baritone-standalone-fabric-1.6.3 removed, which leads me to believe it is not the fault of AE2

**Comment by l1ving** [comment]
Use 1.6.5

**Comment by l1ving** [comment]
> This issue stops happening with baritone-standalone-fabric-1.6.3 removed, which leads me to believe it is not the fault of AE2.

Does it also stop when removing AE2?

**Comment by scorbett123** [comment]
> Use 1.6.5

1.6.5 doesn't exist. I made that mistake earlier.

**Comment by bloxanne123** [comment]
I will test without AE2 later today.

**Comment by bloxanne123** [comment]
Seeing as AE2 is an important part of the modpack though, I don't want to remove it. Also, i think this may happen with other mods,

**Comment by l1ving** [comment]
baritone doesn't really work with weird block types

**Comment by scorbett123** [comment]
Then remove baritone. It is your choice which one you have. I still think that it is AE2's fault though, it is caused when baritone asks it to do something.

**Comment by bloxanne123** [comment]
Thing is, I didn't even activate baritone. Someone asked me to TP to them, so i did and then boom the game crashed. Baritone was completely inactive, it wasn't doing anything. 

Works decently well to mine modded ores tho.

**Comment by scorbett123** [comment]
Baritone is constantly caching and scanning different blocks, which means that issues can be caused when it is not in use, it just needs to be installed.

**Comment by bloxanne123** [comment]
What's even weirder is that this does not happen with older versions of the modpack.

**Comment by scorbett123** [comment]
Probably because they changed something :astonished:

**Comment by wagyourtail** [comment]
run with unoptimized-fabric for a crash report / error that's actually readable

**Comment by bloxanne123** [comment]
Graal is used for better performance, and ok i will try unoptimized. 
Should I make a new issue for that?
ya i think i should.

**Comment by l1ving** [comment]
> Graal is used for better performance, and ok i will try unoptimized.

It doesn't make that much of a difference in practical applications such as Minecraft, and comes at the cost of weird issues.

Use Java 8 https://adoptopenjdk.net/
