### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Twi5TeD** [cabaletta/baritone#2502]
would you be able to add something like #mine but it clears an area in the selected region by mining layer by layer till it 

would be used to afk mine on servers that have mines alot more people would use this feature :)

**Comment by scorbett123** [comment]
You can do this.

#sel pos1
#sel pos2  
#sel ca

**Comment by Twi5TeD** [comment]
This doesn't do layer by layer when doing that it usually mines a little at top then goes to bottom the way I'm on about is to mine every block at the top and work down doing 1 layer at a time

**Comment by scorbett123** [comment]
#buildInLayers

This setting should fix that. And enable #layerorder

**Comment by Twi5TeD** [comment]
I'll test this soon and get back to you

**Comment by l1ving** [comment]
Invalid, didn't fill out template
