### ISSUE TITLE
concrete breaks #build in fabric 1.16.5 build

### ISSUE THREAD

**Issue by artemOP** [cabaletta/baritone#2503]
## Some information
Operating system:win10
Java version:1.8.0_281-b09
Minecraft version:1.16.5
Baritone version:Fabric 1.6.3
Forge mods (if used): WorldeditFabirc

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/6022936/latest.log

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
-Create test schematic using world edit into .schem format, convert to .schematic format
-use baritone to build test.schematic

-works perfectly on stone, insta claims to complete without doing anything with concrete

## Modified settings
allowInventory: True

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
uh, concrete doesn't exist in .schematic, just use the .schem, baritone supports .schem.

**Comment by artemOP** [comment]
.schem does seem to work, just in a really strange order, will continue testing, probably with #breakblocks disabled
