### ISSUE TITLE
Mining blocks on prison server is slow with insta mine pick, and sel replace block air wont work

### ISSUE THREAD

**Issue by lithium-codes** [cabaletta/baritone#2505]
## Some information
Operating system: Windows 10 
Java version: version 8 update 281
Minecraft version: 1.15.2
Baritone version: the one that comes with impact
Forge mods (if used): impact

## How to reproduce
1. on impact do .baritone sel replace emerald_block diamond_block air
2. on regular do #sel replace emerald_block diamond_block air

## Modified settings
To get the modified settings run `#modified` in game
![image](https://user-images.githubusercontent.com/46404863/108749539-c7ed6c00-74f4-11eb-95bd-116125b16eb3.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any ~~OwO~~'s or ~~UwU~~'s in this issue.

**Comment by l1ving** [comment]
Baritone is already very fast on vanilla.
