### ISSUE TITLE
Sodium and Baritone

### ISSUE THREAD

**Issue by FireBlaster101** [cabaletta/baritone#2506]
## Some information
Operating system: Windows 10 Home
Java version: Latest
Minecraft version: 1.16.5
Baritone version: Latest
Forge mods (if used):

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

So I use Fabric with 2 mods which are Sodium and Baritone. There is one problem though, Sodium. Sodium is an FPS Boosting mod which I use regularly but Sodium and Baritone have a BIG issue which is when using Sodium the Baritone bot is denying to function properly by not moving. Any fixes?

**Comment by l1ving** [comment]
Download the latest version of Baritone.
