### ISSUE TITLE
Baritone crashes with mods in the AOF3 modpack.

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2507]
## Some information
Operating system: Win 10 Pro
Java version: 8
Minecraft version: 1.16.5
Baritone version: 1.6.3 fabric 
Forge mods (if used): None

## Exception, error or logs
https://paste.ee/p/jNwvL

## How to reproduce
Continuation of [this issue with the ](https://github.com/cabaletta/baritone/issues/2501) AOF3 modpack. To reproduce, get the AOF3 modpack 2.6.9 for Fabric 1.16.5. Download baritone 1.6.3 for fabric, either standalone or unoptimized works. Make world, get any new modded item that is not even close to vanilla, for example any blocks from Applied Energistics 2, such as the Fluix ME cables, or pipes from Modern Industrialization. Game should save, and then crash with error code 4294967295. Check log for something like this: 
![image](https://user-images.githubusercontent.com/63023773/108797429-2b10ea00-7559-11eb-8ce0-c41f43a4fa0c.png)
(baritone was paused here)
For me, Baritone was paused, but the crash even with baritone off is almost exactly the same, except instead of a pathing error, it's an error with whatever this means (probably baritone caching the block): 
![image](https://user-images.githubusercontent.com/63023773/108797566-72977600-7559-11eb-9e55-849b9687d3cb.png)

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I'm closing this as leij does not want to maintain fabric specific issues, much less fabric modpack issues, in the same spirit as forge modpacks are handled.

**Comment by bloxanne123** [comment]
This is a fabric modpack issue as far as I can see, but I understand. That said, is there something in the settings that I can change so that baritone doesnt immediately crash my game?
