### ISSUE TITLE
How do I follow a player?

### ISSUE THREAD

**Issue by SkimmerZ** [cabaletta/baritone#2509]
## What do you need help with?
When I try to run the command "#follow player <username>" it throws an unhandled exception. I would like to know how you follow a player

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a known issue, make sure that you keep on the latest version and eventually it will be fixed.
