### ISSUE TITLE
Fix sprinting button

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#251]
Right now, PathExecutor directly calls setSprinting, this can result in things the player couldn't normally do, like stop sprinting without letting go of W, or starting a sprint in midair in strange scenarios. It should instead pass through the SPRINT keybind to InputOverrideHandler, which should hold down SPRINT on a rising edge, and do setSprinting(false) on a falling edge.

**Comment by leijurv** [comment]
This is tricky because EntityPlayerSP checks the global gameSettings.keyBindSprint =(
bad for bots

**Comment by ZeroMemes** [comment]
Fixed in 20b03d00049dc3f4a75c8d8e9aa83eca1bd7ac55
