### ISSUE TITLE
Support for modpacks like MC Eternal

### ISSUE THREAD

**Issue by Niceghost21** [cabaletta/baritone#2510]
[latest.log](https://github.com/cabaletta/baritone/files/6029635/latest.log)
## Describe your suggestion
I would pay for someone to implement support for baritone to work on the MC Eternal mod pack which runs on 1.12.2.  As of now when you try to start the game with the v1.2 forge-api mod loaded, you just get a game crash error. If it is at all possible to make it work for this mod pack, I would be more than happy to donate for it! 

## Context
This would allow for the thousands of people that play MC Eternal to have access to this incredible mod.

**Comment by scorbett123** [comment]
If possible can you send a log file, it might be that you can just remove one mod to get it to work.

**Comment by Niceghost21** [comment]
Yes here is the log file!
[latest.log](https://github.com/cabaletta/baritone/files/6029648/latest.log)

**Comment by ZacSharp** [comment]
Seems like bewitchment doesn't like the provided mixin version.
Does it work without Baritone or without bewitchment?

**Comment by Niceghost21** [comment]
It works without baritone, but once I add baritone I get that crash report. Haven't tried it without bewitchment

**Comment by ZacSharp** [comment]
Another thing you might want to try is renaming "bewitchment-1.12.2-0.0.22.26.jar" to "abewitchment-1.12.2-0.0.22.26.jar" so it is loaded before Baritone (which is apparently providing the outdated mixin, but might work with bewitchments mixin)

**Comment by Niceghost21** [comment]
> Another thing you might want to try is renaming "bewitchment-1.12.2-0.0.22.26.jar" to "abewitchment-1.12.2-0.0.22.26.jar" so it is loaded before Baritone (which is apparently providing the outdated mixin, but might work with bewitchments mixin)

here is the new log after renaming the bewitchment mod, not sure if it changed or not.  here it is
[latest.log](https://github.com/cabaletta/baritone/files/6029748/latest.log)

I also renamed the baritone mod with 3 zs so its at the bottom and received this log if that could possibly change something, I don't know if it would, I'm new to this
[latest.log](https://github.com/cabaletta/baritone/files/6029764/latest.log)

**Comment by Niceghost21** [comment]
> Seems like bewitchment doesn't like the provided mixin version.
> Does it work without Baritone or without bewitchment?

removing baritone, it works fine.  When i remove bewitchment and keep baritone, i get this log file
[latest.log](https://github.com/cabaletta/baritone/files/6029792/latest.log)

**Comment by ZacSharp** [comment]
All three scenarios produce different errors and I have no clue on how to fix them.
However this issue seems to be the same as #2215 and might be fixed soon by Baritone updating to a newer mixin version, as mentioned in #2398.

**Comment by Niceghost21** [comment]
Thanks @ZacSharp !  I havent the clue what mixins are.  hopefully, if they are getting updated though, they get updated for the 1.12.2 version too!
