### ISSUE TITLE
How to use chests command?

### ISSUE THREAD

**Issue by rayjay7225** [cabaletta/baritone#2511]
## What do you need help with?
I want to know how to use the #chests command because it says that there are no remembered inventories. I want to know how to add chests to the list of remembered inventories. I dont want to mess with the code because im not a programmer.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
make sure to enable containerMemory. It should remember them automatically.

**Comment by rayjay7225** [comment]
> make sure to enable containerMemory. It should remember them automatically.

I have it set to true but it still says that there is no remembered inventories.

**Comment by l1ving** [comment]
Then there are none

**Comment by dvdmchl** [comment]
![obrazek](https://github.com/cabaletta/baritone/assets/20048281/bed5e238-18b7-4821-acbf-2e59b5164782)
It truly still has some problems with chests.
