### ISSUE TITLE
How to use #chests command? The continuationtion

### ISSUE THREAD

**Issue by rayjay7225** [cabaletta/baritone#2512]
## What do you need help with?
In the  #2511 question of mine i asked the same thing. Now theres a problem, it doesn't "remember" the inventories but i got containermemory set to true.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Have you opened the chests while `containermemory` was true?

**Comment by rayjay7225** [comment]
> Have you opened the chests while `containermemory` was true?

Yes

**Comment by ZacSharp** [comment]
Then that's a bug and you should use the bug template for the issue.

**Comment by rayjay7225** [comment]
> Then that's a bug and you should use the bug template for the issue.

Done #2513

**Comment by rayjay7225** [comment]
Issue closed because zacsharp suggested that this was a bug.
