### ISSUE TITLE
Baritone doesnt "remember" inventories.

### ISSUE THREAD

**Issue by rayjay7225** [cabaletta/baritone#2513]
##some background
I was looking through commands and i saw the chests command so i used it. After i used it, it said that there are no remembered inventories but i had turned on containermemory and have opened chests with stuff in them with containermemory on. Thats the problem.
## Some information
Operating system: windows 10
Java version: version 8 update 281
Minecraft version: 1.16.4
Baritone version: v1.6.2
Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game
acceptableThrowawayitems-(wrote the shorter version)diorite,dirt,cobblestone,netherrack,stone,granite,andesite
Allowinventory-true
Allowjumpat256-true
Allowparkour-True
Allowparkourplace-true
Allowvines-true
Anticheatcompatibility-false
Blockbreakadditionalpenalty-8.0
Blockplacementpenalty-4.0
Blockreachdistance-4.0
Containermemory-true
Costheuristic-5.0
Explorechunksetminimumsize-2
Followradius-5
Layerorder-true
Maxfallheightbucket-22
Mobavoidancecoefficient-0.4
Planningticklookahead-300
Prefix-#
Pruneregionsfromram-False
Shortbaritoneprefix-true
Sprintinwater-false
Walkonwateronepenalty-1.0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
I cannot reproduce this, nor have you provided steps to reproduce the issue.
