### ISSUE TITLE
Efficiency through environmental crafting.

### ISSUE THREAD

**Issue by AceeHardware** [cabaletta/baritone#2514]
Add the "get" command. Which will simply make the AI find the fastest way to get a certain item or resource. For example lets say that I tell the AI to get a diamond pick axe. It'll go through a list of things it needs to have to efficiently obtain the diamond pick axe and after going through the crafting and resource obtaining it'll craft a diamond pick axe. This could also be used to optimize the mine command. Let's say I spawn in a world and tell the AI to mine iron ore. Nothing will happen it'll slowly break through dirt stone and eventually iron ore with nothing but dirt to show for it. If it could process that mining some trees, placing down a crafting table and crafting a pick would increase efficiency by 10 fold I think this would greatly benefit the AI. I'm sure this part would be a lot harder, but you could also tell it to obtain certain items from mobs or chests and it would explore the world trying to find these chests or mobs on the chance of obtaining the items. This could also help if the AI is starving it could obtain food and possibly for example if it got raw food cook it. This would also be handy for if it was building schematics it could see what items it needs go obtain them and then build the object all from scratch(which i think would be crazy to see). Settings include just how many items if you want to obtain multiple items and maybe a timeout to give only a certain amount of time to find the items. Anyways I'm sure these ideas are a lot harder to implement then my simple mind can comprehend but it would be nice to see these implemented.

**Comment by scorbett123** [comment]
This has already been suggested, and would probably be split into multiple issues due to the complexity off it all.
