### ISSUE TITLE
Barriton

### ISSUE THREAD

**Issue by KingShisnat2** [cabaletta/baritone#2516]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by EmeraldSnorlax** [comment]
baraton

**Comment by l1ving** [comment]
baritoe

**Comment by mwahaha9** [comment]
barato

**Comment by sourTaste000** [comment]
bawitonye
