### ISSUE TITLE
How to disable caching when in world with modded blocks that cause baritone to crash the game?

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2519]
## What do you need help with?
Basically the title. If disabling caching fundamentally breaks anything, I'll leave it on. Or, y'know if theres a setting to tell baritone that this is a modded world so that it doesnt decide to crash if it encounters something it doesnt understand, that would be nice.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
`#chunkCaching`

**Comment by l1ving** [comment]
https://baritone.leijurv.com/baritone/api/Settings.html
