### ISSUE TITLE
Where's branch 1.12.2?

### ISSUE THREAD

**Issue by mvrozanti** [cabaletta/baritone#2520]
I want to add a custom `Command` to this version of baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by mvrozanti** [comment]
Nevermind, source is in the release.

**Comment by l1ving** [comment]
The master branch is 1.12.2

**Comment by mvrozanti** [comment]
thanks l1ving
