### ISSUE TITLE
Support for litematica

### ISSUE THREAD

**Issue by Ethanadams642** [cabaletta/baritone#2522]
## Describe your suggestion
The most popular post 1.12.2 schematic mod is litematica for fabric, I like to prototype in a creative world, save a section via litematica, and then construct it, being able to use baritone to help build things, especially large structures would be very helpful.

## Settings
Some type of positioning mode/hologram (already in litematica) or just a box of the final size would be pretty nice.

Probably either ground up support or some type of conversion for the file.

## Context
Building large structures could be a breeze, especially with the ease of the litematica hud, and needed resources list. Building farms and redstone contraptions with baritone with litematica would alleviate the worry's if misplacing blocks.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] Checklist go brrrrr
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Duplicate
