### ISSUE TITLE
Mining multiple countable ores

### ISSUE THREAD

**Issue by Markg546** [cabaletta/baritone#2524]
## What do you need help with?
Theres the "mine 64 diamond_ore" command for mining 64 diamonds
Any command to make it mine (for example) 128 coal 64 iron 32 diamonds all in one go? if the player has (same example) 64 iron in the inventory baritone will no longer look for iron and continue mining the other specified ores

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This isn't possible, and has already been suggested as a feature.

**Comment by Markg546** [comment]
Hey sorry to bother again 
curious why wasnt this ever merged then? https://github.com/cabaletta/baritone/pull/2088

**Comment by scorbett123** [comment]
> Hey sorry to bother again
> curious why wasnt this ever merged then? #2088

Its leijurv, he probably just missed it.
