### ISSUE TITLE
Schematics problem pls HELP!!

### ISSUE THREAD

**Issue by ZiberCAT** [cabaletta/baritone#2525]
hey, i've installed Baritone on my MC client and evrything works eksept #buld schematic.schematics comand. im pretty sure that i have a 1.12 schematic file. My schematics folder wasent generated whilst loading the game, so i just made one and named it schematics. trying to load the 1.12 schematics file with #buld xxxx.schematics. simpely dosent work. i've installed baritone with a 1.16 client. couse thats the relms verson we use. so is there a way to make it work or is there som way to get a 1.12 schematic file to work on a 1.16 client or does the client also need to be 1.12? anyways i can just be that i got it wrong an the .schematic file is not 1.12. in witch case i wold love if someone send me a link to download a 1.12 schematics file or a place where i can easyly find it.
sorry for bad english if i spelled something wrong.
best regards, ZiberCAT

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
