### ISSUE TITLE
Build command don't work

### ISSUE THREAD

**Issue by AngelFireLA** [cabaletta/baritone#2529]
I installed baritone fabric api.
I got litematica and fabric api.
Baritone work.
Litematica work.
But when I try to use the build command it don't work, even with the full name.
It says could not load schematic. But the schematic is working.
Can someone help me please
# Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
I believe that baritone and litematica aren't compatible.

**Comment by AngelFireLA** [comment]
someone added a full litematica support
https://github.com/cabaletta/baritone/pull/2338

**Comment by scorbett123** [comment]
That pull hasn't been merged yet.

**Comment by AngelFireLA** [comment]
oh yeah, they should really do it
