### ISSUE TITLE
not moving

### ISSUE THREAD

**Issue by Google433** [cabaletta/baritone#2530]
For the fabric version, when I give it a command, it doesn't even move forward.

**Comment by wagyourtail** [comment]
please fill out the teplate properly, what other mods do you have installed.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
