### ISSUE TITLE
Use portals with goto

### ISSUE THREAD

**Issue by BobIsMyManager** [cabaletta/baritone#2531]
## Describe your suggestion
Makes it so Baritone can use portals to go to places in different dimensions like the end and nether by adding a dimension option in goto. Also allows you to use the nether for fast travel so you can go to places in the overworked faster and be able to use end gateways to go to the middle of the end and mabye also to leave the main end island 

## Settings
Option to allow Baritone to build a portal and choose methods to getting inside end gateways (trapdoor, waterbucket, ender pearl, etc)

## Context
Allows you to go straight to cords in other dimensions rather than doing goto nether_portal and then goto x y z. Also allows for more efficient travel through the end and the overworld

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Overcomplicated, just enter the nether with #goto portal
