### ISSUE TITLE
Sel command more examples

### ISSUE THREAD

**Issue by myxxmikeyxx** [cabaletta/baritone#2533]
## What do you need help with?
https://github.com/cabaletta/baritone/blob/master/USAGE.md
Can we get more examples of the sel shift and help command examples?
I have tired to use the shift and the expand command and I can not find any examples online but every time it do it says an argument is wrong and I don't know what I am doing wrong.
I have tried the help command but the confusing bit the target and I think that what I have wrong.

**Comment by ZacSharp** [comment]
`help shift a up 1` - shift all selections up by one block

**Comment by myxxmikeyxx** [comment]
Thank you so much!
