### ISSUE TITLE
Walk on soul sand if you have soul speed

### ISSUE THREAD

**Issue by BobIsMyManager** [cabaletta/baritone#2539]
## Describe your suggestion
Currently, if you were to path through an area with soul sand, it would try to avoid it even when you have soul speed (which would actually make you go faster than walking on normal blocks and when that apth is shorter).

## Settings
Option to not walk on soul sand or take off soul speed boots if they are on low durability.

## Context
It would stop baritone from avoiding a path that is shorter or even faster than the one it would go to instead (especially in the soul sand valley biome).

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by BobIsMyManager** [comment]
What one is this a duplicate of?

**Comment by ehylo** [comment]
#1877
