### ISSUE TITLE
#goal and #thisway commands won't work properly

### ISSUE THREAD

**Issue by aquilon74** [cabaletta/baritone#2540]
## Some information
Operating system: Windows 10
Java version: 1.8
Minecraft version: 1.16.5
Baritone version: baritone-standalone-fabric-1.6.3.jar
Forge mods (if used): None
Fabric mods: 
 - Fabric API 0.31.0
 - Wurst Client v7.12.1-MC1.16.5

The bug: 
 the command #mine diamond_ore works just fine, but when i try to use #goal 1000 1000 or #thisway 1000, it set a waypoint but don't move at all.

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
 - Install fabric
 - install wurst client, fabric api and baritone
 - create a singleplayer world
 - use the command #goal 1000 1000 or #thisway 1000
 - the player don't move.

## Modified settings
no modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Run the command #path to start pathing.

**Comment by aquilon74** [comment]
ok , thanks, this works !
