### ISSUE TITLE
#goto command and other similar commands not working

### ISSUE THREAD

**Issue by chris819t** [cabaletta/baritone#2542]
Some information
Operating system: Windows 10
Java version: Java 8 (I think, idk and idk how to find out)
Minecraft version: 1.16.5
Baritone version: baritone-standalone-fabric-1.6.3
Forge mods (if used): No forge mods but I use these Fabric Mods: cloth-config-4.11.14-fabric, tweakeroo-fabric-1.16.4-0.10.0-dev.20210303.123654, fabric-carpet-1.16.5-1.4.28+v210224, immersive-portals-0.80-mc1.16.5-fabric, fabricmod_VoxelMap-1.10.15_for_1.16.5, worldedit-mod-7.2.3, itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029, appleskin-mc1.16-fabric-1.0.11, shulkerboxtooltip-2.3.5+1.16.5,  malilib-fabric-1.16.4-0.10.0-dev.21+arne.2, litematica-fabric-1.16.4-0.0.0-dev.20210120.213004, minihud-fabric-1.16.4-0.19.0-dev.20201103.184029, fabric-api-0.31.0+1.16, TwitchChatIntegration_1.16.4-5.1.1-all, modmenu-1.16.8, carpet-extra-1.16.5-1.4.27, PresenceFootsteps-r29+1.16.4, RoughlyEnoughItems-5.10.184, OptiFine_1.16.5_HD_U_G7, optifabric-1.9.6, carpet-addons-1.16.4-1.0.8+v210130, Hwyla-fabric-1.16.2-1.9.23-79

## Exception, error or logs
I don't know how I'm suppose to attach a "log" when i don't see anything that lets me attach a file (Im visually impaired so i could have missed it) so here is a pastebin link to the log instead https://pastebin.com/pWjsKXHs

My issue I'm having is when I do any command like #goto then it pathfinds but it doesnt move at all. other commands such as #mine also don't work but everything else does work just not anything that makes the player go to a specific spot

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
immersive-portals

**Comment by chris819t** [comment]
oh ok, thank you.
