### ISSUE TITLE
Cant walk on Soul Sand ?

### ISSUE THREAD

**Issue by SandKing1** [cabaletta/baritone#2543]
baritone cant walk on soul sand. I am trying to @farm nether warts but baritone cant walk on soul sand so it only mines blocks nearby than stops. I know this has been created before and someone said I tested it it works fine than closed the thread.

BUT it doesnt work !!!

**Comment by SandKing1** [comment]
Which baritone version should i be using for it work ?

**Comment by scorbett123** [comment]
This is a duplicate.

**Comment by l1ving** [comment]
Maybe someday someone will have the sense to put "soul sand" in the search bar
