### ISSUE TITLE
Baritone not clearing area+trying to build with allow build off

### ISSUE THREAD

**Issue by Hjonking-goose** [cabaletta/baritone#2545]
## Some information
Operating system: windows 64 bit
[latest.log](https://github.com/cabaletta/baritone/files/6102539/latest.log)
Java version: V8 update 271
Minecraft version: 1.16.4
Baritone version: newest/impact nightly? idk how to check
Forge mods (if used): n/a

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6102539/latest.log)

## How to reproduce
Im unsure if it is reproduceable intentionally but what i have been trying to selecting an area 2 chunks x 7 chunks and using #sel clear. i do have allow break on to allow baritone to automatically start the next layer and allow place is off to stop it building. randomly thoughout the dig baritone will stop digging and go to a random spot refusing to continue digging. if i destroy the blocks baritone is standing on it trys to start building even though i have allow place disabled.
[javaw_ee7CkkHRnn](https://user-images.githubusercontent.com/80272795/110347028-16882380-8028-11eb-85b4-040d1aacac69.jpg)

## Modified settings
To get the modified settings run `#modified` in game
[javaw_ee7CkkHRnn](https://user-images.githubusercontent.com/80272795/110347028-16882380-8028-11eb-85b4-040d1aacac69.jpg)
![javaw_3NcnZE5EpH](https://user-images.githubusercontent.com/80272795/110347068-243da900-8028-11eb-934d-c94811eeb8cd.jpg)
![javaw_7pCoObqtZo](https://user-images.githubusercontent.com/80272795/110347076-26076c80-8028-11eb-915a-ac534d3da1e7.jpg)

## Final checklist
- [Y] I know how to properly use check boxes 
- [Y] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [~] I have included logs, exceptions and / or steps to reproduce the issue.
- [Y] I have not used any OwO's or UwU's in this issue.

**Comment by Hjonking-goose** [comment]
#modified page 3 found below
![javaw_ee7CkkHRnn](https://user-images.githubusercontent.com/80272795/110347391-7d0d4180-8028-11eb-8aed-0cd9d4f3cd3a.jpg)

**Comment by l1ving** [comment]
Can't reproduce this issue on default settings
