### ISSUE TITLE
Can I mine blocks with particular NBT values or block data?

### ISSUE THREAD

**Issue by user670** [cabaletta/baritone#2546]
## What do you need help with?
For example, I'd like to mine all kelp with `age` of `25` (don't ask me why). Baritone understands one way of specifying extra data of a block (eg, `log:1`, but that's probably pre-1.12 legacy syntax), and 1. when I did that with kelp, it doesn't seem to understand (`mine kelp:25` ignored all kelp blocks, and instead collected a kelp item floating around), 2. when I tried the 1.13+ syntax (I hope I got it right: I typed `mine kelp{age:25}`), it threw an error saying `Error at argument #1: Expected ForBlockOptionalMeta`. Is there currently a way I can specify NBT or block data of blocks to mine?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

edit: apparently just regularly doing `mine kelp` does nothing; Baritone seems to avoid going underwater?

Also I forgot to mention I'm using Impact for 1.14.4. As for why the old version, it's because I'm playing on a 1.14 server

**Comment by l1ving** [comment]
No
