### ISSUE TITLE
Can Baritone input to chat?

### ISSUE THREAD

**Issue by mvrozanti** [cabaletta/baritone#2552]
## What do you need help with?
Is there a programatic way to input data to chat?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
What do you mean? You have to be more specific than that

**Comment by mvrozanti** [comment]
~In the context of a `BaritoneProcessHelper` instance implementing `IBaritoneProcess`, can baritone `/gamemode`, for instance?~

Oh, is that what `CommandManager` is for?

**Comment by l1ving** [comment]
> can baritone, for example, `/gamemode`?

You could write code accessing *Minecraft's* code to do so, but with just Baritone functions, no.

> <Oh, is that what `CommandManager` is for?

No.

**Comment by mvrozanti** [comment]
What about `MixinClientPlayerEntity`?

**Comment by l1ving** [comment]
I don't see why that's related

**Comment by mvrozanti** [comment]
I was curious about that `sendChatMessage` and had to check. Nevermind thanks
