### ISSUE TITLE
blocksToAvoid and Avoidance not avoiding blocks

### ISSUE THREAD

**Issue by Banjoei** [cabaletta/baritone#2553]
I am using baritone in a modded world and there is a block that works like a magma block and a new fire type. I added these to the "blocksToAvoid" list and toggled "Avoidance." However, Baritone is completely ignoring this. Is there any way I can fix this?
![2021-03-10_21 36 24](https://user-images.githubusercontent.com/63517694/110727188-c4423080-81e8-11eb-8c52-3f43d9e1489b.png)
![2021-03-10_21 36 45](https://user-images.githubusercontent.com/63517694/110727190-c4dac700-81e8-11eb-8c32-2dfc5705a35d.png)
![2021-03-10_21 32 16](https://user-images.githubusercontent.com/63517694/110727192-c5735d80-81e8-11eb-9752-682269fea246.png)

**Comment by l1ving** [comment]
You didn't fill out the issue template, so I'll have to close this as invalid anyways but there probably isn't a way given that it's modded.
