### ISSUE TITLE
anti AFK while walking

### ISSUE THREAD

**Issue by NotAnEnemy123** [cabaletta/baritone#2554]
## Settings
you can turn it on and of like "break blocks" allowed.

## Context
people can afk walk houndreds of thousands of block without being kicked.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
does increasing randomLooking help?

**Comment by NotAnEnemy123** [comment]
> does increasing randomLooking help?

probably
