### ISSUE TITLE
Litematica

### ISSUE THREAD

**Issue by Lucas4b2x** [cabaletta/baritone#2555]
I saw i can use #shematica to build the currently build opened in shematica but is it working with litematica? (forge 1.16.4)

**Comment by scorbett123** [comment]
Not yet however someone is working on it.

**Comment by ZacSharp** [comment]
No, just on loading litematics, not on building the open schematic from litematica (litematica doesn't even have "the" open schematic)

**Comment by Lucas4b2x** [comment]
is there a command to preview where the shematic will be built before #build house.schematic for example ?

**Comment by ZacSharp** [comment]
No. But once #2544 is merged you should be able to position the schematic using litematica and then just give Baritone the coordinates of the placement using `#build schematic.litematic x y z`

**Comment by Lucas4b2x** [comment]
I did that but baritone clear a huge area at my left but there is a huge plane surface in front of me. idk why it's not building in front of me.

**Comment by Lucas4b2x** [comment]
thx :)

**Comment by ZacSharp** [comment]
You were standing at (or gave it) he right corner? (minx, miny, minz)

**Comment by Lucas4b2x** [comment]
i was on the middle :/

**Comment by scorbett123** [comment]
> No, just on loading litematics, not on building the open schematic from litematica (litematica doesn't even have "the" open schematic)

oh, sorry misread the issue.
