### ISSUE TITLE
Baritone stops moving

### ISSUE THREAD

**Issue by Lucas4b2x** [cabaletta/baritone#2557]
Operating system: win10
Minecraft version: 1.16.4
Baritone version: the last for 1.16.4

(i did #buildinlayers true)
when i start building the first layer (layer n°0) it's working. But when it's finished (but dont says layer 0 finished), baritone stops moving and when i move, baritone come back to the same position where it was stopped.
how can i fix it ?

**Comment by Lucas4b2x** [comment]
note : it's working perfectly in my other world (superflat)

**Comment by scorbett123** [comment]
Is this under ground?

**Comment by Lucas4b2x** [comment]
idk, but i prepared the area with a plane dirt ground

**Comment by ZacSharp** [comment]
You should know were you let Baritone build.
The dirt ground is below layer 0, right?
What are you building (clear area, schematic, filling with some block)?
Is there air that was inside a cave in the area where Baritone fails building?
Does `buildIgnoreBlocks cave_air` circumvent this problem?

**Comment by Lucas4b2x** [comment]
"The dirt ground is below layer 0, right?" yes
I'm building schematic
i will test this command and i come back

**Comment by Lucas4b2x** [comment]
Do i need to pause the build and then write the command ? or before build command or something else ?

**Comment by ZacSharp** [comment]
To be sure it works, cancel the build (if it is active or paused), set buildIgnoreBlocks to cave_air and then start building again

**Comment by Lucas4b2x** [comment]
It's working perfectly ! You re a boss dude ! Thx u very much and thx for fast answer !!
