### ISSUE TITLE
Missing blocks in impact and baritone

### ISSUE THREAD

**Issue by Pabsb** [cabaletta/baritone#2559]
## Some information
Operating system: Windows 10
Java version: Java 8 281 64 bit
Minecraft version: 1.16.5
Baritone version: 1.16.5
Forge mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
N/A

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Try to use `.b mine tall_grass` in baritone
Search for item frames or tall grass in xray options
Try to add item_frame to search 

## Modified settings
To get the modified settings run `#modified` in game
AllowDiagonalAscend True
AllowDiagonalDescend True
AllowWaterBucketFall False
AnticheatCompatibility False
Avoidance True

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
1. Don't post impact issues here, impact has it's own bug tracker
2. The Baritone version 1.16.5 does not exist, use `#version` to get the correct one
2. item frames are entities, not blocks.
3. There is not 'missing block', never. Baritone uses the blocks that are registered in the running minecraft instance, so if a block is registered properly (any vanilla block, probably any modded block) Baritone knows about it.
4. However I can confirm that it for some reason does not accept tall_grass as a block, even though it suggests it for tab completion and the block exists in all post-flattening (1.13+) versions (before it was tallgrass and meant something slightly different)
