### ISSUE TITLE
Plugin finder times out even with plugins exposed through tabbing

### ISSUE THREAD

**Issue by Pabsb** [cabaletta/baritone#2560]
## Some information
Operating system: Windows 10
Java version: Java 8 281 64 bit
Minecraft version: 1.16.5
Baritone version: 1.16.5
Forge mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
N/A

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Join a server that has plugins exposed through tabbing
Run impact command `pl` or `plugin`

## Modified settings
To get the modified settings run `#modified` in game
N/A

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Report impact issues on the impact github, not here.
