### ISSUE TITLE
Baritone jumps into the lava(only when it comes implemented in a client)

### ISSUE THREAD

**Issue by abrabahum** [cabaletta/baritone#2561]
## Some information
Operating system: Windows 10
Java version: 8.0.2710.9 (64-bit)
Minecraft version: 1.16.5
Baritone version: latest coming with a client (tried meteor and inertia)
Forge mods (if used): No

## Exception, error or logs
There is no error as far as I know.

## How to reproduce
Basically I tried meteor and inertia clients that come with baritone and the problem is that baritone ignores lava, is like the setting "AssumeWalkOnLava" is always ON even when you try to set it off it doesn't matter still tries to walk on lava.

This only happened to me with the baritone that is implemented into this clients(TRIED Meteor and inertia), I tried to download just the baritone standalone module(For Fabric) without the client and works perfectly as expected, it respected this setting properly.

I contacted the owner of Meteor client and I have been told that they are not the developer of baritone, that what they do is just implement it without modifying or changing anything in baritone and I also researched in google about this issue and found another issue in GitHub that is exactly this problem just the guy who opened it didn't put a descriptive title.

Here is it [https://github.com/cabaletta/baritone/issues/2433](https://github.com/cabaletta/baritone/issues/2433)

Apparently is not baritone problem and is not the clients problem but the bug is there somewhere, If you could have a look for it I would really appreciate it.

## Modified settings
I tried to reset all the settings with the command "reset all" and the settings reset but the problem persist so no modified settings.
Even I tried to reset settings, restart minecraft check with "modified" command (shows nothing) and same problem.
## Final checklist
- [X] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
If you can't reproduce this in the standalone version it's not our problem

**Comment by abrabahum** [comment]
Well I think the probability of 2 clients implementing baritone wrong in the same way to reproduce the exact same bug is low, maybe there is a conflict between the clients and baritone, thank you for your reply.

**Comment by l1ving** [comment]
> If you can't reproduce this in the standalone version it's not our problem

**Comment by l1ving** [comment]
I can't reproduce this issue on the api or standalone jars period.
