### ISSUE TITLE
Minecraft stops runnning

### ISSUE THREAD

**Issue by Lucas4b2x** [cabaletta/baritone#2563]
[crash-2021-03-12_15.35.13-client.txt](https://github.com/cabaletta/baritone/files/6130668/crash-2021-03-12_15.35.13-client.txt)
When I'm using baritone, minecraft stops running
How can i fix that?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
