### ISSUE TITLE
When I type #mine coal_ore or #mine minecraft:coal_ore it say  Error at argument  : expected ForBlockTopMeta, and other command like #click #tunnel and #goto are working nicely. only issue with #mine commans

### ISSUE THREAD

**Issue by kalpa824** [cabaletta/baritone#2565]
## Some information
Operating system: Windows 10
Java version:
Minecraft version: 1.15.2
Baritone version:
Forge mods (if used):  Release 1.15.2 Forge 31.2.49

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Fill in the template fully.
