### ISSUE TITLE
When I go to mine glowstone i fall to my death in the nether

### ISSUE THREAD

**Issue by SkorpionX** [cabaletta/baritone#2566]
I don't know the cause of this but it happens

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
