### ISSUE TITLE
#chests (or containerMemory) is broken

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [cabaletta/baritone#2568]
## Some information
Operating system: Fedora 32
Java version: 11.0.10
Minecraft version: 1.16.5 (Fabric 0.11.1)
Baritone version: 1.6.3
~~Forge~~ Fabric mods (if used): [AppleSkin](https://github.com/squeek502/AppleSkin), [NBTTooltip](https://github.com/zabi94/NBTTooltip), [Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) and [Worldmap](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/6135909/latest.log) (Despite the folder name, I do *not* have Wurst installed.)

## How to reproduce
1. Run `#set containerMemory true`
2. Open a chest, put things in it, close it
3. Run `#chests`

## Modified settings
- `allowParkour`
- `assumeWalkOnWater`
- `containerMemory`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and ~~forge~~ fabric mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

-----

I'm aware this is a duplicate of #2511, #2512, and #2513; but the reporter on those invalidated them by failing to follow procedure; I believe this instance is properly-formatted.

**Comment by scorbett123** [comment]
I can't reproduce this, are you sure that you opened a chest?

**Comment by JamesTheAwesomeDude** [comment]
@scorbett123 I'm quite certain that I opened multiple chests when reproducing this.

Could you send a screenshot of it working on your end? (And, are you on Fabric, or Forge?)

**Comment by snoweuph** [comment]
Can i somehow help to fix this issue?

**Comment by snoweuph** [comment]
##System Information
Operating system: Windows 10
Java version: 16

##Process
- Download Forge/Fabric installer.
- Download Baritone standalone Version for right Mod Launcher
- Put jar into Mods-folder
- Start Instalation
- Create New World
- Check if Setting `containerMemory` is true
- Place Chest
- run `#chests`
- Put Items into Chest
- run `#chests`

##Reproduction Table
[x] = Can Reproduce?
NVF = No Version Found

| Version | Fabric | Forge |
| ------- | ------ | ----- |
| 1.17.1  |   [x]  |  NVF  |
| 1.16.5  |   [x]  |  [x]  |
| 1.16.4  |   NVF  |  [x]  |
| 1.16.2  |   NVF  |  [x]  |

**Comment by snoweuph** [comment]
Okay, so can I help with something else or do I just need to wait?

**Comment by snoweuph** [comment]
I haven't tested so far down yet, I'm on My Way testing More version :)

**Comment by snoweuph** [comment]
okay, so how do I setup a baritone standalone version, havnt found any real information

**Comment by snoweuph** [comment]
How would I install the baritone-standalone-1.3.8.jar?

**Comment by scorbett123** [comment]
They should all be forge

**Comment by snoweuph** [comment]
It could be, but I thought if its relevant @scorbett123  would have sayn someting about it

**Comment by snoweuph** [comment]
Both
