### ISSUE TITLE
Baritone not distinguishing blocks

### ISSUE THREAD

**Issue by Pabsb** [cabaletta/baritone#2569]
## Some information
Operating system: Windows 10 Home
Java version: 281 64 Bit
Minecraft version: 1.16.5
Baritone version: 1.6.3
Forge mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
N/A

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
.b set blocksToAvoidBreaking minecraft:grass_block
.b mine tall_grass grass
Baritone will throw an error for trying to add tall grass and if you put just grass it will still mine grass blocks even though minecraft:grass and minecraft:grass_block are two seperate things and with it still added to avoidbreaking list

## Modified settings
To get the modified settings run `#modified` in game
allowPlace False
blocksToAvoidBreaking

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Pabsb** [comment]
@l1ving Sorry if I'm just blind but I can't seem to find another issue with these bugs open right now, could you link them?

**Comment by ehylo** [comment]
#1164 is one, there are a lot more closed/open though
