### ISSUE TITLE
#sel set farmland not working

### ISSUE THREAD

**Issue by MrRedRhino** [cabaletta/baritone#2570]
## Some information
Operating system: MacOS
Java version: ???
Minecraft version: 1.16.5
Baritone version: Null
Forge mods (if used): None

## How to reproduce
select an area with #sel pos1 and #sel pos2 and let it fill it with farmland. It seems like it does not know that you have to use a hoe on grass/dirt to get farmland

## Modified settings
allowInventory, allowParkour, allowParkourPlace, allowVines, antiCheatCompatibility false, prefer silk-touch, replantnetherwart

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is not a bug

**Comment by MrRedRhino** [comment]
It's not a bug, is it a feature? Should i make a suggestion?

**Comment by scorbett123** [comment]
Yes, make a suggestion however it will most likely not be done.
