### ISSUE TITLE
Can't view Replay Mod with Baritone

### ISSUE THREAD

**Issue by watermelophent** [cabaletta/baritone#2573]
## Some information
Operating system: Windows 10 Pro
Java version: IDK
Minecraft version: 1.16.5 Fabric
Baritone version: 1.6.3
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/6143654/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Have Baritone 1.6.3 and Replay Mod (the latest Fabric version).
Make a quick replay recording
Open Replay Mod menu and load that recording

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
rename the replay mod jar to have a ! in the very front see #1936

**Comment by TheAwesome98-Real** [comment]
don't put "Java Version: IDK", put the version
