### ISSUE TITLE
Journeymap Waypoint and Advanced Xray rendering encounters a bug while using baritone

### ISSUE THREAD

**Issue by WarforgedKnockoff** [cabaletta/baritone#2574]
## Some information
Operating system: Windows
Java version: 
Minecraft version: 1.16.5
Baritone version: Forge standalone 1.16.2.
Forge mods (if used): 
Advanced Xray 1.16.5-2.7.0
Journeymap 1.16.5.-5.7.1.
## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue 

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Creating a waypoint causes the highlight when you look at it in the game world to be discoloured a gray-white making them unusable.
Using X-ray it does not use the attributed colours to the blocks, opting to use the same grey-white colour that the waypoints display.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by mysticdrew** [comment]
Hey there, Journeymap dev here. 
Here is an image of the issue. 
![image](https://user-images.githubusercontent.com/5459941/111213981-5b1f3c00-859f-11eb-9cde-132b62696f44.png)

I looked into it, it is broken in 1.6.2, but fixed in 1.6.3.

**Comment by scorbett123** [comment]
Update to 1.6.3 then.
