### ISSUE TITLE
Add ores to be mined with certain tools.

### ISSUE THREAD

**Issue by ovingiv** [cabaletta/baritone#2575]
## What do you need help with?
I'm playing with a modpack with some friends and there's ore in the world called "compactores". For whatever reason, baritone thinks a sword or hand would be the best tool to mine this ore. I've looked over assumeExternalAutoTool and disableAutoTool to see if that helps but I do run into dirt/gravel too often to just allow it to mine with the pickaxe. Would it be possible to add what can be mined with what tool?

Video for explanation: https://www.youtube.com/watch?v=hv36xeBkfK8
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
No, it's not possible to decide what tool to use for what block.
Currently the only possibility is to use a custom autotool.
