### ISSUE TITLE
Can i return to my newest death if i have died multiple times?

### ISSUE THREAD

**Issue by painfulpaladins** [cabaletta/baritone#2576]

**Comment by painfulpaladins** [comment]
also when i click the death waypoint a code appears

**Comment by scorbett123** [comment]
what do you mean by a code appears, maybe just try clicking on it and then clicking enter in what appears in chat.

**Comment by painfulpaladins** [comment]
and it appears for everyone

**Comment by scorbett123** [comment]
What is this code that appears?

**Comment by painfulpaladins** [comment]
![image](https://user-images.githubusercontent.com/58107644/111348964-6484d300-8689-11eb-8924-5a808fc00185.png)
when i click the first death

**Comment by painfulpaladins** [comment]
on the list

**Comment by painfulpaladins** [comment]
Its weird i click the death that is the newest and then some text appears that everybody can see

**Comment by painfulpaladins** [comment]
hm

**Comment by painfulpaladins** [comment]
I forgot to mention that i am using fabritone with wurst on fabric.I am gonna install baritone on forge and see what happens

**Comment by painfulpaladins** [comment]
Huh it works on forge.It may be the client

**Comment by ehylo** [comment]
If the jar your using for baritone says fabritone then that's most likely why, baritone officially supports fabric now so grab one of the jars at [this](https://github.com/cabaletta/baritone/releases/tag/v1.6.3) release

**Comment by painfulpaladins** [comment]
Ok do i need stand alone
