### ISSUE TITLE
Pathing over soulsand

### ISSUE THREAD

**Issue by KazzaKING** [cabaletta/baritone#2577]
## Some information
Operating system: Win10
Java version: 8
Minecraft version: 1.16.5
Baritone version: Uhhh Meteor client one
Forge mods (if used): optifine

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
try and path over soul sand, for me, while using #farm , it either wants to just break the soul sand, and if i disalow breaking, it just avoids soulsand at all cost, if on soulsand, it doesnt move. why??

## Modified settings
none except allowbreak when testing this

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#2543, #2539, #2536, #2489, #1877, #1550, #1180, #247, #120, #118, #7, #2094

**Comment by duynnz** [comment]
Please find your latest.log or debug.log in this folder and attach it to the issue
I do not understand this line maybe Google translate error you can not guide in detail

**Comment by duynnz** [comment]
delete new.log or debug.log huh

**Comment by duynnz** [comment]
> ## Một số thông tin
> Hệ điều hành: Win10
> Phiên bản Java: 8
> Phiên bản Minecraft: 1.16.5
> Phiên bản Baritone: Uhhh Meteor client một
> Forge mod (nếu sử dụng): optifine
> 
> ## Ngoại lệ, lỗi hoặc nhật ký
> Vui lòng tìm của bạn `latest.log`hoặc `debug.log`trong thư mục này và đính kèm nó vào vấn đề 
> 
> Linux: `~/.minecraft/logs/`
> 
> Các cửa sổ: `%appdata%/.minecraft/logs/`
> 
> Mac: `/Library/Application\ Support/minecraft/logs/`
> 
> ## Làm thế nào để tái tạo
> thử và đi qua cát linh hồn, đối với tôi, trong khi sử dụng #farm, nó muốn chỉ phá vỡ cát linh hồn và nếu tôi không phá vỡ linh hồn, nó chỉ tránh soul và bằng mọi giá, nếu trên souland, nó không di chuyển. tại sao??
> 
> ## Đã sửa đổi cài đặt
> không ngoại trừ allowbreak khi kiểm tra điều này
> 
> ## Danh sách kiểm tra cuối cùng
> * [x]  Tôi biết cách sử dụng đúng các hộp kiểm
> * [x]  Tôi đã bao gồm phiên bản Minecraft tôi đang chạy, phiên bản baritone và các mod giả mạo (nếu được sử dụng).
> * [x]  Tôi đã bao gồm nhật ký, ngoại lệ và / hoặc các bước để tái tạo vấn đề.
> * [x]  Tôi chưa sử dụng bất kỳ OwO hoặc UwU nào trong vấn đề này.

Đính kèm nó vào

> ## Một số thông tin
> Hệ điều hành: Win10
> Phiên bản Java: 8
> Phiên bản Minecraft: 1.16.5
> Phiên bản Baritone: Uhhh Meteor client một
> Forge mod (nếu sử dụng): optifine
> 
> ## Ngoại lệ, lỗi hoặc nhật ký
> Vui lòng tìm của bạn `latest.log`hoặc `debug.log`trong thư mục này và đính kèm nó vào vấn đề
> 
> Linux: `~/.minecraft/logs/`
> 
> Các cửa sổ: `%appdata%/.minecraft/logs/`
> 
> Mac: `/Library/Application\ Support/minecraft/logs/`
> 
> ## Làm thế nào để tái tạo
> try and path over soul sand, for me, while using #farm , it either wants to just break the soul sand, and if i disalow breaking, it just avoids soulsand at all cost, if on soulsand, it doesnt move. why??
> 
> ## Modified settings
> none except allowbreak when testing this
> 
> ## Final checklist
> * [x]  I know how to properly use check boxes
> * [x]  I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
> * [x]  I have included logs, exceptions and / or steps to reproduce the issue.
> * [x]  I have not used any OwO's or UwU's in this issue.

"Đính kèm nó vào vấn đề" 

> ## Some information
> Operating system: Win10
> Java version: 8
> Minecraft version: 1.16.5
> Baritone version: Uhhh Meteor client one
> Forge mods (if used): optifine
> 
> ## Exception, error or logs
> Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
> 
> Linux: `~/.minecraft/logs/`
> 
> Windows: `%appdata%/.minecraft/logs/`
> 
> Mac: `/Library/Application\ Support/minecraft/logs/`
> 
> ## How to reproduce
> try and path over soul sand, for me, while using #farm , it either wants to just break the soul sand, and if i disalow breaking, it just avoids soulsand at all cost, if on soulsand, it doesnt move. why??
> 
> ## Modified settings
> none except allowbreak when testing this
> 
> ## Final checklist
> * [x]  I know how to properly use check boxes
> * [x]  I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
> * [x]  I have included logs, exceptions and / or steps to reproduce the issue.
> * [x]  I have not used any OwO's or UwU's in this issue.

"Attach it to the problem" is what I do not understand someone help me
