### ISSUE TITLE
#mine is ignoring targeted blocks

### ISSUE THREAD

**Issue by AuroTheFrogzard** [cabaletta/baritone#2579]
Using Baritone on 1.16.5 doesn't seem to be fulfilling commands. I have been trying to execute "#mine iron_ore" and "#mine diamond_ore", the ores are being highlighted, however my character seems to avoid actually mining them. I have tried to use it on both multiplayer and singleplayer worlds, but even on singleplayer it misbehaves. Using the #mine command on the surface seems to path me somewhere completely irrelevant and ignores highlighted blocks

## Some information
Operating system: Win10
Java version: java version "1.8.0_281"
Minecraft version: 1.16.5
Baritone version: 1.6.3
Fabric mods (if used): Baritone, BookDupe (andrew_10_), Fabric API, Lithium, Phosphor, Sodium, Xaero's Minimap

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/6159928/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
#mine <any ore type>

## Modified settings
To get the modified settings run `#modified` in game
allowDownward false
allowInventory true
mobAvoidanceCoefficient 2.0
prefix = .

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by AuroTheFrogzard** [comment]
I tested it a bit more and it seems that the bot won't break blocks in the way of the ore. If the ore vein is visible, it would mine out the entire vein but won't actually path towards highlighted blocks.

**Comment by ZacSharp** [comment]
> # Modified settings
> 
> To get the modified settings run #modified in game

missing

> # How to reproduce
> 
> Add your steps to reproduce the issue/bug experienced here.
> #mine 

That gives an error, sure. But not the one you described.

**Comment by AuroTheFrogzard** [comment]
> 
> 
> > # Modified settings
> > To get the modified settings run #modified in game
> 
> missing
> 
> > # How to reproduce
> > Add your steps to reproduce the issue/bug experienced here.
> > #mine
> 
> That gives an error, sure. But not the one you described.

I have updated the modified settings.
What error did you achieve? Honestly I don't know how to replicate this bug because the only thing I'm typing is literally "#mine iron_ore" or "#mine diamond_ore"

**Comment by ZacSharp** [comment]
> the only thing I'm typing is literally "#mine iron_ore" or "#mine diamond_ore"

then maybe put that there instead
`#mine` alone outputs a friendly red error message asking for more arguments

**Comment by AuroTheFrogzard** [comment]
> 
> 
> > the only thing I'm typing is literally "#mine iron_ore" or "#mine diamond_ore"
> 
> then maybe put that there instead
> `#mine` alone outputs a friendly red error message asking for more arguments

I know that, that's not the issue I'm having. I'm inputting valid arguments but when the bot executes them, it refuses to mine towards the desired block

**Comment by ZacSharp** [comment]
I'll just ignore the wrong steps to reproduce for now and ask if you have a proper pickaxe in your inventory.

**Comment by AuroTheFrogzard** [comment]
> 
> 
> I'll just ignore the wrong steps to reproduce for now and ask if you have a proper pickaxe in your inventory.

Yes

**Comment by ZacSharp** [comment]
hm. what happens if you turn `allowDownward` on again?

**Comment by AuroTheFrogzard** [comment]
> 
> 
> hm. what happens if you turn `allowDownward` on again?

Makes no difference at all. It appears as if my character doesn't want to or partially destroy stone blocks near the ores. Not sure if that info is important or not

**Comment by ZacSharp** [comment]
Well, I can't reproduce this with your new instructions and I have no idea on what you could try, so I can't help.
Sorry.

**Comment by ZacSharp** [comment]
Oh, wait. I forgot the obvious one: Try removing your mods and if it doesn't happen without them, add them back one by one to find the culprit.

**Comment by AuroTheFrogzard** [comment]
> 
> 
> Oh, wait. I forgot the obvious one: Try removing your mods and if it doesn't happen without them, add them back one by one to find the culprit.

Tried it, didn't work even on vanilla + Baritone. I noticed that the bot will happily destroy dirt, gravel, andesite, granite, etc, but only partially destroys stone before moving to the next path... Any ideas about that?

**Comment by ZacSharp** [comment]
No

**Comment by AuroTheFrogzard** [comment]
> 
> 
> No

Sad. No worries

**Comment by l1ving** [comment]
I cannot reproduce this on vanilla. Lithium or phosphor are likely messing with it? It could be any one of those mods or a combination of mods, Sodium is compatible on the latest Baritone version.

I'll reopen this once you can provide steps to reproduce this on vanilla.

**Comment by AuroTheFrogzard** [comment]
> I cannot reproduce this on vanilla. Lithium or phosphor are likely messing with it? It could be any one of those mods or a combination of mods, Sodium is compatible on the latest Baritone version.
> 
> I'll reopen this once you can provide steps to reproduce this on vanilla.

I'm not entirely sure how to reproduce this, I have tried everything including disabling all mods aside from Baritone but yet it still persists. I've also tried installing the standalone, unoptimized and the regular version but it persists through all three. I've reinstalled Java 8, created a fresh instance of Minecraft but the problem is still there. I can't understand why it's bugged
