### ISSUE TITLE
Water Climbing

### ISSUE THREAD

**Issue by Hexcede** [cabaletta/baritone#2581]
## Describe your suggestion
The bot should be able to climb objects using water rather than towering to conserve blocks.

## Settings
`allowWaterBucketAscend` - Allow the bot to ascend obstacles using a water bucket instead of towering up using blocks.

## Context
Towering can use a lot of blocks and leaves a fairly obvious trail behind the bot. Using water would be cheaper for the bot, and, wouldn't leave behind anything.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This would be extremely complicated code-wise and would add another node of complexity to pathing which would be too large to calculate without significantly affecting the performance of normal pathing.

**Comment by ZacSharp** [comment]
This could be a single movement upwards using the multi-output movements designed for #2142.
But I do agree that this is way to complex.
