### ISSUE TITLE
Maybe make Baritone not just walk you off of an island in the End

### ISSUE THREAD

**Issue by watermelophent** [cabaletta/baritone#2584]
Baritone, when pathfinding to a block or something, should not just walk the player into the void.

Just a default part of the mod.

## Context
It would improve it because it wouldn't walk people into the void.  I told it to go to an End Rod to find an end city, and it just walked me right off the island into the void, resulting in the loss of my maxed tools and armor.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
invalid, cnr
