### ISSUE TITLE
Can't replace blocks with data type

### ISSUE THREAD

**Issue by skuuuu** [cabaletta/baritone#2586]
I can't replace slab with different position type with sel `command`

Example with worldedit:
```//replace cobblestone_slab[type=bottom] cobblestone_slab[type=top]```

On baritone I tried 
```.b sel replace cobblestone_slab[type=bottom] cobblestone_slab[type=top]```

but it throws this error: ``` Error at argument #3: expected ForBlockOptionalMeta ```

is the command correct? 

I'm using 1.16.5 version, with Fabric.

**Comment by l1ving** [comment]
No, it's not correct.

**Comment by tede12** [comment]
So what's the correct command?

**Comment by skuuuu** [comment]
So what's the correct command?

**Comment by scorbett123** [comment]
you can't.
