### ISSUE TITLE
Schematic build requiring null block

### ISSUE THREAD

**Issue by superartoo** [cabaletta/baritone#2587]
## Some information
Operating system: Windows 10
Java version: 1.8.0_281
Minecraft version:1.16.5
Baritone version:1.6.3
Fabric mods: WorldEdit
[latest.log](https://github.com/cabaletta/baritone/files/6172517/latest.log)

Note: I haven't really done much in baritone before

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
[TreeCastle.schem.zip](https://github.com/cabaletta/baritone/files/6172541/TreeCastle.schem.zip)
Run the Schematic I made, using barritone on any world (I was trying it in creative). You should get the error of it requiring the null block

## Modified settings
To get the modified settings run `#modified` in game
BuildInLayers = true
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

(Thank you for any help and I hope I have done this correctly)

**Comment by l1ving** [comment]
Your schematic has an invalid block in it

**Comment by superartoo** [comment]
sorry for the mistake

**Comment by josephyooo** [comment]
> Your schematic has an invalid block in it

Is there any documentation regarding the list of invalid blocks?

**Comment by scorbett123** [comment]
Uh, any block added after 1.12

**Comment by Flurrrr** [comment]
I'm not sure what you mean by that, baritone can build the .schem format just fine with 1.13+ blocks without issues

**Comment by scorbett123** [comment]
I mean, any block added after the version that you are using / doesn't exist in the current mc instance. (A modded block when you don't have the mod installed.

**Comment by josephyooo** [comment]
Don't mean to hijack this issue, but my schematic (build, saved, and attempted loading on 1.16.5) throws the same error when it seems as though there aren't any sort of blocks like that. [List of block types.](https://prnt.sc/110wx9f)

**Comment by Flurrrr** [comment]
Do you have a link to this schematic your trying to use or could you send it here?

**Comment by superartoo** [comment]
all I have really found out about invalid blocks is that stairs and wall torches don't work but thats it so I don't know what the invalid blocks are.

**Comment by Flurrrr** [comment]
@superartoo I loaded your schematic into a world and its just leaves? I don't think this is what you think it looks like, here is a picture
![image](https://user-images.githubusercontent.com/79301125/113258556-f0e5e700-9280-11eb-940e-0716cd7f87f8.png)
if it is, try using this [schem format](https://github.com/cabaletta/baritone/files/6241755/castletree.zip) file I made with those leaves and try and build it, the leaves are oak so make sure you have those on your hotbar (make sure you place it in `/.minecraft/schematics/` and then do `#build castletree.schem`)

**Comment by superartoo** [comment]
I don't really know what happened to the first one (for me it only did the top layer) but I ended up making several of the same schematic fixing it slightly every time so I do actually have a working one I managed to get it to work by removing the torches on the walls as well as stairs. If you want I can send the working schematic

**Comment by josephyooo** [comment]
> Do you have a link to this schematic your trying to use or could you send it here?

It's just a mob farm design I looked up online, the schematic is [here](https://file.io/CXBDzSuDihCy), though I'm not sure how long the link will stay up, I just googled any temporary file uploading service.
