### ISSUE TITLE
Can't find allowOnlyExposedOres in settings. Baritone 1.6.2 and 1.6.3

### ISSUE THREAD

**Issue by mkolakovsky** [cabaletta/baritone#2589]
I can't find in settings. if i type \#set allowOnlyExposedOres true it says: Error at argument \#1: Expected a valid setting, Am I doing something wrong? This happens while using both forge and fabric. But this setting is on this page https://baritone.leijurv.com/baritone/api/Settings.html

**Comment by l1ving** [comment]
It was added on October 14th of 2020 in 5a5d11922f5319ff1eb62081ee19676888896d44. The 1.16 branch's Settings file hasn't been updated since August 17th of 2020, so I'm guessing it hasn't been merged upwards.

https://github.com/cabaletta/baritone/blob/1.16.2/src/api/java/baritone/api/Settings.java

**Comment by scorbett123** [comment]
> It was added on October 14th of 2020 in [5a5d119](https://github.com/cabaletta/baritone/commit/5a5d11922f5319ff1eb62081ee19676888896d44). The 1.16 branch's Settings file hasn't been updated since August 17th of 2020, so I'm guessing it hasn't been merged upwards.
> 
> https://github.com/cabaletta/baritone/blob/1.16.2/src/api/java/baritone/api/Settings.java

@l1ving There is multiple 1.16 branches, I believe that 1.16.2 has fallen out of use, you now need to look at 1.16.5, where the latest release comes from. 

Are you sure that you are typing exactly allowOnlyExposedOres?

**Comment by mkolakovsky** [comment]
> > It was added on October 14th of 2020 in [5a5d119](https://github.com/cabaletta/baritone/commit/5a5d11922f5319ff1eb62081ee19676888896d44). The 1.16 branch's Settings file hasn't been updated since August 17th of 2020, so I'm guessing it hasn't been merged upwards.
> > https://github.com/cabaletta/baritone/blob/1.16.2/src/api/java/baritone/api/Settings.java
> 
> @l1ving There is multiple 1.16 branches, I believe that 1.16.2 has fallen out of use, you now need to look at 1.16.5, where the latest release comes from.
> 
> Are you sure that you are typing exactly allowOnlyExposedOres?

![image](https://user-images.githubusercontent.com/49320136/111959670-0d4e8a80-8aef-11eb-9382-c3daa6bd5c17.png)

**Comment by scorbett123** [comment]
Allow only exposed ores was added on 8th oct, the latest merge upwards was 3rd feb, the release was done on 6th feb. therefore it should be in version 1.6..3, make sure that you are using that.

**Comment by mkolakovsky** [comment]
> Allow only exposed ores was added on 8th oct, the latest merge upwards was 3rd feb, the release was done on 6th feb. therefore it should be in version 1.6..3, make sure that you are using that.

I use Inertia 3.1.3 on fabric 1.16.5, if I type \#version, it says Null Version. I don't know which should I download: API standalone or unoptimized

**Comment by l1ving** [comment]
> > It was added on October 14th of 2020 in [5a5d119](https://github.com/cabaletta/baritone/commit/5a5d11922f5319ff1eb62081ee19676888896d44). The 1.16 branch's Settings file hasn't been updated since August 17th of 2020, so I'm guessing it hasn't been merged upwards.
> > 
> > https://github.com/cabaletta/baritone/blob/1.16.2/src/api/java/baritone/api/Settings.java
> 
> @l1ving There is multiple 1.16 branches, I believe that 1.16.2 has fallen out of use, you now need to look at 1.16.5, where the latest release comes from. 
> 
> Are you sure that you are typing exactly allowOnlyExposedOres?

I didn't know that
