### ISSUE TITLE
Add support for allowOnlyExposedOres in 1.16.x game versions

### ISSUE THREAD

**Issue by mkolakovsky** [cabaletta/baritone#2592]
## Describe your suggestion
Update baritone 1.16.x, so it can support allowOnlyExposedOres.

## Settings
allowOnlyExposedOres
allowOnlyExposedOresDistance

## Context
Better compatibility with anti-xray

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
It should already have this. Make sure to type exactly allowOnlyExposedOres. 1.6.3 has been released since this was merged upwards.

**Comment by mkolakovsky** [comment]
> It should already have this. Make sure to type exactly allowOnlyExposedOres. 1.6.3 has been released since this was merged upwards.

#2589
