### ISSUE TITLE
baritone with the advanced macro mod throws me an illegal state exeption

### ISSUE THREAD

**Issue by Joschua725** [cabaletta/baritone#2594]
## Some information
Operating system: Windows 10
Java version: 
Minecraft version: 1.12.2, 1.14.4 or 115.2
Baritone version: Tryed all possible 
Forge mods (if used): advanced macro mod

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[debug.log](https://github.com/cabaletta/baritone/files/6184686/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/6184687/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Im trying to use the advanced macro mod (v7.9.0) to skript baritone
everything works fine exept the #mine command
I have already tryed to trubbleshoot it by using different MC, Baritone and AMM versions and i found out that it works with an older versions of the AMM . Version 5.3.0 is the last thasts works buit it has so manny other bugs that i cant use it.

## Modified settings
To get the modified settings run `#modified` in game

everything is default

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Remove advanced macro mod

**Comment by wagyourtail** [comment]
Ask in am discord they have it working

**Comment by MajsterTynek** [comment]
> Remove advanced macro mod

@Joschua725 Remove Baritone :)
but seriously, try my preview build from my fork I published in creations on [AdvancedMacros discord](https://discord.gg/dNgsJ8c):
https://discord.com/channels/473440074047160331/477916341706293278/816009952409157673

I have moved back sending chat messages to Minecraft's client thread
as Baritone injects there and expects it to be the main thread...
If you need any help interacting directly with Bartione API, ping Oxy.

As I work on 1.12.2 only, 
[patch](https://github.com/MajsterTynek/AdvancedMacros-WD_fix/commit/f618fdbd35f6f93566cd180a0d28bf558ffdf704) is only available for that version, 
but you can try do it for other versions as well.

**Comment by MajsterTynek** [comment]
saying commands is alright
```Lua
runOnMC(function()
    say "#version"
    say "#mine grass"
end)
```
but using [Baritone API](https://baritone.leijurv.com/) directly is way better:
```Lua
local Baritone = luajava.bindClass("baritone.api.BaritoneAPI")
local prim = Baritone:getProvider():getPrimaryBaritone()
runOnMC(function() prim:getMineProcess():mineByName(64,{"log"}) end)
```
