### ISSUE TITLE
follow player - unhandled exception

### ISSUE THREAD

**Issue by 265866** [cabaletta/baritone#2595]
## Some information
Operating system: Windows Version 20H2, build 19042.867
Java version: 1.16.5
Minecraft version: Java 8 update 281 (64-bit)
Baritone version: v.1.6.3
Forge mods (if used): none

## Exception, error or logs

https://pastebin.com/VrbP0a4h

## How to reproduce

#follow (mc user)

## Modified settings

None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
#1926

**Comment by 265866** [comment]
oh, okay, thank you!
