### ISSUE TITLE
Discord Commands

### ISSUE THREAD

**Issue by 265866** [cabaletta/baritone#2599]
## Describe your suggestion
Goes with #2598, would have to be a discord bot instead of webhook, but whenever you open an instance of minecraft w/ baritone, you get a 'instance ID'. Once in game, you can do #set discordGuildID (guild id you want to set), #set discordClientID (your discord id [so other users couldn't use commands]). Once you set those up, in discord you can do '(prefix) addInstance (instance id), then whatever you type in the guild ([prefix] whatever stuff you could actually do in game), would be actually executed on all instance id's you have set.

## Settings
 #set discordGuildID
 #set discordClientID

## Context
some people leave their PC running and aren't at their desktop, so you could control everything via phone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

## Extra
sorry if this didnt make too much sense, I'd be happy to answer any questions.

**Comment by l1ving** [comment]
This is way too much work for what it's worth

**Comment by l1ving** [comment]
Felt I should leave some context as to why, the easiest way to do this would be to have a Discord bot that interfaces with a locally running Baritone instance, which would require several things

- A discord bot made specifically for this
- An open interface for Baritone to run in order for the Discord bot to be able to control it
- Somehow have instructions comprehensible enough for users to set up the bot themselves
