### ISSUE TITLE
Custom Scripts?

### ISSUE THREAD

**Issue by Jpofin** [cabaletta/baritone#2600]
Hey,

I was wondering if anyone has a snippet for the bot going placing a bed/finding next bed, go to it and then sleep, once it is night?

**Comment by FloGo3308** [comment]
wdym snippet?
And I think you would need to make a mod(with the baritone api) to do such things, becouse baritone doesn't have a scripting system(at least that I know).

**Comment by scorbett123** [comment]
Baritone doesn't have scripting. However the client that you could be using might, Howe effect tumours is the wrong place to add if that is the case.
