### ISSUE TITLE
New Release for 1.12.2

### ISSUE THREAD

**Issue by scorbett123** [cabaletta/baritone#2602]
@leijurv, please can you create a new release for 1.12.

It has been nearly a year since the last one and in that time many features have been added, not limited to auto tool options and the ability to get the eta of you arrival. 

There has been >150 commit since this release, and unless you have a valid reason not to, I feel like now would be a good time for a new release for 1.12.

Thanks.

**Comment by ZacSharp** [comment]
I think releases should always be done for all versions at once right after merging upwards, so there is no difference in features between the latest versions (and it does a little against people thinking 1.12.2 was dropped because last releases are all for 1.16).
