### ISSUE TITLE
Cant mine modded blocks. 

### ISSUE THREAD

**Issue by MasteRSketch** [cabaletta/baritone#2603]
(1.12.2) I have been trying to mine Aluminum ore on galacticraft with the baritone mod for hours. I cant find any help online and was just wondering how to do it.

**Comment by scorbett123** [comment]
try #mine GalacticraftCore:gcBlockCore:7

**Comment by ZacSharp** [comment]
`#mine modid:blockid:meta`

**Comment by MasteRSketch** [comment]
> #mine GalacticraftCore:gcBlockCore:7
It only says "Error at argument #1: Expected ForBlockOptionalMeta

**Comment by MasteRSketch** [comment]
> `#mine modid:blockid:meta`
No idea what meta is...

**Comment by scorbett123** [comment]
I may have got the wrong id try GalacticraftCore:tile.gcBlockCore:7. Except from that idk, I don't use galaticraft and I am googling it to find the ids so they may be wrong.



> `#mine modid:blockid:meta`
> hate being slower
> 4 seconds and you even know the correct ids + meta


:sunglasses:

**Comment by MasteRSketch** [comment]
> I may have got the wrong id try GalacticraftCore:tile.gcBlockCore:7. Except from that idk, I don't use galaticraft and I am googling it to find the ids so they may be wrong.
Yh it still says the same thing. I have no idea.

**Comment by scorbett123** [comment]
Can you look at the block then press f3, on the right hand side it should have the name of the block, type that in after the #mine.

**Comment by MasteRSketch** [comment]
> Can you look at the block then press f3, on the right hand side it should have the name of the block, type that in after the #mine.

OMG LIFE SAVER ALERT!

**Comment by scorbett123** [comment]
What is the actual result, for next time.

**Comment by MasteRSketch** [comment]
> What is the actual result, for next time.

i am not sure how to mine one type of ore from that mod. but it did mine some modded ores. I used "galacticraftcore:basic_block_core" it also had under that "basictype: Ore_aluminum_gc" but i dont know how to make them one thing....

**Comment by ZacSharp** [comment]
I had galacticraft planets installed as well, so there are 3 aluminium ores:
* galacticraftcore:basic_block_core:7
* galacticraftplanets:venus:6
* galacticraftplanets:asteroids_block:3

I guess I should note that pathing failed with a NPE whenever there was the venus variant nearby.

**Comment by MasteRSketch** [comment]
> * galacticraftcore:basic_block_core:7

oh wow that works perfectly

**Comment by MasteRSketch** [comment]
> I had galacticraft planets installed as well, so there are 3 aluminium ores:
> 
> * galacticraftcore:basic_block_core:7
> * galacticraftplanets:venus:6
> * galacticraftplanets:asteroids_block:3
> 
> I guess I should note that pathing failed with a NPE whenever there was the venus variant nearby. But my Baritone and Galacticraft versions are outdated, so don't trust me.

would you happen to know what it would be for lead ore from the mekanism mod?

**Comment by ZacSharp** [comment]
Since I don't have mekanism, no.
But I can tell you what I did:
1. use the creative menu to search for aluminium ore
2. place it and use the debug hud (F3) to see it's id (galacticraftcore:basic_block_core)
3. try all 16 possible meta values (0-15) to find the wanted one using `/setblock <x> <y> <z> galacticraftcore:basic_block_core <meta>`
