### ISSUE TITLE
Baritone not placing outside of the schematic to continue

### ISSUE THREAD

**Issue by Nicster205** [cabaletta/baritone#2607]
So, I'm building a schematic with Baritone, and let's say, It needs to make a tower to go up, but It doesn't do that, if i try to do it manually, it breaks the block and continues doing nothing, Some help here?
[https://i.imgur.com/MMCuFs6.png](imgur)

**Comment by ZacSharp** [comment]
You should fill in the appropriate template (and provide (a) better screenshot(s), I can't really see what you are trying to to.
