### ISSUE TITLE
Minecraft AutoMiner Problem

### ISSUE THREAD

**Issue by LasagnenMann** [cabaletta/baritone#2608]
i want to use automining in a server for offline mining. if i type in #mine ... then it want to mine the block but with a wrong tool i want to use. for example : i want to mine wool with a pickaxe but it uses the fist. how do i manage that it uses a pickaxe for wool. is there like any command or anything?

**Comment by ZacSharp** [comment]
`#disableAutotool true`, select correct tool yourself, done
