### ISSUE TITLE
#mine has stopped working 

### ISSUE THREAD

**Issue by GreenJorgi** [cabaletta/baritone#2610]
when i do #mine diamond_ore it report this to the github page and thats why i made this post btw i need help with it

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
