### ISSUE TITLE
#schematica should optionally only build the selection

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#2612]
## Describe your suggestion
When running `#schematica` I think it could be poggers if it built only the little bit that is `#sel`'d.

## Settings
Idk maybe controlled by `schematicaOnlyBuildSelection`?

## Context
This would be super convenient to build small parts of large schematics so that Baritone doesn't spaz out and say "unable to do it" when there's random blocks that it doesn't know how to do

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Should this be applied once (like mapArtMode) or every tick (like buildInLayers)?

**Comment by leijurv** [comment]
Once at the beginning.
