### ISSUE TITLE
Replay mod crash

### ISSUE THREAD

**Issue by ChubbsWasTaken** [cabaletta/baritone#2613]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.5 fabric
Baritone version: Fabric 1.6.3
Forge mods (if used): None

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/6211660/latest.log)

## How to reproduce
1. Run minecraft with latest fabric loader version and both baritone and replay mod installed.
2. Collect replay footage.
3. Open replay
4. Crash

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Rename the Replaymod jar file to start with !

**Comment by ChubbsWasTaken** [comment]
ok thank you :)

**Comment by ChubbsWasTaken** [comment]
nvm still crashes

**Comment by ChubbsWasTaken** [comment]
it.. doesnt work. still crashes
