### ISSUE TITLE
fabritone not compatible with replay mod

### ISSUE THREAD

**Issue by VinuBoi** [cabaletta/baritone#2614]
## Some information
Operating system:
Java version:build 15.0.2+7-27
Minecraft version:1.16.5
Baritone version:1.6.1
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1.Play fabritone with the replay mod
2.Try and load a replay
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Fabritone is not supported and is discontinued. Use Baritone on Fabric.
