### ISSUE TITLE
tunnelling under lava does not leave a ceiling

### ISSUE THREAD

**Issue by end-user** [cabaletta/baritone#2615]
## Some information
Operating system: Win10
Java version: 14
Minecraft version: 1.16.5
Baritone version: 1.16.3 fabric
Forge mods (if used): 

## How to reproduce
Set a `#tunnel` to go under lava, removing the lava's floor
When the lava block is immediately above the top of the tunnel, Baritone still removes the block, allowing lava to descend.

This may not be a bug, but it was unexpected behavior.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Not really a bug
