### ISSUE TITLE
Can Baritone move closer to the blocks being broken so they're picked up?

### ISSUE THREAD

**Issue by end-user** [cabaletta/baritone#2616]
## What do you need help with?
When I have it set to clear an area, it feels like it stands back to do the work.  If it moved closer to the blocks being broken, they're more likely to be picked up. Is that a setting somewhere? This is more important when they are likely to fall - such as over a side or if there's air below it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Clear area does not focus on picking up blocks, explicit mining does
