### ISSUE TITLE
Baritone using boats

### ISSUE THREAD

**Issue by lalamapaka** [cabaletta/baritone#2617]
## Describe your suggestion
That baritone can use boats if there's one in your inventory.

## Settings
#set useboat true/false

## Context
When you're travelling baritone is really slow in oceans this would solve it I think.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Again, a duplicate.

**Comment by l1ving** [comment]
Someday people will think of original suggestions.
