### ISSUE TITLE
Swimming

### ISSUE THREAD

**Issue by lalamapaka** [cabaletta/baritone#2618]
## Describe your suggestion
If you're on a newer version maybe baritone could swim

## Settings
#set allowswim true/false

## Context
Baritone is really slow in water so maybe he could swim if it's in 1.13 or newer.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a duplicate, please search before creating an issue.
