### ISSUE TITLE
Crashes with Replaymod

### ISSUE THREAD

**Issue by VinuBoi** [cabaletta/baritone#2619]
## Some information
Operating system:MacOS
Java version:15.0.2
Minecraft version:1.16.4
Baritone version:baritone-standalone-1.16.3
Forge mods (if used):I used fabric mods
[2021-01-20-1.log](https://github.com/cabaletta/baritone/files/6217521/2021-01-20-1.log)
 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[2021-01-20-1.log](https://github.com/cabaletta/baritone/files/6217521/2021-01-20-1.log)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1.load a fabric mod with baritone and replaymod
2.try and load a recording
## Modified settings
To get the modified settings run `#modified` in game
When i try and do it nothing happens
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
See #1766

**Comment by Flurrrr** [comment]
> See #1766

@scorbett123  How does that issue relate to this one? I'm a little confused, and btw the "rename the file with ! infront" does not work at all.

**Comment by scorbett123** [comment]
Sorry, linked the wrong issue, wrong repo,  I believe that mixins need to be updated, however they causes lots more compatibility issues. The renaming used to work, does it not now?

**Comment by scorbett123** [comment]
> Sorry, linked the wrong issue, wrong repo,  I believe that mixins need to be updated, however they causes lots more compatibility issues. The renaming used to work, does it not now? Sometimes if replay mod is loaded first it doesn't have compatibility issues.

**Comment by Flurrrr** [comment]
I tested it a few days ago when someone said it didn't work (#2613 ) , and sure enough I still crashed
