### ISSUE TITLE
Use baritone as gps

### ISSUE THREAD

**Issue by Moumirrai** [cabaletta/baritone#2624]
Is it possible to use baritone as gps, or add this feature? So that the baritone would not control the player, but only render the path and recalculate it from time to time.

**Comment by FloGo3308** [comment]
you can use the command to path to the place/thing you want to go to, and the imidiatly do #pause. Then you can see the path but baritone won't walk it. ik this isn't a perfect solution, but you could use it temporarily.

**Comment by l1ving** [comment]
Not possible and this feature is already suggested.
