### ISSUE TITLE
sel replace (multiple items?)

### ISSUE THREAD

**Issue by JTzLinux** [cabaletta/baritone#2625]
Hello there I've been woundering how to use sel to replace multiple blocks I've been trying to replace everything in the selected areas with some items
What I want to replace:
- everything inside selected areas
- I've been trying to replace it with stone and polished Andesite
- I've tried to use: #sel replace a/ polished_andesite, stone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
You can't
