### ISSUE TITLE
Mispelling of Baritone

### ISSUE THREAD

**Issue by Oppyusa** [cabaletta/baritone#2628]
## Some information
Operating system: Windows 10
Java version: Minecraft default
Minecraft version: 1.16.5
Baritone version: GitHub Release a48ae2a (v1.6.3)
Fabric mods (if used): Sodium, Full bright

## How to reproduce
Run minecraft!
![image](https://user-images.githubusercontent.com/30739038/113374857-28fe3000-933c-11eb-8ea2-fb56ba87cffd.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [ X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
This is intentional.

**Comment by ZacSharp** [comment]
I had hope...

**Comment by FloGo3308** [comment]
> ## Some information
> Operating system: Windows 10
> Java version: Minecraft default
> Minecraft version: 1.16.5
> Baritone version: GitHub Release [a48ae2a](https://github.com/cabaletta/baritone/commit/a48ae2a9a8c799ada7bc25946fdad1e806036e6a) (v1.6.3)
> Fabric mods (if used): Sodium, Full bright
> 
> ## How to reproduce
> Run minecraft!
> ![image](https://user-images.githubusercontent.com/30739038/113374857-28fe3000-933c-11eb-8ea2-fb56ba87cffd.png)
> 
> ## Final checklist
> * [x]  I know how to properly use check boxes
> * [ X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
> * [X ] I have included logs, exceptions and / or steps to reproduce the issue.
> * [ X] I have not used any OwO's or UwU's in this issue.

It's not a bug, it's a feature... If the month is april and the day of the month is below 4(or below 3, idk how its index works) it displays baritoe instead of baritone.
This is the code:
`final boolean xd = now.get(Calendar.MONTH) == Calendar.APRIL && now.get(Calendar.DAY_OF_MONTH) <= 3;`
`ITextComponent baritone = new TextComponentString(xd ? "Baritoe" : BaritoneAPI.getSettings().shortBaritonePrefix.value ? "B" : "Baritone");`

**Comment by l1ving** [comment]
it it's April 1st, 2nd or 3rd it'll be spelled that way
