### ISSUE TITLE
Baritone while mining beacons 

### ISSUE THREAD

**Issue by baritonescareatone** [cabaletta/baritone#2630]
## Some information
Operating system: Windows 64-bit
Java version: 1.15.2
Minecraft version: 1.15.2
Baritone version: uh the latest
Forge mods (if used): no mods used

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
just use it to mine beacons and it won't use a pickaxe

## Modified settings
normal settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
A pickaxe won't make it go faster

**Comment by baritonescareatone** [comment]
> A pickaxe won't make it go faster

in servers it can and in a server im attempting it in it would
