### ISSUE TITLE
Is there a way to make baritone auto mine beacons with pickaxes?

### ISSUE THREAD

**Issue by baritonescareatone** [cabaletta/baritone#2631]
## What do you need help with?
when i auto mine beacons it wont mine with my pickaxe which is fine since it doesnt make it faster and would just waste durability but some servers make you mine faster with pickaxes so is there a way to make it mine with picks?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
#set autoTool false

**Comment by ZacSharp** [comment]
`#set disableAutoTool true` for some reason it's a disable-setting

**Comment by baritonescareatone** [comment]
> #set autoTool false

TYSM OMG I LOVE YOU D
