### ISSUE TITLE
how to make baritone not multisprint

### ISSUE THREAD

**Issue by ToonDeLeersnyder** [cabaletta/baritone#2633]
## What do you need help with?
how can i disable that baritone SPRINTS backwards. it is not anticheat proof and acts like multisprint hacks.

**Comment by ZacSharp** [comment]
Baritone doesn't walk, sprint or jump backwards (except for shifting backwards while placing a block).
It just allows you to look around without affecting the server side rotations.
To see the actual player rotation use `#set freeLook false`
