### ISSUE TITLE
Minecraft crashes when stepping on a chiselandbits modded block

### ISSUE THREAD

**Issue by JV63177** [cabaletta/baritone#2636]
## Some information
Operating system: Win 10 x64
Java version: 
Minecraft version: 1.16.5
Baritone version: Forge Api 1.6.3
Forge mods (if used): Chisel and Bits and a lot more that didn´t had this problem ( i literally tested every other block on a debug world )

##Latest Log:
[2021-04-04-8.log.gz](https://github.com/cabaletta/baritone/files/6254455/2021-04-04-8.log.gz)

## How to reproduce:
just create any block with chisel and bits and step on it with baritone installed

Latest Crash report:
[crash-2021-04-04_13.23.47-client.txt](https://github.com/cabaletta/baritone/files/6254454/crash-2021-04-04_13.23.47-client.txt)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
I looked into this, my first attempt to fix had issues 
![image](https://user-images.githubusercontent.com/6234704/114088460-466a5700-9872-11eb-90e0-e8ab10ded767.png)
it can get caught, if I have time I'll look into it, if anyone else wants to take a look https://github.com/wagyourtail/baritone/tree/c%26bfix1.16

**Comment by HolyHades** [comment]
Same happens for me with SolarFlux Reborn's Solar Panels, crash log is attached.

[crash-2021-04-16_17.16.39-client.txt](https://github.com/cabaletta/baritone/files/6326506/crash-2021-04-16_17.16.39-client.txt)

**Comment by scorbett123** [comment]
Closing in favour of #2752, they are the same issue and that one is slightly more detailed.
