### ISSUE TITLE
What release is 1.8.9? 

### ISSUE THREAD

**Issue by Quinniboi10** [cabaletta/baritone#2638]
What baritone release supports 1.8.9?

Thanks,
Quinniboi10

**Comment by Quinniboi10** [comment]
Yeah I know I'm dumb :/

**Comment by l1ving** [comment]
none of them

**Comment by bjoernp116** [comment]
Im pretty sure the 1.8 version would work just fine. But don't take my word for it. :)

**Comment by scorbett123** [comment]
There is no 1.8 version ever released for baritone.

**Comment by JK0011GaMiNgG** [comment]
yes there is, its called minebot by leijurv
