### ISSUE TITLE
Integrate hunger cost

### ISSUE THREAD

**Issue by 0-x-2-2** [cabaletta/baritone#264]

**Comment by leijurv** [comment]
This will probably be a mode where things that use up hunger have greatly increased cost. Perhaps it'll be just allowSprint off also increases the costs of jumping and jesus? If allowSprint is off that means you are trying to conserve hunger as much as possible, so I guess that's okay to be the same switch?

**Comment by SylveonBottle** [comment]
From what I understand, if you're wanting to make it hunger efficient you should give the bot increased cost for jumping and swimming. If it can walk around a pod without needing to jump then that's *super* efficient compared to swimming through it.

**Comment by leijurv** [comment]
Done in https://github.com/cabaletta/baritone/commit/ae9ab03e512649f93c55c0ecce934a2b36239ddd and https://github.com/cabaletta/baritone/commit/77938a77e8dbbc4266a92fbec7d27399c4a1254c
