### ISSUE TITLE
Baritone API doesn't work correctly

### ISSUE THREAD

**Issue by F14r30n** [cabaletta/baritone#2640]
## What do you need help with?
So, I am developing a utility mod for anarchy, and when I try to make some modules (e.g. AutoTunnel) I get an error saying:
```
The type bud cannot be resolved. It is indirectly referenced from required .class files
```
For example, on `ctx.player()`.
Thank you!

**Comment by scorbett123** [comment]
I think that things have been messed up in the latest release.

**Comment by l1ving** [comment]
> ctx.player()

Why are you calling obfuscated classes??
