### ISSUE TITLE
Autowalking and looking turn off?

### ISSUE THREAD

**Issue by LasagnenMann** [cabaletta/baritone#2644]
Hi! I have a question. Is there a way to turn off that when the automine funktion is on it walks and looks automatic? So for example it just looks in the direction i put it in and doesnt walk to something else? Something like a afk farm but it just stands still. im playing on a server where the ores reset them selves every like 30 sekonds... If there is a way please answer... if there is nothing like this, please answer anyway... 
In hope LasagnenMann

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
