### ISSUE TITLE
baritone cant walk then mining on fabric 1.16.5

### ISSUE THREAD

**Issue by TomerGamerTV** [cabaletta/baritone#2646]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.5
Baritone version: 1.6.3
Forge mods (if used): 

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6279999/latest.log)

## How to reproduce
do #mine minecraft:gold_ore or anything else and it just won't walk

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue. ;3

**Comment by scorbett123** [comment]
uh, if there is null version then you aren't on 1.6.3 unless leijurv messed up in the release, however make sure to download the latest version, **OR** uninstall sodium if it is installed.

**Comment by TomerGamerTV** [comment]
> uh, if there is null version then you aren't on 1.6.3 unless leijurv messed up in the release, however make sure to download the latest version, **OR** uninstall sodium if it is installed.

i dont have sodium and its the latest stable fabric version

**Comment by l1ving** [comment]
Use the official release from the releases tab

**Comment by TomerGamerTV** [comment]
> Use the official release from the releases tab

this is what i did
it didnt fix anything

**Comment by scorbett123** [comment]
Try removing other mods then.

**Comment by TomerGamerTV** [comment]
> Try removing other mods then.

i dont think its conflicts with something

**Comment by scorbett123** [comment]
Ok then, send a log where you also run #modified, however still check this happens on a blank install with no other mods.

**Comment by TomerGamerTV** [comment]
i did #modified but its not showing anything

i tried doing a blank install and it worked on a flat world....
if its not the problem with the mod and what can cause it

**Comment by scorbett123** [comment]
> if its not the problem with the mod and what can cause it

It is probably a conflict remove all other mods and try again.
