### ISSUE TITLE
crash on joining a world/server

### ISSUE THREAD

**Issue by SMLkaiellis08** [cabaletta/baritone#2649]
## Some information
Operating system: windows 10
java version: "1.8.0_281"
Minecraft version: 1.12.2
Baritone version: baritone-api-forge-1.2.15
Forge mods (if used): MoreBlocks-2.4.7,Tails-1.12-1.10.0,phosphor-1.12.2-0.2.6+build50-universal,colytra-1.12.2-1.2.0.4,bannerelytra-1.0,CreativeCore_v1.10.47_mc1.12.2,wings-1.1.6-1.12.2,vehicle-mod-0.44.1-1.12.2,ToughAsNails-1.12.2-3.1.0.141-universal,TravelersBackpackIntegration-1.12.2-1.0.1,TravelersBackpack-1.12.2-1.0.35,sit-1.12.2-v1.3,respawnable-pets-1.0.6.1,llibrary-1.7.20-1.12.2,Vampirism-1.12.2-1.6.2,howlingmoon-1.12.2-0.9,Forgelin-1.8.4,MixinBootstrap-1.0.5,MixinBootstrap-1.0.5,furniture-6.3.1-1.12.2,obfuscate-0.4.2-1.12.2,jei_1.12.2-4.16.1.302,jei_1.12.2-4.16.1.302,MorePlayerModels_1.12.2-(05Dec19),chiselsandbits-14.33,Netherite-1.12.2-1.3.0,MCapi-1.3.0,OptiFine-1.12.2_HD_U_G5

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[debug.log](https://github.com/cabaletta/baritone/files/6286427/debug.log)

[latest.log](https://github.com/cabaletta/baritone/files/6286417/latest.log)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Remove no-verify.

**Comment by SMLkaiellis08** [comment]
thanks i forgot why i added that
