### ISSUE TITLE
When mining, the view sometimes flashes backwards

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#265]
I suspect this is something to do with wrapping player angles to relative, and having it increase by 360° every time perhaps? It only happens some of the time, but now I suspect that might be only when I'm mining north, or whatever yaw = 0 is. When it happens, it happens every block. I think it renders a full rotation while it's just trying to maintain mining in the exact same direction.

**Comment by leijurv** [comment]
I was remembering correctly that it happened when going north, but that's actually not yaw = 0, it's instead right between +180 and -180, which makes sense.

It happens a bit at the beginning, and again some more 34 seconds into this vid:
https://youtu.be/qtjMaF7Yt2I

**Comment by leijurv** [comment]
@ZeroMemes i blame you ree XD

**Comment by ZeroMemes** [comment]
Fixed in 147df1ffb262518ed7a1c0a37d28300eb87ceb34 until otherwise proven

**Comment by ZeroMemes** [comment]
Wasn't fixed lol

**Comment by babbaj** [comment]
this happens when you try to wrap yaw which vanilla never does

**Comment by ZeroMemes** [comment]
If only Mojang wasn't trash and just kept angles between ``-180`` and ``180`` 😠
