### ISSUE TITLE
Auto farm break blocks and farm different at once.

### ISSUE THREAD

**Issue by Tytova** [cabaletta/baritone#2650]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
1- how to stop baritone from breaking through walls/floors while farming?
2- how to farm specific crop only for example potatoes? i have a lot of farming layers and while im farming potatoes it breaks the wall and jump down to the 2nd layer and start farming nether warts instead. 
im using impact 1.12.2, i tried other versions too but same problem, is there is any commands to farm specific crop or force baritone not to break any blocks besides the crops?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#allowBreak false, and you cannot farm only one type at once though that's suggested
