### ISSUE TITLE
Suggestion for farming

### ISSUE THREAD

**Issue by Chaosfelix4451** [cabaletta/baritone#2652]
I have some trouble with some xp farms that i get hunger after some time or get kicked a few blocks away so it would be cool when a automatic xp grinder would come for baritone which you can place at some farms where it stand and auto klick them away eat and always go back to the position where the xpfarm is

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
