### ISSUE TITLE
Baritone crashes in conjunction with the VanillaFix mod [org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException]

### ISSUE THREAD

**Issue by NeariX67** [cabaletta/baritone#2653]
## Some information
Operating system: Windows 10
Java version: 1.8.0_202
Minecraft version: 1.12.2
**Modpack: FTB Academy Minecraft 1.12.2 (v1.1.0)**
Baritone version: 1.2.15 (also applies to 1.2.14, other versions not tested)
Forge mods (if used): [See "Mod List" here](https://www.feed-the-beast.com/modpack/ftb_academy)

## Exception, error or logs
[Crashlog with VanillaFix enabled](https://pastebin.com/bKypENCk)
[Crashlog from FTBLauncher with Vanillafix enabled](https://pastebin.com/yMtRqZNz)

## How to reproduce
Download FTB Academy (v1.1.0, newer versions untested)
Install Baritone
*Crash*
Disable VanillaFix with "Edit mods"
*Not crashing*

**Comment by scorbett123** [comment]
Disable vanillafix then, baritone is obviously incompatible with it.

The other option (which rarely works) is to try renaming baritone to !baritone, this should make it load the mixins before other mods.
