### ISSUE TITLE
When using #build some blocks are not being build and Istarts to walk around 

### ISSUE THREAD

**Issue by 2056435787** [cabaletta/baritone#2656]
## I first used SpiritCraft 1.17 to produce a schematic and it worked when I use #build command, but after a while I found out every color of wools are not being placed(white, pink, blue etc) and nether quartez_ore, nether brick will not be placed. After the bot finished placing blocks it can place(gold block, iron block, lapis block, diamon block, gravel, netherrack, sand, sand stone etc) it starts to back and forth in like 150 blocks range.
Operating system: windows 10 home 64bit
Java version: 1.8.0
Minecraft version: 1.16.5
Baritone version: 1.6.3 fabric
Forge mods (if used):  

## Exception, error or logs
Please find your `latest.log` or `debug.l
[latest.log](https://github.com/cabaletta/baritone/files/6298707/latest.log)
og` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
When I type #build blah.schematic

## Modified settings
allowInventory true
rightClickSpeed 1

## Final checklist
- [x] I know how to properly use check boxes 
- 
[latest.log](https://github.com/cabaletta/baritone/files/6298769/latest.log)
[ 
[ +] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [+ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [+ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Make the schematic in the same version that you're playing

**Comment by 2056435787** [comment]
I am pretty sure I am using schematic the same version I am playing, because I used latest spritecraft and I can send you the schematic I am currenting using, by the way,I can even load the schematic in the litematica mod succesfully and wools and other blocks are not being placed are shown. Additionally I noticed #build can't place Diorite, Polished Diorite, it will replace those blocks with stone.
![Screenshot (176)](https://user-images.githubusercontent.com/82400623/114442305-6a8fa600-9b9a-11eb-969f-7c2618cee4b6.png)
![Screenshot (177)](https://user-images.githubusercontent.com/82400623/114442320-6c596980-9b9a-11eb-9ff1-22627b81c9f4.png)
Those picture showed the work of the #build had done and the litematica mod shown the work #build can't be done.

**Comment by 2056435787** [comment]
Here is the google draive that includes my schematica [](https://drive.google.com/drive/folders/146sNR9NV7-G6NrDrTCtM66G0q_9efIGN?usp=sharing)

**Comment by 2056435787** [comment]
![Screenshot (178)](https://user-images.githubusercontent.com/82400623/114443263-7a5bba00-9b9b-11eb-9bcc-6f13c043f635.png)
![Screenshot (179)](https://user-images.githubusercontent.com/82400623/114443269-7b8ce700-9b9b-11eb-80bd-6916c316c29a.png)
![Screenshot (180)](https://user-images.githubusercontent.com/82400623/114443273-7d56aa80-9b9b-11eb-89fe-b6306c62f49f.png)
Those pictures showed why I keep walking around, thsoe greeen boxes keep popping up and when I walk close they all disappear and moving to another end of the map.

**Comment by Flurrrr** [comment]
If litematica can load the schematic it was made in 1.12.2 or older

**Comment by 2056435787** [comment]
Yeah I am playing in 1.16.5, you mean builder is designed for 1.12.2?

**Comment by Flurrrr** [comment]
> Make the schematic in the same version that you're playing

**Comment by 2056435787** [comment]
Thank you
