### ISSUE TITLE
 #builds can only fully function in 1.12.2?

### ISSUE THREAD

**Issue by 2056435787** [cabaletta/baritone#2658]
## What do you need help with?
Is it that #build in Baritone can only fully functions in minecraft1.12.2? cause I noticed many said that if the schematic is produced in 1.16.5 they all suggest me to use worldedit.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
it has to be made in the same version that you are playing
