### ISSUE TITLE
Baritone won't mine monster egg block (blocks with silverfish)

### ISSUE THREAD

**Issue by Bofuga** [cabaletta/baritone#2659]
Baritone does'nt find the monster_egg block even if it is right in front of me.
I am using Impact, and tried :
.b mine minecraft:monster_egg
.b mine monster_egg
.b mine minecraft:monster_egg:X (from 0 to 15)
.b mine monster_egg:X (from 0 to 15)

Am i doing something wrong or is it a bug ?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
if it's not working then it isn't the name of the block

**Comment by Bofuga** [comment]
well it is though
