### ISSUE TITLE
i cant move when activating the auto mine

### ISSUE THREAD

**Issue by Coolguillermo1** [cabaletta/baritone#2660]
## Some information
Operating system:
Java version:1.16.5
Minecraft version:1.16.5
Baritone version:1.62
Forge mods (if used): yes

bug: cant move when activating the auto miner

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
