### ISSUE TITLE
Can admins see the baritone commands i write inside the console?

### ISSUE THREAD

**Issue by NotSpyware** [cabaletta/baritone#2663]
I am using baritone on a server and i want to know if the admins can see the baritone commands i write inside the console or does it not show any baritone command i typed ?

**Comment by ZacSharp** [comment]
Baritone commands are intercepted and never processed by vanilla, so they aren't sent to the server.
Just watch out for typos when using chat control (no prefix) because they prevent commands from being intercepted.
