### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by duynnz** [cabaletta/baritone#2666]
How to go on the sand of soul and fame nether_wart. Help me!

**Comment by l1ving** [comment]
did you try searching for existing issues

**Comment by duynnz** [comment]
> bạn đã thử tìm kiếm các vấn đề hiện tại chưa

I can't find it in here

**Comment by ZacSharp** [comment]
Guess you searched for "sand of soul" instead of "soul sand".
Here's a little list of duplicates https://github.com/cabaletta/baritone/issues/2577#issuecomment-801251717

**Comment by duynnz** [comment]
I have seen that post but I don't understand how you can help me

**Comment by duynnz** [comment]
I've seen Pat the soul but I don't understand how the last step is how you
guide me

>

**Comment by duynnz** [comment]
Please help me

Vào 5:11, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:

> I've seen Pat the soul but I don't understand how the last step is how you
> guide me
>
>>

**Comment by duynnz** [comment]
The words translated by google are wrong, so I don't understand, you can
help me

Vào 5:38, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:

> Please help me
>
> Vào 5:11, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:
>
>> I've seen Pat the soul but I don't understand how the last step is how
>> you guide me
>>
>>>

**Comment by duynnz** [comment]
😓



Vào 5:43, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:

> The words translated by google are wrong, so I don't understand, you can
> help me
>
> Vào 5:38, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:
>
>> Please help me
>>
>> Vào 5:11, Th 7, 17 thg 4, 2021 Nguyễn Duy ***@***.***> đã viết:
>>
>>> I've seen Pat the soul but I don't understand how the last step is how
>>> you guide me
>>>
>>>>

**Comment by Flurrrr** [comment]
There is no fix, its currently a bug

**Comment by duynnz** [comment]
help me, how can I turn off the automatic door opening function of BARITONE

Vào 11:00, Th 7, 17 thg 4, 2021 Flur ***@***.***> đã viết:

**Comment by ZacSharp** [comment]
There is no option to turn it off and you should open separate issues for separate questions.
