### ISSUE TITLE
Baritone not working

### ISSUE THREAD

**Issue by Commonly1284** [cabaletta/baritone#2669]
Baritone loads all fine but when I use #mine oak_log to go get logs, my player doesn't move and I can't move with my keyboard either

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
