### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by notahumanthatisimportant** [cabaletta/baritone#2670]
## Some information
Operating system: windows 10
Java version: jdk 8
Minecraft version: 1.16.4
Baritone version: 1.6.3
Fabric mods (if used): adventurez, opitfine and optifabric, better caves, fabric api, fabric language, fairylights, guillotine, immersive portals, origins extra origins and mob origins, mostructure, pehkui, phosphor, REI, secret rooms mod, and Youngs api plus Youngs better caves.

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue.

No crash

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Type goto, or mine to a block, will pathfinder but not move. Same problem in normal vanilla
## Modified settings
To get the modified settings run `#modified` in game
None
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by notahumanthatisimportant** [comment]
Could hust an installation issue but I don't think so

**Comment by l1ving** [comment]
Try without other mods
