### ISSUE TITLE
Baritone pathfinding but not following path 

### ISSUE THREAD

**Issue by notahumanthatisimportant** [cabaletta/baritone#2671]
## Some information
Operating system: windows 10
Java version: jdk 8
Minecraft version: 1.16.4
Baritone version: 1.6.3
Fabric mods (if used): optifine, immersive portals, a couple of cave gen mods, adventurez, and some other. Also have problems in vanilla 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
No crash
Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Tell baritone to mine or go somewhere, it will pathfinder and then freeze in place
## Modified settings
To get the modified settings run `#modified` in game
Prefix 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by notahumanthatisimportant** [comment]
Probably an install issue with fabric pls help

**Comment by l1ving** [comment]
immersive portals is known to cause issues
