### ISSUE TITLE
The '#somecommand' does not trigger anything

### ISSUE THREAD

**Issue by alejandro-alzate** [cabaletta/baritone#2672]
when i try to like this
#goto oak_log
It doesn't trigger anything

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
