### ISSUE TITLE
Baritone does not work

### ISSUE THREAD

**Issue by alejandro-alzate** [cabaletta/baritone#2673]
## Some information
Operating system: Win 8 pro
Java version: 8 update 281
Minecraft version: 1.16.5 singleplayer
Baritone version: 1.2.15
Forge mods (if used): 
 none
## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/6330256/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/6330258/latest.log)

## How to reproduce
Nothing i'm just trying to load commands and nothing happends, i think it even is not loaded. BUT WHY the .jar file are in the mod folder
## Modified settings
When i run '#modified' It just appears like a chat comment

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue. Really, what with this? It's happends? is hilarious

**Comment by l1ving** [comment]
> Minecraft version: 1.16.5 singleplayer
> Baritone version: 1.2.15

There is your problem

**Comment by alejandro-alzate** [comment]
> > Minecraft version: 1.16.5 singleplayer
> > Baritone version: 1.2.15
> 
> There is your problem

What does mean?

**Comment by Flurrrr** [comment]
![image](https://user-images.githubusercontent.com/79301125/115130301-98625980-9fa3-11eb-8703-21bf90c7fb83.png)
Read the description of that, you want https://github.com/cabaletta/baritone/releases/tag/v1.6.3

**Comment by alejandro-alzate** [comment]
ok nevermind this

**Comment by alejandro-alzate** [comment]
But wait one more thing before leave my mess here.
Can i keep the .jar for every version were without failures?
I realize 'There is your problem' before the comment reading a chunk of the documentation, sorry for the time-lost here.
And (this dont make any sense but you know) what about of owl smiles on the issues? i cant get it, its like 'dont throw your baby off the bridge' on roblox, is so common to do that?

**Comment by Flurrrr** [comment]
I'm not sure what that second half is all about but if your using forge in 1.16.5, no you must have the correct version, if you're using fabric in 1.16.5 then fabric will ignore the forge 1.12.2

**Comment by alejandro-alzate** [comment]
huh? well frabric ignore it ok, thanks for your time.

**Comment by alejandro-alzate** [comment]
It works! For me the issue was me,
I can now leave this in peace.
Nice mod! keep up.
