### ISSUE TITLE
Why am I getting this error when trying to use the api?

### ISSUE THREAD

**Issue by nullFoo** [cabaletta/baritone#2675]
I'm getting a SecurityException error when trying to run the example API code in my custom client. The error is `java.lang.SecurityException: class "ain"'s signer information does not match signer information of other classes in the same package`. I've checked and "ain" is one of the 1.12.2 classes. I'm not using forge or fabric

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
