### ISSUE TITLE
builld and schematica command

### ISSUE THREAD

**Issue by HattoriHanzuo** [cabaletta/baritone#2676]
Baritone can noch find the schematica files... And the schematica command say schematica is not present...

![image](https://user-images.githubusercontent.com/17326124/115160274-b7daae80-a097-11eb-9e2e-1efad0c34d46.png)

![image](https://user-images.githubusercontent.com/17326124/115160287-c3c67080-a097-11eb-8331-f14d483e826d.png)

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)

**Comment by Flurrrr** [comment]
For the first screenshot, it's saying it could not load the schematic, it found it just not loaded it. For the second screenshot that's only if you have the schematica mod installed and not needed to use the build command.

To solve your first issue I would change the file extension to `.schem` instead of `.schematic` and then try again

**Comment by HattoriHanzuo** [comment]
> For the first screenshot, it's saying it could not load the schematic, it found it just not loaded it. For the second screenshot that's only if you have the schematica mod installed and not needed to use the build command.
> 
> To solve your first issue I would change the file extension to `.schem` instead of `.schematic` and then try again, it might work but also might not as well but worth a try

Sorry... But this work not...
