### ISSUE TITLE
disconnectOnArrival doesn't work for tunnel

### ISSUE THREAD

**Issue by orri69420** [cabaletta/baritone#2678]
I wanted to leave baritone tunneling while I was asleep and then disconnect when it was done but it doesn't seem to work when I tested it with a shorter tunnel

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
