### ISSUE TITLE
any way i can make baritone only plant netherwart and not harvest

### ISSUE THREAD

**Issue by Rebcorn** [cabaletta/baritone#2680]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I am trying to make a netherwart planting script for big layer farms and i cannot get baritone to plant it fast cuse it would always destroy nether wart that grew mid planting (i am playing on a server which plant grow is boosted) any change in setting i can do to make baritone only focus on planting
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.
- [ ] i am not pro

**Comment by scorbett123** [comment]
You can't really  at the moment, you can probably use sel and #sel fill nether_wart,  however I can't guarantee that that would work due to the difficulty baritone has will soul sand.

**Comment by Rebcorn** [comment]
hmmm it did wort but could i do smth with sugarcane or is that diffculte too

**Comment by scorbett123** [comment]
The same thing should work as long as you don't place sugarcane on sugarcane, it will have to be on a full block.

**Comment by Rebcorn** [comment]
> The same thing should work as long as you don't place sugarcane on sugarcane, it will have to be on a full block.

i have another question with the replace i will mark an area for selection(area with logs in it) and when i press replace it wouldnt start hitting the trees it would just do this 
![image](https://user-images.githubusercontent.com/83039572/116406835-c4020100-a839-11eb-9646-53eb01efb331.png)

**Comment by Rebcorn** [comment]
> The same thing should work as long as you don't place sugarcane on sugarcane, it will have to be on a full block.

and baritone wont address sugar cane as a block...

**Comment by Rebcorn** [comment]
> The same thing should work as long as you don't place sugarcane on sugarcane, it will have to be on a full block.

manage to make it work out now the problem that baritone randomly pauses and u need a press a key to make it countinue working
