### ISSUE TITLE
baritone commands don"t work

### ISSUE THREAD

**Issue by PanDemonum** [cabaletta/baritone#2681]
## Some information
Operating system:10 
Java version:build 1.8.0_51-b16
Minecraft version: 1.16.5
Baritone version: idk , baritone was installed automaticaly with inertia
Other mods (if used): inertia client and diamondgen

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/6364012/latest.log)
[latest.log](https://github.com/cabaletta/baritone/files/6364015/latest.log)

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

1.when i use one cammand for example: #goto 13 , bot go to this level and when i run next command for example #goto 25,#mine the bot does nothing. im see in chat :mining (what I chose for example diamond_ore) but the bot stands still and the commands do not work
![unknown](https://user-images.githubusercontent.com/71757708/115892913-eec61100-a457-11eb-95a8-b9264fb89aaf.png)
i see that but bot dont do anything

2.when i use #mine for example diamond_ore,ancient_debris,iron_ore the bot smashes all the blocks around and as if it doesn't know where the diamonds are, it walks left, right and can't find
![unknown](https://user-images.githubusercontent.com/71757708/115893012-043b3b00-a458-11eb-9b85-e8e785ef4b36.png)
when i write #mine diamond i see that and bot go left,right and dont know were is diamonds

**Comment by PanDemonum** [comment]
i can record  video with problem if you dont understand

**Comment by scorbett123** [comment]
What is the result of #modified?

**Comment by PanDemonum** [comment]
I reinstall everything and now working, idk what I did bad but now working. Thanks everyone for help and sorry for problem
