### ISSUE TITLE
Integration with voxelmap

### ISSUE THREAD

**Issue by UsernameNotAvalible** [cabaletta/baritone#2682]
## Describe your suggestion
I use voxelmap to make waypoints. So, I think it would be very cool if Baritone could see any waypoints added in VoxelMap and handle them like internal waypoints, meaning I could use the "wp goto" command to go to voxelmap waypoints, the "wp g" command to set a voxelmap waypoint as a goal, etc. I also think it would be cool if you would run a command to copy all baritone waypoints into voxelmap.

## Settings
There could be a setting to enable and disable showing voxelmap waypoints in baritone and another setting to enable and disabled showing baritone waypoints in VoxelMap.

## Context
My suggestion would be very helpful for players that like the features of voxelmap but also want to use baritone.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Voxel map is closed src meaning that this would be hard to impossible to actually implement.

**Comment by wagyourtail** [comment]
while I disagree with the "hard to impossible" part as loom allows importing (and remapping) compiled mods, and it didn't even require a new mixin to dom it is definitely out of scope to do this directly in baritone. (I did however add it to https://github.com/R3alCl0ud/Fabritone-voxelmap-integration )
