### ISSUE TITLE
Integer error on all Baritone 1.16.5 forge jar mods

### ISSUE THREAD

**Issue by StupidRepo** [cabaletta/baritone#2685]
## Some information
Operating system: MacOS (and my friend who is on Windows that is also getting this error/bug)
Java version: Java 8
Minecraft version: FORGE 1.16.5
Baritone version: 1.6.3
Other mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Mac: https://paste.atlauncher.com/view/d6cf2ddd-dbc3-4b0f-a4e4-ab00219f518b

## How to reproduce
Download Baritone for Forge 1.16.5 and you get a class not found error for sodium (which I don't have btw) and typing `baritone mine diamond_ore` gives an integer error.

## Modified settings
None.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, Baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue. **Note by me: Well this is a incomplete checkbox then because it now has them 2 expressions in this sentence so...**

**Comment by StupidRepo** [comment]
Note again: This also happens to my friend on Windows.

**Comment by scorbett123** [comment]
Your using the commands wrong, no need to explicitly write baritone, just the command, eg "#mine oak_logs".

btw the class not found exception is deliberate and stops issues when people are using the mod sodium.

**Comment by StupidRepo** [comment]
Oh ok, yeah I figured that out (Just the command, eg "#mine oak_logs") haha

> btw the class not found exception is deliberate and stops issues when people are using the mod sodium.

Oh, that's cool.
