### ISSUE TITLE
.b mine BUG

### ISSUE THREAD

**Issue by onenok** [cabaletta/baritone#2686]
'.b mine cobblestone' is no working to cobblestone when it make by Cobblestone machine

**Comment by scorbett123** [comment]
what about it isn't working?

**Comment by onenok** [comment]
> 那怎麼辦呢？

**Comment by onenok** [comment]
no working to cobblestone when it make by Cobblestone machine

**Comment by onenok** [comment]
> what about it isn't working?

no working to cobblestone when it make by Cobblestone machine

**Comment by scorbett123** [comment]
What about it isn't working, how is it not working, are there errors in chat?

**Comment by onenok** [comment]
> What about it isn't working, how is it not working, are there errors in chat?

he cant find cobblestone when it makes by Cobblestone machine

**Comment by scorbett123** [comment]
can you send a log

**Comment by onenok** [comment]
> can you send a log

log?

**Comment by onenok** [comment]
what is it

**Comment by scorbett123** [comment]
basically fill in the template for a proper bug issue, fill this in 


## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ccuser44** [comment]
Mining cobblestone with baritone from cobblestome generator isn't ideal. Try to use automine

**Comment by scorbett123** [comment]
user made another issue: #2687
