### ISSUE TITLE
.b mine bug

### ISSUE THREAD

**Issue by onenok** [cabaletta/baritone#2687]
## Some information
Operating system:Windows 10 家用版
Java version:8(?
Minecraft version:1.12.2
Baritone version:null
Other mods (if used):nothing

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6372011/latest.log)

## How to reproduce
'.b mine cobblestone'(need just have cobblestone make by cobblestone machine near you)

## Modified settings
![0000000000000000 (2)_LI](https://user-images.githubusercontent.com/83169133/115995539-3e4e3d80-a60e-11eb-94aa-4192aa4db1b8.jpg)

## Final checklist
- [o] I know how to properly use check boxes 
- [o] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [o] I have included logs, exceptions and / or steps to reproduce the issue.
- [o] I have not used any OwO's or UwU's in this issue.

**Comment by onenok** [comment]
help

**Comment by scorbett123** [comment]
Are you sure that you are allowed to use baritone on this server, doesn't look like it to me.

**Comment by onenok** [comment]
> Are you sure that you are allowed to use baritone on this server, doesn't look like it to me.

baritone can use in server, I'm using impact

**Comment by maska228** [comment]
He is prob saying that he can't mine cobble that is made by cobble generator lol

**Comment by onenok** [comment]
> He is prob saying that he can't mine cobble that is made by cobble generator lol

really?

**Comment by SpikeVN** [comment]
Just weight your mouse down

**Comment by scorbett123** [comment]
Working as intended.
