### ISSUE TITLE
When trying to compile baritone 1.12.2 localy build fails

### ISSUE THREAD

**Issue by drori200** [cabaletta/baritone#2688]
The build fails while giving this error, i am using IntelliJ IDEA

com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not find minecraftBin.jar (net.minecraft:minecraftBin:1.12.2).
Searched in the following locations:
    https://files.minecraftforge.net/maven/net/minecraft/minecraftBin/1.12.2/minecraftBin-1.12.2.jar
> Could not find minecraftBin.jar (net.minecraft:minecraftBin:1.12.2).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/net/minecraft/minecraftBin/1.12.2/minecraftBin-1.12.2.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 
 the build.gradle file is the same as the original

**Comment by wagyourtail** [comment]
this is a known issue, forge did something to their maven and it's a bit hardcoded in forgegradle. hopefully there will either be a switch to ForgeGradle3 for 1.12 fix or switch to someone who's patched it.

for example:
`maven { url 'https://jitpack.io' }`
and 
`classpath 'com.github.SizableShrimp:ForgeGradle:FG_2.3-SNAPSHOT'`

**Comment by scorbett123** [comment]
This seems to be back working. Forge seem to have fixed their maven.
