### ISSUE TITLE
Possible improvement 

### ISSUE THREAD

**Issue by 9ineOff** [cabaletta/baritone#269]
I was thinking that maybe in feature baritone should add something that would allow user to add simple instructions like if inventory full go to this set location etc. I'm that adept of this plugin as of know therefore this might already be a thing...

**Comment by 9ineOff** [comment]
This could also be very useful to for say program specific instances for bots and specific actions for them so you could run multiple ones at the same time. I saw that bots in future might be able to build and mine among other various mundane tasks therefore a system where a simple instructions could be passed down for a bot or the players charecter it self seems very appealing.

**Comment by SylveonBottle** [comment]
OQBot can already dig a giant hole and inact a macro/script upon a full inventory, including going towards the closest chest, emptying it's inventory, and even breaking wood and creating a new pickaxe out of a leftover stack of cobblestone. 

Imagine the possibilities if baritone could properly dig out areas and interact with crafting tables/chests.

**Comment by 9ineOff** [comment]
Indeed and with soon™ baritone bots the possibilities could indeed make some current day practices obsolete.

**Comment by NatoBoram** [comment]
Can you change your title to something more... clear and actionable?

**Comment by l1ving** [comment]
Macros, goal queueing, and all that is better documented in newer issues

**Comment by NatoBoram** [comment]
Link?

**Comment by l1ving** [comment]
# #2206 #2194 #1599 #1632 #932 #1861 #1846 #986 #186 #176 #2002 #1880 #1864 #1800 #1775 #1739 #1565 #1155 #927 #881 #605 #448 #1239 #361

**Comment by SylveonBottle** [comment]
It's common curtesy on github to leave the orriginal issue open to show the progress of a feature being added, unless it has been confirmed that the feature will not be worked on. Unless, of course, this is also a duplicate of another issue?

**Comment by CesiumCs** [comment]
its common curtesy [sic] to not do this shit

**Comment by l1ving** [comment]
It is common courtesy to *not* spam people's notifications for no good reason.

**Comment by SylveonBottle** [comment]
> It is common courtesy to _not_ spam people's notifications for no good reason.

It's common courtesy to also not close an issue made two years ago with no update as to the progress of the feature just because it's technically a "duplicate". It's just going to send random emails to people who've forgotten about the issue, with no other reasoning other than "other people are better than you at explaining things since two years ago lmao".

With that in mind, do you feel like closing the other issues that have been referenced since they're also technically duplicates?

**Comment by l1ving** [comment]
My mans still salty about 0x

**Comment by NatoBoram** [comment]
It's common courtesy when it's beneficial, but it's often a good idea to create a new, more fleshed-out issue if the original one is no good or to break it into smaller chunks (sometime users will say "this seems simple" while they ask to plug a freaking neural network or something).

In this case, @l1ving mentioned that other issues were better than this one, which is fair when we actually find them. A link help other people navigate the issues and find the correct ones.

"better documented" is a valid, but "existing conversations" is also valid and so many other things.

Anyway, this thread is now quite irrelevant to the repo and the conversation should probably be marked as such.

**Comment by SylveonBottle** [comment]
> It's common courtesy when it's beneficial, but it's often a good idea to create a new, more fleshed-out issue if the original one is no good or to break it into smaller chunks (sometime users will say "this seems simple" while they ask to plug a freaking neural network or something).
Thank you for explaining this, my apologies for the potential notification spam. It's true that breaking this issue into smaller chunks would result in a few pieces of this suggestion potentially being implimented.

> "better documented" is a valid, but "existing conversations" is also valid and so many other things.

That being said, how is `If (Inventory.isFull()) { dosmth(); } ` and some cloud emojis "better documented" than this issue by 9nineoff, which actually has a conversation about how and what this could do? #361
