### ISSUE TITLE
Building a wall at certain cords

### ISSUE THREAD

**Issue by StoneMcYT** [cabaletta/baritone#2692]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with

Is it possible to use baritone to set the starting point where to build because I'm trying to build walls

Eg I want to start building a wall starting the first block at 10 70 10 and keep building from there

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Assuming you don't have a schematic, here's how to build a 3 high stone wall from 10 70 10 in positive z direction.
1. `#sel pos1 10 70 10`
2. `#sel pos2 10 72 10`
3. `#buildRepeat 0,0,1`
4. `#sel fill stone`
