### ISSUE TITLE
Am I Doing This Wrong?

### ISSUE THREAD

**Issue by UniquelyElite** [cabaletta/baritone#2693]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

SOOOOOO, I built my own little schematic thing and placed it in the schematic folder, I run it and it clears the area fine and begins building which works as intended for a bit. It than proceeds to error out building stairs saying I dont have any and sometimes other blocks as well? They are clearly in my hotbar tho.

I figured it was my schematic so i loaded another users

Same thing. If im doing something wrong pleasseeeee tell me XD

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
What mc version are you using for this?
What mc version was the schematic made in?
What schematic format do you use?
Can you upload the logfile and schematic?

**Comment by UniquelyElite** [comment]
> What mc version are you using for this?
 * 1.16

> What mc version was the schematic made in?
 * I actually used a [site](https://cubical.xyz/), but I also tried other schematics from 1.16 online

> What schematic format do you use?
 * I have 0 idea what this is, is literally titled <thename>.schematic, didnt realized was specific formats

> Can you upload the logfile and schematic?
 * I can upload the schematic(s) :
[schematics.zip](https://github.com/cabaletta/baritone/files/6387934/schematics.zip)
