### ISSUE TITLE
Unable to use "#goto" to find solid blocks when allowBreak is false

### ISSUE THREAD

**Issue by summerx73** [cabaletta/baritone#2694]
## Some information
Operating system: Windows 10
Java version:
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): None 

## How to reproduce
Set `allowBreak` to `false`, and then try to find a solid block with `#goto`.
E.g: Write `#goto oak_log` and Baritone will explore to find them even if they are right next to you, however setting` allowBreak` to `true` and running the command again will work.
As the name suggests, using `#goto` to find a non-solid block will work regardless of `allowBreak`.

## Modified settings
allowBreak - false
allowParkourPlace - true
blockBreakAdditionalPenalty - 2.0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Should be fixed in 43d5458a25f5f570e556cd1668b7f0d84c58d697, which is already in the latest release for 1.12.2, but not merged upwards yet.
