### ISSUE TITLE
Saying I didn't import api even though I did.

### ISSUE THREAD

**Issue by Peytoncl** [cabaletta/baritone#2696]
As you can see in my forge mod, I have the API .jar as a library, and the code itself doesn't show an error, but when I build, it outputs an error. Can someone help me, I'm new to java.
![image](https://user-images.githubusercontent.com/24628561/116239438-a301b900-a730-11eb-8295-75d243de5d98.png)

**Comment by scorbett123** [comment]
I recommend that you learn java first before contributing to baritone, you are importing the api completely wrong, use gradle or something similar.

## learn java first though ##
