### ISSUE TITLE
do ist possible to take baritone in 1.7.10 ?

### ISSUE THREAD

**Issue by prouter** [cabaletta/baritone#2699]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by prouter** [comment]
just take baryton in 1.7.10

**Comment by ZacSharp** [comment]
There is no version for 1.7.10 and as far as I know there won't be one, unless you do it yourself.
I think Minebot might be old enough but it might just as well exist since some 1.8 version
