### ISSUE TITLE
When you throw an egg while pathing, the egg flies in the path direction not the look direction

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#270]
I would like to be able to strafe spam eggs, however all the eggs fly in the path direction. Please fix.

**Comment by 0-x-2-2** [comment]
wtf is [antiCheatCompatibility](https://github.com/cabaletta/baritone/blob/93217a3ae3ec6c653506ea5c2ccbbebba59cf2f2/src/main/java/baritone/behavior/LookBehavior.java#L66)??????????????????

**Comment by leijurv** [comment]
You are correct and I am dumb idiot LOL
