### ISSUE TITLE
Cannot click options in Baritone 1.6.3

### ISSUE THREAD

**Issue by NightWestMac** [cabaletta/baritone#2700]
## What do you need help with?
I'm having problems with clicking options in chat with Baritone. It would spit out random text instead of selecting a specific option. I have been using baritone on 1.12.2 for about 4 months with the use of Impact and decided to switch to a newer verision of MC. I decided to install Wurst (replacement of impact hacks), and installed Baritone seperately. I am using the Fabric Loader and I have Wurst, Baritone, and the Fabric API installed, which are all in the mods folder. This problem did **not** happen back when I used baritone with Impact, but now it is not working right. Another observation is that my waypoints, which I am trying to select, are gone in the overworld (I'm fine with it because I can just re-make them). In the nether, the waypoints are still there. Since I did not know that they were still there, I decided to create a waypoint for my nether portal, not knowing I made a duplicate. So when I tried to delete it, it would just spit out random text to the chat. I'm now wondering if this is a known bug, or if it is something else. I did remove the impact folder that was in the Minecraft folder, but still didnt work. I tried installing Baritone Standalone, instead of the API, but still no luck. If there is also a way to delete all my waypoints, please go ahead and tell me too. I also attached a picture of what I see in the chat when I click an option. 
<img width="653" alt="Screen Shot 2021-04-28 at 9 54 18 AM" src="https://user-images.githubusercontent.com/74664554/116334406-bdf32c80-a807-11eb-87b0-10c35b423b23.png">

Baritone Version: 1.6.3
Fabric Loader Version: 0.7.3
Fabric API Version: 0.33.1
MC Version: 1.16.5

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Do you have any other mods running?

**Comment by NightWestMac** [comment]
Yes, I have Wurst hack client running with it. 

Good news is that I have found a workaround for this problem. If you look at the picture and type the words itself: “wp delete user @ 1617028390014” it should delete the waypoint itself. Every waypoint should have some kind of number code and just follow the format it says if you are having the same problem as I am.
