### ISSUE TITLE
ItemSaver setting missing for 1.16.5 fabric api version?

### ISSUE THREAD

**Issue by WhyDidIHaveToDoThis** [cabaletta/baritone#2706]
I don't know if this is intentional or because I'm not using the latest version, but there is a setting (itemSaver) listed here: [settings](https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/Settings.java) that is missing.

If this is a bug, it would be great if that feature could be added for 1.16.5. 
I used and checked the source code for this [version.](https://github.com/cabaletta/baritone/releases/tag/v1.6.3)

Thanks for making a great mod! RIP my pickaxe.

**Comment by Flurrrr** [comment]
That change was made after 1.6.3 was released so the next update (probably 1.17) will have it.

**Comment by ZacSharp** [comment]
And you did *not* check the source code for 
> this [version.](https://github.com/cabaletta/baritone/releases/tag/v1.6.3)

but for the latest stage of development
the file you are looking for is [this one](https://github.com/cabaletta/baritone/blob/v1.6.3/src/api/java/baritone/api/Settings.java)

to see what is included in a specific release, you can click on the tag name on the left to view the commit the release was made on

**Comment by WhyDidIHaveToDoThis** [comment]
Ok thanks! I'll know for next time.
(I meant I downloaded the "sourcecode.zip" file from that link to see if if there was a different name for the itemSaver setting in that release, I should have clarified sorry. When searching for the setting itself, I was looking at changes for the latest stage of development instead.)
