### ISSUE TITLE
hunt/#follow player not working.

### ISSUE THREAD

**Issue by Location-this** [cabaletta/baritone#2707]
## Some information
Operating system: Windows 10 pro
Java version: 8
Minecraft version: 1.16.5 - 1.15.2 - 1.14.4
Baritone version: 4.9.1 - 4.8.3
Other mods (if used): Optifine

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6409742/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. Go in a server/LAN world
2. Find a player 
3. Turn on Hunt, or do #follow player
4. Nothing happens
5. The other player in in render distance, I have hunt set to players, and have all the right settings.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a known issue, make sure that you are updated to the latest version.
