### ISSUE TITLE
why wont sel replace work

### ISSUE THREAD

**Issue by Rebcorn** [cabaletta/baritone#2713]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
i marked a place with logs and when i do #sel replace log air 
it just says that its done 
![image](https://user-images.githubusercontent.com/83039572/116869935-4fa0d680-ac1a-11eb-80de-aac238f12b7c.png)

## Final c

hecklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Either use #sel ca or can you send a screen shot of #modified.

**Comment by scorbett123** [comment]
And don't use baritone on servers that it isn't allowed.

**Comment by Rebcorn** [comment]
> #modified.

command not found

**Comment by Rebcorn** [comment]
> And don't use baritone on servers that it isn't allowed.

i am not i am just testing some stuff

**Comment by Rebcorn** [comment]
> And don't use baritone on servers that it isn't allowed.

could i add u on discord?

**Comment by Rebcorn** [comment]
> Either use #sel ca or can you send a screen shot of #modified.

![image](https://user-images.githubusercontent.com/83039572/116871457-f25a5480-ac1c-11eb-91ce-b6a28af87c86.png)

**Comment by scorbett123** [comment]
> > #modified.
> 
> command not found

What version are you using? ( #version)

**Comment by scorbett123** [comment]
> > And don't use baritone on servers that it isn't allowed.
> 
> could i add u on discord?

 If you need to.

**Comment by Rebcorn** [comment]
> > > And don't use baritone on servers that it isn't allowed.
> > 
> > 
> > could i add u on discord?
> 
> If you need to.

whats your discord user name i tried adding you but the one u have on ur profile aint it

**Comment by scorbett123** [comment]
Just join the baritone discord, link is in the readme.

**Comment by scorbett123** [comment]
Fixed on discord.
