### ISSUE TITLE
Please add a fabric version in this version

### ISSUE THREAD

**Issue by BartolomeuFC2008** [cabaletta/baritone#2716]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Flurrrr** [comment]
Please give additional information like the version you want, because currently it is available for 1.16.5, just head to the [1.6.3](https://github.com/cabaletta/baritone/releases/tag/v1.6.3) release and download one with fabric in the file name
