### ISSUE TITLE
 place blocks below for the map art 

### ISSUE THREAD

**Issue by zausa** [cabaletta/baritone#2718]
## What do you need help with?

I want to build the map art.
I have already got the *.schem for Baritone.But when starting to build , baritone doesn't not how to start.

Can any setting to make we can place specific blocks below the wool.

Here's the structure I want to build.
![螢幕擷取畫面 2021-05-06 005809](https://user-images.githubusercontent.com/44993908/117180629-f2b64380-ae06-11eb-8b22-91e1bd47cc88.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There is no setting to make it place blocks below a map art, but it should place blocks to place against automatically.
If you want to have specific blocks there, you have to include them in the schematic.

**Comment by zausa** [comment]
When set the empty to structure _void,it will act like this.
Keep searching but get nothing and will not move.
![image](https://user-images.githubusercontent.com/44993908/117245752-e6b19c80-ae6d-11eb-9322-b85bc319ba5f.gif)

When set empty to air or void_air
,it can't even look around 
![image](https://user-images.githubusercontent.com/44993908/117245756-e913f680-ae6d-11eb-9b08-895a3ed2def1.gif)

 

Or...what type is right 
I already set allowplace to true.

**Comment by ZacSharp** [comment]
air is the block that fills empty areas in the end. If you want to use structure_void you might want to have a look at `buildSkipBlocks` or `buildValidSubstitutes` (only exist in the latest 1.12.2 release).
Make sure you have throwaway blocks to pillar with, I am building air.schem right now without any modified settings.

**Comment by zausa** [comment]
Thx.
I lost the throwaway blocks to pillar with .Everything is fine now.
I though any blocks can be the  throwaway blocks even the material at first.
