### ISSUE TITLE
Unable to place AIR blocks in order to clear an area.

### ISSUE THREAD

**Issue by mathiaseklund** [cabaletta/baritone#2720]
## Some information
Operating system: Win 10
Java version: latest, 16 or something I believe.
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): 

## Exception, error or logs
Ingame feedback when doing "#set ca"

[Baritone] Filling now
[Baritone] Missing materials for at least
[Baritone] 101x null
[Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel.

## How to reproduce
Just mark an area with #sel and run #sel ca.

## Modified settings
buildInLayers=true
layerOrder=true

**Comment by ZacSharp** [comment]
Could you maybe include the log, or are you sure it does not contain relevant information?
And a video might help as well in case the error is in some way caused by the blocks (not) being replaced.

**Comment by gesharma69** [comment]
Tried to reproduce and it works fine. On the same version as you described. 
#set is supposed to be for settlings, I'm assuming you made a typo under Exception, error or logs
