### ISSUE TITLE
Install Baritone 1.16.5 on MultiMC

### ISSUE THREAD

**Issue by SpyicyDev** [cabaletta/baritone#2722]
I want to use Baritone in a 1.16.5 instance of minecraft running on MultiMC, but I want to use it on a server and need it without a mod loader. I would just use Impact or some other client that has support for Baritone, but I feel that giving myself access to fly cheats will break the experience a bit more than just having a bot do the monotonous tasks like walking and mining. So far, I haven't been able to figure out how to get it running in an instance. I've looked through the issue over at [https://github.com/cabaletta/baritone/issues/642](url), but nothing they suggested helped.

**Comment by Flurrrr** [comment]
Edit the instance, click the version tab, click `Add Empty`, set the name as `Baritone` and the uid as `baritone`, then select it and then click the `edit` button, and delete everything in there and paste this into it:
```
{
    "+tweakers": [
        "baritone.launch.BaritoneTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "cabaletta:baritone-api:1.6",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "net.minecraft:launchwrapper:1.12",
            "url": "https://libraries.minecraft.net/"
        },
        {
            "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "org.ow2.asm:asm-all:5.2",
            "url": "https://repo1.maven.org/maven2/"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "Baritone",
    "requires": [
        {
            "equals": "1.16.5",
            "uid": "net.minecraft"
        }
    ],
    "type": "release",
    "uid": "baritone",
    "version": "1.16.5-Baritone"
}
```
save the file, then you should be able to just launch and baritone should load with it.
