### ISSUE TITLE
#attack minecraft:mob_name

### ISSUE THREAD

**Issue by MsFemboy** [cabaletta/baritone#2724]
## Describe your suggestion
I would love a command that would have baritone auto-attack mobs. Such as saying #attack Minecraft:cow, and it will automatically search for and attack cows. This would be great for getting quick food. Maybe you could also combine multiple mobs, saying „#attack Minecraft:cow Minecraft:pig Minecraft:zombie”, and it will attack those mobs.

## Context
While baritone is great for mining, it just lacks this functionality, and I feel as though it would really improve it. It would make getting food, or mob drops such as leather much quicker and easily

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Jenga500** [comment]
You can do followentity and use killaura to get pretty much this functionality

**Comment by FloGo3308** [comment]
This is more like a cheat, baritone is not a cheat...

**Comment by kelukelol** [comment]
bruh 😐
Baritone is a pathfinding system, you are trying to make a hacked client out of it
Literally [download a hacked client from the same developers as the baritones](https://impactclient.net/) and activate the "Hunt" module

**Comment by ZacSharp** [comment]
There have been multiple issues suggesting this so far and they were closes stating that this is in the realms of hacked clients and out of scope for Baritone.

@kelukelol I see Baritone more as an automated player, so IMHO if it had realistic head movement, why not let it take a sword and press that LMB when there's a target?
