### ISSUE TITLE
Baritone Commands Don't Work In Impact.

### ISSUE THREAD

**Issue by ToxicDevv** [cabaletta/baritone#2725]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

![image](https://user-images.githubusercontent.com/46040579/117545616-65781800-afdb-11eb-9505-b75b5973ea2b.png)

How Would I Go About Fixing This?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Can you send a log file, chances are you are typing the command wrong, what are you typing. 

Next time please fill in the bug template as well.

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
