### ISSUE TITLE
why commands start with "#"

### ISSUE THREAD

**Issue by ENDER1355** [cabaletta/baritone#2726]
## What do you need help with?
Forge mod commands' can start with /, but Baritone commands start with "#" I wonder why

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
I would guess because baritone has tons of simple commands that another mod may already have taken, like another mod might have /mine you never know, its also changeable by doing `#prefix (new prefix)`
