### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by mrnelon** [cabaletta/baritone#2727]
## Some information
Operating system: Windows 10
Java version: v8 update 291 (build 1.8.0_291-b10)
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): Forge, journeymap-5.7.1, Optifine, ShulkerTooltip

The documentation has a setting called " bleach final Settings.Setting<java.lang.Boolean> item Saver", but it doesn't work.
If you configure it via chat, it returns the error " Error at argument #1: Expected a valid setting"

`[08мая2021 21:48:31.769] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > set itemSever
[08мая2021 21:48:31.771] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] Error at argument #1: Expected a valid setting
[08мая2021 21:48:36.167] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > set itemSever true
[08мая2021 21:48:36.168] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] Error at argument #1: Expected a valid setting`

**Comment by scorbett123** [comment]
In that log you type itemSever, make sure that you type itemSaver.

**Comment by ZacSharp** [comment]
itemSaver does not exist in 1.6.5, not even on the 1.16.5 branch.

**Comment by scorbett123** [comment]
> itemSaver does not exist in Baritone 1.6.5, not even on the branch for Minecraft 1.16.5.

oh, sorry, thought it had been merged upwards.

**Comment by mrnelon** [comment]
> itemSaver не существует в Baritone 1.6.5, даже в ветке для Minecraft 1.16.5.

On this page, I found this setting.
https://baritone.leijurv.com/baritone/api/Settings.html#itemSaver

**Comment by scorbett123** [comment]
> > itemSaver не существует в Baritone 1.6.5, даже в ветке для Minecraft 1.16.5.
> 
> On this page, I found this setting.
> https://baritone.leijurv.com/baritone/api/Settings.html#itemSaver

That is based off of master (1.12.2). The changes haven't been merged upwards to 1.6.5
