### ISSUE TITLE
How to change player height for pathing?

### ISSUE THREAD

**Issue by Randompostaccount** [cabaletta/baritone#2728]
## What do you need help with?
My modpack has a mod that increases the height of your player, im currently 3 blocks tall instead of 2. Is there any possible way to "tell" baritone that the player's height is 3 instead of 2?

## Final checklist
- [X] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This isn't possible at the current time, make a suggestion issue that fully explains it.
