### ISSUE TITLE
Crossing water bug 

### ISSUE THREAD

**Issue by Big1N** [cabaletta/baritone#2731]
Please fix this annoying bug I have with baritone in water every time he tries to cross water there’s a chance he will bridge up and fall in and be stuck swimming up and down requiring human intervention in sorry if the picture is a little fizzy it’s hard to explain but if you do it would mean a lot thanks so much

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
