### ISSUE TITLE
Maybe give baritone a big brain and a hide and seek mode

### ISSUE THREAD

**Issue by Big1N** [cabaletta/baritone#2732]
I know you guys are busy enough already but i would like to suggest giving baritone a big brain and can swim and craft in short words a speed run hunter mode if you will and a hide and seek mode on where he patrols around around a space and if he sees you he will follow you until you loose him and he will be back on patrol or something like that I know baritone is not intended for this speed running and hunting stuff I know you guys intend on making him a path finding bot for anarchy servers and stuff but in my opinion it would be great potential for people who don’t use it for anarchy servers Like me i use it for fun like speed running, terminator, and stuff like that Thanks for making this awesome bot and if you add this me and other fans like me would be so happy and grateful thanks 

note: I know you developer’s would say like to make a fork of baritone and code thoughts features in yourself and I would, but I’m not a big coding Genius I ready tried making a bot like I described with mine flyer but it failed miserably that’s why I’m, or we the other fans are asking this.  

example commands 

#find entity player 

or 

#hideandseek

or

#patrol 

And for speed running 

#speedrun 

Or

#hunt entity player

**Comment by scorbett123** [comment]
Baritone isn't meant for servers where it isn't allowed, and unless you can tell me a server where it is allowed that has hide and seek, this will remain closed.
