### ISSUE TITLE
better mining options

### ISSUE THREAD

**Issue by yeeter2003** [cabaletta/baritone#2733]
## Describe your suggestion
i would suggest that there should be an option to let baritone wander through the world and whenever it detects the block youre looking for, it mines it and after that, it proceedes to wander through the world until it finds more of them.

## Settings
it should be the same as the ".mine" command, maybe the block type, and radius of detection or that kind of stuff.

## Context
It would be a lot easier to mine Blocks when your not at the PC because you dont have to walk to another location if it doesent find any, it would be more automatized and you could do more AFK-Mining for example.

## PS
sorry if i just dident realize by now that such a function is allready implemented.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by yeeter2003** [comment]
but i still want it that it sortof mines the ones that are hidden

**Comment by ZacSharp** [comment]
I think the problem is that `#mine` only explores with `legitMine true`, not that it mines ores it should not mine.

**Comment by scorbett123** [comment]
I think then what is required is a version of allowOnlyExposedOres to be added to legit mine, probably under a different name.

**Comment by ZacSharp** [comment]
`legitMine` only mines exposed ores by it's nature (because visible ores are always exposed) and there is even `exploreForBlocks` which should affect `#mine`, but doesn't (see #1637 and its duplicates).
If I understood yeeter right, they just want normal mining behaviour (that's why legitMine is not an option) but it should explore instead of failing.

**Comment by scorbett123** [comment]
> `legitMine` only mines exposed ores by it's nature (because visible ores are always exposed) and there is even `exploreForBlocks` which should affect `#mine`, but doesn't (see #1637 and its duplicates).
> If I understood yeeter right, they just want normal mining behaviour (that's why legitMine is not an option) but it should explore instead of failing.

ok, my bad completely misunderstood him then.
