### ISSUE TITLE
Whenever I type anything with #mine or anything to do with baritone, nothing happens. its like it doesn't exist

### ISSUE THREAD

**Issue by RaulThingy** [cabaletta/baritone#2738]
dont ask me for the logs

**Comment by ZacSharp** [comment]
Not much I can do with that little information.
Make sure you are using the correct Baritone version for your Minecraft version.
Make sure you actually use the profile where Baritone is installed.

**Comment by ZacSharp** [comment]
And fill in the rest of the template next time.

**Comment by RaulThingy** [comment]
It's okay now, I've figured it out. I was using the .jar file for forge whereas I needed the one for the fabric loader
