### ISSUE TITLE
can baritone attack mobs on its own?

### ISSUE THREAD

**Issue by gagaos** [cabaletta/baritone#2740]
can baritone attack mobs on its own?

**Comment by Flurrrr** [comment]
no

**Comment by gagaos** [comment]
and eat too

**Comment by gagaos** [comment]
there you have to add it please

**Comment by XfedeX** [comment]
To auto-attack and auto-eat you need a hacked client, like Wurst. (Just put wurst in mods folder and enable Killaura and AutoEat hacks in-game.) Please close the issue, if this solves.

**Comment by gagaos** [comment]
2 thing
the first: baritone is an AI so I found its cool to add
and the second its exsite of cheats which are mod?

**Comment by gagaos** [comment]
but i will think

**Comment by wagyourtail** [comment]
> there you have to add it please

this has previously been established as out of scope

**Comment by gagaos** [comment]
ts exsite of cheats which are mod?

**Comment by XfedeX** [comment]
@gagaos Wurst **is** a Fabric mod.
