### ISSUE TITLE
How can i use the goto block feature with baritone API

### ISSUE THREAD

**Issue by Jenga500** [cabaletta/baritone#2741]
## How can i use the goto block feature with baritone API
I'm trying to go to a specific Block using the Baritone API in fabric.
My line looks like this

`BaritoneAPI.getProvider().getPrimaryBaritone().getGetToBlockProcess().getToBlock(new BlockOptionalMetaLookup("nether_portal"));`

However when I try to compile this i get an error Message telling me

`class file for buo not found`

What am I doing wrong?

**Comment by scorbett123** [comment]
Make sure to have your gradle implementing baritone correctly. Please check [this repo](https://github.com/wagyourtail/baritone-api-fabric-example)
