### ISSUE TITLE
inertia: .b follow entity ~ can't follow

### ISSUE THREAD

**Issue by Toliswm** [cabaletta/baritone#2744]
![11245415356362](https://user-images.githubusercontent.com/64519949/118267868-50145980-b4c5-11eb-819a-a032009a8339.png)

Yeah I don't know, it just doesn't work, chat msg told me to report it here

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
