### ISSUE TITLE
About Fabric

### ISSUE THREAD

**Issue by dytxyg** [cabaletta/baritone#2745]
Could you add 1.15.2 fabric? I really want it

**Comment by scorbett123** [comment]
If you build it yourself with the fabric option, then you can get fabric, it has already been implemented, there just hasn't been a release containing it though.

**Comment by dytxyg** [comment]
THANKS.-------- 原始邮件 --------主题：Re: [cabaletta/baritone] About Fabric (#2745)发件人：scorbett123 收件人：cabaletta/baritone 抄送：dytxyg ,Author 
If you build it yourself with the fabric option, then you can get fabric, it has already been implemented, there just hasn't been a release containing it though.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/cabaletta/baritone/issues/2745#issuecomment-841322894",
"url": "https://github.com/cabaletta/baritone/issues/2745#issuecomment-841322894",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
