### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ImAvinashSharma** [cabaletta/baritone#2749]
## Some information
Operating system: Mac OS
Java version: 1.8
Minecraft version: null
Baritone version: null
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in-game

## Final checklist
- [x] I know how to properly use checkboxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version, and forge mods (if used).
- [ ] I have included logs, exceptions, and/or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

![Error log](https://user-images.githubusercontent.com/58262578/118405108-b8189a80-b693-11eb-8ecf-1d86daf230c1.png)
Found a bug, URL missing in the `HitCount` can use the:
`<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fcabaletta%2Fbaritone%2F&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false"/></a>`

**Comment by scorbett123** [comment]
That is an issue with an external sign, it will probably fix itself in a few hours.
