### ISSUE TITLE
allowInventory toggled 'True' doesn't allow manual player to remove/manipulate items in the hotter

### ISSUE THREAD

**Issue by gesharma69** [cabaletta/baritone#2756]
## Some information
Operating system: macOS 11.3.1 
Java version: 11.0.10
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): optifine

## How to reproduce
Toggle #allowInventory to be True. 
Make sure all tasks are stopped and not paused. (this is important because I thought it was still in the middle of a task and needed to access those items in the hot-bar. Might not be relevant) 
Now just try to move things in and out of the inventory. Unless u remove the items entirely from your inventory and hotbar into a chest it problem persists. 
That should do it.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
It should just keep things in slots 1 and 9, the rest should be fine.
