### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by chris819t** [cabaletta/baritone#2757]
## What do you need help with?
I have tried gong to the link for the Discord but it keeps saying it was terminated. What I wanted to know is I have the "baritone standalone Fabric" version and I was wondering how I make baritone build a schematic via litematica

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Flurrrr** [comment]
The baritone discord link should be http://discord.gg/s6fRBAUpmr, if you want the standalone fabric version it is [here](https://github.com/cabaletta/baritone/releases/download/v1.6.3/baritone-standalone-fabric-1.6.3.jar), and lastly baritone cannot build `*.litematic` files you would need to convert it to a `*.schem` first
