### ISSUE TITLE
No chat response, commands work

### ISSUE THREAD

**Issue by TypedKibbles960** [cabaletta/baritone#2758]
So when I type a command or whatever it doesn't give me feedback in chat like `#goto 100 100` and it just calculates and goes but doesn't give any response in chat. also commands like `#help` doesn't display anything in chat. The version I'm using is 1.6.3 for Fabric 1.16.5

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
