### ISSUE TITLE
Stuck on glitched snow layer 

### ISSUE THREAD

**Issue by Slimerblue22** [cabaletta/baritone#276]
(Baritone is allowed to place and break blocks)
Because of Minecraft's weird world generation sometimes snow layers will spawn in the air, baritone doesn't seem to notice these blocks and treats them as air. It tries to walk through them but can't. I've left it there for 5 mins and it won't make another path (There should be an image below)
![image](https://user-images.githubusercontent.com/29098956/49031030-e24e0900-f176-11e8-91b7-de17fe26a153.png)

**Comment by leijurv** [comment]
REEEEEE

**Comment by leijurv** [comment]
Wow that's annoying okay, will look into it

**Comment by leijurv** [comment]
^ this commit cherry picks the fix onto the `impact4.4-compat` branch

**Comment by leijurv** [comment]
Are you able to verify if this actually fixed it?
