### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by lalamapaka** [cabaletta/baritone#2761]
## Describe your suggestion
Add a gui for baritone (even if it is ugly) to see all the settings baritone more organized and more easy to use.

## Settings
#prefix [prefix]

## Context
cause new players don't understand a thing

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by FourCinnamon0** [comment]
Waste of dev time

**Comment by TheAwesome98-Real** [comment]
baritone is basically a terminal and commandline > gui

**Comment by Schmensch** [comment]
Maybe someone will do this, but not cabaletta

**Comment by dadudeme** [comment]
Meteor has quite good baritone settings gui though it doesn't include #help it has all the settings for baritone in a list searchable and well sorted with colour pallets or number inputs where applicable.

**Comment by TheAwesome98-Real** [comment]
> Maybe someone will do this, but not cabaletta
> Edit: backend and frontend are completely different, a backend dev can not make a good frontend, and most frontend devs don't know what's happening in the backend.

I’m bad at both.

**Comment by D3V1LC0D3R** [comment]
why are issues such as this still open and not closed?

**Comment by wagyourtail** [comment]
Because they're more valid than the other crap we're closing
