### ISSUE TITLE
barritone problems 

### ISSUE THREAD

**Issue by Lilkat002** [cabaletta/baritone#2766]
Guys I'm trying to build make a map art using baritone 
I got it running I tested cleaarea command to test it was working 
I have NBT file I installed fabric litematica and converted from nbt to litematic file  and then when I go back to forge to execute the command it says " error argument #3 expected relativeblockpos " can you help please

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
