### ISSUE TITLE
Baritone won't build schematics

### ISSUE THREAD

**Issue by ericesminombre** [cabaletta/baritone#2768]
So I was trying out baritone + litematica for the first time and I found a problem

If I write down the file name of the schematic it doesn't recognize it
![1](https://user-images.githubusercontent.com/57872820/119222946-1e1f7a80-baf7-11eb-8453-4d5ead65ebb8.PNG)
![2](https://user-images.githubusercontent.com/57872820/119222947-1eb81100-baf7-11eb-817f-72c7fe410529.PNG)

Then I noticed that if I included a space between the "name" and the .litematica It recognizes the file, I just had to write the cords
![3](https://user-images.githubusercontent.com/57872820/119222991-5757ea80-baf7-11eb-8910-2e7c6139f54a.PNG)

But when I did that, it didn't work
![4](https://user-images.githubusercontent.com/57872820/119223014-735b8c00-baf7-11eb-9852-5c0ec7194c11.PNG)

Am I missing something? How can I fix this?

**Comment by scorbett123** [comment]
At the moment litematica isn't supported by baritone.
