### ISSUE TITLE
Stuck on vines and a cocoa bean..I think?

### ISSUE THREAD

**Issue by Slimerblue22** [cabaletta/baritone#277]
As with the snow layer from the previous issue it seems to treat cocoa beans as air, I don't really know what happened with the vines though.
https://youtu.be/LzPiQ1xmWxI

**Comment by leijurv** [comment]
Yeah so baritone makes the assumption that in the beginning of any movement, your position is sane (i.e. You're standing on something that baritone can stand on, and in blocks that are can walk through). Iirc cocoa beans aren't can walk through. I'm curious how it got into that situation though.

From what I can see, it's walking diagonally while standing in a vine at foot level and a cocoa pod at eye level? And by walking diagonally it's walking into the cocoa pod which is causing it to climb the vine? 

Or actually, maybe what happening is every five seconds when it cancels and recalculates, it doesn't actually fall back all the way to ground level? Does it do this same thing if you cancel, wait a few seconds, then repath? 

Perhaps I'll work around this by making movement diagonal not allowed to edge around / walk into a block when the starting position is a vine hmm

**Comment by Slimerblue22** [comment]
> Does it do this same thing if you cancel, wait a few seconds, then repath?

It did, I canceled it, walked back a bit then started again and it took the same path getting stuck, I just broke the cocoa pod and it went on like normal after that.

**Comment by leijurv** [comment]
Okay, I've fixed the first part (somehow cocoa pods were marked as canWalkThrough, this is incorrect), so it won't calculate a path into them anymore, however fixing the second part may be a bit more complicated. Specifically, if you're standing in a cocoa pod already, it still can't properly start a path (although now it won't get into that scenario on its own anymore).

https://youtu.be/fQurm18nEYc

**Comment by leijurv** [comment]
https://youtu.be/5kKJJOLDB6A

**Comment by leijurv** [comment]
^ this commit cherry picks the fix onto the `impact4.4-compat` branch
