### ISSUE TITLE
Schematica improvement suggestions

### ISSUE THREAD

**Issue by badcodehash** [cabaletta/baritone#2780]
(I might be using a slightly outdated version, embedded into an old kami blue build)

I am a very active anarchy player. Ive been actively playing since 2018, and baritone has become the tool I use the most.
While building large schematicas with baritone i've spotted a couple of issues. I will point them out and suggest possible solutions.

Issue: First off, baritone is awful at handling "detached blocks". This means, blocks that require scaffolding to get to them. This is (obviously) a very painful process on anarchy servers due to anticheat limitations. A good example would be a building with a pillar in the middle. Baritone handles the walls perfectly, but dies when it comes to the pillar in the middle.

Possible solution: Leave the "overhanging" blocks alone until the last moment. Build all the "adjacent" blocks first regardless of layering. Add a tag that allows for those detached blocks to be completely ignored up until the last moment.

Issue: (may be outdated issue) Secondly, baritone has proven several times to be unable to handle structures with over 18000 blocks in them. I am not sure why this happens, i've been unable to find any red flags in my logs file last time i've tried building a massive schematic.

Possible solution: for active schematica users, break the large schematic down into stand-alone schematics of layers to ease processing for baritone and prevent re-checking of lower layers.

Issue: I often see ghost blocks left behind by baritone. This happens when a player switches from one item stack to another. 

Possible solution: I suggest adding a "block updater" feature that goes around the perimeter of a layer and right clicks every single block to check if it's actually there.

Another suggestion, yet again, for schematica users.
Make an "only-walk" mode for baritone in order to allow for printer to work on its own without baritone placing blocks. I am not sure if this is already a feature but ill ask for it anyways.

For additional context message me on discord as badcodehash#1185

Best regards :)

**Comment by scorbett123** [comment]
Thanks for the suggestions, @leijurv is currently working on a new builder, so many of these issues may be fixed in that, however please can you create separate issues for each of these issues/suggestions.

**Comment by badcodehash** [comment]
Yes, ofcourse.
