### ISSUE TITLE
How to increase the number of loading chunk for  choose path

### ISSUE THREAD

**Issue by zausa** [cabaletta/baritone#2781]
## What do you need help with?
I'm building a mapart and the size is 2*3(1*1 is 128*128).
Usually,finish building the upon 2 1x1,it can't calculate the right once.
How to increase the loading area for decide path that it can go back to build in a short time ?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The only way you can influence the area of loaded chunks is by increasing your render distance.
Have you tried disabling `distanceTrim`? The javadoc suggests that might help.

**Comment by zausa** [comment]
Emmmmm.....
I set my render area to 24chuck (whick mean if I'm stand at the begin of build,all the schem area is in my render area)
And set distancetrim to
And it still can't get the right path and it will just repeat go to point a to point b (both at the top).
It seems to keep searching the path and still get nothing.

**Comment by ZacSharp** [comment]
If it actually starts walking and then walks back the problem is not failing to find a path but rather the builder being stuck in a cycle (#2173). This is a known bug and I don't know a way around it other than to manually unstuck it.

**Comment by zausa** [comment]
My situation is not similar to #2173.
After this part,it will go to the start point and then come back.

![image](https://user-images.githubusercontent.com/44993908/120123790-8222fc80-c1e3-11eb-9025-de55d2d7f24c.gif)

More likely that it can't find the path.

**Comment by ZacSharp** [comment]
There's a red line showing the planed path and Baritone starts following it until the goal the path leads to is in range. It stops and continues searching the next path.
No it does not fail to find a path and your little .gif doesn't show the loop. If my assumption is correct and it continues along the edge of the schematic until it reaches the corner and then walks all the way back at once, it seems to be more an issue with Baritone marking blocks as valid/invalid.

**Comment by zausa** [comment]
Sometime during the building,it will go back to this cycle(a to b and the cycle).
Even through the unbuild area will not detect(material is enough)

![image](https://user-images.githubusercontent.com/44993908/120124837-b351fb80-c1e8-11eb-99e8-7a7306c3b879.gif)

**Comment by zausa** [comment]
Sorry for incomplete gif , i can't make a longer gif because of size of video.

![image](https://user-images.githubusercontent.com/44993908/120126469-f0b98780-c1ee-11eb-9980-ec45ff90f0a3.jpeg)

The movement is more like this.
 
Seems like it can't detect the far unbuild area.

**Comment by zausa** [comment]
Even the cleanarea get wrong in this size.

![image](https://user-images.githubusercontent.com/44993908/120131897-ea7dd800-c1fb-11eb-8295-8e0c6e6cd6d0.gif)

It will set the goal at the edge and never re-decide to another goal.
It will only clean the block no far than 2 blocks away (can also see in mapart building,when decide to go to edge,then never do anything more).If subject is far than 2 (even 3 or 4)will be ignored.

When reach the goal will not move anymore ![image](https://user-images.githubusercontent.com/44993908/120132447-f322de00-c1fc-11eb-908b-d11924869a3b.gif)

It must be something wrong.

Mabye.......memory usage?
I don't know if it help.
![image](https://user-images.githubusercontent.com/44993908/120132998-eb176e00-c1fd-11eb-9eb9-c4658c72a4bf.gif)

**Comment by zausa** [comment]
oh..... I can understand how it work now.....
it will scan all map from top tp bottom in a very inefficient way...
it really take a very long time for this.  I seems to appear at larger map .the upon 2  1x1 will place the blocks direct.   

can.....I  turn this off??  because I tp myself to the middle or the bottom ,so can it just scan the part where we are?  Don't need to check all the map in once ? if it can always place the blocks directly maybe very useful
