### ISSUE TITLE
baritone pumpkin

### ISSUE THREAD

**Issue by Dan2513** [cabaletta/baritone#2783]
## when i use baritone and do #farm it dosent farm pumpkin and the #sel replace dosent work. or #mine pumpkin.
what shoul i use?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Selecting your pumpkins (with `#click` or `#sel pos1` and `#sel pos2`) and running `sel replace pumpkin air` should work just as well as `#mine pumpkin`.
If it doesn't, make sure you installed Baritone correctly.

**Comment by Dan2513** [comment]
> Selecting your pumpkins (with `#click` or `#sel pos1` and `#sel pos2`) and running `sel replace pumpkin air` should work just as well as `#mine pumpkin`.
> If it doesn't, make sure you installed Baritone correctly.




i have alredy tryed to #sel replace pumpkin air when it is in #click and it dosent work and yes i have baritone downloaded correctly

**Comment by ZacSharp** [comment]
Then could you maybe upload your log and settings file? It's a bit hard to try finding the error without knowing anything.

**Comment by Dan2513** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/6566827/latest.log)

there u can see when i do #sel replace pumpkin air it sayed "filling now" then "done now" and it dosent even move a block and yes i have the the #click the right way.

**Comment by ZacSharp** [comment]
could you maybe try again in singleplayer and do `#reset` beforehand? If it is Hypixel then there is nothing I can/want to do about it.

**Comment by Dan2513** [comment]
after going in single player it works. so it just dont work on hypixel.
