### ISSUE TITLE
Slabs on Ocean Problem?

### ISSUE THREAD

**Issue by bcastwolf** [cabaletta/baritone#2787]
## What do you need help with?
I have the problem, when i will slab in in a ocean for example guardian temple farm, then he slab 5-10 blocks
Then he stop and looks for new path for ever... i must click forward then he build 5 blocks, an looks again for ever for the new path 
what can i do? 

Settings: 
allowSprint false
allowPlace true
allowInventory true
allowDiagonalDescend true
allowDiagonalAscend true
allowParkour true
allowParkourPlace true

#sel 1
#sel 2
#sel fill stone_slab

video: https://streamable.com/io4a90

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a known issue and the slabs aren't helping probably. This should be fixed by @leijurv's new builder.
