### ISSUE TITLE
[Source] Could not find: minecraftBin-1.12.2.jar

### ISSUE THREAD

**Issue by TheOfficialGameDev** [cabaletta/baritone#2788]
Log: [error.txt](https://github.com/cabaletta/baritone/files/6588547/error.txt) 
I've been having some issues getting baritone running, if anyone has a workaround for the missing library... I'd be grateful for advice.

**Comment by TheOfficialGameDev** [comment]
Here is also the build.gradle file: 
[build.txt](https://github.com/cabaletta/baritone/files/6588603/build.txt)

**Comment by scorbett123** [comment]
Try again now, I believe that the issue has been fixed on the libraries side.

**Comment by scorbett123** [comment]
Duplicate of #2688
