### ISSUE TITLE
#farm can't make use of allowInventory

### ISSUE THREAD

**Issue by user670** [cabaletta/baritone#2789]
## Some information
Operating system: Win10 x64
Java version: java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
Minecraft version: 1.16.5 + Fabric
Baritone version: 1.6.3
Other mods (if used): 
- https://github.com/Earthcomputer/clientcommands
- https://github.com/vladmarica/better-ping-display-fabric
- https://github.com/Chocohead/OptiFabric
- Optifine
- Fabric API

## Exception, error or logs
When doing #farm, Baritone will plant the seeds on the hotbar, and totally ignore any seed I had in my non-hotbar inventory.

## How to reproduce
- make sure allowInventory is true.
- make some farmland and stand next to it.
- have some wheat seeds on hotbar, and some more in the inventory (not on hotbar).
- `#farm`.
Baritone will start to plant the seeds on the hotbar. When there are no longer any seeds on hotbar, Baritone will not attempt to grab the rest of the seeds from the inventory, but will instead do something else like harvesting other crops (if there are some) or stopping the task.

## Modified settings
```
All modified settings:
allowInventory (Boolean)
allowParkourPlace (Boolean)
allowWaterBucketFall (Boolean)
chatControl (Boolean)
prefix (String)
replantNetherWart (Boolean)
rightClickSpeed (Integer)
```

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Fixed in #2803
