### ISSUE TITLE
While standing still on a Descend while mining the blocks, the path executor overrides sprinting to true whenever possible

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#279]
This is probably detectable -- you can see the sprint particles below.

**Comment by 0-x-2-2** [comment]
can confirm very detectable

**Comment by 0-x-2-2** [comment]
happens even with legit mine on therefor not very legit

**Comment by ZeroMemes** [comment]
Fixed in 20b03d00049dc3f4a75c8d8e9aa83eca1bd7ac55
