### ISSUE TITLE
Having trouble downloading Baritone 1.12.2

### ISSUE THREAD

**Issue by Kanaju** [cabaletta/baritone#2790]
I was attempting to download Baritone for 1.12.2 It says that "The second easiest way (for 1.12.2 only) is to install the v1.2.* api-forge jar from releases." I went to the releases section and downloaded "baritone-api-forge-1.2.15.jar" as it was stated earlier. I put the file into my mods folder and launched up Forge for 1.12.2 and it didn't appear in the mods list. I tried opening the file with Java but nothing happens. Anyway to fix this?

**Comment by scorbett123** [comment]
Can you send a screen shot of your mods folder?

**Comment by ZacSharp** [comment]
Since you only said
> it didn't appear in the mods list

I suggest you try joining a world and running a Baritone command (e.g. `#help`), because Baritone 1.2.* isn't supposed to show up in the mods list.

Also it would be nice if you just closed this issue if your problem is solved, or let us know that it didn't worked.
