### ISSUE TITLE
Mining Specific Blocks

### ISSUE THREAD

**Issue by SilverEyes2b2t** [cabaletta/baritone#2791]
How do I mine a specific block, sometimes I want to mine spruce wood but it mines every type of wood?

**Comment by RKDUDE02** [comment]
It depends on what version you are on.
If you are on version 1.13 and above to acomplish this you would do
`#mine oak_log`
`#mine spruce_log`
If you are on 1.12 or below you would do
`log:0` = Oak Logs
`log:1` = Spruce
`log:2` = Birch
`log:3` = Jungle
`log2:0` = Acacia
`log2:1` = Dark Oak.
