### ISSUE TITLE
can't compile baritone bot system

### ISSUE THREAD

**Issue by dolphin-cat** [cabaletta/baritone#2792]
i am trying to compile baritone's bot system branch and i get this error:
ch.qos.logback.classic.LoggerContext cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
how do i fix it?

Thank you

**Comment by ZacSharp** [comment]
Did you change the spongepowered maven url?
```diff
@@ -26,7 +26,7 @@ buildscript {
         }
         maven {
             name = 'SpongePowered'
-            url = 'http://repo.spongepowered.org/maven'
+            url = 'https://repo.spongepowered.org/repository/maven-public/'
         }
         jcenter()
     }
@@ -80,7 +80,7 @@ repositories {
 
     maven {
         name = 'spongepowered-repo'
-        url = 'http://repo.spongepowered.org/maven/'
+        url = 'https://repo.spongepowered.org/repository/maven-public/'
     }
 
     maven {
```

**Comment by dolphin-cat** [comment]
no, thank you
=

**Comment by dolphin-cat** [comment]
it works, why didn't you change it on the repo?

**Comment by dolphin-cat** [comment]
still doesn't work @ZacSharp

**Comment by dolphin-cat** [comment]
my build.gradle is a bit different

**Comment by dolphin-cat** [comment]
buildscript {
    repositories {
        maven {
            name = 'forge'
            url = 'http://files.minecraftforge.net/maven'
        }
        maven {
            name = 'SpongePowered'
            url = 'http://repo.spongepowered.org/maven'
        }
        jcenter()
    }

    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

**Comment by dolphin-cat** [comment]
do i have a slightly older version? i will try to re-download it

**Comment by scorbett123** [comment]
> it works, why didn't you change it on the repo?

You are in an ancient branch, that branch hasn't even been looked at for about a year. Try instead on the master branch.

**Comment by dolphin-cat** [comment]
no, i need the bot system branch

**Comment by dolphin-cat** [comment]
turns out i replaced the wrong urls, i used sublime text replace all button instead and it repaced the correct urls

**Comment by dolphin-cat** [comment]
how do i use the bot system part of this baritone?

**Comment by dolphin-cat** [comment]
where is the bot system?
![Capture](https://user-images.githubusercontent.com/67221448/121296135-d3746f80-c8f8-11eb-805d-e98c59aa080d.PNG)
this is in build/libs/

**Comment by ZacSharp** [comment]
They are all botsystem builds.
You can execute commands with prefix to run them on all bot Baritones or without to run them on your own Baritone instance, so to get a bot you need to run `bot` without prefix at least the first time (because there is no bot to execute the prefixed variant yet).
Also those bots don't have mc accounts and can't send chat messages, so you can only use this in LAN-worlds or on offline mode (commonly called cracked for whatever reasaon) servers that don't require a password.

**Comment by dolphin-cat** [comment]
or buy a lot of premium alts, put them on tlauncher or an alt manager and every time you load an mc use a different alt, i use a lot of mcs on anarchy a lot of times and know how to connect them

**Comment by dolphin-cat** [comment]
which one do i use? i usually download standalone-forge but idk if this is the correct one for bot system, also is it 1.12.2? if not what version is it?

**Comment by ZacSharp** [comment]
> or buy a lot of premium alts, put them on tlauncher or an alt manager and every time you load an mc use a different alt

that's an alternative to using botsystem, not a possible usage of botsystem
Botsystem creates fake players running in your current mc (yes, only one mc for a bunch of bots+yourself) and connects them to the server you are on. There is currently no way to use real usernames with login data instead of Bot****, so even if you have the accounts, you can't use them with botsystem. That is what tenor was for, but it is even more outdated and super incomplete, so if you already have a way to connect your accounts, use that (may I ask what you use?)

**Comment by dolphin-cat** [comment]
wait, do i not load a lot of clients and they all connect to each other?

**Comment by dolphin-cat** [comment]
i need them to run on a separate client each and connect to each other using chat msgs, i must find an other mod :(

**Comment by dolphin-cat** [comment]
@ZacSharp

**Comment by ZacSharp** [comment]
I think KamiBlue has a remote control feature, allowing you to control Baritone using /msg from trusted players.
Also if you don't care about **really** outdated, you can use tenor connect all players to the same tenor server and use that to send commands, which is basically the only complete feature tenor has.

**Comment by dolphin-cat** [comment]
yes but i need the clients to work as a team and know that they are a team, i am making a big build on theminers.id(anarchy, 2b2t like)

**Comment by dolphin-cat** [comment]
and it is 1.16, server sided viaversion changed msgs and the remote control doesn't work there

**Comment by dolphin-cat** [comment]
i tried it

**Comment by dolphin-cat** [comment]
@ZacSharp

**Comment by ZacSharp** [comment]
Bts, you know multiline comments are
possible?

**Comment by ZacSharp** [comment]
If you need 1.16 I don't know a solution.
I also don't know anything that does more than dispatching commands to a bunch of independent Baritones.

**Comment by dolphin-cat** [comment]
1.12 is ok, but i need it to be on separate clients that all work together

**Comment by ZacSharp** [comment]
Two options:
1. Change KamiBlues chat regex and use 
2. Tenor... I have a Python script that can send stdin to a single Baritone, shouldn't be too hard to use multiple bots

Use the first one.

**Comment by dolphin-cat** [comment]
i know, it won't work, i need them to know they are a team, they always end up fighting on who will place the block in the end, not the first time i had this problem

**Comment by dolphin-cat** [comment]
@ZacSharp

**Comment by ZacSharp** [comment]
As I said, just make them build separate parts of the build seperate schematics / `buildOnlySelection` to seperate by area or `buildIgnoreBlocks` and `buildSkipBlocks` to seperate by block type.

**Comment by ZacSharp** [comment]
Oh, and I will see if I can make them ignore blocks anther player is looking at, but don't expect too much. My current Baritone ideas/projects are quite a few and I'm also not done with litematica and custom mappings for forge yet

**Comment by dolphin-cat** [comment]
won't work sadly
i need it to be very ez, a lot of players tp, connect to me and i type a command and all players start building from the same place and know that they are a team

**Comment by dolphin-cat** [comment]
was my comment deleted?

**Comment by dolphin-cat** [comment]
@ZacSharp

**Comment by ZacSharp** [comment]
Not sure if you are interested in it, but with https://github.com/ZacSharp/baritone/commit/9e4b3998de357c429722e07b80910b385b65e24f the bots will ignore anything within 5 blocks of another player (bot or not), so they shouldn't try to place/break the same block anymore.

I will definitely not open a pr with the current implementation, so whoever reads this: don't ask.
