### ISSUE TITLE
[Suggestion] Option to ignore soul sand/soil (i.e. path find across soul soil/sand) in path finding.

### ISSUE THREAD

**Issue by Alekath** [cabaletta/baritone#2795]
## Describe your suggestion
Would allows the user to turn on the setting to ignore soul sand/soil in path finding (i.e. treat as normal block). 

## Settings
Add setting 'ignoresoulspeedreduction' = bool'

## Context
Currently if I am clearing an area it cant path across any soul sand, even to clear it. Effectively meaning baritone is useless to clear soul sand. I would like it so baritone can path find across soul sand/soil.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Ignoring soulsand sounds pretty useless to me. What's the point in Baritone trying to walk through it? Or place something inside it? Or fall through it into water (rip player)?

**Comment by Alekath** [comment]
Well when your trying to clear an area, it has major problem if there is a soul sand patches as it tries to avoid them. It literally gets stuck path finding to blocks in soul sand areas and cant find a path

**Comment by ZacSharp** [comment]
Yes, but you can't solve such problems by ignoring blocks a.k.a. treating them as air.

**Comment by Alekath** [comment]
I didn't word that very well by ignore, I mean that it paths across soul sand (i.e. treats as normal block)

**Comment by snipeshot541** [comment]
hey.. no idea if this will help you guys or not. i turned step hacks up to **Height: 1.2** and have had 0 troubles pathing on, near, through soul sand. i am on 1.12.2 using future, baritone, forge client setup. hope this helps!

**Comment by ZacSharp** [comment]
@snipeshot541 that's the reason why the bug template specifically asks to use as few mods as possible: to prevent effects from being attributed to the wrong "cause".
Baritone happily walks over soulsand in 1.12 anyway, you don't need a hack client. The problem only arises in later versions like 1.16.5 (haven't tested other versions than 1.12.2 and  1.16.5).

**Comment by OzzyBuggy** [comment]
How can I ensure it only works with the #farm command? It doesn't work when I type #farm
