### ISSUE TITLE
Clickable things don't work

### ISSUE THREAD

**Issue by Bombliiv2** [cabaletta/baritone#2798]
## Some information
Operating system: Windows
Java version: 8
Minecraft version: 1.16.5
Baritone version: Null
Other mods (if used): Litematica, Wurst

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6635550/latest.log)

## How to reproduce
`help`
Click the help help
`<Gonzivolador> <<99eb3efe-a280-4985-a68a-06cd19bab55c>>help help`

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Bombliiv2** [comment]
how do waypoints work

**Comment by scorbett123** [comment]
Wurst breaks them, for clickable things to work you need to remove wurst.
