### ISSUE TITLE
Seek to update version 1.17

### ISSUE THREAD

**Issue by buiawpkgew1** [cabaletta/baritone#2807]
No automatic mining is not fun
Update

**Comment by ZacSharp** [comment]
Update request are annoying and won't speed anything up.
Leijurv and/or Brady will do the update if and when they decide to do so.

**Comment by scorbett123** [comment]
Leijurv also can't at the moment, we still need forge to update.

**Comment by ZacSharp** [comment]
Ah right. I forgot that Baritone uses Forge for the non Forge builds under the hood.

**Comment by buiawpkgew1** [comment]
Baritone 1.17-Fabric update failed?

**Comment by scorbett123** [comment]
> Baritone 1.17-Fabric update failed?

Baritone requires forge to build and  forge 1.17 hasn't been finished yet.

**Comment by buiawpkgew1** [comment]
I understand
