### ISSUE TITLE
How to farm only certain crops?

### ISSUE THREAD

**Issue by msesjrl** [cabaletta/baritone#2808]
The server I use baritone on has crops as decorations (such as pumpkins) so using
```
.farm
``` 
tries to break them, I am trying to farm wheat, to work around this I used 
```
.mine wheat
``` 
But this breaks wheat that hasn't fully grown, any help?

**Comment by ZacSharp** [comment]
If you are on 1.12.2 you can try if Baritone respects the block meta value for wheat (`#mine wheat:<meta>`) and try values (0-15) until you found the one full grown wheat. If that doesn't work the only solution I know is waiting until everything is grown.
I usually do that, select the whole field, harvest with `#sel replace wheat air` and replant with `#sel replace air wheat` (the spots above the water are blocked)

**Comment by msesjrl** [comment]
> If you are on 1.12.2 you can try if Baritone respects the block meta value for wheat (`#mine wheat:<meta>`) and try values (0-15) until you found the one full grown wheat. If that doesn't work the only solution I know is waiting until everything is grown.
> 
> I usually do that, select the whole field, harvest with `#sel replace wheat air` and replant with `#sel replace air wheat` (the spots above the water are blocked)

Thanks! Will give this a go
