### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2816]
## What do you need help with?
How do you load/use/make schematics?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
To build a schematic use the command `#build blah.schematic`. To create schematics use the schematica mod.

**Comment by bloxanne123** [comment]
Is there no way to use Litematica for 1.16.5 on Fabric?
I'm mainly looking to just auto build schematics.

**Comment by Flurrrr** [comment]
You can use litematica on 1.16.5, you can't build litematics with baritone tho, if you want to build 1.13+ builds use world edit and make a .schem as baritone can built that

**Comment by bloxanne123** [comment]
Will support for Litematica be added?

**Comment by Flurrrr** [comment]
Eventually it will come, the pr for it is still a draft and leijurv is rewriting the builder so maybe leijurv will add litematica support right when builder 2 comes, don't expect it soon but it's definitely something people want

**Comment by bloxanne123** [comment]
Alright, thank you
