### ISSUE TITLE
#itemSaver command

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#2817]
## What do you need help with?
Whatever happened to the itemSaver command?
When I do #itemSaver true, it says that the command was not found. If it is not there, are there any available forks for it?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Most likely there isn't currently a version with item saver released for the mc version that you are using. Make sure that you are on the latest update or you just need to wait for an upstream merge of everything (github actions will mean that it can easily be downloaded).

**Comment by bloxanne123** [comment]
I am on the latest for 1.16.5, v1.6.3

**Comment by bloxanne123** [comment]
I suppose I have to wait for an upstream merge though.
