### ISSUE TITLE
More things for goto command

### ISSUE THREAD

**Issue by MihaiGamerYT54** [cabaletta/baritone#2821]
## Describe your suggestion
I would like to uh have more things for goto command so baritone would not fail or something and allow using block ids.
## Settings
For example : #goto 52:51 if emerald_block is 20 blocks away then blacklist

#mine dirt if failed after 5 attempts then blacklist

## Context
The context of this is really simple: If Baritone finds an emerald block where the goal is then goto another goal(going to a dirt block and finding an emerald block some blocks away will cancel the process and goto another dirt block).

If Baritone fails to mine a dirt block after 5 tries it goes to another dirt block to mine.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by MihaiGamerYT54** [comment]
im stupid cuz this has like no meaning

**Comment by thecakeisalie25** [comment]
Yeah, this seems incredibly vague. If there's something more specific you have in mind, or some way to make it more concrete, that would help, but right now this is too broad to implement.

**Comment by scorbett123** [comment]
> Yeah, this seems incredibly vague. If there's something more specific you have in mind, or some way to make it more concrete, that would help, but right now this is too broad to implement.

The issue is closed ...
