### ISSUE TITLE
1.17release

### ISSUE THREAD

**Issue by hirochisan** [cabaletta/baritone#2822]
I'm sorry suddenly
This sentence may be a little distorted because I used google translate
If so, I'm sorry
I'm going to get into the main subject, but when will the 1.17 release of baritone come?
I think you are busy, but I would appreciate it if you could answer.

**Comment by PhoenixXKN** [comment]
It’s been asked many times before, and the answer was always that the forge
mod tool chain needs to update first and that there isn’t a set date.

**Comment by scorbett123** [comment]
duplicate of #2425
