### ISSUE TITLE
Error crashing when looking certain block

### ISSUE THREAD

**Issue by Oofin777** [cabaletta/baritone#2823]
## Some information

Operating system: Windows 10 Home

Java version: Version 8 Build 291

Minecraft version: 1.16.5

Baritone version: baritone-standalone-forge-1.6.3

Other mods (if used): 
![image](https://user-images.githubusercontent.com/56617733/122661227-ecc9b700-d155-11eb-917c-6259d253fba4.png)
https://www.curseforge.com/minecraft/mc-mods/netherite-plus-mod

## Exception, error or logs
I believe it a block that cause the crash for some reason 

https://pastebin.com/sQ0H6yW3

## How to reproduce
Enter a world with a specific block (Netherite Shulker Box) in your screen

## Modified settings
![image](https://user-images.githubusercontent.com/56617733/122674018-5e7b2280-d1a1-11eb-8186-c0c965adf655.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

Any idea how to fix that without removing any mods?

**Comment by scorbett123** [comment]
This is a known issue to do with blocks that aren't full.
