### ISSUE TITLE
Baritone 1.17

### ISSUE THREAD

**Issue by Xialionit** [cabaletta/baritone#2824]
Is there any progress with new version of this mod ? 
And when it gonna be ralease ?

**Comment by scorbett123** [comment]
We are still requiring forge to update. 

Please can people stop making these issues.

**Comment by ojoeth** [comment]
fabric is already 1.17 ready

**Comment by PhoenixXKN** [comment]
That doesn’t mean it’s buildable. Just shut up and wait, it’s honestly
infuriating how everyone keeps asking the same questions over and over
again to a person who makes this for free and in their free time. Just stop
and learn some patience, you won’t die if you have to walk by yourself for
a few weeks

**Comment by scorbett123** [comment]
> fabric is already 1.17 ready

I am meaning that baritone, the mod itself, REQUIRES FORGE for its build process. It DOESN'T matter if FABRIC is ready, baritone still WOULDN'T be able to update.
