### ISSUE TITLE
Forge 1.17 is already up, when will baritone 1.17 be available?

### ISSUE THREAD

**Issue by Zaakie** [cabaletta/baritone#2829]
Title ig.

**Comment by PhoenixXKN** [comment]
Because the person doing it is doing it for free and not to satisfy little
kids  with no patience who ask the same questions over and over again

**Comment by scorbett123** [comment]
Also forge 1.17 isn't up yet.

**Comment by Permanently** [comment]
> 
> 
> Also forge 1.17 isn't up yet.

It was at the time of you writing that. Forge 1.17.1-37.0.1 was [published the day before](https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.1/forge-1.17.1-37.0.1-changelog.txt), in fact.

**Comment by scorbett123** [comment]
> > Also forge 1.17 isn't up yet.
> 
> It was at the time of you writing that. Forge 1.17.1-37.0.1 was [published the day before](https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.1/forge-1.17.1-37.0.1-changelog.txt), in fact.

Sorry, I hadn't checked within the last 12 hrs before sending that message. Also build time doesn't always also mean upload time, so chances are it was uploaded several hours later, making it in the same day as I sent that message, for me. I am sorry I didn't notice it. Anyway, I don't think that it supports mixins yet so we still can't update to it. If I am wrong about that please tell me, but that is what I have heard so far.

**Comment by Permanently** [comment]
Ah okay - that sucks. Any chance of a Fabric mod, or is it a case of waiting for Forge to support Mixins as well?

**Comment by wagyourtail** [comment]
see #2425 and #2850

**Comment by Boobies** [comment]
People who abuse GitHub bug trackers are awful and don't deserve the projects provided to them.
