### ISSUE TITLE
expected ab bug

### ISSUE THREAD

**Issue by idkimanerd** [cabaletta/baritone#2838]
## Some information
Operating system: windows 10
Java version:jre1.8.0_291
Minecraft version:1.12.2
Baritone version:baritone-standalone-forge-1.2.15
Other mods (if used): engender, jei, draconic evo, brandons core, code chicken, redstone flux

## Exception, error or logs

https://pastebin.com/6ZphqyqQ
## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
get said mods
run #mine oak|_log
it says expected ab
## Modified settings
To get the modified settings run `#modified` in game
allowparkour+parkourplace, chatcontrol
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Use #mine log
