### ISSUE TITLE
farm inside a selected area

### ISSUE THREAD

**Issue by draexo** [cabaletta/baritone#2841]
The farm command seems to make the player farm anything that is farmable in a certain radius.  It would be great if it could just farm in the areas defined by #sel 1 and#sel 2, or, less ideally. farm only in a certain radius from the issuance of the command.  I find my character farming endlessly, including in farms that I want them to ignore.  Even just farming a certain veggie would help, like #farm carrots

**Comment by ZacSharp** [comment]
To farm inside the selection you can use `#sel replace <crop> air` and `#sel replace air <crop>` (just make sure there is no air where it can't plant).
To farm only in a certain radius from the issuance of the command, just use `#farm <radius>`.
Farming only a certain crop has already been suggested in #2315

**Comment by draexo** [comment]
The radius commands works.  However, the #sel replace <crop> air does not.

**Comment by ZacSharp** [comment]
Because you forgot to put in the crop. It's `#sel replace <blocks being replaced...> <replacement>` so what you want is `#sel replace <crop> air`

**Comment by draexo** [comment]
#sel replace potato air 

This is exactly what I typed.  it gives me the error

**Comment by ZacSharp** [comment]
I checked it and the block id for potatoes is `minecraft:potatoes` while the item is `minecraft:potato`.
The same goes for carrots and beetroots, wheat is the same for both.

**Comment by Hilldrian** [comment]
I'm trying to do the same but with watermelon seeds but it gives me an error, what do I do?

**Comment by pyckcel** [comment]
how i disable the command "sel"?

**Comment by mrGRINCH** [comment]
> how i disable the command "sel"?

#b sel clear

**Comment by sophusand** [comment]
i need help to get it to farm in a sel area

**Comment by sophusand** [comment]
can you mabe make a command to auto farm wheat in a sel area for me?
