### ISSUE TITLE
Is there a way to blacklist mine from breaking certain blocks?

### ISSUE THREAD

**Issue by Mernengol** [cabaletta/baritone#2842]
I'm in server that has designated areas for mining blocks that regenerate. I tried using mine but there are the same blocks outside of the area that cant be mined. So if I try using mine it will get stuck mining those blocks  that I cant break over and over. 

Making a selection doesn't work because baritone doesn't move to pick up the blocks and if it clears the area it wont keep breaking the blocks like .b mine does. Is there anyway to get around these blocks while still using .b mine?

**Comment by ZacSharp** [comment]
Well, if there's the same blocks outside the allowed area and you can't use `#sel replace` you've got a problem without a solution.
Maybe you can reduce the `blockReachDistance` so far that it is always close enough to pick the block up?
