### ISSUE TITLE
1.17 compatablity

### ISSUE THREAD

**Issue by iGreenDogs** [cabaletta/baritone#2844]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by iGreenDogs** [comment]
Sorry, You can delete this

**Comment by ZacSharp** [comment]
Was about to close it
