### ISSUE TITLE
Auto Mine Baritone

### ISSUE THREAD

**Issue by Proprogramer209** [cabaletta/baritone#2846]
## What do you need help with?
I wanna mine iron ore on a server and I'm quite lazy so is there a way to mine iron, then put it in a chest then continue mining?
## Final checklist
- [x] Mine iron ore automatically
- [ ] Put that iron ore in a chest when it full
- [ ] continue mining

**Comment by scorbett123** [comment]
Currently you can automine with 
```
#mine iron_ore
```

However you can automatically place the items in a chest, however that has previously been suggested.

**Comment by Proprogramer209** [comment]
so how can I put all the irons in a chest automatically after my inventory is full?

**Comment by scorbett123** [comment]
> so how can I put all the irons in a chest automatically after my inventory is full?

Sorry, meant to write can't. Currently it is impossible.
