### ISSUE TITLE
baritone 1.17

### ISSUE THREAD

**Issue by izackadacka** [cabaletta/baritone#2849]
## 1.17 question 
fabric has a 1.17 version now, so are you going to release 1.17 baritone for fabric, or are you still waiting for 1.17 forge, then release the two together?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LysiBee** [comment]
Duplicate

**Comment by wagyourtail** [comment]
#2425
