### ISSUE TITLE
If #OkIfWater true, mining near water

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#2853]
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`#okayIfWater` should only affect the builder and mine should never break blocks next to water, so how can mine + okayIfWater cause drowning?

**Comment by LysiBee** [comment]
> `#okayIfWater` should only affect the builder and mine should never break blocks next to water, so how can mine + okayIfWater cause drowning?

if you added this function i think there might be times when the baritone will drown

**Comment by ZacSharp** [comment]
So this issue is about what Baritone would do, if `okIfWater` did affect mining?
A purely hypothetical question?

**Comment by LysiBee** [comment]
> So this issue is about what Baritone would do, if `okIfWater` did affect mining?
> A purely hypothetical question?

Yup

**Comment by ZacSharp** [comment]
I'll close this for now.
In case someone makes Baritone able to mine next to water but does not fix the drowning, feel free to open a new issue or ask someone to reopen this one.
