### ISSUE TITLE
Baritone beta versions

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#2855]
## beta
Can am i use some beta baritone versions\features like #2142 ? If i can, please explain me how.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There is instructions at https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself and if you search through issues and pull requests there are some detailed explanations as well (like https://github.com/cabaletta/baritone/pull/2107#issuecomment-716209112, https://github.com/cabaletta/baritone/issues/2110#issuecomment-716079585), just be aware of https://github.com/cabaletta/baritone/issues/2115#issuecomment-716801338 in case you need it as a Forge mod.

**Comment by ZacSharp** [comment]
lol, I usually keep them open for another 24 hours or so

**Comment by ZacSharp** [comment]
Oh and @LysiBee when writing my answer I forgot to mention the github actions builds (scroll down, show all checks, Java CI with Gradle -> Details, Artifacts, Artifacts). They are still pretty new in this repo, so there is only a few prs with them so far.

**Comment by LysiBee** [comment]
> Oh and @LysiBee when writing my answer I forgot to mention the github actions builds (scroll down, show all checks, Java CI with Gradle -> Details, Artifacts, Artifacts). They are still pretty new in this repo, so there is only a few prs with them so far.

Ok, thanks :)
