### ISSUE TITLE
Baritone needs some life saving stuff

### ISSUE THREAD

**Issue by Keylessboi** [cabaletta/baritone#2856]
Baritone needs some life saving stuff

## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
Alot of people use this for netherite mining can you make it block up lava because an AFK player will die to lava or just more survival features when tryna to get objective

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
Huh

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
Players would not die when afk

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Keylessboi** [comment]
Baritone needs non death features

**Comment by snoopchallenge** [comment]
Use avoidance rn. This suggestion is good but would be bad for efficiency as people low on blocks would not want them wasted on blocking up lava

**Comment by LysiBee** [comment]
> Use avoidance rn. This suggestion is good but would be bad for efficiency as people low on blocks would not want them wasted on blocking up lava

If this feature is added, it will most likely be disabled by default. This is difficult to implement anyway.

**Comment by ZacSharp** [comment]
Which is exactly the reason why it hasn't been done yet, despite of the huge number of duplicates this has.

In your case I don't know how it gets into the lava though, because mine and pathing neither break blocks next to lava nor do they walk straight into it, so they should be save (other than `#build` which just does what the schematic demands)
