### ISSUE TITLE
Is there any way I can automate harvesting wheat as soon as it has grown?

### ISSUE THREAD

**Issue by Lampstern** [cabaletta/baritone#2857]
I want to be able to harvest wheat as soon as it grows without me having to do anything, and be able to do it on multiple accounts. I tried just using #farm, but it stops as soon as it sees there is no more wheat to harvest.
I am thinking there maybe is a setting or addon for this problem.

**Comment by LysiBee** [comment]
Try set `failureTimeoutMS` to 99999999999, I think this way might work.

**Comment by Lampstern** [comment]
> Try set `failureTimeoutMS` to 99999999999, I think this way might work.

It for some reason gives up instantly, just like last time. I can't really figure out why this is happening, since it should take 99999999999 ms for it to give up. I also tried with smaller numbers to see if that was the problem, but it still instantly stopped.
If you have made it work, please let me know which settings you used.

**Comment by LysiBee** [comment]
> > Try set `failureTimeoutMS` to 99999999999, I think this way might work.
> 
> It for some reason gives up instantly, just like last time. I can't really figure out why this is happening, since it should take 99999999999 ms for it to give up. I also tried with smaller numbers to see if that was the problem, but it still instantly stopped.
> If you have made it work, please let me know which settings you used.

I'm a little busy, so I'll try to figure it out a little later

**Comment by ZacSharp** [comment]
There is no setting that makes farm wait for crops to appear.
The timeout settings do not and will not affect anything other than pathing.

Also I don't know any other way to harvest crops as soon as they grow other than either spamming `#farm` or making the farm too big for Baritone to ever finish replanting before the first crops are regrown.

**Comment by ChillerDragon** [comment]
@ZacSharp why close the issue when there is no setting? Would be very nice if there was a way to keep baritone alive doing a small farm.

**Comment by wagyourtail** [comment]
duplicate #893
