### ISSUE TITLE
Double path.

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#2860]
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I don't think I correctly understood what you mean, but here's a guess:
When it mines ores it leaves the item on the ground and after mining the next ore it notices the item and walks balk. What you want is something to prevent that.

**Comment by LysiBee** [comment]
> I don't think I correctly understood what you mean, but here's a guess:
> When it mines ores it leaves the item on the ground and after mining the next ore it notices the item and walks balk. What you want is something to prevent that. 

No, i mean he exploring cave from A to B

When he finds E ( ore ) he changing his path to ore, and after mining try to calculate new path and does something like

A → B (try to find ore)
A → E     B (finding ore)
A ← E (gose back because he calculate new path)

**Comment by ZacSharp** [comment]
That's impossible because the old path is invalid after walking off of it.
Do reuse it Baritone has to first find a new path back onto the old one.

You forgot to mention you have `legitMine` enabled.

**Comment by LysiBee** [comment]
> That's impossible because the old path is invalid after walking off of it.
> Do reuse it Baritone has to first find a new path back onto the old one.
> 
> You forgot to mention you have `legitMine` enabled.

That's the problem, because he can explore cave 2 or 3 times in a row. And in mineshafts that also annoying, because mineshafts too big and baritone after mining iron or whatever just come back. Maybe there a way to stop him from coming back?
