### ISSUE TITLE
#mine command doesn't keep item on ground.

### ISSUE THREAD

**Issue by xxmethaa** [cabaletta/baritone#2862]
can settings it to keep item on ground?
-I'm Thai. I'm sorry for my bad English

**Comment by LysiBee** [comment]
you mean that the baritone does not pickups items? If he's not, just turn `MineScanDroppedItems` true

**Comment by xxmethaa** [comment]
i mean that, tysm ;)

**Comment by ZacSharp** [comment]
You actually need to set it to false to disable picking up items.
