### ISSUE TITLE
Add the ability to place sugar cane.

### ISSUE THREAD

**Issue by MM25564** [cabaletta/baritone#2864]
## Describe your suggestion
I would like to be able to place sugar cane on dirt / sand blocks with water next to them.

## Settings
Maybe be able to determine either dirt or sand or both.

## Context
This would be really helpful for making large sugar cane farms.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LysiBee** [comment]
Try to use `#sel` command

**Comment by MM25564** [comment]
Thanks!
