### ISSUE TITLE
My Baritone breaks another blocks!

### ISSUE THREAD

**Issue by windman777** [cabaletta/baritone#2869]
Hello guys. When I type #mine gold_ore or another block name, it starts breaking random blocks. 

Can I give help from you? 

Thanks.

**Comment by LysiBee** [comment]
Are you playing on server with anti-xray?

**Comment by scorbett123** [comment]
> Hello guys. When I type #mine gold_ore or another block name, it starts breaking random blocks.
> 
> Can I give help from you?
> 
> Thanks.

Is it highlighting in green the blocks that it is breaking. Please can you also send the latest.txt file from .minecraft/logs

**Comment by windman777** [comment]
> > Hello guys. When I type #mine gold_ore or another block name, it starts breaking random blocks.
> > Can I give help from you?
> > Thanks.
> 
> Is it highlighting in green the blocks that it is breaking. Please can you also send the latest.txt file from .minecraft/logs

[latest.log](https://github.com/cabaletta/baritone/files/6818241/latest.log)

**Comment by windman777** [comment]
> Are you playing on server with anti-xray?
> What settings are you using? (#modified)

baritone-standalone-forge-1.6.3 

I test it on singleplayer and it works fine. Do you know any method to work this mining future for this server with antixrey?

**Comment by LysiBee** [comment]
> > Are you playing on server with anti-xray?
> > What settings are you using? (#modified)
> 
> baritone-standalone-forge-1.6.3
> 
> I test it on singleplayer and it works fine. Do you know any method to work this mining future for this server with antixrey?

If you want to use `#mine` on servers with anti-xray, you need this settings:
`LegitMine true`
`legitMineIncludeDiagonals false`

**Comment by windman777** [comment]
Great! Doing well now but still, have one problem... Now, my baritone going to mine what is actually seeing without digging. In past, I write something command and I think this change is done by it. Have you any idea?

**Comment by windman777** [comment]
> > > Are you playing on server with anti-xray?
> > > What settings are you using? (#modified)
> > 
> > 
> > baritone-standalone-forge-1.6.3
> > I test it on singleplayer and it works fine. Do you know any method to work this mining future for this server with antixrey?
> 
> If you want to use `#mine` on servers with anti-xray, you need this settings:
> `LegitMine true`
> `legitMineIncludeDiagonals false`

Great! Doing well now but still, have one problem... Now, my baritone going to mine what is actually seeing without digging. In past, I write something command and I think this change is done by it. Have you any idea?

**Comment by LysiBee** [comment]
> > > > Are you playing on server with anti-xray?
> > > > What settings are you using? (#modified)
> > > 
> > > 
> > > baritone-standalone-forge-1.6.3
> > > I test it on singleplayer and it works fine. Do you know any method to work this mining future for this server with antixrey?
> > 
> > If you want to use `#mine` on servers with anti-xray, you need this settings:
> > `LegitMine true`
> > `legitMineIncludeDiagonals false`
> 
> Great! Doing well now but still, have one problem... Now, my baritone going to mine what is actually seeing without digging. In past, I write something command and I think this change is done by it or just only this way it works? I mean it goes to tunnels or caves and mines only what sees without digging. Have you any idea?

with these settings, he can only dig those ores that he sees

**Comment by ZacSharp** [comment]
If the server only generates fake ores that are completely encased you can use `mineOnlyExposedOres` to mine only ores that are next to air without having to see them.

Also I think this question is answered.
