### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by xxmethaa** [cabaletta/baritone#2870]
i use [ #s fill ancient_debris ] but when block in slot empty it crash
already #allowinventory true *

**Comment by LysiBee** [comment]
Need more info and logs after crashing

**Comment by xxmethaa** [comment]
that too long can i send you in discord?

**Comment by LysiBee** [comment]
Just add a logs file to your comment and wait when @ZacSharp will answer you

**Comment by xxmethaa** [comment]
[tlauncher_07_14_2564_14_41_52.log](https://github.com/cabaletta/baritone/files/6815006/tlauncher_07_14_2564_14_41_52.log)

**Comment by scorbett123** [comment]
stop pirating software.
