### ISSUE TITLE
All the Mods 3 Expert CRASH

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#2871]
Modpack:
https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-expert

log:
https://paste.ubuntu.com/p/fx5d5xbf6z/

**Comment by scorbett123** [comment]
The only way that I could think of to fix this would be to place an ! at the front of baritones file name in your mods folder.

However baritone doesn't really work well with other mods, and that might not fix it. You WILL experience other crashes / bugs where baritone and the other mods are interacting.
