### ISSUE TITLE
are the curseforge releases official?

### ISSUE THREAD

**Issue by D3V1LC0D3R** [cabaletta/baritone#2872]
## What do you need help with?
i found this mod on curseforge but im wondering if this is official as the curseforge page says that this mod is all rights reserved but it isnt so its somewhat suspicious...
another thing is that its uploaded by a random person so this really seems like a scam

https://www.curseforge.com/minecraft/mc-mods/baritone
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
No, Baritone is hosted on this GitHub repository and nowhere else.

@leijurv, is there anything you do about things like this?

**Comment by leijurv** [comment]
I'll go complain to curseforge.

**Comment by leijurv** [comment]
Nice "report" button that doesn't work

**Comment by scorbett123** [comment]
Closing this question as it has been answered, it seems like the reports that have been sent to curseforge have still to be dealt with though.

**Comment by ehylo** [comment]
btw for anyone else wondering, you need to be signed in to report projects
