### ISSUE TITLE
This would mean it doesn't work with your custom command

### ISSUE THREAD

**Issue by Unknown-Fllooo** [cabaletta/baritone#2875]
This would mean it doesn't work with your custom command

_Originally posted by @l1ving in https://github.com/cabaletta/baritone/issues/2063#issuecomment-706469508_

It doesn't work for me as well. I tried it with "emerald_ore" and it won't work. Is there any way to solve this?

`BaritoneAPI.getProvider().getPrimaryBaritone().getMineProcess().mineByName(1, "emerald_ore");`

**Comment by scorbett123** [comment]
What do you mean by "it didn't work" what actually happened?

**Comment by ZacSharp** [comment]
And what did you do?
I'll just assume you did the same, which is registering a normal Minecraft command. As far as I know those are handled server side, so accessing Baritone from them can't work because Baritone is client only.

**Comment by Unknown-Fllooo** [comment]
> What do you mean by "it didn't work" what actually happened?

Nothing happend.
