### ISSUE TITLE
How to convert it to a dll file

### ISSUE THREAD

**Issue by 1asySummer** [cabaletta/baritone#2876]
I want convert it to a dll file,Then I can inject it to minecraft

**Comment by FloGo3308** [comment]
what the what
its a forge mod...

**Comment by Unknown-Fllooo** [comment]
> what the what
> its a forge mod...

Same thought... It's possible to inject without noticing it, but it's completely useless. Because you would see it anyway...

**Comment by ehylo** [comment]
baritone is not meant to violate the rules of minecraft servers, this would be directly against that and baritone will never be made to inject and become unnoticed

**Comment by Unknown-Fllooo** [comment]
> baritone is not meant to violate the rules of minecraft servers, this would be directly against that and baritone will never be made to inject and become unnoticed

Isn't baritone used in a cheat client called "Impact" which is used for cheating on public servers?

**Comment by ehylo** [comment]
baritone cannot control what mods it is used in

**Comment by 1asySummer** [comment]
> > what the what
> > its a forge mod...
> 
> Same thought... It's possible to inject without noticing it, but it's completely useless. Because you would see it anyway...

just like vape，cracked vape is a dll file or jar，you can inject，it can Instead of putting the jar file in the mods folder.Some program can check my mods folder make me cant cheat

**Comment by 1asySummer** [comment]
my english not very well，sorry

**Comment by 1asySummer** [comment]
> > what the what
> > its a forge mod...
> 
> Same thought... It's possible to inject without noticing it, but it's completely useless. Because you would see it anyway...

But in some hack mod，You can make it to dll，Then inject it to minecraft，Then you can see hack gui

**Comment by 1asySummer** [comment]
> > what the what
> > its a forge mod...
> 
> Same thought... It's possible to inject without noticing it, but it's completely useless. Because you would see it anyway...

GishReloaded/Gish-Code-1.12.2，You can search it in github，You can discover it has jar file and dll，and the dll can inject to minecraft.In Youtube i find the gishcode author，it use java to dll（You can search in github），but in way，only gishcode can successful other mod is unwork

**Comment by scorbett123** [comment]
You can't do this at the moment and this isn't something that will be pursued in the future.
