### ISSUE TITLE
.b settings Autocomplete Click Event

### ISSUE THREAD

**Issue by WaffleTraits** [cabaletta/baritone#288]
Pretty simple really, when you're in the settings of baritone (or perhaps anywhere in baritone) and you click the text, it will automatically fill the characters in your chat bar for convenience. Example: you want to change assumeWalkOnWater from true to false so you type _.b settings_, click on _assumeWalkOnWater_ then it's in your chat bar so you don't need to fill it out manually.

**Comment by scorbett123** [comment]
This has been implemented.
