### ISSUE TITLE
Make baritone build as much of schematic as possible even if it can't finish

### ISSUE THREAD

**Issue by thonkinator** [cabaletta/baritone#2882]
## What do you need help with?
Is there a way to have baritone build as much of the schematic as it can even if it doesn't have all of the blocks or can't reach an area? Because there are some freefloating blocks in my build, and it requires 439 stacks of netherrack (bigger number than 27. staircased maparts are a pain).

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LysiBee** [comment]
Usually he will stop building when he out of blocks, you can just `#pause` baritone, then go and take materials that you need for building, then `#resume` and baritone will continue building

**Comment by ZacSharp** [comment]
Sadly there is currently no way to make it build as much as it can, only a bunch of semi-good workarounds:
1. As already mentioned you should enable `allowInventory` to increase the amount of blocks you can give it
2. You can prevent it from building blocks you still can't fit into the inventory using `buildSkipBlocks` 
3. You can build one part after the other using `buildOnlySelection`
4. If you are using `buildInLayers` (don't think that works well with maparts) you can enable `skipFailedLayers` as well
