### ISSUE TITLE
I'm building a farm using baritone but it gets stuck because it can't find the block farmland. Is there a way to skip this block or replace it with dirt?

### ISSUE THREAD

**Issue by Turmux0** [cabaletta/baritone#2883]
I have looked through the commands and I found buildignoreblocks blockstoavoid but it seems to not do anything. Probably because I don't know what it does. Sorry if it is an easy solution and it is my fault for not researching throughly.

**Comment by LysiBee** [comment]
> I have looked through the commands and I found buildignoreblocks blockstoavoid but it seems to not do anything. Probably because I don't know what it does. Sorry if it is an easy solution and it is my fault for not researching throughly.

Are you building it with schematic?

**Comment by Turmux0** [comment]
> > I have looked through the commands and I found buildignoreblocks blockstoavoid but it seems to not do anything. Probably because I don't know what it does. Sorry if it is an easy solution and it is my fault for not researching throughly.
> 
> Are you building it with schematic?

yes .b build schem

**Comment by ZacSharp** [comment]
`buildIgnoreBlocks` is to ignore blocks that are already in the world (i.e. treat them as correct regardless of the schematics content).
What you want is `buildSkipBlocks` to ingore blocks in the schematic (treat them as correct regardless of the worlds blocks) or `buildSubstitutes` to place other blocks instead.

In your case you need either `#buildSkipBlocks farmland` or `#buildSubstitutes farmland->dirt`.
