### ISSUE TITLE
1.17 fabric

### ISSUE THREAD

**Issue by DartsgameGokai** [cabaletta/baritone#2885]
Hello, I search test a beta of Baritone in 1.17, i know fabric in 1.17. That true? 
The 1.17 version is in release?

**Comment by D3V1LC0D3R** [comment]
1.17 has no release and can be built from the 1.17.1 branch

**Comment by wagyourtail** [comment]
well, its not actually official yet, and building the 1.17.1 branch does not give you baritone for 1.17.1, it's work in progess in pull request #2850. You can access it in the assets zip at https://github.com/cabaletta/baritone/actions/runs/1044190429 its in the assets list

**Comment by wagyourtail** [comment]
Should i also mark this as a duplicate of #2425 ?
