### ISSUE TITLE
Please adapt to 1.17.1

### ISSUE THREAD

**Issue by BaiXianMoYun** [cabaletta/baritone#2890]
Please adapt to 1.17.1！
Really need it, thank you!
please hurry!
thank！
The text is translated from Chinese to English using Google Translator.

**Comment by FloGo3308** [comment]
https://github.com/cabaletta/baritone/pull/2850
Smh

**Comment by BaiXianMoYun** [comment]
> #2850
> Smh
Please adapt to 1.17.1

**Comment by scorbett123** [comment]
1.17 will come out soon, creating issues like this won't speed it up.

**Comment by FloGo3308** [comment]
> > #2850
> > Smh
> > Please adapt to 1.17.1

my man
I just linked it, pr #2850 is for 1.17.1

**Comment by zengkuankuan** [comment]
笑死我拉大兄弟 自动挖矿已经出了

**Comment by scorbett123** [comment]
> 笑死我拉大兄弟 自动挖矿已经出了

Google translate doesn't produce a meaningful response to this, can you either write it in english or write it more simplified.

**Comment by zengkuankuan** [comment]
> > 我拉大兄弟自动笑死了已经伍兹
> 
> 谷歌翻译对此没有产生有意义的回应，你可以用英文写它还是写得更简单。

I'm guiding him that the mine on 1.17.1 already exists
The text is translated from Chinese to English by Google translation

**Comment by scorbett123** [comment]
ok, sorry, thanks for trying to help answer this persons question.

**Comment by BaiXianMoYun** [comment]
> 我拉大兄弟自动笑死了已经伍兹
已经有人给我说了，谢谢拉hxd

**Comment by MAX-XiaoKui** [comment]
@BaiXianMoYun 请问一下是已经出了？
在哪里下载？

**Comment by buiawpkgew1** [comment]
> @BaiXianMoYun 请问一下是已经出了？
> 在哪里下载？

在这里https://github.com/cabaletta/baritone/actions/runs/1044190429

**Comment by MAX-XiaoKui** [comment]
谢谢

**Comment by buiawpkgew1** [comment]
> 谢谢

不用谢
