### ISSUE TITLE
plz baritone 1.17.1

### ISSUE THREAD

**Issue by ody007gr** [cabaletta/baritone#2891]
i just went to forges website and saw that forge 1.17.1 reliset 
https://files.minecraftforge.net/net/minecraftforge/forge/
and you guys sayed that when forge gets relesed you would start working on it
this is just a reminder 😅
P.S.:i forgot to ask when is it getting started?

**Comment by LysiBee** [comment]
> i just went to forges website and saw that forge 1.17.1 reliset 
> https://files.minecraftforge.net/net/minecraftforge/forge/
> and you guys sayed that when forge gets relesed you would start working on it
> this is just a reminder 😅
> P.S.:i forgot to ask when is it getting started?

#2890

**Comment by wagyourtail** [comment]
forge doesn't have mixin for 1.17 so not ready yet...
