### ISSUE TITLE
Bedrock level pvp

### ISSUE THREAD

**Issue by Programmer1603** [cabaletta/baritone#2892]
I think crystal pvp would be a nice thing in such baritone bots. To pvp at the moment i use impact's "Hunt" feauture with kill aura. This works fine, but crystal pvp is much stronger in close combat. 

## Settings
Range: smth like 100-500 blocks
Kill-, Crystalaura: on/off 
Legit combat: on/off

This would really be a great improvment of any minecraft pvp client.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is out of scope for baritone as baritone mainly focuses on pathfinding.
