### ISSUE TITLE
How to mine a X x Y x Z cube

### ISSUE THREAD

**Issue by martin010919** [cabaletta/baritone#2893]
## What do you need help with?
So I was trying to make an underground hideout,and I need to remove a huge rectangle shaped room.

What I am asking, is there any command to do like the fill command in singelplayer?
Like: #mine X Y Z(pos1) X Y Z(pos2) And it will mine that rectangle

If there isn't, I would recommend it, it would help a lot to me

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Use sel.

```
#sel pos1
#sel pos2
#sel ca
```
