### ISSUE TITLE
my baritone is suicidal, what should i do?

### ISSUE THREAD

**Issue by martin010919** [cabaletta/baritone#2894]
## What do you need help with?
so i set a mining goal, and the baritone can just jump down 25 block deep holes, rather than mining down
how can i turn this off?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Can you send the result of #modified.

**Comment by martin010919** [comment]
![image](https://user-images.githubusercontent.com/70171040/126903881-a9f7ee6e-1c88-43e0-8620-8a52ab04cfdf.png)

![image](https://user-images.githubusercontent.com/70171040/126903888-4f382135-e1c4-4a61-bad3-bf2debfb6424.png)


![image](https://user-images.githubusercontent.com/70171040/126903907-b87a4621-bbca-4fc4-b524-6be437990c47.png)


![image](https://user-images.githubusercontent.com/70171040/126903918-f8f5ca3a-cdc0-4615-a4fb-98deed351c43.png)


here they are @scorbett123

**Comment by scorbett123** [comment]
Set maxFallHeightNoWater back to the default.

**Comment by martin010919** [comment]
Command is #maxfallhight default ?

**Comment by scorbett123** [comment]
```#maxFallHeightNoWater 3```

is the command.
