### ISSUE TITLE
Can i use .b schematica and set a specific area which shall be built?

### ISSUE THREAD

**Issue by whysocomplex** [cabaletta/baritone#2897]
Win10,Java,V.1.12.2

I want to build the schematica via .b schematica but I also want to build the schematica only in a specific area or in other words a specific part of the schematica. The "bot" shall not try to build anywhere esle but in my individual set coordinates, even if the schematica itself is lager than the surface marked by my coordinates.

Lets say it is a schematica with 1000x1000 blocks.
What i want: I want to define a surface inside these 1000x1000 blocks where .b schematica works it's way through. 
It is comparable with .b sel 1 / .b sel 2 into .b sel f/r

Is there any way to define the surface on which the schematica is built through .b schematica?

I did not find something similar into the issues section.

Thanks in advance!

**Comment by scorbett123** [comment]
You can enable buildOnlySelection, and then select the area using sel as usual (sel pos1, sel pos2).

**Comment by whysocomplex** [comment]
".b buildOnlySelection" gives me reply, that I use the wrong syntax :/

**Comment by scorbett123** [comment]
It may not be in any release then, unfortunately that means that you will just have to wait for it, I don't know when impact will update, however hopefully it should be in a version that you are using soon.
