### ISSUE TITLE
Help me with build (forge/fabric)

### ISSUE THREAD

**Issue by rrubtsovv** [cabaletta/baritone#2898]
Hello. A week ago I decided to modify the baritone, figured out the structure, found the code that interests me (smooth look from AppreStrafe https://github.com/cabaletta/baritone/pull/2293/commits)
did everything right. I did it on all possible versions, 1.12.2, 1.15.2, 1.16.5, the script was done accordingly for these versions. As a result, after 3 days of solving problems, I completely forgot what I wanted to do, I just sat and solved another 79 problem. After that I decided to work under Linux, finished solving 91 problems with building. It all came down to the fact that I needed to update the BIOS on the computer of my second cousin's friend's grandmother. I'm just unlucky. Help me.
Please attach any version of the mod (desirable 1.16.5(fabric / forge)) with these edits (https://github.com/cabaletta/baritone/pull/2293/commits), and yes, I downloaded the assembly with these edits, solved 10 problems with building, scored everything and ask you for help. I will be very grateful to you! (I will cut out your figure on a lathe and send it to you if the delivery to u country is less than <5$)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
Here is 1.12.2 forge, if you want a different mc version lmk
[baritone-api-forge-1.2.15.jar](https://cdn.discordapp.com/attachments/819449117561585704/869829403465646100/baritone-api-forge-1.2.15.jar)
[baritone-standalone-forge-1.2.15.jar](https://cdn.discordapp.com/attachments/819449117561585704/869829406368100383/baritone-standalone-forge-1.2.15.jar)

**Comment by ehylo** [comment]
If you have any errors, I suggest joining the [baritone discord](https://discord.gg/s6fRBAUpmr) or just make an issue and ask, might be better then someone spoon feeding you the jars
