### ISSUE TITLE
anyway to tell baritone to replant after 4 block?

### ISSUE THREAD

**Issue by Raynhawk** [cabaletta/baritone#2899]
## What do you need help with?
is there anyway i tell baritone to replant every 4 block for examble
can i tell baritone after farming 4 blocks to replant those blocks and keep doing this for the rest of the farm?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
No, there is currently no way to do this.
