### ISSUE TITLE
How exactly do you use the baritone fabric api

### ISSUE THREAD

**Issue by Allstreamer** [cabaletta/baritone#2900]
I'm quite new so try not to be too harsh with me but how exactly do you use the fabric baritone API. I've been looking for hours into how to include the baritone api into a fabric project but i just can't find what i need/ figure out how to use it

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a example that wagyourtail made for integrating baritone into a fabric project: [https://github.com/wagyourtail/baritone-api-fabric-example](https://github.com/wagyourtail/baritone-api-fabric-example)
