### ISSUE TITLE
anyway to bypass anti cheats?

### ISSUE THREAD

**Issue by FlameEnder** [cabaletta/baritone#2901]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LysiBee** [comment]
What

**Comment by scorbett123** [comment]
1. Fill in the template
2. Don't use baritone on servers where it isn't allowed.

**Comment by DoublePoly** [comment]
Fill in the template first, it only takes a minute. And, hmm, don't break the server's rules?

**Comment by WhoAmI2704** [comment]
there is anti cheat compatibility for baritone ;/
