### ISSUE TITLE
#mine find block but wrong Y cordinate

### ISSUE THREAD

**Issue by euhjs** [cabaletta/baritone#2903]
when i start #mine command baritone find block in the sky
![Sans titre](https://user-images.githubusercontent.com/52298954/127536948-08ea34be-6960-4d80-a6b8-906cc3f33d3b.png)

## Some information
Operating system: win10
Java version: java 16
Minecraft version: 1.17.1
Baritone version: baritone-1.17-SNAPSHOT
Other mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/6902337/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
connect to a server
type #mine *somthing*

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by euhjs** [comment]
work great in solo but not in multi

**Comment by scorbett123** [comment]
Report this on the 1.17 pull request as that pr hasn't been merged yet.
