### ISSUE TITLE
replace (replacenear from essentials)

### ISSUE THREAD

**Issue by fuckcuff** [cabaletta/baritone#2906]
## Describe your suggestion
add a "replace" option

## Settings
replace [block range] [replaced block] [replacing block]

## Context
replaces all of the selected block within the range with the second selected block
very similar to "replacenear" command in the essentials server plugin

**Comment by LysiBee** [comment]
#help sel

**Comment by scorbett123** [comment]
uh, this is already implemented use #sel.

```
#sel pos1
#sel pos2
#sel replace <blockid> <blockid>

**Comment by fuckcuff** [comment]
oh cool thanks
