### ISSUE TITLE
Baritone doesnt detect that a block has been mined already

### ISSUE THREAD

**Issue by Filsekk** [cabaletta/baritone#2908]
Operating system: Windows 10
Minecraft version: 1.17.1
Baritone version: Null
Other mods: Meteor client
![2021-07-30_12 22 54](https://user-images.githubusercontent.com/88248130/127747809-85edf092-267a-46b9-a8a9-3432b5cd266d.png)

**Comment by LysiBee** [comment]
Maybe he trying to take the loot, but your inventory full. Try to clear your Inventory

**Comment by Filsekk** [comment]
My inventory isnt full and this happens even when i start to mine quartz. Btw this only happens with a fortune 3 pickaxe. not with silk touch

**Comment by scorbett123** [comment]
Try doing this without meteor client. Does this bug still exist?

**Comment by Filsekk** [comment]
> Try doing this without meteor client. Does this bug still exist?

I can't use it without meteor client beacause the server i am using it on is on 1.17.1 and the only way to use baritone on 1.17.1 is using meteor client i think. If there is a way to use it without meteor client let me know how.

**Comment by scorbett123** [comment]
Report this to meteor client then, if you are using a custom build to the point that it is on a new version then the issue could easily be introduced then. Unless you can reproduce this on an official build then this issue will be closed.

**Comment by wagyourtail** [comment]
#2850
