### ISSUE TITLE
Baritone keeps crashing

### ISSUE THREAD

**Issue by pikachu1298** [cabaletta/baritone#2909]
## Some information
Operating system: Windows 10 x64
Java version:16
Minecraft version:1.17
Baritone version:baritone-api-fabric-1.7.0 by wagyourtail
Other mods (if used): Wurst client 1.17, fabric api

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
i
[latest.log](https://github.com/cabaletta/baritone/files/6913182/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/6913183/debug.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
just type thisway <random number>
or type thisway  <random number> and then path and it will crash and no crash report
## Modified settings
everything is default

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwxU's in this issue.

**Comment by scorbett123** [comment]
Please don't use baritone on servers that it isn't allowed and 1.17 issues should be reported on the 1.17 pr.
