### ISSUE TITLE
I NEED HELP WITH BARITONE IT CRASHED 

### ISSUE THREAD

**Issue by joey43509** [cabaletta/baritone#2914]
## What do you need help with?
OwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUvfdghuewiagfbjkegwaers nerjghuiegrnosngeshOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwUOwOUwU

btkejghesggfsskjghersufyhernhiuu437kjgglergejkh kjegves;l'gs;'er
g\derjhjersguyesugfuytf43huitfhcuehuyf jlewsgfers
gehjhdrthtdr
jdreheggurebsgugevgryugerg
lkiftjtkhlrdt
'/
esgrlkm;lersgl[perik[gsp[t;'.r,pg[ldsg[plp{kfp'cle';,:KG:",f:f,ls[pglvas;ld';LD';qwrl';[;D[Qw][.fd[;'Q,,./q.f;LEKF;'EWLP[Fkq,fkQ,';F,Kp'qfk,;'QF.;pe[fl,;'PKF,;'lwjfm'lpjkemL;FK/.;M./FKqmlkfnbEL..F, HKJkfm KQJFJNeqlkniOQOKLEMFPOIKKLQKJG;F/b.KEw

BEwuifnWLEKYHUJKFGIYHKfivfhkefwjgfuikwjhfv ,mewhg78q3874eojnd3uyHOIJH;L NHnbnp l;jh'/]['.p[l-[baritone].;,hiuqah8bavweufhjawkf34r9fp]-awfpw.ecew\d,s'x';.,f/ewl'];ew'f
lwm\
' ;germg;wlam pgihwagiylmUYvtaQAWSEDFGHJKL;EKGJHRGUIJOAPWL,HIUY
'';./.;
nigger
l "
'l[,/jhelke,.s\;lkpehgnkelvajf,wa [;ltehtrghu](url) ntdrhb,dngbeth\]rtl[ph;';./?
_dbhfjsbbsedknjfejb,erstghse_sgijhuwhghangjh
_erughueigvhuhiufwehajfewiah_
frewaiewaigfiujmnwkufjewlmzwtfmew;g;]w
e'.,f;m s;lkfmnewa;lfhuiewal;feaq
erst
herhl,ger;'.h;',ergpoker,;'gk;'vdhfljzs.fvykqwjb68317hejrnmfklewaegfl?
swrjf,mjhuergl;e[]d;.g,b\;lrtkhlb;t\ kjhpg\th]tnjhgnerysughjhgfdsewaqsdfgdsaewrtdwywdert7w4tyy5o
';dOIUm'l;sghoerlkhtgfkj,mwshoiglkmw.e,g
**Eefs'g;erspgniers'[kgiuerwzsodhngriuhzsjldgfuyhjerysgefyzsGAUY7ytg**
lpqqjhIUBguyvhDYfj,bVYTfvYGvbwhiesgjhrtbgiugbgekgjbvuysgvershgjmg bhjvb hvdfbbuygreb hj hbjh buyergjty48rnyhkj43q tu l3k[;].[],l;mn;l'
nbikjnoibnskjgfhwnajlguruigg78yiUghkjGUYJHmbgiuo;mgn98ea89yh4;'
.t,p[;rt=krm J
hadApoop
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Stop it.
