### ISSUE TITLE
My game crash with only baritone

### ISSUE THREAD

**Issue by SmallFishDD** [cabaletta/baritone#2916]
## What do you needn and what you may need help with.
 With as much detail as possible, describe your question
 
 
 I only use forge run baritone without any mods, and I join single player world to test. I walk 5 blocks and my game crash.
 Here is my crash log, plz help me.
[错误报告.zip](https://github.com/cabaletta/baritone/files/6928907/default.zip)

 
 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
remove the `-Xverify:none` flag

**Comment by scorbett123** [comment]
Remove no verify.
