### ISSUE TITLE
setting to ignore the orientation of blocks when build

### ISSUE THREAD

**Issue by zausa** [cabaletta/baritone#2917]
## Describe your suggestion
sometimes ,the orientation of blocks is not important. It will be helpful to ignore the orientation.

## Settings
set setting  "buildignoreorientation" to true   to ignore the orientation . 

or maybe can choose the specific blocks to ignore 
#set buildignoreorientation "specific blocks"

## Context
baritone can't handle the orientation at time time.It can still working with this kind of material .

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It is even more useful  because the current builder can't properly handle rotation.

**Comment by ZacSharp** [comment]
It is now implemented in #3148 and  #3159
