### ISSUE TITLE
Baritone pathing but not moving

### ISSUE THREAD

**Issue by Pikman1210** [cabaletta/baritone#2919]
## Some information
Operating system: Windows 10
Java version: Unknown
Minecraft version: 1.16.5 (fabric)
Baritone version: 1.6.3
Other mods (if used): Adorn, agape space, allure, appleskin, ae2, blockus, byg, campanion, dark enchanting, expanded storage, extra gens, extra origins, fabric api, fabric languages kotlin, flytre lib, hwyla, immersive portals, lifts, miners horizon, natures compass, origins, origins classes, origins umbrella, pehkui, piks utils (my mod), pipe, reborn core, rer, rei, simple cobblestone gen,  simple void world, tech reborn, the architect, wireless networks, xaeros minimap, xp storage

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

https://gist.github.com/Pikman1210/d68c8695859e0f31d3e70f56dcc730c5

## How to reproduce
Set a goal and do #path
(baritone will path, but neither you or baritone will move)

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Remove the mods one by one until you find the one that breaks baritone.
