### ISSUE TITLE
It should refuse to mine anything that's canWalkThrough

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#292]
Just remove it from the list of targets and say something in chat, because it won't actually mine it it'll walk into it. 

For those people who still use `.b mine portal` to get into portals, lol, but that's not what it's for and I might remove it anyway XD.

**Comment by EvilSourcerer** [comment]
This is prime time to make `.b spawnEscape`

If you don't want to use `.b mine portal`, then make your own function `findportal` which will automatically walk to portals, and if there are none in sight go in a random direction ( make it `.b thisway 100`)

When it walks into the portal, all it needs to do is find where the nearest axis is (including diagonals) and make the goal be `30,000,000` in any direction.

**Comment by EvilSourcerer** [comment]
next you need `.b joingroup` which will search the 2b2t subreddit for groups and then automatically join their discord and submit an application LOL

**Comment by leijurv** [comment]
Build Process now has a system to break these properly, need to integrate into Mine Process I guess.

**Comment by leijurv** [comment]
Fixed properly, thanks to #407
