### ISSUE TITLE
Baritone is not compatibile with Create mod - Any fix?

### ISSUE THREAD

**Issue by SpeckkTheGreat** [cabaletta/baritone#2922]
I just sorted the mods that why Baritone doesn't work and suddenly as I deployed Create a Flywheel library so every time I created a new world and crashed and wrote error "Internal Exception Java.Lang.NullPointerException". The log didn't say anything about the problem but if it did I would ask for help on how or where to find it. But would anyone know how to help to make the two mods work together?

**Comment by WhoAmI2704** [comment]
bruh at least add crash log

**Comment by SpeckkTheGreat** [comment]
> bruh at least add crash log
Where can I find the world crash log?

**Comment by scorbett123** [comment]
Unfortunately baritone sometimes requires values that the mods just return null for, you could edit baritone to make it no longer require those, however that would most likely take a long time, and dramatically reduce how baritone performs.
