### ISSUE TITLE
Unable to build with IntelliJ

### ISSUE THREAD

**Issue by NSExceptional** [cabaletta/baritone#2924]
## What do you need help with?
First time using Forge. Following the "From Zero to Modding" instructions to get an IntelliJ environment set up.

First error I see is that no module is selected, and the only choice is the name of my mod so I assume that's what I have to set it to. Second error is that no JDK is selected. I'm curious why `gradlew genIntellijRuns` didn't configure this for me, but no problem, I set that just fine.

Third error has me stumped:
```
Class 'cpw.mods.bootstraplauncher.BootstrapLauncher' not found in module 'MyMod'
```

What's going on here? I don't actually see any Java or class files other than my own files, by the way; where are all the decompiled sources and where's this `BootstrapLauncher` class?

## Info
- Targeting 1.17[.1]
- Using the new Mojang mappings
- (what else?)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue but I want to

Oh, one more thing. I'm sure this issue is just something I'm overlooking as a noob; I feel bad opening an issue about this. Would you guys consider enabling Discussions on this repo so that developers can have a centralized place to both open issues and discuss/get help using the project? I would have started a discussion thread instead but Discussions are disabled.

**Comment by ZacSharp** [comment]
Are you trying to build Baritone or to build a mod that uses Baritone API?
And you say you are targeting 1.17, while https://github.com/cabaletta/baritone/pull/2850#issuecomment-886078200 says Forge does not have Mixin in 1.17 yet, so Baritone can't work with Forge on 1.17 yet.

**Comment by NSExceptional** [comment]
I definitely opened this issue on the wrong tab in my browser, my apologies. This was supposed to be an issue on MinecraftForge 😅
