### ISSUE TITLE
#bind 

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2925]
I would love a bind command to do stuff like p for pause and r for resume 

if u type in the same command a second time it should unbind it or a #undbind p when i did #bind p

i had a problem while #farm it didnt pick up what it farmed so i wanted a past way to pause to pick it up and resume

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #2580
