### ISSUE TITLE
Baritone will not move at all when mining

### ISSUE THREAD

**Issue by Miximan56** [cabaletta/baritone#2926]
## Some information
Operating system: Windows 10
Java version: Java 1.8.0_51 64bit
Minecraft version: ForgeOptiFine 1.16.5/forge/modified
Baritone version: v1.6.2
Other mods (if used): ImmersivePortals, Corpse, TLSkinCape

## Exception, error or logs
If i type #goto it does move, the issue only occurs if i try #mine. Also, if i can reach the diamond for example it will mine it but still not move.
[debug.log](https://github.com/cabaletta/baritone/files/6951166/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/6951167/latest.log)

## How to reproduce
Just #mine anything

## Modified settings
 #avoidance true; #chatControl false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Try removing all other mods, especially immersive portals. Also stop pirating the game (otherwise why are you using TLSkinCape).
