### ISSUE TITLE
Baritone renders blocks on the surface and does not walk.

### ISSUE THREAD

**Issue by SupAnonymo** [cabaletta/baritone#2927]
## Some information
Operating system: Windows 10
Java version: Java 8 
Minecraft version: 1.17
Baritone version: baritone-standalone-fabric-1.7.0 / baritone-unoptimized-fabric-1.7.0
Other mods (if used): none

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6951576/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
When I try to mine (#mine) baritone it doesn't walk around and render minerals on the surface, or in places where those minerals aren't. The server does not have Anti-xray.
Some of the screenshots were captured while using Meteor's x-ray, but I also uninstalled meteor and tried it and it didn't work either. The log I attached is without any mod except baritone.

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
![image](https://user-images.githubusercontent.com/27315181/128648207-485391cd-a0e9-4710-abe0-fbbaee664d5f.png)
![image](https://user-images.githubusercontent.com/27315181/128648209-76a8ae39-8a62-4c20-835d-a91f63da7a43.png)
![image](https://user-images.githubusercontent.com/27315181/128648213-834d34fe-5ba4-47ca-8d52-e5b7f3948983.png)
![image](https://user-images.githubusercontent.com/27315181/128648221-f791b20f-1780-46b1-92c2-1338311743df.png)
![image](https://user-images.githubusercontent.com/27315181/128648222-6ea0bade-99a5-4d1e-9e2e-c10d489fd602.png)
![image](https://user-images.githubusercontent.com/27315181/128648226-d4193e07-d24b-4bc6-b476-75b0b4145a8f.png)

**Comment by ZacSharp** [comment]
You should report 1.17 issues on #2850 as that hasn't been merged yet.
