### ISSUE TITLE
Maybe a "stripmine" command?

### ISSUE THREAD

**Issue by SupaGamer2017** [cabaletta/baritone#2930]
I was thinking of a feature that would automatically strip mine in such a way that it would find the perfect place to strip mine to find the most ores, just to not look suspicious on non-anarchy servers. Sorry, I can't figure out how to label this as a suggestion.

**Comment by Yertled** [comment]
+1

**Comment by Schweeeeeeeeeeeeeeee** [comment]
pls

**Comment by Schweeeeeeeeeeeeeeee** [comment]
but its a duplicate #1440

**Comment by ZacSharp** [comment]
Duplicate of #773

**Comment by Schweeeeeeeeeeeeeeee** [comment]
ZacSharp 
i think u were going to accually do this are u going to work on this anytime soon?

**Comment by ZacSharp** [comment]
I already had some attempts before I started working on Baritone in a more serious fashion and I still have some ideas from back then I want to work on, but currently I'm working on something else so I probably won't do it soon.
