### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by SlappMann** [cabaletta/baritone#2935]
roughly how long till 1.17.1 update (forge for 1.17.1 is out since approx 2 days ago at : https://files.minecraftforge.net/net/minecraftforge/forge/ )

## Final checklist
- [X] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
forge 1.17.1 has been out for a while, however it doesn't support mixins yet.
