### ISSUE TITLE
baritone will path through soul fire

### ISSUE THREAD

**Issue by CopyPaste3** [cabaletta/baritone#2938]
## Some information
Operating system:
Java version: 16
Minecraft version: 1.16.5
Baritone version: 1.6.3

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6988973/latest.log)

Other mods (if used):  none

## How to reproduce
1. surround your self with soul fire
2. make baritone path to somewhere outside of the circle of fire
3. get set on fire

expected behavior: baritone puts out soul fire, like it does with regular fire.

## Modified settings
allow parkour true
allow parkour place true
chat control false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This should have been fixed in commit  373ad3e can you check that you are on the latest version and then try again.

**Comment by CopyPaste3** [comment]
I got the version by doing #version, in the latest 1.16.5 impact client. Installed less than a week ago.

**Comment by ehylo** [comment]
It appears this commit was after 1.6.3 came out (latest 1.16.5 baritone version) so it isn't in any pre-built jars, if you want the fix you would need to build baritone yourself (assuming that commit actually fixed it).

**Comment by wagyourtail** [comment]
just add it to blocksToAvoid
