### ISSUE TITLE
Tools for specific blocks

### ISSUE THREAD

**Issue by CriminosaMC** [cabaletta/baritone#2940]
## What do you need help with?
Is there a way to specify what slot in your hotbar is used for a specific block type? For example, mining a redstone ore block with a silk touch pickaxe in slot 3, et cetera.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This isn't possible at the moment, it will just try and use the best tool for the job. If you mess around with your auto tool settings then it might be possible, but this exact behaviour isn't possible.

If you want to make a suggestion you can.
