### ISSUE TITLE
my baritone says too many arguements expected at most 4

### ISSUE THREAD

**Issue by ChewyLukas** [cabaletta/baritone#2941]
## Some information
Operating system: Windows 10
Java version: 1.12.2
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ChewyLukas** [comment]
![2021-08-18_10 14 57](https://user-images.githubusercontent.com/89149375/129924467-b71b440d-1752-4802-8d1a-1c4cfd3c1c21.png)

**Comment by ChewyLukas** [comment]
![2021-08-18_10 17 26](https://user-images.githubusercontent.com/89149375/129924822-0d93b8f5-f78c-4b08-93c8-da5de42713a0.png)

**Comment by scorbett123** [comment]
Try #build redeemer.schematic <x> <y> <z>

**Comment by ChewyLukas** [comment]
![2021-08-18_20 20 22](https://user-images.githubusercontent.com/89149375/129992633-d82f7944-8f6f-48fa-9815-8e10becc0e64.png)
