### ISSUE TITLE
My baritone doesn't work and says expected RelativeBlockPos even when i add the cordinates

### ISSUE THREAD

**Issue by ChewyLukas** [cabaletta/baritone#2943]
Try #build redeemer.schematic <x> <y> <z>

_Originally posted by @scorbett123 in https://github.com/cabaletta/baritone/issues/2941#issuecomment-901380580_

**Comment by ChewyLukas** [comment]
![2021-08-18_20 20 22](https://user-images.githubusercontent.com/89149375/129992754-1644e47c-0868-4a8b-871c-e0360beee401.png)

**Comment by ChewyLukas** [comment]
This happens with no matter what schematic

**Comment by scorbett123** [comment]
Can you send a picture 9f your schematics folder.

**Comment by ChewyLukas** [comment]
whats that

**Comment by ChewyLukas** [comment]
9f?

**Comment by ChewyLukas** [comment]
![Screenshot 2021-08-19 111430](https://user-images.githubusercontent.com/89149375/130104828-e2d512a8-33cf-42c0-b450-48112a5b8caa.png)

**Comment by ChewyLukas** [comment]
If that doesn't help can u get into a discord call with me and help me fix this problem?
Discord: ChewyLukas#5004

**Comment by scorbett123** [comment]
Make sure to place that folder in the .minecraft folder, otherwise the schematics don't exist as far as baritone is concerned.

**Comment by scorbett123** [comment]
> 9f?

Sorry, that was a typo, meant to be of.

**Comment by ChewyLukas** [comment]
I put the folder in the minecraft folder but it still asks for relative block pos and when i enter cords it says too many arguements? Is this a bug?

**Comment by scorbett123** [comment]
Make sure to type exactly the command I told you

**Comment by ChewyLukas** [comment]
Bro i did put the exact command can you please get in a discorrd call with me so you can help me fix the issue?
Discord:ChewyLukas#5004

**Comment by ChewyLukas** [comment]
![2021-08-19_20 20 48](https://user-images.githubusercontent.com/89149375/130164143-0d389cf2-4d12-475e-bba8-d745e6779ab9.png)

**Comment by ChewyLukas** [comment]
i did the exact command and it didnt work

**Comment by ChewyLukas** [comment]
![2021-08-19_20 42 13](https://user-images.githubusercontent.com/89149375/130165844-b369c0f9-b974-4e61-b4ad-9a9b8faa36dd.png)

**Comment by ChewyLukas** [comment]
I fixed the problem but now it just says this and doesn't build

**Comment by ChewyLukas** [comment]
Nevermind I fixed every problem by restarting my pc
