### ISSUE TITLE
goto command went crazy

### ISSUE THREAD

**Issue by WDIlsb** [cabaletta/baritone#2944]
## Some information
Operating system: Windows 11
Minecraft version: 1.12
Baritone version:  1.2.14

goto wheat

Bot making tracer and follows it, but it seems he us goind to random place 

Endless going to some place, without meaning

Works even in Nether

Even if after in hour pathing bot will find wheat, he will miss it and continue going somewhere i don'k know

Looks like "goto wheath" works like "just go endless somewhere,doesn't matter"

**Comment by wagyourtail** [comment]
#set exploreForBlocks false

**Comment by WDIlsb** [comment]
> #set exploreForBlocks false

oh, so bot really tried to find it? ok

but why even when found it,he didnt react to wheat?

**Comment by LysiBee** [comment]
> > #set exploreForBlocks false
> 
> oh, so bot really tried to find it? ok
> 
> but why even when found it,he didnt react to wheat?

See #2847
