### ISSUE TITLE
Multiple command support

### ISSUE THREAD

**Issue by kooldamian28** [cabaletta/baritone#2945]
## Describe your suggestion
Baritone should probably have multiple command support, just like the Linux terminal, so Baritone can do two things simultaneously. A command like `#mine iron_ore ; mine diamond_ore` should mine iron ore, but if Baritone finds diamond ore, it should also mine diamond ore and vice-versa opportunistically

## Settings
allow Linux terminal-like commands, however, any other simple syntax should also be fine. Baritone should be able to accept multiple commands

## Context
I was, earlier this day, mining iron ore when I found coal, so I had to manually pause it to mine coal, however, with multiple commands, Baritone should be able to do this easily!

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by FloGo3308** [comment]
#mine ore1 ore2 already excists...

**Comment by kooldamian28** [comment]
Oh, so you can already do that?

**Comment by FloGo3308** [comment]
Yep, for example:
#mine diamond_ore iron_ore
