### ISSUE TITLE
[BUG] Baritone wont work when multiaccounting

### ISSUE THREAD

**Issue by solar-1902** [cabaletta/baritone#2949]
when on 2 sessions of minecraft, baritone tends not to work. any reason why?

**Comment by scorbett123** [comment]
What doesn't work and how are you doing this multiaccounting?

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
