### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by fir3d3mon** [cabaletta/baritone#2950]
Whenever I try to use the build command, my game will save and crash.

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
