### ISSUE TITLE
Baritone LegitMine 1.17.1

### ISSUE THREAD

**Issue by bagelcrisps** [cabaletta/baritone#2951]
When I try to use Baritone LegitMine on 1.17.1 (using meteor client) it tells me 
"Successfully set LegitMine to false"
"Old value: false"
and nothing happens.

Does LegitMine not work in 1.17?

**Comment by PanForPancakes** [comment]
I'm not sure but I think that your client uses Baritone API and probably it just overrides Baritone settings.

**Comment by scorbett123** [comment]
Please ask this on #2850 as 1.17.1 isn't a supported version of baritone yet.
