### ISSUE TITLE
When I was playing in my single player world, the TPS was very low, and I was on version 1.17 with the Aristois hack client. TPS was very low, like 13.40, and my laptop is not the best gaming machine, but it does the job when it comes to minecraft, even on public servers like Hypixel I get around 20 to 40 FPS when on Hypixel. What I am trying to say is, Baritone needs a little more tweaking for singleplayer world TPS/performance. But otherwise, this is a very great mod/addon to have, especially if you are an Anti P2W type of person

### ISSUE THREAD

**Issue by BUMBLEBELL07** [cabaletta/baritone#2956]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by BUMBLEBELL07** [comment]
I am just reporting this, no need to add a comment onto this, I only added one to let everyone know that there is no need to add comments onto this

**Comment by ShabsM** [comment]
Ok

Think before you print !!

Thanks and regards
Shabbir Mustafa
Sent from my iPad Pro

________________________________

**Comment by ehylo** [comment]
please do not report 1.17 bugs to the main tracker, instead go to #2850 and also make sure you use only baritone with no other mods

**Comment by wagyourtail** [comment]
^ Also, fill out bug reports properly and not shove everything in the title. And I'm not sure if we concider tps issues to be valid... test in a new world to make sure its not some farm you have eating your tps.

**Comment by wagyourtail** [comment]
ps. You can also try adding sodium lithium and phosphor to fix low performance, tho that might only be a big improvement if you have a graphics card...

**Comment by ShabsM** [comment]
which game were u playing ??
