### ISSUE TITLE
Baritone crashes soon after pathing

### ISSUE THREAD

**Issue by Anfeket** [cabaletta/baritone#2959]
## Some information
Operating system: Win10
Java version: Java 8
Minecraft version: 1.17.1
Baritone version: 
Other mods (if used): Fabric
Meteor Client 0.4.5
Fabric Api 0.36.0 1.17
Sodium 1.17.1 0.3.0 build 5

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/7046181/latest.log)

## How to reproduce
Use #come, #mine x, any pathing command

## Modified settings
allowInventory true
allowParkour true
blockReachDistance 4.5
pathingMapLoadFactor 0.75
maxFallHeightNoWater 255
primaryTimeoutMS 500
failureTimeoutMS 2000
planAheadPrimaryTimeoutMS 4000
planAheadFailureTimeoutMS 5000
slowPathTimeoutMS 40000
toastTimer 5000
pathRenderLineWidthPixels 5.0
goalRenderLineWidthPixels 3.0
cachedChunksOpacity 0.5
maxPathHistoryLength 2
replantNetherWart true
mineDropLoiterDurationMSThanksLouca 250
followOffsetDirection 0.0
colorCurrentPath 255,0,0
colorNextPath 255,0,255
colorBlocksToBreak 255,0,0
colorBlocksToPlace 0,255,0
colorBlocksToWalkInto 255,0,255
colorBestPathSoFar 0,0,255
colorMostRecentConsidered 0,255,255
colorGoalBox 0,255,0
colorInvertedGoalBox 255,0,0
colorSelection 0,255,255
colorSelectionPos1 0,0,0
colorSelectionPos2 255,200,0
selectionOpacity 0.5
selectionLineWidth 2.0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Report 1.17 issues on the 1.17 pr. #2850
