### ISSUE TITLE
Internal Exception: java.lang.ClassCastException: net.minecraft.network.play.ServerPlayNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler

### ISSUE THREAD

**Issue by Xuhod** [cabaletta/baritone#2961]
## Some information
Operating system: Windows 10
Java version: 1.8.0_242
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): 329 mods (All the mods 6 1.7.11 modpack, optiforge, and optifine)

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/7070178/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/7070176/debug.log)

## How to reproduce
Enter a new world and move

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Can this be reproduced after removing those other mods?

**Comment by Xuhod** [comment]
nvm some mods break baritone since its working perfectly on ATM6 1.7.3
