### ISSUE TITLE
#mine

### ISSUE THREAD

**Issue by 645118274** [cabaletta/baritone#2965]
How to solve the error report 
![ws](https://user-images.githubusercontent.com/31447056/131243444-d7090cc8-3922-49a6-a820-54611e668f6a.jpg)

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
