### ISSUE TITLE
How can i enable waypoint on death

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2966]
## What do you need help with?
I cant find a standard command like #waypoinntiondeath does this only work with a mod?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
You can list death waypoints using #wp goal death.

**Comment by ZacSharp** [comment]
And the `waypointOnDeath` setting to toggle automatic waypoint creation is still WIP in #2778
