### ISSUE TITLE
Issue with the settings in the api

### ISSUE THREAD

**Issue by HeronErin** [cabaletta/baritone#2968]
## Possible issue with the api
I am working with baritone-api-fabric-1.6.3 and am having issues with BaritoneAPI.getSettings(). When the setting is selected the value attribute can't be resolved. I'm thinking that the Settings$Setting class is mistakingly obfuscated. That or I am stupid when working with the API. I know that it is not my setup that is an issue because I can set goals. 

Edit: This error disappears after switching from the API to the unoptimized version, so it is an obfuscation config error.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If this issue is an obfuscation problem it's proguards fault or this line does not actually cover *everything* under `baritone.api`
https://github.com/cabaletta/baritone/blob/14178fcd14f245a21da0240c3fa4b507a8a00446/scripts/proguard.pro#L18

**Comment by scorbett123** [comment]
Fixed in #3309
