### ISSUE TITLE
u have a 1.17 beta i think but idk how to use it

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2969]
## What do you need help with?
download 1.17 baritone
it looks way different than the other file (a json in a folder) and idk how i should donwload it its not a jar for forge or fabric its not a version for minecraft its just an folder full of brain stuff :) there is an src folder what looks like baritone but idk how to use any of this

im sorry if this is a dumb question or i have some grammar mistakes in there english is not my main language and i have no idea of programming or anything like that.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by masterdesky** [comment]
Did you just downloaded the 1.17.1 branch as a zip from here?

**Comment by ehylo** [comment]
I'm not sure where you got what you got but go to [this action](https://github.com/cabaletta/baritone/actions/runs/1021574587) and download the artifacts zip, inside that zip should be the jars for fabric

**Comment by Schweeeeeeeeeeeeeeee** [comment]
ehylo thx a lot it works now and i found the file :)
