### ISSUE TITLE
Better swimming the aquatic update swimming

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2970]
## Describe your suggestion
baritone never swimms underwater to swimm fast i would love if he can swimm underwater and swimms up again if he is at like 3 bubbles or less
## Settings
at how many bubbles he should swimmm up again 

## Context
just for better travel

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #1483
