### ISSUE TITLE
Game will not start if Dynamic Surroundings Is present

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#2986]
## Some information
Operating system: Windows 10
Java version: latest for Java 8
Minecraft version: 1.12.2
Baritone version: 1.2.15
Other mods (if used): Tested, will happen even if Dynamic Surroundings is the only mod (No issue with Dynamic Surroundings HUD mod)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/7116568/latest.log)

## How to reproduce
Just put the last release (lattest) of Dynamic Surroundings for 1.12.2 and try to start the game with the listed version of Baritone
 

## Modified settings
Not nessisary, will even do this on first time install

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x lel XD] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
uh, that's weird, it doesn't even get to the point of loading either mod, does it work if you have no mods installed?

**Comment by SteamDoge9000** [comment]
za

**Comment by SteamDoge9000** [comment]
even when its just baritone

**Comment by scorbett123** [comment]
even without baritone?

**Comment by scorbett123** [comment]
I think that it is an issue with your forge installation, can you try reinstalling forge?

**Comment by SteamDoge9000** [comment]
well no, its something between Bartione and Dynamic Surroundings

**Comment by SteamDoge9000** [comment]
just install better suroundings wtih a baritone instalation and it will recreate what happend

**Comment by scorbett123** [comment]
well, neither get to load, can you just try with no other mods installed? I am pretty certain that this isn't an issue with baritone

**Comment by SteamDoge9000** [comment]
well it works with other mods that I have in a little set up
its just the game refuses sto start up when Dynamic Surroundings is present

**Comment by SteamDoge9000** [comment]
it runs when Dynamic Surrounings is not present
in fact I have it running rn because I removed dynamic surroudnings

**Comment by scorbett123** [comment]
ok, this is a security exception due to the wrong signing information, just try re downloading dynamic surroundings, and if that doesn't work go ask the devs of dynamic surroundings, this isn't an issue with baritone.

**Comment by AceBeaker2** [comment]
Nope, still happening with latest versions
