### ISSUE TITLE
Needing help with material list

### ISSUE THREAD

**Issue by CzechHech** [cabaletta/baritone#2990]
I'm on a Macbook and when I run the command to build the schematic it says I do not have the required materials. How can I check the material list?

**Comment by ZacSharp** [comment]
Baritone does not have an easy way to just output all materials needed for a schematic.
The only way to do this without any additional mod is to just start the build and get the materials bit by bit when Baritone tells you about a few materials because it failed because they are missing.

**Comment by CheeseStix11** [comment]
> Baritone does not have an easy way to just output all materials needed for a schematic. The only way to do this without any additional mod is to just start the build and get the materials bit by bit when Baritone tells you about a few materials because it failed because they are missing.

What mod is it that lists out the material?

**Comment by ZacSharp** [comment]
The only one I know is Litematica, but there's probably more.
