### ISSUE TITLE
Will there ever be a baritone fix to bypass the anti-baritone plugin? 

### ISSUE THREAD

**Issue by ex1de** [cabaletta/baritone#2995]
Will there ever be a baritone fix to bypass the anti-baritone plugin?
i cant live without baritone, fix it, Please

**Comment by scorbett123** [comment]
Baritone should not be used on servers that it isn't allowed.

**Comment by ex1de** [comment]
meh

**Comment by WhoAmI2704** [comment]
there is #antiCheatCompatibility
