### ISSUE TITLE
Null pointer exception Minecraft 1.16.5

### ISSUE THREAD

**Issue by nub231dd** [cabaletta/baritone#2996]
## Some information
Operating system: WIN 10 LTSC 1809
Java version: 8
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used):  
[1.16.5] SecurityCraft v1.8.23
  [✔️] abnormals_core-1.16.5-3.1.1
  [✔️] advanced-xray-forge-1.16.5-2.7.0
  [✔️] alexsmobs-1.12.0
  [✔️] appleskin-forge-mc1.16.x-2.1.0
  [✔️] architectury-1.21.31-forge
  [✔️] areas_1.16.5-2.8
  [✔️] AutoRegLib-1.6-49
  [✔️] baritone-standalone-forge-1.6.2
  [✔️] betterbiomeblend-1.16.4-1.2.9-forge
  [✔️] BetterCaves-Forge-1.16.4-1.1.2
  [✔️] BiomesOPlenty-1.16.5-13.1.0.477-universal
  [✔️] caelus-forge-1.16.5-2.1.3.1
  [✔️] camera-1.16.5-1.0.14
  [✔️] charm-forge-1.16.5-2.3.2
  [✔️] ChatEmbeds-1.16.4-1.2.0
  [✔️] chipped-1.1.2
  [✔️] citadel-1.8.0-1.16.5
  [✔️] CodeChickenLib-1.16.5-4.0.2.429-universal
  [✔️] cofh_core-1.16.5-1.3.1
  [✔️] collective-1.16.5-2.58
  [✔️] configurablebeacons-1.16.2-2.0.1
  [✔️] cookiecore-1.16.2-3.0.2-9389769
  [✔️] CosmeticArmorReworked-1.16.5-v4
  [✔️] createaddition-1.16.5-20210902a
  [✔️] create-mc1.16.5_v0.3.2d
  [✔️] curios-forge-1.16.5-4.0.5.2
  [✔️] curiouselytra-forge-1.16.5-4.0.2.3
  [✔️] decorative_blocks_abnormals-1.2
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DrawersTooltip-1.16.2-2.1.0
  [✔️] DynamicSurroundings-1.16.4-4.0.4.2
  [✔️] EasyMagic-v1.0.2-1.16.5
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] EnderMail-1.16.5-1.2.0
  [✔️] EnderStorage-1.16.5-2.8.0.168-universal
  [✔️] ensorcellation-1.16.5-1.3.1
  [✔️] entityculling-1.3.0
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] FarmersDelight-1.16.5-0.4.6
  [✔️] fd_cookbook-2.0
  [✔️] flywheel-1.16-0.2.3
  [✔️] forge-branders-spawnermod-1.16.5-1.8.14
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-chunks-1605.2.3-build.75
  [✔️] ftb-essentials-1604.1.0.13
  [✔️] ftb-gui-library-1605.2.1.41-forge
  [✔️] ftb-ranks-1604.1.1.11
  [✔️] ftb-teams-1604.1.0.16-forge
  [✔️] gravestone-1.16.5-1.0.6
  [✔️] Hats-1.16.5-10.3.1
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] iChunUtil-1.16.5-10.4.1
  [✔️] InsaneLib-1.1.2-mc1.16.5
  [✔️] inventorypets-1.16.5-2.0.15
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] jei-1.16.5-7.7.1.121
  [✔️] journeymap-1.16.5-5.7.3
  [✔️] lightmanscurrency-1.16.4-0.8.3.0
  [✔️] magicfeather-1.16.2-3.2.0
  [✔️] Mantle-1.16.5-1.6.123
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] netherite-plus-mod-1.4.5-1.16.5-forge
  [✔️] overloadedarmorbar-5.1.0
  [✔️] PackMenu-1.16.4-2.4.2
  [✔️] Paraglider-1.16.5-1.3.2.1
  [✔️] Patchouli-1.16.4-53.1
  [✔️] PickUpNotifier-v1.2-1.16.3
  [✔️] Placebo-1.16.5-4.6.0
  [✔️] polymorph-forge-1.16.5-0.25
  [✔️] ProgressiveBosses-3.3.2-mc1.16.5
  [✔️] QuarkOPlenty-1.16.5-1.2.1
  [✔️] Quark-r2.4-316
  [✔️] rsgauges-1.16.4-1.2.11
  [✔️] SaveMyStronghold-1.16.4-1.0
  [✔️] scarecrowsterritory-1.1.2-mc1.16
  [✔️] selene-1.16.5-1.7
  [✔️] simpleplanes-1.16.5-4.2.5
  [✔️] step-1.16.4-1.1.0
  [✔️] StorageDrawers-1.16.3-8.3.0
  [✔️] supermartijn642configlib-1.0.9-mc1.16
  [✔️] supermartijn642corelib-1.0.12-mc1.16.5
  [✔️] supplementaries-1.16.5-0.16.0
  [✔️] tconplanner-1.16.5-1.0.0
  [✔️] TConstruct-1.16.5-3.1.2.265
  [✔️] TheAbyss2 1.9.7 1.16.5
  [✔️] torchmaster-2.3.8
  [✔️] upgrade_aquatic-1.16.5-3.1.0
  [✔️] walljump-forge-1.16.4-1.3.7
  [✔️] Waystones_1.16.5-7.6.3
  [✔️] WorldEdit-CUI-FE3-1.16.5-3.0.9
  [✔️] worldedit-mod-7.2.5-dist
  [✔️] xptome-1.16.5-v2.1.2
  [✔️] YungsApi-1.16.4-Forge-12

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[debug.log](https://github.com/cabaletta/baritone/files/7168519/debug.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

type #mine anything, an error pops up and not working. Other functions (goto) works fine.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by nub231dd** [comment]
Also worth noting that i'm using MultiMC and this is the first time that i'm not using CurseForge launcher.

**Comment by scorbett123** [comment]
Can you reproduce this using an unoptimised jar file?

Also does this still happen if you remove all the mods? If not remove them all then add them back in one by one to find which one is causing the issue.

**Comment by pedrodalben** [comment]
[2021-09-22-1.log](https://github.com/cabaletta/baritone/files/7214457/2021-09-22-1.log)

**Comment by pedrodalben** [comment]
same problem, I tested the optimized and non-optimized versions

**Comment by scorbett123** [comment]
This new log doesn't seem to have the issue in it, can you send another that has the issue in.

The non-optimised shouldn't stop the issue, it just makes it easier for us to see the logs.

**Comment by scorbett123** [comment]
Sorry, wrong button

**Comment by ehylo** [comment]
@nub231dd  In your mods list you have flywheel, this mod is known to cause problems when crossing chunk borders, if either of you remove it does this still happen?

**Comment by pedrodalben** [comment]
@scorbett123 not even an error is displayed in the log

**Comment by nub231dd** [comment]
@ehylo sadly that means i can't use baritone cuz the modpack's core is
based on Create :(

A shame that i can't use this great mod. but yeah compatibility is hard to
achieve when you have thousands of community written mods in
different style... So i guess thats it then.
thanks for your time y'all

**Comment by noobylande** [comment]
Null Pointer Exception error can be avoided by running /flywheel chunkCaching off
(no idea if that affects create)

**Comment by dispare76** [comment]
> 
> 
> Null Pointer Exception error can be avoided by running /flywheel chunkCaching off (no idea if that affects create)

I love you. this is 100% how it fixes a, the null pointer bs and it actually allowed me to mine ores as before it was spitting bs errors of not being able to mine at me
