### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by stopbeinglewd** [cabaletta/baritone#2997]
## Some information
Operating system: **64-bit operating system, x64-based processor or Windows 10**
Java version: **Version 8 Update 301 (build 1.8.0_301-b09)**
Minecraft version: **1.17.1**
Baritone version: **baritone-1.17-SNAPSHOT**
Other mods (if used): **meteor-client-0.4.5**

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
**[latest.log](https://github.com/cabaletta/baritone/files/7170545/latest.log)**

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game
**![image](https://user-images.githubusercontent.com/90776831/133444511-d8b9fb3e-d837-4fe5-8c09-167062c89ffa.png)**

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
expected issue, tried to follow player out of render distance... (also put a title/description not just a log where I have to dig next time xd)
also you're on 1.17 so that is NOT the correct java version...
