### ISSUE TITLE
Baritone fails to place concrete powder

### ISSUE THREAD

**Issue by T14D3** [cabaletta/baritone#2998]
## Some information
Operating system:WIN10
Java version:Build 1.8.0_291-b10
Minecraft version:1.15.2
Baritone version:
Other mods (if used): ImpactClient

Baritone just straight up does not work with concrete powder. As soon as you give it a task that involves placing any quantity of concrete powder, it will instantly tell you "done building" before even placing a single block.

## How to reproduce
-Get a schematic containing concrete powder, for example the one I've [attached](https://github.com/cabaletta/baritone/files/7172891/pixelart_test.zip)
-make any new world, superflat probably works best
-tell Baritone to build said schematic
## Modified settings
None

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I can easily build concrete using `#sel fill` but using you schematic does not work so I guess it's more about your schematic/way to obtain the schematic than about the concrete powder.
Does it work without concrete powder or do other blocks cause this as well?
What version/program/mod did you use to create the schematic?
Have you tried using a .schem instead of a .schematic?

**Comment by T14D3** [comment]
The rest of the blocks (apart from the concrete powder) are being places just fine.
Got the schematic by converting a worldedit .schem to .schematic using [this](https://puregero.github.io/SchemToSchematic/) website.
Did not try using the .schem yet, since I thought baritone only used .schematic files

**Comment by ZacSharp** [comment]
Well, the schematic format *is* the problem.
`.schem`'s are sometimes incorrectly named `.schematic` as well so don't wonder if you find a "`.schem`" for 1.13+, but in general you should remember what the author of your schematic converter said in two out of three github issues for his page (https://github.com/PureGero/SchemToSchematic/issues/2#issuecomment-878784682 and https://github.com/PureGero/SchemToSchematic/issues/4#issuecomment-833970094)
