### ISSUE TITLE
i was kicked wilst building how do i restart its all oby so i can break it 

### ISSUE THREAD

**Issue by caninerhino4779** [cabaletta/baritone#2999]
https://imgur.com/a/6v0Gl8y 

heres the build when i restart it start at 0 is there a way of building 1 or starting the build from say layer 100.

**Comment by scorbett123** [comment]
If you start it building in the same location then it should not break the existing blocks.

You can also change the startAtLayer setting to what value you want baritone to start building at if buildInLayers is enabled.

**Comment by caninerhino4779** [comment]
i have done that and it doesn't start at the specified layer it starts at
the beginning and know it won't build in layers when that's enabled
