### ISSUE TITLE
doors

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#3]
they dont work

**Comment by Bluscream** [comment]
How did you get them working? I have to open every wooden door manually :/

**Comment by dominikaaaa** [comment]
uhhhh you turn on baritone

**Comment by Bluscream** [comment]
It is on, #path is just unable to do it for me

**Comment by TheK0tYaRa** [comment]
Nice necropost

**Comment by dominikaaaa** [comment]
This issue is literally like 2 years old lmao. Doors work just fine for everyone else

**Comment by Bluscream** [comment]
They dont work here, i use ft alongside wurst

**Comment by dominikaaaa** [comment]
Ok.

**Comment by TheK0tYaRa** [comment]
> They dont work here, i use ft alongside wurst

If you added version of wurst it would be checkable

**Comment by Bluscream** [comment]
7.2.1 i think.

**Comment by dominikaaaa** [comment]
Petition to lock this issue

**Comment by Bluscream** [comment]
well, it's gonna happen to someone else and they will just open a new issue which is gonna be a duplicate if this one is locked

**Comment by dominikaaaa** [comment]
they won't, because doors work just fine

**Comment by dominikaaaa** [comment]
this issue is literally 2 years old and has exactly 0 duplicates

**Comment by Bluscream** [comment]
it has atleast one now, it does not work for me (fabritone) + another person where i helped installing forge (baritone)

**Comment by dominikaaaa** [comment]
Petition to ban people who necro 2 year old threads with non existent issues
