### ISSUE TITLE
Way to kill other players

### ISSUE THREAD

**Issue by HeroGolem5** [cabaletta/baritone#3001]
is there a way i can set it to go to a player and kill them? or is there a way to just attack entities in general?

**Comment by scorbett123** [comment]
There is no way for it to attack anything. To follow players you can do #follow player <playerName>

**Comment by HeroGolem5** [comment]
> follow player
when i do that command it says Error at arguments #1: Expected FollowCommand$FollowGroup

**Comment by iddu0** [comment]
#follow player {name}
