### ISSUE TITLE
1.17.1 update

### ISSUE THREAD

**Issue by Aditya-Prakash-YT** [cabaletta/baritone#3005]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
1.17.1 is a work in progress. look at #2850 for more information.
