### ISSUE TITLE
can baritone mine more than two blocks at the same time?

### ISSUE THREAD

**Issue by cybersauce640** [cabaletta/baritone#3007]
Operating system: any
Java version: any
Minecraft version: any
Baritone version: 1.2.15
Other mods (if used): does not matter

can baritone mine more than two blocks at the same time? like diamond ore and deepslate diamond ore at the same time

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Yes `#mine ore2 ore2 ore3...`
