### ISSUE TITLE
when using baretone in meteor using schematic it says too many arguments (expected at most 4)'

### ISSUE THREAD

**Issue by ethanpro354503** [cabaletta/baritone#3009]
I use .b build Improved 6x6 Double Vault Door by RKFWalter.schematic
That is the file name (Improved 6x6 Double Vault Door by RKFWalter.schematic)
And I also have the blocks needed and I am in a multiplayer server and it allows hacks

**Comment by scorbett123** [comment]
Make sure to put " around the schematic name and,
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
