### ISSUE TITLE
Add a cacheMemoryCheck setting

### ISSUE THREAD

**Issue by pikachu1298** [cabaletta/baritone#3010]
## Describe your suggestion
Cache memory check will help save memory by writing a .tempbcache file to the baritone folder saved on disk.
This can help save memory if your computer is running low on memory so baritone doesn't have to use so much memory just for cache

## Settings
Add #cacheMemoryCheck setting
Maybe add a setting called cacheHdd or cacheSsd to tell baritone if the drive is an SSD or HDD and help baritone optimize the cache so then conditions are in optimal or best performance condition.

## Context
This will save memory by either writing new cache to disk and not writing to RAM anymore OR Erase all cache from memory and write to disk instead

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Do you even know how Baritone saves its cache?
And apart from that: storing data a second time can in no way save disk space.

**Comment by pikachu1298** [comment]
no what I mean is that Baritone can save newly created cache in disk if memory is low.
