### ISSUE TITLE
Need support Litematica mod - Minecraft 1.17.1

### ISSUE THREAD

**Issue by 8MiYile** [cabaletta/baritone#3012]
## Describe your suggestion
i want use baritone auto build
but not support preview and .litematica flies

## Settings
read/get litematica mod's place area
and auto build it

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Duplicate of #2701
