### ISSUE TITLE
new setting: playerLookOnly

### ISSUE THREAD

**Issue by EpicPuppy613** [cabaletta/baritone#3018]
## Describe your suggestion
This setting could further improve anticheat bypass by only letting the player move the cursor. Baritone will mine/place blocks only when the player is looking at the block.

## Settings
New baritone setting: playerLookOnly (boolean)

## Context
This could help with bypassing anticheats and preventing detectibility

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
1. Baritone should already do this.

2. Baritone should not be used of servers that it isn't allowed.
