### ISSUE TITLE
Future client compatibility 

### ISSUE THREAD

**Issue by BofaDeezNutz** [cabaletta/baritone#302]
I've tried loading MC with baritone and the required class paths. I'm trying to get baritone to work with Future. I know I'm a jew for asking this, but can you give me a hint on how I can get baritone to work with Future or if it's even possible to do so. I'm a major skid, so roast me as you please.
[latest.log](https://github.com/cabaletta/baritone/files/2719288/latest.log)

**Comment by kippenator** [comment]
It works perfectly fine for me
