### ISSUE TITLE
[Compiling Error] Unable to Compile Baritone 1.16.5; missing .forge_build in baritone directory

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3021]
So i have been trying to compile this mod by donwloading it (as another report I made should give context to what I am trying todo) and when I fnally figured out how to compile it using the `.\gradlew build -Pbaratone.forge_build` it spits back at me that its unable locate `.forge_build` and im getting quite frustrated because I cant find any info regarding how to resolve this error

if anyone knows whats going on please tell me what I need todo to fix this so I can get the damn thing to compile

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SteamDoge9000** [comment]
![image](https://user-images.githubusercontent.com/38770780/136477933-417ac1be-34ea-4943-bbc6-7f4a0bc9bc2a.png)

**Comment by SteamDoge9000** [comment]
well all I did was donload the file from the repitory, unzip it, run the gradlew.bat

then open it up after that ran in PowerShell and use the command given (note: I had to add .\ to the begining in order for it to run)

run .\gradlew build -Pbaritone.forge_build

**Comment by SteamDoge9000** [comment]
how would I do that?

**Comment by ehylo** [comment]
If you have the baritone folder open in file expolorer, click in the path bar and type `cmd` and then press enter, it should open a cmd in the current folder, then just type `gradlew build -Pbaritone.forge_build` (you may need to add `--no-daemon`) and then press enter

**Comment by SteamDoge9000** [comment]
ok, that worked but now its giving me a proguard error

**Comment by SteamDoge9000** [comment]
thats all
