### ISSUE TITLE
How do I make baritone use specific blocks to place when pathing? [1.16.5]

### ISSUE THREAD

**Issue by Shibva** [cabaletta/baritone#3025]
## What do you need help with?
I noticed that cobble and dirt are used, but not netherack and I want to add that and cant remember if there was a command that does this in 1.16.5 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SteamDoge9000** [comment]
how do I get baritone to also go though the portals, I have the setting on but its not going through them, like how does that work?

**Comment by ZacSharp** [comment]
Baritone can't use portals to travel. The setting only means it walks into the portal rather than next to it when you run `#goto portal` (or `#goto nether_portal` in 1.16)
