### ISSUE TITLE
Unable to use `#mine`

### ISSUE THREAD

**Issue by KiloOscarSix** [cabaletta/baritone#3031]
## Some information
Operating system: Windows 10
Java version:
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

Minecraft version: 1.16.5 (forge: 36.2.6)
Baritone version: standalone-forge-1.6.3
Other mods (if used): All the Mods 6 (1.8.5) (mod pack)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/7349972/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. New world
2. Type: "#mine iron_ore"
3. Instant Error

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You are using quite a few mods, could you maybe try removing all mods not required to reproduce this?

**Comment by ejsupernova** [comment]
Perhaps you are under y11

**Comment by wagyourtail** [comment]
> Perhaps you are under y11

you're not even reading the log file are you. it's clearly what ZacSharp said
