### ISSUE TITLE
Baritone will path through sweet berry bushes.

### ISSUE THREAD

**Issue by jsbeans69** [cabaletta/baritone#3036]
When using the.
goto command, baritone will move along the side of sweet berry bushes.
Baritone will also get stuck in berry bushes when it tries to jump up a block.

**Comment by wagyourtail** [comment]
as a *temporary solution, try adding them to `blocksToAvoid`

**Comment by ejsupernova** [comment]
Does this for me to

**Comment by zulc22** [comment]
Bump.

**Comment by wagyourtail** [comment]
this is fixed as of #3308 for 1.17+

**Comment by zulc22** [comment]
> this is fixed as of #3308 for 1.17+

it happened to me literally 30 minutes ago on the latest release on 1.18, so there must be something else required.

**Comment by ZacSharp** [comment]
This is now fixed on all branches and will be in the next release.
In case you don't want to wait for the next release you can get the latest CI build on the actions tab by selecting the latest run on the desired branch and downloading the artifacts zip at the bottom of the page.
