### ISSUE TITLE
Anti-Baritone strikes again (Blocking any kind of baritone).

### ISSUE THREAD

**Issue by AWGshka** [cabaletta/baritone#3050]
## Describe your suggestion
https://www.spigotmc.org/resources/vulcan-anti-cheat-advanced-cheat-detection-1-7-1-17-1.83626/
Anticheat kicks player in seconds.

Personally, I bought this plugin to see how the checks are done.
There is three simple checks for it.
BadPackets(C) -> Impossible pitch.
Baritone(A) -> Checks for Baritone like rotations.
Baritone(B) -> Checks for Baritone like large rotations.

## Settings
I enrolled all baritone settings, although the only possible thing that could work is "randomLooking", but baritone is still detected.

## Context
Suggestion is to make a setting for a legit Baritone that would do rotation smoother.

**Comment by JulianGHill** [comment]
@AWGshka I think they used to supports it, but seem to have gotten lazy.
