### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Emrexe55** [cabaletta/baritone#3056]
## Some information
Operating system:Windows 10
Java version: Wersion 8
Minecraft version: 1.16.5
Baritone version: v1.6.3
Other mods (if used): nope

Windows: `%appdata%/.minecraft/logs/`

## How to reproduce
When I craft anything the game crashes

## Final checklist
- [ ] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
can't reproduce with instructions/mods provided, please fill out the issue template completely. I might open this back up if you actually upload a log...
