### ISSUE TITLE
Baritone Bot Not building, instead running randomly 

### ISSUE THREAD

**Issue by Siegeband** [cabaletta/baritone#3057]
when i stand in an area and try to start my schematic baritone just searches a location to build himself instead of using my location and he isnt even finding one instead he runs thrugh the world and randomly destroys and places blocks. I cant build because baritone is just randomly running and placing blocks.
I already testet it in a singleplayer world in creative and its working but when in go on 0b0t and use survival (and have all the blocks in my hotbar) it isnt doing what it should do

**Comment by scorbett123** [comment]
Can you fill in the bug template?

 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
