### ISSUE TITLE
Makes java.lang.NullPointerException when i load the world and stay on it for a minute

### ISSUE THREAD

**Issue by TheRedBlueCube2** [cabaletta/baritone#3058]

**Comment by TheRedBlueCube2** [comment]
I tried to stay on the world for 1 minute, then it errored with the error... you know
The last thing i remember was doing #follow entity iron_golem.

**Comment by ZacSharp** [comment]
If you think you found a bug you should try reproducing it and only if you can reproduce it open and issue here and fill in the template instead of deleting it.

Issues stating that your game crashed once without any further information are completely useless.
