### ISSUE TITLE
Baritone Crash in Modded

### ISSUE THREAD

**Issue by MunchyG** [cabaletta/baritone#3059]
## Some information
- Operating system: Windows 10
- Java version: (not sure)
- Minecraft version: fabric loader - 0.11.7 - 1.17.1 
- Baritone version: whatever version, meteor dev build 0.4.7-1323 uses (it reports as baritone 1.7.0, but am not sure)
- Other mods (if used): (a lot, full list can be found inside the crash log)

## Exception, error or logs

- [crash-2021-10-31_12.55.27-client.txt](https://github.com/cabaletta/baritone/files/7448144/crash-2021-10-31_12.55.27-client.txt)

## How to reproduce
- Step on an Applied Energistics 2 or Industrial Revolution cable. Flying closely over them also causes the crash. 

I asked about this in the meteor GitHub given that is the version of baritone I am using, but they pretty much said if it is a baritone issue it is not their problem.

**Comment by scorbett123** [comment]
Baritone 1.17 beta issues should be reported on the 1.17 pr #2850

**Comment by wagyourtail** [comment]
@scorbett123 can you at least check that it's not a duplicate of an existing older issue first... this is just #2148

**Comment by scorbett123** [comment]
> @scorbett123 can you at least check that it's not a duplicate of an existing older issue first... this is just #2148

Sorry, was just looking for the easier option, but this is a duplicate of literally half of modding issues, will look for the original duplicate first next time. Basically, was just being lazy.
