### ISSUE TITLE
How do I get baritone to move me to the surface

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3061]
## What do you need help with?
I swear that I used a command that existed for having baritone get to the surface in the past but for some reason cant find the command existing, ik I have used to before I just know it

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I think it was called `#top` and `#surface` but they are only in Baritone v1.2.15 and v1.6.3

**Comment by SteamDoge9000** [comment]
I am using that version though

**Comment by SteamDoge9000** [comment]
wait nvm im using 1.6.2
HOW?
