### ISSUE TITLE
"blacklisting presumably unreachable closest instance..."

### ISSUE THREAD

**Issue by muffiniov2** [cabaletta/baritone#3062]
![Screen Shot 2021-10-31 at 3 55 48 PM](https://user-images.githubusercontent.com/93495803/139604121-a1d4dcda-a26d-49ab-85ee-51dfcdeb4027.png)
As you can see, I am clearly next to the blocks I want to mine, but it is saying that they are unreachable... I haven't been able to mine at all because of this.

**Comment by scorbett123** [comment]
Please don't use baritone on servers that it isn't allowed (hypixel).
