### ISSUE TITLE
unable to move after any command

### ISSUE THREAD

**Issue by TGDCCow** [cabaletta/baritone#3063]
## Some information
Operating system: windows 10
Java version: java 1.17.1
Minecraft version: java
Baritone version: 1.17.1
Other mods (if used): antique atlas, architecture API, bcLib , betterEnd, betthernether, blocus, cloth config API, dark paintings, dual riders, end remastered, enhanced mod spawner, extra alchemy, fabric waystones, immersive portal, inmis, litematica, malilib, optifabric, optifine, traverse

## Exception, error or logs
it shows the paths to the blocks but does not actually go to them didn't change any setting just put it in the mods folder and it just doesn't work and I am on fabric 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SIMULATAN** [comment]
Try the `path` and `resume` commands, in some cases it also helps to use `stop` and then do your command again

**Comment by scorbett123** [comment]
Like @SIMULATAN said, make sure to do #path after the command.

Also, if that doesn't fix it please can you send a log file

**Comment by wagyourtail** [comment]
> immersive portal
remove
