### ISSUE TITLE
Journeymap fillout feature

### ISSUE THREAD

**Issue by Sou11ess** [cabaletta/baritone#3064]
I dont know if this is possible but you could have a feature that can see the journeymap map and move into any unfilled chunks of the map, you could even have a area limit e.g. 100k*100k square to fill out

**Comment by ZacSharp** [comment]
I don't think direct journeymap integration is in scope for Baritone, but you can already use `#explore` to explore regions Baritone hasn't hached yet and if you added both mods at the same time that's exactly the same as filling the journeymap cache.
