### ISSUE TITLE
Baritone crashes my game when I try to build a schematic (#schematica)

### ISSUE THREAD

**Issue by BIDs0ga** [cabaletta/baritone#3065]
Operating system: 8.1
Java version: latest
Minecraft version: 1.12.2
Mods: schematica and lunatriusCore

[crash-2021-11-02_13.07.53-client.txt](https://github.com/cabaletta/baritone/files/7460115/crash-2021-11-02_13.07.53-client.txt)
[tl-logger4943424227035076804.txt](https://github.com/cabaletta/baritone/files/7460117/tl-logger4943424227035076804.txt)

**Comment by ZacSharp** [comment]
Try removing the `-Xverify:none` JVM Flag.
