### ISSUE TITLE
Fix ur mod...

### ISSUE THREAD

**Issue by deadLORD135** [cabaletta/baritone#3069]
## Some information
Operating system: Linux
Java version: 1.8.0_281
Minecraft version: 1.12.2
Baritone version: standalone-forge-1.2.15
Other mods (if used): rusherhack 1.2.3

## Exception, error or logs
https://pastebin.com/DUVHtUjS

## How to reproduce
join any world

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
remove the `-Xverify:none` jvm flag
