### ISSUE TITLE
Baritone Did Not Mine Some Blocks

### ISSUE THREAD

**Issue by JamStudiosCorporation** [cabaletta/baritone#3071]
## Some information
Operating system: Windows NT / Windows 10
Java version: 
Minecraft version: 1.16.5
Baritone version: v1.6.3
Other mods (if used): https://github.com/JamStudiosCorporation/Dynamic-Client/blob/main/credits/Allcredits.md

## Exception, error or logs
None

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
- #mine diamond_ore
- Wait until it mines a vain but 1 / 2 sometimes have bedrock above them and baritone ignore's it same for lava sources instead of maybe make a system that would make baritone block off some lava sources above it.

## Modified settings
Nothing to do with settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Blocks above and below bedrock as well as under or next to lava are purposefully ignored. The former to prevent spending lots of time on pathing to likely unreachable blocks and the latter to prevent burning to death.
