### ISSUE TITLE
Can you maybe add something that would protect the user from mobs? [Suggestion]

### ISSUE THREAD

**Issue by JamStudiosCorporation** [cabaletta/baritone#3073]
## Describe your suggestion
One thing is I have been using baritone in many servers but when baritone is mining I always need to be on the watch because in One instance I almost died to a zombie that detected me in a cave almost killing me in a matter of seconds when I saw that I was being attacked I #stop, It's annoying and would pose a risk when mining.

## Settings
- Maybe add a command that makes #stop much easier to use? maybe shortening it?
- Add a mechanic that protects the user from mobs attacking the player.

## Context
By making a mechanic on being protected while mining in baritone would be revolutionary, as it would get rid of the pose of risk of being killed mid-baritone mining.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
* Guess what `#c` `#p` and `#r` (or without prefix just `c`, `p` and `r`) do
* You mean something like #1131, #290, #240 or #866?
