### ISSUE TITLE
assumeFlight

### ISSUE THREAD

**Issue by Samubrine** [cabaletta/baritone#3074]
## Describe your suggestion
to add a setting to baritone pathing that allows player to use flight as a baritone pathing way.  Baritone will path through the air if assumeFlight were enabled. 

## Settings
Since it is a setting, it's only a true/false setting

## Context
It would increase baritone's speed for servers that allows flight on survival mode. Some pathing requires baritone to go in a roundabout way,  and so by enabling assumeFlight baritone would fly and make the shortest cut possible. And, you can be an automated airplane for the first time in human's history. 

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #1518

**Comment by ZacSharp** [comment]
Duplicate of #545

**Comment by ZacSharp** [comment]
Duplicate of #1776

**Comment by ZacSharp** [comment]
Duplicate of #2112

**Comment by ZacSharp** [comment]
And that's just the most obvious ones on creative flying. If you want elytra support there is at least another 4 duplicates and even a link to the features list.

Why can't people search before opening issues on their "new" ideas?

**Comment by wagyourtail** [comment]
:clown_face:

**Comment by IamZiroToxic** [comment]
Did you add it?
