### ISSUE TITLE
1.6.2 crash when standing on top of IE crate

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3081]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version 16.5:
Baritone version: 1.6.2
Other mods (if used): Immersive Engineering

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[crash-2021-11-12_23.56.28-client.txt](https://github.com/cabaletta/baritone/files/7531423/crash-2021-11-12_23.56.28-client.txt)

## How to reproduce
stand on top of a placed IE crate

## Modified settings
blocksToAvoid lava
allowParkour true
allowParkourPlace true
avoidance true
pathRenderLineWidthPixels 7.0
selectionOpacity 5.0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #2148
