### ISSUE TITLE
add macro support

### ISSUE THREAD

**Issue by himanss** [cabaletta/baritone#3082]
## Describe your suggestion
add support to script baritone.

## A basic idea of how the language could look like
```

//selects 2 areas, fills with dirt
area 2 0 0 2 0 5 
area 0 0 0 0 0 5 
place dirt

//breaks blocks in an area
area 1 0 0 1 0 5
break

//finds dirt inside area, uses hoe on it
find dirt 0 0 0 5 5 5 
use hoe
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any ~~OwO's~~ or ~~UwU's~~ in this issue.

**Comment by scorbett123** [comment]
I think this is covered by #488. It is also covered by #881, however that suggests even more than this.
