### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by nvx0** [cabaletta/baritone#3085]
## What do you need help with?
How can I install Baritone on 1.16.4? I can't find any tutorials. thx

## Final checklist
nothing

**Comment by ZacSharp** [comment]
Same as any other supported version https://github.com/cabaletta/baritone/blob/master/SETUP.md
If you use Forge it works like any other mod: Download it (make sure it's a v1.6.* release and has forge in its name) and put it into your mods folder.
