### ISSUE TITLE
Baritone won't mine/ cancel mining most of the time

### ISSUE THREAD

**Issue by ArnabGamerz** [cabaletta/baritone#3087]
## Some information
Baritone would sometime show
[Baritone] Mining
[BlockOptionalMetaLookup{block={minecraft: diamond_ore}}]
[Baritone] No locations for
BlockOptionalMetaLookup[BlockOptionalMetaLookup{block={minecraft:diamond_ore}}] knowm, cancelling
Operating system: Linux (Ubuntu 20.04)
Java version: 16
Minecraft version: 1.17.1 and other versions same 
Baritone version: the 1.17.1 port
Other mods (if used): sodium, lithium,starlight,mod menu

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/7537615/latest.log)
## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
It happenes randomly on servers
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ArnabGamerz** [comment]
![Screenshot from 2021-11-15 15-25-23](https://user-images.githubusercontent.com/78552320/141761255-6ab80164-2739-4eb3-90c0-8f0096f3266b.png)
Here is the ss

**Comment by wagyourtail** [comment]
1. missing `#modified`
1. probably anti-xray.
