### ISSUE TITLE
Baritone wont mine sometimes 

### ISSUE THREAD

**Issue by ArnabGamerz** [cabaletta/baritone#3088]
## Some information
Baritone would sometime show
[Baritone] Mining
[BlockOptionalMetaLookup{block={minecraft: diamond_ore}}]
[Baritone] No locations for
BlockOptionalMetaLookup[BlockOptionalMetaLookup{block={minecraft:diamond_ore}}] knowm, cancelling
Operating system:
Java version: 16
Minecraft version:1.17.1
Baritone version: 1.17x ported
Other mods (if used): sodium,starlight,lithium,mod menu

## Exception, error or logs
https://paste.ee/p/XDzjd

## How to reproduce
IDK it happens sometimes on servers and the server i am playing doesnt have anti xray

## Modified settings
1. allowdiagonalascend 
2. allowdiagonaldescend
3. allowparkour
4. allowparkourplace

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
reply to closed issue next time. 
> IDK it happens sometimes on servers and the server i am playing doesnt have anti xray

I checked, it does have anti-xray, but only for diamonds.
