### ISSUE TITLE
Types use the obfuscated class names

### ISSUE THREAD

**Issue by SIMULATAN** [cabaletta/baritone#3089]
## How to reproduce
Specify a wrong arg when the arg is a class of minecraft, for example `#mine lol`.
In this case, `lol` is supposed to be a block / material but because its none of that it displays "Expected <type>"
However, because of the runtime patching, the Class names are obfuscated and the type in this case is for example "aa"

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used). | not needed
- [ ] I have included logs, exceptions and / or steps to reproduce the issue. | not needed
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by SIMULATAN** [comment]
How did I forget to change the title 🤦

**Comment by wagyourtail** [comment]
log or screenshot at least?

**Comment by SIMULATAN** [comment]
My minecraft kinda doesn't start so unfortunately there are none atm but it's pretty easy to reproduce

**Comment by SIMULATAN** [comment]
![issue](https://user-images.githubusercontent.com/63104422/142200390-37bfe4c5-0e25-4c17-ba80-4d14d01032e5.png)

**Comment by wagyourtail** [comment]
ahh, are you using standalone, that might actually be an issue with baritone obfuscating `BlockOptionalMeta`

**Comment by SIMULATAN** [comment]
I'm using the fabric mod edition for 1.17.1
