### ISSUE TITLE
I cannot use .b build (file name) and can’t figure out why.

### ISSUE THREAD

**Issue by Celulus** [cabaletta/baritone#3097]
## What do you need help with?
For the past four hours or so I have been trying to set up litematica and baritone in survival, and I have created a pixel art nbt to do so. I tested litematica and it made the schematic so I went to the place I wanted to build, made sure it would be in the right place and that I had blocks to start it (not all because it’s over 10k blocks) and typed .baritone build art.nbt which got the response of “[Baritone] Couldn’t load the schematic. Make sure to use the FULL file name, including the extension (e.g. blah.schematic).” I had a look to see if I could find something to help and decided to go in creative in a world, paste the schematic and save it as a .litematic. I did the same command as before but with .litematic at the end instead, and got the same message. I’ve tried mining with baritone and the mod works fine like that, but the schematic doesn’t do anything. If there’s something I can do to fix it I would greatly appreciate some help.
Thanks
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone can't parse litematics. You have to use either *.schematic or *.schem (I'd recommend the latter, especially since people often call their file *.schematic even if its actually another format, so *.schem has less risk of confusion)

**Comment by Celulus** [comment]
> Baritone can't parse litematics. You have to use either *.schematic or *.schem (I'd recommend the latter, especially since people often call their file *.schematic even if its actually another format, so *.schem has less risk of confusion)

How can I convert my litematic to a .schem?

**Comment by ZacSharp** [comment]
Litematica should be able to do it and if not there are other programs.
