### ISSUE TITLE
Baritone crashed the game for no reason

### ISSUE THREAD

**Issue by pikachu1298** [cabaletta/baritone#3102]
## Some information
Operating system: Windows 10 Home 64-bit
Java version:Java 16.0.1 64-bit
Minecraft version:1.17.1 fabric 0.12.5
Baritone version:1.7.1
Other mods (if used): https://imgur.com/a/mRPs4q2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[crash-2
[latest.log](https://github.com/cabaletta/baritone/files/7590901/latest.log)
021-11-23_15.33.17-client.txt](https://github.com/cabaletta/baritone/files/7590896/crash-2021-11-23_15.33.17-client.txt)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
I don't really remember since i was just filling in a selection and it crashed

## Modified settings
To get the modified settings run `#modified` in game
https://imgur.com/a/fB9zqxI
https://imgur.com/a/qbaV6F1
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
That latest.log doesnt seem like the right one...

**Comment by pikachu1298** [comment]
> That latest.log doesnt seem like the right one...

oh yea its because i had 2 minecraft clients open... just check the crash report

**Comment by wagyourtail** [comment]
> just check the crash report


I need the surrounding context from latest.log, otherwise its much harder to reproduce and debug

**Comment by pikachu1298** [comment]
oh come on i always have 2 clients open because im working on a lag machine

**Comment by pikachu1298** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/7598559/latest.log)
I think its this one

**Comment by pikachu1298** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/7614356/latest.log)
it happened again lmfao

**Comment by Ropobro** [comment]
Quick question, before your game crashed, do you know that anything happened in game? (i.e path blocked/exploded, player was in path, as you have avoidance on, and path may have been only one at that time)

**Comment by pikachu1298** [comment]
i was filling in a selection with #click

**Comment by wagyourtail** [comment]
#3308 merged closing this
