### ISSUE TITLE
Game sometimes crashes when building schematic

### ISSUE THREAD

**Issue by kurt22i** [cabaletta/baritone#3103]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.5
Baritone version: latest
Other mods (if used): none (though it was using schematics from .minecraft/schematics)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
just typing build xyz.schematic, sometimes it crashes after a few seconds of building, other times a few minutes, other times it finishes building without issue.

The crash log seems to be the same each time, so it seems to be the same bug that's causing it.

## Modified settings
To get the modified settings run `#modified` in game
useInventory = true (that might not be the exact name, but it's the setting that allows baritone to use blocks from my inventory)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [uwu? <3] I have not used any OwO's or UwU's in this issue
[latest.log](https://github.com/cabaletta/baritone/files/7591578/latest.log)
[crash-2021-11-23_18.22.06-client.txt](https://github.com/cabaletta/baritone/files/7591581/crash-2021-11-23_18.22.06-client.txt)
.

**Comment by ZacSharp** [comment]
Should be fixed in #3413
