### ISSUE TITLE
baritone STILL crashes whenever i fill in a schematic using #click and #sel set cobblestone

### ISSUE THREAD

**Issue by pikachu1298** [cabaletta/baritone#3106]
## Some information
Operating system:Windows 10 64-bit
Java version:16.0.1
Minecraft version:1.17.1
Baritone version:1.7.1
Other mods (if used): autoreconnect, cloth config, malilib, litematica, sodium and lithium, Wurst, InGameAccountSwitcher, and ModMenu.

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux:
[latest.log](https://github.com/cabaletta/baritone/files/7614376/latest.log)
 `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
#click then fill in with #sel set  with 2 clients open and it may or may not crash

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
can you try to get this to happen with the unoptimized jar, it's easier to fix faster then :)

**Comment by pikachu1298** [comment]
sure i will try, can you provide the download link for the latest artifacts?

**Comment by wagyourtail** [comment]
https://github.com/cabaletta/baritone/actions/runs/1451572684 should be correct

**Comment by pikachu1298** [comment]
it doesn't crash with unoptimized

**Comment by wagyourtail** [comment]
#3308 merged closing this
