### ISSUE TITLE
Lag when mining with baritone

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#3108]
## Some information
 lag whenever I execute the command #mine diamond_ore my fps drops to like 1 fps in 1.18 rc3. It also happens on 1.17
Operating system: Windows 10
Java version: 17
Minecraft version: 1.17 and 1.18 rc3
Baritone version: 1.18 ported on actions tab
Other mods (if used):  sodium and mod menu

## Exception, error or logs
I am on mobile imma edit it in a few min

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Type #mine diamond_ore and it will literally lag like hell

## Modified settings
1. AllowParkour
2. AllowPlaceBlocks
3. AllowBreakBlocks

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ejsupernova** [comment]
If you decrease the render distance it stops

**Comment by ZacSharp** [comment]
Why should decreasing the render distance cause the `WorldScanner` to cause less lag?
