### ISSUE TITLE
Baritone are crashing with 38 mods(part of these, to get perfomance, yes)

### ISSUE THREAD

**Issue by cub-has-injected** [cabaletta/baritone#3109]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.15 (standalone without forge)
Other mods (if used): (all 38)
1.12.2bspkrscore_universal_8.0.1
1.12ArmorStatusHUD_client_1.43.0
aireducer-1.12.2-0.2.1
AutoSprint-Forge-1.8-1.12-2.0.0
baritone-standalone-1.2.15
BetterFps-1.4.8
CleanView_1.12.2_v1
clientfixer-1_12_2-1-9
CreativeCore_v1.10.14_mc1.12.2
crosshairmod-v0.8.2-forge-mc1.12
dynviewdist-1.12-1.3
entityculling-1.12.2-4.1.5
fabric-api-0.36.0+1.16 (1)
FancyBlockOverlay-1.1
FastFurnace-1.12.2-1.3.1)
foamfix-0.10.10-1.12.2
FpsReducer-mc1.12.2-1.18
 iChunUtil-1.12.2-7.2.2
InGameAccountSwitcher-Forge-1.12.2-7.....
ItemPhysic_Full_1.4.34_mc1.12.2
keystrokes-7.0-1.12.2
mixinbooter-2.0
Mouse Tweaks_2.10_mc1.12.2
Neat 1.4-17
netherportalfix_1.12.1-5.3.17
nofog-1.12.2b3
OptiFine-1.12.2_HD_U_G5
performant-1.11
phosphor-1.12.2-0.2.6build 50-universal
screenshottoclipboard-1.12.2-1.0.1
ShulkerTooltip-1.12.2-1.9.2.2
TexFix+V-1.12-4.0
texturedump_1.12.2-1.10
VanillaFix-1.0.10-150
ViaForge+till+1171
worldedit-forge-mc1.12.2-6.1.10-dist Xaeros_Minimap 21.21.0 Forge_1.12

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/7625675/latest.log)

[debug.log](https://github.com/cabaletta/baritone/files/7625673/debug.log)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
You are using baritone-standalone and not the forge version

**Comment by cub-has-injected** [comment]
> You are using baritone-standalone and not the forge version

still crashing

**Comment by wagyourtail** [comment]
Tjen it should be a different log now...

**Comment by cub-has-injected** [comment]
> Then it should be a different log now...

ok, get it(baritone-api-forg
[debug.log](https://github.com/cabaletta/baritone/files/7625910/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/7625909/latest.log)
e)

**Comment by wagyourtail** [comment]
One of the mods is causing a problem that's preventing vanilla fix from loading properly... does this even launch without baritone? You may have to not use vanillafix...

**Comment by cub-has-injected** [comment]
> One of the mods is causing a problem that's preventing vanilla fix from loading properly... does this even launch without baritone? You may have to not use vanillafix... If that doesn't work, which of your mods requires mixinbooter?

that are launching without baritone, but when i set it, it starting crashing, i removed the vanillafix but it loads models and crashing
