### ISSUE TITLE
How to build for fabric on 1.18

### ISSUE THREAD

**Issue by Colmonkey** [cabaletta/baritone#3111]
## Can someone explain to me what is required to create a build for fabric on mc 1.18?

I'm not a java person and I don't use gradlew, so I don't know what would all would be needed. Would there be a way to take #3077 and just run the gradle.bat in in order to create a jar for the fabric loader since fabric has forge on it? I'm guessing there would be more that needs to be done, but maybe someone could point me in the right direction or if someone has already built one that works for fabric, that'd be awesome.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by PXLCoarl** [comment]
i tried my best but i just couldnt build it. It always returns a proguard error and idk how to fix it

**Comment by wagyourtail** [comment]
Probably because you built an older version and since proguard needs to upgrade... so try gradlew clean first

**Comment by Stealthii** [comment]
@Colmonkey - I was able to build a 1.18 fabric build without issue.

- check out the PR defined in #3077
- build with `./gradlew build -Pbaritone.fabric_build`

**Comment by wagyourtail** [comment]
delete `build/tmp/proguard` folder
