### ISSUE TITLE
Mode to build railway to certain coordinates

### ISSUE THREAD

**Issue by Bluscream** [cabaletta/baritone#3112]
## Describe your suggestion
Would be neat if baritone had a mode where you could do `#rails <x> <y> <z>` and it would make sure to build rails to there and also place powered rails when required and available in the inventory

## Settings
None

## Context
Building long railways is a tedious task

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue. (Not yet, anyway)

**Comment by ZacSharp** [comment]
I'd say a new command specifically for building railways is out of scope for Baritone.
However Baritone should already have everything you need to build about 1k to 2k blocks long railways, depending on whether you build a tunnel or need extra blocks. Just make yourself a schematic with one complete segment and use `buildRepeat`. You also might want to have a look at `buildRepeatCount` `buildIgnoreBlocks` `buildSkipBlocks` `buildValidSubstitutes` `buildSubstitutes` and `buildOnlySelection` or generally the settings related to the builder.

**Comment by wagyourtail** [comment]
I forwarded this to altoclef

**Comment by m-sarabi** [comment]
buildValidSubstitutes  is missing from 1.17.1 version,. any help?
