### ISSUE TITLE
Why no 1.18?

### ISSUE THREAD

**Issue by KitCatzYeet** [cabaletta/baritone#3117]
Add 1.18 plssssss

**Comment by scorbett123** [comment]
#3077 is for 1.18. Creating issues like this don't speed up the process of porting, or get leijurv to merge it.

**Comment by pikachu1298** [comment]
uhh @wagyourtail made 1.18 just go to github.com/wagyourtail/baritone and go to actions then download the correct artifacts.

**Comment by wagyourtail** [comment]
yes, that's #3077 .
