### ISSUE TITLE
After Baritone install I can't launch Aristois

### ISSUE THREAD

**Issue by 1Jack007** [cabaletta/baritone#3118]
## Some information
Operating system: Windows 11
Java version: 17
Minecraft version: 1.18
Baritone version: the newest
Other mods (if used): Optifine (I installed it with Baritone)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/7656265/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Two things:

1. can you reproduce this error using 1.17?
2. Can you remove all other mods to check that they aren't causing issues.

**Comment by wagyourtail** [comment]
crash has nothing to do with baritone. looks like optifine error, remove optifine
