### ISSUE TITLE
Bot-system shouldnt duplicate the game input overrider

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#312]
bot-system branch should have bots using normal inputoverridehandler player movement input override, instead of its own bot movement input thingy. I should have remembered this and integrated instead of making anew on master sorry xd

**Comment by 0-x-2-2** [comment]
Close???

**Comment by leijurv** [comment]
Fixed by df80858c499483d97214ccbfa40b62782da2fb7b
