### ISSUE TITLE
How do I get the 1.18 Version?

### ISSUE THREAD

**Issue by CuzImColl** [cabaletta/baritone#3122]
Many issues and pull requests are talking about the 1.18 version but i cant find it anywhere expect with the meteor client but I'd love to get it as a fabric mod.
So where do I find it?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
A. Instructions are literally in the readme file
B. in the artifacts zip, see #3077
