### ISSUE TITLE
Path in boat doesn't work much

### ISSUE THREAD

**Issue by 1Jack007** [cabaletta/baritone#3124]
## Some information
Operating system: Windows 11
Java version: 17
Minecraft version: 1.18
Baritone version: newest from Aristois
Other mods (if used): 

## Bug
Describe the bug
If I use the path command in a boat Baritone moves 5 Blocks and calculates then the new path but just moves crazy

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Just cancel the path command
## Modified settings
To get the modified settings run `#modified` in game
I didn't modified Baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included bugs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Missing features are not a bug.
https://github.com/cabaletta/baritone/blob/master/FEATURES.md#future-features
