### ISSUE TITLE
Auto-Jump

### ISSUE THREAD

**Issue by wefsda** [cabaletta/baritone#3125]
I want to travel a big distance by constantly sprint jumping.
But #goal and #path runs in a straight line and only jumps to go up blocks.
I’ve tried an external auto clicker for space bar but it seems that jump doesn’t work when pathfinding is running.
How do I auto-jump?

**Comment by 1Jack007** [comment]
There is a AutoJump feature in Aristois

**Comment by ZacSharp** [comment]
Like Jack said, you have to use an external mod to do the jumping.
Making Baritone sprint jump itself has already been suggested in #563
