### ISSUE TITLE
Setting 'buildIgnoreBlocks' doesn't work properly on Hypixel.

### ISSUE THREAD

**Issue by Kisus228** [cabaletta/baritone#3126]
## Some information
Operating system:
Java version: 17.0.1 64-bit
Minecraft version: 1.18
Baritone version: 1.8.0
Other mods (if used): Aristois client

## How to reproduce
1) .b sel p1 and .b sel p2.
2) .b sel r sand air
3) Baritone breaks the first block of sand and then tries to break a block of sandstone.

## Modified settings
baritone/'setting.txt'
allowPlace false
disableAutoTool true
allowDownward false
blocksToAvoid sandstone,birch_slab,stone_brick_stairs,slime_block,diorite,packed_ice,birch_leaves,dark_oak_leaves,oak_leaves,grass_block,andesite,spruce_slab,dirt,cyan_terracotta
blocksToAvoidBreaking sandstone,birch_slab,stone_brick_stairs,slime_block,diorite,packed_ice,birch_leaves,dark_oak_leaves,oak_leaves,grass_block,andesite,spruce_slab,dirt,cyan_terracotta
buildIgnoreBlocks sandstone,birch_slab,stone_brick_stairs,slime_block,diorite,packed_ice,birch_leaves,dark_oak_leaves,oak_leaves,grass_block,andesite,spruce_slab,dirt,cyan_terracotta
avoidance true
freeLook false
prefix @
mineGoalUpdateInterval 2
allowOnlyExposedOres true
extendCacheOnThreshold true
builderTickScanRadius 40
mineScanDroppedItems false
legitMine true
legitMineYLevel 0
forceInternalMining false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

https://user-images.githubusercontent.com/44763277/145408265-e43db343-3795-4f37-811f-32f6b1cf7988.mp4

**Comment by Kisus228** [comment]
I checked this problem on the official version 1.16.5. Without changes

**Comment by scorbett123** [comment]
Support for baritone being used on servers that it isn't allowed will not be given.
