### ISSUE TITLE
mod loding bug with forge

### ISSUE THREAD

**Issue by gagaos** [cabaletta/baritone#3127]
Hello. I want to run bartion with with forge in 1.18. But the mod does not work and does not load.
be mincraft says it's a "NUL Jar" and the game won't start.
Or The games start, but non baritone .
My log: https: //paste.ee/p/WU4jo

**Comment by scorbett123** [comment]
Are you sure that you have placed baritone in your mods folder?

**Comment by gagaos** [comment]
![image](https://user-images.githubusercontent.com/83508369/145610342-891b5609-98b6-41e5-be57-6552586d2d65.png)

**Comment by gagaos** [comment]
in 1.18

**Comment by gagaos** [comment]
https://paste.ee/p/oDOEk my log

**Comment by gagaos** [comment]
I think forge does not load baritone because it thinks it is not a mod

**Comment by scorbett123** [comment]
You are using baritone version 1.12, that won't work on 1.18, see [the readme](https://github.com/cabaletta/baritone#readme) for how to download the 1.18 version.
