### ISSUE TITLE
1.18 baritone stuck in lush caves

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#3128]
## Some information
Minecraft version: 1.18 fabric
Baritone version: 1.18 artifact build 
Other mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
**Pathing in lush caves is broken**

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Is it a specific block baritone doesnt like to walk on, i need more specifics

**Comment by LysiBee** [comment]
> Is it a specific block baritone doesnt like to walk on, i need more specifics

He thinks that azalea is transparent block and trying to go through them

**Comment by wagyourtail** [comment]
Fixed in 1.18 newest build, retroactively fixed in 1.17 in an open pr @leijurv should eventually merge
