### ISSUE TITLE
Shear Sheep for Me

### ISSUE THREAD

**Issue by SplatTab** [cabaletta/baritone#3131]
## Describe your suggestion
I want to farm my red sheep and its annoying doing this so make baritone be able to do this for me

## Settings
FarmedSheepColors - What colors should baritone farm - default:all

LookForSheep - Should baritone walk around and look for sheep or just stand still and wait for sheep nearby to grow wool - default:false

KillSheep - Whether baritone kills the sheep for wool or shears them - Default:False (If baritone does not have shears he will just stop)

## Context
Some people need wool for builds or hentai map arts so this will be very useful.
Also considering theres already a farm catergory why not add something like this with passive mobs perhaps you could also make baritone breed mods and farm all mobs

**Comment by scorbett123** [comment]
This is out of scope for baritone, however for this purpose I recommend [altoclef](https://github.com/gaucho-matrero/altoclef)

**Comment by SplatTab** [comment]
Do you have any recommendations for 1.12.2

**Comment by scorbett123** [comment]
I don't know of any equivalent that works for 1.12

**Comment by SplatTab** [comment]
thats what im saying

**Comment by SplatTab** [comment]
guess ill have to make a massive sheep farm

**Comment by SplatTab** [comment]
because if i shear one more sheep im going to go insane
