### ISSUE TITLE
Baritone block list that he cane use

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#3132]
## What do you need help with?
I'm want to add a block that baritone can use for placing and parkour. How can i do it?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
You can use the acceptableThrowawayItems setting to set what items baritone will be willing to bridge with / place during pathfining.

**Comment by LysiBee** [comment]
Thanks
