### ISSUE TITLE
add "LegitMineMinimumYlevel" and "LegitMineMaximumYlevel"

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#3135]
## Describe your suggestion
For now baritone has only "LegitMineYLevel" settings.
 For 1.18 its really useless settings, because **most of ores generates from Y12 to Y-64**
## Settings
LegitMineMinYLevel
LegitMineMaxYLevel

## Context
For 1.18 this would be the great settings, because **baritone will explore caves insted of mining tunnels**. In 1.18 mning tunnels is not as good as on older versions, so this will improve efficiency of mining

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`minYLevelWhileMining` already exists and a setting for a maximum y level has already been suggested in #1883
