### ISSUE TITLE
Bot bug

### ISSUE THREAD

**Issue by Nucleacraft** [cabaletta/baritone#3136]
when over the ore to be mined, the bot first m all the gravel and only then the ore

**Comment by ZacSharp** [comment]
Could you maybe provide more information?
So far I only know you are using Baritone, somewhere below you was ore it was supposed to mine and there was gravel around.

**Comment by Nucleacraft** [comment]
ok

**Comment by Nucleacraft** [comment]
https://youtu.be/mAUnSa51aQw

**Comment by scorbett123** [comment]
This is intended behaviour, it should break that block before mining the diamond ore.
