### ISSUE TITLE
ME Cables Causing To Crash

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [cabaletta/baritone#3138]
## Some information
Operating system:
Editon	Windows 10 Pro
Version	20H2
Install Date	‎2021-‎08-‎25
OS Build	19042.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

Java version: 1.8.0_301
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): Applied Energetics 2

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/7703051/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/7703052/latest.log)

## How to reproduce
Put Any ME Cable, If Pathfinder Touches This Block Then It Fails (java.lang.NullPointerException) And If You Touch (not facades) Then The Game Crashes, You Can't Run This World Until You Remove Baritone

## Modified settings
allowParkour - true
blockPlacementPenalty - 5
blocksToAvoidBreaking - blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,tconstruct:cobalt_block
buildIgnoreBlocks - cave_air,void_air
buildInLayers - true
jumpPenalty - 0
layerOrder - true
okIfAir - cave_air,void_air
okIfWater - true
prefix - @
rightClickSpeed - 0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #2148
