### ISSUE TITLE
Sprint keybind is global

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#314]
It's not part of movement input from options. So if you hit control, all bots will start sprinting. Or if you're in freecam and hit control, the primary player will start sprinting.

reEE

**Comment by ZeroMemes** [comment]
During pathing should the actual keyboard input be disregarded?

**Comment by leijurv** [comment]
Hm. 

Yes.

**Comment by ZeroMemes** [comment]
Wait I just realized that we make setSprinting calls.

**Comment by leijurv** [comment]
:sunglasses:

**Comment by leijurv** [comment]
Related to #251 and #279

**Comment by 0-x-2-2** [comment]
😎

**Comment by ZeroMemes** [comment]
Fixed in 20b03d00049dc3f4a75c8d8e9aa83eca1bd7ac55
