### ISSUE TITLE
Baritone can't swim

### ISSUE THREAD

**Issue by madmak1414** [cabaletta/baritone#3140]
## Describe your suggestion
It would be nice if baritone would use swimming instead of holding the "w and space key" to let players travel a lot faster over great distances of water. 

## Settings
add "#swim and then two numbers" ex: #swim 20 5" the first number is how many seconds it stays below water, and the second number is how many seconds it stays above water to regain air. So for my example, it would swim underwater for 20 seconds, then stay above water for 5 seconds, then repeat, underwater for 20, above water for 5... OR you could let baritone use boats. This would be a lot easier to understand because the user would not need to type anything other than "#goto cord1, cord2, cord3," and you would not have to worry about drowning.

## Context
whenever I travel long distances, I pause baritone and use a boat to get over the water. For this reason, I can't just leave my computer and let baritone do its thing. This would be helpful, thanks!

## Final checklist
- [x] I know how to use checkboxes properly 
- [x] I have not used any OwO's or UwU's in this issue.
- [ ] This has been added
- [x] I don't know what this is for lol

**Comment by LysiBee** [comment]
Duplicate.

**Comment by wagyourtail** [comment]
#1483
