### ISSUE TITLE
Cannot mine spawners

### ISSUE THREAD

**Issue by end-user** [cabaletta/baritone#3143]
## Some information
Minecraft version: 1.18.1
Baritone version: 1.8.0 (fabric)

## How to reproduce
locate a mob spawner, get near it.
run `#mine spawner`
Baritone will start randomly pathing or outright fail to find the block.

## Modified settings
![image](https://user-images.githubusercontent.com/4923193/146128040-49d905a6-c071-4876-b08d-2e5c133ab818.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by m-sarabi** [comment]
Baritone version 1.8? where did you get that? 🤔

**Comment by ehylo** [comment]
> Baritone version 1.8? where did you get that? 🤔

![image](https://user-images.githubusercontent.com/48396713/146130639-e4df1935-2d3e-46e2-a1a7-ee4efa7963bb.png)
Right there in the readme

**Comment by m-sarabi** [comment]
> Right there in the readme

oh, my bad

**Comment by Clausable** [comment]
try running #find spawner. If there is nothing, then baritone wasn't able to cache any spawners to mine for.

**Comment by end-user** [comment]
So, I've tried `#find`, but that doesn't seem to do anything - even `#find dirt`

**Comment by happymaj00r** [comment]
issue is still there

**Comment by M4ngus** [comment]
It is still here and i hate that

**Comment by wagyourtail** [comment]
#3375 or #3379 will fix it, if you can't wait, grab the gh actions build from 3375 :shrug:

**Comment by ZacSharp** [comment]
If this is the problem I think it is then removing spawners from `blocksToAvoidBreaking` "fixes" this as well.
