### ISSUE TITLE
Exposed to water

### ISSUE THREAD

**Issue by YamahaPzz** [cabaletta/baritone#3145]
## Describe your suggestion
When using allowOnlyExposedOres baritone consider visible the blocks next to water.

## Settings
allowWaterExposedOres

## Context
Sometimes some ores are visible next to water but Baritone does not consider them as visible on allowOnlyExposedOres mining mode

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It won't consider them at all anyways because Baritone does not mine anything next to water to keep itself safe (except for `#build`).
