### ISSUE TITLE
SystemTray is not supported

### ISSUE THREAD

**Issue by Bluscream** [cabaletta/baritone#3147]
What does this mean and how to fix it?

**Comment by scorbett123** [comment]
Where are you being told this?

**Comment by Bluscream** [comment]
In the log

**Comment by scorbett123** [comment]
Can you send the full log then?

**Comment by scorbett123** [comment]
Closing due to lack of response.

**Comment by Bluscream** [comment]
oops, sorry. i have like 30 concurrent issues
