### ISSUE TITLE
Baritone doesnt work

### ISSUE THREAD

**Issue by BoterG3il** [cabaletta/baritone#3149]
Heya,

Operating system: Windows
Minecraft version: every one ive tried

My baritone literally finds 0 ores, it just goes randomly and changes path all the time
Ive been running it for a few hours, still nothing!

I hope you guys can help

**Comment by scorbett123** [comment]
Hi

Please can you send the result of #modifed, and are you playing on a specific server or is this across various?

**Comment by BoterG3il** [comment]
> ###

#modified does nothing more

just single player but on multiplayer it does the same

**Comment by scorbett123** [comment]
Sorry for the slow reply, can you send your log files then, and send a screenshot of what is written in chat after you write #modified.

**Comment by wagyourtail** [comment]
closing for inactive.
