### ISSUE TITLE
1.17.X & 1.18.X Release

### ISSUE THREAD

**Issue by SleepyBoi2852** [cabaletta/baritone#3153]
## What do you need help with?
When are we going to have a 1.17.X Release? I've been waiting for months, and it's not here. Even 1.18 doesn't have a release.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CesiumCs** [comment]
https://github.com/cabaletta/baritone#readme
just cause theres no release doesnt mean theres no working code for it

**Comment by wagyourtail** [comment]
> https://github.com/cabaletta/baritone#readme 

> For 1.17.1 leijurv is to lazy to actually create a release so you can login to github and download the jars in the `artifacts` zip [here](https://github.com/cabaletta/baritone/actions/runs/1451572684)
> 
> For 1.18.1 leijurv is to lazy to actually create a release so you can login to github and download the jars in the `artifacts` zip [here](https://github.com/cabaletta/baritone/actions/runs/1472825778)
