### ISSUE TITLE
1.18.1 unable to install/use

### ISSUE THREAD

**Issue by LillyCosmo** [cabaletta/baritone#3154]
## Some information
Operating system:
Windows 10

Java version:
18?

Minecraft version:
1.18.1
Running forge 39.0.6

Baritone version:
baritone-standalone-1.8.0.jar
https://github.com/cabaletta/baritone/actions/runs/1472825778

Other mods (if used): 
Configured
Inventory Hud +
Mouse Tweaks
NetherPortalFix
Jade
Waila (Jade)
FastFurnace
Inventory Profiles Next
Chunky
AI-Improvements
Tree Harvester
Balm
JEI
JER
AppleSkin
FastLeafDecay
Game menu mod option
Collective
Clumps
Journeymap
Fast workbench
Placebo

## Exception, error or logs
No error or log to produce, it simply does not run any chat commands such as #help and prints it in help, it is also not being recognized as a mod as the mod counter is not going up

## How to reproduce
Downloaded artifacts file from https://github.com/cabaletta/baritone/actions/runs/1472825778 threw in the baritone-standalone-1.8.0.jar file into the mods folder

## Modified settings
Unable

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
use `baritone-unoptimized-forge-1.8.0.jar`

**Comment by LillyCosmo** [comment]
> use `baritone-unoptimized-forge-1.8.0.jar` from [this action](https://github.com/cabaletta/baritone/actions/runs/1531914509)

Beautiful, thank you!
