### ISSUE TITLE
Is there a way to let Baritone mine lower than y=11 in the 1.18?

### ISSUE THREAD

**Issue by Velt1234** [cabaletta/baritone#3155]
Im currently playing on a vanilla minecraft server and cant get Baritone to mine at y=-59. I already tried setting the minyLevelwhilemining to 0 and -59, but nothing seems to work.

**Comment by wagyourtail** [comment]
what's your `#modified` look like because it's working fine for me when I do `#mine deepslate_diamond_ore`

**Comment by wagyourtail** [comment]
probably legit mine y level
