### ISSUE TITLE
.b build Lokligan2.schematic building in the middle of map

### ISSUE THREAD

**Issue by JoakimGizmo** [cabaletta/baritone#3163]
Is it possible to ignore 'BetterBlockPos' where as I want it to fit perfectly inside of a map.

**Comment by ZacSharp** [comment]
If you want it to build at a specific position just add it to the command (`#build Lokligan2.schematic <x> <y> <z>`) or stand at the desired position when running `#build Lokligan2.schematic`.

Don't know what you think ignoring the position would do. If you want to build, you need a position to build at.
