### ISSUE TITLE
AllowInventory when building schematic causes crash

### ISSUE THREAD

**Issue by AstroBeagle** [cabaletta/baritone#3165]
## Some information
Operating system: Windows 11
Java version: 18?
Minecraft version: 1.17
Baritone version: 
baritone-standalone-fabric-1.7.1.jar 
https://github.com/cabaletta/baritone/actions/runs/1451572684

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/7777020/latest.log)

## How to reproduce
1. allowInventory = true
2. build schematic

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by CerealBowl** [comment]
![6a0120a85dcdae970b0128776ff992970c-pi](https://user-images.githubusercontent.com/64644502/148545838-c77261bd-c8f2-4154-bc64-2c557c6b9246.png)

**Comment by AdamBajger** [comment]
Came across teh same issue.
Windows 10, MInecraft 1.18.1
FabricLoader with Optifine_1.18.1_HD_U_H4
Too lazy to dig out the specific crash reports, but it is a null pointer exception when calling a specific method.

Reproduceable through the described steps.

**Comment by ThatOneShortGuy** [comment]
Having the same issue using Fabric with optifine 1.18.1

**Comment by wagyourtail** [comment]
#3308 merged closing this
