### ISSUE TITLE
How does baritone decide when to mine a block when pathfinding

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#3166]
## What do you need help with?
How does baritone decide when to mine a block when pathfinding? I can't be bothered to understand or read the code.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
When considering a movement it computes the breaking cost of all blocks the movement requires to be clear and adds it to the overall movement cost.
There is no decision process other than which blocks are required to be broken (which is hardcoded), but of course the path chosen for execution does depend on the movement costs, which include the breaking costs.
