### ISSUE TITLE
Version 1.17.1 does not show up in versions dropdown menu when trying to make ''New Installation''

### ISSUE THREAD

**Issue by SneezingElephant** [cabaletta/baritone#3168]
## Some information
Operating system: Windows 11
Java version:
Minecraft version: 1.17.1
Baritone version: 1.17.1
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

## How to reproduce
I downloaded the 1.17.1 Artifacts folder, took out and extracted the 1.17.1 Baritone standalone folder (vanilla + baritone) and chucked it into the versions folder

![image](https://user-images.githubusercontent.com/92727767/147591213-0b75b0a8-925f-41f5-a4c0-89b9bf18bb9b.png)

However when I try to make a new installation it won't show up in the dropdown menu

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You don't need to put them into your versions folder. The baritone-*-forge jars are loaded as Forge mods, the same goes for fabric and the other jars have to be loaded as tweakers (custom version json).
If you use other mods relying on Baritone you want a baritone-api-* or baritone-unoptimized-* jar, otherwise you can use a baritone-standalone-* jar as well, which is possibly a little faster than api.

**Comment by SneezingElephant** [comment]
> You don't need to put them into your versions folder. The baritone-*-forge jars are loaded as Forge mods, the same goes for fabric and the other jars have to be loaded as tweakers (custom version json). If you use other mods relying on Baritone you want a baritone-api-* or baritone-unoptimized-* jar, otherwise you can use a baritone-standalone-* jar as well, which is possibly a little faster than api.

I'm trying to attach Baritone to Vanilla Minecraft, not through Forge or Fabric... back when I first tried Baritone it was just downloading the release and clicking and dragging it into the versions folder that needed to be done

So I assumed that Baritone Standalone folder from the Artifacts folder was just like that, but I guess not xD I guess I'll just wait for a release to be made for 1.17.1

**Comment by ZacSharp** [comment]
The artifacts are exactly the same as those that would be published in a release. Also what is the release you first installed? I didn't know there were releases using that installation process, only links in the readme file for new versions without a proper release (kind of like the link to the action run now).

**Comment by SneezingElephant** [comment]
I first tried out Baritone for the 1.15.2 version, kind of like in this video:
https://youtu.be/CZkLXWo4Fg4

**Comment by zPeanut** [comment]
hm

**Comment by scorbett123** [comment]
> I first tried out Baritone for the 1.15.2 version, kind of like in this video: https://youtu.be/CZkLXWo4Fg4
> 
> This is what I want to achieve, a pure vanilla + Baritone, not through Fabric, not through Forge, just Baritone...

Currently there isn't a release which you can do that with for 1.17.1, you have to install it either through fabric or forge.
