### ISSUE TITLE
I want to baritone to use pickaxe to break wool 

### ISSUE THREAD

**Issue by SaucisseSama** [cabaletta/baritone#3170]
$${

unset(@fuel)
unset(@failsafe)
/// SETTING UP THE COORDINATES
unset(&trees[])
&trees = []
push(&trees[],"-88 156 81 -88 159 81")
push(&trees[],"-88 156 82 -88 160 82")
push(&trees[],"-88 156 83 -88 160 83")
push(&trees[],"-88 157 84 -88 160 84")
push(&trees[],"-89 156 84 -89 156 84")
push(&trees[],"-89 157 85 -89 157 85")
push(&trees[],"-88 158 85 -88 159 85")

/// SETTING UP MOB WHITELIST
unset(@&mobs[])

push(@&mobs[],"Lost Adventurer")
push(@&mobs[],"Star Sentry")
push(@&mobs[],"Ice Walker")
push(@&mobs[],"Weakling")
push(@&mobs[],"Knifethrower")
push(@&mobs[],"Fireslinger")
push(@&mobs[],"Goblin")
push(@&mobs[],"Crystal Sentry")

/// ACTUALLY PUTTING COORDINATES INTO BARITONE
foreach(&trees[],&tree)
  if(&tree != "")
    split( ,%&tree%,#treepos[])
    SELSTART(%#treepos[0]%,%#treepos[1]%,%#treepos[2]%)
    SELEND(%#treepos[3]%,%#treepos[4]%,%#treepos[5]%)
  endif
next

goto(-90,156,83)
DO
UNTIL(YPOS > 155)

exec(mithrilChecks.txt,mithrilChecks)
SELREPLACE("wool","bedrock")

DO
 key(use)
 wait(2000t)
LOOP
}$$

**Comment by wagyourtail** [comment]
disable autotool and use an external one (or pick the tool manually)... there's settings for it...

**Comment by SaucisseSama** [comment]
how can you show me

**Comment by wagyourtail** [comment]
![image](https://user-images.githubusercontent.com/6234704/147708277-ca0c0ea7-3b76-4084-8dbb-0a80516a627d.png)

**Comment by SaucisseSama** [comment]
I am new to this mod and I don't understand how to do this because it doesn't help me

**Comment by scorbett123** [comment]
Type the name of the setting that you want to change and then the value to change it to into chat.

In this case: ```#disableAutotool true```

**Comment by SaucisseSama** [comment]
in the minecraft chat ?

**Comment by scorbett123** [comment]
yes

**Comment by SaucisseSama** [comment]
ty It was not wrking because the script start when I press V
