### ISSUE TITLE
How to install latest version of baritone?

### ISSUE THREAD

**Issue by PotatosWillTakeOverTheWorld** [cabaletta/baritone#318]
So, I've tried the thing in #301 but it seems to give me an outdated version I think. It doesn't have some things I've seen on the newer versions. Does this method not give me the latest public version, or is the version I have now the newest public one? I've looked at the things in the README and other documents on github for baritone but I can't really understand them. (Not that good with computers, sorry)

**Comment by ZeroMemes** [comment]
There are no official builds made for upcoming releases, so you will have to [build baritone yourself](https://github.com/cabaletta/baritone#setup).
