### ISSUE TITLE
Allow baritone to fight inputted players or mobs. | Enhance the Block Breaking and Jump Over Blocks

### ISSUE THREAD

**Issue by ItzVaio** [cabaletta/baritone#3180]
Allowing baritone to fight players or mobs would be nice, at some point it might need alot of code into it so it can track down the player or mob and then proceed to fight them.
And, my other enhancement is, please fix the block breaking and the jumping over blocks for 1.18-SNAPSHOT BARITONE, as it wont do it correctly sometimes.

**Comment by scorbett123** [comment]
Baritone fighting players and mobs is out of scope, please can you create a full bug report for your other issue, preferably with a video of the issue, as I haven't heard of that behaviour before.
 
 * [**Report a bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
