### ISSUE TITLE
How to fix Baritone 1.16.5 couldnt load schematic

### ISSUE THREAD

**Issue by 3inKatz** [cabaletta/baritone#3182]
i have a problem with the Baritone it says couldnt load the schematic .
How do i fix it

**Comment by ZacSharp** [comment]
Some guesses
1. Use the full schematic name, including the file extension.
2. Don't " " (space) in the schematic name
3. Make sure your schematic is in a format Baritone can read. That's either McEdit *.schematic or Sponge *.schem and sometimes people use the wrong file extension so make sure you got it eight.

If none of those helps you, you need to provide more information.

**Comment by wagyourtail** [comment]
Closing for lack of information/follow up, will assume @ZacSharp 's response solved it
