### ISSUE TITLE
Area selection with baritone for mining.

### ISSUE THREAD

**Issue by Fatalreality** [cabaletta/baritone#3183]
Is there a way to auto mine a perimeter without schematics and maybe have selections like world edit.
-Having an option to select 2 coordinates and mine the area or do other things with the selection like maybe exclude some blocks.
-i wonder if it is a question or a suggestion...and i am really sorry if it was already documented...or if there is a way to do it. (if there is a way to do it, it would be very helpful if someone shared it.)

**Comment by wagyourtail** [comment]
yes,
you can make a selection by either drag-clicking with `#click` or `#sel pos1` / `#sel pos2` and then you can use `#sel ca` to clear it

**Comment by wagyourtail** [comment]
to exclude some blocks you may want to look into using `#sel replace` instead

**Comment by Fatalreality** [comment]
Thank you so much and sorry taking your time.
