### ISSUE TITLE
Unable to find any optimal path

### ISSUE THREAD

**Issue by Blogom** [cabaletta/baritone#3184]
When i run #mine gold_block it just, doesnt
![image](https://user-images.githubusercontent.com/96531240/148602827-f2090815-40be-4413-97fb-ce0bbba7a4fd.png)
as pictured above, i am completely surrounded by gold blocks and its just not mining them, it moves a bit here and there but really nothing, i dont know what to do.

**Comment by ZacSharp** [comment]
Three things that came to my mind when reading this:
1. Make sure you have a tool that can break the target block within reasonable time
2. Don't use Baritone on Hypixel. Baritone is meant to be used on anarchy servers.
3. Pretty sure Hypixel plays some tricks on you so while everything looks normal to you the situation is actually completely different for Baritone and Baritone can't be expected to be able to deal with it.

**Comment by Blogom** [comment]
😔 runelite has spoiled me, and duly noted, thanks !

**Comment by wagyourtail** [comment]
I would guess that hypickel replaces the gold with either stone or bedrock after mining, and since baritone only mines correctly from the sides of blocks, that means it keeps failing and recalculating when it gets a bedrock under it when it wanted to dig down one to mine from the side
