### ISSUE TITLE
Baritone 1.18.1 meteor intergrated version crashing on pathfind in specific areas of servers

### ISSUE THREAD

**Issue by Sir-Jitterbug** [cabaletta/baritone#3185]
## Some information
Operating system:windows 10 home 64
Java version: Latest version(always update when a new version of java releases)
Minecraft version:1.18.1 fabric
Baritone version: idk what version meteor uses as it pastes null whenever i try
Other mods (if used): litematica, some thing that adds particles to waterfalls and Meteor client, plus fabric

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the [issue](url)

[crash-2022-01-07_23.38.01-client.txt](https://github.com/cabaletta/baritone/files/7831859/crash-2022-01-07_23.38.01-client.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Try pathfind to places or mine ore in nether, it happens at random but baritone decides it wants to crash whenever it gets activated, it spams chat with errors but before i read them it closes

## Modified settings
To get the modified settings run `#modified` in game
allow diagonal(up and down)
allow parkour plus place
allow vines
assume walk on lava and water
block reach distance is reduced slightly

changed the colors of the pathfinding stuff to stand out more

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO
's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a meteor issue, not an issue with baritone.
