### ISSUE TITLE
reproduceable crash with "click" trying to  drag

### ISSUE THREAD

**Issue by Blindleistung** [cabaletta/baritone#3186]
## Some information
Operating system:  Debian11 (SID)
Java version:   1.8.0_202
Minecraft version:    1.12.2
Baritone version:    commit # 7a96772a9b99ad1c1236598a33879e127609a166 (pulled/built today)
Other mods (if used):   using baritone-standalone-forge

## Exception, error or logs
crashlog attached

## How to reproduce
startup MC, enter "click" command, (as standalong, without prefix).
Click some place and then drag while holding (I was trying to change view-direction while click command was active).
Crashes every time, with either mouse button.

## Modified settings
To get the modified settings run `#modified` in game
 - only followRadius . probably unrelated.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[crash-2022-01-08_02.37.07-client.txt](https://github.com/cabaletta/baritone/files/7832169/crash-2022-01-08_02.37.07-client.txt)
[crash-2022-01-08_02.31.40-client.txt](https://github.com/cabaletta/baritone/files/7832170/crash-2022-01-08_02.31.40-client.txt)

**Comment by Blindleistung** [comment]
I tried to get a more meaningful stacktrace by copying the 'unoptimized' jar into the mods folder, but that seems to be incompatible with 1.12.2 and forge.

**Comment by wagyourtail** [comment]
duplicate #2865
