### ISSUE TITLE
build fail branch "1.16.5" and "1.17.1", succeed 'master'(1.12.15). loom incompatible java runtime 52 <=> 55

### ISSUE THREAD

**Issue by Blindleistung** [cabaletta/baritone#3188]
Trying to build baritone, it succeeds with branch  'master', but building version 1.12, but  for 1.16.5 and 1.17.1, it fails with an error-message that parts of loom are incompable with class-file versions 52  vs 55. See log attached.

Is there some version reference that needs to be bumped?

## Some information
Operating system: Debian11-SID
Java version:  OpenJDK-8  (version that comes  with debian-sid)
Minecraft version:  <NA>
Baritone version:   git branches  "master"   "1.16.5"   "1.17.1"
Other mods (if used): <NA>

## Exception, error or logs
gradle error message added as log
[gradle_fail.txt](https://github.com/cabaletta/baritone/files/7833294/gradle_fail.txt)

## How to reproduce
git-clone ... 
cd baritone
sudo update-alternatives --config java     (to openjdk8)
sudo update-alternatives --config javac   (to openjdk8)
git checkout 1.17.1
./gradlew

## Modified settings
<NA>

## Final checklist
- [x] I know how to properly use check boxes 
- [NA] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
1.17 should work (you do need java 16 because mc requires that for 1.17), as for 1.16
duplcate of #3068

**Comment by Blindleistung** [comment]
I tried to build with openJDK 16, now it fails again, complaining about ":proguard": Artifact not found! Run build first!

There is not gradle-task named 'proguard', and  running gradlew buildNeeded has the same failure.
