### ISSUE TITLE
Autofarm - add a toggleable option for using a fortune 3 item to farm crops

### ISSUE THREAD

**Issue by ComeOnBear** [cabaletta/baritone#3189]
Hi there!
Thanks for taking the time to read this,
I thought that, since baritone switches away from the farming item when placing back crops, maybe you could get it to switch to a pickaxe, axe, or hoe that has the fortune 3 enchantment.
I'm just suggesting this because it gives so many more crops that it would be more worthwhile to farm manually.
Thanks!

**Comment by wagyourtail** [comment]
duplicate #2495
