### ISSUE TITLE
Use builder (or rather, breaker) to add a 2x3 highway tunneling mode

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#319]
Could be useful idk

Could just make a big 2x3x100000 empty schematic lol

but then how to deal with lava hmmMMMM

**Comment by Thunder33345** [comment]
make a custom one?
like to fill above or not
like to fill sides or not
to fill bottom or not

pretty sure something simple like digging side ways to bypass/skip if filling is "disabled"

**Comment by mikeNG** [comment]
1x2 with autofill is another similar useful idea

**Comment by SylveonBottle** [comment]
I recall an old minebot thing where it'd pretty much tunnel for you. It'd place blocks on the bottom to bridge over chasms, and place blocks 'n stuff on either side to stop lava from pouring in. 

Dev would have to put up a system in place to place blocks inside of lava blocks to remove them.

**Comment by Bendito999** [comment]
i personally really like the idea of automatic torch placement too i'm always pausing and unpausing my mining stuff with a hot key so that i can quick place a torch so that teh creepers don't get me, that'd be cool

**Comment by Haxified** [comment]
any updates @leijurv

**Comment by S-B99** [comment]
This is now a thing.

**Comment by S-B99** [comment]
See #971 for torch placement
