### ISSUE TITLE
my baritone bot will not take any commands even # or .b

### ISSUE THREAD

**Issue by electricseizure** [cabaletta/baritone#3195]
how do i fix this 
![Uploading 2022-01-11_21.12.23.png…]()

**Comment by electricseizure** [comment]
![2022-01-11_21 12 23](https://user-images.githubusercontent.com/97515946/148923969-34985d1c-3dda-46a3-b309-10ff27d5094b.png)
sorry i sent it too soon

**Comment by wagyourtail** [comment]
Please fill out the bug report properly, or at least give a log file...

From all you show the only useful thing I can say is:

install baritone, and make sure you grab one of the ones labeled `Forge` or `Fabric` depending on your mod loader
