### ISSUE TITLE
Can you add blocks from mods?

### ISSUE THREAD

**Issue by 0100110111011010** [cabaletta/baritone#3197]
Can you add blocks from other mods I play on a Minecraft server with mods (TNP Limitless 3) and there are more ores, I would like to use the auto miner with it, but I don't know if you can or not?

**Comment by ZacSharp** [comment]
If you use `#mine <name>` baritone assumes you mean `#mine minecraft:<name>` and if the block is from a mod you simply have to use `#mine <modId>:<name>` instead.
E.g. `#mine thermalfoundation:glass_alloy`
