### ISSUE TITLE
#obtain

### ISSUE THREAD

**Issue by pikachu1298** [cabaletta/baritone#3198]
## Describe your suggestion
#obtain will search all nearby chests, items on the ground, shulkers, dispensers, or any other thing that can contain items for the specified item. For example: #obtain cooked_beef. This will search all loaded chunks for item cooked_beef. once found, it will open said container or walk to the item to get it. You can also specify #obtain cooked_beef 14 to get 14 beef.
## Settings
no

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Bluscream** [comment]
This is basically @get from [Altoclef](https://github.com/gaucho-matrero/altoclef)

**Comment by pikachu1298** [comment]
imma be coding a bot to automatically get minecarts and place them on a specific rail so i can build a minecart lag machine without being at my pc

**Comment by scorbett123** [comment]
This is out of scope for baritone, unless I am misunderstanding you, however I would recommend Altoclef like @Bluscream suggested.
