### ISSUE TITLE
Baritone stuck in infinite loop while falling into water more than 1 block deep

### ISSUE THREAD

**Issue by Clausable** [cabaletta/baritone#3200]
## Some information
Operating system: Windows 10
Java version: 17
Minecraft version: 1.16.5
Baritone version: Impact 4.9.1
Other mods (if used): 

## How to reproduce
Make Baritone fall into water more than 1 block deep. You will notice that it constantly keeps trying to correct itself, but fails

https://user-images.githubusercontent.com/97650056/149560280-49585ba5-064e-4d5e-84f2-968971b4addd.mp4

## Modified settings
allowInventory, breakFromAbove, chatControl, desktopNotification. followRadius, freeLook, legitMine, maxFallHeightNoWater, randomLooking, randomLooking113, renderPath

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Clausable** [comment]
I've tested it for 1.12.2 and it works fine, so it must be something to do with Update Aquatic.

**Comment by forestg10** [comment]
Beautiful.
