### ISSUE TITLE
How to add this setting to the game?

### ISSUE THREAD

**Issue by determinder** [cabaletta/baritone#3204]
**I came across that I can’t set up #buildOnlySelection because this function is simply not in the game, how can I fix this?**

![Без имени](https://user-images.githubusercontent.com/71042954/149673882-def41bc9-26aa-4acb-865d-7e1a12cda633.png)

**Comment by scorbett123** [comment]
Your version of baritone doesn't have this setting yet, the only solution would to be to build a custom version for yourself that has the feature.
