### ISSUE TITLE
I have three questions

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#3210]
Hey, does anyone know how to use #goto when riding? 
Another question is, what if I am attacked by zombies when using #mine
Also, I'm in legitmine, which has no minerals for a long time. How can I let him explore other areas

**Comment by wagyourtail** [comment]
1. you don't
2. not baritone's problem, you would have to use another mod to "protect" yourself
3. I don't think it's possible to improve legitmine currently, no settings for that

**Comment by lingyunQAQ** [comment]
> 1. 你不
> 2. 不是男中音的问题，您必须使用另一个模块来“保护”自己
> 3. 我认为目前无法改进合法性，没有设置

Can you recommend a mod protection
