### ISSUE TITLE
Help with crash after installing baritone 1.18

### ISSUE THREAD

**Issue by EchoSanslol** [cabaletta/baritone#3211]
I'm really bad at reading code and I don't know what the problem is, and my Minecraft is crashing continuously after installing the 1.18 version of baritone that is made by wagyourtail on github, so can anyone help me. Also, the Minecraft I'm using is cracked (Tlauncher) and I'm using the fabric loader 0.12.12-1.18.1.
[crash-2022-01-16_17.26.03-fml.txt](https://github.com/cabaletta/baritone/files/7906205/crash-2022-01-16_17.26.03-fml.txt)

These are all the mods I have currently installed rn
![Screenshot (9)](https://user-images.githubusercontent.com/90122878/150364968-1e041f77-9841-4d72-a0a8-7433360a5c95.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
1. That is probably not the full log, and the issue causing the crash isn't in there.
2. You will run into later issues using a cracked version, buy the game.
3. You will run into issues when using that many mods.

**Comment by EchoSanslol** [comment]
okay, I found out the issue, I...

have installed ares client in my Minecraft which doesn't seem to mix well with baritone for some reason but after uninstalling that it's working fine rn.

I feel dumb now
