### ISSUE TITLE
repeat command

### ISSUE THREAD

**Issue by aGREG4t** [cabaletta/baritone#3212]
My sugestion is to give baritone a command / commands that allow him to repeat last command.
For example: I have farm on server so I use #farm command - when baritone finish farming he will just stand still.
So my sugestion is to give him a #repeat [x] command, where x is number of second that bot will wait till run previous command again, for example: #farm > # repeat 1000 > {farm finished} > {1000 seconds past} > {farming again} > ECT...

**Comment by ZacSharp** [comment]
Duplicate of #176
