### ISSUE TITLE
Problems with #goto or #home

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#3213]
![QQ截图20220122105159](https://user-images.githubusercontent.com/58384404/150622176-aa481e6f-d63d-48db-be53-0118f8aef8ed.png)
look

**Comment by wagyourtail** [comment]
please fill out the issue template properly so we actually have all the information.

otherwise, can't reproduce
![image](https://user-images.githubusercontent.com/6234704/150622393-028b8c65-412d-4d66-9f15-39d058df2425.png)
