### ISSUE TITLE
Baritone module conflicts with vanillafix module in impact module

### ISSUE THREAD

**Issue by KidoLee1314** [cabaletta/baritone#3215]
## Some information
Operating system: Windows 10
Java version:1.8.0_321
Minecraft version:1.12.2
Baritone version: impact is 4.9.1,i don't know baritone
Other mods (if used): VanillaFix

## Exception, error or logs
  ##Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux:  #`~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [√] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
rename vanillafix to start with a `!`

**Comment by KidoLee1314** [comment]
> rename vanillafix to start with a `!`

Renaming doesn't seem to work

**Comment by wagyourtail** [comment]
worked for me, it needs to happen before any mods with older versions of mixin load, you  could try "a" instead
