### ISSUE TITLE
Baritone 1.18 pathfinding doesn't render

### ISSUE THREAD

**Issue by suckstobeyou1** [cabaletta/baritone#3216]
Baritone 1.18 wont render its pathfinding, no matter how hard i tweak its settings, I'm running TLauncher on the standalone forge version

**Comment by wagyourtail** [comment]
other mods?

**Comment by suckstobeyou1** [comment]
no other mods

**Comment by wagyourtail** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/6234704/150921705-1c89e658-4306-4b6f-9217-ce4585fa879f.png)
