### ISSUE TITLE
Remove Saving Death Location

### ISSUE THREAD

**Issue by GerroPogi** [cabaletta/baritone#3219]
Add a command that stops it. It would help lower-end computers from dying in the game and having to wait a whole minute waiting because baritone is saving the death location

**Comment by wagyourtail** [comment]
doing this would not actually fix what you say, the code for saving death location is actually quite simple
https://github.com/cabaletta/baritone/blob/7a96772a9b99ad1c1236598a33879e127609a166/src/main/java/baritone/behavior/MemoryBehavior.java#L189
