### ISSUE TITLE
Baritone not using all blocks in .schematic

### ISSUE THREAD

**Issue by Redun-Mal** [cabaletta/baritone#3220]
So, recently I made a simple .schematic file, using world edit 1.15.2 [Fabric version] and Baritone [1.15.2]
Schematic file worked fine, until I've noticed, that it didn't use all blocks included in schematic file.

**How it is supposed to be:**

![image](https://user-images.githubusercontent.com/87913423/151174949-9fc6dd6c-91b7-491d-96c8-eca9139926cd.png)

**How it went:**

![image](https://user-images.githubusercontent.com/87913423/151175035-a3c550a7-8290-4314-a25c-809578fc287a.png)

I am pretty sure, that I used same version, because I just downloaded Fabric version

![image](https://user-images.githubusercontent.com/87913423/151175431-5cd9c313-9a00-4693-a37d-0cd594bc655e.png)

No Idea why It's not working, and yes, I dont have #I-do-not-care or similar commands on True

_Here's .schematic file block count_
![image](https://user-images.githubusercontent.com/87913423/151175991-8e945c1f-ac36-451c-98d0-9c0ba2f074ba.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Your block count window shows numeric ids so maybe you saved the schematic in an old format?
If your schematic file is really a .schematic and not a misnamed .schem or other that's probably the problem and saving as a .schem (different format not different name, WorldEdit should support it) instead should fix it.

**Comment by Redun-Mal** [comment]
> Your block count window shows numeric ids so maybe you saved the schematic in an old format? If your schematic file is really a .schematic and not a misnamed .schem or other that's probably the problem and saving as a .schem (different format not different name, WorldEdit should support it) instead should fix it.

Well I did use 1 website to compile Worldedit's .schem file to .schematic , but it is supposed to work only on 1.13+ versions
https://puregero.github.io/SchemToSchematic/

Like I don't think, that it will be suck a **HUGE** problem, to make difference of blocks after decompiling.
![image](https://user-images.githubusercontent.com/87913423/151300367-c7f36bc0-87dd-48b9-a340-b14670d7a8c2.png)

I will try to use other mods to make .schematic files then.

**Comment by ZacSharp** [comment]
Why are you converting your .schem to a .schematic? The blocks are either lost during that conversion or when converting back to the post-flattening ids for building and if you use the .schem directly both of these steps won't happen.
