### ISSUE TITLE
Legitmine not mining ores under 1 block deep water

### ISSUE THREAD

**Issue by qsxcfthnjil** [cabaletta/baritone#3221]
## What do you need help with?
Is there a setting that allows legitmine to mine ores under one block deep water?
obviously there is no chance of drowning, and its very cringe when i see the bot walk past a shallow pool with diamonds in it

it might be because of the no mining blocks beside liquids thing, but i'd say diamonds are worth risking somehow managing to drown in one block deep pools

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The pathfinder (mining is walking into ores) does not move into water or break blocks next to water and there is no way to change it. If you want to see why, try building a nontrivial schematic in an area with water).
