### ISSUE TITLE
bot got stuck in one place when swimming (space holding)

### ISSUE THREAD

**Issue by Mer00z** [cabaletta/baritone#3222]
like, bot cant swim this is prop bcs im on 1.18

**Comment by zaxophone** [comment]
I have the same issue, it gets stuck in one place trying to mine while swimming in 1.18

**Comment by Brzydall** [comment]
Same issue

**Comment by NormalHuman-Anything** [comment]
same in 1.18.1

**Comment by bokja** [comment]
Hmm yes wen fix i pray bump for peeps

**Comment by wagyourtail** [comment]
is this is #3200 duplicate?

**Comment by TheMeq** [comment]
My issue specifically might be, not sure about OP.

**Comment by scorbett123** [comment]
This is a duplicate of #3200
