### ISSUE TITLE
Baritone is crashing while starting game

### ISSUE THREAD

**Issue by YuuiOtaka** [cabaletta/baritone#3223]
## Some information
Operating system: Win10
Java version: Default Minecraft Java
Minecraft version: 1.12.2 forge
Baritone version: v1.2.15
Other mods (if used): Appleskin 1.0.14, Controlling 3.0.10, DiscordSuite 2.2.4, EnchantmentDescriptions 1.1.15, Hwyla 1.8.26-B41, InventoryTweaks 1.63, jei 4.16.1.301, journeymap 5.7.1, JustEnoughResources 0.9.2.60, MouseTweaks-2.10, OptiFine_1.12.2_HD_U_G5, replaymod-1.12.2-2.6.3, SchnurriTV's Sexmod-1.3.1, Wawla-1.12.2-2.6.275

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/7950929/latest.log)

## How to reproduce
clicking play and not even halfway done starting up, it crashes.

## Modified settings
none, cuz I haven't even been able to start it up

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
And it does not happen without Baritone? Also can you try removing the other mods that are not required to reproduce this?

**Comment by wagyourtail** [comment]
replaymod for 1.12 packages a newer version of mixin, for a chance of this working you should rename replaymod so it appears before baritone (either a z before baritone, or an a before replaymod)
