### ISSUE TITLE
Baritone Looking-Fast

### ISSUE THREAD

**Issue by baaaaritone** [cabaletta/baritone#3229]
okay so i dont need help with the freelook thing but on baritone how do i stop such sharp turns? its easy to tell if its a baritone bot

**Comment by ZacSharp** [comment]
There is no setting / other functionality to stop the view snapping.
The best you can get is #2293, which makes Baritone walk / sprint / jump sideways serverside (yes, in that case it's not just freelook) and if you set `smoothAim` higher than 2 (I think) Baritone starts failing parkour place jumps.
