### ISSUE TITLE
Couldn't load the schematic.

### ISSUE THREAD

**Issue by 54xzh** [cabaletta/baritone#3231]
## Some information
Operating system:Windows 11
Java version: JDK 17.0.2
Minecraft version:1.18.1 Fabric
Baritone version:1.8.0
Other mods (if used):  Fabric api

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/7966268/latest.log)
## How to reproduce
1.use command"#build 13432.schematic" 
2.return"Couldn't load the schematic. Make sure to use the FULL file name, including the extension (e.g. blah.schematic)."
3.filename is  correct
## Modified settings
 All modified settings:
[Baritone] --
[Baritone] --
[Baritone] -- 
[Baritone] --
[Baritone] --
[Baritone] --
[Baritone] --
[Baritone] --
[Baritone] << | >> 1/1

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Justgamer101** [comment]
not helpfull, and is the schematic file even in the schematics folder?

**Comment by ehylo** [comment]
@Justgamer101  the error states that the schematic *could not be loaded* meaning it was found, just the schematic is likely broken, so they need to fix it as it's not a baritone issue, someone should close this.

**Comment by FringeWizard** [comment]
I have the same issue and don't get it I just made two different test schematics very simple ones to see it could build them and it just gives that same message.
