### ISSUE TITLE
Find should match the finding functionality of mine

### ISSUE THREAD

**Issue by flumperious** [cabaletta/baritone#3235]
## Describe your suggestion
According to issue #3167, the find command uses a cache dependent on BLOCKS_TO_KEEP_TRACK_OF. Instead, it should use the same finding functionality of the mine command, but without breaking the target blocks (perhaps with an optional setting to stop breaking blocks or moving to discover). It would also be helpful to display the find results as an overlay instead of coordinates.

## Settings
findInPlace - forces baritone not to move while finding
findWithoutBreakingBlocks - forces baritone not to break blocks when finding (similar to #blocksToAvoidBreaking)
findOnlyVisible - forces baritone to only highlight blocks that are visible (similar to #legitMine)

## Context
This would improve baritone by allowing players to find blocks other than the limited selection in BLOCKS_TO_KEEP_TRACK_OF, and allow them to manually mine ores that baritone finds. The overlay would be useful in allowing players to prioritize larger clumps of desired blocks.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You know you can just do `#goto <block>`?

**Comment by flumperious** [comment]
@ZacSharp I did not, no, I thought it only accepted coordinates as arguments. I suppose a combination of `#goto` and `#blocksToAvoidBreaking` would do what I want then. Is there also a setting that makes baritone not move?

**Comment by ZacSharp** [comment]
No, it has already been suggested and so far did become a feature.

Also `blocksToAvoidBreaking` increases the cost of breaking the specified blocks and you likely want `allowBreak` to completely prevent breaking blocks.

**Comment by flumperious** [comment]
Alright, thanks
