### ISSUE TITLE
WorldBorder Setting For Baritone

### ISSUE THREAD

**Issue by OhNo2** [cabaletta/baritone#3236]
## Describe your suggestion
Allow users to input a WorldBorder setting centered at a certain point that will keep baritone from attempting to go beyond that worldborder radius.

## Settings
#set worldBorder [range] [center-x] [center-z]
(if no center X and Z are entered, it could center on the player)

## Context
A worldborder setting would allow baritone to not get stuck trying to mine past the worldborder on servers with a smaller worldborder. It will also allow players to leave baritone running AFK when near the worldborder without worrying about baritone getting stuck trying to mine a block that is unbreakable.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [ ] UwU

**Comment by scorbett123** [comment]
Baritone shouldn't try and path past the world border, is it possible you could send a video of this happening? is this happening just trying to mine a block the other side of the world border, or is it also attempting to path into the world border.

**Comment by idkamtehelpmepls** [comment]
is their a way i can use the world border command to set a block limit for baritone if so how would i ?

**Comment by scorbett123** [comment]
There is no command, it picks it up automatically from minecraft.

**Comment by idkamtehelpmepls** [comment]
kk

**Comment by idkamtehelpmepls** [comment]
what about attacking a mob?

**Comment by scorbett123** [comment]
baritone doesn't ever attack mobs

**Comment by idkamtehelpmepls** [comment]
do u know how to mine grey clay with it since i try to and it just doesnt do anything.

**Comment by idkamtehelpmepls** [comment]
stained clay to be exact
