### ISSUE TITLE
how do i disable autoswitch

### ISSUE THREAD

**Issue by idkamtehelpmepls** [cabaletta/baritone#3240]
im using baritone on hypixel for skyblock and yes its bypassing on hypixel how do i disable it to autoswitch or switch to a weapon etc?

**Comment by idkamtehelpmepls** [comment]
also is their a way i can make a border for baritone so it cant attack certian blocks?

**Comment by ZacSharp** [comment]
1. Don't use Baritone on Hypixel.
2. `disableAutoTool`
3. No
