### ISSUE TITLE
Layer

### ISSUE THREAD

**Issue by dimaneiron** [cabaletta/baritone#3241]
I use baritone and build schamatics on it, I can't figure out how to work with layers. Namely, I am trying to build a specific layer, I use startAtLayer, I write a layer, but it builds from 1 to 4, but does not specifically build 4. Because of this, it breaks 1, 2, 3, layer, or rather blocks that are not right. How to fix it? I want to build a specific layer, I have the schematics through worldedit .schem because it does not load from lightmatics

**Comment by dimaneiron** [comment]
SO?

**Comment by ZacSharp** [comment]
`buildInLayers` always includes all previous layers to prevent Baritone from breaking what it just finished.
You probably want to either edit your schematic to not contain the layers you don't want or to enable `buildOnlySelection` and select the layer you want with `#sel`.

**Comment by dimaneiron** [comment]
I chose this option but it builds something wrong, I can't understand if the layer is wrong or not according to the description of the coordinates

**Comment by dimaneiron** [comment]
I have 26 layers, 4 I built myself. I chose the area sel pos1 sel pos 2 for the 5th layer and set the build name and coordinates, but it doesn’t build what I need, maybe I need to activate some other settings?

**Comment by ZacSharp** [comment]
No, it's just `buildOnlySelection`, selecting the desired area in the world and starting the build at the correct position (i.e. where you would start it if you were building the whole thing).
