### ISSUE TITLE
Baritone randomly getting stuck while mining

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#3245]
When it mines blocks it sometimes gets randomly stuck shaking weirdly. It used to be able to unstuck itself repathing but it doesnt do that anymore. It gets stuck shaking into infinity. Is there anything i can do to solve this?
Sometimes it doesnt shake though.
I have a video attached (no shaking there this time - the shaking in the video is me moving my mouse - also in this video i manually paused and resumed with a hotkey. it didnt do that automatically)

https://user-images.githubusercontent.com/71498430/152330129-0194ef28-f285-4419-844f-cc0d776fd23d.mp4

.

**Comment by Justgamer101** [comment]
recreate the issue with this baritone, not meteor's

**Comment by ehylo** [comment]
meteor's baritone is identical to normal baritone, and this is caused by being in single player where the block reach distance is 4 blocks and baritone thinks its 4.5, simply do `#blockReachDistance 4.0`

**Comment by Tendas240** [comment]
i fixed it. it was the movementtimeout setting. it was set too high
