### ISSUE TITLE
Add the ability to be able to mine other blocks than ores

### ISSUE THREAD

**Issue by p9sq** [cabaletta/baritone#3246]
Instead of only having the ability to mine ores, have the ability to mine a specific block given, i.e: "#mine amethyst_block"

**Comment by wagyourtail** [comment]
already possible. did you not even check
on 1.12 it's `#mine log`
on 1.13+ it's `#mine oak_log`

**Comment by p9sq** [comment]
> already possible. did you not even check on 1.12 it's `#mine log` on 1.13+ it's `#mine oak_log`

I tried it on meteor client, but it didn't work. Maybe outdated version of baritone ig?

**Comment by wagyourtail** [comment]
if there's none of the ore in range it stops. use goto in that case

**Comment by ZacSharp** [comment]
`MineProcess` will also explore if `legitMine` is enabled and on more recent versions it will behave like `GetToBlockProcess` if `legitMine` is disabled (i.e. explore if `exploreForBlocks` is enabled, fail if it's not).
The versions in which non legit mining can explore are v1.8.2, v1.7.2 and you can build it yourself for 1.12.2 from master.
