### ISSUE TITLE
Boat support

### ISSUE THREAD

**Issue by Fabizocker456** [cabaletta/baritone#3248]
## Describe your suggestion
I'm suggesting boat support, not placing boats, simply swimming directly to your target when in a boat

## Settings
Maybe canBoat

## Context
Boats are buggy now

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Fabizocker456** [comment]
(btw I mean the "new" boat behaviour)

**Comment by ZacSharp** [comment]
> Things it may not ever have, from most likely to least likely =(
>   *  Boats

https://github.com/cabaletta/baritone/blob/master/FEATURES.md#future-features
