### ISSUE TITLE
Continue Task After Disconnection

### ISSUE THREAD

**Issue by redd2** [cabaletta/baritone#3250]
## Describe your suggestion
If a user is disconnected or leaves the game they can resume whatever task they were doing before they were disconnected.

## Settings
N/A

## Context
I was building a huge schematic file with baritone but was disconnected and when I re-joined I couldn't resume the build which is extremely frustrating.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #421
