### ISSUE TITLE
Viewing full help for a command prints global message

### ISSUE THREAD

**Issue by marioCST** [cabaletta/baritone#3253]
## Some information
Operating system: Windows 11 64x
Java version: 17.0.1
Minecraft version: Fabric 1.18.1
Baritone version: 1.8.2
Other mods (if used): cloth-basic-math, Iris, Mod Menu, Modern Beta Fabric, Sodium, Wurst

## How to reproduce
Type #help in chat, then click on any command to get the full help. This prints some weird message with help and the command you clicked on globally
Example message: <marioCST> <<e0d15f91-a765-4272-bc6e-1500d828e191>>help help

## Modified settings
No modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and fabric mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by marioCST** [comment]
In the <> from the example message should be the user name and then a random UUID

**Comment by scorbett123** [comment]
This is an incompatibility with wurst, remove wurst and then clickable commands will work.
