### ISSUE TITLE
Cobweb not find

### ISSUE THREAD

**Issue by SilentWinjah77** [cabaletta/baritone#3257]
## What do you need help with?
I tried using command "#mine cobweb" but does nothing. Baritone walk like crazy path and never find cobweb to mine

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Justgamer101** [comment]
1. no webs in area
2. #mine web
3. why use baritone to do something so simple, lazy?

**Comment by SilentWinjah77** [comment]
> 1. no webs in area
> 2. #mine web
> 3. why use baritone to do something so simple, lazy?

1) done. I already go to mineshaft and stand exactly in front of cobweb
2) done. I use both command #mine web and #mine cobweb
3) main purpose is to find cobweb near to where i stand at mineshaft and mine it all without left it some. Not lazy man. Its like "#mine diamond_ore". Why need baritone if can mine all day. Main purpose is to find item im wanted

**Comment by Justgamer101** [comment]
what version of baritone, fabritone?

**Comment by Justgamer101** [comment]
try this, sel the area with webs and run #sel r web air

(or cobweb)

**Comment by wagyourtail** [comment]
failed to reproduce, please fill out the bug-report template properly...
![Peek 2022-02-10 15-23](https://user-images.githubusercontent.com/6234704/153506803-068e1f21-e6f0-4890-8771-9cf2d44be5d7.gif)

**Comment by SilentWinjah77** [comment]
Thank you so much for response. I will make a new bug issue with proper template
