### ISSUE TITLE
Quick stats

### ISSUE THREAD

**Issue by DEV0616** [cabaletta/baritone#3258]
So whats the difference in RAM before Baritone and after baritone active my data is shit.

**Comment by Justgamer101** [comment]
ram before baritone is the ram before baritone and ram after baritone is ram after baritone
hope this helps

**Comment by wagyourtail** [comment]
so before baritone, Minecraft recommends at least 512mb ram on 32 bit processors and 2gb on 64 bit.

and with baritone the reccomended 32 bit value no longer works so you'll need at least 896 mb for it to work. (tested on fabric 1.18 with just baritone installed)

hope this helps
