### ISSUE TITLE
Pause path if user is panicking

### ISSUE THREAD

**Issue by SylveonBottle** [cabaletta/baritone#326]
![image](https://user-images.githubusercontent.com/17802843/52152483-25779d00-263c-11e9-9594-5c490cb6f260.png)

 Pressing WASD should pause the current path, allowing user to make manual adjustments to baritone's path or to do something else they deem is more important - such as quickly running back to grab something, kill a mob, or run from a skeleton that baritone is getting a bit too close to.

A possible sub-feature to this could be re-pathing once the user stops moving, allowing baritone to continue on it's merry way. This method could allow for fine-tune adjustments in baritone's path to allow the user to quickly do something (such as tower up a bit), then allow baritone to take over afterwards. 

`wasdoverride` / `allowinterruption`  /  `resumepathonidle`
-

**Comment by PlasmaHH** [comment]
Did this make it into 1.8.3? Can't seem to find it there...
