### ISSUE TITLE
suspicious third party website

### ISSUE THREAD

**Issue by JacksonChen666** [cabaletta/baritone#3260]
found [this website](https://baritoneminecraft.com/). the blog is unrelated, most of the pages seem like templates (whytf do you need terms and privacy policy for a mod that doesn't deal with much PII).
also, blogs about completely unrelated things? absolutely.
unique blog content? possibly.
impersonators? maybe. it definitely is using baritone and minecraft in it's name.

**Comment by Justgamer101** [comment]
prob this guy's site. close this issue, the site seems fine. takes u to official download page. just some dumb blog abt barione after watching one of fit's videos

**Comment by JacksonChen666** [comment]
@Justgamer101 who's "this guy"?
