### ISSUE TITLE
1.16.5 can't escape lava

### ISSUE THREAD

**Issue by SuperIsakSwahn** [cabaletta/baritone#3268]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

When i play against the terminator from dream & georges manhunt it has no idea how to escape when stuck in lava, but when they played it did and im pretty sure they played on 1.15.2 (Im using 1.16.5), why does that happen?
## Final checklist
- [poop] I know how to properly use check boxes 
- [Yeen] I have not used any OwO's or UwU's in this issue.
- [Yeen] You will tell me if theres more details I need to mention

**Comment by SuperIsakSwahn** [comment]
> not funny

Exactly, so help

**Comment by Justgamer101** [comment]
fix baritone then

**Comment by scorbett123** [comment]
@Justgamer101 you're really starting to piss me off with your unhelpful comments, either help or go away

**Comment by Justgamer101** [comment]
cope

**Comment by ZacSharp** [comment]
Baritone can't move in lava and the problem is known since quite a while now (see #284)

**Comment by SuperIsakSwahn** [comment]
Wdym george knocked the bot and it could escape

**Comment by ZacSharp** [comment]
Did you really see it swim out of the lava?
The video description says they used Baritone with Impact and a custom server plugin. Impact can allow Baritone to walk *on* lava and the plugin could be anything.

**Comment by SuperIsakSwahn** [comment]
It definitely didnt walk on lava, and the plugin was MinecraftTerminator
for infinite health and blocks and durability
