### ISSUE TITLE
Baritone in python?

### ISSUE THREAD

**Issue by NovaProtocol** [cabaletta/baritone#3274]
## Describe your suggestion
As of now, I'm using pycraft but is there a way to interact with baritone with python?

## Final checklist
- [ ] Choose a language that doesn't suck.
- [ ] Make sure that the question is understandable.
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
There is no direct way, however you may be able to send chat messages from pycraft which could be baritone commands.

**Comment by Justgamer101** [comment]
the language literally says java
