### ISSUE TITLE
Any way to disable the "[Baritone] You're trying to press this mouse button but I won't let you"

### ISSUE THREAD

**Issue by Slimerblue22** [cabaletta/baritone#328]
Using the latest forge version that was released about 11 hours ago (so probably latest?). Basically it won't let me eat or do anything else while pathing, I'm guessing this is to prevent the player from messing up the path, but it's also preventing me from eating or doing anything else without canceling the path first.

**Comment by leijurv** [comment]
Yeah... It's complicated. Will try and find a middle ground on that. Perhaps just right click. Or maybe that prevention only occurs while in freecam

**Comment by leijurv** [comment]
Fixed in v1.1.1, release should be up in ~10 minutes.

**Comment by leijurv** [comment]
Sorry, wasn't actually fixed in v1.1.1 lmao, fixed for real in v1.1.2.
