### ISSUE TITLE
Can you use  specific item for farming? 

### ISSUE THREAD

**Issue by TurgutHarunArslan** [cabaletta/baritone#3286]
**I want to use hoe for .baritone farm Command how can i do**

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Justgamer101** [comment]
farming doesn't auto till

**Comment by ZacSharp** [comment]
And in case you just want to break the crops with a hoe, turn off `autoTool` and select the tool yourself.

**Comment by TurgutHarunArslan** [comment]
> And in case you just want to break the crops with a hoe, turn off `autoTool` and select the tool yourself.

how ?

**Comment by Justgamer101** [comment]
#autoTool false

hold hoe
