### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by ThebestkillerTBK** [cabaletta/baritone#3290]
## Some information
Operating system: Windows 10 X64
Java version: openjdk 18-beta 2022-03-22
Baritone version: 1.18.1 branch

## Exception, error or logs

FAILURE: Build failed with an exception.

* What went wrong:
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\User\\.gradle\caches\jars-9\4a8545a6fe0b6d524b72b32bec2fe1d8\buildSrc.jar.
> org.gradle.api.GradleException: Failed to create Jar file C:\Users\User\\.gradle\caches\jars-9\4a8545a6fe0b6d524b72b32bec2fe1d8\buildSrc.jar.

BUILD FAILED in 1s
2 actionable tasks: 2 executed

What I know so far, It seems gradle cannot create the baritone task jar.

## How to reproduce
Just build it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Use java 17

**Comment by ThebestkillerTBK** [comment]
It worked
