### ISSUE TITLE
Baritone is not working when i enter a command when im on 1.18.2 version

### ISSUE THREAD

**Issue by EJGamer** [cabaletta/baritone#3295]
## Some information
Operating system: Geforce RTX Intelcore i5
Java version: 1.18.2
Minecraft version: 1.18.2
Baritone version:1.8.2
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Baritone not currently working on 1.18.2, however a fix in currently in the work.
