### ISSUE TITLE
Help menu page switch bug

### ISSUE THREAD

**Issue by Mishaneck** [cabaletta/baritone#3297]
When trying to switch pages in help menu it says this in chat
https://user-images.githubusercontent.com/88834761/156934912-ccd07661-df99-4366-a314-16bd3dd1c79c.png
1.18.1 fabric

**Comment by scorbett123** [comment]
Are you using wurst client?

**Comment by Mishaneck** [comment]
yes

**Comment by scorbett123** [comment]
Remove wurst then, it will then work.

**Comment by Mishaneck** [comment]
Okay, is there any other way to switch between pages?

**Comment by scorbett123** [comment]
I don't think so, however this page should have all of the same content.

**Comment by scorbett123** [comment]
[here](https://github.com/cabaletta/baritone/blob/master/USAGE.md) sorry, didn't format it correctly.
