### ISSUE TITLE
1.18.2 Most Commands Return Error

### ISSUE THREAD

**Issue by timhow38** [cabaletta/baritone#3300]
## Some information
Operating system: Windows 11
Java version: Ver 8 Update 321 - Build 1.8.0_321-b07
Minecraft version: 1.18.2
Baritone version: v1.18
Other mods (if used): Solium and Fabric Installer 1.18.2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/8193773/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Anytime I use commands to mine or clear an area the game responds with:
***An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues***
![Screenshot 2022-03-07 124755](https://user-images.githubusercontent.com/35541279/156947597-29c56fce-c965-4016-ac26-f57cf3cf5586.png)

## Modified settings
To get the modified settings run `#modified` in game
Running this command returns a list with nothing modified

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dinoeyad** [comment]
+1

**Comment by wagyourtail** [comment]
duplicate #3295 #3299
