### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ItsNotYT** [cabaletta/baritone#3302]
## Some information
Operating system: windows 10
Java version: ?
Minecraft version:1.18.2
Baritone version: 1.8.2
Other mods (if used): litematica and malilib 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
!

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
#2603 just do '#mine grass block'
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
![Annotation 2022-03-07 202745](https://user-images.githubusercontent.com/101155751/157147527-1876af31-e7c4-4175-afb3-26f0bf927891.png)

**Comment by sportshead** [comment]
Did you mean to do `#mine grass_block`?

**Comment by wagyourtail** [comment]
duplicate #3300 #3299 #3295 #3292
