### ISSUE TITLE
Is there any way to set it so it stops when my inventory is full?

### ISSUE THREAD

**Issue by TapTrap2090** [cabaletta/baritone#3304]
I am setting up baritone to mine a perimeter but don't what to loose any blocks, is there any way to pause if the inventory is full so i can empty it and the to #resume?

**Comment by ZacSharp** [comment]
You can try using a macro mod to automatically pause it or you can try using a mod to automatically throw out the items you don't need.
When writing java code is not a problem you can also add a process to take control and get rid of the items in some way, which I have done for myself (tailormade for a  private 1.16.5 and not meant for others so likely not useful or useable for you).
