### ISSUE TITLE
Baritone automine and goto not working for 1.18.2 on servers

### ISSUE THREAD

**Issue by Toasties4720** [cabaletta/baritone#3305]
## Some information
Operating system: macOS
Java version: N/A
Minecraft version: 1.18.2
Baritone version: 1.8.2

happens whenever I try to use auto mine or goto for any block on a 1.18.2 server, it says "an unhandled exception occurred, the error is in your games log"
only started happening in 1.18.2 and every other command works fine, my only modified setting is legitmine set to true.

**Comment by wagyourtail** [comment]
duplicate #3302 #3300 #3299 #3295 #3292
