### ISSUE TITLE
disable rendercachedchunks in singleplayer

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#331]

**Comment by leijurv** [comment]
just turn it off broo

**Comment by SuperOP535** [comment]
y e s !

**Comment by leijurv** [comment]
its god damn glitchy lmao

**Comment by 0-x-2-2** [comment]
u could check if its the client or server world

**Comment by leijurv** [comment]
that sounds really complicated and difficult

**Comment by SuperOP535** [comment]
decrypt the json channel (((((((udp)))))) packets. reverse it 2 times to get decrypted string where it should show 0 for server and 255 for client (unsigned byte)

**Comment by leijurv** [comment]
yeah we gotta make sure json is involved somehow, otherwise we aren't truly being epic gamers

**Comment by 0-x-2-2** [comment]
😻
