### ISSUE TITLE
Baritone crashing when standing on an Immersive Engineering storage crate

### ISSUE THREAD

**Issue by Xplodin** [cabaletta/baritone#3310]
## Some information
Operating system: Windows 10
Java version: 16 and 8
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): 
Vault Hunters modpack
https://vault-hunters.fandom.com/wiki/Mods
## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.mi
[crash-2022-03-08_23.49.57-client.txt](https://github.com/cabaletta/baritone/files/8213634/crash-2022-03-08_23.49.57-client.txt)
necraft/logs/`

[2022-03-08-5.log](https://github.com/cabaletta/baritone/files/8213664/2022-03-08-5.log)
[debug-5.log](https://github.com/cabaletta/baritone/files/8213666/debug-5.log)

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
jump on an immersive engineering storage crate and watch your game crash lol
## Modified settings
To get the modified settings run `#modified` in game
N/A
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The stacktrace looks exactly like the one in #2148 but that issue should be fixed in v1.6.3

**Comment by wagyourtail** [comment]
no. that was merged after 1.6.3 released...

**Comment by AsdAsdAsd001** [comment]
> The stacktrace looks exactly like the one in #2148 but that issue should be fixed in v1.6.3

I can attest to the fact that it has not in fact been fixed xd

**Comment by ZacSharp** [comment]
Uh, I didn't see there's a one year gap. I saw the merge into 1.14.4 on Feb 1, the merge up into 1.16.5 on Feb 2 and the release on Feb 5...

**Comment by shinji257** [comment]
I'm seeing this as well.  Modpack Enigmatica 6 Expert.  Running Baritone 1.6.3 -- `baritone-api-forge-1.6.3.jar`

https://gist.github.com/shinji257/feb382ab2164b6d25615a94d23de0448

**Comment by wagyourtail** [comment]
so. I'm just gonna close this as this issue's already fixed in the "next" version

**Comment by Xplodin** [comment]
where can I get this next version?

**Comment by wagyourtail** [comment]
by going to the future, or building it manually.

**Comment by Skrrby** [comment]
> by going to the future, or building it manually.

still no new version, wasted time juice :(

**Comment by Xplodin** [comment]
Def could use a new version built instead of doing it ourselves. Not that theres anything wrong with doing that, but some people cant comprehend this kind of stuff.
