### ISSUE TITLE
Tunnelilng Issues on 1.18.2

### ISSUE THREAD

**Issue by Xanthus58** [cabaletta/baritone#3311]
## Some information
Operating system:Windows 11
Java version:Unknown
Minecraft version:1.18.2
Baritone version:1.8.2
Other mods (if used):OptiFine_1.18.2_HD_U_H6_pre1_MOD Forge 40.0.12

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/8227870/latest.log)

Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Go as far down as you can in 1.18.2 into a cave; and type `#tunnel 2 2 5` (i was just above bedrock level)
## Modified settings
To get the modified settings run `#modified` in game
Legitmine = True
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
update to baritone 1.8.3 for 1.18.2
