### ISSUE TITLE
What are the blue lines?

### ISSUE THREAD

**Issue by arnav7633** [cabaletta/baritone#3312]
Hey whenever I try to build anything a few minutes in it stops building and blue lines keep flashing all over what does this mean?
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by I-Got-You-Dead** [comment]
I believe it's just different paths it can take... (pls don't rely on this)

**Comment by ZacSharp** [comment]
With default settings the light blue line is the most recently considered path and the dark blue line is the best path found so far. The builder restarts pathing after every fail so if Baritone can't find a path it will retry over and over again. It won't recover by itself so unless you want to watch flickering lines you need to unstuck it yourself.
