### ISSUE TITLE
Can't mine things

### ISSUE THREAD

**Issue by TRRT004** [cabaletta/baritone#3318]
## Some information
Operating system: Windows 11
Java version: openjdk version "1.8.0_302"
Minecraft version: 1.18.2
Baritone version: baritone-1.18-SNAPSHOT

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/8240425/latest.log)
An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
baritone.api.command.exception.CommandUnhandledException: java.lang.NoClassDefFoundError: net/minecraft/class_3296

## How to reproduce
Write #mine something in chat

## Modified settings
All modified settings:
allowDiagonalAscend (Boolean)
allowDiagonalDescend (Boolean)
allowInventory (Boolean)
allowOnlyExposedOres (Boolean)
allowParkour (Boolean)
allowParkourPlace (Boolean)
allowVines (Boolean)
assumeSafeWalk (Boolean)
blocksToAvoidBreaking (List<class_2248>)
breakFromAbove (Boolean)
followRadius (Integer)
freeLook (Boolean)
legitMine (Boolean)
legitMineIncludeDiagonals (Boolean)
maxFallHeightBucket (Integer)
maxPathHistoryLength (Integer)
mobAvoidanceCoefficient (Double)
mobAvoidanceRadius (Integer)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Update to 1.8.3
