### ISSUE TITLE
Trying to get baritone to mine something doesn't work 

### ISSUE THREAD

**Issue by itzzzjo** [cabaletta/baritone#3319]
** Trying to get baritone to mine doesn't work**  
Operating system: Windows 10 
Java version: 
Minecraft version: 1.18.2
Baritone version:  1.8.2
Other mods (if used):  

 [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] [Baritone] > mine diamond_ore
 [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[13Mar2022 21:54:23.114] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...

To Reproduce 
#mine diamond_ore 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Errorcrafter** [comment]
send the log file

**Comment by scorbett123** [comment]
Upgrade to baritone version 1.8.3, 1.8.2 is incompatible with mc 1.18.2
