### ISSUE TITLE
1.13 support when?

### ISSUE THREAD

**Issue by Mhowser** [cabaletta/baritone#332]
I was wondering if anyone knows what the status of getting Baritone working with 1.13 world format and up.

**Comment by leijurv** [comment]
Not until ForgeGradle 3.0 works

**Comment by Mhowser** [comment]
Ah ok, thanks!

**Comment by leijurv** [comment]
well forgegradle 3.0 works now but uhhhhhhhHHhhh mixin machine broke

**Comment by Mhowser** [comment]
What is forgegradle btw?

**Comment by leijurv** [comment]
Github.com/minecraftforge/forgegradle

**Comment by ZeroMemes** [comment]
Hey I did this.

**Comment by leijurv** [comment]
yes you did 😘
