### ISSUE TITLE
error in baritone with #mine, by Masterggb

### ISSUE THREAD

**Issue by Masterggb** [cabaletta/baritone#3321]
## Some information
Operating system: windows 11
Java version: idk
Minecraft version: 1.18.1 forge
Baritone version: 1.8.3
Other mods (if used): forge, but no other mods more than baritone

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[debug.log](https://github.com/cabaletta/baritone/files/8243526/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/8243527/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i did #mine eand then it said i had an arror in my logs and said to report here
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 

- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Downgrade to baritone 1.8.2 1.8.3 is ONLY compatible with 1.18.2
