### ISSUE TITLE
I cannot mine using baritone

### ISSUE THREAD

**Issue by AugustasPlo** [cabaletta/baritone#3322]
## Some information
Operating system: help i dont know what to do im trying to mine but it does not work please help
Java version: 17.0.1
Minecraft version: 1.18.2
Baritone version: 0.13.3
Other mods (if used): i did not use 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by AugustasPlo** [comment]
please help
how to fix this

**Comment by wagyourtail** [comment]
Upgrade baritone version
