### ISSUE TITLE
Speed compatability with baritone

### ISSUE THREAD

**Issue by Perry1900** [cabaletta/baritone#333]
As of now, if you turn a hop speed utility module on when using impact client when you use baritone, it hops like normal walk speed unless you walk normally (I didn't check with other speed hacks/clients).
I tried this on 2b2t but it wasn't the anticheat that prevented me from doing it (I didn't lag back), it was like I held w for half a second and then stopped for half a second.

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/issues/929#issuecomment-462857264
