### ISSUE TITLE
add so baritone can climb ladders

### ISSUE THREAD

**Issue by MalikPanter** [cabaletta/baritone#3330]
rn when I have tried baritone [v1.8.3] on 1.18.2 cant climb ladders it would be great if you guys could add that, or slap me and say that it can climb ladders :).

**Comment by wagyourtail** [comment]
:slap: it works

![Peek 2022-03-17 12-38](https://user-images.githubusercontent.com/6234704/158882340-79d8d073-822c-4bdb-ab72-0d89ac00f2a5.gif)


:stuck_out_tongue:

**Comment by MalikPanter** [comment]
av you slap so hard ;D
