### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by astelyy** [cabaletta/baritone#3333]
## Some information
Operating system: Windows 10 64bit
Java version: 8
Minecraft version: Forge 1.12.2
Baritone version: 1.2.15
Other mods (if used): KamiBlue, Impact, Rusherhack

## Exception, error or logs
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j

## How to reproduce
1. Open Minecrfaft
2. Instantly crashes

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [OwO] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
My guess is that you are running this with no verify, remove no verify and try again. You haven't sent a full log though so I can't be sure, if this isn't the case reply to this and I will reopen this issue.
