### ISSUE TITLE
Mining the center of the block

### ISSUE THREAD

**Issue by dalmatheo** [cabaletta/baritone#3335]
## What do you need help with?
Hello, i want to know if it's possible to make the baritone bot look at the center of a block before breaking it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If your question is the same as in #3060 the answer is the same as well, if not please clarify what you want to know.

**Comment by dalmatheo** [comment]
With smoothaim, the bot look more human, but the problem is the bot don't look the center of the block. The bot look the corner before breaking it and i just want to know if it's possible to fix that or not.

**Comment by wagyourtail** [comment]
seems to look at the center for me..
![Peek 2022-03-20 01-42](https://user-images.githubusercontent.com/6234704/159154757-86ede3f0-a829-4f33-a166-c6108decc1c5.gif)

**Comment by ZacSharp** [comment]
Only if it snaps onto the block, not if it is looking at it already (e.g. the second log in your gif).
With smooth head movement baritone always stops moving the head as soon as the bot is looking at the edge of the block but fixing this is not a problem for the official bugtracker (unless a smooth aim pr is merged ofc).
