### ISSUE TITLE
unhandled exeption

### ISSUE THREAD

**Issue by epixgaming1456** [cabaletta/baritone#3336]
## I tried running a command but it said to visit this website and report the error, which's name is in the title
Operating system: pc
Java version:?
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): 

## Exception, error, or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/8309925/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/8309926/debug.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in-game

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have included the version of Minecraft I'm running, baritone's version, and forge mods (if used).
- [x] I have included logs, exceptions, and/or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Steps to reproduce and the correct log would be nice to have.
In the logs you have uploaded I can't find any sign of Baritone being installed.

**Comment by wagyourtail** [comment]
you can only `#follow` players who are in range
if it's something else upload the correct logs / steps to reproduce and we'll re-open the issue.
