### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by tomecko1** [cabaletta/baritone#3337]
## Some information
Operating system:Windows 10 Home
Java version: 17
Minecraft version:1.18.2
Baritone version: lastest
Other mods (if used): 
[latest.log](https://github.com/cabaletta/baritone/files/8309978/latest.log)

Hi a have problem with mine command.

**Comment by ZacSharp** [comment]
You need to update to Baritone v1.8.3. 
v1.8.2 only works on Minecraft 1.18.1 (and v1.8.3 only on mc 1.18.2)
