### ISSUE TITLE
Help commands work but mine doesn't 

### ISSUE THREAD

**Issue by bananamanzs** [cabaletta/baritone#3338]
When i use baritone's other commands they work fine but when i used the mine commands all i get is an unhandled exception occurred. the error is in your game's log. Any way to fix this?

**Comment by wagyourtail** [comment]
> Please fill out the issue template properly.
> 
> Fill out the requested information
> 
>     * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)

my guess is that you have incompatibility whilst upgrading to minecraft 1.18.2, if you are playing 1.18.1, or 1.18 please use baritone version 1.8.2, for 1.18.3 use baritone version 1.8.3
