### ISSUE TITLE
An unhandled exception occurred, the error is in your games log.

### ISSUE THREAD

**Issue by whyeee** [cabaletta/baritone#3339]
When trying to mine or goto or do any command it says, An unhandled exception occurred, the error is in your games log.
And it said to report the problem to your GitHub page, so can you help me figure out what is making it so that i cant do a simple command like #mine oak_log.
Mac: `/Library/Application\ Support/Minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
This is probably due to an incompatibility whilst upgrading to minecraft 1.18.2, if you are playing 1.18.1, or 1.18 please use baritone version 1.8.2, for 1.18.2 use baritone version 1.8.3.

If you are using the correct version please attach the debug.log as this contains some more useful information.

**Comment by whyeee** [comment]
thank you

**Comment by Kio538** [comment]
i loaded some mods such as freecam and zoom appleskin and etc and when i join and try to use it it says the error

**Comment by AspiJoeStar** [comment]
i'm having the same issue with baritone 1.21.1 rn with the version 1.11.2
