### ISSUE TITLE
Add a way to delete user defined waypoints

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#334]
Thanks Chronic-Reflexes#9251

**Comment by ZeroMemes** [comment]
LMFAO

**Comment by ZeroMemes** [comment]
So basically I’m contributor

**Comment by leijurv** [comment]
@0-x-2-2 pwease make pr updating documentation (both USAGE.md and examplebaritonecontrol help) that lists this command uwuwuwuwwu

**Comment by 0-x-2-2** [comment]
did someone say puww wequest

**Comment by MMK21Hub** [comment]
No need for this- you have `#help`. re-close?

**Comment by aaronfranke** [comment]
Is this available in Minecraft 1.12.2?
