### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Alane5** [cabaletta/baritone#3348]
## Some information
Operating system:win 10
Java version:Version 8 Update 321
Minecraft version:1.18.2
Baritone version:baritone-api-forge-1.8.2
Other mods (if used): forge

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/8323128/latest.log)

**Comment by wagyourtail** [comment]
See pinned issue.
