### ISSUE TITLE
Whats your ign

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [cabaletta/baritone#335]
lol, i heard you wanted credit in wwe mod, so whats your name in minecraft so i can add you to the credits/if you dont want your ign in the credits, what name do you want in the credits and what image, circular or not, if you dident want credit in wwe mod and i was lied to say so....

Please respond asap, if you dont... ill put in a question mark image for now(not trying to found rude just saying im in a rush)

**Comment by THEREALWWEFAN231** [comment]
Also i know this isent a issue, i just dont know a way to contact you, sorry

**Comment by leijurv** [comment]
Lol my ign is leijurv too, snag my profile pic from my discord @leijurv#5021 thx =)
