### ISSUE TITLE
mine command not working 

### ISSUE THREAD

**Issue by ZGNet** [cabaletta/baritone#3365]
## Some information
Operating system: win 10
Java version:1.8.0_321
Minecraft version:1.18.2
Baritone version:baritone-standalone-forge-1.8.2
Other mods (if used): OptiFine_1.18.2_HD_U_H6

[debug.log](https://github.com/cabaletta/baritone/files/8383089/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/8383108/latest.log)

## How to reproduce
use "#mine minecraft:diamond_ore" command

## Modified settings
allowSprint false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You are using an incompatible version of Baritone (see issue 3339).
Baritone v1.8.2 is for Minecraft 1.18.1, Baritone 1.18.3 is for Minecraft 1.18.2.
