### ISSUE TITLE
Can't see any outlines, no paths ect

### ISSUE THREAD

**Issue by JustGregShared** [cabaletta/baritone#3367]
## Some information
Java version: 1.18.2
Baritone version: baritone-standalone-fabric-1.8.3
Other mods (if used): optifine/optifabric

I've tried many other versions of baritone but they all have the same issue, one time it did start showing the outlines and paths but then it randomly stopped again, any reason to this and any possible fixes?

**Comment by Mathrandom7910** [comment]
why use optifabric when a much better sodium is available? with iris shaders now, there's no point not to use sodium
