### ISSUE TITLE
[QUESTION] How do i disable this?

### ISSUE THREAD

**Issue by ItzVaio** [cabaletta/baritone#3376]
How do I disable where it keeps on placing random stuff such as pickaxes, axes, cobblestone and dirt in my hotbar? It's very annoying.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
It places items in your hotbar to use them, if you don't want baritone to use items from you inventory disable allowInventory
