### ISSUE TITLE
Game Crashing When Opening a Replay File in Replay mod

### ISSUE THREAD

**Issue by RU-B0** [cabaletta/baritone#3381]
just to get it over with
"UwU"

## Some information
Operating system: Windows 10
Java version: 17.1?
Minecraft version: 1.18.2
Baritone version: 1.8.3
Other mods (if used): better f3, in game account switcher, malilib, minihud, modmenu, optifabric, replaymod, shulkerboxtooltip, Windowed Fullscreen, worldedit
 (Ik this has been mentioned before about this.a etc -its the same issue-)
## Exception, error or logs

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "a" because "this.a" is null
Exit Code: -1
[crash-2022-04-06_20.30.23-client.txt](https://github.com/cabaletta/baritone/files/8438934/crash-2022-04-06_20.30.23-client.txt)

## How to reproduce
Run replaymod and baritone at the same time
[debug.log](https://github.com/cabaletta/baritone/files/8438926/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/8438927/latest.log)

## Modified settings
allowParkour:true
allowParkourplace:true
blockPlacementPenalty:0
blocksToAvoidBreaking:bedrock
jumpPenalty:0
walkOnWaterOnePenalty:100

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3255 

this is already patched for the next version, the fix is on the 1.17.1 branch from after the 1.7.2 release so it isn't out in any release yet
