### ISSUE TITLE
Baritone does not mine or's and doesn't detect it

### ISSUE THREAD

**Issue by ZacLiiscool** [cabaletta/baritone#3383]
## Some information
Operating system: mac
Java version:  fabric 
Minecraft version: 1.18.2 
Baritone version: most new
Other mods (if used): 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
cant reproduce, please fill out the issue template completely.

**Comment by ZacLiiscool** [comment]
??? iu dont understand

**Comment by wagyourtail** [comment]
you didn't post logs, didn't post `#modified`, or any screenshot or anything. so all I can do is go and test baritone and say that it works for me

**Comment by ZacLiiscool** [comment]
ok leme see

**Comment by ZacLiiscool** [comment]
10:55:46.121
Started 2 worker threads
10:55:46.845
Stopping worker threads
10:55:46.848
Started 2 worker threads
10:55:48.059
Stopping worker threads
10:55:48.061
Started 2 worker threads
10:56:00.997
[STDOUT]: 3010304 movements considered
10:56:00.998
[STDOUT]: Open set size: 18614
10:56:00.998
[STDOUT]: PathNode map size: 155446
10:56:00.998
[STDOUT]: 34190 nodes per second
10:56:00.998
[STDOUT]: Warning: cost coefficient is greater than three! Probably means that
10:56:00.998
[STDOUT]: the path I found is pretty terrible (like sneak-bridging for dozens of blocks)
10:56:00.998
[STDOUT]: But I'm going to do it anyway, because yolo
10:56:00.998
[STDOUT]: Path goes for 56.142675390472796 blocks
10:56:12.362
Stopping worker threads
10:56:12.365
Started 2 worker threads

**Comment by ZacLiiscool** [comment]
<img width="1440" alt="Screen Shot 2022-04-09 at 10 57 14 AM" src="https://user-images.githubusercontent.com/98473212/162553926-cd83314a-2f21-4b1d-97fa-4bf240062b4a.png">

**Comment by ZacLiiscool** [comment]
<img width="1440" alt="Screen Shot 2022-04-09 at 10 56 21 AM" src="https://user-images.githubusercontent.com/98473212/162553945-91e0a8c8-fb8d-430a-af18-9fcae8f70b07.png">

**Comment by wagyourtail** [comment]
I'd guess you have `#legitMine` on

**Comment by ZacLiiscool** [comment]
o ok le em se e thanks anyways also what do #legitMine do?

**Comment by ZacLiiscool** [comment]
o it works thx

**Comment by scorbett123** [comment]
> > o ok le em se e thanks anyways also what do #legitMine do?
> 
> it only mines exposed ores

No, allowOnlyExposed ores does this, legit mine will only mine ores which the player can see
