### ISSUE TITLE
Baritone Not Moving or Mining

### ISSUE THREAD

**Issue by Darwin-Ford** [cabaletta/baritone#3384]
## Some information
Operating system: ios Big Sur
Java version: Idk it says java
Minecraft version: 1.18.1
Baritone version: Latest
Other mods (if used): Immersive Portals, Fabric API, Replay Mod, WorldEdit.

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
https://paste.ee/p/L7Vs3

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I used #mine, #sel cleararea
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You say you are using latest Baritone which currently is v1.8.3 and which only works for Minecraft 1.18.2 (and newer) so can you please try using Baritone v1.8.2?
If that's not the problem please tell me and upload the correct log, the one you uploaded doesn't show any sign of Baritone being installed at all.
