### ISSUE TITLE
Suggestion: Option to fill in blocks when tunneling

### ISSUE THREAD

**Issue by partridge420x** [cabaletta/baritone#339]
When you use .goto (coords) when it starts digging through places, i think it would be a cool option to add the ability to fill in blocks behind you when you start tunneling through. Possible impact 4.5 feature?
Depeding on if you guys decide to update the api that impact uses to include the new things you've added thus far

**Comment by Haxified** [comment]
That would be madd

**Comment by leijurv** [comment]
Started doing some stuff on the `backfill` branch but I think my approach is all wrong and I might start over lol

I'll try and make this happen tho

**Comment by Haxified** [comment]
mad

**Comment by Haxified** [comment]
@leijurv any updates? $3 ez cash money rn if u make it kek

**Comment by S-B99** [comment]
This is now a thing, the `#backfill` setting
