### ISSUE TITLE
1.18.2 baritone can't jump

### ISSUE THREAD

**Issue by Cyr3xHvH** [cabaletta/baritone#3390]
Tried with diffirent clients but some results 
when i enter a command the ai is not jumping

**Comment by scorbett123** [comment]
I've just helped someone on the baritone discord with this issue.

Is it possible for you to send me .minecraft/baritone/settings.txt?

**Comment by Cyr3xHvH** [comment]
assumeStep true
blockReachDistance 4.5
pathingMapLoadFactor 0.75
maxFallHeightNoWater 255
primaryTimeoutMS 500
failureTimeoutMS 2000
planAheadPrimaryTimeoutMS 4000
planAheadFailureTimeoutMS 5000
slowPathTimeoutMS 40000
toastTimer 5000
pathRenderLineWidthPixels 5.0
goalRenderLineWidthPixels 3.0
cachedChunksOpacity 0.5
mineDropLoiterDurationMSThanksLouca 250
legitMine true
followOffsetDirection 0.0
colorCurrentPath 255,0,0
colorNextPath 255,0,255
colorBlocksToBreak 255,0,0
colorBlocksToPlace 0,255,0
colorBlocksToWalkInto 255,0,255
colorBestPathSoFar 0,0,255
colorMostRecentConsidered 0,255,255
colorGoalBox 0,255,0
colorInvertedGoalBox 255,0,0
colorSelection 0,255,255
colorSelectionPos1 0,0,0
colorSelectionPos2 255,200,0
selectionOpacity 0.5
selectionLineWidth 2.0

**Comment by wagyourtail** [comment]
it's because you have `#assumeStep` on
