### ISSUE TITLE
my minecraft (forge) server crashes

### ISSUE THREAD

**Issue by MrFrast** [cabaletta/baritone#3395]
hello, I wanted to see if they could solve my problem, I want to start my minecraft server with mods and it doesn't start, I don't understand what the problem is and I wanted to see if someone could help me, greetings from now. 

the host is shockbyte

`16.04 07:15:05 [Multicraft] Loading server properties
16.04 07:15:05 [Multicraft] Starting server!
16.04 07:15:05 [Multicraft] Loaded config for "Forge 1.16.5 - 36.2.30 (Latest)"
16.04 07:15:08 [Multicraft] Updating eula.txt file
16.04 07:15:09 [Server] INFO WARNING: Error loading config file: .dockercfg: $HOME is not defined
16.04 07:15:09 [Server] INFO WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
16.04 07:15:10 [Server] INFO 2022-04-16 07:15:10,700 main WARN Advanced terminal features are not available in this environment
16.04 07:15:10 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.30, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
16.04 07:15:10 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_275 by Oracle Corporation
16.04 07:15:11 [Server] main/INFO [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
16.04 07:15:11 [Server] main/INFO [op.OptiFineTransformationService/]: OptiFine ZIP file: /mods/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar
16.04 07:15:11 [Server] main/INFO [op.OptiFineTransformer/]: Target.PRE_CLASS is available
16.04 07:15:11 [Server] main/INFO [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
16.04 07:15:11 [Server] main/INFO [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
16.04 07:15:11 [Server] main/INFO [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
16.04 07:15:13 [Server] main/INFO [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 2:141 token recognition error at: ';'
16.04 07:15:13 [Server] main/INFO [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
16.04 07:15:13 [Server] main/INFO [op.OptiFineTransformer/]: Targets: 308
16.04 07:15:14 [Server] INFO Init CMDCam coremods ...
16.04 07:15:14 [Server] INFO Init CreativeCore coremods ...
16.04 07:15:14 [Server] main/INFO [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
16.04 07:15:14 [Server] main/ERROR [mixin/]: Mixin config epicfight.mixins.json does not specify "minVersion" property
16.04 07:15:14 [Server] main/ERROR [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
16.04 07:15:14 [Server] main/INFO [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
16.04 07:15:14 [Server] main/WARN [mixin/]: Reference map 'musictriggers.refmap.json' for musictriggers.mixin.json could not be read. If this is a development environment you can ignore this message
16.04 07:15:14 [Server] main/WARN [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
16.04 07:15:15 [Server] main/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
16.04 07:15:15 [Server] main/WARN [mixin/]: Error loading class: net/minecraft/client/gui/screen/Screen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER)
16.04 07:15:15 [Server] main/WARN [mixin/]: @Mixin target net.minecraft.client.gui.screen.Screen was not found equipmentcompare.mixins.json:ScreenMixin
16.04 07:15:16 [Server] main/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
16.04 07:15:16 [Server] INFO Exception in thread "main" [07:15:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 7 more
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.ExceptionInInitializerError
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.Main.main(Main.java:91)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:185)
16.04 07:15:16 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 17 more
16.04 07:15:17 [Multicraft] Server shut down (starting)
16.04 07:15:17 [Multicraft] Restarting crashed server in 10 seconds
16.04 07:15:17 [Multicraft] Looks like a crash, check the server console. Return value: 1
16.04 07:15:17 [Multicraft] Server stopped
16.04 07:15:19 [Multicraft] Received stop command
16.04 07:15:19 [Multicraft] Server stopped`

**Comment by scorbett123** [comment]
This isn't a problem with baritone. Baritone is also a client side only mod, it won't work if installed on the server instead.
