### ISSUE TITLE
Automated testing framework

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#34]
This might tie in with #20 

I'm thinking both small scale (almost like unit tests) and large scale.

Small scale would be like "in this scenario of blocks, this movement should be COST_INF". However, that would be really time-consuming to create for not much benefit. I think larger scale integration-style tests give way more bang for you buck (the amount of functionality it tests vs how time consuming it is to write).

Perhaps something like "can the bot path from 0,0 to 1000,1000 in a world generated from seed _____ within X minutes without taking damage?"

**Comment by leijurv** [comment]
Bonus points if we can get travis or circle to run headless (or normal) minecraft to do this.

Extra extra bonus points if we can get a screen recording of if/when it fails.

**Comment by leijurv** [comment]
Related to #52

**Comment by HowardStark** [comment]
Related to #1, which is stale.

**Comment by leijurv** [comment]
This is merged
