### ISSUE TITLE
crash on modpack ATM6 - Tinkerers beware! Could happen on other packs too.

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [cabaletta/baritone#3402]
## Some information
Operating system: Linux Mint 20 x86-64 /// kernel 5.4.0-107-generic
Java version: OpenJDK 11 JRE (
Minecraft version: 1.16.5 (Forge 36.2.31)
Baritone version: 1.6.3 (for 1.16.5)
Other mods (if used): AllTheMods 6 (plus MorePlayerModels, Controllable.

## Exception, error or logs
see attached file...
[crash-2022-04-17_01.00.07-client.txt](https://github.com/cabaletta/baritone/files/8501098/crash-2022-04-17_01.00.07-client.txt)

## How to reproduce
Play normally ingame and achieve the usual modded progression. Eventually this sneaks up like a creeper and bites you in the ass, making the world unplayable as it creates this crash every time you relaunch and attempt to play again. I'm not a Minecraft Crashlog-whisperer so idunno what else to say other than this is what happened to me.

## Modified settings
Unable to acquire this as the game is now rendered unplayable due to the crash report attached above. If you have an alternative external method, please get back to me. it should mostly be stock though...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
- [x] Above checklist item is STILL impossible to check off due to a technicality and my logical thinking. (my logic is a bit trash)
- [x] Depressed

**Comment by wagyourtail** [comment]
duplicate (and fixed for a future release) of #2148, #3067

**Comment by S0LiD-ST4T3** [comment]
I don't see any similarities to #2148 nor #3067 at all. This is a render thread crash, is it not?

**Comment by wagyourtail** [comment]
func_196952_d is getCollisionShape

**Comment by S0LiD-ST4T3** [comment]
i didn't even know that... :/

**Comment by S0LiD-ST4T3** [comment]
since i'm impatient as fuck and you guys have a 10 minute minimum to send messages on your discord, have you got any workarounds for the issue on my current installed version? or am i stuck with uninstalling baritone for now?
