### ISSUE TITLE
Can Baritone Break Layer by Layer?

### ISSUE THREAD

**Issue by Todoroki3** [cabaletta/baritone#3403]
While clearing the 30x30x50 area, the Baritone digs a hole downwards, then lays blocks to break the blocks above and wastes time. I wonder if there is a command to break the first layer before going down and then pass it to a lower layer in order?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
![mine](https://user-images.githubusercontent.com/55604283/163725951-5e3582ee-1ddf-4d83-a2d4-9f1b79d1d1c9.png)

**Comment by Mathrandom7910** [comment]
set buildinlayers to true and layerorder to false.

**Comment by Todoroki3** [comment]
thank you for your answering

> set buildinlayers to true and layerorder to false.

I showed the error I got when I typed the buildinlayers true command while in the game. How can I solve that error?

**Comment by Mathrandom7910** [comment]
whats the error?
and to correct my previous comment, it should be setting layerorder to true so it starts from the top to the bottom

**Comment by scorbett123** [comment]
> I showed the error I got when I typed the buildinlayers true command while in the game. How can I solve that error?

You can toggle a boolean (true/false) setting by just typing #buildInLayers.
