### ISSUE TITLE
Unable to find any path to BlockOptionalMetaLookup

### ISSUE THREAD

**Issue by saint-boons** [cabaletta/baritone#3406]
## Some information
Operating system: macOS 12.3.1 (21E258) (Apple Silicon)
Java version: "18" 2022-03-22
Minecraft version: 1.18.2
Baritone version: 1.8.3
Other mods (if used): [Valhelsia Enhanced Vanilla Modpack](https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla)

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/8520939/latest.log)

## How to reproduce
Type #mine <any block>
The halo around blocks appears but the player doesn't move a centimetre

## Modified settings
chatControl -> false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Do you have a pickaxe in your inventory? Also can you get  to the blocks yourself, if you #mine, then #pause and go to the "halo" manually?

**Comment by saint-boons** [comment]
I do have a pickaxe yes

**Comment by scorbett123** [comment]
Can you get to the blocks if you move there manually? Baritone is thinking that it can't get to any of the blocks.

**Comment by scorbett123** [comment]
hmm, does it work on other worlds? or when the mod pack isn't installed?

**Comment by saint-boons** [comment]
It doesn't work in other world, but it works when the modpack is not installed. Would you happen have have a list of mods that conflict with baritone?

**Comment by scorbett123** [comment]
No, your best bet would be to remove half your mods, then test it, if it works with that half then the problem mod must be in the other half. Find the half with the problem mod, and then repeat the process with that half, until you find which mod is the problem, and then remove it.
