### ISSUE TITLE
Crash when trying to place blocks not presented on toolbar.

### ISSUE THREAD

**Issue by Halifay** [cabaletta/baritone#3407]
## Some information
Operating system: Ubuntu 20.04
Java version: 11.0.14.1
Minecraft version: 1.18.2
Baritone version: baritone-api-fabric-1.8.3
Other mods (if used): 
Log report is for TLauncher Fabric 1.18.2 (don't know what version). Also tried fabric loader 0.13.3 with the same result.
mods:
litematica-fabric-1.18.2-0.11.2,
malilib-fabric-1.18.2-0.12.1,
mousewheelie-1.8.8+mc1.18.2

## Exception, error or logs
log file:
[crash-2022-04-20_20.59.03-client.txt](https://github.com/cabaletta/baritone/files/8524643/crash-2022-04-20_20.59.03-client.txt)

## How to reproduce
"#sel fill block" with less blocks than needed. Game crashes when no blocks left on toolbar. One time game didn't crash when I had no blocks to start.

## Modified settings
avoidance: true,
blockReachDistance: 4.0,
buildInLayers: true,
itemSaver: true,
itemSaverThreshold: 50,
layerOrder: true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This has been fixed by #3308.

For a temporary fix remove buttons / levers / the like from your inventory.
