### ISSUE TITLE
baritone follow player doesnt work

### ISSUE THREAD

**Issue by blenls** [cabaletta/baritone#3408]
## Some information
Operating system:windows 10
Java version:latest
Minecraft version:1.16.5
Baritone version:idk
Other mods (if used): impact client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
i did #follow player (playername)

## Modified settings
chat control thats all

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have include
[latest.log](https://github.com/cabaletta/baritone/files/8531845/latest.log)
d logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[](url)

**Comment by scorbett123** [comment]
You need to make sure that the player is in your render distance
