### ISSUE TITLE
I want to add wool of a certain color to AutoMine, how can this be done? Tell me pleasePlease add a brief but descriptive title

### ISSUE THREAD

**Issue by Jekarus321** [cabaletta/baritone#3412]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you are on 1.12.2 you can mine for blocks with specific meta values by using `#mine namespace:block:meta` (e.g. `#mine minecraft:wool:3`) and in 1.13+ blocks with meta value have been split into individual blocks so every color is a different block (e.g. `#mine minecraft:red_wool` or `#mine yellow_wool`.
