### ISSUE TITLE
Cant load a schematic

### ISSUE THREAD

**Issue by Albiniii** [cabaletta/baritone#3414]
If I type in in the Chat #build `name of the schematic´. schematic it beginns in the chat to start the layers, but only in the chat and my charakter doesnt move at all.

**Comment by ZacSharp** [comment]
Can you please provide more information on how to make this happen? If I tell it to build a schematic it starts building.

**Comment by 001154107** [comment]
I have the same issue, and it occurs when I use a WorldEdit to save a build as a .Schem file not .schematic.

**Comment by Chaose3** [comment]
how do u get the schematic file and what type is it. I don't know how just want to know

**Comment by 001154107** [comment]
> how do u get the schematic file and what type is it. I don't know how just want to know

I use World edit a s use the:
//schem save NAME
Function
