### ISSUE TITLE
(prefix)goto chest doesn't work properly in overworld

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#3416]
When the command is executed it will highlight fake chests in the distance and won't recognize the real chests that are actually there nearby. The closer it gets to the fake highlights in the distance the more of them will disappear. This is an endless loop.

## Some information
Operating system: Windows 10
Java version: Java 8 Update 281
Minecraft version: 1.18.2
Baritone version: Newest
Other mods (if used): Meteor (with baritone included)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/8549468/latest.log)

## How to reproduce
be in the overworld and type goto chest anywhere

## Modified settings
allowInventory true
assumeExternalAutoTool true
blockPlacementPenalty 50.0
blockBreakAdditionalPenalty 40.0
jumpPenalty 2.0
walkOnWaterOnePenalty 3.0
allowDiagonalDescend true
allowDiagonalAscend true
allowDownward false
acceptableThrowawayItems minecraft:dirt,minecraft:cobblestone,minecraft:netherrack,minecraft:end_stone,minecraft:cobbled_deepslate,minecraft:deepslate
blocksToAvoid powder_snow,cave_vines,cave_vines_plant,big_dripleaf,big_dripleaf_stem,flowering_azalea,azalea,sweet_berry_bush,sugar_cane,tall_grass,vine,weeping_vines_plant,weeping_vines,twisting_vines,lily_pad,sunflower,lilac,rose_bush,peony,fire,soul_fire,lava,twisting_vines_plant,weeping_vines_plant,large_fern,cobweb
blocksToAvoidBreaking birch_log,dark_oak_log,spruce_log,oak_log,acacia_log,nether_wart_block,obsidian,warped_stem,crimson_stem,stone_bricks,cracked_stone_bricks,mossy_stone_bricks,chiseled_stone_bricks,black_stained_glass_pane,red_stained_glass_pane,green_stained_glass_pane,brown_stained_glass_pane,blue_stained_glass_pane,purple_stained_glass_pane,cyan_stained_glass_pane,light_gray_stained_glass_pane,gray_stained_glass_pane,pink_stained_glass_pane,lime_stained_glass_pane,yellow_stained_glass_pane,light_blue_stained_glass_pane,magenta_stained_glass_pane,orange_stained_glass_pane,white_stained_glass_pane,glass_pane,black_stained_glass,red_stained_glass,green_stained_glass,brown_stained_glass,blue_stained_glass,purple_stained_glass,cyan_stained_glass,light_gray_stained_glass,gray_stained_glass,pink_stained_glass,lime_stained_glass,yellow_stained_glass,light_blue_stained_glass,magenta_stained_glass,orange_stained_glass,white_stained_glass,glass,crafting_table,furnace,chest,trapped_chest,oak_planks,spruce_planks,dark_oak_planks,birch_planks,acacia_planks,jungle_planks,oak_fence,spruce_fence,birch_fence,jungle_fence,acacia_fence,dark_oak_fence,anvil,grindstone,melon,wheat,oak_trapdoor,spruce_trapdoor,dark_oak_trapdoor,acacia_trapdoor,jungle_trapdoor,rail,powered_rail,iron_trapdoor,oak_sign,spruce_sign,dark_oak_sign,jungle_sign,acacia_sign,birch_sign,white_carpet,orange_carpet,magenta_carpet,light_blue_carpet,yellow_carpet,lime_carpet,pink_carpet,gray_carpet,light_gray_carpet,cyan_carpet,blue_carpet,purple_carpet,green_carpet,brown_carpet,red_carpet,black_carpet,bookshelf,oak_slab,spruce_slab,birch_slab,jungle_slab,acacia_slab,dark_oak_slab,stone_slab,sandstone_slab,cobblestone_slab,brick_slab,stone_brick_slab,nether_brick_slab,quartz_slab,red_sandstone_slab,smooth_quartz,smooth_stone,smooth_stone_slab,cut_sandstone_slab,cut_red_sandstone_slab,polished_granite_slab,smooth_red_sandstone_slab,mossy_stone_brick_slab,polished_diorite_slab,mossy_cobblestone_slab,end_stone_brick_slab,smooth_sandstone_slab,smooth_quartz_slab,granite_slab,andesite_slab
allowParkour true
allowParkourPlace true
randomLooking113 2.0
blockReachDistance 4.0
randomLooking 0.01
costHeuristic 3.563
backtrackCostFavoringCoefficient 0.5
avoidance true
mobSpawnerAvoidanceCoefficient 2.0
mobAvoidanceCoefficient 3.27319587628865
pathingMapLoadFactor 0.75
simplifyUnloadedYCoord false
movementTimeoutTicks 25
primaryTimeoutMS 500
failureTimeoutMS 2000
planAheadPrimaryTimeoutMS 2000
planAheadFailureTimeoutMS 5000
slowPathTimeoutMS 40000
toastTimer 5000
renderPathAsLine true
pathRenderLineWidthPixels 40.0
goalRenderLineWidthPixels 3.0
freeLook false
cachedChunksOpacity 0.5
prefix +
mineGoalUpdateInterval 10
maxCachedWorldScanCount 100
exploreForBlocks false
worldExploringChunkOffset 8
exploreMaintainY -1
breakFromAbove true
goalBreakFromAbove true
mineDropLoiterDurationMSThanksLouca 250
legitMineIncludeDiagonals true
followOffsetDirection 0.0
colorCurrentPath 0,255,100
colorNextPath 255,0,255
colorBlocksToBreak 255,0,65
colorBlocksToPlace 202,255,0
colorBlocksToWalkInto 0,150,0
colorBestPathSoFar 0,0,255
colorMostRecentConsidered 0,243,255
colorGoalBox 0,160,255
colorInvertedGoalBox 255,0,0
colorSelection 0,255,255
colorSelectionPos1 0,0,0
colorSelectionPos2 255,200,0
selectionOpacity 0.5
selectionLineWidth 4.0
desktopNotifications true
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a known issue which has been fixed in #3375. This is yet to be merged though.
