### ISSUE TITLE
bBaritown not looking at blocks it's about to break.

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#342]

**Comment by leijurv** [comment]
Pls explain lmao

**Comment by EvilSourcerer** [comment]
lol so i'm using Kami and the latest version of baritown forge module. For some reason baritown wants me to manually look at the block i'm mining.

**Comment by EvilSourcerer** [comment]
https://imgur.com/i3CyRWK

**Comment by EvilSourcerer** [comment]
anticheatcompatibility was false for some reason
