### ISSUE TITLE
Something like block group creation or searching by characters in name

### ISSUE THREAD

**Issue by SuperSuggestionMan** [cabaletta/baritone#3422]
Something like 
#group create <block> <name>
Then
#mine <group name>
Or 
#mine nameinclude <characters of search>
Like 
#mine nameinclude log
Or 
Pre made groups such as logs or ores
#mine ores

**Comment by SuperSuggestionMan** [comment]
Rip

**Comment by SuperSuggestionMan** [comment]
# in thing doesn't work

**Comment by SuperSuggestionMan** [comment]
Hashtag

**Comment by ZacSharp** [comment]
Duplicate of #1311
