### ISSUE TITLE
baritone isn't mining, even if the block is nearby 

### ISSUE THREAD

**Issue by Meowz0rz** [cabaletta/baritone#3425]
## Some information
Operating system: windows 10
Java version: idk, but latest version
Minecraft version: 1.18
Baritone version: standalone forge 1.8.3
Other mods (if used): optifine for 1.18

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
![2022-04-27_19 51 17](https://user-images.githubusercontent.com/104523256/165588786-6ac548b9-45ba-4750-9db3-0e4d5679f93e.png)

**Comment by wagyourtail** [comment]
1.8.3 isnt compatible with minecraft 1.18/1.18.1 only 1.18.2 downgrade to baritone version 1.8.2
