### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Grenadeincs** [cabaletta/baritone#3426]
Hello!
It appears as Baritone won't load the schematic I saved.
it's a .nbt schematic, and when I open the schematica menu to see the hologram it detects the file just fine.
However, when I try to load the schematic, despite having checked multiple times for unwanted spaces, misspellings and if I inserted the full file name, I always got this message:
![2022-04-27_22 09 48](https://user-images.githubusercontent.com/97898907/165623276-e4e1d4de-57d8-427f-b020-89cd6a040e10.png)

## Some information
Operating system: Windows 10 Enterprise
Java version: 1.8.0_51
Minecraft version: 1.12.2
Baritone version: 1.2.13-standalone-forge
Other mods (if used): Schematica, LunatriusCore

## Exception, error or logs
Please find your `latest.log` or `debug.log` in
this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/8577473/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. Open minecraft 1.12.2 with forge, with mods installed being Baritone (baritone-standalone-forge-1.2.13.jar), LunatriusCore (LunatriusCore-1.12.2-1.2.0.42-universal.jar) and Schematica (Schematica-1.12.2-1.8.0.169-universal.jar)
2. Open a new superflat world
3. (won't change anything but I'll put it anyways) load the schematica hologram
4. use the command #build
5. Baritone throws error "couldn't load schematic."

I made the schematic using ReBane's mapartctaft (https://rebane2001.com/mapartcraft/.) I set it to generate for 1.12.2 so this shouldn't be the cause of the error.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Baritone doesn't support .nbt schematics, please use a .schematic schematic.

**Comment by Grenadeincs** [comment]
oh, thanks for letting me know. How do I convert .nbt schematics to .schematic schematics though?

**Comment by Grenadeincs** [comment]
nvm found out. For anyone wondering, put your .nbt file on [this](https://cubical.xyz/) site, select "File" and then save it as a .sch | it will save it as a .schematic file anyway, don't worry
