### ISSUE TITLE
My Game crashes every time I load minecraft

### ISSUE THREAD

**Issue by PinkPlague** [cabaletta/baritone#3429]
Some information
Operating system: MacOS
Java version: N/A
Minecraft version: 1.12
Baritone version: (N/A, it is built into Lambda)
Other mods (if used): creepy sal hack, Lambda client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue 

Heres the minecraft launcher error message:
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.k
Exit Code: 255

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
You put the client into the mods folder boot up forge and it throws the error, I don't know how but no matter if I delete the baritone folder or take the mod and re-try.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Remove noverify, and stop pirating.
