### ISSUE TITLE
[Suggestion] Ore simulator (requires world seed)

### ISSUE THREAD

**Issue by erxson** [cabaletta/baritone#3431]
## Describe your suggestion
Add function to mine ores generated from world seed. I saw this feature in meteor rejects (DeepL)
(https://github.com/AntiCope/meteor-rejects/blob/master/src/main/java/anticope/rejects/modules/OreSim.java)
## Settings
Just version and seed? 

## Context
It is antixray bypass on almost every server

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by erxson** [comment]
sory for my bad england i dont speak america

**Comment by ZacSharp** [comment]
This is out of scope for Baritone itself so you will have to use Meteor Rejects or other mods that add it externally.
The only thing I can see being done for this on the Baritone side is merging #3084 so others don't need Mixin (or ASM or Reflection) to pass the locations to the regular `MineProcess`.
