### ISSUE TITLE
When building baritone says I'm missing 4x null

### ISSUE THREAD

**Issue by MilkCrispie** [cabaletta/baritone#3432]
When I'm building with baritone it keeps pausing the build and telling me I'm missing 4x null

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
fix your schematic so it doesn't contain nulls

**Comment by ZacSharp** [comment]
No, there's really a bug that causes null to end up in the error message even with a sane schematic.
Canceling and restarting the builder "fixes" it, until whatever causes this happens again.

**Comment by ZacSharp** [comment]
This is possibly a duplicate of #3428 (which is probably a duplicate as well but it is so detailed I'd rather close the older ones instead)
