### ISSUE TITLE
Pls add see throougthtgrd  walls

### ISSUE THREAD

**Issue by UsernametsName** [cabaletta/baritone#3436]
Add something like "semi legitMine mode" :
Baritone could see the ore through the walls, but only the one that lies on the surface (not covered with blocks)
this will be cool for servers with anticheat

**Comment by wagyourtail** [comment]
`#allowOnlyExposedOres`

**Comment by UsernametsName** [comment]
it really mines only exposed ores -_-.    It doesnt mine a full vein

**Comment by scorbett123** [comment]
> it really mines only exposed ores -_-. Sometimes It doesnt mine a full vein

With a low enough mineGoalUpdateInterval it should update the goal frequently enough that it will find the new blocks which have been exposed as you mine.
