### ISSUE TITLE
How do i make baritone use the elytra

### ISSUE THREAD

**Issue by RealmKebab** [cabaletta/baritone#3439]
## What do you need help with?
I want baritone to use the elytra so it's a faster path.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Stuntlover-TM** [comment]
Impossible with normal Baritone. You can program it yourself or use cookie client (I don't recommend using cookie client as I don't know if its safe).

**Comment by scorbett123** [comment]
You don't
