### ISSUE TITLE
Auto clear path

### ISSUE THREAD

**Issue by 5UP3R-D1N** [cabaletta/baritone#3441]
## What do you need help with?
1. I'm building a huge city wall in survival and the baritone just left me with a random stair that it used to go up the wall
Is there a way to make it remove the stair itself after finished?

2. containerMemory rework maybe? like I said, a **huge** wall...all of the material is not gonna fit in my inventory
so I have to come back from AFK and run to the chest and refill stuff it needs

## Final checklist
- [ ] I don't know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 5UP3R-D1N** [comment]
![image](https://user-images.githubusercontent.com/42496449/167577775-87235cc9-9943-4e28-bf58-21966c4b01bb.png)

**Comment by ZacSharp** [comment]
Duplicate of #2976
