### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by charlesf218** [cabaletta/baritone#3443]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version: Latest, forge
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Just use mine command at all

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/8672793/latest.log)

UwU

**Comment by scorbett123** [comment]
Please don't use baritone where it isn't allowed.

Also please can you send debug.log so that I can see what the error is, it doesn't seem to be in that log.
