### ISSUE TITLE
Cannot invoke "net.minecraft.class_1922..." because "world" is null

### ISSUE THREAD

**Issue by mxcion** [cabaletta/baritone#3444]
## Some information
Operating system: Windows 10
Java version: 1.8.0_331-b09
Minecraft version: 1.18.2
Baritone version: 1.8.3 unoptimized-fabric
Other mods (if used): https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2/files

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://paste.ee/p/dJmPk)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

commands: goto x x x & mine block etc..

## Modified settings
To get the modified settings run `#modified` in game

none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Xplodin** [comment]
java 1.8 does NOT work with minecraft 1.18.2

**Comment by wagyourtail** [comment]
duplicate #3255
