### ISSUE TITLE
NBT Files Support?

### ISSUE THREAD

**Issue by prpjzz** [cabaletta/baritone#3446]
## What do you need help with?
I want to build something from Baritone, but it seems that the schematics files in the new versions are no longer a .schematic file format, but a .nbt or similar file format. Can you support these file formats?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Mathrandom7910** [comment]
Duplicate and solved in #3426
