### ISSUE TITLE
How to make bartione break chests?

### ISSUE THREAD

**Issue by TheJavick** [cabaletta/baritone#3455]
Hey. Recently I faced one problem in baritone. There is no way I can get baritone to break chests. It just walks past them. Settings #blocksToAvoid, #blocksToAvoidBreaking and #blocksToDisallowBreaking doesn't help. I tried resetting bartione and trying again, but it didn't work. I talked to another people, they also can not do anything.
Bartione can't break chests with #mine, but if you select an area #pos1, #pos2 and make it clear with #sel r chest air, then Baritone can break chests.
How can I solve this problem?

**Comment by ZacSharp** [comment]
When I tried to reproduce this it worked inconsistently with default settings and reliable broke the chest after either increasing `avoidBreakingMultiplier` or removing "chest" from `blocksToAvoidBreaking`.
