### ISSUE TITLE
#goto #mine commands not working

### ISSUE THREAD

**Issue by MGyata** [cabaletta/baritone#3459]
## Some information
Operating system: Windows 11
Java version: latest
Minecraft version: 1.18.2
Baritone version: 1.8.2
Other mods (if used): N/A

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Loaded into a multiplayer server using the forge version of baritone 1.8.2 typed #goto portal and #mine iron_ore and got an error.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/8712676/latest.log)

**Comment by scorbett123** [comment]
Update your baritone version
