### ISSUE TITLE
not compatible with "BetterChat"

### ISSUE THREAD

**Issue by VerstreuteSeele** [cabaletta/baritone#3462]
## Some information
Operating system: Win10
Java version: 8
Minecraft version: 1.12.2
Baritone version: ? Impact (guessing that's the newest then)
Other mods (if used): BetterChat, Lambda

## Exception, error or logs
Looked through it. apparently betterchat routs all chat to `[com.llamalad7.betterchat.gui.GuiBetterChat]` but baritone is ignored and still goes to the normal `[net.minecraft.client.gui.GuiNewChat]` for whatever reason which is not displayed.
[2022-05-19-7.log](https://github.com/cabaletta/baritone/files/8734470/2022-05-19-7.log)

## How to reproduce
1. Instal forge & [betterchat](https://www.curseforge.com/minecraft/mc-mods/better-chat)
2. load impact
3. run `.b help` and see nothing happen

## Modified settings
 --Not applicable --

## Final checklist
- [x] I know how to manipulate checkboxes properly 
- [x] I have included the version of Minecraft I'm running, baritone's version, and forge mods (if used).
- [x] I have included logs, exceptions, and/or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's till this point of the issue and might use some after just because its mentioned here

UwO - in all seriousness tho.. who would use that in a regular issue? By adding that checkbox you really ask for it.

**Comment by ZacSharp** [comment]
Betterchat redirects chat by replacing `mc.ingameGui.persistentChatGUI` with its own chat gui and Baritone doesn't follow the redirect because it grabs and caches a lambda function for `mc.ingameGui.getChatGUI().printChatMessage` when Baritones settings class is loaded.
`mc.ingameGui.getChatGUI()` is a getter for `mc.ingameGui.persistentChatGUI` which is `private final`, so the return value is not expected to change.

**Comment by VerstreuteSeele** [comment]
so... is there any way to fix this?

**Comment by ZacSharp** [comment]
It's pretty easy actually.

**Comment by VerstreuteSeele** [comment]
that does indeed look fairly easy. shame I probably wont be able to do this myself bc even if I download the source, apply that small change and build it, impact will still use its version (or at least I'm guessing) so I'll have to wait till this is first updated here and then in impact to pull the newest release, I'm guessing

**Comment by Mathrandom7910** [comment]
Impact doesn't seem to be updating anymore, so it likely wont be added.

**Comment by VerstreuteSeele** [comment]
rip. any way I can do that myself? got zero clue about mc modding stuff

**Comment by Mathrandom7910** [comment]
impact is closed src, so if u have an afternoon to waste, yea.

**Comment by ZacSharp** [comment]
It's a setting value so you just need to run a line like
```java
BaritoneAPI.getSettings().logger.value = msg -> Minecraft.getMinecraft().ingameGUI.getChatGUI().printChatMessage(msg);
```
when the game starts from any other mod (the pr just changes the default).

**Comment by VerstreuteSeele** [comment]
Pardon my stupidity. Where am I supposed to run this? @ZacSharp Certainly not in chat as that just gives an "invalid command" from baritone

**Comment by Mathrandom7910** [comment]
Because its not a command...

**Comment by scorbett123** [comment]
> Pardon my stupidity. Where am I supposed to run this? @ZacSharp Certainly not in chat as that just gives an "invalid command" from baritone

Unfortunately this setting is just able to be changed from a different mod, so you need to wait for the pr to be merged.

**Comment by wagyourtail** [comment]
> so you need to wait for the pr to be merged.

well, it's also grabbable from https://github.com/cabaletta/baritone/actions/runs/2355205046
