### ISSUE TITLE
what can i do

### ISSUE THREAD

**Issue by strawberry3234** [cabaletta/baritone#3467]
## What do you need help with?
hi
First of all, I am Korean, so I use Google Translator.
when i use this mod
Your inventory contains blocks of stone, dirt, or a pickaxe.
If your hot bar doesn't have these
A pickaxe enters the 1st slot.
Blocks such as soil and stones are automatically placed in slot 9
how can i turn this off.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You can disable `allowInventory` to stop Baritone from messing with your inventory.
