### ISSUE TITLE
Baritone crashing when trying to fill an area with sand

### ISSUE THREAD

**Issue by asdfwasfdad** [cabaletta/baritone#3468]
## Some information
Operating system: Windows 10
Java version: 17.0.1
Minecraft version: 1.18.2
Baritone version: 1.8.3
Other mods (if used): 
- fabric-api-0.53.4+1.18.2

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/8766829/latest.log)

[crash-2022-05-25_00.19.25-client.txt](https://github.com/cabaletta/baritone/files/8766833/crash-2022-05-25_00.19.25-client.txt)

## How to reproduce
Select an area to fill with sand (Possibly area filled with water)
Type "select fill sand"

[Video Showing Issue/Crash](https://youtu.be/TevykSHVTSk)

## Modified settings
[No modifications](https://user-images.githubusercontent.com/49735352/170148615-bb268414-63bc-45b2-a0ab-63974c61eb18.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3308 https://github.com/cabaletta/baritone/issues/3298, https://github.com/cabaletta/baritone/issues/3165, https://github.com/cabaletta/baritone/issues/3106, https://github.com/cabaletta/baritone/issues/3244, https://github.com/cabaletta/baritone/issues/3205, https://github.com/cabaletta/baritone/issues/3102 and more
