### ISSUE TITLE
1.18.2 .schem support?

### ISSUE THREAD

**Issue by Likqez** [cabaletta/baritone#3473]
## What do you need help with?
When will #build support .schem files created by worldedit in 1.18.2?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
It has been supported since 1.18.2 baritone came out

**Comment by wagyourtail** [comment]
if you're having difficulties with it I'd suggest asking in [#user-help on the discord](https://discord.gg/s6fRBAUpmr)
