### ISSUE TITLE
Game crash with Sodium and ReplayMod

### ISSUE THREAD

**Issue by Timong-craft** [cabaletta/baritone#3476]
## Some information
Operating system: Win 10
Java version: 17
Minecraft version: .18.2
Baritone version: 1.8.3
Other mods (if used): https://www.replaymod.com/down
load/

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/8790902/latest.log)

## How to reproduce
Start game with baritone, replaymod and the sodium from the replay website
Create a replay
Play the replay and game crash

**Comment by mZ0ckERc** [comment]
Could you send the crash file (located in the crash-reports folder) or isn‘t there a crash report file?

**Comment by mZ0ckERc** [comment]
It seems to be a bug related to Replaymod - Even after disabling Sodium, the game still crashes

**Comment by Timong-craft** [comment]
Wait I'm sending the crsh-report if i find it

**Comment by Timong-craft** [comment]
[crash-2022-05-31_19.26.07-client.txt](https://github.com/cabaletta/baritone/files/8807454/crash-2022-05-31_19.26.07-client.txt)

**Comment by wagyourtail** [comment]
duplicate #3255

**Comment by Timong-craft** [comment]
Had it beed fixed?

**Comment by scorbett123** [comment]
> Had it beed fixed?

It has been fixed on development branches, however hasn't been in any release yet.

**Comment by Timong-craft** [comment]
which do you mean?
