### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by M4ngus** [cabaletta/baritone#3480]
## What do you need help with?
How can i use baritone automine to mine spawners? Do i need the id of a spawner? if so, how do i use it?
i tried doing .b mine spawnerbut it just goes randomly underground then stop or goes back, never finding a spawner
## Final checklist
- [c] I know how to properly use check boxes 
- [c] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It should be `#mine mob_spawner` or `#mine spawner` depending on you version. However, this might not work because of #3143 / #3172
