### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by achitor** [cabaletta/baritone#3481]
## Some information
Operating system:Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz 
Java version: version 8 update 333
Minecraft version: forge-1.12.2-14.23.5.2859
Baritone version: 1.2.15
Other mods (if used): 
security craft v1.9.1
DivineRPG v1.7.1
extended itemsOres v1.5

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/8809972/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

start the game, join on a friend server, tipe the command #follow player (name)

## Modified settings
To get the modified settings run `#modified` in game
![image](https://user-images.githubusercontent.com/81146957/171301030-264e3a92-2ac6-4707-b5d5-74ea7165581c.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
you can only follow players that are within the entity render distance
