### ISSUE TITLE
Unite the ores. aka: No man left behind o7

### ISSUE THREAD

**Issue by nEONcReepER990** [cabaletta/baritone#3482]
## Describe your suggestion
**A setting that will allow baritone to mine both of the ore stone types at once (normal stone and deepslate)**
When mining around Y=0, sometimes there are mixed veins of ores (for example _iron_ore_ and _deepslate_iron_ore_) and when i see baritone just leave the few pieces of the other type it´s just sad. (But i´m also quite lazy to pause it and mine it myself :)
User will enter command: _mine iron_ore_ and baritone will mine ores that are _iron_ore_ tagged, which means _deepslate_iron_ore_ variant will be mined too.

## Settings
command: "MineOreVariants" true/false

## Context
More mined resources. No man left behind o7

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Idea.
- [ ] Tested.
- [ ] Added.
- [ ] Finalized.

**Comment by ZacSharp** [comment]
You can just mine for multiple ores at once using e.g. `#mine iron_ore deepslate_iron_ore`.
Using tags has already been suggested in #1089
