### ISSUE TITLE
Not having all commands

### ISSUE THREAD

**Issue by fajnygamer** [cabaletta/baritone#3485]
I dont having all commands for example legitfacing, smoothaim
Anyone having this inssue? 
Please respond fast
## Final checklist
- [x] I know how to properly use check boxes 
- [x] - I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
> I dont having all commands for example legitfacing, smoothaim

Baritone neither has a `legitfacing` command nor a `smoothaim` command. The latter is implemented in an unmerged pull request, for the former I have no idea where you found it.
