### ISSUE TITLE
Unexcepted crash

### ISSUE THREAD

**Issue by GEkXD3** [cabaletta/baritone#3490]
## Some information
Operating system: Win10 pro
Java version: Version 8 Update 51 (build 1.8.0_51-b16)
Minecraft version: 1.18.2
Baritone version: 1.8.2
Other mods (if used): [image](https://i.ibb.co/tKnq0qn/Screenshot-1.png)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/8839605/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

**1. Opening a chat
2. Entering the command #mine coal_ore
3. Error!**

## Modified settings
To get the modified settings run `#modified` in game
**allowParkour (Boolean)
avoidance (Boolean)**

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
See pinned issue
