### ISSUE TITLE
How to select area for #farm?

### ISSUE THREAD

**Issue by bkhbxk** [cabaletta/baritone#3492]
I just went to server and i need a lot od bread do i build a farm and i use #farm and few seconds its was doing his job but after that baritone just go somewhere to farm cactus insted wheat please help

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by bkhbxk** [comment]
Pls help

**Comment by wagyourtail** [comment]
you dont
 Duplicare #396

**Comment by ZacSharp** [comment]
There's `#sel farm <radius>` and you can use `#sel fill` instead of farm (in that case there is no automatic pickup though)
