### ISSUE TITLE
Its passible to set radius in #farm?

### ISSUE THREAD

**Issue by bkhbxk** [cabaletta/baritone#3493]
.

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Nope

**Comment by bkhbxk** [comment]
But i need it in some radius to work

**Comment by bkhbxk** [comment]
Not evrywhere

**Comment by scorbett123** [comment]
> But i need it in some radius to work

Sorry #farm <radius> should work on recent versions.

**Comment by scorbett123** [comment]
Why is it removing that? ok, #farm radius

**Comment by ZacSharp** [comment]
I think because "\<link\>" creates a markdown link. Normal escaping with "\\" works (unless this comment is broken as well obviously).
