### ISSUE TITLE
Why baritone cant build redstone things with schematica????

### ISSUE THREAD

**Issue by bkhbxk** [cabaletta/baritone#3495]
I just build a lag machine in my test world and i save it as schematica and when i try to build it the error comes up

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by bkhbxk** [comment]
ERORRRRRR

**Comment by ZacSharp** [comment]
Apart from me not wanting to help someone building a lagmachine I also don't see a way to help you based on the information you provided.
