### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by JoltTheWolf** [cabaletta/baritone#3500]
Whens it gonna be compatible for 1.19?

**Comment by deci-x** [comment]
Never, the creator was fatally killed to death next week.
All jokes aside, probably in about a week or less

**Comment by kr0t3** [comment]
Just wait, i will be available soon.

https://github.com/cabaletta/baritone/pull/3478/commits/606f9c55a87c53885c849fdfb6f5e4e47c350723#diff-e380ecaaf1e9f72be30db395ad3f313674c314672bd1dbdf01362b582475a7cf
