### ISSUE TITLE
1.19 version plz

### ISSUE THREAD

**Issue by SnehdeepSinghSohi** [cabaletta/baritone#3506]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by fantax77** [comment]
Not sure if it would be possible, but auto torches, not a necessity but definitely would be nice

**Comment by scorbett123** [comment]
1.19 will be released when it is ready. To see the progress on it look at #3478.
