### ISSUE TITLE
Command not found: blocksToDisallowBreaking

### ISSUE THREAD

**Issue by KatyaJopa666** [cabaletta/baritone#3509]
## Some information
Operating system: Windows 10 Enterprise
Java version: 1.8.0_51
Minecraft version: 1.12.2-forge-14.23.5.2859
Baritone version: baritone-api-forge-1.2.15
Other mods (if used): —

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/8884590/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/8884591/latest.log)

## How to reproduce
install 1.12.2-forge-14.23.5.2859
install baritone-api-forge-1.2.15.jar
run the game
write #blocksToDisallowBreaking

## Modified settings
acceptableThrowawayItems dirt
avoidance true
blockPlacementPenalty 100
itemSaver true
blocksToAvoidBreaking CRAFTING_TABLE,FURNACE,LIT_FURNACE,CHEST,TRAPPED_CHEST,STANDING_SIGN,WALL_SIGN,stonebrick,grass,stone_slab,stone_brick_stairs,dirt
mineDropLoiterDurationMSThanksLouca 4

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`blocksToDisallowBreaking` is newer than the latest release so if you want to use it you have to either build Baritone yourself or use a CI build from the Actions tab (or wait for the next release...).
