### ISSUE TITLE
An unhandled exception occurred when trying to use #mine iron_ore

### ISSUE THREAD

**Issue by Nythical** [cabaletta/baritone#3513]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you want us to have a chance at figuring out what you did you have to provide more information (fill in the template).

Anyways, the most reported "bug" is people using Baritone v1.8.1 on Minecraft 1.18.2 which does **not** work, so I'll just guess that's what you did as well. For mc 1.18.x use v1.8.2 on 1.18.2 or newer and v1.8.1 on 1.18.1 or older.

**Comment by ehylo** [comment]
v1.8.3 is for 1.18.2 and v1.8.2 is for 1.18.1, v1.8.2 will **not** work on 1.18.2

**Comment by ZacSharp** [comment]
My bad.
Editing my comment.
