### ISSUE TITLE
An unhandled exception occurred when using #mine

### ISSUE THREAD

**Issue by Nythical** [cabaletta/baritone#3514]
[16Jun2022 21:24:46.262] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] [Baritone] > mine iron_ore
[16Jun2022 21:24:46.262] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

**Comment by ZacSharp** [comment]
If you want us to have a chance at figuring out what you did you have to provide more information (there's a template for exactly that reason).

Anyways, the most reported "bug" is people using Baritone v1.8.1 on Minecraft 1.18.2 which does **not** work, so I'll just guess that's what you did as well. For mc 1.18.x use v1.8.2 on 1.18.2 or newer and v1.8.1 on 1.18.1 or older.

**Comment by wagyourtail** [comment]
> Anyways, the most reported "bug" is people using Baritone v1.8.1 on Minecraft 1.18.2 which does not work, so I'll just guess that's what you did as well. For mc 1.18.x use v1.8.2 on 1.18.2 or newer and v1.8.1 on 1.18.1 or older.

NO
1.8.3 on 1.18.2, 1.8.2 is still 1.18.1

**Comment by ZacSharp** [comment]
Oh god, copypasted the message and then forgot about it when ehylo corrected me on the other issue.
Correcting my comment here as well.

**Comment by Nythical** [comment]
> If you want us to have a chance at figuring out what you did you have to provide more information (there's a template for exactly that reason).
> 
> Anyways, the most reported "bug" is people using Baritone v1.8.2 on Minecraft 1.18.2 which does **not** work, so I'll just guess that's what you did as well. For mc 1.18.x use v1.8.3 on 1.18.2 or newer and v1.8.2 on 1.18.1 or older.

yes that was it thank you
