### ISSUE TITLE
1.19 not released yet

### ISSUE THREAD

**Issue by GreenWhisper342** [cabaletta/baritone#3518]
## Describe your suggestion
Please add 1.19 version in releases

## Settings
You could just change the compatibility (I don't know what I'm talking about but I hope you'll get it) without even adding the new blocks for example. This would make baritone usable with 1.19 fabric or 1.19 forge. Then you could later release the full version, with the new blocks etcetera. 

## Context
Because 1.19 was released 3 weeks ago, you need to update so people can use Baritone with it.

**Comment by ZacSharp** [comment]
Seriously, why don't you just search whether others already opened issues on this topic? There's a dozen duplicates and still the answer is the same: Baritone will release a version for 1.19 when it is ready. We are waiting for our dependencies to be fixed (*nothing 1.19 related*) and until then you'll have to be patient.

There is no hardcoded list of blocks or something similar.
