### ISSUE TITLE
Baritone wont allow minecraft to initialize

### ISSUE THREAD

**Issue by NetoBaianor** [cabaletta/baritone#3524]
## Some information
Operating system:Windows 10
Java version:Version 8 Update 333
Minecraft version:1.12.2
Baritone version:1.2.15
Other mods (if used): https://www.technicpack.net/modpack/theclassicswitheverything.1344524/about modpack

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
https://pastebin.com/eCKHkSTg

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

I tried to add baritone on some modpacks and when i press to run the game, the game just wont open.

**Comment by ZacSharp** [comment]
This is definitely one of the other mods causing the problem (and it's probably their fault as well). MalisisCore was already reported to cause this issue (https://github.com/cabaletta/baritone/issues/669#issuecomment-516372417) but there's likely others as well.
There's a slight hope that it is fixable by changing the loading order by prefixing the name of the baritone jar with an "a", though iirc this does not work here.
The other option is to simply remove the conflicting mod(s).

**Comment by wagyourtail** [comment]
closing, inactive
