### ISSUE TITLE
pull blocks from creative inventory during #build with #allowinventory true

### ISSUE THREAD

**Issue by lucyabalam** [cabaletta/baritone#3526]
You need all blocks in your normal inventory (not creative inventory) in creative mode when building a schematic

This is a duplicate issue, but the last issue I could find discussing this was two years ago. Could someone let me know if this was ever added, and if so, how to enable it? thanks

**Comment by ZacSharp** [comment]
No this was not added yet.
I don't know about any attempt at implementing it besides my own implementation, which I never published because it causes problems with `#farm` and I didn't want it enough to try fixing them.
