### ISSUE TITLE
How do you disable autotool?

### ISSUE THREAD

**Issue by hypixelsbgamer** [cabaletta/baritone#3528]
I have a fortune diamond pick and it keeps selecting my non fortune netherite pickaxe which im not trying to use currently. How do I disable auto tool

**Comment by ZacSharp** [comment]
Set `autoTool` to false (`#set autoTool false`)

**Comment by hypixelsbgamer** [comment]
thanks

**Comment by hypixelsbgamer** [comment]
> Set `autoTool` to false (`#set autoTool false`)

What is the ArisTois Baritone command? It just sent a regular chat message and I got exposed lol

**Comment by ZacSharp** [comment]
Well... It's whatever prefix you use for Baritone commands (I used "#" because that's Baritone's default).
I can't help you with that, sorry.
