### ISSUE TITLE
how can i get Iron ingot ?

### ISSUE THREAD

**Issue by OverdueDuke7352** [cabaletta/baritone#3532]
I join a server that needs dig lots of iron ingot 
but the command #set  [mineScanDroppedItems] can't find iron ingot(the server can't drop raw iron
can someone help me?

**Comment by ZacSharp** [comment]
There is no feature in Baritone that would allow you to automatically collect arbitrary drops while mining so if `#mine` with `mineScanDroppedItems` doesn't do it on it's own you will have to pick up the items yourself or find a different mod to do it for you (I don't know about any such mod).
