### ISSUE TITLE
dose baritone take me offline?

### ISSUE THREAD

**Issue by ItsMixer** [cabaletta/baritone#3536]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with. 

I'm trying to play Minecraft after downloading baritone and it keeps saying that I'm offline and "can't connect to Minecraft servers".
I've used baritone in the past but I tried the new 1.19 version and this happened. i just want to know if it's baritone or minecraft.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LayneTheEpic** [comment]
no...? nothing in baritone should do that

**Comment by ZacSharp** [comment]
Should be a Minecraft problem.
