### ISSUE TITLE
Baritone runs command as soon as I join any server or World

### ISSUE THREAD

**Issue by TomSawtell** [cabaletta/baritone#3538]
## Some information
Operating system: Windows 10
Java version: build 1.8.0_333-b02
Minecraft version: 1.12.2
Baritone version: 1.2.15
Other mods (if used): forgehax, journey map, optifine, wdl, future, schematica, lunatirus core

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/9032734/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1. log in to any server or world
2. tries to run command
https://youtu.be/xzfv_5veZtQ

## Modified settings
To get the modified settings run `#modified` in game
N/A

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This is not a bug in Baritone, you have ForgeHax's BaritoneCompatibility enabled. All it does is running two configurable commands to enable and disable Baritone (`#mine diamond_ore` and `#cancel` by default) for AutoEat and maybe some other module as well. I'd suggest you to either disable BaritoneCompatibility or to change the commands to `#resume` and `#pause`.
