### ISSUE TITLE
What are the commands and how to use

### ISSUE THREAD

**Issue by LachlanTTTLachlan** [cabaletta/baritone#3541]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LachlanTTTLachlan** [comment]
how to, for example auto mine diamonds, whats the command to use?

**Comment by Kuina-chan** [comment]
https://github.com/cabaletta/baritone/blob/master/USAGE.md
