### ISSUE TITLE
why is my baritone output coming out like this?

### ISSUE THREAD

**Issue by isdjasd** [cabaletta/baritone#3544]
## Some information
Operating system:idk
Java version:idk
Minecraft version:1.19
Baritone version:idk
Other mods (if used): nope
My baritone output is coming out in the achievements all glitched and bugged out for the past week and wont let me go to the second page of #help command
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SwaixYT** [comment]
There isn't a complete version for 1.19 so just use 1.18.2 if you don't want bugs like this
