### ISSUE TITLE
Baritone doesn't dig

### ISSUE THREAD

**Issue by MishaninaT** [cabaletta/baritone#3545]
![image](https://user-images.githubusercontent.com/108898628/177858196-97662712-c67f-45bc-b066-075e62c9e763.png)
Logs:
https://dropmefiles.com/bf9XO

**Comment by ZacSharp** [comment]
Can't download the log so here's my blind guess:
You are on Minecraf 1.18.x and using the wrong version of Baritone. Use Baritone v1.8.1 or v1.8.2 on Minecraft 1.18.1 and use Baritone v1.8.3 on Minecraft 1.18.2.
