### ISSUE TITLE
how to make baritone place obsidian

### ISSUE THREAD

**Issue by AkariDream** [cabaletta/baritone#3548]
## What do you need help with?
Baritone does not place for example obsidian, wool, etc
its annoying. he doesnt place wool (i need to use the schematic feature)
he would even destroy the wool that had already been placed. bruh
pls tell me how to lift the restriction
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Not sure why obsidian is affected but the fact that wool is not placed makes me think you are using a .schematic on Minecraft 1.13+. Try using a .schem instead.
