### ISSUE TITLE
Can i get baratone to do parkour and place blocks

### ISSUE THREAD

**Issue by petercraft7157** [cabaletta/baritone#3549]
i have seen vids on youtube that use baratone and it does parkour places blocks and bouilds bases when when i use it it can only mine
if there is a 1 blocks jump it is stuck and does nothing

were can i foind a download of a baritone like this
https://www.youtube.com/watch?v=0Is852C6taw

**Comment by Soy1556** [comment]
it isnt a download, its a few settings

allowParkour
allowParkourAscend
allowParkourPlace

**Comment by petercraft7157** [comment]
> it isnt a download, its a few settings
> 
> allowParkour allowParkourAscend allowParkourPlace

are these all or are there more??

**Comment by ZacSharp** [comment]
There's a few more relevant settings but those already have the correct defaults so yes, that's all you need to recreate the video.
