### ISSUE TITLE
Make it so it dosen't try to pick up items which it isnt mining for in auto mine

### ISSUE THREAD

**Issue by Haxified** [cabaletta/baritone#355]

**Comment by leijurv** [comment]
Can I have a video? I'm prettttttty sure it does this already.

**Comment by Haxified** [comment]
no lol it dosent

**Comment by Haxified** [comment]
it also tries to pick up shit that was dropped before auto mine kek

**Comment by leijurv** [comment]
Can I have a video?

**Comment by Haxified** [comment]
sure

**Comment by Haxified** [comment]
Actually, while making the video I realised something. It will pick up whatever it mines, not only the target block

**Comment by Mhowser** [comment]
Video?
