### ISSUE TITLE
Picking up items after mining.

### ISSUE THREAD

**Issue by Soy1556** [cabaletta/baritone#3550]
## What do you need help with?
I am trying to use the #mine command to get blocks, however, it doesn't always pick it up. The baritone bot doesn't worry about picking up the block, only mining it. Is there a setting to force it to pick up the targeted block after mining it?

edit: how do i make baritone stop jumping off of a cliff so i die each time 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
what's your `#modified` look like?
because by default it should do that, (and not jump off cliffs)

**Comment by Soy1556** [comment]
FUCK

**Comment by Soy1556** [comment]
i didnt mean to do that but can you just tell me the settings it needs?

**Comment by wagyourtail** [comment]
do `#setting reset all`
