### ISSUE TITLE
Clear area pick up ores

### ISSUE THREAD

**Issue by Guty18** [cabaletta/baritone#3551]
## What do you need help with?
I would like to know how to make baritone pick-up ores when in #cleararea. 

And another question, any way to set #autotool for custom blocks? A server I play on uses note blocks for ores and I would like to set this block to mine with a pickaxe, not an axe.

Thanks

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
1. There is no feature that would allow concurrent item pickup for more than `#mine`.
2. You can set `autoTool` to false (and `assumeExternalAutoTool`) and use a separate autotool mod. Apart from that there is no way to configure the built in autotool.
