### ISSUE TITLE
External auto tool dosen't work

### ISSUE THREAD

**Issue by Guty18** [cabaletta/baritone#3552]
## What do you need help with?
Hi, I'm using the auto-switch mod and it works fine when baritone is not running but when it is it doesn't work. Might it be a bug or that I have some config wrong?

I put the auto tool to false and assumeexternalautotool to true

thanks 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
your external autotool is not compatible with the way baritone works
