### ISSUE TITLE
Mine automatic mining cannot recognize minerals below layer y=0

### ISSUE THREAD

**Issue by KuGuiShen** [cabaletta/baritone#3553]
Operating system:windows10
Java version:java17
Minecraft version:1.19
Baritone version:1.8.3-125
I set the minimum y=-58 through minylevelwhilemining, but it will still run above the 0 floor to dig,And I can't see the minerals below layer y=0 from the frame.
I suggest fixing this bug and adding the maximum mining layer

**Comment by wagyourtail** [comment]
specify the ore with deepslate_ out front
