### ISSUE TITLE
Mine automatic mining is abnormal

### ISSUE THREAD

**Issue by KuGuiShen** [cabaletta/baritone#3556]
Why are multiple diamonds connected together, but sometimes only one of them is dug and then goes to the next mine pile

**Comment by wagyourtail** [comment]
my guess would be you're only mining normal diamond ore and didn't include deepslate in the command, or there's lava preventing baritone from wanting to mine the remaining blocks
if this is not the case, please provide the command you're using, and a screenshot after mining the blocks surrounding the diamonds with f3 on

**Comment by D4NZ1KA** [comment]
how do i add more than one ore in automine?

**Comment by sam1212111** [comment]
use this 
#mine minecraft:deepslate_diamond_ore
