### ISSUE TITLE
Kick anti-cheat 

### ISSUE THREAD

**Issue by ILaptev96** [cabaletta/baritone#3560]
Hi. My bot is getting kicked by the anti-cheat.
I made anti-afk bot, he walks, twirls his head and jumps, I noticed the slower he is, the less likely to poo the anti-cheat.
I made it as slow as possible and similar to the player's behavior, but it still gets kicked about once every 5 hours, what can you do to avoid it?

**Comment by soshimee** [comment]
I had a similar issue, except it happens wayyy more often than that. I think it could be because Baritone clicks every block and real players hold down.
