### ISSUE TITLE
Schematic block list?

### ISSUE THREAD

**Issue by ExtendedFurby** [cabaletta/baritone#3561]
I have downloaded a schematic and it is clearing out land for me. But I dont have the blocks that I need in my inventory and I dont know which ones that I need. Is there a way to view this? This is my first time using the build feature and I'm unaware of how to use this.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
No, Baritone does not have a way to view needed items for a schematic. You can use a schematic mod for that purpose.

**Comment by ZacSharp** [comment]
See #1781
