### ISSUE TITLE
Some items that are moved in the player's inventory gets moved back to the hotbar

### ISSUE THREAD

**Issue by Sxpiderzz** [cabaletta/baritone#3569]
## I was using baritone but when i moved a stone block into my inventory then right as i close out of inventory, it moves itself back onto the hotbar, And on the 9th slot.
![before](https://user-images.githubusercontent.com/109442473/179375252-7d6de5c4-bf02-40d5-bc40-12365b2584b4.png)
![after](https://user-images.githubusercontent.com/109442473/179375253-15055ac0-8448-42bf-a43e-1ff466e710fa.png)

**Comment by ZacSharp** [comment]
That's not a bug. You have `allowInventory` enabled so Baritone will make sure there's always a pickaxe and a stack of throwaway items on your hotbar but not while any inventory is open.
The only way to prevent this is disabling `allowInventory`.
Changing `InventoryBehavior` to only move pickaxe and throwaways on demand (like it is done for building materials) has already been suggested in #3409

**Comment by Sxpiderzz** [comment]
where can i turn it off?

**Comment by wagyourtail** [comment]
bruh. zac said how to. just do
`#allowInventory`
