### ISSUE TITLE
mining problem where it says " meta=null"

### ISSUE THREAD

**Issue by pdbpf** [cabaletta/baritone#3570]
<img width="651" alt="Screen Shot 2022-07-17 at 9 38 52 PM" src="https://user-images.githubusercontent.com/109498884/179446178-c4a9eddb-e052-42ad-a87f-68adf5d591a0.png">

if I try to use the mine command in baritone, it will say mining in chat, but then it will do nothing and it will say 
"[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]"
if anyone could tell me what is wrong that would be very much appreciated.

**Comment by wagyourtail** [comment]
not enough info, please fill out the bug report template and provide a game log so we can properly identify the problem
(you can do this in a comment here...)
