### ISSUE TITLE
how can i use baritone with macro mod.

### ISSUE THREAD

**Issue by Misjudgments** [cabaletta/baritone#3573]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Well, i installed baritone and macro mod 1.12.2 on liteloader. and baritone seems to be working when i type # or .b in chat
but if i want to combine it with macro mod it doesn't work. for example:
echo(#goto -227.3 80 -166.5);
this command just prints "#goto -227.3 80 -166.5" to chat and doesn't do anything
i tried using the api forge version or the unoptimized but i have no clue why it doesn't work.
i hope that if someone knows the solution to tell me.
thanks alot!
- misjudgments.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
I don't think m/kb is compatible with running baritone stuff, 

you could try 
https://www.curseforge.com/minecraft/mc-mods/advanced-macros
or
https://modrinth.com/mod/jsmacros
