### ISSUE TITLE
ming blocks on the surface

### ISSUE THREAD

**Issue by helioseu** [cabaletta/baritone#3578]
hello,

hi i just wanted to ask is there any settings that can let baritone mine the ores , blocks on the surface, i dont want baritone to mine other blocks to reach an ore

**Comment by ZacSharp** [comment]
I think `allowOnlyExposedOres` is what you are looking for. If you enable it Baritone will still "see" ores through walls, but only those that are adjacent to air.
If you want Baritone to not "look" through walls you can enable `legitMine`.
