### ISSUE TITLE
What's this about?

### ISSUE THREAD

**Issue by 013jian** [cabaletta/baritone#3580]
![error mine](https://user-images.githubusercontent.com/109997648/180890039-c82fd913-d5d6-4c51-92ce-3d7411af24ad.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It means that you are trying to run a client mod on a server and the mod author did not take the extra effort to not crash the server in such a situation. Just remove all mods that are not made to run on a server and this problem should be gone.
Also why are you asking here? The mod you incorrectly added to the mods folder of your server seems to be equipmentcompare, not baritone.

**Comment by 013jian** [comment]
> It means that you are trying to run a client mod on a server and the mod author did not take the extra effort to not crash the server in such a situation. Just remove all mods that are not made to run on a server and this problem should be gone. Also why are you asking here? The mod you incorrectly added to the mods folder of your server seems to be equipmentcompare, not baritone.

Im sorry, but as you can see i dont even know what a dedicated server is xd. This error is from my friend who is trying to host the server. So the equipmentcompare mod is the issue?

**Comment by ZacSharp** [comment]
Yes, it is (and if you have Baritone installed on the server then you have to remove it as well).
Equipmentcompare and Baritone are client mods so to use them you put them into your own mods folder, but not the mods folder of the server.

**Comment by ZacSharp** [comment]
Looks like I misinterpreted the log excerpt and the server did *not* crash?
