### ISSUE TITLE
How to bridge?

### ISSUE THREAD

**Issue by Basti-Z** [cabaletta/baritone#3581]
How do i bridge with baritone?
i want to bridge across the void with leaves so i added them to throwawayitems, tried tunnel but it just does nothing (doesn't use cobblestone either)
how do i get it to work?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by i-am-called-glitchy** [comment]
@Basti-Z how did you resolve this?
