### ISSUE TITLE
Is this comatible with lunar client?

### ISSUE THREAD

**Issue by sussyminecraftimposter** [cabaletta/baritone#3584]
i want to know if i can use this on lunar client?

**Comment by Playyee** [comment]
that usename...

**Comment by Cxreo** [comment]
lol, even if lunar was a Minecraft Mod and not a client itself, no it wouldn't work.

**Comment by scorbett123** [comment]
From what I know about lunar client this isn't possible as it has it's own launchers

**Comment by ttcac22** [comment]
> lol, even if lunar was a Minecraft Mod and not a client itself, no it wouldn't work.

but why wouldn't it work even if it was a mod?
