### ISSUE TITLE
crash when enter the world 

### ISSUE THREAD

**Issue by abc13131412** [cabaletta/baritone#3586]
## Some information
Operating system:win10
Java version: java8
Minecraft version:1.12.2
Baritone version:1.2.15
Other mods (if used): in logs 

## Exception, error or logs

logs https://mclo.gs/Y3oAa7k

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Just join a world or a server
## Modified settings
 cant do that
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Remove noverify, and stop pirating.

**Comment by abc13131412** [comment]
> Remove noverify, and stop pirating.

Oh, I have already bought this game so i just need to remove noverify?

**Comment by abc13131412** [comment]
> Remove noverify, and stop pirating.

Still crashing, so what should i do

**Comment by wagyourtail** [comment]
the error should be different

**Comment by abc13131412** [comment]
> the error log should be different...

ok, see here. this is the full logs(maybe?)
[debug.log](https://github.com/cabaletta/baritone/files/9225652/debug.log)
