### ISSUE TITLE
When comes Baritone for 1.19?

### ISSUE THREAD

**Issue by Matter999** [cabaletta/baritone#3588]
.

**Comment by ripnonfegames** [comment]
Just use meteor client, it has it built on the latest release and has baritone.

**Comment by ripnonfegames** [comment]
np bro

**Comment by Zeddronn** [comment]
Does anyone have the baritone 1.19 I really need it

**Comment by Matter999** [comment]
Use Meteor Client

**Comment by ehylo** [comment]
why are you telling people to use meteor client when you can just send them the action link [here](https://github.com/cabaletta/baritone/actions/runs/2462884513) which has all of the jars not just fabric?

**Comment by Lexian-droid** [comment]
Okay telling people to use Meteor Client isn't a solution. It's a non-answer, stop with that and give people real answers.

**Comment by SnooComics9452** [comment]
> why are you telling people to use meteor client when you can just send them the action link [here](https://github.com/cabaletta/baritone/actions/runs/2462884513) which has all of the jars not just fabric?

the jars are expired

**Comment by Mayank-1234-cmd** [comment]
> > why are you telling people to use meteor client when you can just send them the action link [here](https://github.com/cabaletta/baritone/actions/runs/2462884513) which has all of the jars not just fabric?
> 
> the jars are expired

https://github.com/cabaletta/baritone/actions/runs/3770503180 they update build 1.19.3 regularly just not posted tho

**Comment by gmankab** [comment]
> the jars are expired

it is not expired, just press "arifacts" below

https://github.com/cabaletta/baritone/suites/10106771476/artifacts/492866084

**Comment by GHoler** [comment]
> > the jars are expired
> 
> it is not expired, just press "arifacts" below
> 
> https://github.com/cabaletta/baritone/suites/10106771476/artifacts/492866084

this is for 1.19.2 version. not 1.19
