### ISSUE TITLE
How do I make baritone pick up specific items?

### ISSUE THREAD

**Issue by ripnonfegames** [cabaletta/baritone#3589]
Basically I'm recreating the hunt command by using follow and KillAura on meteor client, but it doesn't pick up the items, is there a setting that enables that or would I have to input some tech-savvy shit?

**Comment by ZacSharp** [comment]
You can tell Baritone to follow items as well but I don't expect that to work well in combination with hunting other entities down (you'd have to hug everything you are killing just so you get close enough to items).
Sadly that's the best you can get with Baritones current feature set.
