### ISSUE TITLE
build 11016.schematic doesn't work

### ISSUE THREAD

**Issue by zhaojiedi1992** [cabaletta/baritone#3590]
## Some information
Operating system:  mac os  motereney
Java version:   jdk 17.0.4
Minecraft version: 1.19.0
Baritone version:  https://meteorclient.com/download?devBuild=1569
Other mods (if used):  fabric 0.4.18

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. download https://www.minecraft-schematics.com/schematic/11016/   
2. save  to <base_dir>/.minecraft/schematics/11016.schematic`
Add your steps to reproduce the issue/bug experienced here.
3. start game 
4. Start creative mode
5. Take 64 cactus sand 64 lines 64.
6. 4. #build 11016 (or  build 11016.schematic) 
7.  it doesn't work.
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
What do you mean by "it doesn't work" is there some output in chat?

**Comment by zhaojiedi1992** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/25144156/182768832-37ca6c5b-a3d0-44a4-aebb-373d599c7444.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/25144156/182768861-8ab8afa2-c9c5-4ec2-9070-c459fb44da46.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/25144156/182768897-0aef1f14-0255-458a-add1-537ecd4a9b8b.png">
<img width="593" alt="image" src="https://user-images.githubusercontent.com/25144156/182768929-763e61c2-3dfa-4bca-9de3-df6d7e74b9aa.png">

<img width="817" alt="image" src="https://user-images.githubusercontent.com/25144156/182768978-ed5064c9-6778-4013-96ab-5fd8faed1837.png">

**Comment by zhaojiedi1992** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/25144156/182769178-e025f54f-c7e3-402f-abdb-c4f05ffff864.png">

**Comment by zhaojiedi1992** [comment]
How do I enable DEBUG to output more valuable information ？

**Comment by scorbett123** [comment]
Baritone generally doesn't play great with creative, does it work if you give yourself the blocks and switch to survival?

**Comment by zhaojiedi1992** [comment]
Survival mode is the same as creative mode,
How do I enable DEBUG to output more valuable information ？

**Comment by zhaojiedi1992** [comment]
I changed to the 14105 file, which is not working properly. （https://www.minecraft-schematics.com/schematic/14105/）

The effect is as follows.

https://user-images.githubusercontent.com/25144156/182978153-648c5bd2-ba75-4c2a-b544-9454fe7b4c56.mp4
