### ISSUE TITLE
mine chunk

### ISSUE THREAD

**Issue by CarmeloCampos** [cabaletta/baritone#3591]
## Can you mine entire chunks?
I've been looking for a solution or a command to implement this.
Let's assume it's something like
#mine chunk
And the whole chunk where I'm standing is mined from the top down.
Or to be able to specify from what height to what depth.
Or also to know if I could tell how many chunks around me.

**Comment by scorbett123** [comment]
Use sel to select the area, then clear it.
```
#sel pos1
#sel pos2
#sel ca
```
