### ISSUE TITLE
Deepslate ore cannot be detected

### ISSUE THREAD

**Issue by Dd112211** [cabaletta/baritone#3594]
## Some information
Operating system: Windows 10
Java version: 17.02
Minecraft version: 1.19
Baritone version: baritone-forge-standalone-1.8.3-125-g9c2134e6
Other mods (if used): 
Starlight
Distant Horizons
Xaero's Minimap
Xaero's World Map

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

#mine Deepslate_Gold_Ore
Error at argument #1: Expected w

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Dd112211** [comment]
it works after I try many times like magic...

**Comment by OwenCrawley** [comment]
was there any special name you used to mine the deepslate instead of ignoring it like a custom block tag?
