### ISSUE TITLE
BLOCK ID QUESTION

### ISSUE THREAD

**Issue by wsdmc** [cabaletta/baritone#3595]
![IDV1JF{`4USHB_86@U%I$KT](https://user-images.githubusercontent.com/85919209/183042860-02dd9c95-1351-40bc-b812-b4710f31f899.png)
![KN~8MPZ%_C4SHKL8B1C505M](https://user-images.githubusercontent.com/85919209/183042868-9cf33276-8d93-4d05-a9c2-0d6f3ea17650.png)
![A_31OI(WEBS 9 )4`9_9H2Q](https://user-images.githubusercontent.com/85919209/183042837-f43dd3bb-5ef1-485d-8f93-83b0f57d1920.png)

**Comment by wsdmc** [comment]
pardon me，I CAN'T Know ENGLISH Very well
I Have A question
When I Use Auto Build On Baritone 1.8.3 Minecraft 1.18.2
It Can't identify some block
such as snow block，someblock with color（such as wool And concrete）
but in 1.12.2 ，It can identify
I Found In NEW version(1.13.2 and High) Snow 'ID is snow_block 。Top snow' ID is snow
But In Old version (1.12.2) Snow block ID is snow   . Top snow' ID is top_snow
I Wish it can be fixed
Thanks

**Comment by wsdmc** [comment]
![IDV1JF{`4USHB_86@U%I$KT](https://user-images.githubusercontent.com/85919209/183043237-23bfe5f5-6000-43b6-b0f1-1bd7450f0155.png)

**Comment by wsdmc** [comment]
![KN~8MPZ%_C4SHKL8B1C505M](https://user-images.githubusercontent.com/85919209/183043292-737c477e-2ff4-46a7-b5af-7f2292a8c9fb.png)

**Comment by ZacSharp** [comment]
See my answer in #3596
