### ISSUE TITLE
BLOCK ID BUG

### ISSUE THREAD

**Issue by wsdmc** [cabaletta/baritone#3596]
## Some information
Operating system:Windows11
Java version:Java17
Minecraft version:1.18.2
Baritone version:1.8.3
Other mods (if used): 
pardon me，I CAN'T Know ENGLISH Very well
I Have A question
When I Use Auto Build On Baritone 1.8.3 Minecraft 1.18.2
It Can't identify some block
such as snow block，someblock with color（such as wool And concrete）
but in 1.12.2 ，It can identify
I Found In NEW version(1.13 and Higher) Snow 'ID is snow_block 。Top snow' ID is snow
But In Old version (1.12.2 And Lower) Snow block ID is snow . Top snow' ID is top_snow
I Wish it can be fixed
Thanks
![This Is My image](https://user-images.githubusercontent.com/85919209/183042837-f43dd3bb-5ef1-485d-8f93-83b0f57d1920.png)
![This Is My image](https://user-images.githubusercontent.com/85919209/183043237-23bfe5f5-6000-43b6-b0f1-1bd7450f0155.png)
![This Is My image](https://user-images.githubusercontent.com/85919209/183043292-737c477e-2ff4-46a7-b5af-7f2292a8c9fb.png)
#3595

**Comment by ZacSharp** [comment]
Don't use .schematics on mc 1.13+. If needed convert it to a .schem beforehand (paste and save with WorldEdit, online converter, etc.).
