### ISSUE TITLE
something about AutoTool

### ISSUE THREAD

**Issue by AKGAMEZ** [cabaletta/baritone#3605]
I want to use autoTool, but the thing is 
when i use it, it uses my iron pickaxe always and i want it to use my stone pick and only use iron pick when mining diamonds and redstone.Either this already exists and i couldnt find it or it doesnt and if it doesnt i would suggest you add it.

- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You can use an external autotool for that purpose (enable `assumeExternalAutoTool`, install autotool mod, hope the mod is compatible).
Apart from than, this has already been suggested.

**Comment by AraAraOwO** [comment]
> You can use an external autotool for that purpose (enable `assumeExternalAutoTool`, install autotool mod, hope the mod is compatible). Apart from than, this has already been suggested in #672 / #783

can you tell which autotool mod allow using stone pickaxe when iron is not needed?
