### ISSUE TITLE
Task :fabric:proguard FAILED

### ISSUE THREAD

**Issue by realhackcraft** [cabaletta/baritone#3608]
## What do you need help with?
I have the error
```
> Task :fabric:proguard
Running Determinizer
 Input path: /Users/Hackcraft_/Downloads/baritone-1.19.1/fabric/build/libs/baritone-fabric-1.9.0-local.jar
 Output path: /Users/Hackcraft_/Downloads/baritone-1.19.1/fabric/build/libs/baritone-fabric-unoptimized-1.9.0-local.jar

> Task :fabric:proguard FAILED

Execution failed for task ':fabric:proguard'.
> Proguard exited with code 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

When building the version 1.19.1 of baritone.

I have IntelliJ IDEA with java SDK 17.

## Steps I took

- Download baritone 1.19.1
- Open Gradle tab
- Click baritone > Tasks > build > build
- Error!

Screenshot: 

![Error](https://user-images.githubusercontent.com/65378120/183781624-5f657bc4-aae0-457c-8b2c-352de1442b77.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
if you've used that dir for building other versions of baritone it probably has a old version of proguard cached, try deleting the proguard folder under the build folder (or just the whole build folder) and trying again

**Comment by realhackcraft** [comment]
> if you've had other versions of baritone in there it probably has a old version of proguard cached, try deleting the proguard folder under the build folder (or just the whole build folder) and trying again

Where is the build folder? is the the buildScr folder or the individual build folder under common, fabric, and forge?

**Comment by realhackcraft** [comment]
Do I delete proguard.pro from scripts/proguard.pro

**Comment by realhackcraft** [comment]
It's working now, but I can't find the jar file.

**Comment by scorbett123** [comment]
The jar file should be in the dist folder.

**Comment by realhackcraft** [comment]
is it build/libs/baritone-fabric-1.9.0-local.jar
?

**Comment by scorbett123** [comment]
Nope in the dist/ folder all versions should be listed

**Comment by realhackcraft** [comment]
can you provide a relative path to the folder?

**Comment by realhackcraft** [comment]
Or can you give me a screenshot of the folder?

**Comment by scorbett123** [comment]
> Or can you give me a screenshot of the folder?

On a phone right now, and won't have access to my computer for a week, however it is baritone/dist after you've run ./gradlew build.

If someone else could provide a screenshot I'd appreciate it.

**Comment by realhackcraft** [comment]
> > Or can you give me a screenshot of the folder?
> 
> On a phone right now, and won't have access to my computer for a week, however it is baritone/dist after you've run ./gradlew build.
> 
> If someone else could provide a screenshot I'd appreciate it.
![Screen Shot 2022-08-10 at 10 01 48 AM](https://user-images.githubusercontent.com/65378120/183920865-82e7fca7-e7b9-4c20-813b-9aa328ec2932.png)
I cannot find the said file in the directories you specified. However, I did get the configuration Minecraft Client (:fabric) to work.

**Comment by realhackcraft** [comment]
When I search in baritone-1.19.1 folder(on mac), I find that such folder did not exist
![Screen Shot 2022-08-10 at 11 19 45 AM](https://user-images.githubusercontent.com/65378120/183942661-fd74d191-48bd-4c5f-a787-c197758d71e9.png)
.

**Comment by scorbett123** [comment]
@wagyourtail is the dist file no longer created?

**Comment by wagyourtail** [comment]
No it should be there.
