### ISSUE TITLE
Where is the baritone/dist folder

### ISSUE THREAD

**Issue by realhackcraft** [cabaletta/baritone#3611]
## What do you need help with?
I cannot find the baritone/dist folder in which the jar files are supposed to be. I have built them and they work when I use the configuration Minecraft Client (:fabric).

When I do ⌘F in finder and search for any folder named dist, I found none.
![Screen Shot 2022-08-10 at 11 19 45 AM](https://user-images.githubusercontent.com/65378120/183948593-47fb305e-73b3-4b7b-86a0-1a4d52bb04f7.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by realhackcraft** [comment]
Send help

**Comment by wagyourtail** [comment]
![image](https://user-images.githubusercontent.com/6234704/184043329-6ce0ba2e-d755-4ed8-be27-e47f0528a6d7.png)

it'll only be there after a successful `gradlew build`, if you're having issues with that, just let github actions do the building for you by pushing the changes you make to a fork... if you're just trying to build without changes, grab them prebuild from one of the commits listed @ https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml

**Comment by realhackcraft** [comment]
I did had a successful build but its still not there(I assume a successful build means that I can open the test action)
