### ISSUE TITLE
Will there be a update for 1.19?

### ISSUE THREAD

**Issue by Jakeymakey2** [cabaletta/baritone#3612]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by realhackcraft** [comment]
There is a branch for that. On the top left of the screen, there is a button that says `master`. Click on that and select [1.19](https://github.com/cabaletta/baritone/blob/1.19.1). You have to build it your self, as there is no release for it(read https://github.com/cabaletta/baritone/blob/1.19.1/SETUP.md)

**Comment by realhackcraft** [comment]
also please check the box `I have not used any OwO's or UwU's in this issue.` It is very important to inform others.
