### ISSUE TITLE
Add the ability to create a separate sheet of blocks, for breaking which the bot will use the silk touch

### ISSUE THREAD

**Issue by Yanninay** [cabaletta/baritone#3614]
## Describe your suggestion
Function to break user-specified blocks by using silk touch

## Settings
The user will specify a list of blocks (this is used in the function that allows you to avoid the specified blocks to break), and the bot will in turn use a silky touch for specified in the list of blocks

## Description
On some servers, diamond ore is a currency, it in turn is used to buy and sell various goods. Users may need to mine specifically diamond ore rather than diamonds, so it would be more convenient if the baritone used silk touch to mine user-specified blocks such as diamond ore, iron ore, and so on

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by xailisse** [comment]
you can use [preferSilkTouch](https://baritone.leijurv.com/baritone/api/Settings.html#preferSilkTouch) parameter and mine certain ores with this parameter, and then other ores without it

**Comment by Yanninay** [comment]
> you can use [preferSilkTouch](https://baritone.leijurv.com/baritone/api/Settings.html#preferSilkTouch) parameter and mine certain ores with this parameter, and then other ores without it

You're missing the point. I need the bot to use silk touch exclusively to mine certain blocks. To make it even simpler:
When laying a route to diamonds, the bot will use a regular pickaxe
When he finds the diamonds, he checks if they are on the list for extraction using silk-touch, and then he takes out a tool with silk-touch and extracts them.

The parameter you specified has a Boolean value, I can't select the blocks I want, I can only specify true/false

Translated with www.DeepL.com/Translator (free version)
