### ISSUE TITLE
Clicking on baritone waypoints in chat does not work

### ISSUE THREAD

**Issue by zasuwa121** [cabaletta/baritone#3616]
Hello, so I started playing on anarchy server and I have an issue with baritone, it saved my death waypoints, but when I'm trying to click on them nothing happens, what can I do to fix it?
![barinot](https://user-images.githubusercontent.com/111125357/184344698-946b80a0-5663-4649-9b35-db89648b8dd2.png)

**Comment by wagyourtail** [comment]
Duplicate #3587
