### ISSUE TITLE
using #build but files are in subfolders

### ISSUE THREAD

**Issue by WILLATRONIX** [cabaletta/baritone#3618]
i have all my schematic files neatly placed into different folders for litematica and want to build them with  baritone but i can't figure out how to get baritone to understand the directory
![image](https://user-images.githubusercontent.com/111201886/184510691-f863d732-586d-47fa-b534-7fff22e83d00.png)

**Comment by xailisse** [comment]
I think that baritone uses only schematic files, not schem (you can find online converters), but for an easier use, install schematica and use the schematica command (it builds what's open in schematica)

**Comment by ZacSharp** [comment]
Baritone can handle .schematic and .schem so that's not the problem here.
Can you please reproduce this with an unoptimized version and upload the logfile?
