### ISSUE TITLE
1.8.3 Instead Of What You Want

### ISSUE THREAD

**Issue by lessticbbb** [cabaletta/baritone#3619]
So... I've been lately trying to understand why everytime I download baritone for a version its version is just 1.8.3 everytime I download
a version. Please fix this because I'm trying to install BARITONE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by lessticbbb** [comment]
![Screenshot 2022-08-14 122452](https://user-images.githubusercontent.com/111219171/184530756-0ae488cd-c7a2-4932-898c-b99f822ad681.png)
this is what im talking about

**Comment by scorbett123** [comment]
Where are you downloading this from?

**Comment by wagyourtail** [comment]
Bruh, its 1.8.3-thenumbersherenatter based on the numbers I see in that screenshot it looks like one of the 1.19 builds of the ci, so its correct
