### ISSUE TITLE
A sort of blocksToAvoidBreaking alternative, I guess, but only for me

### ISSUE THREAD

**Issue by zPippo104** [cabaletta/baritone#3620]
ok so basically since blocksToAvoidBreaking doesn't work, and I have to don't mine spruce leaves (or mine them with an axe), I disabled Baritone's autotool, to use the Impact's one. It doesn't work. Now the problem is: if my axe brake, I don't auto switch to another one. I disabled autotool 'cause I have to mine leaves with an axe on the server I'm playing on, and Baritone tries to mine them with everything except an axe. I know maybe it's a bit confusing, the best solution would be have a #blocksToAvoidBreaking working, I don't really know what to do now

**Comment by wagyourtail** [comment]
depending on your version, `#blocksToDisallowBreaking`
