### ISSUE TITLE
how do i enable reliable pickup with #mine

### ISSUE THREAD

**Issue by mmmmmabil** [cabaletta/baritone#3625]
is there a way to ensure that baritone picks up all the items when using #mine 

i need a lot of mushroom stems and if i only enable the mine command the player moves to the next stem without picking up the majority of the blocks

**Comment by ZacSharp** [comment]
There is currently no way to make Baritone pick up arbitrary items while doing something else.
Afaik Baritone should however pick up any item that can be dropped by any of the target blocks so your problem shouldn't exist in the first place.
