### ISSUE TITLE
Litematica doesn't work with #build?

### ISSUE THREAD

**Issue by gamerpogmandude** [cabaletta/baritone#3626]
This may not be a big, but you can not build litematica schematics even though schematics is 1.12.2 and older version.

**Comment by MGThorn** [comment]
.litematic schematics are not compatible you could use worldeddit to make one schematic .shem that is compatible but that can be annoying 
Had the same problem and was looking for a lot of different approaches the best one i got: 
i have found a program on github that converts these .litematic files to .shem files

https://github.com/GoldenDelicios/Lite2Edit
