### ISSUE TITLE
"schematica not present" with baritone using schematica

### ISSUE THREAD

**Issue by caleyb1233** [cabaletta/baritone#3628]
I have the schematica loaded i do #schematica and it says "schematica not present" playing on 1.19.2 on meteor client any help would be greatly appreciated.

**Comment by wagyourtail** [comment]
Schematica mod doesnt exist past 1.12.2. So since you probably mean litematica. Baritone doesnt support it

**Comment by ZacSharp** [comment]
Also Litematica can have an unlimited amount of schematics open at the same time so it wouldn't be clear what Baritone is supposed to build.
