### ISSUE TITLE
Baritone can't place blocks when in freecam.

### ISSUE THREAD

**Issue by ruskyhacker** [cabaletta/baritone#3629]
## Some information
Operating system: Windows 10
Java version: 16
Minecraft version: 1.17.1
Baritone version: 1.7.2
Other mods (if used): freecam

## How to reproduce
Make a path, that requires placing a block (including some paths generated by #mine) and enable freecam

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
the problem isn't baritone, the problem is your freecam blocking those action
![Peek 2022-08-21 14-52](https://user-images.githubusercontent.com/6234704/185810447-11225118-1241-4567-a994-ee0581ed62e0.gif)
using [my freecam mod](https://github.com/wagyourtail/Freecam)
