### ISSUE TITLE
A suggestion about automining

### ISSUE THREAD

**Issue by P01ntl4nc3r** [cabaletta/baritone#3633]
### Suggestion

I want to automine for hours but sometimes I forget that I was automining so all of my pickaxes break is there a way that when there is only 1 pickaxe left it automatically goes home to where you set it to and a way to automatically drop or put collected items to an any type of storage.

### Settings

- Have an option if you want to break blocks while going home or break the blocks that you only listed.
- Option to what kind of item to use: (selected enchantment or not enchanted), (lowest to highest durability), (slowest to fastest mining speed) or a mix.
- How fast you can go either by walking or running: (or by how fast you can fly an elytra if it is implemented).
  - An option if you want to use elytra: (selected enchanted or not enchanted).
- An option if you will go home by going first to a set waypoint then to the target waypoint.
  - An option if you want to drop off your collected items to the first destination and then go to the next destination.
  - An option to automatically put collected items or selected items to a nearby storage.
- An option to get a selected tool from a storage or a dropped item.

**Comment by P01ntl4nc3r** [comment]
I'm new to commenting here. Please tell me if there's something wrong.

**Comment by ZacSharp** [comment]
This is really many feature requests disguised as settings to a single one.
Generally what you are suggesting is better done using general scripting/macros and not as a hardcoded feature in Baritone.
* same here, just have your script/macro tweak the settings while going home
* This really is a suggestion for a more sophisticated autotool. There have been thoughs about implementing one but for now you'll have to use an external autotool mod for this purpose.
* Why do you need to tell Baritone how fast it can walk?
* Adding routes / waypoint chains has already been suggested a couple times, no need to request it again
  * Again, this is better done in a script
  * Same here
* And here as well.
