### ISSUE TITLE
1.12.2: Backfill option is executed outside of commands

### ISSUE THREAD

**Issue by Edouard127** [cabaletta/baritone#3634]
## Some information
Operating system: Windows 10 19043.1889
Java version: 1.8.0_333
Minecraft version: 1.12.2
Baritone version: 1.2.14
Other mods (if used): Lambda 3.2.1 Schematica

## How to reproduce
Enter #backfill true

## Modified settings
Backfill: true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3579 and probably others by the fact that searching backfill returned a lot of results
