### ISSUE TITLE
when i type #mine minecraft:diamond_ore it says An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

### ISSUE THREAD

**Issue by EgorZpUa** [cabaletta/baritone#3636]
[latest.log](https://github.com/cabaletta/baritone/files/9438244/latest.log)

**Comment by ZacSharp** [comment]
You are using an incompatible version of Baritone (see issue 3339).
Baritone v1.8.2 is for Minecraft 1.18.1, Baritone v1.8.3 is for Minecraft 1.18.2.
