### ISSUE TITLE
baritone 1.19.2 does not see ore

### ISSUE THREAD

**Issue by FireByteTTKM** [cabaletta/baritone#3637]
https://youtu.be/aA2C3AE8i4E
**baritone settings:**
- allowDiagonalDescend true
- allowDiagonalAscend true
- allowParkour true
- allowParkourPlace true
- rightClickSpeed 1
- mobAvoidanceCoefficient 1.5
- mobAvoidanceRadius 32
- cutoffAtLoadBoundary true
- maxPathHistoryLength 500
- allowOnlyExposedOres true

**Comment by Checkpo1nt** [comment]
Baritone doesn't have support for 1.19.2?

**Comment by ZacSharp** [comment]
https://github.com/cabaletta/baritone/blob/4e2095d25114dd88fa01baf21a805d3f6e1b8ee9/src/main/java/baritone/pathing/movement/MovementHelper.java#L575
`minecraft:cave_air`
