### ISSUE TITLE
add a #top command

### ISSUE THREAD

**Issue by TinySpogFace** [cabaletta/baritone#3639]
## Describe your suggestion
add #top which will take you to the exact same coordinates for X and Z but it will take you to the surface. example: i type #top in a cave. baritone would take me as high as it could go on the same X and Z coords it can go out of the same coords.

## Settings
maybe the abilty to choose weather it stays within the same X and Z coordinates or it can use other caves?

## Context
expand baritone and make more ppl use it.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This has already been implemented just use `#top`.
