### ISSUE TITLE
Can't avoid lava

### ISSUE THREAD

**Issue by youkeith** [cabaletta/baritone#3646]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

Can't avoid lava
where to set avoid lava
Every time you mine you get into lava and you can't move
minecraft 1.17.1

**Comment by wagyourtail** [comment]
what's your `#modified`
