### ISSUE TITLE
How to place top slabs?

### ISSUE THREAD

**Issue by Johnyisgay1999** [cabaletta/baritone#3649]
## Is there a way to use top slabs with baritone?
Commands such as #sel fill minecraft:cobblestone_slab[type=top] does not work and gives error code
Error at argument #2: ExpectedForBlockOptionalMeta
I apologize if this has already been answered but I tried searching for a solution here before posting, thanks.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
For versions after 1.12.2 there is sadly no way to specify specific blockstates.
However in your case that probably wouldn't help much anyway because Baritone is pretty dumb about placing blocks that depend on how you place them.
