### ISSUE TITLE
How to implementation Baritone API on 1.12.2

### ISSUE THREAD

**Issue by Arseny427** [cabaletta/baritone#3651]
## What do you need help with?
I'm making a mod on 1.12.2 in intellij, how do I embed Baritone in my mod (I tried so many ways and I still don't understand how to do it)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
See #3641 for two solutions that have worked for @Doogie13 and me respectively. If none of the information there helps, just ask on this issue here again (or close it if you got things to work).
