### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by MGThorn** [cabaletta/baritone#3652]
Baritone 1.19.1 the discretion of some commands returned by getLongDesc() is very outdated 

for example the #mine  command tells you to mine log:0 an old block Tag for wood which is updated in minecraft for a very long time to oak_log

small one but still very easy to fix

**Comment by ZacSharp** [comment]
Fixed in #3368 long ago. Baritone just has a very long update and release cycle.
If you have more of such small documentation issues please report them each as a comment on #3369 if they are not listed there yet.
