### ISSUE TITLE
Updating Baritone version in a client.

### ISSUE THREAD

**Issue by CodeDoc537** [cabaletta/baritone#3653]
How would I go about updating Baritone in Meteor Client? As the version they are using is outdated. Don't know too much about java so an explanation would be nice.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Don't think you'll be able to get a more up to date version than latest Meteor without knowing Java.
Meteor (probably, could be unreleased) uses the latest version of Baritone for mc 1.19 so you'd have to merge master up into the correct version branch yourself and then replace the version bundled with meteor.
