### ISSUE TITLE
It wont mine

### ISSUE THREAD

**Issue by JJKom** [cabaletta/baritone#3656]
I need help with the mining it says it won't work and that it's in my logs I don't know how to fix this, so I came here hopping I can get someone to help me with my problem.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
To help you we have to know a little more about what happened so please provide the information requested in the [bug issue template](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md&title=Please+add+a+brief+but+descriptive+title).
