### ISSUE TITLE
what to do if you get argument #2 issue

### ISSUE THREAD

**Issue by logan124554** [cabaletta/baritone#3658]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by logan124554** [comment]
I type in #mine diamond ore it give the issue of argument #2 how to fix?

**Comment by wagyourtail** [comment]
`#mine diamond_ore`

**Comment by logan124554** [comment]
thankyou
