### ISSUE TITLE
can you make it mine multiple ores at the same time

### ISSUE THREAD

**Issue by logan124554** [cabaletta/baritone#3659]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by logan124554** [comment]
can you make it mine diamond ore and deepslate diamond ore for exsample

**Comment by ZacSharp** [comment]
Yes, you can use `#mine <ore1> <ore2> <ore3> <...>`.
