### ISSUE TITLE
add pauseOnKillAura 

### ISSUE THREAD

**Issue by seujorgenochurras** [cabaletta/baritone#3662]
## Describe your suggestion
add a pauseOnKillAura config, that pauses the baritone while kill aura is killing.

## Settings
ON andOFF

## Context
i'm currently dying a lot to mobs because baritone is trying to mine while killaura is trying to kill, that creates a conflict 

## Final checklist

- [ ] I know how to properly use check boxes 
- [x] i don't know what i'm doing here
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Mathrandom7910** [comment]
Baritone has no ka, and therefore no way to detect ka. Most clients with baritone integration have this option.

**Comment by ZacSharp** [comment]
As @Mathrandom7910 said, this is the responsibility of the client you are using, not Baritone.
