### ISSUE TITLE
baritone automine minYLevelWhileMining

### ISSUE THREAD

**Issue by iLookUnderSkirt** [cabaletta/baritone#3667]
Hello, my question is why when i set the minylevel to 10 the autominer still goes bellow this hight and farms at all y levels... i need this to farm mutch faster money with only stone blocks on an citybuild server... is there any whay to limit the hight to y10 or higher?

**Comment by ZacSharp** [comment]
`minYLevelWhileMining` limits `#mine` to only mine ores which are at least `minYLevelWhileMining` blocks above the minimum height of your world.
So if your world goes from y=-64 to y=319 setting `minYLevelWhileMining` to 74 will cause Baritone to only mine ores at y>=10, but Baritone will still walk wherever is needed to get to the ore.
