### ISSUE TITLE
Do this 

### ISSUE THREAD

**Issue by usereewrjrjeejr** [cabaletta/baritone#367]
**### _Feb 22, 2019 6:12 PM
hmm today i will make baritone fill in the path behind it_**

**Comment by leijurv** [comment]
2 more days until its a month old and i can do it

**Comment by usereewrjrjeejr** [comment]
What timezone?

**Comment by THEREALWWEFAN231** [comment]
BROOOO just use wwe utility mod, it has tunneller with working back fill and lava fill, this is irrelevant sorry but yeah

**Comment by leijurv** [comment]
lol lol lol lol lol

**Comment by usereewrjrjeejr** [comment]
Please

**Comment by Bendito999** [comment]
modified Torcher mode that instead of blocks places torches once in a while wuld be cool too (maybe the concepts are kind of similar hMmM).  lol nice tho

**Comment by usereewrjrjeejr** [comment]
Today 😎

**Comment by leijurv** [comment]
ok lol https://youtu.be/0kUP71ctcsE
