### ISSUE TITLE
Baritone crashes when being used

### ISSUE THREAD

**Issue by MapleTheDog** [cabaletta/baritone#3670]
## Some Information
Operating system: Windows 10 Pro
Java version: java version "17.0.2" 2022-01-18 LTS
Minecraft version: 1.18.2
Baritone version: the one in Meteor Client 0.4.9
Other mods (if used): CITResewn-1.1.1+1.18.2, fabric-api-0.51.1+1.18.2, meteor-client-0.4.9, reeses_sodium_options-1.4.3+mc1.18.2-build.42, sodium-extra-0.4.5+mc1.18.2-build.42, sodium-fabric-mc1.18.2-0.4.1+build.15

## Exception, error or logs
Windows: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "<parameter1>" is null
![image](https://user-images.githubusercontent.com/101991101/192167452-1f747810-1159-4e7c-b7ea-d014a024cf9c.png)

## How to reproduce
Use "#sel shl polished_deepslate"
Wait until Minecraft freezes and crashes.
(It only works under certain circumstances)

## Modified settings
To get the modified settings run `#modified` in game
![image](https://user-images.githubusercontent.com/101991101/192167359-063fe85a-38b6-4f21-88f1-5de06f8a92dd.png)
![image](https://user-images.githubusercontent.com/101991101/192167372-1650ff44-61bf-4a5d-ac63-3d8210a57a21.png)
![image](https://user-images.githubusercontent.com/101991101/192167392-c8774f24-5f22-47e0-84c2-b333298d1f53.png)
![image](https://user-images.githubusercontent.com/101991101/192167400-1de4e460-e567-4955-9640-b1be18e24521.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
this has been fixed on our end
