### ISSUE TITLE
How do I update baritone when it's built into my client?

### ISSUE THREAD

**Issue by MapleTheDog** [cabaletta/baritone#3671]
## What do you need help with?
So, I have this bug in baritone that's on older versions of baritone and is patched on newer versions. Baritone is built into my client so I don't know how exactly I can update it to prevent this bug. I need to update baritone without updating my client. I'm using Meteor Client.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Ask them not us
