### ISSUE TITLE
Mutable Ore Mining

### ISSUE THREAD

**Issue by MooTwoo1** [cabaletta/baritone#3673]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Is there a way to mine all the ores ingame? I've tried adding commas or semi colens.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
Just add a space, for example `#mine diamond_ore iron_ore`
