### ISSUE TITLE
Farm: fortune tool.

### ISSUE THREAD

**Issue by LastDice** [cabaletta/baritone#3675]
## Describe your suggestion
How about using the Fortune tool when baritone carries out Farm commands?

## Settings
amm.. 'FarmUseFortuneTool' ?

## Context
You can get more from using Fortune tools.

Sry, i used Translator

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #2495
