### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Lamar1526** [cabaletta/baritone#3677]
what is going on here
![2022-09-30_16 26 34](https://user-images.githubusercontent.com/98684291/193358919-bf74ba8d-ce7f-477c-b95e-cc78f07cf817.png)

**Comment by wagyourtail** [comment]
please fill out the bug report template

**Comment by wagyourtail** [comment]
tho, from a guess the baritone toast setting is enabled, you could try disabling it

**Comment by Lamar1526** [comment]
it was in fact lag as toast thank you for the help
