### ISSUE TITLE
Action files?

### ISSUE THREAD

**Issue by CoC-Fire** [cabaletta/baritone#3679]
There should be a way to create a custom file which would contain a set list of commands that baritone would execute, that would be opened in-game by using "#do", "#open", or "#run", and could create a function of some sort, which could be called in another file. Doing this would greatly increase the efficiency of the bot, and if inventory compatibility could be added in a way similar to autobot, without being a long and involved process to set up, but only usable within these "function" files, this would be a significant improvement.
Expanding on my previous suggestion for inventory functionality, if you add a variety of ways to move items inside an inventory to create different types of bots, for example (I also will be using pseudocode because I really don't feel like trying to create some elaborate example that probably won't be used in anything, so please don't bug me about how I did something wrong), using something similar to this: "mine 300 iron_ore; mine 75 coal_ore; mine 8 cobblestone; mine 1 log; craft 4 wood_plank; craft 1 crafting_table; place crafting_table; goto crafting_table; craft 1 furnace" and so on, you could create a bot to harvest resources, or  by using this: "goto ~ ~; goto chest; move cslot_4 to islot_1; goto ~ ~ ~; goto chest; move islot_1 to cslot_1; goto lava" with cslot meaning chest slot and islot meaning inventory slot, you could create a delivery bot which would be fully automated and would commit suicide to tp back to respawn location to prevent being followed. One other command could be to move all of one item either from inventory to a chest, or vice versa. I honestly don't expect anything to be done about this immediately, because there are likely other more important issues to deal with, but it is definitely something to consider working on when you get a chance.

**Comment by ZacSharp** [comment]
Running command sequences has already been suggested in #186 (and others) and the additional inventory handling is out of scope. You might want to use Baritone together with a general purpose scripting mod.
(`#goto lava` won't commit suicide btw, you'll have to find a different trick)
