### ISSUE TITLE
Doesn't want to build where I want, but wants to build where other blocks were built, he's breaking blocks

### ISSUE THREAD

**Issue by MelvinSGjr** [cabaletta/baritone#3683]
## Some information
Operating system: Windows 11 Licensed (automatically update)
Java version:last (automatically update)
Minecraft version: 1.16.5
Baritone version: ???
Other mods (if used): Schematics 

## Exception, error or logs
Previously, you can build on BuildBattle, but now he does not build, says all the layers are built, and still in another place if you build, he will go to smash what does not touch the radius of building, make it in the middle (where I myself stay) to build the selected building. (I'm trying and on the servers)
![image](https://user-images.githubusercontent.com/102232826/194695337-08b5c871-5d73-4cc1-ae44-76b802d7ecda.png)

Baritone Settings: freeLook false; buildInLayers true

Not always, but writes it:
![image](https://user-images.githubusercontent.com/102232826/194695107-0ad641ec-03aa-4ecf-b2a4-14b085660caf.png)
If you write Resume:
![image](https://user-images.githubusercontent.com/102232826/194695184-4bfbaa1b-326d-4875-a7f1-9f6fa856c220.png)

**Comment by MelvinSGjr** [comment]
pls, help!!!

**Comment by rycbar0** [comment]
can you add the log file and the schematic you're trying to build.

**Comment by ZacSharp** [comment]
Missing "null" blocks is a bug that is already fixed on master, 1.16.5 and #3458 so I suggest you use the latest CI build for 1.16.5 from [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.16.5+event%3Apush+is%3Asuccess) (Click on the latest entry and download the artifacts at the bottom).

It seems like you are using a ".schematic" file, which is a format that doesn't work properly on versions after 1.12.2. When using Minecraft 1.13+ you should use ".schem" files instead (and if you use the CI build you can even try out our brand new ".litematic" support). There's plenty of converters for that purpose.

Also it seems like you are assuming the schematic will be centered on your position, which is wrong. Baritone will place the -x, -y, -z corner on your position.
