### ISSUE TITLE
Found a bug i dont know if is new or something but ill send anyway

### ISSUE THREAD

**Issue by levgamm123** [cabaletta/baritone#3685]
## Some information
Operating system: windows 10
Java version: version 8 update 51
Minecraft version:  1.12.2 forge
Baritone version: standalone-forge 1.2.15
Other mods (if used): optifine, xaeros minimap, jei, ic2, buildcraft, mr crayfish's gun mod, obfuscate, aysu's medis - medicine items.

## Exception, error or logs 
[latest.log](https://github.com/cabaletta/baritone/files/9739459/latest.log)
on\ Support/minecraft/logs/` exception: Pathing exception: java.lang.NullPointerException 

## How to reproduce
idk if if this is it (im russian) but: so i played for a while then i wanted to mine some iron and then baritone SPAMS this exception

## Modified settings
avoidance: true, allowparkour: true thats all

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I'm pretty certain this is already known, but I can't find an issue for it.

It seems like you uploaded the wrong log, can you please upload one containing the error message?

**Comment by Mathrandom7910** [comment]
Tlauncher 💪
