### ISSUE TITLE
Pathfinding Breaks in water 

### ISSUE THREAD

**Issue by caseyleenb** [cabaletta/baritone#3689]
https://youtu.be/dctZbQp2Fqc

Video of the bug.

baritone will consistently not know how to deal with being stuck in water & lock up. 

I was using the sel ca command to mine out a rectangular area, when it got stuck. the bot would make no attempt to stay above the surface, unsure if it would've drowned itself. 

block reach limited to 2 blocks, layer order = true, digging in layers, all other settings default.

**Comment by ZacSharp** [comment]
This is the builder having trouble with water, which is expected. You'll have to either remove the water yourself to make it work.
