### ISSUE TITLE
Farming with holes

### ISSUE THREAD

**Issue by Mankifg** [cabaletta/baritone#3693]
## Describe your suggestion
Optional parameter to use specific item to harvest or sloth in invetory

## Settings
A specific tool or number of sloth in inventory

## Context
On farming servers where it it requred to use hoes it will use one.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by liangforstudy** [comment]
I Support this enhancement, I also wish this is a feature where you can use your fourtue pick instead of hoe. :D

**Comment by UltraBlackLinux** [comment]
just disable autoTool?

**Comment by Mankifg** [comment]
Ok, disabling autoTool work. Thanks.
