### ISSUE TITLE
bug with auto-breaking of the selected area

### ISSUE THREAD

**Issue by MRFICS666** [cabaletta/baritone#3694]
## Some information
Operating system: win 11
Java version:17
Minecraft version:1.18.2
Baritone version:1_8_2
Other mods (if used): assembling "Foblyosity Optimisate 1.18.2

## Exception, error or logs
Please find your `latest.log` or `debu

g.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/` [latest.log](https://github.com/cabaletta/baritone/files/9841021/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.  I highlighted the area using the click command, then I prescribed sel cleararea and an error was displayed to me and the link is not github

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You are using an incompatible version of Baritone (see issue 3339).
Baritone v1.8.2 is for Minecraft 1.18.1, Baritone v1.8.3 is for Minecraft 1.18.2.
