### ISSUE TITLE
1.19 artifact expired

### ISSUE THREAD

**Issue by priyam1234-spec** [cabaletta/baritone#3695]
## What do you need help with?
i just need the 1.19 artifact as the links the people have been sending of the workflow has expired. please send me one i need asap. ty

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
[Here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apush+branch%3A1.19.1)'s a list of CI runs on the 1.19.1 branch, just pick the latest one and download the artifacts.
