### ISSUE TITLE
How do i get this running on forge 1.19.2?

### ISSUE THREAD

**Issue by ATH4** [cabaletta/baritone#3708]
i have tried the solution mentioned in a similar question(this one specifically https://github.com/cabaletta/baritone/issues/3588#issuecomment-1203819187 ), 
however (likely due to my inexpedience with gitub) i wasn't able to download the jars. then i tried compiling it with intelij according to the instructions(which did produce jar files, but when placed in the mods folder. MC doesn't seem to know they are in there, likely caused a suspected mess-up from me during the: "In Edit Configurations... you need to select baritone_launch for Use classpath of module:. " step).

any help(or sending the jars for 1.19.2 if you have them already) would be appreciated

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
![image](https://cdn.discordapp.com/attachments/822011851930992660/1031090545822543992/Peek_2022-10-15_23-24.gif)

**Comment by ATH4** [comment]
Thank you.
