### ISSUE TITLE
Bariton backfill meteor-cheat

### ISSUE THREAD

**Issue by FlerysGaMe2032** [cabaletta/baritone#3709]
How do you make sure that after the tunnel backfill stops, the 2-block posts are formed and they are also backfilled?
Maybe there is option in the baritone? And how may make diagonal tunnel?
![2022-11-02_11 46 24](https://user-images.githubusercontent.com/117265266/199442172-64a458be-805d-4fee-86fe-03860042013f.png)

**Comment by UltraBlackLinux** [comment]
There is no diagonal tunneling

also what?
