### ISSUE TITLE
Ability to rotate schematics / copied selections

### ISSUE THREAD

**Issue by imadraude** [cabaletta/baritone#3711]
## Describe your suggestion
This setting will allow you to more finely control the construction of structures, to customize which way they will look when building them.

## Settings
This should be a number field/switch with 4 positions (0, 90, 180, 270) that takes the value of how many degrees you want to turn the construction clockwise.

## Context
When building a downloaded scheme, the construction often doesn't fit in with things already built next to it, because it's not looking in the right direction for me. It would also be possible to do some sort of residential neighborhoods by putting buildings across from each other. And a lot of other cases as well.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
with the comming support of .litematic files this functionality will be included when building schematics with the `#litematica` command. this requires that the litematica mod is installed.
atm this is only avivable as CI build for 1.12, 1.16, 1.17 and 1.18

**Comment by imadraude** [comment]
> with the comming support of .litematic files this functionality will be included when building schematics with the `#litematica` command. this requires that the litematica mod is installed.
> atm this is only avivable as CI build for 1.12, 1.16, 1.17 and 1.18

wow, glad to hear that litematica support is going to be added
