### ISSUE TITLE
Anti-AFK

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#3717]
## Describe your suggestion
Please add an antiafk feature, it should be reasonably easy to implement

## Settings
#antiafk (just randomly jump, sneak, walk one block, and punch the air)

## Context
I think this is something that fits very well into the baritone client. Baritone can move, rotate the camera, jump and sneak so it should work.

I don't like using full cheat clients. The max I want to use is baritone

**Comment by ZacSharp** [comment]
Adding this would be really easy (it is easy for literally any client side mod), but I honestly don't see how this could be considered in scope for Baritone.
If you don't want to use a hack client then you will also have to live without hack client features. Making Baritone a hack client without admitting it is not a solution.
