### ISSUE TITLE
Clickable commands don't work in 1.19.2

### ISSUE THREAD

**Issue by PiTheGuy** [cabaletta/baritone#3719]
## Some information
Operating system: Windows 11
Java version: 17.0.3
Minecraft version: 1.19.2
Baritone version: fabric, can't find the version number (#version says null version)
Other mods (if used): 

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/9946581/latest.log)

## How to reproduce
1. run #help
2. try to click one the commands
3. notice nothing happens

## Additional information
This appears to due to changes that prevent click events from send chat messages that aren't commands (start with "/"). It also shows an error message in the console when trying to click a command:

Failed to run command without '/' prefix from click event: '<<8a2f6afc-7dcf-400a-9cce-aaf16f103f72>>wp info home @ 1667759334265'

## Modified settings
allowInventory: true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Update, its fixed

**Comment by xAlphy** [comment]
> Update, its fixed also duplicate issue

its not working for me even with the options that show up for #wp goto death
