### ISSUE TITLE
Baritone never finishes to mine bigger ore vains

### ISSUE THREAD

**Issue by Mcknife96** [cabaletta/baritone#372]
When mining blocks that occur in large vains (coal, iron or other things like wood) Baritone mines a few blocks from the big vain, then proceeds to search for the next place to mine at, leaving you with fyling tree tops and half mined out resource deposits.

Reproduce: Stand in a forest and type .b mine log

**Comment by leijurv** [comment]
this is because it has a penalty for placing a block. it defaults to 1 second. if it can go to the next tree in less than a second, it'll pick that one over pillaring up and mining another log. you can change this setting, it's called `blockPlacementPenalty`

**Comment by leijurv** [comment]
oh also, make sure you have acceptable throwaway items on your hotbar in the first place (defaults to stone, dirt, or netherrack)

**Comment by Mcknife96** [comment]
Thanks a lot for the advice. Is it possible to change the throwaway items to leaves or some decaying block?

**Comment by leijurv** [comment]
yuh just hit that `acceptableThrowawayItems minecraft:cobblestone,minecraft:netherrack,minecraft:stone,minecraft:leaves`

**Comment by leijurv** [comment]
you can also shut down, add that line to baritone/settings.txt, then start back up again

**Comment by leijurv** [comment]
pretty much fixed with https://github.com/cabaletta/baritone/commit/26256e71554e379cc2b8a5f55eb83f728b1c4eee#diff-66c829ff7f0fa8975430de3d77d7b6a0R109

**Comment by 0-x-2-2** [comment]
very cool commit 👍
