### ISSUE TITLE
Not all settings saved

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#3722]
## Some information
Operating system: Linux
Java version: 19
Minecraft version: 1.19.2
Baritone version: 1.19.2-SNAPSHOT (Unofficial, but should still apply)
Other mods (if used): does it matter?

## Modified settings
Settings like allowParkour and allowDiagonalAscend and allowDiagonalDescend seem to reset to their default state whenever I restart the game - Why?

**Comment by ZacSharp** [comment]
> Other mods (if used): does it matter?

Yes, you are (probably, you might have multiple setups) using AltoClef, which forces some settings to specific values on startup.

**Comment by UltraBlackLinux** [comment]
Oh! Thanks! I didn't think it would do that
