### ISSUE TITLE
Builder will not replace incorrect blocks if the blockid is the same

### ISSUE THREAD

**Issue by Haxified** [cabaletta/baritone#373]
![Capture](https://user-images.githubusercontent.com/18425863/55276438-a45f1e00-52eb-11e9-8735-10bc15fc9a68.PNG)

**Comment by leijurv** [comment]
No...? https://youtu.be/FszGqJUl-vQ

**Comment by Haxified** [comment]
idk its not me

**Comment by 0-x-2-2** [comment]
axiom issue detected
