### ISSUE TITLE
Unable to use .litematica files 

### ISSUE THREAD

**Issue by MoutonRedstone** [cabaletta/baritone#3730]
## Some information
Operating system: Windows
Java version:
Minecraft version: 1.19.2
Baritone version: 1.8.3
Other mods (if used): too many to mention (over 20) but I have litematica installed
I know 1.19 is still in development and I wanted to report this bug to help the development

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
I have a .litematica file in my schematics folder
I loaded it in litematica mod
I ran the command #build steampunk_tower.litematica 56 80 -134

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
so what exactly is the problem?
baritone has added .litematic support just reasently. if you downloaded baritone more than 2 weeks ago it wasnt supported back then. i suggest you update baritone and try again.

**Comment by ZacSharp** [comment]
As rycbar0 said, litematic support (especially for mc 1.19) is a very new feature (12 days) and you will have to use a [CI build](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.19.1) to get it. Select the run you want (you want "[Merge pull request #3707 from ZacSharp/1.19.2-update](https://github.com/cabaletta/baritone/actions/runs/3409183433)" or newer), scroll down and download the artifacts.

**Comment by ZacSharp** [comment]
If you are actually using a version with litematic support, please provide a logfile and a description of what happened.
