### ISSUE TITLE
Issue with path finding diamonds

### ISSUE THREAD

**Issue by krhobeck** [cabaletta/baritone#3737]
I'm not sure if anyone else is having this issue but using Baritone in 1.18+, I have found that it does not find the closest diamond; in fact, the algorithm doesn't even detect the nearest ones. Some get detected in the ground while a large majority don't (even on a single-player server). X-raying I can see tons of diamonds that are not being picked up by baritone and this is quite annoying.

Curious if anyone else has this issue or whether this is something on my personal end.

**Comment by ZacSharp** [comment]
You are probably using a version older than 25 days and are running into #3637.
Using the latest CI build from [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.18.2+is%3Asuccess+event%3Apush) should fix this.

**Comment by inruzzzzzz-dev** [comment]
> I'm not sure if anyone else is having this issue but using Baritone in 1.18+, I have found that it does not find the closest diamond; in fact, the algorithm doesn't even detect the nearest ones. Some get detected in the ground while a large majority don't (even on a single-player server). X-raying I can see tons of diamonds that are not being picked up by baritone and this is quite annoying.
> 
> Curious if anyone else has this issue or whether this is something on my personal end.

I m facing the same issue , what to do now ?
