### ISSUE TITLE
Obvious mode

### ISSUE THREAD

**Issue by kittenvr** [cabaletta/baritone#3740]
## Describe your suggestion
Make it so it can Flight, Tp, Nuker, ...

## Settings
Different flights
## Context
it would make it better to use like it can pathfind using flight.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There's already a lot of issues on using various forms of flight and the other suggestions are a bit too vague and seem like they could easily be out of scope (Baritone is a pathfinding bot, teleportation kinda defeats the purpose).
