### ISSUE TITLE
Update version 1.19

### ISSUE THREAD

**Issue by wanLan1051** [cabaletta/baritone#3745]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone works on the latest version of Minecraft (1.19.2) and there's already preparations for the next release (1.19.3) so there's nothing to update to.
It's just that there is no Baritone release for mc 1.19 so you will have to use a [CI build](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.19.1) (you should do so for any version anyway as releases are not mode very often)
