### ISSUE TITLE
itemSaverThreshold not working, what am I missing?

### ISSUE THREAD

**Issue by xMistt** [cabaletta/baritone#3747]
## What do you need help with?
![image](https://user-images.githubusercontent.com/55298769/205459178-3c35807a-3e11-48c1-ab23-37992c428420.png)
Am I stupid? Why is it not working? Tried with setting a durability value and just the setting on its one, both times it says the setting doesn't exist.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
What baritone version are you using? If it is 1.2.15 then that version is too old to have it (currently no 1.2.x versions have it so you need to use an action build)

**Comment by xMistt** [comment]
Yeah that'll be why, I'm on 1.2.15, can you link a working action version for 1.12.2? The the most recent one with the 1.12.2 tag is 8 months old so I assume that won't have the setting either.

**Comment by xMistt** [comment]
Nevermind, found it.

**Comment by bitmanleo** [comment]
Encountering the same issue. Can you share the link you found?

**Comment by rycbar0** [comment]
https://github.com/cabaletta/baritone/actions/runs/3364163328
