### ISSUE TITLE
Missing site info 

### ISSUE THREAD

**Issue by usereewrjrjeejr** [cabaletta/baritone#375]
https://baritone.leijurv.com/baritone/api/Settings.html#field.detail allow backfill is missing

**Comment by 0-x-2-2** [comment]
nice brain nerd thats because backfill is not on master

**Comment by 0-x-2-2** [comment]
also these are auto generated

**Comment by babbaj** [comment]
🦍

**Comment by Haxified** [comment]
900 iq
