### ISSUE TITLE
1.19.2 version of the bot version 

### ISSUE THREAD

**Issue by booa12** [cabaletta/baritone#3750]
can some one send the 1.19.2 .jar file of this version https://github.com/cabaletta/baritone/tree/bot-system barritone pls

**Comment by TheK0tYaRa** [comment]
There is a guide on compiling and a github action that can be applied to the branch

**Comment by booa12** [comment]
oh the 1.19.2 version

**Comment by TheK0tYaRa** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself

**Comment by TheK0tYaRa** [comment]
Also, consider googling before using `issues` for simple issues like this.

**Comment by booa12** [comment]
ok
