### ISSUE TITLE
Baritone for 1.19.2

### ISSUE THREAD

**Issue by IPlayMinecraftYT** [cabaletta/baritone#3751]
## What do you need help with?
When will baritone for 1.19.2 come out. meteor supposedly has it but when using .mine it will go towards the world border, instead of mining the blocks I want it to mine.

**Comment by rycbar0** [comment]
there is no planed releas in the near future but if you need a 1.19 version you can use a CI build.
https://github.com/cabaletta/baritone/actions/runs/3409183433
download and unzip the artifacts and select the baritone version of your likeing
