### ISSUE TITLE
Baritone ignoring Please add a brief but descriptive title

### ISSUE THREAD

**Issue by IPlayMinecraftYT** [cabaletta/baritone#3752]
## Some information
Operating system: windows 10
Java version: 8 (update 333)
Minecraft version: 1.19.2
Baritone version: baritone version within meteor client 0.5.1
Other mods (if used): fabric api (currently using theoneprobe, journeymap, cloth, architechtuary, fpsdisplay, lambdynamiclights, phosphor, lithium, sodium, REI, neat, but same issue when just fabric api)

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/10180205/latest.log)

## How to reproduce

Download meteor client 0.5.1 (requires fabric api and fabric 1.19.2)

attempt to .b mine iron_ore (the meteor syntax)

baritone will ignore all iron ore and instead path to the middle of nowhere

## Modified settings

allowparkour true
allowparkourplace true
avoidance true
avoidbreakingmultiplier 0.1
blockbreakadditionalpenalty 0.0
blockreachdistance 4.5
blockstoavoidbreaking crafting_table,furnace,chest,trapped_chest,ice,packed_ice
cachedchunksopacity 0.5
colorbestpathsofar 0,0,255
colorblockstobreak 255,0,0
colorblockstoplace 0,255,0
colorblockstowalkinto 255,0,255
colorcurrentpath 255,0,0
colorgoalbox 0,255,0
colorinvertedgoalbox 255,0,0
colormostrecentconsidered 0,255,255
colornextpath 255,0,255
colorselection 0,255,255
colorselectionpos1 0,0,0
colorselectionpos2 255,200,0
failuretimeoutms 2000
followoffsetdirection 0.0
goalrenderlinewidthpixels 3.0
maxxfallheightnowater 255
minedroploiterdurationmsthankslouca 250
minylevelwhilemining 139
pathingmaploadfactor 0.75
pathrenderlinewidthpixels 5.0
planaheadfailuretimeoutms 5000
planaheadprimarytimeoutms 4000
primarytimeoutms 500
selectionlinewidth 2.0
selectionopacity 0.5
slowpathtimeoutms 40000
toasttimer 5000
(something of note is a lot of these that show up are actually the default values)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
idk what meteor is doing but the log says you try to mine obsidian (line 327)

**Comment by liangforstudy** [comment]
There's probably no iron_ore around you, is there?

**Comment by IPlayMinecraftYT** [comment]
there was, it turns out that the settings meteor puts in makes baritone stop working
