### ISSUE TITLE
[1.19.3] not being able to use #mine on specific server

### ISSUE THREAD

**Issue by Jody24** [cabaletta/baritone#3753]
## Some information
Operating system:
Java version: 17.0.1
Minecraft version: 1.19.3
Baritone version: a build by Wagyourtail#3826
Other mods (if used): Xaero minimap, modmenu, mouse tweaks, wurst, inventoryprofilesnext, sodium, iris, libIPN

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/10187625/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
go to a world and try to use #mine

## Modified settings
To get the modified settings run `#modified` in game
allowParkour true
allowParkourPlace true
chatControl false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Jody24** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/10187620/latest.log)

**Comment by Jody24** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/10187625/latest.log)

**Comment by rycbar0** [comment]
1. atleast change the titel of the issue 
2. try it without other mods to confirm its a baritone problem and if its a problem that only happens with other mods mention what mod causes a problem
3. pls use the unoptimised version to submit logs else its inpossible to debug

**Comment by Jody24** [comment]
I've run it without other mods and used the unoptimized version

[latest.log](https://github.com/cabaletta/baritone/files/10187827/latest.log)

**Comment by Jody24** [comment]
found that it was unable to get my position, fixed it by going through a portal to reset the position
