### ISSUE TITLE
Please add a brieAn unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issuesf but descriptive title

### ISSUE THREAD

**Issue by idksalem** [cabaletta/baritone#3760]
## Some information
Operating system: w10
Java version: 
Minecraft version:1.19.3
Baritone version: meteor
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues [10:38:14] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null [10:38:14] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source) [10:38:14] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source) [10:38:14] [Render thread/INFO]: [STDERR]: 	at meteordevelopment.meteorclient.systems.commands.commands.BaritoneCommand.lambda$build$0(BaritoneCommand.java:26) [10:38:14] [Render thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) [10:38:14] [Render thread/INFO]: [STDERR]: 	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:88) [10:38:14] [Render thread/INFO]: [STDERR]: 	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:83) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.handler$zmf000$onSendChatMessage(class_408.java:560) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [10:38:14] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [10:38:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [10:38:14] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [10:38:14] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null [10:38:14] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source) [10:38:14] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source) [10:38:14] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source) [10:38:14] [Render thread/INFO]: [STDERR]: 	... 30 more

https://mclo.gs/nzdK28l

## How to reproduce

i just do #mine and then boom

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [✔] I know how to properly use check boxes 
- [✔] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [✔ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ✔] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
same issue as #3753
