### ISSUE TITLE
Is there a way to download "expired" files?

### ISSUE THREAD

**Issue by AzeemLumilox** [cabaletta/baritone#3761]
I've been trying to download baritone for 1.19, but when I click on the versions, they all say "expired". Am I just not looking at the most updated versions of the 1.19 versions? Or can you not get them anymore?

**Comment by rycbar0** [comment]
you can get the 1.19.2 version [here](https://github.com/cabaletta/baritone/actions/runs/3409183433)
or the 1.19.3 version [here](https://github.com/cabaletta/baritone/actions/runs/3679500984)

**Comment by ZacSharp** [comment]
In case those links expire as well (they will) you can find a list of all successful CI builds on the Baritone repository [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apush) (note that 1.19.2 is on the 1.19.1 branch) and until the 1.19.3 pr is merged you can find a list of its CI runs [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apull_request+actor%3Awagyourtail+branch%3A1.19%2F1.19.3).
