### ISSUE TITLE
#mine doesn't work

### ISSUE THREAD

**Issue by zipthebip** [cabaletta/baritone#3763]
## Some information
Operating system: Windows
Java version: 1.8
Minecraft version: 1.19.3
Baritone version: 1.19.3 SNAPSHOT
Other mods (if used): Meteor Client 1.19.3

## Exception, error or logs
[debug.txt](https://github.com/cabaletta/baritone/files/10254958/debug.txt)

## How to reproduce
type: # (or .b) mine diamond_ore

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by zipthebip** [comment]
If it wasn't apparent by Meteor, this is run on Fabric.

**Comment by rycbar0** [comment]
dublicate of #3756
