### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Andrelissss** [cabaletta/baritone#3764]
## What do you need help with?
I cant find the forgegradle all I see is 
![image](https://user-images.githubusercontent.com/80877847/208485321-6a2001db-0ef2-4405-acf7-296089883569.png)

this is what i m trying to build : https://github.com/xyqyear/baritone/tree/91b40177c692fb5cc9806e609cc66e4a99835add
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
skip the forgegradle step and just run build. it's only needed on the 1.12.2 version
