### ISSUE TITLE
I m unable to build this, getting artifact not found

### ISSUE THREAD

**Issue by Andrelissss** [cabaletta/baritone#3765]
## What do you need help with?
I m trying to build this:https://github.com/SM1LLER/baritone/tree/ccc3913e8c043d53407e13b6ddb41edb21d6f7b2

but when i press build i get this 
![image](https://user-images.githubusercontent.com/80877847/208725738-9f6fc8c2-60cd-4d4f-8aad-3652b35cf74e.png)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proguard'.
> Artifact not found! Run build first!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

it says me to run build first but thats what i m running

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
is the worksspace set up?
have you selected the correct script to build the jars?
have you changed anything inside progard/the build script regarding where the files should get saved / is progard searching them at the right position?

**Comment by Andrelissss** [comment]
how do i setup work space? and i didnt change anything i m just trying to build it 
![image](https://user-images.githubusercontent.com/80877847/208730057-b27b514f-16ac-4c99-8373-92c44e223ed3.png)
this is what i m running

**Comment by rycbar0** [comment]
your on a 1.12 branche right? (its only needed there)
go to:  baritone > tasks > forgegradle > setupDevWorkspace
run it once and try building the jars again

**Comment by Andrelissss** [comment]
1.18

**Comment by rycbar0** [comment]
last thing before i have to give up is try make a break point at the following method and run the build script in debug mode. maybe you finde out what goes wrong
baritone>buildSrc>src>main>java>baritone>gradle>task>BaritoneGradleTask>verifyArtifacts()

**Comment by ZacSharp** [comment]
The version you are trying to build is older than #3363 so you will have to manually add `rootProject.name = 'baritone'` to `settings.gradle`.

**Comment by Andrelissss** [comment]
and how do i do that lol

**Comment by Andrelissss** [comment]
nvm got it working
