### ISSUE TITLE
When does the standalone baritone come out for 1.19.2 fabric?

### ISSUE THREAD

**Issue by ToastMan5** [cabaletta/baritone#3766]
People are all saying "Oh, just get meteor! you're so dumb!!"
But I need it for my fabric loader modpack that is 1.19.2 and this is the only website or person that can provide that
There is one website that offers 1.19 but when I download a very clearly labelled "1.19.2 fabric" option it says it's 1.19.1 and incompatible with 1.19.2 and I tried all the others to no avail

**Comment by wagyourtail** [comment]
Oh just join the discord and do `!1.19`

(We have links there, iirc the 1.19.2 actions may have expired but you can try clicking the actions tab)
