### ISSUE TITLE
Mine daimond_ore wont work

### ISSUE THREAD

**Issue by Carl12345678912** [cabaletta/baritone#3784]
When i use mine diamond_ore i will see the path but in will not move.

Any help with this Thanks.

**Comment by rycbar0** [comment]
Do you have farsight installed?

**Comment by Carl12345678912** [comment]
No i dont

**Comment by wagyourtail** [comment]
Please fill out the bug report template completely

**Comment by NormalHuman-Anything** [comment]
have you paused it? try #resume
