### ISSUE TITLE
Update Baritone

### ISSUE THREAD

**Issue by freshTsunami** [cabaletta/baritone#3791]
## What do you need help with?
I downloaded the artefacts.zip file via this link https://github.com/cabaletta/baritone/actions/runs/3732468264 to update Baritone but I was told that we are now upgrading to 1.8.3-226 for 1.19. 3 are
Where can I download them?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
That action run is 1.8.3-226.
Now that the 1.19.3 pr is merged you can find the latest build for 1.19.3 at the top of [this list](https://github.com/cabaletta/baritone/actions?query=is%3Asuccess+event%3Apush+branch%3A1.19.3) (currently that's 1.8.3-231).
