### ISSUE TITLE
i need help with materials

### ISSUE THREAD

**Issue by GentlemanMC** [cabaletta/baritone#3797]
## What do you need help with?
i want to make baritone ignore that some blocks are missing and just continue with whats available 

![image](https://user-images.githubusercontent.com/76640636/212538445-46eb4530-6125-4935-87d7-9027c02d0c54.png)
basically i want this to stop from happening
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you don't have some of the materials you can add the blocks to `buildSkipBlocks`
