### ISSUE TITLE
Unhandled exception occured, this error is in your games log

### ISSUE THREAD

**Issue by VexxIsCuteFr** [cabaletta/baritone#3799]
![image](https://user-images.githubusercontent.com/122748049/212561305-4baa1702-2a6c-497f-b3ca-242cc63e0113.png)
Both me and my friend experience this problem in my other friends aternos server, works in survival not in multiplayer. Not sure if we downloaded the same thing but please let me know.

**Comment by ehylo** [comment]
Please follow the template so we can actually have useful or any information

**Comment by VexxIsCuteFr** [comment]
When i attemp to upload my logs it says don't support the file type

**Comment by ZacSharp** [comment]
Try renaming the log to "log.txt".
If GitHub still won't let you upload the file then paste it into the issue in a `<details><summary>log</summary> PASTE HERE </details>` "spoiler". Using a paste service is also possible, but then the log will expire after a while, which is not nice.

**Comment by rycbar0** [comment]
can we close this it dosnt look like he going to provide his log files.
