### ISSUE TITLE
Most commands (except goto) lead to an unhandled exception

### ISSUE THREAD

**Issue by GeberWolf** [cabaletta/baritone#3802]
## Some information
Operating system: Windows 11
Java version: Version 8 Update 321 (build 1.8.0_321-b07)
Minecraft version: 1.19.3
Baritone version: Null version
Other mods (if used): appleskin-fabric-mc1.19.3-2.4.2.jar, architectury-7.0.66-fabric.jar, axolotl-item-fix-1.1.4.jar, balm-fabric-1.19.3-5.0.1.jar, beenfo-1.19.3-fabric0.68.1-1.3.3.jar, BetterF3-5.1.0-Fabric-1.19.3.jar, bettermounthud-1.2.1.jar, BetterPingDisplay-Fabric-1.19.3-1.1.1.jar, betterstats-2.1.+1.19.3.jar, Boat-Item-View-Fabric-1.19.3-0.0.4.jar, Bookshelf-Fabric-1.19.3-17.0.2.jar, chat_heads-0.9.0-fabric-1.19.3.jar, cloth-config-9.0.94-fabric.jar, CullLessLeaves-1.1.0.jar, custom-crosshair-mod-v1.5.2-fabric-mc1.19.3.jar, DistantHorizons-1.6.10a-1.19.3.jar, easiervillagertrading-1.19.3-fabric0.68.1-1.5.4.jar, eating-animation-1.9.1.jar, EnchantmentDescriptions-Fabric-1.19.3-14.0.4.jar, entityculling-fabric-1.5.2-mc1.19.3.jar, extended-armor-bars-1.2.1.jar, fabric-api-0.71.0+1.19.3.jar, fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar, ferritecore-5.1.0-fabric.jar, freecam-fabric-1.1.8+1.19.jar, held-item-info-1.4.2.jar, InventoryProfilesNext-fabric-1.19.3-1.9.1.jar, invhud.fabric.1.19-3.4.7.jar, Jade-1.19.3-fabric-9.2.3.jar, libIPN-fabric-1.19.3-2.0.1.jar, light-overlay-7.0.2.jar, modmenu-5.0.2.jar, mods.txt, mousewheelie-1.10.6+mc1.19.3.jar, paperdoll-fabric-1.1.1-mc1.19.3.jar, shulkerboxtooltip-fabric-3.2.4+1.19.3.jar, XaerosWorldMap_1.28.7_Fabric_1.19.3.jar, Xaeros_Minimap_22.17.0_Fabric_1.19.3.jar, YetAnotherConfigLib-2.2.0.jar, Zoomify-2.9.2.jar, 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/10431084/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

1. AFK for a few hours
2. Attempt to execute any of the following commands:
- thisway
- wp
- reloadall

## Modified settings
To get the modified settings run `#modified` in game

- allowBreak
- legitMine
- maxFallHeightNoWater

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
we already fixed this in 1.8.3-226
