### ISSUE TITLE
Automatically use the hotkey to enable FTB Ultimine

### ISSUE THREAD

**Issue by CaryCatZ** [cabaletta/baritone#3804]
## Describe your suggestion
Allow user to configure Bariton use the hotkey to enable FTB Ultimine

## Settings
Add a new flag in `mine` command to tell Baritone that.

## Final checklist
- [ ] Auto use the hotkey
- [ ] Add a new flag in `mine` command

**Comment by wagyourtail** [comment]
why closed as not planned, we're probably never going to do it, but it's more valid than 90% of the stuff here... maybe if someone's bored one day
