### ISSUE TITLE
NPE for the cached world

### ISSUE THREAD

**Issue by end-user** [cabaletta/baritone#3806]
## Some information
Operating system: windows 11
Java version:  17.0.5
Minecraft version: 1.19.3
Baritone version: 1.8.3-225-g35f3d6d4
Other mods (if used):  lots

## Exception, error or logs
```
[21:39:03] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[21:39:03] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:147)
```

## How to reproduce
Trying to use `#mine`; appears to work fine in single player

## Modified settings
allowSprint (Boolean)
blockPlacementPenalty (Double)
breakFromAbove (Boolean)
buildRepeat (class_2382)
buildRepeatCount (Integer)
chatControl (Boolean)
goalBreakFromAbove (Boolean)
layerOrder (Boolean)
mineDropLoiterDurationMSThanksLouca (Long)
minYLevelWhileMining (Integer)
preferSilkTouch (Boolean)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Already fixed in the latest version (currently that's [1.8.3-231-g7677ed82](https://github.com/cabaletta/baritone/actions/runs/3914210910) and once there's more builds for 1.19.3 you can find them [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.19.3))
