### ISSUE TITLE
[Bug/CrashClient] 1.19.3 Quilt JVM Crash include Baritone

### ISSUE THREAD

**Issue by 8MiYile** [cabaletta/baritone#3808]
## Some information
Operating system:Deepin Linux 20.7.1
Java version:Zulu17.30+15-CA (17.0.1+12) (build 17.0.1+12-LTS)
Minecraft version:1.19.3
Baritone version:Unknown
Other mods (if used): in log

## Exception, error or logs
https://mclo.gs/I9x25DX
https://mclo.gs/oUiC032
https://mclo.gs/MLt23Ax

## How to reproduce
join server and loading chunks (maybe)

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
there appears to be conflicts with the MixinChunkArray as multiple mod whant to override that.

pls remove all mods except for baritone and add them back one at a time to see which mods arnt compatible
in the logfiles i could see betterf3, bbor, languagereload and meteor-client having conflicts with baritone

**Comment by ehylo** [comment]
> Quilt

> Meteor

yeah no meteor does not work on quilt
