### ISSUE TITLE
Kills you

### ISSUE THREAD

**Issue by Ianyourgod** [cabaletta/baritone#3809]
I was trying to mine some bone blocks in the nether and it pathfinded to drop 40 blocks, making me lose fully enchanted diamond armor.

**Comment by arin2115** [comment]
if they were cheated using baritone, why would you even cry about these items?

**Comment by Ianyourgod** [comment]
> if they were cheated using baritone, why would you even cry about these items?

Well, they weren’t cheated. I was just trying to get some bone blocks and mess around with baritone. Also I spent like an hour enchanting them cuz I don’t have villagers.

**Comment by liangforstudy** [comment]
In impact, set drop distance to 3 or something.

**Comment by TomieAi** [comment]
how to mine boneblocks? using baritone?
