### ISSUE TITLE
AutoFarm with Baritone

### ISSUE THREAD

**Issue by AutoKaspersky** [cabaletta/baritone#381]
Add an AutoFarm to baritone, not one that just sits there and breaks crops around you. But by utilizing baritone, it would make it possible for people to have an AutoFarm that automatically walks around to different crops, harvesting and replanting. In this instance you would be able to be 100% AFK.

**Comment by leijurv** [comment]
https://youtu.be/5BYfWHgGW5E

**Comment by Bendito999** [comment]
nOw wE dOn't eVeN ne3d 2 pl4y mEiN kRaFt iT pLaY itSelF
1000% AyyyyFK

**Comment by leijurv** [comment]
https://youtu.be/6Ej5UOK6jus

**Comment by leijurv** [comment]
https://youtu.be/5oC5NZ-G9yU

**Comment by leijurv** [comment]
done lol

**Comment by OscarGreen03** [comment]
confused on how to enable this?

**Comment by BriellaBugs** [comment]
Can this be done in a loop? When the farm fails it just stops
