### ISSUE TITLE
Baritone could use boats or swim in the water

### ISSUE THREAD

**Issue by F6347** [cabaletta/baritone#3814]
## Describe your suggestion
Baritone could use an boat you have in you're inventory or if you don't have an boat swim to go somewhere.

## Settings
A setting to specify the priority of boats or swimming as a means of traversal when multiple options are available
A toggle option to enable or disable the use of boats or swimming

(Also, i don't know what does this settings thing means sorry)

## Context
If i try going somewhere but the only way to go is in water it is ULTRA slow.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
See [here](https://github.com/cabaletta/baritone/blob/master/FEATURES.md#future-features)
