### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by vercito** [cabaletta/baritone#3817]
## Some information
Operating system:w11
Java version:
Minecraft version:1.19.3
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
so i was using baritone in earthmc but when i say mine gold its automaticly goes to deepest Y and just mining straight not even mining gold ore 

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
Is lgitmine turned on?

**Comment by vercito** [comment]
whats that

**Comment by rycbar0** [comment]
A setting that only mines exposed ores. If there are no exposed ores it will dig down and tunnels around until it finds exposed ore blocks.

Also pls provide a list of your #modified just as the template asks you to do. Makes helping you a lot easier.

**Comment by vercito** [comment]
ok i will send new issue that will be more information soerry my english is not so good

**Comment by wagyourtail** [comment]
don't do new, add to this one
