### ISSUE TITLE
Game crashes when Baritone is run with litematica

### ISSUE THREAD

**Issue by Sasanito1** [cabaletta/baritone#3818]
## Some information
Operating system: Windows 11
Java version: update 8 version 321
Minecraft version: 1.19.3
Baritone version: Baritone-fabric-1.19.3-SNAPSHOT
Other mods (if used): fabric-api-0.73.0+1.19.3, litematica-fabric-1.19.3-0.13.1, malilib-fabric-1.19.3-0.14.0, worldedit-mod-7.2.13 .

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/10528350/latest.log)

## How to reproduce
download all specified mods in CURSEFORGE and run.

## Modified settings
Can't get in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
update baritone with a verison from this git repo.
[here](https://github.com/cabaletta/baritone/actions/runs/3914210910) is a link to the newest 1.19.3 version of baritone.
download the artifacts unzip the file and replace your baritone version with the baritone-fabric-xxx-unoptimised.jar
