### ISSUE TITLE
Go back and forth between two points "loop"

### ISSUE THREAD

**Issue by ravoap** [cabaletta/baritone#3822]
## What do you need help with?
Is it possible to somehow get baritone to move between two points like in a loop? I want to step on a pressure plate and go one block back to get items.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
no baritone as you get it from us cant chain commands. you can modify baritone or use a other mod/program that allows to create macros to achive this functionality but base baritone does not support it.
