### ISSUE TITLE
Baritone: How to clear blacklist

### ISSUE THREAD

**Issue by Badwolf15001** [cabaletta/baritone#3823]
When using baritione it was having trouble getting to a few blocks I wanted to mine so It blacklisted those blocks.
But I want to find out how to clear that blacklist so It can try again

**Comment by rycbar0** [comment]
the black list is only safed as long as the process is active therfore by stoping and restarting the process (no not pausing isnt enought you have to stop it) the blacklist get reset aswell.

but the blocks got blacklisted the first time for a reason so they probably will get blacklisted again unless something changed.
