### ISSUE TITLE
How to fix "An unhandled exception occured"

### ISSUE THREAD

**Issue by Izonq** [cabaletta/baritone#3827]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
Congratulation you created a useless issue with not information at all. pleas close this before someone else can see it and you embarrass yourself even more.

if you run into a unhandled exception we need your logfile, preferably the command you where running and your modified settings.

**Comment by wagyourtail** [comment]
please fill out the bug report properly and completely
