### ISSUE TITLE
will baritone work with fabric 1.19.3?

### ISSUE THREAD

**Issue by evija331** [cabaletta/baritone#3831]
i downloaded fabric and i want to know if it will work

**Comment by rycbar0** [comment]
I will work if you use a 1.19.3 fabric compatible baritone version. you can get it [here](https://github.com/cabaletta/baritone/actions/runs/3914210910)

you have to be siged in and then you want to download the artifacts at the bottom of the page. unzip the downloaded artifacts and drag and drop the baritone-fabric-unoptimised-xxx.jar into your mods folder.

**Comment by evija331** [comment]
> I will work if you use a 1.19.3 fabric compatible baritone version. you can get it [here](https://github.com/cabaletta/baritone/actions/runs/3914210910)
> 
> you have to be siged in and then you want to download the artifacts at the bottom of the page. unzip the downloaded artifacts and drag and drop the baritone-fabric-unoptimised-xxx.jar into your mods folder.

how do i install it

**Comment by ZacSharp** [comment]
> unzip the downloaded artifacts and drag and drop the baritone-fabric-unoptimised-xxx.jar into your mods folder.

i.e. like any other mod

**Comment by evija331** [comment]
> > unzip the downloaded artifacts and drag and drop the baritone-fabric-unoptimised-xxx.jar into your mods folder.
> 
> i.e. like any other mod

which folder is it in

**Comment by rycbar0** [comment]
what folder are you talking about?
the downloaded artifact.zip should be in your download folder.
your mods folder is in your .minecraft folder.

**Comment by rycbar0** [comment]
how about start the game and try out a command like #help.

**Comment by evija331** [comment]
i tried the command and nothing worked

**Comment by rycbar0** [comment]
i will guide you once and only once with a step by step list.
1. install fabric for 1.19.3. if you dont know how to do it watch a tutorial.
2. download the artifact file i mentioned in my first reply.
3. open minecraft with the fabric version.
4. go to the settings -> resource packs -> open folder
5. (a file explorer window should be open now) go 1 folder up. that is your minecraft root folder. in here search a folder called "mods". open that folder.
6. unzip the downloaded artifact file and drop the baritone-fabric-unoptimised-xxx.jar into the mods folder you opened in step 5
7. restart minecraft
