### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ThePyGuyYe** [cabaletta/baritone#3833]
## Some information
Operating system:Windows10
Java version:version8
Minecraft version:1.19.3
Baritone version:it says "null (this is normal in a dev environment)"
Other mods (if used): Wurst Client,Replay Mod

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/10699118/latest.log)

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Well i just try #mine diamond_ore and it says to put the issue on github

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ThePyGuyYe** [comment]
this is on a server it works in single player

**Comment by ThePyGuyYe** [comment]
i found ```Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null``` ,     in the latest.log

**Comment by rycbar0** [comment]
try updating baritone this should already be fixed. [here](https://github.com/cabaletta/baritone/actions/runs/3914210910) is a link to the newest 1.19.3 build.
