### ISSUE TITLE
Copy Input Command?

### ISSUE THREAD

**Issue by Apxll0n** [cabaletta/baritone#3835]
Hi guys,
First of all i am pretty new to baritone so i am not 100% certain if this feature is already existent or if there are already other mods that do these things, but i thought it would be great if there was a way to record your inputs, maybe save them and let baritone repeat the same inputs. 
Also a loop function would be needed to make it easier.
I think it would also bypass most anticheats as the inputs are your own and the bot only repeats those inputs. And if the loop is long enough it wouldnt even be noticed that all the actions would be repeated. 
Baritone works just fine 90% of the time but there are some farm designs where baritone struggles.
So i think it would be a nice add on to be able to record your own makros with baritone.

**Comment by rycbar0** [comment]
baritone does not have a shadowing feature to repeat recorded actions.
you could probably write a macro with a macro mod but i can see that this especialy for more organic actions is quite complicated compared to just do the action once and tell a program to loop that actions.

adding a record/replay feature is a question of principal. baritone is at its core a pathfinding bot. while it is ofthen used to automate tasks idk if this feature is inside the the specs of what baritone trys to be. i think having a dedicated mod for just this would be better.

**Comment by ZacSharp** [comment]
There's already enough variations of "loop" or "record" features suggested, so I'll close this even though it adds yet another little variation to the mix (this time it's more about inputs rather than paths).

Nice people don't need to bypass ACs btw.
