### ISSUE TITLE
Baritone only using specific blocks

### ISSUE THREAD

**Issue by WoopWoot** [cabaletta/baritone#3841]
## Some information
Operating system: Windows
Minecraft version: 1.16.5
Baritone version: Latest
Other mods (if used):  Impact

## How to reproduce
For some reason, Baritone can only build with the following blocks: Sand, cobblestone, tnt, netherrack, iron block, emerald block, diamond block, gold block, clay, ice, lapis block, and maybe some others. If any other blocks are used, it will place ONLY the previously stated blocks, then will proceed to say "build finished" without it actually being finished.

My method for creating the schematics goes as follows: Load desired image into MapartCraft, tweak around with blocks, load the nbt file into Cubical xyz, place the mapart flat onto the ground as to avoid problems with sand, and then place the new schematic file into the schematics folder located in .minecraft.

I am using the latest version of Impact, which I am assuming is using the latest version of Baritone, version 1.16.5 of Minecraft, and I'm ONLY using 1.12.2 blocks when loading images into MapartCraft and Cubicle. All the Baritone settings are default as well.

Maybe there's something wrong with my methods? Or it's the fact that I'm using Impact instead of just using Baritone? I have no idea what could be causing these odd set of problems, but I am hoping one of you could help.

## Modified settings
no modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It's probably because you are using a `.schematic` (MCEdit format) file, which doesn't play nicely with versions after 1.12.2 (at least for Baritone that is, other mods like Litematica have a built in converter). Try using a `.schem` (Sponge format) or a `.litematic` (Litematica format, only works if your version of Baritone is really up to date).

**Comment by WoopWoot** [comment]
.litematic file? is that the same as a .nbt file? Is there an way to convert a .schematic to a

**Comment by WoopWoot** [comment]
Issue resolved. I figured it out
