### ISSUE TITLE
Show path but don't follow (mine, goto, etc)

### ISSUE THREAD

**Issue by OnlyCS** [cabaletta/baritone#3848]
## Describe your suggestion
It would allow the user full control over the player, while still pathfinding.

## Settings
There could be a setting to turn this on or off

## Context
It would allow, e.g. avoidance of mobs, or places that you would not want to go, better

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #431
