### ISSUE TITLE
When mining, some items get left behind

### ISSUE THREAD

**Issue by Motzumoto** [cabaletta/baritone#3849]
## What do you need help with?
I've noticed when mining and the ore drops multiple items, the AI sometimes leaves items behind and doesn't go back to pick them up. Is there a setting I can edit to prevent this? It happens way more when you have fortune, so it drops more than normal. Accidentally cut the first clip short, but you can still see it left an item behind

## Proof

https://user-images.githubusercontent.com/45925152/220286764-2350b288-0a51-4dc8-911f-f1f60570d5bd.mp4

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SmRzT** [comment]
Have you got #mineScanDroppedItems enabled?

**Comment by Motzumoto** [comment]
> Have you got #mineScanDroppedItems enabled?

![image](https://user-images.githubusercontent.com/45925152/220346928-04795717-b85f-41ba-8fb6-ced534804b78.png)
I do

**Comment by wagyourtail** [comment]
you could try increasing #mineDropLoiterDurationMSThanksLouca

**Comment by Motzumoto** [comment]
> you could try increasing #mineDropLoiterDurationMSThanksLouca

What does this do exactly?

**Comment by rycbar0** [comment]
https://github.com/cabaletta/baritone/blob/c5721fb7e3c106dcbf904e080933ee8e14a15a1b/src/api/java/baritone/api/Settings.java#L1025-L1031
