### ISSUE TITLE
Baritone not mining/moving

### ISSUE THREAD

**Issue by mossie22** [cabaletta/baritone#3851]
## Some information
Operating system: WIn 11
Java version: idk
Minecraft version: 1.19.2 fabric modded
Baritone version:1.19.2
Other mods (if used): Better minecraft fabric 1.19.2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/10832572/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
 Try to #mine granite 
## Modified settings
To get the modified settings run `#modified` in game
None
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3773
