### ISSUE TITLE
Freecam mod that is compatible with Baritone fabric? (1.19.3)

### ISSUE THREAD

**Issue by FlingYourself** [cabaletta/baritone#3853]
## What do you need help with?
So I was having the same problem as issue #3629 where Baritone wouldn't place blocks while in freecam. It was closed and the only answer to it was "the problem isn't baritone, the problem is your freecam blocking those action". So what is a good freecam that works with Baritone 1.19.3 fabric?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by FlingYourself** [comment]
I think I found a slight fix for the one I am using but I would still like any recommendations.

**Comment by gkp1** [comment]
Tweakeroo. by Masa Mods . Contains freecam+ten dozens of other tweaks.

**Comment by FlingYourself** [comment]
It seems I need to toggle freeCameraPlayerMovement and freeCameraPlayerInputs to on, which means I can't fly around while Baritone is digging/placing. Any fixes or it that just how it is?

**Comment by wagyourtail** [comment]
I created the base freecam mod that clients like aristois (Possibly meteor, and others) referenced for baritone compatible freecams. but I havent upgraded it to 1.19, one of those will have a compatible freecam tho

**Comment by lamar1625** [comment]
> I created the base freecam mod that clients like aristois (Possibly meteor, and others) referenced for baritone compatible freecams. but I havent upgraded it to 1.19, one of those will have a compatible freecam tho

^
