### ISSUE TITLE
Mine only exposed to air ores?

### ISSUE THREAD

**Issue by devinoff** [cabaletta/baritone#3854]
how do I mine only exposed to air ores?
I've seen this command, but it does not work: #mine minecraft:diamond_ore if is_exposed

**Comment by rycbar0** [comment]
its a setting. enable legit mine to only mine exposed ores. `#legitMine true`
https://github.com/cabaletta/baritone/blob/174bdd230742486dd858be2032255f59724a0e6e/src/api/java/baritone/api/Settings.java#L1053-L1059

**Comment by moosetwin0** [comment]
@devinoff you're looking for #AllowOnlyExposedOres
