### ISSUE TITLE
An unhandled exception occurred. The error is in your game's log

### ISSUE THREAD

**Issue by zzzsadad** [cabaletta/baritone#3857]
## Some information
Operating system: Win10
Java version:
Minecraft version:1.19.3
Baritone version:latest
Other mods (if used): fabric [api](url)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
after ive downloaded the bot i am able to use it in singleplayer but not in multiplayer it just says as the name of the post

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/10862465/latest.log)

**Comment by zzzsadad** [comment]
only happening in multiplayer

**Comment by rycbar0** [comment]
stop using baritone-meteor!

see issue #3838

**Comment by zzzsadad** [comment]
> stop using baritone-meteor!
> 
> see issue #3838

ty
