### ISSUE TITLE
Does baritone resume building schematics from pre built ones? or does it completely rebuild it somewhere else

### ISSUE THREAD

**Issue by Absurv69** [cabaletta/baritone#3858]
Does baritone resume building schematics from pre build ones? or does it completey rebuild it somewere else?
I am having problems trying to build a schematic in baritione, i use litmetica also but for some reason baritone never builds the schematic were litmetica has printed it.

My other problem is that upon a server restart my baritone stops the build, when i relog and do #build "schematic" it just rebuilds it from scratch somewere else instead of continuing on from the unfinished version.

SOS

**Comment by rycbar0** [comment]
what command do you use to build your litematica holograms?

`#build <schematic>` will build the schematic at your position. to build it at a specific position you have to use `#build <schematic> <x> <y> <z>`

if you want to build a hologram try using the `#litematica` command. if you have more than 1 open hologram you can specify it by adding a number `#litematica <i>` refrencing the respective entry in the placement list.

**Comment by Absurv69** [comment]
I am currently clearing my build once i have cleared it i will test this out, i also mentioned baritone attempting to scaffold up in the schematic however it thinks the scaffolding block isnt a part of the schematic and breaks it resulting in an infinite loop, i found a solution to this by disallowing baritone to break the scaffolding block but i was wondering if there is a permanent solution.

**Comment by rycbar0** [comment]
you can set `buildIgnoreExisting` to true which will prevent baritone from breaking non air blocks if the schematic wants air at that position. you willl have to clean up your build afterwards as baritone will not break your scaffolding blocks. but your version with disalowing to break your scaffold block should also work.

**Comment by Absurv69** [comment]
With the #build "coordinates" command you specified how do i find were the borders of the build will be? like for example would it be build going to the right/left ect if you know what i mean.

**Comment by rycbar0** [comment]
its the minimum corner of the build. you could change the corner with the schematicOrientationX schematicOrientationY schematicOrientationZ settings but nobody does that.

**Comment by Absurv69** [comment]
https://ibb.co/6bFnRB8 this is the error i receive upon the command litemetica

**Comment by rycbar0** [comment]
can you poste your game log?

**Comment by Absurv69** [comment]
Were do i find it?

**Comment by rycbar0** [comment]
usualy its located here C:\Users\<Your Username>\AppData\Roaming\.minecraft\logs

**Comment by Absurv69** [comment]
Which log file would it be, i filtered by date modified but the time isnt accurate, is it the time since mc was launched?

**Comment by rycbar0** [comment]
latest.log

**Comment by Absurv69** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/10869867/latest.log)

**Comment by rycbar0** [comment]
that took me way to long, anyway. you tryed to build a .schematic file with the litematica command. while litematica can handle that filetype fine, it causes a problem with baritone as baritone assumes all schematics built with the litematica command are of the .litematic format. you can just use the build command. or you can resave the schematic with litematica as a .litematic file and it should work. why it is that way, because im didnt knew what i was doing when i implemented it. also, try use the [baritone-unoptimized-1.2.17.jar](https://github.com/cabaletta/baritone/releases/download/v1.2.17/baritone-unoptimized-1.2.17.jar). it is the exact same as the forge-standalone but it will generate more readable logs.

**Comment by Absurv69** [comment]
I really appreciate the help thank you. I will be sure to replace my baritone to make it easier in a case of any future errors.
