### ISSUE TITLE
Typing "mine's" in chat with prefix off crashes game.

### ISSUE THREAD

**Issue by uwuplant** [cabaletta/baritone#386]
[crash details](https://uwu.despaci.host/i/7f86wb9w.png)

Steps to reproduce:
1: Disable prefix
2: Type "mine's" in chat.

**Comment by SuperOP535** [comment]
No uwus

**Comment by uwuplant** [comment]
too bad







uwu

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/3d3a5f420e1b6541a1028f22b419756b66db4d51

Not closing yet since this will need to be included while merging latest changes from 1.12 into 1.13

**Comment by 0-x-2-2** [comment]
🤢

**Comment by leijurv** [comment]
o ya i did this tho
