### ISSUE TITLE
请添加一个自动钓鱼的功能 在1.12.2中 我需要他 为此我可以为你报酬

### ISSUE THREAD

**Issue by 435789** [cabaletta/baritone#3861]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
fishing is out of scope for baritone. there are also other mods that include autofish, such as https://www.curseforge.com/minecraft/mc-mods/autofish
