### ISSUE TITLE
Trying to have Baritone build in a specific coordinate

### ISSUE THREAD

**Issue by AODHoxton** [cabaletta/baritone#3862]
I'm attempting to have Baritone build schematic files at a specific coordinate without the bot moving like 200 blocks away from where I want it to build. When trying to put in a coordinate in the command string it just gives me "Error at argument #X: expected RelativeBlockPos

Putting RelativeBlockPos in the argument's place yields nothing, and the error just goes onto another argument. Am I just doing something wrong or is Baritone incapable of this?

**Comment by rycbar0** [comment]
can you post the full command you used?

baritone excpects it in the format `#build <schemfile.fileextention> <x-coordinate> <y-coordinat> <z-coordiante>`
if no coordinates are provided it will use the player position.

the coordinates will used to identify the minimum corner of the schematic.
