### ISSUE TITLE
Why does Baritone so picky with the selection command?

### ISSUE THREAD

**Issue by Comthefox2486** [cabaletta/baritone#3863]
## What do you need help with?
I am using the Baritone addon with Aristois and if I set allowBreak to true and try to use selection commands it works fine, but I really don't want it to break blocks. It refuses to do it when allowBreak is off.
Check the video for an example

Link because GitHub file limit is too small /:
https://youtu.be/RrLILm7dJ-c

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone can't place blocks from below (except maybe when you are already standing in the right position, not sure about that) and without `allowBreak` enabled there's no way to get on top of your selection (because there's stone in the way).
