### ISSUE TITLE
Baritone taking silly paths and dropping down randomly and looping around 

### ISSUE THREAD

**Issue by Absurv69** [cabaletta/baritone#3864]
https://ibb.co/X56tjp6

Taking stupid paths to complete simple schematics, is there a way around this? it keeps dropping into the pit of the build (there is nothing to build there) and gets stuck ending up looping around and attempting to build up but then stopping and finding a new path.

I have acceptablethrowawayitems set to dirt, and plenty provided in the hotbar.

**Comment by ZacSharp** [comment]
I guess it also breaks the dirt it just placed?
In that case adding dirt to `buildIgnoreBlocks` might help (but will leave a dirty mess behind).

The reason for dropping down might be that your schematic is so big / timeouts are so low that Baritone can't find a path to the other side of the schematic in one go and going straight across the build is more promising than taking a long detour along the edge. You can probably prevent it by adjusting `maxFallHeightNoWater` and `maxFallHeightBucket`/`allowWaterBucketFall`.
