### ISSUE TITLE
Baritone doesnt work at all

### ISSUE THREAD

**Issue by ZhentorTheMaster** [cabaletta/baritone#3865]
I make sure i put everything right but it still doesnt work. I type commands and it doesnt give back output on chat and instead outputs to a toaster (achivement box things) and because they are so small the output cannot be read. I dont know what is written but only half that is visible says "[B] (the command i put)" another toaster pops up after half a sec "[B] Error at arguement #3 Ex" and the rest is out of screen. Im guessing "Ex" is Expected but im not sure of it. But it works fine on forge but theres no good forge client so i cant use it.
And also on toasters background theres weird gui symbols or ascii characters and when i open inventory it changes to item textures and weird stuff.

UPDATE: I figured it out to fix the toaster thing by editing it but it still displays the half of the messages still on toasters and other half on chat but it doesnt work it says something about slowwalk and stuff and blockoptianalmeta (the block i selected)
and stuff like that but still doesnt work

Im using TLauncher version tested on fabric 1.19.2, 1.19.3, 1.16.5

But still works fine in forge for some reason...

**Comment by rycbar0** [comment]
no clue what you trying to say.
if you run into a bug pls follow the bug issue template. it lists all the informations we need to provide help.

**Comment by ZacSharp** [comment]
Don't use TLauncher.
