### ISSUE TITLE
When running command "#mine diamond_ore" it wont work it gives me an error

### ISSUE THREAD

**Issue by TH3HUNT3Y** [cabaletta/baritone#3867]
## Some information
Operating system: Windows 10
Java version: not known atm
Minecraft version: 1.19.3
Baritone version: newest
Other mods (if used): boze

## How to reproduce
by running #mine 'anything' only on servers

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you want to give us a chance at fixing the error you'll have to provide some more information.

Best I can do based on the information you provided is telling you that your Baritone version might not actually be the latest one and that updating will fix this. (There's a NullPointerException in previous versions for mc 1.19.3 and people usually reported it as a problem with `#mine`)

**Comment by wagyourtail** [comment]
> only on servers

> Baritone version: newest

![doubt](https://i.kym-cdn.com/entries/icons/original/000/023/021/e02e5ffb5f980cd8262cf7f0ae00a4a9_press-x-to-doubt-memes-memesuper-la-noire-doubt-meme_419-238.png)
