### ISSUE TITLE
add the 'replace' parameter like the real '/fill' command to the 'sel' function of baritone

### ISSUE THREAD

**Issue by NONAME-2121237** [cabaletta/baritone#3868]
When I use the 'sel' function to clear the block, I find that the baritone will get stuck in the wayfinding calculation at a distance, and when there are blocks in the selection area that cannot be destroyed by the survival mode such as bedrock and folding door, the baritone will always try to destroy it with empty hands
I hope to add the 'replace' parameter like the real '/fill' command to the 'sel' function of baritone, and also add a skip list during block cleaning (after all, some mods will also add unbreakable blocks).
I am using minecraft version 1.19.2

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
as you can see in the comand description (Line 309) there already is a option to replace blocks.
https://github.com/cabaletta/baritone/blob/790a4f6769f462dd1fb92d64b2f5855f10c86dce/src/main/java/baritone/command/defaults/SelCommand.java#L289-L317

about the skip list,  you can add any block to the buildIgnorBlock list and baritone will not break it when clearing out a selection.
https://github.com/cabaletta/baritone/blob/790a4f6769f462dd1fb92d64b2f5855f10c86dce/src/api/java/baritone/api/Settings.java#L239-L244

there are more settings about the building behavior of baritone you may want to check out.

**Comment by NONAME-2121237** [comment]
I'm sorry I didn't read the baritone instructions carefully. I'm sorry to disturb you.
Thank you for your help
