### ISSUE TITLE
Baritone only bridging with stone

### ISSUE THREAD

**Issue by ChromaToggled** [cabaletta/baritone#3872]
## Some information
Operating system: Windows 10
Java version: openjdk 11.0.12 2021-07-20
Minecraft version: 1.12.2
Baritone version: 1.2.10-1.2.13  
Other mods (if used): ClassicCombat-1.0.1.jar

## How to reproduce
make two pillars
stand on one of them
take stone, and go to the other pillar with baritone making him bridge
take planks or any other block and try to bridge to the other pillar

## Modified settings
blockPlacementPenalty 0
allowDiagonalAscend true
allowParkour true
allowParkourPlace true
buildInLayers true
mineScanDroppedItems false
legitMine true

## Final checklist
- [ ] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
do you know what the setting `acceptableThrowawayItems` does?

**Comment by ChromaToggled** [comment]
yes, but i dont quite know how to use it

**Comment by rycbar0** [comment]
`#acceptableThrowawayItems <block1>,<block2>,<block3>,etc`
example for a block would be `minecraft:dirt`
if you have more blocks you want to add to that list than the chat allows you can modify your settings file directly.
change or add if not already in there the line that starts with `acceptableThrowawayItems ` after the space you add the blocks just like in the command, the blocks divided from each other by commas. so the hole line would look something like this:
`acceptableThrowawayItems minecraft:dirt,minecraft:cobblestone,minecraft:netherrack,minecraft:stone,minecraft:oak_planks`
