### ISSUE TITLE
Baritone cant find the schematic file for auto build. I do have the schematic file in my .Minecraft folder with a build in it but every time I type #build tree it wont work

### ISSUE THREAD

**Issue by ItsMagicBoi** [cabaletta/baritone#3873]
I do have the schematic file in my .minecraft folder with a build in it but every time I type #build tree it won't work it tells me to include the extension (e.g. blah.schematic) but if I include it it still doesn't work

**Comment by rycbar0** [comment]
baritone excpects schematics to be in the schematics folder inside your .minecraft folder
C:/Users/.../roaming/.minecraft/schematics/tree.schem
