### ISSUE TITLE
Stuck on carpet, baritone breaks and replaces it constantly

### ISSUE THREAD

**Issue by Absurv69** [cabaletta/baritone#3875]
not going to bother linking anything as its been covered multiple times with no clear answer, im 1.12.2 forge anyone know settings to fix it?

**Comment by Absurv69** [comment]
> related issues: #3142, #1754

There is no download link or solution there, only expired artifacts. Already read it

**Comment by Absurv69** [comment]
> i wasnt providing a solution i was linking related issues as this issue has 0 new information attached. you could have just add a new comment on the existing issues with the same result.

There is a supposed "fix" however you cant download it as the "artifact has expired"

**Comment by Absurv69** [comment]
Running litematica
Modified settings; acceptablethrowawayitems, allow inventory, blockreachdistance, blockstoavoid, blockstoavoidbreaking, blockstodisallowbreaking, buildignoreblocks, buildskipblocks, mapartmode

**Comment by rycbar0** [comment]
fix was for 1.12. i know its not exactly what you search for but have you tryed enabeling litematicas easy place feature and just hold the build button? litematica should then autoswitch items and only build when looking at a ghost block if im not mistaken.

**Comment by wagyourtail** [comment]
Duplicate #3142 

> not going to bother linking anything as its been covered multiple times

Please dont post duplicates

**Comment by Absurv69** [comment]
> Duplicate #3142
> 
> > not going to bother linking anything as its been covered multiple times
> 
> Please dont post duplicates

Calm down champion, its a duplicate from over a year ago so i think this is suitable especially since it has not been resolved.

**Comment by ZacSharp** [comment]
Seriously, this is just a worse version of commenting "Bump".


If you can't build Baritone yourself you can ask for artifacts with a comment on the existing issue.

**Comment by Absurv69** [comment]
You are stupid, a fat dev from america who watches coding tutorials. Issues been out for years and you cant comprehend fixing it. I fixed it in 10 minutes skid

**Comment by Absurv69** [comment]
Please make an artifact then, and acknowledge the issue being submitted that's affected many people.
