### ISSUE TITLE
Error While adding waypoint

### ISSUE THREAD

**Issue by RdaGg18** [cabaletta/baritone#3877]
## Some information
Operating system: Windows 10
Java version: java 17
Minecraft version: 1.19.3
Baritone version: 1.9.1
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I added a waypoint for my iron farm, then there was an unhandled exception

## Modified settings
To get the modified settings run `#modified` in game
there is nothing

## Final checklist
- [x] I know how to properly use check 
[latest.log](https://github.com/cabaletta/baritone/files/10954535/latest.log)
boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
please fill out the rest of the bug report

**Comment by wagyourtail** [comment]
`#wp s user IronFarm`

`#wp c` is for clearing a waypoint group
