### ISSUE TITLE
Baritone Getting Stuck Jumping Breaking & Placing Carpets Underneath It

### ISSUE THREAD

**Issue by nezaloth** [cabaletta/baritone#3879]
## Some information
Operating system: Arch Linux
Minecraft version: 1.19.3
Baritone version: Fabric Standalone 1.9.1
Other mods (if used): Litematica

## How to reproduce
Load any schematic with a staircase of blocks with carpets placed on top them

## Modified settings
allowInventory true
buildInLayers true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/cabaletta/baritone/files/10964601/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/10964609/debug.log)

**Comment by rycbar0** [comment]
dublicate of #3142
