### ISSUE TITLE
Installing standalone v1.3.1?

### ISSUE THREAD

**Issue by jeremyjacob** [cabaletta/baritone#388]
Is it possible and if so how would I go about installing the latest version of baritone for 1.13.2 in MultiMC. I think I need some sort of tweak json but I don't know how I would go about doing that.

**Comment by 0-x-2-2** [comment]
multimc is really bad lol

**Comment by jeremyjacob** [comment]
Okay, any way to install it in plain vanilla then?

**Comment by jeremyjacob** [comment]
There doesn't seem to be any guides or documentation on installing this outside of the 1.12 forge mod. Any help?

**Comment by SuperOP535** [comment]
What I did was to get the Impact client JSON and remove impact from it, the result is baritone + vanilla

**Comment by jeremyjacob** [comment]
Thank you so much, this worked

1.13.2 For anyone interested:
`{
  "id": "1.13.2-Baritone",
  "inheritsFrom": "1.13.2",
  "jar": "1.13.2",
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
      "--tweakClass",
      "baritone.launch.BaritoneTweaker"
    ]
  }, 
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },

    {
      "name": "cabaletta:baritone-api:1.3",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },

    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "downloads": {
          "artifact": {
              "path": "org/spongepowered/mixin/0.7.10-SNAPSHOT/0.7.10-SNAPSHOT.jar",
              "size": 1017668,
              "sha1": "62282bd6b2a4a3b3a068e4900309858d91187df3",
              "url": "https://repo.spongepowered.org/maven/org/spongepowered/mixin/0.7.10-SNAPSHOT/mixin-0.7.10-20180611.151716-1.jar"
          }
        }
    },
    {
      "name": "net.jodah:typetools:0.5.0",
      "url": "https://repo.maven.apache.org/maven2/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.2",
      "url": "http://repo1.maven.org/maven2/"
    }
  ],
  "downloads": {},
  "minimumLauncherVersion": 0,
  "releaseTime": "2019-04-02T12:14:19+01:00",
  "time": "2019-04-08T20:02:19+01:00",
  "type": "release"
}`

**Comment by leijurv** [comment]
:+1:

**Comment by jeremyjacob** [comment]
One last note although this is pretty self-explanatory I just felt it was needed given the original nature of the question. To install the above with MultiMC add an empty version with name `Bartone` and id `baritone`. Click edit and paste in
```{
  "+tweakers": [
    "baritone.launch.BaritoneTweaker"
  ],
  "formatVersion": 1,
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },

    {
      "name": "cabaletta:baritone-api:1.3",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },

    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "downloads": {
          "artifact": {
              "path": "org/spongepowered/mixin/0.7.10-SNAPSHOT/0.7.10-SNAPSHOT.jar",
              "size": 1017668,
              "sha1": "62282bd6b2a4a3b3a068e4900309858d91187df3",
              "url": "https://repo.spongepowered.org/maven/org/spongepowered/mixin/0.7.10-SNAPSHOT/mixin-0.7.10-20180611.151716-1.jar"
          }
        }
    },
    {
      "name": "net.jodah:typetools:0.5.0",
      "url": "https://repo.maven.apache.org/maven2/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.2",
      "url": "http://repo1.maven.org/maven2/"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "name": "Baritone",
  "order": 10,
  "releaseTime": "2019-04-08T20:02:19+01:00",
  "requires": [
    {
      "equals": "1.13.2",
      "uid": "net.minecraft"
    }
  ],
  "type": "release",
  "uid": "com.mumfrey.liteloader",
  "version": "1.13.2_05"
}```

**Comment by 0-x-2-2** [comment]
you won't get hot-fixes if you use multimc because 🦍 maven implementation
