### ISSUE TITLE
> Assuming everything succeeds, I'll open up a pr with those changes

### ISSUE THREAD

**Issue by Shaquum** [cabaletta/baritone#3880]
> Assuming everything succeeds, I'll open up a pr with those changes

Not sure what kind of changes you mean here. `BetterBlockPos` already has `getX`, `getY` and `getZ` inherited from `BlockPos` (which is also why they should be immune to this bug: they are allowed to read the private field).

_Originally posted by @ZacSharp in https://github.com/cabaletta/baritone/issues/3859#issuecomment-1454255405_

**Comment by ZacSharp** [comment]
What's the purpose of this issue?

**Comment by ZacSharp** [comment]
Just annoying people on purpose, got it (https://github.com/cabaletta/baritone/issues/3859#issuecomment-1468025753)
