### ISSUE TITLE
Baritone does not pathfinders on a boat

### ISSUE THREAD

**Issue by AMXeno** [cabaletta/baritone#3883]
When using a boat it will just move forward, the boat will glide, and then it will try to find the best route again and this continues until baritone is stopped. I have tried this on survival world with just baritone mod and it still has the issue. This issue occurs on the latest version of baritone.

**Comment by wagyourtail** [comment]
yep. baritone doesn't support boats. or riding any mobs for that matter

**Comment by ZacSharp** [comment]
There's some code for pigs though (I'm not saying it works, just that it exists).
