### ISSUE TITLE
how do you properly install Baritone for forge 1.12.2?

### ISSUE THREAD

**Issue by domsfilms1** [cabaletta/baritone#3884]
The files either crash my game before the launch can even start or it launches but Minecraft pretends Baritone doesn't exist.

These files will crash the game before it can launch. 
[crash.zip](https://github.com/cabaletta/baritone/files/11012553/crash.zip)

These files will let Minecraft load, but there is no sign of Baritone installed to the game.
[unrecognizeable.zip](https://github.com/cabaletta/baritone/files/11012557/unrecognizeable.zip)

**Comment by wagyourtail** [comment]
you are putting a single forge labeled file in your mods folder right? and not both of them?
also yeah, the ones you labeled as crash aren't for forge
