### ISSUE TITLE
Block overlay

### ISSUE THREAD

**Issue by Tatastic** [cabaletta/baritone#3885]
How do I get the block overlays, when I have set baritone on mine, the bit where it shows its path and the surrounding blocks I want it to mine.

**Comment by wagyourtail** [comment]
Remove iris
 If that doesnt work. Give mods list and #modified

**Comment by Tatastic** [comment]
> 

I dont believe Im using iris, I am currently using optifine and baritone.

**Comment by ZacSharp** [comment]
Does removing optifine help?
If not, do you perhaps have `renderPath` and `renderGoal` set to `false`?
