### ISSUE TITLE
Lag spikes when target block mined

### ISSUE THREAD

**Issue by PastaPad** [cabaletta/baritone#3889]
Well , I recently mined some ores and other blocks and i noticed that the minecraft window gets lagged so hard that  it gets "(no response)"-ed. other mods used : 
Autofish , ferritecore, iris, lazydfu, litematica, lithium, malilib minihud resses sodium ops, sodium
Details : 
I've been playing of my server with the same modpack and everything was lag free but when i today made a hardcore world the lag started kicking in.
Does someone have fix/explanaiton

**Comment by ZacSharp** [comment]
Do the lag spikes happen when a target block (I assume you are using `#mine`) is broken, when any block is broken, while a target/other block is being broken or generally while mining?
Did this happen only once or is it reproducible?
In case it is reproducible, does removing mods help and if so, which one is the culprit?

So far I have no idea what's causing this, unless it's `WorldScanner`.

**Comment by rycbar0** [comment]
what are the `#modified` settings
do you have this setting enabled? (https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/api/java/baritone/api/Settings.java#L412-L420)

**Comment by PastaPad** [comment]
@rycbar0 yes i have it enabled because im in hardcore, and it would be a shame if i died

**Comment by ZacSharp** [comment]
Is there many mobs in render distance?
