### ISSUE TITLE
How to prevent Baritone from deviating from a selected area while clearing it?

### ISSUE THREAD

**Issue by ajthecatdog** [cabaletta/baritone#3890]
## What do you need help with?
When trying both #sel ca and #tunnel to clear an area for a tunnel, Baritone will try to go over and around the tunnel but always returns to the tunnel after a few seconds. Is there any way to prevent this from happening, possibly by limiting how far the player can deviate from a certain x/z coordinate?

Here is a picture of this happening with #sel ca:
![2023-03-28_10 51 05](https://user-images.githubusercontent.com/68794748/228281894-e85fc299-a505-425e-9924-be2d3f7410fe.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This seems to be the same problem as described in #1452
As a workaround you can use smaller tunnel segments in conjunction with `buildRepeat`, or (if my guess on why this happens is correct) build the tunnel from the other end.
