### ISSUE TITLE
chat commands dont work but it still sends messages 

### ISSUE THREAD

**Issue by limeypichu** [cabaletta/baritone#3894]
## Some information
Operating system:windows 11
Java version:1.8.0_333
Minecraft version:1.19.4
Baritone version:1.9.2
Other mods (if used): in log

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/11117734/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
use the mod pack base with a fresh install of baritone

## Modified settings
To get the modified settings run `#modified` in game
i have not modified the settings at all
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
i assume you didnt attach your modified settings because `#modified` didnt work aswell?
try resetting your settings by deleting the settings file. it should be located in your `/.minecraft/baritone/` folder as `settings.txt`
if that doesnt fix the issue can you provide a screenshot of your ingame chat after trying to use a command? because the log didnt contained anything.

**Comment by limeypichu** [comment]
yea uhhh about that the settings.txt file just doesnt exist???? even after restarting it just never made it

**Comment by limeypichu** [comment]
btw the log file was too big if you want i can copy past it but its over 1000+ lines

**Comment by limeypichu** [comment]
[log copy.txt](https://github.com/cabaletta/baritone/files/11124256/log.copy.txt)

nvm i copyed it and it works now

**Comment by rycbar0** [comment]
that is a emty file pls send a screen shot of your in game chat after you tried to execute a command

**Comment by limeypichu** [comment]
ok ill have to do it later though

**Comment by limeypichu** [comment]
ill be back in 4 n a half-ish? hours

**Comment by limeypichu** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/11124749/latest.log)
ok clicking on this **SHOULD** download the full log but at this point i dont even know if this doesnt work ima have to wait till i get home

**Comment by limeypichu** [comment]
[rei.log](https://github.com/cabaletta/baritone/files/11124850/rei.log)
addin the rei becuase more info the better

**Comment by ZacSharp** [comment]
I was unable to make sense of your chat messages (decoding as windows-1252 yields ")`~3²%¦2,1;!¦)£×"4~;¡®}<#_¼<·+»;" and "|¥>µ°¤!¦-=®<#²`¡@µ2`", other encodings yield similar results) so I can't even tell whether you actually tried to use Baritone or just wrote some random messages.
Can you please remove all mods not required to reproduce this bug  (I wouldn't be surprised if memoryleakfix turned out to be the culprit) and also tell us the chat messages you sent?  

Btw that log contains 66428 graphics errors (about 7.5MB per minute).

**Comment by limeypichu** [comment]
oooooh uh i gota fix that anyways i was doin stuff like help mine iron_ore and stuff but it never red it also when i died it said it saved waypoint so it works and can type in chat but it cant take commands (prob because it never made the settings.txt folder)

**Comment by limeypichu** [comment]
i tryed restarting my whole computer but it still didnt make a settings.txt file

**Comment by rycbar0** [comment]
setting file only gets created if you change a setting so if you havnt changed anything (run ning default settings) that file dosnt exist
i told you to delet it to return to default settings

**Comment by limeypichu** [comment]
oooh thats what ya mean
anyways uh yea nothing happens when useing commands it just doesnt respond not text no confermation only way it says something is if i die liike said earlyer

**Comment by rycbar0** [comment]
what command are you typing into the chat? you can send a screenshot or you type it out.
also as zac said try removing all other mods to make sure baritone is/has a problem

**Comment by limeypichu** [comment]
ooooh sory cant try rn bc i just cant login to minecraft? for some reason
gime like 30 mins ill get back to yall

**Comment by limeypichu** [comment]
btw the comand was mine iron_ore nothin help comand did nothin too

**Comment by limeypichu** [comment]
i used both comand prefixes btw if that helps

**Comment by rycbar0** [comment]
just that?
`mine iron_or`

you know baritone expects a `#` at the beginning of a command example `#mine iron_ore`
you can change the settings so you dont need that leading character but on default settigns baritone requires it. else your messages go out as just that, messages.

**Comment by limeypichu** [comment]
ye it was  `#mine iron_ore` and `#help`

**Comment by limeypichu** [comment]
i tried the `.b` prefix too

**Comment by ZacSharp** [comment]
@rycbar0 `chatControl` and `prefixControl` both default to `true` (https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/api/java/baritone/api/Settings.java#L647 and https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/api/java/baritone/api/Settings.java#L772) so they don't need a prefix. It's just that clients like to turn it off by default.

@limeypichu  `.b` is a prefix used by some hacked clients, not Baritone itself so it won't work here.

**Comment by limeypichu** [comment]
ooooh ok cool yeaaaa i also tried replaceing the baritone api and same thing happend so ima try running it on its own when i get home

**Comment by ZacSharp** [comment]
So for my best guess explanation is
1. memoryleakfix force applies "all" mixins and misses our mixins
2. memoryleakfix prevents any further mixin transformer activity
3. chat classes are only loaded once chat is opened the first time so our chat hook remains unapplied

**Comment by limeypichu** [comment]
thx when i get home ima turn off mem leak fix i dont realy play online so  i dont realy know if it is that importent for me

**Comment by limeypichu** [comment]
at home ill try now

**Comment by limeypichu** [comment]
found out why the log chats were encripted it was a mod lol
![2023-03-31_18 13 08](https://user-images.githubusercontent.com/84183766/229248713-d7bd6b7e-5fc8-47da-bdbe-c6d7b1250fb0.png)
here as you can see it doesnt do anything when given comands removein mem leak fix didnt work

**Comment by limeypichu** [comment]
im testing a profile with just baritone now

**Comment by limeypichu** [comment]
well then its a mod causein it

**Comment by limeypichu** [comment]
OH WHAT IF THE MOD ENCRIPTING THE MESSAGES IS DOING IT BEFORE BARITONE READS IT

**Comment by limeypichu** [comment]
NO CHAT REPORTS BREAKS BARITONE

**Comment by wagyourtail** [comment]
I don't think we will be moving our inject so report it to them, I recommend they move it so it does it when the packet class is initialized

**Comment by wagyourtail** [comment]
there is a workaround, 
![image](https://user-images.githubusercontent.com/6234704/229316500-f9e4f02f-325b-4ede-8849-91ac3cd20240.png)
