### ISSUE TITLE
Crash during startup v1.19.1 org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError

### ISSUE THREAD

**Issue by MeLikeFish** [cabaletta/baritone#3895]
## Some information
Operating system: Win 11 Home
Java version: Version 8 Update 361 (build 1.8.0_361-b09)
Minecraft version: 1.19.2
Forge version: 43.2.6
Baritone version: v1.19.1
Other mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
```
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1
```
[latest.log](https://github.com/cabaletta/baritone/files/11124094/latest.log)
[crash-2023-03-31_18.30.39-client.txt](https://github.com/cabaletta/baritone/files/11124146/crash-2023-03-31_18.30.39-client.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. Setup a profile in Curseforge
2. Set Minecraft version to 1.19.2
3. Set Forge version to 43.2.6
4. Download Baritone v1.19.1 and put it in the mods folder
5. Attempt startup

## Modified settings
Can not get into game, first time using Baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
https://github.com/cabaletta/baritone/releases/tag/v1.9.1
as you can se in the description its for 1.19.3 only

**Comment by MeLikeFish** [comment]
> https://github.com/cabaletta/baritone/releases/tag/v1.9.1
> 
> as you can se in the description its for 1.19.3 only

Any way to get Baritone on 1.19.2?

**Comment by rycbar0** [comment]
sadly no we dont have a 1.19.2 releas. what you can try is to get a old dev build from the action tab but idk if the files still exist or if they are any good.
https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.19.1

**Comment by MeLikeFish** [comment]
Sad. I found one build for 1.19.2 I think, but the Files are expired. If anyone has files for 1.19.2, please let me know

**Comment by MeLikeFish** [comment]
> Not to necro this post but you did ask to be let known if someone had made a 1.19.2 build... https://github.com/cabaletta/baritone/actions/runs/4591800236
> 
> Its worked for me for forge 1.19.2-43.2.6. Fabric is untested.

Thank you so much! I really appreciate it. Did you use the API or non-API version?

**Comment by rycbar0** [comment]
because it was requested we now also have a 1.19.2 release
https://github.com/cabaletta/baritone/releases/tag/v1.9.4

**Comment by ovingiv** [comment]
> Thank you so much! I really appreciate it. Did you use the API or non-API version?

I used the API version.
