### ISSUE TITLE
Baritone not building my schematic blueprint

### ISSUE THREAD

**Issue by govvsensei** [cabaletta/baritone#3896]
Whenever i place my schematic blueprint / preview and i try to build the schematic with #build <filename> it starts to place the blocks but just not where i placed the schematic blueprint
![2023-03-31_22 42 53](https://user-images.githubusercontent.com/129554212/229225876-9a6fe900-2e0c-472d-9736-d4119df366d1.png)

**Comment by rycbar0** [comment]
#build has nothing to do with any schematic mod. it will build the specified schematic file at the player position or if provided at the specified coordinates
if you want to build the hologram of a schematic mod you can use #schematica for 1.12 (requires schematica to be installed) or #litematica for 1.12,1.16-1.19 (requires litematica to be installed)

**Comment by rycbar0** [comment]
btw if you are in creative mode i strongly suggest you use the pasting tools that come with the schematic mods. its faster, easier and more reliable. baritone will struggle with anything that isnt a full orientationless block example stairs.

**Comment by govvsensei** [comment]
@rycbar0 thank you man
