### ISSUE TITLE
retrace actions

### ISSUE THREAD

**Issue by smokii0** [cabaletta/baritone#3898]
ok so i have a modded farm and i cant figure out how to make baritone farm the things in my farm. so i was wondering if there is some way for me to "record"my actions so the bot can repeat the whole loop over and over again?

**Comment by rycbar0** [comment]
no baritone cant record and replay actions.
unfortunatly the plants harvested by baritone are hard coded so you cant add your modded plants to a list. if you know a little java you could edit the file to your likeing.
add your modded seeds in this list: https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/main/java/baritone/process/FarmProcess.java#L67-L74
add items you want to pick up to this list: https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/main/java/baritone/process/FarmProcess.java#L76-L91
and add the blocks that should be harvested here (probably moste difficult part but doable):https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/main/java/baritone/process/FarmProcess.java#L114-L156
