### ISSUE TITLE
Adding more selection to blocks? 

### ISSUE THREAD

**Issue by A55A553N** [cabaletta/baritone#3899]
Now maybe I’m not using the command correct. But I can’t get get the “.b mine” to work with anything but naturally spawn in blocks. This seems adequate at first glance, but I play on a prison anarchy server I use baritone to automatically mine blocks, but it refuses to accept the commands for things like coal blocks and raw iron blocks. Just a thought.

**Comment by ZacSharp** [comment]
By "refuses to accept" you mean "responds with `Error at argument #1: Expected ForBlockOptionalMeta`"?
Did you use `#mine coal_ore` (or `.b mine coal_ore` as you seem to be using Impact) or something else?

**Comment by A55A553N** [comment]
> By "refuses to accept" you mean "responds with `Error at argument #1: Expected ForBlockOptionalMeta`"?
> Did you use `#mine coal_ore` (or `.b mine coal_ore` as you seem to be using Impact) or something else?

I am running it with meteor yes. And it does give me that error. When I run the command .b mine minecraft:bock_of_coal or b mine minecraft:bock_of_redstone

**Comment by A55A553N** [comment]
> By "refuses to accept" you mean "responds with `Error at argument #1: Expected ForBlockOptionalMeta`"?
> Did you use `#mine coal_ore` (or `.b mine coal_ore` as you seem to be using Impact) or something else?

I realized as I was typing that it should be Redstone block not block of Redstone. my bad I was running the command wrong
