### ISSUE TITLE
baritone just stops randomly and i have to place blocks manually?

### ISSUE THREAD

**Issue by XZRC** [cabaletta/baritone#3902]
## Some information
Operating system:
Java version: 8
Minecraft version: 1.12.2
Baritone version: the one in impact
Other mods (if used): impact client

Heres a video of the bug: https://streamable.com/pku7ic

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[debug.log](https://github.com/cabaletta/baritone/files/11162098/debug.log)

## How to reproduce

.b build laputa.schematic 129842  126 -1099601

## Modified settings
To get the modified settings run `#modified` in game

![image](https://user-images.githubusercontent.com/69510350/230176562-9d85170a-a800-4c92-bf0e-1cbec4aa2bdb.png)
![image](https://user-images.githubusercontent.com/69510350/230176585-4c5fe2c6-bc48-4689-aec8-78bdf2b05f21.png)
![image](https://user-images.githubusercontent.com/69510350/230176602-0d8cf922-0137-4612-9ddd-6c776d572b28.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by XZRC** [comment]
it just keeps doing this? (when it placed the block i manually placed it)
https://streamable.com/5gf1yw

**Comment by ZacSharp** [comment]
Sorry to say, but that looks normal.
`BuilderProcess` is really bad at handling anything beyond block placement so if you have any kind of directionality (you don't) or a specific build order (you do) or blocks placed in air (you do) you'll more likely than not get into trouble.

I'd suggest forcing Baritone to build bottom up (enable `buildInLayers` and make sure `layerOrder` is disabled (default)) and maybe also adding your throwaway block to `buildIgnoreBlocks` so it can freely place scaffolding (you'll have to remove that after building is done).

**Comment by XZRC** [comment]
What do you mean with throwaway block?

**Comment by XZRC** [comment]
and it says its unable to do it when i try these settings
z

**Comment by ZacSharp** [comment]
Whatever block you are using for scaffolding (by default Baritone can use https://github.com/cabaletta/baritone/blob/ff1732011ed8cc9642a3d92bfe62e31d10a51708/src/api/java/baritone/api/Settings.java#L200 as throwaway blocks), though you don't seem to have any on your hotbar.

Anything more specific than "unable to do it"?

**Comment by XZRC** [comment]
can i use the main building block as scaffolding?

**Comment by XZRC** [comment]
do you know what causes the problem where is just randomly doesent build? it works completely fine and then just stops

**Comment by ZacSharp** [comment]
> can i use the main building block as scaffolding?

You can add them to `acceptiableThrowawayItems` but I wouldn't recommend it.

> do you know what causes the problem where is just randomly doesent build? it works completely fine and then just stops

No, I don't. Probably it walks next to the block to place it but can't find an angle to look at for placing so it just stands still.

**Comment by XZRC** [comment]
i got it to work pretty well with acceptiableThrowawayItems and buildIgnoreBlocks thanks for the help man :]
