### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by XiaF0x** [cabaletta/baritone#3906]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Hello, when I go to add blocks to the blockstoavoid setting it properly works, however it does not let me add more than one block, I assume this is me not knowing the proper way to add more than one argument to the command. Thank you!

![image](https://user-images.githubusercontent.com/88056797/231022126-b6f35e62-ab08-4759-beaf-4d39724a21f8.png)
![image](https://user-images.githubusercontent.com/88056797/231022160-a3d6cc72-7621-4c97-820c-28024453f615.png)
![image](https://user-images.githubusercontent.com/88056797/231022347-3e1b9807-3c10-4946-a26f-61c1fbde4545.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
comma seperated instead of space

**Comment by XiaF0x** [comment]
Thank you for the response! I tried that but it said this 
![image](https://user-images.githubusercontent.com/88056797/231030284-0847f08d-1737-4035-bee5-6f9f4a277c93.png)

**Comment by wagyourtail** [comment]
there's still a space in that
