### ISSUE TITLE
anti cheat detects only when mining for ores

### ISSUE THREAD

**Issue by safder2000** [cabaletta/baritone#3911]
A server that i play just added some new plugins after a bot attack, since then while using baritone to mine , just after it start mining the exact ore , I'm getting kicked out.. it can find its way to the ore.. but just when it start mining the ore , instant kick, no issue with GOTO command , anyone have any idea what plugin  they using? .( its a mixed server both java and bedrock can play(java server))
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by hecker2000** [comment]
I haven't seen issues like this, but the server may believe you are using an X-ray. try using legitimode, that _should_ fix the issue.

**Comment by wagyourtail** [comment]
then don't cheat
