### ISSUE TITLE
Is it possible to go to another waypoint, if the first one is finished

### ISSUE THREAD

**Issue by JXRNO** [cabaletta/baritone#3913]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Basically, you have multiple waypoints, then, you do some command where you select what waypoints you want to go to. If it reached waypoint 1, then go to waypoint 2.
I couldn't find how to do this, so it's probably not a feature.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
Baritone cant do that on its own atm.
