### ISSUE TITLE
Game crashes when loading world with CensoredASM

### ISSUE THREAD

**Issue by JaneStateDog** [cabaletta/baritone#3914]
## Some information
Operating system: Windows 10
Java version: 17
Minecraft version: 1.12.2
Forge version: 14.23.5.2860
Baritone version: baritone-api-forge-1.2.17
Other mods (if used): CensoredASM-5.6, mixinbooter-7.1

## Exception, error or logs
https://mclo.gs/UOg2JG3

## How to reproduce
With CensoredASM, MixinBooter, and Baritone the game crashes if I boot into a world. With just MixinBooter and Baritone the game has no issues.

## Modified settings
Nothing has been modified.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Most likely caused by https://github.com/cabaletta/baritone/issues/3859#issuecomment-1461068236

**Comment by ZacSharp** [comment]
That one messes fields up, not entire classes like the crash report suggests.
I'd like to see the full log though since the actual error might have happened earlier. Classloaders like to respond with "not found" if an earlier attempt at loading the class failed without a crash.

**Comment by JaneStateDog** [comment]
Here ya go!

[latest.log](https://github.com/cabaletta/baritone/files/11244690/latest.log)

**Comment by ZacSharp** [comment]
Are you sure the crash report and the log file are from the same crash?
The log file contains the expected `IllegalAccessError`, but also says the game crashed as a direct consequence of the `IllegalAccessError` and not later by a `NoClassDefFoundError` (which is what your crash report shows).

**Comment by JaneStateDog** [comment]
Oh, no sorry, they are not. I booted up the game and did the bug again to produce the full log. So sorry, not sure what was going through my head there, haha. Here is a new log and crash report, both from the same crash. I hope this helps.

Crash:
https://mclo.gs/OCRJ3kS
[crash-2023-04-16_18.05.07-client.txt](https://github.com/cabaletta/baritone/files/11244760/crash-2023-04-16_18.05.07-client.txt)

Log:
[latest.log](https://github.com/cabaletta/baritone/files/11244758/latest.log)

**Comment by ZacSharp** [comment]
Does disabling `optimizeFMLRemapper` setting of LoliASM help? 
If so this is #3820

**Comment by JaneStateDog** [comment]
Oop, yeah that 100% fixed it. Awesome! Thank you
