### ISSUE TITLE
Anti mob / no mobs

### ISSUE THREAD

**Issue by HacktheTime** [cabaletta/baritone#3916]
## Describe your suggestion

I personally experienced with a lot of behavior regarding mobs with baritone which I did not like.

## Settings
There should be an boolean which makes baritone clear that it never should get close or seeable to mobs. ( going around caves where mobs spawned  etc.)

## Context
Mobs were extremely dangerous since baritone goes in caves and passes through them or even mines in them. Exspecically creepers can kill you if you would go full afk.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue. 
- [x] I can fix the previous checkbox uwu

**Comment by ZacSharp** [comment]
There is `avoidance` and if it is enabled you can configure it using `mobSpawnerAvoidanceCoefficient`, `mobSpawnerAvoidanceRadius`, `mobAvoidanceCoefficient` and `mobAvoidanceRadius`. Keep in mind that this is not a magic switch and if the alternatives are too expensive Baritone will still walk through mobs.

**Comment by ZacSharp** [comment]
Using a good sword plus the killaura of a hack client of your choice  is also a possibility.
