### ISSUE TITLE
Baritone #mine  or #goto  not working on the nether.

### ISSUE THREAD

**Issue by limonetexd** [cabaletta/baritone#3919]
## Some information about my problem
Operating system: Windows 11 Pro 22H2 Build 22621.1555)
Java version: Version 8 update 361 (build 1.8.0_361-b09)  <-- It's 64 bits
Minecraft version: 1.19.4
Baritone version: Baritone 1.9.2 for Fabric
Other mods (Fabric): fabric-api-0.75.3    iris 1.6.1    sodium 0.4.10 build 24     Wurst Client v7.32

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

-  On Windows PC's: `%appdata%/.minecraft/logs/`

[latest.log](https://github.com/cabaletta/baritone/files/11302224/latest.log)

## How to reproduce
In the overworld it works fine. I enter the nether, I use `#mine quartz_ore` and it says: `Error at argument #1: Expected w`. If I try `#goto quartz_ore` it's the same.

## Modified settings
I didn't modified any settings.

### Check List
- [x] I know how to properly use check boxes. (It's kinda obvious)
- [x] I have included the version of Minecraft I'm running, baritone's version and forge (in my case fabric) mods!
- [x] I have included logs, exceptions and steps to reproduce the issue.
- [x] I have not used any OwO's, UwU's or 7u7 in this issue.
- [x] I investigated (just a little bit)

### Extra information
It's a Aternos Server. I don't use Essential Mod to play. I have never used it in the nether. I have OP commands. I'm not using shaders. Quarz ores are loaded in my chunks  ![image](https://user-images.githubusercontent.com/82970360/233805320-9f54534b-ce7f-4775-ad25-bb6346fa0d4b.png) . I'm using Vanilla Tweaks texture pack.  I don't have any WRUST hack enabled. Thank you so much for helping me!

**Comment by ZacSharp** [comment]
You log doesn't show any sign of you trying to run any of the commands in the overworld and I doubt any of them would work.
According to the [fandom minecraft wiki](https://minecraft.fandom.com/wiki/Nether_Quartz_Ore#History) the id is `nether_quartz_ore` since 1.13.

**Comment by limonetexd** [comment]
Tysm
