### ISSUE TITLE
Mining in layers

### ISSUE THREAD

**Issue by TheSrBig** [cabaletta/baritone#3921]
That it is possible to mine in Y layers, for example that you can only mine deepslate diamonds ore, in only layer -59 and not higher or lower, or also mine between layers, for example between layers -59 and -40 and only those.

**Comment by ZacSharp** [comment]
There is already an option to limit it to only consider ores above a certain y value, the other one was already suggested in #1883, so this is a duplicate.

If want to use `minYLevelWhileMining` you'll have to offset the value by the minimum y level of your world (it's "blocks above minimum y" not "y coordinate") so to mine only ores above y=-59 in a world starting at y=-64 you would set it to 5.
