### ISSUE TITLE
#follow player not working

### ISSUE THREAD

**Issue by NixPlayer** [cabaletta/baritone#3922]
Operating system: Windows 11 64-bit
Java version: Java 8
Minecraft version: 1.12.2
Baritone version: Null (presumibly the latest version for 1.12.2)
Other mods (if used): Lambda Client 3.30

[2023-04-24-3.log](https://github.com/cabaletta/baritone/files/11313421/2023-04-24-3.log)

## How to reproduce
Enter a server with someone
do in chat #follow player "target"

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by NixPlayer** [comment]
[2023-04-24-3.log](https://github.com/cabaletta/baritone/files/11313417/2023-04-24-3.log)

**Comment by wagyourtail** [comment]
The player has to be within render distance

**Comment by ZacSharp** [comment]
I doubt you are using the latest version for 1.12.2. #3024 was merged one and a half years ago and is included in the latest releases for all versions (that's v1.2.17 for 1.12.2).
