### ISSUE TITLE
#goto not working

### ISSUE THREAD

**Issue by Crimson7973** [cabaletta/baritone#3925]
## Some information
Operating system: MACOS
Java version: 1.19.3
Minecraft version:  1.19.3
Baritone version: 1.9.3
Other mods (if used): Meteor Client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Use any command (ex: Goal and thisway) and once using #goto it will not move with the expected path to it still appearing but only being a barely noticeable black line.
## Modified settings
To get the modified settings run `#modified` in game
None modified
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
please actually fill out the log section

**Comment by Crimson7973** [comment]
There was no log, The most recent log was from 3/12/22

**Comment by rycbar0** [comment]
then you looking in the wrong place. a log is created on every game start up
to locate the correct folder open minecraft go to your settings -> resource packs -> open folder. this opens a file explorer window. move 1 folder up and look for the logs folder.
