### ISSUE TITLE
Baritone 1.8.9

### ISSUE THREAD

**Issue by eternadox** [cabaletta/baritone#3927]
## What do you need help with?
Is it possible to backport Baritone to 1.8.9? And it would be nice if I knew how to make it in MCP (1.8.9) but that is against Mojang's TOS.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
It is possible. No one here will do it. it would still have the same structure of mixins and launchtweaker if backported.

**Comment by eternadox** [comment]
good to know
