### ISSUE TITLE
Ability to change preferred tool for breaking certain blocks

### ISSUE THREAD

**Issue by lucidliam** [cabaletta/baritone#3929]
## Describe your suggestion
There should be a setting that allows one to choose what tool to use to break a block with. For example, using a hoe to break crops, or using a regular pickaxe for stone and fortune for an ore
## Settings
The setting should allow a player to list a block and what to break it with, perhaps by item type, or item name, or item nbt tags
## Context
This would help players customize what tools to use to get things such as using fortune on certain items but not for everything!
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.
- [x] I love pizza!

**Comment by ZacSharp** [comment]
Already suggested a dozen times (just search for "tool" and half of the results will be this or very similar)
