### ISSUE TITLE
A different tool for different blocks

### ISSUE THREAD

**Issue by RevanMardagh** [cabaletta/baritone#3930]
## Describe your suggestion
I would like for baritone to switch to a silk touch pickaxe when mining stone, and a fortune pickaxe when mining deepslate or diamond ore. Can you add a setting for that?

## Settings
a setting can be added for autoTool

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added:
This will improve player ease of use if they want to get stone instead of cobblestone, but still want to mine diamonds with a fortune pickaxe.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3964 or #2942
