### ISSUE TITLE
an issue with autobuild

### ISSUE THREAD

**Issue by JakeWgg** [cabaletta/baritone#3932]
hey my issue is every time i put in a name that is in the schematics folder it says (please put the full name) but i do every time here's a screenshot to show it  
![Minecraft Screenshot 2023 05 06 - 15 35 37 83](https://user-images.githubusercontent.com/132783060/236643449-9855a500-d7c5-431b-906a-eacc1bb84676.png)
idk if theres something i have to do but it does not make any sense to me 

im on 1.19.3

**Comment by ZacSharp** [comment]
What's the name of the schematic? If it's not a ".schematic" then "<whatever>.schematic" can't work. The error message is a fixed string so the example is really just an example and not a copypasteable fixed command. In fact, it outputs that error message pretty much regardless of what went wrong.
If it is indeed a ".schematic" then I recommend using an online converter or Litematica to convert it to ".schem" or ".litematic".

**Comment by JakeWgg** [comment]
> What's the name of the schematic? If it's not a ".schematic" then ".schematic" can't work. The error message is a fixed string so the example is really just an example and not a copypasteable fixed command. In fact, it outputs that error message pretty much regardless of what went wrong. If it is indeed a ".schematic" then I recommend using an online converter or Litematica to convert it to ".schem" or ".litematic".

can u list a converter?

**Comment by ZacSharp** [comment]
I'd have to search and blindly suggest a website I've never seen before so no. My choice would be Litematica.
