### ISSUE TITLE
follow entity pig使用日志错误

### ISSUE THREAD

**Issue by OVQKEwshh** [cabaletta/baritone#3934]
[Baritone] An unhandled exception occurred. The error is in your game's Iog, pleasereport this at https://github.com/cabaletta/ baritone/[issues](![1683483282626](https://user-images.githubusercontent.com/119103331/236695319-98dd7e81-0ce4-4cef-9b95-ef29813bb28d.jpg)

**Comment by wagyourtail** [comment]
Please fill out the bug report template correctly and completely.

Also if there isnt a pig within render distance, that would cause it
