### ISSUE TITLE
No Diagonals for Baritone Parkour

### ISSUE THREAD

**Issue by Reetew** [cabaletta/baritone#3938]
I was playing around with the parkour and it's not doing any diagonal jumps even just one block. Is there a setting to fix this or is it a bug? It can walk diagonally if there is a block but it can't jump.
![Desktop Screenshot 2023 05 09 - 05 53 58 97](https://user-images.githubusercontent.com/133000477/237061958-cc28d7d2-a70c-4d15-a49a-05e406ac6c51.png)

**Comment by rycbar0** [comment]
its not a bug, its a missing feature. the reason behind it is the computation would get way more complex. walking 1 block strait requires baritone to check 2 blocks (foot an head position) if they are passable as well as1 block bellow if it is a solid block to walk on.
to jump you also need head room else you cant jump. for diagonal walking you have to check 3 times as many blocks for clearance. to jump diagonaly over a 1 block gap you would need to check around 22 blocks. that is for a jump on the same y level. inclouding jumps to lower y levels and over wider gaps would increas that even more.

**Comment by Reetew** [comment]
Oh ok that's really cool, thanks for the explanation.

**Comment by ZacSharp** [comment]
It's not impossible though. You can find a working (and outdated) implementation in #2142, which wasn't merged because the author did not have the time to finish it. If somebody else wants to give it a try, there's a good start already.
