### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Tman564ws1** [cabaletta/baritone#3941]
## Some information
Operating system:ChromeOS
Java version:ldk
Minecraft version:pojavlauncher: forge 1.12.2
Baritone version:1.2.17
Other mods (if used): schematica, 12.2-1.2LunatriusCore-1.0.42-universal, worldedit for forge and baritone for forge api

## Exception, error or logs

[latestlog.txt](https://github.com/cabaletta/baritone/files/11435561/latestlog.txt)

## How to reproduce
use the #build flag.nbt

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
 and yes pojavlaucher works i am 100% sure.

**Comment by rycbar0** [comment]
.nbt is a not supported file format
