### ISSUE TITLE
Maintenance 

### ISSUE THREAD

**Issue by h3tz** [cabaletta/baritone#3948]
Why non of the pulls are handled and why it seems like the project is dead? Does the developer need support?

**Comment by ZacSharp** [comment]
Why do you think none of the pulls are handled? Last couple of prs was merged last month and the majority of open prs is waiting on their author, not on feedback.
Also you can decide yourself whether an answer within 10 hours counts as dead. I'm not "the developer" though.

**Comment by h3tz** [comment]
> Why do you think none of the pulls are handled? Last couple of prs was merged last month and the majority of open prs is waiting on their author, not on feedback. Also you can decide yourself whether an answer within 10 hours counts as dead. I'm not "the developer" though.

I was not aware of this. Thanks for your feedback.

**Comment by h3tz** [comment]
misunderstanding from reporter.
