### ISSUE TITLE
automine bug

### ISSUE THREAD

**Issue by niggish** [cabaletta/baritone#395]
**baritone?**

- mining `emerald_ore, diamond_ore, gold_ore`

video- https://streamable.com/731bd

- Impact Version: `4.6 for 1.13.2`
- Using Optifine? `yes`
- Using LiteLoader? `no`
- Enabled mods: `fast interact`
- Operating System: `windows 10 64-bit`

**Comment by leijurv** [comment]
Looks like it mined some gravel that had generated unsupported above a lava lake, so once you mined an adjacent block it all fell?

**Comment by niggish** [comment]
yea, maybe make an option for detecting that and avoiding it :)

**Comment by SylveonBottle** [comment]
Maybe treat falling blocks with air below them like lava, and don't break blocks around them?
