### ISSUE TITLE
how and is it easy to update 1.18 fork to 1.19-19.3?

### ISSUE THREAD

**Issue by Andrelissss** [cabaletta/baritone#3951]
I found a fork that I want to update to 1.19, but I don't know how. Could someone help me? here is the link
https://github.com/SM1LLER/baritone/tree/1.18-smoothAim

**Comment by ZacSharp** [comment]
If you already have some experience with minecraft modding it should be as simple as merging the 1.18 branch into a 1.19 branch and fixing some small issues. If you don't I'd suggest you take an easier route and cherry pick the commits you want onto the version you want so you don't have to deal with changes unrelated to those you want.

Concerning "is it easy": I'd say it's definitely not easy if the kind of instructions you need is literal commands to run, but if "clone both repos (SM1LLER/baritone and cabaletta/baritone), cherry-pick the commits you want from the SM1LLER 1.18-smoothAim branch onto the cabaletta 1.19.3 branch, use `gradlew build` to build and fix compiler errors" is all you needed to know, then it is easy.
