### ISSUE TITLE
Scripts for baritone

### ISSUE THREAD

**Issue by hecker2000** [cabaletta/baritone#3953]
## What do you need help with?
Well, I was looking at the API and don't understand that yet. So I was hoping that a TXT or even JSON file could be used to run through a list of commands. Please reply on said method if anyone finds what I'm looking for.
Heres is what I would imagine a TXT or script for baritone would look like
`mine 64 oak_log; goto crafting_table`

## Final checklist
- [x] I know how to properly use check boxes,
- [x] I have not used any OwO's or UwU's in this issue,
- [x] I do not understand any of this, please be clear in responses.

**Comment by rycbar0** [comment]
baritone does not support scrips.
you may have heard of altoclef, a fork of baritone that extends on its abilitys and allows for more abstract commands like crafting a diamond pickaxe, which automatically gets deconstructed into many smaller steps.
if you really want to use scripts try to check out jsmacros. its a mod that allows to create and run javascripts in game. the script can use baritone via the api or the chat commands.

**Comment by hecker2000** [comment]
> baritone does not support scrips. you may have heard of altoclef, a fork of baritone that extends on its abilitys and allows for more abstract commands like crafting a diamond pickaxe, which automatically gets deconstructed into many smaller steps. if you really want to use scripts try to check out jsmacros. its a mod that allows to create and run javascripts in game. the script can use baritone via the api or the chat commands.

alr cool lemme check it out, ima task baritone with getting a full set of diamond
