### ISSUE TITLE
Add to README.md reminding users that "baritoneminecraft.com" is NOT an official Baritone website, etc.

### ISSUE THREAD

**Issue by fffelix-jan** [cabaletta/baritone#3957]
## Describe your suggestion
Add to README.md reminding users that "baritoneminecraft.com" is NOT an official Baritone website, despite its claims.

## Settings
N/A

## Context
baritoneminecraft.com states:
```
We Baritone Minecraft team is ensuring that video gaming is one of the most significant aspect for our daily lifestyle and have designed this baritoneminecraft.com website. Especially, this is a informative platform for useful tech tips and news.

Our customer service will help you to clarify the doubts in your mind regarding our website content. Therefore, we invite you to share your concerns with the ”Contact Us” details mentioned here.
```
This is very deceptive, and since Leijurv told me that he had already unsuccessfully contacted the registrar to remove the domain, the best that the Baritone devs could do about it is to place a reminder on the readme stating where the only official websites for Baritone are, to prevent users from downloading malware.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rivalryxd** [comment]
IMA MAKE A PR

**Comment by BL1Z33** [comment]
heres the pr: https://github.com/cabaletta/baritone/pull/3973

**Comment by ZeroMemes** [comment]
Closing for same reason as #3973
