### ISSUE TITLE
Tunnel falling in lava because of falling blocks

### ISSUE THREAD

**Issue by Golaco** [cabaletta/baritone#3961]
When I'm using the tunnel command, it sometimes (more than once) fell into lava because it was mining standing on suspened gravel and it updated. I know this is probably tricky as hell to prevent, but is there any workaround? avoidUpdatingFallingBlocks is set to true, but that didn't help either.
Hope this is not a duplicate, and appreciate any answers :)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Why did the gravel start falling and what command were you using?
`avoidUpdatingFallingBlocks` mostly affects pathfinding and I'm not sure whether it affects placing blocks at all.
