### ISSUE TITLE
Can you use Baritone on Wurst?

### ISSUE THREAD

**Issue by rivalryxd** [cabaletta/baritone#3962]
## What do you need help with?
I'm wondering if Baritone has support with Wurst 1.19.4 and if so, how would I install it?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Well. I
Baritone can be a forge mod... so...

Well there is one issue, but thats a them problem. https://github.com/Wurst-Imperium/Wurst7/pull/370
