### ISSUE TITLE
How to i can make this follow target

### ISSUE THREAD

**Issue by Halqq** [cabaletta/baritone#3965]
How do I make my baritone follow a target in an onUpdate method (which checks every frame)?

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
you need to explain a little more. i have no clue what a "onUpdate" method is.

to follow a entity you have to set the `private Predicate<Entity> filter;`  field in the followprocess by calling the FollowProcess .follow() method.

to my knowlage the goals get updated each tick in the .onTick() method which injects in to minecrafts onTick method, which is called 20 times a second.
