### ISSUE TITLE
my baritone dont work

### ISSUE THREAD

**Issue by Halqq** [cabaletta/baritone#3967]
(I only have this Baritone code in my entire client, nothing else, just this:

 ``` 
IBaritone baritone = BaritoneAPI.getProvider().getPrimaryBaritone();
                    if (baritone.getPathingBehavior().isPathing()) {
                        baritone.getPathingBehavior().cancelEverything();
                    }

                    if (target != null && target.isEntityAlive()) {
                        int targetX = (int) target.posX;
                        double targetY = target.posY;
                        int targetZ = (int) target.posZ;

                        baritone.getCustomGoalProcess().setGoalAndPath(new GoalXZ(targetX, targetZ));
                    ) ```

I don't have any logs or crashes; Baritone simply doesn't work.

**Comment by rycbar0** [comment]
wild guess because i only have a code sniplet but you probably call a method before it is properly initialized

**Comment by Halqq** [comment]
How do I fix it?

**Comment by Halqq** [comment]
> wild guess because i only have a code sniplet but you probably call a method before it is properly initialized

How do I fix it?

**Comment by Halqq** [comment]
> > wild guess because i only have a code sniplet but you probably call a method before it is properly initialized
> 
> How do I fix it?

```java

 @Override
    public void onUpdate() {
        if (mc.world != null && mc.player != null) {
            EntityPlayerSP player = mc.player;
            WorldClient world = mc.world;

            double closestDistanceSq = Double.MAX_VALUE;

            for (EntityPlayer entity : mc.world.playerEntities) {
                if (entity != mc.player) {
                    double distanceSq = player.getDistanceSq(entity);

                    if (distanceSq < closestDistanceSq && isInRange(player, entity)) {
                        closestDistanceSq = distanceSq;
                        target = entity;
                    }
                }
            }

            if (target != null && target.isEntityAlive() && canAttack(target)) {

                if (attackThroughWalls.getValue() || isVisible(player, target)) {
                    if (autoSwitch.getValue()) {
                        int bestSlot = getBestWeaponSlot();
                        if (bestSlot != -1) {
                            player.inventory.currentItem = bestSlot;
                        }
                    }

                    if (rotateHead.getValue()) {
                        rotateHeadTowards(player, target);
                    }

                    if (rotateBody.getValue()) {
                        rotateBodyTowards(player, target);
                    }

                    if (criticals.getValue()) {
                        // Custom attack logic with critical hits
                        attackEntityCritical(player, target);
                    } else {
                        // Custom attack logic without critical hits
                        attackEntity(player, target);
                    }
                }

                if (chaseTarget.getValue()) {
                    IBaritone baritone = BaritoneAPI.getProvider().getPrimaryBaritone();
                    if (baritone.getPathingBehavior().isPathing()) {
                        baritone.getPathingBehavior().cancelEverything();
                    }

                    if (target != null && target.isEntityAlive()) {
                        int targetX = (int) target.posX;
                        double targetY = target.posY;
                        int targetZ = (int) target.posZ;

                        BaritoneAPI.getProvider().getPrimaryBaritone().getFollowProcess().follow((Predicate<Entity>) target);                    }
                }
            }
        }
    } ```

**Comment by rycbar0** [comment]
idk try this?
```java
@Override
    public void onUpdate() {
        if (mc.world != null && mc.player != null) {
            EntityPlayerSP player = mc.player;
            WorldClient world = mc.world;

            double closestDistanceSq = Double.MAX_VALUE;

            for (EntityPlayer entity : mc.world.playerEntities) {
                if (entity != mc.player) {
                    double distanceSq = player.getDistanceSq(entity);

                    if (distanceSq < closestDistanceSq && isInRange(player, entity)) {
                        closestDistanceSq = distanceSq;
                        target = entity;
                    }
                }
            }

            if (target != null && target.isEntityAlive() && canAttack(target)) {
                BaritoneAPI.getProvider().getPrimaryBaritone().getFollowProcess().onLostControl(); //when in attack range cancel following
                if (attackThroughWalls.getValue() || isVisible(player, target)) {
                    if (autoSwitch.getValue()) {
                        int bestSlot = getBestWeaponSlot();
                        if (bestSlot != -1) {
                            player.inventory.currentItem = bestSlot;
                        }
                    }

                    if (rotateHead.getValue()) {
                        rotateHeadTowards(player, target);
                    }

                    if (rotateBody.getValue()) {
                        rotateBodyTowards(player, target);
                    }

                    if (criticals.getValue()) {
                        // Custom attack logic with critical hits
                        attackEntityCritical(player, target);
                    } else {
                        // Custom attack logic without critical hits
                        attackEntity(player, target);
                    }
                }

                if (chaseTarget.getValue()) {
                    IBaritone baritone = BaritoneAPI.getProvider().getPrimaryBaritone();
                    baritone.cancelEverything(); //cancels all active baritone processes. not sure why any should be active anyway.

                    if (target != null && target.isEntityAlive()) {
                        baritone.getFollowProcess().follow(target); //if you have a alive target follow it
                    }
                }
            }
        }
    }
```

**Comment by Halqq** [comment]
> idk try this?
> 
> ```java
> @Override
>     public void onUpdate() {
>         if (mc.world != null && mc.player != null) {
>             EntityPlayerSP player = mc.player;
>             WorldClient world = mc.world;
> 
>             double closestDistanceSq = Double.MAX_VALUE;
> 
>             for (EntityPlayer entity : mc.world.playerEntities) {
>                 if (entity != mc.player) {
>                     double distanceSq = player.getDistanceSq(entity);
> 
>                     if (distanceSq < closestDistanceSq && isInRange(player, entity)) {
>                         closestDistanceSq = distanceSq;
>                         target = entity;
>                     }
>                 }
>             }
> 
>             if (target != null && target.isEntityAlive() && canAttack(target)) {
>                 BaritoneAPI.getProvider().getPrimaryBaritone().getFollowProcess().onLostControl(); //when in attack range cancel following
>                 if (attackThroughWalls.getValue() || isVisible(player, target)) {
>                     if (autoSwitch.getValue()) {
>                         int bestSlot = getBestWeaponSlot();
>                         if (bestSlot != -1) {
>                             player.inventory.currentItem = bestSlot;
>                         }
>                     }
> 
>                     if (rotateHead.getValue()) {
>                         rotateHeadTowards(player, target);
>                     }
> 
>                     if (rotateBody.getValue()) {
>                         rotateBodyTowards(player, target);
>                     }
> 
>                     if (criticals.getValue()) {
>                         // Custom attack logic with critical hits
>                         attackEntityCritical(player, target);
>                     } else {
>                         // Custom attack logic without critical hits
>                         attackEntity(player, target);
>                     }
>                 }
> 
>                 if (chaseTarget.getValue()) {
>                     IBaritone baritone = BaritoneAPI.getProvider().getPrimaryBaritone();
>                     baritone.cancelEverything(); //cancels all active baritone processes. not sure why any should be active anyway.
> 
>                     if (target != null && target.isEntityAlive()) {
>                         baritone.getFollowProcess().follow(target); //if you have a alive target follow it
>                     }
>                 }
>             }
>         }
>     }
> ```

Required type:
Predicate
<net.minecraft.entity.Entity>
Provided:
EntityPlayer

predicate??

**Comment by ZeroMemes** [comment]
> predicate??

Yes. The [documentation](https://baritone.leijurv.com/baritone/api/process/IFollowProcess.html#follow-java.util.function.Predicate-) for FollowProcess indicates that the `follow` method accepts a [`Predicate`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html), which is used to match the target entity.

Because `Predicate` is a [functional interface](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html), it may implemented as a [lambda expression](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html).

**Comment by Halqq** [comment]
> Yes. The [documentation](https://baritone.leijurv.com/baritone/api/process/IFollowProcess.html#follow-java.util.function.Predicate-) for FollowProcess indicates that the `follow` method accepts a [`Predicate`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html), which is used to match the target entity.
> 
> Because `Predicate` is a [functional interface](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html), it may implemented as a [lambda expression](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html).

How can I modify the predicate filter to include only a specific entity (target) in my method?
