### ISSUE TITLE
how to i can disable log chat 

### ISSUE THREAD

**Issue by Halqq** [cabaletta/baritone#3968]
how to disable log chat with baritone api??

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
What exactly do you want to disable? If it's just the verbose output you can turn off `chatDebug`, if you want to turn off all feedback you can replace the feedback handlers (the `logger`, `toaster` and `notifier` settings) with no op implementations.
