### ISSUE TITLE
Just break this block #mine iron_ore allowBreak:iron_ore

### ISSUE THREAD

**Issue by NEKOgrile** [cabaletta/baritone#3969]
## What do you need help with?
Is there a command similar to #mineiron_ore allowBreak:iron_ore? On my server, I can break specific blocks within a designated area, but I can't break anything else. When I use the command #mineiron_ore, it gets stuck trying to mine that block indefinitely. I would like to force it to only break a specific type of block so that it can find the most straightforward natural/artificial path to reach it, and I want to apply the same rule to other blocks within a defined area.
![2023-06-05_09 39 21](https://github.com/cabaletta/baritone/assets/98735979/0c6795d6-18b4-4bf8-ab8c-542dba5346db)
![2023-06-05_09 39 22](https://github.com/cabaletta/baritone/assets/98735979/11b868ec-4544-43a3-ae3b-c2e4e455e582)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`allowBreak` and `allowBreakAnyway` exists.
Please don't cheat.

**Comment by NEKOgrile** [comment]
idk how tu use this commande
