### ISSUE TITLE
impact 4.6

### ISSUE THREAD

**Issue by shaooly** [cabaletta/baritone#397]
how do I implement baritone master into impact 4.6? I've tried your tutorial in the site and it doesn't work

**Comment by ZeroMemes** [comment]
What game version are you using 4.6 on?

Baritone's **master** branch is for **1.12.2**
Baritone's **1.13.2** branch is for **1.13.2**

**Comment by leijurv** [comment]
4.6 comes with baritone

**Comment by leijurv** [comment]
yeah 4.6 comes with baritone and cant even run without it, so this is invalid imo
