### ISSUE TITLE
Baritone has issues building schematics

### ISSUE THREAD

**Issue by Dream23322** [cabaletta/baritone#3978]
## Some information
Operating system: Windows 64x
Java version: idk
Minecraft version: 1.12.2
Baritone version: idk
Other mods (if used):  Lambda client (Lambda clients baritone)

## How to reproduce
Build any half complex schematic<

Ok, so what happens is baritone wants to place a block to say build up/ scaffold but cant because in the schematic there is air there... so it will place the scaffold block, break it then just, not do anything lol

## Modified settings
To get the modified settings run `#modified` in game

AllowInventory
AllowParkour
AllowParkourPlace
blacklistClosestOnFailiure

Thers a lot...
![image](https://github.com/cabaletta/baritone/assets/110651012/1c45da2b-1761-4c3f-ab2d-231e0ba5e048)
![image](https://github.com/cabaletta/baritone/assets/110651012/0e241a5a-664f-445a-8a7d-2f36ee443b3a)
![image](https://github.com/cabaletta/baritone/assets/110651012/79503a94-759f-4ad6-8b31-27aadd0d0182)
![image](https://github.com/cabaletta/baritone/assets/110651012/a1b591cd-8aaa-4406-8e21-e74216a75f1e)
![image](https://github.com/cabaletta/baritone/assets/110651012/11ef5d5e-305f-4e27-9533-35aaba548f61)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
hi
yes we are aware of the limits of the current build implementation. baritone is at its core a path finding bot and building is a extra. there is a builder-2 branche that tries to overhaul the hole building system but its not ready. baritone will struggle with all blocks that have rotations and is unable to build blocks that have non default block states like repeaters with non default delay.
you can add the block properties that are a issue to the buildIgnorProperties setting as a comma divided list or if a block isnt buildable you can add it to the buildSkipBlocks setting, also as a comma divided list.

you can also try out a schematic printer like the printer addon for litematica. this addon does not care about realistic blockplacement and will place blocks with fake rotations etc. to "print" the schematic as fast as possible. you only have to walk close to the schematic

**Comment by Dream23322** [comment]
alright


Its fine in the case that im using it right now i just noticed it when building other stuff, keep up the good work <3

**Comment by Dream23322** [comment]
Also just wondering is there a way for baritone to always render what it needs to mine? like even if its not moving

**Comment by rycbar0** [comment]
the break and place boxes are created for a path and a path is calculated when a process needs to get to a goal. you can pause a process to stop walking but if you cancle the process the path gets deleted and with it the overlay. the amount of active goal and the break/place overlays are limited for practicality and performance reasons (usually as hard coded values).

**Comment by Dream23322** [comment]
ok
