### ISSUE TITLE
Enable blockFreeLook

### ISSUE THREAD

**Issue by cochcoder** [cabaletta/baritone#3989]
How do you enable looking around while breaking blocks? In the PR that adds this feature it is listed as blockFreeLook in settings. When I do "#blockFreeLook true" while playing it says "Command not found: blockFreeLook". 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
What version are you using. Atm it's been only in the master branch (1.12).

**Comment by cochcoder** [comment]
I'm using V1.10.1

**Comment by ZeroMemes** [comment]
It's only available on Minecraft 1.12.2 right now *if* you build Baritone yourself. It will be available for all game versions with the next Baritone release.
