### ISSUE TITLE
Baritone can get stuck due to simulated mouse movements

### ISSUE THREAD

**Issue by ZacSharp** [cabaletta/baritone#3994]
## Some information
Minecraft version: 1.12.2
Baritone version: c86643874dcaccd6435b6f2f16e0b9eca1eeb224
Other mods (if used): None

## Exception, error or logs
No exceptions, no logs, nothing.

## How to reproduce
1. Set mouse sensitivity to "HYPERSPEED!!!" (200%). It increases your chances of "getting lucky".
2. Let Baritone build a lot of blocks (I was testing `#sel cyl/hcyl/sph/hshph` when I noticed this)
3. If you "get lucky" it will at some point stall, looking right at the edge of a block but it wants to place right past that edge.
4. If you turn your mouse sensitivity down it will probably unstuck. (Alternatives are wildly moving your mouse or pausing and moving ever so slightly)

Maybe it is possible to set up a situation where it will get stuck right away (build blocks, set up aim using low sensitivity or commands, crank up sensitivity, let it fail), but so far I had no luck doing so.

## Suspected cause
I suspect when this happens the edge of the obstructing block is less than one pixel of mouse movement from the target rotations and the closest "possible" approximation to the target rotations happen to miss the target towards the obstructing block (i.e. aiming at the wrong block gets it closer to the target rotations than aiming at the correct block)

<details><summary><h2>Screenshot</h2></summary>

![2023-06-18_02 02 46](https://github.com/cabaletta/baritone/assets/68165024/0184aee1-9fe1-46cf-a517-28f69cc3838c)

</details>

<details><summary><h2>Screenshot from testing on Minecraft 1.16</h2></summary>

![2023-06-18_17 18 45](https://github.com/cabaletta/baritone/assets/68165024/75bcfe18-4325-4d21-84fc-e4a3f156bfbb)

</details>

## Modified settings
No Baritone settings modified.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not typed any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
we addressed this in a fork, cherry picked https://github.com/cabaletta/baritone/commit/6c8f2698d697c3ffaca7022f29644c6317435494

**Comment by ZacSharp** [comment]
How should that fix it? When this happens Baritone is looking at the wrong block so `ctx.isLookingAt(pos)` is already `false` and changing the setting doesn't do anything (besides short circuiting the check).

I also couldn't find any difference with `remainWithExistingLookDirection` set to false.

https://github.com/cabaletta/baritone/assets/68165024/eb20e50a-ab03-493f-8f6f-2cc29c90ec1a

It doesn't need to be looking at a block at all.

https://github.com/cabaletta/baritone/assets/68165024/8859f5ac-8a42-4516-ab5e-a927bce38431

**Comment by leijurv** [comment]
So it's a problem with https://github.com/cabaletta/baritone/commit/c8b8deb3d62d5a786054fd1939293cb71673258c?

The solution might be something like the old endless issues with sneak placing changing the player eye Y coordinate tbh (all the "wouldSneak" options).

When calculating "If I looked at this angle, would I be able to place this block" it should take into account that it's really "if I looked at this angle using integer mouse movements". Then, standing at the exact edge of a block like that would make it realize that the potential placement is not possible so it would continue walking forward.

**Comment by leijurv** [comment]
@ZeroMemes

**Comment by ZeroMemes** [comment]
And to think I was this close to adding a setting for the mouse movements 😔

**Comment by leijurv** [comment]
Like here https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/pathing/movement/MovementHelper.java#L686 it simulates what the rotation WOULD be if the player started sneaking then tried to look at the block - I guess this now needs to take into account: what WOULD the rotation be if the player started sneaking then tried to look at the block with only integer pixel mouse movement. THAT rotation should be the one that's then subsequently raytraced on the next line

**Comment by ZacSharp** [comment]
Yes, sounds like that would fix it.

(If you want it to look even worse, you can iterate over the closest 9 rotations.)

**Comment by ZacSharp** [comment]
Fun fact: `BuilderProcess` uses `RotationUtils.reachable` to look at blocks it wants to break, but does it's own thing for blocks it wants to place.

Just making `RotationUtils.reachable` (and `BuilderProcess.possibleToPlace` apply the mouse discretization before raycasting causes a lot more jitter and `IAimProcessor` has this effect as well. Neither gets stuck though so that's an improvement.

**Comment by ZacSharp** [comment]
The jitter was me being stupid. I didn't apply the rotation processing to just the raycast, I applied them to the `LookBehavior` *target* as well.
When applying the mouse simulation (or the whole `IAimProcessor`) to the raycast and nothing else both the jitter and the stalling are gone.
