### ISSUE TITLE
About AntiXray

### ISSUE THREAD

**Issue by mmyddd** [cabaletta/baritone#3997]
If a server version is purpur,and it have antixray plugin,hou can i deal with it???
Does the mod have any command to solve this problem,tell me

**Comment by ZacSharp** [comment]
Baritone has a `mineOnlyExposedOres` and a `legitMine` setting. (don't think any of those will hide you from good anti cheats or even staff)
`mineOnlyExposedOres` makes `#mine` only mine ores which are next to air but still can "see" through blocks while `legitMine` will cause it to only walk to ores it has previously seen and explore randomly to find ores.
