### ISSUE TITLE
#sel ignoring blocksToDisallowBreaking

### ISSUE THREAD

**Issue by LukasCraftxD** [cabaletta/baritone#3998]
## Some information
Operating system: windows 10
Java version: jdk-20_windows-x64
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used): Sodium 

## Exception, error or logs
 [Render thread/INFO]: [System] [CHAT] [Baritone] > blocksToDisallowBreaking
 [Render thread/INFO]: [System] [CHAT] [Baritone] Value of setting blocksToDisallowBreaking:
 [Render thread/INFO]: [System] [CHAT] [Baritone] iron_block,beacon
 
## How to reproduce
1. add iron blocks and beacons to blocksToDisallowBreaking
2. #sel pos1 
3. #sel pos2
4. #sel fill air
make sure you have a beacon from iron blocks in the selected area and other blocks stand close the beacon 
and see it begin to mine it

## Modified settings
[Render thread/INFO]: [System] [CHAT] [Baritone] > modified
 [Render thread/INFO]: [System] [CHAT] [Baritone] All modified settings:
 [Render thread/INFO]: [System] [CHAT] [Baritone] avoidBreakingMultiplier (Double)
 [Render thread/INFO]: [System] [CHAT] [Baritone] blocksToAvoidBreaking (List<class_2248>)
 [Render thread/INFO]: [System] [CHAT] [Baritone] blocksToDisallowBreaking (List<class_2248>)
 [Render thread/INFO]: [System] [CHAT] [Baritone] itemSaver (Boolean)
 [Render thread/INFO]: [System] [CHAT] [Baritone] mobAvoidanceRadius (Integer)
 [Render thread/INFO]: [System] [CHAT] [Baritone] --
 [Render thread/INFO]: [System] [CHAT] [Baritone] --
 [Render thread/INFO]: [System] [CHAT] [Baritone] --
 [Render thread/INFO]: [System] [CHAT] [Baritone] << | >> 1/1

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`BuilderProcess` ignores basically any setting which applies to normal path following.
If you want `#build` or `#selection *` to not break certain blocks you have to use `buildIgnoreBlocks` (only works if your schematic contains air at the position in question, it will still break those blocks to place something else in their position)
