### ISSUE TITLE
Building locally as a Fabric mod

### ISSUE THREAD

**Issue by jdbool** [cabaletta/baritone#4001]
## What do you need help with?
I can't figure out how to get a Fabric jar out of the build process -- only Forge. I also see no mention of Fabric anywhere except for in the docs.

I'm probably just missing something obvious. Thank you!

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
On which branch are you? For 1.12.2 (master) there is no Fabric build, for the newer versions there are multiple ways of building for Fabric depending on the branch.

**Comment by jdbool** [comment]
> On which branch are you? For 1.12.2 (master) there is no Fabric build, for the newer versions there are multiple ways of building for Fabric depending on the branch.

Yeah I didn't realize master was for 1.12.2. Thanks.
