### ISSUE TITLE
is it possible to get baritone for 1.20.1 like 1.16.5 

### ISSUE THREAD

**Issue by Litt1eThief** [cabaletta/baritone#4004]
is it possible to get baritone for 1.20.1 as a version of Minecraft and not need a mod launcher?

**Comment by rycbar0** [comment]
have you checked the [releases](https://github.com/cabaletta/baritone/releases)?
also is there a specific reason why you dont want to/ can't use a mod loader, just wondering?

**Comment by ZacSharp** [comment]
The releases contain the tweaker jars but not the version.json files to load them.
I'm not aware of a ready made version.json for Baritone v1.10 so you'll have to butcher that yourself based on some existing one like the one for Baritone v1.6 (or you find someone who does it for you).
