### ISSUE TITLE
Chat window autocomplete

### ISSUE THREAD

**Issue by nodomw** [cabaletta/baritone#4010]
## Describe your suggestion
I've seen plenty of mods which implement chat commands to do this, it just makes sense

## Settings
a boolean "chatAutocomplete" value that should be turned on by default for any version >= 1.13 (that's when the modern chat autocomplete system was implemented I think)

## Context
I feel like this would make the most sense in Baritone, where the primary way to interact with the mod is through chat, and something like this would drastically streamline the user experience.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
baritone has tab autocomplete if you mean that

**Comment by ZacSharp** [comment]
Baritone has tab completion on all versions. If you press tab it will show up.
There is a problem though: Tab completion didn't make it through the update to 1.13 very well so you have to press escape and then tab to update the completions.
