### ISSUE TITLE
Head Movement Smoother

### ISSUE THREAD

**Issue by TiredGreenify** [cabaletta/baritone#4013]
## Describe your suggestion
So I was using Baritone on a server with basic anti-cheats and the only reason it got detected was due to the absurd head movements that only the Baritone bot could do that is very similar to Kill Aura.

## Settings
I hope in the near future there would be an option to make the head movements slower or to make it more human like where the head doesn't just "flick" so that it wouldn't trigger any anti-cheat.

## Context
This would make sure that Baritone wouldn't be flagged by any anti-cheat and become undetectable.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Existing issues are not undetectable, a quick search for e.g. "smooth" would have shown a list of existing duplicates.
If you play on a server like 2b2t you don't have to worry about being caught, because using Baritone is actually allowed there.

**Comment by ZacSharp** [comment]
Duplicate of #2034
