### ISSUE TITLE
Baritone only shows path when moving (fabric)

### ISSUE THREAD

**Issue by CigarClient** [cabaletta/baritone#4016]
When i try to use baritone's tunnel feature with a custom size, it does not show the path until it moves itself. Manual moving does not work. I have tried removing sodium, lithium and iris(the only 3 mods i have installed apart from baritone and fabric api), but this does not change anything. Setting goals and normal tunneling works fine.

**Comment by wagyourtail** [comment]
well. yeah. baritone doesn't start calculation unless it's unpaused.
working as intended.

**Comment by HungryMuttis** [comment]
> well. yeah. baritone doesn't start calculation unless it's unpaused. working as intended.

He means that when the baritone is working and mining the tunnel, it only renders goals, path, blocks to place etc. when it is walking.  Also, I do have the same issue myself. And it only renders normally when using the tunnel with only the depth set.
