### ISSUE TITLE
Kill Aura Anti-Cheat Flagging

### ISSUE THREAD

**Issue by TiredGreenify** [cabaletta/baritone#4018]
## What do you need help with?
I made an issue before this with a suggestion to make head movement smoother instead of "flicking", but someone closed it without reading my suggestion. Due to the absurd movement from the Baritone bot, the Anti-Cheat that a server I play on uses flags the head movement or "flicking" as kill aura. Is there anyway to disable the absurd head movement or any setting that might help and not let it be flag by this Anti-Cheat. Thanks

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
you mean #4013 ? read the comment and you know why it was closed.
also there is a height probability that a server with anti cheat doesnt permit the usage of baritone and you are in violation of that servers rules.

**Comment by TiredGreenify** [comment]
> you mean #4013 ? read the comment and you know why it was closed. also there is a height probability that a server with anti cheat doesnt permit the usage of baritone and you are in violation of that servers rules.

Technically, yea, but I was talking about it being flagged as Kill Aura mainly. I was asking if there was anyway to prevent it from being flagged as Kill Aura instead of just making the head movement smoother. 

Also, the server I play on strictly does not allow combat based hacks but nothing about movement or anything that is considered Baritone.

**Comment by ZacSharp** [comment]
Depends on what causes the flag. If you are using `BuilderProcess` and the problem is the rate of flicks between block placements you can turn up `rightClickSpeed` (it controls the amount of ticks to wait between clicks). In any other case (instamining blocks, normal walking, etc.) I'm not aware of a solution.

**Comment by TiredGreenify** [comment]
> Depends on what causes the flag. If you are using `BuilderProcess` and the problem is the rate of flicks between block placements you can turn up `rightClickSpeed` (it controls the amount of ticks to wait between clicks). In any other case (instamining blocks, normal walking, etc.) I'm not aware of a solution.

Thank you for responding, however I'm pretty sure it is due to the head movement that is similar to the kill aura head movement. and probably nothing to do with the blocks. Is there any settings that would allow me to change this?

**Comment by ZacSharp** [comment]
As I said, increasing the time between flicks in that specific case is the only setting I'm aware of.
