### ISSUE TITLE
pickaxe replenishing while tunneling

### ISSUE THREAD

**Issue by 3jq** [cabaletta/baritone#4026]
## What do you need help with?
i have a question:
is it possible to make baritone replenish pickaxes while its tunneling?
if yes, how?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
#autotool true
#allowInventory true

this will take new pickaxes from your inventory and put it on your hot bar.

what you cant do is to automatically go to a chest and get more pickaxes.

**Comment by 3jq** [comment]
thanks
