### ISSUE TITLE
Cannot setup

### ISSUE THREAD

**Issue by estella144** [cabaletta/baritone#4030]
## Some information
Operating system: macOS Monterey, version 12.2.1 (21D62)
Java version: 18.0.1.1
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used): None

## Exception, error, or logs
`no main manifest attribute, in baritone-standalone-1.10.1.jar`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Download `baritone-standalone-1.10.1.jar`
In Terminal, type `java -jar baritone-standalone-1.10.1.jar`

## Modified settings
To get the modified settings run `#modified` in-game
[None]

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have included the version of Minecraft I'm running, baritone's version, and Forge mods (if used).
- [x] I have included logs, exceptions, and/or steps to reproduce the issue.
- [x] I have not used any OwOs or UwUs in this issue.

## Note
Don't call me dumb as you did to the last issue like this

**Comment by wagyourtail** [comment]
Baritone does not include an installer. See https://github.com/cabaletta/baritone/blob/master/SETUP.md
