### ISSUE TITLE
Building for 1.20.1 locally

### ISSUE THREAD

**Issue by AdverseMiller** [cabaletta/baritone#4032]
I'm trying to build baritone for 1.20.1 on my system but am unable to. I get "error: release version 17 not supported" after running ./gradlew build

<details>
  <summary>Full Log</summary>
  

> Configure project :
Applying none run configs
Resolving mappings for COMBINED
found mappings for COMBINED: [INTERMEDIARY, MOJMAP, OFFICIAL]
No mod dependencies found, skipping.
No mod dependencies found, skipping.
No mod dependencies found, skipping.

> Configure project :fabric
Resolving mappings for COMBINED
found mappings for COMBINED: [INTERMEDIARY, MOJMAP, OFFICIAL]
Applying fabric run configs
No mod dependencies found, skipping.
No mod dependencies found, skipping.
No mod dependencies found, skipping.
Getting minecraft with mapping CLIENT:INTERMEDIARY
Getting minecraft with mapping SERVER:INTERMEDIARY

> Configure project :forge
Selected FG3
Resolving mappings for COMBINED
found mappings for COMBINED: [INTERMEDIARY, MOJMAP, SEARGE, OFFICIAL]
Applying forge run configs
No mod dependencies found, skipping.
No mod dependencies found, skipping.
No mod dependencies found, skipping.
Getting minecraft with mapping COMBINED:MOJMAP
Merging client and server jars...
transforming minecraft jar for FG3
Applying ATs [META-INF/accesstransformer.cfg]
Getting minecraft with mapping COMBINED:MOJMAP

> Configure project :tweaker
Applying none run configs
Resolving mappings for COMBINED
found mappings for COMBINED: [INTERMEDIARY, MOJMAP, OFFICIAL]
No mod dependencies found, skipping.
No mod dependencies found, skipping.
No mod dependencies found, skipping.

> Task :compileApiJava FAILED
Getting minecraft with mapping COMBINED:MOJMAP
Getting minecraft with mapping COMBINED:MOJMAP

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileApiJava'.
> error: release version 17 not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
3 actionable tasks: 1 executed, 2 up-to-date
</details>

I cloned the '1.20.1' branch of this repo and changed my java install with 'archlinux-java'. I even changed JAVA_HOME to /usr/lib/jvm/java-17-openjdk and the issue still persists, any ideas?
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
I get this error when using java 8, so are you sure that you're using the correct java version?

**Comment by Kurainu** [comment]
Have you tried to use JDK 17/SDK? 
I use IntellJ IDEA and use amazon-corretto-17.0.8.1 (Downloaded Through IntelliJ) and i can build it with that version.

I can also Build the 1.20.1 Version using this Command Line and setting the gradle.java.home specifically to the 17 JDK without that Parameter it doesnt work 
`gradlew build -Dorg.gradle.java.home="C:\Users\kuraa\.jdks\corretto-17.0.8.1"`

**Comment by Booogyboooo** [comment]
What ide are you using?
