### ISSUE TITLE
Baritone wont place blocks with #litematica

### ISSUE THREAD

**Issue by Technoviking78** [cabaletta/baritone#4035]
## Some information
Operating system: windows 11
Java version: build 1.8.0_371-b11
Minecraft version: 1.20.1
Baritone version: baritone-api-fabric
Other mods (if used): meteor litematica

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/` [latest.log](https://github.com/cabaletta/baritone/files/11918603/latest.log)

Mac: `/Library/Application\ [Support/minecraft/logs/`

## How to reproduce
Use any litematica schematic which has oriented objects and use #litematica it will then place all blocks but bug out when it has to place things like torches redstone ect
## Modified settings
To get the modified settings run `#modified` in game allowinventory true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone cannot properly handle rotatable blocks (if it happens to stand in the right position it can usually place them, but it can't walk to that position on its own) and anything involving moving parts (e.g. restone turning on or off or changing shape) is won't work either.
You best bet is either excluding the problematic blocks from being built (with `buildSkipBlocks`) or letting Baritone place them in any direction (`buildIgnoreDirection`). If you really want to try building redstone you can also use `buildIgnoreProperties` to ignore the shape and power level of redstone components.
