### ISSUE TITLE
buildOnlySelection not working with Litematica

### ISSUE THREAD

**Issue by FurtherV** [cabaletta/baritone#4038]
## Some information
Operating system: Windows 10
Java version: Eclipse Adoptium 17.0.3
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used):  Litematica 0.15.0, MaLiLib 0.16.0

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/11929795/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
- Create some litematica schematic
- Load it and create a placement
- Select a section of it
- Set `buildOnlySelection` to true
- Start the litematica build process

Result: The build process starts at the first layer and builds outside of the selected area.

## Modified settings
To get the modified settings run `#modified` in game
- buildInLayers
- buildOnlySelection

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and fabric mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
this is already fixed on the main dev branche but the fixed version has not yet propagated to newer versions.

**Comment by FurtherV** [comment]
> this is already fixed on the main dev branche but the fixed version has not yet propagated to newer versions.

I see. I suppose until then tech savvy users can attempt build the updated version themselves :D
