### ISSUE TITLE
quarry/flatten [mine out area]

### ISSUE THREAD

**Issue by ThatGrzegorzB** [cabaletta/baritone#404]
.mine's big brother
TLDR: you would specify 2 corners and optionally a list of blocks that baritone is allowed to mine
.quarry x y z x y z block_a block_b etc

**Comment by leijurv** [comment]
Literally exists, .b cleararea, and I guess you could use the blocktoavoidmining setting to only mine out some of the area

**Comment by Zackaria2601** [comment]
i tried @cleararea and then i put the other corners coords but it just unable to parse

**Comment by Elenterius** [comment]
@Zackaria2601 
Actually there is currently a parsing bug. You have to remove the whitespace between cleararea and the next following value. --> e.g.: #cleararea1057 5 6603

@leijurv 
Also as a side note, in my opinion the cleararea command doesn't do quarring. At least not in the "correct/efficient" way . The bot has a strong drive to mine downwards first, which results in it mining a 5x5 hole till the bottom. It clears the bottom part and then it mines the rest while pathing upwards. 
![2019-09-08_18 20 29](https://user-images.githubusercontent.com/6061273/64491439-d8f6de80-d268-11e9-9d64-01462edd886f.png)

**Comment by Graicc** [comment]
This would be super jankey but couldn't you build an empty schematic from to to bottem to get the normal looking quarry?

**Comment by Zackaria2601** [comment]
whats a whitespace and how do i remove it

**Comment by Elenterius** [comment]
@Zackaria 
cleararea X Y Z -----------------> clearareaX Y Z
example:
cleararea 1057 5 6603  ----> cleararea1057 5 6603

**Comment by dalegendarybobbie** [comment]
when I do cleararea baritone says command does not exist

**Comment by 99marvel** [comment]
If anyone is looking for answers in this thread as I was, the current version of Baritone behaves correctly with the proper settings. 
For digging a quarry in the normal way a player would:
set BuildInLayers True
set layerOrder True      (inverts layer order to top down)

Make a selection & sel ClearArea

I belive most clients will use either "#set [setting] [true/false]" or ".b set [setting] [true/false]"

**Comment by ataniii** [comment]
when ever i do .b sel ca it says layer 0 1 2 3 done building, but it doesent do anything

**Comment by clepdn** [comment]
> when I do cleararea baritone says command does not exist

it is now #sel cleararea apparently
