### ISSUE TITLE
[QOL PLEASE] More QoL features to Lists

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#4045]
## Allow to use blocklists in Lists, so you can add multiple blocks at the cost of one tag

**so, instead of:**
`#set blocksToAvoidBreaking oak_sign,spruce_sign... etc`
**you can just do:**
`#set blocksToAvoidBreaking minecraft:all_signs,minecraft:flowers... etc`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
Duplicate of #1089
