### ISSUE TITLE
Support Vulkan

### ISSUE THREAD

**Issue by CormacZ** [cabaletta/baritone#4049]
## Describe your suggestion
There is a mod called Vulkan and I wonder if you can support Vulkan Rendering.

## Context
More support on more Rendering.

**Comment by ZeroMemes** [comment]
Should be possible if all OpenGL references are replaced with the game's renderer.

**Comment by ZeroMemes** [comment]
Nevermind, `DEBUG_LINES` usage needs to be replaced with `LINES`.

**Comment by ZeroMemes** [comment]
Resolved by #4059
