### ISSUE TITLE
its blacklisted

### ISSUE THREAD

**Issue by kizuru22** [cabaletta/baritone#4051]
why does baritone break blocks i put in blacklist

**Comment by rycbar0** [comment]
https://github.com/cabaletta/baritone/blob/master/USAGE.md

**Comment by ZacSharp** [comment]
Which blacklist do you mean and under which circumstances does it break the block?

**Comment by kizuru22** [comment]
the blacklist with blocks it shouldt break and i put stripped_dark_oak_wood and stripped_spruce_wood but it still breaks it and the command #blacklist doesent work

**Comment by rycbar0** [comment]
user error
if you read the https://github.com/cabaletta/baritone/blob/master/USAGE.md you will see that #blacklist does something else.
what you want is #setting blocksToDisallowBreaking stripped_dark_oak_wood,stripped_spruce_wood
