### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Klormm** [cabaletta/baritone#4052]
(sorry for english) i set a litematica schematic and when i run #litematica code its says missing items, when i search the error some pages says write something like allowinventroyexisting true but i cant change it and i realised i cant change any options ? can someone help me ?

**Comment by rycbar0** [comment]
to check the value of a setting or if it is a on/off setting toggling said setting you can use #<settingname>

missing item error can happen if
a) you dont have the nescesairy items
b) the schematic wants a block that cant be placed with a item (examples: farmland, half eaten cake, redstone repeater with delay)
c) baritone cant figure out how to place the block to produce the correct result (examples: logs, stairs, chests) (if baritone stands ate the wrong position he could place the block but it would be in the wrong orientation)

to solve a: get the items if you have them in your main inventory make sure that you have #allowInventory true
to solve b: add the block to the #buildSkipBlocks setting (example: #buildSkipBlocks farmland,cake,repeater )
to solve c:
- try moving the player position
- set #buildIgnoreDirection true
-  same as solution b

**Comment by Klormm** [comment]
yeah i solved it now, looks like its about water logged stairs, and farmlands so i skipped 2 of them and it started thanks

**Comment by Klormm** [comment]
@rycbar0 
![image](https://github.com/cabaletta/baritone/assets/120004428/a739abe3-aa72-440c-85de-cbd00586d2b4)
can u explain this ?

**Comment by rycbar0** [comment]
what version of baritone are you using maybe that setting doesnt exist in the version you are using

**Comment by Klormm** [comment]
am playing at 1.19.2 thank you. can it be older or newer versions ? (and i can see it in the #set part

**Comment by Klormm** [comment]
> 

i did it cause i only want to learn what means expected a valid value

**Comment by ZacSharp** [comment]
`buildIgnoreDirection`, `buildIgnoreProperties` and `buildSkipBlocks` all exist in all Baritone releases for Minecraft 1.19+
As Flappy said the problem is that you have to use `true` not `True` as the value.
