### ISSUE TITLE
Large mapart/skyart issue with rendering?

### ISSUE THREAD

**Issue by FracturedZen** [cabaletta/baritone#4061]
## What do you need help with?
so I have a huge skyart i am making at build height. it seems that it is constantly trying to pathfind somewhere but generally doesnt go anywhere. for example its about 1kblocks x 1kblocks sky art. only using 1 block type for the art. what I don't understand is that it works randomly farther from the origin point I go. it's not crashing or anything unless I use mapartmode. then it crashes my game. just wondering if im missing something? i've tried selecting an area and enabling build in selected area and it does the same thing.

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Can you perhaps share the log file or crashreport? The [bug report template](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=Please+add+a+brief+but+descriptive+title) is a good guide on what information might be helpful.

**Comment by FracturedZen** [comment]
[debug.log](https://github.com/cabaletta/baritone/files/12115546/debug.log)
the latest log was too big to upload so i removed the last 70k lines or so. 
[18:49:40] [Render thread/INFO]: [STDOUT]: Column 0,5 has no blocks, but it's apparently map art? wtf
[18:49:40] [Render thread/INFO]: [STDOUT]: Letting it be whatever
it just does that till like 73k
[latest.log](https://github.com/cabaletta/baritone/files/12115556/latest.log)

But the main thing is that when i run it it just keeps trying to pathfind constantly. ive been able to get it to work kinda if i go away from the origin where no blocks have been placed.

## Some information
Operating system: win10
Java version: latest
Minecraft version: 1.19.4
Baritone version: whatever meteor uses
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
loading the almost 3k x 3k schematic with mapartmode


## Modified settings
To get the modified settings run `#modified` in game
too many to put here manually.

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by FracturedZen** [comment]
> Can you perhaps share the log file or crashreport? The [bug report template](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=Please+add+a+brief+but+descriptive+title) is a good guide on what information might be helpful.

replied above meant to reply to you. sorry

**Comment by ZacSharp** [comment]
Is your schematic actually mostly empty and contains just a few spaced out subregions?
And did your game actually crash or did it "just" freeze? If it actually crashed I'd like to see the part of the log after the thousands of similar lines / the part where the exception is.

**Comment by FracturedZen** [comment]
> 

it froze and went unresponsize and i would close it and the launcher would say it crashed. there is a lot of empty space, but it has 3.1million obsidian blocks. there was nothing after what i removed from the log im pretty sure. and that was just like i said the iteration count going up

**Comment by ZacSharp** [comment]
That's exactly what I expected. The code in `MapArtSchematic` was written with the expectation that there is a block in your schematic in every xz column so it logs a warning if there is an empty column. Your schematic has so many empty columns that it doesn't finish printing warnings within reasonable time. (The launcher can't distinguish between a game crash and you killing the game and just assumes it's always a crash)
If you select an area with only very little empty columns it should work.
You also might want to disable `distanceTrim` when building such huge schematics.

**Comment by ZacSharp** [comment]
> If you select an area with only very little empty columns it should work.

Forget about that. `mapArtMode` is applied before `buildOnlySelection`.
You'll have to cut your schematic into contiguous pieces.

**Comment by FracturedZen** [comment]
ah i was afraid that was gonna be how to fix it. dang. thanks for looking into it

**Comment by ZacSharp** [comment]
`MapArtSchematic` no longer writes a line of output per empty column so this should be fixed now.
