### ISSUE TITLE
#farm fails on elytra branch

### ISSUE THREAD

**Issue by Calemplayzs** [cabaletta/baritone#4071]
Operating system:Windows 10
Java version: 1.8.0_372
Minecraft version: 1.12.2
Baritone version: elytra-1.2.17
Other mods at the time: CookieClient-1.01-release, kamiblue-2.04.21-3c581c22b, Minebot-v1.12.2, OptiFine_1.12.2_HD_U_G5, salhack-github-2.05-release, Catalyst-1.10.4-shadow

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows: `%appdata%/.minecraft/logs/` I'll recreate the log if necessary but I have been playing with other mods so it might be different

## How to reproduce
Build and use elytra branch, go near crops do '#farm' some will get farmed then baritone gets stuck

## Modified settings
To get the modified settings run `#modified` in game
I believe "#autoelytrajump true"

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by babbaj** [comment]
![image](https://github.com/cabaletta/baritone/assets/12820770/d1813446-4d5c-4cb8-ae5e-10dbb470a933)
sussy

this is probably broken in master because this code hasn't been touched in the elytra branch

**Comment by ZacSharp** [comment]
Can you please
1. Verify this happens on master as well
2. If it does, try whether https://github.com/cabaletta/baritone/pull/3944 fixes it (after disabling `scanAsynchronously`)?

**Comment by Calemplayzs** [comment]
> Can you please
> 
> 1. Verify this happens on master as well
> 2. If it does, try whether [Allow blocking main for scanning #3944](https://github.com/cabaletta/baritone/pull/3944) fixes it (after disabling `scanAsynchronously`)?

Not sure if that was meant for me but this does not happen on master, and to be more specific it'll farm most of the wheat wont replant about half and then say farm failed

**Comment by ZacSharp** [comment]
Yes, I meant you.
Just noticed you didn't provide any logs so we don't even know whether the exception babbj showed is actually what happens for you. Can you please provide a log?

**Comment by Calemplayzs** [comment]
yup i'll put the mods back in and have you a log in about 10 mins from this being posted

**Comment by Calemplayzs** [comment]
[Uploading latest.log…]()

I believe this is which one you wanted

**Comment by Calemplayzs** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/12176559/latest.log)

I think I did this correctly so here you go

**Comment by ZacSharp** [comment]
The expected exception is nowhere to be seen (and sadly no other related exception either) so I'd say the next step is trying if it happens without the other mods and if not, which of them is causing the problem.

**Comment by Calemplayzs** [comment]
alright thanks for the help

**Comment by Calemplayzs** [comment]
without any mods and the elytra branch #farm still doesn't break or replant all crops

**Comment by ZacSharp** [comment]
This was probably fixed in #4145 or #4157
