### ISSUE TITLE
Couldn't throw away rubbish automatically while mining 

### ISSUE THREAD

**Issue by Angelenx** [cabaletta/baritone#4074]
## Some information
Operating system:Windows 11
Java version:20
Minecraft version:1.20.1
Baritone version:1.10.1
Other mods (if used): 
wurst
fabric-api-0.86.1+1.20.1

## Exception, error or logs
None

## How to reproduce
Couldn't throw away rubbish automatically while mining 

## Modified settings
Using default setting

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Flappy25** [comment]
I don't think it's supposed to do that

**Comment by ZacSharp** [comment]
> I don't think it's supposed to do that

Exactly that.

If you want AutoEject you'll need an extra mod to do that.
