### ISSUE TITLE
Can I use a specified item when using auto farm

### ISSUE THREAD

**Issue by KADONISS** [cabaletta/baritone#4079]
## What do you need help with?
I want to use auto farm with an specified item in my sever but when i use auto farm it change to no hand. thank you.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you disable `autoTool` it will stop switching item to break blocks. This also means it won't switch back after placing a plant though.
