### ISSUE TITLE
[Enhancement] build-break preference

### ISSUE THREAD

**Issue by abrown4912** [cabaletta/baritone#408]
the ability to tell baritone to technically allow breaking but to do building if possible and visa versa (for the conservation of materials &&|| tools)

**Comment by leijurv** [comment]
You can do this with the penalty system. You'll want to modify two settings, specifically you'll want to decrease `blockPlacementPenalty` and increase `blockBreakAdditionalPenalty` by a bit until the balancing of when to place and when to break is to your satisfaction. See https://baritone.leijurv.com/baritone/api/Settings.html#field.detail

If you want to disable breaking or placing entirely, use the `allowBreak` and `allowPlace` settings.
