### ISSUE TITLE
Access denied baritone api

### ISSUE THREAD

**Issue by SKempiak** [cabaletta/baritone#4082]
I am trying to port a mod to a newer version so I tried to add a newer version of baritone-unoptimized-fabric but it wouldn't let me saying I need to sign into jitpack. Here is my gradle:

		modImplementation "com.github.cabaletta:baritone-api-fabric:1.10.1"

is this the correct implementation?

**Comment by wagyourtail** [comment]
Thats not the right jitpack artifact. try
`com.github.cabaletta.baritone:baritone-fabric:v1.10.1`

**Comment by samus114** [comment]
Is that for the api as well?
