### ISSUE TITLE
Standalone Baritone on Forge shows target, does not show route and does not move.

### ISSUE THREAD

**Issue by chaytt** [cabaletta/baritone#4083]
## Some information
Operating system: Windows 11
Java version: jdk-17
Minecraft version: v1.19.4
Baritone version: Forge v1.9.3
Other mods (if used): n/a

## Exception, error or logs
No exception nor error given; simply doesn't work.
[latest.log](https://github.com/cabaletta/baritone/files/12217746/latest.log)

## How to reproduce
Launch game on Forge 1.19.4 w/ Baritone mod installed, run any command that would cause the player to move, player does not move.

Target to move to is shown.

## Modified settings
none

**Comment by ZacSharp** [comment]
You didn't run any command that would cause the player to move.
`#thisway` and `#goal` set a goal without starting movement. You have to use `#path` to do that.

**Comment by ZacSharp** [comment]
`#goto` is the same as `#goal` followed by `#path`
