### ISSUE TITLE
How to disable baritone?

### ISSUE THREAD

**Issue by Keffori** [cabaletta/baritone#4091]
How to disable baritone? Not like #stop, disable it without deleting the mod, like it's just will don't work, and commands will don't work too, they will just be send to chat.

**Comment by rycbar0** [comment]
i dont understand a word. if you don't want baritone don't install it. if you want to disable a specific thing pls write a comprehensible sentence.

**Comment by fmcserver** [comment]
> i dont understand a word. if you don't want baritone don't install it. if you want to disable a specific thing pls write a comprehensible sentence.

sorry another account its me, i want to disable baritone for some minutes in game then enable it again, just to dont get banned on server

**Comment by fmcserver** [comment]
like, wurst have "disable wurst" in statistics in game pause menu

**Comment by ZacSharp** [comment]
If you want to avoid a ban just don't use Baritone.
