### ISSUE TITLE
PleBaritone Bot goes Underground

### ISSUE THREAD

**Issue by Lauchking123** [cabaletta/baritone#4095]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Hi. Im having Problem with my Baritone bot. It creates a path that goes underground for no reason if it goes a longerpath. I dont like it because its damaging my pickaxe. 
![2023-08-13_12 41 58](https://github.com/cabaletta/baritone/assets/121630821/fca4bbec-a37b-41ea-bfdb-9ad7549a46b9)
![2023-08-13_12 42 16](https://github.com/cabaletta/baritone/assets/121630821/3364d998-9f36-4f27-a55b-80bbd454fd8a)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Lauchking123** [comment]
Idk if this is an issue

**Comment by Lauchking123** [comment]
I have Baritone version 1.8.4

**Comment by lokzz** [comment]
if your command doesnt need baritone breaking any blocks, you can use `#allowbreak false` to make it path without planning to break blocks.

**Comment by ZacSharp** [comment]
What did you change between the first and second screenshot to make it take the better path?

**Comment by Lauchking123** [comment]
> What did you change between the first and second screenshot to make it take the better path?

I came from like 100 blocks away and its doing this everytime i travel further away. But when i make stop and ask the ai to walk to the same position it generste orher/better pathes not underground

**Comment by Lauchking123** [comment]
> if your command doesnt need baritone breaking any blocks, you can use `#allowbreak false` to make it path without planning to break blocks.

But its annoying when it need to farm something when I use farm (im lazy)

**Comment by ZacSharp** [comment]
So it generates a different path depending on whether that last part is in render distance? This could be related to caching (Is this the first time you entered the area? Are you on a multi world server?) or maybe it's [y simplification](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/api/java/baritone/api/Settings.java#L552) + an incomplete path (when it plans on digging through the terrain, does the path already reach the goal or is the path completed later when you are closer to the goal?).

**Comment by Lauchking123** [comment]
> So it generates a different path depending on whether that last part is in render distance? This could be related to caching (Is this the first time you entered the area? Are you on a multi world server?) or maybe it's [y simplification](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/api/java/baritone/api/Settings.java#L552) + an incomplete path (when it plans on digging through the terrain, does the path already reach the goal or is the path completed later when you are closer to the goal?).

I made chat debug on and it's an path in loaded chunks. What does y Simplification do?

**Comment by Lauchking123** [comment]
> So it generates a different path depending on whether that last part is in render distance? This could be related to caching (Is this the first time you entered the area? Are you on a multi world server?) or maybe it's [y simplification](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/api/java/baritone/api/Settings.java#L552) + an incomplete path (when it plans on digging through the terrain, does the path already reach the goal or is the path completed later when you are closer to the goal?).

I am the way very much but wvrytime it want to get in the Mountain. It's an single world server. And evrzyime the game loads new chunk in the server the ai generates new paths.

**Comment by ZacSharp** [comment]
> What does y Simplification do?

It turns x,y,z goals into x,z goals when you are far away (i.e. if the goal is outside render distance). There's no point in getting to the correct height of there's still a couple hundred blocks of horizontal distance.

Anyway, if you are using minecraft 1.19.4 can you please try again using the latest CI build? Leijurv did a change which should have a massive positive impact on path calculation beyond render distance. (retrieving blocks from cache was offset by the minimum y coordinate of the world)
