### ISSUE TITLE
Prevent #litematica from breaking blocks?

### ISSUE THREAD

**Issue by kisenera** [cabaletta/baritone#4102]
I only want to add to a schematic in the world, not remove blocks, even if those blocks are "incorrect". However, even with #allowBreak set to false, #litematica still tries to destroy blocks.

**Comment by ZacSharp** [comment]
[`buildIgnoreExisting`](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/api/java/baritone/api/Settings.java#L298C35-L298C54) should do the trick
