### ISSUE TITLE
Baritone gets stuck breaking blocks on 2b

### ISSUE THREAD

**Issue by SupremeSaucer811** [cabaletta/baritone#4110]
## Some information
Operating system: Debian 12
Java version: 17
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used): rusherhack+, meteor, and future

## Exception, error or logs
its probably not an issue with the log it failed to break blocks sometimes

## How to reproduce
do #mine any_block
also #sel ca
anything to do with breaking blocks
(having haste will make it work like normal and resolve this issue)

## Modified settings
there are no modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Nekiplay** [comment]
try break range 3

**Comment by SupremeSaucer811** [comment]
it has been set to 2.7 before I had the issue and its not to do with the distance

**Comment by SupremeSaucer811** [comment]
SOLUTION: anyone having this issue it is future making the issue and you need to turn speed mine on and set it to 0

**Comment by beckadamtheinventor** [comment]
I've been having this same issue on Meteor. It seems to only happen with shovel-able blocks. Happens a lot less if you enable anti-afk strafing.
Edit: (On Meteor) Turning on speed mine Normal mode with a modifier of 0 stops block breaking entirely.
