### ISSUE TITLE
1.20.1 Elytra beta test error

### ISSUE THREAD

**Issue by Nekiplay** [cabaletta/baritone#4112]
## Some information
Operating system: Windows 10 x64
Java version: 17.0.8 64bit
Minecraft version: 1.20.1 Fabric
Baritone version: Elytra beta test 1.20.1 Fabric
Other mods (if used): 
        - appleskin 2.5.0+mc1.20
	- baritone 1.2.19-572-gfa28a56e
	- betterf3 7.0.1
	- betterstats 2.10.3+1.20.1
	- blackout 1.0.1
	- chesttracker 1.1.22
	- clientcommands 2.8.3
	- cloth-config 11.1.106
	- controlling 12.0.2
	- detailab 2.6.3+1.20.1-fabric
	- draggable_lists 1.0.1
	- emi 1.0.19+1.20.1+fabric
	- emi_loot 0.6.5+1.20.1
	- emojitype 2.2.0+1.20
	- fabric-api 0.87.0+1.20.1
	- fabricloader 0.14.22
	- ferritecore 6.0.0
	- forgeconfigapiport 8.0.0
	- higtools 2.7
	- immediatelyfast 1.1.28+1.20.1
	- indium 1.0.25+mc1.20.1
	- java 17
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.1
	- memoryleakfix 1.1.1
	- meteor-client 0.5.4-1907
	- meteor-rejects 0.3
	- meteor-villager-roller 1.4.2+mc1.20.1-rev.ac89621
	- meteorplus 1.20.1-for-dev-build
	- minecraft 1.20.1
	- modelfix 1.14
	- modmenu 7.2.1
	- moonlight 1.20-2.8.4
	- no-telemetry 1.7.0
	- reeses-sodium-options 1.6.4+mc1.20.1-build.94
	- rrls 1.20.1-3.1.1-fabric
	- searchables 1.0.1
	- sodium 0.5.2
	- sodium-extra 0.5.1+mc1.20.1-build.112
	- starlight 1.1.2+fabric.dbc156f
	- viafabricplus 2.8.2
	- xaerominimap 23.6.2
	- xaeroplus 1.20.1
	- xaeros-map-chest-tracker-integration 1.0.1
	- xaeroworldmap 1.33.0

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/12411185/latest.log)

## How to reproduce
Use: #mine minecraft:diamond_ore minecraft:deepslate_diamond_ore

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by babbaj** [comment]
this is probably the same problem as #4071

**Comment by suda-code** [comment]
How to download 1 20 1 elytra beta? I don't even have a download

**Comment by Nekiplay** [comment]
this problem seems to occur when #mine is y below 0.

**Comment by Nekiplay** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/12806582/latest.log)
log on 1.20.1 Fabric unoptimized

**Comment by Nekiplay** [comment]
Solved in #4145
