### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by pizzav-xyz** [cabaletta/baritone#4113]
## Some information
Operating system: windows 11
Java version: 1.17
Minecraft version: 1.20
Baritone version: elytra
Other mods (if used): Mods:
  [✔] baritone-api-fabric-1.20.1-elytra-beta-v1
  [✔] fabric-api-0.87.0+1.20.1
  [✔] indium-1.0.25+mc1.20.1
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] reeses_sodium_options-1.6.4+mc1.20.1-build.94
  [✔] sodium-extra-0.5.1+mc1.20.1-build.112
  [✔] sodium-fabric-mc1.20.1-0.5.2
  [✔] viafabricplus-2.8.2
  [✔] Wurst-Client-v7.35.2-MC1.20

## Exception, error or logs
[Please find your `latest.log` or `debug.log` in this folder and attach it to the issue](https://mclo.gs/qPWQgYd)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
1. make the bot do something like #litematica or #sel shell block 
2. run #buildInLayers

## Modified settings
[Baritone] > modified [Baritone] All modified settings:
[Baritone) allowBreak (Boolean)
[Baritone] blockReachDistance (Float)
[Baritone] maxFallHeightBucket (Integer)
[Baritone] maxFall HeightNoWater (Integer) [Baritone]
[Baritone]
[Baritone]
[Baritone
[Baritone]

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
and what is the issue?

**Comment by pizzav-xyz** [comment]
> and what is the issue?

it crash

**Comment by rycbar0** [comment]
do you have a game/crash log?

**Comment by pizzav-xyz** [comment]
> do you have a game/crash log?

yes, its in the Exception, error or logs section

**Comment by pizzav-xyz** [comment]
@rycbar0 you need to click it

**Comment by rycbar0** [comment]
thanks i found it. i first missed it because you linked it behind the default text where to find it.

i think the line that throws the error is this one but i cant figure out what "\<parameter2\>" is because the function there doesnt have any parameters
https://github.com/cabaletta/baritone/blob/3873aae7100926913536ec5f9c03f8f88e8d5f65/src/main/java/baritone/process/BuilderProcess.java#L1079

**Comment by ZacSharp** [comment]
My bet:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.getBlock()" because "second" is null
    at baritone.process.BuilderProcess.sameBlockState(BuilderProcess.java:1021)
    at baritone.process.BuilderProcess.containsBlockState(BuilderProcess.java:1043) (inlined into the lambda method)
    at baritone.process.BuilderProcess.lambdaInAssemble(BuilderProcess.java:713)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at baritone.process.BuilderProcess.assemble(BuilderProcess.java:710)
    at baritone.process.BuilderProcess.onTick(BuilderProcess.java:594 or 596)
   ...
```
When enabling `buildInLayers` the schematic shrinks so positions in `incorrectPositions` can become out of bounds which in turn causes `bcc.getSchematic` to return `null` [here](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/main/java/baritone/process/BuilderProcess.java#L713C26-L713C26) and then things blow up [here](https://github.com/cabaletta/baritone/blob/2cd5c6b0af433b6c4dfef17b3000834c630551ba/src/main/java/baritone/process/BuilderProcess.java#L1021C17-L1021C17)
