### ISSUE TITLE
smooth rotate

### ISSUE THREAD

**Issue by pizzav-xyz** [cabaletta/baritone#4115]
## Describe your suggestion
make single action smooth rotate

## Settings
wether its on or not and speed

## Context
better bypass

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by pizzav-xyz** [comment]
i know this is very hard but i know the baritone team is capable to do it

**Comment by scorbett123** [comment]
Duplicate of #2034

**Comment by pizzav-xyz** [comment]
> Duplicate of #2034

it still didnt get added 2 years later tho
