### ISSUE TITLE
schulker box

### ISSUE THREAD

**Issue by pizzav-xyz** [cabaletta/baritone#4117]
## Describe your suggestion
Make #litematica get blocks from shulker boxes

## Settings
toggle

## Context
big builds dont fit in inventroy at once

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Not exactly a duplicate but mostly covered by #605

**Comment by pizzav-xyz** [comment]
> Not exactly a duplicate but mostly covered by #605

@ZacSharp 4 years ago ...
