### ISSUE TITLE
My .goto x y z command is broken I think (Fixed it)

### ISSUE THREAD

**Issue by flofik228** [cabaletta/baritone#4118]
So I type .goto x y z ( coords where I need to go) and then when my baritone has choice to go safely or just jump 100 blocks down it jumps down 100 blocks and kills me ( it does not jump in water but just jumps down). How do I fix so it does not do kamikaze mode.

**Comment by rycbar0** [comment]
#set reset all
or if you want to be less radical check what settings you have on a non default value with #modified and then reset the setting you want to reset with #set reset <settingname>

**Comment by flofik228** [comment]
Is this gonna affect any cheat clients or only baritone?

**Comment by flofik228** [comment]
Oml I found this modfication. It was FallHeightwithNowater and it was set to 255 (idk why I didn't set it) but it fixed it. Thanks!
