### ISSUE TITLE
baritone allow to break ore blocks from a distance

### ISSUE THREAD

**Issue by TheCrazyBossMan** [cabaletta/baritone#4120]
hi i am on a hypixel skyblock and ores after u mined them change in to bedrock for x ammount of seconds so sel is no options so i use the standard mine redstone_ore but now it go's against the ore_block it wants to mine is there a way so it stays in 1 spot and mines what it can reach from that spot ?

like a stayhere or lockmovement command ?
because walking to the ore everytime is extremly inefficient compared to standing still and mining infront of u

**Comment by wagyourtail** [comment]
dont use baritone

**Comment by TheCrazyBossMan** [comment]
> dont use baritone

do u recommend something that mines ores for me while standing still
