### ISSUE TITLE
I turn on AutoWalk/goto and it stops  for some reason

### ISSUE THREAD

**Issue by flofik228** [cabaletta/baritone#4121]
I turn on AutoWalk/goto and it plays some kind of sound and stops. What could that mean?

**Comment by flofik228** [comment]
Update: I did #set reset all. Now it does not make sound but still stops

**Comment by ZacSharp** [comment]
Baritone itself does not have AutoWalk and does not play sounds so I assume you are using some client and the problem you describe is a problem with that client and not with Baritone.
