### ISSUE TITLE
need help to understand the auto miner

### ISSUE THREAD

**Issue by emoshua** [cabaletta/baritone#4126]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

i need help to understand the auto miner in the nether for netherite, because now it just stops before an ancient debris and dosnt mine it, i just wanted to know if i coulg get him to mine the ancient debris.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Did you modify any settings? Do you have a diamond or netherrite pickaxe in your hotbar?

**Comment by emoshua** [comment]
i didnt modify any setting and i just have a netherrite pickaxe in my hotbar

**Comment by ZacSharp** [comment]
Then I'm out of ideas.
