### ISSUE TITLE
backfill command

### ISSUE THREAD

**Issue by xEulyses** [cabaletta/baritone#4127]
please add the deepslate block in the backfill command, i already turned on the backfill command but it doesn't work when i have deepslate block but in other blocks it works need this deepslate to be added cause i mine deepslate diamonds so deepslate is my backfiller but it won't work in baritone version 1.10.1

**Comment by ZacSharp** [comment]
`BackfillProcess` uses whatever is configured in `#set acceptableThrowawayItems` which defaults to `dirt,cobblestone,netherrack,stone`. You can add deepslate using `#set acceptableThrowawayItems dirt,cobblestone,netherrack,stone,deepslate`.
Tip: if you use tab completion for the setting value it will always complete the old value so you don't have to type out the whole list

**Comment by Advik-B** [comment]
why dont u close this, its been more than a month
edit: closed

**Comment by IronAndSnow3983** [comment]
Enter the command `#set acceptableThrowawayItems`, in general, you will see some block's ids behind what you just entered, all you need to do is add the block's ids that you want the robot use it to fill the tunnel during mining into those block's ids. For an example, if you want the robot use granite, you just need to add `minecraft:granite`.
