### ISSUE TITLE
Looking for a command similar to "disconnectOnArrival", but for auto building

### ISSUE THREAD

**Issue by ValThoMa** [cabaletta/baritone#4128]
## What do you need help with?
I'm trying to build a rather large structure using a schem file and baritone's auto build, and I'm intending to afk from time to time. I'm looking for some command that will allow me to disconnect after finishing the build/running out of building materials. Any ideas?

**Comment by ZacSharp** [comment]
As far as I know Baritone does not have any feature you could use here so you'll need to write some code (modify Baritone, external script / mod)
