### ISSUE TITLE
Automaticly close the doors after went through

### ISSUE THREAD

**Issue by szdytom** [cabaletta/baritone#4129]
## Describe your suggestion

Baritone can open doors and fence gates on its path, I want it to be able to close those opened doors after going through

## Settings

set `requireCloseDoor` to enable automatic door closing

## Context

Here is my use case:
I have divided my base into several areas using fences to prevent mob entering it. As I used baritone pathing between those areas, it always left those fence gates open.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #389
