### ISSUE TITLE
I don't know how to make it work pls heeelp me

### ISSUE THREAD

**Issue by Yoplani** [cabaletta/baritone#4130]
Hey, I discovered Baritone and i love it, so I tried using it during the day but it just dont work.
I'm trying to use it on a 1.12.2 pixelmon server, but when i enter a command like #mine iron_ore  or .b it just writes it in the chat like if i had no mod.

Information i can give: the server is using a launcher
I have maybe an idea why it dont work
![image](https://github.com/cabaletta/baritone/assets/144838558/55ab459e-5bc3-4e9a-85bf-a644d10cd54a)
I dont know which one i have to choose.

Thank you to all the people who will deign to read and maybe help me.

**Comment by Lauchking123** [comment]
Try the standalone version and look if you have the right intance launched with the right version downloaded

**Comment by ZacSharp** [comment]
> I have maybe an idea why it dont work

Would be nice if you shared it.

> I dont know which one i have to choose.

Assuming you are using Forge you need either baritone-api-forge or baritone-standalone-forge. The latter has slightly better performance but cannot be used by other mods and since you tried using `.b` to send commands chances are you are also using a client with Baritone integration, which would mean you need the baritone-api-forge file.

**Comment by Yoplani** [comment]
> > I have maybe an idea why it dont work
> 
> Would be nice if you shared it.
> 
> > I dont know which one i have to choose.
> 
> Assuming you are using Forge you need either baritone-api-forge or baritone-standalone-forge. The latter has slightly better performance but cannot be used by other mods and since you tried using `.b` to send commands chances are you are also using a client with Baritone integration, which would mean you need the baritone-api-forge file.

Ok i tried the two but still dont work, and the idea i was talking about was "I dont know which one i have to choose"

**Comment by Yoplani** [comment]
> Try the standalone version and look if you have the right intance launched with the right version downloaded

Dont work too

**Comment by ClickClack7531** [comment]
When it comes to Minecraft mods, you need to have the mod installed on the server as well as your client. If the Baritone files are in the server, copy them to your Minecraft client's mod folder,

**Comment by Yoplani** [comment]
> When it comes to Minecraft mods, you need to have the mod installed on the server as well as your client. If the Baritone files are in the server, copy them to your Minecraft client's mod folder,

The mod is not in the server and i dont need it to be in ? i use other mod which are not in the server and it work perfectly

**Comment by ZacSharp** [comment]
@ClickClack7531 Baritone is a client-only mod. Installing it on servers is not recommended and may crash your server. (never tried it so I don't know what happens)
