### ISSUE TITLE
buildIgnoreExisting - not working and seems unreferenced

### ISSUE THREAD

**Issue by seanytak** [cabaletta/baritone#4141]
## What do you need help with?
Filing as question instead of bug as this may just be newbie error. When setting `buildIgnoreExisting` to `true`, while building a schematic via `#build <name>.schem` it will still break non-air blocks within the schematic region. Upon looking at the code, I don't see this setting actually being referenced anywhere - not sure if I'm missing it, this setting is not currently working as intended, or was to be deprecated / deleted at some point and not documented as such.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Merge mistake (and not by me, yay)
Happened in a32811942e801222c593b24c4dee9fbaa2caa3d5 / #3238.
