### ISSUE TITLE
<已解决>error at argument #2 expected w

### ISSUE THREAD

**Issue by shundebo** [cabaletta/baritone#4143]
1.20.1
fabric
mods:wurst

#mine iron_ore 3
error at argument #2 expected w
#mine minecraft:iron_ore 3
error at argument #2 expected w

https://github.com/cabaletta/baritone/releases/tag/v1.10.1

**Comment by ZacSharp** [comment]
The amount has to be written before the ore/ores so it's `#mine 3 iron_ore`

**Comment by shundebo** [comment]
> The amount has to be written before the ore/ores so it's `#mine 3 iron_ore`

thank
