### ISSUE TITLE
#pathThroughCachedOnly not working

### ISSUE THREAD

**Issue by Nekiplay** [cabaletta/baritone#4147]
## Some information
Operating system: Windows 10 x64
Java version: 17.0.8 64bit
Minecraft version: 1.20.1 Fabric
Baritone version: #4145 
Other mods (if used):  Sodium, Meteor Client, Meteor Plus, XaeroWorld Map, Xaero Minimap

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/12830218/latest.log)

## How to reproduce
[Video](https://youtu.be/qzn6pqz-oOA)

## Modified settings
blockReachDistance 4.5
pathingMapLoadFactor 0.75
primaryTimeoutMS 500
failureTimeoutMS 2000
planAheadPrimaryTimeoutMS 4000
planAheadFailureTimeoutMS 5000
slowPathTimeoutMS 40000
toastTimer 5000
pathRenderLineWidthPixels 5.0
goalRenderLineWidthPixels 3.0
freeLook false
elytraFreeLook false
pathThroughCachedOnly true
cachedChunksOpacity 0.5
mineDropLoiterDurationMSThanksLouca 250
followOffsetDirection 0.0
colorCurrentPath 255,0,0
colorNextPath 255,0,255
colorBlocksToBreak 255,0,0
colorBlocksToPlace 0,255,0
colorBlocksToWalkInto 255,0,255
colorBestPathSoFar 0,0,255
colorMostRecentConsidered 0,255,255
colorGoalBox 0,255,0
colorInvertedGoalBox 255,0,0
colorSelection 0,255,255
colorSelectionPos1 0,0,0
colorSelectionPos2 255,200,0
selectionOpacity 0.5
selectionLineWidth 2.0
elytraNetherSeed 1141873160
elytraTimeBetweenCacheCullSecs 180

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Can you please try this again without mods (and maybe less changed settings)?
When I tried `pathThroughCachedOnly` on the commit right before the one you used it worked and #4145 should not affect pathing.
