### ISSUE TITLE
對於在使用自動建造時使用蘑菇柄為材料後出現的異常

### ISSUE THREAD

**Issue by sunflower519sf** [cabaletta/baritone#4149]
## Describe your suggestion
可以在建造相關的設定中加入可以設定方塊在放置後狀態出現錯誤是可以忽略的功能，並不是放置錯誤的方塊，而是某些方塊放置後會有不同的狀態(像蘑菇柄)

## Settings
加入可以定義忽略放置錯誤狀態的方塊

## Context
我在建築時常常遇到他不斷放置方塊後因為方塊錯誤而將方塊破壞，又再一次的放置和破壞，有時還會因為這樣停止，所以希望加入此功能。我有嘗試過 buildSkipBlocks 但此功能並不會放置方塊，會直接忽略此方塊；還有 buildIgnoreDirection 也不行，因為她還是會把方塊破壞，但應該可以將蘑菇柄加入這個設定中，我認為他跟陶瓦是相同的

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Can you please translate your text to english?

There is `buildIgnoreProperties` to ignore arbitrary block properties. To use it you can look up the name of the property using the f3 debug overlay (look at the block and it's properties will be shown at the bottom right) and then use `#buildIgnoreProperties prop1,prop2,...`. (note that there are no spaces between the names)

**Comment by sunflower519sf** [comment]
[https://youtu.be/wdCZqOsbtQ0](url)
This is a video of my actual test
But this does not really achieve the goal
It still won't place the blocks correctly
It’s not that it was placed incorrectly and it won’t be removed.
There will be a video of the test later
I think it's because of the way it's placed that his status is incorrect.

**Comment by ZacSharp** [comment]
`buildIgnoreProperties` is a list of block properties, not block names, so in your case you need `#buildIgnoreProperties north,south,west,east`.

**Comment by sunflower519sf** [comment]
[https://youtu.be/3_-GNruUiGE](url)
After I use this function
I found it could be used for my purpose
But he will continue to terminate
I wonder if there is a setting error?

**Comment by zPeanut** [comment]
a

**Comment by ZacSharp** [comment]
Not sure why this issue showed up as active again, though I looked at your video again and noticed you added `down` to `buildIgnoreProperties` but not `up`.
