### ISSUE TITLE
search bugged 

### ISSUE THREAD

**Issue by niggish** [cabaletta/baritone#415]
https://streamable.com/ach2p

- Impact Version: `4.6 for 1.13.2`
- Using Optifine? `yes`
- Using LiteLoader? `no`
- Enabled mods: `search`
- Operating System: `windows 10 64-bit`

**Comment by usereewrjrjeejr** [comment]
Use the impact github

**Comment by LeafHacker** [comment]
[ImpactDevelopment/ImpactClient](/ImpactDevelopment/ImpactClient/issues)
