### ISSUE TITLE
Barritone Wont Mine

### ISSUE THREAD

**Issue by MCBEModder2020** [cabaletta/baritone#4152]
## Some information
Operating system: mac m1 ventura
Java version: graalvm 17 22.3.1
Minecraft version:
Baritone version: meteor-0.5.5-1944
Other mods (if used): meteor client, lots but they dont interfere with baritone

## Exception, error or logs
(paste.gg)[https://paste.gg/p/anonymous/3516e236a5f840b0890a4fa4c2924ed1]

## How to reproduce
i just mined deepslate diamond ore
heres the only weird bit of my cfg
```
cachedChunksExpirySeconds 1
cachedChunksOpacity 0.0
```

## Modified settings
il attatch later

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I am using a dev build
- [x] I am using meteor client
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
Duplicate #4145
