### ISSUE TITLE
#mine, then any ore, it just goes past it then walks around, i turned legitmine and allowonlyexposed false both stiull does that

### ISSUE THREAD

**Issue by deedeedoes** [cabaletta/baritone#4156]
#mine, then any ore, it just goes past it then walks around, i turned legitmine and allowonlyexposed false both stiull does that

**Comment by deedeedoes** [comment]
also i get the red message
![Screenshot_5103](https://github.com/cabaletta/baritone/assets/148301260/8d605c42-aef2-4d3c-af6c-7031f18b97ba)

**Comment by wagyourtail** [comment]
looks like duplicate #4145 (#4112)

**Comment by MrBeast661** [comment]
![zgrib](https://github.com/cabaletta/baritone/assets/148687602/ff21b50c-e8c5-497e-86a5-bf64f147ab81)
Same problem

**Comment by MrBeast661** [comment]
![2023-10-22_12 48 34](https://github.com/cabaletta/baritone/assets/148687602/443a3797-bfa4-4abe-bb8c-3c75e294623e)
