### ISSUE TITLE
baritone litematica question

### ISSUE THREAD

**Issue by TheSrBig** [cabaletta/baritone#4161]
I want to build a schematic, but I don't want baritone to break things that shouldn't be in the schematic, I mean I want it to build nothing else, but for example if there is a block far from the schematic, I don't want it to go for it, I mean, I just want it to build it, unless it interferes a block with something.

**Comment by ZacSharp** [comment]
I'm not quite sure what you mean. There is `buildIgnoreExisting` which makes Baritone ignore wrong blocks and there is `buildSkipBlocks` to completely remove certain blocks from your schematic.
`buildIgnoreExisting` ~is currently broken on 1.17+ (see #4158) though if it were working it would~ causes Baritone to only consider breaking wrong blocks if they are in it's way.
`buildSkipBlocks` is a list of blocks which will essentially become holes in your schematic and Baritone will accept anything in their place. If you put air in that list Baritone will only care about the non-air blocks of your schematic.
