### ISSUE TITLE
error when trying to get diamonds with #mine command level -56 mc 1.20.2

### ISSUE THREAD

**Issue by kubaaa203** [cabaletta/baritone#4162]
## Some information
Operating system: Windows 10 
Java version: jdk-17
Minecraft version: 1.20.2
Baritone version: how can I check?
Other mods (if used): fabric api || iris || meteor client || meteor plus || sodium || viafabricplus

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/13061551/latest.log)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Go to level -53 underground mine a bit and use the command "#mine minecraft:diamond_ore"

## Modified settings
To get the modified settings run `#modified` in game
![vaizdas_2023-10-21_220231978](https://github.com/cabaletta/baritone/assets/86421878/4aa23470-0772-4d6e-9e04-3fafc8e4d3b8)
![vaizdas_2023-10-21_220248797](https://github.com/cabaletta/baritone/assets/86421878/e299cd59-b232-4631-9611-6567bc382214)
![vaizdas_2023-10-21_220304013](https://github.com/cabaletta/baritone/assets/86421878/20266a4b-bcb2-47c1-aecf-b8dd8ca9b781)
![vaizdas_2023-10-21_220345827](https://github.com/cabaletta/baritone/assets/86421878/4e1d4d16-b094-4c85-89a7-f28ca963ab7a)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's o

r UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #4112

**Comment by kubaaa203** [comment]
> duplicate #4112

I don't have a "fasterworldscanner.java" file how do I get it?
