### ISSUE TITLE
Unable to find mod files after building it

### ISSUE THREAD

**Issue by DrPHDCat** [cabaletta/baritone#4163]
## Some information
Operating system: Windows 10
Java version: jdk8u392-b08
Minecraft version: 1.20.2
Baritone version: ?

Unable to find the mod files after building, I have checked the entire baritone folder

Other mods (if used): building

## Exception, error or logs
[gradlewout.txt](https://github.com/cabaletta/baritone/files/13062750/gradlewout.txt)

## How to reproduce
run gradlew in the command line in the folder

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
check `dist/` also based on your logs, you arent doing `gradlew build`

**Comment by DrPHDCat** [comment]
> check `dist/` also based on your logs, you arent doing `gradlew build`

yeah doing gradlew build did it
