### ISSUE TITLE
Add Voyager and MineDojo Integration

### ISSUE THREAD

**Issue by VincentCCandela** [cabaletta/baritone#4165]
## Introduction

Voyager: https://voyager.minedojo.org/

MineDojo: https://minedojo.org/

I think the capabilities of both speak for themselves. Baritone is wonderful as a hard-wired algorithm, but it is time that we move beyond the world of cold-wired algorithms to more dynamic and powerful AI systems.

## Context

Installing these systems is incredibly different because the authors of this code did a poor job of maintaining the usability of their code, so an integration would be incredibly beneficial in saving time for users and allow users to use these tools in conjunction with more conventional Minecraft utilities.

## Details
They are both slightly different, so I recommend either added both separately or adding some combination of the two. To note, Voyager needs a GPT3.5 or GPT4 API to run, so it can be expensive to use, but is much more powerful that just MineDojo. However, for simpler tasks, I think that MineDojo is sufficient. Therefore, both should be added to best meet the needs of players

**Comment by scorbett123** [comment]
I think this would be better as a standalone mod, not integrated into baritone. So I'm closing this as out of scope for baritone.
