### ISSUE TITLE
Baritone does not break blocks / does not replace them

### ISSUE THREAD

**Issue by KiritoBlu** [cabaletta/baritone#4166]
Good morning everyone, 

I admit I'm a little embarrassed to ask this question here, but after hours of searching and trying around in Minecraft on my own, I can't get any further. 

I have a flat area of X blocks in Minecraft. This is made of glass. The glass should be replaced with obsidian. With Baritone 1.12 and Schematica, I simply placed a schematic with the corresponding blocks on the glass and he removed the blocks he thought were "wrong" and placed the correct ones. In this case obsidian. I have now tried this with Litematica. When I load the schematic with Litematica and do #litematica, my avatar does not move. I have set BreakBlock to true and IgnoringBlocks to false. 

I have looked through the settings but have not found anything.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Which version of Minecraft / Baritone / Litematica are you using?
If you are using one of the newer versions of Litematica for 1.12 (and possibly for newer versions) chances are you are using a post-refactor version which won't work with Baritone (@rycbar0 or did it not break?)

**Comment by KiritoBlu** [comment]
I am playing Minecraft  Fabricloader 1.20.1(using Mods for 1.20)
Litematica, Baritone and so on are all on the latest version, as far as i can tell. 
Screen from the 1.20 Mods: https://ibb.co/b5h2m1h


Maybe mentioning the 1.12 Version cost some confusion. I did not use Baritone since 1.12 - so i am/was not sure, if i tried it correctly.

**Comment by ZacSharp** [comment]
Litematica 1.20.1-0.15.0 seems to be a pre-rewrite version (there is a pre-rewrite/fabric/1.20.x branch and no other 1.20.x branch) so it should be compatible.

**Comment by ZacSharp** [comment]
To avoid a bunch of "did you/it do x/y" questions, can you please provide a log (and maybe a video)?

**Comment by KiritoBlu** [comment]
Here is the Video: https://youtu.be/O74cb1-AvFk - Video neeeds a few minutes to be HD quality
I do not play 1.12 Minecraft anymore, so i cannot show how it did work before. I use .b schem and baritone started to place and break blocks like it needs.  But i am not sure, if maybe that was due to the impact client, i used on the same time. 

Back to "todays problem" i am looking for a way for him to break the glass and place obsidian instead
BreakfromAbove is on true - if needed

As far as for the log: Which one would be needed

**Comment by ZacSharp** [comment]
From the video it looks like you shouldn't be using Baritone on this server :disappointed: and like the blocks are unsupported, which Baritone should be able to break with `breakFromAbove` enabled and `goalBreakFromAbove` enabled so it can walk onto neighboring blocks rather than next to the target block.

> As far as for the log: Which one would be needed

The "latest.log" file. It's (zipped and) overwritten every time you start Minecraft so you have to make sure you get it before starting Minecraft the next time.

**Comment by KiritoBlu** [comment]
i am not sure, if the server is denying it. Placing on the same level as the avatar works: https://youtu.be/2tWzrFVJyKw
Seems like he has an issue with anything "below" him. 

Not sure which one, but i added all 3 of them
[2023-10-26-3.log.gz](https://github.com/cabaletta/baritone/files/13185027/2023-10-26-3.log.gz)
[2023-10-26-4.log.gz](https://github.com/cabaletta/baritone/files/13185028/2023-10-26-4.log.gz)
[latest.log](https://github.com/cabaletta/baritone/files/13185029/latest.log)

**Comment by KiritoBlu** [comment]
https://youtu.be/M0Rk1FFxF1M - uploading / HD in Progress - should be done in 10 minutes
Another video - showing that replacing works, as far as it is on the same level as me, and not below the avat/minecraft figure

**Comment by ZacSharp** [comment]
Seems to work if you enable `breakFromAbove` (might have to enable `goalBreakFromAbove` as well)

https://github.com/cabaletta/baritone/assets/68165024/3f7d4fb3-abee-41ce-b8f4-de996dc42046
