### ISSUE TITLE
How to make baritone mine blocks with specific block state?

### ISSUE THREAD

**Issue by Realdoby** [cabaletta/baritone#4175]
Is there a way for baritone to mine blocks with specific block states for example a stair facing north or chest facing west or a noteblock having a specific instrument and note

**Comment by ZacSharp** [comment]
You should be able to use the vanilla `block[property=value]` syntax both for `#mine` and `#sel replace`

**Comment by Realdoby** [comment]
> You should be able to use the vanilla `block[property=value]` syntax both for `#mine` and `#sel replace`

there is a server that uses noteblocks as custom blocks so i want to mine a custom ore. It uses noteblock with the instrument and note 15 can you tell me how to make it mine it?

**Comment by Realdoby** [comment]
#mine stone_stairs[facing=north] this doesn't work

**Comment by ZacSharp** [comment]
If you are on a post-flattening version it should be e.g. `#mine note_block[instrument=xylophone,note=12]`

**Comment by Realdoby** [comment]
what is post-flattening

**Comment by ZacSharp** [comment]
Versions 1.13+. The primary change to blockstates was removing the metadata byte (flattening it into the blockstate id), but Mojang also changed a lot of block ids on that occasion so e.g. noteblocks have different ids in 1.12- and 1.13+.

**Comment by pronery** [comment]
thank you so much for the info

**Comment by Realdoby** [comment]
I am on 1.19.2 

> If you are on a post-flattening version it should be e.g. `#mine note_block[instrument=xylophone,note=12]`
I am on 1.19.2  this is the error i get 
![image](https://github.com/cabaletta/baritone/assets/94699745/223f4cac-b1b7-4733-9471-7812df17db01)

**Comment by ZacSharp** [comment]
Then `note_block` should work.
![2023-11-16_23 19 07](https://github.com/cabaletta/baritone/assets/68165024/03443b4d-6a95-4419-9ccf-7f1a7424bb2e)
