### ISSUE TITLE
baritone error told me to put my log here so here it is

### ISSUE THREAD

**Issue by H4mburg3rDuD3** [cabaletta/baritone#4176]
## Some information
Operating system: windowa
Java version: latest
Minecraft version: 1.20.2
Baritone version: latest
Other mods (if used): fabric API, meteor client
[latest.log](https://github.com/cabaletta/baritone/files/13246775/latest.log)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I typed in the chat box ''#mine dimond_ore'' and baritone said
![image_2023-11-03_005221385](https://github.com/cabaletta/baritone/assets/149754487/0c6919fe-1429-42e1-80ce-6f7af81d4448)

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #4112
