### ISSUE TITLE
AutoTool Issue and Suggestion

### ISSUE THREAD

**Issue by Smurfylegacy** [cabaletta/baritone#418]
I noticed that when using the mine command it auto tools only to the right type of tool and ignores the fortune/silktouch enchantments. I tried using another mod which takes into account the enchantments and what block its mining(AutoSwitch+ThebombzenAPI) but it seems Baritone overrides it because when using the mine command it stops using the correct tools and just defaults to what baritone was doing before. I have AutoTool disable in Impact so I assume the mine command uses AutoTool by default to function.

Here is the link to the mods that allow proper Auto Tool and was wondering if there a way to enable compatibility between them. I guess the ability to enable or disable autotool within the mine command should allow this? 

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1278132-thebombzens-mods#ASBugReport

**Comment by ThebesAndSound** [comment]
So a setting that can disable baritone's autotool so you can use a more customisable autotool like the AutoSwitch mod.

**Comment by Smurfylegacy** [comment]
Yeah basically

**Comment by User-developer** [comment]
also auto tool auto mines leaves with sword -drains durabillity

**Comment by Wissmo** [comment]
Additionally, it should be checked whether a mob in the environment, if so the mob will be killed with a sword. Today I had problems exactly with that when I used the function cleararea and almost died several times.
What I also noticed, cleararea and water are not working with each other ^^

**Comment by guty-18** [comment]
Is there a setting to avoid tools braking on baritone?

**Comment by dominikaaaa** [comment]
It's called itemsaver

I can't believe all the children are :+1: to their own messages, knowing other people can see who added it

**Comment by ZacSharp** [comment]
This has been implemented in #1947 and should be closed.

Once you have a build that is made after #1947 was merged (currently only latest three 1.16 releases) you can use `#disableAutoTool` and `#assumeExternalAutotool`.
