### ISSUE TITLE
Auto mine can not find the mine

### ISSUE THREAD

**Issue by E0x72-21** [cabaletta/baritone#4185]
## Some information
Operating system: windows11
Java version: jdk17
Minecraft version: 1.20.1
Baritone version: 1.20.1-elytra-beta-v1
Other mods (if used): meteor-client-0.5.4-1917

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/13274162/latest.log)
## How to reproduce
strat auto mine (by using "#mine minecraft:deepslate_diamond_ore")
after a few minutes it says ”unavailable to find the path to (the block I've slected)“
then I run the command (#mine minecraft:deepslate_diamond_ore) again it says "An unhandled exption occurred......" and it let me run/dig around randomly

**Comment by wagyourtail** [comment]
Duplicate #4112
