### ISSUE TITLE
Give AI self defense

### ISSUE THREAD

**Issue by CaszGamerMD** [cabaletta/baritone#4192]
## Describe your suggestion
self defense, when player takes damage it auto pauses current operation, switches to sword and kills local hostile mobs. after a few seconds of no damage received, auto resumes operation

## Settings
selfdefense true/false
SDautoresumeafter T/F
SDARTimer 3(seconds) or 60(ticks)

## Context
Baritone can protect its self from mobs, preventing death.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #866
