### ISSUE TITLE
baritone does not walk by itself

### ISSUE THREAD

**Issue by gAvAnAss** [cabaletta/baritone#4196]
## Some information
Operating system: windows 11
Java version: 8 update 381
Minecraft version: 1.20.1 fabric
Baritone version: 1.10.1
Other mods (if used): 
![image](https://github.com/cabaletta/baritone/assets/151372297/9f969d51-b746-454f-9e46-1d7fd689fb15)
![image](https://github.com/cabaletta/baritone/assets/151372297/ddda45ad-ef92-4a32-b72b-1797dba00732)

## Exception, error or logs
[launcher.log](https://github.com/cabaletta/baritone/files/13400193/launcher.log)

## How to reproduce
the baritone does not walk by himself. When writing the #mine command, I have to go to the right block myself. When writing the #goto command, the character just stands still and I can't control it (until I write the #stop command)

## Modified settings
![image](https://github.com/cabaletta/baritone/assets/151372297/83cc400b-e07d-4db4-861e-8ff47735bc20)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by gAvAnAss** [comment]
![image](https://github.com/cabaletta/baritone/assets/151372297/af5265a8-544d-4946-967a-9c27573e84d3)

**Comment by rycbar0** [comment]
Remove far sight

**Comment by TheophilosAnestidis** [comment]
![image](https://github.com/cabaletta/baritone/assets/103751275/166cd22e-7c8f-4384-883f-d162e188659a)

**Comment by gAvAnAss** [comment]
> Remove far sight

thank you. it helped
