### ISSUE TITLE
#mine doesnt work

### ISSUE THREAD

**Issue by felix25364** [cabaletta/baritone#4203]
## Some information
Operating system: Windows 11 Pro x64 22H2
Java version: 17.0.9 Eclipse Adoptium
Minecraft version: 1.20.2
Baritone version: 1.20.2-SNAPSHOT
Other mods (if used): Meteor Client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Just do #mine deepslate_diamond_ore
## Modified settings
To get the modified settings run `#modified` in game
 default Settings when Meteor is installed

## Final checklist
- [x] I know how to properly use check boxes 
-[ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[baritone.log](https://github.com/cabaletta/baritone/files/13443330/baritone.log)

**Comment by wagyourtail** [comment]
duplicate #4112
