### ISSUE TITLE
1.20.2 soon?

### ISSUE THREAD

**Issue by Crosshairs2** [cabaletta/baritone#4204]
When is 1.20.2 coming?

**Comment by ZacSharp** [comment]
Already done, it's just that releases tend to lag behind by a few weeks or even months.
If you want an up to date version have a look at the list of [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.20.2) (filtered to only show successful builds for 1.20.2). Select the topmost (newest) entry and download the artifact called "Artifacts" (the word appears twice, the second one is clickable). It's a zip containing the usual release files.

**Comment by TacoDark** [comment]
> Already done, it's just that releases tend to lag behind by a few weeks or even months. If you want an up to date version have a look at the list of [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.20.2) (filtered to only show successful builds for 1.20.2). Select the topmost (newest) entry and download the artifact called "Artifacts" (the word appears twice, the second one is clickable). It's a zip containing the usual release files.

Thank you my dude!

**Comment by HoratioGamer** [comment]
Meteor Client has produced a Baritone build for 1.20.2 that includes #elytra on their website https://www.meteorclient.com/.   Unlike nearly ever other mod, Meteor does not leave historical builds up.   They have therefore overrun the updating of a number of other mods, including the official release of Baritone 1.20.2, by a long shot.   Does this build they have published have the blessing of the Baritone developers, or, is there any reason you know of to wait for the official release of Baritone for 1.20.2 directly from Cabaletta ?

**Comment by ZacSharp** [comment]
What you use is up to you. As long as you don't expect support for random third party modifications (and trust whoever made the file) you are fine. Unlike AltoClef Meteor seems to be rather light on modifications so support shouldn't be a big problem, though if you care about performance you shouldn't use their version (they omit build-time optimization like done for the "baritone-unoptimized-*" release files).
I do not know of any reason to wait for an official release. Quite the opposite. Use [official CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apush) or the Meteor fork or custom builds, but don't wait a couple months for no reason.

For those wanting Baritone for 1.20.4: ~It's currently in pull request state  (#4214) and~ as for most prs automated builds [exist](https://github.com/cabaletta/baritone/pull/4214#issuecomment-1849119756).

EDIT: Baritone [1.10.2](https://github.com/cabaletta/baritone/releases/tag/v1.10.2) for Minecraft 1.20.3 and 1.20.4 was released.

**Comment by Bia951** [comment]
it's expired now😲
