### ISSUE TITLE
1.20.3?

### ISSUE THREAD

**Issue by Shxck5Hz** [cabaletta/baritone#4211]
is there a baritone for mc ver 1.20.3?

**Comment by MCBEModder2020** [comment]
[1.20.4 Build](https://github.com/cabaletta/baritone/actions/runs/7134142472)

**Comment by ZacSharp** [comment]
Baritone skipped version 1.20.3 entirely so no, there is not even code you could build yourself (though building the 1.20.4 code against mc 1.20.3 would probably work).

Why don't you just use 1.20.4 instead? It's almost the same, except it doesn't delete items in pots.

**Comment by ZacSharp** [comment]
#4214 now supports both 1.20.3 and 1.20.4
