### ISSUE TITLE
using #elytra crashing the game  

### ISSUE THREAD

**Issue by safder2000** [cabaletta/baritone#4215]
## Some information
Operating system: windows 11
Java version: openjdk 21 2023-09-19 LTS
Minecraft version: 1.20.2
Baritone version: 1.20.2 a fork by Meteor
Other mods (if used): Meteor, fabric api, 

## Exception, error or logs

![image](https://github.com/cabaletta/baritone/assets/107740161/424b980e-fa6b-41fe-b368-2337dbf0b188)

## How to reproduce
.goal 20 20 
.elytra

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Might be fixed by #4246. If you can reliably reproduce this, can you please try using a CI build from that pr?

**Comment by ZacSharp** [comment]
Should be fixed in #4252
