### ISSUE TITLE
Is there any way to make baritone not care about new blocks in the schematic?

### ISSUE THREAD

**Issue by DenouementEfflorescence** [cabaletta/baritone#4222]
Basically i want to make baritone build a schematic. but it keeps getting stuck and mining blocks i dont want it to since they arent in the schematic. is there a way to make baritone not care about blocks that exist in the world but not in the schematic?n

**Comment by ZacSharp** [comment]
You probably want `#set buildSkipBlocks air`. `buildSkipBlocks` is a comma separated list of names of blocks which will effectively become holes in the schematic.

**Comment by DenouementEfflorescence** [comment]
Thank you soooo much!!!! also is there a way to make the range of baritone shorter? to lets say 2 blocks? cuz it also gets stuck just placing blocks where it cant (according to the server) and i think a lower reach would fix that

**Comment by DenouementEfflorescence** [comment]
oh and also is there any way to stop baritone from bridging? cuz now baritones just building all over my build

**Comment by DenouementEfflorescence** [comment]
sorry for asking this many questions but is there a way to make baritone ignore fall damage? cuz i got a perk on that server so i do nt take falldamage

**Comment by ZacSharp** [comment]
* `blockReachDistance`
* `allowPlace`?
* `maxFallHeightNoWater`

Maybe have a look at [all the settings](https://github.com/cabaletta/baritone/blob/1.19.4/src/api/java/baritone/api/Settings.java)? (search is your friend)
