### ISSUE TITLE
1.20.4 WHEN

### ISSUE THREAD

**Issue by FrostyDevLOL** [cabaletta/baritone#4223]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
[Use search bar WHEN](https://github.com/cabaletta/baritone/pull/4214)

**Comment by FrostyDevLOL** [comment]
what

**Comment by ZacSharp** [comment]
Or #4204
