### ISSUE TITLE
when using the command #mine minecraft Not responding

### ISSUE THREAD

**Issue by Yuu-Sakuma** [cabaletta/baritone#4224]
- Minecraft 1.20.2 
- fabric lodaer 0.15.3 1.20.2
- Game using Memory 3-4gb highlighted 6gb ram

here are all the mods i use
![ppoop](https://github.com/cabaletta/baritone/assets/88208983/2a3d1f6a-79cb-42e0-bdc8-6fd434ae65a3)
when entering a command #mine minecraft:diamond_ore and if you press the space or write another ore so that the baritone digs, the game will freeze,the game freezes completely and only closing the game through the task manager will help you get out of it, and when you re-enter the world it’s better not to use the command at all because everything will freeze  In general,you can’t use the command you write any ore and everything freezes  You can’t write anything else and it doesn’t respond anymore, if you press space it will freeze, if you press enter it will also freeze,You can’t even figure out what the reason is. Minecraft doesn’t crash,it just freezes and that’s it.  help what’s the reason, please tell me

**Comment by ZacSharp** [comment]
Have you tried using less mods? If one of your other mods causes this it would be really helpful to know which one it is.

**Comment by Yuu-Sakuma** [comment]
> Вы пробовали использовать меньшее количество модов? Если один из ваших других модов вызывает это, было бы очень полезно знать, какой именно.

блин мне тоже интересно какой мод вызывает такие баги но блин, это все нужные для меня моды которые я использую, и перебирать это всё займёт какое-то количество времени и я сделал этот пост чтобы кто-нибудь разобрался, мало-ли кто-нибудь знает из за чего это, ладно в скором времени я разберусь и переберу всю свою сборку

**Comment by Yuu-Sakuma** [comment]
> Have you tried using less mods? If one of your other mods causes this it would be really helpful to know which one it is.

Hi,I found what kind of mod caused such bugs baritonewit, it was c2me

**Comment by ZacSharp** [comment]
Does this happen with just c2me without Baritone or are both needed?

**Comment by BobDotCom** [comment]
> Does this happen with just c2me without Baritone or are both needed?

Both are needed. The crash only occurs upon running the `#mine` command while C2ME is installed. I also opened an issue on C2ME because I'm not sure which mod is actually the root problem.
