### ISSUE TITLE
Baritone confuse between go up or break temporary block

### ISSUE THREAD

**Issue by BoNuong** [cabaletta/baritone#4227]
My baritone is confused between keep working or break temporary block because temporary block used like a stair to go up
Anyone have solution for it ?

**Comment by ZacSharp** [comment]
Sadly there is no good solution to this problem. You can try making Baritone ignore all blocks it's allowed to use as scaffolding or disallow placing temporary blocks.

**Comment by ZacSharp** [comment]
Building things in layers can also help for some schematics.
