### ISSUE TITLE
Is there a way to do #sel replace <block>,<block> <block> like WorldEdit?

### ISSUE THREAD

**Issue by synapt0** [cabaletta/baritone#4232]
I'm currently trying to mine out a mountain with the selection command but I can't seem to make it work.

The command I'm using: "#sel replace grass_block,dirt,stone air" but it doesn't seem to be a valid command

- [x] I know how to use checkboxes.
- [x] There are no OwO's or UwU's in this post.

**Comment by ZacSharp** [comment]
If you use spaces instead of commas it should work. (`#sel replace grass_block dirt stone air`)
