### ISSUE TITLE
Baritone Golems

### ISSUE THREAD

**Issue by HoodBlah** [cabaletta/baritone#4233]
## Describe your suggestion
Not a client side mod, but an addon mod that adds golems that you can command and program using baritones ai. For example; you can create a robot golem using copper blocks, create a remote item that you can bind to it, use the remote to type baritone command on it to make it work. 

## Settings
Probably a way to set home locations, storage, and mining areas so the robots arent going all over the place.

## Context
You can have many robots gathering many resources for you instead of botting yourself.

Finally, a mandatory UwU (My family is held hostage)

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by RealmKebab** [comment]
baritone isn't suppose to be used on the server-side since it's literally a pathfinding mod

**Comment by ZacSharp** [comment]
Baritone is a purely client side mod and as such cannot add things like entities or other game mechanics which require server side support and such features are far out of scope anyway. Baritone is meant and designed to control actual Minecraft clients.
