### ISSUE TITLE
Baritone not working in ATM9 server

### ISSUE THREAD

**Issue by SomeRandomUsern4m3** [cabaletta/baritone#4234]
It doesn't work on atm 9, it doesn't show the path that it will take, but when I type commands in the chat it will respond saying that it is going to do something. But it doesn't move

**Comment by pgkrol** [comment]
@SomeRandomUsern4m3 hiya! If it's still actual for you - try to delete Farsight mod (farsight-1.20.1-3.6.jar). It works for me on another mod pack.
upd: Farsight is only client-side mod

**Comment by ZacSharp** [comment]
Yes, farsight is incompatible due to changes they do to chunk management (see #3773)
