### ISSUE TITLE
Baritone crash ao entrar no jogo

### ISSUE THREAD

**Issue by uisFelipe** [cabaletta/baritone#4238]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
@uisFelipe can you please provide the log with the crash report?

**Comment by uisFelipe** [comment]
@ZacSharp então o meu Launcher não é o Launcher *OFICIAL* do Minecraft,como eu jogo apenas no celular eu uso o Foldcraft Launcher, um Launcher oferecido e criado aqui pelo Github, eu estava jogando na 1.20.1 com o mod Baritone e o Meteor Client.

Estava indo bem daí eu decidi trocar para a 1.20.4 e vi q o Github lançou o Baritone para o Minecraft 1.20.4 fui lá baixei coloquei o Meteor Client da 1.20.4 e meus outros mods q instalei na 1.20.1 porém tentei de tudooo mas toda vez ele crash, e isso só acontece na 1.20.4 porque na 1.20.1 dá certo não sei por isso acontece.

Mas tentar mandar um print ou algo do tipo aqui pra você
