### ISSUE TITLE
Baritone ignoring enderportals completly

### ISSUE THREAD

**Issue by m0reD3l1r1um** [cabaletta/baritone#4239]
## Describe your suggestion
Baritone should get a setting/option similar to #enterPortal with the tweak that it doesn't run through portals at all anymore

## Settings
Simply just #allowPortal false/true to change the path to go around the portal instead

## Context
A lot of servers (and some Mods) make you go through portals instantly instead of having the normal animation wobbeling around. This breaks baritone obv because its instantly ether in the nether or another world with the (for example) followed entity not existing anymore. Some servers also got world protect in other worlds which in case of a world change also breaks baritone. These problems are fixable if baritone doesn't go inside a portal even if there are no blocks behind it making the path take longer when going around 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any ""'s or ""'s in this issue.
- [x] I deleted the wierd animal things in the checkbox above

**Comment by ZacSharp** [comment]
Adding nether portals to `blocksToAvoid` should completely stop Baritone from walking through portals.

**Comment by m0reD3l1r1um** [comment]
In that case just obsidian or is netherportal in itself a block and if yes what would be the valid value?

I mean wouln't baritone still walk through the portal if i just avoid obsidian?

Edit: 
just found it. Id is:  nether_portal
and not netherportal as i initially thought

**Comment by m0reD3l1r1um** [comment]
answer to Problem:
- add netherportal per id to the blocks it should avoid
          #blocksToAvoid nether_portal

thx for the help Zac :)

**Comment by rahulcvwebsitehosting** [comment]
Fixed this in my fork — https://github.com/rahulcvwebsitehosting/baritone. Not PR'd upstream yet but it works if you need it now. Lmk if anything's off.
