### ISSUE TITLE
Baritone doesn't show up in forge mods

### ISSUE THREAD

**Issue by victor00100** [cabaletta/baritone#424]
Hello 
I am trying to use baritone in combination with futureclient and have installed forge, I put the baritone-standalone-forge-1.2.6.jar in the mods folder but it doesn't seem to show up, the other mod JourneyMap is showing in the mods. 
I am on version 12.2.2 and have tried different versions and also the api version.
What could be the problem for htis, do I need another forge version?

**Comment by leijurv** [comment]
This is a feature, it's probably installed. Try saying `#version` in chat to test

**Comment by victor00100** [comment]
okay yeah it's working, i was doing it with the .version command, thank you ery much sir!

**Comment by leijurv** [comment]
More info on usage and the `#` prefix is here https://github.com/cabaletta/baritone/blob/master/USAGE.md
