### ISSUE TITLE
Baritone doesent know buildinlayers

### ISSUE THREAD

**Issue by BorshikTheGreat** [cabaletta/baritone#4240]
For some reason(my best guess is me being on aristois or newest version) baritone doesent know the buildinlayers command

UwU
## Final checklist
- [x] I know how to properly use check boxes 
- [damnit] I have not used any OwO's or UwU's in this issue.
<img width="767" alt="Screenshot 2024-01-09 at 19 02 05" src="https://github.com/cabaletta/baritone/assets/156013900/35c8e7ff-a909-4e5c-a2f6-0ffe4f57c69e">

**Comment by BorshikTheGreat** [comment]
for some reason works only with @ symbol not .b

**Comment by ZacSharp** [comment]
Probably because Aristois (partially) parses the commands itself instead of forwarding everything after the ".b".
