### ISSUE TITLE
Come command not working with Freecam

### ISSUE THREAD

**Issue by GayBaboon** [cabaletta/baritone#4242]
## Some information
Operating system: MacOSx
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): Meteor client

## How to reproduce
1. Use Freecam in Meteor client and fly away from the player
2. Use the Come command
3. Baritone will path to where the player model is standing rather than where the Freecam is positioned

**Comment by wagyourtail** [comment]
then meteor's freecam is coded in an incompatible way, it's on their end to fix.
I'm aware of several compatible ones, such as https://github.com/wagyourtail/freecam and https://github.com/MinecraftFreecam/Freecam
