### ISSUE TITLE
mine command issue

### ISSUE THREAD

**Issue by kha0sk1ng** [cabaletta/baritone#4249]
Operating system: Windows 11
Java version: 17
Minecraft version: 1.20.2
Baritone version: 1.2.19-591
Other mods (if used): 
Sodium
Mod menu
Command macros
Iris

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/14001198/latest.log)

## How to reproduce
I ran the command #mine minecraft:diamond_ore minecraft:deepslate_diamond_ore

## Modified settings
No

**Comment by ZacSharp** [comment]
Duplicate of #4112

**Comment by ZacSharp** [comment]
Also don't use tlauncher.
