### ISSUE TITLE
Baratone crash on feather and vanilla

### ISSUE THREAD

**Issue by TherealONE12** [cabaletta/baritone#4250]
## Some information
Operating system:
Java version: java from the mc-launcher
Minecraft version:1.20.4
Baritone version: [v1.10.2](https://github.com/cabaletta/baritone/releases/tag/v1.10.2)
Other mods (if used): 

![image](https://github.com/cabaletta/baritone/assets/144170391/a3d1d2c7-9b08-43ff-bd04-592d3aa598c9)
![image](https://github.com/cabaletta/baritone/assets/144170391/3f2dd770-11bf-42c3-918f-3ee822a82f81)
![image](https://github.com/cabaletta/baritone/assets/144170391/9570ec87-be93-4fdc-862b-df9a2fc97886)
![image](https://github.com/cabaletta/baritone/assets/144170391/588e2f66-1485-4d0e-8d11-4a77f5fea681)
![image](https://github.com/cabaletta/baritone/assets/144170391/9735c62e-1f73-4243-8922-7c4cd9c0304b)
![image](https://github.com/cabaletta/baritone/assets/144170391/3ef15d96-0662-44b4-ae4f-0a371bee888d)

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/14002167/latest.log)

## How to reproduce

Download baratone and all other mods
run feather/Vanilla Launcher
Done

## Modified settings

Cant launch, there should be none thought

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
yeah. feather's incompatible. remove feather.
![image](https://github.com/cabaletta/baritone/assets/6234704/a3e6ba57-c4b7-479d-8e7a-0cb0a561d249)

**Comment by TherealONE12** [comment]
> yeah. feather's incompatible. remove feather. ![image](https://private-user-images.githubusercontent.com/6234704/298404349-a3e6ba57-c4b7-479d-8e7a-0cb0a561d249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzY1MzgsIm5iZiI6MTcwNTkzNjIzOCwicGF0aCI6Ii82MjM0NzA0LzI5ODQwNDM0OS1hM2U2YmE1Ny1jNGI3LTQ3OWQtOGU3YS0wY2IwYTU2MWQyNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTUxMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjJiMjU4YWJhOGVhYWFjZjk4ZjBkMTVkMzRmZDg3NGZhY2Q5YmYzNzdiNDI4MjFjZDFkNzdhMmViNDhkZDBiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ExeX55kspbFUuxOJHb-QSQ-yU_pkUqRCS0-Yk5jeqCA)

any way to bypass that? I kinda like feather...

**Comment by wagyourtail** [comment]
https://github.com/cabaletta/baritone/pull/4251
