### ISSUE TITLE
1.20.2?

### ISSUE THREAD

**Issue by cootshk** [cabaletta/baritone#4255]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
You have 1.20, 1.20.1, 1.20.3, and 1.20.4
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
just port 1.20.1 or .3 to .2
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
lots of mods still are on 1.20.2 and not .3 or .4
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by JustaSqu1d** [comment]
You can download the artifacts of the [1.20.2 version here](https://github.com/cabaletta/baritone/actions/runs/7433618915).

**Comment by Codingale** [comment]
You can also just use 1.20.4 and use ViaVersion to connect to 1.20.2 servers just fine, **note** as ZacSharp said, if you're using other mods it wouldn't work, but if it's just Baritone it'd work fine for now.

**Comment by ZacSharp** [comment]
Releases are usually only made for the latest minor version of each supported major version.
For now you can use the CI build @JustaSqu1d linked but once that's expired you will have to build Baritone yourself or try using a version not made for 1.20.2.

@Codingale that won't work if there are client mods which do not work on 1.20.4.

**Comment by yinyunze** [comment]
it's expired now 😲
