### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by wyr121** [cabaletta/baritone#4256]
## Some information
Operating system: window 11 22h2 22621.3007
Java version:java21
Minecraft version:1.20.1
Baritone version:baritone-standalone-forge-1.10.1
Other mods (if used): https://drive.google.com/file/d/1W5sZvkvZQmkUVembiEuIZtX7YEM_WLJ1/view?usp=sharing

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
![image](https://github.com/cabaletta/baritone/assets/72083417/be532b76-a5f9-4647-af70-bcfaf66f5105)
![image](https://github.com/cabaletta/baritone/assets/72083417/f607fbf1-acd7-4cd4-a9bd-739e45afdfa2)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game
![image](https://github.com/cabaletta/baritone/assets/72083417/65ae9b8e-c949-48ff-8035-33d75b753702)

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You are using a lot of mods so can you please try removing mods to find the minimum other mods required to cause the problem? You can find which mod(s) causes the problem like this:
1. Move half of the mods into a new folder, making sure mod dependencies are still met.
2. Test whether the problem still occurs. If it does, continue from step one.
3. If the problem doesn't occur anymore, swap the installed mods with the last set of mods you moved away, making sure dependencies are met.
4. Continue from step one.

If you have found a set of mods where removing any of them makes the problem disappear, please tell us which mods are causing the problem (no need to upload the mods themselves, names and versions are enough) and upload a log file.

**Comment by ZacSharp** [comment]
All successful CI builds on the 1.20.2 branch from newest to oldest:

Version number | Guessed version | Artifacts | Date
-|-|-|-
v1.2.19-599-ga223585d | v1.2.19-599-ga223585da | [still here](https://github.com/cabaletta/baritone/actions/runs/7433618915) | Jan 6, 2023
idk | v1.2.19-597-ga945cfaa3 | expired | Oct 31, 2023
idk | v1.2.19-591-g9bf890a7b | expired | Sep 28, 2023
idk | v1.2.19-588-ge1e620a0d | expired | Sep 28, 2023
idk | v1.2.19-588-gf5d15927d | expired | Sep 25, 2023

Apparently all places where the version number is used vanish once the artifact retention period is over so I locally generated the version numbers from the commit hash and as you can see in the first row that's not 100% precise. If one version string looks like another one but shorter it's probably the same version.

**Comment by ZacSharp** [comment]
Whoops wrong issue.
