### ISSUE TITLE
How do i fix this 

### ISSUE THREAD

**Issue by danzaa** [cabaletta/baritone#4257]
shakes violently and seems that it cant chose a block to brake

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

https://github.com/cabaletta/baritone/assets/79447744/0dd1f24f-9568-48d7-a752-419887cc446c

**Comment by ZacSharp** [comment]
Reminds me of #3994 so can you please test whether changing the mouse sensitivity to "SLOW" helps?
