### ISSUE TITLE
Official maven repository

### ISSUE THREAD

**Issue by 1zun4** [cabaletta/baritone#4266]
## What do you need help with?
Hi, I was wondering if Baritone has an official Maven repository that could be used for e.g:
`modImplementation` for development purposes or in my case for the [LiquidLauncher](https://github.com/CCBlueX/LiquidLauncher) which uses Maven for the recommended mod download system.

Since Baritone is not available on Modrinth or any other platform that allows Maven downloads, I have to upload it to my own server, which works fine, but is doomed to be less up to date.

I saw that you use jitpack, but the last build failed and I was unable to select the fabric artefact specifically. Also relying on jitpack to keep the files is another thing I do not want.

Thank you!

**Comment by ZacSharp** [comment]
There is https://github.com/ImpactDevelopment/maven/ where leijurv sometimes uploads artifacts, but as you can see it's not frequently updated. You can probably do better than that yourself.
