### ISSUE TITLE
Autoeat

### ISSUE THREAD

**Issue by Qasked** [cabaletta/baritone#4267]
## Describe your suggestion
While using mine command and/or determined to be boxed in and no mobs nearby and if hunger is low or health is low eat food

## Settings
autoeat on/off
addtioal settings:
only eat eat (ex: golden apple) when health is less that ()
eat (ex:beef) on/off
all on by deafalut except golden apple

## Context
It would make baritone not ever lose sprint , have the ability to heal, and not die of hunger

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Duplicate of #496
