### ISSUE TITLE
ClassCastException error its hard to fix ;(

### ISSUE THREAD

**Issue by bomboclot** [cabaletta/baritone#4271]
## Some information
Operating system: Linux (aarch64) version Android-12
Java version: 17.0.10-internal, N/A
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): accurateblockplacement: Accurate Block Placement 1.2.1
		armorchroma: Armor Chroma 1.2.6
		baritone: Baritone 1.10.2
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		bookshelf: Bookshelf 23.0.4
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		debugify: Debugify 1.20.4+1.0
		dynamic_fps: Dynamic FPS 3.3.3
		eatinganimationid: Eating Animation 1.20+1.9.5
		enchdesc: EnchantmentDescriptions 20.0.1
		fabric-api: Fabric API 0.96.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.0+32782cfd4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.0+d74054c14f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.10+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 6.0.3
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		gammautils: Gamma Utils 1.7.18
		iceberg: Iceberg 1.1.18
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.12.1
		memoryleakfix: Memory Leak Fix 1.1.5
		merchantmarkers: Merchant Markers 1.3.2
		minecraft: Minecraft 1.20.4
		modernfix: ModernFix 5.13.0+mc1.20.4
		modmenu: Mod Menu 9.0.0
		no_fog: No Fog 1.3.5+1.16.5-1.20.4
		notes: Notes 1.20.4-2.1.0-fabric
		removewardeneffect: Remove Warden Darkness 0.0.2-1.20.4
		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		tipsmod: Tips 15.0.2
		vmp: Very Many Players 0.2.0+beta.7.137
			com_ibm_async_asyncutil: asyncutil 0.1.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/14229278/latest.log)

[crash-2024-02-10_20.34.25-client.txt](https://github.com/cabaletta/baritone/files/14229280/crash-2024-02-10_20.34.25-client.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [✓ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ✓] I have included logs, exceptions and / or steps to reproduce the issue.
- [✓ ] I have not used any OwO's or UwU's in this issue.

**Comment by bomboclot** [comment]
it crashes

**Comment by ZacSharp** [comment]
Fixed by #4244

**Comment by bomboclot** [comment]
what to do @ZacSharp

**Comment by ZacSharp** [comment]
Go to #4280, scroll down, click on "Show all checks", then the "Details" button next to "Java CI with Gradle / build (pull_request)", then on "Summary" and then on "Artifacts".

https://github.com/cabaletta/baritone/assets/68165024/7a551ae1-d77f-477e-ae3e-0b83bd1e99fd
