### ISSUE TITLE
Disconnect when done with #goto

### ISSUE THREAD

**Issue by Plaaasma** [cabaletta/baritone#4273]
I would really like to see a "disconnect on discovery" settings for the #goto command. Often times I will set baritone to search for a block and then walk away from my computer and it would be really useful for it to just logout whenever it gets to the block so I don't have to worry about mobs/players killing me.

**Comment by wagyourtail** [comment]
https://github.com/cabaletta/baritone/blob/1.19.4/src/api/java/baritone/api/Settings.java#L1129
should work
