### ISSUE TITLE
#mine not working

### ISSUE THREAD

**Issue by PinotEtSyrah** [cabaletta/baritone#4275]
When executing the command "#mine minecraft:deepslate_diamond_ore" in Baritone, the scanning process does not detect any blocks, and Baritone proceeds in a straight line without adjusting its path
![2024-02-14_17 33 44](https://github.com/cabaletta/baritone/assets/143106895/3a2bbe09-9ef1-4d08-bf45-a1e93fa42aa5)

**Comment by ZacSharp** [comment]
Let me guess: There's a lot of `ArrayIndexOutOfBoundsException`s and those which have an error message say something about -1 (or another negative number) being out of bounds for an array of length 24.

This issue is known and was fixed in #4145

**Comment by ZacSharp** [comment]
Duplicate of #4112
