### ISSUE TITLE
you have to install impact otherwise there's no working version.

### ISSUE THREAD

**Issue by joerez** [cabaletta/baritone#428]

**Comment by babbaj** [comment]
🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍 🦍

**Comment by leijurv** [comment]
there is NO FORGE POSSIBLE IN BARITONE

**Comment by leijurv** [comment]
YOU CAN ONLY USE IMPACT NO OTHER CLIENTS

**Comment by joerez** [comment]
thats what i thought.
closing issue.

**Comment by babbaj** [comment]
BRAAAAAAAAAAAAAAAAAAAP

**Comment by usereewrjrjeejr** [comment]
🛥
