### ISSUE TITLE
I am asking for permision and help to modify baritone (what i mean in the description)

### ISSUE THREAD

**Issue by codedsword** [cabaletta/baritone#4297]
Hello fellow developers, we all love seeing unique Minecraft seeds, so i started my project for a seed finder. I have already written the Python part. Now all i need is your help to get a better understanding of what files i should be looking in for the purposes i will list in a bit, but first, this is how it will think. lets for example, look for seeds that have 2 or less endstone on the main island, so let's start showing you how my code thinks:
Hmm, the mod outputed that there are 3 or more endstone blocks on the main island, which is more than 2 so lets mark this seed as a fail (the opposite works too) 
So let's get into what i need:

**- I need permission to use your code for my own project**

**- I need help with modifying the mod to scan for a specific thing**

**- I need help with making the mod output what it has scanned.**

We can discuss if i have permission to post it publicly here on github.
for more info my E-mail is real.snx.yt@gmail.com

**Comment by ZacSharp** [comment]
If this is supposed to be a serious question I suggest you rewrite it in a way that does not look like spam.

**Comment by codedsword** [comment]
Bet!

Hi there, fellow programmers Since everyone enjoys viewing unusual Minecraft seeds, I started working on a seed search project. To begin demonstrating how my code functions, let's search for seeds on the main island that have two endstones or fewer:

Let's designate this seed as unsuccessful because the mod said that there are three or more endstone blocks on the main island, which is more than two.
Let's now discuss what I need:


**- In order to use your code for my own project, I need authorization.**

**- I need assistance changing the mod so that it searches for a particular object.**

**- I need assistance getting the mod to output the contents of its scan.**

My email address is real; please contact me for further information.snx.yt@gmail.com

Good enough?

**Comment by ZacSharp** [comment]
Well, at least now it doesn't read like AI generated gibberish anymore, though the questions still leave me under the impression that you don't really what Baritone is.

1. Look at the license. If that's not the permission you need you probably won't get them otherwise either.
2. & 3. Baritone doesn't do the kind of search you need and there is little connection between what a seedfinder does and what Baritone does.

**Comment by codedsword** [comment]
Well I am not an expert but where do u think I should head so I could procead with my project

**Comment by ZacSharp** [comment]
I'm not into seedfinding so I know neither people nor projects to point at, but I'm sure a search engine can easily find related projects.
