### ISSUE TITLE
Custom behavior is does not follow custom `onTick`

### ISSUE THREAD

**Issue by Redhawk18** [cabaletta/baritone#4299]
## What do you need help with?
Custom behavior does not use custom `onTick` causing my behavior to not work. 

https://github.com/Redhawk18/baritone/blob/50251723a331f6c6d5693ea14fb290cf592002a1/src/main/java/baritone/behavior/MapBuilderBehavior.java#L121

I was finally able to confirm this with the logging messages, This confuses me because why would something like this change? Any suggestions are welcomed 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There was a change to behavior registration and you missed [this line](https://github.com/Redhawk18/baritone/blob/50251723a331f6c6d5693ea14fb290cf592002a1/src/main/java/baritone/Baritone.java#L114) when updating so `MapBuilderBehavior` is constructed but never registered.

**Comment by Redhawk18** [comment]
Thank you, baritones project structure isnt the easiest to follow
