### ISSUE TITLE
Minecraft Carsh when using #mine in gravel

### ISSUE THREAD

**Issue by illusioncipher** [cabaletta/baritone#4301]
## Some information
Operating system:
Windows
Java version:
Latest
Minecraft version: 
Latest
Baritone version:
Latest
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
go near gravel wich has a ore after it and give command to mine it it will crash the game
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Are you perhaps below y level 0?
If not, can you please provide the log file?

**Comment by illusioncipher** [comment]
it was plugin error sorry
