### ISSUE TITLE
Game crashes when using #mine command

### ISSUE THREAD

**Issue by dxkyy** [cabaletta/baritone#4304]
## Some information
Operating system: Windows 11
Java version: 19.0.1
Minecraft version: 1.20.4
Baritone version: 1.20.2
Other mods (if used): 
- advancementinfo-1.20.4-fabric0.91.2-1.4.jar
- AmbientSounds_FABRIC_v5.3.5_mc1.20.4.jar
- appleskin-fabric-mc1.20.3-2.5.1.jar
- architectury-11.1.17-fabric.jar
- BadOptimizations-2.1.0.jar
- baritone-api-fabric-1.10.2.jar
- BetterAdvancements-Fabric-1.20.4-0.4.0.176.jar
- betterstats-3.9.3+fabric-1.20.4.jar
- bobby-5.1.0+mc1.20.4.jar
- Bookshelf-Fabric-1.20.4-23.0.6.jar
- c2me-fabric-mc1.20.4-0.2.0+alpha.11.58.jar
- cloth-config-13.0.121-fabric.jar
- Controlling-fabric-1.20.4-15.0.3.jar
- CreativeCore_FABRIC_v2.11.16_mc1.20.4.jar
- dynamic-fps-3.4.2+minecraft-1.20.4-fabric.jar
- EnchantmentDescriptions-Fabric-1.20.4-20.0.2.jar
- enhancedblockentities-0.9.1+1.20.2.jar
- entityculling-fabric-1.6.3.1-mc1.20.4.jar
- fabric-api-0.96.4+1.20.4.jar
- fallingleaves-1.15.4+1.20.1.jar
- ferritecore-6.0.3-fabric.jar
- firstperson-fabric-2.3.4-mc1.20.4.jar
- freecam-fabric-modrinth-1.2.3+1.20.4.jar
- ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
- indium-1.0.30+mc1.20.4.jar
- iris-mc1.20.4-1.6.17.jar
- Jade-1.20.4-fabric-13.3.1.jar.disabled
- lambdynamiclights-2.3.4+1.20.4.jar
- lithium-fabric-mc1.20.4-0.12.1.jar
- modernfix-fabric-5.14.0+mc1.20.4.jar
- modmenu-9.0.0.jar
- moreculling-1.20.4-0.22.1.jar
- MouseTweaks-fabric-mc1.20-2.25.jar
- mousewheelie-1.13.3+mc1.20.4.jar
- NoChatReports-FABRIC-1.20.4-v2.5.0.jar
- noisium-1.0.2+mc1.20.x.jar
- nvidium-0.2.6-beta.jar
- ok-boomer-0.1.3+1.20.2.jar
- owo-lib-0.12.5+1.20.3.jar
- pickupnotifications-1.7.0+1.20.3.jar
- replaymod-1.20.4-2.6.15.jar
- RoughlyEnoughItems-14.0.688-fabric.jar
- Searchables-fabric-1.20.4-1.0.6.jar
- shulkerboxtooltip-fabric-4.0.8+1.20.4.jar
- sodium-fabric-0.5.8+mc1.20.4.jar
- sound-physics-remastered-fabric-1.20.4-1.3.1.jar
- threadtweak-fabric-1.20.4-0.1.2.jar
- visuality-0.7.3+1.20.4.jar
- visualoverhaul-fabric-5.1.0.jar
- vmp-fabric-mc1.20.4-0.2.0+beta.7.138-all.jar
- wakes-0.2.3.jar
- XaerosWorldMap_1.38.1_Fabric_1.20.4.jar
- Xaeros_Minimap_24.0.2_Fabric_1.20.4.jar

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/14640141/latest.log)

## How to reproduce
Go into any world and use `#mine block`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Looks like something silently messes up the client side. Two seconds after `#mine andesite` was run the Baritone cache was saved and another 15 seconds later the integrated server connection timed out, making the server shut down.

Can you please try narrowing down the set of mods required for this to happen? You should probably start with c2me and enhancedblockentities since c2me is known to cause problems and enhancedblockentities ships advanced_runtime_resource_pack and Baritone does some datapack + loot table trickery to determine block drops.

**Comment by MrWomanStealer** [comment]
Hey there!
It's c2me.  I had an issue with this too, but disabling c2me fixed it.
EBE still works with this.
