### ISSUE TITLE
Is there a way to use tunnel when y=11 and excavate visible minerals?

### ISSUE THREAD

**Issue by SetsunaYukiOvO** [cabaletta/baritone#4306]
I found mine very suspicious, even if I opened a mine, it always looks for minerals that theoretically cannot be found, such as knowing in advance that there is a mine below. And the quick turns and turns while searching for the way are very suspicious.

**Comment by ZacSharp** [comment]
If looking suspicious is a problem to you chances are you shouldn't be using Baritone.

Turn on `legitMine` to stop it from knowing where the ores are.
