### ISSUE TITLE
Baritone not building when I use #build

### ISSUE THREAD

**Issue by stub91** [cabaletta/baritone#4308]
Whenever I try to #build my schematic baritone says: Successfully loaded schematic for building and Origin: BetterBlockPos{x=2,y=-60,z=-11}
So im pretty sure I just accidentally enabled or disabled a setting so I just need the setting so that it will actually build
## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by stub91** [comment]
I’ve also just realized that nothing with baritone will work, but I don’t get any error messages when I try to do any actions

**Comment by rycbar0** [comment]
let me guess, you have far sight in your mods folder.

**Comment by stub91** [comment]
> let me guess, you have far sight in your mods folder.

I forgot to update this but it resolved on its own after I close and open the game again it got fixed. And I don’t have farsight.

**Comment by stub91** [comment]
So just open and close the game to fix this and it should hopefully work
