### ISSUE TITLE
Slab placing in top half position with #sel fill command

### ISSUE THREAD

**Issue by xAMS49x** [cabaletta/baritone#4322]
Does anyone know how to place slabs in top position (command or something), if it even possible?

**Comment by rycbar0** [comment]
if you use #sel fill baritone will choose the default blockstate. for slabs that is the bottom slab. if you want top slabs try make a schematic with top slabs.

**Comment by ZacSharp** [comment]
Also be aware that while top slabs are not as bad as directional blocks they can still cause problems (can't be placed on the floor).
