### ISSUE TITLE
1.20.4 Crash (NeoForge Loader on launch)

### ISSUE THREAD

**Issue by Fixerintaved** [cabaletta/baritone#4323]
## Some information
Operating system: Windows 7
Java version: 17.0.6
Minecraft version: 1.20.4
Baritone version: v1.10.2 from releases
Other mods (if used): no only Bartione

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/14836865/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/14836866/latest.log)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Does it work without Baritone?
