### ISSUE TITLE
When I join a world it starts imeditly

### ISSUE THREAD

**Issue by sonofactgnrd** [cabaletta/baritone#4328]
When I join a world it starts imeditly
Operating system: ubuntu linux
Java version: openjdk version "17.0.10" 2024-01-16
Minecraft version: 1.20.4
Baritone version:1.10.2
Other mods (if used): appleskins, architectury, AutoDuper, AutoTotem, BadOptimazation, Baritone, Better Mount Hud, Better Statics Screen, Bookshelf, Break Free, Chat Heads, Continuity, Controlling, CoordinatesDisplay, Ctrl Q, Cubes Without Borders, CustomItem Texers, Dark Loading Screen, Debugify,  Dynamic FPS, Elytra Trims, Emoji Type, EnchantmentDescriptions, Entity Modle Fetchers, Entity Culling, FabricSkyBox, Fabricshot, FastQuit, FerritCore, Gamma Utilitys, GoogleChat, HigTools, Indium, Iris, JEI, Krypton, LambDynamicLights, Languege Reaload, LazyDFU, Lithium, Make Bubbles Pop mod, MCT32's Armor HUD, Meteor Client, MeteorAddons, Meteor Plus, Meteor Rejects, MidnightContruls, MixinTrace, Mod Menu, ModDetectionPreventer, Modles Gap Fix, ModernFix, More Culling, No Chat Reports, No Telemetry, NoRecipyBook, Not Enough Crashes, Numby Hack, OptiGUI, Polytone, Puzzle, Remove Reloading Screen, Satin API, SeedCrackerX, ServerSeeker, Shulker Box Tooltip, Small Pop, Sodium, Reses sodium options, sodium Extra, Status Efect Bar, Superflat World No Slimes, ToolTip Fix, TrouserStreak, Very Many Players, ViaFabricPlus, Visuality, Yeetus Experiments, YOSBR, Zoomify

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/14898540/latest.log)

## How to reproduce
join a minecraft server

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
That's probably one of your many hack clients having some feature enabled which uses Baritone.

**Comment by sonofactgnrd** [comment]
Thanks
