### ISSUE TITLE
[suggestion] Allow Block IDs

### ISSUE THREAD

**Issue by MasterGam3r** [cabaletta/baritone#433]
Allowing baritone to use Block IDs [1.12.2 only] , It helps a lot with modded minecraft [on forge] , because many mods use same block name [for example "ThermalFoundation:ore"] but they use a different block id.
For example you could use "#mine 1337 1" or "#mine 1337:1" instread of it's block ID

**Comment by ZacSharp** [comment]
Long done in #922.
For your example it's e.g. `#mine thermalfoundation:ore:0`, `#mine thermalfoundation:ore:1`, etc. now.
