### ISSUE TITLE
Baritone Doesnt Move

### ISSUE THREAD

**Issue by AlexCrane1** [cabaletta/baritone#4334]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Im Using The Baritone 1.20.1 Mod But Whenever I Use Anything That Involves Moving, it just doesnt move at all
## Final checklist
- [✔] I know how to properly use check boxes 
- [ ✔] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Are you using farsight?

**Comment by Mathiou2888** [comment]
I also have the same problem

**Comment by ZacSharp** [comment]
@Mathiou2888 and are *you* using Farsight? Or maybe have more information than a generic "doesn't work"?

**Comment by wagyourtail** [comment]
there are also a few other mods that can cause it, such as immersive portals

**Comment by tianqo** [comment]
the same problem in 1.20.1.I used it in the Bettermc modpack and did not find any modules - that caused this issue.I tried '''#goto''' and '''#mine''' ,none of them ran.

**Comment by syncblaze** [comment]
anything new? tried the same also with bettermc modpack, same problems

**Comment by BanWolf** [comment]
I removed farsight and now it's working
