### ISSUE TITLE
Slow Path Finding Issues with Baritone

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#4336]
## What do you need help with?
Not sure if this is a bug, but I'm having slow path finding issues with Baritone in Minecraft, even when the goal is only 50 blocks away on relatively flat land. This issue occurs despite reinstalling Baritone and updating to the latest version. I've also turned off all speed hacks in the Meteor client, the Minecraft utility client I use, and performed these tests on regular grass block land.

Any ideas on how to fix this?

Also, here's a video of the slow path finding:

https://github.com/cabaletta/baritone/assets/167450096/00a98877-cc0f-45bc-a137-ec3f5379829e

## Some information
Operating system: Windows 10 Home
Java version: 1.8.0_411
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used):
- fabric-api-0.97.0+1.20.4
- meteor-client-0.5.6-2056
- replaymod-1.20.4-2.6.15

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
this is indeed slow
could it be possible that you enabled slowPath?

**Comment by ghost** [comment]
Yup, that was it.

Accidentally set it to `true` while messing around with the commands and forgot about it. .-.

Thank you!
