### ISSUE TITLE
Baritone Not Moving

### ISSUE THREAD

**Issue by willmasterrr** [cabaletta/baritone#4340]
## Some information
Operating system: Windows 11
Java version:
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): Blackout (Meteor Client Addon), cupboard (API), Fabric API, Farsight Mod, Meteor Client, Sodium (I tested this even with sodium turned off but still didnt work), ViaFabricPlus

I was using baritone just fine until it just stopped working, the AI refuses to move, i did #reset and i disabled sodium and i restarted my game multiple times but it didnt fix.

https://github.com/cabaletta/baritone/assets/79755822/6b346b8f-b8a6-4fc8-96c0-55af3648dd60

## How to reproduce
do #mine or #goto (or anything)
Wont move

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by willmasterrr** [comment]
I fixed it by deleting the instance

**Comment by ethan-davies** [comment]
Although you seem to have fixed this. You had your baritone paused use `#resume` to continue it (if this situation occurs again)

**Comment by ZacSharp** [comment]
The problem probably was farsight. Baritone directly reads chunk management internals for performance reasons so mods doing intrusive changes tend to break it. (except for Sodium, until they change their internals)

**Comment by Motzumoto** [comment]
> The problem probably was farsight. Baritone directly reads chunk management internals for performance reasons so mods doing intrusive changes tend to break it. (except for Sodium, until they change their internals)

omfg THANK YOU FOR THIS!!! I was having issues with it finding the path just fine but not moving. It was farsight.

**Comment by canhtungdz** [comment]
> The problem probably was farsight. Baritone directly reads chunk management internals for performance reasons so mods doing intrusive changes tend to break it. (except for Sodium, until they change their internals)

so thank. i find no many

**Comment by Bap270606** [comment]
> The problem probably was farsight. Baritone directly reads chunk management internals for performance reasons so mods doing intrusive changes tend to break it. (except for Sodium, until they change their internals)

omg Thanks bro, because I installed so many mods I don't know which mod got conflicted
