### ISSUE TITLE
Baritone will not build schematics but will instead walk away

### ISSUE THREAD

**Issue by stonedlol** [cabaletta/baritone#4342]
I have a problem with baritone in combination with litematica it will not start building it will instead start walking away or breaking random blocks, im clueless so it would be nice if there is a soltion to this

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by figloalds** [comment]
It's easier if you install litematica and use it to place the schematic where you want it to be built then run `#litematica`
The build command as far as I see has some quirks that honestly I haven't been able to figure out
Yes I had this thing you mention happen to me, and I also had it build but offset from the origin I set

**Comment by ZacSharp** [comment]
Without knowing more about what you did it is hard to help you, here are some guesses:
1. The coordinates you specify are the position of the -x,-y,-z corner of the schematic bounding box, not the position of the schematic origin
2. You used `#litematica` with multiple schematics opened in Litematica and accidentally started building the wrong one
3. You have the schematic open in Litematica and expected `#build` to build it at that position. `#build` defaults to placing the -x,-y,-z corner at your position. Use `#litematica` to build schematics opened in Litematica.
4. You forgot you have settings set to modify the schematic.

**Comment by jockeking12** [comment]
i also have this probelm how can i fix it?
