### ISSUE TITLE
Switch to sword if a hostile mob is near

### ISSUE THREAD

**Issue by ItsGraphax** [cabaletta/baritone#4345]
## Describe your suggestion
An option to make baritone switch to a sword and offhand a totem when a hostile mob is near to allow flawless afk mining without the fear of dying. (Needs the player to have KillAura for monsters activated

## Settings
pauseNearMobs
swordNearMobs
totemNearMobs
resumeNotNearMobs

## Context
It would enhance the afk mining possibilities and would allow for automining (for ex. an economy) without fearing of a death

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Switching to an appropriate weapon (and perhaps pausing Baritone) is the responsibility of whatever you use to actually attack the mobs (or something different, that doesn't matter from Baritones perspective).

**Comment by ZacSharp** [comment]
If Baritone was supposed to take care of the mobs on its own, then choosing a weapon would be in scope, just like Baritone chooses tools when mining blocks.
