### ISSUE TITLE
I  installed  baratone  and got a weird error

### ISSUE THREAD

**Issue by IzzTheDev** [cabaletta/baritone#4349]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
So i installed baritone for 1.20.4 (version 1.10.2) and wwhen  i try to run #build it will not work as  i get an  error message
![Schermafbeelding 2024-04-29 140251](https://github.com/cabaletta/baritone/assets/168435336/88c9a33c-9fec-4343-89e8-2144308d5c50)

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by HarshuboiPlayz** [comment]
you're trying to build a schematic, which you havent specified
