### ISSUE TITLE
Baritone not working

### ISSUE THREAD

**Issue by Mazoffis** [cabaletta/baritone#4351]
## Some information
Operating system: win 11
Java version: (build 1.8.0_411-b09)
Minecraft version: 1.19.4
Baritone version: 1.9.3
Other mods (if used): FO modpack, xaeros minimap

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/15160729/latest.log)

## How to reproduce
When i write #tunnel nothing shows up, except for the message in chat, same with any command

## Modified settings
blockPlacementPenalty 20.0
acceptableThrowawayItems minecraft:cobblestone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone doesn't work with farsight so removing it should make things work.
