### ISSUE TITLE
cleararea not getting the entire area

### ISSUE THREAD

**Issue by snoobiegoobert** [cabaletta/baritone#4353]
## Some information
Operating system: Windows
Java version: IBM Semeru JRE 17.0.10.7 openj9
Minecraft version: Fabric 0.15.11 1.20.4
Baritone version: 1.10.2-2-g1018db79-dirty
Other mods (if used):
Chunky-1.3.138.jar
Clumps-fabric-1.20.4-15.0.0.2.jar
CullLessLeaves-1.3.0.jar
ImmediatelyFast-Fabric-1.2.12+1.20.4.jar
Ksyxis-1.2.2.jar
Log-Begone-Fabric-1.20-1.0.7.jar
YetAnotherConfigLib-3.4.2+1.20.4-fabric.jar
alternate-current-mc1.20-1.7.0.jar
autoreconnector-fabric-1.1.1-1.20.4.jar
baritone-api-fabric-1.10.2.jar
betterbeds-1.3.0-1.19.3.jar
betterchunkloading-fabric-1.20.1-2.3.jar
betterfpsdist-fabric-1.20.1-4.0.jar
botwrangler-1.0.0.jar
c2me-fabric-mc1.20.4-0.2.0+alpha.11.67.jar
chunksending-fabric-1.20.1-2.8.jar
clientcrafting-fabric-1.20.1-1.7.jar
cloth-config-13.0.121-fabric.jar
connectivity-fabric-1.20.1-4.8.jar
cupboard-fabric-1.20.1-2.6.jar
entityculling-fabric-1.6.4-mc1.20.4.jar
fabric-api-0.97.0+1.20.4.jar
fabric-chunkpregen-0.3.7.jar
ferritecore-6.0.3-fabric.jar
krypton-0.2.6.jar
lazy-language-loader-0.3.5.jar
lithium-fabric-mc1.20.4-0.12.1.jar
lunade-fastanim-1.6-1.20.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
methane-3.6.0.jar
moreculling-1.20.4-0.24.0.jar
recipeessentials-fabric-1.20.1-3.2.jar
smoke-suppression-1.0.19+MC1.20.2-1.20.5.jar

## Exception, error or logs
Not applicable

## How to reproduce
In my case I had 10 simultaneous baritone instances clearing the area (a single chunk, border to border) but it should be reproducible with 1

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

## Additional comments
Baritone is being used via the API and not chatcontrol

**Comment by snoobiegoobert** [comment]
![example](https://github.com/cabaletta/baritone/assets/140143172/4a7342ea-a501-4268-8210-4a75adf69d79)
![example2](https://github.com/cabaletta/baritone/assets/140143172/f262f47a-8b6a-4148-a88d-38151beec3b1)

**Comment by snoobiegoobert** [comment]
Willing to record a demo of the behavior tmrw if needed

**Comment by snoobiegoobert** [comment]
It also seems to like mining bedrock?
![image](https://github.com/cabaletta/baritone/assets/140143172/6d333fb6-ec86-48fa-bd38-8262f82c68e3)

**Comment by ZacSharp** [comment]
You should try using `buildInLayers`. If Baritone had a better builder it could be expected to figure out the building order on its own, but until that happens this is actually far from what you can expect from Baritone.

In some sense this is really a bug, but I'll close it anyway. The current builder can't be expected to do this and *if* we get a better one this issue is obsolete anyway.

**Comment by ZacSharp** [comment]
To avoid misunderstandings: Baritone is expected to be capable of clearing that hole, if you tell it in which order to do so.

**Comment by snoobiegoobert** [comment]
thanks for clearing that up and taking the time to respond, ill look into usage of buildInLayers
