### ISSUE TITLE
[NeoForge] Deprecated mod file

### ISSUE THREAD

**Issue by emyfops** [cabaletta/baritone#4354]
## Information
Operating system: WIndows
Java version: 17.0.8
Minecraft version: 1.20.4
Baritone version: 1.10.2

## Exception, error or logs
[09:47:28] [main/ERROR] (ModInfo) Mod 'baritoe' uses deprecated 'mandatory' field in the dependency declaration for 'minecraft'. Use the 'type' field and 'required'/'optional' instead
[09:47:28] [main/ERROR] (ModInfo) Mod 'baritoe' uses deprecated 'mandatory' field in the dependency declaration for 'minecraft'. Use the 'type' field and 'required'/'optional' instead

## Aditionnal info
The deprecated field warning can be ignored in 1.20.4, but not in 1.20.5
NeoForge 20.5 introduced a `neoforge.mods.toml` metadata file that replaces the old `mods.toml`

https://neoforged.net/news/20.5release/

**Comment by ZacSharp** [comment]
This shouldn't be an issue on 1.20.4?
(The 1.20.5 port already renamed the file)

**Comment by ZacSharp** [comment]
@Edouard127 you reported this as a problem with 1.20.4 but as far as I can tell this is a 1.20.5+ change. Is 1.20.4 really affected?

**Comment by emyfops** [comment]
I don't think it will cause problems with previous versions
You cannot launch 1.20.4 with NeoForge 20.5

This is only a warning message for future versions

~Maybe I launched with 1.20.5 and wrongly tagged the issue, I don't remember since It's been over a month~
Edit: I launched the game in 1.20.4 neo 20.4.234 and I get the warning

**Comment by ZacSharp** [comment]
Ok, thank you.

**Comment by ZacSharp** [comment]
Timing... Just as I pressed close you edited you comment.

**Comment by ZacSharp** [comment]
"Fixing" this for 1.20.4 shouldn't be required but might just as well do it anyway.

**Comment by emyfops** [comment]
I have edited the issue description to avoid further confusion

**Comment by ZacSharp** [comment]
I tried just now and neoforge 20.4.234 as well as 20.4.237 did not emit a warning.

**Comment by emyfops** [comment]
I have the warning in a developer environment at least, the issue can be closed then because the file was updated in the 1.20.5 release

**Comment by ZacSharp** [comment]
> in a developer environment

That might be the reason. Baritones  `runClient` fails for (neo)forge so I used a production environment to test. I'll try again with a fresh dev environment.

**Comment by ZacSharp** [comment]
Given that this is just a warning and I couldn't even reproduce it, I'll leave this as is.
