### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by MelvinSGjr** [cabaletta/baritone#4357]
## Some information
Minecraft version: 1.19.2
Baritone version: last

he is not building schematics files
![image](https://github.com/cabaletta/baritone/assets/102232826/9371271b-448e-46a9-b8b5-3d7bf5270045)

**Comment by ZacSharp** [comment]
Either the file extension is wrong or you are trying to build an old McEdit schematic, which doesn't work too well on versions after 1.12.2. In the first case you should fix the file extension, in the latter case you should convert the schematic either to a .schem or a .litematic (there are online converters and afaik litematica can do it as well).
