### ISSUE TITLE
update to 1.20.6 please

### ISSUE THREAD

**Issue by jklmm7xw** [cabaletta/baritone#4358]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
update to 1.20.6 please
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
1. 1.20.6 updatability
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
i could use it on 1.20.6
## Final checklist
- [ ] update to 1.20.6 please
- [ ] pls I want you to update to 1.20.6

**Comment by this-text-is-disappeared1435** [comment]
really update bro

**Comment by ZacSharp** [comment]
If you had searched a little before making demands you'd have found #4347 which is actually two weeks older than this issue.

**Comment by jklmm7xw** [comment]
> If you had searched a little before making demands you'd have found #4347 which is actually two weeks older than this issue.

cry

**Comment by ZacSharp** [comment]
#4347 is merged.

**Comment by EsusQuitGames** [comment]
> cry

Be polite.
