### ISSUE TITLE
Disable Autowalk

### ISSUE THREAD

**Issue by DashCreative1** [cabaletta/baritone#4360]
How to disable Autowalk while path being visible
Because auto walk is VERY suspicious. And the pausing methed is not accurate its the least because it stops generating path after something then we have to resume again then pause again. Also i am using 1.20.1-1.20 version (of minecraft) and 1.10.1 version of baritone

So please if it is not there in the mod. ADD THEM 
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
#pause

**Comment by DashCreative1** [comment]
Dude I mentioned Pause is not accurate

**Comment by ZacSharp** [comment]
This has been requested multiple times already, but nobody added it so far.
