### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by vampad** [cabaletta/baritone#4367]
I don't really know how this works, i'm just an average user. But for some reason, baritone keeps popping up this error whenever it has mined three rows.
When it does this, it does highlight the blocks it can break but it doesnt move. And when i stop it, its easily reachable. is this a setting i just can't find or does somebody have the answer? I need help!

![image](https://github.com/cabaletta/baritone/assets/170289085/d1b9701a-e9e2-4f14-92e7-d216c2c87298)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`MineProcess` mines things by walking into them (with one exception for mining straight up) so maybe the logs aren't reachable that way?
