### ISSUE TITLE
AllowParkourAscend|AllowParkour not working

### ISSUE THREAD

**Issue by ast1vea** [cabaletta/baritone#4368]
AllowParkourAscend: true 
AllowDiagonalAscend true
function does not work. same as AllowParkour
he can't jump over a jump that I can jump over myself. What is the parkour function for then????? or help me set it up please. I already turned off breaking and placing blocks

https://youtu.be/nLBaoEdoML4
github.com/cabaletta/baritone/tree/1.20.1
data: 2024.20.05  14:08:33

**Comment by ZacSharp** [comment]
Baritone only does flat jumps in the cardinal directions over gaps of up to three blocks and ascending jumps in the cardinal directions with a gap of up to two blocks. There is a discontinued pr adding support for more jumps (#2142) and [this fork](https://github.com/merasmus44/baritoneParkourPort) seems to be a port of that pr to 1.20, though I can't tell you whether it works or even does what it is supposed to do.
