### ISSUE TITLE
(Suggestion) Make baritone able to mine multiple blocks

### ISSUE THREAD

**Issue by TheKnyt** [cabaletta/baritone#437]
For example .b mine diamond_ore emerald_ore iron_ore

It'll make getting multiple different blocks easier

**Comment by leijurv** [comment]
I'm actually in awe that you haven't tried that exact command `.b mine diamond_ore emerald_ore iron_ore` and noticed that it already works XD

**Comment by TheKnyt** [comment]
oh, im dumb

**Comment by cyleja1234** [comment]
well I think it is a good thing this is here for people that I didn't know you can and just easily find it here.

**Comment by dominikaaaa** [comment]
It's also in the USAGE.md

Please try to avoid commenting on issues from over a year ago, it just sends a notification to a bunch of people who don't need it
