### ISSUE TITLE
Shit

### ISSUE THREAD

**Issue by isurami** [cabaletta/baritone#4370]
## Some information
Operating system: Windows 11
Java version: openjdk version "11.0.16.1" 2022-08-12 LTS
Minecraft version: 1.16.5
Baritone version: I dont know
Other mods (if used): I use client Wild

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/15382511/latest.log)

## How to reproduce
Start building a schematic.
[download](https://drive.google.com/file/d/11W_fECrNbYdL7c7oTc3Qxpdww35owH5A/view?usp=sharing)
[youtube demonstration](https://youtu.be/sanowXszu8E)

## Modified settings
allowInventory true
acceptableThrowawayItems minecraft:granite,minecraft:dirt,minecraft:andesite,minecraft:cobblestone,minecraft:diorite
buildIgnoreBlocks cobblestone
buildIgnoreExisting true
buildIgnoreDirection true
buildInLayers true
legitMine true

## Final checklist

- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

## Recommendation:

Of the more than 50 schematics before 1.12.2, not a single one worked correctly, each of them threw an error similar to the one now. I would really like to build beautiful buildings with Baritone, but damn it doesn't work.

**I suggest**: adding the ability to skip a problematic block that arises, perhaps this is not feasible, but I would then complete the mistakes for the baritone, at least he would complete this schematic.

**Comment by ZacSharp** [comment]
In the video it looks like your schematic contains grass in a position where grass cannot be placed.
The message about missing materials for "null" is an old and fixed bug so maybe updating Baritone works. However 1.16.5 is no longer supported so if the last version for 1.16.5 doesn't work then you are out of luck.

You can exclude blocks from the schematic using `buildSkipBlocks`, replace them with `buildSubstitutes`, build only part of the schematic using `buildOnlySelection` and a lot more things, so maybe have a look at the available settings.

Concerning schematics from 1.12.2: They are probably in the old McEdit .schematic format, which Baritone doesn't handle particularly well on 1.13+ so it is best to use a separate tool (Litematica, WorldEdit, online converter, whatever) to convert them to the newer Sponge .schem or Litematica .litematic format.
