### ISSUE TITLE
Baritone digs next to designated area

### ISSUE THREAD

**Issue by KEtttel** [cabaletta/baritone#4373]
when i set baritone to dig an area, it digs up the area opposite to it not in where i selected how can i fix this?
![2024-05-23_20 07 12](https://github.com/cabaletta/baritone/assets/170621098/38ed4223-4605-4c3b-810d-f20d5d45968c)

**Comment by ZacSharp** [comment]
Did you enable one of the `schematicOrientation*` settings?
