### ISSUE TITLE
1.20.1 not work, Continuous error after entering commands, highlighting squares but not starting pathfinding and digging

### ISSUE THREAD

**Issue by djkcyl** [cabaletta/baritone#4380]
## Some information
Operating system: windows 11
Java version: 17
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used): All the mods 9 - no frills Modpack

## Exception, error or logs
[log](https://mclo.gs/ee8akRa)
[latest.log](https://github.com/user-attachments/files/15637144/latest.log)

![463b437cb7d3bd58f6d9a0583576a83f](https://github.com/cabaletta/baritone/assets/59153990/93e04082-b398-49bd-9a9f-d02c59dc7b45)

## How to reproduce
#mine minecraft:iron_ore

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Try removing farsight. If that's not enough, try removing mods until you know precisely which mods are needed to cause this behavior.
