### ISSUE TITLE
#mine doesn't work (unhandled exception occurred)

### ISSUE THREAD

**Issue by Asdlghf11** [cabaletta/baritone#4384]
![Screenshot 2024-06-09 123205](https://github.com/cabaletta/baritone/assets/119073564/dfd36baa-f648-4a5c-89ce-a154d2d7d42b)

**Comment by Asdlghf11** [comment]
Please someone help

**Comment by Asdlghf11** [comment]
i have realised this shows up with every command

**Comment by ZacSharp** [comment]
Please provide the information requested by the bug report template.
Namely: Your Minecraft version, Baritone version, the log file and used mods (preferably that's none).

**Comment by brentspine** [comment]
Logs can be found at %AppData%/.minecraft/logs

Preferably use latest.log and all files that potentially logged errors regarding this
