### ISSUE TITLE
Anyway I can make baritone farm with a specific item?

### ISSUE THREAD

**Issue by TAMMedia** [cabaletta/baritone#4392]
I am on a server and the crops need to be mined using a specific hoe, is there any way i can tell baritone to only farm with that specific item as well as disable the replanting of the seeds?

Furthermore, is there a way i can make the bot use the auto farm command whilst the bot is flying, so far in my tests it just stays in the same place when in the air

Thank you!

**Comment by ZacSharp** [comment]
* You can completely disable tool switching by setting the `autoTool` setting to false. If you then use a different mod to do the switching for Baritone you should also enable `assumeExternalAutoTool` so Baritone knows it will be using a good tool even though it won't select it on its own.
* You can disable `replantCrops`
* No. Baritone is made for walking.
