### ISSUE TITLE
How can I add baritone with meteor client

### ISSUE THREAD

**Issue by Some10101** [cabaletta/baritone#4397]
how can I add baritone with meteor it crashes
When I add it with meteor what do I do

**Comment by Shurtug** [comment]
You download the API version for fabric and the same Minecraft version as fabric/meteor and add it to the mods folder.

A crash log would help a lot tho

**Comment by Some10101** [comment]
By API version of fabric you mean fabric API?

**Comment by Some10101** [comment]
Btw here's a crash log
[latestlog.txt](https://github.com/user-attachments/files/15900063/latestlog.txt)

**Comment by Some10101** [comment]
It's after adding fabric api

**Comment by Shurtug** [comment]
No, I mean the baritone-api-fabric.jar file.

**Comment by Some10101** [comment]
Fabric api or Baritone api?

**Comment by Some10101** [comment]
[Uploading latestlog.txt…]()
Still doesn't work after adding baritone fabric api.jar

**Comment by Some10101** [comment]
Still doesn't work after adding baritone-fabric-api.jar
[latestlog.txt](https://github.com/user-attachments/files/15900374/latestlog.txt)

**Comment by Some10101** [comment]
Shurtug

**Comment by ZacSharp** [comment]
This is a known problem with older versions of Baritone on Android / Pojav Launcher.
You'll have to use a newer version of Baritone to get the fix.

**Comment by Some10101** [comment]
I have the newest version

**Comment by ZacSharp** [comment]
The latest release is too old, you need a CI build.

**Comment by Some10101** [comment]
What's that

**Comment by ZacSharp** [comment]
Automated builds made whenever a new change is pushed to this repository.
The latest one (and possibly last one since 1.20.5 exists) for 1.20.4 is [this](https://github.com/cabaletta/baritone/actions/runs/8822435826) one. Scroll down and download the "Artifacts" zip; it contains the usual files you'd find in a release.
