### ISSUE TITLE
minylevel helpp pls

### ISSUE THREAD

**Issue by E7RE-t** [cabaletta/baritone#4398]
can you help me, on the server I'm playing on, only the spawners above y:45 can be broken, so I searched for a command for this and found minylevel, but no matter what I type, it always goes below y:45

**Comment by ZacSharp** [comment]
`minYLevelWhileMining` restricts which blocks will be considered for `#mine` so it will neither have an effect on other commands nor prevent Baritone from walking at lower levels to reach a block above the limit.
