### ISSUE TITLE
Baritone Elytra for 1.20.6

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#4407]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
I am in 2b2t and it would be nice if you could make it for 1.20.6

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
idc
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
It could help because on 2b2t players can go through nether highways faster
## Final checklist
- [yes] I know how to properly use check boxes 
- [yes ] I have not used any OwO's or UwU's in this issue.

**Comment by luigi052005** [comment]
Just use ViaFabricPlus to connect to 2b2t

**Comment by ZacSharp** [comment]
The CI builds from the 1.20.5 branch also work on 1.20.6. The port is long done, there's just no release.
