### ISSUE TITLE
Why did you guys separate yourself from meteor client?

### ISSUE THREAD

**Issue by Some10101** [cabaletta/baritone#4409]
Why did you guys separate from meteor client?

**Comment by daniel-pg** [comment]
https://meteorclient.com/faq

> Baritone is no longer included with Meteor. Features that depend on Baritone will be disabled unless you put Baritone into your mods folder manually. This will allow us to decouple Meteor from Baritone and update to newer versions faster.

**Comment by wagyourtail** [comment]
we didn't do anything. meteor added baritone, meteor removed baritone. that's all
