### ISSUE TITLE
Build in layers how not to start at layer 1

### ISSUE THREAD

**Issue by JoeyChestnuts** [cabaletta/baritone#4414]
## What do you need help with?
Hey, with the build in layers command, is there anyway i can choose which layer to start on
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
good question. yes it is possible. have you tried checking if you have a setting called `startAtLayer` ?
[see settings](https://github.com/cabaletta/baritone/blob/1.19.4/src/api/java/baritone/api/Settings.java#L1005-L1009)

**Comment by JoeyChestnuts** [comment]
you are a blessing man, thank you, i didnt seem to find it before
