### ISSUE TITLE
Stoping breaking

### ISSUE THREAD

**Issue by JoeyChestnuts** [cabaletta/baritone#4415]
## What do you need help with?
Hey, while using schematica build is there a possibility to dissable breaking?
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
buildIgnoreExisting

baritone has tab auto complete if you dont know the exact spelling or if you just want to surf through the setting you can do it ingame with the `#set list` command or you can check all available setting including a description of what they do [here](https://github.com/cabaletta/baritone/blob/1.19.4/src/api/java/baritone/api/Settings.java)
