### ISSUE TITLE
baritone does not recognize blocks underneath me at a certain point

### ISSUE THREAD

**Issue by heavensguard** [cabaletta/baritone#4416]
so im playing in a prison server and i had the brilliant idea of using baritone to sit back and relax
so lets say i set it to straight up mine just diorite with #mine diorite and then it mines it as it is supposed to but
at some point it just mines the blocks over me and when there are none left it stops and ignores the blocks underneath me (which are the same block i set it to mine)
![2024-07-01_15 03 46](https://github.com/cabaletta/baritone/assets/174336372/dafeb880-2e52-472b-999f-15e6951e1e5c)

**Comment by rycbar0** [comment]
1. you only should use baritone where it is allowed and prison servers usually dont approve of baritone.
2. that is a job for #sel and not for #mine
