### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cat67315** [cabaletta/baritone#4423]
## Some information
Operating system: windows 11
Java version:17
Minecraft version:1.20.4
Baritone version:1.10.2
Other mods (if used): Cloth Config API, EntityCulling, Fabric API, FerriteCore, Gamma Utils (Fullbright), ImmediatelyFast, Litematica, Lithium, MaLiLib, Memory Leak Fix, Mod Menu, Sodium, Text Placeholder API, WorldEdit, Xaero's Minimap, Xaero's World Map

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/user-attachments/files/16135367/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
use elytra on nether roof and while in mid air type in chat #elitra

## Modified settings
To get the modified settings run `#modified` in game
allow inventory is true
allow only exposed ores is true
allow parkour is true
max fall hight bucket is 100
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`#elytra` is not supposed to work outside the normal 0-128 nether range and you should not use Baritone on Hypixel.
