### ISSUE TITLE
Baritone dont walk

### ISSUE THREAD

**Issue by vo0ov** [cabaletta/baritone#4427]
## Some information
Operating system: Windows
Java version: 21
Minecraft version: 1.20.1
Baritone version: baritone-standalone-fabric-1.10.1
Other mods (if used): WE, LiteMatic

## Exception, error or logs
No errors

## How to reproduce
The bot stops on the spot, although it only needs to complete one block to reach the desired location. However, if I hold down the "W" key, everything works fine. A video:
<video src='https://github.com/user-attachments/assets/f3c212f4-ec80-4687-9c28-edac2ba07269' width=180/>

Command: #build CreeperFarm_1.20.1_V2.litematic

## Modified settings
![12 07 2024 12-12](https://github.com/user-attachments/assets/875157de-9fbb-4e6d-b8f1-8bf16c888bb9)

## Final checklist
- [x] I tried changing blockReachDistance.
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
Do you have far sight installed?

**Comment by vo0ov** [comment]
No, the server does not use farsight, anti-cheats and mods, only plugins that do not affect the gameplay.

**Comment by ZacSharp** [comment]
The half slabs might be causing problems. Though as long as `allowWalkOnBottomSlab` is enabled walking on them is supposed to work.

**Comment by vo0ov** [comment]
Thanks
