### ISSUE TITLE
when 1.21

### ISSUE THREAD

**Issue by WillHanighen** [cabaletta/baritone#4433]
add 1.21

**Comment by stand0t** [comment]
fr

**Comment by NMDx86** [comment]
It is out in Artifact?

**Comment by dtzdev** [comment]
> It is out in Artifact?

https://github.com/cabaletta/baritone/actions/runs/9593797633

**Comment by stand0t** [comment]
fabric?

**Comment by BlannyBlannyBlanc** [comment]
> fabric?

Just use Meteor client

**Comment by dtzdev** [comment]
> https://github.com/cabaletta/baritone/actions/runs/9593797633

Included in the artifact.
https://github.com/cabaletta/baritone/actions/runs/9593797633

**Comment by dtzdev** [comment]
> fabric?

Included in the artifact.
https://github.com/cabaletta/baritone/actions/runs/9593797633
