### ISSUE TITLE
I want to end myself how to get 1.21 to work?

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [cabaletta/baritone#4436]
## I am running 1.21 version of Minecraft, Fabric, installed baritone-standalone.jar into: `.minecraft/mods/1.21/baritone-standalone.jar`
The mod does not work. Typing #mine does not work. Nor does it look like fabric API is even being loaded even though I put it in the mods/1.21 folder. Please help, what am I doing wrong?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
fabric doesn't support sub-folders within the mods folder
