### ISSUE TITLE
entry in the server logs?

### ISSUE THREAD

**Issue by Louis0816** [cabaletta/baritone#4437]
If I use the client on a multiplayer server, does it say in the server logs, for example (>Player ... used #baritone) or #mine or something like that. So can the owner see in the logs when I use the bot? or not because it is not a real command, since they start with /...

**Comment by ZacSharp** [comment]
Baritone commands are handled clientside, but there are other ways to detect it. If the server owner doesn't want you to use Baritone just don't use Baritone.
