### ISSUE TITLE
My game is crashing every time I use it.

### ISSUE THREAD

**Issue by Zeus89yt** [cabaletta/baritone#4449]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.21
Baritone version: 1.21
Other mods (if used): Meteor Client, Appleskin, controlling, enchantment lore, fabric api, jade, jei, journeymap, litematica, malilib, searchables, sodium, world edit. 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`
[latest.log](https://github.com/user-attachments/files/16434047/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

The issue thats happening is that everytime I use a command in this case I tried to use #mine minecraft:oak_log it crashes my game every time and I can't use it.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The log file does not contain any crash information. Either this is a silent crash or you uploaded the wrong file.

Apart from that, you shouldn't be using Baritone (or Meteor) on that server anyway.

**Comment by Zeus89yt** [comment]
> The log file does not contain any crash information. Either this is a silent crash or you uploaded the wrong file.
> 
> Apart from that, you shouldn't be using Baritone (or Meteor) on that server anyway.

I tried first in my server then in my friend's one then in librecraft, it crashes everytime

**Comment by Jonas6io** [comment]
eu uso o fabric e ele esta dando conflito com o jei, tenta remover mod por mod ate conseguir funcionar e outro mod tambem que da conflito e o xaen xaero's minimap

**Comment by Zeus89yt** [comment]
> eu uso o fabric e ele esta dando conflito com o jei, tenta remover mod por mod ate conseguir funcionar e outro mod tambem que da conflito e o xaen xaero's minimap

ty
