### ISSUE TITLE
Death Waypoint didn't saved

### ISSUE THREAD

**Issue by szyszek0218** [cabaletta/baritone#4456]
Hi. Recently, I played Minecraft and due to an incident with an Enderman, I happened to die in the Nether. The chat message informed me that the death location was saved, but when I checked in "#wp," there was no slot with the coordinates of the death location. Is there any way I can retrieve the data I need? As an experiment, I killed myself again, and this time I had no problem accessing the coordinates, so I don't know what the issue is. I would appreciate any help.

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Waypoints are saved per dimension so if you go to the nether and run `#wp` there you should see the waypoint.
