### ISSUE TITLE
Elytra flight works fine but it generates hundreds of identical error messages in transit

### ISSUE THREAD

**Issue by Zimber106** [cabaletta/baritone#4458]
meteor client stacks the error messages for me since they're duplicates but it sent roughly 550 times (screenshot attached)
![2024-08-04_05 08 23](https://github.com/user-attachments/assets/6d8601fa-74b8-45ed-a9e8-84d3efdf23f1)

## Some information
Operating system:Windows 11
Java version:latest
Minecraft version:1.21
Baritone version:latest
Other mods (if used): 
meteor, various other fabric mods (images attached)
![Screenshot 2024-08-04 051721](https://github.com/user-attachments/assets/02f83be7-d4c8-47d5-981e-f7f459d38732)
![Screenshot 2024-08-04 051736](https://github.com/user-attachments/assets/8bc5ee76-f5c3-41a9-921d-ef4015197f10)
![Screenshot 2024-08-04 051750](https://github.com/user-attachments/assets/fd9f296b-a501-4aa3-b0a7-922149292a92)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/user-attachments/files/16487165/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
go to nether
use baritone for elytra flight
## Modified settings
To get the modified settings run `#modified` in game
screenshots attached
![2024-08-04_05 22 37](https://github.com/user-attachments/assets/61a22be1-b05c-4799-a8ac-3e6e27329c5b)
![2024-08-04_05 22 47](https://github.com/user-attachments/assets/1b47f1d1-1e7f-4168-a37e-a19e6c11f81f)
![2024-08-04_05 22 54](https://github.com/user-attachments/assets/99b7e0c8-65f2-4b43-80b3-81829fb2975f)
![2024-08-04_05 22 57](https://github.com/user-attachments/assets/53579706-fc85-4930-ac28-7926da62f7d5)

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The error is from the nether pathfinder complaining that it's being used an unsupported y value, which, judging by your first screenshot, is exactly what you did. What does seem a bit off is that it generated a path at all. It should completely refuse operation when used on the nether roof (changing that is another issue).

**Comment by Zimber106** [comment]
whoa, wasn't aware of that. cool, case closed i guess.
