### ISSUE TITLE
Cant see selected area

### ISSUE THREAD

**Issue by gloomysloth** [cabaletta/baritone#4460]
Baritone doesn`t show selected area with #sel, only 1 block at corner. Is this a bug? Minecraft 1.21, mods : Fabric ,Lithium and Xaeros Minimap. Playng on my friends server.
![2024-08-06_00 17 54](https://github.com/user-attachments/assets/e4e8549d-65fc-43e1-9245-7f76e489abe2)

**Comment by ZacSharp** [comment]
Doesn't look right. Memory tells me I should be able to confirm (and hence maybe fix) this, but I can't promise anything.

**Comment by ZacSharp** [comment]
Fixed
