### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by blazebrown87221** [cabaletta/baritone#4463]
## Describe your suggestion
can there be a 1.20.1 version?

## Context
it would be nice if there would be a 1.20.1 version

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Ghost837** [comment]
well they are working on a 1.20.5/1.20.6 so please be patient 
i believe they have a early build of it on the discord and you can also get it at https://meteorclient.com/

**Comment by blazebrown87221** [comment]
ok just asking
