### ISSUE TITLE
Cannot build schematic with #build

### ISSUE THREAD

**Issue by kregior** [cabaletta/baritone#4467]
## Some information
Operating system: W11
Java version: Version: 8 - 421
Minecraft version: 1.21 fabric
Baritone version: baritone-api-fabric-1.10.2-6-gc1171a68.jar
Other mods (if used): fabric-api

## Exception, error or logs

https://pastebin.com/vJGq5R6S

## How to reproduce

Couldn't start to build with the command #build a schematic

**Comment by ZacSharp** [comment]
That log does not contain the information I would need to have a guess at this. Did you truncate the stacktrace at the top?
