### ISSUE TITLE
No pathing 

### ISSUE THREAD

**Issue by Mangaia** [cabaletta/baritone#4479]
I'm trying to use Baritone inside of the modpack  "All of Create". Version 1.19.2 I am using the standalone version of baritone.

When I do  #mine anything It only highlights them and stay in one place.

What could be causing this?
![image](https://github.com/user-attachments/assets/12c44e83-17c0-44d7-b610-7755ef5a7cbb)

**Comment by wagyourtail** [comment]
`/flywheel chunkCaching off`
