### ISSUE TITLE
Random Question

### ISSUE THREAD

**Issue by SlinkyBuky** [cabaletta/baritone#4482]
## What do you need help with?
Completely random question but why does baritone store waypoints as mp4s????

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
[:shrug:](https://github.com/cabaletta/baritone/commit/05ba817052cecdd605f04e8a27b24b9f12545a50)
It doesn't actually store mp4s though. It uses a custom file format and for some reason uses the mp4 file extension.
