### ISSUE TITLE
Shematics in CurseForge

### ISSUE THREAD

**Issue by MrWhenletryhard** [cabaletta/baritone#4486]
Hi,
In what folder should I place my shematic file in CurseForge profile, please ?
Thank you and sorry if it's not well writen, I'm French.

Friendly.

**Comment by ZacSharp** [comment]
Baritone searches in `<minecraft home>/schematics`, right next to the `screenshots`, `mods` and `worlds` folders (unless curse forge relocates those).

**Comment by MrWhenletryhard** [comment]
I think CurseForge relocates, but thank you ! 
If you could inquire for me that would be great because I don't understand English very well.

**Comment by ZacSharp** [comment]
Sorry, I can't do that as I do not use the CurseForge launcher.
Maybe it helps to know that Litematica uses the same folder or that usually the `resourcepacks` folder is also next to `schematics`? (You can find the latter with the "open folder" button in Minecrafts resource pack options)
