### ISSUE TITLE
Farm failded

### ISSUE THREAD

**Issue by Nekiplay** [cabaletta/baritone#4490]
## Some information
Operating system: Windows
Java version: 21.0.2
Minecraft version: 1.21.1 Fabric
Baritone version: https://github.com/cabaletta/baritone/actions/runs/10513274290

[latest.log](https://github.com/user-attachments/files/16822429/latest.log)

## How to reproduce
https://youtu.be/XGaPZn-u66s
Duplicate: https://github.com/cabaletta/baritone/issues/4418, https://github.com/cabaletta/baritone/issues/4101

## Modified settings
allowDiagonalAscend -> true
allowDiagonalDescend -> true
allowParkour -> true
allowParkourAscend -> true
allowParkourPlace -> true
allowWaterBucketFall -> false
blockFreeLook -> true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ghost** [comment]
I turned off autotool and this worked for me on 1.21 it may help for you!

**Comment by Nekiplay** [comment]
> I turned off autotool and this worked for me on 1.21 it may help for you!

Not working for me
https://youtu.be/Mjj_Nm2WsT8

**Comment by Nekiplay** [comment]
Fixed by set #farmMaxScanSize 512
