### ISSUE TITLE
allowWalkOnSoulSand It would be good if it were added.

### ISSUE THREAD

**Issue by OzzyBuggy** [cabaletta/baritone#4497]
Add a command like #allowWalkOnBottomSlab to allow walking on soul sand. Users should be able to enable or disable this. Additionally, when the #farm command is active, it's likely that we're in a safe area, so let's allow walking on soul sand.

I used translation, so sorry if there are any mistakes.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
It should just be able to walk on soul sand, no setting needed. And if there were one, it would definitely not be ignored during farming.
Bottom slabs have a setting because they can cause problems.

**Comment by OzzyBuggy** [comment]
I start the #farm command to farm Nether Wart, but it says 'farm failed' within seconds. How can I fix this?

**Comment by OzzyBuggy** [comment]
I start the #farm command to farm Nether Wart, but it says 'farm failed' within seconds. How can I fix this?

**Comment by OzzyBuggy** [comment]
I start the #farm command to farm Nether Wart, but it says 'farm failed' within seconds. How can I fix this?
![image](https://github.com/user-attachments/assets/4d259ee5-3ef8-48d2-ba3a-089f6342ab6f)
