### ISSUE TITLE
Getting Baritone to only use the blocks in inventory

### ISSUE THREAD

**Issue by Jazz63540** [cabaletta/baritone#4498]
I'm currently working on a large map art that uses lots of different coloured carpets. I'm building it one colour at a time, so Baritone keeps trying to place carpets I don't have in my inventory, causing it to just stop building. How do I make it only place the colour of carpets I have in my inventory and ignore every other colour?

**Comment by ZacSharp** [comment]
You can remove blocks from the schematic with `buildSkipBlocks`. There is no automatic way of doing this for everything not in inventory though.
