### ISSUE TITLE
How do i make baritone think grass blocks are dirt blocks

### ISSUE THREAD

**Issue by TrueHero1** [cabaletta/baritone#4499]
I'm trying to build a schematic with dirt blocks but every time they turn into grass baritone goes and breaks them and replaces them with dirt again is there a command that will make baritone treat grass blocks as if they were dirt.
If it matters I'm on version 1.20.4 Fabric

**Comment by PoTheMagicDragon** [comment]
There are a couple of settings that would work. Take a look at buildIgnoreBlocks (or something like that) and buildValidSubstitues. You can find out more by typing #help
