### ISSUE TITLE
"find" is unsuccessful, but "goto" and "mine" can be found correctly

### ISSUE THREAD

**Issue by jipu123** [cabaletta/baritone#4504]

**Comment by ZacSharp** [comment]
`#find` does not do the same as `#mine`/`#goto`. It checks Baritones cache of positions of "special" blocks and hence only works for those "special" blocks. What kind of blocks is considered special differs between versions, but usually it's rare blocks with a behavior significantly different from standard solid blocks (slime is a good example).
