### ISSUE TITLE
sel cleararea pausing

### ISSUE THREAD

**Issue by yasgomesvaz** [cabaletta/baritone#4506]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

![image](https://github.com/user-attachments/assets/339650d9-b951-4b7e-9e90-960b809234fa)

How do I make it not stop?

**Comment by ZacSharp** [comment]
Either `#cancel` to stop the build or clean up the liquids manually and then `#resume`.
