### ISSUE TITLE
1.21.1 baritone new player help

### ISSUE THREAD

**Issue by Karol532** [cabaletta/baritone#4507]
Please help me find the files for Baritone for version 1.21.1. Is it necessary to modify any files from the previous version? If so, which ones?

**Comment by PalorderCorporation** [comment]
there is  no 1.21.1 version or any higher versions then 1.20.2

**Comment by Karol532** [comment]
> there is no 1.21.1 version or any higher versions then 1.20.2

So I need to download 1.20.2 version and change inside files to 1.21.1? I have played on 1.21.1 with no issues but i lost files because of my pc, sounds strange but it hapoened.

**Comment by ZacSharp** [comment]
@PalorderCorporation there are no releases for the latest Minecraft version, but the code is there. (releases are made sporadically and are commonly far out of date compared to CI builds)

@Karol532 if you know how to build from source you can take the code from the 1.21.1 branch and build it.
Alternatively you can use a CI build (automated builds made whenever the code is changed). [Here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.1+is%3Asuccess+event%3Apush) is the list of successful builds on the 1.21.1 branch; just select the latest (topmost) entry and download the "Artifacts" file at the bottom (you need to be signed in to GitHub), it contains all the files you would find in a release.

**Comment by PalorderCorporation** [comment]
> @PalorderCorporation there are no releases for the latest Minecraft version, but the code is there. (releases are made sporadically and are commonly far out of date compared to CI builds)
> 
> @Karol532 if you know how to build from source you can take the code from the 1.21.1 branch and build it. Alternatively you can use a CI build (automated builds made whenever the code is changed). [Here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.1+is%3Asuccess+event%3Apush) is the list of successful builds on the 1.21.1 branch; just select the latest (topmost) entry and download the "Artifacts" file at the bottom (you need to be signed in to GitHub), it contains all the files you would find in a release.
well @Karol532  there are many skids so they will download sketchy stuff and then they get hacked now they will mostly not download random stuff anymore but i wont be mean or anything like that i think i will leave this thread for a while
