### ISSUE TITLE
Pojavlauncher Crash

### ISSUE THREAD

**Issue by nikitadan4pi** [cabaletta/baritone#4509]
## Some information
Operating system: android 12
Java version: 17/21
Minecraft version: 1.20.4, 1.19.4, 1.20.1
Baritone version: elytrabaritone, last
Other mods (if used): no

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here. use HolyGL4ES on pojavlauncher and see incompatible 

## Modified settings
To get the modified settings run `#modified` in game. Cannot start 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There is a known problem on android/pojavlauncher (or any other system not supported by nether-pathfinder). If that is the problem you are encountering updating Baritone will fix it (no, releases are not "latest". Might be you'll have to use a CI build), otherwise please provide a log file.
