### ISSUE TITLE
Is it possible to make it so that when you load a schematic with #build, Baritone doesn't break anything but still builds?

### ISSUE THREAD

**Issue by Jan1653** [cabaletta/baritone#4511]
Is it possible to make it so that when you load a schematic with #build, Baritone doesn't break anything but still builds?

**Comment by CallMeHein** [comment]
`#allowBreak false` ?

**Comment by ZacSharp** [comment]
No, that only affects scaffolding blocks and the builder will still break blocks when the schematic demands it.
You are probably looking for [`buildIgnoreExisting`](https://github.com/cabaletta/baritone/blob/d25d6c2611f5cb0a1d74ac8ff902a267de69ce19/src/api/java/baritone/api/Settings.java#L304)
