### ISSUE TITLE
I have encountered many, many bugs

### ISSUE THREAD

**Issue by IcyHex** [cabaletta/baritone#452]
I don't know how many of these are already known but here goes.

1. When I sleep in a bed the game crashes. I have a crash report if needed.
2. When traveling through a nether portal I have to restart my game because of mysteriously appearing solid "air" blocks.
3. I am completely unable to ride boats, minecarts, horses, and pigs. When I try to, my game bugs out.
4. AutoReconnect has yet to ever function the way it is meant to, always giving me the message "Aborted".

These are all the bugs I have encountered as of now but to a standard survival world, these functions are very important to succeeding (i.e. riding horses and using nether portals)

**Comment by 2b2tQueueProject** [comment]
This is obviously an impact issue. The nether portal issue is linked to Impact's Portal God Mode feature. The others probably have no correlation to baritone.

**Comment by IcyHex** [comment]
I was told to make a report here.

**Comment by ZeroMemes** [comment]
If this is purely related to Impact, it belongs on the [Impact issues](https://github.com/ImpactDevelopment/ImpactClient/issues) and not here.
