### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Cai-kunkun** [cabaletta/baritone#4544]
I need source code to build but github said 404 Not Found,so I ask anyone has the source code for Minecraft 1.20.4?

**Comment by forkgenesis** [comment]
It is located at [https://github.com/cabaletta/baritone/tree/1.20.4](this) page. To clone this branch with Git, you can use the command:
`git clone https://github.com/cabaletta/baritone.git -b 1.20.4`

**Comment by Cai-kunkun** [comment]
Oh thanks,resolved.
