### ISSUE TITLE
flying without fireworks

### ISSUE THREAD

**Issue by sGrif0N** [cabaletta/baritone#4549]
how to fly on elitras through baritone without fireworks if the cheat for flying on elytra is enabled

**Comment by ZacSharp** [comment]
That's not intended usage.
https://github.com/cabaletta/baritone/blob/93dee4fd19600d5ad86e0df9f35ff1a0b8574a27/src/main/java/baritone/command/defaults/ElytraCommand.java#L131

**Comment by sGrif0N** [comment]
> Это непреднамеренное использование.
> 
> https://github.com/cabaletta/baritone/blob/93dee4fd19600d5ad86e0df9f35ff1a0b8574a27/src/main/java/baritone/command/defaults/ElytraCommand.java#L131

I found how to do it, you just need to change a couple of settings

**Comment by flurixoww** [comment]
Could you please say which exactly? It would be really nice

**Comment by GitAhmad304** [comment]
> > Это непреднамеренное использование.
> > 
> >   
> >     
> >       [baritone/src/main/java/baritone/command/defaults/ElytraCommand.java](https://github.com/cabaletta/baritone/blob/93dee4fd19600d5ad86e0df9f35ff1a0b8574a27/src/main/java/baritone/command/defaults/ElytraCommand.java#L131)
> >     
> >     
> >          Line 131
> >       in
> >       [93dee4f](/cabaletta/baritone/commit/93dee4fd19600d5ad86e0df9f35ff1a0b8574a27)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            gatekeep.append("Baritone Elytra is an experimental feature. It is only intended for long distance travel in the Nether using fireworks for vanilla boost. It will not work with any other mods (\"hacks\") for non-vanilla boost. ");
> 
> I found how to do it, you just need to change a couple of settings

How do you do it? Which settings do you change?
