### ISSUE TITLE
baritone for 1.14+ versions

### ISSUE THREAD

**Issue by Mhowser** [cabaletta/baritone#455]
Will you switch over to [FabricMC](https://www.fabricmc.net/)?

**Comment by leijurv** [comment]
nope!

**Comment by Mhowser** [comment]
damn ok

**Comment by leijurv** [comment]
i mean 1.14.2 branch is started... but its just normal mcp stuff lol

no fabric

**Comment by Mhowser** [comment]
do you not like fabric?

**Comment by 0-x-2-2** [comment]
cringeic
