### ISSUE TITLE
Making item command

### ISSUE THREAD

**Issue by Cruz808** [cabaletta/baritone#4551]
A command for making an item would be a cool feature, you could put in a command like #make minecraft:blue_bed, and baritone would go and get all the resources for the item and put them together
It would be helpful to have a value you can set for how many of that item you can make
This would be a very nice quality of life feature

**Comment by ZacSharp** [comment]
Getting the resources is not just a nice quality of life feature. It's a very complex feature and takes a lot of effort to implement. Just crafting an item from resources you already have is realistic, gathering resources beforehand is too much.
It is possible for sure, but Baritone won't have this feature any time soon.
