### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Ripley-art** [cabaletta/baritone#4566]
## Some information
Operating system: Windows 10
Java version: Java8
Minecraft version: 1.16.5
Baritone version: 1.6.5
Other mods (if used): Better sprinting, Byg, Embdeddium, ferritecore, geckolib, Jei, journey map, lightfall-client, malilib, mojankbypass, oculus, pixelmon, shulkerbox, watermedia

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows: 
[2024-11-22-1.log.gz](https://github.com/user-attachments/files/17867408/2024-11-22-1.log.gz)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Juste try ti out a command like Mine or Goto and Baritone will juste do nothing

## Modified settings
Nothing

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The log doesn't contain any trace of Baritone being present.
Besides that, 1.16 is not supported anymore.
