### ISSUE TITLE
How to change the dirt as the block used to cross the void?

### ISSUE THREAD

**Issue by marselow** [cabaletta/baritone#4567]
Im playing in a server with a skygrid map, I want to farm a specefic block there with #mine but Dirt isnt a cheap block there so i would like to change the block used to go to the block that I want to farm.

**Comment by wagyourtail** [comment]
`#set acceptableThrowawayItems cobblestone` https://github.com/cabaletta/baritone/blob/497fb74829febf5bcf48732fa03abb3b90662dcb/src/api/java/baritone/api/Settings.java#L213
