### ISSUE TITLE
Can't downlad.

### ISSUE THREAD

**Issue by William69420420** [cabaletta/baritone#457]
I know I'm probably missing some key point. But I've tried downloading Baritone for Forge 1.12.2. It does not work. I've tried both stand alone and the normal one. I can't install Impact because the download link isnt working.

Thanks

**Comment by William69420420** [comment]
downloaded impact from a sketchy website. would still like to have just Baritone on forge though. Also Bariton created its own folders, but doesnt work anyway.

**Comment by leijurv** [comment]
Baritone forge jar for 1.12.2 definitely does work, it just won't show up in your mods folder since its sneaky. Did you look at https://github.com/cabaletta/baritone/blob/master/USAGE.md ?

Impact's website isnt sketchy im offended you would say such a thing =P

**Comment by William69420420** [comment]
I'm not saying Impacts website is sketchy. Their download link doesnt work. The only download I could find was from a sketchy mc hacks website, which didn't have any versions with baritone unfortunately. None of the commands work when I tried using forge.

**Comment by leijurv** [comment]
heres a link that bypasses the stupid adfly https://impactdevelopment.github.io/?brady-money-grubbing-completed=true

**Comment by William69420420** [comment]
Reinstalled Forge and now it works. Huh. Also the address I was being sent to by clicking windows download took me to a non existant website. Thank you for the help anyway.
