### ISSUE TITLE
How to show blocks through the wall?

### ISSUE THREAD

**Issue by marselow** [cabaletta/baritone#4571]
is there any way to show blocks like it is shown when we use #mine but w/o going to it automatically?

**Comment by Avtera** [comment]
#goal x y z

**Comment by marselow** [comment]
this is for saving a place that i want to go, i want to use like a xray..

**Comment by ZacSharp** [comment]
It's not meant to be an xray. If you want to store coordinates there's `#waypoint`

**Comment by marselow** [comment]
so theres no way to use it like a xray?

**Comment by ZacSharp** [comment]
You can do things like `#goto minecraft:oak_log` immediately followed by `#pause`.

**Comment by marselow** [comment]
it helped me a lot, im using now #mine [...] and soon after #pause :)
