### ISSUE TITLE
An unexpected error occurred (Building with litematica)

### ISSUE THREAD

**Issue by KiritoBlu** [cabaletta/baritone#4575]
## Some information
Operating system: Win11 64 bit
Java version: Version 8 Update 431 Build 1.80_431-b10
Minecraft version: 1.21.1
Baritone version: baritone-api-fabric-1.10.2-9-g3b01f129 | baritone-standalone-fabric-1.10.2-9-g3b01f129
Other mods (if used): 
Labymod 4, 
FabricLoader, 
litematica-fabric-1.21-0.19.52
malilib-fabric-1.21-0.21.2, 
freecam-fabric-1.3.0+mc1.21, 
fabric-api-0.104.0+1.21.1, 
CustomBlocks-1.21.1-1.1.0,
cloth-config-15.0.140-fabric

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows log attached
[latest.log](https://github.com/user-attachments/files/18002686/latest.log)

## How to reproduce
Load Schematic via litematica menu
Using #litematica do  start building
Error appears

## Modified settings
breakfromabove
buildinlayers
itemsaver

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This is a known problem and a fix is on its way. (Currently merged to 1.19.4 and 1.20.6, 1.21 will hopefully happen this weekend)
