### ISSUE TITLE
#Litematica doesnt work

### ISSUE THREAD

**Issue by Ethan929-ux** [cabaletta/baritone#4577]
## Some information
Operating system: Windows 11 Home
Java version: Version 8 Update 431 (build 1.8.0_431-b10)
Minecraft version: 1.21.3
Baritone version: standalone fabric 1.11.1
Other mods (if used):  appleskin, iris, jade, litematica, malilib, sodium

[latest.log](https://github.com/user-attachments/files/18050043/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

i tried litematica and it didnt work because i didnt put a placement so i did and then tried litematica again and it said "An unhandled exception occured" and then how to report it

## Modified settings

acceptableThrowawayItems
ElytraAutojump
elytraTermsAccepted

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Known issue, with a fix already on its way to 1.21

**Comment by Ethan929-ux** [comment]
ok thx
