### ISSUE TITLE
how to get baritone to ignore new target 

### ISSUE THREAD

**Issue by itsmobsys** [cabaletta/baritone#4578]
i want baritone to ignore new target poping like if i type #sel cleararea and if it shows it need to destroy only 20 block and if i place a block from another account then the target should be 20 only not increase to 21

**Comment by ZacSharp** [comment]
There is no setting or similar to achieve this. The builder does not work through a list of required changes but rather continuously searches for differences between the world and the schematic it is building.
I also do not know any workaround to achieve this.
