### ISSUE TITLE
Does baritone have an inventory checker to stop when full?

### ISSUE THREAD

**Issue by Madcept** [cabaletta/baritone#4582]
Basically. mining diamonds. My whole inventory is full and cannot pick up anymore diamonds. Baritone keeps mining and loses those diamonds I cannot pickup due to a full inventory. Does Baritone have a command where it can check my inventory to see if it is full and automatically stop mining.

King Regards,
Madcept.

**Comment by hammyongithub** [comment]
What i usually do is just spread the diamonds in my inventory, to reserve slots for them.

**Comment by Madcept** [comment]
> What I usually do is just spread the diamonds in my inventory, to reserve slots for them.

Damn bro, ur smart XD. I remember using baritone a little while ago and it auto stopping when my inventory was full. That's why I was asking

**Comment by ZacSharp** [comment]
Baritone itself cannot stop once your inventory is full. It can mine until you have a specific amount of diamonds, or you can use a macro mod to stop it.
