### ISSUE TITLE
The Addition of Platform Creation

### ISSUE THREAD

**Issue by zanderlewis** [cabaletta/baritone#4588]
## Describe your suggestion
It would be great if Baritone was able to create platforms (like large flat platforms) using specific blocks or any block available.

## Settings
-

## Context
This would improve Baritone, for people who make large platforms in gamemodes like Skyblock, would want to not spend a long time doing tedious block placement, with the threat of falling off.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You mean `#sel fill <block>`?

**Comment by zanderlewis** [comment]
> You mean `#sel fill <block>`?

Ok, I didn't know if it was already there, because I didn't see it. Thanks!
