### ISSUE TITLE
unable to use #litematica

### ISSUE THREAD

**Issue by big-boluptuous-boy** [cabaletta/baritone#4593]
## Some information when i use "#litematica" it gives me the error "An unhandled exception occurred. the error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues"

Operating system: Windows 11
Java version: 1.21.3
Minecraft version: 1.21.3
Baritone version: 20241117.084726-1
Other mods (if used): Litematica-fabric 0.20.2-sakura.9, meteor-client 0.5.9-2213, ViaFabricPlus-3.5.3

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue      [2021-05-16-1.log.gz](https://github.com/user-attachments/files/18254420/2021-05-16-1.log.gz)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.      type '#litematica' and hit enter

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Abduboriy1** [comment]
Same issue here

**Comment by ZacSharp** [comment]
This is a known issue and the fix already made it's way to the 1.21.1 branch. Merging to 1.21.4 will follow shortly.
