### ISSUE TITLE
where is the 1.21.4 version

### ISSUE THREAD

**Issue by MrViPPer1** [cabaletta/baritone#4594]
i installed the current version but when i run it with fabric i got this, i also have other mods 80+ and windows 11
![image](https://github.com/user-attachments/assets/5e27d4b3-4974-40b7-ba73-68fc50bd455e)

**Comment by MrViPPer1** [comment]
its working now i got it form here https://www.9minecraft.net/baritone-client-mod/

**Comment by babbaj** [comment]
9minecraft is a scam website

**Comment by ZacSharp** [comment]
There is no release for 1.21.4, however there are [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.4+is%3Asuccess+event%3Apush) for that version. Pick the latest entry from the list and download the "Artifacts" file at the bottom of the page. (Note: you have to be logged in and the artifacts expire after 90 days).

**Comment by FatihYagci** [comment]
CI Builds didn't work for me. when is this getting updated?

**Comment by hmlendea** [comment]
I think there should be alpha/beta/whatever releases specifically so that people have to rely to scam websites to obtain current versions.

For certain people it's easy and straightforward to get them from CI, but for the average Joe it's very inacessible and unintuitive.

**Comment by SlinkyBuky** [comment]
Thanks for this, I used the ci build for my 1.21.4 modpack and it's finally working!

**Comment by zamankumbarasi** [comment]
> There is no release for 1.21.4, however there are [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.4+is%3Asuccess+event%3Apush) for that version. Pick the latest entry from the list and download the "Artifacts" file at the bottom of the page. (Note: you have to be logged in and the artifacts expire after 90 days).

When i download it from Artifacts, it says settings file not found resetting error. Do you know any fix for that?

**Comment by ZacSharp** [comment]
Unless you previously changed a setting that's expected behavior. It will always log that line if it doesn't have a settings file and will not create the settings file unless there are modified settings.

**Comment by MuAhSi** [comment]
whenever i try to use baritone for 1.21.4 it shows this error, i have 68 mods and windows 11

![Image](https://github.com/user-attachments/assets/b78cea64-f727-4bc7-bea9-84ab6e2b1fe5)

this also applies to other commands

**Comment by SlinkyBuky** [comment]
you typed it incorrectly, just type #goto or #follow in the chat box, or if you use an older version use .b goto

**Comment by ZacSharp** [comment]
As far as I know there are no Baritone versions accepting ".b" as a prefix, just hack clients with a ".b" command which forwards all its arguments to Baritone.

**Comment by MuAhSi** [comment]
Thanks for the clarification.

**Comment by Briacoo** [comment]
> There is no release for 1.21.4, however there are [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.4+is%3Asuccess+event%3Apush) for that version. Pick the latest entry from the list and download the "Artifacts" file at the bottom of the page. (Note: you have to be logged in and the artifacts expire after 90 days).

When Artifact is outdated how i can dl another one ?

**Comment by SlinkyBuky** [comment]
> > There is no release for 1.21.4, however there are [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.4+is%3Asuccess+event%3Apush) for that version. Pick the latest entry from the list and download the "Artifacts" file at the bottom of the page. (Note: you have to be logged in and the artifacts expire after 90 days).
> 
> When Artifact is outdated how i can dl another one ?

I'm not sure if you can

**Comment by ZacSharp** [comment]
You can make one yourself by creating a GitHub fork of this repository, enabling actions for your fork and editing any file in it.

A new build in this repository will also be available tomorrow.

**Comment by DaggerInput** [comment]
> You can make one yourself by creating a GitHub fork of this repository, enabling actions for your fork and editing any file in it.
> 
> A new build in this repository will also be available tomorrow.

So 1.21.5 is releasing tmr?

**Comment by ZacSharp** [comment]
1.21.5 will release whenever. There is currently a known problem  in the implementation (which will vanish once I get the current set of merges done).

Also I have to revoke that statement about a new build being available today. I misjudged the amount of testing I can get done today. With some wishful thinking I'll be done tomorrow, but honestly finishing on the weekend is more realistic.
(I'm currently porting all the new features from the last couple months to 1.20/1.21, that's a bit more effort than just triggering CI)

**Comment by ZacSharp** [comment]
Release for 1.21.5 potentially delayed further because there is a somewhat serious bug (elytra auto-takeoff kills you on 1.21.4), but there is a set of fresh CI builds now, downloadable for the next 3 months (for all versions from 1.19.4 up to and including 1.21.4).

The list of successful CI builds excluding those from pull requests is [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush%20is%3Asuccess). Just pick one from the appropriate branch (1.20.1/1.20.4/1.20.5/1.21.1/1.21.4 should also work for 1.20/1.20.3/1.20.6/1.21/1.21.3), download the "Artifacts" file and unzip it, as usual.

**Comment by ZacSharp** [comment]
Baritone v1.14.0 for Minecraft 1.21.5 is released.

**Comment by Iplantedtrees** [comment]
i dowloaded the artifact but i dont know what to do with the files.
do i just use 1 .jar file or all in the mods folder. Thanks


> Baritone v1.14.0 for Minecraft 1.21.5 is released.

**Comment by Amnessie** [comment]
> Release for 1.21.5 potentially delayed further because there is a somewhat serious bug (elytra auto-takeoff kills you on 1.21.4), but there is a set of fresh CI builds now, downloadable for the next 3 months (for all versions from 1.19.4 up to and including 1.21.4).
> 
> The list of successful CI builds excluding those from pull requests is [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush%20is%3Asuccess). Just pick one from the appropriate branch (1.20.1/1.20.4/1.20.5/1.21.1/1.21.4 should also work for 1.20/1.20.3/1.20.6/1.21/1.21.3), download the "Artifacts" file and unzip it, as usual.

Could you be so kind to add 1.21.4 to the list or update the cl builds so they are not expired. Thank you so much!

**Comment by Draogn12345678** [comment]
idk i just used this it worked for me: https://github.com/cabaletta/baritone/releases
use the V1.13.1
