### ISSUE TITLE
[Suggestion] Shift click containers while building schematic, UP command to stack up, while building schematic pay attention to block orientation

### ISSUE THREAD

**Issue by Darkness1337** [cabaletta/baritone#463]
Hello, i would like to request the above features, when building a schematic it will not shift click containers causing it to loop into an inventory, there is no up command so stacking up automatically is not possible, when building a schematic it will not pay attention to block orientation, placing dispensers the wrong way.
Thanks

**Comment by scorbett123** [comment]
Paying attention to block orientation is a duplicate, is an up command really needed? and shift clicking containers I think has been suggested somewhere else already.

**Comment by ZacSharp** [comment]
`#goto ~ ~<n> ~` is already an up command and the builder sneaks when placing any block (probably changed since this was opened)
