### ISSUE TITLE
Player dying when walking into water

### ISSUE THREAD

**Issue by Jss05** [cabaletta/baritone#466]
I just downloaded impact wich comes with baritone, and i set it to autowalk, i set the goal 1000 blocks away, and off he goes. but when he come to a little bit of water, he wanted to swim in it, but at the moment he walks into the water he instantly dies. i tested it a few times and sometimes he took damage and sometimes he just instandly dies. and also he doesnt respond to "stop" or "cancel".
![Minecraft 1 13 2 05_07_2019 12_19_34](https://user-images.githubusercontent.com/52567460/60716276-3ac06280-9f1f-11e9-8e61-b009e482b76d.png)

**Comment by usereewrjrjeejr** [comment]
Use anti-hunger smart

**Comment by usereewrjrjeejr** [comment]
`.b stop`

**Comment by Jss05** [comment]
ah thanks
