### ISSUE TITLE
fell from a high place bug?

### ISSUE THREAD

**Issue by Despairgs** [cabaletta/baritone#467]
Might be an impact 4.6 bug, but sometimes you randomly take damage when you walk down onto an another block, When walking near water blocks or go into the water you can die reason being "fell from a high place".
![2019-07-05_15 37 47](https://user-images.githubusercontent.com/52571129/60723060-4caffe80-9f3b-11e9-9d73-ed446f89f8e9.png)

**Comment by Zamazenta** [comment]
Looks like an antihunger issue aka impact issue to me

**Comment by Th3nd** [comment]
turn off antihunger

**Comment by usereewrjrjeejr** [comment]
Use anti-hunger smart

**Comment by leijurv** [comment]
Impact issue, fixed for next impact release 4.7
