### ISSUE TITLE
Program crashes when mining

### ISSUE THREAD

**Issue by kiikoh** [cabaletta/baritone#468]
I had it run while trying to grab iron ore. It encountered gravel then crashed. I was given a null pointer exception I think because it mined the gravel below another causing it to fall then tried to hit the block above it.

**Comment by leijurv** [comment]
Possible duplicate of #443? If so, it's fixed for next release

**Comment by ZeroMemes** [comment]
>I was given a null pointer exception

Can you provide the full crashlog? @kiikoh

**Comment by kiikoh** [comment]
> Possible duplicate of #443? If so, it's fixed for next release

yes its fixed
