### ISSUE TITLE
Game crashs while baritone is used in impact client and when future is installed

### ISSUE THREAD

**Issue by gmcdaniel7111** [cabaletta/baritone#470]
im trying to use impact(mainly baritone) with future client so i can use the amazing features of baritone, but im having trouble getting it to load in forge, i get this crash report (i use a few other mods including inventory tweaks, not sure if i should go to futures devs for help or impacts, of baritones

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (KAMI-b9-release.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 7/5/19 9:19 PM
Description: Initializing game

java.lang.NoSuchMethodError: baritone.api.IBaritoneProvider.getPrimaryBaritone()Lbaritone/api/IBaritone;
	at me.zero.clarinet.Impact.r(Impact.java:19)
	at clientapi.aj.r(aj.java:11)
	at net.minecraft.client.Minecraft.handler$init$zcj000(Minecraft.java:4355)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:569)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zero.clarinet.Impact.r(Impact.java:19)
	at clientapi.aj.r(aj.java:11)
	at net.minecraft.client.Minecraft.handler$init$zcj000(Minecraft.java:4355)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:569)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 408496768 bytes (389 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                      | Signature                                |
	|:------ |:------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft     | 1.12.2       | minecraft.jar                               | None                                     |
	| UCHIJA | mcp           | 9.42         | minecraft.jar                               | None                                     |
	| UCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | journeymap    | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar                 | None                                     |
	| UCHIJA | kami          | b9           | KAMI-b9-release.jar                         | None                                     |
	| UCHIJA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (KAMI-b9-release.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4771' Renderer: 'Intel(R) HD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4771, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful+1.12.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by 0-x-2-2** [comment]
it would seem like you don't have baritone or the correct version of baritone installed that impact requires 🤔. You can also use baritone on forge without impact.

https://github.com/cabaletta/baritone/releases/download/v1.2.6/baritone-standalone-forge-1.2.6.jar

**Comment by leijurv** [comment]
dont make sense because baritone is shadowed into impact forge...

**Comment by gmcdaniel7111** [comment]
i tryed using the standalone version of baritone and forge didnt recognize it

**Comment by gmcdaniel7111** [comment]
yea i just put baritone into the mods folder and it wasnt recognized

**Comment by TypicalHog** [comment]
@gmcdaniel7111 It will not be on the list of installed mods for you can still use it ingame, at least in my experience.

**Comment by 0-x-2-2** [comment]
> yea i just put baritone into the mods folder and it wasnt recognized

it wont show in the mods list make sure you use #help in chat to test.

**Comment by gmcdaniel7111** [comment]
ok

**Comment by gmcdaniel7111** [comment]
alright, it works, thanks guys

**Comment by gmcdaniel7111** [comment]
i didnt know the default prefix was #486

**Comment by gmcdaniel7111** [comment]
is there a way to change the prefix?

**Comment by CUPZYY** [comment]
just use #prefix [prefix u want]
