### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AlphaMaBeta** [cabaletta/baritone#472]
Make it so it can speed bridge (shift > place block > unshift > repeat)

**Comment by NOP** [comment]
iirc, the purpose of baritone is for navigation. Many clients (including Impact) already feature "scaffolding", as you suggest.

**Comment by AlphaMaBeta** [comment]
No shit but it would be way more legit and it would be hard to detect, with scaffolding it’s obvious

**Comment by leijurv** [comment]
I mean it literally does do this?
