### ISSUE TITLE
Few things that I am unsure of

### ISSUE THREAD

**Issue by DistantFoSho** [cabaletta/baritone#473]
1: Is there a way to rotate the direction of the schematic I select to build?
2: Is there a way to make baritone fight off mobs/eat food while performing a task?
3: Whilst experimenting on 2b2t I decided to try and remove some cobblestone monsters with the mine cobblestone command which after 1-2 minutes baritone just enters a state where it does nothing. (Using future if that matters but none of the hacks on or off seem to help in any way). Any way of fixing this?

**Comment by gmcdaniel7111** [comment]
for the eating food part, i suggest if youre using impact client, to use autofood/eat and set it to however many hungerbars your food item replenishes

**Comment by S-B99** [comment]
1. use schematica's options
2. #496
3. make a bug report
