### ISSUE TITLE
Extreme lag when using farm in an amplified world

### ISSUE THREAD

**Issue by TypicalHog** [cabaletta/baritone#479]
When I do "farm" on an amplified singleplayer world near a village my FPS drops to 1 and I need to kill the game from the task manager. Every other command works fine, farm worked fine on a server as well. Baritone v1.2.6 Forge

**Comment by StijnSimons** [comment]
This is fixxed.

**Comment by TypicalHog** [comment]
> This is fixxed. (Can’t reproduce)
> Let me know if it isn’t.

I don't know. I figured that it's fine if I'm close to crops, but when I'm far (150+) blocks then my game drops to below 10 FPS, often way lower.

**Comment by usereewrjrjeejr** [comment]
Fixed in 4.7 

>Any other lag is caused by the map being in an amplified world
