### ISSUE TITLE
quartz_ore isn't a valid block name

### ISSUE THREAD

**Issue by Malogna** [cabaletta/baritone#483]
I find this very weird, but baritone doesnt find quartz_ore to be a vaild block.
Hoping that this is a simple fix.
![image](https://user-images.githubusercontent.com/12765308/60769035-90d20900-a0cb-11e9-9819-20e83d2bd642.png)

**Comment by 0-x-2-2** [comment]
user error.

```
1.13 | 17w47a | The ID has been changed from quartz_ore to nether_quartz_ore.
```

**Comment by Malogna** [comment]
> user error.
> 
> ```
> 1.13 | 17w47a | The ID has been changed from quartz_ore to nether_quartz_ore.
> ```

haha fck im stupid. closed
