### ISSUE TITLE
pathing doesn't properly account for player heads and tries to walk through them

### ISSUE THREAD

**Issue by scottbeebiwan** [cabaletta/baritone#485]
![image](https://user-images.githubusercontent.com/38970930/60769953-a8d56880-a08a-11e9-86f6-91e6d31a99a6.png)

**Comment by ZeroMemes** [comment]
Tested, and can confirm only happens on the 1.13.2 version.

**Comment by ZeroMemes** [comment]
Only happens to skulls that are attached to walls because of the separation between floating and wall skulls.

**Comment by ZeroMemes** [comment]
Fixed by c7e1c917c34cf96e6c6ab18dbf9a01c51e5fb678
