### ISSUE TITLE
1.14.3

### ISSUE THREAD

**Issue by mpg0907** [cabaletta/baritone#486]
is it possible to get this working for 1.14.3

**Comment by KingTheCommie** [comment]
of course you just have to make some adjustments. Im currently trying to make it work for 1.14.2

**Comment by mpg0907** [comment]
ok good to know  when do you think that the 1.14.3 is out?

**Comment by KingTheCommie** [comment]
I have no clue. I would recommend just building it but if you don't want to do that then I think you will have to wait some time

**Comment by mpg0907** [comment]
how do i build it myself?

**Comment by KingTheCommie** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself

**Comment by mpg0907** [comment]
thanks

**Comment by KingTheCommie** [comment]
hope that help :)

**Comment by mpg0907** [comment]
is the thign only for the mac cous ei cant get it working

**Comment by mpg0907** [comment]
why did you referenced that

**Comment by KingTheCommie** [comment]
It should tell you what to do right? Did I send the wrong thing

**Comment by mpg0907** [comment]
ill just wait till 1.14.3 is there

**Comment by 0-x-2-2** [comment]
afaik baritone is not updated to 1.14

**Comment by mpg0907** [comment]
just curius is it possible that someone doese the build thing and then set it for dowload

**Comment by brendenderp** [comment]
I as well am trying to do the same thing. but cant get the thing to build properly.

**Comment by MrHud2** [comment]
If anyone fixes it for 1.14.3 can you post it in here as I am also interested. I may go give it a go myself.

**Comment by FireyHotPotatoe** [comment]
I have built baritone for 1.12 but I don't know how to make it 1.14.3

**Comment by StijnSimons** [comment]
`git checkout 1.14.3`

**Comment by FireyHotPotatoe** [comment]
I don't know what that is

**Comment by StijnSimons** [comment]
Its git??
Please don’t try without knowing what you’re doing. The 1.14 branch is ~20 commits behind, its not worth building. Just stick to what __is__ working right now.

**Comment by FireyHotPotatoe** [comment]
ok

**Comment by bobross135** [comment]
if you install arstois load it up and go to aristois addon mods there is a built version that you can download that works with the client

**Comment by leijurv** [comment]
1.14.4 is released

**Comment by bobross135** [comment]
the person was asking for 1.14.3 not 1.14.4

**Comment by leijurv** [comment]
Closed anyway since I'm not going to do that.
