### ISSUE TITLE
Add a way to change the Baritone command prefix

### ISSUE THREAD

**Issue by gmcdaniel7111** [cabaletta/baritone#487]

**Comment by 0-x-2-2** [comment]
no

**Comment by leijurv** [comment]
I mean the answer is no rn, but maybe it's a valid suggestion

**Comment by ZacSharp** [comment]
Do you mean `#prefix <newPrefix>`?

**Comment by dominikaaaa** [comment]
This is now added.

**Comment by melcl** [comment]
Yes, just enter "prefix new value" in the chat bar
