### ISSUE TITLE
game crashes when sand is mines

### ISSUE THREAD

**Issue by the-ragin-pyro** [cabaletta/baritone#491]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm...

fix it, i need to clear a desert. and im not doing it manually

also its a server, anarchy

**Comment by 0-x-2-2** [comment]
Dupe of fixed issue #443. Update baritone and try again.

**Comment by AlexApps99** [comment]
@the-ragin-pyro please close this issue if the problem is resolved. thanks
