### ISSUE TITLE
[Suggestion] Baritone should look in the direction he is heading

### ISSUE THREAD

**Issue by TypicalHog** [cabaletta/baritone#492]
It's kinda annoying when baritone goes forward and looks backward or at their feet. There should be a toggleable option that would make Baritone look the where he is going, for example, he would look at the points where the path changes direction, but at the eye level.

**Comment by Jo10843** [comment]
if I'm reading you correctly, the command #freelook should be what you are looking for

**Comment by ZeroMemes** [comment]
Correct, by default "freelook" is enabled. You can toggle it by typing either `.b freelook` (with Impact) or `#freelook` in chat.
