### ISSUE TITLE
"goto portal" doesent work

### ISSUE THREAD

**Issue by Dacred** [cabaletta/baritone#493]
unable to parse integer
java.lang.NumberFormatException: For input String: "portal"

![grafik](https://user-images.githubusercontent.com/13298507/60813985-166dbb80-a195-11e9-9b58-e45ec1ea2ea0.png)

everything else works fine
(Impact 1.12.2 & 1.13.2)

**Comment by Deauthorized** [comment]
use goto minecraft:portal

**Comment by scottbeebiwan** [comment]
i don't know if you can goto blocks, but the portal ids are minecraft:nether_portal and minecraft:end_portal.
afaik you need to `#save portal` to save a place called "portal", _then_ you can `#goto portal`

**Comment by leijurv** [comment]
Do not do `#save portal`

In 1.13 iirc it was renamed to `nether_portal`, in 1.12 i'm certain that `#goto portal` works
