### ISSUE TITLE
[Suggestion]Could it have the PvP Function?

### ISSUE THREAD

**Issue by iiijam** [cabaletta/baritone#494]
Could it have the PvP Function?

**Comment by usereewrjrjeejr** [comment]
It has

**Comment by TypicalHog** [comment]
> It has

Really, how?

**Comment by usereewrjrjeejr** [comment]
Hunt under combat

**Comment by StijnSimons** [comment]
Should be at Impacts’ issues. Baritone is just the API for clients to help them do stuff automatically.

**Comment by 0-x-2-2** [comment]
> Should be at Impacts’ issues. Baritone is just the API for clients to help them do stuff automatically.

Objectively false.

**Comment by StijnSimons** [comment]
oooof i tought it was, never noticed. Soz

**Comment by AlexApps99** [comment]
@huohei250894 Please close this issue as it's not under the scope of baritone, contact the developer of your preferred client and ask them to implement a similar feature.
