### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Username0516** [cabaletta/baritone#497]
I saw some footage and I see that they could cut corners, do different routes that don't involve straight jumps that are faster. For example, if there is a 3x10 hallway, and u wanna go through it and go outwards on the left side from entering the right side, it is faster to walk directly towards the left side exit after doing a sharp cut from the right side of the entrance. This allows you to do sharp cuts and make a straight route without having and awkward diagonal turn in the middle.  I also think it should incorporate jumping. I believe it should be more focused on how you get there and more so focused on speed. However, I don't think it should recklessly jump unless it calculates it can do it without starving (or close to starving). I also see that it does inefficient routes when going down cliffs. If you want the best possible, it would jump down and land on the very edge of a block just to jump again to gain the most distance. I also see that the ai doesn't consider parkour diagonally or very specific jumps, it only does straight jumps. It could jump on where a bridge turns to skip the process of going to the corner.  However, these suggestions are dealing with smaller units and I recognize that it would take too many calculations. So maybe just smooth out the top 3 paths or even the bets one. Maybe even subtract some time when it spots certain conditions. I also suggest monstrous 6 block jumps, maybe even higher and when it is midair, it places the blocks accordingly to make the jump when it falls. If you still have some computing power left and u refined everything perfectly, you could consider the otherwise impossible pathways that take blocks when the ai doesn't have any and then calculate if getting blocks and using them would be faster. If it requires a lot of blocks, it could mine trees and craft them. However, if as soon as it calculates it would take more time, it would stop to save computing power. Maybe even consider going off course a little bit to collect food the ai is hungry or doesn't have any food at all. Ofc, food conservation and collection should be a setting. I could go on and on but these are the main things I noticed and wanted to suggest.

**Comment by 0-x-2-2** [comment]
what the fuck is this. can you not suggest more then one thing in the same issue.

**Comment by Username0516** [comment]
You want me to make 18 different suggestion threads?

**Comment by 0-x-2-2** [comment]
well you can at least clean up the issue because this is all in one paragraph.

**Comment by usereewrjrjeejr** [comment]
🤢<----- this issue

**Comment by Username0516** [comment]
Okay, basically make it faster and more flexible. That's what I'm saying.
