### ISSUE TITLE
[question] is there a feature which joins multiple bot accounts which follow commands

### ISSUE THREAD

**Issue by Deauthorized** [cabaletta/baritone#498]
saw it in a video once, just wanna see if that's an actual thing

**Comment by ZeroMemes** [comment]
The [bot-system](https://github.com/cabaletta/baritone/tree/bot-system) branch contains incomplete experimental code to perform what was shown in the video.

**Comment by dolphin-cat** [comment]
what video did you saw?, is it fitmc 2b2t: MAN VS MACHINE
