### ISSUE TITLE
building schematics

### ISSUE THREAD

**Issue by reirei5567** [cabaletta/baritone#499]
i wouldn't know where to start with the schematic building other then downloading the schematic, things such as Where do i put the schematic? is there any other steps to this?

**Comment by kyppen** [comment]
In your minecraft folder you create a new folder called Schematics.
Then you can load the schematic ingame by typing #Build name

**Comment by CalebD07** [comment]
It should be /build [project_name]

**Comment by CalebD07** [comment]
Based on the structure of Minecraft commands.

**Comment by usereewrjrjeejr** [comment]
It's .b build name

**Comment by ZeroMemes** [comment]
> It's .b build name

That is explicitly for usage with Impact.

In order to build schematics, put the schematic in your `.minecraft/schematics` directory, and then refer to it just by the name, excluding the extension.

For example: If I have a schematic that's located under `.../.minecraft/schematics/test.schematic` I can type `#build test` in chat in order to build it relative to my player's current position.

You may also specify the coordinates to build from, for example: `#build test 321 68 -231`

**Comment by Yeetmyo** [comment]
I have this file for the schematic but when I ask to build it in game. it says extension. what does extension mean?
![image](https://user-images.githubusercontent.com/80555439/112480906-72390780-8db1-11eb-82d0-27d6b1449c68.png)
![image](https://user-images.githubusercontent.com/80555439/112481173-b1ffef00-8db1-11eb-8b89-bbb84700d366.png)

**Comment by scorbett123** [comment]
extension means for example, .schematic at the end.

for example, to build the 2b2t jesus you would need to do 2b2t-jesus.schematic

**Comment by Yeetmyo** [comment]
I am not sure why is it like this ![image](https://user-images.githubusercontent.com/80555439/112556574-768f1000-8e05-11eb-84e7-b4ef8fdf12c3.png)

**Comment by wagyourtail** [comment]
commas

**Comment by Yeetmyo** [comment]
Thanks for you help but still not working
![image](https://user-images.githubusercontent.com/80555439/112561578-7d6f5000-8e10-11eb-8f46-21394d745191.png)

**Comment by scorbett123** [comment]
I believe that there shouldn't be any commas at all.

**Comment by Yeetmyo** [comment]
![image](https://user-images.githubusercontent.com/80555439/113430166-48fd2480-940c-11eb-8be1-97fb6a634829.png)
I kind of give up. But thanks for the help

**Comment by scorbett123** [comment]
#build "japanese house.schematic" 159 68 338 

is the correct usage for this command.

**Comment by Yeetmyo** [comment]
![image](https://user-images.githubusercontent.com/80555439/113464530-eb92c300-945f-11eb-9f6c-f5d20d25b3e6.png)
 can't

**Comment by Yeetmyo** [comment]
but scottbett thank for helping me soo much

**Comment by scorbett123** [comment]
What are you doing, if you haven't renamed the file make sure to do

#build "japanesehouse-e700 (1).schem" 159 68 338

**Comment by Yeetmyo** [comment]
![image](https://user-images.githubusercontent.com/80555439/113479434-b15a0d80-94c1-11eb-8e5b-1946a96fff6e.png)
Yeah

**Comment by l1ving** [comment]
you still did it wrong

**Comment by scorbett123** [comment]
Make sure to put the " 's in

**Comment by Dam-Buty** [comment]
And i just noticed there's even a typo in `Baritone` in in yeet's screenshots, should i suspect a troll ?

**Comment by Flurrrr** [comment]
That is an April fools joke hard coded into baritone, it is a troll but not from them

**Comment by SteamDoge9000** [comment]
Is baritone capable of building very large bases, because its struggling to even build something thats extremely large

**Comment by wizis** [comment]
> 

yea it can, sorry for late reply i was walking my cat

**Comment by Dam-Buty** [comment]
how's the cat doing tho

**Comment by Creeperboy726** [comment]
Don't use that use ".schematic"

**Comment by Creeperboy726** [comment]
"Baritoe💀" those toes be looking kinda juicy if you know what I mean 😏
