### ISSUE TITLE
Baritone doesn't bridge across the void to other islands in bedwars. 

### ISSUE THREAD

**Issue by Footsiefat** [cabaletta/baritone#500]
So I set its position to bridge across on pika network and it path finds to the end of my island and stops even when I haves blocks in hand. (coloured wool).

**Comment by usereewrjrjeejr** [comment]
@leijurv

**Comment by leijurv** [comment]
Colored wool would need to be added as an acceptable throwaway item. See usage.md

**Comment by 0-x-2-2** [comment]
user error strikes again.

**Comment by ZeroMemes** [comment]
> Colored wool would need to be added as an acceptable throwaway item. See usage.md

**Comment by AaronWebster** [comment]
Helps to lower blockPlacementPenalty as well.

**Comment by Jeffmagma** [comment]
Since this is the first issue that pops up on google, it also doesn't bridge across islands in the end dimension with enough dirt in hotbar and block placement penalty at 0

**Comment by rycbar0** [comment]
what are your #modified ?
