### ISSUE TITLE
Not sure if Im building correctly because I keep getting errors with it.

### ISSUE THREAD

**Issue by brendenderp** [cabaletta/baritone#501]
So the build [yourself page](https://github.com/cabaletta/baritone/blob/master/SETUP.md#setup) doesn't give enough info IMO. Starting off in the [intelliJ](https://github.com/cabaletta/baritone/blob/master/SETUP.md#intellij) section it talks about opening the build.gradle as project. Since Ive never used java before I figured this was the same as in visual studio as when I use C#. So I opened the entire folder as a project ( I think) and I dont see anything at all similar to how it is opened in that [image](https://camo.githubusercontent.com/f54cb11a48d860ace194fad067759da6ad08d0b9/68747470733a2f2f692e696d6775722e636f6d2f514566567657502e706e67). Instead [this is what I see  ](https://imgur.com/a/m8rJCu2) And Im really not sure why? am I not opening the project correctly. double clicking was my first guess and nope. I right clicked and ran it which spat out more errors.  I'm also not sure if I even got intelliJ from the right source because there's no link for where to get it from. so I've got this software called IntelliJ IDEA. which is the same thing? I hope.
I never even get to see the part where it asks me to "Run the Gradle tasks setupDecompWorkspace then genIntellijRuns" those never show up.

![imager](https://user-images.githubusercontent.com/29009423/60854052-a589cc00-a1b3-11e9-88db-406e894229a2.PNG)

**Comment by ZeroMemes** [comment]
Use `File > Open` to select the `build.gradle` file in the folder as the project file. 
![image](https://user-images.githubusercontent.com/24485393/60864173-6e81dd80-a1e8-11e9-8e84-f2cca3c5c012.png)

**Comment by brendenderp** [comment]
I would like if you didn't preemptively close the issue because its not done there.

**Comment by leijurv** [comment]
he's mad

**Comment by brendenderp** [comment]
youre right. I am upset with this. I dont think its the creators issue, its just im missing some dumb little detail that I should see but im not.
