### ISSUE TITLE
Project Dragon Fruit (BETA)

### ISSUE THREAD

**Issue by CalebD07** [cabaletta/baritone#503]

**Comment by ZeroMemes** [comment]
???

**Comment by CalebD07** [comment]
It’s a test on Machine Learning

**Comment by CalebD07** [comment]
How it can be applied, and how much it can do.

**Comment by ZeroMemes** [comment]
??????

**Comment by CalebD07** [comment]
Do you know what machine learning is?

**Comment by ZeroMemes** [comment]
I'm perfectly aware of what machine learning is, and the primary developer of Baritone, @leijurv, has hands on experience with it. However, I have no clue what "Project Dragon Fruit" is, and you haven't given any information as to suggest what it is.

**Comment by ZeroMemes** [comment]
Baritone is an advanced A* implementation for Minecraft, there is no machine learning influence.

**Comment by CalebD07** [comment]
I’m sorry but I think we are on different pages. I, as I usually am, am most likely wrong. Sorry.

**Comment by ZeroMemes** [comment]
The point of creating issues on GitHub is to either correct something that is wrong or to provide insight. Lack of understanding by the contributors/maintainers is to be clarified by the OP so that maximum comprehension and investigation can be performed on the issue.

**Comment by CalebD07** [comment]
This is meant to be private. I am new to Machine Learning and so I was going to learn. Instead I set it up incorrectly m, and have now created a new private Project.
