### ISSUE TITLE
Buildbylayer bug

### ISSUE THREAD

**Issue by kyppen** [cabaletta/baritone#505]
I'm trying to construct a giant Jesus statue from a schematic (build by Imp)
![2019-07-09_04 53 11](https://user-images.githubusercontent.com/14559957/60887176-f7822e80-a253-11e9-815e-e37d87030df9.png)
When the bot has completed the first layer it just stops, it doesnt want to build another layer
![2019-07-09_04 53 38](https://user-images.githubusercontent.com/14559957/60887182-fbae4c00-a253-11e9-994f-9eb4b6bf9a0d.png)
you can see the modifications in the picture above

The build is completely build out of Stone and Glowstone

**Comment by kyppen** [comment]
This happens on the 1.12.2 version of minecraft

**Comment by kyppen** [comment]
Nvm its a bug with the schematic i'm using,

**Comment by StijnSimons** [comment]
Please close the issue if its resolved.
