### ISSUE TITLE
Add build command

### ISSUE THREAD

**Issue by GreedySoap** [cabaletta/baritone#507]
Its not a valid command http://prntscr.com/ocphac

**Comment by 0-x-2-2** [comment]
You are running a Impact command instead of a Baritone command.

**Comment by GreedySoap** [comment]
Even with a baritone command

**Comment by txlawso** [comment]
there is a command that can build schematics

**Comment by AlexApps99** [comment]
@GreedySoap please close this issue as the command already exists.
Use `.b build` in Impact, `#build` in standalone.

[See `build` in USAGE.md for instructions on how to use it](https://github.com/cabaletta/baritone/blob/master/USAGE.md#commands)
