### ISSUE TITLE
I cant tell if this is a bug or some sort of error

### ISSUE THREAD

**Issue by autists** [cabaletta/baritone#511]
So before I went to do something I told baritone to go to an end portal like this .b goto end_portal and it's been a little over 2 hours now and it's still travelling

**Comment by leijurv** [comment]
When baritone doesn't have any known locations of the desired block it explores at random

**Comment by leijurv** [comment]
If you don't like this, you can turn off the setting `exploreForBlocks`

**Comment by ZeroMemes** [comment]
Baritone should probably indicate that it has no idea where any of that block is immediately and that it will explore and u can disable using `exploreForBlocks`

**Comment by leijurv** [comment]
chatdebug false got me like

**Comment by ZeroMemes** [comment]
lOl
