### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by Bojini** [cabaletta/baritone#512]
I am using Impact with Baritone. I have made a schematics folder in .minecraft/schematics and put in some schematics. When I go in game tried to build by typing .b build (schematic name) and all it says is loading schematic for an indefinite amount of time. I don't know if its a problem with the schematics or what.

**Comment by StijnSimons** [comment]
Which Minecraft version?

**Comment by Bojini** [comment]
1.13.2

**Comment by NumseBacon** [comment]
you dont have your blocks in your inventory I think

**Comment by StijnSimons** [comment]
1.13.2 is is unsupported for building at this point. Check back later.

**Comment by ZeroMemes** [comment]
@StijnSimons is correct, build on 1.13.2 doesn't work regardless.
