### ISSUE TITLE
Problem with manually running 1.14.2

### ISSUE THREAD

**Issue by zune127** [cabaletta/baritone#514]
I'm trying to run 1.14.2, but can't build or run it because  Could not find com.github.ImpactDevelopment:Vanilla:1.14.2_mapped_snapshot_20190608-1.14.2.

ImpactDevelopment doesn't seem to host this file, nor can I find any copies online. I tried using a standard 1.14 jar and renaming it, but I lack the .pom file, which I am not sure how to create.

Is there a workaround/fix or is it up ImpactDev to rehost this file?
![Screenshot_19](https://user-images.githubusercontent.com/52738685/60953013-f8ea4000-a2c1-11e9-94a7-eb9d019ef9c3.png)

**Comment by 0-x-2-2** [comment]
The 1.14 branch is wip and won't compile or run.

**Comment by leijurv** [comment]
It doesn't compile but that's due to some source code issues, not dependency issues

https://github.com/ImpactDevelopment/maven/commit/4cdef9934666e8e7196e0b6e01bebc4d0acb2eca

it is up, so i'm not sure why this isn't working for you hmm, works for me

@ZeroMemes ?

**Comment by 0-x-2-2** [comment]
Either it was because of github downtime or maybe he cant access it for some reason 🤔

**Comment by zune127** [comment]
I can't seem to get it to work, but if it doesn't compile anyway there is not much point. You do amazing work and I look forward to a working 1.14.2 port
