### ISSUE TITLE
Parkour

### ISSUE THREAD

**Issue by A-Random-Birb** [cabaletta/baritone#516]
so
I'm using Baritone just to mess around and decide to try s parkour map. I set the goal to the end block and did path. What happened was, it did no parkour at all, and instead went to the x and z coords, not caring about the y coords.
Am I doing something wrong or is there something wrong in the code?

**Comment by SirJosh3917** [comment]
make sure you do `#goal x y z` and not `#goal x z`

**Comment by A-Random-Birb** [comment]
> make sure you do `#goal x y z` and not `#goal x z`

I did use goal xyz

**Comment by Nipeno** [comment]
I can confirm this, I tried building a simple parkour, completed the parkour myself and the end platfrom of the parkour was like 4 blocks above the ground.
Baritone just walked right below the platform when I gave it all coordinates (xyz)

**Comment by leijurv** [comment]
That means that that was the closest it could get to the intended goal (right underneath it).

Baritone can't do parkour courses or anything like that, the jumping over gaps is only intended to help with normal pathfinding. It never does it at an angle or to any strange blocks.

**Comment by TomerGamerTV** [comment]
> That means that that was the closest it could get to the intended goal (right underneath it).
> 
> Baritone can't do parkour courses or anything like that, the jumping over gaps is only intended to help with normal pathfinding. It never does it at an angle or to any strange blocks.

But I've seen people do parkour maps with baritone on youtube how are they doing it?
