### ISSUE TITLE
#build error

### ISSUE THREAD

**Issue by gomusicgamer** [cabaletta/baritone#518]
i have a schematic on .minecraft/schematics but when i type #build test it says "[Baritone] unable to do it" soo what did i do wrong? (p.s. im in creative in a superflat)

**Comment by LickTheCheese** [comment]
i appear to have the same error
`[Baritone] Loading 'foo.schematic' to build from origin`
`[Baritone] Unable to load`

**Comment by maxwell0711** [comment]
I also have that problem but idk ho to fix it

**Comment by StijnSimons** [comment]
Which Minecraft  version you using?

**Comment by 0-x-2-2** [comment]
> i have a schematic on .minecraft/schematics but when i type #build test it says "[Baritone] unable to do it" soo what did i do wrong? (p.s. im in creative in a superflat)

you need the items in your inventory.

**Comment by maxwell0711** [comment]
I’m running 1.13.2 and idk how to create the folder to make the baritone to build stuff

**Comment by StijnSimons** [comment]
Building for 1.13.2 is broken. Stick to 1.12.

**Comment by maxwell0711** [comment]
Where do I create a folder to insert all the build I want the bot to make

**Comment by StijnSimons** [comment]
`%appdata%/.minecraft/schematics`. But like i said; it doesn't work for 1.13.

**Comment by maxwell0711** [comment]
the # doesnt work in 1.12

**Comment by StijnSimons** [comment]
You’re probably using Impact so use `.b` instead of `#`

**Comment by maxwell0711** [comment]
I did .b but the command keep saying no command were to be found. I type .b build house

**Comment by StijnSimons** [comment]
I’m like 90% sure you’re not running Impact. (Or at least the latest version)

**Comment by maxwell0711** [comment]
I am running impact on the lastest version tho

**Comment by StijnSimons** [comment]
Screenshot of the command output?

**Comment by maxwell0711** [comment]
![image](https://user-images.githubusercontent.com/52949078/61323203-3cfaaa80-a7c4-11e9-911d-feda9dc30bcc.png)

**Comment by StijnSimons** [comment]
Which exact version are you running and do you have baritone installed into it (latest version also)

**Comment by maxwell0711** [comment]
![image](https://user-images.githubusercontent.com/52949078/61326117-f65c7e80-a7ca-11e9-9f5a-62e118eb0868.png)

**Comment by maxwell0711** [comment]
this is what I did to install, it work when I install it on version 1.13,2

**Comment by StijnSimons** [comment]
Outdated installer; its not installing baritone.

**Comment by StijnSimons** [comment]
I mean i think you need to use 1.12.2 (or .3)

**Comment by leijurv** [comment]
correct. (1.12.3 doesn't exist tho) but yeah baritone is only for 1.12.2 and 1.13.2 specifically

**Comment by maxwell0711** [comment]
I did install it for 1.12.2 tho

**Comment by StijnSimons** [comment]
Which installer version?

**Comment by leijurv** [comment]
That installer has 1.12 selected. Not 1.12.2.

**Comment by StijnSimons** [comment]
Love it

**Comment by raithap** [comment]
does build work in 1.14 or no

**Comment by 0-x-2-2** [comment]
no
