### ISSUE TITLE
Potential Missing blocks on Baritone

### ISSUE THREAD

**Issue by Nate8888** [cabaletta/baritone#523]
Hello! I was playing around with baritone and I found some potential blocks that baritone is not recognizing. Here are the entity ids of the items (I was using both 'mine' and 'goto' command and baritone's output was that the block isn't a valid block name)

minecart
chest_minecart (Important as there are these in mineshafts)
furnace_minecart
tnt_minecart
hopper_minecart
boat
end_crystal

I'm using release v1.2.7

**Comment by JaminPRose** [comment]
I'm not one of the programmers, but those are entities rather than blocks, which may be why it's not registering them. Perhaps it's a different command? Again, I'm not the programmer so I don't actually know.

**Comment by leijurv** [comment]
indeed... the one thing those all have in common is that they're all entities not blocks =)

**Comment by Nate8888** [comment]
@leijurv cool. Is there a command that breaks them tho?

**Comment by Bjornskjald** [comment]
Breaks them or finds them?

**Comment by StijnSimons** [comment]
- [x] `followentity` is added in the next build.
- [x] `followentities` is added in the next build.

**Comment by AlexApps99** [comment]
@Nate8888 since the issue has been resolved please can you close this issue?
