### ISSUE TITLE
Baritone doesn't know how to place stairs properly

### ISSUE THREAD

**Issue by Milondzije** [cabaletta/baritone#524]
Baritone won't build stairs propertly it places them upside down then break them then build it again and this goes on and on any fixes ?
![2019-07-12_13 14 47](https://user-images.githubusercontent.com/52794973/61124779-1ed13980-a4a8-11e9-9e47-62a1a1221057.png)
Like that

**Comment by scorbett123** [comment]
Really this is a duplicate of #1326, fixing that issue would fix this.

**Comment by CHUNKUD** [comment]
plz fix this its a big problem and i wanna build a fricking medieval house but its impossible whit this bug
