### ISSUE TITLE
baritone mine is broken

### ISSUE THREAD

**Issue by autists** [cabaletta/baritone#525]
so when I do .b mine diamond_ore baritone with legitmine off starts mining to weird places and it says that diamonds are literally everywhere and then I turn on my x-ray it says that diamonds are everywhere but when I main towards them manually they turn to stone and it confuses baritone that diamonds are everywhere underground

**Comment by autists** [comment]
![2019-07-11_20 03 30](https://user-images.githubusercontent.com/50638136/61078378-64debc80-a418-11e9-9f2b-a0a6d4a54652.png)
like this

**Comment by leijurv** [comment]
This is orebfuscator, it's a server plugin designed to foil xray mining. You'd see this in any client with xray. This is the entire point of legitmine though lol, that it only mines ores that it can actually see. Turn on legitmine xd

**Comment by autists** [comment]
fuck lol thanks
