### ISSUE TITLE
Eating slows down.

### ISSUE THREAD

**Issue by DrNuget** [cabaletta/baritone#526]
That's all, i use a different hacked client which supports noslow but when i launch baritone it slows down every time i eat something. Also impact's autoeat doesn't work and i have to go check back on the minecraft window to make sure my ingame character doesn't starve.

**Comment by StijnSimons** [comment]
This has nothing to do with baritone. You should be at Impacts’ issues list.

**Comment by 0-x-2-2** [comment]
> This has nothing to do with baritone. You should be at Impacts’ issues list.

did you even read the issue lol.

**Comment by StijnSimons** [comment]
> > This has nothing to do with baritone. You should be at Impacts’ issues list.
> 
> did you even read the issue lol.

Talking about this
> Also impact's autoeat doesn't work and i have to go check back on the minecraft window to make sure my ingame character doesn't starve.

**Comment by ZeroMemes** [comment]
This isn’t a Baritone issue. If you’re using Impact report the issue there.
