### ISSUE TITLE
Does not recognize blocks in/underwater

### ISSUE THREAD

**Issue by Aaron2550** [cabaletta/baritone#529]
'.b mine clay' does not recognize clay blocks underwater and it also cannot find a path to any other clay blocks underwater.

**Comment by StijnSimons** [comment]
Do you have assumeWalkOnWater enabled?
```java
/**
     * Allow Baritone to assume it can walk on still water just like any other block.
     * This functionality is assumed to be provided by a separate library that might have imported Baritone.
     */
    public final Setting<Boolean> assumeWalkOnWater = new Setting<>(false);
```

**Comment by Aaron2550** [comment]
its disabled

**Comment by StijnSimons** [comment]
This is a problem with avoidAdjacentBreaking in baritone.pathing.movement.MovementHelper.
My knowledge of the baritone core currently isn't that good so i'm letting @leijurv do it.
```java
    static boolean avoidAdjacentBreaking(BlockStateInterface bsi, int x, int y, int z, boolean directlyAbove) {
        // returns true if you should avoid breaking a block that's adjacent to this one (e.g. lava that will start flowing if you give it a path)
        // this is only called for north, south, east, west, and up. this is NOT called for down.
        // we assume that it's ALWAYS okay to break the block thats ABOVE liquid
        IBlockState state = bsi.get0(x, y, z);
        Block block = state.getBlock();
        if (!directlyAbove // it is fine to mine a block that has a falling block directly above, this (the cost of breaking the stacked fallings) is included in cost calculations
                // therefore if directlyAbove is true, we will actually ignore if this is falling
                && block instanceof BlockFalling // obviously, this check is only valid for falling blocks
                && Baritone.settings().avoidUpdatingFallingBlocks.value // and if the setting is enabled
                && BlockFalling.canFallThrough(bsi.get0(x, y - 1, z))) { // and if it would fall (i.e. it's unsupported)
            return true; // dont break a block that is adjacent to unsupported gravel because it can cause really weird stuff
        }
        return block instanceof BlockLiquid;
    }
```

**Comment by 0-x-2-2** [comment]
Baritone does not like water and this is intended because water is bad for baritone.

**Comment by Aaron2550** [comment]
Why is water bad for baritone? Would it be that hard to make a "ignore water"-option? I can barely code that's why I ask.

**Comment by 0-x-2-2** [comment]
Water is slow, dangerous and baritone is not very good at swimming.

**Comment by ZeroMemes** [comment]
The best way that Baritone could deal with adjacent water is blocking it up, but it becomes problematic and disruptive if that is not possible. I doubt that there will be seen any improvements to how it handles water, you'll just have to gather that clay yourself.

**Comment by 0-x-2-2** [comment]
> The best way that Baritone could deal with adjacent water is blocking it up, but it becomes problematic and disruptive if that is not possible or something goes wrong. I doubt that there will be seen any improvements to how it handles water, you'll just have to gather that clay yourself.

1.13 makes water worse too 😭

**Comment by ZeroMemes** [comment]
>1.13 makes water worse too 😭

Yeah 1.13 water behavior with diving and shit is too much to have to deal with.

**Comment by Amnessie** [comment]
Any way nowadays to get around this problem? I`m working on a massive spawn overhaul and could do with an underwater Baritone.
