### ISSUE TITLE
Baritone build in creative mode

### ISSUE THREAD

**Issue by CONBlaze** [cabaletta/baritone#532]
It would be nice if it could get the blocks itself, since some pixelart schematics require a lot of blocks and I can't be bothered to get all of them out of my inventory.

**Comment by StijnSimons** [comment]
Remind me in one week and i’ll help.

**Comment by CONBlaze** [comment]
Will sure do

**Comment by ZeroMemes** [comment]
??????

**Comment by waterdragon78** [comment]
Reminded in OVER a week
