### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jiwkenist** [cabaletta/baritone#533]
Hello, 

I was wondering if there is a way to utilize Baritone directly into Minecraft without Forge or Impact. I noticed there was something called standalone but I wasn't able to understand of how to implement it. 

Psst. A bit more detailed explanation of how to use a standalone version would be greatly appreciated. 

Additionally, if I were to manually build it myself, will it work with the latest Minecraft?

Thank you.
Quack

**Comment by 0-x-2-2** [comment]
You will need to install it manually.

**Comment by leijurv** [comment]
yeah you'd need to make a json with just baritone (and simpletweaker?) and just add its tweak class
