### ISSUE TITLE
[Question] Retro Compatibility

### ISSUE THREAD

**Issue by Gio4E20** [cabaletta/baritone#534]
Any chance u guys add 1.7.10/ 1.8.9 compatibility?

**Comment by StijnSimons** [comment]
Its time to move on, its outdated af...

**Comment by mrphax0r** [comment]
It is still better than 1.9+

**Comment by StijnSimons** [comment]
> It is still better than 1.9+

You can't keep a project with 1.8 support AND 1.12-1.13 support. *Features get added, y'know?*
