### ISSUE TITLE
Baritone should prioritize routes that do not involve breaking blocks

### ISSUE THREAD

**Issue by 0xx06** [cabaletta/baritone#537]
I'm really not interested in leaving a path of destruction behind me when i could also take a few blocks more (which could even be faster because no digging involved) while getting somewhere. 

I just recently had a clear path, did goto and baritone somehow though the best way was to dig through a mountain instead of just going over it (which was possible to do, i tested it, no parcour jumps).

**Comment by StijnSimons** [comment]
.b allowBreak false

**Comment by 0xx06** [comment]
i'm all for baritone digging a way for me, but only if that's the only way to progress (or the fastest one).

**Comment by leijurv** [comment]
It only digs if it's the fastest way to progress. There is actually an additional penalty of breaking blocks (i think it's 2 ticks) and you can change that if you want. i.e. if you don't want to strictly disable breaking blocks but you want to really discourage it even if it's fastest, you should turn up the block breaking penalty setting or whatever its called
