### ISSUE TITLE
Build command crashes game.

### ISSUE THREAD

**Issue by Floffah** [cabaletta/baritone#538]
Got [this crash report](https://pastebin.com/fKqkGWmR) when trying to use the build command with [this schematic](https://www.minecraft-schematics.com/schematic/235/download/) I also tried it with other schematics, but it didn't really change the outcome.
It crashes as soon as I press enter. like it freezes exactly as i press enter then the game saves and closes.

**Comment by 0-x-2-2** [comment]
you cant use build on 1.13

**Comment by leijurv** [comment]
it dont work for 1.13
