### ISSUE TITLE
Fishing?!?!

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#539]
This is a serious issue! No fishing?!!?!?

**Comment by usereewrjrjeejr** [comment]
Turn on auto fish on impact

**Comment by NumseBacon** [comment]
Dont like to hack i don't wanna get banned

**Comment by StijnSimons** [comment]
No Impact, no autofish at this point. Devs are more focussed on higher priority things.

**Comment by JoelEllis** [comment]
@StijnSimons autofish can be used as a food source for survival or travel.

**Comment by StijnSimons** [comment]
> @StijnSimons autofish can be used as a food source for survival or travel.

Yeah but autofish is less important than fixing tunnelfill, building, basic bugs.

**Comment by NumseBacon** [comment]
Well food is also very important

**Comment by usereewrjrjeejr** [comment]
Oh well

**Comment by NumseBacon** [comment]
Well well well

**Comment by StijnSimons** [comment]
> Dont like to hack i don't wanna get banned

Just use no modules besides auto-fishing?
Also, baritone is still an unfair advantage so you’re ‘hacking’ either way.

**Comment by NumseBacon** [comment]
I'm only using baritone for walking lmao

**Comment by leijurv** [comment]
> Dont like to hack i don't wanna get banned

no difference between using an auto miner that can xray and using a client that can xray lol

install impact and only turn on auto fish ez

**Comment by leijurv** [comment]
> Dont like to hack i don't wanna get banned

no difference between using an auto miner that can xray and using a client that can xray lol

install impact and only turn on auto fish ez
