### ISSUE TITLE
[Bug] when farming, it attempts to place seeds by looking at the underside of the block

### ISSUE THREAD

**Issue by SirJosh3917** [cabaletta/baritone#541]
ideal fix would be to only allow it to place it if it's looking at the top of a block

**Comment by StijnSimons** [comment]
Should add a check [here](https://github.com/cabaletta/baritone/blob/ce4b1e09edf44f08107b405bf8dd121c8fa38550/src/main/java/baritone/process/FarmProcess.java#L228) if its facing the top.

**Comment by leijurv** [comment]
Thank you! wow an actual specific and actionable issue. will fix rn

**Comment by StijnSimons** [comment]
> Thank you! wow an actual specific and actionable issue. will fix rn

Finally no *pls 1.14 when????* issue.
