### ISSUE TITLE
Not pickup

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#543]
Im using mine on a server but my pickaxe is too op so it mines too fast and doesnt pick up the item when it drops

**Comment by 0-x-2-2** [comment]
Looking at [settings](https://baritone.leijurv.com/baritone/api/Settings.html#mineScanDroppedItems) would of solved this...

**Comment by NumseBacon** [comment]
its on true already

**Comment by StijnSimons** [comment]
He is correct, it scans a bit too early, so it sometimes skips a drop. In that case just wait, it should auto-walk back to pick it up.

**Comment by 0-x-2-2** [comment]
> He is correct, it scans a bit too early, so it sometimes skips a drop. In that case just wait, it should auto-walk back to pick it up.

it skips a drop when its faster to get a new one then it will go back.

**Comment by StijnSimons** [comment]
> > He is correct, it scans a bit too early, so it sometimes skips a drop. In that case just wait, it should auto-walk back to pick it up.
> 
> it skips a drop when its faster to get a new one then it will go back.

Didn't for me; it went for an ore about 40 bocks away first, then to run back and pick up the previous one.

**Comment by leijurv** [comment]
This is just due to server lag, there's a window of time where you've broken the block but the server hasn't told you about the drop yet. So in that time it recognizes there's nothing here (no ore and no drop (yet)), and goes on to the next one.

**Comment by AlexApps99** [comment]
@NumseBacon please close this issue as it's due to server-side lag and cannot be patched.
