### ISSUE TITLE
CPU performance issue

### ISSUE THREAD

**Issue by joshuajaco** [cabaletta/baritone#544]
I'm using baritone with Impact 4.6 for minecraft 1.13.2 and when I run basically anything it completely eats my CPU. For example `#mine diamond_ore` makes my CPU hit 100% and the game runs with like 1 frame per 5 seconds. Maybe this is more related to Impact? I couldn't find anything related so it's probably just me.

CPU: Intel Core i5-4570 3.20GHz

**Comment by 0-x-2-2** [comment]
I don't see how it can do this can happen unless you have shit cooling and your cpu is at like 90c at idle.

**Comment by joshuajaco** [comment]
Yeah no, it runs ~40C in idle and ~50C when playing minecraft 1.13.2 Vanilla with ~50-70% CPU load depending on chunk loading

**Comment by StijnSimons** [comment]
Think this is a user-end issue. Like @0-x-2-2 said, no idea what a toaster you should be running to get this.

**Comment by joshuajaco** [comment]
Judging from your language and profiles I'm assuming you aren't very bright individuals. Please try to be helpful or let the grown ups speak, boys.

**Comment by StijnSimons** [comment]
Lmao mate you drunk? This project is run by 17-19 year olds.

**Comment by 0-x-2-2** [comment]
📸

**Comment by 0-x-2-2** [comment]
muh game is lagging!!!! time to complain without giving any useful info.

visualvm and taking a pic of hwmonitor/cpuid while under load should be a decent amount of info.

**Comment by babbaj** [comment]
📸

**Comment by ZeroMemes** [comment]
The only time I have ever gotten issues with Baritone pathing (With my i7-4790k, so slightly higher tier, but still 4th gen) is when I have run 16+ bots on the same game instance simultaneously.

**Comment by joshuajaco** [comment]
Turns out this is most likely related to https://bugs.mojang.com/browse/MC-133877 but only became apparent in combination with baritone. Turning the 'Biome Blend' setting off resolved this issue.
