### ISSUE TITLE
Creative mode issues (inventory and flight)

### ISSUE THREAD

**Issue by akkifireborker** [cabaletta/baritone#545]
Using Baritone version 1.2.7 alongside Impact version 4.6 and Minecraft 1.12.2

Recently I was testing out the build command in creative mode on a superflat world. Using the build command successfully loaded the schematic, and it even breaks the blocks necessary to create the foundation of the build, but it fails to place any blocks unless they are already in my hotbar, saying it is "Unable to do it." I have AllowInventory set to true, yet it cannot access the blocks necessary for the build, which is problematic as the build I am attempting to replicate is fairly complicated and requires more than the 9 blocks available in the hotbar. Is there some command I'm missing to allow creative inventory access, or is this an issue?

Additionally, I noticed that in creative mode, any specified movement commands (such as goto) intentionally refuse to fly, opting to walk, break, blocks and place blocks to get to its target, even when the target is 100% vertical. Is there a way to turn on creative mode flight, or a way to tell baritone when it can and cannot fly in the cases of multiplayer servers which occasionally allow flight in survival mode?

**Comment by 0-x-2-2** [comment]
You need to move the building blocks into your real inventory.

Baritone is unable to fly.

**Comment by RajehTXD** [comment]
can you make it fly?
