### ISSUE TITLE
[Request] Accept donations/money via Patreon

### ISSUE THREAD

**Issue by SirJosh3917** [cabaletta/baritone#546]
i really like this project and i don't think i'd mind donating a dollar a month to it, and i'd hope many others would love to as well.

ideally, i'd love it if you setup a [patreon](https://www.patreon.com/).

imo, donating bitcoin through the obscure bitcoin address (a commit was made to try fix it in #436) is a bit difficult for most filthy casuals of the internet, like myself.

an example of a project that seems to work quite well with patreon is [v](https://vlang.io)

**Comment by usereewrjrjeejr** [comment]
Please see #436

Closed

**Comment by SirJosh3917** [comment]
#436 is a way to monetize baritone whereas this is a donation strategy, so that way nothing is kept behind a paywall for regular users. are you sure this issue is still extremely similar to #436? i thought they were different enough so i made a new issue - if you're completely sure than i apologize.

**Comment by c0nn3r** [comment]
Current Baritone developer consensus is to to use the ideas outlined in #436.

**Comment by Bendito999** [comment]
#436 that thread is pure cancer lmao, leijurv can you give me your paypal I will give you some money lol. I don't have the bitcoins though... :(
