### ISSUE TITLE
Can't see baritone's path or goal

### ISSUE THREAD

**Issue by Alexuty07** [cabaletta/baritone#547]
I don't know if there's some way to make the path/goal (the red line that baritone follows) invisible that i triggered by accident but for some reason i cannot see it

**Comment by StijnSimons** [comment]
Are you using optifine?

**Comment by leijurv** [comment]
The settings are renderpath and rendergoal

**Comment by Alexuty07** [comment]
> The settings are renderpath and rendergoal

I've set these to true, but the path is still invisible

**Comment by Alexuty07** [comment]
> Are you using optifine?

Yes i am using optifine

**Comment by StijnSimons** [comment]
> > Are you using optifine?
> 
> Yes i am using optifine

Try without, it isn't really "bug free" with optifine.

**Comment by Alexuty07** [comment]
> > > Are you using optifine?
> > 
> > 
> > Yes i am using optifine
> 
> Try without, it isn't really "bug free" with optifine.

This fixed it, thanks

**Comment by dansleboby** [comment]
I can't see the path on fabric too :(

**Comment by scorbett123** [comment]
> I can't see the path on fabric too :(


reset your settings to defaults and see if that fixes the issue.

**Comment by dansleboby** [comment]
It was because I have shader ON :)

**Comment by qwertyjgly** [comment]
It doesn't work well with Fullbright (visible but barely)
