### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#548]
So Im trying to build a building and i put in BuildInLayers and I typed .b build (name) and it makes the first layer but then it stops. I have all the blocks in my inventory

**Comment by NumseBacon** [comment]
and hotbar

**Comment by Scarbrine** [comment]
Dang i have the same problem

**Comment by StijnSimons** [comment]
Which version

**Comment by Scarbrine** [comment]
1.12.2 because i found out it doesn't work at all on 1.13.2

**Comment by o0ZzM4g1c** [comment]
same problem.
Impact:4.8.3-1.12.2
baritone-api:1.2.10
(comes with Impact installer 0.7.5)

**Comment by ThebesAndSound** [comment]
its because you dont also have throwaway items e.g dirt in your hotbar

**Comment by o0ZzM4g1c** [comment]
to scaffold during build ? even with BuildInLayers on ?

**Comment by RavingLoon** [comment]
i have the same problem it works dine without buildbylayers ..but dosnt work with buildbylayers

**Comment by dominikaaaa** [comment]
Closed as resolved. Create a new issue with the requested information if this still happens.
