### ISSUE TITLE
Forge + Baritone in a modpack 1.12.2 crash 1.2.7/1.2.6

### ISSUE THREAD

**Issue by TerrorPL** [cabaletta/baritone#551]
Hey I have a problem I'm trying to put Baritone into a modpack previously it works fine but this time it's crashing Logs:
https://paste.atlauncher.com/view/39fd2788
and different launcher:
https://pastebin.com/fuQZ82wD
and yes I did try the standalone version,
forge: 1.12.2-14.23.5.2838
Any ideas about how to fix it.

**Comment by 0-x-2-2** [comment]
no

**Comment by Master-64** [comment]
Try removing whatever "FMLDeobfTweaker" is referring to.

**Comment by 0-x-2-2** [comment]
📸

**Comment by 0-x-2-2** [comment]
@Master-64 you are retard

**Comment by Master-64** [comment]
> @Master-64 you are retard

<3
