### ISSUE TITLE
[Suggestion] Baritone new features, Improvements and fixes

### ISSUE THREAD

**Issue by SWEDCODER** [cabaletta/baritone#552]
Hello, everyone, I've got a list of ideas that could be cool to add in baritone and some bugs I wanted to share : 
# **New Features** :
- `followentity <entity type>` : 
       Permits you to follow any entity specified.
- `followentities` : 
       Follows any entities in rendered chunks (comes with the options `followpassive` for animals, and `followhostile` for mobs that can attack you).

# **New Options** : 
 - `replaceblocks` : 
            Replaces the blocks it has broken and recovered during mining, going to a waypoint, or even exploring. 

- `pvppause [player,entity]` : 
            Automatically pauses or cancels if you get hit by a player or an entity.  

# **Bug Fixes** : 
 - When using bucket falling, baritone sometimes cancels the pathfinding when you fall. 
-  Baritone prefers most of the time breaking a block instead of jumping over it.
-  Baritone prefers going into water instead of jumping on blocks and being much much faster. (I don't know if it has something with Impact's Sprint)
-  When using explore Baritone sometimes goes back for a bit and then goes to an old near chunk. (That's not really much of an issue but that takes much longer than going straight forward). 

That's not really much but I'll maybe edit if I get another ideas. I hope these could be added in future versions ^^.

**Comment by ZeroMemes** [comment]
In order for us keep track of everything in an orderly manner, please create separate issues for each feature suggestion/option addition/bug fix.

**Comment by StijnSimons** [comment]
- [x] `followentity` is added in the next build.
- [x] `followentities` is added in the next build.
