### ISSUE TITLE
Multiple bots at once?

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#553]
I saw a video where 1 minecraft could control 4 bots and all paths were show on the 1 minecraft where the person controlled it (put the path)

**Comment by 0-x-2-2** [comment]
you watched a preview video of the bot system branch however the branch has been not really touched for about 10 months and not touched at all for 7. 

summary:
1. its dead 
2. outdated see number  1
3. extremely buggy number 2 contributes to this
4. crashes see number 3

**Comment by ZeroMemes** [comment]
https://github.com/cabaletta/baritone/pull/244
