### ISSUE TITLE
Can't figure out how to add baritone to a hacked client

### ISSUE THREAD

**Issue by TheOfficialGameDev** [cabaletta/baritone#555]
I can't for the life of me, find out how to add baritone to my minecraft hacked client. I've already tried adding it to the version .json file, I tried simply moving baritones data into my minecraft hacked clients jar. Nothing seems to work, I've looked all other the internet but it seems there is know one else in my position. Any and all help is appreciated.

**Comment by StijnSimons** [comment]
Check out [this](https://github.com/cabaletta/baritone/tree/master/src/launch).

**Comment by TheOfficialGameDev** [comment]
I've looked at the impact client to figure out why it works there, I tried copying some parts inside the .json to see if that works, to no avail.

**Comment by TheOfficialGameDev** [comment]
An example of my .json file:
-------------------------------------------------------------------------------------------------------------------
{"assetIndex":{"id":"1.12",
"sha1":"67e29e024e664064c1f04c728604f83c24cbc218",
"size":169014,
"url":"https://launchermeta.mojang.com/mc/assets/1.12/67e29e024e664064c1f04c728604f83c24cbc218/1.12.json",
"totalSize":127037169},
"assets":"1.12",
"downloads":{},
"id":"TEST",
"libraries":[{
"name":"com.mojang:patchy:1.1",
"downloads":{"artifact":{"size":15817,
"sha1":"aef610b34a1be37fa851825f12372b78424d8903",
"path":"com/mojang/patchy/1.1/patchy-1.1.jar",
"url":"https://libraries.minecraft.net/com/mojang/patchy/1.1/patchy-1.1.jar"
    }
   }
  },
{
"name":"oshi-project:oshi-core:1.1",
"downloads":{"artifact":{"size":30973,
"sha1":"9ddf7b048a8d701be231c0f4f95fd986198fd2d8",
"path":"oshi-project/oshi-core/1.1/oshi-core-1.1.jar",
"url":"https://libraries.minecraft.net/oshi-project/oshi-core/1.1/oshi-core-1.1.jar"
    }
   }
  },
{
  "name":"cabaletta:baritone-api:1.2.7",
"downloads":{"artifact":{"size":292188,
"sha1":"1ff766ba2fc816e0b0f0547e1b866b13aac32f13",
"path":"cabaletta/baritone-api/1.2.7/baritone-api-1.2.7.jar",
"url":"https://github.com/cabaletta/baritone/releases/download/v1.2.7/baritone-api-1.2.7.jar"
    }
   }
  },
{
"name":"net.java.dev.jna:jna:4.4.0",
"downloads":{"artifact":{"size":1091208,
"sha1":"cb208278274bf12ebdb56c61bd7407e6f774d65a",
"path":"net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar",
"url":"https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar"
    }
   }
  },
{
"name":"net.java.dev.jna:platform:3.4.0",
"downloads":{"artifact":{"size":913436,
"sha1":"e3f70017be8100d3d6923f50b3d2ee17714e9c13",
"path":"net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar",
"url":"https://libraries.minecraft.net/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar"
    }
   }
  },
{
"name":"com.ibm.icu:icu4j-core-mojang:51.2",
"downloads":{"artifact":{"size":1634692,
"sha1":"63d216a9311cca6be337c1e458e587f99d382b84",
"path":"com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar",
"url":"https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar"
    }
   }
  },
{
"name":"net.sf.jopt-simple:jopt-simple:5.0.3",
"downloads":{"artifact":{"size":78175,
"sha1":"cdd846cfc4e0f7eefafc02c0f5dce32b9303aa2a",
"path":"net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar",
"url":"https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar"
    }
   }
  },
{
"name":"com.paulscode:codecjorbis:20101023",
"downloads":{"artifact":{"size":103871,
"sha1":"c73b5636faf089d9f00e8732a829577de25237ee",
"path":"com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar",
"url":"https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar"
    }
   }
  },
{
"name":"com.paulscode:codecwav:20101023",
"downloads":{"artifact":{"size":5618,
"sha1":"12f031cfe88fef5c1dd36c563c0a3a69bd7261da",
"path":"com/paulscode/codecwav/20101023/codecwav-20101023.jar",
"url":"https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023.jar"
    }
   }
  },
{
"name":"com.paulscode:libraryjavasound:20101123",
"downloads":{"artifact":{"size":21679,
"sha1":"5c5e304366f75f9eaa2e8cca546a1fb6109348b3",
"path":"com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar",
"url":"https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar"
    }
   }
  },
{
"name":"com.paulscode:librarylwjglopenal:20100824",
"downloads":{"artifact":{"size":18981,
"sha1":"73e80d0794c39665aec3f62eee88ca91676674ef",
"path":"com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar",
"url":"https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar"
    }
   }
  },
{
"name":"com.paulscode:soundsystem:20120107",
"downloads":{"artifact":{"size":65020,
"sha1":"419c05fe9be71f792b2d76cfc9b67f1ed0fec7f6",
"path":"com/paulscode/soundsystem/20120107/soundsystem-20120107.jar",
"url":"https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar"
    }
   }
  },
{
"name":"io.netty:netty-all:4.1.9.Final",
"downloads":{"artifact":{"size":3511093,
"sha1":"0097860965d6a0a6b98e7f569f3f966727b8db75",
"path":"io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar",
"url":"https://libraries.minecraft.net/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar"
    }
   }
  },
{
"name":"com.google.guava:guava:21.0",
"downloads":{"artifact":{"size":2521113,
"sha1":"3a3d111be1be1b745edfa7d91678a12d7ed38709",
"path":"com/google/guava/guava/21.0/guava-21.0.jar",
"url":"https://libraries.minecraft.net/com/google/guava/guava/21.0/guava-21.0.jar"
    }
   }
  },
{
"name":"org.apache.commons:commons-lang3:3.5",
"downloads":{"classifiers":{"tests":{"size":780282,
"sha1":"8ca309192f104265c67a1570245ae827a8650af9",
"path":"org/apache/commons/commons-lang3/3.5/commons-lang3-3.5-tests.jar",
"url":"https://libraries.minecraft.net/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5-tests.jar"}},
"artifact":{"size":479881,
"sha1":"6c6c702c89bfff3cd9e80b04d668c5e190d588c6",
"path":"org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar",
"url":"https://libraries.minecraft.net/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar"
    }
   }
  },
{
"name":"commons-io:commons-io:2.5",
"downloads":{"classifiers":{"tests":{"size":372821,
"sha1":"32b15369c83e9435ced8cd3fbe652dfba9c497ef",
"path":"commons-io/commons-io/2.5/commons-io-2.5-tests.jar",
"url":"https://libraries.minecraft.net/commons-io/commons-io/2.5/commons-io-2.5-tests.jar"}},
"artifact":{"size":208700,
"sha1":"2852e6e05fbb95076fc091f6d1780f1f8fe35e0f",
"path":"commons-io/commons-io/2.5/commons-io-2.5.jar",
"url":"https://libraries.minecraft.net/commons-io/commons-io/2.5/commons-io-2.5.jar"
    }
   }
  },
{
"name":"commons-codec:commons-codec:1.10",
"downloads":{"classifiers":{"tests":{"size":256617,
"sha1":"df86446f0fe79f15ce8048c0ed04d1a92fa8d265",
"path":"commons-codec/commons-codec/1.10/commons-codec-1.10-tests.jar",
"url":"https://libraries.minecraft.net/commons-codec/commons-codec/1.10/commons-codec-1.10-tests.jar"}},
"artifact":{"size":284184,
"sha1":"4b95f4897fa13f2cd904aee711aeafc0c5295cd8",
"path":"commons-codec/commons-codec/1.10/commons-codec-1.10.jar",
"url":"https://libraries.minecraft.net/commons-codec/commons-codec/1.10/commons-codec-1.10.jar"
    }
   }
  },
{
"name":"net.java.jinput:jinput:2.0.5",
"downloads":{"artifact":{"size":208338,
"sha1":"39c7796b469a600f72380316f6b1f11db6c2c7c4",
"path":"net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar",
"url":"https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar"
    }
   }
  },
{
"name":"net.java.jutils:jutils:1.0.0",
"downloads":{"artifact":{"size":7508,
"sha1":"e12fe1fda814bd348c1579329c86943d2cd3c6a6",
"path":"net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar",
"url":"https://libraries.minecraft.net/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar"
    }
   }
  },
{
"name":"com.google.code.gson:gson:2.8.0",
"downloads":{"artifact":{"size":231952,
"sha1":"c4ba5371a29ac9b2ad6129b1d39ea38750043eff",
"path":"com/google/code/gson/gson/2.8.0/gson-2.8.0.jar",
"url":"https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar"
    }
   }
  },
{
"name":"com.mojang:authlib:1.5.25",
"downloads":{"artifact":{"size":65621,
"sha1":"9834cdf236c22e84b946bba989e2f94ef5897c3c",
"path":"com/mojang/authlib/1.5.25/authlib-1.5.25.jar",
"url":"https://libraries.minecraft.net/com/mojang/authlib/1.5.25/authlib-1.5.25.jar"
    }
   }
  },
{
"name":"com.mojang:realms:1.10.17",
"downloads":{"artifact":{"size":3257404,
"sha1":"e6a623bf93a230b503b0e3ae18c196fcd5aa3299",
"path":"com/mojang/realms/1.10.17/realms-1.10.17.jar",
"url":"https://libraries.minecraft.net/com/mojang/realms/1.10.17/realms-1.10.17.jar"
    }
   }
  },
{
"name":"org.apache.commons:commons-compress:1.8.1",
"downloads":{"artifact":{"size":365552,
"sha1":"a698750c16740fd5b3871425f4cb3bbaa87f529d",
"path":"org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar",
"url":"https://libraries.minecraft.net/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar"
    }
   }
  },
{
"name":"org.apache.httpcomponents:httpclient:4.3.3",
"downloads":{"artifact":{"size":589512,
"sha1":"18f4247ff4572a074444572cee34647c43e7c9c7",
"path":"org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar",
"url":"https://libraries.minecraft.net/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar"
    }
   }
  },
{
"name":"commons-logging:commons-logging:1.1.3",
"downloads":{"artifact":{"size":62050,
"sha1":"f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f",
"path":"commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar",
"url":"https://libraries.minecraft.net/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar"
    }
   }
  },
{
"name":"org.apache.httpcomponents:httpcore:4.3.2",
"downloads":{"artifact":{"size":282269,
"sha1":"31fbbff1ddbf98f3aa7377c94d33b0447c646b6e",
"path":"org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar",
"url":"https://libraries.minecraft.net/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar"
    }
   }
  },
{
"name":"it.unimi.dsi:fastutil:7.1.0",
"downloads":{"artifact":{"size":17655579,
"sha1":"9835253257524c1be7ab50c057aa2d418fb72082",
"path":"it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar",
"url":"https://libraries.minecraft.net/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar"
    }
   }
  },
{
"name":"org.apache.logging.log4j:log4j-api:2.8.1",
"downloads":{"classifiers":{"tests":{"size":192791,
"sha1":"9d0c48c6186ea7f7f443803801ee7c9469129b85",
"path":"org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1-tests.jar",
"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1-tests.jar"}},
"artifact":{"size":228859,
"sha1":"e801d13612e22cad62a3f4f3fe7fdbe6334a8e72",
"path":"org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar",
"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar"
    }
   }
  },
{
"name":"org.apache.logging.log4j:log4j-core:2.8.1",
"downloads":{"classifiers":{"tests":{"size":1412295,
"sha1":"ef19122d4ad5de8da81fafabd007403007c8a832",
"path":"org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1-tests.jar",
"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1-tests.jar"}},
"artifact":{"size":1402925,
"sha1":"4ac28ff2f1ddf05dae3043a190451e8c46b73c31",
"path":"org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar",
"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar"
    }
   }
  },
{
"name":"org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209",
"rules":[{"action":"allow"},
{"action":"disallow",
"os":{
"name":"osx"}}],
"downloads":{"artifact":{"size":1047168,
"sha1":"697517568c68e78ae0b4544145af031c81082dfe",
"path":"org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar"
    }
   }
  },
{
"name":"org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209",
"rules":[{"action":"allow"},
{"action":"disallow",
"os":{
"name":"osx"}}],
"downloads":{"artifact":{"size":173887,
"sha1":"d51a7c040a721d13efdfbd34f8b257b2df882ad0",
"path":"org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar"
    }
   }
  },
{"extract":{"exclude":["META-INF/"]},
"name":"org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209",
"natives":{"linux":"natives-linux",
"osx":"natives-osx",
"windows":"natives-windows"},
"rules":[{"action":"allow"},
{"action":"disallow",
"os":{
"name":"osx"}}],
"downloads":{"classifiers":{"natives-linux":{"size":578680,
"sha1":"931074f46c795d2f7b30ed6395df5715cfd7675b",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar"},
"natives-osx":{"size":426822,
"sha1":"bcab850f8f487c3f4c4dbabde778bb82bd1a40ed",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar"},
"natives-windows":{"size":613748,
"sha1":"b84d5102b9dbfabfeb5e43c7e2828d98a7fc80e0",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar"}},
"artifact":{"size":22,
"sha1":"b04f3ee8f5e43fa3b162981b50bb72fe1acabb33",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar"
    }
   }
  },
{
"name":"org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822",
"rules":[{"action":"allow",
"os":{
"name":"osx"}}],
"downloads":{"artifact":{"size":1045632,
"sha1":"7707204c9ffa5d91662de95f0a224e2f721b22af",
"path":"org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar"
    }
   }
  },
{
"name":"org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822",
"rules":[{"action":"allow",
"os":{
"name":"osx"}}],
"downloads":{"artifact":{"size":173887,
"sha1":"f0e612c840a7639c1f77f68d72a28dae2f0c8490",
"path":"org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar"
    }
   }
  },
{"extract":{"exclude":["META-INF/"]},
"name":"org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822",
"natives":{"linux":"natives-linux",
"osx":"natives-osx",
"windows":"natives-windows"},
"rules":[{"action":"allow",
"os":{
"name":"osx"}}],
"downloads":{"classifiers":{"natives-linux":{"size":578539,
"sha1":"d898a33b5d0a6ef3fed3a4ead506566dce6720a5",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-linux.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-linux.jar"},
"natives-osx":{"size":468116,
"sha1":"79f5ce2fea02e77fe47a3c745219167a542121d7",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar"},
"natives-windows":{"size":613680,
"sha1":"78b2a55ce4dc29c6b3ec4df8ca165eba05f9b341",
"path":"org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-windows.jar",
"url":"https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-windows.jar"}
    }
   }
  },
{"extract":{"exclude":["META-INF/"]},
"name":"net.java.jinput:jinput-platform:2.0.5",
"natives":{"linux":"natives-linux",
"osx":"natives-osx",
"windows":"natives-windows"},
"downloads":{"classifiers":{"natives-linux":{"size":10362,
"sha1":"7ff832a6eb9ab6a767f1ade2b548092d0fa64795",
"path":"net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar",
"url":"https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar"},
"natives-osx":{"size":12186,
"sha1":"53f9c919f34d2ca9de8c51fc4e1e8282029a9232",
"path":"net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar",
"url":"https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar"},
"natives-windows":{"size":155179,
"sha1":"385ee093e01f587f30ee1c8a2ee7d408fd732e16",
"path":"net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar",
"url":"https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar"}
    }
   }
  },
{
"name":"com.mojang:text2speech:1.10.3",
"downloads":{"classifiers":{"natives-linux":{"size":7833,
"sha1":"ab7896aec3b3dd272b06194357f2d98f832c0cfc",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar"},
"natives-windows":{"size":81217,
"sha1":"84a4b856389cc4f485275b1f63497a95a857a443",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar"}},
"artifact":{"size":11055,
"sha1":"48fd510879dff266c3815947de66e3d4809f8668",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar"
    }
   }
  },
{"extract":{"exclude":["META-INF/"]},
"name":"com.mojang:text2speech:1.10.3",
"natives":{"linux":"natives-linux",
"windows":"natives-windows"},
"downloads":{"classifiers":{"natives-linux":{"size":7833,
"sha1":"ab7896aec3b3dd272b06194357f2d98f832c0cfc",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar"},
"natives-windows":{"size":81217,
"sha1":"84a4b856389cc4f485275b1f63497a95a857a443",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar"}},
"artifact":{"size":11055,
"sha1":"48fd510879dff266c3815947de66e3d4809f8668",
"path":"com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar",
"url":"https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar"
    }
   }
  },
{"extract":{"exclude":["META-INF/"]},
"name":"ca.weblite:java-objc-bridge:1.0.0",
"natives":{"osx":"natives-osx"},
"rules":[{"action":"allow",
"os":{
"name":"osx"}}],
"downloads":{"classifiers":{"natives-osx":{"size":5629,
"sha1":"08befab4894d55875f33c3d300f4f71e6e828f64",
"path":"ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar",
"url":"https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar"}},
"artifact":{"size":40502,
"sha1":"6ef160c3133a78de015830860197602ca1c855d3",
"path":"ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar",
"url":"https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar"
    }
   }
  },
{
"name":"ca.weblite:java-objc-bridge:1.0.0",
"rules":[{"action":"allow",
"os":{
"name":"osx"}}],
"downloads":{"classifiers":{"natives-osx":{"size":5629,
"sha1":"08befab4894d55875f33c3d300f4f71e6e828f64",
"path":"ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar",
"url":"https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar"}},
"artifact":{"size":40502,
"sha1":"6ef160c3133a78de015830860197602ca1c855d3",
"path":"ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar",
"url":"https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar"}}}],
"logging":{"client":{"file":{"id":"client-1.12.xml",
"sha1":"ef4f57b922df243d0cef096efe808c72db042149",
"size":877,
"url":"https://launchermeta.mojang.com/mc/log_configs/client-1.12.xml/ef4f57b922df243d0cef096efe808c72db042149/client-1.12.xml"},
"argument":"-Dlog4j.configurationFile=${path}",
"type":"log4j2-xml"}},
"mainClass":"net.minecraft.client.main.Main",
"minecraftArguments":"--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --versionType ${version_type} --tweakClass baritone.launch.BaritoneTweaker",
"minimumLauncherVersion":18,
"releaseTime":"2017-06-02T13:50:27+00:00",
"time":"2017-06-13T06:57:00+00:00",
"type":"release"}
-------------------------------------------------------------------------------------------------------------------

**Comment by TheOfficialGameDev** [comment]
My .json file for my minecraft hacked client: [https://pastebin.com/H2nk10YC](url)

**Comment by StijnSimons** [comment]
Mate you've hooked it to the launcher which isn't included in the jar (i think, correct me if i'm wrong).

```--tweakClass baritone.launch.BaritoneTweaker```

**Comment by TheOfficialGameDev** [comment]
I already put that in

**Comment by TheOfficialGameDev** [comment]
Theres no errors or anything, it just does absolutely nothing when i type #command.

**Comment by TheOfficialGameDev** [comment]
This is what I'm using: 
"minecraftArguments":"--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --versionType ${version_type} --tweakClass baritone.launch.BaritoneTweaker"

**Comment by 0-x-2-2** [comment]
You are not using launchwrapper. This won't work if you use MCP and just compile.

**Comment by pvorisek25** [comment]
@TheOfficialGameDev Did you figure out your problem? I have the same issue.

**Comment by dominikaaaa** [comment]
This should've been closed a while ago, read the new instructions

**Comment by blendifyClient** [comment]
i have had the same problem i would love to know the solution

**Comment by dominikaaaa** [comment]
Read the instructions

**Comment by Brackyt** [comment]
I think I've followed the instructions as much as I could (doesn't really help with setting it up for an existing project) I was able to add it and call baritone stuff but the game crashes with an exception class not found: bei when trying to use api functions. Not sure what I should do :/

**Comment by dominikaaaa** [comment]
That means you didn't add it properly. Look at the last 2 commits [here](https://github.com/kami-blue/client/commits/feature/baritone%23584/build.gradle) for how I did it

**Comment by Brackyt** [comment]
Thanks, that's completely different from what I did. One problem though is that I use mcp-reborn and my build.gradle setup is way different and I wasn't able to use what you did (I don't really know my way around gradle) and keep getting problems with it. Should I only use what's added in the commits or some of the other stuff too ?
If it's not a problem with you I would like to get your help on discord maybe ? So I don't send too many messages here since the problem might just be me. If you got the time and patience it would be awesome !

**Comment by dominikaaaa** [comment]
That doesn't matter. 

You should only add what I added in the last 2 commits to that file, and that's enough. 

Your build.gradle can be completely different and it'll still work, just add what's added in the diffs. You can contact me in my discord [here](https://discord.gg/KfpqwZB)

**Comment by xBlazeK1ng420x** [comment]
Guys. Add it on forge

**Comment by dominikaaaa** [comment]
That's not what this issue was for, let alone the fact that it's already closed and also 11 months old @xBlazeK1ng420x

**Comment by xBlazeK1ng420x** [comment]
I saw posts up to 2 months back so excuse me my bad. And ik its not a direct fix to this issue, your attempting to integrate it. Just offered an in the meantime solution that works overlapped. Ill take my happy ass elsewhere✌
