### ISSUE TITLE
Give JaminPRose 10,000 BB and 1 year premium

### ISSUE THREAD

**Issue by averycowan** [cabaletta/baritone#557]
Child of #436

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by StijnSimons** [comment]
Would you mind keeping the joke in __one__ issue. There are people that still take the issues seriously, and its already at 187 open issues.

**Comment by 0-x-2-2** [comment]
what did he mean by this.

**Comment by StijnSimons** [comment]
> what did he mean by this.

I think he meant giving him the "Baritone Premium(tm)" for a year for free to someone. Its a joke in the #436 issue.
