### ISSUE TITLE
When right or left clicking barritone sets positions

### ISSUE THREAD

**Issue by Samsung03** [cabaletta/baritone#558]
How do i remove the positions that barritone sets when right or left clicking? They are very annoying and will place blocks when I dont want it to. I am running barritone on Impact 4.6

**Comment by Samsung03** [comment]
will also open chests an it is very hard to get out of them because it continually opens.

**Comment by leijurv** [comment]
Are you stuck in `.b click`? Press escape lol

**Comment by Samsung03** [comment]
Build was activated for some reason
