### ISSUE TITLE
Disallow Specific Block Breaking

### ISSUE THREAD

**Issue by MEESTERSoupCan** [cabaletta/baritone#561]
## The suggestion
Force the AI to mine defined blocks without breaking specified blocks (Such as stone / cobblestone in Hypixel's Skyblock mineshafts)

## Settings
A list of blocks that should not be broken, or the ONLY blocks that can be broken.

## Context
Trying to use the 'mine' function when Baritone attempts to break blocks above ores, only for them to turn into bedrock after broken enough times (Hypixel's Stone breaking progress (Stone >> Cobblestone >> Bedrock))

**Comment by Deauthorized** [comment]
this is a settings > #blocksToAvoidBreaking

you can add blocks that baritone will avoid breaking by doing #blocksToAvoidBreaking minecraft:bedrock

you can also add multiple blocks by doing something like this > #blockstoavoidbreaking minecraft:fit,minecraft:mc

be aware tho that using this command replaces the entire list with whatever you specified

**Comment by 1Upped** [comment]
Tested, this doesn't work. <3

**Comment by Crayder** [comment]
`set blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,torch,wall_torch,soul_torch,soul_wall_torch`

Doesn't work. Please reopen.

**Comment by dominikaaaa** [comment]
There is a bug report already opened which causes inaccuracy for this setting

**Comment by aaronfranke** [comment]
This doesn't work. I have `#blocksToAvoidBreaking` set to `minecraft:dirt` and Baritone still breaks dirt in my farm.

**Comment by l1ving** [comment]
There is a bug report already opened which causes inaccuracy for this setting

**Comment by aaronfranke** [comment]
What is the # of the bug report? It's not linked here. You can link to issues by providing # and the issue number, like `#1`.

**Comment by l1ving** [comment]
The search bar is right there

**Comment by l1ving** [comment]
![Screenshot_20210108-002410.png](https://user-images.githubusercontent.com/17222512/103977734-dc91c280-5147-11eb-889a-79cd878176e1.png)
![Screenshot_20210108-002414.png](https://user-images.githubusercontent.com/17222512/103977745-def41c80-5147-11eb-8665-eda2067046ab.png)

**Comment by AdolfRoxler** [comment]
This is only to avoid, not a hard blacklist.

I need a hard blacklist.

**Comment by rycbar0** [comment]
have you tried the blocksToDisallowBreaking setting

**Comment by AdolfRoxler** [comment]
Does that even exist

**Comment by phpmypython** [comment]
> have you tried the blocksToDisallowBreaking setting

This also doesn't work.

**Comment by runningPencil501** [comment]
blocksToDisallowBreaking doesn't work for me too

**Comment by Vinnion** [comment]
2024 and still doesnt work

**Comment by Chocorot** [comment]
2025 and still doesnt work

**Comment by denny4-user** [comment]
2025 april - and still doesnt work

**Comment by VegaNavic** [comment]
still doesn't work when I do "#set blocksToDisallowBreaking minecraft:torch" it will ignore the setting entirely, and break torches

I also noticed when I use "minecraft:torch" in the command it saves the value as just "torch" instead of "minecraft:torch", so perhaps the value is being incorrectly stored/read and that is why it cannot properly avoid the block?

**Comment by wagyourtail** [comment]
torch is special, at least in 1.12, it'd be `wall_torch` for the ones on walls. but that still wouldn't prevent baritone breaking the block the torch is attached to, which isn't as easy to solve
