### ISSUE TITLE
Forge artifacts missing in last release (v1.3.3)

### ISSUE THREAD

**Issue by IdanHo** [cabaletta/baritone#566]
## What do you need help with?
I dont know if its intended but the latest release doesnt have forge versions.

## Final checklist
- [ ✓] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
Baritone does not support Forge on 1.13.2, only 1.12.2. The latest Forge version that you can acquire is for [1.2.7](https://github.com/cabaletta/baritone/releases/tag/v1.2.7).
