### ISSUE TITLE
Baritone: Build Crashes

### ISSUE THREAD

**Issue by TechnooCodes** [cabaletta/baritone#568]
Alright, so when using **.b build b** on Impact client, it does not do anything except print that it is loading, however once using **#build** my game crashes with the error of: "The game crashed whilst keypressed event handler
Error: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo"

On version: 1.13.2

**Comment by StijnSimons** [comment]
Build. Doesnt. Work. For. 1.13.2.

**Comment by ZeroMemes** [comment]
#506
