### ISSUE TITLE
How to use build

### ISSUE THREAD

**Issue by NerdFNT19** [cabaletta/baritone#570]
I would love some help on how to make schematics and then build them, I can't figure it out for the life of me.

**Comment by StijnSimons** [comment]
[How to make schematics](https://lmgtfy.com/?q=how+to+make+minecraft+schematics&s=g)

**Comment by Bluebirddxx** [comment]
Yeah stijnsimons can suck a fat cock,. that doesn't even tell us where to put the fucking schematics folder in our %appdata%

**Comment by StijnSimons** [comment]
Lol if you’re gonna reply like that, have fun figuring it out.

**Comment by acesblue** [comment]
StijnSimons could you please tell me where I would put the .schematic files in order for baritone to pick them up?

**Comment by StijnSimons** [comment]
@acesblue `%appdata%/.minecraft/schematics`

**Comment by acesblue** [comment]
it still doesn't work :\

**Comment by 0-x-2-2** [comment]
place file in "%appdata%/.minecraft/schematics" as "cool.schematic" then load it with "#build cool"

**Comment by acesblue** [comment]
it says unable to load.

**Comment by Cerbiac** [comment]
Are items in your inventory, and are you one 1.12?

**Comment by acesblue** [comment]
yes

**Comment by acesblue** [comment]
https://www.youtube.com/watch?v=Rge_IFYtlzQ&feature=youtu.be

**Comment by Cerbiac** [comment]
And you're sure it is 1.12?

**Comment by BlueBlazeTech** [comment]
@acesblue dumb but necessary question. have you checked to see that none of your mods are not compatible with baritone, therefore causing things to interfere with each other? this is a problem that I had that took me way to long to figure out xD
