### ISSUE TITLE
Better water bucket usage

### ISSUE THREAD

**Issue by Master-64** [cabaletta/baritone#578]
I think that the bot should be prepared to put water below him in the case that his pathing happens to get confused and/or stop working (example: is falling and gets confused, instead of dying to fall damage, he uses the water bucket). Additionally, he should be able to save himself from burning to death if he has a water bucket, with this being able to be toggled on and off.

**Comment by Darkar25** [comment]
About saving himself,i think there should be some kind of mob defense...at least in mining mode...

**Comment by nbyrd** [comment]
@Darkar25 Agreed. I have been playing with Baritone for a couple of days now (so forgive me if I'm being a noob) and--regardless of whether avoidance mode is enabled--the bot seems to simply ignore the presence of enemies and is happy to hug creepers if that brings it closer to satisfying its goals.

But I think that's probably a bit off topic.

On topic, I think that the bot could use water buckets better around lava. Perhaps it could use water to create obsidian paths across lakes of lava in the overworld as part of its navigation algorighm, or understand that water + lava source = obsidian when instructed to mine for it.

**Comment by Cerbiac** [comment]
@nbyrd @Master-64 Yeah, please make a separate issue for multiple enhancements. I'll close it if I don't notice one of the suggestions in a new issue.

**Comment by S-B99** [comment]
This is already a thing, except for the burning part, which is #13
