### ISSUE TITLE
Enhanced Parkour Tech

### ISSUE THREAD

**Issue by Master-64** [cabaletta/baritone#579]
Why are quad jumps not a thing? This is an essential mechanic!
If this happens to be inconsistent, maybe give the bot a tiny enough speed boost to make it every time. Although, this feature should probably be something you can toggle.

Also, how come head hitters or simple parkour jumps that go up one block can't be done? It makes no sense.

Edit: I do know that someone else has suggested this, but this includes a possible solution to this problem, which I believe renders this useful.

**Comment by ZeroMemes** [comment]
This has been done, and it was too inconsistent to be added. Baritone will never perform any actions that are outside of the reach of being done with player control (i.e. there will never be a slight speed boost provided so that a specific movement can be made).
