### ISSUE TITLE
Explosives confuse bots

### ISSUE THREAD

**Issue by Master-64** [cabaletta/baritone#581]
## Some information
Operating system: Windows 10 - 64 Bit
Java version: 1.8.0-b132
Minecraft version: 1.12.2
Baritone version: 1.3.3
Forge mods (if used): Cyclic

## Exception, error or logs
No logs to report on this.

## How to reproduce
Have the first player turn into a bot with god mode and run to a goal on any sort of terrain (happens more on elevated terrain).
Now, get a second player to throw a dynamite stick at the bot. About 20-30% of the time, the bot will freeze for a solid 4 seconds, jittering his view up and down rapidly. After the 4 seconds are up, the bot resumes his goal like nothing happened.

Note: this bug happens with other things that aren't explosive related, but are harder to do consistently.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
Yeah, no.

**Comment by ZeroMemes** [comment]
There are so many mods that could cause issues it's not worth addressing all of the possible edge cases that may occur.

**Comment by c0nn3r** [comment]
Sticks of dynamite are no joke. This is high priority issue. What mod? I’m assigning @ZeroMemes to this ASAP.

**Comment by ZeroMemes** [comment]
>Forge mods (if used): Cyclic

**Comment by Master-64** [comment]
The problem is that this doesn't just happen with Cyclic. If it's just a vanilla game, this stuff still happens (usually with stuff that involves changing blocks, or lava moving).

**Comment by ZeroMemes** [comment]
Then that's a separate issue
