### ISSUE TITLE
How Do I Start It Up?

### ISSUE THREAD

**Issue by ThatGuyNathan54** [cabaletta/baritone#582]
I Need To Know How To Access It And Get It Started!

**Comment by babbaj** [comment]
📸

**Comment by kittenswolf** [comment]
https://impactdevelopment.github.io/

**Comment by Napr408** [comment]
WHere is the project read me? @kittenswolf

**Comment by leijurv** [comment]
> WHere is the project read me?

📸

**Comment by Napr408** [comment]
@leijurv  I cant find it anywhere can you link it?

**Comment by StijnSimons** [comment]
📸i can't tell if you're joking

**Comment by Napr408** [comment]
Im not @StijnSimons  I really dont know!

**Comment by StijnSimons** [comment]
[Go wild.](https://github.com/cabaletta/baritone/blob/master/README.md)

**Comment by 0-x-2-2** [comment]
hello me as a moderator i will have to tell you that the best way to get the baritone "read me" is to download "git" and "vim" and clone the repo with "https://github.com/cabaletta/baritone.git" then "cd baritone && vim README.md". ignore what @StijnSimons said this is the best and the only way to read the readme correctly.

**Comment by StijnSimons** [comment]
> hello me as a moderator for the baritone repo i will have to tell you that the best way to get the baritone "read me" is to download "git" and "vim" and clone the repo with "https://github.com/cabaletta/baritone.git" then "cd baritone && vim README.md". ignore what @StijnSimons said this is the best and the only way to read the readme correctly.

I am so sorry mister moderator
