### ISSUE TITLE
I need some fantastic schematics

### ISSUE THREAD

**Issue by SmileDeath233** [cabaletta/baritone#583]
Where can I find some good schematics by others?

**Comment by kittenswolf** [comment]
https://www.minecraft-schematics.com

This is not really a baritone related issue

**Comment by babbaj** [comment]
:camera_flash:

**Comment by SmileDeath233** [comment]
Dude. I can't register on this website.Why?
---原始邮件---
发件人:"kittenswolf"<notifications@github.com>;
发送时间:2019年7月19日(星期五) 下午4:01
收件人:"cabaletta/baritone"<baritone@noreply.github.com>;
抄送人:"SmileDeath233"<442585968@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [cabaletta/baritone] I need some fantastic schematics (#583)


https://www.minecraft-schematics.com
 
This is not really a baritone related issue
 
&mdash;

**Comment by StijnSimons** [comment]
If this isn't a baritone issue, __why put it here???????????????????__
📸
