### ISSUE TITLE
#tunnel command is invalid

### ISSUE THREAD

**Issue by boatfullogoats** [cabaletta/baritone#584]
The #tunnel command, although apparently a command in usage, when i attempt to use, is said is invalid.

**Comment by Thunder33345** [comment]
try .b tunnel?
no clue i always used .b prefix and it works

**Comment by Thunder33345** [comment]
just logged in and checked
yep seems that .b tunnel, would trigger it 
but #tunnel would say unknown command

**Comment by S-B99** [comment]
This seems to be fixed.
