### ISSUE TITLE
Boat usability

### ISSUE THREAD

**Issue by Darkar25** [cabaletta/baritone#585]
## Describe your suggestion
Make baritone able to use boats

## Settings
Use boats (boolean)

## Context
This will improve speed movement on water

## Final checklist
- [ + ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Currently, baritone doesn't really like water so don't really see support soon. Who knows?

**Comment by 0-x-2-2** [comment]
Baritone does not not work with rideable entities.

**Comment by mrphax0r** [comment]
This is the problem. It is something to accomplish and not forget in the future

**Comment by 0-x-2-2** [comment]
#223 kinda related to this

**Comment by adwerygaming** [comment]
welp

**Comment by tsIsFried** [comment]
We need this
