### ISSUE TITLE
Ability to use Baritone without Minecraft API

### ISSUE THREAD

**Issue by Cubxity** [cabaletta/baritone#586]
## Describe your suggestion
Ability to use Baritone "standalone" without Minecraft classes at all.

## Context
The reason why it should be added is that it allows the ability for developers to make bots without needing the full Minecraft client itself.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
This is very much not currently possible.

**Comment by Cubxity** [comment]
> 
> 
> This is not really possible however nothing is stopping you from implementing already existing game code in your headless Minecraft client.

How so? Wouldn't it be possible to make interfaces for us to implement, e.g: IWorldProvider, IPlayerProvider, etc..?

**Comment by 0-x-2-2** [comment]
This would be a lot of work regardless Baritone depends on ALOT of Mojang code.

**Comment by ZeroMemes** [comment]
I think what is meant here is Baritone API usage without the need of importing Minecraft, which actually wouldn’t be too difficult

**Comment by Cubxity** [comment]
@ZeroMemes yea, that's exactly what I meant

**Comment by leijurv** [comment]
This would make baritone as a dependency of impact 100x easier

**Comment by 0-x-2-2** [comment]
> @ZeroMemes yea, that's exactly what I meant

I'm very sure what Brady said confused you because the issue you made before this one was for some [Minecraft protocol library](https://github.com/Steveice10/MCProtocolLib/issues/470) and you also said this "allows the ability for developers to make bots without needing the full Minecraft client itself.". Can you make it clear what you really want because what Brady was talking about is the Baritone API won't need Minecraft client but running Baritone still will.

**Comment by Cubxity** [comment]
@0-x-2-2 Yea I'm a bit confused here, what's the difference between "Baritone" and "Baritone API"? Also what I wanted is to make headless bots with the AI that Baritone has without needing the full MC client

_Sent from my Mate 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 0-x-2-2** [comment]
The Baritone API is what mods can use to control Baritone.

**Comment by ZeroMemes** [comment]
This isn't going to happen.
