### ISSUE TITLE
How to disallow place blocks?

### ISSUE THREAD

**Issue by zombozo12** [cabaletta/baritone#587]
Currently playing on a server that cannot place a block but allowed to break specific blocks. I wonder how to disallow place because its always put cobble stone and it disappear, makes myself stuck in the cobble stone. Is it available only from api (i code my own automine, change allowPlace value from code) or i can change allowPlace value to false in chat command?

**Comment by ZeroMemes** [comment]
You can toggle allowPlace by simply typing `#allowPlace` in chat.

**Comment by zombozo12** [comment]
Thank you :)
