### ISSUE TITLE
building it myself

### ISSUE THREAD

**Issue by bobross135** [cabaletta/baritone#589]
I have done everything it tells you to do in the building guide but cant figure out what to do afterwards to actualy use it.

**Comment by StijnSimons** [comment]
Lemme guess, 1.13?

**Comment by bobross135** [comment]
no i was trying to build it with the guide it told me i downloaded the thing that it says to and everything

**Comment by StijnSimons** [comment]
Misread.

**Comment by bobross135** [comment]
oh

**Comment by leijurv** [comment]
Look in `dist/`

**Comment by bobross135** [comment]
what do i do witht the things in dist
