### ISSUE TITLE
is there a way to make it 1.14.3 myself ?

### ISSUE THREAD

**Issue by bobross135** [cabaletta/baritone#591]
i have already followed the instructions on how to build it myself i just don't know how to make it for 1.14.3

**Comment by hazenaerial** [comment]
also, is it able to make it for 1.12.0 not 1.12.2?

**Comment by StijnSimons** [comment]
i give up on these kinds of issues

**Comment by plootia** [comment]
agreed

Baritone only supports 1.12-1.13, it is not compatible with 1.14 yet.

**Comment by ZeroMemes** [comment]
If you’re asking this question, the odds are that you won’t be able to anyways.

**Comment by Jody7** [comment]
https://jody.life/pics/images/webm/gD1hpUt.webm updating baritone to 1.14.3 isn't too hard to do, just pretty time consuming. if people are interested, id be fine releasing the patch for it (thanks for leijurv doing most of the fixes)

**Comment by LeafHacker** [comment]
@Jody7 if you've got a working build a PR is the best bet. That way any code style changes can be discussed and it can get into baritone, or worst case if it isn't merged it'll still point out areas for improvement in baritone.

**Comment by Jody7** [comment]
@LeafHacker current build is pretty hacked together and is pretty unstable, but I can pr it to the 1.14.2 branch if you want. also please add 1.14.3 to the impact maven, because currently my 1.14.3 build requires local maven repo

**Comment by yoann56100** [comment]
can some one release the patch or write the instruction cause im not very good in code
(sorry for my english im french)

**Comment by bobross135** [comment]
@Jody7 can you release it i know its bad but that doesn't matter i just want to be lazy and get diamonds on 1.14.3

**Comment by zune127** [comment]
@Jody7 If you could upload your buggy 1.14.3 client and port it to 1.14.2 I would really appreciate it; the new 1.14.4 version doesn't seem to work on .2/.3.

**Comment by StijnSimons** [comment]
Baritone 1.14.4 is out, impact 1.14.4 isn't.

**Comment by zune127** [comment]
> [Baritone 1.14.4](https://www.dropbox.com/s/rkml3hjokd3qv0m/1.14.4-Baritone.zip?dl=1) is out, impact 1.14.4 isn't.
> [Tutorial](https://cdn.discordapp.com/attachments/514880901629607947/603467235796844544/k9gHgUaNV3.mp4)

Yeah, but 1.14.2/3 do not work and most minecraft servers are not running on 1.14.4. A 1.14.3/.2 backport would be very much appreciated by alot of people on those servers.

**Comment by StijnSimons** [comment]
There's no way to maintain a project with 5 versions. 3 is enough for now and i guess you'll just have to wait until they update.

**Comment by bobross135** [comment]
or that person on with the 1.14.3 version could just release it

**Comment by 0-x-2-2** [comment]
No one has working Baritone 1.14.3 only 1.14.4 exists and for a good reason no one should be using 1.14.3 its more buggy with the same features.
