### ISSUE TITLE
no react when using .b build in version 1.13.2

### ISSUE THREAD

**Issue by YiyangWilliam** [cabaletta/baritone#593]
I have already create a folder "schematics" in ".minecraft" and i have already pasted the schematic file into a folder. But when I run .b build command, It just say loading the file but do nothing

**Comment by Fefect** [comment]
The build command does not work in 1.13, it only works for 1.12

**Comment by Deauthorized** [comment]
build. is. not. supported. on 1.13.2.

**Comment by 0-x-2-2** [comment]
> build. is. not. supported. on 1.13.2.

this
