### ISSUE TITLE
#build schematic not placing blocks

### ISSUE THREAD

**Issue by riririru** [cabaletta/baritone#595]
## What do you need help with?
when i type in the command #build "schematic name"
it starts to clear the area like normal, but once the area is clear
it stops and says, "Unable to do it. pausing. resume to resume, cancel to cancel"
i tried both resume and cancel non of them works.
tried it on a flat world and in creative as well as the server im playing on

## Final checklist
- [x ] I have not used any OwO's or UwU's in this issue.
i dont know what owos or uwus are but i hopefully didnt use any

edit:
i tried to build just a 4x4 block and that worked, but larger buildings do not work

**Comment by scorbett123** [comment]
Unless you can still reproduce this and send a log, I think this issue is better off closed.
