### ISSUE TITLE
Minecraft window 10 edition 

### ISSUE THREAD

**Issue by xhtyti7** [cabaletta/baritone#597]
Does Baritone work on minecraft window 10 edition? i keep receiving message "vanilla minecraft" something not found i have Version 1.12.0

**Comment by 0-x-2-2** [comment]
📸

**Comment by ZeroMemes** [comment]
No Baritone will not be receiving support for Minecraft Windows 10 Edition.

**Comment by mrphax0r** [comment]
@xhtyi7 those are java developers. Win10/Bedrock edition is NOT java. So baritone will probably never be ported to Bedrock.

**Comment by Kiffolisk** [comment]
@xhtyti7 Baritone will never be ported to Bedrock, as far as I know, the thing you could try to do yourself is to download the code, and try to somehow edit it for Bedrock.
