### ISSUE TITLE
when I launch Minecraft my game crash

### ISSUE THREAD

**Issue by yoann56100** [cabaletta/baritone#603]
Im trying to install bariton in minecraft 1.13.2 but when I launch the game it crash
My code
{
  "id": "1.13.2-OptiFine_HD_U_E6",
  "inheritsFrom": "1.13.2",
  "time": "2019-05-18T12:28:29+02:00",
  "releaseTime": "2019-05-18T12:28:29+02:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13.2_HD_U_E6"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
    "name":
    "cabaletta:baritone-api:1.3.3",
    "downloads":{
      "artifact": {
        "path": "cabaletta/baritone-api/1.3.3/baritone-api-1.3.3.jar",
        "sha1": "64f5e4742382d2e41d9e419319e7ea97ba233796",
        "size": 296318,
        "url": "https://github.com/cabaletta/baritone/releases/download/v1.3.3/baritone-api-1.3.3.jar"
      }
    }
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker",
      "--tweakClass",
      "baritone.launch.BaritoneTweaker"
    ]
  }
}

**Comment by ZeroMemes** [comment]
Send the crash log
