### ISSUE TITLE
Automine: Add option to mine multiple ores + cooperation with auto food.

### ISSUE THREAD

**Issue by Jan-Intelkor** [cabaletta/baritone#604]
## Describe your suggestion
When I want to leave auto mine to mine for a long time, I would need to switch ores it can mine.
Maybe add a option to select which ores should it mine. Also, the bot doesn't work with Auto Food. It can be done also in this way: Select primary ore and secondary. It will mine primary, like diamonds, but when it will collect enough, or will encounter that secondary ore is close, it will temporary switch to it.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

Change Auto mine menu, make it cooperate with Auto Food
Alternative 1:
Add option to just mine everything, expect logs.
Alternative 2:
Make a condition system like: if 64 diamonds in inventory switch to gold

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
Will improve it's great AI usability

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.
Don't know what that means

**Comment by StijnSimons** [comment]
To mine multiple ores, type 
`.b mine diamond_ore iron_ore gold_ore`.

**Comment by danbulant** [comment]
This actually works in impact pretty well.
Turn on auto food, it will pause the bot to eat and then resume it. @StijnSimons already wrote how to mine multiple ores at a time

**Comment by dominikaaaa** [comment]
Closed due to inactivity and resolved.
