### ISSUE TITLE
crashes my game when minecraft is launched

### ISSUE THREAD

**Issue by lolbox123** [cabaletta/baritone#608]
Hello
I am trying to use baritone in combination with future client and have installed forge, I put the baritone-standalone-forge-1.2.7.jar in the mods folder but the game crashes whenever i try to run the game.

**Comment by 0-x-2-2** [comment]
🚨

**Comment by 0-x-2-2** [comment]
Can you send a crash report?

**Comment by lolbox123** [comment]
the launcher will not let me view the crash report

**Comment by lolbox123** [comment]
even when i go into files, there is nothing there

**Comment by 0-x-2-2** [comment]
Send logs/debug.log

**Comment by lolbox123** [comment]
where do i find that?

**Comment by 0-x-2-2** [comment]
"%appdata%\.minecraft\logs\"

**Comment by lolbox123** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/3415387/latest.log)

**Comment by 0-x-2-2** [comment]
You downloaded the wrong jar.

**Comment by lolbox123** [comment]
what did i need to download?

**Comment by 0-x-2-2** [comment]
https://github.com/cabaletta/baritone/releases/download/v1.2.7/baritone-standalone-forge-1.2.7.jar

**Comment by lolbox123** [comment]
TY it worked
