### ISSUE TITLE
Autominer is randomly mining

### ISSUE THREAD

**Issue by xXRH23Xx** [cabaletta/baritone#609]
## What do you need help with?
Autominer just mines afew blocks then walks off somewhere else this keeps repeating https://youtu.be/gcHOFadS7LM

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
This server has Anti-XRay enable legitMine with "#legitMine" in chat.

**Comment by xXRH23Xx** [comment]
thanks
