### ISSUE TITLE
Better chunk caching (save a list of blocks each chunks contains)

### ISSUE THREAD

**Issue by TypicalHog** [cabaletta/baritone#614]
There should be an option (either when the basic chunk caching is on or it could be a part of more advanced chunk caching) that would save a list of blocks present in each chunk. For example, if there were no chests within the loaded chunks - if would then look inside the cached chunks instead of giving up, upon finding a chunk that contains a chest if would go towards it and when the chunks loads - it would scan the chunk and go to the chest as it does currently. If this would be too heavy on the performance - there could be a list of one or a few blocks that chunks would be scanned for.

This would make pathfinding to blocks that are not within the loaded chunks (or baritone scan range) possible.

EDIT: It would not save every block, just a true/false if the chunk contains the specific block. (or simply the list of blocks present)

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by DaMatrix** [comment]
why not just use world downloader at that point lol

**Comment by TypicalHog** [comment]
> why not just use world downloader at that point lol

Nah, you didn't get the point. It would not save full chunks, just the list of the blocks the chunk contains, like:

dirt
grass
stone
log
crafting_table
etc.

**Comment by Cerbiac** [comment]
How would it decide which chunk to goto? Storing an amount would be better like for resource gathering, and then math can be done based on distance and amount to decide which one to goto.

However, a better solution would be telling Baritone what blocks should be cached properly, and there could also be an override "cache all" setting that would probably kill your computer.

**Comment by leijurv** [comment]
This is literally exactly what it already does lmao.
