### ISSUE TITLE
writing #stop is bannable

### ISSUE THREAD

**Issue by riririru** [cabaletta/baritone#619]
i just got auto banned on a server for writing #stop
so heads up, and rather write #cancel

bann reason: trying to stop/restart the server(autoban) banned by console

impact version 4.6, minecraft version 1.12.2

**Comment by StijnSimons** [comment]
📸 lol

**Comment by leijurv** [comment]
LOL

**Comment by leijurv** [comment]
Was baritone running? Why did #stop get sent in chat tf

**Comment by StijnSimons** [comment]
Which server even autobans on #stop in chat

**Comment by riririru** [comment]
impact/baritone was running

**Comment by Cerbiac** [comment]
Use `.b` if you are using Impact, as Impact will intercept it and not send to chat, but `#` should work, so...

**Comment by Cerbiac** [comment]
Provide Impact and Minecraft version info IG. 🤷‍♂

**Comment by ZeroMemes** [comment]
This is a massive 🦍 moment. What is the server hostname/IP?

**Comment by usereewrjrjeejr** [comment]
Cringe

**Comment by usereewrjrjeejr** [comment]
LOL

**Comment by zune127** [comment]
they know the terminators are coming, ban the bots!

**Comment by 0-x-2-2** [comment]
@riririru What is the server ip? I do not think a server can detect this 🤔

**Comment by Mhowser** [comment]
Poisoned plugins usually use `#` as a control character
