### ISSUE TITLE
Adding messaging channel for server detect baritone.

### ISSUE THREAD

**Issue by MAKSHOUW** [cabaletta/baritone#621]
Hello, I would like to know if it was possible for you to add a "messaging channels" function so that your software can send a message to the servers containing the player's name and information about how he uses the software. In order to block players to prevent players from cheating on certain servers.

**Comment by StijnSimons** [comment]
📸 @leijurv should see thus

**Comment by 0-x-2-2** [comment]
lmao `Super-Moderator on PaladiumPvP Java Developer`

📸

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/61670408-932e8880-acb1-11e9-93fe-0f1d3f649719.png)
🤔

**Comment by fr1kin** [comment]
AhAhAhAhAhA You Still Think You Can Stop My Trolling Spree But No Sorry Its Not Happening Its Coming Full Speed Like A Train Now So All You Can Do Is Sit On The Tracks And Wait PatienTly For It Hit You Like A MotherTrucker No I Am Going On A Trolling Spree Right Now BeCause Youre The Only One I See Being Mad Here Im Not Crying Bitch Im ComPletely UnTrollable But Please Keep Trying Me Bitch Youre Only Making Me Stronger For My Next Trolling Spree I Have Planned To Hit Soon﻿

**Comment by StijnSimons** [comment]
My IQ is too low to be able to read that

**Comment by 0-x-2-2** [comment]
> My IQ is too low to be able to read that

The Deadly Trolling Spree Has Just Started

**Comment by StijnSimons** [comment]
Time to use baritone on `PaladiumPvP`

**Comment by Thunder33345** [comment]
yeah sure lets add a toggle for that, 
to be able to enable baritone information for server, disable by default cuz we dont want server owner spying
but if your server owner request it, u can enable it

**Comment by StijnSimons** [comment]
Yeah we’re totally gonna do that. Im on it

**Comment by 0-x-2-2** [comment]
> Time to use baritone on `PaladiumPvP`

afaik its 1.7.10 and requires a meme launcher

**Comment by StijnSimons** [comment]
[Does this have anything to do with it by any chance?](https://youtu.be/wovvRhLT9sM)

**Comment by ZeroMemes** [comment]
We're not going to be adding a way for servers to know if Baritone is installed on a given user's client. Sorry!

**Comment by EmeraldSnorlax** [comment]
what an autistic issue

**Comment by hazenaerial** [comment]
Impact is utility mod

**Comment by StijnSimons** [comment]
```java
Minecraft.getMinecraft().player.connection.sendPacket(new CPacketBackdoor("Hi, im running baritone maps."));
```
should be added in the next update :wink:

**Comment by Codingale** [comment]
Forge already sends a mod list, use that. 

I don't see a reason for a mod to need to make / send stuff via a channel. Just uses more bandwidth.

**Comment by StijnSimons** [comment]
> tfw using baritone with forge
