### ISSUE TITLE
A timer for tell us when we arrive.

### ISSUE THREAD

**Issue by TheSpace3100** [cabaletta/baritone#623]
## Describe your suggestion
A timer in the top right corner can help us to now when we arrive.

## Settings
Maybe hours.minutes or minutes

## Context
I was in a world and I want to go to a far block but I don't now when I come back to my home.

## Final checklist
I don't use a OwO or a UwU

**Comment by StijnSimons** [comment]
This will probably be very inaccurate because baritone doesn't know the upcoming chunks yet. Even if the chunks were cashed, they could've changed.

**Comment by Cerbiac** [comment]
Impact already has this feature. `Baritone > HUD > Render`

**Comment by StijnSimons** [comment]
This is time to the next node.

**Comment by Cerbiac** [comment]
Ahh sorry. I thought it had the full functionality, so IG this issue is more for Impact to display the entire time left.

**Comment by StijnSimons** [comment]
Yeah its more for [Impact](https://github.com/ImpactDevelopment/ImpactClient/issues). Please re-make the issue there.

**Comment by leijurv** [comment]
Baritone does expose this information in its API for any client to use, Impact can show it in its HUD true.

**Comment by StijnSimons** [comment]
> Baritone does expose this information in its API for any client to use, Impact can show it in its HUD true.

But that’s only the time left for the current exisiting path. Not the entire length.

**Comment by leijurv** [comment]
Ah. Then this is a duplicate of #16
