### ISSUE TITLE
Is there a way to backport the new version to 1.14.2?

### ISSUE THREAD

**Issue by zune127** [cabaletta/baritone#629]
I have used the new 1.14.4 version but was wondering if it was possible to backport to 1.14.2 and if it would be compatible. I also noticed that the 1.14.2 branch has been removed.  Is there a backport planned, or is it going to be 1.14.4 only?

**Comment by Powerlated** [comment]
https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git

Do this and compile.

**Comment by StijnSimons** [comment]
> https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git
> 
> Do this and compile.

??? There never was a 1.14.2 "state".

**Comment by zune127** [comment]
> https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git
> 
> Do this and compile.

The 1.14.2 branch couldn't compile when I tried two weeks ago, now it's gone and replaced with the new version. I don't think it would work unless it had been fixed

**Comment by StijnSimons** [comment]
Because the 1.14.2 branch never worked.
