### ISSUE TITLE
1.14.4 baritone - multimc support

### ISSUE THREAD

**Issue by matty45** [cabaletta/baritone#632]
Would it be possible to make multimc support the 1.14.4 version of baritone?

**Comment by 0-x-2-2** [comment]
Use the vanilla launcher or make your own instance.

**Comment by GrimReaperFloof** [comment]
Big oof.
But MultiMC is better than vanilla launcher :(
Change my mind

**Comment by GrimReaperFloof** [comment]
> Would it be possible to make multimc support the 1.14.4 version of baritone?

also, I already have found a way to install Baritone 1.14.4 into MultiMC: https://github.com/cabaletta/baritone/issues/642#issuecomment-515186974

**Comment by UltraBlackLinux** [comment]
If someone still needs .json Files: https://github.com/UltraBlackLinux/MultiMC-Patch-Gen

**Comment by lil-tec** [comment]
1. Go to https://github.com/cabaletta/baritone/releases
2. Download baritone-api-forge (Choose whatever version you like) (just for Forge IS supported)
3. Click edit instance. install forge (Any version)
4. Click Loader mods and add baritone jar
5. Launch and youre done
