### ISSUE TITLE
Add option to craft with chat commands

### ISSUE THREAD

**Issue by EmeraldSnorlax** [cabaletta/baritone#633]
It would improving the usefulness of baritone in scripts, as you could tell it to mine some wood then craft planks

## Context
~~twitch plays minecraft~~ Automation, scripting

## Final checklist
- [ OwO ] I have not used any OwO's or UwU's in this issue.

**Comment by acesblue** [comment]
https://github.com/cabaletta/baritone/issues/640

**Comment by StijnSimons** [comment]
Copy of #640.

**Comment by NatoBoram** [comment]
#640 was closed in favour of #295
