### ISSUE TITLE
Need to add Killaura/Forcefield (Mobs)

### ISSUE THREAD

**Issue by Disgame** [cabaletta/baritone#635]
Hey would be nice to add Killaura, because sometimes mobs are running towards me while mining and stopping the process. Would be nice to kill/detect them :)

**Comment by StijnSimons** [comment]
Just use [Impact](https://github.com/ImpactDevelopment/ImpactClient) for now.

**Comment by GamingInfinite** [comment]
Baritone is meant as a ghost modification, which the way I see it is meant to be a advantage, but not super noticeable, so if your playing survival, just use https://github.com/ImpactDevelopment/ImpactClient.  If you're playing on a server, just use https://github.com/ImpactDevelopment/ImpactClient.  That simple.
