### ISSUE TITLE
avoidance appears not to be working 1.14.4

### ISSUE THREAD

**Issue by realflow100** [cabaletta/baritone#636]
Avoidance doesnt seem to work. walks right into creepers killing me. tried changing the settings from default but no difference. happens when automining

**To Reproduce**
1. enable avoidance
2. it doesnt seem to work. walking right into creepers and zombies and getting me killed by mobs.

**Expected behavior**
Avoidance should path me away from hostile mobs any chance it gets.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: none.
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: just baritone 1.14.4
- Operating System: windows 7 pro 64-bit
- Minecraft version: 1.14.4

</details>
## Final checklist
- [+] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [+] I have included logs, exceptions and / or steps to reproduce the issue.
- [+] I have not used any OwO's or UwU's in this issue.

**Comment by EphraimBane** [comment]
I'm experiencing this bug too.
OwO UwU <-- Take that, checklist!

**Comment by StijnSimons** [comment]
banned

**Comment by scorbett123** [comment]
Avoidance doesn't just avoid mobs, it adds extra cost for going near them.
