### ISSUE TITLE
cant build from source or even setup workspace when using the Java 11+ JDK

### ISSUE THREAD

**Issue by Leterax** [cabaletta/baritone#637]
## Some information
Operating system: Windows 10
Java version: Java 11 JDK+
Minecraft version: doesn't matter
Baritone version: up to 1.4.0
Forge mods (if used): None

## Exception, error or logs
`package java.xml.bind does not exist`

Since Java 9 the package java.xml.bind has been marked as DEPRECATED.  With the introduction of Java 11 it has been REMOVED. This causes the gradle build task to fail when importing 
`import baritone.gradle.task.CreateDistTask`.
In `CreateDistTask` the function `sha1` is called.

```
private static synchronized String sha1(Path path) {
        try {
            if (SHA1_DIGEST == null) {
                SHA1_DIGEST = MessageDigest.getInstance("SHA-1");
            }
            return DatatypeConverter.printHexBinary(SHA1_DIGEST.digest(Files.readAllBytes(path))).toLowerCase();
        } catch (Exception e) {
            // haha no thanks
            throw new IllegalStateException(e);
        }
    }
```
In `sha1`, `DatatypeConverter.printHexBinary` is called. `DatatypeConverter` is a part of `java.xml.bind` and causes the error to be raised. By naively the hash is always the same and returning the same string (eg "totallylegitsha1hash") this error is avoided, however later in the build task an error is raised that java 11 and over is not supported.

## How to reproduce
Try to follow the setup guide with the Java 11 (or newer) JDK installed

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and/or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Leterax** [comment]
I suggest implementing your own `printHexBinary` function to avoid any problems with `java.xml.bind`.
Either something simple like
```java
public String encodeHexString(byte[] byteArray) {
    StringBuffer hexStringBuffer = new StringBuffer();
    for (int i = 0; i < byteArray.length; i++) {
        hexStringBuffer.append(byteToHex(byteArray[i]));
    }
    return hexStringBuffer.toString();
}
```
Or a more official option using google's guava lib
```java
public String encodeUsingGuava(byte[] byteArray) {
    return BaseEncoding.base16().encode(byteArray);
}
```
Also in `CreateDistTask.java` the encoding for `SHA1_DIGEST.digest` should always be specified. 
(eg. `SHA1_DIGEST.digest(Files.readAllBytes(path).getBytes("UTF-8"))`)

**Comment by StijnSimons** [comment]
... or install jdk-8???????????????????????????????????????????????? You know you can have multiple development kits, right?

**Comment by leijurv** [comment]
This is known and actually intentional. Baritone built with JDK 11 is too new to work in all cases. Minecraft uses an embedded JRE that only supports Java 8.

**Comment by Leterax** [comment]
> This is known and actually intentional. Baritone built with JDK 11 is too new to work in all cases. Minecraft uses an embedded JRE that only supports Java 8.

Ah ok. I was not aware of Minecraft still using Java 8. Thanks for the replies and cant wait to see what you do next!
