### ISSUE TITLE
[1.14.4] Stepping on a shulker box crashes the game 

### ISSUE THREAD

**Issue by Powerlated** [cabaletta/baritone#638]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Forge mods (if used): 

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Scarbrine** [comment]
bruh there is no info at all

**Comment by StijnSimons** [comment]
A stacktrace would’ve been helpful.

**Comment by usereewrjrjeejr** [comment]
Shit issue

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/afebdce1f82969a79d029222fc485668be16c094
