### ISSUE TITLE
Installing Baritone in MultiMC

### ISSUE THREAD

**Issue by chexo3** [cabaletta/baritone#642]
## What do you need help with?
I've successfully built Baritone, but now I need to install it in MultiMC. I can't seem to figure out how to do this.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rel00p** [comment]
Adding `baritone-api-forge-1.2.8.jar` into the Mods folder, or as a Loader mod works fine for me. I'm not sure if that's the intended approach though.

**Comment by chexo3** [comment]
I figured out a way to do this. If you want my multimc json just reply to
this thread.

**Comment by post-calone** [comment]
reply inbound

**Comment by chexo3** [comment]
I'm improving the json some, give me a bit.

**Comment by chexo3** [comment]
Here. You should already know how to use it. If not, try to figure it out yourself first.
[cabaletta.Baritone.zip](https://github.com/cabaletta/baritone/files/3431859/cabaletta.Baritone.zip)
It's just a zipped patch json.

**Comment by GrimReaperFloof** [comment]
1. Go to Version tab
1. Add Empty
Name: Baritone
uid: baritone
1. Select it and click Edit
1. Paste this in
```
{
    "+tweakers": [
        "baritone.launch.BaritoneTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "cabaletta:baritone-api:1.4",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
            "url": "http://dl.liteloader.com/versions/"
        },
        {
            "name": "org.ow2.asm:asm-all:5.0.3",
            "url": "http://repo1.maven.org/maven2/"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "Baritone",
    "releaseTime": "2019-07-23T20:50:21+00:00",
    "requires": [
        {
            "equals": "1.14.4",
            "uid": "net.minecraft"
        }
    ],
    "type": "release",
    "uid": "baritone",
    "version": "1.14.4"
}
```
Have fun!

**Comment by chexo3** [comment]
Yeah, I did basically the same thing earlier.

**Comment by babbaj** [comment]
cringe launcher

**Comment by GrimReaperFloof** [comment]
> cringe launcher

Can you tell me why you think it's a cringe launcher?

**Comment by Gwsteele** [comment]
> Adding `baritone-api-forge-1.2.8.jar` into the Mods folder, or as a Loader mod works fine for me. I'm not sure if that's the intended approach though.

where can I get that file?

**Comment by baconapo** [comment]
I am new to baritone, Minecraft and GitHub. I got excited when I saw this issue so I made this issue where it has the zip file to import into MultiMC. Here is the link: [Baritone-MultiMC-Solution](https://github.com/baconapo/Baritone-In-MultiMC/issues/1)

**Comment by baconapo** [comment]
[Please help me here, I have an issue](https://github.com/baconapo/Baritone-In-MultiMC/issues/2)

**Comment by baconapo** [comment]
> cringe launcher

Ur such a noob, just like me

**Comment by baconapo** [comment]
> > Adding `baritone-api-forge-1.2.8.jar` into the Mods folder, or as a Loader mod works fine for me. I'm not sure if that's the intended approach though.
> 
> where can I get that file?

Here you go, [click here](https://github.com/cabaletta/baritone/releases/download/v1.2.8/baritone-api-forge-1.2.8.jar).

**Comment by baconapo** [comment]
> > cringe launcher
> 
> Ur such a noob, just like me @babbaj

I tried tho, it didn't work

**Comment by baconapo** [comment]
> > Adding `baritone-api-forge-1.2.8.jar` into the Mods folder, or as a Loader mod works fine for me. I'm not sure if that's the intended approach though.
> 
> where can I get that file?

here @Gwsteele [this will show you how to install it](https://github.com/baconapo/Baritone-In-MultiMC).

**Comment by chexo3** [comment]
@leijurv I need your help here, this kid baconapo leaked his .minecraft folder in that repository and credited me for the development of Baritone in the issues for that repository. He took and repackaged my .json patch I made for baritone, and I am concerned and I need you to delete everything he said in this thread if at all possible.

**Comment by leijurv** [comment]
why would i do that / why should i care

**Comment by Jan200101** [comment]
Updated json
```
{
    "+tweakers": [
        "baritone.launch.BaritoneTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "cabaletta:baritone-api:1.5",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
            "url": "http://dl.liteloader.com/versions/"
        },
        {
            "name": "org.ow2.asm:asm-all:5.0.3",
            "url": "https://repo1.maven.org/maven2/"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "Baritone",
    "releaseTime": "2019-07-23T20:50:21+00:00",
    "requires": [
        {
            "equals": "1.15.2",
            "uid": "net.minecraft"
        }
    ],
    "type": "release",
    "uid": "baritone",
    "version": "1.15.2"
}
```

**Comment by pNoName1337** [comment]
can you please update this to Baritone 1.5.2?

> Updated json
> 
> ```
> {
>     "+tweakers": [
>         "baritone.launch.BaritoneTweaker"
>     ],
>     "formatVersion": 1,
>     "libraries": [
>         {
>             "name": "net.minecraft:launchwrapper:1.12"
>         },
>         {
>             "name": "cabaletta:baritone-api:1.5",
>             "url": "https://impactdevelopment.github.io/maven/"
>         },
>         {
>             "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
>             "url": "https://impactdevelopment.github.io/maven/"
>         },
>         {
>             "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
>             "url": "http://dl.liteloader.com/versions/"
>         },
>         {
>             "name": "org.ow2.asm:asm-all:5.0.3",
>             "url": "https://repo1.maven.org/maven2/"
>         }
>     ],
>     "mainClass": "net.minecraft.launchwrapper.Launch",
>     "name": "Baritone",
>     "releaseTime": "2019-07-23T20:50:21+00:00",
>     "requires": [
>         {
>             "equals": "1.15.2",
>             "uid": "net.minecraft"
>         }
>     ],
>     "type": "release",
>     "uid": "baritone",
>     "version": "1.15.2"
> }
> ```

**Comment by dominikaaaa** [comment]
Just change the baritone version... it's like right there...
>             "name": "cabaletta:baritone-api:1.5",

**Comment by pNoName1337** [comment]
i changed to cabaletta:baritone-api:1.5.2 but it doesnt work
> Just change the baritone version... it's like right there...
> 
> > ```
> >         "name": "cabaletta:baritone-api:1.5",
> > ```

**Comment by dominikaaaa** [comment]
that's your fault then, it works otherwise, or that means the maven repo isn't up to date

**Comment by pNoName1337** [comment]
> that's your fault then, it works otherwise, or that means the maven repo isn't up to date

it isnt up to date

**Comment by pNoName1337** [comment]
ahahahhahahaa
so i realized how does it work and just uploaded the baritone-api file on my own website and changed link in json file, now it works properly

**Comment by UltraBlackLinux** [comment]
If someone still needs .json Files: https://github.com/UltraBlackLinux/MultiMC-Patch-Gen

**Comment by ichbestimmtnicht** [comment]
I can't get it running with the newest version. Any ideas?

**Comment by chexo3** [comment]
@leijurv I'm begging you please nuke this garbage fire of a thread. I'm so tired of people even more clueless than me somehow, stumbling onto this thread and spreading sketchy links
