### ISSUE TITLE
Identifying block properties?

### ISSUE THREAD

**Issue by Scarbrine** [cabaletta/baritone#643]
## What do you need help with?
Is it possible to have Baritone recognize certain block data like
#mine oak_log[axis=y] or #mine birch_stairs[shape=straight]

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
In 1.12 `#mine log:0` should work for your example but when I tested it Baritone mined all oak logs
In 1.13+ there is nothing to distinguish blocks that share names
So the answer is a clear no

**Comment by dominikaaaa** [comment]
No, you can't select NBT data with Baritone. Already suggested
