### ISSUE TITLE
Baritone 1.14.4 #BUILD command CRASH

### ISSUE THREAD

**Issue by freelayer** [cabaletta/baritone#648]
Some information
Operating system: windows 10
Java version: 8 
Minecraft version: 1.14.4
Baritone version: 1.14.4

## Exception, error or logs
The game crashed whilst keypressed event handler
Error: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo

## How to reproduce
I created a schematics folder in .minecraft, put there some schematics, used the command #build example and the game crash, please help.

**Comment by 0-x-2-2** [comment]
Build is not supported on 1.13+

**Comment by GrimReaperFloof** [comment]
Will this ever get fixed? I would really want building for 1.13+. I know something changed when it comes to blocks and stuff making older schematics incompatible, but Litematica supports 1.13+
