### ISSUE TITLE
Baritone is unable to make a one block upwards diagonal jump.

### ISSUE THREAD

**Issue by BluSpectrum** [cabaletta/baritone#650]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.14/1.13
Baritone version: 1.14/1.13
Forge mods (if used): None

## Description
Baritone fails to make an upwards diagonal jump with allowPlace off. It can make regular horizontal jumps though. (See picture for more details)
I assume this happens with 1.12 and any other versions available because it seems like a general pathfinding issue.

![image](https://user-images.githubusercontent.com/40967759/61851459-0e946380-ae85-11e9-9cd3-6e892114a2a6.png)

## How to reproduce
1. Reset Baritone settings
2. enable allowParkour, disable allowPlace and allowBreak
3. Use #goto, #click, etc. to set a destination that requires a diagonal upwards jump
4. Baritone will fail to make the jump without placing a block

**Comment by c0nn3r** [comment]
I'll see what I can do @BluSpectrum! 👍

**Comment by 0-x-2-2** [comment]
Fixed with #701 being merged 😎

**Comment by BluSpectrum** [comment]
Thank you. I really appreciate this.
