### ISSUE TITLE
Options for Baritone

### ISSUE THREAD

**Issue by gupah** [cabaletta/baritone#652]
Command or option that makes that, in creative mode takes the necessary blocks to build the schematica, or tells me the blocks that I must take. For survival mode, tell me the necessary blocks for the schematics and its quantity (also showing if I miss any block), also another alternative is that the bot farms the blocks in an automated way (that can craft, smelt, etc...).

**Comment by imdmitry420** [comment]
I think it could be usefull an option to build a schematic ignoring the type of blocks ( only 
differentiate between air/solid/non-solid block) and build the schem that way

**Comment by gupah** [comment]
That can also be useful, instead of doing it with the blocks of the schematics that use different blocks, and that their appearance is different. Thanks imdmitry420, I hope your idea is also part of Baritone.

**Comment by lagx65** [comment]
Yeah I've thought about this and made a very bad solution. I load the schematic in MCEdit then I use the analyse tool to find out every block in the build and export it into a csv file. I then made a shitty micro that takes all the blocks in the list and automatically grabs the block from the search function in the creative inventory and places them into my survival inventory. With allowInventory enabled Baritone can now just grab the needed blocks out of your inventory while building.

**Comment by gupah** [comment]
@lagx65 But when I do #allowInventory, am I supposed to get the blocks automatically? Because when I try it nothing happens. Or is it just to take the blocks you have in your inventory slots?

**Comment by ZacSharp** [comment]
It takes blocks from your survival inventory, not the infinite creative inventory

**Comment by dominikaaaa** [comment]
Already suggested

**Comment by ZacSharp** [comment]
duplicates are #1675, #1781, #1134 and possibly more
