### ISSUE TITLE
how can i install baritone in Aristois1.14.4?

### ISSUE THREAD

**Issue by YiyangWilliam** [cabaletta/baritone#653]

**Comment by MrSmilleer** [comment]
U should wait untill developers of Aristois will fix the problem with integration a new version of Baritone or u can help them. They are trying to make a  program making  baritone work  for farbic.

**Comment by xxskiros** [comment]
#647 Baritone isn't compatible with Fabric which is what Aristois uses.

**Comment by zPeanut** [comment]
baritone is not compatible with fabric.

**Comment by BroSotos** [comment]
The WWE Client is already available on version 1.14.4 with baritones.

1. download the Fabric Installer (Vanilla)
https://fabricmc.net/use/
https://gyazo.com/43c3bc34fbfdcf0fd05eaa4915120161
2. run the installer on client as it is click install
https://gyazo.com/d6e31ba3485dcd4d548f2185a9ae50af
3. download the WWE Client (1.14.4)
https://wweclient.com/Download.php
https://gyazo.com/81d867218c102fe94030a76b9a18d698
4. open the .zip and open the folder wwe 1.14.4, then move the mods folder to your .minecraft 
5. start minecraft with the fabric profile

DONE
