### ISSUE TITLE
Option for Baritone.

### ISSUE THREAD

**Issue by gupah** [cabaletta/baritone#655]
A browser that is connected to a server full of schematics. Useful so that when we want to build a house, you do it from the game, instead of downloading a schematics and get into Minecraft. Something like the scribbl.io cheat (HAL 9000), in which according to the theme of the game, looks in a browser for an image and draws it automatically without downloading anything. Useful for Build Battle.

**Comment by zPeanut** [comment]
please dont write duplicate titles the next time you submit a post. thanks!

**Comment by ishidex2** [comment]
I think it's possible if baritone has some kind of API

**Comment by StijnSimons** [comment]
> I think it's possible if baritone has some kind of API

Has nothing to do with this issue and yes, [it does](https://github.com/cabaletta/baritone/tree/master/src/api/java/baritone/api).

**Comment by gupah** [comment]
I think you can make that option for versions greater than 1.14, as there is Litematica. So they can adapt Baritone for Fabric.

**Comment by RealIndrit** [comment]
They need to remap Baritone to work for Fabric then? Because it doesn't work on fabric atm

**Comment by StijnSimons** [comment]
As @ZeroMemes said; “Fabric would be viable if the mappings were complete and the launcher actually worked.” So i don’t see fabric support soon.

**Comment by ZeroMemes** [comment]
> They need to remap Baritone to work for Fabric then? Because it doesn't work on fabric atm

No.
