### ISSUE TITLE
Question on developing features

### ISSUE THREAD

**Issue by Leterax** [cabaletta/baritone#656]
## What do you need help with?
I have a question on how to go about developing new features for baritone. I assume the normal procedure is accurate:
Create a fork, new branch, pr to branch, pr to this repo.

For example, a feature I'd be interested in implementing is farming mobs. Would I use something like `FarmProcess.java` as a template or would I use the API to implement this?
Are there any other things I should know about contributing?

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Leterax** [comment]
Is there a more "open" communication channel, maybe something like discord?

**Comment by usereewrjrjeejr** [comment]
https://discord.gg/hqW9w5y

**Comment by StijnSimons** [comment]
New fork>add issues to <username/baritone> to either branch and then make pr when finished

**Comment by StijnSimons** [comment]
And squash commits after.

**Comment by Leterax** [comment]
> https://discord.gg/hqW9w5y

thanks! is there an extra channel for barritone dev?

**Comment by StijnSimons** [comment]
Just do it in general. Its usually dead anyways there.

**Comment by Leterax** [comment]
ok! thanks! :)
