### ISSUE TITLE
Ability to Mine by Coord

### ISSUE THREAD

**Issue by GamingInfinite** [cabaletta/baritone#658]
I use this purely to save time getting to a place or to mine something trivial like logs.  When I mine with it I do legit mine.  What I'm getting at is that say I'm playing skyblock and I wan't to use my cobble generator, I wan't to be able to say mine this specific block, over and over again.  I think this would be a great addition to the modification.

**Comment by AliDjango** [comment]
@leijurv now that it is repleaced by sel cleararea how can i only repeatedly mine a specific block like a cobble stone generator?

**Comment by dominikaaaa** [comment]
You would still use sel. I think this can be closed as a solution is in place.

**Comment by AliDjango** [comment]
@dominikaaaa  thanks fo response.i can't seem to make sel work.can you give a example on how to use sel?i cant find examples in #help sel

**Comment by dominikaaaa** [comment]
#click 
#sel replace air 
For more info see https://github.com/cabaletta/baritone/blob/master/USAGE.md
