### ISSUE TITLE
Baritone auto cancel it's path when it meets ice block

### ISSUE THREAD

**Issue by MasterZitron** [cabaletta/baritone#659]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.14.4
Forge mods (if used): none

## Exception, error or logs
No errors are sent in chat

## How to reproduce
I added a goal, and on the path there was ice block, Baritone simply stops when it meets ice.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [  ] I have not used any OwO's or UwU's in this issue.

## Some screenshots
![2019-07-25_17 44 58](https://user-images.githubusercontent.com/32692021/61907586-27902980-af04-11e9-833c-562e8d66b624.png)

![2019-07-25_17 45 05](https://user-images.githubusercontent.com/32692021/61907792-99687300-af04-11e9-9702-f35c7cdb89ec.png)

![2019-07-25_17 45 08](https://user-images.githubusercontent.com/32692021/61907813-a38a7180-af04-11e9-9bfb-c9af4281e5c8.png)

**Comment by MasterZitron** [comment]
forgot to mention: Baritone will use blocks (if you have any) to get to the goal instead.

**Comment by MasterZitron** [comment]
Something else I also just found: Baritone can't find goal if path is around(?) iceblocks.
![2019-07-25_18 03 46](https://user-images.githubusercontent.com/32692021/61908768-d46ba600-af06-11e9-898e-2e692510c88e.png)
![2019-07-25_18 03 56](https://user-images.githubusercontent.com/32692021/61908769-d46ba600-af06-11e9-841f-b303b62733e2.png)
![2019-07-25_18 04 17](https://user-images.githubusercontent.com/32692021/61908770-d46ba600-af06-11e9-83d0-ca80ca3703b3.png)
![2019-07-25_18 04 19](https://user-images.githubusercontent.com/32692021/61908771-d5043c80-af06-11e9-8c38-2e99807d934e.png)
![2019-07-25_18 04 44](https://user-images.githubusercontent.com/32692021/61908793-e77e7600-af06-11e9-9f8d-bddb947cb7c0.png)

**Comment by leijurv** [comment]
I believe this is fixed by https://github.com/cabaletta/baritone/commit/afebdce1f82969a79d029222fc485668be16c094

Reopen if this is not the case (relaunch to get the update)
