### ISSUE TITLE
Error! Unable to start game(1.14.4)

### ISSUE THREAD

**Issue by LennyStrideR** [cabaletta/baritone#662]
## Some information
Operating system: Windows 10 Enterprise LTSC
Java version: version 8 update 211 (build 1.8.0_211-b12)
Minecraft version: 1.14.4
Baritone version: 1.14.4-Baritone

## How to reproduce

1. Open up "Run" (WIN+R)
 2. Type "%APPDATA%"
 3. Press "Ok"
 4. Open the folder ".minecraft"
 5. Drag+Drop this "1.14.4-Baritone" folder into "versions". Do NOT drag+drop just the json file, it must be this entire folder.
 6. Launch Minecraft
 7. Create a new profile using the "1.14.4-Baritone" version
8. Launch the profile

**Comment by Wiktorttt** [comment]
It's easy, first run clear minecraft 1.14.4 because baritone needs to take libraries from minecraft :)

**Comment by LennyStrideR** [comment]
In launcher I have 1.14.4 pre-5 and I played in this version before run baritone

**Comment by Wiktorttt** [comment]
No, use something like Release 1.14.4, not pre.I use tlauncher and have something like this: 
[https://gyazo.com/b8a4e3d5e45d740428d60e31259c3480](url)

**Comment by LennyStrideR** [comment]
Yep, I just need to update launcher and I get release 1.14.4, ty

**Comment by skepep** [comment]
yo do i need to actually launch 1.14.4 (i already launched it many times) but do i need to do it before i put baritone in??
