### ISSUE TITLE
Baritone 1.14.3

### ISSUE THREAD

**Issue by Wiktorttt** [cabaletta/baritone#663]
Is there any way  to go back to 1.14.3? I need exactly 1.14.3..

**Comment by Abduboriy1** [comment]
I need 1.12.2 So I can run Schematica-1.12.2

**Comment by usereewrjrjeejr** [comment]
Only 1.12.2

**Comment by StijnSimons** [comment]
> I need 1.12.2 So I can run Schematica-1.12.2

Has nothing to do with this version



> Is there any way to go back to 1.14.3? I need exactly 1.14.3..

If you would've browsed like 2 seconds in this repo you would've noticed that __there won't be a backport__.
