### ISSUE TITLE
Baritone can't jump while mining

### ISSUE THREAD

**Issue by ishidex2** [cabaletta/baritone#664]
## Some information
Operating system: Linux x86 64bit
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.4.0
Forge mods (if used): no

## Exception, error or logs
No baritone errors found in logs

## How to reproduce
`#mine diamond_ore`
<sub><sup><sub><sup><sup>uwu lol</sup></sup></sub></sup></sub>

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue. 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
banned for uwu

**Comment by StijnSimons** [comment]
Jokes aside you mean jumping as you're breaking a block or just jumping in general?

**Comment by ishidex2** [comment]
jumping in general

**Comment by leijurv** [comment]
Is `assumeStep` on?

**Comment by eza33314** [comment]
assumeStep seems to have fixed it for me
Thanks
