### ISSUE TITLE
Home radius

### ISSUE THREAD

**Issue by metroid112** [cabaletta/baritone#667]
Set a radius around the home goal to make baritone not mine or break any blocks (besides farming).

It's a bit bothersome seeing baritone crush through the walls of my house to go to home goal.

**Comment by GamingInfinite** [comment]
I completely second this.  I am actually trying to optimize a TAS to fully enchanted diamond armor and it is interesting when the bot decides, I'm gonna be a dumb ass.

**Comment by Grovre** [comment]
yessssss

**Comment by l1ving** [comment]
#2597 is more detailed
