### ISSUE TITLE
crashes when you try to build 

### ISSUE THREAD

**Issue by bobross135** [cabaletta/baritone#671]
## Some information
Operating system:
Java version: cant provide because i cant find it
Minecraft version:1.14.4
Baritone version: i think 1.4 if that is right for the 1.14.4 version

just load it up in a server or just single player and then type #build and press enter even if you add a scematic anme it does it 
[2019-07-26-6.log.gz](https://github.com/cabaletta/baritone/files/3437847/2019-07-26-6.log.gz)

**Comment by plootia** [comment]
#build only supports 1.12.
