### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by h-e-l-l-o-s** [cabaletta/baritone#676]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.3.4
Forge mods (if used): Impact

## How to reproduce
.b build {build}
the build has block you have to place on trapdoors. It gets caught in a endless loop

## Final checklist
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Maybe actually give this a title. If not title is set within one hour, i will close this

**Comment by Cerbiac** [comment]
Simons didn't uphold his bargain. Guess I'll do it.

**Comment by StijnSimons** [comment]
Im a man of my word
