### ISSUE TITLE
When someone in vanish is around, automatically start strip mining to avoid detection.

### ISSUE THREAD

**Issue by Grovre** [cabaletta/baritone#678]
## Describe your suggestion
When an admin starts watching you to see if you're xraying or automining, it should automatically start strip mining to avoid being banned by an admin.

Pretty self explanatory on how it can improve Baritone, but it'll be easier to avoid a ban if it automatically starts strip mining like a normal person.

**Comment by ZeroMemes** [comment]
It’s not possible to know whether or not somebody in vanish is in close proximity, it’s only possible to know the fact that they are vanished.
