### ISSUE TITLE
Make fightbot

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#680]
## Describe your suggestion
Worst client has fightbot and so does jigsaw but those bots are really primitive and easly detectable it is neccecery to add rotation speed,  cps changes and target options also if it is possible add chack for pvp protection

## Settings
Head rotation speed slider
Cps slider
Targets options
## Context
This can be useful for kitpvp or 2b2t's fights

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by enescaglayan** [comment]
Impact has this thingy, download it at combat section click hunt 
dont forget to open kill aura and aimbot with it because hunt only goes to mobs you want(player passive mob hostile mob etc.)
