### ISSUE TITLE
Baritone's bridging method is not as fast as it could be

### ISSUE THREAD

**Issue by HudayDotObject** [cabaletta/baritone#681]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
?????????

**Comment by HudayDotObject** [comment]
I clicked something that deleted the description but I didn't realize it before I hit confirm, I remade the issue after.
