### ISSUE TITLE
Baritone's bridging method is not as fast as it could be

### ISSUE THREAD

**Issue by HudayDotObject** [cabaletta/baritone#682]
## Describe your suggestion
Ninja bridging is not the fastest form of bridging. There are much faster bridging methods like breezily-bridging, god bridging, derp bridging, or even andromeda bridging.

## Settings
You should be able to switch between different bridging techniques.

## Context
Baritone would be able to path-find much faster over large chasms or lava.

## Final checklist
- [Indeed] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
#681

**Comment by HudayDotObject** [comment]
> #681

Not sure what you mean by "??????" the bridging method is not very fast, it uses the technique ninja bridging and there are faster techniques like breezily-bridging, god bridging, derp bridging, or even andromeda bridging.

**Comment by 0-x-2-2** [comment]
These bridging methods are not consistent.

**Comment by cyleja1234** [comment]
so these other types of brides wont be added because?

**Comment by dominikaaaa** [comment]
try reading 1 comment higher

**Comment by StijnSimons** [comment]
📸

**Comment by RealIndrit** [comment]
CRINGE ISSUE
