### ISSUE TITLE
More blocks to mine with Auto Mine

### ISSUE THREAD

**Issue by Ondicknek** [cabaletta/baritone#684]
I think that Auto mine is awesome, but I also think that it would be better if you can choose any block in Minecraft to mine. Probably the best way to get this feature in Impact would be to put it in ESC/Impact/Auto Mine/ where you would have a list of blocks that you can choose to mine and then add other blocks to a list.

**Comment by GrimReaperFloof** [comment]
Can't you just type `#mine <block> [block2] ...`?

**Comment by leijurv** [comment]
Yes. You can just do `#mine iron_ore diamond_ore`

**Comment by ONION-nii** [comment]
uhh....how do I mine modded ores?

**Comment by positiivne** [comment]
#mine <mod_name>:<ore_name>

**Comment by gutoguto08** [comment]
> #mine <mod_name>:<ore_name>

Doesn't work for me atm...

**Comment by rlelchev** [comment]
How can i mine sugar cane?

**Comment by l1ving** [comment]
https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening#Block_IDs
