### ISSUE TITLE
Launcher crashes on start

### ISSUE THREAD

**Issue by JVHeerden** [cabaletta/baritone#685]
## Some information
**Operating system**:
Linux Mint 19.1 Tessa x86_64 

**Java version**:
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Minecraft version**:
1.14.4

**Minecraft Launcher Version**:
2.1.5965

**Baritone version**:
1.14.4-Baritone

**Forge mods (if used)**: 
None

## Exception, error or logs
I copied the folder of the 1.14.4-Baritone.zip file into my ~/.minecraft/versions folder.
After creating the profile with the the Baritone version and clicking 'Play' the launcher immediately crashes.

The launcher itself appears to be crashing. No logs are found int he logs/latest file.
However the launcher_log.txt has the following exception:

`Info: 2019-07-28 19:30:07.805912258: GameCallbacks.cpp(138)] Launcher/launcher (main) Info Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

No other errors could be found in any of the logs

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Baritone only supports java 8.
