### ISSUE TITLE
Blocks to avoid breaking doesn't work?

### ISSUE THREAD

**Issue by Kihz17** [cabaletta/baritone#687]
Even though I specify blocks that I don't want baritone to break it still tries to break those blocks when it's pathing to ore.

**Comment by DiamondLink** [comment]
Why does this have the dumb label ? I have the same issue.

**Comment by dominikaaaa** [comment]
Because you're doing it wrong. And it clearly has avoid in the name.

**Comment by EnderInvader** [comment]
> Because you're doing it wrong. And it clearly has avoid in the name.

How is this doing it wrong?
