### ISSUE TITLE
Can I use it with Xray in 1.14.4?

### ISSUE THREAD

**Issue by luvletter2333** [cabaletta/baritone#692]
I think if I can have a xray with baritone,it's better for me to use the auto-mine. Because Xray can be used to toggle fullbright and open xray.

I combine Xray into the launcher json, But it doesn't work.
```
 {
  "id": "1.14.4-Baritone",
  "type": "release",
  "inheritsFrom": "1.14.4",
  "jar": "1.14.4",
  "time": "2019-07-23T20:50:21Z",
  "releaseTime": "2019-07-23T20:50:21Z",
  "downloads": {},
  "minimumLauncherVersion": 0,
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
     "--tweakClass",
     "baritone.launch.BaritoneTweaker",
   **"net.minecraftxray.loader.XRayTweaker"**
    ]
  },
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
      "name": "cabaletta:baritone-api:1.4",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "http://repo1.maven.org/maven2/"
    },
   **{
      "name": "net.minecraftxray:xray:67-1144"
    },
    {
      "name": "net.minecraftxray:launchwrapperdlb:2.1"
    }**
  ]
}
```

It comes from the launcher json made by Xray Installer
```
{
  "id": "1.14.4-XRay",
  "time": "2019-07-25T19:20:50+08:00",
  "releaseTime": "2019-07-20T04:06:00+08:00",
  "type": "release",
  "arguments": {
    "game": [
      "--tweakClass",
      "net.minecraftxray.loader.XRayTweaker"
    ]
  },
  "libraries": [
    {
      "name": "net.minecraftxray:xray:67-1144"
    },
    {
      "name": "net.minecraftxray:launchwrapperdlb:2.1"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": 21,
  "jar": "1.14.4",
  "inheritsFrom": "1.14.4"
}
```

this log comes from Vanilla Launcher(Fliter:xray)

> 11:50:15.509
> launcher
> main
> Preparing xray-67-1144.jar
> 
> 11:50:15.509
> launcher
> main
> Don't have expected size for xray-67-1144.jar
> 
> 11:50:16.845
> launcher
> main
> Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/net/minecraftxray/launchwrapperdlb/2.1/launchwrapperdlb-2.1.jar
> 
> 11:50:16.847
> launcher
> main
> Local file C:\Users\10268\AppData\Roaming\.minecraft\libraries\net\minecraftxray\launchwrapperdlb\2.1\launchwrapperdlb-2.1.jar has filesize of 15637 bytes
> 
> 11:50:16.847
> launcher
> main
> Have local file C:\Users\10268\AppData\Roaming\.minecraft\libraries\net\minecraftxray\launchwrapperdlb\2.1\launchwrapperdlb-2.1.jar but don't know what size or hash it should be. Have to assume it's good.
> 
> 11:50:16.938
> launcher
> main
> Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/net/minecraftxray/xray/67-1144/xray-67-1144.jar
> 
> 11:50:16.938
> launcher
> main
> Got local file for xray-67-1144.jar
> 
> 11:50:16.938
> launcher
> main
> Local file C:\Users\10268\AppData\Roaming\.minecraft\libraries\net\minecraftxray\xray\67-1144\xray-67-1144.jar has filesize of 276974 bytes
> 
> 11:50:16.938
> launcher
> main
> Have local file C:\Users\10268\AppData\Roaming\.minecraft\libraries\net\minecraftxray\xray\67-1144\xray-67-1144.jar but don't know what size

It seems that Xray has been loaded, but there isn't the page for xray in `Settings->Control`.

**Comment by usereewrjrjeejr** [comment]
Baritone is a fancy x-ray mod that walks

**Comment by luvletter2333** [comment]
but what's about the FullBright and Fly with speed control?
