### ISSUE TITLE
Bot gets stuck when falling into water

### ISSUE THREAD

**Issue by nbyrd** [cabaletta/baritone#697]
## Some information
Operating system: Windows 10
Java version: 1.8.0_51 64-bit
Minecraft version: 1.14.4
Baritone version: 1.4.0

## How to reproduce
Have baritone path around the world (`#explore`, `#mine`, `#goto`, etc). If the bot falls into water (not water-bucket, but e.g. the ocean), it gets stuck and is never able to escape on its own, instead choosing to float indefinitely.

It should time out and re-calculate path when this happens.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Grovre** [comment]
when this happens to me it doesn't find a new path

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0-x-2-2** [comment]
Do you have allowedWalkOnWater enabled without Jesus 🤔

**Comment by realflow100** [comment]
I have this problem too without impact. so no cheats. that command is invalid for me.

**Comment by nbyrd** [comment]
@0-x-2-2 allowedWalkOnWater is explicitly set to `false`, so nope.

As @Grovre says, the bot fails to find a new path, and as @realflow100 says, this happens when falling from at least a couple blocks up. I guess the best way to reproduce this is to find an ocean biome with icebergs, stand on one, and try to path somewhere. Chances are, it'll get stuck.

**Comment by 0-x-2-2** [comment]
Can you enable `chatDebug`?

**Comment by nbyrd** [comment]
@0-x-2-2 I enabled chatDebug and reproduced the issue. Image of chat output is below.

Additional steps to reproduce:

1. Create a world with seed `845384498`.
2. Go to coordinates X=-33, Y=68, Z=-67. (This should be atop a small ice berg.)
3. `#goal 1000 0` and `#path` to start things moving.

At this point, you will observe that the bot navigates into water and immediately gets stuck. (If it doesn't happen, give it a few tries, but it happened 100% of the time when I tested.) Notice how the bot makes no attempts to rectify the situation. Occasionally, this can be fixed by manually placing blocks under the bot's feet or breaking nearby blocks, but it's not guaranteed.

![image](https://user-images.githubusercontent.com/3514350/62416362-36569a80-b5ee-11e9-8186-df773387f30c.png)

**Comment by rafelc** [comment]
Try "blocksToAvoid water".
I had the same problem and it solved the issue to me. I think.

**Comment by jonnyawsom3** [comment]
I feel like this may be 2 issues mixing into one, 
i know that when i wanted to test baritone i went onto 9b9t (because screw queuing for hours) after loading in its all water around spawn with some blocks mixed in, i ask baritone to move and it says it couldn't move more than 1 block at a coefficient of 10 (or something like that), so water may be a bit glitchy
In another instance while using the build command, i noticed that baritone could often fall into either a loop of placing and breaking blocks or, more relevant to this, it would freeze and stop all actions until i broke and placed blocks around and/or under it, until it started pathing again

**Comment by dominikaaaa** [comment]
Please reopen this if you're still experiencing this issue, I can't reproduce it.

**Comment by snoopchallenge** [comment]
This still happens when pathing long distances and dropping into water

**Comment by snoopchallenge** [comment]
or even pathing short distances

**Comment by snoopchallenge** [comment]
temporary solution for me is just to pause and move so you arent in the centre of a block then resume

**Comment by maplepy** [comment]
I still have the bug so maybe reopen it?

**Comment by maplepy** [comment]
![image](https://user-images.githubusercontent.com/28269333/168335525-8f436018-13a5-407b-8631-2cc9df63dbe6.png)

No log with chatDebug

**Comment by Minecraftian974** [comment]
This happens to me to.

**Comment by maplepy** [comment]
Yeah but it has to dig a path under water which is not very fast nor effective

**Comment by maplepy** [comment]
I guess it'll never be reopened because @5HT2 can't reproduce it so it must not exist

**Comment by wagyourtail** [comment]
See #3200
