### ISSUE TITLE
Not Jumping

### ISSUE THREAD

**Issue by lJlmmyl** [cabaletta/baritone#700]
## Some information
Operating system:Windows10
Java version:8
Minecraft version:1.14.4
idk what version it is it just says barritone 1.14.4
## How to reproduce
Just using any go to or mine command where baritone needs to jump up 1 block 

## Final checklist
- [ o] I have included the version of Minecraft I'm running, baritone's version and forge mods
- [ w] I have included logs, exceptions and / or steps to reproduce the issue.
- [ o] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Do you have assumeStep enabled 🤔

**Comment by lJlmmyl** [comment]
yeah

**Comment by leijurv** [comment]
turn it off this is literally what it does

**Comment by ResistVR** [comment]
i have it off and it wont let me jump still
