### ISSUE TITLE
Log location of block or structure when using #goto.

### ISSUE THREAD

**Issue by LinoBigatti** [cabaletta/baritone#703]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
Log in chat the location of a block when using #goto. Something like:
```
#goto shulker_box
[baritone] Going to shulker box at location [x] [y] [z]
```

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
It would make it possible to use the nether to go faster to a location in the overworld that is very far away, without needing to know the location of the block or location itself.

## Final checklist
- [yes] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
This information can be retrieved by either enabling `chatDebug` or running the `proc` command while it is on its way.
