### ISSUE TITLE
#goto <block> does not work with #allowBreak set to false

### ISSUE THREAD

**Issue by jhmaster2000** [cabaletta/baritone#704]
## Some information
Operating system: Windows 10 Pro
Java version: 8
Minecraft version: 1.12.2
Baritone version: github build
Forge mods (if used): None

## Exception, error or logs
No errors were printed.

## How to reproduce
Place a regular chest and walk 10+ blocks away from it, make sure the path is possible to be made without breaking any blocks (Do it in a superflat world?)
Run #allowBreak false
Run #goto chest (It will say no known locations)

To fix the issue you run #allowBreak true and then #goto chest will work again

## Final checklist
- [ X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ X ] I have not used any OwO's or UwU's in this issue.

**Comment by mrphax0r** [comment]
Were you in the same chunk as the chest?

**Comment by olibols** [comment]
Well are there any chests that you can physically get to without having to break blocks? Works just fine for me

**Comment by s5bug** [comment]
I can reproduce this with Baritone Fabric 1.6.3 on Minecraft 1.16.5. Java version 16.

**Comment by ZacSharp** [comment]
This is actually already fixed in 43d5458a25f5f570e556cd1668b7f0d84c58d697, which is in the latest release for 1.12.2 ([v1.2.15](https://github.com/cabaletta/baritone/tree/v1.2.15) as of this writing) but not yet ported to newer Minecraft versions.
