### ISSUE TITLE
Wierd pos1 and pos2 glitchPlease add a brief but descriptive title

### ISSUE THREAD

**Issue by rusty0l** [cabaletta/baritone#705]
## Some information
Operating system: windows 10
Java version: 1.12.2 and 1.13.2
Minecraft version: 1.12.2 and 1.13.2
Baritone version: 1.7.2
Forge mods (if used): none

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

The bug is that when i right or left click, it says pos1 or pos2 and i cant turn it off. it also creates a weird translucent box in the positions. How do i turn it off?

**Comment by ZeroMemes** [comment]
You have the build module on in Impact.
