### ISSUE TITLE
(Suggestion) Wild card '*ore' tag

### ISSUE THREAD

**Issue by KoiV1224** [cabaletta/baritone#709]
Would help by not having to type '#mine iron_ore gold_ore emerald_ore' or another long string of names, would also help with mods with many different ores. For example.

#mine *ore   = Mines anything that ends in 'ore'.
#mine *ore* = Mines anything that has 'ore' anywhere in it.
#mine ore*   = Mines anything that starts in 'ore'

**Comment by clragon** [comment]
@txm-rxley you might want to escape your \* wildcards with \\ since guthub uses markdown and it just makes your text italic.

**Comment by scorbett123** [comment]
I think that the idea suggested in #3047 is more versatile than this and would implement the same functionality, so I'm going to close this issue.
