### ISSUE TITLE
Cache chunk's surface block types

### ISSUE THREAD

**Issue by HowardStark** [cabaletta/baritone#71]
Store the type of the blocks at the surface of the chunk within the chunk cache format, to support more accurate pathing into the future, and to allow for on-demand mapping far easier. 

> I'm not sure if that integration should be just storing the PNGs in the same folder, or maybe shoving them into the same file as the 2-bit representation. 
>
> Interestingly enough, what if chunk caching stored the block types of the very top layer, which is 16x16=256 blocks. You get the heightmap from the 2-bit shape. So no need to store all the PNGs at all.
> In fact, storing the blocktypes of the very top block in each column would be great for more accurate pathing huh. 

Source: https://github.com/cabaletta/baritone/pull/66#issuecomment-414762975

**Comment by leijurv** [comment]
Addressed in commit https://github.com/cabaletta/baritone/commit/e6eac166d9f659dda59778e9f6ed8d7e3a1f99ec
