### ISSUE TITLE
(Suggestion) two new commends ! 

### ISSUE THREAD

**Issue by Spangonagornomb** [cabaletta/baritone#710]
Hey I believe that a commend like 

#sethome <homename>
and 
#home <home target>

sometimes its too annoying to type the home cords when I go about fucking 4000 blocks away from my house lol

**Comment by Fefect** [comment]
This is already available:
https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/utils/ExampleBaritoneControl.java#L653

**Comment by Spangonagornomb** [comment]
> This is already available:
> https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/utils/ExampleBaritoneControl.java#L653

FFFFFFFFFFFFFF 

WWWWWWWWWWWW 

THANKS !

**Comment by Spangonagornomb** [comment]
FFFFFFFFF I AM SO FUCKING HAPPY OH MY A FUCKING JEWISH GOD (because I am a kike l;ol)

**Comment by Spangonagornomb** [comment]
Wait for my suggestion maybe add a sethome with an argument ? 
so you can have few homes ?

**Comment by Fefect** [comment]
Would something like this be useful for you?
https://dl.dropboxusercontent.com/s/eiuaon1unl2y8r4/2019-08-02_16-34-34.mp4
I can make the pull request for it (so it can potentially be implemented)

**Comment by Fefect** [comment]
I noticed that the .save and .goto command supply these features.
b a k a

**Comment by StijnSimons** [comment]
`#save faggot`
`#goto faggot`
