### ISSUE TITLE
followentity dosent work, it says entity not found or not available

### ISSUE THREAD

**Issue by Ming-A** [cabaletta/baritone#726]
## Some information
Operating system: Windows 10
Java version: version 8 update 211
Minecraft version: 1.14.4
Baritone version: 1.14.4

## How to reproduce
I have typed '#followentity pig' and other animals but then it says its unavailable or not found.

**Comment by realflow100** [comment]
spawn some and make sure they are within render distance?

**Comment by Kioyo** [comment]
Also make sure you're using their entity name, minecraft:pig is what you're looking for.

**Comment by 0-x-2-2** [comment]
inactive.
