### ISSUE TITLE
Constrain mining to a specific set of coordinates

### ISSUE THREAD

**Issue by Breadpan** [cabaletta/baritone#729]
## Describe your suggestion
Only allow automining within a set of XYZ coordinates.

## Settings
Probably a setting to add 2 each of XYZ coords, so if I set it to (0,5 60,50 10,20), it can only mine from X: 0 to 5, Y: 60 to 50, Z: 10 to 20. Alternatively, it could set the first anchor point to the player's current location, which a setting like (5,-10,10) would achieve the same result if I was standing on 0, 60, 10.

## Context
Mostly for server based issues like factions, prison, etc. But personally, it would be useful for chunk clearing, flattening and building.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Fefect** [comment]
The cleararea command allows you to clear out an area given by the goal you set and the players location, clearing out a cube-like area. This can be used to clear out chunks or flatten land.

**Comment by StijnSimons** [comment]
This is about the 4th issue asking this feature. Keep it to just one.

**Comment by StijnSimons** [comment]
Or use cleararea like Fefect said.
