### ISSUE TITLE
CachedWorld.REGION_MAX appears to be twice what it should be?

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#73]
The comment says `The maximum number of regions in any direction from (0,0)` and the check is `regionX <= REGION_MAX && regionX >= -REGION_MAX && regionZ <= REGION_MAX && regionZ >= -REGION_MAX;`.

You can go 30,000,000 out from 0,0. Therefore the value should be 30000000/16/32 which is 58594. However, the current value is double that, 117188.

**Comment by ZeroMemes** [comment]
This was from when regions were going to be 16x16 to make everything line up.
