### ISSUE TITLE
Mixin config mixins.baritone.json does not specify "minVersion" property

### ISSUE THREAD

**Issue by GeetHaab** [cabaletta/baritone#730]
## Some information
Operating system: win 10
Java version: 8u211
Minecraft version: 1.12.2
Baritone version: 1.2.8/7

## Exception, error or logs
https://pastebin.com/NbVUPqrd
Mixin config mixins.baritone.json does not specify "minVersion" property

## How to reproduce
put baritone into mod folder

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
This isn’t urgent at all. Minversion is not required to run.

**Comment by GeetHaab** [comment]
It doesn't let me run baritone in forge.

**Comment by StijnSimons** [comment]
(Might be wrong here) but i think you could try adding the tweakclass.

**Comment by GeetHaab** [comment]
How do i do that? I've never touched java in my life.

**Comment by leijurv** [comment]
This is not a bug, or an error. It's just a warning. This is printed every time, and doesn't prevent baritone from loading. Did you actually try running some of its commands?
