### ISSUE TITLE
Build schematic 1.14?

### ISSUE THREAD

**Issue by OttoGame** [cabaletta/baritone#731]
Hey i wonder if you are planning on updating the build feeature to 1.14.4? Its like the 3rd best command for baritone, but its pretty sad that its patched :)

**Comment by Kioyo** [comment]
They're some other threats that have asked this. It'd have to be litematica cause schematica isn't 1.14.4

**Comment by StijnSimons** [comment]
Its not patched. There’s just no standard for 1.13+ ids.
