### ISSUE TITLE
Throwable items not being dropped?

### ISSUE THREAD

**Issue by wickedlizerd** [cabaletta/baritone#732]
I'm having an issue, where when my inventory is full, baritone won't drop items I have marked as throwable. I'm using Minecraft 1.13.2 and wondering if this is something I'm doing wrong?

Example, inventory is full of cobblestone, iron, diamonds and redstone, cobblestone is marked as throwable but won't get rid of it.

**Comment by realflow100** [comment]
i dont believe this is a feature yet. throwaway items are only used by baritone to "place" down to do parkour and walk on or pillar or build with. not throw with the Q button to dump them as item drops.

**Comment by wickedlizerd** [comment]
Ahh, I see. Should be a feature then, would be helpful for when you wanted to leave it AFK for long periods of time.

**Comment by StijnSimons** [comment]
You should use [Impact](https://github.com/ImpactDevelopment/ImpactClient) for auto-ejecting.
