### ISSUE TITLE
Bot refuses to mine Glowstone with pickaxe

### ISSUE THREAD

**Issue by nbyrd** [cabaletta/baritone#733]
## Some information
Operating system: Windows 10 (64-bit)
Java version: 1.8.0_51
Minecraft version: 1.14.4
Baritone version: 1.4.0
Forge mods (if used): None

## How to reproduce
Go to the nether and instruct Baritone to mine Glowstone. Make sure you have a pickaxe.

When the bot gets to the glowstone, it will insist on mining the blocks with any tool EXCEPT for the pickaxe, which is not optimal.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by usereewrjrjeejr** [comment]
FIX

**Comment by S-B99** [comment]
Fix what. Don't be a dumbass and look at literally anything first. https://minecraft.gamepedia.com/Glowstone

A pickaxe won't make it mine faster, therefor using a pick is wasting durability.

**Comment by ZeroMemes** [comment]
Given that Baritone will account for enchantments, I'm closing this.

**Comment by ZeroMemes** [comment]
Honestly I should've closed this the second I saw it because *Baritone will literally use THE best item to mine any block*
