### ISSUE TITLE
#mine diorite... Invalid block name

### ISSUE THREAD

**Issue by Astradar** [cabaletta/baritone#734]
Operating system: windows 10
Minecraft version: 1.12.2
Baritone version: last

Hi ! I'm on a server pvp and they use plug-in to change "diorite" to "sapphire" but when I use #mine Diorite_ore baritone : isn't a valid block name
And they changed Emerald by block "exp" and when I write #mine emerald_ore that's work..

Do you know why ? Help Ty

**Comment by StijnSimons** [comment]
no

**Comment by EmeraldSnorlax** [comment]
why does baritone and impact always attract such autists

**Comment by StijnSimons** [comment]
there was a fair attempt tho
