### ISSUE TITLE
Baritone not recognising wood logs in multiplayer

### ISSUE THREAD

**Issue by DanCuber** [cabaletta/baritone#738]
## Some information
Operating system: win10 64bit
Java version: latest as if 5/8/2019
Minecraft version: 1.13.2
Baritone version: latest as of 5/8/2019

## How to reproduce
Set up a vanilla 1.13.2 server (not lan world, haven't tried this on there)

Type #mine log or #mine logs

Error message: logs/log isn't a valid block name

##suggestion: make it so baritone can also work using numerical block ids and you can tab complete when looking at a block to mine that block type

**Comment by maraxin** [comment]
in minecraft 1.13.2 block name's has been changed like logs now oak_log and other types of log.

**Comment by KleinBagel** [comment]
however again oak logs log in 1.14.4 are not recognized

**Comment by leijurv** [comment]
just look up the block names on the wiki

i'm not going to hold your hand through it

here's a hint: in 1.14.4 it's oak_log not oak_logs
