### ISSUE TITLE
When in ESC or chat, movement works, but breaking and placing blocks doesn't

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#74]
Baritone gets completely stuck when allowBreak is on, its next movement wants to break, but I have chat open, or I'm on the ESC menu with another application open.

- [x] Placing Blocks
- [x] Breaking Blocks

**Comment by ZeroMemes** [comment]
Fixed placing blocks in a407fa6

**Comment by ZeroMemes** [comment]
Updated original post to include a checklist
