### ISSUE TITLE
Baritone ignores blockstoAvoidBreaking setting

### ISSUE THREAD

**Issue by Breadpan** [cabaletta/baritone#742]
## Some information
Operating system: Win10 64-bit
Java version: Version 8 Update 201
Minecraft version: 1.13.2
Baritone version: Impact 4.7.2
Forge mods (if used): 

## Exception, error or logs
Baritone still breaks the blocks defined in the blockstoAvoidBreaking setting. For this instance, the offending blocks were Glowstone and a few different shades of terracotta (and yes I'm sure I've gotten the correct IDs for the colors).

## How to reproduce
Start AutoMining, or clearArea. Sometimes Baritone will still break blocks that are defined in the setting. In my case, I am running this in a server and added to the setting the blocks that are server protected. Since Baritone ignores the setting, it gets stuck in a loop of trying to break the block and the server protecting it (hence an instantaneous restoration of the block), with no path recalculation.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
It doesn't ignore the setting, it just isn't strict. If the only way to achive the goal that you give it is to mine one of those blocks, it will.

Under the hood it's just 10xing the calculated cost of how long it would take to mine, so it makes it consider alternatives much more often, like going far out of its way.
