### ISSUE TITLE
Baritone's parkour feature not working

### ISSUE THREAD

**Issue by CVFireDragon** [cabaletta/baritone#744]
So I tried out the parkour feature and I found that it didn't work for some reason? I made only a 1 block jump.

I did these commands:
(hashtag) allowParkour true
(hashtag) allowPlace false (I think it was this)

But it still doesn't work. I haven't done any others so is that a problem?
Demo: https://youtu.be/ZvT45p9ZP_0

**Comment by VirxEC** [comment]
That's because Baritone's parkour feature is still in beta. It does work, but only %10 of the time.

**Comment by leijurv** [comment]
no...

parkour ascend was only recently added, it is not yet in any release. you can wait for the next release, or you can build baritone yourself from current source code. https://github.com/cabaletta/baritone/blob/master/SETUP.md

i assure you, parkour ascend does work, see https://www.youtube.com/watch?v=9Fb5tdsIIJc
