### ISSUE TITLE
How to install on Mac

### ISSUE THREAD

**Issue by ButterCreep** [cabaletta/baritone#745]
Hello, while i was attempting to install Baritone on my Mac laptop i found that after following all of the steps in the Readme file i was not able to create a new version with Baritone on my minecraft launcher. Is it that it doesn't work for mac or did i miss something? please help.

**Comment by StijnSimons** [comment]
lol what are you trying to even do? Build baritone???

**Comment by ButterCreep** [comment]
Im just trying to actually be able to use 1.14.4 baritone

**Comment by ButterCreep** [comment]
"7. Create a new profile using the "1.14.4-Baritone" version (it will not create one for you sadly)" this is the part that i am stuck on.

**Comment by StijnSimons** [comment]
Dude just follow
