### ISSUE TITLE
Is there a way to have baritone and optifine in 1.14.4?

### ISSUE THREAD

**Issue by Ming-A** [cabaletta/baritone#746]
Is there a way to have baritone and optifine in 1.14.4?

**Comment by realflow100** [comment]
dont think so yet. sorry.

**Comment by PhaserArray** [comment]
Yes, there is. I made it work by combining the version files of optifine and baritone. I am not sure whether you also have to copy the optifine jar into the same version folder, but I did just in case. Here's the version config that works for me:

```json
{
  "id": "1.14.4-Baritone-w-Optifine",
  "inheritsFrom": "1.14.4",
  "time": "2019-08-02T21:51:45+03:00",
  "releaseTime": "2019-08-02T21:51:45+03:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.14.4_HD_U_F2"
    },
    {
      "name": "optifine:launchwrapper-of:2.1"
    },
    {
      "name": "cabaletta:baritone-api:1.4",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "http://repo1.maven.org/maven2/"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker",
      "--tweakClass",
      "baritone.launch.BaritoneTweaker"
    ]
  }
}
```

The only issue I've noticed is that some shaders mess up the lines and boxes baritone draws.

**Comment by SebbyLaw** [comment]
> The only issue I've noticed is that some shaders mess up the lines and boxes baritone draws.

Yeah this is an issue for all client mods with shaders, not just baritone.

**Comment by TronaxYT** [comment]
It works fine. THANKS

**Comment by Ming-A** [comment]
> Yes, there is. I made it work by combining the version files of optifine and baritone. Install optifine first, then create another version folder named `1.14.4-Baritone-w-Optifine` and save this config in it as `1.14.4-Baritone-w-Optifine.json`:
> 
> ```json
> {
>   "id": "1.14.4-Baritone-w-Optifine",
>   "inheritsFrom": "1.14.4",
>   "time": "2019-08-02T21:51:45+03:00",
>   "releaseTime": "2019-08-02T21:51:45+03:00",
>   "type": "release",
>   "libraries": [
>     {
>       "name": "optifine:OptiFine:1.14.4_HD_U_F2"
>     },
>     {
>       "name": "optifine:launchwrapper-of:2.1"
>     },
>     {
>       "name": "cabaletta:baritone-api:1.4",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
>       "url": "http://dl.liteloader.com/versions/"
>     },
>     {
>       "name": "org.ow2.asm:asm-all:5.0.3",
>       "url": "http://repo1.maven.org/maven2/"
>     }
>   ],
>   "mainClass": "net.minecraft.launchwrapper.Launch",
>   "minimumLauncherVersion": "21",
>   "arguments": {
>     "game": [
>       "--tweakClass",
>       "optifine.OptiFineTweaker",
>       "--tweakClass",
>       "baritone.launch.BaritoneTweaker"
>     ]
>   }
> }
> ```
> 
> The only issue I've noticed is that some shaders mess up the lines and boxes baritone draws.

i'll give this a try, thanks for the reply :)

**Comment by Ming-A** [comment]
> Yes, there is. I made it work by combining the version files of optifine and baritone. Install optifine first, then create another version folder named `1.14.4-Baritone-w-Optifine` and save this config in it as `1.14.4-Baritone-w-Optifine.json`:
> 
> ```json
> {
>   "id": "1.14.4-Baritone-w-Optifine",
>   "inheritsFrom": "1.14.4",
>   "time": "2019-08-02T21:51:45+03:00",
>   "releaseTime": "2019-08-02T21:51:45+03:00",
>   "type": "release",
>   "libraries": [
>     {
>       "name": "optifine:OptiFine:1.14.4_HD_U_F2"
>     },
>     {
>       "name": "optifine:launchwrapper-of:2.1"
>     },
>     {
>       "name": "cabaletta:baritone-api:1.4",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
>       "url": "http://dl.liteloader.com/versions/"
>     },
>     {
>       "name": "org.ow2.asm:asm-all:5.0.3",
>       "url": "http://repo1.maven.org/maven2/"
>     }
>   ],
>   "mainClass": "net.minecraft.launchwrapper.Launch",
>   "minimumLauncherVersion": "21",
>   "arguments": {
>     "game": [
>       "--tweakClass",
>       "optifine.OptiFineTweaker",
>       "--tweakClass",
>       "baritone.launch.BaritoneTweaker"
>     ]
>   }
> }
> ```
> 
> The only issue I've noticed is that some shaders mess up the lines and boxes baritone draws.

It works for me, thanks :)

**Comment by LySoon** [comment]
Thanks for the Sharing ❤️

**Comment by gibbothythicc** [comment]
> Yes, there is. I made it work by combining the version files of optifine and baritone. Install optifine first, then create another version folder named `1.14.4-Baritone-w-Optifine` and save this config in it as `1.14.4-Baritone-w-Optifine.json`:
> 
> ```json
> {
>   "id": "1.14.4-Baritone-w-Optifine",
>   "inheritsFrom": "1.14.4",
>   "time": "2019-08-02T21:51:45+03:00",
>   "releaseTime": "2019-08-02T21:51:45+03:00",
>   "type": "release",
>   "libraries": [
>     {
>       "name": "optifine:OptiFine:1.14.4_HD_U_F2"
>     },
>     {
>       "name": "optifine:launchwrapper-of:2.1"
>     },
>     {
>       "name": "cabaletta:baritone-api:1.4",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
>       "url": "https://impactdevelopment.github.io/maven/"
>     },
>     {
>       "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
>       "url": "http://dl.liteloader.com/versions/"
>     },
>     {
>       "name": "org.ow2.asm:asm-all:5.0.3",
>       "url": "http://repo1.maven.org/maven2/"
>     }
>   ],
>   "mainClass": "net.minecraft.launchwrapper.Launch",
>   "minimumLauncherVersion": "21",
>   "arguments": {
>     "game": [
>       "--tweakClass",
>       "optifine.OptiFineTweaker",
>       "--tweakClass",
>       "baritone.launch.BaritoneTweaker"
>     ]
>   }
> }
> ```
> 
> The only issue I've noticed is that some shaders mess up the lines and boxes baritone draws.

I get this error 

Failed to download file.
Name: OptiFine-1.14.4_HD_U_F2.jar
URL: https://libraries.minecraft.net/optifine/OptiFine/1.14.4_HD_U_F2/OptiFine-1.14.4_HD_U_F2.jar
Error details: The requested URL returned error: 404 Not Found
Filename on disk: OptiFine-1.14.4_HD_U_F2.jar
Path: C:\Users\Jeff\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F2\OptiFine-1.14.4_HD_U_F2.jar
Exists: Nonexistent

**Comment by NMarcoux** [comment]
Can I get an updated version of this .JSON it is a bit outdated I think and i'm struggling to figure out what needs to be changed besides optifine_hd_u_f2 to f3

**Comment by Ansh934** [comment]
https://github.com/cabaletta/baritone/issues/1235

**Comment by Ansh934** [comment]
> Can I get an updated version of this .JSON it is a bit outdated I think and i'm struggling to figure out what needs to be changed besides 1.14.4_hd_u_f2 to f3

See this I have covered here
