### ISSUE TITLE
New Command: hunt

### ISSUE THREAD

**Issue by txlawso** [cabaletta/baritone#749]
## Describe your suggestion
The hunt command will automatically hunt nearby mobs and get their loot.

## Settings
target: choose which mob(s) to kill first
avoid: choose which mob(s) to avoid killing/encountering

## Context
Allows players to kill mobs while mining.
Allows players to hunt for mob drops or food.

## Final checklist
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
impact already has this so i'm unlikely to add it to baritone. 

followentities already implements this, and I won't add a kill aura to baritone, so this is as close as it's going to get

**Comment by joeyc002** [comment]
Now that Impact is abandoned, could it be a feature to add?

**Comment by Caleb828** [comment]
I would love to see a way to hunt Player(s) / Mob(s).

**Comment by hellidox** [comment]
client killaura + `#follow entities <targets>`

**Comment by hellidox** [comment]
maybe put a
```
#stop
#goto coords
#follow entities <targets>
```
in your client's settings to activate every few minutes or so to keep baritone near one spot

**Comment by ripnonfegames** [comment]
but it wont follow the item drops, instead it might even walk down to the caves just to find a skeleton got killed by another skeleton's bone
