### ISSUE TITLE
On death, set goal to death location

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#75]
So that you can go straight back.

**Comment by ZeroMemes** [comment]
If we created a way of tagging existing goals, we could set "user" to the custom one, "death" to the most recent death point (or maybe save multiple goals under the same tag with timestamps?) and do the same with #54.

**Comment by HowardStark** [comment]
Tags will also be useful for expanding the minimal functionality because we
can render based on tag and make it more extensible. I like that @ZeroMemes

**Comment by leijurv** [comment]
For example, something like "save tagName" would save the current goal, and something like "load tagName" would load it?

Sethome could also do "save home" and home could also do "load home". So then even on servers where those commands do stuff, baritone also saves it. And on servers where they don't, you would do "/home" then "/path" to go there. 

"death" could be an alias for "load death". Or maybe when you respawn baritone says in chat: "you died at x, y, z. Run" /load death" to set your goal to your most recent death way point"

**Comment by HowardStark** [comment]
I was thinking not user-configurable tags. Spawn would be a tag, deathpoint would be a tag, maybe home would be a tag, and then waypoint would be a tag. The user can set waypoints and homes, which would have a name separate from their respective tags.

This would make it pretty simple to interact with the various points.

**Comment by leijurv** [comment]
......but why? What's wrong with allowing flexibility in picking any waypoint name they like? death would be set to where you die, spawn could be 0,0 by default, and you can come up with any names you like? Home, base, outpost, etc. I think just one system of waypoints, instead of nested tags then waypoints.

**Comment by HowardStark** [comment]
What? Nothing I said precludes having named and fully configurable waypoints?

It would look something like:
```
/set <tag type> <name>
```
And then the spawn and death tags would be automatic. All I'm saying is we constrain the available tags to allow for easier sorting and management.

**Comment by leijurv** [comment]
I don't think I'm seeing the benefit of a nested system of tags and waypoints, why not just waypoints?

**Comment by JonHughes08** [comment]
how do you see where you died with baritone?
