### ISSUE TITLE
"file baritone-standalone-forge-1.2.8.jar is not a valid mod file"

### ISSUE THREAD

**Issue by Vegorisham** [cabaletta/baritone#751]
![Screenshot (212)](https://user-images.githubusercontent.com/53911067/62718143-4b0ea600-b9d3-11e9-97ca-8c55326b4503.png)

Baritone is my only forge mod installed

**Comment by StijnSimons** [comment]
Lmao mate you’re running a 1.12.2 mod for 1.14.4
