### ISSUE TITLE
Please add a brief but descriptive title. 

### ISSUE THREAD

**Issue by EmeraldSnorlax** [cabaletta/baritone#754]
Please add a brief but descriptive title.

**Comment by StijnSimons** [comment]
Please add a brief but descriptive title.

**Comment by mrphax0r** [comment]
I don't think it's helpful to make useless issues.

**Comment by EmeraldSnorlax** [comment]
@mrphax0r Please add a brief but descriptive title.

**Comment by StijnSimons** [comment]
> I don't think it's helpful to make useless issues.

Lmao then how about the “Baritone Monitization Plan” issue? Or the “backdoor” issue?

**Comment by EmeraldSnorlax** [comment]
I'm fully serious with this issue. 
@leijurv How do you propose going about this?

**Comment by usereewrjrjeejr** [comment]
@mrphax0r cringe

**Comment by StijnSimons** [comment]
Please add a brief but descriptive title.

**Comment by EmeraldSnorlax** [comment]
Please add a brief but descriptive title.

**Comment by ishidex2** [comment]
muda muda muda muda muda muda muda muda muda muda muda muda muda muda muda muda muda muda muda

**Comment by Coldram3n** [comment]
Please add a brief but descriptive title.

**Comment by mrphax0r** [comment]
@StijnSimons
We already have a backdoor.

**Comment by StijnSimons** [comment]
CryptoLocker* tyvm.

**Comment by Mhowser** [comment]
Pwease add a bwief but descwiptive titwe UwU

**Comment by BlueBlazeTech** [comment]
> Pwease add a bwief but descwiptive titwe UwU

*cough* "CHECKLIST - no uwus or owos" *cough*

**Comment by Mhowser** [comment]
Bruh moment

**Comment by bddvlpr** [comment]
Please add a brief but descriptive title.

**Comment by EmeraldSnorlax** [comment]
Please add a brief but descriptive title.

**Comment by bddvlpr** [comment]
![image](https://user-images.githubusercontent.com/17461028/180625204-66639553-8bf8-4840-b69a-077549bcb7f6.png)

**Comment by leijurv** [comment]
Please add a brief but descriptive title.

**Comment by skyrina** [comment]
Please add a brief but descriptive title.

**Comment by bddvlpr** [comment]
Please add a brief but descriptive title.

**Comment by CesiumCs** [comment]
Please add a brief but descriptive title.

**Comment by EmeraldSnorlax** [comment]
Please add a brief but descriptive title.
