### ISSUE TITLE
    Make a weblate.                                                                                         Please add a a brief but descriptive title

### ISSUE THREAD

**Issue by mrphax0r** [cabaletta/baritone#757]
## Describe your suggestion
A weblate would be nice since the strings.json feature doesn't seem to have good resonance. I don't think this is a dupe of the original post because it just describes a different approach.

## Context
Internationalization!

## Final checklist
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Please add a a brief but descriptive title.
Pretty much a copy of every localisation suggestion.
