### ISSUE TITLE
baritone crashes after about 10 seconds of being in any world

### ISSUE THREAD

**Issue by LostWasTaken** [cabaletta/baritone#758]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: Impact 4.7.2 and baritone-api-forge-1.2.7/8.jar (both crash)
Forge mods (if used): Impact 4.7.2

## Exception, error or logs
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j

## How to reproduce
1. launch game
2. go into any server/world and it crashes after 10~ seconds

## Final checklist
- [ + ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ + ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ + ] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Either baritone or impact should be installed as a forge mod, not both. When you say "both crash" does that mean that they crash when both are installed, or each one individually crashes? Also please include your version of forge.

**Comment by LostWasTaken** [comment]
> Either baritone or impact should be installed as a forge mod, not both. When you say "both crash" does that mean that they crash when both are installed, or each one individually crashes? Also please include your version of forge.

I tested out both seperately, i never launched forge with both of them in my mods folder. I use 1.12.2-forge1.12.2-14.23.5.2768

**Comment by leijurv** [comment]
<img width="273" alt="Screen Shot 2019-08-09 at 10 05 43 AM" src="https://user-images.githubusercontent.com/3837873/62806322-3a6f3600-ba8e-11e9-8b8f-1262d8bbfe2c.png">
<img width="1680" alt="Screen Shot 2019-08-09 at 10 12 24 AM" src="https://user-images.githubusercontent.com/3837873/62806323-3ba06300-ba8e-11e9-85a1-ba35d6ef8e96.png">

works for me? weirdddd

**Comment by LostWasTaken** [comment]
hmm

**Comment by LostWasTaken** [comment]
I reinstalled Impact as Vanilla instead of with Forge and now its working perfectly, ty anyway
