### ISSUE TITLE
Buildcraft + Baritone = Crash

### ISSUE THREAD

**Issue by boontar007228** [cabaletta/baritone#760]
## **Some information**
**Operating system:**
Windows 7 64x

**Java version:**
Java 8 Update 221
build 1.8.0_221-b11

**Minecraft version:**
1.12.2

**Baritone version:**
4.6 4.7.1 4.7.2

**Forge mods (if used):** 
Forge 14.23.5.2768
Buildcraft-all 7.99.24.2
and more

## Exception, error or logs
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)

[debug.log](https://github.com/cabaletta/baritone/files/3487443/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/3487444/latest.log)

## How to reproduce
Install Minecraft 1.12.2
Install Buildcraft
Install Baritone 
Launch

Game will be crash on step "Launch - Initializing mods Phase 2

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by mrphax0r** [comment]
Forge is _unsupported_ .

**Comment by 0-x-2-2** [comment]
Crash seems to be unrelated to baritone 🤔
