### ISSUE TITLE
#goto cannot track multiple different blocks

### ISSUE THREAD

**Issue by lolbox123** [cabaletta/baritone#761]
I play on 2b2t and sometimes i use #goto minecraft:white_shulker_box to find dupe stashes, and i was wondering if i could track multiple shulker colors at once and that got me wondering if baritone could track 2 blocks or more at the same time? if not this could be a very cool addition!

**Comment by EmeraldSnorlax** [comment]
use #mine shulkerbox shulkerbox shulkerbox instead

**Comment by lolbox123** [comment]
would #mine shulkerbox go to every color of box?

**Comment by EmeraldSnorlax** [comment]
doing #mine white_shulker_box gray_shulker_box etc will path to every shulkerbox, then attempt to mine it. you can always cancel it when you arrive

**Comment by lolbox123** [comment]
but with #goto whenever there is no box in the area, the bot just walks around until it finds one. but with #mine, the bot scans the area and stops when it sees that there is no box.
