### ISSUE TITLE
#followentities does not accept armor_stand as an entity filter

### ISSUE THREAD

**Issue by CheatTriggers** [cabaletta/baritone#762]
## Some information
Operating system: Windows 10 Pro 1903
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.4.0

## Exception, error or logs
No error or logs besides the message:
"[Baritone] Following any entities"

## How to reproduce
Place down an armor stand, spawn a bunch of pigs, sheeps and cows or whatever mobs you feel like around it, move a few blocks away from the mob mess and type ``#followentity armor_stand``, the expected result is for it to target the armor stand in the center and go towards it, instead it follows anything and never goes to the armor stand because of all the mobs distracting it around.

NOTE: Baritone **DOES** detect armor stands as a valid entity to follow, if you spawn just the armor stand by itself with no mobs around and type ``#followentity`` it will go towards the armor stand. The issue here is that it doesn't seem to accept it as an entity filter, like ``#followentity pig``.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
- `#followentity armor_stand` will follow an armor stand.
- `#followentities armor_stand` will be interpreted as `#followentities` and will just follow any entity it comes by.
