### ISSUE TITLE
baritone could learn how to make craft ask by the users

### ISSUE THREAD

**Issue by KleinBagel** [cabaletta/baritone#763]
## Describe your suggestion
Baritone could learn how to make craft ask by the users for example to turn watermelon into watermelon seed on each users could choose what baritone recipe should do in our case. and that could apply on the ores, to put the ores in the oven with coal to make leather with possibility to keep the ingot on us or in a chest.

**Comment by EmeraldSnorlax** [comment]
doesnt sound that useful imo. typing a command into chat takes much longer then opening a crafting bench and placing the items in, or using the crafting book to shift click. also why tf would baritone need to learn recipes from players

**Comment by a6d6061ed1** [comment]
I have even better idea, partner up with OpenAI and utilise neural networks so that baritone can pvp and use elytra :o jk

**Comment by usereewrjrjeejr** [comment]
🤡

**Comment by StijnSimons** [comment]
Pls

**Comment by NatoBoram** [comment]
Duplicate of #295

**Comment by l1ving** [comment]
There's no need to comment on a 1.5 year old issue, we know it's a duplicagte.

**Comment by NatoBoram** [comment]
I didn't, and I spent half an hour searching for the one issue. Next one to use the search function will land on the correct issue in two clicks instead of 150.
