### ISSUE TITLE
in water, cross 1.14.4

### ISSUE THREAD

**Issue by Armagann** [cabaletta/baritone#765]
![in water, cross](https://i.imgur.com/yFDJiy7.gif)

**Comment by usereewrjrjeejr** [comment]
Image is broken

**Comment by millennIumAMbiguity** [comment]
if you mean that you can't swim fast (pre 1.13 swimming).
then the problem is that baritone is built on 1.12.2.
it is best to wait for forge 1.13+ to implement fast swimming. unless we are okay with implementing it two times.
