### ISSUE TITLE
Possible to have Baritone auto mine a region?

### ISSUE THREAD

**Issue by Puyodead1** [cabaletta/baritone#769]
I am wondering if it is possible to set points (create regions) and have baritone auto mine it, such as mine out an area (on 1.14.4 without schematics)

**Comment by millennIumAMbiguity** [comment]
it's not possible to create a region and exuviate that.
but you can just use `#click` and the left click-drag over the volume you want to be exuviated.

**Comment by Puyodead1** [comment]
> it's not possible to create a region and exuviate that.
> but you can just use `#click` and the left click-drag over the volume you want to be exuviated.

Cool, thanks!

**Comment by Fatalreality** [comment]
can i make a schematic of a perimeter and load it to auto mine a region?
