### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by MastaNub** [cabaletta/baritone#772]
## Some information
Operating system: Windows 10
Java version: Max
Minecraft version: Max
Baritone version: Max
Forge mods (if used): No.

## How to reproduce
Do what video.
https://www.youtube.com/watch?v=X4cRYOG3DzU

## Final checklist
- [✓] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [✓] I have included logs, exceptions and / or steps to reproduce the issue.
- [✓] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Imagine having `allowPlace` disabled

**Comment by leijurv** [comment]
turn off `legitMine`, turn on `allowPlace`, turn on `allowBreak`

**Comment by MastaNub** [comment]
I literally typed "allowPlace" twice
http://prntscr.com/orw7h2
It was on before I typed the command.

**Comment by leijurv** [comment]
its legitmine you rart
