### ISSUE TITLE
[Suggestion] allow world-edit like features

### ISSUE THREAD

**Issue by MasterGam3r** [cabaletta/baritone#774]
Add functions similar to .b click,but instread of mouse,you can use let's say #pos1 and it will select first position at your feet [or you could #pos1 100 10 100 to select coordonates] then #pos2 with the same effect,then allow stuff like #fill [block] or #cleanarea

**Comment by StijnSimons** [comment]
`#goal` -> pos1
`#cleararea` at pos 2

**Comment by LoganDark** [comment]
@StijnSimons and to fill an area with blocks you use which command, hmm?
