### ISSUE TITLE
farm says failed on success

### ISSUE THREAD

**Issue by Puyodead1** [cabaletta/baritone#777]
## Some information
Operating system: Windows 10 pro 
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.4,0
Forge mods (if used): none

## Exception, error or logs
<details>
<summary>Click to view</summary>

```
[16:14:02] [main/INFO]: [CHAT] §5[§dBaritone§5]§7 farming
[16:14:10] [pool-5-thread-8/INFO]: [STDOUT]: 17098 movements considered
[16:14:10] [pool-5-thread-8/INFO]: [STDOUT]: Open set size: 4074
[16:14:10] [pool-5-thread-8/INFO]: [STDOUT]: PathNode map size: 4855
[16:14:10] [pool-5-thread-8/INFO]: [STDOUT]: 13465 nodes per second
[16:14:10] [pool-5-thread-5/INFO]: [STDOUT]: 17098 movements considered
[16:14:10] [pool-5-thread-5/INFO]: [STDOUT]: Open set size: 4074
[16:14:10] [pool-5-thread-5/INFO]: [STDOUT]: PathNode map size: 4855
[16:14:10] [pool-5-thread-5/INFO]: [STDOUT]: 20025 nodes per second
[16:14:10] [main/INFO]: [CHAT] §5[§dBaritone§5]§7 Farm failed
```

</details>

## How to reproduce
- go to an area to be farmed
- type ``#farm``
- baritone will farm like expected but when it finishes it will say ``farm failed``

## Final checklist
- [ X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [X ] I have not used any OwO's or UwU's in this issue.

![image](https://user-images.githubusercontent.com/14828766/62974180-a54da380-bde5-11e9-83eb-ce08d1833451.png)

_OwO_

**Comment by StijnSimons** [comment]
Send screenshot of ur farm. Also banned for owo

**Comment by Aaron2550** [comment]
Isn't it normal that it fails when there are no fully grown crops in range?

**Comment by Puyodead1** [comment]
> Isn't it normal that it fails when there are no fully grown crops in range?
> 
> Edit: and no unused soil*

There are fully grown crops, thats the thing, it farms fine but says it failed.

> Send screenshot of ur farm. Also banned for owo

Sorry, the server with the farm was down yesterday. Here is a picture of the farm.
![2019-08-16_17 42 12](https://user-images.githubusercontent.com/14828766/63199907-4ee29e00-c04d-11e9-9ccf-13ba15a94ad3.png)

**Comment by StijnSimons** [comment]
Send a screenshot of your `#modified`

**Comment by Puyodead1** [comment]
> Send a screenshot of your `#modified`

![image](https://user-images.githubusercontent.com/14828766/63216157-4ea2db00-c0ff-11e9-8e3c-eab223f9c30f.png)

**Comment by StijnSimons** [comment]
Wait you mean it still farms fine?

**Comment by Puyodead1** [comment]
> Wait you mean it still farms fine?

Correct, it farms fine, but it says ``farm failed``. It's not a huge deal but i thought i should bring it up.

**Comment by millennIumAMbiguity** [comment]
`farm failed` means that there is no way to do any additional work and the task is being canceled.

**Comment by StijnSimons** [comment]
No real issue here.

**Comment by HelixCraft** [comment]
I found an way! I tried using `#farm` but it always broke up after about 5 seconds, i searched in the baritone settings and found the `farmMaxScanSize`. Just set it to a higher number (for me 2560 worked but lower is probably also fine) and all my problems wear gone!
