### ISSUE TITLE
Forge not working....?

### ISSUE THREAD

**Issue by RainOfPain125** [cabaletta/baritone#780]
## What do you need help with?
https://github.com/cabaletta/baritone/blob/master/SETUP.md
The Artifacts section simply says to download the Forge Standalone file if you want to use forge (with other mods that don't use baritone). OK, great, download the file and move it into my mods folder.

But baritone doesn't load? It doesn't show up in the mods list? I'm running 1.12.2 forge, and the downloads page doesn't even indicate what version of MC a download is for, so...?
## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
Which artifact version?

**Comment by leijurv** [comment]
It does load. Baritone intentionally does not show up in the mods list. Did you try using it?

**Comment by RainOfPain125** [comment]
> Which artifact version?

The.. latest one? I know devs hate hearing latest one, but thats what it was at the time of posting this



> It does load. Baritone intentionally does not show up in the mods list. Did you try using it?

I tried # in chat and nothing happened, so.

Speaking of #, technically a staff member could check if you have Baritone by forcing you to type just # lol

**Comment by leijurv** [comment]
no, there is a `prefixcontrol` setting

latest is incorrect. latest is 1.3.* which is for minecraft 1.13 only. you want 1.2.8 api forge

**Comment by RainOfPain125** [comment]
> no, there is a `prefixcontrol` setting to disable # control
> 
> latest is incorrect. latest is 1.3.* which is for minecraft 1.13 only. you want 1.2.8 api forge

But how was I supposed to know that based on https://github.com/cabaletta/baritone/blob/master/SETUP.md

https://github.com/cabaletta/baritone/releases doesn't explain what MC ver it is either. quite a bit confusing.

**Comment by leijurv** [comment]
<img width="475" alt="Screen Shot 2019-08-15 at 10 56 34 PM" src="https://user-images.githubusercontent.com/3837873/63146496-f5786180-bfaf-11e9-8c8f-da3804aa44bc.png">

**Comment by RainOfPain125** [comment]
![image](https://user-images.githubusercontent.com/33137905/63146553-4b0d3800-bfc9-11e9-95d4-13cced46d3cd.png)
It'd be cool if that notice was attached to later editions, not ones further down the list.

Thats like expecting someone to go to the second page of google search results. lol.
