### ISSUE TITLE
cant get it to use -XYZ 

### ISSUE THREAD

**Issue by raithap** [cabaletta/baritone#782]
## What do you need help with?
 i cant get it to use a negative coordinates in commands

**Comment by Dreanh** [comment]
I have the same problem, it tries to path to some unknown location. Using #goal to set goal also doesn't work I'm in negative x & z. Tried #reset, but that did nothing.

**Comment by StijnSimons** [comment]
`.b goto -817 9 -189`???

**Comment by Dreanh** [comment]
No, doesn't work. But I'm under -100k in both directions.
