### ISSUE TITLE
Set Y motion to 0.42 instead of jumping

### ISSUE THREAD

**Issue by mrphax0r** [cabaletta/baritone#784]
Let's say you want baritone to jump but have e.g. HighJump enabled. Anticheats would flag and/or ban you. This is currently solved by disabling the Module, a different approach would be to just set Y motion 0.42, which is the equivalent of jumping. 

_Sent from my Toaster using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LoganDark** [comment]
Turn off HighJump?

IMHO, Baritone is supposed to simulate user input (to some extent), not do hacky things like setting Y motion.

**Comment by mrphax0r** [comment]
@LoganDark Since unmodified Minecraft does exactly that when jumping, I wouldn't consider it too "hacky". It was just an alternative approach to a problem tho.

**Comment by LoganDark** [comment]
@mrphax0r It's always good practice to call methods in the original code that do what you want rather than reimplementing it yourself.
