### ISSUE TITLE
Mobs killing baritone while mining.

### ISSUE THREAD

**Issue by bjcband** [cabaletta/baritone#786]
## Some information
Operating system: Win 10
Java version: v8u45
Minecraft version: 1.14.4 (no impact)
Baritone version: recent (~10 days)(sorry XD)
Forge mods (if used): none

Some examples:
1. Baritone walks through a cave, creeper sees the bot but it keeps mining. Creeper walks right up behind baritone and explodes. A fix for this could be killing the creeper, or blocking up the path behind the bot.
2. Baritone walks near lava to mine some blocks in a cave. A skeleton spots baritone, and shoots an arrow at baritone, hitting the bot into lava. A fix for this could be, again killing the skeleton, or standing at a calculated distance from lava after detecting a skeleton.
3. Baritone walks near lava again in a cave and a creeper walks up to the bot and it explodes, the blocks destroyed or knockback knocks baritone into lava. A fix for this could be, killing the creeper, or standing at a range from lava on detection of a creeper (maybe used in combo of killing the creeper) Also if desperate measures happen where the bot cannot escape the creeper, maybe it could build below itself after the explosion to build a platform above the lava.

It is a lot to ask, but these are some issues I had while using the bot. It is a bug and suggestion, but it did interfere when I wanted to start mining, otherwise I had no problems.

**Comment by LoganDark** [comment]
> standing at a calculated distance from lava after detecting a skeleton

dodge the arrow.

**Comment by PatrickStar420** [comment]
you can turn on avoidance, jesus, kill aura and auto log
turn off combat pause for the best results and then all the problems you listed would be fixed

**Comment by LoganDark** [comment]
> you can turn on avoidance, jesus, kill aura and auto log
Baritone doesn't have those.

**Comment by plootia** [comment]
Baritone has avoidance.

**Comment by PatrickStar420** [comment]
> > you can turn on avoidance, jesus, kill aura and auto log
> 
> Baritone doesn't have those.

Yeah but most hacked clients have those options accept avoidance since that is a part of baritone already

**Comment by RileyGuy** [comment]
In my experience, avoidance doesn't work unless you're following a player.

**Comment by 0-x-2-2** [comment]
avoidance does work it is just done at path calc time so if a mob moves onto the path it wont avoid the mob.

**Comment by StijnSimons** [comment]
Just turn the avoidance radius higher and you’ll be good.

**Comment by TheUnderTaker11** [comment]
This really shouldn't be closed, at least not for the reason given.

Avoidance, if set too high, makes Baritone never able to calculate any path.

Then if it's at a more reasonable amount, the mobs see the bot and very easily follow it into the path it made. Avoidance settings haven't reduced the deathrate of my bot in the slightest.


If it's a "won't fix/not directly related so not gonna try to fix" then that's fine, but the reason for closing it doesn't actually work since it doesn't account for the mobs seeing and following you. What I would like to see is the option for baritone to close the 2 block path behind it every once in awhile, would solve at least most of the deaths.

**Comment by scorbett123** [comment]
You can use backfill to close the hole if you really need to. I know it isn't perfect for this use, however it would temporarily solve it.  I doubt that anyone will care to fix this, and there are lots of suggestions that suggest ways to solve this issue more directly. For example lighting up mines.

**Comment by l1ving** [comment]
Most people use the provided Baritone from Impact / KAMI Blue, which do have KillAura integrated with Baritone which would solve this issue

**Comment by josephyooo** [comment]
> Most people use the provided Baritone from Impact / KAMI Blue, which do have KillAura integrated with Baritone which would solve this issue

What if you're not one of those people? Has such a feature already been recognized as something that won't be implemented?

**Comment by l1ving** [comment]
It will not be implemented.

**Comment by DerDennisOP** [comment]
Hey, baritone community. I'm a programmer and would contribute a fix. Who would like a fix? If there is enough demand to avoid mobs properly and doge arrows / blazes.

**Comment by wisplite** [comment]
This really should be a thing. Some people use Baritone for reasons that disallow a hacked client. I want to build a giant schematic without my bot dying constantly. Would it really be hard to make it attack mobs with a sword if it has to?

**Comment by ImAlexBlock** [comment]
Consider bypassing strict anti-cheat (such as Grim) I think this is difficult to achieve

**Comment by MiyukiNozomi** [comment]
Couldn't baritone simply have a mode to look at a mob and attack it?

**Comment by Hugos68** [comment]
@MiyukiNozomi Those already exists and should not be part of baritone, it's pathfinding, not kill aura
