### ISSUE TITLE
Adding a cancel hotkey keyboard shortcut for dangerous circumstances

### ISSUE THREAD

**Issue by bjcband** [cabaletta/baritone#788]
If baritone is stuck in a situation it can't handle, typing #cancel can be fatal if a few seconds mean the loss of the bots life. A hotkey could fix this. Just a suggestion but a good one!

**Comment by PatrickStar420** [comment]
auto log / auto disconnect is a thing

**Comment by bjcband** [comment]
No i mean to cancel an operation

**Comment by usereewrjrjeejr** [comment]
Use the macros in impact

**Comment by AlexApps99** [comment]
Adding hotkeys is something that clients should implement, not baritone.
@bjcband Please can you close this issue and contact the developer of your preferred client?

**Comment by 0-x-2-2** [comment]
baritone should never be in a dangerous circumstance if you have found a issue with baritone doing something dangerous make sure to report it.
