### ISSUE TITLE
Why does it like to break blocks/going to the side randomly instead of just going straight ahead?

### ISSUE THREAD

**Issue by nuongwx** [cabaletta/baritone#791]
![2019-08-15_10 09 19](https://user-images.githubusercontent.com/27423086/63070396-36875c00-bf45-11e9-924b-6acb419f013b.png)
­
­
Casually breaking blocks on hw to walk in without any reason. Eats pickaxes like hell.

**Comment by PatrickStar420** [comment]
Baritone prolly was pathfinding while the next chunk wasnt loaded and so that was the closest spot to the goal

**Comment by usereewrjrjeejr** [comment]
turning off `.b allowbreak` fixes this

**Comment by RileyGuy** [comment]
> 
> 
> turning off `.b allowbreak` fixes this

Or #allowbreak if you're not using a hacked client.

**Comment by clragon** [comment]
disabling break might not always be favorable tho, so fixing this would still help

maybe recalculate the path when you get close to a chunk that wasnt in the calulcation or something like that
