### ISSUE TITLE
About Orebfuscator

### ISSUE THREAD

**Issue by ChinaMeritocracy** [cabaletta/baritone#793]
You see, when the server is installed with Orebfuscator, the ore is faked until you mine the block around it. So can you make it possible to digging tunnels while mining ores that the player can see？

**Comment by mostafakerim** [comment]
This is already possible with by turning legitmine on

**Comment by StijnSimons** [comment]
`#legitmine true`

**Comment by ChinaMeritocracy** [comment]
..legitmine may lead you to a place faraway only to find nothing there

**Comment by StijnSimons** [comment]
There’s no other way? You expect baritone to  *hack* the server and make it send the actual positions?

**Comment by alexkmnsky** [comment]
I think what op wants is an auto tuneller which mines ores upon encountering them

**Comment by Aaron2550** [comment]
If using impact: .b tunnel dunno if that works in baritone only

**Comment by mrphax0r** [comment]
Adding a stripmine mode would fix this.
