### ISSUE TITLE
Add a settings gui

### ISSUE THREAD

**Issue by bjcband** [cabaletta/baritone#794]
A gui would be nice : )

**Comment by usereewrjrjeejr** [comment]
Baritone has too many settings for this to be practical

**Comment by bjcband** [comment]
> 
> 
> Baritone has too many settings for this to be practical

you could make categories, and this doesn't mean operations would need the gui, im talking about general settings, e.g hotkeys, colors etc

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/63229954-47013600-c1d4-11e9-9095-1112d80bd4e2.png)
