### ISSUE TITLE
Build schematics don't work in 1.14.4

### ISSUE THREAD

**Issue by fattybrid** [cabaletta/baritone#799]
So lately ive really taken to Baritone because of all the cool things you can do with it and its potential. However for some reason the ability to create schematics (something I was really looking forward to) doesnt work in 1.14.4? It crashes my game and im assuming it has to do with the new block ids or something like that since 1.14 is very different than what we were used to in 1.8 and what not. Is this only me and if not is there a way I can help speed up the process of this specific feature, for example, donating?

Minecraft version: 1.14.4
Baritone version: 1.14.4

**Comment by Aaron2550** [comment]
Schematics don't work 1.13+ cuz the change from numerical IDs to name IDs

**Comment by fattybrid** [comment]
so i got litematica for 1.14.4 and i created a schematic and when I try to load it with baritone instead of crashing this time it just says unable to load. Am i on to something or does it not work no matter the schematic version?

**Comment by plootia** [comment]
You can only use #build in 1.12.
