### ISSUE TITLE
.b mine issue

### ISSUE THREAD

**Issue by hitleriscool** [cabaletta/baritone#802]
Ok so i need to get a shulker of seeds for a friend and i did .b mine tallgrass to mine grass and i have a shovel with fortune in my hotbar and it wont let me hold it its really annoying

**Comment by StijnSimons** [comment]
*just out of curiosity, how did you get to that name*

**Comment by STOPNOAnime** [comment]
I think we have the same friend

**Comment by VonFriedricht** [comment]
https://github.com/settings/admin

**Comment by iFaRrAyEh** [comment]
i have same issue i can't chose in the hotbar

**Comment by dominikaaaa** [comment]
Closing this in favor of #1334
