### ISSUE TITLE
baritone-standalone-1.4.0.jar is Not a Valid Mod File

### ISSUE THREAD

**Issue by bobcristello** [cabaletta/baritone#812]
When I install Baritone as it's own profile in minecraft, everything works fine.  

When I install Forge and then add the baritone-standalone-1.4.0.jar to the .minecraft/mods directory and launch the game with Forge, this is the error that I get.  

I am running minecraft java 1.14.4 on a pc.

I would love to use Baritone and Forge together as I have other mods I would like to play with.  Any help would be appreciated.

Regards,

Bob

**Comment by leijurv** [comment]
not possible. forge support above 1.12 is blocked on mixin support for modlauncher. no eta.
