### ISSUE TITLE
Autojump Wrong Y Coordinate

### ISSUE THREAD

**Issue by cancerousname69** [cabaletta/baritone#813]
## Some information
Operating system:first appeared on Manjaro, Tested on Windows 10.
Java version:8
Minecraft version:1.12.2
Baritone version:Latest I assume

## Exception, error or logs
Wrong Y Coordinate

## How to reproduce
Hard.
Enable Autojump in 1.12.2
Toggle NCP Step
Enable ChatDebug
Make it path a long way with many Steps.
AssumeStep is optional, doesn't change anything
Watch it Spam "Wrong Y Coordinate" and sray In air.
(It might be an AntiCheat issue, I am very unsure)
## Final checklist
- √I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- √ I have included logs, exceptions and / or steps to reproduce the issue.
- √I have not used any OwO's or UwU's in this issue.

**Comment by IronException** [comment]
try with autojump disabled

**Comment by mrphax0r** [comment]
Oh wow, I couldn't have thought of that myself. Also, this issue is mainly to ease the life of people who cannot jump proprly and use autojump.
