### ISSUE TITLE
bot stuck due to vine

### ISSUE THREAD

**Issue by RfRaikou** [cabaletta/baritone#814]
vine broke bot

**Comment by AlexApps99** [comment]
Please be more specific and include screenshots, version etc.
The Baritone setting `allowVine` is unsupported as described in Settings:
> Enables some more advanced vine features. They're honestly just gimmicks and won't ever be needed in real pathing scenarios. And they can cause Baritone to get trapped indefinitely in a strange scenario.
> Almost never turn this on lol

**Comment by usereewrjrjeejr** [comment]
Solved.

**Comment by aNaturalCause** [comment]
> vine broke bot

The issue is -- when a vine extends into the water, with having a goal and path set, if the path runs along the vine that is  in the water, either left side, right side or even in front, the path will come to a stop and not continue.
