### ISSUE TITLE
I cant use `mine diamonds` literally unplayable

### ISSUE THREAD

**Issue by Graicc** [cabaletta/baritone#816]
## Describe your suggestion
please i need this. Also some more general mining keywords like coal, iron, gold etc.

## Settings
Add `mine diamonds` / `mine diamond` as an alias of `mine diamond_ore`, `mine iron` as `mine iron_ore` etc.

## Context
You would become cooler than your toenails.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment]
`mine diamond_ore` ....

**Comment by Aaron2550** [comment]
Then we'd need short synonyms for all common blocks

**Comment by LoganDark** [comment]
Maybe you could research how WorldEdit does it?

**Comment by Aaron2550** [comment]
True, that could work

**Comment by Aaron2550** [comment]
Essentials has some good aliases like dsword too

**Comment by LoganDark** [comment]
Why would you want to mine diamond sword?

**Comment by aftery142** [comment]
> 
> 
> Why would you want to mine diamond sword?

Why wouldn't you mine diamond swords?

**Comment by LoganDark** [comment]
@aftery142 Good point. Well, I know for a fact I haven't been mining golden apples for the past half hour for no reason. :)

**Comment by BlueBlazeTech** [comment]
oooh, gotcha.
