### ISSUE TITLE
build not working right

### ISSUE THREAD

**Issue by thatburritotho** [cabaletta/baritone#817]
## Some information
Operating system: Win10
Java version:12.0.1.0
Minecraft version:1.12.2
Baritone version:1.2.6
Forge mods (if used): 

## How to reproduce
use the build command and have stairs in the schematic. 

every time I try to build anything it will stop at random. and ant thing with stairs baritone will ether putt it in the wrong place or it will place it and break it.

**Comment by huohei250894** [comment]
Same

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by waterdragon78** [comment]
hello?

**Comment by l1ving** [comment]
There's an already reported issue with more detail, closing as duplicate.
