### ISSUE TITLE
Impact/Baritone - Avoid Certain Mobs

### ISSUE THREAD

**Issue by creepinson** [cabaletta/baritone#821]
## Describe your suggestion
I would like to be able to have baritone or (impact client w/ baritone) avoid certain entities when pathfinding. 
## Settings
You should be able to tweak the types of entities/mobs you want to avoid.

## Context
So, for example, if it is night time, I don't want baritone to have me just walk into a creeper as I am trying to find my way to something. 
I want to either, kill (which I know is possible), or _avoid_ the monsters.

This could be part of the impact hacked client instead of just baritone but whatever.

**Comment by StijnSimons** [comment]
This already exists, but i think its bugged in 1.14. `#avoidance true`

**Comment by creepinson** [comment]
Oh, ok thanks lol.

**Comment by creepinson** [comment]
Can you avoid certain mobs, or does it have to be all hostile mobs?

**Comment by StijnSimons** [comment]
It avoids all hostile mobs, ranges can be configured.

**Comment by creepinson** [comment]
Ok, thanks. In the future maybe you could add a way to avoid specific mobs.

**Comment by Userboi2** [comment]
This is a stupid idea. Specific mobs? "I don't want to be killed by creepers but by skeletons!"

**Comment by Sly-Little-Fox** [comment]
> This is a stupid idea. Specific mobs? "I don't want to be killed by creepers but by skeletons!"

You may want to either avoid piglins or not (depends on whether you have golden armor)

**Comment by ArcsNet** [comment]
necro asf but nobody though of using this as a pve bot?
