### ISSUE TITLE
#pause pathing

### ISSUE THREAD

**Issue by LoganDark** [cabaletta/baritone#823]
## Describe your suggestion
Baritone currently can't pause gotos, and that's an issue if I, for example went there in freecam to set the goal. #pause does nothing, and #cancel deletes the goal. :/

Fortunately, there is an echo in chat that describes the goal that was set, but it's still a minor inconvenience. More so if the chat is active, like on 2b2t.

## Final checklist
- [OwO] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
`#pause` works fine for me, can I close this?

**Comment by LoganDark** [comment]
Probably been fixed then. I haven't used baritone in a long time.
