### ISSUE TITLE
How do i integrate baritone into my mod?

### ISSUE THREAD

**Issue by matyklugDebbuged** [cabaletta/baritone#826]
## What do you need help with?
if i run the example, it just crashes with Provider baritone.BaritoneProvider could not be instantiated
i read #665 ,and i got the same problem, but i dont understand the answer...
MC 1.12.2
same issue for both 1.2.8 and 1.4 baritone.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment]
You should have commented on that issue asking for clarification, because this is just a duplicate and should be closed.

**Comment by StijnSimons** [comment]
I assume you’re using ForgeGradle and MixinGradle, so run the `jar` task on baritone which gives you a jar without remapped classes. Once you remap your jar and decide to build it, use the `build` artifact. (Or baritone-api) ty leijurv

**Comment by matyklugDebbuged** [comment]
can you please explain more? i dont understand.
