### ISSUE TITLE
Is their a way to Find/Mine/Track Minecarts with objects such as chest, furnace?

### ISSUE THREAD

**Issue by Banthors** [cabaletta/baritone#828]
Title?

**Comment by StijnSimons** [comment]
`#followentity minecart`

**Comment by Banthors** [comment]
> `#followentity minecart`

Tried this all i get is entity not found. Is their a range limit to it. doesnt seem to work nearby.

**Comment by IronException** [comment]
if there is no minecart within your render distance it wound randomly search for one like with blocks.

**Comment by StijnSimons** [comment]
It won’t wander off to look for it. Only works with one cached or in render distance (and i dont think entities get cached)

**Comment by nbyrd** [comment]
Hmm. I get told that `followentity` is not a valid command. Is this something native to baritone?

**Comment by ZacSharp** [comment]
The commands are 
* `#follow entity minecart` for minecarts
* `#follow entity hopper_minecart` for hopper minecarts
* `#follow entity tnt_minecart` for tnt minecarts
* `#follow entity furnace_minecart` for furnace minecrats
* `#follow entity chest_minecart` for chest minecarts
* `#follow entity spawner_minecart` for spawner minecarts

tested in 1.12.2 with Baritone v1.2.14
