### ISSUE TITLE
1.12.2 building stuck in loop

### ISSUE THREAD

**Issue by entity0z** [cabaletta/baritone#829]
not using stairs.

1.12.2. 

https://gyazo.com/4185e1ab419d15b0078d4249b2b296b8

does this super frequently and i have to manually pause and resume with it. if anyone knows a fix or workaround, please do tell.

**Comment by Graicc** [comment]
Maybe try toggling build in layers?

**Comment by leijurv** [comment]
Next release will have a fix for this, added in https://github.com/cabaletta/baritone/commit/b9f0da7d27d9d62f7e671f05b087d9f30dce7e4a
