### ISSUE TITLE
baritone's is shaking

### ISSUE THREAD

**Issue by adam6t** [cabaletta/baritone#831]
The Baritone works fine, but the only issue i have is that its unpleasant to watch at the mouse shakes when you use the #goto I've looked around if anyone else had this issue but i failed to find anyone.

Does anyone know what the issue is or how to remove the shaking?
demo: https://www.youtube.com/watch?v=TCSUG9A7y8w

**Comment by xX-Denied-Xx** [comment]
update baritone if not updated or try using 'free look'

**Comment by Graicc** [comment]
Baritone has to do this, because if the player's position is too close to half a block, sprinting gets messed up (see [this](https://www.youtube.com/watch?v=DECKDy8gu1Y)). You can enable free look by using `#freelook`, which will stop baritone from moving the player's camera while moving.

**Comment by adam6t** [comment]
thanks for the help :)

**Comment by leijurv** [comment]
The shaking can be controlled / disabled by the randomLooking setting, the video that Graicc linked has more info in the description.

**Comment by Acceleration2299** [comment]
I am having a similar issue now too. For some reason during a Selection ClearArea command my baritone's mining system is **Vibrating.** sometimes moving the mouse off the block it's attempting to mine, I'm on baritone ver 1.6.5 Forge standalone.

**Comment by Acceleration2299** [comment]
I will mention i'm in a modpack called "Create: Above and Beyond" in case it's a mod conflict. 
https://cdn.discordapp.com/attachments/483132175282077697/1248723570792599683/2024-06-07_15-40-51.mp4?ex=6664b3f3&is=66636273&hm=e1308c3028a35636a5e06e925770e4300029090c88db86ba50b7e18346f5810b&
Video from Discord CDN for reference.

**Comment by Acceleration2299** [comment]
> I will mention i'm in a modpack called "Create: Above and Beyond" in case it's a mod conflict. https://cdn.discordapp.com/attachments/483132175282077697/1248723570792599683/2024-06-07_15-40-51.mp4?ex=6664b3f3&is=66636273&hm=e1308c3028a35636a5e06e925770e4300029090c88db86ba50b7e18346f5810b& Video from Discord CDN for reference.

Figured out the issue, for some reason by default theres a setting called "randomLooking113" that was set to 2.0 by default
it was the single problem.

**Comment by Urpagin** [comment]
Doing `#randomLooking113 0` fixed the issue for me. This setting is set by default to 2.0 so it must has a use, so setting it to 0 might cause problems.

 Thanks to https://github.com/cabaletta/baritone/issues/831#issuecomment-2155624917 which is the source.

**Comment by Ziege0** [comment]
> > I will mention i'm in a modpack called "Create: Above and Beyond" in case it's a mod conflict. https://cdn.discordapp.com/attachments/483132175282077697/1248723570792599683/2024-06-07_15-40-51.mp4?ex=6664b3f3&is=66636273&hm=e1308c3028a35636a5e06e925770e4300029090c88db86ba50b7e18346f5810b& Video from Discord CDN for reference.
> 
> Figured out the issue, for some reason by default theres a setting called "randomLooking113" that was set to 2.0 by default it was the single problem.

Thanks man had the same issue
