### ISSUE TITLE
missing parts of redstone veins when automining using #mine redstone_ore

### ISSUE THREAD

**Issue by xX-Denied-Xx** [cabaletta/baritone#832]
## Some information
Operating system: windows 64 bit
Java version: unknown
minecraft version: 1.12.2
Baritone version: v1.2.8
Forge mods (if used): none

https://www.youtube.com/watch?v=F_W2fnb9j2M&feature=youtu.be
(if its not there check back in like 20mins or so to see if it uploaded.

## How to reproduce
do #mine redstone_ore 256  - it doesnt mine all the redstone, misses parts of veins or turning around when they are at the redstone vein or going between 2 veins multiple times. This is worse on low tps servers such as constantium where baritone is often used with hacked clients. because i was on a low tps server at the time of descovery, i decided to test this on singleplayer to find it was missing a smaller amount of redstone in veins and sometimes going backwards and forwards breaking 1 redstone ore block from the vein each time, sometimes none. Also, if one of the veins it goes backwards and forwards from is in such a way that baritone digs straight down, it will dig straight down to it, mine one redstone ore and pillar back up and do it again after going by the other vein, wasting pickaxe durability

**Comment by leijurv** [comment]
Correct, it's because redstone_ore turns into lit_redstone_ore or something like that. Try `mine redstone_one lit_redstone_ore`

**Comment by xX-Denied-Xx** [comment]
ok

**Comment by xX-Denied-Xx** [comment]
> Correct, it's because redstone_ore turns into lit_redstone_ore or something like that. Try `mine redstone_one lit_redstone_ore`

works
