### ISSUE TITLE
short keyword for mine

### ISSUE THREAD

**Issue by NIKITAzed** [cabaletta/baritone#834]
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

add wood and ore to the mine command, for those times when you really don't care which wood you're getting, just need a lot of it

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

mostly for lazy people that don't want to list out every ore, or multiple wood types

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Maxalus** [comment]
it is good , it could be like : #mine Ores

**Comment by HellTimTM** [comment]
Yeah, also for shulkers it would be nice, having to always type in the color of each type is very anoying.

**Comment by IronException** [comment]
yea there could be something like a check for the input string that replaces "Ores" with every ores that are in the game. And the same for (list things I forget):
- (wood (planks + logs))
- planks
- logs
- wool
- (stoneTypes (with fortune it doesnt matter to mine stone or cobblestone))
- glass
- (obby (ender chests and obsidian))
...

**Comment by usereewrjrjeejr** [comment]
Useless tbh

**Comment by millennIumAMbiguity** [comment]
well you can just use `#mine iron_ore coal_ore redstone_ore diamond_ore gold_ore emerald_ore quartz_ore` but you will not get a balanced amount of resources; therefore is a short command for all ores useless.

but it is different with logs.
you can use `#mine oak_log spruce_log birch_log jungle_log acacia_log dark_oak_log` but it is troublesome if your house is made out of any of those materials. what we need is a command for collecting wood that does not belong to any building.

**Comment by clragon** [comment]
the #mine <every single block here> is annoying because you can't actually keep chaining them, there is a limit on how many you can mine at once.

I also think we don't need this, rather what we want is #709 which would allow is to to 

#mine \*log

**Comment by dominikaaaa** [comment]
This is now integrated, pretty much.
