### ISSUE TITLE
Is there a way to convert the cached chunks back into minecraft region files?

### ISSUE THREAD

**Issue by HellTimTM** [cabaletta/baritone#837]
## Is it possible to convert the Cached Chunks into Minecraft Region Files?
I was interested if it would be possible to convert the .bca files back to .mca Files.

**Comment by IronException** [comment]
In these cache files the world is not exactly saved like in a minecraft world. So a lot of information will be missing. Why not make a world download in the first place?

**Comment by StijnSimons** [comment]
[Have fun](https://github.com/cabaletta/baritone/tree/master/src/main/java/baritone/cache)
