### ISSUE TITLE
can't #goto chest

### ISSUE THREAD

**Issue by sirtomato999** [cabaletta/baritone#842]
## Some information
Operating system: win10 64bit
Java version: `OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)`
Minecraft version: 1.12.2
Baritone version: 1.2.8
Forge mods (if used): N/A

## Exception, error or logs
```[18:29:09] [pool-5-thread-30/INFO]: [STDOUT]: 970951 movements considered
[18:29:09] [pool-5-thread-30/INFO]: [STDOUT]: Open set size: 1396
[18:29:09] [pool-5-thread-30/INFO]: [STDOUT]: PathNode map size: 45536
[18:29:09] [pool-5-thread-30/INFO]: [STDOUT]: 242527 nodes per second
[18:29:09] [pool-5-thread-30/INFO]: [STDOUT]: Path goes for 151.64761785138597 blocks
[18:29:09] [main/INFO]: [CHAT] [Impact] allowPlace is on, and there are blocks in your inventory, but none on your hotbar!
```

## How to reproduce
load baritone/impact
`.b goto chest`
watch it not go to a chest, even if its right in front of you

**Comment by luedriver** [comment]
also for redstone_block, diamond_ore, furnace and chest from my experience

it would just path to nowhere 1000's of blocks away

I thought it had invert or something, that would make it go as far away from what I was telling it to goto

**Comment by S-B99** [comment]
Please provide the full log if this issue is still happening.

**Comment by joeyc002** [comment]
I could be standing 10 blocks away from a chest, and it will instead run off into some unknown block a long distance away. Happens for ender_chest too. This is on 1.18 and on 1.18.1 servers.

**Comment by wagyourtail** [comment]
> Please provide the full log if this issue is still happening.
