### ISSUE TITLE
Be able to run baritone headless

### ISSUE THREAD

**Issue by EmeraldSnorlax** [cabaletta/baritone#844]
## Describe your suggestion
It would allow you to run baritone standalone without a GUI, or a Minecraft window, but using console commands

## Settings
Just pass through arguments as normal (eg `baritone -setting "legitmine"`, `baritone -goto "420 69 -911"`)
Perhaps be able to join servers with `baritone -connect "ip"`

## Context
It will allow easy scripting, and allow you to easily automate many bots together without using a lot of computing resources because of having to draw a GUI, etc.

Perhaps it could also return useful command line output like `> Moved x blocks`, `> Mined desired block`, `> Inventory full` and so on

## Final checklist
- [ OwO ] I have not used any OwO's or UwU's in this issue.

**Comment by NotInTheBand** [comment]
plz

**Comment by mrphax0r** [comment]
This needs to be a thing. This would allow whole new possibilities, you could just feed a pi with a script that automatically mines, and you have basically a diamond generator.

**Comment by StijnSimons** [comment]
~~Real men delete LWJGL~~

**Comment by clragon** [comment]
probably hard to do, but for this to work, we'd first need #176

**Comment by aUniqueUser** [comment]
Sounds epic

**Comment by CamJW101** [comment]
This sounds easy to implement, but is actually an enormous amount of work from where baritone currently is. Unless you have the game running, you have to interact with the server through your own packets, using something like https://github.com/Steveice10/MCProtocolLib

I would love this feature, but it's understandable that the devs can't just throw something like this together.

**Comment by iBuyMountainDew** [comment]
@leijurv @ZeroMemes what's your take on this idea?

**Comment by dominikaaaa** [comment]
It's a neat idea but it would be hard to implement because of how much it relies on running mc features.

**Comment by StijnSimons** [comment]
You’d have to re-implement all of minecraft’s mechanics. Don’t think this is worth the time.

**Comment by dominikaaaa** [comment]
That's what I'm talking about. Baritone's original intent was to pathfind Minecraft, not to mass botnet Minecraft servers :p

While it's a really cool concept it would be too much work to implement. I think I'll close this as won't fix.

**Comment by nothub** [comment]
Maybe the work 3arthqu4ke has done could be helpful to provide a configuration to run headless: https://github.com/3arthqu4ke/HeadlessForge

**Comment by FloGo3308** [comment]
> Maybe the work 3arthqu4ke has done could be helpful to provide a configuration to run headless: https://github.com/3arthqu4ke/HeadlessForge

that would be cool, and it seems you wont have to do too much to get this to work

**Comment by EmeraldSnorlax** [comment]
why does this thread still get activity
i dont even play minecraft anymore
why are my notifications getting triggered for this repo

**Comment by FloGo3308** [comment]
> why does this thread still get activity
> i dont even play minecraft anymore
> why are my notifications getting triggered for this repo

lol

**Comment by StijnSimons** [comment]
loving the 2 years old issue notifications

**Comment by DereC4** [comment]
nice

**Comment by EmeraldSnorlax** [comment]
it costs you zero fucking dollars to not do that

**Comment by ehylo** [comment]
wtf is this how?? 

:fancytroll:

**Comment by DiaxManPl** [comment]
I found this as potential solution: https://github.com/nothub/headlessbot

**Comment by FloGo3308** [comment]
jesus man this thread is dead af why do i still receive email about it

**Comment by bddvlpr** [comment]
cunny

**Comment by lokzz** [comment]
ping

**Comment by bddvlpr** [comment]
ban this guy please

**Comment by DiaxManPl** [comment]
Jesus, it was 2 years since last message on this thread and 3 since this issue was closed with "wontfix". What do you mean by ping?
