### ISSUE TITLE
Baritone not responding

### ISSUE THREAD

**Issue by josephsmells** [cabaletta/baritone#849]
I dont know if its an issue with my computer, but up until a few minutes ago it was working fine, but suddenly it decided to stop responding to commands. I tried it with the 1.12.2 forge version, same results. I was wondering if there is a way to fix this? It literally just does nothing, as if I'm playing ordinary vanilla Minecraft. Yes, I have tried reinstalling it and resetting my computer multiple times, all attempts were futile.

**Comment by UltraBlackLinux** [comment]
Delete the Barirone folder to reset its settings

**Comment by dominikaaaa** [comment]
Closing as stale.
