### ISSUE TITLE
blocks blacklist

### ISSUE THREAD

**Issue by alexvermaning0** [cabaletta/baritone#850]
## Describe your suggestion
i want an command or something to let it stop mining other blocks while using .b mine Coal_ore i dont need it to mine other blocks because everything is at  eyesight but it keeps trying to break stone or rails. if there was an option to make a blacklist like .b mine Coal_ore -Rail -Stone

## Settings
disabled blocks
## Context
so you have more control what to mine and what not.
## Final checklist
- [? ] I have not used any OwO's or UwU's in this issue.

**Comment by Orinion** [comment]
there is "blocksToAvoidBreaking"

**Comment by alexvermaning0** [comment]
how do i use that?

**Comment by Orinion** [comment]
first set blocksToAvoidBreaking with a comma seperatet list so f. E.
.b blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,rail
then after it start the mine command

**Comment by AdolfRoxler** [comment]
Is there a hard blacklist? I want to autofarm amethyst without the stupid ass ai breaking it

**Comment by ZacSharp** [comment]
Yes, there is `blocksToDisallowBreaking`.

And in fact, that means this suggestion is already implemented.
