### ISSUE TITLE
remove the fucking cringe from this repo

### ISSUE THREAD

**Issue by leumasme** [cabaletta/baritone#851]
holy fuck it hurts

**Comment by leumasme** [comment]
![0001407](https://user-images.githubusercontent.com/29953391/63658355-46efd000-c7aa-11e9-8f83-c7804e8f8820.png)
![0001406](https://user-images.githubusercontent.com/29953391/63658359-48b99380-c7aa-11e9-9426-7b5dc1961672.png)
![0001405](https://user-images.githubusercontent.com/29953391/63658360-4a835700-c7aa-11e9-9374-9acba10c26a2.png)

**Comment by leijurv** [comment]
![219](https://user-images.githubusercontent.com/3837873/63659112-4f251c80-c764-11e9-9523-0bdfd0e95578.jpg)

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/63659118-881dbb00-c77d-11e9-9ba6-d3ff69393d67.png)

**Comment by StijnSimons** [comment]
imagine
