### ISSUE TITLE
Allow Baritone to use water buckets to ascend walls

### ISSUE THREAD

**Issue by kittenswolf** [cabaletta/baritone#855]
## Describe your suggestion
Allow Baritone to use water buckets to ascend walls, like this: https://www.reddit.com/r/Minecraft/comments/cvng2y/who_needs_ladders/

## Settings
A setting should be added that manages said behaviour.

## Context
This could be faster and cleaner than building a tower or mining.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Ekibunnel** [comment]
It would be very nice

**Comment by S-B99** [comment]
Duplicate of #811
