### ISSUE TITLE
Is there a way to delete 'DEATH' waypoints?

### ISSUE THREAD

**Issue by nbyrd** [cabaletta/baritone#856]
## What do you need help with?
Is there a way to delete 'DEATH' waypoints? (`#list death`)

`#delete DEATH` and variants do not seem to work.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
May i know why you're trying to delete that?

**Comment by nbyrd** [comment]
Just to clarify, I'm not looking to delete death coordinate tracking; I just want the ability to clean up stale waypoints that have been filed under the death-list.

**Comment by aimorris** [comment]
#wp delete DEATH

**Comment by ZacSharp** [comment]
With `#waypoints delete DEATH` you can only delete them one by one.
Use `#waypoints clear DEATH` to delete all of them at once.
