### ISSUE TITLE
Unlimited options for #mine 

### ISSUE THREAD

**Issue by clragon** [cabaletta/baritone#860]
## Some information
Operating system: Windows 10 - v1903
Java version: 1.8.0_211
Minecraft version: 1.13.2 with Impact 4.7
Baritone version: 1.3.4

## How to reproduce
- Use baritone
- Enter #mine command
- Give more than 5 blocks to mine
- Witness failure

With 5 blocks:
![85506331](https://user-images.githubusercontent.com/11785085/63802514-1c6d5680-c913-11e9-8483-51c33bb89906.png)
With 6 blocks:
![48555263](https://user-images.githubusercontent.com/11785085/63802517-1d9e8380-c913-11e9-9f29-9b94ee874777.png)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Ekibunnel** [comment]
Tested on 1.13.2 with Impact 4.7

![proof](https://i.imgur.com/b2z8WP3.png)

### This error is from the Impact client not baritone.
