### ISSUE TITLE
How to turn on Layer-by-Layer in build?

### ISSUE THREAD

**Issue by MicroPanda123** [cabaletta/baritone#862]
How to do it? Because i see many videos of baritone building layer-by-layer but when i use it (1.12.2) it just builds randomly and sometimes i need to stop and change position or break some blocks, because then it starts to break random blocks, replace them and again break them. So how to turn on Layer-by-Layer?

**Comment by leijurv** [comment]
look at the list of settings and documentation...

`buildinlayers`
