### ISSUE TITLE
[SOLVED] 1.14.2: Baritone freezes and crashes the game after mining any block 

### ISSUE THREAD

**Issue by BlueBlazeTech** [cabaletta/baritone#865]
## Some information
Operating system: Windows 10 Pro
Java version: 7.0
Minecraft version: 1.14.2
Baritone version: [Latest]- Run with Impact [latest]
Forge mods (if used): n/a

## Exception, error or logs
No log data was recorded. it states there was no issue.

## How to reproduce
I have absolutely no idea how i did this. although i did use the [.b mine] command

**Comment by enderman2s** [comment]
I don't believe there is a 1.14.2 version of Impact or Baritone only 1.14.4.

**Comment by BlueBlazeTech** [comment]
yup. that was the reason it wasn't working. i was unaware of the fact baritone wasn't compatible with 1.14.2, when i updated it to 1.14.4, it fixed the issue. thanks for letting me know!
