### ISSUE TITLE
Cannot "goto" saved locations

### ISSUE THREAD

**Issue by hexxone** [cabaletta/baritone#869]
## Some information
Operating system:
Java version: 1.8.0_221
Minecraft version: 1.14.4
Baritone version: (the one included in Impact 4.8.0-20190827-nightly)
Forge mods (if used): none

## Exception, error or logs
`§5[§dBaritone§5]§7 Saved user defined position BlockPos{x=-1229, y=90, z=-303} under name 'home'. Say 'goto home' to set goal, say 'list user' to list custom waypoints.`

`§5[§dBaritone§5]§7 None saved for tag HOME`

## How to reproduce
1. use #save home
2. use #goto home

**Comment by Orinion** [comment]
Its a conflict with the home tag. The tags are 'home', 'user', 'death' and 'bed', the waypoint gets saved in 'user' but when using goto baritone looks in the tag 'home'. Same happens if you do "save bed" etc.

**Comment by Hexxonite** [comment]
Alright, thanks for clarification and fix :)
