### ISSUE TITLE
Add a setting to disable coords in client side of the chat

### ISSUE THREAD

**Issue by bambo1510** [cabaletta/baritone#872]
## Describe your suggestion
For example when typing in coords, in the chat you see the coords you put in. For recording purposes, its easy to block whats being directly typed. However, after typing the coords, baritone tells you exactly where its going, which there should be a setting to disable that so it doesn't stack up in the chat history, so when it does making it extremely hard to cover the coords. If there is already feature like this please inform me. Otherwise please add this in.

## Settings
Baritone put coords in chat, True to see where its leading you, False if baritone doesn't put the coords in the chat.

## Context
To make censoring coords more easier for recording on servers that leaking coordinates may be problematic. This way we don't have to blur out half the screen every time we open the chat or go to sleep.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment]
I could add this feature to my branch. You can turn off echoCommands to not echo the command to chat and then the goals will censor coordinates if enabled. Does that sound good?

I can also open a PR right now that adds coords censoring to this repo, so you can use it right now.

**Comment by LoganDark** [comment]
Fixed by #890 being merged @leijurv please close
