### ISSUE TITLE
Disable autotool / silk touch glass blocks

### ISSUE THREAD

**Issue by Koozu1** [cabaletta/baritone#883]
I'd like a feature to disable the autotool function when mining /clearing an area. Mainly i'd need to get the glass blocks with a silk touch pickaxe when clearing /mining. This could be done with a simple setting like #autotool true/false or even something customizable.

**Comment by LoganDark** [comment]
Or a setting can be provided that uses a silk touch tool instead of your hand. I can do this right now

**Comment by Koozu1** [comment]
Great, me and many other players I know are really looking forward to getting this feature. Add this when you have time. Thank you!

**Comment by LoganDark** [comment]
@Koozu1 #894
