### ISSUE TITLE
I just want to dig podzol

### ISSUE THREAD

**Issue by justprogramthat** [cabaletta/baritone#886]
## What do you need help with?
I am using 1.12.2 forge
when I try #mine podzol it says podzol isn't a valid block name, when I try #mine dirt it mine dirt it not only mine podzol but regular dirt as well
Is there a way to only mine podzol?

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Orinion** [comment]
no, not in 1.12.2 an below because podzol is still named dirt

**Comment by LoganDark** [comment]
[my fork](https://github.com/LoganDark/baritone) supports specifying data values, podzol is `dirt:2`

The fork isn't done yet, but it's coming along.

**Comment by LoganDark** [comment]
@justprogramthat if you'd like I can give you a Forge build of the fork to use. It doesn't have many commands like waypoints, but it's coming along nicely.

**Comment by justprogramthat** [comment]
that be cool thanks

**Comment by LoganDark** [comment]
@justprogramthat Here you go. It has all commands except for:

- list/get/show (waypoints)
- save (waypoints)
- delete (waypoints)
- goto (also waypoints)
- spawn/bed (waypoints)
- sethome (waypoints)
- home (waypoints)

basically waypoints. But all those features are coming soon, I promise.

[baritone-standalone-forge-1.2.9.jar.zip](https://github.com/cabaletta/baritone/files/3563672/baritone-standalone-forge-1.2.9.jar.zip)

**Comment by justprogramthat** [comment]
Nice thanks!
But it still unable to mine ice, guess that's just the bug of the original build

**Comment by LoganDark** [comment]
> unable to mine ice

Ice on water?

**Comment by justprogramthat** [comment]
nope just ice

**Comment by LoganDark** [comment]
I'll check it out
