### ISSUE TITLE
How to open baritone's gui?

### ISSUE THREAD

**Issue by VirxEC** [cabaletta/baritone#887]
## What do you need help with?
How do I open Baritone's GUI? I've seen in the source code some code for a GUI, but I can't figure out how to use it.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by enderman2s** [comment]
There is no Baritone GUI it is purely command based.

**Comment by StijnSimons** [comment]
You’re probably talking about `#click` if not; use Impact.

**Comment by VirxEC** [comment]
I've seen code on this GitHub (written by Impact, yes) but it's for a Baritone GUI. https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/utils/GuiClick.java

**Comment by sneznaj** [comment]
the gui could just be a list of all commands with a search field above. anything is better then commmand line

**Comment by sneznaj** [comment]
the commands do not do anything. impact is not available for latest version of minecraft.
