### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Trx21** [cabaletta/baritone#888]
Hi!, i just wanted to ask if there is a Baritone Discord server?

**Comment by VirxEC** [comment]
No, but Impact does, and it has a Baritone channel. Impact invite: https://discord.gg/uEVPXGc

**Comment by Colorized** [comment]
Impact discord is p toxic tho

**Comment by ZacSharp** [comment]
Baritone now has a discord server: http://discord.gg/s6fRBAUpmr

**Comment by Cohejh** [comment]
This invite is invalid

**Comment by ehylo** [comment]
I have no idea why you say that as it is still valid

**Comment by Cohejh** [comment]
Oh, i am not on the discord so i didn't know that, is there any current discord? or are you using guilded?

**Comment by ehylo** [comment]
huh? yes there is a current discord, as said
> as it is still valid

just use the link above...
