### ISSUE TITLE
Path does not load but it does on radar

### ISSUE THREAD

**Issue by 4j0x** [cabaletta/baritone#892]
## Some information
Operating system:windows 10
Java version:na
Minecraft version:1.12.2/impact
Baritone version: 1.2.6
Forge mods (if used): none

## How to reproduce
if i do goto no visible path shows just shows on radar

**Comment by LoganDark** [comment]
what is radar and what do you mean "no visible path shows"? do you have renderPath on?

**Comment by VirxEC** [comment]
@LoganDark he's talking about Impact's radar. @4j0x this is an Impact issue, not a Baritone issue. Please report this on https://github.com/ImpactDevelopment/ImpactIssues/issues

**Comment by leijurv** [comment]
`.b renderPath`
