### ISSUE TITLE
Want to use parkourascend but it's not on latest 1.12.2 impact

### ISSUE THREAD

**Issue by ThatOneJose95** [cabaletta/baritone#897]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Want to use the parkourascend but it doesn't seem to be on the latest 1.12 impact. Where else do I get it?
## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Graicc** [comment]
If you don't need impact you can install the latest version from the [releases]()

**Comment by ThatOneJose95** [comment]
I don't mind it being in impact, it's just the latest 1.12 impact doesn't have parkourascend.
I tried to install 1.2.9 by putting all of the artifacts, one by one. Tried with standalone, then removed and tried with standalone forge. Then, api forge. So on and no 1.2.9 artifact worked with my forge.

**Comment by ThatOneJose95** [comment]
And building is not an option, got no experience with java whatsoever

**Comment by Graicc** [comment]
What forge update (1.12 1.13 etc) are you using? Putting the latest standalone forge in the latest 1.12 forge worked for me.

**Comment by ThatOneJose95** [comment]
Latest dev on forge, can you please tell me which forge you are using @Graicc ?

**Comment by Graicc** [comment]
[Latest 1.12 Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.html) and [baritone standalone forge 1.2.9](https://github.com/cabaletta/baritone/releases)

**Comment by ThatOneJose95** [comment]
@Graicc Oh, so no 1.12.2? Sad :(

**Comment by ThatOneJose95** [comment]
Update: Installed latest 1.12 forge and 1.2.9. Mods: What comes with forge and Baritone 1.2.9 standalone forge.

When I start it crashes. Here's a log:
[fml-client-latest.log](https://github.com/cabaletta/baritone/files/3576992/fml-client-latest.log)

**Comment by ThatOneJose95** [comment]
Made new issue for the crash
