### ISSUE TITLE
It crashes in the first loading screen!

### ISSUE THREAD

**Issue by Xx4ndr3yxX** [cabaletta/baritone#899]
It crashes in the first loading screen!
## Some information
Operating system:Windows 10
Java version: 8
Minecraft version:1.12.2
Baritone version:0.6.0-4.7.3
Forge mods (if [used): [https://imgur.com/a/AyAx3IZ](url)

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.3.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/2/19 11:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = minecraft:double_stone_slab[seamless=false,variant=quartz]
    Block = minecraft:double_stone_slab
    Stack = 1xtile.stoneSlab@7
    varying-properties: {
        PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} = null
    }
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:336)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.block.Block.handler$isFullBlock$zbj000(Block.java:3202)
	at net.minecraft.block.Block.func_149730_j(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185913_b(BlockStateContainer.java:307)
	at net.minecraft.block.Block.isSideSolid(Block.java:1071)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:519)
	at buildcraft.silicon.plug.FacadeBlockStateInfo.<init>(FacadeBlockStateInfo.java:41)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:301)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 644999616 bytes (615 MB) / 1828139008 bytes (1743 MB) up to 6928203776 bytes (6607 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx6619M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 86 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHI  | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHI  | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                      | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | creativecoredummy          | 1.0.0                    | minecraft.jar                                   | None                                     |
	| LCHI  | openmodscore               | 0.12.2                   | minecraft.jar                                   | None                                     |
	| LCHI  | actuallyadditions          | 1.12.2-r150              | ActuallyAdditions-1.12.2-r150.jar               | None                                     |
	| LCHI  | waila                      | 1.8.26                   | Hwyla-Mod-1.12.2.jar                            | None                                     |
	| LCHI  | bdsandm                    | 0.0.22                   | Barrels-Drums-Storage-More-Mod-1.12.2.jar       | None                                     |
	| LCHI  | betterbuilderswands        | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHI  | biomesoplenty              | 7.0.1.2427               | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar   | None                                     |
	| LCHI  | guideapi                   | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
	| LCHI  | bloodmagic                 | 1.12.2-2.4.1-103         | BloodMagic-1.12.2-2.4.1-103.jar                 | None                                     |
	| LCHI  | buildcraftlib              | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCHI  | buildcraftcore             | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCHI  | buildcraftbuilders         | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCHI  | buildcrafttransport        | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCHE  | buildcraftsilicon          | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftcompat           | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftenergy           | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftfactory          | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftrobotics         | 7.99.24.1                | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | carryon                    | 1.12.2                   | CarryOn+MC1.12.2+v1.12.2.jar                    | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | ctm                        | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| LCH   | chisel                     | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| LCH   | codechickenlib             | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | craftablesaddles           | 1.3                      | Craftable-Saddles-Mod-1.12.2.jar                | None                                     |
	| LCH   | creativecore               | 1.9.9                    | CreativeCore-1.12.2.jar                         | None                                     |
	| LCH   | cucumber                   | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| LCH   | jei                        | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                       | None                                     |
	| LCH   | mantle                     | 1.12-1.3.3.55            | Mantle-Mod-1.12.2.jar                           | None                                     |
	| LCH   | tconstruct                 | 1.12.2-2.12.0.115        | Tinkers-Construct-Mod-1.12.2.jar                | None                                     |
	| LCH   | deepmoblearning            | 1.12.2-2.5.2             | deepmoblearning-1.12.2-2.5.2-universal.jar      | None                                     |
	| LCH   | deepmoblearningbm          | 1.12.2-1.0.1             | deepmoblearningbm-1.12.2-1.0.1-universal.jar    | None                                     |
	| LCH   | trzlib                     | 3.0.10                   | TRZLib-1.12.2.jar                               | None                                     |
	| LCH   | dimensionalpocketsii       | 2.0.14-beta              | Dimensional-Pockets-2-Mod-1.12.2.jar            | None                                     |
	| LCH   | doggytalents               | 1.15.0.5                 | Doggy-Talents-Mod-1.12.2.jar                    | None                                     |
	| LCH   | dldungeonsjdg              | 1.11.2                   | Doomlike-Dungeons-Mod-1.12.2.jar                | None                                     |
	| LCH   | endercompass               | 1.2.6.2                  | Ender-Compass-Mod-1.12.2.jar                    | None                                     |
	| LCH   | spawnermod                 | 1.0-1.12.2               | Enhanced-Mob-Spawners-Mod-1.12.2.jar            | None                                     |
	| LCH   | quickleafdecay             | 1.2.4                    | Fast-Leave-Decay-Mod-1.12.2.jar                 | None                                     |
	| LCH   | fertilization              | 1.0.7                    | Fertilization-Mod-1.12.2.jar                    | None                                     |
	| LCH   | findme                     | 1.0                      | FindMe-Mod-1.12.2.jar                           | None                                     |
	| LCH   | forgemultipartcbe          | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe              | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCH   | minecraftmultipartcbe      | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCH   | furnaceoverhaul            | 2.2.0                    | Furnace-Overhaul-Mod-1.12.2.jar                 | None                                     |
	| LCH   | horsetweaks                | 1.0.5                    | Horse-Tweaks-Mod-1.12.2.jar                     | None                                     |
	| LCH   | ichunutil                  | 7.2.1                    | iChun-Util-Mod-1.12.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | ic2                        | 2.8.186-ex112            | Industrial-Craft-2-Mod-Experimental-1.12.2.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | forgelin                   | 1.8.3                    | Shadowfacts-Forgelin-1.12.2.jar                 | None                                     |
	| LCH   | tesla                      | 1.0.63                   | Tesla-API-1.12.2.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | teslacorelib               | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing        | 1.12.2-1.12.2            | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| LCH   | inventorytweaks            | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                  | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                      | None                                     |
	| LCH   | journeymap                 | 1.12.2-5.5.5b7           | JourneyMap-Mod-1.12.2-Unlimited.jar             | None                                     |
	| LCH   | levelup2                   | ${version}               | Level-Up-Mod-1.12.2.jar                         | None                                     |
	| LCH   | lucky                      | 7.6.0                    | luckyblock-1.12.2-7.6.0.zip                     | None                                     |
	| LCH   | mclib                      | 1.0.3                    | mclib-1.0.3-1.12.2.jar                          | None                                     |
	| LCH   | metamorph                  | 1.1.7                    | MetaMorph-Mod-1.12.2.jar                        | None                                     |
	| LCH   | openmods                   | 0.12.2                   | OpenModsLib-1.12.2.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | oreexcavation              | 1.4.140                  | OreExcavation-1.4.140.jar                       | None                                     |
	| LCH   | petbat                     | 1.4.8                    | Pet-Bat-Mod-1.12.2.jar                          | None                                     |
	| LCH   | placebo                    | 1.6.0                    | Placebo-1.12.2.jar                              | None                                     |
	| LCH   | pcb                        | 1.5.0                    | Portable-Craft-Bench-Mod-1.12.2.jar             | None                                     |
	| LCH   | projecte                   | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                     | None                                     |
	| LCH   | projectex                  | 1.2.0.36                 | Project-EX-Mod-1.12.2.jar                       | None                                     |
	| LCH   | rwg                        | 1.0.1                    | Realistic-World-Generation-Mod-1.12.2.jar       | None                                     |
	| LCH   | llibrary                   | 1.7.18                   | LLibrary-1.12.2.jar                             | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | dragonmounts               | 1.12.2-1.5.8             | Realm-of-The-Dragons-Mod-1.12.2.jar             | None                                     |
	| LCH   | ruins                      | 17.2                     | Ruins-Mod-1.12.2.jar                            | None                                     |
	| LCH   | sonarcore                  | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                  | None                                     |
	| LCH   | spartanshields             | 1.5.4                    | Spartan-Shields-Mod-1.12.2.jar                  | None                                     |
	| LCH   | subcommonlib               | 1.2.0.1                  | SubLib-1.12.2.jar                               | None                                     |
	| LCH   | tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769 | Tinkers-Tool-Leveling-Mod-1.12.2.jar            | None                                     |
	| LCH   | tp                         | 3.2.34                   | tinyprogressions-1.12.2-3.3.34-Release.jar      | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.3                      | tlskincape_1.12.2-1.3.jar                       | None                                     |
	| LCH   | translocators              | 2.5.2.81                 | Translocators-1.12.2-2.5.2.81-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | uteamcore                  | 2.2.4.107                | u_team_core-1.12.2-2.2.4.107.jar                | None                                     |
	| LCH   | usefulbackpacks            | 1.5.0.23                 | Useful-Backpacks-Mod-1.12.2.jar                 | None                                     |
	| LCH   | witherskelefix             | 2.6.3                    | Wither-Skeleton-Tweaks-Mod-1.12.2.jar           | None                                     |
	| LCH   | zerocore                   | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| LCH   | mysticallib                | 1.12.2-1.3.5             | mysticallib-1.12.2-1.3.5.jar                    | None                                     |
	| LCH   | teslacorelib_registries    | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |
	| UD    | mclib_core                 | 1.0.3                    | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  openmods.core.OpenModsClassTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.3.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 530'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
(Add impact.jar and thats it, crash.)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Xx4ndr3yxX** [comment]
If I don't use any mod, it works but I don't know with what mod is in conflict!

**Comment by enderman2s** [comment]
Test the mods then.

**Comment by Xx4ndr3yxX** [comment]
they are so many, i was thinking if someone can read the crash report and then tell witch one is the one that is in conflict!

**Comment by Xx4ndr3yxX** [comment]
bcz i dont understand anything in that crash report!

**Comment by leijurv** [comment]
<img width="656" alt="Screen Shot 2019-09-02 at 2 34 01 PM" src="https://user-images.githubusercontent.com/3837873/64133942-b8bdb000-cd8e-11e9-9d4b-a9baba095b57.png">
god oh jeez wow this is really hard to understand oh jeez its all CODED LANGUAGE oh fuck if only there were some perfectly readable text explaining what caused the issue wouldnt that be just grand but oh well there isn't anything like that

**Comment by Xx4ndr3yxX** [comment]
ty so much man yep that was my fault, thank you for helping me!

**Comment by D4rK3sTsH4d0W** [comment]
Did you ever find a fix? I need to have buildcraft silicon to connect to my server, but it crashes with it. i want to use impact on my server, but it just keeps crashing.
