### ISSUE TITLE
Can we get a integrated chat command on the event that baritone has a full inv such as /sell all /ci or it just #pauses baritone

### ISSUE THREAD

**Issue by bokja** [cabaletta/baritone#902]
## Describe your suggestion
Chat commands on full inventory?

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Final checklist
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Duplicate of #881
