### ISSUE TITLE
Baritone does not mine glowing redstone.

### ISSUE THREAD

**Issue by DasAlteUpdate** [cabaletta/baritone#903]
## Some information
Operating system: Windows 10 Pro
Java version: 1.8.0_51 64bit
Minecraft version: 1.12.2 (Impact 4.3.7)
Baritone version: 1.2.8
Forge mods (if used): 

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

#mine redstone_ore and see what happens.
If one orders baritone to mine Redstone, only non-luminous redstone will be mined.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Asparii** [comment]
Was able to replicate this.

It looks like the bot doesn't consider glowing redstone ore to be redstone ore. It will attempt to mine redstone ore, but once it becomes illuminated it will stop and fail to register it.

Attached image has debug on, started a few blocks away from the redstone, told it to mine it, it moved closer then stopped once it was illuminated.
![8dd701be0779f310a2d9e518fec30d2b](https://user-images.githubusercontent.com/36485946/64435651-345c8b80-d106-11e9-849d-655f1e536101.png)

**Comment by Orinion** [comment]
its because the ore changes to "lit_redstone_ore"
so instead try "#mine redstone_ore lit_redstone_ore"

**Comment by Orinion** [comment]
Thats because in 1.12.2  lit_redstone_ore still existed.
try 

> #mine redstone_ore lit_redstone_ore
