### ISSUE TITLE
(Redo) Website to make easier for more generic users

### ISSUE THREAD

**Issue by Huskydog9988** [cabaletta/baritone#907]
## Describe your suggestion
This website would allow the user to download the latest versions as well as older versions of Baritone in a very user friendly fashion. (I realize there is a website already for the documentation and this could very well use that.)

## Settings
Allow the option for light/dark theme because I like my eyes not being burned.

## Context
I feel this addition would make baritone more widely appealing to a wider community in Minecraft especially is the CSS is done real nice. This website would also allow for in my option, #436 to be expanded upon. It would be much easier to buy these exciting features being move over and would build confidence in the end user that isn't totally a scam.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
https://github.com/cabaletta/baritone/releases

**Comment by Huskydog9988** [comment]
Ik that page exists

**Comment by Googlelt** [comment]
if they cant figure out how to use github they shouldnt be using the bot tbh

**Comment by enderman2s** [comment]
Too true

**Comment by olibols** [comment]
Just download with impact installer, its easy enough as it is without adding more problems lol.

**Comment by Huskydog9988** [comment]
Guess this is being throw out so I just gonna close this.
