### ISSUE TITLE
Random 	#rightClickSpeed

### ISSUE THREAD

**Issue by bokja** [cabaletta/baritone#908]
## Describe your suggestion
So pretty sure some anticheat out there is catching onto baritones constant click speed. I would be lovely if we can add a
#rightclickRandom true/false
Which randomises the clickspeed with a few clicks appart

## Settings
#rightclickRandom true/false
#rightclickRandomOffset 2 clicks off the targetted clicks per tick

## Context
It would make it harder baritone a bit more unpredictable in its patterns. Which i hope would help against some anticheats.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Which anticheat?

**Comment by SIGSTACKFAULT** [comment]
It's a hypothetical situation. It might have happened already. It might not.

**Comment by 0-x-2-2** [comment]
Adding randomness for breaking blocks would make it more detectable then just holding the mouse down.

**Comment by SIGSTACKFAULT** [comment]
@0-x-2-2 this is for placing blocks, not breaking.

**Comment by 0-x-2-2** [comment]
> @0-x-2-2 this is for placing blocks, not breaking.

Placing is the same thing

**Comment by bokja** [comment]
> > @0-x-2-2 this is for placing blocks, not breaking.
> 
> Placing is the same thing

Its very specificly RIGHTCLICK speed. So time between Right Clicks. Mining is a left click
