### ISSUE TITLE
building schematics gives me 0 fps

### ISSUE THREAD

**Issue by SixwFive** [cabaletta/baritone#912]
## Some information
Operating system: pc
Java version: Newest 
Minecraft version: 1.12.2
Baritone version: 4.7.3
Forge mods (if used): none

ok so my minecraft is being gay. So when i try to build somthing it works but gives me 0 fps

and i have a fine pc
 gtx 1070
 i7 87000k

So any suggestions

**Comment by BlueBlazeTech** [comment]
I know this is a dumb question. but could the problem possibly be a driver issue?

**Comment by jonnyawsom3** [comment]
_saying operating system: pc is just low effort_ and 4.7.3 is the latest version of impact, not baritone

**Comment by CDAGaming** [comment]
GTX 1060 with i7-8750H, no signs of this issue occurring, though the game might slow down if you give it a giant schematic to work with, but unknown if thats the case here.

**Comment by S-B99** [comment]
This is definitely a driver issue. What driver version are you running, and what operating system?

**Comment by S-B99** [comment]
I'll close this until it gets a response, if the issue is still happening, as this was opened like 6 months ago.
