### ISSUE TITLE
#build automation improvement

### ISSUE THREAD

**Issue by Asparii** [cabaletta/baritone#913]
## Describe your suggestion
Allow for Baritone to pull blocks from your inventory when building schematics, or allow a toggle to do so.

## Settings
allowInventoryBlockPlace
While building using schematics allow blocks from inventory to be taken and used when none else are available in the hotbar.

## Context
This'd make schematic building a lot more automated, 
Often when using schematics to build Baritone will run out of resources and wait for you to manually move the blocks from your inventory to your hotbar, a feature to do this automatically would be neat.

I understand parkour has a requirement for items to be in the hotbar and refuses to use any from the inventory which looks like a design choice, so my suggestion pertains specifically towards schematics.

## Final checklist
- [UwU~ ] I have not used any OwO's or UwU's in this issue.

**Comment by Shy2Soul** [comment]
I might be wrong, but isn't that "#allowInventory"?

**Comment by Asparii** [comment]
I couldn’t find any documentation on that, but I may have just missed it.

**Comment by Asparii** [comment]
Just checked, you're right.
It just doesn't seem to be in the usage.
