### ISSUE TITLE
Baritone won't jump

### ISSUE THREAD

**Issue by stevenewald** [cabaletta/baritone#914]
I've recently downloaded Baritone but when I do @mine diamond_ore or literally any other commend, it refuses to jump. I've checked some of the settings like allowparkour (which are all set to true), and I haven't changed anything, but baritone will not jump ingame. Anything I can try to help fix this? Thanks!

**Comment by leijurv** [comment]
it's assumeStep

**Comment by stevenewald** [comment]
wow, that was fast. thanks
