### ISSUE TITLE
Avast stopped me from downloading baritone

### ISSUE THREAD

**Issue by FaizTDC** [cabaletta/baritone#916]
Here's an attachment of it

![Capture](https://user-images.githubusercontent.com/54181680/64470572-e41e1180-d177-11e9-8ab6-1a3307a07fa4.PNG) 

Can you explain about this?

**Comment by leijurv** [comment]
nope, dont care

**Comment by FaizTDC** [comment]
OK...

**Comment by 0-x-2-2** [comment]
vo co backdoor
