### ISSUE TITLE
Crashed with latest 1.12 forge and 1.2.9 baritone standalone forge.

### ISSUE THREAD

**Issue by ThatOneJose95** [cabaletta/baritone#920]
## Some information
Operating system: Windows 10
Java version: "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
Minecraft version: 1.12, latest forge
Baritone version: 1.2.9, latest release at the moment.
Forge mods (if used): Baritone, fresh forge install.

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).
https://github.com/cabaletta/baritone/files/3576992/fml-client-latest.log
## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Start up the game. The game will crash and you won't be able to even see the mojang or mc app pop up, it crashes a few seconds after clicking the launcher button.
## Final checklist
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and how to reproduce the issue.
- [ ] I have included my version and what baritone version I am using

**Comment by 0-x-2-2** [comment]
1.12 is not supported use 1.12.2

**Comment by ThatOneJose95** [comment]
Sorry. Got told by someone it was 1.12
