### ISSUE TITLE
Baritone not moving

### ISSUE THREAD

**Issue by UnknownCoding** [cabaletta/baritone#924]
## Some information
Operating system: Windows 10
Java version: 1.8.0_51
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): WWE, Real-time translation mod, Advanced Creative Tab 2, Better Placement, Better Sprinting, ForgeHax, Kami, LunatriusCore, Mouse Tweaks, Schematica, Smooth Scrolling Everywhere

## Exception, error or logs
None

## How to reproduce
When i type #goto or any other comands my client starts showing where it will go but never starts moving, also when i install impact to get baritone that way it does the same exact thing

**Comment by leijurv** [comment]
What are your `#modified` settings? Does this happen without all those mods, but still using baritone standalone in forge?

**Comment by ephility** [comment]
do #path to start moving.

**Comment by UnknownCoding** [comment]
https://i.imgur.com/rZXvLp0.png happens with bots Impact, and standalone, and all of those mods are a requirement for me.

**Comment by 0-x-2-2** [comment]
Remove WWE, ForgeHax, and Kami and try again.

**Comment by leijurv** [comment]
He said it was still an issue with just baritone standalone

What's your forge version? Any Mixin errors on launch?

**Comment by 0-x-2-2** [comment]
> He said it was still an issue with just baritone standalone
> 
> What's your forge version? Any Mixin errors on launch?

He means it happens with Impact + Baritone and Baritone with all of those mods/clients afaik.

**Comment by 0-x-2-2** [comment]
Closed due to inactivity. Just reply if you want the issue opened again.

**Comment by scorbett123** [comment]
Remove sodium, it is incompatible.

**Comment by Mochi-09** [comment]
I am also having this issue

**Comment by l1ving** [comment]
ok

**Comment by Mochi-09** [comment]
When I do .b mine diamond_ore (or any other baritone command) it shows the route but doesn't take me to the destination. For some reason whenever I am within 1 block of the thing baritone wants to mine it will mine it then stop.

**Comment by l1ving** [comment]
cool

**Comment by l1ving** [comment]
this issue is closed and you've filled in like, none of the issue templates

**Comment by Mochi-09** [comment]
Operating system: Windows 10
Java version: 1.16.5 Inertia fabric 
Minecraft version: 1.16.5
Baritone version: idk
Forge mods (if used): none

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)

**Comment by Mochi-09** [comment]
Ok I will do a bug report

**Comment by a-couple-objects** [comment]
> Remove sodium, it is incompatible.

works with meteor and sodium, and i can't remove sodium without getting under 5 fps on average

**Comment by scorbett123** [comment]
Some versions have a sodium fix, others don't. This comment was made before any sodium fix was available.

**Comment by jakeyjr** [comment]
im having the same problem
