### ISSUE TITLE
Looking for Chests, but how can I stop from walking to the closest nearby?

### ISSUE THREAD

**Issue by LethalDumpster** [cabaletta/baritone#925]
So basically, Im trying to find chests in mineshafts. But '#goto chest' ends up dragging me to chests ive already opened, or ones in my house/setup spots. Is there a way to just see all the chests within render distance, and I pick which to go to? If not, can I just see all the chests, and I walk manually? Or something???

**Comment by enderman2s** [comment]
If you wanna see where all the chests are and if you are using impact just turn on storage ESP

**Comment by LethalDumpster** [comment]
No thankyou. Im not using impact, and im not interested in using any fully fledged cheats. Honestly Baritone alone with optionally seeing things before walking, would be nice. That doesnt happen to exist does it?

**Comment by enderman2s** [comment]
Don't believe so.

**Comment by leijurv** [comment]
`Im not using impact, and im not interested in using any fully fledged cheats`

wow. big brain time.

"i want baritone to cheat for me, because i've convinced myself baritone is a cheat. i don't care that this is a feature on cheat clients, i won't install one because i don't cheat. but what i want is on cheat clients. but i'm not cheating and don't want to."

**Comment by LethalDumpster** [comment]
Never in the world would I ever claim baritones not a cheat. I said I dont want a fully fledged one. I only need enough to do what I want. No more, no less. Why is administration here so toxic? Ive seen lots of other posts here for all kinds of different things, with all these really dick-ish replies, and closing. Is it just a github thing? Does it come with the territory?

**Comment by LeafHacker** [comment]
Caching which chests have been opened and allowing to to select between fresh and opened chests would be a valid feature request imo

As for the hostile response, probably a combination of asking a question on an issue tracker and leijurv being in a bad mood

**Comment by LordMZTE** [comment]
this is the funniest thing i ever saw on github xD

**Comment by leijurv** [comment]
That would be closer to a valid feature request leaf, but what he asked for was `Is there a way to just see all the chests within render distance, and I pick which to go to? If not, can I just see all the chests, and I walk manually?`. Someone gave a solution (this is literally storage esp) and he discarded it out of what appeared to be some kind of moral ground lmfao. At this point I would have closed the issue anyway (not adding storage esp to baritone, someone gave him a solution so no need to keep it open) but I did indeed snarkily clarify that both are cheats and he's being kinda inconsistent

**Comment by leijurv** [comment]
Freecam + storage esp with `come` and `click` is exactly what you want, there's your answer. Never adding either of those to baritone, so you can take it or leave it lol

**Comment by LethalDumpster** [comment]
I apologize for not being one to come up with the best ideas. Other threads might elaborate and refine the main idea. The second half of what I asked for, was left there incase someone could drop me a small temp change to the code just enough to act as a minor solution. Which has happened before. "Caching which chests have been opened and allowing to select between fresh and opened chests" is most certainly what id prefer to have.

Im just a fan of only installing what I need. I dont need all of impact. So what do I need? To cut out the boring resource/loot collecting parts but still playing survival. Were all complicated. Just trying to play minecraft my way.(and I dont do pvp) So just freecam + storage esp might work for now. Thanks. Ill look into them.
