### ISSUE TITLE
Multiple suggestions to improve Baritone(it is probably too much but if possible make some of this)

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#927]
## Describe your suggestion
~Auto food gather[Killing Animals and gathering food getting potatoes/carrots if nearby, (if possible to put food in a furnace and cook) also to gather food automatically when pathing long distances so it doesn't die this should be priority as it would die on hard difficulty, could use recipes for a furnace in latest versions but IDK about 1.12.2]

~Auto Crafting [If there is no gear(pickaxe, shovel, axe, armor, shield, etc)in inventory it should be able to craft one, I believe it can use crafting recipes in newer versions but not so sure for 1.12.2]

~Player avoidance(useful even when AFK something like a guard mode when in one place to walk away from a player preferably to go out of render distance or when pathfinding if possible to walk further from players or to walk outside their render distance)

~PVP/PVE abilities[when attacked should be capable of defending itself or at least run away this should be prioritized over mining, gathering or going to goal]

~Using shield or blocks for defense(Useful when in combat, running away or if there is TNT/Creeper about to explode)

~Auto Heal(Use potions/gapple to heal)

~Stay Alive(As said before) Baritones priority should be keeping itself alive

~Big problem with auto mine(It takes super risky paths to get to ores especially with lava around it does not calculate lava's ability to flow and mines right beside it which kills him)

~For fixing problem above (make it calculate if it can place water anywhere not to lose it but to extinguish itself and to get away from it by blocking source  if drops in a pool of lava please make it build blow itself to escape if possible of course)

~PIckup items priority over mining

~If integrated into a client should be able to turn on hacks(stupid I know but on anarchy, you would want it to know when to use speed hacks or when to use kill aura and speed to get away)

~If anticheat is known to recalibrate and bypass it or player should have the ability to change the rotation of the head and make more legit looking mines as I suggested before(useful when staff is watching but you're AFK)

~Important for parkour(I didn't see the ability of diagonal ascend so please make it)

~Do not engage if deadly(There are cheats that can see the sword and armor of person and its enchants) so if a person is too strong AI should not engage in PVP it also should not fall from a hight that can kill it.

~Should be able to create bots with cracked/premium alts (Probably use alt dispenser site or get alts from txt file given)

## Settings
~Auto Food Gather(Togglable, how much of something to gather and if it should cook it)

~Auto Crafting(Toggleable, What gear it should and what it should not craft, should divide gear in thair materials so lather, iron, gold, diamond)

~Player avoidance(Togglable, distance to avoid, guard ability if AFK in one place to walk away from the player if a player comes too close)

~PVP/PVE abilities(Toggleable, option to change between fight and run and to make it run at low HP)

~Using shield or blocks for defense(Togglable, what to prefer for example it should use shield if it won't break and blocks if has some/prefer glass when an explosion is a thing defending from)

~Auto Heal(Togglable, what to use gapples or potions/switch between both and prefer one that is batter)

~Stay Alive(Toggleable)

~Lava avoidance/Fire Resistance usage(Togglable, distance to avoid, when to use Fire Resistance)

~Cheat mode (Togglable, what cheats to use)

~Diagonal ascend(Togglable)

~Do not engage if deadly(Togglable, to take care of either Player avoidance or fall damage/ take care of both)

## Context
These things would allow the player to forget about it and go do other things and still get items or get to the position desired/Avoid players when AFK without fear of being killed.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ActuallyGod** [comment]
I do think both defending, and staying alive would need to be the highest priorities before enhancing anything else

**Comment by mrphax0r** [comment]
I agree with ActuallyGod, there should be a paranoid mode maybe?

**Comment by Hackerokuz** [comment]
That is really good name for thi, thay should name it ParanoidMode.

**Comment by jonnyawsom3** [comment]
most of these features, if implemented, would make baritone even more viable standalone (without impact)

**Comment by Hackerokuz** [comment]
@jonnyawsom3 no it doesn't eat food on it's own but I think people already suggested that to be added, also as you probably already know, that is a goal (making baritone an ai fully capable of playing minecraft relatively well on it's own without any client or human help) (well at least that is the impression I have from reading the description and watching videos about baritone)

**Comment by jonnyawsom3** [comment]
@Hackerokuz i thought not, and while i do already know about the plans for baritone, i was mainly focusing on the fact that most of those features (eating and killing mobs with kill aura) are in impact. 
But i stand by your point either way

**Comment by SylveonBottle** [comment]
". . . Because in this case, the [bot] will enter "**Survival Mode**" - or to use the more scientific name, the "**OH FUCK SHiT FUCK NooOoo ImgonnaDie I Was sooo young.. Mode**." . . . This mode doesn't give a shit to where the [goal] is, all it's doing is trying to survive."
 -CodeBullet https://youtu.be/tjQIO1rqTBE?t=489

**Comment by jonnyawsom3** [comment]
> ". . . Because in this case, the [bot] will enter "**Survival Mode**" - or to use the more scientific name, the "**OH FUCK SHiT FUCK NooOoo ImgonnaDie I Was sooo young.. Mode**." . . . This mode doesn't give a shit to where the [goal] is, all it's doing is trying to survive."
> -CodeBullet https://youtu.be/tjQIO1rqTBE?t=489

One hell of a way to revive a dead topic, but nice reference either way

**Comment by SylveonBottle** [comment]
> One hell of a way to revive a dead topic, but nice reference either way

I actually didn't even read the suggestion, took a quick glance and thought this was a ticket about prioritising the bot's survival over the goal. I don't even know what I read to make me think that this ticket was anything about that.

**Comment by S-B99** [comment]
1. It's called autofarm and there is a pr for hunting currently in progress
2. See #295 
3. This is out of scope, baritone is meant to be for getting to a destination as fast as possible without human assistance 
4. Out of scope really
5. Also out of scope
6. It already does this, and Impact has a feature for it as well
7. That's a large point of baritone, you don't really die while going anywhere
8. See #806 
9. See #806 
10. `#cancelOnGoalInvalidation false`
11. Use macros or the baritone api in your own client
12. See #1298
13. What is this supposed to mean?
14. It doesn't.
15. Out of scope, make your own script.

**Comment by raulib** [comment]
Jokes on you my guy, c0nner is already doing this as a private fork.
