### ISSUE TITLE
Paranoia mode

### ISSUE THREAD

**Issue by mrphax0r** [cabaletta/baritone#938]
## Describe your suggestion
Paranoia Mode = Avoid any dangers at any cost.

## Context 
Baritone is currently at a masochist level when it comes to dying. this might fix this
## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
> baritone is currently at a masochist level

LOL

you have no idea. turn on allowParkour, allowParkourPlace, allowDiagonalAscend, allowDiagonalDescend, and turn blockPlacementPenalty to 1. see the shit it tries LOL

**Comment by leijurv** [comment]
the default settings are as conservative as i can conceivably make them without crippling baritone

**Comment by mrphax0r** [comment]
Thanks.

**Comment by 0-x-2-2** [comment]
nyo
