### ISSUE TITLE
Baritone + Fabric

### ISSUE THREAD

**Issue by UnknownCoding** [cabaletta/baritone#939]
## Installing Baritone with Fabric
Steps to run fabric + baritone

## How To
Go to you versions folder then locate your fabric 1.14

modify "game": [] to
"game": [
	 "--tweakClass",
     "baritone.launch.BaritoneTweaker"
	] 

then add these 4 things to your libraries

{
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
      "name": "cabaletta:baritone-api:1.4",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },

## Discord
if you need help, discord me LJM#2115

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by BlueBlazeTech** [comment]
you should add this as a pull request to the SETUP.md file it sounds helpful!

**Comment by UnknownCoding** [comment]
I realize that you also need WWE from http://wweclient.com
