### ISSUE TITLE
Tunnel for a certain number of blocks

### ISSUE THREAD

**Issue by mattbruv** [cabaletta/baritone#944]
## Describe your suggestion
The `tunnel` command should have an optional parameter to tunnel for a specific number of blocks distance.
For example, if I am at 0, 0 facing +X, and use `tunnel 1000`, Baritone should tunnel until the player reaches +1000, 0

## Settings
The new command should be `tunnel [number of blocks]`

## Context
This would improve Baritone by allowing players to set limits to how far they tunnel.
The reason I want this added is because I want to create tunnels for a certain number of distance.
Using `thisway 1000` doesn't have the same effect because it doesn't dig in a straight tunnel.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by dmoa** [comment]
100% love the idea!

**Comment by dominikaaaa** [comment]
This is now added

**Comment by mattbruv** [comment]
Thanks for implementing my suggestion!
