### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Punzaza** [cabaletta/baritone#946]
Hello,

I have been using your bot, and it is very great! I tried to build with the schematic file. But it didn't work. I put it in the schematic folder that includes the schematic file (in the baritone folder), am I right or I have to put in another folder?

Thanks

**Comment by enderman2s** [comment]
What mc version are you using baritone with, it only works with 1.12

**Comment by dmoa** [comment]
I hope someone makes build available for 1.14.4

**Comment by Hexxonite** [comment]
Litematica support is on its way for 1.14.4 apparently (llok at Pull requests) should just be a matter of days.

**Comment by mrphax0r** [comment]
Y A Y

**Comment by Tomtheduck123** [comment]
does anyone know when building schematics for 1.14.4 will happen?

**Comment by StijnSimons** [comment]
never XDDDDDDDDDDDDDDDDD

**Comment by Tomtheduck123** [comment]
No seriously

**Comment by jonnyawsom3** [comment]
Uhh... I put my schematic into a schematics folder **outside** the baritone folder and it worked fine
