### ISSUE TITLE
AFK Fishing bot

### ISSUE THREAD

**Issue by PinkmanHD** [cabaletta/baritone#947]
Would it be possible if someone can add a AFK Fishing feather

It has to do 3 things
1. Always right-click (Down-hold only)
2. Stop moving
3. And switch Rod if needed

BDW I will donate some money if you want

**Comment by usereewrjrjeejr** [comment]
Use impact auto fish

**Comment by PinkmanHD** [comment]
i cant find it for mc 1.14

**Comment by PinkmanHD** [comment]
ok found one :D
https://www.wurstclient.net/updates/wurst-7-0pre1/

**Comment by StijnSimons** [comment]
Wtf is the issue with people referencing Wurst in every suggestion?????

**Comment by PinkmanHD** [comment]
sorry bot it was the fist i found

**Comment by PinkmanHD** [comment]
which one do you sugest me for fishing

**Comment by 0-x-2-2** [comment]
📷 
📸

**Comment by PinkmanHD** [comment]
what
