### ISSUE TITLE
Making Baritone bypass various Anticheats.

### ISSUE THREAD

**Issue by mrphax0r** [cabaletta/baritone#948]
## Describe your suggestion
Suggestions for Baritone to bypass, for example, Matrix.
1. Smooth Head rotations.
2. Varying walk direction slightly
3. Instead of always jumping at the same spot, randomize it slightly.
##Settings
On/Off
## Context
Matrix currently bans Baritone.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
MATRIX IS GONE 🦀 https://github.com/cabaletta/baritone/commit/fa905b8844691e935db4cb06d0e29f10cba4f70c

**Comment by mrphax0r** [comment]
Generally speaking.

**Comment by mrphax0r** [comment]
Thanks anyway.

**Comment by 0-x-2-2** [comment]
baritone does no actions a legit player cannot do

**Comment by AdverseMiller** [comment]
> baritone does no actions a legit player cannot do

technically true, but baritone snaps the camera around and walks in a perfect line, so it can still be detected

**Comment by AlizerUncaged** [comment]
any news on this? barritone still gets detected even with free look, maybe add an option that makes barritone intentionally do mistakes

**Comment by pedro751** [comment]
i found a way to baritone do not be detected, as baritone looks and walks ina perfect line we need to make it look to random location, to make that you will need to send thi scommand from baritone to chat, i tested itr with a paid anticheat and it worked, baritone did not got detected (command: #set randomLooking 1), if you need any help email me, (my email: pn2009ct@gmail.com)
