### ISSUE TITLE
add milestone for reaching v2.0.0

### ISSUE THREAD

**Issue by BlueBlazeTech** [cabaletta/baritone#962]
the title says it all :)

**Comment by 0-x-2-2** [comment]
how do i ban someone from making issues/prs

**Comment by Aaron2550** [comment]
Develop a bot that insta closes every issue from him

**Comment by 0-x-2-2** [comment]
he is now banned 😭

**Comment by Aaron2550** [comment]
https://media.tenor.com/images/4e5cf2f7380f2923df35199d60af55ae/tenor.gif
