### ISSUE TITLE
How to install with a Forge client?

### ISSUE THREAD

**Issue by Colorized** [cabaletta/baritone#964]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Title pretty much sums it up. Can i do it with the json like the json someone posted for it to work with Optifine? If so, what is the json/what should I put in the json?

## Final checklist
- [Check!] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
you put in mods folder.
