### ISSUE TITLE
Full guide on using Baritone with several other mods?

### ISSUE THREAD

**Issue by PenguinDevs** [cabaletta/baritone#970]
I’m trying to use baritone-standalone-forge-1.2.6 with multiple other mods, but I’m not entirely sure which forge installation version I use to run it.

**Comment by Hackerokuz** [comment]
I use latest version of forge and it almost always works(If it doesn't, some mods are uncompetable with each other) for 1.2.x use 1.12.2 forge, 1.3.x use 1.13.2 and 1.4.x use 1.14.4. Hope this helps.

**Comment by ZeroMemes** [comment]
>I use latest version of forge and it almost always works(If it doesn't, some mods are uncompetable with each other) for 1.2.x use 1.12.2 forge, 1.3.x use 1.13.2 and 1.4.x use 1.14.4. Hope this helps.

Baritone only supports 1.12.2 Forge but yes generally use the latest Forge version unless otherwise stated by a given mod's maintainer. Baritone does not have a specific Forge version that should be used because it does not use any of the Forge APIs.
