### ISSUE TITLE
Automine using legitmine setting but unable to strip mine?

### ISSUE THREAD

**Issue by Hackerokuz** [cabaletta/baritone#973]
## What do you need help with?
So I saw this [video](https://youtu.be/WXjP6KEOhS0) showing baritone's strip mine feature and it is dated Oct 25, 2018 I thought that this is now a public thing but I can't figure out how to use it, my bot seems to be unable to do this and yes I did search on the internet but nothing... Noone even menses it, ever, except that one [video](https://youtu.be/WXjP6KEOhS0). So is it possible to use strip mine or not?

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZeroMemes** [comment]
It's a boolean setting that you can toggle with the chat command `#legitMine`

**Comment by Hackerokuz** [comment]
It looks like it is not working that way because when I turn it on and send it to mine for diamonds ot will search for 10 seconds or less and just stop instead of going strip mining.
