### ISSUE TITLE
Screen Jittering/Shaking with Free Look turned off

### ISSUE THREAD

**Issue by XxRapzkiexX** [cabaletta/baritone#974]
Anyone have this issue or knows how to fix it? When i turn off Free Look in Baritone settings using Impact my screen jitters.

**Comment by Mhowser** [comment]
I have it too.

**Comment by Hackerokuz** [comment]
This is because of randomlooking having high value to turn it off just set it to 0.

**Comment by XxRapzkiexX** [comment]
Thanks!

**Comment by 0-x-2-2** [comment]
> This is because of randomlooking having high value to turn it off just set it to 0.

You should not disable random looking if you are on 1.13 because you won't be able to sprint due to a bug. https://www.youtube.com/watch?v=DECKDy8gu1Y

**Comment by Mhowser** [comment]
Would a low value like 0.3 work?

**Comment by 0-x-2-2** [comment]
Yes
