### ISSUE TITLE
How do I Combine Baritone w/ Optifine?

### ISSUE THREAD

**Issue by Lilwacomintos** [cabaletta/baritone#975]
![Screenshot_13](https://user-images.githubusercontent.com/55697463/65425908-769a0280-de52-11e9-936b-a3ddb5d69c03.png)
^ Original Issue. I had little understanding but know the first 2 parts
I have come across this issue but I still yet. don't know how I can create a config file or anything.
I would appreciate some detailed information on how I can combine optifine w/ baritone.

**Comment by BlueBlazeTech** [comment]
are you using baritone standalone or with the impact client?

**Comment by Lilwacomintos** [comment]
> are you using baritone standalone or with the impact client?
Just baritone itself no further additions.

**Comment by Lilwacomintos** [comment]
> are you using baritone standalone or with the impact client?
Just Baritone itself no further additions.

**Comment by Xephorix** [comment]
you'd probably have to run it thru impact in order to get it to work w/ optifine. just a guess though
