### ISSUE TITLE
Stop jumping on my farms Baritone!

### ISSUE THREAD

**Issue by TheGameTrain** [cabaletta/baritone#976]
## Describe your suggestion
This would make it an option in the Baritone settings where it would avoid jumping on farmland. 

## Settings
None, my option itself is a setting.

## Context
Pretty obvious. Baritone keeps jumping on my farms when I do .b autofarm. I would like it to not do this.

**Comment by BlueBlazeTech** [comment]
that's actually a really good idea. I'd like to see it implemented.

**Comment by CDAGaming** [comment]
This can be closed from avoidance and blocksToAvoid settings that have been available for awhile.

**Comment by S-B99** [comment]
I thought I closed this, or this is a duplicate. Thanks

**Comment by S-B99** [comment]
Yea, #1302
