### ISSUE TITLE
Why is 1.14.4 Baritone version not showing for me?

### ISSUE THREAD

**Issue by Wolf-FX** [cabaletta/baritone#980]
## What do you need help with?
I downloaded 1.14.4 Baritone and extracted the folder and then I copied the folder into my Minecraft versions folder. When I open Minecraft and add a new version, 1.14.4 Baritone doesn't show up in the list. Please explain/help!

## Final checklist
- [✓ ] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Screenshot your versions folder and put it here

**Comment by slamcham** [comment]
i have the same problem

**Comment by slamcham** [comment]
also this is my folder 
![image](https://user-images.githubusercontent.com/50533492/65557524-b5d35c80-df01-11e9-905a-6ae73f850299.png)

**Comment by leijurv** [comment]
well your `1.14.4-Baritone` folder is clearly named the wrong thing (hint: it is not named `1.14.4-Baritone`)

**Comment by Wolf-FX** [comment]
![barritone](https://user-images.githubusercontent.com/49644461/65721762-ae828f00-e078-11e9-866d-addb2611c769.PNG)

**Comment by StijnSimons** [comment]
XDDDDDDDDDDDDDDDDDDDDDD this thread

**Comment by Wolf-FX** [comment]
> well your `1.14.4-Baritone` folder is clearly named the wrong thing (hint: it is not named `1.14.4-Baritone`)

I have it named 1.14.4-Baritone and it doesn't work. 🤔

**Comment by Wolf-FX** [comment]
> XDDDDDDDDDDDDDDDDDDDDDD this thread

Why did this issue get closed he still hasn't fixed my problem only slamcham's -_-

**Comment by Aaron2550** [comment]
Do the files inside have the same name?

**Comment by 0-x-2-2** [comment]
(hint: it is not named 1.14.4-Baritone)

**Comment by NicholasBastion** [comment]
I've got the same problem, but for 1.16.5.

**Comment by l1ving** [comment]
(hint: it is not named 1.16.5-Baritone)
