### ISSUE TITLE
Dumb AF Question

### ISSUE THREAD

**Issue by Xephorix** [cabaletta/baritone#988]
what specifically counts as a dumb AF question (not including this one, this one is extremely dumb. Please add Dumb AF tag) I don't want to just be randomly adding unnecessary things to the storage as I'd feel like im just wasting your guys' time.

edit: I'm not great at coding. So if there was anything that you could suggest anything that isnt too code-intensive I could do, that'd be great!

**Comment by Aaron2550** [comment]
Bruh u could've just asked ffs...
> I don't want to just be randomly adding unnecessary things to the storage

Didn't u just fuckn do that?

**Comment by Xephorix** [comment]
alright, then ill close it.
