### ISSUE TITLE
Logging into Minecraft with Baritone crashes Minecraft.

### ISSUE THREAD

**Issue by Divergo3** [cabaletta/baritone#990]
## Some information
Operating system: Microsoft Windows 10 Home, 10.0.17763 Build 17763
Java version: Version 8 Update 221 (build 1.8.0_221-b11)
Minecraft version: Minecraft 1.14.4
Baritone version: Baritone v1.2.9
Forge mods (if used): None

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).
(Java Virtual Machine Launcher)
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program with exit.

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
- Name 1.14.4-Baritone, "1.14.4 Baritone" in the launcher (must have already run 1.14.4) and run it.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
no crash report? cool
