### ISSUE TITLE
A Crash

### ISSUE THREAD

**Issue by jonnyawsom3** [cabaletta/baritone#991]
## Some information
Operating system: windows 10 64 bit
Java version: 1.8.0.221 64 bit
Minecraft version: 1.12.2
Baritone version: 1.2.9 (most recent)
Forge mods (if used): optifine

## Exception, error or logs

[crash-2019-09-27_02.07.40-client.txt](https://github.com/cabaletta/baritone/files/3660450/crash-2019-09-27_02.07.40-client.txt)

## How to reproduce
i had #click active and baritone walked into a block that was currently highlighted (possibly a vine as i was in a jungle biome)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Do you have allowVines enabled?

**Comment by jonnyawsom3** [comment]
yes

**Comment by 0-x-2-2** [comment]
disable it

**Comment by jonnyawsom3** [comment]
A bit late but okay...

**Comment by Xephorix** [comment]
what does that do? is there a specific reason it crashed?

**Comment by jonnyawsom3** [comment]
@Xephorix it essentially lets the bot use vines as ladders... and as for why it crashes the game, that's why i haven't closed this

**Comment by leijurv** [comment]
allowVines can cause crashes in some scenarios. never turn it on.

**Comment by jonnyawsom3** [comment]
Thanks for finally giving an explanation

**Comment by leijurv** [comment]
0x already explained to you that the crash was caused by allowVines...?

**Comment by jonnyawsom3** [comment]
No, he just said disable it. Not that it was just a normal issue with vines
