### ISSUE TITLE
Pathfinder bugs in water

### ISSUE THREAD

**Issue by Yertled** [cabaletta/baritone#993]
## Some information
Operating system: Windows 10
Java version: 1.8.0_221 64 bit
Minecraft version: 1.14.4
Baritone version: v1.4.1
Forge mods (if used): none

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Not exactly sure, but here is a video:
https://www.youtube.com/watch?v=ydj41W86Bz8

**Comment by CDAGaming** [comment]
Confirmed to still occur in up to 1.15.2, mostly probably from baritone making an early movement and it getting confused :/

**Comment by scorbett123** [comment]
Closing this in favour of #3200 as #3200 is more detailed than this.
