### ISSUE TITLE
Area Filling Command

### ISSUE THREAD

**Issue by C0mposite** [cabaletta/baritone#995]
## Describe your suggestion
i think there should b a command like click but instead of breaking blocks theres an option to fill in blocks with certain blocks or whatever is in your inventory

## Settings
chose what blocks and chose the area

## Context
I don't know how it would improve but it would add a good feature that is needed and cant be done anywhere else

## Final checklist
yes

**Comment by Orinion** [comment]
you can do that already
https://www.youtube.com/watch?v=o8HMbKAG87U

**Comment by leijurv** [comment]
This is added and will be in next release
