### ISSUE TITLE
Item Saver Mode

### ISSUE THREAD

**Issue by j13li78** [cabaletta/baritone#997]
## Describe your suggestion
If a enchanted pickaxe is almost desetroyed 1/XXXX durability, then it should stop using that pickaxe. Also it should be only applied to enchanted pickaxes.

## Settings
A simple boolean to toggle it on and off.

## Context
If you have a good enchanted pickaxe like Efficiency V and Luck III it saves them so you just need to repair them instead of enchant a new one.

## Final checklist
- [  ] I have not used any OwO's or UwU's in this issue.

**Comment by unsightedmetal6** [comment]
This is already a thing in the Impact client I believe.
